### ISSUE TITLE
Deployment failed on Heroku after upgrading to 3.0.0-beta.20.1, Locally runs completely fine

### ISSUE THREAD

**Issue by Nebras-othman** [strapi/strapi#6045]
**Describe the bug**
My app was running fine Locally and on Heroku , but I updated to the latest version 3.0.0-beta.20.1.
It still run locally fine without any issues but when I deploy to Heroku it fails.

Build succeed, Build logs : 
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >=10.0.0
       engines.npm (package.json):   >=6.0.0
       
       Resolving node version >=10.0.0...
       Downloading and installing node 14.1.0...
       Bootstrapping npm >=6.0.0 (replacing 6.14.4)...
       npm >=6.0.0 installed
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > sharp@0.24.1 install /tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.0/libvips-8.9.0-linux-x64.tar.gz
       make: Entering directory '/tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/sharp/build'
         TOUCH Release/obj.target/libvips-cpp.stamp
         CXX(target) Release/obj.target/sharp/src/common.o
         CXX(target) Release/obj.target/sharp/src/metadata.o
         CXX(target) Release/obj.target/sharp/src/stats.o
         CXX(target) Release/obj.target/sharp/src/operations.o
         CXX(target) Release/obj.target/sharp/src/pipeline.o
         CXX(target) Release/obj.target/sharp/src/sharp.o
         CXX(target) Release/obj.target/sharp/src/utilities.o
         SOLINK_MODULE(target) Release/obj.target/sharp.node
         COPY Release/sharp.node
       make: Leaving directory '/tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/sharp/build'
       
       > core-js@3.6.5 postinstall /tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/apollo-env/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js@2.6.11 postinstall /tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > @apollo/protobufjs@1.0.3 postinstall /tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/@apollo/protobufjs
       > node scripts/postinstall
       
       
       > strapi@3.0.0-beta.20.1 postinstall /tmp/build_8b9881f31bd139b7cf714383a1ca4136/node_modules/strapi
       > node lib/utils/success.js
       
       added 1530 packages from 2260 contributors and audited 27518 packages in 68.527s
       
       53 packages are looking for funding
         run `npm fund` for details
       
       found 2 vulnerabilities (1 low, 1 high)
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build
       Running build
       
       > docstream-backend-1@0.1.0 build /tmp/build_8b9881f31bd139b7cf714383a1ca4136
       > strapi build
       
       Building your admin UI with production configuration ...
       ℹ Compiling Webpack
       ✔ Webpack: Compiled successfully in 1.23m
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       audited 27518 packages in 13.021s
       
       53 packages are looking for funding
         run `npm fund` for details
       
       found 2 vulnerabilities (1 low, 1 high)
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 149.5M
-----> Launching...
       Released v17
       https://docstream.herokuapp.com/ deployed to Heroku
 
 
**Steps to reproduce the behavior**

1. Go to create stapi app with new version 3.0.0-beta.20.1
2. Deploy to Heroku
3. Visit site

**Expected behavior**
App is running

**Screenshots**
<img width="1431" alt="Screenshot 2020-05-04 at 00 52 30" src="https://user-images.githubusercontent.com/15252152/80928179-6d3b2600-8da3-11ea-827a-097c0bcb3037.png">

**Code snippets**

**System**

- Node.js version: v13.7.0
- NPM version:
- Strapi version: 6.13.7
- Database: MongoDB
- Operating system: Mac-os

**Comment by remi2j** [comment]
I'm getting the same problem with Strapi 3.0.0-beta.20

It's my first time trying to deploy this app to Heroku, so I can't tell if it's related to this Strapi version in particular. What's really annoying is that the state just goes from "starting" to "crashed" without any information.

In your case, be careful that Heroku uses Node 14 when Strapi currently only supports v12 (the current LTS version). I fixed the same problem on my end but it didn't fix it.

**Comment by remi2j** [comment]
I [found the fix in another issue](https://github.com/strapi/strapi/issues/5652#issuecomment-606525432). Hopefully this is the same for you! You should probably still set the Node version to 12.16.x though

**Comment by Nebras-othman** [comment]
@remi2j  thanks a lot this fix [ found the fix in another issue](https://github.com/strapi/strapi/issues/5652#issuecomment-606525432) did work for me
