### ISSUE TITLE
Blank Content Type fields after renaming them in Admin panel

### ISSUE THREAD

**Issue by moh3ni** [strapi/strapi#6049]
**Describe the bug**
When I update a field for an already created Content Type with entries, it is a blank new field. 

**Steps to reproduce the behavior**

I assume you already have Strapi with MongoDB Atlas installed on your local machine 
1. Go to Admin panel
2. Create a new Content Type "Article" with a "title" field
3. Go to Articles and create some article entries
4. Now go to Content Types Builder and edit "title" to "article_title"
5. Go back to Articles and you see a blank "article_title". All your entry titles are gone.

**Expected behavior**
It should update the old field names without loosing field values

**System**

- Node.js version: 12.16.1
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: MongoDB Atlas
- Operating system: Windows 10

**Comment by moh3ni** [comment]
Anyone?
I think it is the MongoDB . when I change a field name, it does not changes in MongoDB Atlas

**Comment by lauriejim** [comment]
Hello! This is related to this issue - https://github.com/strapi/strapi/issues/1114
Strapi will not replace your existing key values in each object.
So it created a new key.
You will have to create a migration key values script.
