### ISSUE TITLE
custom controller with dynamic data

### ISSUE THREAD

**Issue by shreyansh-zazz** [strapi/strapi#6057]
I am trying to create a custom controller which will be used as a webhook e.g. I will add the post link in GitHub app so that any update will be pushed to my custom controller but this payload has not defined any way we can pull this off in Strapi?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
