### ISSUE TITLE
Manage private field option for relations

### ISSUE THREAD

**Issue by ralphsomeday** [strapi/strapi#6060]
**Describe the bug**

Setting a relation manully as a private property in the content type settings json file is being reset by the Content type builder UI when changing another property of the content type

**Steps to reproduce the behavior**

1. Go to content type settings json file
2. Find a relation field and put it as a private field by adding `private: true` to the relation
3. Save & server restart
4. Go to the Content type builder change another property and save
5. Go back to the content type settings json file
6. Go to the previously modified relation and the private field is gone

**Expected behavior**

Private field in the relation should stay even if modified in the Content type builder or add a private option for relations in the content type builder UI

**Code snippets**

```json
"collaborators": {
      "plugin": "users-permissions",
      "collection": "user",
      "via": "document",
      "dominant": true,
      "private": true
    },
```

**System**

- Node.js version: v12
- Strapi version: v3.0.0-beta.20.1
- Database: Mysql 5.7
- Operating system: Mac OSX

**Comment by TylerR909** [comment]
Yeah I'm spinning up my first Strapi+CRA app right now and I'm running into a related issue.

I want people to be able to submit a Registration form for Brands. This includes Brand Names, Instagram handles, YouTube accounts, etc. I want to save that as a single "Registration" collection item so my server can convert Handles and Account Names to the actual User ID. For example, a user can change their Instagram handle, but I want to store their account by ID (not handle).

So a Registration form might look like

```
- Name
- YouTube Account
- IG Handle
- Twitter Handle
```

But the new "Brand" would be

```
- Brand Name
- YouTube ID
- Instagram ID
- Twitter ID
- Reach (Subs+Followers calculated during lookup)
- Profile Photo (From one of their accounts)
- Description (Taken off Instagram or something)
- etc
```

I want to be able to privately link a Registration to an emitted Brand. And I want to be able to reverse-lookup what the Registration details were for a Brand, so it's a 2-way 1-to-1 relationship.

I certainly don't want people to be able to query a Brand to look up their Registration details. Registration itself is easy enough to lock down by blocking find/findOne.

So yes a use case for Private Relations is high up on my list. Not a blocker yet but certainly a point of concern.

**Comment by ralphsomeday** [comment]
@TylerR909 you can set a relation as private in the settings file of the model but if you update the model via the content type builder UI then you will loose the property and you have to reset it manually so you can for now use this as a temp workaround until the strapi team can fix this.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.

It's because of the `private` option is not managed in the Content Type Builder for relations.

I think it's a good first issue. I will appreciate if you can have a look to add this option in the `advanced` tab of a field configuration.

**Comment by ralphsomeday** [comment]
@lauriejim can you indicate where this is located in the code? thank you

**Comment by lauriejim** [comment]
That's a good question, it will be in the Content Type Builder plugin - https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-type-builder

After you will have to check how `required` field is manage an see if there is exception for the relation field.

I don't know if it's manage in the front end and/or in the back end.
You will have to investigate that.

**Comment by weidox** [comment]
Wonder why priority is low, it's problematic thing in that it makes to take risky workaround (or hardcode fields in controllers), and it is really needed to work. And fixing I expect would be overly simple. Property already works, just needs handling in strapi admin like for simple fields.

**Comment by ralphsomeday** [comment]
Agreed @weidox 
I mean there is a workaround and you have to keep an eye on it if you modify the content type to always reset all those relations to private in the settings.json file but not handy at all. I did not have time to look into it, if you do have time to create a PR and submit it that would be great.

**Comment by weidox** [comment]
I'd be happy but I'm only a beginner strapi user so not having a clue where it would be in strapi code.
