### ISSUE TITLE
Strapi presents 403 server error notifications with a green exclamation mark (!)

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#6062]
**Describe the bug**
Strapi presents 403 server error notifications with a green exclamation mark (!)

**Steps to reproduce the behavior**

1. Try to update/delete/modify any records
2. When there is a 403 forbidden Server Error
3. See the Warning icon color
 
**Observed Behavior** 
The Warning icon is in  **GREEN**.

**Expected behavior**
The Warning icon should be **RED**.

**Screenshots**
![Screen Shot 2020-05-02 at 8 06 08 AM](https://user-images.githubusercontent.com/23507845/81040143-4991e180-8e70-11ea-9015-4328a481db81.png)

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.19.3
- Database: Mongo & Redis
- Operating system: MAC

**Additional context**

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
I think it's a really simple issue to fix.
Can you please investigate and submit a PR.

Can you also talk to me about your use case of Strapi, I'm interested.

**Comment by VinitSarvade** [comment]
@lauriejim I would like to take this up.

**Comment by rahul2106** [comment]
Hi, interested in fixing this issue. Please assign it to me.

**Comment by thiagoaugusto** [comment]
@vinod77 , @lauriejim , @rahul2106 
Hey guys, this issue have had already fixed on #5942
