### ISSUE TITLE
Remove port requirement from manual CLI config

### ISSUE THREAD

**Issue by RNCTX** [strapi/strapi#6065]
**Describe the bug**

Strapi requires a port input on its manual CLI config, but when the user is connecting to a local Postgres server by socket, the port should be blank.

**Steps to reproduce the behavior**

1. Create a strapi installation via the CLI manual config...
```
npx create-strapi-app --use-npm --dbclient postgres \ 
--dbhost /var/run/postgresql --dbname strapi \
--dbusername strapiuser --dbpassword xxxxxxxxxx \
strapi
```

2. Leave the port blank if using the postgres socket (host: "/var/run/postgresql", port: "")
3. See error returned from install CLI utility about "port required"

```
npx: installed 83 in 4.187s
Required database arguments are missing: dbport.
```

**Expected behavior**
Connecting via the pgsql socket does not require a port. It should allow a user to leave that option blank if they selected "--dbclient postgresql". After manually editing the config afterward to clear the port, the socket connection seems to work fine.

**System**

- Node.js version: 12.13.0
- NPM version: 6.14.4
- Strapi version: strapi@3.0.0-beta.20.1
- Database: PostgreSQL v10
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
This isn't always the case however, such as Strapi not supporting the mongo URI.

Most likely the cli until needs to be rewritten. @alexandrebodin would it better to open a general discussion issue about this so we can cover all the bases for all the databases?

**Comment by RNCTX** [comment]
Yes, auto-discovery of the socket within the runtime files folder is a postgres convention, afaik. Some conditional checking of the user's database type is in order to determine the other requirements.

The obvious hangup for this (and the one I was working on when reporting the bug) is writing an ansible script to deploy strapi. Along those lines, the docs do not mention a CLI way of generating the admin account.  Is that possible outside of the web UI?

**Comment by derrickmehaffy** [comment]
> Yes, auto-discovery of the socket within the runtime files folder is a postgres convention. Some conditional checking of the user's database type is in order to determine the other requirements.
> 
> The obvious hangup for this (and the one I was working on when reporting the bug) is writing an ansible script to deploy strapi. Along those lines, the docs do not mention a CLI way of generating the admin account + password. Is that possible outside of the web UI?

Sure you could just fire a curl post request, if you create a new application, open the AdminUI, open the dev tools and watch the network tab you can see what the POST request is sending and simply create a curl command to do the same thing.

**Comment by derrickmehaffy** [comment]
I'm going to mark this issue as closed @RNCTX unless you think this needs to remain open for some reason. Please let me know if you think it should be reopened.
