### ISSUE TITLE
[Question] Can I extend other plugins using my own plugin?

### ISSUE THREAD

**Issue by periabyte** [strapi/strapi#6066]
**Describe the topic**
I'm currently creating a strapi plugin for our company, as we intend to use strapi as our main Headless CMS. I would like to implement our business logic using the plugin but the logic needs to extend (like what we'll do in `extensions` folder) the user-permissions plugin, is it possible?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
