### ISSUE TITLE
Account registration confirmation bypass security issue

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#6069]
**Describe the bug**
There are no checks for the payload that goes into `/auth/local/register`, which means an attacker can simply bypass email confirmation by setting `confirmed: true` in the payload.

**Steps to reproduce the behavior**

1. Enable email confirmation in `Roles & Permissions` -> `Advanced Settings` -> `Enable email confirmation`
2. Create a new user through the `/auth/local/register` endpoint with the following payload:
```json
{
	"email": "abc@example.com",
	"password": "abc123",
	"username": "abc"
}
```
This user will not be confirmed.
3. Now do the same thing, but with this payload:
```json
{
	"email": "abc2@example.com",
	"password": "abc123",
	"username": "abc2",
	"confirmed": true
}
```
4. This user will receive a confirmation email anyway, but the account will already be confirmed.

**Expected behavior**
No additional information should be able to go into the registration endpoint. Only `email`, `password` and `username`, especially if it's not made from an administrator account.

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/81057131-bf736880-8ec3-11ea-9f3b-8083d2874b13.png)

**Code snippets**
I'll be submitting a PR that should fix this issue.

**System**

- Node.js version: `v13.6.0`
- NPM version: `v6.13.6`
- Strapi version: `3.0.0-beta.20.1`
- Database: `Mongo DB`
- Operating system: `Windows 10 1909 (WSL Ubuntu 18.04)`

**Additional context**
There is also no check for username and password restrictions. Any non-empty value is valid.

**Comment by alexandrebodin** [comment]
Deleting the issue to avod leaking
