### ISSUE TITLE
restarting crash

### ISSUE THREAD

**Issue by akwatra** [strapi/strapi#607]
**Node.js version**:
8.4.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.9.1
**Operating system**:
linuxmint | ubuntu 16.04

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by akwatra** [comment]
Auto restarting and manual restarting also failed sometimes with message taking long time.

INFO (7493 on mera-laptop): File changed: /www/htdocs/noder/strapi/plugins/users-permissions/services/Jwt.js
INFO (7483 on mera-laptop): The server is restarting

WARN (7578 on mera-laptop): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (7578 on mera-laptop): Perhaps you forgot to call it?
INFO (7578 on mera-laptop): Server started in /www/htdocs/noder/strapi
INFO (7578 on mera-laptop): Your server is running at http://localhost:1337
DEBUG (7578 on mera-laptop): Time: Wed Feb 07 2018 22:54:18 GMT+0530 (IST)
DEBUG (7578 on mera-laptop): Launched in: 11129 ms
DEBUG (7578 on mera-laptop): Environment: development
DEBUG (7578 on mera-laptop): Process PID: 7578
DEBUG (7578 on mera-laptop): Version: 3.0.0-alpha.9.1 (node v8.4.0)
INFO (7578 on mera-laptop): To shut down your server, press <CTRL> + C at any ti

--

INFO (7069 on mera-laptop): The server is restarting

DEBUG (7439 on mera-laptop): Server wasn't able to start properly.
ERROR (7439 on mera-laptop): (hook:mongoose) takes too long to load

how to resole this?

**Comment by lauriejim** [comment]
Hi @akwatra, please follow this issue https://github.com/strapi/strapi/issues/616 please.
