### ISSUE TITLE
Failed to start: too many connections for role XY

### ISSUE THREAD

**Issue by ondrej-janosik** [strapi/strapi#6070]
**Describe the bug**
The server wasn't able to start properly.
[2020-05-05T10:52:25.648Z] error error: too many connections for role

**Steps to reproduce the behaviour**

1. Create a new app
2. Update `database.json` -> connect to DB in cloud (HEROKU/elephantsql)
3. `npm run develop`
4. see an error

[2020-05-05T10:52:25.645Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-05T10:52:25.648Z] error error: too many connections for role "nftqiwzy"

I check the DB and there is no active connection,

**Expected behaviour**
App starts

**Screenshots**
![image](https://user-images.githubusercontent.com/18070427/81059083-0e26ff80-8ed0-11ea-8832-5bf1f163f8f8.png)

**System**

- Node.js version: `12.13.0`
- NPM version: `6.12.0`
- Strapi version: `3.0.0-beta.20.1`
- Database: `postgres`
- Operating system: `windows 10`

**Comment by ondrej-janosik** [comment]
My package.json
`{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "^7.18.2",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.20.1",
    "strapi-admin": "3.0.0-beta.20.1",
    "strapi-connector-bookshelf": "3.0.0-beta.20.1",
    "strapi-plugin-content-manager": "3.0.0-beta.20.1",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.1",
    "strapi-plugin-email": "3.0.0-beta.20.1",
    "strapi-plugin-upload": "3.0.0-beta.20.1",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.1",
    "strapi-utils": "3.0.0-beta.20.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "f4266e9a-70c6-4af0-b7a7-18d956f11146"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
`

**Comment by ondrej-janosik** [comment]
Resolved in newer version.

**Comment by tiberiumihai** [comment]
@ondrej-janosik  In what version? I'm using beta-20.3 and I'm encountering the same issue in heroku with postgres addon.

**Comment by tiberiumihai** [comment]
My bad. I've forgot pool.max connections in database.json grater than 20. Heroku free postgres allows 20 connections max.

**Comment by jacobdo2** [comment]
> My bad. I've forgot pool.max connections in database.json grater than 20. Heroku free postgres allows 20 connections max.

This is a gotcha for Heroku users, putting the pool over 20 causes an error.
