### ISSUE TITLE
Filter "is" doesn't work on dates

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#6074]
**Describe the bug**
Applied filter `created_at` doesn't work at all. I can select any date, my article is still there as a result. See screenshot:
![Screenshot from 2020-05-05 16-48-48](https://user-images.githubusercontent.com/45003352/81080016-91f0e400-8ef0-11ea-8d61-1baf0120fc9f.png)

On the other way applying multiple filters with at least one date filter (set with the correct date) shows NO results. See screenshot: 
![Screenshot from 2020-05-05 16-49-19](https://user-images.githubusercontent.com/45003352/81080324-e7c58c00-8ef0-11ea-92da-bfdc4ca6ea50.png)

 
**Steps to reproduce the behavior**

1. Build a content type (name: `article`) with Text, Rich text, Relation (with User - User has many Articles)
2. Go to collection types `Articles`
3. Apply filter: `id` `is` `1`
4. Apply filter: `created_at` `is` `the actual date of creation`

**Expected behavior**
Show the article

**Screenshots**
See above

**System**
- Node.js version: v10.15.0
- NPM version: 6.13.1
- Strapi version: v3.0.0-beta.20.2
- Database: sqlite
- Operating system: Ubuntu 18.04

**Comment by marudhupandiyang** [comment]
Hello, When you say `applied filter` `created_at`, from the UI you have shown, the filter does not seem to have been applied, because when a filter is applied you would get a `blue box` showing what is filtered right next to the `Filters` button. 
What happens when you click on `Apply` button after selecting the Apply button. Are there any errors in console ??

**Comment by baermathias** [comment]
You are right, the filter wasn't applied, my fault. 
But if I add a new article (with the date of today) and then apply the `created_at` filter also with today, the result is empty. Its the same as in the combined case with id & created_at

**Comment by marudhupandiyang** [comment]
Select the right operator. This should be mostly considered as an enhancement by the strapi team. When you select a date option, the backed receives both the date and time. But the UI just shows a date. 
If you select > or < as operator and choose appropriate date, the results would be perfect. The eq operator looks for both date and time and it fails. 

Let someone from strapi address this and see what can be done, either change the UX or something elsee.

**Comment by lauriejim** [comment]
Thank you for reporting this issue.

**Comment by shtelzerartem** [comment]
@lauriejim @baermathias 
Found where you can fix filter to remove time from query. ```components/FilterPicker/reducer.js``` there is a string checking if the updated value is a moment object and returns ```object.toISOString()``` that is obviously contains time. Replaced with object.format('yyyy-MM-DD'). The output is perfect, but I think in the backend it strictly compares if input timestamp equal to any in the db.

This requires core fixes too.

**Comment by StipJey** [comment]
This problem is still relevant to me. Are you planning to fix it?

**Comment by fveracoechea** [comment]
Is there any progress on this issue?

**Comment by derrickmehaffy** [comment]
> Is there any progress on this issue?

Most likely this will be resolved in our v4 that we are working on

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
