### ISSUE TITLE
Get data from 3rd party API into Strapi

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#6076]
I would like to populate some of my fields with data fetched from a 3rd party API. So f.ex. I would have a field called `api_id`, and that `id` would be part of the call. Then, with the response, I would populate several fields. Finally, I would update this data periodically (f.ex, every week)

If anyone can point me a direction where to start, I would be grateful.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
