### ISSUE TITLE
users-permissions/permissions endpoint is pointless

### ISSUE THREAD

**Issue by abanchev** [strapi/strapi#6077]
The current permissions endpoint is a bit pointless, it returns the names of all the permissions, however not the state (enabled or not) for the current role.
If we want to have the appropriate permissions we need to have the "getRole" permission, however that also returns users in the role, as well as rights for other roles.

i think  getPermissions(ctx) in UsersPermissions.js should check the current context and return the permissions for the requesting user.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
