### ISSUE TITLE
JWT token expiration and refresh

### ISSUE THREAD

**Issue by akwatra** [strapi/strapi#608]
**Node.js version**:
8.4.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.9.1
**Operating system**:
linuxmint | ubuntu 16.04
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by akwatra** [comment]
Hi, 

I created jwt token with user /auth/local and then pass the token in header Authorisation bearer, it works.

But i wanted to limit the token expiration with couple of hours, While testing i tried to set the two minutes
const defaultJwtOptions = { expiresIn: 120 }; in Jwt.js  but that did not work 

means able to access the data even after expiration minutes with pollicy: isAuthenticate endpoint 

how can i limit to expiration and other jwt refresh methods on demand,

**Comment by lauriejim** [comment]
Hello @akwatra .
Can you try with https://github.com/zeit/ms format. '2m' for 2 minutes and tell me if it works.
It works fine on my computer with number and string format.

**Comment by akwatra** [comment]
I tried earlier with numeric value 120 it worked then,
