### ISSUE TITLE
database names should be singular

### ISSUE THREAD

**Issue by baumannalexj** [strapi/strapi#6081]
We found strapi for a work project, and we love the idea! Our data flow has strict naming conventions: We believe table names should be singular as the correspond to a single row entity. 

Strapi should allow table names to be singular.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
