### ISSUE TITLE
Media association after migration to version 3.0.0-beta.20.2

### ISSUE THREAD

**Issue by PhantomxJoker** [strapi/strapi#6082]
Hello!

Excuse my english, is not my mother language

I was using the alpha26.2 version of Strapi and I had a lot of content types with associated media that was stored in AWS by the Upload's plugin configuration. Now, all that content types does not show the associated media and I have to replace all medias (I really do not know it this is a normal behaviour, maybe I forgot something on my migration).

You can get the error doing this

1. Create a content type in alpha version and associate a media file (a JPG image, for example) after create some items for that content type
2. Persist the data into a Mongoose database and configure de Upload plugin for store the images into aws
3. Update to 3.0.0-beta.20.2
4. See the created item and scroll to the media field (the image is not available)

I guess that at this point, I should have the same associated media.

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.20.2
- Database: Mongoose
- Operating system: Elementary OS

**Comment by derrickmehaffy** [comment]
Did you follow all the migration guides? The jump from alpha to beta is not an easy one

**Comment by PhantomxJoker** [comment]
@derrickmehaffy Yes I did, in fact I changed the mongoose hook and the bucklet for upload plugin. But in the migration guides I didn't find nothing related to my issue :(

**Comment by PhantomxJoker** [comment]
I was searching by a difference between alpha's database and the current. The first one make a relation from the upload_file item to the content type item (in my case, from upload_file to _producto_). With the beta version, the relation is now from content type item to upload_file (_producto_ to upload_file item). Can I change that relation?

**Comment by PhantomxJoker** [comment]
Yep, the https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html url works for me.

Im sorry, I will close this
