### ISSUE TITLE
Documentation plugin doesn't reference auto generated attribute for responses

### ISSUE THREAD

**Issue by kueronya** [strapi/strapi#6088]
**Describe the bug**
The documentation plugin doesn't reference already created schemas for 200 responses, although the documentation suggests something like this (at least for plugins). Instead a foo object is described as response model for all 200 responses.

> If the model is unknown it generates a response like the following { foo: "string" } that you can easily override later.

Actually the schemas are generated, although without created_at/updated_at fields but not referenced on 200 responses

This makes generating client code from API documentation less useful since type safety and autocomplete is lost for responses.

**Steps to reproduce the behavior**

1. Create a collection type
2. Generate documentation
3. Check tree paths/_mycollection_/get/responses/200/content of file /extensions/documentation/1.0.0/full_documentation.json 

**Expected behavior**
The plugin should auto-generate response schemas including default fields (created_at, modified_at) excluding private set fields and reference them for all appropriate responses.

**System**

- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version:  v3.0.0-beta.20.1
- Database: Mysql 5.6
- Operating system: Win10

**Comment by RaikBitters** [comment]
As I understand it, there is a problem with the collection name. When I create a collection named "foo" I have no problem, when I create a collection like "foo-bar" I see "{foo: "string"}" in the model response.

**Comment by emilieringwald** [comment]
Hello @kueronya! We indeed need to work on the documentation plugin, we'll have a look in the coming weeks and keep you posted.
