### ISSUE TITLE
Authentication providers broken on Windows

### ISSUE THREAD

**Issue by AnthonyPhan** [strapi/strapi#6089]
**Describe the bug**
When using Strapi 3.0.0--beta.20 or newer, third party authentication providers no longer work. Strapi reports back that the provider is disabled even if it has been enabled in the administration panel. 

**Steps to reproduce the behavior**

1. Update your global strapi version to beta20 or newer
2. Create a new strapi project using "strapi new myProject"
3. Create a new administrator and login
4. Navigate to the "Roles & Permissions" section
5. Navigate to the providers tab and enable one of the authentication providers and fill out the relevant fields. 
6. Now navigate to "http://localhost:1337/connect/microsoft"
7. you will be notified that the authentication provider is not enabled, even though it was enabled in step 5

**Expected behavior**
when navigating to "http://localhost:1337/connect/microsoft" you should be redirected to the authentication providers login page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12785492/81165404-7fe07580-8fc4-11ea-94f6-cf1f69037f75.png)

**System**

- Node.js version: 12.6.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.20.2
- Database: SQLLite
- Operating system: Windows 10

**Additional context**
I have authentication providers working without issues before 3.0.0-beta.20. Currently unable to upgrade, as users will be unable to login.

**Comment by bamne123** [comment]
Any breakthrough ?

**Comment by bamne123** [comment]
Found Solution ...

For windows, it is checking `\\` but the requestPath has value `/connect/google`.
Platform check is not needed.

File Path: `strapi-pluging-users-permissions\controllers\Auth.js`
Line Number: `258`

```
const provider =
      process.platform === 'win32' ? requestPath.split('\\')[2] : requestPath.split('/')[2];
```

**Comment by HonzaVrkota** [comment]
> Found Solution ...
> 
> For windows, it is checking `\\` but the requestPath has value `/connect/google`.
> Platform check is not needed.
> 
> File Path: `strapi-pluging-users-permissions\controllers\Auth.js`
> Line Number: `258`
> 
> ```
> const provider =
>       process.platform === 'win32' ? requestPath.split('\\')[2] : requestPath.split('/')[2];
> ```

Whats the solution? 
`const provider =  requestPath.split('/')[2];` ?

**Comment by HonzaVrkota** [comment]
Solution is:

1. Replace line 258
- File path: node_modules/strapi-pluging-users-permissions\controllers\Auth.js
- This code replace `const provider =
      process.platform === 'win32' ? requestPath.split('\\')[2] : requestPath.split('/')[2];`
- New code: `const provider = requestPath.split('/')[2];`

2. Restart strapi

**Comment by lauriejim** [comment]
Hello! Can you please submit a PR to fix that, thank you.

**Comment by alexdevmotion** [comment]
I created [this PR](https://github.com/strapi/strapi/pull/6551) to fix the issue.

**Comment by lauriejim** [comment]
Hello, someone can check if this work with the latest version of the stable please.
Thank you.

**Comment by HonzaVrkota** [comment]
> Hello, someone can check if this work with the latest version of the stable please.
> Thank you.

Hello, 
it still does not work on Windows. Same error "This provider is disable" 
- Windows 10
- Strapi v3.0.1

**Comment by Jamilur-rahman-470** [comment]
I am still encountering this issue after following the fix. 
windows: 10
Strapi: 3.0.1

**Comment by petersg83** [comment]
Fixed by https://github.com/strapi/strapi/pull/6546
