### ISSUE TITLE
Admin interface - select format in editing component

### ISSUE THREAD

**Issue by ronny35** [strapi/strapi#6091]
Currently, when I edit a content with a component and this component has a relation field, the display of select has not a appropriate format (too small in my case).
Is it possible to have responsible display ?

![image](https://user-images.githubusercontent.com/15168987/81171477-bc987680-8f9c-11ea-9bbd-f13237d8fe20.png)

- Strapi version: Strapi v3.0.0-beta.18.7

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
