### ISSUE TITLE
Admin interface - editing view

### ISSUE THREAD

**Issue by ronny35** [strapi/strapi#6092]
Currently, during view configuration, it is not possible to select one specific field from one single component (no repeatable).

- Strapi version: Strapi v3.0.0-beta.18.7

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
