### ISSUE TITLE
Handle singular and plural word collision in content type naming for GraphQL schema exports

### ISSUE THREAD

**Issue by jwerle** [strapi/strapi#6093]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Handle "uncountable" words in content type naming so singular and plural forms do not collide.

**Your suggestions for this topic**
Check for the collision of a singular word and a plural word and append an `s` (or something) to the plural form of the word.

An example would be the word `audio` becoming `audios` where naturally both the singular and plural form of the word `audio` is `audio`

**Additional context**
related: https://github.com/strapi/strapi/issues/3471#issuecomment-624733875

**Comment by jwerle** [comment]
Maybe something like:

```js
if (singularName === pluralName) {
  pluralName += 's'
}
```

here: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/type-definitions.js#L337

**Comment by jwerle** [comment]
perhaps it could be possible in the model settings to override the singular and plural forms of a model too

**Comment by jwerle** [comment]
A work around, if anyone lands on this issue, is to name an uncountable/irregular word in a forced plural form like `audios` which creates the odd `Audios` type

**Comment by lauriejim** [comment]
Hello! Can you please check this issue.
https://github.com/strapi/strapi/issues/1198

**Comment by lauriejim** [comment]
And thank you for this workaround

**Comment by jwerle** [comment]
@lauriejim thanks for the response! Hopefully something like https://github.com/blakeembrey/pluralize/pull/150 gets merged in so downstream could modify the state of that module to help here (like remove an uncountable word for edge cases like `audio` or `series`)

btw.. Looking forward to strapi@3 !
