### ISSUE TITLE
Hope webhook has data before modification

### ISSUE THREAD

**Issue by crazyair** [strapi/strapi#6096]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Hope webhook has data before modification. To know what's changed.

webhook update demo image.
![image](https://user-images.githubusercontent.com/7971419/81489481-79921800-92a8-11ea-8b97-b69e24105c36.png)
I want to old entry data.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by crazyair** [comment]
@derrickmehaffy you see see?

**Comment by lauriejim** [comment]
Hello! Can you please precise your message because I don't understand you you mean.

**Comment by crazyair** [comment]
I want to 



```json
{
    "event":"event.update",
    "entry":{
        "name":"new some"
    },
    "old_entry":{
        "name":"old some"
    }
}
```
We can know what has been changed through comparison

**Comment by lauriejim** [comment]
I'm not sure it is how WebHook are supposed to work 🤔
Ping @Aurelsicoko and @alexandrebodin about this.

**Comment by alexandrebodin** [comment]
Hello, This is not something we will be adding to the default webhooks, mainly to avoid performance issue of loading / send too much data.

You can easily create a custom webhook using the lifecycles hooks and call your API.

You can check the lifecycle docs here: https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

I'm closing this issue. Feel free to discuss it if you need more information

**Comment by crazyair** [comment]
How to use
