### ISSUE TITLE
[Admin] Conflict in Font Awesome versions

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#6098]
I noticed that both version 4.7.0 and 5.11 are required in `strapi-admin` package.json:

https://github.com/strapi/strapi/blob/022b22827900eec11ce87fa2e802e141b3bc0e41/packages/strapi-admin/package.json#L49

https://github.com/strapi/strapi/blob/022b22827900eec11ce87fa2e802e141b3bc0e41/packages/strapi-admin/package.json#L31
https://github.com/strapi/strapi/blob/022b22827900eec11ce87fa2e802e141b3bc0e41/packages/strapi-admin/package.json#L33
https://github.com/strapi/strapi/blob/022b22827900eec11ce87fa2e802e141b3bc0e41/packages/strapi-admin/package.json#L34

This is useless (I tried locally to remove the use of font awesome 4.7 and did not notice any issue without it).

The only use that's made of it is here: 
https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/app.js#L22

I think `font-awesome` dep should be removed from package.json (Also note that this package has not been updated for the last 4 years - https://www.npmjs.com/package/font-awesome)

Is there another reason why both these versions are bundled ? Or would you accept a PR to remove the oldest one ?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
