### ISSUE TITLE
Yarn is required in order to install plugins

### ISSUE THREAD

**Issue by pawelangelow** [strapi/strapi#6100]
**Describe the bug**
I've tried to install the GraphQL plugin on a strapi repo configured by some of the tutorials. Here is a [link to it](https://github.com/pawelangelow/strapi-playground). If you start the instance and navigate to the Admin Dashboard, try to install let's say GraphQL plugin. An error is shown
<img width="594" alt="Screenshot 2020-05-07 at 12 13 53" src="https://user-images.githubusercontent.com/6314481/81276947-61c65400-905c-11ea-9cbd-c9a6f675f901.png">
After checking the log and reproduced the step manually got this error:
```
strapi "install" "graphql"

spawn yarn ENOENT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 strapi: `strapi "install" "graphql"`
npm ERR! Exit status 1
```

**Everything was OK** when I've installed `yarn`, but there wasn't any information in the tutorials or documentation about that. Not sure if this is a bug or I should open PR for the documentation.

**Steps to reproduce the behavior**

1. Go to the Admin Dashboard
2. Click on Marketplace (on the left menu)
3. Click on the install icon of GraphQL plugin

**Expected behavior**
GraphQL plugin to be installed successfully.

**System**

- Node.js version: v12.16.2
- NPM version: v6.14.4
- Strapi version: 3.0.0-beta.20
- Operating system: Ubuntu 18.04.3 LTS

**Comment by marudhupandiyang** [comment]
can you point to those tutorials /documentation ur mentioning ?

**Comment by pawelangelow** [comment]
Sure. I believe this is the tutorial: https://strapi.io/documentation/3.0.0-beta.x/deployment/amazon-aws.html

https://strapi.io/documentation/3.0.0-beta.x/deployment/azure.html here it says that `yarn` is optional, but haven't tried if `strapi install graphql` will trigger `yarn`

The other guides from https://strapi.io/documentation/3.0.0-beta.x/getting-started/deployment.html#hosting-provider-guides don't provide information about `yarn` as well.

It's not critical or anything like that, but it might improve the process for newcomers.

**Comment by lauriejim** [comment]
Hello! According to the code base - https://github.com/strapi/strapi/blob/8281ed7a8fd3f35af9106b846b41d3404c9208d5/packages/strapi/lib/commands/install.js#L18-L19

Can you make sure you have or not a `yarn.lock` in your project.
This file has been generated if, when you created the project, your machine has yarn installed.

**Comment by pawelangelow** [comment]
Hey @lauriejim. I DO have `yarn.lock` in the project. We can close this issue 😃 🎉 🙌 Thank you!

I'm just wondering if additional information should be provided somewhere in the deploying guides. The error log gives enough information, but someone may need more time to solve this.

**Comment by JadenSWang** [comment]
Somehow I feel like using yarn should not be dependent on this one file existing...
