### ISSUE TITLE
Display alternative HOST settings in google app engine deployment document

### ISSUE THREAD

**Issue by FamilyMan** [strapi/strapi#6106]
**Describe the bug**
There is an issue with the documentation for deploying Strapi on Google App Engine.

**Steps to reproduce the behavior**

1. Go to 'https://strapi.io/documentation/3.0.0-beta.x/deployment/google-app-engine.html'
2. Scroll down to 'Create app.yaml and .gcloudignore'
3. There is an error with the code displayed

**Expected behavior**
HOST should display HOST: '0.0.0.0' or maybe, if you run into an error using HOST: '<project_id>.appspot.com' then try HOST: '0.0.0.0'

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: postgres
- Operating system: windows 10

**Comment by derrickmehaffy** [comment]
@FamilyMan that spot is not for domains, that is the literal binding of Strapi to the interface of the system it's running on, in which the domain provided by not actually map to that interface on the system (especially in the cloud) where it's likely the host is actually being proxied through multiple levels.

In this case providing `0.0.0.0` just means to "Bind to all outside interfaces" If you need proxy support, there is a spot for that. https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#server

Although this proxy system will be changed in the next major version, the same logic still applies. Setting a domain as the host is not going to work **most** of the time. Previously before beta.19.4 this host variable didn't really do much as Strapi was bound to all interfaces by default anyway, but beyond beta.19.4 it is a literal binding.

**Comment by derrickmehaffy** [comment]
Marking this as closed as it was fixed in the above PR
