### ISSUE TITLE
Cannot discern instruction in google app engine deployment documentation

### ISSUE THREAD

**Issue by FamilyMan** [strapi/strapi#6107]
**Describe the bug**
Cannot discern what instruction is referring to.

**Steps to reproduce the behavior**

1. Go to 'https://strapi.io/documentation/3.0.0-beta.x/deployment/google-app-engine.html'
2. Scroll down to 'File uploading to Google Cloud Storage'
3. Cannot discern where settings are found.

**Expected behavior**
After 'Save the JSON credentials file.', there is a line displaying 'Plugins > File Upload > Settings > Production tab'. I cannot find what this is referring to. Can there please be more detail added to this step.

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: postgres
- Operating system: windows 10

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this.
Since the Medial Lib has been published, upload configurations changed.
You will have to use this documentation to configure your provider.
https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider

**Comment by derrickmehaffy** [comment]
This will be fixed when I rewrite the Deployment guides for stable release.

**Comment by derrickmehaffy** [comment]
Fixed in: https://github.com/strapi/strapi/pull/6275
