### ISSUE TITLE
Gprahql controllers and policies called only for top level objects

### ISSUE THREAD

**Issue by abanchev** [strapi/strapi#6108]
**Describe the bug**

I have three collections A, B, and C.
When i request nested data using graphql the **controller functions do not get called** for each sub object in the path that we request.
**Neither do the policies or resolvers** for B and C if the root object is A.
And what is more the controller for A may see and modify some of the fields for B, however they get populated at a later time again. And the A controller never sees the data in C.

**Steps to reproduce the behavior**
Check the example repo

**Expected behavior**
To be able to inspect/modify the data using the controllers that are setup for the different collections

**Code snippets**
Here is a repo that illustrates the problem
https://github.com/abanchev/strapi-issues-test

**System**

- Node.js version: 12
- NPM version: 6.14.4
- Strapi version: v3.0.0-beta.20.3
- Database: mysql
- Operating system: linux

**Additional context**
The issue was discussed here:
https://github.com/strapi/strapi/discussions/5875

**Comment by lauriejim** [comment]
Ping @alexandrebodin about that.
What we plan to do about this topic.
It's not related only to GraphQL, also for REST API when we populate data.
