### ISSUE TITLE
Global policies don't work if you use them like mentioned in the docs

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#6111]
**Describe the bug**
Using global policies like in this example (https://strapi.io/documentation/3.0.0-beta.x/concepts/policies.html#usage) doesn't work:
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/restaurants",
      "handler": "Restaurant.find",
      "config": {
        "policies": ["global::isAuthenticated"]
      }
    }
  ]
}
```

It gives an error:
`error Error creating endpoint get /restaurants: Could not find policy "global::isAuthenticated"`

THE SOLUTION
This is what works for me: `"policies": ["isAuthenticated"]`
Do the docs have to be updated?

**Steps to reproduce the behavior**
See steps here https://strapi.io/documentation/3.0.0-beta.x/concepts/policies.html#usage

**System**

-  Node.js version: v10.15.0
-  NPM version: 6.13.1
-  Strapi version: v3.0.0-beta.20.2
-  Database: sqlite
-  Operating system: Ubuntu 18.04

**Comment by abanchev** [comment]
Where did you place the policy file? If you place it in api/restaurants/config/policies you have to reference it directly "isAuthenticades"
if you place it in the root /config/policies, then you have to use "global::isAuthenticated"

**Comment by derrickmehaffy** [comment]
That specific policy comes from users-permissions, the docs are correct @baermathias thus I'm marking this issue as closed.

**Comment by luixal** [comment]
I'm reopening this as totally crazy.

Docs say global policies should be use this way:

```js
"policies": [
          "global.isAuthenticated"
        ]
```

Didn't work for me. Using ```"global::isAuthenticated"``` like this issues said, works.

¿?

**Comment by MattieBelt** [comment]
Hey @luixal, it indeed should be with double `:`, can you share the docs that mention a dot notation?

**Comment by luixal** [comment]
My bad @MattieBelt , one of the best positioned result for my google seach "strapi global policies" was sending me to a "gitee" domain with old docs.

I can confirm current docs use the ":" notation. I can also confirm I need yo pay attention to the "old docs" message at the top xD
