### ISSUE TITLE
AWS S3 option not showing in admin panel

### ISSUE THREAD

**Issue by realabbas** [strapi/strapi#6119]
**Describe the bug**
I have setup the whole strapi project on AWS EC2. Then I installed the strapi-provider-upload-aws-s3@beta. Now to configure access and secret keys in the admin panel, I am not able to add any credentials under the file upload tab. Its just showing LOCAL SERVER.

**Expected behavior**
I should be able to add  AWS S3 credentials under the file upload tab 

**Screenshots**

Development Stage

![image](https://user-images.githubusercontent.com/43527087/81372992-5422d400-9119-11ea-9db7-2cfa66dbbb3a.png)

Production Stage

![image](https://user-images.githubusercontent.com/43527087/81373410-59345300-911a-11ea-8917-eb590fe45cf5.png)

**System**

- Node.js version: v10.20.1
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.19.5
- Database: Postgres ^8.0.2
- Operating system: Ubuntu Server 18.04 LTS (HVM)

**Additional context**

**Comment by derrickmehaffy** [comment]
Please see the migration guide, upload provider settings have been moved to files: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings
