### ISSUE TITLE
Dead link in documentation (concepts/parameters)

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#6121]
**On this page:** 
https://strapi.io/documentation/3.0.0-beta.x/content-api/parameters.html#available-operators

**The link inside the following line:**
 See the [parameters](https://strapi.io/documentation/3.0.0-beta.x/concepts/parameters.html)' concepts for details.

**Responses with a 404**

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/pull/5893
