### ISSUE TITLE
Media field does not display validation errors

### ISSUE THREAD

**Issue by ykorovko** [strapi/strapi#6123]
**Describe the bug**
Validation errors are not displayed for a media fields, so it is unclear for users what is wrong.

**Steps to reproduce the behavior**

1. Create a new collection type with media field required
2. Go to creation a new collection type
3. Click on `Save` button
4. See Media field

**Expected behavior**
Validation errors are displayed for media fields

**Screenshots**

<img width="1411" alt="Screenshot 2020-05-08 at 14 57 58" src="https://user-images.githubusercontent.com/53710324/81403573-63674900-913c-11ea-88ad-633dffa2990c.png">

<img width="1304" alt="Screenshot 2020-05-08 at 13 44 45" src="https://user-images.githubusercontent.com/53710324/81402176-94924a00-9139-11ea-9336-249693aeddec.png">

<img width="1406" alt="Screenshot 2020-05-08 at 15 20 21" src="https://user-images.githubusercontent.com/53710324/81405001-7deef180-913f-11ea-9b8b-17231dd0436a.png">

<img width="1398" alt="Screenshot 2020-05-08 at 14 55 13" src="https://user-images.githubusercontent.com/53710324/81403408-023f7580-913c-11ea-81ed-e89919630539.png">

**System**

- Node.js version: v12.16.0
- NPM version: v6.14.4
- Strapi version: v3.0.0-beta.20.1
- Database: mongo
- Operating system: macOS

**Additional context**
Dependencies list: 

```
"dependencies": {
    "axios": "0.19.0",
    "ckeditor4-react": "^1.1.0",
    "lodash": "^4.17.5",
    "strapi": "3.0.0-beta.20.1",
    "strapi-admin": "3.0.0-beta.20.1",
    "strapi-connector-mongoose": "3.0.0-beta.20.1",
    "strapi-plugin-content-manager": "3.0.0-beta.20.1",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.1",
    "strapi-plugin-email": "3.0.0-beta.20.1",
    "strapi-plugin-graphql": "^3.0.0-beta.20.1",
    "strapi-plugin-upload": "3.0.0-beta.20.1",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.1",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.20.1",
    "strapi-utils": "3.0.0-beta.20.1"
  }``,`

**Comment by lauriejim** [comment]
I can confirm this issue.
Thank you for reporting this issue.
I ping @soupette about this.
