### ISSUE TITLE
Impossible to disable tutorials button in Admin UI since RC.0

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#6127]
**Describe the bug**
Can't disable tutorials in Admin UI.

**Steps to reproduce the behavior**

1. Create file under /admin/src/config.js:

```
export const SHOW_TUTORIALS = false;
```

2. Delete `build` directory
3. Restart "develop" task, so admin UI rebuilds
4. Open Admin UI http://localhost:1337/admin

**Expected behavior**
Tutorials button should disappear.

**Screenshots**
I get a blank window and the following errors in a console:
![image](https://user-images.githubusercontent.com/5739191/81412206-57dc4800-9165-11ea-9eaf-f51732c530e3.png)

**System**

- Node.js version: v12.10.0
- NPM version: 6.14.5
- Strapi version: 3.0.0-RC.0
- Database: MySQL
- Operating system: Catalina 10.15.4

**Additional context**
It does work in v3.0.0-beta.20.3

**Comment by derrickmehaffy** [comment]
@soupette

**Comment by soupette** [comment]
@webcoderkz [here's the documentation](https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html#tutorial-videos) about how to disable the tutorial button. You are missing some other important exports can you try to add the following and restart your app:

```
export const LOGIN_LOGO = null;
export const SHOW_TUTORIALS = false;
export const SETTINGS_BASE_URL = '/settings';
```
