### ISSUE TITLE
Image upload does not generate "small_" files

### ISSUE THREAD

**Issue by monkeymosher** [strapi/strapi#6130]
**Describe the bug**
When uploading small images (I don't know if it's the dimensions or file size the problem), the small format is not generated while the original file and thumbnail versions are uploaded fine.

**Steps to reproduce the behavior**

1. Edit one entry in the content-manager
2. Upload an image via the media manager (content-type: media, single media, allowed-images only)
3. Upload and save
4. No small_filename.jpg is generated or added to the database

**Expected behavior**
Upload and generate all formats

**Screenshots**
![Screen Shot 2020-05-08 at 2 02 29 PM](https://user-images.githubusercontent.com/4013355/81434810-c5bc4b80-9134-11ea-8cfd-f609f037be60.png)

See attached file for one image that triggers this bug.

![ceremony_ruined](https://user-images.githubusercontent.com/4013355/81434834-cce35980-9134-11ea-881a-042df4a20b16.jpg)

**System**

- Node.js version: 13.12.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.20
- Database: SQLite
- Operating system: MacOS Mojave 10.14.6

**Comment by derrickmehaffy** [comment]
`Strapi version: 1.22.4` Please double check your Strapi version as I think you have it confused with yarn.

**Comment by monkeymosher** [comment]
Oh sorry, bad copy-paste, I'm using 3.0.0-beta.20.

**Comment by alexandrebodin** [comment]
Hello the resizing only happens if your image is bigger than the breakpoints we have set. 

`large: 1000`
`medium: 750`
`small: 500`

This avoids resizing when there is no reason to do it.

**Comment by alexandrebodin** [comment]
Closing this issue as this is intended

**Comment by violabg** [comment]
Where can we configure breakpoints?

**Comment by DaTurboD** [comment]
> 
> 
> Where can we configure breakpoints?

you can configure breakpoints in https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/image-manipulation.js

**Comment by silveur** [comment]
@alexandrebodin Seems fair to avoid resizing images smaller than output although anyone should be able to set their image size preferences.
It comes natively in wordpress in the image size section and would come very handy for generating banners etc...
Furthermore you should be able to define a fit function such as `inside` like you did in the plugin's code.
Should we fork the upload plugin in the meanwhile? :(

**Comment by milanbargiel** [comment]
I ran into a similar problem as described above on my production system, a Virtual Private Server with Ubuntu 18.04 LTS. Sometimes image variants were not created even though the image dimensions were bigger than the defined breakpoints. I debugged the `strapi-plugin-upload` module and found out that resizing with sharp often failed with **glib: Error creating thread: Resource temporarily unavailable** error message.

```javascript
//strapi-plugin-upload/services/image-manipulation.js
const resizeTo = (buffer, options) =>
  sharp(buffer)
    .resize(options)
    .toBuffer()
    .catch(err => strapi.log.error(err)); // Print out error message
```

This was due to a limit on Max Tasks on my server.

By setting `DefaultTasksMax=infinity` in `/etc/systemd/system.conf` I could fix the issue and uploads now always have the defined breakpoint image variants.

**Comment by alexandrebodin** [comment]
@silveur right now you can use extensions and overwritte the file you want but that's not as clean as forking for sure. In the future forking will be the way to go for big changes. For the size preference we have the v2 in our roadmap but still are a few devs in the team only so feel free to go talk to @JabStrapi  or @sam-pires if you want to helps us with that ;)

**Comment by acalvino4** [comment]
> Hello the resizing only happens if your image is bigger than the breakpoints we have set.
> 
> `large: 1000`
> `medium: 750`
> `small: 500`
> 
> This avoids resizing when there is no reason to do it.

It would be great for this to be documented here: https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html

**Comment by lucagasparetto** [comment]
> Hello the resizing only happens if your image is bigger than the breakpoints we have set.
> 
> `large: 1000` `medium: 750` `small: 500`
> 
> This avoids resizing when there is no reason to do it.

Hi @alexandrebodin,
about this logic to skip breakpoints if not needed, I have a question:
It happens that We manage images with small dimensions (i.e. 600x600), but with large file sizes (i.e. 1,5MB).

Is there any way to force Strapi generating all the breakpoints, also if it thinks the image is already small enough?

I'm not an expert about image compression, but using Sketch it generates this kind of images. It would be great if Strapi can handle this without our manual intervention every time.
Thank you!
