### ISSUE TITLE
Assigning custom field to model attribute throws DB schema error

### ISSUE THREAD

**Issue by jameslouiz** [strapi/strapi#6132]
Following instructions [here](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/frontend-field-api.html#registering-a-new-field) I can register my plugin and custom field, which can be found on `FieldApi.getFields()`.

However when it comes to assigning this custom field to an attribute in my models file, I get a mongoose error:

```error TypeError: Invalid schema configuration: `custom-field` is not a valid type at path `foobar`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.```

**Steps to reproduce the behavior**

1. [Register plugin](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/frontend-field-api.html#registering-a-new-field)
2. Assign field to attribute type
```
"foobar": {
      "type": "custom-field",
},
```

**Expected behavior**
To see my component rendered in the content manager view

**System**

- Node.js version: 14.2.0
- NPM version: 6.14.4
- Strapi version:  Strapi v3.0.0-beta.20.1
- Database: MongoDB 4.2.6
- Operating system: OSX 10.14.6 

**Additional context**

**Comment by edwinofsakh** [comment]
I have the same issue. As I understand it is connected to the implementation of `convertType` function from `strapi-connector-mongoose/lib/utils/index.js`. It supports just a predefined list of types.

**Comment by lauriejim** [comment]
Hello! I ping @soupette about that.

**Comment by soupette** [comment]
@edwinofsakh @lauriejim as documented in our [docs](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/frontend-field-api.html#plugin-s-front-end-field-api) this API is currently only available for the content-manager. 
Regarding the content type builder we need to make some small updates especially in this [file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js) before allowing this API in the admin. Then, we will need to find a way to have its backend accepts custom fields which is currently not the case. 

Despite the fact that the content-type-builder does not accept custom fields yet you can still use the files system to create new ones, I know it's not the expected answer but our focus is currently on another feature. 

If someone from the community feels like improving the plugin I'll be more than happy to provide infos on how to do it, feel free to DM on the community Slack!
