### ISSUE TITLE
Error: ENOENT: No such file or directory, open '.../build/index.html'

### ISSUE THREAD

**Issue by peter-palmer** [strapi/strapi#6138]
Hello there.

I just made `npm start` in my new strapi project and when the browser opens there is a blank screen with a message that says: Not Found

![image](https://user-images.githubusercontent.com/58218056/81471315-966b1480-91f0-11ea-8e17-6ff2b5f39e07.png)

Also, in the console says: Error: ENOENT: No such file or directory, open '.../build/index.html'

![image](https://user-images.githubusercontent.com/58218056/81471407-1ee9b500-91f1-11ea-9dea-a16db53ad7df.png)

I configured the project with mongo. If I make `--quickstart` the project works correcly, but if I configure a custom project with mongo then I don't know why does not work.

![image](https://user-images.githubusercontent.com/58218056/81471397-f661bb00-91f0-11ea-9a5d-74b8d7482354.png)

The database seems to be created, I have checked that, but I the folder build is not in the project, so maybe is not compiling the files... any thought?

Thanks for your time.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by admhemed** [comment]
I wonder how can an issue descriptive be better than this one from @peter-palmer  
Please just follow this: 
>I just made npm start in my new strapi project and when the browser opens there is a blank screen with a message that says: Not Found

The app breaks from first step.

**Comment by derrickmehaffy** [comment]
@admhemed the Bug report or Feature request template is **required** no matter how simple the issue is. Any normal questions should be directed towards [discussions](https://github.com/strapi/strapi/discussions).

It makes both the Strapi team and Contributors lives much easier when we can clearly see all the variables relating to the bug such as node, npm, strapi versions as well as the OS being used.

It's a small ask from us to fill out the simple template that saves us time from having to dig through the issue to locate the information we need to try and reproduce the issue.

**Comment by derrickmehaffy** [comment]
I can tell just based on looking at this, the user had an old version of Strapi they tried updating to beta.20.3 (the error messages).

@peter-palmer please fill out the template so I can properly understand from what version you were coming from. Also please ensure you do read the migration guides and the update guide on the docs:

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/
https://strapi.io/documentation/3.0.0-beta.x/guides/update-version.html

**Comment by ljc-dev** [comment]
@peter-palmer 
I was brought here by the exact same issue. Just made it work now. Here's how:
As you said, there is no build folder. So I built the strapi app first by running
`npm run build`
and it should add the missing files.

**Comment by rjbernaldo** [comment]
`NODE_ENV npm run build`

**Comment by jattoo** [comment]
As i am on localhost, running `npm run develop` solved all for me too as well. Checking package.json, you should see script `"develop": "strapi develop"` and therefore i took the solution provided by @ljc-dev. After everything finished installing, it automatically opened the admin page up.

**Comment by Yomittheking** [comment]
Firstly i would like to say that, I FEEL YOU MY BROTHER

i am no coder but i managed to solve this problem by a rather unusual method 
here is what i did:

step1: open your cmd and run this command "yarn create strapi-app my-project --quickstart"
step 2: this new "my-project "  file would be found under your personal dir (the user dir)
step 3: now copy the build folder from that folder
step 4:now paste that build folder under your main server folder and now re-run your app

this worked for me i hope it does for u too

**Comment by derrickmehaffy** [comment]
> Firstly i would like to say that, I FEEL YOU MY BROTHER
> 
> i am no coder but i managed to solve this problem by a rather unusual method
> here is what i did:
> 
> step1: open your cmd and run this command "yarn create strapi-app my-project --quickstart"
> step 2: this new "my-project " file would be found under your personal dir (the user dir)
> step 3: now copy the build folder from that folder
> step 4:now paste that build folder under your main server folder and now re-run your app
> 
> this worked for me i hope it does for u too

You can also just run `npm run build` or `yarn build` in the main project folder. (Using `NODE_ENV` if needed)

**Comment by peter-palmer** [comment]
Thanks to @ljc-dev has the solution.

So, execute `yarn develop` and it will work!

**Comment by dsfai2020** [comment]
> You can also just run `npm run build` or `yarn build` in the main project folder. (Using `NODE_ENV` if needed)

This resolved my issue.  npm run build.  Thank you and everyone here as well.  I think my Strapi directory corrupted when I turned off my computer while it was running (forced a restart for an update to windows 10 and selected - Force Restart).

**Comment by ElianGarcia01** [comment]
Para entender este error, es importante aclarar primero la diferencia entre npm run develop y npm run start, ya que el primero es para correr el proyecto en modo desarrollo y el segundo (npm start) es para cuando el proyecto ya esta listo para ser iniciado en producción, por lo tanto, con npm run develop siempre "deberia" correr bien ya que trae la configuración de strapi por defecto, en cambio, cuando lo haces con npm run start es porque algo esta fallando en tu configuración del proyecto para ser desplegado en producción. y por lo tanto lo importante es que tambien logre ejecutarse el comando npm run start correctamente. 
Este error me ha ocurrido varias veces y siempre lo he solucionado siguiendo el orden de comandos, primero: npm install para asegurar que todas las dependencias de node-modules estén actualizadas, segundo el NODE_ENV=production npm run build y tercero, ejecutar el comando npm run start, con esto debería solucionarse el error, ya que este error generalmente ocurre porque el proyecto de strapi en build no se esta construyendo correctamente.
Incluso con nodejs sueles ocurrir que ocupe mas memoria para ejecutar correctamente strapi, esto se soluciona dando mas memoria a node js con el comando: NODE_OPTIONS="--max-old-space-size=4096" npm run build (Es importante que primero tengan en cuenta el valor de la memoria del ordenador en donde se esta desplegando su proyecto).
