### ISSUE TITLE
TypeScript types do not match reality

### ISSUE THREAD

**Issue by Industrial** [strapi/strapi#6141]
The TypeScript types in https://github.com/strapi/strapi/blob/master/packages/strapi/index.d.ts#L3 do not match with the implementation in https://github.com/strapi/strapi/blob/master/packages/strapi/lib/Strapi.js#L37.

```ts
import strapi from 'strapi'

const api = strapi()
```

**Comment by derrickmehaffy** [comment]
Typescript isn't entirely support yet (and this isn't following the proper bug report template)

see: 
https://github.com/strapi/strapi/issues/630
https://portal.productboard.com/strapi/1-public-roadmap/c/30-support-typescript
