### ISSUE TITLE
[Question] How to configure the admin correctly

### ISSUE THREAD

**Issue by Industrial** [strapi/strapi#6142]
Hi!

I have `config/environments/development/request.json` with `"router.prefix": "/api"` .
I have `config/environments/development/server.json` with `"admin.path": "/api/admin"`.

Because of `request.json`, strapi is served correctly.
Because of `server.json`, The URL `/api/api/admin` is now serving the `index.html` and `/api/admin` is 404.
The generated HTML/CSS files correctly point to `/api/admin` where I want it but it is mounted at `/api`.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
