### ISSUE TITLE
GET http://localhost:1337/content-type-builder/reserved-names 404 (Not Found)

### ISSUE THREAD

**Issue by thiagoaugusto** [strapi/strapi#6143]
**Describe the bug**
I'm getting this "GET http://localhost:1337/content-type-builder/reserved-names 404 (Not Found)" error related to "reserved-names" feature.
The error only occurs on v3.0.0-rc.0 git tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/3350767/81481955-09cd5000-920a-11ea-9e04-af4a8dbc8222.png)

![image](https://user-images.githubusercontent.com/3350767/81481931-dc80a200-9209-11ea-9b71-416f27c50f1d.png)

When "reserved-names" is removed from array, the page is rendered with no errors:

![image](https://user-images.githubusercontent.com/3350767/81482180-86acf980-920b-11ea-85e1-bcfe60c29457.png)

![image](https://user-images.githubusercontent.com/3350767/81482198-97f60600-920b-11ea-8a0f-1d283d993241.png)

When  the app is created by using "npx create-strapi-app@rc my-test --quickstart" command, the page is rendered with no errors as well:

![image](https://user-images.githubusercontent.com/3350767/81482606-b0b3eb00-920e-11ea-90e9-e0b82e42119c.png)

**Comment by derrickmehaffy** [comment]
@thiagoaugusto Please completely fill out the template, with the core part of it being the versions at the bottom of the template


> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
Could not reproduce this on rc.0: 
![image](https://user-images.githubusercontent.com/8593673/81787642-33aa9f00-94b6-11ea-9665-5735f0a7c0c2.png)

**Comment by Jayshri-Rathod** [comment]
same issue I am facing have. you got any solution? please let me know.
