### ISSUE TITLE
Issue on /auth/local/register

### ISSUE THREAD

**Issue by w0dm4n** [strapi/strapi#6145]
Hello, there is an issue with the endpoint '/auth/local/register'

While i add a required column to 'Users' on the admin dashboard:

> {
> 	"username": "foo2",
> 	"email": "foo2@foo.com",
> 	"password": "hello"
> }

this request fail everytime with the error 'username already exist' when i add on User collection another required field, i suppose that it due to the fact that it did not take the new required column as part of the scheme?
Thanks.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by w0dm4n** [comment]
Yeah, not really sorry i'm lazy, and it's more to help you then me.
It's simple to understand: with your registration system there is no ways to add required columns or it block completely the calls saying that the basic 'username' one isnt in the payload. don't need a retarded format to understand that!
thanks.
