### ISSUE TITLE
Resetting the 'id' field, how to?

### ISSUE THREAD

**Issue by Ryuk-hash** [strapi/strapi#6148]
A little help, please? I've just started exploring strapi. ;)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
