### ISSUE TITLE
Act on fetched data globally / shared controller

### ISSUE THREAD

**Issue by rroblik** [strapi/strapi#615]
**Strapi version**:
3.0.0-alpha.9

Hi,

(As you will see) I'm newbie using both strapi and mongo with npm :) 

I'm testing strapi for now, and I would like to apply some cleanup on returned data (aka : remove `_id` and `__v` keys)

For now, what i'm doing is  :
```js
// @file api/Testentry/controllers/Testentry.js
// ...
find: async (ctx) => {
  // Add lean to the fetched data, to get them as simple js object
    const data = await strapi.services.testentry.fetchAll(ctx.query).lean();
	
    // Use a custom cleanup function to act on `data` 
    ctx.send(dataCleanupFunction(data));
  },
//...
```

I think there is more elegant way of doing such things ; moreover I would like to know how to "hook" on every `find` `findOne` (...) methods for all my controllers (or models) without to manually have to write code on each methods. Sort of controller inheritance maybe ...

Thanks.

Regards

NB : sorry for my bad english 

EDIT : maybe the solution is to act on the model itself... to do something like this : https://gist.github.com/fiveisprime/9749782

**Comment by lauriejim** [comment]
Hello @rroblik , did you try the gist you linked ? It works ?

**Comment by Aurelsicoko** [comment]
The gist won't work because you're using the Mongoose `lean` method. So the magic applied by Mongoose is not executed like the `transform` middleware.

However, the cleaner way to do what you're trying to do is to use the policy.

`./api/**/config/routes.json`
```js
{
  "routes": [
    {
      "method": "GET",
      "path": "/testentry",
      "handler": "Testentry.find",
      "config": {
        "policies": ['cleaner']
      }
    }
  ]
}
```

Create the `cleaner.js` policy.

```js
module.exports = async (ctx, next) => {
  // Execute the controller action.
  await next();

  // After.
  ctx.body = dataCleanupFunction(ctx.body);
};
```

**Comment by rroblik** [comment]
Hi 

@lauriejim : is used
`strapi generate:policy dataCleanup`

Then updated my `routes.json` to add : 
```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/site",
      "handler": "Site.find",
      "config": {
        "policies": ["global.dataCleanup"]
      }
    }
   ]
}
```
Here is the `config/policies/dataCleanup.js` file content
```js
'use strict';

const _ = require('lodash');
const USELESS_KEYS = ['_id', '__v'];

function dataCleanup(data) {
  var cleaned_data = [];

  _.forEach(data, function (d) {
    var buff = _.omit(d, USELESS_KEYS);
    cleaned_data.push(buff);
  });

  return cleaned_data;
}

module.exports = async (ctx, next) => {
  await next();

  // After.
  ctx.body = dataCleanup(ctx.body);
};
```

But ... not working ; as the problem is the same : `ctx.body` is not a plain javascript object isn't it ?

How to do ?

Thanks

**Comment by rroblik** [comment]
Okay let's add a self (half) answer :  

Here is the corrected policy file:
```js
'use strict';

const _ = require('lodash');
const USELESS_KEYS = ['_id', '__v'];

function dataCleanup(data) {
  var cleaned_data = [];

  _.forEach(data, function (d) {
    var buff = _.omit(d.toObject(), USELESS_KEYS);

    cleaned_data.push(buff);
  });

  return cleaned_data;
}

module.exports = async (ctx, next) => {
  await next();

  // After.
  ctx.body = dataCleanup(ctx.body);
};
```

Note the `toObject()` use ([mongoose doc](http://mongoosejs.com/docs/api.html#document_Document-toObject)) ; but I think doing this way is a little dirty... isn't it (performances impact) ?

**Comment by rroblik** [comment]
(@lauriejim please reopen this issue :))

**Comment by yagobski** [comment]
Still have the same issue. I still not get data as simple js object

**Comment by Aurelsicoko** [comment]
You need to execute `toJSON()` method.

```js

// function dataCleanup(data) {
// ...

module.exports = async (ctx, next) => {
  await next();

  ctx.body = dataCleanup(ctx.body.toJSON ? ctx.body.toJSON() : ctx.body);
}
```
