### ISSUE TITLE
Link to programmatic usage doesn't exist

### ISSUE THREAD

**Issue by aviskarkc10** [strapi/strapi#6152]
**Describe the bug**
The link to programmatic usage doesn't exist.

![image](https://user-images.githubusercontent.com/13309631/81494969-7ad53c00-92cc-11ea-9351-c553e0112a57.png)

**Steps to reproduce the behavior**

1. Go to https://strapi.io/documentation/3.0.0-beta.x/content-api/parameters.html#available-operators
2. Click on `programmatic usage` on the image I posted above.
3. You will get to a 404 page.

**Expected behavior**
This should lead to the documentation for `programmatic usage`

**Screenshots**
N/A

**Code snippets**
N/A

**System**
N/A

**Additional context**
N/A

**Comment by derrickmehaffy** [comment]
Fixed in: https://github.com/strapi/strapi/pull/5893
