### ISSUE TITLE
Custom swagger link but admin click not change

### ISSUE THREAD

**Issue by cjfff** [strapi/strapi#6153]
**Describe the bug**
I change the plugin document setting.json but admin button link also old

the setting.json as follow

```json
{
  "x-strapi-config": {
    "path": "/cms/dashboard/documentation",
    "showGeneratedFiles": true,
    "generateDefaultResponse": true
  }
}
```

**Steps to reproduce the behavior**
1. yarn strapi install documentation
2. change the path of the x-strapi-config to /cms/dashboard/documentation
3. into admin docuemnt. click open document
4. the link do not Expected the 127.0.0.1:/3337/cms/dashboard/documentation

**Expected behavior**
the link Expected my  custom path 

**Screenshots**
![image](https://user-images.githubusercontent.com/20502762/81495230-71a29a00-92e1-11ea-8d33-81d6e1abe4dd.png)

![image](https://user-images.githubusercontent.com/20502762/81495305-ed9ce200-92e1-11ea-8cc8-41df97a3d9f1.png)

**System**
- Node.js version: v12.14.1
- NPM version: 6.14.1
- Strapi version: 3.0.0-beta.20
- Database: mysql
- Operating system: macos

**Additional context**
other, now my server has custom api prefix, but the swagger plugins static file url how to setting add the prefix...

![image](https://user-images.githubusercontent.com/20502762/81495442-f0e49d80-92e2-11ea-9344-b3796b6f8ee8.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
I thinks this link should be hardcoded.
Could you please try to investigate this issue and submit a PR to fix it.
I really appreciate if you do that.
