### ISSUE TITLE
Dynamic zone  returned content is incorrect

### ISSUE THREAD

**Issue by yacir** [strapi/strapi#6157]
**Describe the bug**
A get request for content type returns an incomplete response of a other nested content type with this one has a dynamic zone.

**Steps to reproduce the behavior**

1- Run this sample project [dz-issue.zip](https://github.com/strapi/strapi/files/4607514/dz-issue.zip)
2- Get available buttons: http://localhost:1337/buttons (to compare response with next one)
3- Get available responses: http://localhost:1337/responses
4- The `action` field is not returned for the button object

PS: admin login : demo | password : password

**Expected behavior**
All the field should be returned

**System**

- Node.js version: v12.4.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.20.3
- Database:
- Operating system:

**Comment by lauriejim** [comment]
Hello can you please share your API response in the body of you question.
This will save me some time.
After that, if it's because the deep populate, your can check this video - https://www.youtube.com/watch?v=VBNjCgUokLk&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=10&t=0s
By default we limit to 2 level of population.

**Comment by yacir** [comment]
@lauriejim here are the responses: 

* `/buttons`
```json
[
  {
    "id": 1,
    "title": "Yes",
    "desciption": null,
    "created_at": "2020-05-07T12:31:53.493Z",
    "updated_at": "2020-05-07T12:31:53.493Z",
    "action": [
      {
        "__component": "action.url",
        "id": 1,
        "type": "url",
        "url": "https://example.com/option"
      }
    ]
  }
]
```

* `responses`
```json
[
  {
    "id": 1,
    "reference": "welcome",
    "created_at": "2020-05-07T12:47:52.226Z",
    "updated_at": "2020-05-07T12:47:52.226Z",
    "items": [
      {
        "__component": "components.replies",
        "id": 1,
        "text": "Do you want to Subscribe for this type of content? ",
        "buttons": [
          {
            "id": 1,
            "title": "Yes",
            "desciption": null,
            "created_at": "2020-05-07T12:31:53.493Z",
            "updated_at": "2020-05-07T12:31:53.493Z"
          }
        ]
      }
    ]
  }
]
```

**Comment by lauriejim** [comment]
Ho okay, you don't have the last relation level.
It's normal that the population doesn't work but you should have the key.
There is already an issue about that.
Components doesn't send relation when they deep populate.
I'm not able to find the issue to link it there, but I assure you we are aware of this issue.
I don't have any workaround for now sadly :/

**Comment by mgurevin** [comment]
> Ho okay, you don't have the last relation level.
> It's normal that the population doesn't work but you should have the key.
> There is already an issue about that.
> Components doesn't send relation when they deep populate.
> I'm not able to find the issue to link it there, but I assure you we are aware of this issue.
> I don't have any workaround for now sadly :/
> But thank you for reporting this issue, I appreciate.

hey @lauriejim,
do you have a link for the related issue already opened?
any progress about this issue?

**Comment by Sid-Turner-Ellis** [comment]
Can you not just make a second request using the key of the relation?
