### ISSUE TITLE
Bootstrap is taking unusually long to execute its callback

### ISSUE THREAD

**Issue by mittalyashu** [strapi/strapi#616]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.9.2

**Operating system**: Windows 10

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** `strapi start` is not working

**If the current behavior is a bug, please provide the steps to reproduce the problem** `strapi start`

**What is the expected behavior?** Strapi should start runnig

**Comment by redni** [comment]
Is there any error or something else? From my own experience, I know that after using `strapi start` the console is empty until you enter `http://localhost:1337/` on the browser.

At the beginning I was also wondering if everything works and started. It turned out that any information in the console only appears after visiting the site. For new users it can be confusing because they do not know what to do next.

**Comment by mittalyashu** [comment]
I have a chat with @Aurelsicoko on slack.

![image](https://user-images.githubusercontent.com/29014463/36029794-a98f314c-0dca-11e8-8b61-585014b523ce.png)

**Comment by Aurelsicoko** [comment]
@mittalyashu Is this https://github.com/strapi/strapi/issues/561 the same issue?

I'm working on it. First of all, we need to increase the default timeout for loading hook. I will increase the 1000ms to 3000ms.

**Comment by mittalyashu** [comment]
@Aurelsicoko, I am not sure that #616 and #561 are the same issue or not.

I tried to increase the timeout but no effect.

**Comment by abrakadobr** [comment]
i have same problem and it comes quite interesting way:
1. i use nvm, node 9.2.0, npm 5.5.1, installed npm i -g strapi@alpha
2. i created test project (strapi new sa1) and all goes fine - i generated auth, try module developent and admin panel - like all =)
3. now i got idea to repeat steps of "basic installation" and have no success at all (repeated 6-7 times already), so i have a bit more logs, every time same:

```
developer@abrakadobr-nb:~/dev/nodejs/strapiTests$ nvm ls
         v8.9.1
->       v9.2.0
default -> 9 (-> v9.2.0)
node -> stable (-> v9.2.0) (default)
stable -> 9.2 (-> v9.2.0) (default)
unstable -> 8.9 (-> v8.9.1) (default)
iojs -> iojs- (-> N/A) (default)
developer@abrakadobr-nb:~/dev/nodejs/strapiTests$ npm -v
5.5.1
developer@abrakadobr-nb:~/dev/nodejs/strapiTests$ node -v
v9.2.0
developer@abrakadobr-nb:~/dev/nodejs/strapiTests$ 
developer@abrakadobr-nb:~/dev/nodejs/strapiTests$ strapi new sa2
INFO (18089 on abrakadobr-nb): Creating your application... It might take a few seconds.
INFO (18089 on abrakadobr-nb): Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: sa2
 Host: localhost
 Port: 27017
 Username: 
 Password: 
INFO (18089 on abrakadobr-nb): Testing database connection...
INFO (18089 on abrakadobr-nb): Copying the dashboard...
INFO (18089 on abrakadobr-nb): Installing dependencies...
INFO (18089 on abrakadobr-nb): The plugin settings-manager has been successfully installed.
INFO (18089 on abrakadobr-nb): The plugin content-type-builder has been successfully installed.
INFO (18089 on abrakadobr-nb): The plugin content-manager has been successfully installed.
INFO (18089 on abrakadobr-nb): The plugin users-permissions has been successfully installed.
INFO (18089 on abrakadobr-nb): The plugin email has been successfully installed.
INFO (18089 on abrakadobr-nb): The plugin analytics has been successfully installed.
INFO (18089 on abrakadobr-nb): Linking `strapi` dependency to the project...
INFO (18089 on abrakadobr-nb): Your new application `sa2` is ready at `/home/developer/dev/nodejs/strapiTests/sa2`.
developer@abrakadobr-nb:~/dev/nodejs/strapiTests$ cd sa2
developer@abrakadobr-nb:~/dev/nodejs/strapiTests/sa2$ strapi start
(node:18264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: strapi.store is not a function
(node:18264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: strapi.store is not a function
WARN (18264 on abrakadobr-nb): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (18264 on abrakadobr-nb): Perhaps you forgot to call it?
WARN (18264 on abrakadobr-nb): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (18264 on abrakadobr-nb): Perhaps you forgot to call it?
^C
developer@abrakadobr-nb:~/dev/nodejs/strapiTests/sa2$ 

```

4. but my 1st test project running succesfully

```
developer@abrakadobr-nb:~/dev/nodejs/strapiTests/strapi1$ strapi start
INFO (18625 on abrakadobr-nb): Server started in /home/developer/dev/nodejs/strapiTests/strapi1
INFO (18625 on abrakadobr-nb): Your server is running at http://localhost:1337
DEBUG (18625 on abrakadobr-nb): Time: Tue Feb 13 2018 22:52:59 GMT+0700 (+07)
DEBUG (18625 on abrakadobr-nb): Launched in: 8132 ms
DEBUG (18625 on abrakadobr-nb): Environment: development
DEBUG (18625 on abrakadobr-nb): Process PID: 18625
DEBUG (18625 on abrakadobr-nb): Version: 3.0.0-alpha.9.3 (node v9.2.0)
INFO (18625 on abrakadobr-nb): To shut down your server, press <CTRL> + C at any time

```

**Comment by lauriejim** [comment]
@abrakadobr you don't have the same issue.
Please be sure the application you launch has been created with the Strapi version you have on your computer.

**Comment by mittalyashu** [comment]
I tried creating a new project as seeing how it work and here what I found out.

I get this error in MongoDB
![image](https://user-images.githubusercontent.com/29014463/36330314-2ad91bea-138f-11e8-9ee1-fc89d12242b9.png)

MySQL
![image](https://user-images.githubusercontent.com/29014463/36330342-40fe47d8-138f-11e8-8cc6-7d290ce42a02.png)

**Comment by Aurelsicoko** [comment]
@mittalyashu Can you please use the latest version of Node.js? 9.5.0 with npm 5.6.0. And try again. It's strange because it should work with MongoDB. Also, make sure, you dropped your Mongo collection before creating a new app.

**Comment by lauriejim** [comment]
@mittalyashu any update about your issue ?

**Comment by mittalyashu** [comment]
I have tried again and this time I got this error:
![image](https://user-images.githubusercontent.com/29014463/36902504-b02cd8b0-1e50-11e8-91e0-9bdc096c05cb.png)

**Comment by lauriejim** [comment]
Can you update you Strapi version. And test again with new project.

**Comment by paulmerz** [comment]
@mittalyashu this error might be caused by the server being localhost in environment -> development -> database.json. Try to replace with 127.0.0.1.

I have the same error than you with bootstrap on windows 10 x64

**Comment by paulmerz** [comment]
I have the same error than you with **bootstrap** on windows 10 x64

**Comment by lauriejim** [comment]
That is a good new :)

**Comment by mittalyashu** [comment]
That didn't work for me.
![image](https://user-images.githubusercontent.com/29014463/37710669-5a297e44-2d34-11e8-9010-5618b6f49531.png)

**Comment by Aurelsicoko** [comment]
@mittalyashu It seems that the server cannot connect to your MySQL database... It's not related to this issue. Make sure your MySQL database is running...

**Comment by mittalyashu** [comment]
So, how to connect the server to MySQL database?

**Comment by Aurelsicoko** [comment]
@mittalyashu You need to install and run the MySQL on your own. You can use [Mamp](https://www.mamp.info/en/) (Mac) or [Wamp](http://www.wampserver.com/) (Windows) to easily run a MySQL database.

**Comment by tudorbertiean** [comment]
@mittalyashu I encountered the exact same error when I was attempting to migrate from version 14.5 to 15. In the process, I had left strapi-hook-mongoose at 14.5 and I was getting the error from that. I then npm installed strapi-hook-mongoose version 15 and the error went away.

**Comment by jimmymam18** [comment]
I'm using yarn on my terminal of visual studio and after I used Strapi and the error appears stating that "Warn Bootstrap is taking unusually long  to execute  its call back 3500 millisecond" can someone help me

**Comment by jimmymam18** [comment]
I think strapi is still buggy.

**Comment by jimmymam18** [comment]
<img width="714" alt="Screen Shot 2019-06-17 at 2 50 33 AM" src="https://user-images.githubusercontent.com/5707436/60629777-eea0e100-9dab-11e9-9a43-673718d9ec9e.png">

**Comment by jimmymam18** [comment]
<img width="1370" alt="Screen Shot 2019-07-03 at 4 00 45 PM" src="https://user-images.githubusercontent.com/5707436/60629782-fd879380-9dab-11e9-8544-f7d00f8a6b96.png">

**Comment by jimmymam18** [comment]
<img width="1440" alt="Screen Shot 2019-07-03 at 4 03 58 PM" src="https://user-images.githubusercontent.com/5707436/60629832-3e7fa800-9dac-11e9-946d-f079c11fc4f0.png">

**Comment by jimmymam18** [comment]
<img width="1440" alt="Screen Shot 2019-07-03 at 4 05 28 PM" src="https://user-images.githubusercontent.com/5707436/60629919-ab933d80-9dac-11e9-8722-240a819f2063.png">

**Comment by jimmymam18** [comment]
<img width="1433" alt="Screen Shot 2019-07-03 at 4 05 53 PM" src="https://user-images.githubusercontent.com/5707436/60629929-b4840f00-9dac-11e9-8014-9ec772290e75.png">

**Comment by jimmymam18** [comment]
<img width="1440" alt="Screen Shot 2019-07-03 at 4 06 24 PM" src="https://user-images.githubusercontent.com/5707436/60629938-bc43b380-9dac-11e9-8bab-230f97461fff.png">

**Comment by jimmymam18** [comment]
I think strapi is stupid problem a amateur invented strapi

**Comment by jimmymam18** [comment]
Can someone fucking help me because this bullshit Strapi is not work

**Comment by derrickmehaffy** [comment]
@jimmymam18 please be kinder with your words, if you need help like this use slack.
