### ISSUE TITLE
Relation selector from content-manager not working correctly

### ISSUE THREAD

**Issue by DimitrieStraoanu** [strapi/strapi#6160]
**Describe the bug**
The relation selector allows adding the same content-type multiple times.

**Steps to reproduce the behavior**
1. Go to 'content-types builder'.
2. Create new collection type.
3. Add a new relation field type 'has many'.
4. Go to content-manager, select the created content-type and click 'add new'.
5. Add a item/content-type from the relation selector.

**Expected behavior**
After you added the content-type you should not be able to select it again.

**System**

- Node.js version: v12.14.0
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Can you give a screenshot of which relation you are using?

**Comment by DimitrieStraoanu** [comment]
Relation type
![relation type](https://user-images.githubusercontent.com/48469159/81571037-14bee680-93aa-11ea-88e8-ef3bc895e8d7.jpg)

Selector issue. 
![selector2-80](https://user-images.githubusercontent.com/48469159/81571546-c231fa00-93aa-11ea-873b-91abebaf03ed.jpg)

**Comment by derrickmehaffy** [comment]
So it's using the `manyWay` type :thinking: 

@alexandrebodin I'm not entirely sure if I could think of a usecase where you would want to include multiples of the same relation but is this intended?

**Comment by alexandrebodin** [comment]
Would I would argue why not ? This is what the unique option would make sense for :)

**Comment by DimitrieStraoanu** [comment]
If I save the content type and come back  I can't select the Authenticated option again. So I guess it's something buggy.

**Comment by alexandrebodin** [comment]
@DimitrieStraoanu Good to know. Tagging @soupette to check if this is just a minor bug in the admin :)

**Comment by derrickmehaffy** [comment]
> I would argue why not ? This is what the unique option would make sense for :)

I mean I don't disagree, but since we can't set unique on relations yetttt >.>
