### ISSUE TITLE
Strapi main info page broken on 3.0.0-beta.20.3

### ISSUE THREAD

**Issue by maximg-cybcube** [strapi/strapi#6161]
**Describe the bug**
Home page layout broken

**Steps to reproduce the behavior**

1. Go to strapi main page (without /admin)

**Screenshots**
![image](https://user-images.githubusercontent.com/60916240/81561689-3ca74d80-939c-11ea-9094-a2a5390986ad.png)

**System**

- Node.js version: 13.8.0
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.20.3
- Database: mysql

**Additional context**
Updated from 3.0.0-beta.19.5

**Comment by DimitrieStraoanu** [comment]
This is intended, see migration guide about index page: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html

**Comment by maximg-cybcube** [comment]
Oh, my mistake :) Thanks for quick response
