### ISSUE TITLE
Split admin frontend into devDependencies

### ISSUE THREAD

**Issue by benedictjohannes** [strapi/strapi#6163]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Strapi front end is written in React. The step of building the admin front end, if there are no change in Strapi data model, would remain unchanged after build step. But as far as I observe, in most projects, front end build chain takes up the majority of *node_modules* dependencies.

In development mode where data models might be changing, having Strapi automatically develop the front end is totally awesome. However, in production mode, the front-end build chain dependencies are probably never called upon. This limits Strapi's ability to be launched in serverless containers, that limit application size. 

The front end toolchain that Strapi packages that calls it should be included as `devDependencies`. As such, to develop, Strapi projects should be installed with `devDependencies`.
In production, Strapi projects should be installed with `--production` flag that eliminate `devDependencies` of front-end tool chain. This is of course, after build step, and the build folder can either be committed to source control or deployed separately to the application. 

Right now, my Strapi *node_modules* are 380MB in size, which means if Strapi is to be deployed using Google Cloud Run fully managed container service, I would probably need at least 1GB RAM to deploy Strapi.

If the *node_modules* can be shrinked under 50MB, the RAM requirement would be half of that. 
Or even better, Strapi can be deployed on AWS Lambda / Google Cloud Functions, with only database server as persistent service. I'm fairly sure purely backend-only Strapi would not consume more than 40MB of *node_modules* and 10MB of source code / build folder, making it into AWS Lambda nicely.

**Comment by derrickmehaffy** [comment]
I disagree with this, as in most development flows you are either rebuilding each time you deploy (as you are not storing the build in git, that is bad) or your CI/CD process is building and deploying the admin on it's own.

**Comment by derrickmehaffy** [comment]
https://kentcdodds.com/blog/why-i-dont-commit-generated-files-to-master
https://stackoverflow.com/questions/34559061/should-the-build-directory-be-committed-in-a-version-controlled-project

It is fairly universal that you don't commit generated files into Source control (Node Modules, Build, Dist, ect)

**Comment by benedictjohannes** [comment]
@derrickmehaffy Thank you for your respond. I would argue on your first comment (most development flows) that the CI/CD scenario can be easily altered to start by `npm install`, afterwards, build and test Strapi.
After all done, run `npm install --production`
And deploy the folder.
Or even simpler: do not use `--production` flag in development builds.

On your point of commit it to source control, I argee with you at large, and I was *not* suggesting it as the main solution. Point taken, but I won't discount it entirely. I can come up with an example like having `.gitignore` in `master` that is removed in `deploy` branch, making CI/CD able to commit `build` without cluttering up master branch. Your linked stackoverflow question has 2 answers  that explains it better than me. I brought this up to highlight that the `build` folder and purely backend code is enough to present a UI when no data model change is necessary.

And in the [docs](https://strapi.io/documentation/3.0.0-beta.x/admin-panel/deploy.html#deploy-the-administration-panel-on-another-server-aws-s3-azure-etc-than-the-api), the `build` directory can be deployed on storage services like AWS S3. 
This further accentuate my point that in production/stable environment, the frontend building code will never get touched. The unused dependencies can be eliminated if front-end code build chain are included as separate packages.

**Comment by derrickmehaffy** [comment]
The core problem with your argument @benedictjohannes though is Strapi uses environments during the build process as well.

`npm run build` is not the same as `NODE_ENV=production npm run build` Simply having 380mb worth of node modules is not really that large (IMO at least). There are multiple factors that go into this, and simply complicating things for the sake of decreases the node_modules folder size is not worth the trade offs.

I'll be interested to see what the Core Strapi team think though, maybe I'm wrong here as I'm certainly no frontend dev.

@soupette @virginieky @HichamELBSI thoughts?

**Comment by benedictjohannes** [comment]
Thank you for your reply. Perhaps I wasn't clear previously. Yes, in Strapi, `npm run build` is not `NODE_ENV=production npm run build` that it affect how the code works (`NODE_ENV can be used in switching configs)
What I meant to was `npm install --production` which will *not* pull `devDependencies` during install process, resulting in smaller `node_modules`.

380MB might not be large, @derrickmehaffy but it certainly make running Strapi in AWS S3 out of the question. My whole feature request is centered around wanting to use Strapi as a backend for a Gatsby static site generator (feed images, text, content into Strapi admin interface and store it, and have Gatsby generate website out of it). 

A website builder with multiple (finished) clients would deploy multiple Strapi service for each finished client at anytime. Strapi can be used to collect form data from static the website's frontend.
A finished website has no changing structure, no need for changing frontend build tool chain.

This is likely scenario I have in mind: Strapi backend seeing about 1 hour of activity per week. 

If I have 20 such Strapi backend, 400MB of project folder would require more RAM (in Google Cloud Run). If I assume 1 GB, that translate roughly into 20 GB hour of RAM. 
If the project fits in 50MB, I assume that the project needs only 512MB of RAM. This translate roughly into 10 GB hour of RAM every month.
As a systems engineer, would you agree that this would result in at least 20% cost saving?

**Comment by derrickmehaffy** [comment]
I think it would be far more cost effective to simply keep a static deployment (you could even run multiple instances of Strapi on a static VPS, though that isn't terribly clean)

Your primary cost is going to be the constant "cold boot" of each instance especially if you are constantly starting and stopping them.

With an "always-on" there is no cold boot wait, you could run on cheaper resources (since you aren't constantly taking API requests), and simply trigger Gatsby rebuilds using webhooks.

I am personally not a fan of "server-less" applications nor do I believe that Strapi fits the "server-less" architecture. But more often than not I generally see a fair decent cost increase in complex solutions like this.

Regardless, the issue I see is for people that -are not- doing it this way (in which you are the minority). It's not the normal "node way" and will likely cause quite a bit of confusion for those who are contributors. I do also feel it's adds quite a bit of unneeded complexity for such a niche case.

**Comment by benedictjohannes** [comment]
@derrickmehaffy I understand your approach. Coming from "always-on", there are sacrifices in deploying using serverless architecture. Given enough deployments, though, running multiple Strapi backend in one always-on server is indeed a great alternative to reduce costs.
Sorry for the overdue reply, I deployed a new Strapi application to Google Cloud Run (managed container service) to get some insight about this.

I've leaved the container to do nothing for at more than 12 hours, more than enough time for the container to be stopped.
The screenshot shows the first response, which is about 8.64ms (subsequent request: 350ms). 
In my development laptop, starting Strapi instance itself took quite some time (>4s) when the database is on the cloud (I tested on MongoDB Atlas free tier), while connecting to localhost PostgreSQL DB, Strapi start up in less than 1s.

These shows that you were totally right, container start up indeed caused cold boot wait. 

However, for my specific use case, it is not an issue, as I Strapi as headless CMS: The only users would be content authors and CI task building statically generated Gatsby site.

**Comment by derrickmehaffy** [comment]
Certainly, I know there is usecases like yours that it would make sense, but as I mentioned before it is **extremely** niche so I'm not sure if the drawbacks would be worth it in the long run (in terms of onboarding additional contributors to a non-standard package layout)

I know the Strapi team are quite busy right now with the new RBAC stuff to provide any of their own updates but for now I will leave this open until they get the chance. While I am still opposed to this change I do want to hear their feedback as they certainly have more experience than myself.

I do think the cold boot would be more costly on instances that measure cost based on load (that cold boot can easily spike single core, slow CPUs up to their max and hold it there) so constantly killing and cold-booting is not ideal.

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed but the discussion can be continued on our [forums](https://forum.strapi.io/) if someone would like to create a thread

**Comment by octalpixel** [comment]
@benedictjohannes Were you able to find a workaround ? Really interested to know!

@derrickmehaffy  Do you think serverless will be possible  with Lamba Containers ?

**Comment by derrickmehaffy** [comment]
> @benedictjohannes Were you able to find a workaround ? Really interested to know!
> 
> @derrickmehaffy  Do you think serverless will be possible  with Lamba Containers ?

Many have tried and failed, I've never seen a successful run in this way and its not something we will entertain going forward (support, bug reports, ect)

Strapi is not built that way

**Comment by benedictjohannes** [comment]
> @benedictjohannes Were you able to find a workaround ? Really interested to know!

I've never tried AWS Lambda containers. But I'd think it should be possible, as I've successfully deployed Strapi (production mode that never would do frontend rebuild, not development) in Google Cloud Run that also deploy containers, albeit with its own drawbacks (>5s cold start)

**Comment by octalpixel** [comment]
> > @benedictjohannes Were you able to find a workaround ? Really interested to know!
> 
> I've never tried AWS Lambda containers. But I'd think it should be possible, as I've successfully deployed Strapi (production mode that never would do frontend rebuild, not development) in Google Cloud Run that also deploy containers, albeit with its own drawbacks (>5s cold start)

Can you share your learnings  and experience?

**Comment by benedictjohannes** [comment]
@octalpixel Sure. Note that my app were using `"strapi": "3.0.0-beta.20.3"`. In short, 
1. I develop (locally) the structure (content-types, plugins) that I would need, `npm run strapi develop` (or in a server/VM. The point is, the structures that Strapi's going to define will be source controlled, if you use default strapi settings).
2. If you're going to use GCP, use the platform fully by using their [build service](https://cloud.google.com/cloud-build) and [container registry](https://cloud.google.com/container-registry).
3. In my case, I defined my [`cloudbuild.yaml`](https://cloud.google.com/cloud-build/docs/build-config) on the finished project folder as:
```yaml
steps:
  - name: 'node:12-slim'
    entrypoint: npm
    args: ['install']
  - name: 'node:12-slim'
    env:
      - 'NODE_ENV=production'
    entrypoint: npm
    args: ['run','build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/strapi', '.']
images: ['gcr.io/$PROJECT_ID/strapi']
```
3. I would create a Cloud Run deployment by choosing the container image. You can see that the production frontend is built right inside the container. 

I don't think this issue is the right place to take this discussion further to avoid derailing the topic or polluting Derrick's mailbox, but I think that can get you started into using Strapi at GCP, which, IMHO, has documentation made for developers (I can't wrap my head around documentation of the other cloud platform you mentioned). You can also reach me at benedict dot johannes at outlook dot co dot id

**Comment by jonatanalava** [comment]
> @benedictjohannes Were you able to find a workaround ? Really interested to know!
> 
> @derrickmehaffy Do you think serverless will be possible with Lamba Containers ?

We have it deployed serverless (split admin into SPA and API into Lambda containers) and are currently looking to improve the cold start aspects of it. Has anyone already looked into this before?
