### ISSUE TITLE
Should respond with 415 Unsupported Media Type when receiving a payload that isn't formatted correctly for the endpoint

### ISSUE THREAD

**Issue by toastyghost** [strapi/strapi#6166]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
The title pretty much covers it. The specific example of how I ran into this was I had a request interceptor in my front-end app that was errantly adding a "Content-Type: application/x-www-form-urlencoded" header to a login request, which should be "application/json". When this happens, Strapi responds with a generic 400 Bad Request rather than the appropriate 415.

**Comment by toastyghost** [comment]
Also maybe worth noting that I put this on the product board under my work email, josh dot clark at sunnydayfund dot com

**Comment by derrickmehaffy** [comment]
I completely agree with this (per my convo with @toastyghost on slack) There are certain endpoints that don't accept for instance the formData for media uploads, and I think all requests need to be checked for their formats and if the endpoint doesn't support we need to return the proper error code.

This would certainly help newer users debug their frontend when a library is sending the wrong format.

**Comment by lauriejim** [comment]
Ping @alexandrebodin and @soupette about this topic.

**Comment by alexandrebodin** [comment]
Hi, actually we use a body parser so it is pretty much agnostic to the query your are doing. the error is a 400 because the parsed body doesn't match the expected input. We have left it like this so a user that wants to develop a custom controller with a specific type won't be blocked but this policy :)

**Comment by derrickmehaffy** [comment]
Marking as closed as the current logic is what is intended
