### ISSUE TITLE
I can't login in Strapi

### ISSUE THREAD

**Issue by franklinpr2010** [strapi/strapi#6169]
Hello,

I try get login in strapi, but it's return bad request 400, I try with postman and it get token result with auth/login, but when I try login in strapi show this error.

My user and password are correct, because it's ok in my application front-end that use strapi api, but in strapi it say: invalid username or password.

I need help, please!

Thanks

**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
@franklinpr2010 please properly fill out the bug report template
