### ISSUE TITLE
Pagination configuration "Entries per page" for Media Library

### ISSUE THREAD

**Issue by omgMath** [strapi/strapi#6181]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
For _Collection Types_, when opening _Settings_ -> _Configure the view_, there is the option to configure _Entries per page_ (10, 20, 50, 100).

It would be nice to have the same feature in the Media Library.

Nonetheless the new Media Library is awesome!  :rocket: 

Thank you!

**Comment by lauriejim** [comment]
Hello! It's already possible nop ?

I have the pagination and the entries per pages in the screen bellow.

<img width="2667" alt="Screen Shot 2020-05-19 at 12 52 17 PM" src="https://user-images.githubusercontent.com/5716596/82318110-98428e00-99cf-11ea-9e73-2fa69d251a56.png">

**Comment by omgMath** [comment]
Sorry, I was a little unclear. I was talking about the default value (in this case 10).

Like in the _Collection Types_, e.g. for User:
![image](https://user-images.githubusercontent.com/24620670/82320758-199c1f80-99d4-11ea-8e47-6844a03d52d3.png)

Here we can use another vale as default:
![image](https://user-images.githubusercontent.com/24620670/82320889-48b29100-99d4-11ea-83af-1b712140c58f.png)

It would be nice to have the same for the Media Library.

**Comment by lauriejim** [comment]
Ho thank you for the precision.
You are right it could be cool / useful to have this.
Sadly it's not in our prio for now.
This feature requires design and some specification because it's not exactly the same as in the content manager.
I ping @Aurelsicoko about this.
Let me know if you want to develop it.

**Comment by omgMath** [comment]
Hi.
Thanks for the feedback. I agree that this is a low priority.
My backlog is quite full at the moment, but should I have more time at some point, I'll see what I can do.
Cheers

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/entries-per-page-how-to-change-default-value/6650/2

**Comment by dallasclark** [comment]
+1 on this feature

**Comment by jhoward1994** [comment]
Hi all, this feature has been implemented in https://github.com/strapi/strapi/releases/tag/v4.5.5
