### ISSUE TITLE
SQLITE_ERROR: duplicate column name: ID

### ISSUE THREAD

**Issue by litehacker** [strapi/strapi#6184]
This is a bug report. It happened when I add ID variable in a content data like Users for example. It when you save, project won't complete its restart, because the server won't start again. The reason is that the ID was a duplicate.

Reproduce the behavior:
1) Clone Repo,
2) Create a quick project
3) Add a new SHORT string in a content type
4) Name ID, in advanced mark private and unique variable (cz somebody might not know that they are duplicating)
5) Save it.
`Server wasn't able to start properly.
error Error: SQLITE_ERROR: duplicate column name: ID`
-------------------

**System**

- Node.js version: v13.8.0
- NPM version: 6.14.5
- Strapi version: latest
- Database: Guess SQLite (anything default what comes along with Strapi)
- Operating system: Catalina

**Comment by derrickmehaffy** [comment]
`Strapi version: latest` Please specify `latest` as I was just testing another bug and Strapi certainly blocks creation of fields using `id` as a name in beta.20.3

**Comment by derrickmehaffy** [comment]
On a side note, not directly related to this: `Node.js version: v13.8.0` That is not a supported version of node.

**Comment by derrickmehaffy** [comment]
Indeed I was able to reproduce on beta.20.3 :thinking: that shouldn't be possible as the CTB has a specific route that references this:

```
[2020-05-13T16:59:31.710Z] error Error: SQLITE_ERROR: duplicate column name: id
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-id@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-id@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dmehaffy/.npm/_logs/2020-05-13T16_59_31_720Z-debug.log
```

@soupette, is this something that is only in the rc.0+?

**Comment by lauriejim** [comment]
Hello! thank you for this issue; This has already been reported but I'm not able to find where.

Ping @alexandrebodin and @soupette about this topic.
About restriction of some names, in the admin and in the command line generators.

**Comment by litehacker** [comment]
Should be there any solution for me to avoid recreation of the project from the beginning, but fix with a command line?

**Comment by calvinf** [comment]
In my case, I had created a Content Type called `list` and gave it an `id` field that used `uuid` type.  It seems this conflicts with a default id value that is given to a content type by Strapi (unless this is something specific to the sqlite code)?  In any case, I was able to run `npm run develop` again after editing `api/list/models/list.settings.json` and removing the `id` field from it.

**Comment by derrickmehaffy** [comment]
@litehacker @calvinf you are correct, directly modifying the model settings file and removing the field with the issue will allow you to restart.

In the new stable release (and the rc.x releases for testing) there is an API that prevents users from creating new fields with the name `id` (among others).

As a side point @calvinf in the stable, support for changing the `id` name and data type is being removed until it can be reviewed at a later date. For the moment it breaks far too much.

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed, as it has already been fixed and will be released in the stable version. (already released in the rc.x versions)

**Comment by wesbos** [comment]
If anyone is still getting this, update knex:

`"knex": "^0.21.5",`

**Comment by davicyyo** [comment]
> If anyone is still getting this, update knex:
> 
> `"knex": "^0.21.5",`

Fixed!

with the intention of clarifying:

`npm update knex`  and fix for me.
