### ISSUE TITLE
Relations returning array of ID's and not an array of objects as expected. 

### ISSUE THREAD

**Issue by altaygileren** [strapi/strapi#6186]
**Describe the bug**
I create a relationship between the user and the collection type.. when I create the relationship I set "User has many Tweets".. when I go to create a "Tweet" it doesn't show a field for relation to users so I manually create that relationship again for "Tweets" as "Tweet has one user".. after I create a "Tweet" I GET the user from users/me and I get back an array of ID's instead of an array of objects like it used to be. 

**Expected behavior**
I expect the users/me query to return back an array of objects for the users/me request for Tweets.

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 20.3
- Database: MongoDB Atlas
- Operating system: Mac

**Comment by derrickmehaffy** [comment]
This is intended and was changed in https://github.com/strapi/strapi/pull/4540

Marking this as closed for now, but you can read through the PR and use extensions to change the populate method in your project to add back the relationship populate.

This change was made from a security standpoint

**Comment by insivika** [comment]
@altaygileren did you figure out a solution for this?

**Comment by derrickmehaffy** [comment]
@insivika you'll need to use our extensions system and modify the population (default is only the role relation) here: https://github.com/strapi/strapi/blob/d5049777ead948e1041690f8c88772423603959a/packages/strapi-plugin-users-permissions/services/User.js#L71-L77
