### ISSUE TITLE
Would strapi work for a multisite approach ? 

### ISSUE THREAD

**Issue by victorkurauchi** [strapi/strapi#619]
Hi guys, i'm using strapi on a new project and so far it's being a good experience.

**Do you want to request a *feature* or report a *bug*?**
I was thinking about a different scenario, where we could have something similar to the drupal multisite (https://www.drupal.org/docs/7/multisite/multi-site-sharing-the-same-code-base)

Scenario: We have a client that wants do build a few sites, but the team who manage the content is the same for all sites. (around 8 people for 30 websites). I'm not so sure if multisite would be the best. But do you guys have a good idea about how could i accomplish this goal with Strapi ?

- Have you guys discussed about it before ? 
- Would that be interesting for Strapi ?
- Currently the strapi source does not support multisite, right ?
- Would be possible to have one login for different strapi instances ? (example: 1 login for 3 different heroku strapi applications)

Thanks!

**Comment by lauriejim** [comment]
The difference between your 30 websites is just about the front-end part ? But have the same API and data ?

**Comment by Aurelsicoko** [comment]
@victorkurauchi Thank you for the suggestion! I'm pretty sure we will head to this kind of feature in the future. I don't see any problem to implement it. However, it's clearly not a priority for us right now.

To be more precise, in your description you talk about 1 login for 3 different applications. It means that you need to have a main API to manage the authentication for everyone or having the same database for all the APIs. It seems to be the more difficult thing in your case. I don't any idea how to implement it but our friends at Drupal already resolved it so maybe we could take a deeper look and find the inspiration there.

**Comment by xstable** [comment]
I'm also looking for a solution like that, but with a Database which is splitted up for each client.
So authentication, providing api and other stuff might be on the "main-db" of strapi, but each Customer-Data Tables should be able to go in a seperated / connected Database (maybe on external mongodb)
