### ISSUE TITLE
UID field cannot be set private

### ISSUE THREAD

**Issue by kueronya** [strapi/strapi#6204]
**Describe the bug**
The UID field is missing the private setting in advanced settings.

**Steps to reproduce the behavior**

1. Create an UID field
2. Go to advanced settings
3. Only required, max and min settings are available

**Expected behavior**
It should be possible to set an UID field private

**Screenshots**
![strapi-uid-private](https://user-images.githubusercontent.com/5357444/81900280-c6356600-95bc-11ea-8a49-923af9f8bcc1.PNG)

**System**

- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: v3.0.0-beta.20.1
- Database: Mysql 5.6
- Operating system: Win10

**Comment by derrickmehaffy** [comment]
Can you test doing so via the model settings? (wondering if this is a frontend/backend issue or just frontend)

**Comment by kueronya** [comment]
> Can you test doing so via the model settings? (wondering if this is a frontend/backend issue or just frontend)

Setting private in model json works as expected. It's just missing in the view.

**Comment by derrickmehaffy** [comment]
@soupette @virginieky was where a reason private was not an option in the frontend?

**Comment by soupette** [comment]
> @soupette @virginieky was where a reason private was not an option in the frontend?

Not it was just something we forgot to add.

**Comment by soupette** [comment]
The PR has been merged should we close this issue @lauriejim ?

**Comment by derrickmehaffy** [comment]
Marking as closed since the PR was merged.
