### ISSUE TITLE
AWS S3 Option in Strapi@3.0.0-beta.20.3

### ISSUE THREAD

**Issue by realabbas** [strapi/strapi#6206]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

There is no option for AWS S3 upload image, only local upload is available in the new version of strapi. Previously the plugin was File Upload but the new one Media Library doesn't have AWS S3 Support. 
Am I missing something or is it yet to be integrated?

![image](https://user-images.githubusercontent.com/43527087/81938034-007d2280-9612-11ea-8200-0ef772b3daed.png)

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider

**Comment by realabbas** [comment]
Thanks. @derrickmehaffy
