### ISSUE TITLE
Can't Save Default language as zh_Hant_HK in Setting Manager

### ISSUE THREAD

**Issue by wingsiu** [strapi/strapi#621]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.9.2

**Operating system**: OSX 10.13.3

report a *bug*?**

**What is the current behavior?**
Can't Save Default language as zh_Hant_HK in Setting Manager
the following error is shown in safari console: 
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "target": "language.defaultLocale",
            "messages": [
                {
                    "id": "request.error.type.select"
                }
            ]
        }
    ]
}
**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by soupette** [comment]
Hi I need to make a hot fix for that. However, for the time being could you go to your app folder
modify the `language.json`file (`/my-app/config/language.json`) and  change the `defaultLocale` key as follows:

```json

{
  "enabled": true,
  "defaultLocale": "zh_Hant_HK",
  "modes": [
    "query",
    "subdomain",
    "cookie",
    "header",
    "url",
    "tld"
  ],
  "cookieName": "locale"
}
```
