### ISSUE TITLE
Can't save config for custom mail provider

### ISSUE THREAD

**Issue by NuclleaR** [strapi/strapi#6216]
Hello!

I've created custom email provider

```
module.exports = {
  provider: "local",
  name: "Local provider",
  auth: {
    default_from: {
      label: "Default from",
      type: "text"
    },
    host: {
      label: "Host",
      type: "text"
    },
    port: {
      label: "port",
      type: "text"
    },
    username: {
      label: "Username",
      type: "text"
    },
    password: {
      label: "Password",
      type: "text"
    }
  },
  ...
};
```

when I open /admin/plugins/email/configurations/development
I can see all this fields
but if I want to save config PUT request 
`/email/settings/development` to update config is incorrect. All my field are missing
request body is empty

**System**
- Node.js version: v14.0.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.3
- Database: postgres
- Operating system: Mac OS 10.15.5

**Comment by lauriejim** [comment]
Hello! Did you followed this documentation?

https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#create-new-provider
