### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object

### ISSUE THREAD

**Issue by kvbalib** [strapi/strapi#6219]
I'm trying to make the app send an e-mail using built-in provider on POST message type (api/message/controllers/message.js). I altered native create function. It adds the object correctly to the database, the POST request keeps on processing and after a while it throws this error:

```
AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at Function.boomify (node_modules/boom/lib/index.js:107:14)
      at formatBoomPayload (node_modules/strapi/lib/middlewares/boom/index.js:47:22)
      at node_modules/strapi/lib/middlewares/boom/index.js:84:36
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Then the server restarts. I've tried this on production server - it acts the same. I've also rebuilt the app clean, to rule out conflicts factor.

**Expected behavior**
The app was suppose to send an email on POST request with the content of the new item.

**Code snippets**

```
const { parseMultipartData, sanitizeEntity } = require('strapi-utils');

module.exports = {
  async create(ctx) {
    let entity;
    if (ctx.is('multipart')) {
      const { data, files } = parseMultipartData(ctx);
      entity = await strapi.services.message.create(data, { files });
    } else {
      entity = await strapi.services.message.create(ctx.request.body);
    }

    const messageObj = sanitizeEntity(entity, { model: strapi.models.message });

    const recipient = await strapi.query('user', 'users-permissions').findOne({email: messageObj.recipient});

    console.log(recipient);
    console.log(messageObj);

    await strapi.plugins['email'].services.email.send({
      to: 'info@orb2.space',
      from: messageObj.message,
      replyTo: messageObj.email,
      subject: `orb2 | wiadomość od ${messageObj.name}`,
      text: messageObj.message,
      html: null,
    });

    return messageObj;
  },
};

```

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: MySQL
- Operating system: OSX 10.15.4

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
