### ISSUE TITLE
Model toObject() is not a function

### ISSUE THREAD

**Issue by dodo007** [strapi/strapi#6220]
Strapi 3.0.0-beta.20.3 (node v12.16.3)

I tried multiple times and multiple ways to work with Models but whatever I try I get back the toObject is not a function.

const result = strapi.query('customer').model.find({
  date: { $gte: '2019-01-01T00.00.00Z' },
});

const fields = result.toObject();

I tried using the exact same example from the documentation just changed the model name.

If someone can clarify the issue that would be great. 

I also tried using toObject() on the count query example

const result = strapi.services.packages.count({user})
const fields = result.toObject();

I get back the toObject is not a function.

 Query {
  _mongooseOptions: { populate: {} },
  _transforms: [],
  _hooks: Kareem { _pres: Map {}, _posts: Map {} },
  _executionCount: 0,
  mongooseCollection: NativeCollection {
    collection: Collection { s: [Object] },
    Promise: [Function: Promise],
    opts: {
      bufferCommands: true,
      capped: false,
      Promise: [Function: Promise],
      '$wasForceClosed': undefined
    },
    name: 'packages',
    collectionName: 'packages',
    conn: NativeConnection {
      base: [Mongoose],
      collections: [Object],
      models: [Object],
      config: [Object],
      replica: false,
      options: null,
      otherDbs: [],
      relatedDbs: {},
      states: [Object: null prototype],
      _readyState: 1,
      _closeCalled: false,
      _hasOpened: true,
      plugins: [],
      _listening: false,
      _connectionOptions: [Object],
      '$dbName': 'coach',
      name: 'coach',
      host: '127.0.0.1',
      port: 27017,
      user: undefined,
      pass: undefined,
      client: [MongoClient],
      '$initialConnection': [Promise],
      db: [Db]
    },
    queue: [],
    buffer: false,
    emitter: EventEmitter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      [Symbol(kCapture)]: false
    }
  },
  model: Model { packages },
  schema: Schema {
    base: Mongoose {
      connections: [Array],
      models: [Object],
      modelSchemas: [Object],
      options: [Object],
      _pluralize: [Function: pluralize],
      Schema: [Function],
      plugins: [Array],
      mongoDBVersion: '2.6.10'
    },
    obj: {
      name: [Object],
      trial: [Object],
      price: [Object],
      defaultPackage: [Object],
      user: [Object]
    },
    paths: {
      name: [SchemaString],
      trial: [SchemaNumber],
      price: [Float],
      defaultPackage: [SchemaBoolean],
      user: [ObjectId],
      _id: [ObjectId],
      updatedAt: [SchemaDate],
      createdAt: [SchemaDate],
      __v: [SchemaNumber]
    },
    aliases: {},
    subpaths: {},
    virtuals: { id: [VirtualType] },
    singleNestedPaths: {},
    nested: {},
    inherits: {},
    callQueue: [],
    _indexes: [],
    methods: { initializeTimestamps: [Function] },
    methodOptions: {},
    statics: {},
    tree: {
      name: [Object],
      trial: [Object],
      price: [Object],
      defaultPackage: [Object],
      user: [Object],
      _id: [Object],
      updatedAt: [Function: Date],
      createdAt: [Function: Date],
      __v: [Function: Number],
      id: [VirtualType]
    },
    query: {},
    childSchemas: [],
    plugins: [ [Object], [Object], [Object], [Object], [Object] ],
    '$id': 9,
    s: { hooks: [Kareem] },
    _userProvidedOptions: { timestamps: true, minimize: false },
    options: {
      typePojoToMixed: true,
      typeKey: 'type',
      id: true,
      noVirtualId: false,
      _id: true,
      noId: false,
      validateBeforeSave: true,
      read: null,
      shardKey: null,
      autoIndex: null,
      minimize: false,
      discriminatorKey: '__t',
      versionKey: '__v',
      capped: false,
      bufferCommands: true,
      strict: true,
      timestamps: true,
      toJSON: [Object],
      toObject: [Object],
      pluralization: true
    },
    '$timestamps': { createdAt: 'createdAt', updatedAt: 'updatedAt' },
    '$globalPluginsApplied': true
  },
  op: 'countDocuments',
  options: {},
  _conditions: { '$and': [ [Object] ] },
  _fields: undefined,
  _update: undefined,
  _path: undefined,
  _distinct: undefined,
  _collection: NodeCollection {
    collection: NativeCollection {
      collection: [Collection],
      Promise: [Function: Promise],
      opts: [Object],
      name: 'packages',
      collectionName: 'packages',
      conn: [NativeConnection],
      queue: [],
      buffer: false,
      emitter: [EventEmitter]
    },
    collectionName: 'packages'
  },
  _traceFunction: undefined,
  '$useProjection': true,
  count: [Function: count]
}

Maybe I'm doing something wrong.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by dodo007** [comment]
**System**

Operating system: Ubuntu 16.04
Database: MongoDB 2.6.10
Strapi version: Strapi 3.0.0-beta.20.3
Node v12.16.3
NPM 6.14.4

**Code example**

First example

const result = strapi.query('customer').model.find({
date: { $gte: '2019-01-01T00.00.00Z' }
});

const fields = result.toObject();

**additional: example which I do not know if it is supposed to work or not but I guess it should 

const result = strapi.services.packages.count({user})
const fields = result.toObject();

I get back the toObject is not a function so the same result as on the other function.

**Behaviour**
I tried using the exact same example from the documentation just changed the model name.

**Expected**

I should have received the object of the model back.

**Steps to reproduce the behavior**

Recreate any model and try to execute any query that is custom-built like the one in the **Code example**

**Comment by Moizsohail** [comment]
Any solution?

**Comment by derrickmehaffy** [comment]
> Any solution?

In this case you don't actually need to use `.toObject()` and just need to make the query an async/await

**Comment by dodo007** [comment]
await strapi.query.('model name').model.find({ use your query parameters })

The example in the docs is showing something different that does not work
at all. In the parameters, you can't use any of the strapi filters like
_limit, _contains.... You need mongo syntax.

Robert Lovreković

**Comment by derrickmehaffy** [comment]
Ah yup I missed that, you are directly using the mongoose .model. :thinking: @alexandrebodin are our docs out of date here?

https://strapi.io/documentation/v3.x/concepts/queries.html#mongoose

```
const result = strapi.query('restaurant').model.find({
  date: { $gte: '2019-01-01T00.00.00Z' },
});

const fields = result.toObject();
```

It does reference `.toObject()`

**Comment by derrickmehaffy** [comment]
Just tested on a latest release Strapi v3.1.3 and the `.toObject()` does throw an error but is not needed anyway: 
![image](https://user-images.githubusercontent.com/8593673/89831333-88d86a00-db12-11ea-95ac-8ee9ab2abdef.png)

**Comment by alexandrebodin** [comment]
toObject is for single enties indeed so `results.map(entry => entry.toObject())`
