### ISSUE TITLE
make integration with nx.dev monorepo and angular cli builders possible

### ISSUE THREAD

**Issue by fxck** [strapi/strapi#6221]
I'm trying to integrate strapi into nx monorepo. In theory it should be possible, in reality, not so much. There are two main problems:

1) strapi cli expects package.json to be on the same level as your strapi app
2) there's no way to defined output path for production build

With nx monorepo, your project structure looks something like this

![image](https://user-images.githubusercontent.com/1303561/82044164-1ee42c00-96ad-11ea-8fbe-ab4a57bf2648.png)

and you want your build to end up in `/dist`.

If only you could pass optional `--dir`, `--root` and `--outputPath` options to `strapi develop` / `strapi build` and take those in consideration instead of hardcoding those paths, it should all work fine.

Thoughts?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
