### ISSUE TITLE
Language file names Mac OS issue

### ISSUE THREAD

**Issue by backnight** [strapi/strapi#6224]
**Describe the bug**
in config/locales/ there are filenames with the same name with and without caps:
de_de.json
de_DE.json
en_us.json
en_US.json
...

Mac doesn't support same filenames with caps and no caps, causing a bug with the translations as the system only see one of the two files.
https://www.informit.com/articles/article.aspx?p=1144082&seqNum=4

**Steps to reproduce the behavior**
install Strapi on Mac OS

**System**
- Operating system: Mac OS Catalina 10.15.4 (the latest version of Mac OS)

**Comment by derrickmehaffy** [comment]
I'm not sure where you are seeing that because none of those files exist in the mono-repo: https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src/translations

Where are you referring and what Strapi version are you trying to use?

**Comment by backnight** [comment]
Hmmm, I'm currently using Strapi v3.0.0-beta.16.3
My issue is related with Strapi (post install) but not with this repository code I think.

I have a config/ folder in which there is locales/

This is what I have when I run a tree command in my Strapi project (I excluded some unnecessary folders from the ouput):
```
.
├── config
│   ├── application.json
│   ├── custom.json
│   ├── environments
│   │   ├── development
│   │   │   ├── custom.json
│   │   │   ├── database.json
│   │   │   ├── request.json
│   │   │   ├── response.json
│   │   │   ├── security.json
│   │   │   └── server.json
│   │   ├── production
│   │   │   ├── custom.json
│   │   │   ├── database.json
│   │   │   ├── request.json
│   │   │   ├── response.json
│   │   │   ├── security.json
│   │   │   └── server.json
│   │   └── staging
│   │       ├── custom.json
│   │       ├── database.json
│   │       ├── request.json
│   │       ├── response.json
│   │       ├── security.json
│   │       └── server.json
│   ├── functions
│   │   ├── bootstrap.js
│   │   ├── cron.js
│   │   └── responses
│   │       └── 404.js
│   ├── hook.json
│   ├── language.json
│   ├── locales
│   │   ├── de_de.json
│   │   ├── de_DE.json
│   │   ├── en_us.json
│   │   ├── en_US.json
│   │   ├── es_es.json
│   │   ├── es_ES.json
│   │   ├── fr_fr.json
│   │   ├── fr_FR.json
│   │   ├── it_it.json
│   │   ├── it_IT.json
│   │   ├── ja_jp.json
│   │   ├── ja_JP.json
│   │   ├── ru_ru.json
│   │   ├── ru_RU.json
│   │   ├── tr_tr.json
│   │   └── tr_TR.json
│   └── middleware.json
├── Dockerfile
├── favicon.ico
├── package.json
├── README.md
└── strapi.sh
```

**Comment by lauriejim** [comment]
Hello, I just created a new app and here are my files in the config local folder.

<img width="449" alt="Screen Shot 2020-05-22 at 1 14 23 PM" src="https://user-images.githubusercontent.com/5716596/82662499-4186bf80-9c2e-11ea-9637-644ec5c9f486.png">

I don't know why you have 2 files for each language.

**Comment by backnight** [comment]
Is there a way to force Strapi to rebuild this folder?
I deleted some files in it and they were rebuilt few moment later so I deleted everything and now nothing is happening ahah

**Comment by lauriejim** [comment]
Hello, I'm not sure to understand.
These files are generated during the project creation and not on the server start.

**Comment by backnight** [comment]
Okay, I will setup a new test project and copy the locales/ folder into my project. Maybe this problem is due to an old version of Strapi (my project was setup a long time ago and I did a lot of migrations for each new Strapi releases, maybe I fucked up something).
