### ISSUE TITLE
Email plugins not working

### ISSUE THREAD

**Issue by jsaguiar** [strapi/strapi#6228]
**Describe the bug**
Try to installed different email plugin but all of them failed

`strapi_1  | [2020-05-15T17:32:22.659Z] error Bootstrap function in plugin "email" failed-strapi_1  | [2020-05-15T17:32:22.661Z] error Error: Cannot find module 'strapi-provider-email-sendgrid'
`

**Steps to reproduce the behavior**

1. npm install strapi-provider-email-sendgrid
2. npm run develop

**Expected behavior**
Should work 

**System**

- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version:  3.0.0-beta.20.3",
- Database :poastgres
- Operating system: macos - docker alpine

**Comment by derrickmehaffy** [comment]
Please provide your `package.json`

**Comment by jsaguiar** [comment]
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "strapi",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "axios": "^0.19.2",
    "knex": "<0.21.1",
    "pg": "8.2.0",
    "strapi": "3.0.0-beta.20.3",
    "strapi-admin": "3.0.0-beta.20.3",
    "strapi-connector-bookshelf": "3.0.0-beta.20.3",
    "strapi-plugin-content-manager": "3.0.0-beta.20.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.3",
    "strapi-plugin-email": "3.0.0-beta.20.3",
    "strapi-plugin-graphql": "^3.0.0-beta.20.3",
    "strapi-plugin-upload": "3.0.0-beta.20.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.3",
    "strapi-provider-email-sendgrid": "^3.0.0-beta.20.3",
    "strapi-provider-email-ses": "^0.1.1",
    "strapi-utils": "3.0.0-beta.20.3",
    "uuid": "^8.0.0"
  },
  "author": {
    "name": ""
  },
  "strapi": {
    "uuid": "780f3419-b354-454f-aa9c-c1f9b9b507e7"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

**Comment by jsaguiar** [comment]
somehow I was able to overcome this! not sure what caused it and how I fix it. 
I clean up everything, including my docker images

Sorry to bother you guys!

**Comment by NuclleaR** [comment]
I faced with the same (or maybe not) issue
I created a custom email plugin

```
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "latest",
    "strapi": "3.1.3",
    "strapi-admin": "3.1.3",
    "strapi-connector-bookshelf": "3.1.3",
    "strapi-plugin-content-manager": "3.1.3",
    "strapi-plugin-content-type-builder": "3.1.3",
    "strapi-plugin-email": "3.1.3",
    "strapi-plugin-upload": "3.1.3",
    "strapi-plugin-users-permissions": "3.1.3",
    "strapi-provider-email-custom": "file:providers/strapi-provider-email-custom",
    "strapi-utils": "3.1.3"
  },
```

and receive a bootstrap error
`error Bootstrap function in plugin "email" failed
error Error: The provider package isn't installed. Please run `npm install strapi-provider-email-custom` --save`

**Comment by NuclleaR** [comment]
I managed to resolve the issue
my issue was that I have a bug in my code and run fails. but there is the problem in source code
```
try {
    provider = require(`strapi-provider-email-${providerName}`);
  } catch (err) {
    throw new Error(
      `The provider package isn't installed. Please run \`npm install strapi-provider-email-${providerName}\` --save`
    );
  }
```

in this case, if you have an issue like it was with, can not read property `x` of undefined, you lose all stack trace. I believe better to return exceptions that fail, instead of creating new one, because it's really unclear what is going on
