### ISSUE TITLE
Content Type with Multiple Relation Fields has weird behavior

### ISSUE THREAD

**Issue by bogdancrisu** [strapi/strapi#623]
**Node.js version**:
9.5.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.9

**Operating system**:
OSX

I have a Content-Type "Cars" with Multiple Relation Fields, two of them are many to many and one is one to many, as soon as I delete an entry "Combustible" from the one to many relation, the other relations are empty after the save action, before the save action both of them had a value assigned.

**Comment by lauriejim** [comment]
Can you be more precise with your models definition. The best wait to be able to help you is to share your 4 models. It's will be more easy to reproduce your issue.

**Comment by lauriejim** [comment]
No news about that, I close this issue :)
