### ISSUE TITLE
Quickstart lead to 404 page not found.

### ISSUE THREAD

**Issue by RinaldoBenaccetta** [strapi/strapi#6234]
**Describe the bug**
When install a new project, like explainded in quickstart guide, the admin page lead to a 404 page.

**Steps to reproduce the behavior**
1. npx create-strapi-app my-project --quickstart
2. installation and build work.
3. The Strapi process open localhost:1337/admin
4. The page displays *404 page not found*

**Expected behavior**
Opening properly the admin page.

**System**
- Node.js version: 12.16.3
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database:
- Operating system: windows 10 (64bits)

**Additional context**
Here is the html of the 404 page :

```
<head>

    <link rel="stylesheet" href="resource://content-accessible/plaintext.css">

</head>

<body>

    <pre>

        404 page not found

    </pre>

</body>
```

**Comment by derrickmehaffy** [comment]
It looks like your build didn't complete? Can you try to navigate to the project root and run `yarn build` or `npm run build`

I was not able to reproduce this on beta.20.3

**Comment by RinaldoBenaccetta** [comment]
I changed just now the port on staging and environment, from 1337 to 8000.
That solved the problem.
