### ISSUE TITLE
Can't see media library

### ISSUE THREAD

**Issue by filipesmedeiros** [strapi/strapi#6237]
**Describe the bug**

When I click on Media library, the pop up for "Error occurred" shows up, and no media is shown.

**Steps to reproduce the behavior**

(Not sure)
1. Upload image (maybe svg?)
2. Create single type called "Home page"
3. Go to Media library

**Expected behavior**
Should see normal media library

**Screenshots**
![image](https://user-images.githubusercontent.com/26208850/82145020-baa5a180-983f-11ea-8dc8-81959c8ce12c.png)

**Code snippets**
```shell
error Error: The target polymorphic type "home_pages" is not one of the defined target types
    at Object.morphCandidate (D:\Better\better-website\cms\node_modules\bookshelf\lib\helpers.js:140:13)
    at D:\Better\better-website\cms\node_modules\bookshelf\lib\eager.js:52:15
    at D:\Better\better-website\cms\node_modules\lodash\lodash.js:13401:38
    at D:\Better\better-website\cms\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (D:\Better\better-website\cms\node_modules\lodash\lodash.js:2990:24)
    at Function.mapValues (D:\Better\better-website\cms\node_modules\lodash\lodash.js:13400:7)
    at EagerRelation.morphToFetch (D:\Better\better-website\cms\node_modules\bookshelf\lib\eager.js:51:28)
    at EagerRelation.eagerFetch (D:\Better\better-website\cms\node_modules\bookshelf\lib\eager.js:25:19)
    at EagerRelation.<anonymous> (D:\Better\better-website\cms\node_modules\bookshelf\lib\base\eager.js:67:14)
    at EagerRelation.tryCatcher (D:\Better\better-website\cms\node_modules\bluebird\js\release\util.js:16:23)
    at EagerRelation.fetch (D:\Better\better-website\cms\node_modules\bluebird\js\release\method.js:15:34)
    at D:\Better\better-website\cms\node_modules\bookshelf\lib\eager.js:96:73
    at tryCatcher (D:\Better\better-website\cms\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (D:\Better\better-website\cms\node_modules\bluebird\js\release\method.js:39:29)
    at EagerRelation._eagerLoadHelper (D:\Better\better-website\cms\node_modules\bookshelf\lib\eager.js:83:23)
    at Sync.<anonymous> (D:\Better\better-website\cms\node_modules\bookshelf\lib\eager.js:31:31)
[2020-05-17T12:04:44.732Z] debug GET /upload/files?_limit=10&_start=0&_sort=updated_at:DESC (21 ms) 500
```

**System**

- Node.js version: 13.11.0 (Currently using 64-bit executable)
- NPM version: 6.14.3
- Yarn version: 1.22.4
- Strapi version: Latest
- Database: SQLite
- Operating system: Windows 10 64 bit

**Additional context**
Although the table name for Home page is `home_pages`, the folder created in the `api` folder is named `home-page`. Don't know if it's related.

**Comment by derrickmehaffy** [comment]
`Strapi version: Latest` please actually provide the version. "Latest" doesn't tell me anything.

Also node v13 is not supported.

Likewise can you please provide me with your package.json as I have the feeling you have mixed versions

**Comment by yagotome** [comment]
I'm facing the same problem here running on `node v12.16.3` and `Strapi v3.0.0-beta.20.3`. My OS is `Ubuntu 18.04.4` and I use `postgres v12.2`.

My `package.json`:

```json
{
    ...
    "devDependencies": {},
    "dependencies": {
      "knex": "<0.20.0",
      "pg": "^8.2.0",
      "sqlite3": "latest",
      "strapi": "3.0.0-beta.20.3",
      "strapi-admin": "3.0.0-beta.20.3",
      "strapi-connector-bookshelf": "3.0.0-beta.20.3",
      "strapi-plugin-content-manager": "3.0.0-beta.20.3",
      "strapi-plugin-content-type-builder": "3.0.0-beta.20.3",
      "strapi-plugin-email": "3.0.0-beta.20.3",
      "strapi-plugin-graphql": "3.0.0-beta.20.3",
      "strapi-plugin-upload": "3.0.0-beta.20.3",
      "strapi-plugin-users-permissions": "3.0.0-beta.20.3",
      "strapi-provider-upload-google-cloud-storage": "3.0.0-beta.20.3",
      "strapi-utils": "3.0.0-beta.20.3"
    },
    "engines": {
      "node": ">=10.0.0",
      "npm": ">=6.0.0"
    }
    ...
}
```

**Comment by yagotome** [comment]
I solved it here! The problem here was that [Strapi Content Type Builder plugin](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-type-builder) didn't delete file references from `upload_file_morph` when I removed a file field from my Content Type. So running `delete from upload_file_morph where field='dropped_file_field' and related_type='my_content_type';` solved the problem.

However, that plugin should do this delete operation for us, souldn't it? @derrickmehaffy

**Comment by filipesmedeiros** [comment]
@derrickmehaffy Sorry, here you go. I'll also switch to Npm 12 (although it seems not to be the problem)

![image](https://user-images.githubusercontent.com/26208850/82159027-7b00a900-9883-11ea-96f7-ffd954bf492d.png)

**Comment by derrickmehaffy** [comment]
@filipesmedeiros you have far too many various node versions. Between a mix of beta.20.1 and beta.20.3. When it comes to core Strapi packages (those built by Strapi) all versions should be the same, as each release updates all plugins regardless of changes. 

Included in that you should not have any `^` or `~` in those packages as currently (until Strapi goes stable) npm can accidentally pull from other "tagged" releases and not just the "beta" tags. In your case I see two issues related to this.

```
"strapi-plugin-graphql": "^3.0.0-beta.20.1"
"strapi-provider-upload-cloudinary": "^3.0.0-beta.20.3"
```

And again all these should be the same version `3.0.0-beta.20.3`, after you have updated the packages please delete `node_modules`, `package-lock.json`, `yarn.lock`, `.cache`, and `build` and reinstall/rebuild. Likewise if you are migrating to beta.20.x from any previous version you should read through the [migration guides](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/) specifically about provider configs being moved to files (they will no longer show in the admin)

**Comment by derrickmehaffy** [comment]
> I solved it here! The problem here was that [Strapi Content Type Builder plugin](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-type-builder) didn't delete file references from `upload_file_morph` when I removed a file field from my Content Type. So running `delete from upload_file_morph where field='dropped_file_field' and related_type='my_content_type';` solved the problem.
> 
> Anyway, that plugin should do this delete operation for us, souldn't it? @derrickmehaffy

I am not entirely sure I follow the issue chain here :thinking: I believe that Strapi already addressed the cascading delete issue from before. Can you break down the steps to reproduce for me?

**Comment by tonoli** [comment]
I had the same issue. 
- Create a Single Type called "hero"
- Add Madia Field to it
- Delete the type called "hero"
- Then got the error: `error Error: The target polymorphic type “heroes” is not one of the defined target types`

Solved: 
- Delete the related uploded files
- On psql terminal `delete from upload_file_morph where related_type='heroes'`

**Comment by lauriejim** [comment]
Closing in favor of this one - https://github.com/strapi/strapi/issues/6347
Thank you for reporting this issue.
