### ISSUE TITLE
To Avoid Duplicate field name when designing  or  UPDATING 

### ISSUE THREAD

**Issue by Shadow-Boxer** [strapi/strapi#6243]
I Corrupted Strapi.  I was changing a name of one of the field names and accidentally used 
the same name already in use.  Did not get a warning message.   And now have to rebuild
from scratch.  ( not a big deal but could be if it was larger)

- [ 
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

**Comment by derrickmehaffy** [comment]
@Shadow-Boxer can you please open this as a bug report (on a side note, you can quickly fix this issue by changing the field name in the `api/modelName/models/modelName.settings.json` file)

Will mark this one as closed but please do open a valid bug report, following the bug report template so it can be addressed. Thank you!
