### ISSUE TITLE
Strapi CLI unable to connect to Mongo Altas Cluster running on GCP

### ISSUE THREAD

**Issue by madudding** [strapi/strapi#6244]
**Describe the bug**
executing strapi new command fails to connect to Mongo Atlas cluster on Google Cloud Platform.
```

? Choose your default database client mongo
? Database name: raft-backend
? Host: @cluster0-i6dcv.gc
? +srv connection: true
? Port (It will be ignored if you enable +srv): 27017
? Username: _{redacted}_
? Password: ******************
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: No

⛔️ Connection test failed: **URI does not have hostname, domain name and tld**
```

**Steps to reproduce the behavior**
1. Provision free tier Mongo Atlas cluster running on Google Cloud Patform.
2. Open firewall access providing your IP address
3. get connection string - here is what mine is:

```
const MongoClient = require('mongodb').MongoClient;
const uri = "mongodb+srv://_{redacted}_:<password>@cluster0-i6dcv.gcp.mongodb.net/test?retryWrites=true&w=majority";
const client = new MongoClient(uri, { useNewUrlParser: true });
client.connect(err => {
  const collection = client.db("test").collection("devices");
  // perform actions on the collection object
  client.close();
});
```

`⛔️ Connection test failed: **URI does not have hostname, domain name and tld**`

**Expected behavior**
The app has been connected to the database successfully!  

**Screenshots**

**Code snippets**

**System**

- Node.js version:  v14.2.0
- NPM version: 6.14.5
- Strapi version: 

`"strapi": "3.0.0-beta.20.3"`

- Database: mongoDB
- Operating system:  Darwin Marks-MBP.home 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Additional context**
The error alludes to the issue the "URI does not have hostname, **domain name and tld**". It is in the the form **host.gc**

**Note:** I'm able to connect with mongo CLI 

```
mongo "mongodb+srv://cluster0-i6dcv.gcp.mongodb.net/test" --username _{redacted}_
MongoDB shell version v4.2.0
Enter password:
connecting to: mongodb://cluster0-shard-00-00-i6dcv.gcp.mongodb.net:27017,cluster0-shard-00-01-i6dcv.gcp.mongodb.net:27017,cluster0-shard-00-02-i6dcv.gcp.mongodb.net:27017/test?authSource=admin&compressors=disabled&gssapiServiceName=mongodb&replicaSet=Cluster0-shard-0&ssl=true
2020-05-18T01:47:16.394-0500 I  NETWORK  [js] Starting new replica set monitor for Cluster0-shard-0/cluster0-shard-00-00-i6dcv.gcp.mongodb.net:27017,cluster0-shard-00-01-i6dcv.gcp.mongodb.net:27017,cluster0-shard-00-02-i6dcv.gcp.mongodb.net:27017
2020-05-18T01:47:16.394-0500 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to cluster0-shard-00-02-i6dcv.gcp.mongodb.net:27017
2020-05-18T01:47:16.395-0500 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to cluster0-shard-00-01-i6dcv.gcp.mongodb.net:27017
2020-05-18T01:47:16.395-0500 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to cluster0-shard-00-00-i6dcv.gcp.mongodb.net:27017
2020-05-18T01:47:16.573-0500 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for Cluster0-shard-0 is Cluster0-shard-0/cluster0-shard-00-00-i6dcv.gcp.mongodb.net:27017,cluster0-shard-00-01-i6dcv.gcp.mongodb.net:27017,cluster0-shard-00-02-i6dcv.gcp.mongodb.net:27017
Implicit session: session { "id" : UUID("229ffa5b-9132-4677-91ea-ef7f4502c409") }
MongoDB server version: 4.2.6
```

**Comment by derrickmehaffy** [comment]
`Strapi version: strapi@beta` Please give your actual strapi version listed in your `package.json`

Also can you please clean up your post a bit and use code blocks? (thank you)

**Comment by madudding** [comment]
I terminated my MongoDB Cluster and recreated it on Amazon, and was able to establish connection with strapi.

**Comment by filipesmedeiros** [comment]
Just my 2 cents: ins't it necessary to use the URL that *doesn't* include `+srv`? I noticed that the tutorial requires Node >2.2.12 and not Node >3, which I think changed that URL (at least for me).

**Comment by lauriejim** [comment]
Hello! I just did it and it works.

Here is steps I did - [video](https://www.loom.com/share/8e1a4b477ec84fb5a966b6198acada1e)
