### ISSUE TITLE
Duplicate names crash the system

### ISSUE THREAD

**Issue by Shadow-Boxer** [strapi/strapi#6258]
I Corrupted Strapi. I was changing a name of one of the field names and accidentally used
the same name already in use. Did not get a warning message. And now have to rebuild
from scratch. ( not a big deal but could be if it was larger)

[
**Steps to reproduce the behavior**

1. Go to 'field'
2. change name to one you are using already.
3. refresh....

**Expected behavior**
 Server wasn't able to start properly.
[2020-05-18T05:32:23.293Z] error Error: SQLITE_ERROR: duplicate column name..

 
 
 
- Node.js version: 
- NPM version:6.3
- Strapi version: 
- Database: sqlite
- Operating system: ubuntu

**

**Comment by lauriejim** [comment]
Thank you for reporting that, other issues report the same thing.
So I will close this one.

To fix, go in your `api/../models/**.settings.json` file and update the attribute name.
