### ISSUE TITLE
I can't update user by using FormData

### ISSUE THREAD

**Issue by voidbass** [strapi/strapi#6268]
When I use update users at UI of Strapi, it's working normally. I see it use FormData to update the user and I reproduce it at my page.
But when I'm using my website to update users, it's an error. 
I also use FormData to update my users like Strapi with FormData but it doesn't work.

I can update the user with POST normally but it just happens with FormData.

**Screenshots**
![image](https://user-images.githubusercontent.com/49196215/82312401-3004a400-99f1-11ea-8e7c-f31732816396.png)
![image](https://user-images.githubusercontent.com/49196215/82312513-5de9e880-99f1-11ea-8459-a83fda3d8599.png)

![image](https://user-images.githubusercontent.com/49196215/82312051-ba98d380-99f0-11ea-9de0-e9780ab73de9.png)
![image](https://user-images.githubusercontent.com/49196215/82312223-f6cc3400-99f0-11ea-972a-01e646f4afe9.png)

**System**
- Node.js version: Node v13.11.0
- NPM version: NPM v 6.13.7
- Strapi version: "3.0.0-beta.19.3",

**Comment by lauriejim** [comment]
Hello! The `POST /users` is calling this function - [code](https://github.com/strapi/strapi/blob/c01bda9fff144a21ae86ea4ad79fbdedd29ffa1f/packages/strapi-plugin-users-permissions/controllers/User.js#L89)

We can see this get the data with `ctx.request.body` so it means that the `multipart` is not supported (multipart means FormData)

And the Content Manager (the admin) call this function - [code](https://github.com/strapi/strapi/blob/c01bda9fff144a21ae86ea4ad79fbdedd29ffa1f/packages/strapi-plugin-users-permissions/controllers/User.js#L89)

And we can see a condition for the multipart, so it manage the FormData.
