### ISSUE TITLE
import and export csv or googlesheets

### ISSUE THREAD

**Issue by Brunowilliang** [strapi/strapi#6270]
import by google or import a csv with all files

**Comment by derrickmehaffy** [comment]
Please see: https://portal.productboard.com/strapi/1-public-roadmap/c/23-administration-data-importation-exportation

**Comment by lauriejim** [comment]
Additionnal info - here is a video I made to import data from a file - [video](https://www.youtube.com/watch?v=-NuExe4NfpQ&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=2&t=0s)
