### ISSUE TITLE
Cannot create a relation attribute named id

### ISSUE THREAD

**Issue by Monte47** [strapi/strapi#6279]
**Describe the bug**
I have a local strapi environment setup with a local version of a mysql db.

I have two basic content-types, TestRelation1 and TestRelation2. They each have a text field and an integer field in addition to their ID Integer field (the primary key) that is created in the DB.
![image](https://user-images.githubusercontent.com/21068946/82345089-b4cbcf80-99a9-11ea-9be7-d6fc10dce2d8.png)

![image](https://user-images.githubusercontent.com/21068946/82345140-c319eb80-99a9-11ea-9da7-ffbef1821d73.png)

I add a one-to-many relation to the TestRelation1 Content Type, pointing a new field to the existing ID field of TestRelation2 Content Type. 

![image](https://user-images.githubusercontent.com/21068946/82345241-e349aa80-99a9-11ea-96ab-0b768d1669ec.png)

And now when I go to select an entry in the TestRelation2 type. It both does not display the ID column anymore:
![image](https://user-images.githubusercontent.com/21068946/82345521-37548f00-99aa-11ea-97ce-fa96415b9827.png)

and gives me an error when I select an entry:
![image](https://user-images.githubusercontent.com/21068946/82345615-53583080-99aa-11ea-862b-d5b146e68c38.png)

It seems like the URL is not able to get the ID of that entry, instead getting [object Object]

`http://localhost:1337/admin/plugins/content-manager/collectionType/application::testrelation2.testrelation2/[object%20Object]?redirectUrl=/plugins/content-manager/collectionType/application::testrelation2.testrelation2`

When I manually edit the ID in the url, it looks fine:
![image](https://user-images.githubusercontent.com/21068946/82345884-a336f780-99aa-11ea-9fb7-66eda964c66b.png)

**System**

- Node.js version: v10.17.0
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.20.2
- Database: mysql 
- Operating system: macos 10.15.4

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
We have other attribute name that you can't use, other issues exist.

The `id` represent the attribute name that will be created in the other model.
This not represent the existing field you want to do the relation with.

**Comment by litehacker** [comment]
https://github.com/strapi/strapi/issues/6184 here might be the similar issue.

**Comment by lauriejim** [comment]
This has been fixed, you can't set `id` anymore.
