### ISSUE TITLE
TypeError: type.split is not a function when uploading media via URL

### ISSUE THREAD

**Issue by brotsky** [strapi/strapi#6286]
**Describe the bug**
Uploading an image via URL gives a 500 error with a `TypeError: type.split is not a function` log on the server. 

**Steps to reproduce the behavior**

1. Go to "Media Library" at /admin/plugins/upload
2. Click on "Upload assets"
3. Upload via URL. You could try https://images-na.ssl-images-amazon.com/images/I/61vjUCzQCaL._AC_SL1484_.jpg

**Expected behavior**
The image gets has a 500 error and the server has the following logs:

`
May 19 21:32:15 daily-deal-videos heroku/router at=info method=GET path="/upload/proxy?url=https://images-na.ssl-images-amazon.com/images/I/71tg3ruJCxL._AC_SL1500_.jpg" host=daily-deal-videos.herokuapp.com request_id=89acaca3-b4c0-4cd5-9038-344aa93ddb2f fwd="76.174.144.17" dyno=web.1 connect=0ms service=39ms status=500 bytes=120 protocol=https
May 19 21:32:32 daily-deal-videos app/web.1 
May 19 21:32:32 daily-deal-videos app/web.1   TypeError: type.split is not a function
May 19 21:32:32 daily-deal-videos app/web.1       at Object.get type [as type] (/app/node_modules/koa/lib/response.js:383:17)
May 19 21:32:32 daily-deal-videos app/web.1       at /app/node_modules/koa-compress/index.js:54:56
May 19 21:32:32 daily-deal-videos app/web.1       at processTicksAndRejections (internal/process/task_queues.js:97:5)
May 19 21:32:32 daily-deal-videos app/web.1       at async /app/node_modules/strapi/lib/middlewares/responses/index.js:17:9
May 19 21:32:32 daily-deal-videos app/web.1       at async cors (/app/node_modules/@koa/cors/index.js:56:32)
May 19 21:32:32 daily-deal-videos app/web.1       at async /app/node_modules/strapi/lib/services/metrics/middleware.js:29:5
May 19 21:32:32 daily-deal-videos app/web.1       at async /app/node_modules/strapi/lib/Strapi.js:302:9
`

**Screenshots**
<img width="983" alt="Screen Shot 2020-05-19 at 9 39 17 PM" src="https://user-images.githubusercontent.com/2758150/82405609-41fa3d00-9a19-11ea-9e0b-000d09efed2d.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 14.2.0
- NPM version: 6.14.0
- Strapi version: 3.0.0-beta.20.3
- Database: Postgresql
- Operating system: Linux on Heroku

**Additional context**
This does not happen on my local machine on OSX.

**Comment by brotsky** [comment]
Could this be fixed by https://github.com/strapi/strapi/pull/5971 ?

**Comment by derrickmehaffy** [comment]
`Node.js version: 14.2.0` This is not a supported node version, only v10 and v12 (v14 doesn't go LTS until october)

**Comment by brotsky** [comment]
> `Node.js version: 14.2.0` This is not a supported node version, only v10 and v12 (v14 doesn't go LTS until october)

I also tried with 12.0.0 and it gave me the same error. I only upgraded to 14.2.0 to attempt fixing this.

**Comment by lauriejim** [comment]
Hello! What is the browser you used.
I just tried and it works well on my side.

**Comment by Froelund** [comment]
We have the same issue after upgrading from `3.0.0-beta.20.2` to `3.0.0-beta.20.3`.

Stacktrace:
```
  TypeError: type.split is not a function
      at Object.get type [as type] (<project-src>/node_modules/koa/lib/response.js:382:17)
      at <project-src>/node_modules/koa-compress/index.js:49:56
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async <project-src>/node_modules/strapi/lib/middlewares/responses/index.js:17:9
      at async <project-src>/middlewares/magic-link/index.js:37:7
      at async cors (<project-src>/node_modules/@koa/cors/index.js:85:16)
      at async <project-src>/node_modules/strapi/lib/Strapi.js:302:9
```

Browser: `Chrome 81.0.4044`.

**Comment by Froelund** [comment]
I just tried to roll back to `3.0.0-beta.20.2`, and the issue still persist.

**Comment by AHgPuK** [comment]
> 
> 
> Could this be fixed by #5971 ?

No, it is not related issue.

**Comment by alexandrebodin** [comment]
Hi, this issue is closed by https://github.com/strapi/strapi/pull/6340

**Comment by NuclleaR** [comment]
+1 faced with same issue

**Comment by Froelund** [comment]
@NuclleaR this should be fixed in recent versions. Which version are you using?
