### ISSUE TITLE
CORS error on Strapi-Admin panel for Video's accessing from S3 File storage Bucket

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#6298]
**Describe the bug**
We are using AWS S3 bucket for Strapi File Storage purpose & we have created a local Provider: strapi-provider-upload-mcqueen for this.
When I try to run Strapi Admin locally I am getting CORS error for Video preview’s on Admin panel when I try to access these Video’s on Media Library page. But when I try to access these Video’s from separate front-end React application connecting to Strapi, which uses same Media Library files.. these Video preview’s are working fine on front-end app.
We have used * for CORS on our S3 File storage bucket.. which means those files can be accessible by any URL 
Not knowing why I am getting CORS error for Videos only on Strapi Admin panel.. 

**Note:**  I have tested same behavior on default Strapi Beta.20.3 app which doesn't uses any File Storage bucket & found it's working fine.
So issue is only when we use S3 bucket
 
**Steps to reproduce the behavior**

1. Try using AWS S3 bucket for File storage purpose
2. Try uploading mp4 Videos
3. Go to Media Library page on Admin panel & see
4. Throws CORS error for these Videos and Vide preview doesn't work

**Expected behavior**
Videos or Video preview should work fine on Strapi Admin panel/ Media Library page with out any CORS error when using separate S3 File Storage bucket

**Screenshots**
<img width="1667" alt="Strapi - Media Library 2020-05-20 13-20-09" src="https://user-images.githubusercontent.com/23507845/82482752-ec677400-9a9c-11ea-8964-f02b94c71d67.png">

**System**

- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.20.3
- Database: Mongo & S3 File storage for File uploads
- Operating system: MAC

**Comment by DimitrieStraoanu** [comment]
Add CORS configuration to your bucket.
Go to your bucket -> permissions -> CORS configuration
paste this
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
then save

**Comment by lauriejim** [comment]
Thank you for your help @DimitrieStraoanu

**Comment by vinod77** [comment]
Thank you @DimitrieStraoanu It worked with your's solution.

**Comment by lopermo** [comment]
Anybody looking for a solution from November 2020 onwards, S3 CORS config only allows JSON:

`[
   {
      "AllowedHeaders":[
         "*"
      ],
      "AllowedMethods":[
         "GET",
         "PUT",
         "POST",
         "DELETE"
      ],
      "AllowedOrigins":[
         "*"
      ],
      "ExposeHeaders":[
         
      ]
   }
]`
