### ISSUE TITLE
Allow scoped packages for plugins and providers

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#6299]
**Describe the bug**
Not able to access AWS S3 local Provider from different path inside Node_modules

**Steps to reproduce the behavior**

1. Install your local AWS S3 provider, which gets added in to a separate folder inside node_modules
2. On `./extensions/upload/config/settings.json` there is no way to use different path for local provider except using this way:  "provider": "aws-s3",
3. Can't access local provider from separate folder inside node_modules

**Expected behavior**
 Should be able to access local Provider even from a different path inside node_modules.

**Screenshots**

**System**

- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.20.3
- Database: Mongo & S3 File storage for File uploads
- Operating system: MAC

**Comment by lauriejim** [comment]
Hello! We have an issue with scoped plugins and providers.
I already pinged @alexandrebodin about that.
I don't have any workaround to bypass this issue.
If this is your provider, I suggest you publish it in non-scoped package.
Then you will be able to use it.

**Comment by alexandrebodin** [comment]
Hi, for now we only look for relative names based on the strapi-plugin-* or strapi-provider-* in the next major release we will change some of those mechanisms to load plugin and provider with more flexibility. 

I'm setting this as a feature request so we don't forget about it ;)

**Comment by vinod77** [comment]
This can be closed, we have overridden Strapi default code to achieve this.
Thank you!

**Comment by derrickmehaffy** [comment]
planned for v4
