### ISSUE TITLE
logo_login.jpg points to strapi.io not local asset

### ISSUE THREAD

**Issue by Brad-Christie** [strapi/strapi#6301]
**Describe the bug**
It appears the [index.html](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/public/index.html) [still?] references assets on strapi.io. It also appears this asset is blocked due to a referral policy.

**Steps to reproduce the behavior**

1. npx strapi create strapi --quickstart
2. visit http://localhost:1337/
3. Observe logo missing

**Expected behavior**
Logo should be present.

**Screenshots**
![2020-05-20 14_50_04-Welcome to your Strapi app](https://user-images.githubusercontent.com/10567322/82485421-64d43200-9aa9-11ea-8604-31db51f29e2f.png)

**System**

- strapi/strapi:3.0.0-beta.20.3 docker image
- Node.js version: v12.13.0
- Database: mongo

**Comment by iraguhalionel** [comment]
Hi @Brad-Christie I had the same issue before but I think strapi upgraded their files

After running strapi build && strapi develop the image is available.

![localhost_1337_](https://user-images.githubusercontent.com/26253283/82496364-e4cfbb80-9aec-11ea-8335-ca782c380cbe.png)

**Comment by Brad-Christie** [comment]
@iraguhalionel Thanks, but still believe this should be a local asset. In fact, the "people saying hello" should, as well as with anything else that's pointing to strapi.io.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this.
I think it's an easy fix to do.
Can you please submit a PR to fix it.
I will appreciate your contribution on this issue.
Ping @HichamELBSI and @soupette about that.
