### ISSUE TITLE
Error Media Libary upload: Cannot wrap non-Error object

### ISSUE THREAD

**Issue by stiveurkel** [strapi/strapi#6305]
**Describe the bug**
In Production whenever I try to upload files I get an error.
` AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object`

It has worked so far, but now it doesn't work anymore. I cannot upload anymore pictures/videos in production.

I have figured out why I have this error, but I don't know how to resolve it. Basically if I hard code my api_key and api_secret instead of the variables it works as expected. How can I make these variables work (process.env.XXXXX) ?

**Screenshots**
![image](https://user-images.githubusercontent.com/42664988/82494607-23b04200-9aea-11ea-941c-1d927ca4b985.png)
![image](https://user-images.githubusercontent.com/42664988/82494650-31fe5e00-9aea-11ea-947a-5b3ae6e9a1a5.png)
![image](https://user-images.githubusercontent.com/42664988/82495464-6cb4c600-9aeb-11ea-8e00-ddfdb27e5641.png)

**Code snippets**
Here is my cloudinary config in extensions\upload\config\settings.json
`{ 
  "provider": "cloudinary", 
  "providerOptions": { 
    "cloud_name": "mycloudinarynamehere", 
    "api_key": "${process.env.CLOUDINARY_API_KEY}", 
    "api_secret": "${process.env.CLOUDINARY_API_SECRET}" 
  } 
} 
`

I have tried this as well [https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#configuration-per-envrionment](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#configuration-per-envrionment) and it is not working either.

**System**
- Node.js version: v12.13.1
- NPM version: 6.13.6
- Strapi version: 3.0.0-beta.20.3
- Database: Postgresql from DigitalOcean
- Operating system: Digital Ocean droplet

**Comment by stiveurkel** [comment]
Ok I have figured out why I have this error, but I don't know how to resolve it. Basically if I hard code my api_key and api_secret instead of the variables it works as expected. How can I make these variables work (process.env.XXXXX) ?

**Comment by derrickmehaffy** [comment]
I did test with @stiveurkel on my twitch stream earlier and it appears to come from defining variables in the lifecycle config from PM2, actually using a .env file (likewise using the .env from the RC tagged releases) works fine.

**Comment by khanharis87** [comment]
deleting folder upload folder in /extensions did it for me
