### ISSUE TITLE
Ability to create new entry for relational fields

### ISSUE THREAD

**Issue by Guang0404** [strapi/strapi#6307]
I noticed that relational fields don't allow us to add or createa new enry for the content type we are trying to connect. I highly suggest adding this capability, as Directus already has it.  It greatly reduces production not being able to do this.

I honestly believe, from a business person's and coder's perspective, that these are the main issues that should be priortized :

1. Export and import CSV/JSON data into strapi.
2. Export and import schemas into strapi
3. Capability to create new content-item in relational fields.

#1 & #2 is important for reducing initial fear of using strapi.
#3 Its just a great feature to have an makes a lot of sense.

**Comment by derrickmehaffy** [comment]
1. https://portal.productboard.com/strapi/1-public-roadmap/c/23-administration-data-importation-exportation
2. This isn't possible via the Admin (at least not in a good way) as models are stored in files. Although you could create a request on the product board
3. https://github.com/strapi/strapi/issues/4948 

Closing as it's a duplicate and also was not opened with the feature request template.
