### ISSUE TITLE
cross-database references are not implemented

### ISSUE THREAD

**Issue by tiberiumihai** [strapi/strapi#6308]
**Describe the bug**
I'm using a postgresql database cluster from digital ocean.
I've added a connection pool and added configuration in .env file which I'm using to start the project.
If I'm using the database connection instead of the pool connection, it works but then I get limited connections error.
When starting using the pool connection I get this error when loading strapi admin ui in browser:
```
error: cross-database references are not implemented: "database-pool.public.users-permissions_role"
```

**Steps to reproduce the behavior**
1. Create Database Cluster in Digital Ocean
2. Create Pool and set Pool mode to Session
3.  Start the server using strapi develop;  Everything is ok.
4. Load localhost:1337/admin in browser
5. Loading infinitely; See error in console
```
error: cross-database references are not implemented: "database-pool.public.users-permissions_role"
```

**Expected behavior**
I'm expecting the pool connection to work as in the case when I'm using the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/12754525/82534849-8fc49180-9b4e-11ea-8dcc-961eac675281.png)
![image](https://user-images.githubusercontent.com/12754525/82535855-3198ae00-9b50-11ea-90be-7009c5d749a2.png)

**Code snippets**
database.json
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "${process.env.DATABASE_CLIENT}",
        "host": "${process.env.DATABASE_HOST}",
        "port": "${process.env.DATABASE_PORT}",
        "username": "${process.env.DATABASE_USERNAME}",
        "password": "${process.env.DATABASE_PASSWORD}",
        "database": "${process.env.DATABASE_NAME}",
        "schema": "public",
        "ssl": { "rejectUnauthorized": false }
      },
      "options": {
        "pool":{
          "min": 0,
          "max": 22,
          "idleTimeoutMillis": 100000,
          "createTimeoutMillis": 100000,
          "acquireTimeoutMillis": 100000,
          "propagateCreateError": false
        },
        "debug": true
      }
    }
  }
}
```

**System**

- Node.js version: v10.17.0
- NPM version: 6.14.5
- Strapi version: beta-20.3
- Database: Postgresql Database Cluster from Digital Ocean
- Operating system: MacOS / strapi:alpine

**Additional context**
If I'm connecting directly using database connection instead of connection pool, it works, but then I get limited connections error, so that is not an option for me.

I'm not sure if this is a problem with DO db clusters, Postgresql or Strapi.
Thanks!

**Comment by derrickmehaffy** [comment]
this is likely something to look at Knex for as that handles DB connections.

**Comment by tiberiumihai** [comment]
I'll try to move everything to Heroku. We'll see how that goes.

**Comment by tiberiumihai** [comment]
Also, Digital Ocean has CA certificate, and I can't find any information on how I can give it to strapi for postgres connection. All the testing was made using public connection with my IP allowed.

**Comment by tiberiumihai** [comment]
I'm closing this. Already moved to heroku, fast and easy. Hassle free.
