### ISSUE TITLE
Proper documentation on working with models fields and relations on lifecycle callbacks

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [strapi/strapi#6322]
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I wanted to check simple lifecycle based callbacks:

    beforeDestroy: async (model, attrs, options) => {        
        console.log(model.name)
    },

When I delete this content type, my console shows this:

    undefined

Now if I look at [current documentation about these callbacks](https://strapi.io/documentation/3.0.0-beta.x/concepts/models.html#life-cycle-callbacks). I have learned nothing. What these `model`, `attrs` and `options` are for? How I can work with model's fields and relations? Do I really need to dig on issues page of this repo in order to understand what to do?

**Comment by derrickmehaffy** [comment]
While the new lifecycle callbacks aren't in the beta (hence why the docs haven't been deployed)

You can test the new lifecycle callbacks on the rc.x releases with the following docs: https://github.com/strapi/strapi/blob/master/docs/3.0.0-beta.x/concepts/models.md#lifecycle-hooks

lifecycle callbacks on beta are broken, and the recent changes to the rc tagged releases will not be back ported to the beta (as stable is due by the end of the month, which is based on the rc tagged releases)

**Comment by derrickmehaffy** [comment]
For now I'm going to mark this as closed, as it has already been fixed.
