### ISSUE TITLE
Provide a way to constomize admin authentication

### ISSUE THREAD

**Issue by agustinflorez** [strapi/strapi#6326]
Hi,

First I wanted to thank you for a great app and all the effect you spent in this great app. 

I wanted to request a way to customize admin authentication, we want to use Azure so our admin users can authenticate, is there a way to do it currently? 

Thanks

**Comment by derrickmehaffy** [comment]
Duplicate: 

https://github.com/strapi/strapi/issues/5188
https://github.com/strapi/strapi/issues/4838

Also closing as required templates were not followed.
