### ISSUE TITLE
Can't add some another languag character in ENUMERATION from Content-Type

### ISSUE THREAD

**Issue by aungkyawkyawsoe** [strapi/strapi#6328]
#### Dear Friends! (Mingalarpar) 

I am using **Strapi** to create a new horoscope application and then create a new collection-type and add an **enum** field, but it can't add for some another language (like Chinese, Japanese or Burmese) characters and show the  **Regex validation error**. 

![Imgur](https://i.imgur.com/tP3DZRT.png)

**Comment by derrickmehaffy** [comment]
Please see the following discussion: https://github.com/strapi/strapi/discussions/4780

For the moment this isn't possible due to the regex restrictions put in place for GraphQL. You will need to follow the regex stated in that discussion. I'm going to mark this as closed for now.
