### ISSUE TITLE
@sailshq/lodash not found when `npm i`

### ISSUE THREAD

**Issue by faebeee** [strapi/strapi#633]
**Node.js version**:
8.9.4

**npm version**:
5.6.0

**Strapi version**:
strapi@3.0.0-alpha.9.3

**Operating system**:
OSX

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Getting this error after removing `node_modules` and running `npm i`

```
npm ERR! path /Users/fabiogianini/Work/portfolio-strapi/node_modules/.staging/strapi-2db00c29/node_modules/@sailshq/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/fabiogianini/Work/portfolio-strapi/node_modules/.staging/strapi-2db00c29/node_modules/@sailshq/lodash' -> '/Users/fabiogianini/Work/portfolio-strapi/node_modules/.staging/@sailshq/lodash-babbe47e'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Read above

**What is the expected behavior?**
Install those modules

**Comment by e2o** [comment]
Hmm, I tried to exact same thing and the install worked for me. Have you tried removing your `package-lock.json` before reinstalling?

If possible, please provide your `package.json` file so I can have a look at it.

**Comment by lauriejim** [comment]
Hi @faebeee , same as @e2o , I can't reproduce your issue.
Did you change you npm registry ?

**Comment by faebeee** [comment]
Hi @lauriejim and @e2o I tried to install it this morning and It seems to work now. No idea why or how but the installation is running through. At the beginning, I had the same error on Heroku and on my local machine. Now it works on both. Therefore I'll close this issue

**Comment by Froelund** [comment]
Has the exact same issue. Fixed by removing my `package-lock.json` and running `npm i`.

**Comment by ntloi95** [comment]
Had the exact same issue. Fixed by removing package-lock.json and running npm i, too
