### ISSUE TITLE
Error running strapi with postgres in production

### ISSUE THREAD

**Issue by abelsoares** [strapi/strapi#6335]
**Describe the bug**
Strapi is unable to start correctly with PM2 and postgres configuration.

**Steps to reproduce the behavior**

1 - Follow the deployment guide for aws, and configure `...production/database.json` like in the guide: https://strapi.io/documentation/3.0.0-beta.x/deployment/amazon-aws.html#_2-edit-the-database-json-file

2 - Create the PM2 `ecosystem-config.js` like in the guide, exporting the env variables to connect to a postgres RDS instance.

3 - Run the app and the following pm2 logs shows: 
```bash
0|strapi   | [2020-05-24T19:02:06.951Z] debug ⛔️ Server wasn't able to start properly.
0|strapi   | [2020-05-24T19:02:06.953Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
0|strapi   |     at /home/ubuntu/Applications/strapi-demo/node_modules/knex/lib/client.js:318:17
```

4 - The problem seems to arise from the database production configuration: 
```bash
...
"connector": "bookshelf",
"settings": {
  "client": "postgres",
  ...
},
...
```

If `client` is changed to `sqlite`, everything goes ok, and the database used is indeed a Postgres instance.

**Expected behavior**
We should have the client configured as `postgres`.

**System**

- Node.js version: v14.1.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.3
- Database: Postgres 10.6
- Operating system: Ubuntu

**Comment by guppythegod** [comment]
I'm having the same issue.

**Comment by bellib** [comment]
Add option like : 
`
....     
 "options": {
        "pool": {
          "min": 0,
          "max": 15,
          "idleTimeoutMillis": 30000,
          "createTimeoutMillis": 30000,
          "acquireTimeoutMillis": 30000
        }
      }`

**Comment by abelsoares** [comment]
@bellib, if this options solve the problem, I think it's still an issue, as it should be default options when the connection is Postgres. WDYT?

**Comment by derrickmehaffy** [comment]
@alexandrebodin the amount of times I have seen this issue come in the past week is growing quite a bit. We should entertain digging into this more (else we should maybe pass along some of the tarn stuff by default because it's apparent that most users are not using local databases, and thus their latency is too high).

Alternatively there is some massive unoptimization being introduced.

**Comment by abelsoares** [comment]
@alexandrebodin @derrickmehaffy, i'm sure there's a rational behind [this](https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/knex.js#L115), but shouldn't strapi stick with the `knex` defaults of `60000ms`? 
I'm connecting to an RDS instance, inside an aws VPC, which is not an edge case.

**Comment by derrickmehaffy** [comment]
tbh I'm honestly not sure why in the world it would be set so low.

**Comment by abelsoares** [comment]
And the min connection pool set to `0` may also be changed. Anyway, it's a very sensitive area, but knex defaults sound kind of save. @derrickmehaffy, I do understand `knex` uses `tarn` under the wood, but IMO, since strapi uses the `knex` abstraction, it would be much safer to pass the `knex` defaults and not the `tarn` defaults. Imagine `knex` has some issue and changes a pool configuration default, strapi will handle that gracefully.

**Comment by derrickmehaffy** [comment]
> And the min connection pool set to `0` may also be changed. Anyway, it's a very sensitive area, but knex defaults sound kind of save. @derrickmehaffy, I do understand `knex` uses `tarn` under the wood, but IMO, since strapi uses the `knex` abstraction, it would be much safer to pass the `knex` defaults and not the `tarn` defaults. Imagine `knex` has some issue and changes a pool configuration default, strapi will handle that gracefully.

That sounds like a good idea, if you are up for it do you want to create a PR to change the defaults (at the same time too, it might be good to review the depends and update to the newer version of knex if we can. Not too sure about any breaking changes, but I do remember reading the knex changelog including some transaction fixes I believe :thinking: )

**Comment by abelsoares** [comment]
The PR would be basically to remove this code: https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/knex.js#L111, but I would like to have more insights on why connections other than `sqlite` gets the config so ripped off. Maybe @aleksandryackovlev can give some insights, the commit history it's not a good source, seams like copy/rewrite from other places: https://github.com/strapi/strapi/commit/66b2d4f5c3b4aabfed4eeaff10d0122f9b720430

**Comment by probityrules** [comment]
I also followed the instructions in the AWS postgres deployment guide, and I'm seeing this same issue. I tried modifying `options` as shown above, but it doesn't seem to help (other than making the ultimate `Server wasn't able to start properly.` message take longer to appear).

**Comment by abelsoares** [comment]
@probityrules, i think that, if it's a connection timeout issue, you can handle it by tweaking the pool configuration. Just check this code: https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/knex.js#L111, connections other than `sqlite`, will get this defaults. 
Do this, pass the `client` option as `sqlite`, even if `postgres`. Them, if ok, update with `postgres`, but set the poll options like the `knex` and `tarn` libs. Check github repos.

**Comment by dangercris** [comment]
I trie change the client to `sqlite` Strapi run but never connect to my RDS still use de `sqlite ` local db, its very frustrating, I spent a lot of hours trying to deploy instead of develop my app :(

**Comment by abelsoares** [comment]
@dangercris If you've read all the comments in this issue, you'll get that you need to tune the connection pool settings. Try a higher `acquireTimeoutMillis`.

**Comment by dangercris** [comment]
> @dangercris If you've read all the comments in this issue, you'll get that you need to tune the connection pool settings. Try a higher `acquireTimeoutMillis`.

Thanks for the response, what will be a great number for this, of what is the calculation methood?

**Comment by abelsoares** [comment]
@dangercris try the knex defaults:
```
... acquireConnectionTimeout defaults to 60000ms and is used to determine how long knex should wait before throwing a timeout error...
```
And you should be fine.

**Comment by probityrules** [comment]
Okay, my solution was different although it exhibits this same error: I seemed to have applied a security group to the postgres db that blocked the 5432 port. I guess I made a misstep from the guide, but opening that port fixed the issue for me. (Thanks to [this comment](https://github.com/knex/knex/issues/2302#issuecomment-493709133) for the solution.)

**Comment by Cally99** [comment]
Honestly Strapi team really need to sort out these stupid deployment issues or else people are going to find another CMS to use. This will be the last time I use it.
