### ISSUE TITLE
Cast error for components return 500 for MongoDB

### ISSUE THREAD

**Issue by gbkwiatt** [strapi/strapi#6342]
**Describe the bug**
When I am using component in my collection, that has 2 fields, string and number -
When creating with POST, and providing wrong values (string instead of number), I get :
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```
But record is created anyway, with empty component property. 
My component is required field, so shouldn't be created if validation failed ? 

**Steps to reproduce the behavior**

1. Create component with some fields
2. Add that component as a field in collection and select required
3. Try to create data for that collection with wrong values to trigger validation field

**Expected behavior**
component is required field, so shouldn't be created if validation failed ? 

**System**

- Node.js version: 14.x
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database: mongo
- Operating system: windows 10

**Comment by lauriejim** [comment]
Hello! Can you please try with the v3.0.0 version of Strapi please.
I think there is no error and your component is created with `null` values.
Can you confirm?

**Comment by gbkwiatt** [comment]
Sorry for late response, yes that's correct

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
