### ISSUE TITLE
Break Media Lib when deleting a Media field from an Content Type

### ISSUE THREAD

**Issue by mitri-dev** [strapi/strapi#6347]
# **Bug**
In Strapi, after deleting a **Media** Field from a **Collection-Type**, a **GET request to /upload/files** throws an **Error**.  
This should not happened.  

**Steps to reproduce the behavior**

1. Create a new Strapi App.
2. Create a **Collection-Type** with a **Media** Field.
3. Create a new **Entry** from this **Collection-Type** with a **File** uploaded.
4. Delete the **Media** Field from the **Collection-Type**.
5. Finally going to the Media Library (**GET request to /upload/files**) will result in an **ERROR**. 

**Expected behavior**
When deleting a **Media** Field from a **Collection-Type** should remove any relation between the Entries that used **Media** as a Fields and the uploaded files.

**Screenshots**
![steps](https://user-images.githubusercontent.com/54691546/82836210-8fa0fa80-9e9c-11ea-8d53-7aa489acdb99.jpg)

**Code snippets**
This Bug can be achieved **without** using code, this scenario **only uses the Strapi CMS**.

**System**

- Node.js version: v12.16.1.
- NPM version: 6.13.2.
- Strapi version: v3.0.0-beta.20.1
- Database: Default (SQLlite I believe).
- Operating system: Windows.

# **FIX**
I did find a "solution" to this issue.
1. Add the Media field back to the Collection-Type.
2. Remove the Media field manually from every Entry.
3. Now you can remove the Media field from the collection-type without triggering this error.

## **Possible solution**
As stated before, when deleting the Media field from the Collection-Type should remove the Media attached to every Entry that uses it.

**Comment by derrickmehaffy** [comment]
Can you check this in beta.20.3 (and if you want on rc.1, will need a fresh project for the testing rc.x tag)

**Comment by mitri-dev** [comment]
I'm using the version that the command "npx create-strapi-app . --quickstart" creates.

**Comment by ElliottLMz** [comment]
Can repro on Strapi v3.2.3 — Community Edition. This is a very annoying issue.

**Comment by lodi-g** [comment]
Hi, just to confirm that this bug is not entirely fixed. I can't give exact steps to reproduce but basically my setup was :

- 2 single type that have the same component with text and repeatable images
- I modified the component and removed the image field
- I now have this error in the log: ` Error: The target polymorphic type "components_home_supported_bies" is not one of the defined target types`. My single type is `home` and my component is called `supportedBy`. It seems to match with the error.

Good luck and thanks :)

**Comment by derrickmehaffy** [comment]
@lodi-g can you open up a new bug report with the updated information?
