### ISSUE TITLE
Limit content type to user_id

### ISSUE THREAD

**Issue by fabiomig** [strapi/strapi#635]
Hello,

How should i implement on strapi a limitation of witch user can see / edit / delete by their user_id?

Example

GET /things

I only want to show to the user all the things that matches his user_id.

Thanks

**Comment by soupette** [comment]
Hi @fabiomig you need to use the `users-permissions` plugin : [Auth & Permission](http://localhost:1337/admin/plugins/users-permissions/roles) link in the Admin for this.

You can create a role and manage its permissions in the edit view

**Comment by fabiomig** [comment]
Hi @soupette, so the strategy yo recommend me is to have a different role for each user?

Is that equivalent of this? This is what i want.
Select *  from table where user_id = x 

What i've understand of what you suggested is something like this:
Select * from table where role = x

But the problem is any user that have the same role will be able to see what other users of same role do.

Thanks

**Comment by soupette** [comment]
Ok I understand, well in your case you have to either create a plugin that will handle the display of the admin or modify the admin itself to handle it. The second solution will not be dynamic since you'll have to set your user_id directly in the the code instead of having a plugin that can handle it.

**Comment by lauriejim** [comment]
Hi @fabiomig if your user provide an `Authorization` header you will have access to his user.id (https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js)
So you can customize your API controller for you use case

**Comment by lauriejim** [comment]
I close this issue, follow this one. It's really similar https://github.com/strapi/strapi/issues/624
