### ISSUE TITLE
Custom field not appearing on Content-Type Builder. 

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [strapi/strapi#6351]
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

Hello.

I have created my custom field by this [documentation](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/frontend-field-api.html#plugin-s-front-end-field-api) like this:

    import React, { useEffect, useState } from 'react';

    const Translatable = props => {
  
      console.log('TRANSLATABLE!');
      console.log(props);
  
      return <div>Translatable</div>;
    };

    export default Translatable;

Then I have registered it on `../my-plugin/admin/src/index.js`:

    strapi.registerField({type: 'translatable', Component: Translatable});

Then I run:

    npm run build
    npm run develop

When I open admin and try to add my field to my content type I get this:

![image](https://user-images.githubusercontent.com/8684688/82861447-7cdf0200-9f3e-11ea-9db1-1e78ee9de964.png)

I can't find my custom Field in Content Type Builder. Is it even possible?

There is also one main problem. Where I can describe what kind of data structure this filed should be using on database? Where is backend handling.

In documentation, there are only giant walls of code that describes nothing.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
