### ISSUE TITLE
Importing csv into Postgres → duplicate key and value error on adding/saving new Strapi entry

### ISSUE THREAD

**Issue by Guang0404** [strapi/strapi#6352]
**Describe the bug**
 I receive an error when trying to add Strapi content-type entry. 

> insert into "content_type" ("created_at", "description", "field", "title", "uid", "updated_at") values ($1, $2, $3, $4, $5, $6) returning * - duplicate key value violates unique constraint "content_type_pkey"

This happened after I uploaded csv files into any of the content_type's table in pgAdmin (postgres 12).  The new entries from the csv file show up, but I cannot 

**Steps to reproduce the behavior**

1. Go to pgAdmin 
2. Select the table of the content type you want to upload csv
3. Successfully import csv into table
4. Got to strapi admin panel.
5. Select content type with imported data
6. You will see all your new entries from the csv
7. Try to add new entry with different uid, title and values.

**Expected behavior**
You get an error similar to that I have mentioned : 

> insert into "content_type" ("created_at", "description", "field", "title", "uid", "updated_at") values ($1, $2, $3, $4, $5, $6) returning * - duplicate key value violates unique constraint "content_type_pkey"

**Screenshots**
![image](https://user-images.githubusercontent.com/40015483/82865950-9015b180-9eed-11ea-95df-033e1de47d17.png)

**Code snippets**
I have no other code changes from Strapi's original code. My locally hosted Postgres server (using original installation) also does not have any deviations from original code. This is also purely a problem involving Strapi and Postgres

**System**

- Node.js version: 12.13.0
- NPM version: 6.10.1
- Strapi version: 3.0.0-beta.20.1
- Database: POSTGRES 12
- Operating system: Windows 10 Home edition

**Additional context**
It is possible that strapi returns an error, because I had to manually create the numeric ID for the csv entries before importing them into Postgres using pgAdmin. Perhaps strapi is still trying to create the new entry with an id of "1" even though my import already contains an entry with id of "1"

**Comment by derrickmehaffy** [comment]
I don't believe this is directly an issue with Strapi and thus I'm moving this over to a discussion.
