### ISSUE TITLE
Error while trying to send mail for forgot password

### ISSUE THREAD

**Issue by rvigneshw** [strapi/strapi#6356]
**Describe the bug**
When try to send email to forgot-password route the console says "Auth.form.error.email.invalid"

**Steps to reproduce the behavior**

1. Go to '/auth/forgot-password.'
2. Click on 'submit button'
3. open developer console'

**Expected behavior**
A mail to send to the given mail address

- Node.js version: 12.13.1
- NPM version:6.12.1
- Strapi version: 3.0.0-alpha.26.2
- Database: mongo db atlas
- Operating system: windows [deployed on heroku]

**Additional context**
I've used both inbuilt provider and also http://sendgrid.com/ as email provider

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-alpha.26.2` This version of Strapi is not supported.

**Comment by rvigneshw** [comment]
I'm currently using
"strapi": "3.0.0",
    "strapi-admin": "3.0.0",
    "strapi-connector-bookshelf": "3.0.0",
    "strapi-plugin-content-manager": "3.0.0",
    "strapi-plugin-content-type-builder": "3.0.0",
    "strapi-plugin-documentation": "3.0.0",
    "strapi-plugin-email": "3.0.0",
    "strapi-plugin-graphql": "3.0.0",
    "strapi-plugin-upload": "3.0.0",
    "strapi-plugin-users-permissions": "3.0.0",
    "strapi-utils": "3.0.0"

Still the same error
{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.form.error.email.invalid"}]}],"data":[{"messages":[{"id":"Auth.form.error.email.invalid"}]}]}

**Comment by aksdevac** [comment]
@rvigneshw  you will need to debug more starpi will always return Auth.form.error.email.invalid error to find out exact error add log/debugger inside strapi sendgrid package inside your node module
https://github.com/strapi/strapi/blob/728e8c63b97389f61fac38a3853262ccd24f3970/packages/strapi-provider-email-sendgrid/lib/index.js#L29

**Comment by tombpain** [comment]
Please see the following fork of the sendgrid provider which should be a fix for the above issue.

https://github.com/tombpain/strapi-provider-email-sendgridmail?organization=tombpain&organization=tombpain

Looks to me like the sendgrid node implementation now only supports ES6/ES8 methodology and not callbacks.

A PR has been raised to merge the changes into the main repo.

Cheers,

Tom

**Comment by lauriejim** [comment]
Hello, by default Strapi is using `nodemailer`.
But it's possible that your computer can't send email with this local no-smtp tool.
I suggest you to use a third party to send email, like sendgrid.
