### ISSUE TITLE
Images dissapearing from Media Library after ~ 1 hour on Heroku / postgres Hobby deplyoment

### ISSUE THREAD

**Issue by kempsterrrr** [strapi/strapi#6359]
**Describe the bug**
I have a Strapi instance deployed on a hubby dyno with a postreSQL backend using the default media library without an external provider e.g. S3. I can uploaded images successfully however after a short period of time those images disappear from the library and a 404 is return from the heroku logs when a request is made.

**Steps to reproduce the behavior**

1. Add images in Media library
2. Come back to media library ~ 1 hour later and images are no longer found in media library and cannot be called from the API

**Expected behavior**
Images should remain in the media library.

**Screenshots**
![Screenshot 2020-05-26 at 15 36 14](https://user-images.githubusercontent.com/9025997/82914291-3baf1800-9f67-11ea-9a1b-275e405df231.png)

**Code snippets**
```
2020-05-26T14:30:05.966904+00:00 heroku[router]: at=info method=GET path="/uploads/small_cazoo_9bafd9a97d.png?6839" host=backend-cms.herokuapp.com request_id=40141d23-16b8-40b6-b83d-91b8893b1597 fwd="176.252.5.7" dyno=web.1 connect=1ms service=5ms status=404 bytes=479 protocol=https
2020-05-26T14:30:05.943811+00:00 heroku[router]: at=info method=GET path="/uploads/small_hard-hat_03a71d3aec.jpeg?6826" host=backend-cms.herokuapp.com request_id=fcb1a9bc-5aeb-4ebd-80f1-cd45ecbba053 fwd="176.252.5.7" dyno=web.1 connect=0ms service=3ms status=404 bytes=479 protocol=https
2020-05-26T14:30:05.986502+00:00 heroku[router]: at=info method=GET path="/uploads/small_cazoo-delivery-female_9ccb4ee98d.jpeg?6848" host=backend-cms.herokuapp.com request_id=3edf7470-f1cb-405f-890f-3254380bcc4c fwd="176.252.5.7" dyno=web.1 connect=0ms service=3ms status=404 bytes=479 protocol=https
```

**System**

- Node.js version: 12.13.0
- NPM version: 6.13.0
- Strapi version: v3.0.0-beta.20.3
- Database: Heroku postgreSQL
- Operating system: Heroku

**Comment by alexandrebodin** [comment]
Hello @kempsterrrr 

Heroku dynos are reset after some inactivity and the local files persisted are deleted. You will need to configure a third party upload provider if you want to host strapi on heroku. You can refere to this documentation to learn more: https://strapi.io/documentation/v3.x/deployment/heroku.html#file-uploads

**Comment by derrickmehaffy** [comment]
Also: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

**Comment by jenaro94** [comment]
Hello @derrickmehaffy , I am having the same issue, I thought that hosting the images on cloudinary and linking them to the media library would fix this issue, but it doesn't, is there a heroku plugin or something that I need to install for the images to stay? It is working with the pg plugin and all the other data stays, I could just add a link to the image on Strapi as text, but it is counter intuitive, thank you in advance!

_Also, the link https://strapi.io/documentation/developer-docs/latest/deployment/heroku.html#file-uploads is not working any more_

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#file-uploads

Did you configure the cloudinary provider in Strapi (see: https://github.com/strapi/strapi/tree/master/packages/strapi-provider-upload-cloudinary)

**Comment by jenaro94** [comment]
That worked @derrickmehaffy thank you very much!
