### ISSUE TITLE
New project fails to connect to database

### ISSUE THREAD

**Issue by Synj24** [strapi/strapi#636]
**Node.js version**:
v9.5.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.9.3
**Operating system**:
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1049-aws x86_64)

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When trying to start a new project strapi throws a warning that it is unable to connect to the database.
```
ubuntu@ip-172-31-45-231:~$ strapi new access-api
INFO (12996 on ip-172-31-45-231): Creating your application... It might take a few seconds.
INFO (12996 on ip-172-31-45-231): Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: strapi-access
 Host: localhost
 Port: 27017
 Username: synj
 Password: *********
INFO (12996 on ip-172-31-45-231): Testing database connection...
WARN (12996 on ip-172-31-45-231): Database connection has failed! Make sure your database is running.
(node:12996) UnhandledPromiseRejectionWarning: MongoError: Authentication failed.
    at /home/ubuntu/access-api/node_modules/mongodb-core/lib/connection/pool.js:595:61
    at authenticateStragglers (/home/ubuntu/access-api/node_modules/mongodb-core/lib/connection/pool.js:513:16)
    at Connection.messageHandler (/home/ubuntu/access-api/node_modules/mongodb-core/lib/connection/pool.js:549:5)
    at emitMessageHandler (/home/ubuntu/access-api/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/ubuntu/access-api/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
(node:12996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**If the current behavior is a bug, please provide the steps to reproduce the problem**
Fresh Ubuntu 16.04 instance on aws, install nvm and then node at latest version
```
nvm install node
```
Install mongodb using [this guide](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/) when finished */var/log/mongodb/mongod.log* displays:
```
...
[initandlisten] waiting for connections on port 27017
```
Install Strapi
```
npm install strapi@alpha -g
```
Start a new strapi project ([I have tried with both *localhost* & *127.0.01*](https://github.com/strapi/strapi/issues/563#issuecomment-362746175))
```
strapi new access-api
```

**What is the expected behavior?**
strapi starts a new project and connects to the database

I am fairly new to MongoDB so apologies if this is a stupid mistake on my part :fearful:

**Comment by e2o** [comment]
Looks like your MongoDB is not running.
You can start it by running `mongod` in terminal. (leave the terminal open).

Re-try generating a project now, so strapi can generate your `strapi-access` database for you.

**Comment by Synj24** [comment]
Thanks, when i ran `mongod` instead of using systemd to start and stop it i realised it was throwing errors because there wasn't a directory at */data/db* so i created one and `chown`'d it to $USER.
After that `strapi new ...` appeared to work.
However now when i try `strapi start`  it still wont connect
```
$ strapi start                                                                                                                            
DEBUG (15257 on ip-172-31-45-231): Server wasn't able to start properly.
ERROR (15257 on ip-172-31-45-231): Make sure your MongoDB database is running...
```
and `mongod` complains about an authentication failure
```
2018-02-13T15:32:56.255+0000 I ACCESS   [conn4] SCRAM-SHA-1 authentication failed for synj on access-strapi from client 127.0.0.1:42740 ; UserNotFound: Cou│fully installed.
ld not find user synj@access-strapi
```
And I can't see either the database or the user using mongo shell
```
> show users                                                                                                                                               
> show dbs                                                                                                                                                 
admin   0.000GB                                                                                                                                            
config  0.000GB                                                                                                                                            
local   0.000GB
```

**Comment by e2o** [comment]
It appears like no strapi database was made after running `strapi new [name]`.

Can you try again and verify that no error is thrown during `strapi new ...` execution?

**Comment by Synj24** [comment]
I tried again and `mongod` didn't respond at all when ran `strapi new ...`
```
2018-02-13T16:29:52.792+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
```
Heres the error it throws when i run strapi start: 
```
2018-02-13T16:31:19.139+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:42856 #1 (1 connection now open)
2018-02-13T16:31:19.198+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:42856 conn: { driver: { name: "nodejs", version: "3.0.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-1049-aws" }, platform: "Node.js v9.5.0, LE, mongodb-core: 3.0.2" }
2018-02-13T16:31:19.206+0000 I ACCESS   [conn1] SCRAM-SHA-1 authentication failed for synj on strapi-access from client 127.0.0.1:42856 ; UserNotFound: Could not find user synj@strapi-access
2018-02-13T16:31:19.208+0000 I NETWORK  [conn1] end connection 127.0.0.1:42856 (0 connections now open)
```

**Comment by e2o** [comment]
Wat version of MongoDb do you have installed? Should be at least 3.4.

**Comment by Synj24** [comment]
v3.6.2

**Comment by blurdylan** [comment]
I had the same issue with 3.0.0-alpha.10.
I ran `strapi new project-name` then when it prompts to enter username and password,
I left it blank.

Now when I run `strapi start` it works.

**Comment by Synj24** [comment]
Thanks @blurdylan , after updating both mongo & strapi and leaving the username and password blank when using `strapi new ...` it now works!
:champagne: :confetti_ball:

**Comment by wadeziegler** [comment]
I have a problem where the database is accessible while creating the app and then it will not start.

`[2018-03-30T02:07:58.036Z] info Creating your application... It might take a few seconds.
[2018-03-30T02:07:58.178Z] info Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: strapi
 Host: 127.0.0.1
 Port: 27017
 Username: 
 Password: 
 Authentication database: 
 Enable SSL connection: false
[2018-03-30T02:08:13.578Z] info Testing database connection...
[2018-03-30T02:08:14.063Z] info The app has been connected to the database successfully!
[2018-03-30T02:08:14.193Z] info Copying the dashboard...
[2018-03-30T02:08:17.523Z] info Installing dependencies...
[2018-03-30T02:08:26.812Z] info The plugin settings-manager has been successfully installed.
[2018-03-30T02:08:34.352Z] info The plugin content-type-builder has been successfully installed.
[2018-03-30T02:08:35.926Z] info The plugin content-manager has been successfully installed.
[2018-03-30T02:08:43.166Z] info The plugin users-permissions has been successfully installed.
[2018-03-30T02:08:45.265Z] info The plugin email has been successfully installed.
[2018-03-30T02:08:48.587Z] info The plugin upload has been successfully installed.
[2018-03-30T02:08:50.077Z] info The plugin analytics has been successfully installed.
[2018-03-30T02:08:50.079Z] info Linking `strapi` dependency to the project...
[2018-03-30T02:08:50.080Z] info Your new application `puretext` is ready at `/workspace/puretext`.
root@eaba4b438dd6:/workspace# cd puretext
root@eaba4b438dd6:/workspace/puretext# strapi start                                                                                                                                                                                                  
Make sure your MongoDB database is running...`

**Comment by awitherow** [comment]
@Synj24 should this be closed? I am not sure that having no username or password in the prompt is a WORKING solution?

**Comment by derrickmehaffy** [comment]
@awitherow by default mongo doesn't require authentication to connect. This was the problem here.

**Comment by emezeta** [comment]
I know it's closed.  At  https://strapi.io/getting-started  it reads: 

`Fill the database information. The default values should work if you have just installed MongoDB.`

 Could you add something like `Try blanks for user/password.` please? Thanks!

**Comment by lpj145** [comment]
Ok but i'm use Atlas mongodb service, and not needed local mongodb, alright ? how to solve this issue ?

**Comment by zahafyou** [comment]
@lpj145 maybe you'll have information here : [https://github.com/strapi/strapi/issues/432](url)

**Comment by lpj145** [comment]
Invalid url, please check type.

**Comment by zahafyou** [comment]
I edit it : https://github.com/strapi/strapi/issues/432

**Comment by zahafyou** [comment]
use this link youtube  : https://www.youtube.com/watch?v=Ej05tq1220A&ab_channel=MongoDB

**Comment by akobashikawa** [comment]
Hello, I note **config/environments/production/database.json** has property **uri** but not **config/environments/development/database.json**
It works if you add uri property to config/environments/production/database.json, as in 

```json
"settings": {
        "client": "mongo",
        "uri": "mongodb://username:password@hostname.mlab.com:12345/dbname",
        "host": "hostname.mlab.com",
        "port": "12345",
        "database": "dbname",
        "username": "username",
        "password": "password"
},
```

So, to start, you could do this:
```
- $ strapi new myapp
Choose mongo local as in simple case
- edit config/environments/development/database.json
Add uri property
- $ strapi start
```

**Comment by lisaiceland** [comment]
Does NOT work

**Comment by pilotdeveloper** [comment]
Leaving the username, password, and authentication blank worked for me.

**Comment by lisaiceland** [comment]
That's NOT a valid solution ;-)
This is what worked. I have it running on my local machine and mLab Mongo instance in the sandbox and also in the mongoDB clusters.
SOLUTION: What needs to happen is that you need to take out any "@" symbols in the password. The parser reads that as part of the connection string and aborts. That's it.

**Comment by emmajnrk** [comment]
try this in ur config/environments/development/database.json
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "uri": "mongodb://localhost:27017/dbappname",
        "port": 27017,
        "database": "server"
      },
      "options": {
        "ssl": false
      }
    }
  }
}
```
