### ISSUE TITLE
Missing media fields in ctx.state.user

### ISSUE THREAD

**Issue by benjamincanac** [strapi/strapi#6360]
**Describe the bug**

I want to add an `avatar` to my User model, however I can't get it once uploaded through the `/users/me` route. It is present when loading users from relations and on login.

I noticed it was missing from the `ctx.state.user` variable. Since the `/users/me` route returns this variable, media fields are missing.

**Steps to reproduce the behavior**

1. Add an `avatar` or any other media field to the User model
2. Login will get you the `avatar`
3. Call `/users/me`
4. No `avatar` field

**Expected behavior**

Expected to find the media fields added to the User model in the `/users/me` route.

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: v3.0.0
- Database: pg
- Operating system: Mac os

**Comment by derrickmehaffy** [comment]
Please completely fill out the bug report template and include the following:

```
**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:
```

**Comment by aksdevac** [comment]
@benjamincanac by default it will populate only role relation you will need to customise user-permissions extension's User's contoller.
https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#plugin-extensions

**Comment by benjamincanac** [comment]
Hey,

So I ended up overriding all the `config/permissions.js` to add my fields here:

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js#L19

Is there no other way to do it?

Thanks!

**Comment by aksdevac** [comment]
@benjamincanac if you want that only in users/me api you should override that controller (https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/User.js#L44) instead.
Generally so many models are related to User so its not good idea to populate all data in all authenticated requests.

**Comment by benjamincanac** [comment]
@aksdevac I don't see how I can override this controller instead. The user is already populated, you're suggestion is to query user again in `User.me`?

**Comment by aksdevac** [comment]
@benjamincanac yes you will need to query the user again, don't pass second param in findOne it should populate all relational fields by default.

**Comment by benjamincanac** [comment]
@aksdevac Ok thank you, I dit it this way!

**Comment by danielehrhardt** [comment]
What is the reason to not populate media fields to /users/me?

**Comment by derrickmehaffy** [comment]
> What is the reason to not populate media fields to /users/me?

https://github.com/strapi/strapi/pull/4540
