### ISSUE TITLE
Status Page Unexpected Output 

### ISSUE THREAD

**Issue by lpanjwani** [strapi/strapi#6363]
**Describe the bug**
Strapi Main Page/Status Page shows weird HTML response 

**Steps to reproduce the behavior**
1. Place Custom index.html inside /public

**Expected behavior**
Remove All Server-Side Variables

**Screenshots**
![image](https://user-images.githubusercontent.com/10087186/82937038-8ac56f00-9fa0-11ea-8c64-c2ef62fbcb5d.png)

**Code snippets**
index.html is taken from [Strapi Github](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/public/index.html)

**System**
- Node.js version: **v12.x**
- NPM version: **6.14.4**
- Strapi version: **3.0.0**
- Database: **Mangoose**
- Operating system: **Ubuntu 18.04 LTS**

**Additional context**
This bug is happening after update from beta.20+. I have taken a new project and it is still showing the bug in that too.

**Comment by alexandrebodin** [comment]
Hi, Make sure you followed the previous migration guide. What you are experiencing is because you missed a migration step from beta.19 to beta.20: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html#index-page

Closing as it will be solved once migrated
