### ISSUE TITLE
Server wasn't able to start properly. TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by FamilyMan** [strapi/strapi#6369]
**Describe the bug**
On npm run strapi dev, I get the following error:
Server wasn't able to start properly.
TypeError: Cannot read property 'url' of undefined
at Object.initialize ...\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:114:45

which is the endpoint here:
        serverParams.playground = {
          endpoint: `${strapi.config.server.url}${strapi.plugins.graphql.config.endpoint}`,
          shareEnabled: strapi.plugins.graphql.config.shareEnabled,
        };

**Steps to reproduce the behavior**

Everything was working fine using 3.0.0-beta.20.3. I tried to update to 3.0.0 and got this error. I have now gone back to using beta.20.3 and yet this error still persists.

**Expected behavior**
Server to start

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.6.3 
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.3 
- Database:
- Operating system: Windows 10

**Additional context**

**Comment by derrickmehaffy** [comment]
The proxy settings have changed in the migration: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html#migrating

**Comment by asdutoit** [comment]
Hi @derrickmehaffy , I had exactly the same issue. 
Found the problem to be that the `strapi.config.server` returned "undefined".  Why this happened, I don't know.  

I just reinstalled the package strapi-plugin-graphql and it seemed to have resolved my issue.  
Maybe it can work for you too.

**Comment by wokalamps** [comment]
I got this error after updating 3.0.0-beta.19.3 to 3.0.0-beta.19.4. Just wanted to start updating to 3.0.4 step bay step but hanging at the first step. Reinstalling strapi-plugin-graphql didn't work.

` error TypeError: Cannot read property 'url' of undefined
    at Object.initialize (...\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:119:45)
    at Promise.resolve.then ...\node_modules\strapi\lib\hooks\index.js:37:28)
`

**Comment by wokalamps** [comment]
(This is for update 3.0.0-beta.19.3 to 3.0.0-beta.19.4.)
I got it working. It seems that the caret in the strapi-plugin-graphql version entry was the problem (But not sure. Did so many tries.) The package.json it worked with looks like this:
```
"dependencies": {
    "knex": "<0.20.0",
    "slugify": "^1.4.0",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.20",
    "strapi-admin": "3.0.0-beta.20",
    "strapi-connector-bookshelf": "3.0.0-beta.20",
    "strapi-plugin-content-manager": "3.0.0-beta.20",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20",
    "strapi-plugin-email": "3.0.0-beta.20",
    "strapi-plugin-graphql": "3.0.0-beta.20",
    "strapi-plugin-upload": "3.0.0-beta.20",
    "strapi-plugin-users-permissions": "3.0.0-beta.20",
    "strapi-utils": "3.0.0-beta.20"
  },
```
before I had
`"strapi-plugin-graphql": "^3.0.0-beta.20",`

**Comment by derrickmehaffy** [comment]
@wokalamps glad to hear it, I'm going to  mark this as closed, if anyone else has the same problem do feel free to reply back.

**Comment by nathanhannig** [comment]
> I got a similar error
> 
> `[2020-10-16T04:54:15.980Z] debug ⛔️ Server wasn't able to start properly. [2020-10-16T04:54:15.982Z] error TypeError: Cannot read property 'includes' of undefined at Object.isPrivateAttribute 

For me this issue was caused by package.json allowing later versions to be installed
``"strapi-plugin-graphql": "^3.0.5",``

Change it to:

`"strapi-plugin-graphql": "3.0.5",`
