### ISSUE TITLE
No scroll when adding an entry

### ISSUE THREAD

**Issue by awdriggs** [strapi/strapi#6370]
**Describe the bug**
When I try to add an entry to my collection, there is no scrolling happening so I cannot reach some fields without changing the magnification of my browser.

**Steps to reproduce the behavior**

1. Go to a collection type
2. Click "Add new"
3. If there are many fields, the last one will be off the viewport. There is not scroll happening.

**Expected behavior**
I expect to be able to scroll to see the other fields

**Screenshots**
100% browser magnification
![image](https://user-images.githubusercontent.com/1815808/82968976-8303cb80-9f9c-11ea-9a25-7363fb8974bc.png)

80% browser magnification
![image](https://user-images.githubusercontent.com/1815808/82968995-92831480-9f9c-11ea-904f-a412944b0ce6.png)

**System**

- Node.js version: v8.10.0
- NPM version: 3.5.2
- Strapi version: v3.0.0-beta.20.3
- Database: mongodb
- Operating system: Ubuntu 18.04.3 (LTS) x64
- Strapi is running in a docker container with another container running an nginx proxy

**Comment by fadhilx** [comment]
Can you provide us what browser did you use? i tested it, it works on chrome and firefox.

**Comment by awdriggs** [comment]
So this was happening on Chrome Version 81.0.4044.138

I relaunched, now on version 83.0.4103.61. Problem Resolved! Working on firefox as well.
