### ISSUE TITLE
Can´t get strapi to work

### ISSUE THREAD

**Issue by creativtools** [strapi/strapi#6383]
I followed the quick start guide, but I can´t get strapi to work.

with the flag --quickstart doesn´t auto start;
with 'yarn develop', just show 'Done in X seconds';
The only command that seems to do something is 'yarn strapi watch-admin", it starts the server on 'localhost:8000', but in the browser nothing happens, just showing a loading circle.

am I missing something?

**System**

- Node.js version: 12.14.0
- NPM version: 6.14.5
- Strapi version: 3.0.0
- Database: sqlite3
- Operating system: Osx 10.11.6

**Comment by derrickmehaffy** [comment]
@creativtools we need more information to be able to help you. What kind of errors are you getting?

**Comment by creativtools** [comment]
> @creativtools we need more information to be able to help you. What kind of errors are you getting?

I was able to make it work using "npm i -g strapi@alpha", not sure why it doesn´t work with the quick guide on the site.
Anyway, thank you for your time.
