### ISSUE TITLE
Migration from 3.0.0-beta to 3.0.0 stable failed (implemented with migration guide)

### ISSUE THREAD

**Issue by karelnet** [strapi/strapi#6385]
**Describe the bug**
Server keeps restarting again and again with message :
`File changed: C:\Users\karel\Node\librairie\config\locales\fr_fr.json`
Cannot access admin at all (blank page)

**Steps to reproduce the behavior**
Follow the migration guide to change structure of config files : database.js, middleware.js, server.js
Clean build and start

**Expected behavior**
Access to panel

**Code snippets**
config/server.js
```
module.exports = ({ env }) => ({
  host: env('HOST', 'localhost'),
  port: env.int('PORT', 1337),
  // url: `http://localhost:1337`,
  admin: {
    url: '/dashboard',
    autoOpen: true,
  },
});
```
config/database.js
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'mysql',
        host: env('DATABASE_HOST', 'localhost'),
        port: env.int('DATABASE_PORT', 3306),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', 'strapi'),
        password: env('DATABASE_PASSWORD', 'strapi'),
      },
      options: {},
    },
  },
});
```
config/env/development/database.js
```
module.exports = {
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "mysql",
        database: "librairie",
        host: "127.0.0.1",
        port: 3306,
        username: "root",
        password: ""
      },
      options: {}
    }
  }
}
```
middleware.js
```
module.exports = {
  timeout: 100,
  load: {
    before: ['responseTime', 'logger', 'cors', 'responses', 'gzip'],
    order: [
      "Define the middlewares' load order by putting their name in this array is the right order",
    ],
    after: ['parser', 'router'],
  },
  settings: {
    favicon: {
      path: "favicon.ico",
      maxAge: 86400000
    },
    public: {
      path: './public',
      maxAge: 60000,
    },
    language: {
      enabled: true,
      defaultLocale: "fr_fr",
      modes: [
        "query",
        "subdomain",
        "cookie",
        "header",
        "url",
        "tld"
      ],
      cookieName: "locale"
    },
    request: {
      session: {
        enabled: true,
        client: "cookie",
        key: "strapi.sid",
        prefix: "strapi:sess:",
        secretKeys: ["mySecretKey1", "mySecretKey2"],
        httpOnly: true,
        maxAge: 86400000,
        overwrite: true,
        signed: false,
        rolling: false
      },
      logger: {
        level: "debug",
        exposeInContext: true,
        requests: true
      },
      parser: {
        enabled: true,
        multipart: true
      }
    },
    response: {
      gzip: {
        enabled: false
      },
      responseTime: {
        enabled: false
      },
      poweredBy: {
        enabled: true,
        value: "Strapi <strapi.io>"
      }
    },
    security: {
      csp: {
        enabled: true,
        policy: ["block-all-mixed-content"]
      },
      p3p: {
        enabled: false,
        value: ""
      },
      hsts: {
        enabled: true,
        maxAge: 31536000,
        includeSubDomains: true
      },
      xframe: {
        enabled: true,
        value: "SAMEORIGIN"
      },
      xss: {
        enabled: true,
        mode: "block"
      },
      cors: {
        enabled: true
      },
      ip: {
        enabled: false,
        whiteList: [],
        blackList: []
      },
    },
  },
};
```

**System**

- Node.js version: 10.17.0
- NPM version: 6.13.1
- Strapi version: 3.0.0 stable
- Database: MySQL
- Operating system: Windows

**Comment by alexandrebodin** [comment]
Just reproduced it. WIll make a fix for 3.0.1

**Comment by karelnet** [comment]
That was it ! Thank you for your support and quick responsiveness @alexandrebodin

**Comment by gtamas** [comment]
@alexandrebodin 
@karelnet 

I have a similar issue. After upgrade to 3.0 stable, I can access the admin panel, but none of the custom middlewares seem to be loaded. The built-in ones don't produce any error but they don't react to config changes either.

config/middleware.js

`module.exports = ({ env }) => ({
  timeout: 100,
  load: {
    before: ['requestId', 'httpLogger', 'responseTime', 'logger', 'requestLogger', 'cors', 'responses', 'gzip'],
    order: [],
    after: ['parser', 'router', 'nyb', 'helmet', 'errorHandler'],
  },
  settings: {
    public: {
      path: './public',
      maxAge: 60000,
      defaultIndex: env.bool('CMS_DISPLAY_INDEX', true),
    },
    favicon: {
      path: 'favicon.ico',
      maxAge: 86400000,
    },
    language: {
      enabled: true,
      defaultLocale: 'hu_hu',
      modes: ['query', 'subdomain', 'cookie', 'header', 'url', 'tld'],
      cookieName: 'locale',
    },
    session: {
      enabled: true,
      client: 'redis',
      settings: {
        host: env('CMS_REDIS_HOST', 'localhost'),
        port: env.int('CMS_REDIS_PORT', 6379),
        database: env.int('CMS_REDIS_DATABASE', 10),
        password: env('CMS_REDIS_PASSWORD'),
      },
      key: 'strapi.sid',
      prefix: 'strapi:sess:',
    },
    logger: {
      level: env('CMS_LOG_LEVEL', 'debug'),
      exposeInContext: true,
      requests: false,
    },
    parser: {
      enabled: true,
      multipart: true,
    },
    gzip: {
      enabled: true,
    },
    responseTime: {
      enabled: env('NODE_ENV') === 'production' ? false : true,
    },
    poweredBy: {
      enabled: false,
    },
  },
});
`
Is this config not correct?

For example, truning off poweredBy above still produces the X-Powered-By header in the response. Same applies to responseTime. If I set enabled=false, the header is still there.

How to load middlewares in 3.0?

**Comment by gtamas** [comment]
Actually I found it... the file is correct, but if the old config file also exists, it doesn't work.
So you can't have both middleware.js and the old middleware.json in the same dir.

Also, it seems once you have middleware.js, old config files in env directories don't work anymore. Like for example security.json is not taken into account, even though its contents hasn't been migrated to middleware.js.

**Comment by alexandrebodin** [comment]
Yes if we supported the old files you wouldn't have to migrate :) You need to migrate all the files first :D

**Comment by gtamas** [comment]
Yeah that makes sense, but shouldn't it print some kinda error in this case? I mean, it just fails silently. 
If someone accidentally leaves one of the old files there it should at least print s warning.
Anyway, thx, I'll migrate the rest then.

**Comment by alexandrebodin** [comment]
As we support both js and json files if you have the same file at the same place with js and json they will conflict with each other and it depends on the load order. We could try to log something for this case. for the files in a folder that we don't load we just don't know it is here because we don't look for it.

Thanks for the reports this always helos us improve the product !

**Comment by jeremy-hubsy** [comment]
Hello @alexandrebodin 

**Describe the bug**
Since I update my app to 3.0.1 version from strapi I can't use the constructEvent method from stripe because I can't get the raw request body from strapi. 
I don't know if the parser object in middleware.js works as expcted. 

If I `console.log(ctx.request.body[unparsed]) i got` undefined`

And Stripe send me back this error message
` Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe?`

**Steps to reproduce the behavior**

1. Install the stripe cli
2. Create a simple hook in you strapi app
3. Start forwarding to your strapi app the events from the stripe-cli (eg: stripe listen --forward-to localhost:1337/hook)
4. Launch an event with your stripe cli (e.g.: stripe trigger payment_intent.created)
5. See error ( Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

**Expected behavior**
unparsed data, instead got undefined

**Code snippets**
config/middleware.js
```
module.exports = {
  timeout: 100,
  load: {
    before: ["responseTime", "logger", "cors", "responses", "gzip"],
    order: [
      "Define the middlewares' load order by putting their name in this array is the right order",
    ],
    after: ["parser", "router"],
  },
  settings: {
    favicon: {
      path: "favicon.ico",
      maxAge: 86400000,
    },
    public: {
      path: "./public",
      maxAge: 60000,
    },
    public: {
      path: "./public",
      maxAge: 60000,
    },
    language: {
      enabled: true,
      defaultLocale: "en-us",
      modes: ["query", "subdomain", "cookie", "header", "url", "tld"],
      cookieName: "locale",
    },
    request: {
      session: {
        enabled: true,
        client: "cookie",
        key: "strapi.sid",
        prefix: "strapi:sess:",
        secretKeys: ["mySecretKey1", "mySecretKey2"],
        httpOnly: true,
        maxAge: 86400000,
        overwrite: true,
        signed: false,
        rolling: false,
      },
      logger: {
        level: "debug",
        exposeInContext: true,
        requests: true,
      },
      parser: {
        enabled: true,
        multipart: true,
        includeUnparsed: true,
      },
    },
    response: {
      gzip: {
        enabled: false,
      },
      responseTime: {
        enabled: false,
      },
      poweredBy: {
        enabled: true,
        value: "Strapi <strapi.io>",
      },
    },
    security: {
      csp: {
        enabled: true,
        policy: ["block-all-mixed-content"],
      },
      p3p: {
        enabled: false,
        value: "",
      },
      hsts: {
        enabled: true,
        maxAge: 31536000,
        includeSubDomains: true,
      },
      xframe: {
        enabled: true,
        value: "SAMEORIGIN",
      },
      xss: {
        enabled: true,
        mode: "block",
      },
      cors: {
        enabled: true,
      },
      ip: {
        enabled: false,
        whiteList: [],
        blackList: [],
      },
    },
  },
};

```

```
const unparsed = require("koa-body/unparsed.js");
const constructStripeEvent = (ctx, synclyEvent = false) => {
  const endpointSecret = synclyEvent
    ? process.env.STRIPE_SYNCLY_HOOK_SECRET
    : process.env.STRIPE_CONNECT_HOOK_SECRET;
  const signature = ctx.request.headers["stripe-signature"];

  ctx.stripeEvent = stripe.webhooks.constructEvent(
    ctx.request.body[unparsed],
    signature,
    endpointSecret
  );
};

```

**Comment by alexandrebodin** [comment]
Hi you should not be putting the middleware setting in a sub property (request, response and security should be removed) All middlewares should be configured at the root level of settings:

```
module.exports = {
//..
  settings: {
    parser: {},
    cors: {},
  }
}
```

FYI if you don't customize some of the middlwares you can just remove them form the settings to simplify them a lot.

**Comment by jeremy-hubsy** [comment]
Thanks a lot @alexandrebodin
