### ISSUE TITLE
The config file for plugin is missing

### ISSUE THREAD

**Issue by rvigneshw** [strapi/strapi#6388]
**Describe the bug**
The config file for plugin is missing

**Steps to reproduce the behavior**

1. Go to 'the folder where strapi is created'
2.open config directory

**Expected behavior**
a file like plugin.js to be prese
![Screenshot (134)](https://user-images.githubusercontent.com/22572374/83038323-75ad1680-a05a-11ea-9928-74e3dd29bce9.png)
nt

**Screenshots**

**Code snippets**

**System**

- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0
- Database:sqlite
- Operating system:windows 10

**Comment by rvigneshw** [comment]
forgot to look into new way of configuration

**Comment by sabzo** [comment]
@rvigneshw What is the new way of configuration? Running into same issue.

**Comment by derrickmehaffy** [comment]
> @rvigneshw What is the new way of configuration? Running into same issue.

https://github.com/strapi/strapi/issues/6388#issuecomment-730628842
