### ISSUE TITLE
Trying to load admin panel on port 8000 using --watch-admin hangs

### ISSUE THREAD

**Issue by huevoncito** [strapi/strapi#6398]
Hello! Thanks for this great product. Enjoying it so far.

However, I'm now trying to modify the admin panel and having trouble.

`yarn develop --watch-admin` seems to work. It launches the server at `localhost:1337` and also opens a new window to `localhost:8000` for the admin development. 

But that window doesn't load anything. I see the loader (below) but no content ever loads. 

![Screen Shot 2020-05-27 at 3 10 17 PM](https://user-images.githubusercontent.com/4283521/83062216-48497400-a02c-11ea-9632-867fa303c75e.png)

I have now tried in Brave and Firefox. Same result.

Thanks again.

**Comment by cyp3rius** [comment]
@huevoncito follow the workaround proposed here: https://github.com/strapi/strapi/issues/6364#issuecomment-634556827

I've faced same issue and it helps.

**Comment by huevoncito** [comment]
@cyp3rius That did the trick. Thank you!

**Comment by soupette** [comment]
I am reopening the issue has we need to fix it!
@petersg83 is already on it.
 
In the mean time, in order for you to keep developing you can change this [line](https://github.com/strapi/strapi/blob/123ce203e54e4faeb83807355257c9e2dc95fa39/packages/strapi-admin/admin/src/app.js#L137) to `backendURL: 'http://localhost:1337'` using the common customisation system. Once your developments are finished you will need to delete the customised `admin/src/app.js` file in your app will work just fine.

**Comment by bikoev** [comment]
Here is my solution https://github.com/strapi/strapi/issues/5877#issuecomment-639414736
