### ISSUE TITLE
Edit generated API data  from content manager lose data

### ISSUE THREAD

**Issue by suanter** [strapi/strapi#640]
Hi all, i am working with models that includes JSON. I have a Model  that stores the following:{name:"name a", age:23, location: Map { "name": "location a", "_id": "5a78e0cb433c5f62c92ee", "id": "5a78e0cb433c5f17c92ee", "latlng": Map { "lat": "25.7634", "lng": "-60.1933" } }. 

The problem is when i edit this record with the content-manager panel. If i only edit the field ej. "name" somehow the field location also changes, it removes the entire json and store only an id. Very strange behavior.

**Comment by suanter** [comment]
Hi All, I realized one thing.... 
use case:
 from the mobile app i send  like structure : {"product name", redact:{id:"2342423423",name:"andres","comment":"my product coment" } } to this model Product .
Result:  The API stores all the data correctly but the admin app changes the json structure.

Issue: When i edit, any field, of this record from the content-manager - admin GUI ) and save it , apparently the module reads the field "_id" or "id" from the JSON and this is when it mess up. 

Now... if i change  form the json structure  the attribute id for something (idCom) else ej. : {"product name", redact: {idCom:"2342423423",name:"andres","comment":"my product coment" } }.  it works as expected.  We can now edit any field with the content-manager-admin GUI) and it works properly.

**Comment by soupette** [comment]
Hi @suanter can you send me your models so I can reproduce exactly the behavior? Maybe on slack?

**Comment by suanter** [comment]
api / Product
{
  "connection": "default",
  "collectionName": "product",
  "info": {
    "name": "product",
    "description": ""
  },
  "options": {
    "hasTimestamps": true
  },
  "attributes": {
    "username": {
      "type": "string"
    },
    "action": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "idowner": {
      "type": "string"
    },
    "prodCat": {
      "type": "json"
    },
    "users": {
      "collection": "user",
      "via": "products",
      "dominant": true,
      "plugin": "users-permissions"
    }
  }
}

// category schema


{
  "connection": "default",
  "collectionName": "category",
  "info": {
    "name": "category",
    "description": ""
  },
  "options": {
    "hasTimestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "action": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "users": {
      "collection": "user",
      "via": "products",
      "dominant": true,
      "plugin": "users-permissions"
    }
  }
}

**Comment by suanter** [comment]
Project created with 3.0.0-alpha.8 but running with 3.0.0-alpha.9.1.

**Comment by lauriejim** [comment]
Can you please try to create new project with last version of Strapi.
Create in some clicks your model and try again. 

Or try to start your app with the same version of Strapi as your app.

**Comment by soupette** [comment]
What is status on this issue?

**Comment by suanter** [comment]
Hi, sorry for the delay..

Before describing the error, this is my actual configuration: 

- Node v9.4.0
- Strapi  3.0.0-alpha.11.3
- The strapi app was also updated ( I re-created all models and code..etc ).So i wanted to be sure that it was not my code...


Situation:
1) I create a User. 
2) I login and get the user id(_id)
3) I use this id to create an object (License) and associated this user to this license: Ej.

var license={
name:”Package Standard”,
users: [{_id:c6e5a6171e9789587d2e50f79a728506}]
}

An get this Error:
error Cast to ObjectId failed for value "<Buffer 5a d4 f7 8b c4 a5 d8 00 11 29 15 9c>" at path "_id" for model "License"


Not sure why!! it was working properly before…


I tried many things..  
a) running strapi in local host
b)running strapi in a docker container..

None work…

Any Idea and thanks thanks you very much..

Regards, 

Jaime

**Comment by soupette** [comment]
@suanter how can I reproduce the issue?

It is the admin which is breaking or another app?

**Comment by suanter** [comment]
Hi, I fix it. Apparently it was some code that, in the process of creating a new instance (via docker), old code was still there. What i did was to rebuild the admin. Everything is fine now. Although i noticed one thing... that these methods are not working properly.


// Before saving a value.
  // Fired before an `insert` or `update` query.
  // beforeSave: async (model) => {},

  // After saving a value.
  // Fired after an `insert` or `update` query.
  // afterSave: async (model, result) => {},

  // Before fetching all values.
  // Fired before a `fetchAll` operation.
  // beforeFetchAll: async (model) => {},

  // After fetching all values.
  // Fired after a `fetchAll` operation.
  // afterFetchAll: async (model, results) => {},

  // Fired before a `fetch` operation.
  // beforeFetch: async (model) => {},

  // After fetching a value.
  // Fired after a `fetch` operation.
  // afterFetch: async (model, result) => {},

  // Before creating a value.
  // Fired before an `insert` query.
  //  beforeCreate: async (model) => {},

  // After creating a value.
  // Fired after an `insert` query.
   //afterCreate: async (model, result) => {},

  // Before updating a value.
  // Fired before an `update` query.
  // beforeUpdate: async (model) => {},

  // After updating a value.
  // Fired after an `update` query.
  // afterUpdate: async (model, result) => {},

  // Before destroying a value.
  // Fired before a `delete` query.
  // beforeDestroy: async (model) => {},

  // After destroying a value.
  // Fired after a `delete` query.
  // afterDestroy: async (model, result) => {}



I made some test because i wanted to send an email after Update or Create .They are not working the way they suppose to be. Sometime they are triggered more than once.. very strange…

Ej. 
// beforeSave: async (model) => {},




Thanks you very much for your help.

Regards,


Jaime
