### ISSUE TITLE
Bad Request 400 - Forgot-Password request.  Response Data and Message empty

### ISSUE THREAD

**Issue by asdutoit** [strapi/strapi#6406]
**Describe the bug**
Hi There, 
We have an issue when submitting either a POST request to /auth/forgot-password or its equivalent in graphql. 

Bad Request Error 400.

This is the response from a POST request using Postman:
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {},
    "data": {}
}
```

This is the error from graphql playground

```javascript
  "errors": [
    {
      "message": "Bad Request",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "forgotPassword"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": 400,
          "data": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": {},
            "data": {}
          },
          "stacktrace": [
            "Error: Bad Request",
            "    at checkBadRequest (/Users/stephandutoit/Dropbox/Training/Strapi/my-project/node_modules/strapi-plugin-users-permissions/config/schema.graphql.js:11:23)",
            "    at resolver (/Users/stephandutoit/Dropbox/Training/Strapi/my-project/node_modules/strapi-plugin-users-permissions/config/schema.graphql.js:225:11)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "forgotPassword": null
  }
}
```

**Steps to reproduce the behavior**

This issue happened on first attempt.  Not sure why it did not work from the start.

**Expected behavior**

Response should be:
`{ ok:  true }`

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v14.2.0
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database: mongodb
- Operating system: Mac OS catalina

**Comment by asdutoit** [comment]
Im not sure what caused the issue.  Anyways, I have upgraded to the latest release of Strapi 3.0.1 and all seems to be resolved.

**Comment by ScottAgirs** [comment]
I have the same issue, with version 3.0.1, re-installed the node modules and all. @asdutoit any chance you might have tweaked something else along with the version upgrade that could have solved this for ya?

**Comment by asdutoit** [comment]
Hi @ScottAgirs,  I mainly installed Strapi 3.0.1 which resolved my issues. 
However, I also noticed that using Node 14 caused some related issues.  Downgrading to Node 12.17 or 12.18 should ensure you are fully compatible with Strapi and its dependencies. 

Should your issue still persist, I would recommend you add some console.logs in the actual controller.  For example, I had issues in the auth/forgot-password controller.  The controller can be accessed in the following location:  
`/node_modules/strapi-plugin-users-permissions/controllers/Auth.js`

and look for the function: 
`async forgotPassword(ctx) {...omitted}`

Try and work through the responses / results from each section in the function.   For example, try and console.log(email) to ensure the email is pulled from the ctx. 

Let me know if this helped.
