### ISSUE TITLE
graphql AND condition

### ISSUE THREAD

**Issue by bfourgeaud** [strapi/strapi#6408]
Hello,

I saw on the documentation that strapi doesn't allow AND condition on the graphql plugin.
I was wondering how I could do to find objects in my database that matches both conditions.

I have :

```
travels:[
 {
  name: "France 1",
  cities: [ {name:"Lyon"},  {name:"Paris"} ]
 },
 {
  name: "France 2",
  cities: [ {name:"Lyon"},  {name:"Marseille"} ]
 }
]
```

How could I find all the travels which are going through both cities Paris & Lyon ?

I tried whithout success : 
```
"cities": {
      "name_in": "Paris",
      "name_in": "Lyon"
    }
```

I was unable to find any way of using a filter like javascript would do with **Array.every()**

Is that a known issue, or is there a solution to that ?
Thanks,

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
