### ISSUE TITLE
Strapi 3.0 stable: could not load admin login page.

### ISSUE THREAD

**Issue by gtamas** [strapi/strapi#6409]
**Describe the bug**
Admin panel cannot be loaded, because port seems to be unused.  All I can see is the loader spinning. The page never loads.

**Steps to reproduce the behavior**

1. Go to 'http://127.0.0.1:1337/admin'
2. See error

**Expected behavior**
The login screen should show up.

**Code snippets**
I have this in config/server.js

```
module.exports = ({ env }) => ({
  host: env('CMS_HOST', '127.0.0.1'),
  port: env.int('CMS_PORT', 1337),

  cron: {
    enabled: false
  },
  admin: {
    autoOpen: false
  }
});
```

**System**

- Node.js version: 12.16
-  NPM version: 6.14
- Strapi version: 3.0 stable
- Database: MOngoDb
- Operating system: OSX

**Additional context**

The error shows up while loading the http://127.0.0.1:1337/admin, and it is caused by an XHR call whose request URL looks like this: http://127.0.0.1/users-permissions/init. The port number should 1337 but it is not used, so it's requesting the wrong URL.

**Comment by derrickmehaffy** [comment]
`url: env('CMS_ADMIN_URL', 'http://127.0.0.1:1337/admin'),` you shouldn't be hard coding the full path there. If you don't intend to change it from the default `/admin` then delete that key.

**Comment by gtamas** [comment]
@derrickmehaffy 
Ok Thank you! I changed it but I'm still getting same error.

Is this a bug? 3.0 is supposed to be stable, is that correct? I'm trying to migrate from beta20 to the stable version.

**Comment by gtamas** [comment]
@derrickmehaffy 
@soupette 
3.0 is the stable version, but is it also production ready? I thought 3.0 means 3.0 prod.

**Comment by derrickmehaffy** [comment]
It is production ready yes (I and many others are using it as such)

Is your project code somewhere public that I can look at such as on GitHub?

**Comment by gtamas** [comment]
Unfortunately it's not public. :( Which part of the source do you wish to see? Maybe I could copy those fragments here. 
This project worked fine with beta20, however, since I upgraded to 3.0 stable it stopped working.

I followed this guide:

https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html

**Comment by gtamas** [comment]
@derrickmehaffy 
My bad, it works now. 

Apparently, if I rebuild the admin it works. I thought I need to do that only once, and after that the watcher will take care of incremental builds. But if you change config/server.js, you actually need to rebuild the entire thing:

npm run build --clean

Thanks for the help though!

**Comment by derrickmehaffy** [comment]
No problem, but yes any change that affects the admin it needs to be rebuilt.

**Comment by jerson-dp** [comment]
This app is frustrating. Always showing the loading icon after simply install the new pluggin, check the backend terminal, no errors or anything...No idea what is going on

**Comment by soupette** [comment]
@jerson-dp in your plugin `./admin/src/index.js` file can you try to change this [line](https://github.com/strapi/strapi/blob/db6a77697779dcd3434e295f5689faa15080c775/packages/strapi-generate-plugin/files/admin/src/index.js#L21) to `isReady: true` ?
