### ISSUE TITLE
I can login mongo admin using password. But when i try to install it show error

### ISSUE THREAD

**Issue by mrksohag** [strapi/strapi#641]
**Node.js version**:
v9.5.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.1
**Operating system**:
Ubuntu 16.04 LTS

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
UnhandledPromiseRejectionWarning: MongoError: Authentication failed.
    at /var/www/html/nodejs/tmp/node_modules/mongodb-core/lib/connection/pool.js:595:61

**If the current behavior is a bug, please provide the steps to reproduce the problem**
i can login in terminal using the command mongo -u username -p pasword --authenticationDatabase admin

**What is the expected behavior?**
Should be install properly.

**Comment by lauriejim** [comment]
Hello @mrksohag can you be more precise on the steps to reproduce the problem please

**Comment by Rzeszow** [comment]
I had the same error. I've created a new database and it's working.

**Comment by mrksohag** [comment]
@lauriejim please check following image. Thanks.
![screenshot from 2018-02-20 01-18-57](https://user-images.githubusercontent.com/16557162/36394058-a9c4d5da-15dc-11e8-8061-f75733bba654.png)

**Comment by lauriejim** [comment]
@mrksohag I can't reproduce your issue. Can you try to log and debug this file https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/utils/connectivity.js. I think it's here something is wrong for your mongo configuration.

**Comment by lauriejim** [comment]
We had authenticationDatabase option here https://github.com/strapi/strapi/pull/753
