### ISSUE TITLE
I can't have more than 100 records with graphQL

### ISSUE THREAD

**Issue by matthieusibille** [strapi/strapi#6410]
I can't figure out how to request more than 100 records with graphQL

I tried to increase the limit in my query but it doesn' work 
```
query{
	questions(limit:200, sort:"key:asc"){
    key
  }
}
```
I tried to add a ./config/plugins.js in STRAPI as recommanded by the documentation but it didn't work either
```
module.exports = {
    graphql: {
      endpoint: '/graphql',
      tracing: false,
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 300,
    },
  };
```

I'm all out of ideas, anyone has a solution for this?
Thank you for your help

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 19.5
- Database: mongo db
- Operating system: windows

**Comment by derrickmehaffy** [comment]
`Strapi version: 19.5` You are on the beta, the documentation is for the stable release.

Either:
- Update to the stable release
- See the beta docs: https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#configurations

**Comment by matthieusibille** [comment]
@derrickmehaffy oh i didn't see the news, that's great !
I'll update STRAPI then, thank you
