### ISSUE TITLE
Migrating to Strapi 3 stable breaks configurations

### ISSUE THREAD

**Issue by devskope** [strapi/strapi#6411]
**Describe the bug**
Migrating to Strapi 3 stable breaks configurations `./config/environments/*`

**Comment by devskope** [comment]
**Fix**
Renaming `./config/environments/*` to `./config/env/*` fixes this issue for me.

**Comment by derrickmehaffy** [comment]
This is intended to ensure people read the migration guide: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html
