### ISSUE TITLE
some configuration don't work on 3.0.0

### ISSUE THREAD

**Issue by wysher** [strapi/strapi#6416]
**Describe the bug**
I tried to run cron tasks and change admin.url, but it does not work with strapi@3.0.0.
Tested with latest beta and it works like a charm.

1. Cron
I did some testing in functions/bootstrap.js for cron config:
as expected `console.log(strapi.config.server.cron.enabled)` returns false
when set in server.js `module.exports = { cron: {  enabled: true } }` i got true. But cron tasks do not runs.

2. Admin.url
admin.url set to `/dashboard`
localhost:1337/dashboard shows Strapi's 404 page with back link which redirects to /admin. Clicking on it seems to work and it shouldn't because /admin is forbidden.

3. I also tried change middleware.js  with for reques.logger configs, but maybe I did sth wrong (needs more docs?)

```
module.exports = {
    logger: {
      level: 'info',
      exposeInContext: true,
      requests: false
    },
};
// I also tried to move it under settings key.
```

**Expected behavior**
Config works :)

**System**

- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.0
- Database: Sqlite
- Operating system: Linux

**Comment by alexandrebodin** [comment]
Hello. 

I'm going to answer your questions at once but please avoid putting multiple issues into one as it is hard for us to prioritize and follow :) 


1-  Indeed the cron option doesn't work. Until we fix it you can enable it with the middleware config:

```js
module.exports = {
  settings: {
    cron: {
      enabled: true
    }
  }
}
```

This should also answer the thrid question, you need to put middleware config in the `settings` key.


2.  I'm not sure of what you are experiencing. When setting admin.url to /dashboard it works as expected. Did you run yarn build after setting your config ?

**Comment by wysher** [comment]
Hi. Thanks for answering. Admin.url works after rebuild. I also set logger options successfully :)

Happy to hear that cron issue was fixed (so fast).
