### ISSUE TITLE
Docs bug: Redis sessions

### ISSUE THREAD

**Issue by gtamas** [strapi/strapi#6421]
**Describe the bug**
The page below describes Redis as the default session storage, however, Redis connector does not get installed by default.

https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations

**Steps to reproduce the behavior**

1. Go to  'https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations'

**Expected behavior**
Information should be provided about the preferred 3rd pary redis connector, or Redis shouldn't be the default.

**System**

- Node.js version: Node 12.16
- NPM version: 6.14
- Strapi version: 3.0 stable
- Database:
- Operating system:

**Additional context**
There is a package which looks usable, but it's very new. Is this preferred one?

https://www.npmjs.com/package/strapi-connector-redis

**Comment by gtamas** [comment]
Using Redis would be way much better than a session cookie, the former (3.0 beta) default.
Even MongoDB would be better. So if there is a stable and reliable solution, it should be added to the docs.

**Comment by gtamas** [comment]
This issue has been opened 6 days ago and it's about a simple question... someone should get back to me ASAP.

**Comment by lauriejim** [comment]
Hello! Thank you for this question.
I pinged the team to know a little bit more about this.
Will be back soon with a status about session storage.

fyi, we are still a really small team with a community of users that grows super fast.
It's super difficult to answer every questions rapidly.
We are doing our best.

**Comment by gtamas** [comment]
@lauriejim 
Any news on this?

I tried to enable session with redis (following the docs) and I also the above mentioned connector. 
However, when I start up Strapi, it prints this:

(middleware:session) please provide connection for the session store

It starts up without errors though. I can even login, but the appears to be no data in the redis db, so I'm not sure where the session is stored now.

Anyway, Redis is just one option for me, it's a not a must. But I need some way to persist session data, something better than a session cookie. What "clients" are currently supported by Strapi? Only cookie?

**Comment by derrickmehaffy** [comment]
@gtamas No news yes, I will be putting in a PR to change the documentation to reflect the proper default (node memory) but in talking with @lauriejim and @alexandrebodin that middleware is older code that hasn't been updated and won't function correctly currently.

I'll leave this open to allow us to review it, but in the short term I will fix the docs.
