### ISSUE TITLE
Feature request: rich text with formatting options?

### ISSUE THREAD

**Issue by luisnomad** [strapi/strapi#643]
Hi all! 

I am testing Strapi to determine if it fits our needs to integrate it into our stack. For technical people and API related stuff it's perfect. But I miss a more editor-friendly environment. Content fields can be plain text, but if that content very often needs to be formatted. I was wondering if this is going to be an option in the future, or if it's feasible to add that via plugins now.

Thanks!

**Comment by soupette** [comment]
Hi @luisnomad !

It will be an option in the future, we're working on the upload right now but after that we're going to implement it.

A Strapi user posted this https://medium.com/@ceddybi/strapi-rocks-d887c758831e article which explains how to create the rich text editor for the time being.

Hope it will help. If you have more question feel free to join the slack and so can help you.

**Comment by luisnomad** [comment]
Thanks for the answer @soupette, the article was pretty helpful!

Cheers.

**Comment by lauriejim** [comment]
Hi @luisnomad you can also upvote your feature on https://strapi.io/vote page

**Comment by bzhr** [comment]
I like it how the features I need the most (GraphQL, file upload and text formating) are the features that are coming soon!

Is there a road map?

**Comment by lauriejim** [comment]
WYSIWYG is coming soon ! https://github.com/strapi/strapi/tree/wysiwyg

And you can find the roadmap here https://github.com/strapi/strapi/blob/wysiwyg/ROADMAP.md
