### ISSUE TITLE
Foreign keys not getting created on PostgreSQL

### ISSUE THREAD

**Issue by pranab-witbybit** [strapi/strapi#6438]
I have created tables using the admin UI. I have put relations on collections. But the issue is, those fields are not getting a foreign key constraint.

**Comment by alanhr** [comment]
@pranab-witbybit  I'm facing the same problem. How did you fix it?

**Comment by pranab-witbybit** [comment]
I didn't fix it. I browsed through their timeline, and saw they had decided to add the foreign key feature in April - Aug 2020, but later dropped the plan. 

So I finally decided to drop Strapi from my project and chose **AdminBro** with **Sequelize** instead.

**AdminBro** & **ForestAdmin** both are pretty good alternatives of Strapi.

**Comment by lauriejim** [comment]
Here is a related issue - https://github.com/strapi/strapi/issues/2006

**Comment by andre-ab** [comment]
I have the same problem with Mysql, now I don't know if I do this on the mother.
Another problem is the N to M "Many to Many" tables, they do not appear in the webadmin:
Example
TableA> -------- <TableB
a third table is created with the references of the two parent tables
TableA_has_TabelaB

this third table is not shown in webAdmin ...
if I change it in my hand it can give problems ???
