### ISSUE TITLE
Can't generate controller & model by CLI!

### ISSUE THREAD

**Issue by nguyenhoangsin** [strapi/strapi#644]
**Node.js version*8.9.4*:

**npm version*5.6.0*:

**Strapi version*3.0.0-alpha.9.3*:

**Operating system*Win10*:

Hi!
When generate controller & model by CLI, i received the notice:
ERROR (11424 on SIN): No generator called `controller` found.
ERROR (11424 on SIN): No generator called `model` found.
Please help me!

**Comment by Freakspot** [comment]
I ran into the same issue when replicating this using `strapi generate:controller test` in a directory that was generated via `strapi new`. Same thing happened in a clone of this repository.
**However**, running `npm run setup` fixed the issue for both directories, successfully generating my controller.

**Comment by lauriejim** [comment]
Hi @nguyenhoangsin and @Freakspot ! Thank you for this issue.

We will not fix it soon, so to bypass this issue you will have to create new api (`strapi generate:api`) and move generated controller and model and update naming variables and files name.

**Comment by nguyenhoangsin** [comment]
Thank for all! I will close issues.

**Comment by nborko** [comment]
This issue should probably remain open since the documentation does not state that these commands are broken nor provide the alternative mentioned in this issue.  I had to search the closed issues to find this.

**Comment by lauriejim** [comment]
@nborko Yes you are right !

**Comment by nurikabe** [comment]
I think this may now be broken out of the box with alpha.12

**Comment by candacerogue** [comment]
Hi there, have updates been made to adding a model from the CLI?

**Comment by lauriejim** [comment]
Hello! Nothing has been made to add this feature in the CLI.
