### ISSUE TITLE
Reset Password permission is disabled by default

### ISSUE THREAD

**Issue by yurii-sorokin** [strapi/strapi#6440]
**Describe the bug**
Reset Password permission is disabled by default. So you can send an email for a password reset but can't actually reset it.

**Steps to reproduce the behavior**

1. **POST** `/auth/forgot-password { email: 'some@email.com' }`
2. **POST** `/auth/reset-password { code: 'codeFromEmail', password: 'newPassword', ... }`
3. Receive `Forbidden 403`

**Expected behavior**
Password reset successfully.

**System**

- Node.js version: v14.2.0
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: mongodb
- Operating system: MacOs

**Additional context**
I've debugged a code a little and I guess the issue is related to https://github.com/strapi/strapi/pull/5655 (Change Password was renamed to Reset Password) and especially to the following code: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L25

Changing `changepassword` to `resetpassword` might resolve the issue.

**Comment by bsakweson** [comment]
To piggyback on this, I also noticed  the code is pretty long. Is there any documentations on how this code generation be changed to an `x` digits|characters code. At the moment the code is pretty long e.g `10d36318ef4a96b0b240836f7baa8bcbe340d3b3fe1a075e2e67858efa84f6ed89f5fad6f79290cf64068ec054a925808b46a92cc5c4f986f42f279a1a8a1d64`

Cheers.

**Comment by bsakweson** [comment]
I did some additional research, and it seems as if the issue is with authentication. The code is supposed to be JWT that authenticates a user temporarily with limited access to complete this process. Normally, password reset is done before the user is authenticated which explains why we see the 403 error.

**Comment by riyazbhanvadia** [comment]
Hi,

I face same issue and i am able to resolve it with below step.

-  Go to strapi admin

- Click on Roles&Permission in side menu

- You can see two roles there click on public role

- Scroll down you will see **USERS-PERMISSIONS**

- Enable reset password checkbox and click Save.

**Comment by riyazbhanvadia** [comment]
> **Describe the bug**
> Reset Password permission is disabled by default. So you can send an email for a password reset but can't actually reset it.
> 
> **Steps to reproduce the behavior**
> 
> 1. **POST** `/auth/forgot-password { email: 'some@email.com' }`
> 2. **POST** `/auth/reset-password { code: 'codeFromEmail', password: 'newPassword', ... }`
> 3. Receive `Forbidden 403`
> 
> **Expected behavior**
> Password reset successfully.
> 
> **System**
> 
> * Node.js version: v14.2.0
> * NPM version: 6.14.4
> * Strapi version: 3.0.1
> * Database: mongodb
> * Operating system: MacOs
> 
> **Additional context**
> I've debugged a code a little and I guess the issue is related to a PR where Change Password was renamed to Rename Password and especially to the following code: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L25

Hi,

I face same issue and i am able to resolve it with below step.

-  Go to strapi admin

- Click on Roles&Permission in side menu

- You can see two roles there click on public role

- Scroll down you will see **USERS-PERMISSIONS**

- Enable reset password checkbox and click Save.

**Comment by riyazbhanvadia** [comment]
> I did some additional research, and it seems as if the issue is with authentication. The code is supposed to be JWT that authenticates a user temporarily with limited access to complete this process. Normally, password reset is done before the user is authenticated which explains why we see the 403 error.

Hi,

I face same issue and i am able to resolve it with below step.

-  Go to strapi admin

- Click on Roles&Permission in side menu

- You can see two roles there click on public role

- Scroll down you will see **USERS-PERMISSIONS**

- Enable reset password checkbox and click Save.

**Comment by bsakweson** [comment]
That seems to work fine now, thanks for helping out. 

Am I the only one who finds the token to be cumbersome, would it be enough for it to be a simple OTP of say 8 digits or something of that nature?

**Comment by riyazbhanvadia** [comment]
> That seems to work fine now, thanks for helping out.
> 
> Am I the only one who finds the token to be cumbersome, would it be enough for it to be a simple OTP of say 8 digits or something of that nature?

Best way to reset password is having one time use token. Strapi has done that internally so it is good to use inbuilt API.

**Comment by bsakweson** [comment]
I am not sure I followed, `Strapi has done that internally so it is good to use inbuilt API.` What does that mean? Forgive my indulgence, I just started messing with this CMS.

**Comment by riyazbhanvadia** [comment]
Strapi has done that internally so it is good to use inbuilt API means Strapi has reset password api so we dont have to do overhead work for user to have reset password. So its best to use strapi inbuilt api.

**Comment by bsakweson** [comment]
Ah that is what you meant, gotcha. That part definitely works well. Please see my previous riposte, it is updated with more information. In a nutshell, all I am saying is that the token could be much shorter.

**Comment by lauriejim** [comment]
Thank you for reporting this issue. It's an easy issue to fix.
I will continue to review some PR if someone can have a look to the `initialize` function oof the `users-permissions` plugin.
Thank you.

**Comment by litehacker** [comment]
<img width="623" alt="Screen Shot 2020-09-24 at 02 56 01" src="https://user-images.githubusercontent.com/17227327/94082231-7e97d400-fe11-11ea-915e-37818cc7cfba.png">
This was by default, but yet I have `bad request` error. 
 Request:  
```json
{
  "email": "litehacker@mail.ru"
}
```
Address:  
`http://localhost:1337/auth/forgot-password`. 
Response:  
```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {},
    "data": {}
}
```

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by quyetthang122** [comment]
Hi @bsakweson, I am currently looking for a solution to send shorter reset code like 6 digits or OTP sms using firebase. Have you found any solution for it?

**Comment by quyetthang122** [comment]
Hi @bsakweson, I found a temporary solution that we can customize this line `const resetPasswordToken = crypto.randomBytes(64).toString('hex');` in `node_modules/strapi-plugin-users-permissions/controllers/Auth.js` strapi plugin v3.2.4 core, it's not a recommended way we all knew. I hope it could be a temporary solution at the moment.

**Comment by GabrielLiade** [comment]
How can I have access to the code from the email ?

**Comment by Ejazkhan999** [comment]
i have allowed password reset tab still i am not getting access to method. 

![method](https://user-images.githubusercontent.com/61001921/102465624-b52b6680-406f-11eb-8a58-51d76a75e6e1.PNG)
![public](https://user-images.githubusercontent.com/61001921/102465626-b65c9380-406f-11eb-8db6-ee0bf4dc6307.PNG)

**Comment by alexandrebodin** [comment]
Hi @Ejazkhan999  your screenshot shows an invalid URL :) it's repeat `/auth/forgot-password` twice in the url. And if you want to use reset-password the url is /auth/reset-password :)

**Comment by mickhah** [comment]
hello. could somebody explain me how to change password for the strapi login? i have checked resetpassword on under user-permissions. but where do i change the password now?

**Comment by MattieBelt** [comment]
@mickhah these docs should explain you how to implement _reset_ & _forgot_ password: https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#forgotten-reset-password
