### ISSUE TITLE
Cannot deploy Strapi to Google Cloud

### ISSUE THREAD

**Issue by winston0410** [strapi/strapi#6444]
**Describe the bug**
I got the following error when I try to deploy Strapi to Google Cloud:

```
2020-05-30 05:41:04 default[20200530t133735] [2020-05-30T05:41:04.507Z] error Bootstrap function in plugin "users-permissions" failed
2020-05-30 05:41:04 default[20200530t133735] [2020-05-30T05:41:04.509Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

**Steps to reproduce the behavior**

Follow the deployment guide on [Strapi's website](https://strapi.io/documentation/v3.x/deployment/google-app-engine.html). This error was returned after I have `gcloud app deploy`

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.14.1
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database: PostgreSQL
- Operating system: OSX

**Additional context**

**Comment by derrickmehaffy** [comment]
See the following issues:

https://github.com/strapi/strapi/issues/6335
https://github.com/strapi/strapi/issues/6284
https://github.com/strapi/strapi/issues/6249
https://github.com/strapi/strapi/issues/3867

Per the guidelines of opening an issue: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

> You have already searched for related issues, and found none open (if you found a related closed issue, please link to it from your post).
