### ISSUE TITLE
Strapi - undefined blank screen

### ISSUE THREAD

**Issue by ultmatedev** [strapi/strapi#645]
**Node.js version**:
v8.9.1
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.1
**Operating system**:
MAC OSX

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Do not enter the dashboard
**If the current behavior is a bug, please provide the steps to reproduce the problem**
After creating a new user and exiting the strapi, the error happens, even restarting the server does not return to normal.
**What is the expected behavior?**
Access the dashboard

**Comment by lauriejim** [comment]
Hello @ultmatedev I can't reproduce your issue.

Can you send me the error response you get in your browser network please.

**Comment by ultmatedev** [comment]
I get the following errors:

Uncaught (in promise) Error: Unauthorized
    at main.js:56
    at <anonymous>

Uncaught (in promise) Error: Unauthorized
    at main.js:51
    at <anonymous>
16:22:39.231 

Uncaught (in promise) Error: Unauthorized
    at main.js:51
    at <anonymous>


{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}

**Comment by lauriejim** [comment]
Can you delete your root user in database. Register new root admin account (http://localhost:1337/admin, the register form will be displayed) and then make sure, your Guest role have all Users and Permission Auth action available.

**Comment by albertorm95** [comment]
Is this issue related to this one: https://github.com/strapi/strapi-docker/issues/35?
