### ISSUE TITLE
Missing enviroment folder

### ISSUE THREAD

**Issue by holyduke** [strapi/strapi#6450]
**Describe the bug**
I followed [this ](https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#mongodb-installation) tutorial to connect MongoDB to Strapi. However, there is no enviroment folder inside my config folder.

**Expected behavior**
enviroment folder should appear with all other files so I can insert my MongoDB auth

**Screenshots**
![image](https://user-images.githubusercontent.com/48070343/83325196-d4e17580-a26a-11ea-8680-21a87a8bab92.png)

- Node.js version: 
- NPM version: v12v16v2
- Strapi version: 3.0.1
- Database: mongodb
- Operating system: win10

**Comment by abelsoares** [comment]
@holyduke Check this please: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html

Environments folders were removed, you can now use `.env` to set your environment variables.

Also check: https://strapi.io/documentation/v3.x/concepts/configurations.html#environment-variables

**Comment by holyduke** [comment]
Thanks. I will check it. I would suggest updating the tutorial I followed

**Comment by derrickmehaffy** [comment]
They will be updated in due time

**Comment by derrickmehaffy** [comment]
I'm marking this as closed for now

**Comment by Berend-Kalberg** [comment]
As someone following [](https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html) this is giving me many issues deploying my strapi project to Heroku. Im stuck at having to put the environments variables in database.json. It isnt there anymore and I dont know how to use .env

**Comment by derrickmehaffy** [comment]
@Berend-Kalberg see: https://strapi.io/documentation/v3.x/deployment/heroku.html#_4-update-your-database-config-file You were looking at the old docs

**Comment by diegoalvis** [comment]
Please update the docs or remove the old ones as I got the same issue

**Comment by derrickmehaffy** [comment]
> Please update the docs or remove the old ones as I got the same issue

We are working to remove the beta docs
