### ISSUE TITLE
The image keeps on crashing in the site

### ISSUE THREAD

**Issue by sujaydeymountblue** [strapi/strapi#6454]
**Describe the bug**
The image keeps on crashing in  the site on `http://localhost:1337/`

**Expected behavior**
An image should be displayed instead of crashing

**Screenshots**
people saying hello
![people](https://user-images.githubusercontent.com/61132218/83327382-eb9ec100-a298-11ea-921c-173e3dc76010.png)

**System**

- Node.js version:v12.6.0
- NPM version:6.9.0
- Strapi version: 3.0.1
- Database:mongodb
- Operating system:Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
Since the main website got swapped over @soupette these 3 files are missing:

https://strapi.io/assets/images/group_people_1.png
https://strapi.io/assets/images/group_people_2.png
https://strapi.io/assets/images/group_people_3.png

**Comment by sujaydeymountblue** [comment]
@derrickmehaffy and @soupette ...I would like to fix this issue. could you please give the me the exact links of group_people.png's.

**Comment by derrickmehaffy** [comment]
I don't know them, you will have to wait for them to reply

**Comment by soupette** [comment]
I am pinging @maevalienard @Aurelsicoko so we can provide you with the assets.

**Comment by sujaydeymountblue** [comment]
Thank you @soupette

**Comment by maevalienard** [comment]
Thanks for the ping! Here are the assets you're asking for: 

![Group_people3](https://user-images.githubusercontent.com/54801383/83398332-739edb00-a3ff-11ea-9744-6a771924ae64.png)
![Group_people2](https://user-images.githubusercontent.com/54801383/83398334-74d00800-a3ff-11ea-86bf-a33d80bd6c61.png)
![Group_people1](https://user-images.githubusercontent.com/54801383/83398338-75689e80-a3ff-11ea-9305-3f852856b621.png)

**Comment by sujaydey90** [comment]
Thank you @maevalienard

**Comment by lauriejim** [comment]
Hello! Do you plan to submit a PR to fix this issue?
