### ISSUE TITLE
No access to Email configuration

### ISSUE THREAD

**Issue by holyduke** [strapi/strapi#6458]
**Describe the bug**
Hey, so I just wanted to set email configuration to be able to send email notification using SMTP with Gmail. I followed this tutorial:

https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#configure-the-plugin

I can´t acces my developer tab:
http://localhost:1337/admin/plugins/email/configurations/development

**Screenshots**
![image](https://user-images.githubusercontent.com/48070343/83332958-70400e00-a29e-11ea-9b98-db4a105dce30.png)

The react error link is refering here:
https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=null&args[]=

Is there any better solution to send email notification from serer or through SMTP than using strapi? 

Help me, please, thanks :)

**Comment by holyduke** [comment]
Alright, I can see I am seeing deprecated version...

**Comment by nourabbas96** [comment]
@holyduke did you solve it

**Comment by holyduke** [comment]
Well not yet. I struggle to authenticate sendgrid...

They state [here](https://strapi.io/documentation/v3.x/plugins/email.html#configure-the-plugin) that I should insert that code into ./config/plugins.js

That file does not exist tho. When I created one it didn´t work.

**Comment by chamchu** [comment]
@holyduke just going to echo that I am similarly having this issue - the docs seem to be outdated since it's pointing out a cog or call to action to bring up the email provider config settings but it's not there. I am also running into the issue that you're running into with the react pages blowing up when directly navigating to http://localhost:1337/admin/plugins/email/configurations/development

![image](https://user-images.githubusercontent.com/12414656/83337315-14aa5c00-a26f-11ea-9f8c-6d824b985970.png)

Tried in both Chrome/Firefox latest
node version: v14.2.0
npm version: 6.14.4
package.json

`{
    "knex": "<0.20.0",
    "pg": "latest",
    "strapi": "3.0.0",
    "strapi-admin": "3.0.0",
    "strapi-connector-bookshelf": "3.0.0",
    "strapi-plugin-content-manager": "3.0.0",
    "strapi-plugin-content-type-builder": "3.0.0",
    "strapi-plugin-documentation": "3.0.0",
    "strapi-plugin-email": "3.0.0",
    "strapi-plugin-upload": "3.0.0",
    "strapi-plugin-users-permissions": "3.0.0",
    "strapi-provider-email-sendgrid": "^3.0.1",
    "strapi-utils": "3.0.0"
  }`

**Comment by holyduke** [comment]
@chamchu Sad to hear that, hopefully someone might help us...

**Comment by holyduke** [comment]
So I figured it out using vannila sendgrid, here´s what you need to do:

1. helpful tutorial https://www.youtube.com/watch?v=s2bzUzHeSVw
2. `npm install dotenv --save`
4. make .env file and put SENDGRID_API_KEY =YOUR_API_KEY_FROM_SENDGRID_INSERT_HERE
6. this will send an email:
```
    const sgMail = require("@sendgrid/mail");
    require('dotenv').config()
    try {
        sgMail.setApiKey(process.env.SENDGRID_API_KEY);
        const msg = {
            to: "xxx@yyy.zzz",
            from: "xxx@yyy.zzz",
            subject: "test",
            text: "this is a text",
            html: "<strong>stron text</strong>",
        }
        sgMail.send(msg).then(() => {
            console.log('Message sent')
        }).catch((error) => {
            console.log(error.response.body)
        })
      console.log("email sent");
    } catch (err) {
      console.log(err.message);
      return err;
    }
```

hope you´ll manage to make it work

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
