### ISSUE TITLE
UUID issue when installing GraphQL plugin

### ISSUE THREAD

**Issue by chirdeeptomar** [strapi/strapi#6461]
**Describe the bug**
Rest API is working as expected but when I am trying to installing the GraphQL plugin from the Marketplace, I am getting the error as below, removing "strapi-plugin-graphql": "^3.0.1" starts the server back up again ofcourse without graphql support.

**Steps to reproduce the behavior**

1. Go to 'Marketplace'
2. Click on 'Download' from GraphQL Card
3. See error

```
[2020-05-30T17:56:38.734Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-30T17:56:38.735Z] error Error: No valid exports main found for 'C:\Users\xxx\Work\strapi\my-project\node_modules\apollo-engine-reporting\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\ChirdeepTomar\Work\strapi\my-project\node_modules\apollo-engine-reporting\dist\agent.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
```

**Expected behavior**
I would expect to have GraphQL being installed and server restarted successfully.

**System**

- Node.js version: 13.3.0
- NPM version: 6.13.1
- Strapi version: 3.0.1
- Database: PostgreSQL 12.1 (docker)
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by chirdeeptomar** [comment]
@derrickmehaffy updated as per the template.

**Comment by seleckis** [comment]
I can confirm in fresh strapi 3.0.1 install. GraphQL plugin install from marketplace cases an error:
```
error Error: Command failed: npm run strapi -- install graphql
- Installing dependencies
✔ Installing dependencies
- Rebuilding admin UI
Command failed: npm run build
Error: Module not found: Error: Can't resolve '../EditPage' in '…/.cache/plugins/strapi-plugin-users-permissions/admin/src/containers/App'
```

**Comment by seleckis** [comment]
Removed node_modules, build, .cache and yarn.lock then `yarn && yarn build`. After that works well.

**Comment by lukeshiels** [comment]
> Removed node_modules, build, .cache and yarn.lock then `yarn && yarn build`. After that works well.

Unfortunately this doesn't work for me either.

**Comment by lukeshiels** [comment]
@alexandrebodin do you have any idea why this could be happening?

**Comment by alexandrebodin** [comment]
Hey, can you try adding the plugin manually ? 

First stop your instance.

```sh
yarn add strapi-plugin-graphql@3.0.1 
yarn  build --clean
yarn develop
```

**Comment by chirdeeptomar** [comment]
No good, still the same issue whichever way I install and run.

**Comment by lukeshiels** [comment]
> Hey, can you try adding the plugin manually ?
> 
> First stop your instance.
> 
> ```shell
> yarn add strapi-plugin-graphql@3.0.1 
> yarn  build --clean
> yarn develop
> ```

Yep. I've even tried to make a brand new project fresh and as soon as I try to install the GraphQL plugin either through the marketplace or via the CLI it crashes with the uuid error.

**Comment by klbennett** [comment]
I had this issue this morning. I rolled back my version of Node from v13.3.0 to v12.18.0 and it is now working.

**Comment by tobiasoberrauch** [comment]
> I had this issue this morning. I rolled back my version of Node from v13.3.0 to v12.18.0 and it is now working.

Your're awesome. This solves my problem. Now I'm using version 12.18.0 with help of node version manager (nvm)

Thank you :)

**Comment by chirdeeptomar** [comment]
Works on the current LTS version which is 12.8.0 as @klbennett suggested.
