### ISSUE TITLE
Can't Disable tutorial in Admin UI. v3.0.1

### ISSUE THREAD

**Issue by napserious** [strapi/strapi#6462]
**Describe the bug**
Can't disable tutorials in Admin UI.

**Steps to reproduce the behavior**
1. Created file `./admin/src/config.js`
2. Added content to it:
`export const LOGIN_LOGO = null;`
`export const SHOW_TUTORIALS = false;`
`export const SETTINGS_BASE_URL = '/settings';`
3. Deleted `.cache` and `build` folders.
4. Runned: `strapi build` and then `strapi develop`. At this step Tutorials are visible anyway. In `.cache/admin/src/config.js` I see my updated `config.js`

**Expected behavior**
Tutorials should disappear.

**System**
- Node.js version:  v12.16.2 
- NPM version: 6.14.4
- Strapi version: v3.0.1

**Screenshots**
![image](https://user-images.githubusercontent.com/14160283/83339828-ea41b880-a2d9-11ea-9322-cd0e8cadba50.png)
![image](https://user-images.githubusercontent.com/14160283/83339848-33920800-a2da-11ea-9651-fee8888f2278.png)
![image](https://user-images.githubusercontent.com/14160283/83339849-3856bc00-a2da-11ea-83bb-2c724e966358.png)

**Additional context**
Strapi was clean installed v3.0.0 two days ago and upgraded to 3.0.1 yesterday.

**Comment by derrickmehaffy** [comment]
I cannot reproduce this on 3.0.1 on Windows 10, the override works fine: 
![image](https://user-images.githubusercontent.com/8593673/83339174-fef16280-a27f-11ea-9c48-b0c80b0c8072.png)

**Comment by napserious** [comment]
![image](https://user-images.githubusercontent.com/14160283/83339828-ea41b880-a2d9-11ea-9322-cd0e8cadba50.png)

I don't know why. :|
Also I tried to change the settings url and the url changed. That means the file is processed ok. The only problem is in Tutorials sections.

**Comment by napserious** [comment]
> I cannot reproduce this on 3.0.1 on Windows 10, the override works fine:
> ![image](https://user-images.githubusercontent.com/8593673/83339174-fef16280-a27f-11ea-9c48-b0c80b0c8072.png)

![image](https://user-images.githubusercontent.com/14160283/83339828-ea41b880-a2d9-11ea-9322-cd0e8cadba50.png)

I don't know why. :|
Also I tried to change the settings url and the url changed. That means the file is processed ok. The only problem is in Tutorials sections.

**Comment by napserious** [comment]
![image](https://user-images.githubusercontent.com/14160283/83339848-33920800-a2da-11ea-9651-fee8888f2278.png)
![image](https://user-images.githubusercontent.com/14160283/83339849-3856bc00-a2da-11ea-83bb-2c724e966358.png)

**Comment by derrickmehaffy** [comment]
That isn't the tutorials lol, the tutorials is the little blue button in the lower-right (looks like a little question mark), that brings up a bunch of youtube tutorial videos. What you are referring to is the blog-post loader. That I don't believe has an easy "disable" option.

**Comment by napserious** [comment]
> That isn't the tutorials lol, the tutorials is the little blue button in the lower-right (looks like a little question mark), that brings up a bunch of youtube tutorial videos. What you are referring to is the blog-post loader. That I don't believe has an easy "disable" option.

Omg. Indeed. I was thinking these blog-posts are part of TUTORIALS. Because in your screenshots you don't have them. So for these who will make same mistake as me, to delete block posts, social medias etc from homepage, you can find them in:
`admin\src\containers\HomePage\index.js`
