### ISSUE TITLE
Changing server.url resulted in wrong admin page url .js file

### ISSUE THREAD

**Issue by KytoSai** [strapi/strapi#6467]
**Describe the bug**

- Config server.url in `config/server.js` file not work with admin page url in first time setup
- It causes a wrong path to the .js file of the admin page

**Steps to reproduce the behavior**

1. Create three container with:
  - nginx (container name: `nginx`)
  - strapi (container name: `kytosai_api` )
  - mongo (container name: `mongo`)

3. I want to setup api strapi container with url `dev-kytosai.com/api`

2. Add hosts file to custom domain (ex: `127.0.0.1 dev-kytosai.com`)

4. Setting config file in ngix container:

```bash
  server {
    listen 80;

    server_name dev-kytosai.com www.dev-kytosai.com;
    error_log /var/log/nginx/error.log;

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://kytosai_api:1337;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_pass_request_headers on;
    }
  }
```

4. Edit `config/server.js`  file 

```javascript
  module.exports = ({ env }) => ({
    host: env('HOST', '0.0.0.0'),
    port: env.int('PORT', 1337),
    url: 'http://dev-kytosai.com/api',
  });
```

5. Run `docker-compose up` to start container 

6. Check page `dev-kytosai.com/api`. It work fine

![alt text](https://i0.wp.com/s1.uphinh.org/2020/05/31/1.png)

7. Click to `Create the first administrator` . It open new tab to `http://dev-kytosai.com/api/admin` . But it only blank page

8. I opened the inspect element to check the code, I realized that the path to the .js file was wrong

![alt text](https://i0.wp.com/s1.uphinh.org/2020/05/31/2.png)

9. Check log in container

![alt text](https://i0.wp.com/s1.uphinh.org/2020/05/31/3.png)

**Expected behavior**

- I hope that I can modify the strapi url and still work properly
- I think fix static admin url, It can work !

**System**

- Node.js version: node:12.13.1-alpine (docker)
- NPM version: v6.12.1
- Strapi version: v3.0.1
- Database: mongo
- Operating system: Docker in MacOS

**Comment by derrickmehaffy** [comment]
Is your docker container rebuilding the admin? Changing that config requires you to rebuild the admin.

**Comment by KytoSai** [comment]
> Is your docker container rebuilding the admin? Changing that config requires you to rebuild the admin.

I try remove container and up again. But not work. :( 
I am coding in development environment

**Comment by derrickmehaffy** [comment]
Yes you still need to rebuild the admin, Strapi will only build the admin using the `develop` command if the build folder doesn't exist. However if you are saving the build to the local file system, it exists and thus is not rebuilt.

**Comment by KytoSai** [comment]
> Yes you still need to rebuild the admin, Strapi will only build the admin using the `develop` command if the build folder doesn't exist. However if you are saving the build to the local file system, it exists and thus is not rebuilt.

Thank you. After deleting the build folder, the admin page is working normally.

But I think this should happen automatically or have a tutorial that will be useful for developers  ^^

**Comment by derrickmehaffy** [comment]
The short answer would be to just rebuild before strapi starts (you can set this in your docker-compose file. That being said I am no docker pro.

For now though I'm going to mark this as closed.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/blob/master/docs/v3.x/deployment/nginx-proxy.md#L1
