### ISSUE TITLE
Domain name validation

### ISSUE THREAD

**Issue by sujaydeymountblue** [strapi/strapi#6475]
Describe the bug
At the time of registration, email has not been validated correctly `http://localhost:1337/admin/auth/register`

Expected behavior
An email should be valid in all aspect like

- should check valid domain, well-formed and valid mailbox

Screenshots
invalid email1:
![s1](https://user-images.githubusercontent.com/61132218/83353428-2fb0c500-a370-11ea-8afa-e909a4f3b258.png)

invalid email2:
![s2](https://user-images.githubusercontent.com/61132218/83353432-350e0f80-a370-11ea-8d7c-77aa5843f757.png)

invalid in the dashboard:
![dashboard](https://user-images.githubusercontent.com/61132218/83353438-39d2c380-a370-11ea-9a19-66ae3a7b00ae.png)

System

Node.js version:v12.6.0
NPM version:6.9.0
Strapi version: 3.0.1
Database:mongodb
Operating system:Ubuntu 18.04

**Comment by lauriejim** [comment]
Hello!

Thank you for reporting this behavior.

Something I would super appreciate is if you can try to submit a PR to fix this issue.

The topic you are pointing has to be fixed and it could be done by someone from the Community (you 🤗).

Here is the [contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to help you to getting started for contributions to Strapi.

**Comment by uporot1k** [comment]
@lauriejim Hi! Which current status of this issue? Can i try to fix this problem?

**Comment by DJ-Icebear** [comment]
@sujaydeymountblue I get the second example - "comsfjdlkfj" is not an existing domain.

But what is wrong with "a@gmail.com". It's a valid email format as far as I can tell. Although Google themselves have enforced a min-6-char rule for new accounts (but there are still google employees and early adopters that have shorter email addresses).

**Comment by ognjenjevremovic** [comment]
Hey @ lauriejim 👋 
I see there are a few PR referencing this issue. Can you confirm that this issue have been addressed fully - including all 3 scenarios linked and that no further work is required?

If not, I would like to work on this if it is up for grabs an it has not been addressed yet 🙂 .
This seems like a good issue for first time contributors to the project.

Many thanks! 🎉

**Comment by varadp2000** [comment]
Hello, if this issue is still open, I am interested. First time contributor :-)

**Comment by caioluis** [comment]
Is this still to do?

**Comment by siddoinghisjob** [comment]
can i still contribute to this PR? Is it still open?

**Comment by vikasvmads** [comment]
Hello, If the issue is still open, I want to work on it. I am a first time contributor :)

**Comment by derrickmehaffy** [comment]
If the issue has not been closed, or you don't see an attached pull request, please feel free to work on it and submit a pull request.

Locking the issue from further comment as the error is quite clear and the issue is open. We don't assign issues to users, if you want to fix it then just put in a PR.

**Comment by derrickmehaffy** [comment]
Hello, I have moved this request over to our enchancement/feature request database since it's not really a bug. You can find that post here: https://feedback.strapi.io/developer-experience/p/domainemail-name-validation
