### ISSUE TITLE
Strapi 3.0.1 needs at least node 10.10.0

### ISSUE THREAD

**Issue by manestream** [strapi/strapi#6482]
Hey guys,

first of all thanks a lot for this amazing product. i really like that!

i performed the migration from 3.0.0-beta.20.3 to 3.0.1 and i ran into a problem with my node version.

the `package.json` when setting up a new project needs node to be >=10.0.0 but in fact it needs to be >= 10.10.0 in the current version of 3.0.1.

this is due to the fact, that the config in [config-loader.js](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/app-configuration/config-loader.js#L13) is being parsed using `fs.readdirSync` that returns fs.Dirent[] Objects. The function `isFile` is added to node in version `10.10.0` [node docs](https://nodejs.org/api/fs.html#fs_class_fs_dirent) I had an old version of node 10 running (`10.06.3`) so `isFile` was not defined. That broke my process and i needed quiet some time to figure this out

may be you can fix this in a later version so nobody else will run into that problem.

Thanks a lot and stay healthy :)

All the best and keep on the great work!
Kai

**Comment by lauriejim** [comment]
Hello @manestream !
Thank you for reporting this behavior.
Something I would super appreciate is if you can try to submit a PR to fix this issue.
The topic you are pointing has to be fixed and it could be done by someone from the Community (you 🤗).
Here is the [contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to help you to getting started for contributions to Strapi.
I ping @alexandrebodin about this.
Thank you.

**Comment by alexandrebodin** [comment]
@manestream Thank you for reporting. 

Node v10 is in maintenance lts right now. We are going to focus on bringing support to node v14 and will deprecate support for node v10 once it reaches end of life in 2021.

Feel free to fix the engine info in the package.json of the repo it would help a lot :D

**Comment by manestream** [comment]
Hey guys thanks for the quick response ! I see that alexandre has already pushed the fix. that's great. from my side this issue can be closed :)

**Comment by alexandrebodin** [comment]
Thanks, Closing !
