### ISSUE TITLE
Heroku deploy with postgres 503 for '/<page>' and 'favicon.ico' failing to open

### ISSUE THREAD

**Issue by Coffeegerm** [strapi/strapi#6485]
**Describe the bug**
Unable to open web page for strapi server on heroku with postgres once successfully deployed. Problem was noted before here and have attempted to follow all steps within issue as well as documentation and unable to open

**Steps to reproduce the behavior**

1. Create strapi application
2. Deploy to heroku with Postgres after updating env variables
3.  heroku open
4. 'Application Error' from heroku

**Expected behavior**
Open auth page to create managed user

**System**

- Node.js version: >10
- NPM version: >5
- Strapi version: 3.0.0-beta.20.3
- Database: Postgres
- Operating system: Windows (deployed to heroku)

**Comment by derrickmehaffy** [comment]
Need more information to reproduce, what is the error. Closing for now until more information is provided.
