### ISSUE TITLE
Has many and has many + belongs to throws "Your filters contain a field 'undefined'"

### ISSUE THREAD

**Issue by andylacko** [strapi/strapi#6488]
Nested relations in GraphQl don't work

1. create has many relation
2. create nested has many and belongs to relation
3. read nested data in graphql

Every relation to work as expected in GraphQl

```graphql
query lp ($id: ID!){
    lp (id: $id) {
      id
      name
      actualAllocationToPrivateEquity
      contacts {
        id
        profilePicture {
          id
          url
        }
      }
      fund_commitments {
        id
        fund_commitment_investments {
          id
        }
        gp {
          id
          name
        }
      }
    }
  }
```

- Node.js version: v14.3.0
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: sqlite
- Operating system: macOs (I hate microsoft)

**Additional context**
Didn't work in older beta version, relations have issues

**Comment by derrickmehaffy** [comment]
We need to have an example of the error you are getting, it would also be helpful to see the layout of the models to be able to reproduce. If your project code is somewhere public, please provide a link, else please provide some model settings to try and reproduce.

**Comment by andylacko** [comment]
## Model 1 - base model


```json
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "model1",
  "info": {
    "name": "LimitedPartner"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "overview": {
      "type": "richtext"
    },
    "model2": {
      "collection": "fund-commitments"
    }
  }
}
```

## Model 2 - connector for model3 and model4
```json
{
  "kind": "collectionType",
  "collectionName": "model2",
  "info": {
    "name": "model2"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "model3": {
      "collection": "model3"
    },
    "model4": {
      "model": "model4",
      "via": "model2"
    }
  }
}
```

## Model3 - child model of model2
```json
{
  "kind": "collectionType",
  "collectionName": "model3",
  "info": {
    "name": "fundCommitmentInvestment"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    }
  }
}
```

## Model 4 - child model of model2
```json
{
  "kind": "collectionType",
  "collectionName": "model2",
  "info": {
    "name": "model4"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "model2": {
      "via": "model4",
      "collection": "model2"
    }
  }
}
```

## GraphQl which breaks it

```graphql
query model1 ($id: ID!){
    model1 (id: $id) {
      id
      model2 {
        id
        model3 {
          id
        }
        model4 {
          id
          name
        }
      }
    }
  }
```

## Error outcome

![image](https://user-images.githubusercontent.com/7139923/83395152-16ecf180-a3fa-11ea-9361-6bd1019b8c5e.png)

![image](https://user-images.githubusercontent.com/7139923/83395454-98448400-a3fa-11ea-8f1e-fd35630599a8.png)

`path: ["model1", "model2", 0, "model3"]`

**Comment by lauriejim** [comment]
Hello! Can you make sure your models are correct, I just can't start my app with model you shared.

**Comment by coopemor** [comment]
Hey @lauriejim! Loving Strapi so far, just started playing around with it a few days ago. I think I'm running into this issue as well. I recorded a [video showing](https://www.youtube.com/watch?v=co3SBjvNhmc&feature=youtu.be) it working with "belongs to many" on the parent and it throwing this error when I change it to "has many".

I'm very new to Strapi, so very likely I'm doing something wrong, but would love a pointer in the right direction! Happy to provide any code or models that I have that's giving me this issue.

**Comment by votemike** [comment]
I am having a similar problem with nested relations.
{Single Type (Foo Bar)} -> hasMany -> {Collection Type (Category)} -> hasMany -> {Collection Type (Item)}
```
query {
  fooBar {
    name,
    categories {
      name,
      items {name}
    }
  }
}
```
I am tracing the error as far back as https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/data-loaders.js#L190 where my `query` is `{ undefined: 1 }`. But I cannot find where `current.options.query` is set before this and how it is getting a key of `undefined`.

**Comment by votemike** [comment]
I made an example repo:
https://github.com/votemike/graphql-deep
* Clone, install, make admin user.
* Create an Item
* Create a Category (and link it to the Item)
* Create a Foo Bar (and link it to the Category)
* Ensure that the Public role can find and findone of the Item, Category and Foo-Bar
* Visit http://localhost:1337/graphql and paste in....
```
query {
  fooBar {
    name,
    categories {
      name,
      items { id }
    }
  }
}
```
Then you should get the error.

**Comment by lauriejim** [comment]
Thank you for all these details! I really appreciate the app and steps to reproduce.
Really clear.

**Comment by joelbqz** [comment]
I'm also having this issue 😢

**Comment by jaakidup** [comment]
Yes, also having this issue.

Is there any work being done to resolve this issue?

**Comment by derrickmehaffy** [comment]
Nothing currently, as it's marked as a bug we will try to get to it once we have time.

**Comment by alexandrebodin** [comment]
Hi closing this as it was fixed in a recent version :)
