### ISSUE TITLE
Configuration files merging policy.

### ISSUE THREAD

**Issue by blouze** [strapi/strapi#6492]
**Describe the bug**
Merging default and production configurations creates bad database connection string.

**Steps to reproduce the behavior**

1. Use default config in default config file `./config/database.js`
~~~
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        client: 'mongo',
        host: env('DATABASE_HOST', 'localhost'),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', 'strapi'),
        password: env('DATABASE_PASSWORD', 'strapi'),
      },
      options: {
        authenticationDatabase: env('AUTHENTICATION_DATABASE'),
        ssl: env('DATABASE_SSL'),
      },
    },
  },
});
~~~

2.Create production database config in file `./config/env/production/database.js` (in my case Cloud SQL)
~~~
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: `/cloudsql/${env('INSTANCE_CONNECTION_NAME')}`,
        database: env('DATABASE_NAME'),
        username: env('DATABASE_USERNAME'),
        password: env('DATABASE_PASSWORD'),
      },
      options: {},
    },
  },
});
~~~
3. Gives me:
~~~
error Error: connect ENOENT /*********:europe-west1:*********/.s.PGSQL.27017
~~~
4. Works after emptying the default database config and moved original config to `./config/env/development/database.js`

**Expected behavior**
Setting a host and port in default config for development should not interfere with production config when settings are merged.

**System**

- Node.js version: node v10.20.1
- NPM version:
- Strapi version: 3.0.1
- Database: postgres
- Operating system:

**Comment by alexandrebodin** [comment]
Hi, if your default is not compatible with your production config you should set it in development env instead and remove the default one :) Closing as the behaviour is intended
