### ISSUE TITLE
Register mutation doesn't work with email confirmation enabled

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#6497]
**Describe the bug**
PR #6192 introduced this issue.
Because the JWT is not sent anymore if the account is not confirmed, GraphQL throws an error because the `jwt` is marked as required, as we can see from the schema below:

![schema](https://user-images.githubusercontent.com/7467891/83443210-48d57680-a441-11ea-99f0-e76eb70e6b7d.png)

**Steps to reproduce the behavior**

1. Turn on email confirmation
2. Try to register an account using the `register` mutation
3. Receive an error on GraphQL

**Expected behavior**
The user should be registered successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/83443333-74f0f780-a441-11ea-9873-723e6fbaabf6.png)

**Code snippets**
_none_

**System**

- Node.js version: `v13.7.0`
- NPM version: `v6.13.6`
- Strapi version: `v3.0.1`
- Database: `MongoDB`
- Operating system: `Windows 10 1909 (w/ WSL Ubuntu 18.04)`

**Additional context**
I can think of two solutions to this:
 - Mark `jwt` as not required
 - Pass an empty string as `jwt` when the account is not confirmed (what I've done on my project for now)

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
I think it's something easy to update in the GraphQL schema.
Can you please submit a PR to fix this issue, I will appreciate your contribution on this issue.
Ping @alexandrebodin about this issue.
Thank you.

**Comment by alexandrebodin** [comment]
Nice catch. Would you mind making a PR for this ?
