### ISSUE TITLE
Email settings "cog" not visible on the Plugins page

### ISSUE THREAD

**Issue by Saunved** [strapi/strapi#6519]
**Describe the bug**
I am trying to configure an email provider (nodemailer). I am not able to see the "cog" when I go to "Plugins -> Email".

**Steps to reproduce the behavior**

1. Open the dashboard
2. Go to "Plugins"
3. See the "email" line (there is no cog there, for me)

**Expected behavior**
There should be a cog visible over there that allows me to configure my email settings.

**Screenshots**
![no_cog2](https://user-images.githubusercontent.com/16450673/83558321-79e0a480-a530-11ea-92ec-e18bee3964c9.png)

**Code snippets**
NA

**System**

- Node.js version: 12.17.0
- NPM version: 6.14.4
- Strapi version: 3.0.0
- Database: MongoDb v4.2.7
- Operating system: Ubuntu 20.04

**Additional context**
I tried using v3.0.1 of Strapi, then downgraded to v3.0.0. Still unable to view the cog. I also tried going to http://localhost:1337/admin/plugins/email/configurations/development. It just shows a blank page.
I have strapi-provider-email-nodemailer installed (but I don't think it's necessary to have a provider installed for the cog to show).
[This YouTube video](https://www.youtube.com/watch?v=vrLmZCOTj6Y) uploaded on 27 April 2020 shows the settings cog. The user is using a beta version of Strapi.

**Comment by derrickmehaffy** [comment]
Please see:

https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider

https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings

The same applies to the stable release.

**Comment by dazp94** [comment]
I'm having the very same problem here.

**Comment by Saunved** [comment]
Strapi 3.x has a new plugin system. I've written an npm package to help integrate Strapi email with Nodemailer. You can check it out here: https://github.com/Saunved/strapi-provider-email-nodemailer
