### ISSUE TITLE
plugin page is not opening to setup Email providers

### ISSUE THREAD

**Issue by jay01011986** [strapi/strapi#6527]
**Describe the bug**
In Strapi 3.0.1, Plugin page for Email is not opening where, I can setup different Email providers.

**Steps to reproduce the behavior**

1. Install the fresh strapi project with default settings.
yarn create strapi-app my-project --quickstart
2. Go to http://localhost:1337/admin
3. on the admin panel, plugin page, i can see 5 plugin. On clicking of Email, nothing is opening. The Email link is not clickable.

**Expected behavior**
Email provider page should open.

**Screenshots**

This page should open: 
![image](https://user-images.githubusercontent.com/53622585/83630654-3f691d00-a5ad-11ea-8e00-bd2e6fb8f1e7.png)

**System**

- Node.js version: v11.8.0
- NPM version: 0.34.0
- Strapi version: 3.0.1
- Database: mssql
- Operating system: macOS Catalina

**Comment by derrickmehaffy** [comment]
Please see:

https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider

https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings

**Comment by jay01011986** [comment]
@derrickmehaffy If you have gone through the details of the issue, my issue is not related to upload provider. My issue is related to Email provider and that is not working in the Strapi 3.0.1.

**Comment by derrickmehaffy** [comment]
@jay01011986 my bad but the same logic still applies: https://strapi.io/documentation/v3.x/plugins/email.html#configure-your-provider

**Comment by jay01011986** [comment]
@derrickmehaffy , I have followed the same link, but it is not working.

**Comment by derrickmehaffy** [comment]
All the UI elements to configure those options were removed, if you want I can convert this to a discussion to ask for help regarding the file config. I've never used any of these myself so I'm not entirely sure.

**Comment by jay01011986** [comment]
I have found the fix for the issue. 
1. replace the strapi-plugin-email version in package.jason from "strapi-plugin-email": "3.0.1", to "strapi-plugin-email": "3.0.0-rc.0".
2. delete the node-modules folder and yarn.lock file and do yarn install.
3. replace the code of Row.js file in node-modules/strapi-admin/admin/src/containers/installedPluginsPage/Row.js as below:

import CustomRow from './CustomRow';
import LogoContainer from './Logo';

const PLUGINS_WITH_CONFIG = ['email'];

const Row = ({ logo, name, description, isRequired, id, icon, onConfirm }) => {
  const {currentEnvironment, formatMessage } = useGlobalContext();
  const [isOpen, setIsOpen] = useState(false);
  const { push } = useHistory();
  const links = [];

  if (PLUGINS_WITH_CONFIG.includes(id)) {
    links.push({
      icon: <FontAwesomeIcon icon={faCog} />,
      onClick: () => {
        const settingsPath = `/plugins/${id}/configurations/${currentEnvironment}`;

        push(settingsPath);
      },
    });
  }

  const handleClickConfirm = () => {
    handleToggle();
    onConfirm(id);
  };

  const handleToggle = () => {
    setIsOpen(prev => !prev);
  };

  if (!isRequired) {
    links.push({
      icon: <FontAwesomeIcon icon={faTrashAlt} />,
      onClick: handleToggle,
    });
  }

  return (
    <CustomRow>
      <td style={{ paddingLeft: 30, paddingTop: 0, width: 100, verticalAlign: 'bottom' }}>
        <LogoContainer>
          {logo && <img src={logo} alt="icon" />}
          {!logo && (
            <div className="icon-wrapper">
              <FontAwesomeIcon icon={icon} />
            </div>
          )}
        </LogoContainer>
      </td>
      <td>
        <p>
          <Text
            as="span"
            fontSize="xs"
            fontWeight="bold"
            letterSpacing="0.7px"
            textTransform="uppercase"
          >
            {name}&nbsp;—&nbsp;
          </Text>
          <Text as="span" fontSize="md">
            {formatMessage({
              id: `${description}.short`,
              defaultMessage: description,
            })}
          </Text>
        </p>
      </td>

      <td>
        <IconLinks links={links} />
        <PopUpWarning
          isOpen={isOpen}
          toggleModal={handleToggle}
          popUpWarningType="danger"
          onConfirm={handleClickConfirm}
        />
      </td>
    </CustomRow>
  );
};

Row.defaultProps = {
  icon: 'plug',
  isRequired: false,
  logo: null,
  onConfirm: () => {},
};

Row.propTypes = {
  description: PropTypes.string.isRequired,
  icon: PropTypes.string,
  id: PropTypes.string.isRequired,
  isRequired: PropTypes.bool,
  logo: PropTypes.string,
  name: PropTypes.string.isRequired,
  onConfirm: PropTypes.func,
};

export default Row;

4. yarn build
5. yarn develop

Now you can see the settings cog icon in from of Email in plugins page in the admin panel. On clicking of that you can setup the different Email providers.

**Comment by soupette** [comment]
Well this page does not exist anymore has the email configurations are now in files.
