### ISSUE TITLE
Cannot open plugins options.

### ISSUE THREAD

**Issue by kacpermigala** [strapi/strapi#6528]
**Describe the bug**
I'm not able to open plugins settings.

**Steps to reproduce the behavior**

1. Go to Plugins
2. Accordingly, to the documentation there should be a cog icon next to some plugins I cannot see it both on production & locally.
3. When I'm trying to open https://mydomain.com/admin/plugins I receive a 403 status response.
4. While I'm trying to access URL for email settings from the documentation: https://mydomain.com/admin/plugins/email/configurations/development I see an error in the console.

**Screenshots**
<img width="1145" alt="Screenshot 2020-06-03 at 14 20 54" src="https://user-images.githubusercontent.com/15971848/83636970-20678c80-a5a7-11ea-96ce-6f50a0798abf.png">

**Code snippets**
` react_devtools_backend.js:6 Error: Minified React error #130; 
visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at Ml (main.b41f5811.chunk.js:1)
  at main.b41f5811.chunk.js:1
    at Oi (main.b41f5811.chunk.js:1)
    at ji (main.b41f5811.chunk.js:1)
    at Ni (main.b41f5811.chunk.js:1)
    at vc (main.b41f5811.chunk.js:1)
    at sl (main.b41f5811.chunk.js:1)
    at cl (main.b41f5811.chunk.js:1)
    at $c (main.b41f5811.chunk.js:1)
    at main.b41f5811.chunk.js:1
 `

**System**

- Node.js version: v12.18.0
- NPM version:6.14.4
- Strapi version: 3.0.1
- Database: Postgres
- Operating system: Ubuntu 18 & MacOS Catalina

**Additional context**
I've tried to edit plugin.js file manually:

`module.exports = ({ env }) => ({
  email: {
    provider: "sendgrid",
    providerOptions: {
      apiKey: env(
        "x"
      ),
    },
    settings: {
      defaultFrom: "x@xxx.com",
      defaultReplyTo: "x@xxx.com",
    },
  },
});
`
also don't work.

**Comment by derrickmehaffy** [comment]
See: https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider

**Comment by kacpermigala** [comment]
I edited it, sorry for the previous format @derrickmehaffy

**Comment by alexandrebodin** [comment]
Hello, nI v3.0.0 the email settings were moved to files. You can read the migration guide here https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html
