### ISSUE TITLE
Facebook provider frontend Redirect url

### ISSUE THREAD

**Issue by negati-ve** [strapi/strapi#6533]
I'm running on Strapi 3.0.0 beta 20

I have a personal site running on strapi with a react frontend
the frontend allows users to login and strapi's facebook provider sends the request back to the specified frontend redirect URL 

Now, I want to setup another site for testing, with the same reactjs frontend and same strapi backend but the new test site has different domain name

as you can guess.. the problem is when I try to login to the new site hosted on new domain, 
strapi's facebook provider, after authentication still redirects to the old domain.. 

is there a way I can tell strapi to redirect to the new domain instead of the one old one registered in the strapi admin ?

![image](https://user-images.githubusercontent.com/13253073/83650683-3e98b100-a5d6-11ea-9265-67bd61e2a573.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
