### ISSUE TITLE
Server path + Admin path = Relative path (instead of absolute) with some 404

### ISSUE THREAD

**Issue by baytelman** [strapi/strapi#6535]
**Describe the bug**
When setting up `server.url` and `admin.url` both to custom paths, their behavior is unexpected, producing a 404.

**Steps to reproduce the behavior**

1. Set your `./config/server.js` to the following:

```
module.exports = ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  url: "/cms-api",
  admin: {
    url: "/cms-dashboard",
  },
});
```

2. Build `yarn build`
3. Run `yarn develop`

**Expected behavior**
- API endpoints should be available on `http://localhost/cms-api`
- Dashboard should be available on `http://localhost/cms-dashboard`
- Entering dashboard should work.

**Screenshots**
1. Dashboard is accesible in the aggregated path (relative) instead of absolute:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/2747232/83657403-cd81db00-a58e-11ea-8c05-ba0bc133442c.png">

2. After building and running, when entering the relative URL, loading fails:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/2747232/83657641-19cd1b00-a58f-11ea-816b-dd5e3ba932cb.png">

3. Dashboard attempts to get inexistent file. 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/2747232/83661854-be059080-a594-11ea-8b26-5f0f370d12f4.png">

**System**

- Node.js version: v12.16.3
- NPM version: v
- Strapi version: 3.0
- Database: mongo: 4.2.0
- Operating system: MacOS 10.15.5

**Comment by derrickmehaffy** [comment]
This will only work if you are actually using a proxy application, it doesn't actually prefix the routes in Strapi.
