### ISSUE TITLE
Incorrect information in documentation for new configuration loader

### ISSUE THREAD

**Issue by lucas-jg** [strapi/strapi#6541]
**Describe the bug**
Incorrect information in documentation for new configuration loader

**Expected behavior**
There is a possibility of misunderstanding in the document regarding the cron setting.

This is a setting to activate cron (3.0.0.beta.20)
./config/environments/{env}/server.json
```
{
    "host": "0.0.0.0",
    "port": 1337,
    "cron": {
        "enabled": true
    }
}
```

The documentation on how to migrate guides like this.
[Migrating](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html#migrating)
```
Server

Your server configuration can move from ./config/environments/{env}/server.json to 
./config/server.js like shown here.
```
[Server](https://strapi.io/documentation/v3.x/concepts/configurations.html#server)
Available options -> cron

However, to enable cron in version 3.0.0  must do it in the middleware.js

./config/middleware.js
```
    timeout: 100,
    load: {
        before: ['responseTime', 'logger', 'cors', 'responses', 'gzip'],
        order: [
            "Define the middlewares' load order by putting their name in this array is the right order"
        ],
        after: ['parser', 'router']
    },
    settings: {
       ...
       cron: { enabled: true }
       ...
    }

```

**Code snippets**
After checking the code (strapi/middlewares/index.js), I learned that it should be set in middleware.

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.6
- Strapi version: 3.0.0
- Database: mongodb
- Operating system: window, linux

**Comment by derrickmehaffy** [comment]
Can you test the documentation for v3.0.1 as there was already a fix put in place for this.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/pull/6419

Going to mark this as closed due to the above PR already merged and released
