### ISSUE TITLE
Email plugin is not working

### ISSUE THREAD

**Issue by jay01011986** [strapi/strapi#6543]
**Describe the bug**
Email plugin is not working and I am getting errors while sending the email. I have tried with multiple providers like Sendgrid, mailgun and mailtrap etc and same issue is coming. 
I have followed the following link to do the setup:
https://strapi.io/documentation/v3.x/plugins/email.html#programmatic-usage

This is the error log on Strapi console:

```
AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at new AssertionError (internal/assert.js:396:11)
      at Object.exports.assert (/Users/Jay/Desktop/Temp/StrapiTemp1/my-project/node_modules/hoek/lib/index.js:559:11)
      at Function.boomify (/Users/Jay/Desktop/Temp/StrapiTemp1/my-project/node_modules/boom/lib/index.js:107:14)
      at formatBoomPayload (/Users/Jay/Desktop/Temp/StrapiTemp1/my-project/node_modules/strapi/lib/middlewares/boom/index.js:47:22)
      at strapi.app.use (/Users/Jay/Desktop/Temp/StrapiTemp1/my-project/node_modules/strapi/lib/middlewares/boom/index.js:84:36)
      at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

These are the setups, I have used in config/plugins.js:
```js
module.exports = ({ env }) => ({
  email: {
    provider: 'sendgrid',
    providerOptions: {
      apiKey: env('API_KEY'),
    },
    settings: {
      defaultFrom: 'mrityunjay.tiwari@awrostamani.com',
      defaultReplyTo: 'mrityunjay.tiwari@awrostamani.com',
    },
  },
});
```

**Steps to reproduce the behavior**

1. Install the new default Strapi project:
`yarn create strapi-app my-project --quickstart`
2. add the sendgrid package:
`yarn add strapi-provider-email-sendgrid --save`
3. add plugins.js under config folder with the following setup:
```js
module.exports = ({ env }) => ({
  email: {
    provider: 'sendgrid',
    providerOptions: {
      apiKey: env('API_KEY'),
    },
    settings: {
      defaultFrom: 'mrityunjay.tiwari@awrostamani.com',
      defaultReplyTo: 'mrityunjay.tiwari@awrostamani.com',
    },
  },
});
```

yarn develop and try to send the mail from postman using the following service:
`http://localhost:1337/email`

```json
{
        "to": "jay01011986@gmail.com",
        "subject": "Comment posted that contains a appriciations",
        "text": "testing"
 }
```

**Expected behavior**
A mail should be triggered.

**System**

- Node.js version: 13.12.0
- NPM version: 0.34.0
- Strapi version: 3.0.1
- Database: mssql
- Operating system: MacOS Catalina

**Comment by alexandrebodin** [comment]
Hi, in the code you pasted (I edited out the apiKeys) you were using `apiKey: env('yourValue')` That's not of it should be used.

the `env` utility will look for an env var with the name you passed as a parameter. If you want to set a value statically you should remove `env`:

```js
module.exports = ({ env }) => ({
  email: {
    provider: 'sendgrid',
    providerOptions: {
      apiKey: 'Value of the API KEY',
    },
    settings: {
      defaultFrom: 'mrityunjay.tiwari@awrostamani.com',
      defaultReplyTo: 'mrityunjay.tiwari@awrostamani.com',
    },
  },
});
```

**Comment by jay01011986** [comment]
@alexandrebodin , I have tried after removing the env as well but the same issue is there.

**Comment by tombpain** [comment]
Please see the following fork of the sendgrid provider which should be a fix for the above issue. 

https://github.com/tombpain/strapi-provider-email-sendgridmail?organization=tombpain&organization=tombpain

Looks to me like the sendgrid node implementation now only supports ES6/ES8 methodology and not callbacks.

A PR has been raised to merge the changes into the main repo.

Cheers,

Tom

**Comment by akhilmhdh** [comment]
I think there is problem with the email plugin in the stable release. Emails are not being send or the req is being just outputted with email invalid error which was working fine for my other version.

**Comment by njm222** [comment]
I am also having a similar issue with strapi-provider-email-amazon-ses

**Comment by akhilmhdh** [comment]
Actually found the issue its the not providers its the email plugin. The new version configured one is not working.

**Comment by RileyMShea** [comment]
I am also getting the very similar error in strapi run from a `strapi:3.0.1-node12` docker image when attempting to use `/email` endpoint.

request
``` bash
curl --request POST \
  --url https://api.mystrapisite.com/email \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{
	"to": "someemail@gmail.com",
	"subject": "some subject",
	"text": "testing"
}'

response:
```bash
< HTTP/2 500 
< content-type: text/plain; charset=utf-8
< date: Sun, 07 Jun 2020 20:44:43 GMT
< content-length: 21
```

strapi error log:
```
  AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at Function.boomify (/srv/app/node_modules/boom/lib/index.js:107:14)
      at formatBoomPayload (/srv/app/node_modules/strapi/lib/middlewares/boom/index.js:47:22)
      at /srv/app/node_modules/strapi/lib/middlewares/boom/index.js:84:36
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by valdvogel-launchtrip** [comment]
Hey guys, I got the same issue using strapi 3.1.4 e o plugin "strapi-provider-email-mandrill": "^1.0.0". To solve my issue I just added this file config on 'PROJECT/config/plugins.js' and this content :
`module.exports = ({ env }) => (
  {
    email: {
      provider: 'mandrill',
      providerOptions: {
        apiKey: env('MANDRILL_API_KEY'),
        mandrill_default_from_name: 'Launchtrip',
        mandrill_default_from_email: 'info@launchtrip.com'
      },
    },
  });`

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by m-emre-yalcin** [comment]
`try { await strapi.plugins['email'].services.email.send(options) } catch(err) { console.log(err) }`
you can see the error like this.

**Comment by baremetals** [comment]
I am having this issue on Strapi v4, when I deploy to app engine. I get no errors. The email config on the admin is showing Strapi settings instead of my Sendgrid settings. But this is not the case on local hosts.
I have tried various versions. App engine will not change the email plugin configuration.

I tried using the generic sendgrid code not strapi's version that is also not working on app engine.

**Comment by acushlakoncept** [comment]
Hey, @baremetals did you solve this issue?
I am facing the same challenge

**Comment by baremetals** [comment]
Hi @acushlakoncept,

I did resolve it but I didn't work out why it got stuck in the first place. I changed the name for EMAIL_PROVIDER from sendgrid to @strapi/provider-email-sendgrid, I then deleted the cache, build and node_modules. I also deleted my migrations folder.  I did not do all of these things as the same time,. My theory is that the the migration may have been corrupted. I am using version 4.2.2 on the application. but a version change did not resolve the issue the database doesn't change with version change so. Try this first REVERT THE EMAIL PROVIDER BACK TO STRAPI.  Delete the folders then send a build to app engine. Then go back to your email provider.

**Comment by kraisorna** [comment]
> Hi, in the code you pasted (I edited out the apiKeys) you were using `apiKey: env('yourValue')` That's not of it should be used.
> 
> the `env` utility will look for an env var with the name you passed as a parameter. If you want to set a value statically you should remove `env`:
> 
> ```js
> module.exports = ({ env }) => ({
>   email: {
>     provider: 'sendgrid',
>     providerOptions: {
>       apiKey: 'Value of the API KEY',
>     },
>     settings: {
>       defaultFrom: 'mrityunjay.tiwari@awrostamani.com',
>       defaultReplyTo: 'mrityunjay.tiwari@awrostamani.com',
>     },
>   },
> });
> ```

this solution is working for my case as well with below error messages:

```
Error: Couldn't send test email: Unauthorized.
at Object.test (/home/username/workspace/appname/node_modules/@strapi/plugin-email/dist/server/index.js:173:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async returnBodyMiddleware (/home/username/workspace/appname/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
at async policiesMiddleware (/home/username/workspace/appname/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
at async /home/username/workspace/appname/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
at async /home/username/workspace/appname/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
at async /home/username/workspace/appname/node_modules/@strapi/strapi/dist/middlewares/logger.js:6:5
at async /home/username/workspace/appname/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
at async cors (/home/username/workspace/appname/node_modules/@koa/cors/index.js:107:16)
at async /home/username/workspace/appname/node_modules/@strapi/strapi/dist/middlewares/errors.js:8:7
```

**Comment by Eunit99** [comment]
I resolved the error by modifying my code from this:

```typescript

export default ({ env }) => ({
  // ...
  email: {
    config: {
      provider: 'strapi-provider-email-mandrill',
      providerOptions: {
        apiKey: env('MANDRILL_KEY'),
      },
      settings: {
        defaultFrom: 'no-reply@someone.io',
        defaultReplyTo: 'no-reply@someone.io',
        testAddress: 'someone@gmail.com',
      },
    },
  },
  // ...
});
```

to this:

```typescript

export default ({ env }) => ({
  // ...
  email: {
    config: {
      provider: '@palmabit/strapi-provider-email-mandrill',
      providerOptions: {
        apiKey: env('MANDRILL_KEY'),
      },
      settings: {
        defaultFrom: 'no-reply@someone.io',
        defaultReplyTo: 'no-reply@someone.io',
        testAddress: 'someone@gmail.com',
      },
    },
  },
  // ...
});
```

Notice the change in the `provider` value.
