### ISSUE TITLE
server.admin.path no longer respected

### ISSUE THREAD

**Issue by sharpn** [strapi/strapi#6544]
**Describe the bug**
When you set admin.path in the server.js file it is no longer respected when the admin panel is run and it always uses /admin

**Steps to reproduce the behavior**

1. Set admin.path to `/dashboard`
2. Build and run the admin panel
3. The admin panel is available on `/admin`

**Expected behavior**
The admin panel should be available on `/dashboard`

**Code snippets**
server.js
```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    path: '/dashboard',
    serveAdminPanel: env('SERVE_ADMIN_PANEL', true),
    build: {
      backend: '/',
    },
  },
});

```

**System**

- Node.js version: 12
- NPM version:6.14.5
- Strapi version: 3.0.1
- Database: mysql
- Operating system: macos and docker

**Comment by derrickmehaffy** [comment]
Please see: https://strapi.io/documentation/v3.x/concepts/configurations.html#server

**Comment by sharpn** [comment]
Maybe this needs updating as it still shows path
https://strapi.io/documentation/v3.x/admin-panel/customization.html#change-access-url
