### ISSUE TITLE
Mongoose connector authSource no env variable set

### ISSUE THREAD

**Issue by DHvD-R** [strapi/strapi#6548]
**Describe the bug**
When trying to setup authentication with Strapi and Mongo via docker-compose it fails authentication when AUTHENTICATION_DATABASE is not set. It defaults to admin for authentication database.

**Steps to reproduce the behavior**
Following this tutorial on your website:
https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose

**Expected behavior**
When setting the database env variables I would expect Strapi to connect to the database name that I set. This was a gotcha moment for me that I also need to set authenticationDatabase.

**Possible solution**
Would it be an idea to change in the strapi-connector-mongoose/lib/index.js:

```
  if (!_.isEmpty(authenticationDatabase)) {
    connectOptions.authSource = authenticationDatabase;
  }
```

to:

```
  if (!_.isEmpty(authenticationDatabase)) {
    connectOptions.authSource = authenticationDatabase;
  } else {
    connectOptions.authSource = database;
  }
```

Then in most use cases the authentication database defaults to the database you want to connect to.

**System**
- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.1
- Database: Mongo 4.2.7
- Operating system: Linux

**Comment by lauriejim** [comment]
Hello! Thank you for highlighting this.
I don't know if @alexandrebodin will have time to answer this question.
I think you can create a PR to submit your proposal.

**Comment by maazkabir** [comment]
Hey there first time contributor here !
Is this still needed?
Can I add a PR for this issue/enhancement?
If not,  can you nudge me in the right direction I would love to start contributing!

**Comment by alexandrebodin** [comment]
Yeah I think this would make sense

**Comment by DHvD-R** [comment]
Sorry for my late reply. Is the PR from @maazkabir fine or should I still open a PR?

**Comment by alexandrebodin** [comment]
the PR is alright but it would be a breaking change so not going to be added until a major release :)

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
