### ISSUE TITLE
Documentation migrating not available for v3@alpha.10

### ISSUE THREAD

**Issue by Yobikap** [strapi/strapi#655]
**Strapi version**:
v3@alpha.10

In the blog post, all links are leading to 404 or are dead. Also I cannot find any documentation how to upgrade from alpha.9 to alpha.10

https://medium.com/@strapi/release-v3-alpha-10-54df30a6ee7b

**Comment by lauriejim** [comment]
The migration PR https://github.com/strapi/strapi/pull/651 has been merge. Will be available in few minutes
