### ISSUE TITLE
Moving components inside Dynamic Zone doesn't affect UI, but changes are saved to database

### ISSUE THREAD

**Issue by denisgoryaynov** [strapi/strapi#6562]
**Describe the bug**
When using the arrow inside a Dynamic Zone to move a component up or down to reorder the list the admin UI doesn't reflect this update, but pressing save and opening the content type now shows the correct order. As far as I can tell this only happens when trying to move two components of the same kind, but this is not always true.

**Steps to reproduce the behavior**

1. Create the following content type and dynamic zone (as shown in screenshot)
2. Create a page with two or more components from the dynamic zone
3. Try to reorder the sections inside the Dynamic Zone

**Expected behavior**
When using the arrows inside a Dynamic Zone the admin UI should reflect this change, but instead the order stays the same until you save and reload the page

**Screenshots**
<img width="837" alt="Schermata 2020-06-05 alle 14 55 52" src="https://user-images.githubusercontent.com/16140813/83879027-50e12f00-a73d-11ea-9231-0bd1d7b19177.png">
<img width="832" alt="Schermata 2020-06-05 alle 14 56 00" src="https://user-images.githubusercontent.com/16140813/83879048-55a5e300-a73d-11ea-96cf-2d00cb72a09f.png">

**System**

- Node.js version: 12.17.0, 12.18.0
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database:
- Operating system: macOS 10.15.5, Ubuntu 16.04.5 LTS

**Comment by denisgoryaynov** [comment]
I did a little bit of investigation and found out that the issue is inside this [component](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js).

At [line 36](https://github.com/strapi/strapi/blob/dc1d29aae2e67e5914e13ab4464fc339840adbbd/packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js#L36) this method:
```
const getDynamicDisplayedComponents = useCallback(() => {
  return get(modifiedData, [name], []).map(data => data.__component);
}, [modifiedData, name]);
```
returns an array of strings representing a component name, like this:
`["page.media-and-text-layout", "page.media-and-text-layout"]`

So if a component is moved up or down `modifiedData` does change, but the computed array is still: `["page.media-and-text-layout", "page.media-and-text-layout"]` and react doesn't update the UI.

A fast fix would be to change `getDynamicDisplayedComponents` to return an array of objects instead, like this:
```
const getDynamicDisplayedComponents = useCallback(() => {
  return get(modifiedData, [name], []).map(data => ({ 
    id: data.id, 
    componentUid: data.__component
  }));
}, [modifiedData, name]);
```

and change the usage at [line 88](https://github.com/strapi/strapi/blob/dc1d29aae2e67e5914e13ab4464fc339840adbbd/packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js#L88) from this:
`{getDynamicDisplayedComponents().map((componentUid, index) => {`

to this:
`{getDynamicDisplayedComponents().map(({ componentUid, id }, index) => {`

and [line 94](https://github.com/strapi/strapi/blob/dc1d29aae2e67e5914e13ab4464fc339840adbbd/packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js#L94) to use the new "id" field instead of the array index as key:
`<div key={index}>` --> `<div key={id}>`

This way react does recompute the interface and displays dynamic zone with the correct order.

**Comment by lauriejim** [comment]
Hello! I just tried and it works.
Here  is what I did - [video](https://www.loom.com/share/decfa735961c446f9343cb56439229ef)
Let me know if I missed somthing

**Comment by denisgoryaynov** [comment]
Hi! Thank you for your time! I updated to version 3.0.2 and it seems that the issue is solved now!
