### ISSUE TITLE
Email Settings Gear Wheel Missing

### ISSUE THREAD

**Issue by nigel5** [strapi/strapi#6577]
**Describe the bug**
The button to go to email settings is not visible. Directly visiting the link from the documentation http://localhost:1337/admin/plugins/email/configurations/development will redirect to Login page, even if already logged in.

**Steps to reproduce the behavior**

1. Login to admin panel with default admin account
2. Visit Plugins using the left navigation pane
3. Observe the settings cog button for Email is not visible

**Expected behavior**
Expect there to be a ⚙️ gear wheel to go to email settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/28766663/83990127-986ee300-a916-11ea-82c8-30029b7d2d54.png)

**Code snippets**
The cog is not rendered in the HTML either.

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database:
- Operating system: Windows 10 17763
- Chrome version: 83.0.4103.61

**Additional context**
Package.json

> {
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "sqlite3": "latest",
    "strapi": "3.0.1",
    "strapi-admin": "3.0.1",
    "strapi-connector-bookshelf": "3.0.1",
    "strapi-plugin-content-manager": "3.0.1",
    "strapi-plugin-content-type-builder": "3.0.1",
    "strapi-plugin-email": "^3.0.1",
    "strapi-plugin-upload": "3.0.1",
    "strapi-plugin-users-permissions": "3.0.1",
    "strapi-provider-email-sendgrid": "^3.0.1",
    "strapi-utils": "3.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "[redacted]"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

**Comment by derrickmehaffy** [comment]
See: https://strapi.io/documentation/v3.x/plugins/email.html#configure-your-provider

**Comment by soupette** [comment]
Thanks @derrickmehaffy for closing this issue. More generally the plugins' settings will move the settings view in the administration panel which you can access using the link in the main menu. Regarding the email configuration this setting has moved to files which is also the case for the upload providers.

**Comment by adriatic** [comment]
I am one of the unfortunate users that fell in this trap, however, @derrickmehaffy's advice  [above](https://github.com/strapi/strapi/issues/6577#issuecomment-640359100) is not really helpful, as I explained in my [discussion post](https://github.com/strapi/strapi/discussions/6720) today.

The explanation provided by @soupette [above](https://github.com/strapi/strapi/issues/6577#issuecomment-640404299) is another example of a confusing document. It would be great to have it written as a part of the [Upload](https://strapi.io/documentation/v3.x/plugins/upload.html), adding the links to the text

> More generally the plugins' settings will move the settings view in the administration panel which you can access using the link in the main menu.

- what settings view on the administration panel?
- what link in the main menu?

Despite all affection and positive thoughts for strapi, I have to admit that this is pretty frustrating (chasing this took me many hours and I am not an inch closer to the solution 😄 )

**Comment by derrickmehaffy** [comment]
@adriatic I have a big'ol notice pinned to the top of the issues https://github.com/strapi/strapi/issues/6710
