### ISSUE TITLE
Strapi develop keeps failing

### ISSUE THREAD

**Issue by CodingXD** [strapi/strapi#6579]
**Describe the bug**
I installed strapi using the command `npx create-strapi-app my-project --quickstart`. Installation was successful but as soon it started development, it fails with error message 

> $ strapi develop                                                                                                          [2020-06-08T07:21:55.793Z] error Error: bind EACCES 0.0.0.0:1337                                                              at listenOnMasterHandle (net.js:1380:18)                                                                                  at rr (internal/cluster/child.js:132:12)                                                                                  at Worker.<anonymous> (internal/cluster/child.js:99:7)                                                                    at process.onInternalMessage (internal/cluster/utils.js:47:8)                                                             at process.emit (events.js:327:22)                                                                                        at emit (internal/child_process.js:876:12)                                                                                at processTicksAndRejections (internal/process/task_queues.js:85:21) 

I tried with both npm and yarn. Same result. Nothing happens after waiting a long time.

**Steps to reproduce the behavior**

1. Open cmd
2. Type `mkdir velankannimatha-backend && cd velankannimatha-backend`
3. Type `npx create-strapi-app velankannimatha --quickstart`

**Screenshots**
![yarn fail](https://user-images.githubusercontent.com/23221413/84003947-672efb00-a988-11ea-97a9-06aa014dc091.PNG)
![npm fail](https://user-images.githubusercontent.com/23221413/84003949-68602800-a988-11ea-8dca-74ba62e110e0.PNG)

**System**

- Node.js version: v12.18.0
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: sqlite3
- Operating system: Windows 10 64bit

**Comment by derrickmehaffy** [comment]
`error Error: bind EACCES 0.0.0.0:1337` It would appear you don't have the permissions required to bind on that port, increase the port number in the `config/server.js` say to something like `9000`

**Comment by CodingXD** [comment]
Yes, it is working now. Thank you
