### ISSUE TITLE
Support Apple Sign In

### ISSUE THREAD

**Issue by pffigueiredo** [strapi/strapi#6586]
Grant needs to be updated to last version (5.2.0), in order to support Apple Sign In.

**Comment by danielgek** [comment]
related to #4635

**Comment by christophemacabiau** [comment]
This becomes necessary...

_Apps that use a third-party or social login service (such as Facebook Login, Google Sign-In, Sign in with Twitter, Sign In with LinkedIn, Login with Amazon, or WeChat Login) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option._
https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple

**Comment by malikdoksoz** [comment]
There are those who are still waiting for the Apple Sign In to be added.

**Comment by derrickmehaffy** [comment]
If anyone is willing to submit a PR to update Grant, please feel free :smiley:

**Comment by malikdoksoz** [comment]
If login with social media will be added in mobile applications, Apple requires its own system (Sign in with apple). Big problem.

**Comment by Lith** [comment]
We have a mobile app since one year, develop with React + Expo, and our app has been refused because of "Apple Sign-in" missing feature.
It's now a big issue for many of us, I think it's now really urgent to add it !

@derrickmehaffy I agree with you, but I think it's a core feature need to be develop by Strapi themself... It's not possible to wait "someone" for this feature. 

Thanks <3

**Comment by derrickmehaffy** [comment]
@Lith we have already looked into, and to properly test we would need a license (as would anyone wanting to use the sign-in).

At this time we will not be purchasing one of these licenses, and as such we can't test our code ourselves.

We understand the urgency for many of you and we would love to see all of you work together on this. At the moment our priorities are set at least until the end of Q1 2021, after that we may be able to take a look.

**Comment by derrickmehaffy** [comment]
As someone already started it, someone else is more than welcome to pick up the mantle, the PR was closed due to inactivity.

https://github.com/strapi/strapi/pull/6587

**Comment by Lith** [comment]
Hi @derrickmehaffy,

Due to your answer, I've decided to implement Apple Sign-In on my side, and provide to you soon a PR with the complete documentation process.
I understand your difficulty to manage Apple without application, and I can't pending 6 month more (because our application need to be published, and for now, we are blocked 😢)

I think some people has already implement it, but not share with the community, and many others need it right now.

Hope to finish this before the end of the week ;)

Thanks !

**Comment by lauriejim** [comment]
Yeah thank you for sharing your implementation! Can't wait to see a PR.
I really appreciate that.

**Comment by derrickmehaffy** [comment]
Agreed, would love to see a PR, and looking forward to it.

**Comment by yeohwaihong** [comment]
Any updates on this? Really need help implementing Apple Sign In on Strapi now to get my app approved on App Store. Thanks in advance!

**Comment by kabaros** [comment]
Sharing our implementation - `purest` does not support apple (don't think even 5.2 does), so I used `apple-signin-auth` library, it didn't feel right to share a PR as it's not inline with the other providers, adds a new dependency, and from what I understand, user-permissions is moving to `passport` anyhow  - but would happily do if @derrickmehaffy think it's ok. For now, hope this helps anyone stuck with Apple store new review guidelines, to get by:

- First follow the steps here https://strapi.io/documentation/v3.x/plugins/users-permissions.html#prepare-your-files and copy user-permissions from node_modules into your project root, and follow the steps similar to adding discord provider, then update Providers.js

```js
const appleSignin = require('apple-signin-auth');

switch (provider) {
    case 'apple': {
      try {
        const clientId = grant.apple.key; // this is your bundle ID as set in Apple Developer console (something like com.strapi.app) - add the signin with Apple capability to your app, then add the bundle ID to admin if you followed the docs (so you'd access it with grant.apple.key) or as process.env.APPLE_BUNDLE_ID, however you want

        const response = await appleSignin.verifyIdToken(access_token, {
          audience: clientId,
          ignoreExpiration: true, // ignore token expiry (never expires)
        });
        strapi.log.debug('Sigin with Apple:', response);
        callback(null, {
          username: response.email.split('@')[0],
          email: response.email,
        });
      } catch (err) {
        strapi.log.error('Apple Signin failed', err);
        callback(err);
      }
      break;
    }
```

**Comment by derrickmehaffy** [comment]
There is an RFC located here: https://github.com/strapi/rfcs/pull/20

**Comment by derrickmehaffy** [comment]
closing this in favor of the RFC
