### ISSUE TITLE
Button "Cancel" is not functioning when creating a new entry for a Content Type

### ISSUE THREAD

**Issue by Freakspot** [strapi/strapi#659]
**Node.js version**:
9.5.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0.-alpha.10.1
**Operating system**:
Antergos

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The Button "Cancel" (see screenshot below for identification) does not function at all.
![image](https://user-images.githubusercontent.com/2371427/36307708-9d5d4492-131d-11e8-98f6-7dda5bf404fb.png)
**If the current behavior is a bug, please provide the steps to reproduce the problem**

1. Open Content Type
2. Create new entry
3. Hit button

**What is the expected behavior?**
Cancel the current process and be taken back to your Content Type. Essentially the same thing that happens when you use the back arrow located next to the Strapi logo.

**Comment by soupette** [comment]
Hi @Freakspot  the button cancel behavior is to empty all your fields. In this way, redirecting the user back to List view wasn't implemented.

**Comment by derrickmehaffy** [comment]
It may be worth adding a clear button for that purpose and modifying the cancel button to return to the list view. Or change the cancel button instead to say clear.

**Comment by Freakspot** [comment]
Oh I see! Thanks for clarifying that @soupette.
I'd agree with @derrickmehaffy, though. Just to make that a little bit more obvious for new users.

**Comment by denislutz** [comment]
I agree this is small but it looks like a bug if it stays like that. You expect to go back by the cancel button and nothing is happening. Please rename it or add a function to go back.

**Comment by soupette** [comment]
Thanks @abdonrd the button has been renamed 🎉🎉.
