### ISSUE TITLE
is owner policy from documentations not working with mongo

### ISSUE THREAD

**Issue by hazem-a1** [strapi/strapi#6590]
**is owner policy from documentations not working with mongo **
post with relation with user as described in this docs  https://strapi.io/documentation/v3.x/guides/is-owner.html
the only different  using mongo with  atlas 

![image](https://user-images.githubusercontent.com/53303934/84063634-a0379180-a9c1-11ea-91e2-e3458d2fa369.png)

![image](https://user-images.githubusercontent.com/53303934/84063699-c0675080-a9c1-11ea-903b-d94381c43cf2.png)

![image](https://user-images.githubusercontent.com/53303934/84063735-cf4e0300-a9c1-11ea-8554-a3f4f5e78bff.png)

**Steps to reproduce the behavior**

1. get jwt 
2. post request to  /jobs  
3. when deleting this line 
      ctx.request.body.author = ctx.state.user._id;
      ctx.request.body.author = ctx.state.user._id;
      data.author = ctx.state.user.id;
from the create function  every thing works find but with out author prop 
4. try the same scenario  with sql  works fine with  author prop related to the jwt sended with post req 

**Expected behavior**
add author prop to the document 
**Screenshots**

**Code snippets** 
api controller jobs.js
  async create(ctx) {
    let entity;
    if (ctx.is("multipart")) {
      const { data, files } = parseMultipartData(ctx);
      // console.log(ctx.state.user._id);

      data.author = ctx.state.user.id;
      entity = await strapi.services.job.create(data, { files });
    } else {
      ctx.request.body.author = ctx.state.user._id;
      // console.log(ctx.state.user._id);

      entity = await strapi.services.job.create(ctx.request.body);
    }
    return sanitizeEntity(entity, { model: strapi.models.job });
  },
**System**

- Node.js version: v14
- NPM version: 6.14.4
- Strapi version: v3.x
- Database: mongo atlas
- Operating system: windows 10

**Additional context**
also get this warning when start the server  i now that case the node version:

(node:11236) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11236) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:11236) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:11236) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency

**Comment by hazem-a1** [comment]
just debug more and all done

**Comment by HelpMe-Pls** [comment]
@hazem-a1 How did you fix this ? I got this error whenever I start the Strapi server and seems like it causes empty POST request somehow ?
![image](https://user-images.githubusercontent.com/43715386/148165595-0192c57b-1d70-412e-9a81-090cde5c7a9b.png)
![image](https://user-images.githubusercontent.com/43715386/148165625-86c74fea-3768-4619-a635-df15d4e114bd.png)
