### ISSUE TITLE
There is no info about database in installation documentation and CLI

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#6591]
I am trying to install Strapi 3.0.1.

**Problem**: as a developer I would like to know the type of installed database, but there is no such information.

**Docs**: https://strapi.io/documentation/v3.x/getting-started/quick-start.html
There is no information about default database in docs.

**Docs**: https://strapi.io/documentation/v3.x/installation/cli.html
I could find only info that it's possible to use another database than default one. But there is no information which one is default database. 

**Installation process with CLI**: `yarn create strapi-app my-project --quickstart`
There is no information about default database in help text during installation process.

Node: 12.18.0
Yarn: 1.22.4

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
