### ISSUE TITLE
Documentation: Add info about --no-run option during installation process

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#6593]
I am trying to install Strapi 3.0.1.

There are docs about installation process:
https://strapi.io/documentation/v3.x/getting-started/quick-start.html
https://strapi.io/documentation/v3.x/installation/cli.html

There is only option `--quickstart` in these docs. 

I found option `--no-run` in the blog post https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi.

Please, add all options of Strapi CLI to your documentation about installation process.

**Comment by derrickmehaffy** [comment]
Docs for CLI are located here: https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-new

**Comment by teinett** [comment]
I am sorry to say, but all the docs are mess now after owners changed commands and moved from @beta versions to stable one.

For example: installation process in https://strapi.io/documentation/v3.x/installation/cli.html
`yarn create strapi-app my-project --quickstart`or `npx create-strapi-app my-project --quickstart`.
The main command is: _create strapi-app_ or _create-strapi-app_

If we go to your link https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-new:
Create a new project:`strapi new <name>`
Is it yarn? Is it npm? Is it npx?
The main command is: _strapi new_ 

For now I am not sure which command I should use and which docs are the one truth: blog post, docs in getting started or specific docs about every part of Strapi.

Also, if Strapi has this CLI docs, I suggest to add link to this doc to the installation tutorials.
