### ISSUE TITLE
Have clear error messages in tooltip

### ISSUE THREAD

**Issue by cpandit201** [strapi/strapi#6598]
**Describe the bug**
While saving a new collection type, I faced an error. Let the user know about the error description in the tooltip provided

**Steps to reproduce the behavior**

1. Create a new collection type
2. Create a UID field of MaxLength greater than 500
3. Save the collection type
4. See error tooltip without any clue of what happened in background, 

As a dev, I thought it was an issue with my mongo atlas cluster, When checked the network logs, the concise error message indicating the root cause but was not shown in the tooltip

{"error":{"contentType.attributes.productId.maxLength":["contentType.attributes.productId.maxLength must be less than or equal to 256"]}}

**Expected behavior**
Let the user know in the tooltip mentioned about the error description rather than just letting user see a message "An error occoured"

**Screenshots**
![image](https://user-images.githubusercontent.com/42322819/84125251-e8a28e00-aa59-11ea-8de6-9a1c3b2ef586.png)

**System**

- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version:  "strapi": "3.0.1"
- Database: mongo-atlas
- Operating system: osx mojave

**Comment by derrickmehaffy** [comment]
@soupette

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
Can you please try to have a look in the code base of the admin of the Content Type Builder plugin.
I will appreciate your contribution on it.

**Comment by cpandit201** [comment]
Thanks for suggesting, will try to take this up

**Comment by soupette** [comment]
@cpandit201 @lauriejim we could easily display the errors in the content type builder by doing the following:

1. Create a utility to display the errors in the notifications:

```
const displayErrors = error => {
  const errorObject = get(error, ['response', 'payload', 'error'], {});

  if (isEmpty(errorObject)) {
    strapi.notification.error('notification.error');
  }

  Object.values(errorObject).forEach(errorArray => {
    strapi.notification.error(errorArray.join(' '));
  });
};
```
2. In this [file](https://github.com/strapi/strapi/blob/6774667c65925cc2b6ced088200c70a4c0720e95/packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js#L229-L232) we could replace the `console.error({ err })` by `displayErrors(err)`

**Comment by Cr0s4k** [comment]
> @cpandit201 @lauriejim we could easily display the errors in the content type builder by doing the following:
> 
> 1. Create a utility to display the errors in the notifications:
> 
> ```
> const displayErrors = error => {
>   const errorObject = get(error, ['response', 'payload', 'error'], {});
> 
>   if (isEmpty(errorObject)) {
>     strapi.notification.error('notification.error');
>   }
> 
>   Object.values(errorObject).forEach(errorArray => {
>     strapi.notification.error(errorArray.join(' '));
>   });
> };
> ```
> 
> 1. In this [file](https://github.com/strapi/strapi/blob/6774667c65925cc2b6ced088200c70a4c0720e95/packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js#L229-L232) we could replace the `console.error({ err })` by `displayErrors(err)`

Started this in https://github.com/strapi/strapi/pull/7737 basing on your comment!

**Comment by MuhammadHasham23** [comment]
Can I pick this up? if nobody is actively working on this issue?

**Comment by derrickmehaffy** [comment]
will be "fixed" in the v4
