### ISSUE TITLE
Custom content type names for the admin

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#661]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Name of Content Types do not handle spaces well and do not keep proper capitalization of content types that contain spaces.
See the following example:

![strapi-menu-cutoff](https://user-images.githubusercontent.com/8593673/36322158-941ad5a2-1309-11e8-94d5-e53917d66912.PNG)

**What is the expected behavior?**
Content types should contain the ability to give a name that will keep proper Capitalization and spaces.

**Comment by derrickmehaffy** [comment]
Addition of custom Plural names is also something that should be added as some words do not have have a plural form.

**Comment by lauriejim** [comment]
Hi @derrickmehaffy Yes it's a good issue. It's could be super cool to handle it.

**Comment by derrickmehaffy** [comment]
@lauriejim Basically this is just a "Quality of Life" change that wouldn't have any effect on the API itself. More so just a visual variable for the Admin Panel. As I know in the future you guys plan to have Admin panel ACLs and non-technical Users are almost guaranteed to complain about the strange formatting. :)

I hate to reference another project that is more or less a competitor  to strapi but loopback3 has something similar that made a lot of sense.

My thought is something like:
```
DisplayName : What is shown on the Admin Panel
DisplayNamePlural : Plural form of DisplayName
Name : Same as current, used to store in database, API endpoints, ect
Plural : Same as name but plural
```

In that plural forms do not need to be manually defined but can be. The same would apply to displayname where you could define it but instead it would just default to name.

**Comment by lauriejim** [comment]
Thank you for these details.

**Comment by Aurelsicoko** [comment]
Love the idea! It could be easily handled. It's more like an "end-user" issue but as you can see we like clean UI so we definitely have to add this feature in the near future. Recently, we already did something similar with the policies.

```js
module.exports = {
  label: 'User authenticated',
  description: 'Check if the user is authenticated',
  handler: async (ctx, next) => {
    if (!ctx.state.user) {
      return ctx.unauthorized();
    }

    await next();
  }
};
```

It allows you to add description and label to a policy. We'll use this label and description to improve the Permissions page in the adminstration panel.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko glad to hear it should be fairly easy. I'm new to admin panel design, or I would take a look at solving it myself. No rush though, I know you guys are focusing on making things stable which is much more important that QOL features :P

**Comment by jsamr** [comment]
@derrickmehaffy Great proposition. It would be even nicer if it was pluggable in UI localization module.

**Comment by kadaan** [comment]
Following what @derrickmehaffy stated, the api naming should be automatically generated, but able to be overridden.

**Comment by derrickmehaffy** [comment]
@jsamr and @kadaan I agree on both, going with localization it should be automatically generated as kadaan had said using the language specified but able to be overwritten for the admin view. Personally on the backend I think it should remain in English as almost all projects tend to stick to English backend anyway but that is just my opinion.

But I fully agree on localization on the front end, especially with future changes to the Admin panel permissions to allow for granular control on who can see certain items on the panel.

**Comment by derrickmehaffy** [comment]
This is an example of one of the terrible automated plural forms created by default:
![image](https://user-images.githubusercontent.com/8593673/39582201-48b3a420-4ea2-11e8-875e-063cd4785e0f.png)


siteGr -> Sitegrs
siteGs -> Sitegs
siteGy -> SiteGies (completely wrong lol)

**Comment by Aurelsicoko** [comment]
To make a resume on this issue and the related #1055, here are my thoughts:

- We should remove the automatic pluralization of the model' names in the left menu.
- We should offer a way to customize the link value in the left menu. I thought that the `Configurations` link at the bottom of the menu can be the right place to do that. It also means that we need to take care of the i18n support (in another iteration?). We won't store the data in files but we'll certainly use the Core Store API.
- We should create a REST routes & documentation plugin (like Swagger) to be able to generate and customise the documentation, but also edit routes name, policies, etc.
- The table/collection names are already editable through the Content-Type Builder plugin (Advanced Settings tab).

We won't be able to ship all of this in one iteration. A good start will be to focus on the two first points 👍

**Comment by derrickmehaffy** [comment]
1. `We should remove the automatic pluralization of the model' names in the left menu.` Agree 100%, I understand why they default to plural (generally you are storing multiple users, thus user -> to users), but in this case if someone wishes to use a plural form they could just name it as such. Obviously the backend api can still use these forms but for the left menu it really shouldn't be there

2. `We should offer a way to customize the link value in the left menu. I thought that the Configurations link at the bottom of the menu can be the right place to do that. It also means that we need to take care of the i18n support (in another iteration?). We won't store the data in files but we'll certainly use the Core Store API.` Not sure what the i18n support is, I'll have to research that a bit, As for the data in files vs database, I think this is fairly debatable. As once this value is set its unlikely to change during production (and in many cases it shouldn't change) Thus I think this is something that should be defined in the files. To me the core store table is used for variables that may change during normal usage.

3. `We should create a REST routes & documentation plugin (like Swagger) to be able to generate and customise the documentation, but also edit routes name, policies, etc.` PLEASE YES! 😄 

4. `The table/collection names are already editable through the Content-Type Builder plugin (Advanced Settings tab).` Yup no issues there

I think removing the pluralization form and working on the left menu customization should be fairly high on the list as a swagger integration or swagger like will take quite a bit more time.

**Comment by Aurelsicoko** [comment]
About the point 2, we shouldn't store in a file. Imagine the case when the marketing team want to rename a link in the menu in production? If we are storing the data in the file, it means that we should deploy again for a minor front-end change... This is not optimal. I still think we should use the Core Store API for storing this kind of front-end information

**Comment by derrickmehaffy** [comment]
@Aurelsicoko fair point, considering this variable is only going to affect the frontend adminUI.

**Comment by lauriejim** [comment]
Will move it in content manager settings. https://github.com/strapi/strapi/issues/1359
Two issues are linked. I close this one.
