### ISSUE TITLE
Koa-i18n is not working with policies 

### ISSUE THREAD

**Issue by jeremy-hubsy** [strapi/strapi#6613]
Hello 👋 

**Describe the bug**
The koa-i18n package works well in `api folder` but it doesn't seem to work in `/config/policies. `

**Steps to reproduce the behavior**

1. Manually create a JavaScript file named isAllowed.js in /config/policies/ 
2. Define errors in /config/policies/ with the Koa syntax (example: `if (!room) return ctx.notFound("roomNotFound");`
3. Associate isAllowed policie to any route in your project.
4. Follow the migration guide to change structure of config files middleware.js and under settings add:
 ```
settings: {
    favicon: {
      path: "favicon.ico",
      maxAge: 86400000,
    },
language: {
      enabled: true,
      defaultLocale: "en_us",
      modes: ["query", "subdomain", "cookie", "header", "url", "tld"],
      cookieName: "locale",
    },
```
5. in /config/locales/en_us.json give the corresponding error to `"roomNotFound"`: `"Sorry, the room you're requesting wasn't found.",`
6. call the route where you define the policie

**Expected behavior**
The response should be `"Sorry, the room you're requesting wasn't found."` Instead got `"roomNotFound"`

**Code snippets**
/config/policies/isAllowed.js
```
module.exports = async (ctx, next) => {
  const room = await strapi
    .query("room")
    .findOne({ id: ctx.params.id }, "venue.company.users");

  if (!room) return ctx.notFound("roomNotFound");
}
```
/config/middleware.js
```
module.exports = {
  timeout: 100,
  load: {
    before: ["responseTime", "logger", "cors", "responses", "gzip"],
    order: [
      "Define the middlewares' load order by putting their name in this array is the right order",
    ],
    after: ["parser", "router"],
  },
  settings: {
    favicon: {
      path: "favicon.ico",
      maxAge: 86400000,
    },
    public: {
      path: "./public",
      maxAge: 60000,
    },
    language: {
      enabled: true,
      defaultLocale: "en_us",
      modes: ["query", "subdomain", "cookie", "header", "url", "tld"],
      cookieName: "locale",
    },
}
```

/api/**/config/routes.json
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/bookings",
      "handler": "booking.find",
      "config": {
        "policies": ["global::isAllowed"]
      }
    }
}
```

**System**

- Strapi 3.0.1

**Comment by lauriejim** [comment]
Did you follow any documentation to try this implementation?

**Comment by jeremy-hubsy** [comment]
Hey @lauriejim 
Thanks for your reply. 
I install manually `npm i koa` on my project with the `strapi 3.0.1` version and it is working now. 
On the strapi `3.0.0-beta.18.3` version  it was already install but it does not seem to be install on the strapi `3.0.1. `
Is it normal?

**Comment by lauriejim** [comment]
I don't know, sounds good if it works now.
I'm closing this issue.
