### ISSUE TITLE
Insertion of certain field names lead to database crash "on"

### ISSUE THREAD

**Issue by bevenio** [strapi/strapi#6614]
Hi 👋

**Describe the bug**
The strapi admin UI allows the insertion of field names inside the content type builder that lead to a database crash (mongoDB)

**Steps to reproduce the behavior**

1. Open the strapi admin UI
2. Create a new content type with a field called "on" with "Boolean" as the type
3. Save the content type

**Expected behavior**
Blacklisting certain field names that will lead to database errors

**System**
- Node.js version: v12.13.0
- Strapi version: 3.0.1
- Database: MongoDB
- Operating system: Centos 8

**Additional context**
To fix the issue I had to remove the JSON-File from the created model template (*.settings.json)

**Comment by derrickmehaffy** [comment]
hmmm @soupette @alexandrebodin looks like we need to update the "not-allowed" list lol

**Comment by soupette** [comment]
@derrickmehaffy that list is going to be endless 😂!

@Convly or @petersg83 can you check?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy that list is going to be endless 😂!
> 
> @Convly or @petersg83 can you check?

Yes.... Yes it will until we find a different way to deal with the "names"
