### ISSUE TITLE
Column won't delete

### ISSUE THREAD

**Issue by beRoller** [strapi/strapi#6623]
hello some bug on deleting a column test(refer on the screenshot) on SQL Postgress

when you delete a column on the **content type builder** page when it saves it is removed but on the database, they don't delete the column

**Steps to reproduce the behavior**
1. Go to **PLUGINS**>**Content-Types Builder**>**Create new collection type**
2. **create** 2 columns and save
3. **check** the Postgres database
3. then **delete** the 1 column and save
4. **check** the **database** to see if the **column** is **deleted** or not

**Expected behavior**
it should be deleted on the JSON and database but nothing changes if you delete a column test

**Screenshots**
![image](https://user-images.githubusercontent.com/14256208/84325116-aa69b380-abac-11ea-810c-46e5b4c10983.png)
![image](https://user-images.githubusercontent.com/14256208/84325152-b6557580-abac-11ea-99b3-df26d6e7d7e8.png)

**System**
- Node.js version: v12.x.x
- NPM version: 6.10.0
- Strapi version: 3.0.1
- Database: postgres
- Operating system: Windows 10 1903 (build 18362.476) 

**additional note**
when you delete the column test on the database it will fix the problem

thanks

**Comment by derrickmehaffy** [comment]
Duplicate #1114
