### ISSUE TITLE
Media Library Settings (COG Icon) option not available in plugins list

### ISSUE THREAD

**Issue by Jonie-Jacob** [strapi/strapi#6625]
**Describe the bug**
I have tried to integrate the 'strapi-provider-upload-aws-s3' plugin for media upload. The media library settings COG icon is not visible in the plugins list for me to config my provider deatils. 
I have tried adding the './extensions/upload/config/settings.json' file with required data as mentioned in this url, 'https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider'.

**Steps to reproduce the behavior**
1. npx create-strapi-app my-project --quickstart
2. npm install strapi-provider-upload-aws-s3 --save
3. Click on the plugins from the admin sidebar.
4. The media library plugin listed in the list does not have the settings option.

**Expected behavior**
The COG icon must be availabe in the media library plugin listed under the plugins section of the admin UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/45901466/84353051-10216400-abdc-11ea-807c-ba5612c8ec25.png)

**System**

- Node.js version: 12.18.0
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: mysql 5.6
- Operating system: ubuntu

**Comment by derrickmehaffy** [comment]
Wrong docs:

https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider

**Comment by Jonie-Jacob** [comment]
> Wrong docs:
> 
> https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider

Thank you derrickmehaffy for providing the correct doc link.
However I am still facing the same issue. I am not able to see the COG icon in the media library plugin listed along with other plugins.
I have created the ./config/plugins.js file with the correct config values.
![image](https://user-images.githubusercontent.com/45901466/84458769-67c6da80-ac83-11ea-810c-467d0c3580f8.png)

**Comment by adriatic** [comment]
I run into the same issue - also closed by @derrickmehaffy using the same explanation. Unlike @Jonie-Jacob, I tried to use the "strapi-provider-upload-cloudinary: plugin". So, allow me to expand a bit, using a similar screenshot from my app:

![image](https://user-images.githubusercontent.com/2712405/84952637-48371400-b0c0-11ea-8a6d-c29f7da3f1f9.png)

This app was created with the current Strapi (see below)
```
 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Wed Jun 17 2020 16:46:56 GMT-0400 (Eastern Dayl… │
│ Launched in        │ 1040 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 3432                                             │
│ Version            │ 3.0.2 (node v12.14.0)                            │
└────────────────────┴──────────────────────────────────────────────────┘
```

Since there is only the delete icon on the Media Library Plugin, clearly that plugin cannot be configured on the page at http://localhost:1337/admin/list-plugins.

Does this mean how this plugin can only be configured by creating / editing the file at `./config/plugins.js` ? If that is the case, please explain why this (config.js) does not exist, despite having the plugin ' "strapi-provider-upload-cloudinary": "^3.0.2"` installed via
```
yarn add strapi-provider-upload-cloudinary
```

**Comment by derrickmehaffy** [comment]
@adriatic it's not a bug because the file doesn't exist, the documentation states to create it if it doesn't exist.

As my notice states: https://github.com/strapi/strapi/issues/6710

Yes it's all done via files now. I've closed about 20 issues all saying the same thing "cog missing" hence the short and to the point message

**Comment by adriatic** [comment]
Calling this a bug was **_premature_** on my part, sorry about that. I should have called a case of "incomplete documentation" - most likely a consequence of the pressure to release stable version 3.x 

Also, the fact that approx. 20 reported problems were closed with the diagnosis "do not use old documentation") may suggest that the warning about [plugins configuration change](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings) was not "spelled loud enough".

**Comment by derrickmehaffy** [comment]
The short and sweet of it, no one ever goes and reads the migration guides (even though they are linked on every release they are needed on, and those that skip versions don't go back and read them).

We can keep up with the core documentation reflecting every little changes from previous versions, that is just going to confuse new users. The main documentation should reflect **exactly how it is in the current supported release** only, and as my notice states, it is clearly defined you configure them via files and not via the UI.

**Comment by chano-navarro** [comment]
Hi, guys. 

I read the documentation (and all the forum questions and answers) like a hundred times and nothing really worked for me. I get so frustrated (and I'm brand new on this development world).

I leave you a link with an article that helped me to solve my problem with cloudinary.
[https://medium.com/@kwinten.yc.li/strapi-set-default-file-upload-provider-to-s3-cloudinary-rackspace-5b8ef6f61daa](url)

Hope it helps you too!

**Comment by orange-and-red** [comment]
> The main documentation should reflect exactly how it is in the current supported release only, and as my notice states, it is clearly defined you configure them via files and not via the UI.

The deploying to AWS documentation for the current version still say to use the cog:
https://strapi.io/documentation/v3.x/deployment/amazon-aws.html#_3-configure-the-plugin-with-your-bucket-credentials

**Comment by rae004** [comment]
Why do all these strapi.io support links 404??? I installed the S3 provider package, created ./config/plugin.js with correct credentials, then created ./extensions/upload/config/settings.json with credentials. Started my dev environment uploaded an image and it still goes to ./public/uploads.  No error or link to S3, so I go to find docs/resources and everything 404s. The shocking part is this comments here are only six months old.  Does anyone have links to resources that load?
