### ISSUE TITLE
Documentation missing lifecycles (e.g. slug example)

### ISSUE THREAD

**Issue by sanderbz** [strapi/strapi#6628]
**Describe the bug**
The latest documentation does not mention lifecycle-hooks for models. The slug-example therefor doesn't work: https://strapi.io/documentation/v3.x/guides/slug.html#configure-the-layout-for-the-content-editor. The hooks (e.f. beforeSave, beforeUpdate) will not be fired. The new lifecycles format should be used in the examples of the documentation.

**Steps to reproduce the behavior**

1. Install new strapi
2. Use the hooks as in the slug-example (https://strapi.io/documentation/v3.x/guides/slug.html#configure-the-layout-for-the-content-editor)
3. Hooks will not be fired, as it needs to be in the new lifecycles hooks format (https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks)

**Expected behavior**
The documentation should provide examples that work with the latest lifecycles hooks.

**Code snippets**
Current (not working) example from documentation:
```javascript
module.exports = {
  beforeSave: async model => {
    if (model.title) {
      model.slug = slugify(model.title);
    }
  }
```
Expected:
```javascript
module.exports = {
  lifecycles: {
    async beforeCreate(model) {
      if (model.title) {
        model.slug = slugify(model.title);
      }
    }
  }
}
```

**System**

- Node.js version: v14.4.0
- Strapi version: 3.0.1

**Comment by nadershamma** [comment]
Is this being worked on? I found the same issue and had to dig around to know how to implement this. Happy to update the code example if no one else is already working on it.

**Comment by derrickmehaffy** [comment]
There was already a PR to the docs for it, t just hasn't been merged yet: https://github.com/strapi/strapi/pull/6572

**Comment by derrickmehaffy** [comment]
(Marking as closed as the PR exists, just needs to be reviewed and merged)
