### ISSUE TITLE
Renaming the name in collection type does not reflect on Roles and Permissions

### ISSUE THREAD

**Issue by anthonykhy** [strapi/strapi#6630]
1. After Created the Collection type, I named it as Blog, 
2. Save it
3. then i change the name from 'Blog' to 'Article'

in Roles and Permissions still showing 'Blog' but not Article.

<img width="898" alt="Screenshot 2020-06-11 at 10 45 26 PM" src="https://user-images.githubusercontent.com/129839/84401004-5656e180-ac35-11ea-9b62-3ca9d42cd4f6.png">

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
