### ISSUE TITLE
There is no "Add Content Type"

### ISSUE THREAD

**Issue by ballPointPenguin** [strapi/strapi#6639]
**Describe the bug**
I have built and run a fresh Strapi instance with a MongoDB. I have not done anything beyond create a user. The Content-Types-Builder menu shows the default content types but there is no link or button for creating a new content type. I cannot create any new content types.

**Steps to reproduce the behavior**

1. Go to localhost:1337/admin
2. Sign in
3. Click 'Content Types Builder'
4. see there is no option for creating or adding new content types

**Expected behavior**
As shown in the "Getting Started Videos": "Create your first content-type"

**Screenshots**
<img width="3008" alt="Screen Shot 2020-06-11 at 17 17 22" src="https://user-images.githubusercontent.com/35609/84444847-4674d880-ac08-11ea-8990-2bd74fc86ff1.png">

**System**

- Node.js version: 12.16.1
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: Mongo 4.2.7
- Operating system: Mac OS 10.15.5

**Additional context**
running with NODE_ENV=production
happens the same with NODE_ENV=development

There are no errors in the JavaScript console or the node stdout.
There are no bad statuses in the network tab.

**Comment by derrickmehaffy** [comment]
You don't need to specify the `NODE_ENV` for development as that is the default but you do need to use `yarn develop` / `npm run develop` / `strapi develop`. If Strapi is not ran with that command the CTB is disabled and you cannot modify/create/delete content types in production and staging, see: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

**Comment by ballPointPenguin** [comment]
wow. Thanks for the clarification. I'm not sure how I missed that tidbit.

**Comment by ballPointPenguin** [comment]
I can see how the rationale for this restriction might be related to how schema changes **are** code changes. But it also seems like a very severe limitation. I was planning to build and deploy a few client web sites with Strapi in hopes that the client would be able to maintain much of their own data needs, via the CMS.
But the fact that they cannot do this is a bit surprising to me. Imagine if WordPress or Drupal made you recompile from source code every time you wanted to create a new content type. For many end-users, this will be a deal breaker.

**Comment by JamMaster1999** [comment]
Hey guys I'm still having this issue. 

I'm running the command strapi develop. 
But the content types are still not showing up 
![Screen Shot 2020-11-24 at 6 02 53 AM](https://user-images.githubusercontent.com/46285145/100104305-dd31fc00-2e1a-11eb-90a4-4480b3c3a33e.png)

I can't edit anything in the content types

**Comment by derrickmehaffy** [comment]
@JamMaster1999 it is not possible to use the content-type builder on Heroku as the model settings are stored in files, when the Heroku dyno "sleeps" it wipes the local file system and pulls it from git when it "wakes up". Also any change in the code base that triggers a new build/deploy will also wipe the local file system. 

This is quite common on PaaS solutions and is why we disable the CTB there. See: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

This is the same reason you can't use SQLite or the default local uploads provider.

**Comment by JamMaster1999** [comment]
I understand. But isn't Strapi develop supposed to run the project locally? 
Do I need to manually set that? This is my server.js 
`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('', 'https://glacial-river-01756.herokuapp.com'),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'private')
    },
  },
});
`

Thanks and please advise

**Comment by JamMaster1999** [comment]
@derrickmehaffy 
I even created two separate environment folders one for production and one for development

Now the terminal is bringing this up 
![image](https://user-images.githubusercontent.com/46285145/100118422-afed4a00-2e2a-11eb-9327-244a5dd7207e.png)

and yet I still don't have access in Strapi. It says that autoReload feature must be enabled to see content type

server.js config in the development:
`module.exports = ({ }) => ({
  "host": "localhost",
  "port": 1337,
  "autoReload": {
    "enabled": true
  }
});
`
server.js config in the production:
`module.exports = ({ env }) => ({ host: env('HOST', '0.0.0.0'), port: env.int('PORT', 1337), url: env('', 'https://glacial-river-01756.herokuapp.com'), admin: { auth: { secret: env('ADMIN_JWT_SECRET', 'private') }, }, });`

**Comment by derrickmehaffy** [comment]
@JamMaster1999 Since this is a very old thread, can you please open up a Q&A on our forum and we can work through your problems there?

https://forum.strapi.io/

**Comment by JamMaster1999** [comment]
Sure! Here you go https://github.com/strapi/strapi/issues/8729#issue-749846249
@derrickmehaffy 
Thanks for the help in advance

**Comment by capsloq** [comment]
Same issue as @JamMaster1999 .
Can you provide the link to the forum thread?

**Comment by JamMaster1999** [comment]
https://github.com/strapi/strapi/issues/8729#issue-749846249
@capsloq here you go. Check your two things: Do you have admin_JWT in your .env file. Also setup two environments and include your admin_kwt in both of them

**Comment by mateoaldaba** [comment]
> Same issue as @JamMaster1999 .
> It worked for quite some time after deleting some content types it broke down and says "auto reload plugin is missing"
> Can you provide the link to the forum thread?

I have same issue. After deleting some content types it broke down.

@JamMaster1999 What do you mean with "have admin_JWT". Please could you explain more deeply


I have this on server.js

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
 autoReload: { 'enabled': true } , admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'a7c5e3117be3e8c32654c1648fa2b16f'),
    },
  },
});

**Comment by tarvos21** [comment]
Hi there,  set url to localhost in `config/server.js` may solve the problem.

**Comment by MarkEmerson** [comment]
windows: running strapi local
still no content types create buttons

what is the solution?

**Comment by derrickmehaffy** [comment]
@MarkEmerson please open a new issue as to not resurrect old ones, please provide as much information as you can.

Locking thread
