### ISSUE TITLE
error TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by PhantomxJoker** [strapi/strapi#6640]
When I migrate from alpha to v3.0.0, had an error about user-permissions plugin:
`error Bootstrap function in plugin "users-permissions" failed
[2020-06-12T01:15:06.300Z] error TypeError: Cannot read property '_id' of undefined
    at dbPermissions.map.p (/usr/src/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:267:59)
    at Array.map (<anonymous>)
    at Object.updatePermissions (/usr/src/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:266:46)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
`

For reproduce the error, do the next:

1. Migrate from alpha to RC3 using MongoDB
2. Set port to 3000 and run serve 

I guess that is something related to some DB collection but I'm no really sure

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: v3.0.0
- Database: MongoDB
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
Not sure where you got Strapi v1.0.0 but that version hasn't been supported in over 3 years and was built before the Alpha.

**Comment by PhantomxJoker** [comment]
@derrickmehaffy Sorry for that, the version is the last RC, the v3.0.0

**Comment by derrickmehaffy** [comment]
That honestly looks like you have some miss-matched versions or something odd going on with your db

**Comment by PhantomxJoker** [comment]
Just a question, I jumped from beta 26 to RC 3.0.0. In that case, I have just to use strapi@beta for the installation? I was searching for a newest one but I did not find anything

**Comment by PhantomxJoker** [comment]
Do

**Comment by PhantomxJoker** [comment]
I found the, I was running my Docker with an old version of Node.

Thank you

**Comment by hendrikgaffo** [comment]
I am getting the same error, but I did not upgrade anything. I am still running on v3.0.0-beta.20 since it was released. Interestingly everything works in dev (Ubuntu 16 LTS, Node 12.18.1), but not in production (Docker container with node:12.8.0-alpine).

@PhantomxJoker Which version of Node did you use in your container to make it work?

**Comment by PhantomxJoker** [comment]
Hi @hendrikgaffo ! I'm using the same version as you, but with the change I made a clean build too (using npm run build --clean). Not sure if did the trick, but worked for me

**Comment by weilaiqishi** [comment]
the same error,  on strapi the same 3.0.5, in my mongodb user-permission-permission table, some data without role, so dbPermissions.map err

**Comment by basavarajdodamani** [comment]
> 
> 
> the same error, on strapi the same 3.0.5, in my mongodb user-permission-permission table, some data without role, so dbPermissions.map err

Thanks for the hint @weilaiqishi ... We resolved this by removing the document from MONGODB without role! But this should not happen again, observation was that when a route and controller gets edited inthe project directory, it throws this issue. Route and controller files should be replaced as a whole when promoting code from one env to another.
I am not sure if there are any other rootacuses for this issue.

**Comment by Blessen** [comment]
Thankyou!!

**Comment by ms-mousa** [comment]
Just ran into this out of nowhere... didn't even need to reset my db to get across it.

**Comment by shivagouraram** [comment]
I encountered this issue today on version 3.5.3 when I was editing routes and controllers on my local instance. I am still figuring out how to resolve.

**Comment by bbrez1** [comment]
We have encountered this issue many times on our live server. It just happens out of nothing. It's very time-consuming to delete and re-do everything (a lot of tables to re-do all the permissions) + it shouldn't really crash the live server. Does anyone have any solution?

**Comment by bbrez1** [comment]
Still no solution? This makes Strapi completely unusable in production.

**Comment by priyadarsh** [comment]
> I encountered this issue today on version 3.5.3 when I was editing routes and controllers on my local instance. Deleting the records in user-permission-permission with empty role has resolved the issue. Thanks @basavarajdodamani

deleting the records with the below criteria on users-permissions_permission collection did solve the problem. But don't know the root cause

{"role": { $exists: false} }

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/bug-in-production/9122/3

**Comment by phamminhkhoa** [comment]
i go to DB and filter {"role": { $exists: false} } and fixed it but i don't know why it work

**Comment by irenefelita192** [comment]
thank you this post saved me, I got same problem on version 3.6.8, don't know why suddenly some roles are missing when I only upload some images. Got it working when I update the role at users-permissions_permission table (not delete it)
