### ISSUE TITLE
"Search for an asset" on Media Library loses focus while typing

### ISSUE THREAD

**Issue by feg624** [strapi/strapi#6641]
**Describe the bug**
On the Media Library plugin, when you start typing the search criteria into the "Search for an asset" field, the search is triggered after just one character, and the page refreshes, making the field to lose focus. This is very annoying behavior.

**Steps to reproduce the behavior**

1. Go to Media Library.
2. Click on "Search for an asset".
3. Start typing the search criteria.
4. The page reloads after each typed character, and the field loses focus.

**Expected behavior**
The "Search for an asset" field should keep focus.

**Screenshots**
N/A.

**Code snippets**
N/A.

**System**

- Node.js version: v12
- NPM version: N/A
- Strapi version: 3.0.1
- Database: Postgres
- Operating system: Linux

**Additional context**
N/A.

**Comment by lauriejim** [comment]
Hello!
Thank you for reporting this behavior.
Something I would super appreciate is if you can try to submit a PR to fix this issue.
The topic you are pointing has to be fixed and it could be done by someone from the Community (you 🤗).

Here is the [contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to help you to getting started for contributions to Strapi.

**Comment by teabyii** [comment]
@lauriejim I am trying to fix this issue. 
I run the `getstarted` project successfully, but don' t know how to make the page update when I modify the code in `strapi/packages/strapi-plugin-upload/admin/src`.
Any docs about it? 
Thank you.
