### ISSUE TITLE
Static resources cannot set the file cache time, and uploaded pictures cannot be cached.

### ISSUE THREAD

**Issue by varjay** [strapi/strapi#6645]
**Describe the bug**
Static resources cannot set his cache time, and uploaded files cannot be cached.

**Steps to reproduce the behavior**
I use `npm run develop` or `NODE_ENV=production npm run start`, and I can't get the desired result.

**Expected behavior**
You can set `application.json` which is the cache time, the uploaded resources can be cached.
If I wrote incorrectly in `application.json`, please write the correct code and post it in the reply, thank you!
**Screenshots**
<img width="726" alt="iShot2020-06-12下午03 16 51" src="https://user-images.githubusercontent.com/19402345/84475846-cf9b1680-acbf-11ea-84e7-b96fd7270abb.png">
<img width="861" alt="iShot2020-06-12下午03 15 48" src="https://user-images.githubusercontent.com/19402345/84475857-d1fd7080-acbf-11ea-9a3f-6bebe4bafd66.png">

**Code snippets**
See screenshot!

**System**

-Node.js version: v12.13.1
-NPM version: 6.14.5
-Strapi version: 3.0.1
-Database: mySql
-Operating system: macOS 10.15.5

**Comment by lauriejim** [comment]
Hi, thank you for your message.
@alexandrebodin do we still support this feature?

At the end @varjay , if you wan to cache your assets, I highly suggest you to use a tiers service to cache your stuff.
Cloudfront for example if you are using AWS.

**Comment by alexandrebodin** [comment]
The feature still is available and works, you need to configure your middleware in `config/middleware.js` -> `settings` -> `public` instead of `application.json`. 

looking at your screenshots, It seems like you haven't foolowed the stable migration guide : https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html

Closing as it is a usage issue

**Comment by varjay** [comment]
> The feature still is available and works, you need to configure your middleware in `config/middleware.js` -> `settings` -> `public` instead of `application.json`.
> 
> looking at your screenshots, It seems like you haven't foolowed the stable migration guide : https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html
> 
> Closing as it is a usage issue

@alexandrebodin Thanks for your help, I can now set the cache time under `public`. But I cannot set the cache for the uploaded files (`/public/uploads`), what should I do?
I have updated the content and screenshots, please help me, thanks.

**Comment by alexandrebodin** [comment]
hi @varjay indeed We refactored the middleware to serve uploaded files and there is no config available yet. This would be pretty easy to add.

**Comment by varjay** [comment]
> hi @varjay indeed We refactored the middleware to serve uploaded files and there is no config available yet. This would be pretty easy to add.
> 
> If you are intereseted in making a PR here would be the idea:
> 
> in `./packages/strapi-plugin-upload/middlewares/upload/index.js`
> 
> pass some configuration in
> 
> **Before**
> 
> ```js
> //..
> strapi.router.get('/uploads/(.*)', range, koaStatic(staticDir, { defer: true }));
> ```
> 
> **After**
> 
> ```js
> //...
> const localServerConfig = _.get(strapi.plugins.upload.config, 'localServer', {});
> strapi.router.get('/uploads/(.*)', range, koaStatic(staticDir, { defer: true, ...localServerConfig }));
> ```
> 
> and then this will allow to set the config you need in
> 
> `./config/plugins.js`
> 
> ```js
> module.exports = ({ env })=>({
>   upload: {
>     localServer: {
>       maxAge: 456790
>     }
>   }
> });
> ```

This problem has been solved, thank you for your help!
It is recommended that I can customize the cache time of the uploaded file later, or set a longer cache time by default! Uploaded files generally do not require immediate updates.

**Comment by ptitjes** [comment]
@varjay Sorry, but I didn't understand your last answer. How did you solve the problem ??
