### ISSUE TITLE
Error: Username already taken on new user registration

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#6651]
**Describe the bug**
After migrating to the stable version I had an issue where on new user registration I always got an error "Username already taken" or "Email already taken" even tho was registering a new user.

I had an email notification in my custom User.js model at `./extensions/user-permissions/models/User.js` which seemed to be the cause of the issue for me.

After some time troubleshooting, I found that oddly the destructuring of model attributes: `const { email, username } = model.attributes;` was what was causing the issue.

After using these variables without destructing like so:
```javascript

module.exports = {
  lifecycles: {
      afterCreate: async (model, attrs, options) => {
        await strapi.plugins.email.services.email.send({
        to: attrs.email, // ------ this here
...
        subject: `Hey ${attrs.username}, welcome to iJS!`,
      });
    }
  }
};
```

The issue seemed to be solved. This may not be the cause, as it feels incredibly odd that simple destructuring could cause an issue like this, however, this is what solved it for me.

Also if there were no function calls in the beforeCreate lifecycle the issue also wasn't present.

Someone else in the community asked this question so I figure it's not just me and may be worth looking into.
https://strapi.slack.com/archives/C0BLB2VJ7/p1591942797014000

Will try to cook up a reproduction, or if someone else has it, please post it below

**System**

- Node.js version: latest
- NPM version: latest
- Strapi version: 3.0.1
- Database: Postgres

**Additional context**
Migrated from Beta to Stable

**Comment by lauriejim** [comment]
Hello! The life cycle update is mentioned in the Migration Guide.
I think it's the reason of your issue.
