### ISSUE TITLE
ERROR: Create Strapi Project

### ISSUE THREAD

**Issue by lsguillory** [strapi/strapi#6655]
**Describe the bug**
I am a Newbie so please keep this in mind. 
I have tried to start a new Strapi project and get the following error which is the same if I use npx and npm as below with yarn: I successfully used Strapi approximately six months ago and had no problems. I am unsure what the problem is. I did reinstall npm and node to make sure that was not the problem. At one point when I tried to start Strapi, I got Strapi: no command. I reinstalled Strapi and the same messages as below appeared again. As I said, I am a Newbie and I am lost. 

yarn create strapi-app my-portfolio --quickstart
$ yarn create strapi-app my-portfolio --quickstart
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-strapi-app@3.0.1" with binaries:
      - create-strapi-app
Creating a new Strapi application at C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio.

Creating a quickstart project.
Creating files.
- Installing dependencies:
Dependencies installed successfully.

Your application was created at C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode.

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio
  yarn develop

> my-portfolio@0.1.0 build C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio
> strapi build "--no-optimization"

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'date-fns'
Require stack:
- C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi-utils\lib\parse-type.js
- C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi-utils\lib\buildQuery.js
- C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi-utils\lib\index.js
- C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi\lib\commands\build.js
- C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi\bin\strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi-utils\lib\parse-type.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\lsggu\Desktop\testStrapi-new\my-portfolio\node_modules\strapi-utils\lib\buildQuery.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lsggu\\Desktop\\testStrapi-new\\my-portfolio\\node_modules\\strapi-utils\\lib\\parse-type.js',
    'C:\\Users\\lsggu\\Desktop\\testStrapi-new\\my-portfolio\\node_modules\\strapi-utils\\lib\\buildQuery.js',
    'C:\\Users\\lsggu\\Desktop\\testStrapi-new\\my-portfolio\\node_modules\\strapi-utils\\lib\\index.js',
    'C:\\Users\\lsggu\\Desktop\\testStrapi-new\\my-portfolio\\node_modules\\strapi\\lib\\commands\\build.js',
    'C:\\Users\\lsggu\\Desktop\\testStrapi-new\\my-portfolio\\node_modules\\strapi\\bin\\strapi.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-portfolio@0.1.0 build: `strapi build "--no-optimization"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-portfolio@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lsggu\AppData\Roaming\npm-cache\_logs\2020-06-12T23_55_00_707Z-debug.log
error Command failed.
Exit code: 1
Command: C:\Users\lsggu\AppData\Local\Yarn\bin\create-strapi-app
Arguments: my-portfolio --quickstart
Directory: C:\Users\lsggu\Desktop\testStrapi-new
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
v12.18.0

- NPM version:
6.14.5

- Strapi version: 
3.0.0-beta.20.3

- Database:
- Operating system:
Windows
**Additional context**

**Comment by lauriejim** [comment]
Hello, I don't understand why you still have the beta...
Can you make sure an old version of Strapi is not installed globally on your computer.

**Comment by lsguillory** [comment]
thanks lauriejim. I have resolved the issue last evening after many trials and efforts - I had uninstalled Strapi but was still having a problem and after repeating the install I was finally able to move on. Thanks for the assist.
