### ISSUE TITLE
After upgrading from beta.14 to beta.20, we are getting a lot of errors "Error: ValidationError"

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi#6664]
**Describe the bug**
After upgrading from beta.14 to beta.20, we are getting a lot of errors "Error: ValidationError"

**Steps to reproduce the behavior**

Write operations which used to work are no longer working.
For example, String field no longer takes Number

**Expected behavior**
Mention this breaking changes in migration documentation;
Provide suggestion or best practice on how to fix this problem.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by lauriejim** [comment]
Hello @demobo-com ! 
`String field no longer takes Number` I think it's normal.
This is probably a bug fix because this should not be possible.
If you sent a number it's because you should have a Number field, not a Text field.

**Comment by demobo-com** [comment]
This type of breaking changes should have been documented in the migration guide.
