### ISSUE TITLE
"read the documentation" dead link in the plugin install blocker

### ISSUE THREAD

**Issue by evoxmusic** [strapi/strapi#6669]
**Describe the bug**
You have a "Read the documentation" dead link while installing the GraphQL plugin.

**Steps to reproduce the behavior**

1. Go to 'Strapi admin interface'
2. Click on 'Marketplace'
3. Install the GraphQL add on
4. While installing, click on "Read the documentation"

**Expected behavior**
Getting the correct documentation

**Screenshots**
404 -> https://strapi.io/documentation/v3.x/configurations/configurations.html#server

**Code snippets**
N/A

**System**

- Node.js version: One used by your official Docker image
- NPM version: One used by your official Docker image
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: Docker

**Additional context**
None

**Comment by lauriejim** [comment]
Hello @evoxmusic !
Thank you for reporting this behavior.
Something I would super appreciate is if you can try to submit a PR to fix this issue.
The topic you are pointing has to be fixed and it could be done by someone from the Community (you 🤗).
Here is the [contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to help you to getting started for contributions to Strapi.
You will have to check in the code source of the admin, the blocker and update the link.
Thank you.

**Comment by soupette** [comment]
I am closing this issue as it has already been fixed.
