### ISSUE TITLE
Socket.IO should be included to Strapi project

### ISSUE THREAD

**Issue by pravosleva** [strapi/strapi#667]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.9.3

**Operating system**: Ubuntu 16.04

**Do you want to request a *feature* or report a *bug*?** New functional as wost wanted feature.

**What is the current behavior?** Socket.IO could not be included to Strapi project quickly.

**If the current behavior is a bug, please provide the steps to reproduce the problem** Sorry, I have no idea.

**What is the expected behavior?** I want to have ability to include the Socket.IO to Strapi project. How can I do it?

**Comment by derrickmehaffy** [comment]
@pravosleva this I believe is on their to-do list, currently it is not possible

**Comment by Aurelsicoko** [comment]
You can easily add socket.io in a strapi project using the bootstrap file.

`./config/functions/bootstrap.js`
```js
'use strict';

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */

module.exports = cb => {
  strapi.io = require('socket.io')(strapi.server);
  
  cb();
};
```

**Comment by pravosleva** [comment]
@Aurelsicoko, I'am js-beginner.
Will you please, help me.
I have created project with included socket.io here - https://github.com/pravosleva/strapi-socket.io-test
I know, how can I use socket.io in React with express on backend (but not in Strapi).
So, my question is this -> where can i use `io.on( connection, function (socket) {} )`
Thanks.

**Comment by pravosleva** [comment]
@Aurelsicoko Can I use `strapi.io.on( connection, function (socket) {} )`?

**Comment by wonknu** [comment]
Hello @pravosleva , not sure if it will help you but i made some kind of tutorial this weekend to explan how i managed to setup socket io in my projet as i'm using it to. It's a basic example of setting up socket io an then use strapi public html file

https://github.com/wonknu/strapi_socket/blob/master/README.md

**Comment by Aurelsicoko** [comment]
@pravosleva Please follow the tutorial of @wonknu, it seems really great. Well done! I'm closing the issue, please reopen it if it's necessary 👍
