### ISSUE TITLE
Email confirmation redirection url is returning wrong url

### ISSUE THREAD

**Issue by anthify** [strapi/strapi#6670]
**Describe the bug**

`Redirection url` value used when confirming a new user via email is appended to the default url instead of replacing it. 

For example, lets say a strapi app is located on `api.myapp.com` and my redirection url is `https://myapp.com`, the resulting redirection will be `api.myapp.com/https://myapp.com`

**Steps to reproduce the behavior**

1. Go to your strapi dashboard
2. Roles & Permissions
3. Advanced Settings tab
4. Set Enable email confirmation to "ON" 
5. Set `Redirection url` to your app's frontend url
6. Register a user via your frontend app
7. Click on link provided in Email

**Expected behavior**

The redirect to go to the specified address

**System**

- Node.js version: `12.13.1`
- NPM version: `6.12.1`
- Strapi version: `3.0.1` 
- Database: `bookshelf`
- Operating system: MacOS

**Additional context**

I discovered this issue after migrating from beta, so could be related to that. I followed the migration guide, and everything else seems to work.

**Comment by anthify** [comment]
I've been trying to debug the issue. I can't find anything suspect in the code from reading it, but it appears that whatever goes wrong is likely here or just before here;

https://github.com/strapi/strapi/blob/ba6695a87c89c81cde9acd926d13334a2ed2f74f/packages/strapi-plugin-users-permissions/controllers/Auth.js#L592

**Comment by lauriejim** [comment]
Hello @anthify can you make sure you specify https at the beginning of your url.
I just tried and it looks working.

**Comment by anthify** [comment]
@lauriejim thank you. I've tried adding `https://` but the issued remained.

If it's working for you then I suspect it may have something to do with my migration from beta.

This is my `server.js`
```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  cron: {
    enabled: false
  },
  admin: {
    autoOpen: false
  }
});
```

**Comment by lauriejim** [comment]
Hello! I just checked with the lastest version of Strapi (3.1.3) and it has been fixed.
