### ISSUE TITLE
Granularity in aggregations

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#6671]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Granularity in aggregations
I was a bit disappointed to note that there was no granularity when grouping by timestamps and created_at doesn't work as sql is complaining that it is too ambiguous. The intent was to make Strapi generate a DATE_TRUNC("day", "created_at") sql statement when asked to group by a timestamp with day granularity.
The query could look like this in GraphQL
```graphql
callsConnection {
      created_at (granularity: "day") {
        key
        connection {
          aggregate {
            count
          }
        }
      }
    }
```
Which then produces values grouped by created_at as the key.
under the wood that could just add the following SQL statement at the beginning of the generated sql statement like this
SELECT DATE_TRUNC('day', created_at)  .... then continue with the rest of sql as usual. This makes grouping even more useful.
I am sure there are similar statements that work with other databases as well to make it complete.

**Comment by lauriejim** [comment]
Ping @alexandrebodin about this topic.

**Comment by derrickmehaffy** [comment]
aggregations don't exist in v4 anymore, closing
