### ISSUE TITLE
STRAPI + HEROKU RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536

### ISSUE THREAD

**Issue by GinFoB** [strapi/strapi#6673]
Hi everyone <br />

I follow this doc https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html
I try to deploy STRAPI app in Heroku, without success. <br />
I try a lot of solution like change server.js 
```
module.exports = ({ env }) => ({
  host: env('HOST', process.env.HOST || '0.0.0.0'),
  port: env.int('PORT', process.env.PORT || '3000'),
});


```
I get this errors : 
debug ⛔️ Server wasn't able to start properly.
error RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.

Any one can help me to resolve this issue.

**Comment by akhilmhdh** [comment]
The problem is your using env.int which expects integer and then passing '3000' as string. Change it to 3000 and it will work
