### ISSUE TITLE
Admin UI -> Plugins -> Email -> settings are not available

### ISSUE THREAD

**Issue by podeig** [strapi/strapi#6676]
I have installed email provider:
**npm i strapi-provider-email-sendgrid**

Under /config I created a file **plugins.js**

```
module.exports = ({ env }) => ({
    email: {
        provider: 'sendgrid',
        providerOptions: {
          apiKey: env("SENDGRID_API_KEY")
        },
        settings: {
            defaultFrom: 'den@test.com',
            defaultReplyTo: 'den@test.com'
        },
    }
});
```

In Admin UI (user admin) I open Plugins, but I cannot open email settings. Setting icon is not there. HELP!

**Comment by derrickmehaffy** [comment]
There is no more icon for email settings in the Admin, all configs have been moved to files: https://strapi.io/documentation/v3.x/plugins/email.html#configure-your-provider

https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html#email-plugin-settings

**Comment by podeig** [comment]
Thank you for so fast answer! It works for me now. :)
