### ISSUE TITLE
Core entity-service methods do not accept 'plugin' param, only takes 'model'

### ISSUE THREAD

**Issue by ssagga** [strapi/strapi#6678]
**Describe the bug**
Trying to utilize the core entitiy-service in a custom plugin controller to perform built in CRUD operations against the custom plugin's model(s), I have traced the stack to find that the methods (create, update, etc...) fail to capture a {plugin} parameter object along with the {model} parameter object. Therefore, when the core entity-service calls db methods such as `db.getModel()` or `db.getQuery()` , it fails to retrieve the custom plugin's model due to not passing a plugin name identifier as a parameter. This issue renders plugins unable to utilize the core entity-service.

**Steps to reproduce the behavior**

1. Fresh install of Strapi 3.0.1
2. Generate a new plugin
3. Configure routes, a model and controller.
4. In controller, create (example) a `postMessage` controller, which should enable us to create records against the model using the `strapi.entityService.create()` api:

```js
 postMessage: async (ctx) => {
    const query = strapi.query("message", "contact-form");
        const result = await strapi.entityService.create({data: ctx.request.body}, {model:'message' , plugin: 'contact-form'})
        ctx.send(result);        
    } catch (error) {
      strapi.log.error(error);
      ctx.badRequest(null, [
        {
          messages: [
            { id: error.message, message: error.message, field: error.field },
          ],
        },
      ]);
    }
  },
};
```
The above code fails, returning an error from db stating that it cannot assert kind() on this model.

**Code snippets**
This is an example of the current `create` method in entity-service.js after allowing it to accept the `plugin` parameter. Highlighted the amendments between *** *** 
Note: this modified code is not fully debugged, just enough to allow a successful data write (without file upload) to the plugin's model's collection

```js
async create({ data, files }, { model , ***plugin*** }) {
    const { kind } = db.getModel(model , ***plugin***);
    if (kind === 'singleType') {
      // check if there is already one entry and throw
      const count = await db.query(model).count();
      if (count >= 1) {
        throw new Error('Single type entry can only be created once');
      }
    }

    const validData = await entityValidator.validateEntity(db.getModel(model , ***plugin***), data);  
    let entry = await db.query(model , ***plugin***).create(validData);

    if (files) {
      await this.uploadFiles(entry, files, { model });
      entry = await this.findOne({ params: { id: entry.id } }, { model });
    }

    eventHub.emit('entry.create', {
      model: db.getModel(model , plugin).modelName,
      entry,
    });

    return entry;
  },
```

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.1
- Database: sqlite
- Operating system:

**Comment by alexandrebodin** [comment]
Hi, the core entity service was really created for this usecase but you can use the model uid to make this work:

```
strapi.entityService.create({ data: {}}, { model: 'plugins::plugin-name.model-name'})
```

**Comment by ssagga** [comment]
Hi Alex, thanks for your quick reply I will refactor using this approach for the time being. However, what would you recommend as a conventional approach to achieve CRUD from a custom plugin using the built in services if not via the entityService APIs?

**Comment by ssagga** [comment]
> 
> 
> Hi, the core entity service was really created for this usecase but you can use the model uid to make this work:
> 
> ```
> strapi.entityService.create({ data: {}}, { model: 'plugins::plugin-name.model-name'})
> ```

Not a bug, implementation requires passing the model uid instead of model name + plugin name. Thanks for your time!
