### ISSUE TITLE
Strapi and Generated swagger API

### ISSUE THREAD

**Issue by onepointconsulting** [strapi/strapi#6682]
When using Strapi to create a Swagger API using the Strapi documentation plugin, the generated method contains a parameter called '=' (equals sign). This parameter ('=') typically causes trouble when you want to generate code from the Swagger definition using SmartBear's tools.

Below you can see the generated parameter names on the Swagger API:

**Screenshots**

![image](https://user-images.githubusercontent.com/35300398/84656768-20527f80-af0b-11ea-9de9-43cbadb7e918.png)

Whilst most parameters have a syntax involving a leading underscore and no special characters like e.g: _sort, _limit, etc, this parameter contains a single special character. So the API naming seems to be inconsistent in this case.

**System**

- Node.js version: 13.11.0 (Currently using 64-bit executable)
- NPM version: 6.13.7
- Strapi version: 3.0.1
- Database: MySQL
- Operating system: Windows 10

**Expected behavior**

The parameter names for the generate API should be consistent and not have special characters, so that code generator tools can generate method names from the Swagger API.

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
Since we are working on other features, can you please try to have a look on the code base.
And submit a PR to fix this issue. I will really appreciate your contribution ont this thing.
Thank you.

**Comment by lauriejim** [comment]
Closing in the favor of this one - https://github.com/strapi/strapi/issues/7219
Thank you for having reported it.
