### ISSUE TITLE
Auth.form.email.invalid using sendgrid email for sign up email confirmation 3.0.1. version

### ISSUE THREAD

**Issue by mountiny** [strapi/strapi#6683]
**Describe the bug**
If you try to sign up user with email verification turned on and using sendgrid provider at new version 3.0.1 the user gets created but email is not sent throwing error Auth.form.email.invalid. Using 3.0.0@beta.18.5 version of Strapi works normal.

**Steps to reproduce the behavior**

1. npx create-strapi-project 
2. Add strapi-provider-email-sendgrid to your package json and npm install
3. Create Sendgrid account and get sendgrid api key and save it as environmental variable
4. Change appropriately congif/plugins.js as suggested by sendgrid to make it working since admin email plugin configuration part has been deprecated at this version
5. Turn the email verification on in admin panel as well as all the rules and permissions for Public role in user part so they can send emails and register
6. Try to create a user, see error - Bad Request 400 - Auth.form.email.invalid, In the database a user with given credentials has been created as unverified. No email has been sent.

**Expected behavior**
The user should saved in the database and confirmation email should send.

**System**

- Node.js version: 14.4.0
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: Macos Mojave

**Comment by lauriejim** [comment]
Hello @mountiny !
I just tried and it works well on my side.
Can you make sure you will configured your sendgrid provider.
This could come from here.

**Comment by mountiny** [comment]
Hello @lauriejim ! 
Thank you very much for your time and help! I just wanted to write here today. Earlier today, after some discussion with colleagues, we have figured out that the problem was with SendGrid account. 
The problem was that using heroku and their SendGrid add-on, you will get provisional account created and you should verify your email. As I used my email and I previously have not had account at SendGrid associated with that email, I still was not verified. SendGrid did not tell me anything and the tutorials on Heroku does not talk about it. 
When we used a SendGrid account of one of the colleagues which is fully verified with Sendgrid, it worked.

I am still not sure what exactly went wrong there. I have re-deployed the Strapi app to heroku numerous times trying to change SendGrid setup and it did not work til the moment we used verified account.

So yes, I guess the tutorials for Sendgrid should emphasize that the account should get verified in order to send emails:)

Thank you for your help once again, I am gonna close this issue
