### ISSUE TITLE
Issue on deploying the administration panel on another server than the API

### ISSUE THREAD

**Issue by GITMobileTeam** [strapi/strapi#6684]
**Describe the bug**
I am following the below documentation of strpai to deploy the administration panel on another server than the API:
https://strapi.io/documentation/v3.x/admin-panel/deploy.html#deploy-the-entire-project-on-the-same-server

But I can see that the admin panel is not coming up if I am providing the different backend URL. This is the server.js i am using:

```js
module.exports = ({ env }) => ({
  host: env('HOST', 'localhost'),
  port: process.env.PORT,
  cron: {
    enabled: false,
  },
  admin: {
    path: '/', // Note: The administration will be accessible from the root of the domain (ex: http//yourfrontend.com/)
    serveAdminPanel: false, // http://yourbackend.com will not serve any static admin files
    build: {
      backend: 'https://sl-auction-strapi-lite-wehxzjtmaq-ew.a.run.app',
    },
  },
});
```

**Steps to reproduce the behavior**

1. Just create the fresh quickstart project of Strapi and modify the server.js as mention above by providing different URL for backend API.
2. yarn build
3. yarn develop
4. hit http://localhost:1337/admin on browser and this issue is coming up:
{"statusCode":404,"error":"Not Found","message":"Not Found"}

**Expected behavior**
Admin panel and API should be deployed on separate server as mentioned on the documentation.

**System**

- Node.js version: 13.2.0
- NPM version: 0.34.0
- Strapi version: 3.0.1
- Database: Mongo DB
- Operating system: Mac OS Catalina

**Additional context**

**Comment by derrickmehaffy** [comment]
@petersg83 @alexandrebodin I already created a PR to resolve this documentation https://github.com/strapi/strapi/pull/6636

**Comment by lauriejim** [comment]
Since your PR has been merged @derrickmehaffy , should we close this issue?

**Comment by derrickmehaffy** [comment]
I believe we can yes, marking as closed

**Comment by GITMobileTeam** [comment]
@derrickmehaffy, Where can i find the solution or updated document for the same? I have checked on the strapi documentation but nothing is updated there.
https://strapi.io/documentation/v3.x/admin-panel/deploy.html#deploy-the-administration-panel-and-the-plugins-on-another-server-than-the-api

**Comment by derrickmehaffy** [comment]
You can read the updated file here: https://github.com/strapi/strapi/blob/baba84374b60208407379157eced0826d6174c7b/docs/v3.x/admin-panel/customization.md

The docs haven't been deployed yet
