### ISSUE TITLE
Facebook provider hitting 400 - bad request

### ISSUE THREAD

**Issue by Jamilur-rahman-470** [strapi/strapi#6687]
**Describe the bug**

**Steps to reproduce the behavior**

1. Go to 'added facebook provider according to doc'
2. Click on 'hit GET: /connect/facebook'
4. See error - 400 bad request with message - provider disabled

**Expected behavior**
User will be able to authenticate hitting this url

**Screenshots**

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.1
- Database: Mongodb
- Operating system: win64

**Additional context**

**Comment by lauriejim** [comment]
Another issue has been created about the error we have with providers on the 3.0.1.
Should be fixed really soon.
