### ISSUE TITLE
Errors with cors in production mode firts request 

### ISSUE THREAD

**Issue by RaimonxDev** [strapi/strapi#6689]
**Describe the bug**
Hello I have an application created in angular and my api with strapi.

my angular app works on domain.com and my strapi works on api.domain.com 

when I made the first request it generates this error: Access to XMLHttpRequest at **'https://api.domain.com/graphql' from origin 'https://domain.com' has been blocked by CORS policy: No 'Access-Control -Allow-Origin 'header is present on the requested resource.**

**but.....** 

when I make the second request or reload the browser works perfect
and it doesn't show me any cors error? What would be the problem here?

I work with Docker-compose .

Strapi version 3.0.2

also create the middleware.js file 

```js module.exports = {
  timeout: 100,
  load: {
    before: ["responseTime", "logger", "cors", "responses", "gzip"],
    order: [
      "Define the middlewares' load order by putting their name in this array is the right order"
    ],
    after: ["parser", "router"]
  },
  settings: {
   cors: {
      origin: '*',
    },
   public: {
      path: "./public",
      maxAge: 60000
    }
  }
};
`


**System**

- Node.js version: 12.13.0
- NPM version: 6.14
- Strapi version: 3.0.2
- Database: Postgress
- Operating system: Linux, DOCKER


**Everything else works perfectly, the error occurs on the first request, which for me is quite bad due to the user experience **

**Comment by lauriejim** [comment]
@derrickmehaffy or @alexandrebodin any idea?

**Comment by alexandrebodin** [comment]
wow that's some strange behavior. Do you have a sample project you can share so we can reproduce the error ?

**Comment by RaimonxDev** [comment]
Hello, I know it's very strange and I can't solve it.

I have my deploy on Digital Ocean

I share my Docker-compose so that you can generate my project. https://github.com/RaimonxDev/docker-compose-strapi-

es un docker-compose que pude crear y pensaba compartirlo con la comunidad que ayuda a levantar strapi con ssl y una frontend todo con docker. es funcional y solo estoy en la etapa de redaccionand my strapi project https://github.com/RaimonxDev/strapi-mastic

my angular application would be the container that I have the docker-compose. I would appreciate your help

@alexandrebodin

**Comment by RaimonxDev** [comment]
here you can see better the problem: https://slack-files.com/T0BLB2VFV-F015FEJLJSH-dcf8e6ba51

**Comment by RaimonxDev** [comment]
I show you the details that the console shows me. the first error when I make the first request shows me a 502 error


![image](https://user-images.githubusercontent.com/39868803/84841606-cfc54a00-b010-11ea-94ac-64998bd5c117.png)

then when I reload a 200
![image](https://user-images.githubusercontent.com/39868803/84841691-08652380-b011-11ea-8ab9-e7877d2b580e.png)

**Comment by phetw** [comment]
I'm having the same issue on freshly deployed strapi CMS on GCP.

```
Access to XMLHttpRequest at 'https://strapi.io/api/blog-posts...' from origin '....appspot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by alexandrebodin** [comment]
Hi, Can you share your nginx configuration ? You should be able to configure your cors on nginx to fix this

**Comment by derrickmehaffy** [comment]
> Hi, Can you share your nginx configuration ? You should be able to configure your cors on nginx to fix this

Yeah as Alex mentioned this is not normal behavior, but we do need to take a look at the Nginx config, if you don't want to share it publicly you can poke either me or alex on the Strapi slack and send it via a PM.

**Comment by RaimonxDev** [comment]
Hello @alexandrebodin  @derrickmehaffy , after much research, I managed to solve the problem. and it is exactly what they have commented the nginx was blocking the cors, the jwilder: proxy-nginx container in docker has its own configuration and it is somewhat delicate to change (of course it can be done but you have to know very well how the nginx works) ..

My solution was to use TRAEFIK. and now everything works perfect I did not have to make any major changes .. I hope I can create a tutorial on how to deploy in Digital Ocean with Traefik, and generate SSL certificates avoiding this problem

**Comment by alexandrebodin** [comment]
Great to hear it works now ! Going to close the issue ;)
