### ISSUE TITLE
Strapi.io unable to use the frontend development server

### ISSUE THREAD

**Issue by mafzalashraf4044** [strapi/strapi#669]
**Node.js version**: 9.4.0

**npm version**: 5.6.0

**Strapi version**: v3@alpha.10

**Operating system**: elementary os loki

I am using strapi v3@alpha.10. Every things is working fine, but I am unable to customize the frontend, the reason is frontend development server is not working fine. I want to customize the UI of users-permissions plugin, for that I used the command "npm link strapi-helper-plugin". But when I started the development server using the command "npm start" its unable to find the required assets. Same thing happens if I starts the development server inside admin folder

`> strapi-plugin-users-permissions@3.0.0-alpha.9.2 start /home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development node ./node_modules/strapi-helper-plugin/lib/server

Strapi plugin succesfully started in development mode. ✓

-----------------------------------
Access URL: http://localhost:3000
-----------------------------------
Press CTRL-C to stop

(node:5563) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack built 2160d47ebe80d8862f33 in 24315ms

ERROR in ./~/strapi-helper-plugin/lib/src/routes.js
Module not found: Error: Can't resolve 'routes.json' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/node_modules/strapi-helper-plugin/lib/src'
 @ ./~/strapi-helper-plugin/lib/src/routes.js 7:0-33
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/App/index.js
Module not found: Error: Can't resolve 'react-router-dom' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/App'
 @ ./admin/src/containers/App/index.js 51:0-49
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/index.js
Module not found: Error: Can't resolve 'react-router-dom' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/index.js 50:0-40
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/index.js 53:0-28
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/index.js 53:0-28
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/HomePage/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/HomePage'
 @ ./admin/src/containers/HomePage/index.js 51:0-28
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/index.js
Module not found: Error: Can't resolve 'utils/injectSaga' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/index.js 63:0-42
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/index.js
Module not found: Error: Can't resolve 'utils/injectSaga' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/index.js 63:0-42
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/HomePage/index.js
Module not found: Error: Can't resolve 'utils/injectSaga' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/HomePage'
 @ ./admin/src/containers/HomePage/index.js 63:0-42
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/index.js
Module not found: Error: Can't resolve 'utils/injectReducer' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/index.js 64:0-48
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/index.js
Module not found: Error: Can't resolve 'utils/injectReducer' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/index.js 64:0-48
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/HomePage/index.js
Module not found: Error: Can't resolve 'utils/injectReducer' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/HomePage'
 @ ./admin/src/containers/HomePage/index.js 62:0-48
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/index.js
Module not found: Error: Can't resolve 'components/BackHeader' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/index.js 56:0-47
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/index.js
Module not found: Error: Can't resolve 'components/Input' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/index.js 57:0-37
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/index.js
Module not found: Error: Can't resolve 'components/Input' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/index.js 60:0-37
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/index.js
Module not found: Error: Can't resolve 'components/PluginHeader' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/index.js 59:0-51
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/HomePage/index.js
Module not found: Error: Can't resolve 'components/PluginHeader' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/HomePage'
 @ ./admin/src/containers/HomePage/index.js 58:0-51
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/index.js
Module not found: Error: Can't resolve 'components/Button' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/index.js 59:0-39
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/NotFoundPage/index.js
Module not found: Error: Can't resolve 'components/NotFound' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/NotFoundPage'
 @ ./admin/src/containers/NotFoundPage/index.js 53:0-43
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/EditPage/saga.js
Module not found: Error: Can't resolve 'utils/request' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/EditPage'
 @ ./admin/src/containers/EditPage/saga.js 11:0-36
 @ ./admin/src/containers ^\.\/.*\.js$
 @ ./~/strapi-helper-plugin/lib/src/routes.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/HomePage/saga.js
Module not found: Error: Can't resolve 'utils/request' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/HomePage'
 @ ./admin/src/containers/HomePage/saga.js 10:0-36
 @ ./admin/src/containers ^\.\/.*\.js$
 @ ./~/strapi-helper-plugin/lib/src/routes.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/saga.js
Module not found: Error: Can't resolve 'utils/request' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/saga.js 7:0-36
 @ ./admin/src/containers ^\.\/.*\.js$
 @ ./~/strapi-helper-plugin/lib/src/routes.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/containers/AuthPage/saga.js
Module not found: Error: Can't resolve 'utils/auth' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/containers/AuthPage'
 @ ./admin/src/containers/AuthPage/saga.js 6:0-30
 @ ./admin/src/containers ^\.\/.*\.js$
 @ ./~/strapi-helper-plugin/lib/src/routes.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/Plugins/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/Plugins'
 @ ./admin/src/components/Plugins/index.js 50:0-28
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/InputSearch/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/InputSearch'
 @ ./admin/src/components/InputSearch/index.js 49:0-28
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/List/index.js
Module not found: Error: Can't resolve 'components/Button' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/List'
 @ ./admin/src/components/List/index.js 13:0-39
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/EditForm/index.js
Module not found: Error: Can't resolve 'components/Input' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/EditForm'
 @ ./admin/src/components/EditForm/index.js 50:0-37
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/HeaderNav/index.js
Module not found: Error: Can't resolve 'react-router-dom' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/HeaderNav'
 @ ./admin/src/components/HeaderNav/index.js 9:0-43
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/Policies/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/Policies'
 @ ./admin/src/components/Policies/index.js 47:0-28
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/Policies/index.js
Module not found: Error: Can't resolve 'components/Input' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/Policies'
 @ ./admin/src/components/Policies/index.js 53:0-37
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/PopUpForm/index.js
Module not found: Error: Can't resolve 'components/Input' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/PopUpForm'
 @ ./admin/src/components/PopUpForm/index.js 55:0-37
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/HeaderNav/index.js
Module not found: Error: Can't resolve 'utils/colors' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/HeaderNav'
 @ ./admin/src/components/HeaderNav/index.js 13:0-38
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/PopUpForm/index.js
Module not found: Error: Can't resolve 'reactstrap' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/PopUpForm'
 @ ./admin/src/components/PopUpForm/index.js 47:0-80
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/Plugin/index.js
Module not found: Error: Can't resolve 'reactstrap' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/Plugin'
 @ ./admin/src/components/Plugin/index.js 48:0-38
 @ ./admin/src/components/Plugins/index.js
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/ListRow/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/ListRow'
 @ ./admin/src/components/ListRow/index.js 47:0-28
 @ ./admin/src/components/List/index.js
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/ListRow/index.js
Module not found: Error: Can't resolve 'components/IcoContainer' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/ListRow'
 @ ./admin/src/components/ListRow/index.js 54:0-51
 @ ./admin/src/components/List/index.js
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/ListRow/index.js
Module not found: Error: Can't resolve 'components/PopUpWarning' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/ListRow'
 @ ./admin/src/components/ListRow/index.js 55:0-51
 @ ./admin/src/components/List/index.js
 @ ./admin/src/containers/HomePage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/BoundRoute/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/BoundRoute'
 @ ./admin/src/components/BoundRoute/index.js 13:0-28
 @ ./admin/src/components/Policies/index.js
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/Controller/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/Controller'
 @ ./admin/src/components/Controller/index.js 49:0-28
 @ ./admin/src/components/Plugin/index.js
 @ ./admin/src/components/Plugins/index.js
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main

ERROR in ./admin/src/components/InputCheckbox/index.js
Module not found: Error: Can't resolve 'classnames' in '/home/afzal/AFZAL/Cloud_Drive/Development/Always_RM/Always/plugins/users-permissions/admin/src/components/InputCheckbox'
 @ ./admin/src/components/InputCheckbox/index.js 48:0-28
 @ ./admin/src/components/Controller/index.js
 @ ./admin/src/components/Plugin/index.js
 @ ./admin/src/components/Plugins/index.js
 @ ./admin/src/containers/EditPage/index.js
 @ ./admin/src/containers/App/index.js
 @ ./~/strapi-helper-plugin/lib/src/app.js
 @ multi main
javascript node.js`

**Comment by soupette** [comment]
It looks like you didn't start your project in dev mode : `strapi new myProject --dev`
