### ISSUE TITLE
Different API Url and Admin URL doesn't work

### ISSUE THREAD

**Issue by sandrey80** [strapi/strapi#6695]
**Describe the bug**

```
module.exports = ({ env }) => ({
    host: env('HOST', '0.0.0.0'),
    port: env.int('PORT', 1337),
    url: '/content-api/', 
    admin: {
      url: '/content-admin'
    },
  });

```
**Steps to reproduce the behavior**

1. Add this server.js to environment/development
2. run yarn build && yarn develop
3. See log
```
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/content-api/content-admin

To access the server ⚡️, go to:
http://localhost:1337/content-api

[2020-06-16T09:16:09.593Z] debug GET /content-api/content-admin (12 ms) 200
[2020-06-16T09:16:09.714Z] debug GET runtime~main.e53ab4f0.js (9 ms) 200
[2020-06-16T09:16:09.715Z] debug GET main.3e358bee.chunk.js (5 ms) 200
[2020-06-16T09:16:10.441Z] debug GET /content-api/users-permissions/init (2 ms) 404
```
4. Open browser  http://localhost:1337/content-api
```
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```
5. Open browser http://localhost:1337/content-api/content-admin and i see spinner and 404 response status

**Expected behavior**
I expect to see API and Admin, nor 404

- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: sqlite
- Operating system: MacOS

** Linked issues **
https://github.com/strapi/strapi/issues/6684

**Comment by sandrey80** [comment]
Also i tried to use subdomain
```
module.exports = ({ env }) => ({
    host: env('HOST', '0.0.0.0'),
    port: env.int('PORT', 1337),
    /*url: '/content-api/', */
    admin: {
      url: 'http://admin.0.0.0.0.xip.io:1337/'
    },
  });
```
In this case i see only white screen

**Comment by derrickmehaffy** [comment]
Two things:

the normal `url` requires the use of a proxy software (Strapi doesn't prefix anything on it's own)
the `admin.url` requires the admin to be rebuilt for this to take effect

**Comment by lallenfrancisl** [comment]
This shoud be specified in the documentation
