### ISSUE TITLE
Race condition creating permissions for newly deployed model

### ISSUE THREAD

**Issue by iserko** [strapi/strapi#6697]
**Describe the bug**
What happens is if you use more than one web process running `strapi start` and you deploy a new model and it just happens that all web processes start at roughly the same time, you end up with duplicates. This is what happened to me:

The screenshot has different values for `enabled` because we were trying to change permissions after this happened and the UI didn't show the actual status.

A workaround for this issue on PostgreSQL is to just add a unique index:

```
CREATE UNIQUE INDEX "user-permissions_permission_uniq" ON "users-permissions_permission" (type, controller, action, policy, role)
```

My worry is that other data gets duplicated in the same way, but so far hasn't happened.

**Steps to reproduce the behavior**

1. Have a fresh database
2. Start 2 parallel `strapi start` processes
3. Run `SELECT * FROM "users-permissions_permission" WHERE role = 1 AND type = 'application' AND controller = '<your model>' ORDER BY action;`
4. See duplicate rows

**Expected behavior**
I wouldn't see duplicate rows

**Screenshots**
<img width="1062" alt="strapi_db_duplicates" src="https://user-images.githubusercontent.com/473071/84775246-dd5dde00-afd6-11ea-8246-18eff7c6d3b3.png">

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: Debian Buster running inside Docker

**Comment by lauriejim** [comment]
Hallo and thank you for reporting this.
Can you please submit a PR to fix this. I will appreciate your contribution on this issue.
Thank you. I think @alexandrebodin will be able to help you if needed.

**Comment by alexandrebodin** [comment]
@iserko thanks for reporting this. Indeed running multiple instance at the same time might create those racing conditions. We could try to implement it with transactions. this would need a big refactor sadly

**Comment by derrickmehaffy** [comment]
I believe this should be fixed in Strapi v4, gonna go ahead and mark it as closed but if others hit this issue do let us know.
