### ISSUE TITLE
Cannot find module 'slash' on install

### ISSUE THREAD

**Issue by christopher4lis** [strapi/strapi#6699]
**Describe the bug**
When running `yarn create strapi-app my-project --quickstart` or `npx create-strapi-app my-project --quickstart` I get the error `Cannot find module 'slash'`, then am unable to run the scaffolded app.

**Steps to reproduce the behavior**
Just run any of the above install scripts in any directory with the following versions listed below.

**Expected behavior**
For the project to be scaffolded without error messages and runnable with `yarn develop`

**Screenshots**
![image](https://user-images.githubusercontent.com/7675752/84846661-46684480-b01d-11ea-92eb-bc9915966edb.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.10.0
- NPM version: v6.10.3
- Strapi version: v.3.0.2
- Database: not applicable
- Operating system: macOS Catalina 10.15.5

**Comment by derrickmehaffy** [comment]
I've been seeing a ton of these lately for various packages but it always comes down to macOS.

@alexandrebodin @soupette @lauriejim can any of you reproduce this? I don't have a Mac to test on for personal use, and when I tried on my roommates Mac I could not reproduce this at all.

**Comment by soupette** [comment]
@derrickmehaffy I have never encounter this bug. We will try to investigate!

**Comment by alexandrebodin** [comment]
Never seen this and all the core team work on macOS. 

From the logs I'm seeing this is an error in npm itself. It was down some part of the day yesterday so it might be coming from this. I'm going to close as it is not related to strapi

**Comment by christopher4lis** [comment]
Hey all - looks like it was indeed an error with NPM that was only showing for me when I'd run the Strapi create script. I solved it by simply re-installing the most recent LTS version of Node.

Apologies for the inconvenience here.
