### ISSUE TITLE
Access public endpoint with invalid jwt ends up in 403 Unauthorized

### ISSUE THREAD

**Issue by sandrotaje** [strapi/strapi#6702]
**Describe the bug**
Access public endpoint with invalid jwt ends up in 403 Unauthorized
**Steps to reproduce the behavior**

1. Give public permission to an end point
2. Set Authorization header with something invalid (for example an old jwt)
3. Call the endpoint

**Expected behavior**
Since it is public should ignore the jwt

**Comment by derrickmehaffy** [comment]
@alexandrebodin correct me if I'm wrong but this is intended, generally to force the usage of "anonymous" endpoints, as it's quite likely (with policies) you could provide very different data for public vs authorized.

If you want to use public, don't send the JWT

**Comment by sandrotaje** [comment]
It's what I did to workaround, but the frontend shouldn't know if an endpoint is public or not.
For ease, I send always a JWT, if specified, but in my opinion, it is better to check Authorization after the check on roles. If I found that an endpoint is public I ignore the JWT.
I understand your point of view but this behavior can be risky.
It's happened to me that I was using a browser extension to modify headers and I forgot set Authorization header during the first installation of strapi and I end up in many errors.

**Comment by alexandrebodin** [comment]
Hello, this is not how the api works. If you send an auth token it will try to validate it first before reaching the route. the route can also be accessed by authenticated calls so we can't do what you suggest. You will need to call it without auth headers.

**Comment by derrickmehaffy** [comment]
> It's what I did to workaround, but the frontend shouldn't know if an endpoint is public or not.
> For ease, I send always a JWT, if specified, but in my opinion, it is better to check Authorization after the check on roles. If I found that an endpoint is public I ignore the JWT.
> I understand your point of view but this behavior can be risky.
> It's happened to me that I was using a browser extension to modify headers and I forgot set Authorization header during the first installation of strapi and I end up in many errors.

I'm not sure I understand how it would be risky, the whole point of this setup is to first validate the JWT, as that is the most important part. If the JWT is valid, literally nothing else should happen on the server and the request should end and be denied right then and there. If it's not it leaves Strapi vulnerable to some attach vectors to try and sniff out vulnerable code by an unauthorized user.

The first step in securing any application is to actually secure it, which is what is being done here. You certainly don't go walking around sticking your house key into every lock you see, you only put the key in the lock it generally belongs to :wink:
