### ISSUE TITLE
Can not add items to Enumeraion list other then in english ( russian for example).

### ISSUE THREAD

**Issue by fellz** [strapi/strapi#6705]
**Describe the bug**
If you try to add item to Enumeration field in russian ( for example идея), you get warning and unable to add item. Warning is "The value not match the regex."

**Steps to reproduce the behavior**

1. Go to Content-Type Builder.
2. Click on any collection.
3. Add field Enumeration.
4. Add item идея.

**Expected behavior**
Should add item

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.1
- Database: sqlite
- Operating system: windows 7

**Additional context**
You may use virtual keyboard to reproduce bug if it is bug. Thanks.

**Comment by Stun3R** [comment]
I think you should check this discussion: https://github.com/strapi/strapi/discussions/4780

**Comment by fellz** [comment]
> I think you should check this discussion: #4780

As i see the problem exist half a year already and i didn't see any fix there.

**Comment by lauriejim** [comment]
I'm closing this issue.
Everything is explained in this discussion.
I thinks we can continue the discussion there.
