### ISSUE TITLE
NOTICE: Email/Upload Provider settings

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#6710]
If you are having trouble configuring the email (or upload) provider settings:

Please remember to read the Contributing guide for opening issues: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

Also per that guide please ensure you check for [previously opened issues](https://github.com/strapi/strapi/issues?q=is%3Aissue+email+settings) relating to this.

As of `beta.20.x` as well as all stable releases `3.x.x` provider settings for both email and upload **have been moved to file based** meaning you will now configure them via the `./config/plugins.js` file and **not via the admin**.

If you are migrating from a previous beta to beta.20.x, this is detailed in [the following migration guide](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings).

If you are migrating from any beta version to the stable release, it is detailed in [the following migration guide](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html#email-plugin-settings).

These are also specifically mentioned in the stable release documentation:

- Email: https://strapi.io/documentation/v3.x/plugins/email.html#configure-your-provider
- Upload: https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider

**Comment by lauriejim** [comment]
I think we can now close this issue.
