### ISSUE TITLE
All Hosting Provide Guides at Deployment Doc lead to 404

### ISSUE THREAD

**Issue by williamli** [strapi/strapi#6711]
The Heroku guide linked at https://strapi.io/documentation/v3.x/getting-started/deployment.html#hosting-provider-guides to  https://strapi.io/documentation/v3.x/deployment/heroku is 404.

**Comment by williamli** [comment]
In fact all the host provider guides at https://strapi.io/documentation/v3.x/getting-started/deployment.html#optional-software-guides are 404-ing.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/6368
