### ISSUE TITLE
Newly uploaded images from with collection instance creation aren't automatically selected

### ISSUE THREAD

**Issue by josh-unwin** [strapi/strapi#6717]
**Describe the bug**
Perhaps by design, perhaps a feature request? When uploading a new image from within a Collection instance (not in the media library), the newly uploaded image is not automatically selected to be used with that instance of a collection. As the user is uploading directly within that collection it is expected that an uploaded image is automatically selected.

See [gif here](https://recordit.co/GJ4heXoAg5) for example (apologies for the long wait time for the upload in the gif... current internet speed is horrible!)

**Steps to reproduce the behavior**
1. Upload an image from within a collection instance creation.

**Expected behavior**
The newly uploaded image should automatically be selected.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
