### ISSUE TITLE
Bad link at Deployment to DigitalOcean doc

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#6718]
**Describe the bug**
Bad link on page https://github.com/strapi/strapi/blob/master/docs/3.0.0-beta.x/deployment/digitalocean.md

![image](https://user-images.githubusercontent.com/2712405/84921291-48b8b600-b092-11ea-9ab8-2b1cc02e2ebc.png)

**Comment by derrickmehaffy** [comment]
Beta documentation will no longer be updated as the beta is no longer supported, it is being left for a few months until we start seeing more users migrate to the stable release, then like the alpha it will be removed.

**Comment by adriatic** [comment]
There ought to be a reference to the beta documentation somewhere - as I did not reach the document at https://github.com/strapi/strapi/blob/master/docs/3.0.0-beta.x/deployment/digitalocean.md, but rather by clicking some link on the [stable release Strapi Documentation](https://strapi.io/documentation/v3.x/content-api/api-endpoints.html) page,
