### ISSUE TITLE
/config/plugins.js doesn't merge into local plugins

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#6725]
**Describe the bug**
Whether or not it makes sense to override local plugin `config/settings.js` with the general `/config/plugins.js`, it doesn't work. When I offloaded my plugin to be an installed package, it does work and merges in the values I've set in `/config/plugin.js`

**System**

- Node.js version: 12.16.0
- NPM version:
- Strapi version: 3.0.0
- Database: Mongo
- Operating system: Macos

**Additional context**
I'm developing a local plugin in the `/plugins` folder. I want it to have default settings, and I want to be able to set override values in the global `/config` folder

**Comment by rmonnier9** [comment]
Hi !
Shouldn't you use `plugins.js` rather than `plugin.js` ?

**Comment by laurenskling** [comment]
yes, it should be. That isn't the issue tho, I just wrote it wrong for this issue

**Comment by laurenskling** [comment]
Thanks @tudorilisoi  :)
