### ISSUE TITLE
Admin UI not connecting to correct API backend

### ISSUE THREAD

**Issue by zurfluh** [strapi/strapi#6726]
**Describe the bug**
When hosting the API and admin UI on different host/port, the admin UI does not respect the configuration but instead looks for the API under the same host/port as the admin UI.

**Steps to reproduce the behavior**

1. Configure the server as per the snippet below
2. `$ SERVE_ADMIN_PANEL=false yarn start` to start the API under localhost:1337
3. `$ yarn build` to build the admin UI
4. `$ http-server -p 9050 build` (or similar) to serve the admin UI under localhost:9050
5. The admin UI loader keeps spinning, as the XHR request to the backend returns HTTP 404

**Expected behavior**
Update the [relevant documentation](https://strapi.io/documentation/v3.x/admin-panel/deploy.html#deploy-the-administration-panel-on-another-server-aws-s3-azure-etc-than-the-api)

or: admin UI sends requests to the host/port as per configuration of the API.

**Screenshots**
![image](https://user-images.githubusercontent.com/2371518/85016805-bfc17d80-b16a-11ea-9b65-126b21737d9e.png)

**Code snippets**
*server.js*
```js
module.exports = ({ env }) => ({
  host: 'localhost',
  port: 1337,
  cron: {
    enabled: false,
  },  
  admin: {
    url: '/',
    serveAdminPanel: env.bool('SERVE_ADMIN_PANEL', true),
    build: {
      backend: 'http://localhost:1337/',
    },
  },
});
```

**System**

- Node.js version: v12.14.0 and v10.16.3
- NPM version: v6.13.4 and v6.9.0
- Strapi version: v3.0.2
- Database: Postgres
- Operating system: CentOS linux

**Additional context**
To install `http-server`: run `$ yarn add -g http-server`

**Comment by petersg83** [comment]
Hi,
Thanks for the issue! The config has been recently updated to be simpler, and this page of the doc has been forgotten in the process. I'll update it soon.
In the meantime, can you try with this configuration please:
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'http://localhost:1337/',
  admin: {
    url: '/',
    serveAdminPanel: env.bool('SERVE_ADMIN_PANEL', true),
  }
});
```

**Comment by zurfluh** [comment]
👌 Thank you already @petersg83 , your snippet solves the issue. Thanks in advance for updating all relevant docs.

**Comment by fxjordan** [comment]
Thanks @petersg83 , you saved my day 👍  Docs should really be updated

**Comment by petersg83** [comment]
PR #6778 updated the doc
