### ISSUE TITLE
Aggregation ignores policies

### ISSUE THREAD

**Issue by ikonduktor** [strapi/strapi#6727]
Aggregation just ignores policies in graphql.schema;

**DESCRIPTION**
I'm using GraphQL and try get count of the records

```
query feedbacksConnection( 
    $where: JSON
) {
    feedbacksConnection(where: $where) {    
        aggregate {
            count        
        } 
    }
}
```

in my `schema.graphql` i have
```
...
    Query: {
      ...,
      feedbacksConnection: {
        description: 'feedbacks aggregation',
        policies: [
            'global::isAssigneeRead'
        ]   
      }
    }
...
```

`isAssigneeRead` ignored

**Expected behavior**
`isAssigneeRead` run before aggregation.

**System**

- Node.js version: v14.3.0
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: mongo
- Operating system: Ubuntu 18.04.4 LTS

**Comment by derrickmehaffy** [comment]
Hello, can you please give an example from your `isAssigneeRead` policy so we can try to reproduce the issue?

**Comment by derrickmehaffy** [comment]
As no updated information has been provided from the user, closing.
