### ISSUE TITLE
A boolean field set not editable (off) are editable in the user view in strapi.

### ISSUE THREAD

**Issue by thierryc** [strapi/strapi#6736]
**Describe the bug**

A boolean field set not editable (off) are editable in the user view in strapi.

**Steps to reproduce the behavior**

- Create a boolean fields
- Set it editable off 

**Expected behavior**
This boolean toogle should be not editable but it is. 

**System**

- Node.js version: Node LTS 
- Strapi version:  3.0.3
- Database: PG
- Operating system: MacOS

**Comment by lauriejim** [comment]
Hello! Thank  you for reporting this issue.
I ping @soupette about that.

**Comment by soupette** [comment]
Hello @thierryc this will be fixed with #6999

**Comment by thierryc** [comment]
Thank you

**Comment by MattieBelt** [comment]
@soupette wrong PR mentioned, I think.

**Comment by soupette** [comment]
This issue has been fixed with the stable release. I am closing it
