### ISSUE TITLE
Can't use a email provider with a different name

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#6742]
https://github.com/strapi/strapi/blob/9ed11a66829dbdafabb49cb8813dd4d891a247de/packages/strapi-plugin-email/config/functions/bootstrap.js#L9

This line makes it impossible to install my namespaced package: https://www.npmjs.com/package/@laurenskling/strapi-provider-email-postmark

**Comment by derrickmehaffy** [comment]
Moving to a discussion
