### ISSUE TITLE
Field Id with camel case nomenclature

### ISSUE THREAD

**Issue by rsinelle** [strapi/strapi#675]
**Node.js version**:
v8.9.4
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
Centos 

**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
For Rest Apis, it will better to export field name as camel case. 
To do so, a solution is to generate a camel case field id when we create a new field for a content type.

**Comment by lauriejim** [comment]
Thi issue is related to this one https://github.com/strapi/strapi/issues/661
