### ISSUE TITLE
React Markdown no render code styles

### ISSUE THREAD

**Issue by xAgustin93** [strapi/strapi#6751]
**Describe the bug**
https://classic.yarnpkg.com/es-ES/package/react-markdown

I'm rendering the block code with the react-markdown component as you indicate but the JSON, JavaScript styles don't add them

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
