### ISSUE TITLE
Standardize language system for translations

### ISSUE THREAD

**Issue by filipesmedeiros** [strapi/strapi#6756]
These don't apply, I think
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

We were discussing here #6022 and thought that some languages need, for example, formal/informal distinctions, or choosing what gender(s) to use, etc.

Formalizing this in the [CONTRIBUTING.md](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) file would be good. I suppose that French (the original language?) has this kind of stuff, so maybe it's just a matter of it being written down.

**Comment by lauriejim** [comment]
Hello @filipesmedeiros !
We opened a position for a Technical Writer few months ago and found someone for this position.`
When this person will arrive, we will have a huge work on the documentation guidelines about this topics and
also have a check of that in the admin interface.
This is not a topic for right now but more for the end of the year.
Thank you for highlighting this.
