### ISSUE TITLE
Add support for Simplified Chinese

### ISSUE THREAD

**Issue by maxoyed** [strapi/strapi#6758]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
We can add simplified chinese support for documentation, admin panel, so that more developers from China Mainland would like to use it. I can do this job.

**Comment by lauriejim** [comment]
Hello! Thank for for this insight.
For the documentation, we are not planning to have it in many languages for now.
For the Admin Panel, feel free to submit a PR to add / update admin translations.
Here are translations for the admin panel, you will find the same structure for all plugins.
https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src/translations
I'm closing this, doesn't need to stay open.
Thank you.

**Comment by biaji** [comment]
>     * [x]  **I have created my request on the Product Board before I submitted this issue**
> 
>     * [x]  **I have looked at all the other requests on the Product Board before I submitted this issue**
> 
> 
> **Please describe your feature request:**
> We can add simplified chinese support for documentation, admin panel, so that more developers from China Mainland would like to use it. I can do this job.

Actually, It's already there. check zh-hans in translations.
