### ISSUE TITLE
bookshelf generate bad query

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#6759]
**Describe the bug**
Additional data entered into sql query (where) by bookshelf

**Code snippets**
code in controller :

```javascript
  getArticles: async (ctx) => {
    const res = await strapi
      .query('article')
      .model.query((qb) => {
        // qb.where('id', '=', 95);
        // qb.where('user', '=', 311003);
        qb.debug(true);
      })
      .fetchAll({
        withRelated: [
          {
            user: (qb) => {
              qb.where('id', '=', 311003);
              qb.debug(true);
            },
          },
          'thumbnail',
        ],
      });
    ctx.send(res);
  },
};
```
query that generate:

```javascript
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'cdf22830-b464-11ea-b2d1-c13887ed7e82',
  sql: 'select `articles`.* from `articles`'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    311003, 311003,
    452418, 372749,
    311006, 311010,
    311004
  ],
  __knexQueryUid: 'ce033f31-b464-11ea-b2d1-c13887ed7e82',
  sql: 'select distinct `users-permissions_user`.* from `users-permissions_user` where `id` = ? and `users-permissions_user`.`id` in (?, ?, ?, ?, ?, ?)'
}
```
bindings in second query is wrong and are unnecessary and increases computational cost

**System**

- Node.js version: v12
- NPM version:v6
- Strapi version:3.0.1
- Database:mysql
- Operating system:centos7

**Comment by alexandrebodin** [comment]
Hello @marefati110 This is bookshelf default behavior and not an issue with Strapi as you are using bookshelf directly. If you want this to change you will need to open an issue in Bookshelf's repo :) 

Closing as it is not a Strapi issue

**Comment by MANTENN** [comment]
@marefati110, can you reference the issue your created on bookshelf so we can follow through and see what's the status?

Thanks,
Nazar
