### ISSUE TITLE
Audit fields

### ISSUE THREAD

**Issue by rsinelle** [strapi/strapi#677]
**Node.js version**:
v8.9.4
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
Centos 

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
For audit purpose, I can be useful to add automatically somes audit fields like Creation date, Update date.
These fields can be exported with Rest Apis

**Comment by derrickmehaffy** [comment]
This is mainly related to the MongoDB part of strapi, as mongo does not contain anything related to the MySQL `current_timestamp` documented here: https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html

I 2nd this is something that should be added by default especially for anytime changes are made to an entry as well as new entries.

**Comment by jbuck94** [comment]
Looks like it existed in the [V1 Docs](https://strapi.io/documentation/1.x.x/models.html#autocreatedat) - not sure why they would have gone away with this.  Mongoose native timestamps (createdAt, updatedAt) would be very helpful!

**Comment by lauriejim** [comment]
Hi ! Yes it's a useful feature. It's implemented in SQL database with `strapi-bookshelf` but not actually for mongoose.

**Comment by lauriejim** [comment]
It's in `alpha.11` add 
```
   "options": {
     "timestamps": true
   },
```
in your model files
