### ISSUE TITLE
v3.0.4: create-strapi-app has dependency issues

### ISSUE THREAD

**Issue by haschu** [strapi/strapi#6775]
**Describe the bug**
Setting up a new project with `yarn create strapi-app` fails due to dependency conflicts.
We tested it on several machines and it fails reliable:

Creating a project from the database CLI arguments.
Creating files.
Error while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning strapi-admin > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > react-virtualized > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning strapi-admin > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning strapi-plugin-content-manager > draft-js > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-plugin-users-permissions > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
error https://registry.yarnpkg.com/@formatjs/intl-datetimeformat/-/intl-datetimeformat-1.2.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, link '/Users/xxx/Library/Caches/Yarn/v6/npm-@formatjs-intl-datetimeformat-1.2.1-da53daa6480994259371229925700c797f3cac4b-integrity/node_modules/@formatjs/intl-datetimeformat/temp-zic/US/America/Adak' -> '/Users/xxx/Library/Caches/Yarn/v6/npm-@formatjs-intl-datetimeformat-1.2.1-da53daa6480994259371229925700c797f3cac4b-integrity/node_modules/@formatjs/intl-datetimeformat/temp-zic/US/Aleutian'"

**Steps to reproduce the behavior**

1. `yarn create strapi-app`

**Expected behavior**

It should work and setup a new strapi project.

**System**

- Node.js version: v12.14.0
- NPM version: v6.13.4
- Strapi version: v3.0.4
- Database: any
- Yarn version: v1.22.4
- Operating system: macOS 10.15.5

**Comment by haschu** [comment]
This seems to be related to:
https://github.com/formatjs/formatjs/issues/1744

**Comment by lauriejim** [comment]
Thank you reporting this, we are on it to see what we can do.

**Comment by lauriejim** [comment]
Note: is you use `npm` it will work.
You can also use `yarn create strapi-app my-project --use-npm`

**Comment by alessandrocaprarelli** [comment]
As a temporary workaround I did:
- installed using yarn: `yarn create strapi-app my-project `
- the project is successfully created but dependencies are not correctly installed
- added resolution to package.json (credits: https://github.com/formatjs/formatjs/issues/1744#issuecomment-647996524)
- installed packages using `yarn install`


```
"resolutions": {
    "@formatjs/intl-datetimeformat": "1.1.0"
  }
```

**Comment by haschu** [comment]
> Note: is you use `npm` it will work.
> You can also use `yarn create strapi-app my-project --use-npm`

Yep, that works as a temporary solution! Thanks.

**Comment by haschu** [comment]
Wow, that was super fast! 1 hour and a new release is out! 👍 👍

**Comment by thierryc** [comment]
Yarn or NPM  + ^ is always tricky... Congrats.

**Comment by devskope** [comment]
> Yarn or NPM + ^ is always tricky... Congrats.

Pinning dependencies should be the defacto approach
