### ISSUE TITLE
Migration guide link is wrong

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#6776]
**Describe the bug**
Both `v3.x` and `3.0.0-beta.x` migration guide are two same guide but have different link. I followed first one but it turns out it's for 3.0 configuration, which causes database connection error.

1. https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings
> This means that you now have to configure your provider directly in the files. You can read the documentation [here](https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider) to update.

2. https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings
> This means that you now have to configure your provider directly in the files. You can read the documentation [here](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider) to update.

**Expected behavior**
In v3.x guide,
https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider
should be https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider

**Comment by lauriejim** [comment]
Fixed :) thank you for reporting this.

**Comment by lauriejim** [comment]
Will be release when the PR is merged.
