### ISSUE TITLE
backendUrl not using https even when api url is specified in https

### ISSUE THREAD

**Issue by lallenfrancisl** [strapi/strapi#6777]
**Describe the bug**
The issue described in #49 The issue still persists when using different urls for admin and the api(in my case it's the same domain).

**Steps to reproduce the behavior**

1. change the api url to a subdomain
2. change the admin url
3. admin does not because of mixed content error

**Expected behavior**
Admin UI is loaded up

**Code snippets**
server.js file
`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('API_URL', ''),
  admin: {
    url: env('ADMIN_URL', '/admin')
  }
});
`
.env
`NODE_ENV=production
API_URL=https://api.keplerobotics.in
ADMIN_URL=https://keplerobotics.in/admin
`

**System**
- Node.js version: v12.18.1
- NPM version: 6.14.5
- Strapi version: 3.0.4
- Database: MySQL
- Operating system: Ubuntu 20.04

PS: Right now I manually edited backendUrl in the main.*******.js file and it is working.

**Comment by lauriejim** [comment]
@derrickmehaffy This one is definitely for you 🤓

**Comment by derrickmehaffy** [comment]
@lallenfrancisl what proxy software are you using? (Nginx, HAProxy, Caddy, Apache, ect?)

**Comment by lallenfrancisl** [comment]
Oh snap, very sorry for wasting your time. It turns out that there were two main.****.js files. Maybe from a previous build. So earlier I was maybe looking at the file with the non-https link. There were one since I had build with non-https link earlier and when I looked at the other it was indeed https. 

But although for some reason by default the build configuration is production.

**Comment by lallenfrancisl** [comment]
Also I wanted to ask something although not directly linked to this. Do I have to rebuild everytime I change from development env to production env if I am using different databases. In my case I am using MySql for production and sqlite for development. 

I am asking this because I do not have access to users I created in development build when using production build and running `NODE_ENV=development npm run develop`. 

That is,  I first build with development NODE_ENV=development and then create a user by running `NODE_ENV=development npm run develop` . Then if I build using production configuration and then run using `NODE_ENV=development npm run develop` I will not have the user created when I used the development build.

**Comment by derrickmehaffy** [comment]
If you are changing environments yes you should, though it doesn't matter for the database, there are certain different settings that get built into the admin when you specify an environment.

A key point to keep in mind that only the admin is "built" the backend is not, when building with an environment, you are telling the admin where it can **publicly* access the backend APIs (since react is client side rendered)
