### ISSUE TITLE
Model lifecycle not called

### ISSUE THREAD

**Issue by GinFoB** [strapi/strapi#6780]
Hi everyone <br />

Strapi version: 3.0.4

I can't call any lifecycle model method beforeSave or beforeCreate ....

I found this issue https://github.com/strapi/strapi/issues/1153 but not resolve mu issue.

My model look like 

```
module.exports = {
  // Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: async (model) => {
    console.log('[beforeSave]', 'model', model)
    // Do something here with the model
  },

  // Before creating a value.
  // Fired before an `insert` query.
  beforeCreate: async (model) => {
    console.log('[beforeCreate]', 'model', model)
    // Do something here with the model
  },

  // Before updating a value.
  // Fired before an `update` query.
  beforeUpdate: async (model) => {
    console.log('[beforeUpdate]', 'model', model)
    // Do something here with the model
  }
};
```

In console log no function called.

Anyone help me ?

**Comment by alexandrebodin** [comment]
Hello, as per https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks, lifecycle function must be declared in the `lifecycles` property

**Comment by gevhambarzumyan93** [comment]
my model looks like this, afterCreate didn't call

my call looks like this strapi.models.(modelName).create(data);

module.exports = {
  lifecycles: {
    afterCreate: async (model, result) => {
      //karevor chi
    },
  }
};

**Comment by gevhambarzumyan93** [comment]
never mind I just need to read docks 

```
module.exports = {
  async createCustomEntry() {
    const ORMModel = strapi.query(modelName).model;

    const newCustomEntry = await ORMModel.create(data);

    // trigger manually
    ORMModel.lifecycles.afterCreate(newCustomEntry.toJSON());
  },
};
```
