### ISSUE TITLE
When postgres datestyle is set to SQL, DMY all created_at and updated_at dates are returning null

### ISSUE THREAD

**Issue by MSLacerda** [strapi/strapi#6783]
**Describe the bug**

Using postgres datestyle config set to SQL, DMY all dates used in strapi are returned as null in api and admin-ui.

**Steps to reproduce the behavior**

1. Set postgres datestyle to SQL, DMY
2. Create new project on strapi
3. Create a content type and add a entry
4. Make a api request or in collection table in admin visualize the created_at column 

**Expected behavior**

The date fields must return values, actually the attributes created_at and updated_at are returning only null values.

**Screenshots**
![image](https://user-images.githubusercontent.com/20617517/85423161-c24a1b80-b54c-11ea-804d-aeaf52bb7c7a.png)

![image](https://user-images.githubusercontent.com/20617517/85423627-4ef4d980-b54d-11ea-8b70-ad2e0228d810.png)

In database:

![image](https://user-images.githubusercontent.com/20617517/85423702-6338d680-b54d-11ea-9856-5f44a759bc2c.png)

**System**

- Node.js version: v12.18.0
- NPM version: 6.14.4
- Strapi version: 3.0.4
- Database: Postgres
- Operating system: Linux Mint and strapi/base docker image

**Comment by lauriejim** [comment]
Hello!
Why do you want to change the data format that manages Strapi?
I'm closing this issue, Strapi will not be able to manage another format, so please keep the default one.
Thank you and have a good day.

**Comment by derrickmehaffy** [comment]
You will want to review the following guide: https://strapi.io/documentation/v3.x/guides/custom-data-response.html

And you can use something like moment.js to dynamically convert them, (which Strapi uses to convert in the backend on save/fetch anyway)
