### ISSUE TITLE
Strapi@alpha10 error: The hook `_config` failed to load!

### ISSUE THREAD

**Issue by tienthinhturbo** [strapi/strapi#679]
**Node.js version**: 8.9.1

**npm version**: 5.5.1

**Strapi version**: alpha 10

**Operating system**: Windows

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** error: The hook `_config` failed to load!

**If the current behavior is a bug, please provide the steps to reproduce the problem**
- Install Strapi
- mongod
- Cd to fresh install
- strapi start

**What is the expected behavior?** Strapi start

![capture](https://user-images.githubusercontent.com/14198542/36483958-f9ed693c-1717-11e8-8f6c-4cebc5f78f18.JPG)

**Comment by lauriejim** [comment]
@tienthinhturbo Can you update you nodejs version to node 9 please and tell me if it works.

**Comment by francismoreno** [comment]
I had the same error when trying to run `strapi start`:

`error: The hook `_config` failed to load!`

fixed it by running `npm install`
