### ISSUE TITLE
Lifecycles afterFind cannot update query results

### ISSUE THREAD

**Issue by charkcl** [strapi/strapi#6790]
**Describe the bug**
Not able to update query results inside Model with "afterFind" lifecycle hooks

**Steps to reproduce the behavior**

1. Go to 'api/xxx/models/xxx.js'
2. use "afterFind" lifecycle hook to update query results
3. expect updated results to be shown

**Expected behavior**
Provide examples for "afterXXX" [lifecycle hooks](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks)

or I am using the lifecycle hook wrongly?

**Screenshots**
Not able to update query results inside Model with "afterFind" lifecycle hooks. I confirm that the afterFind lifecycle has been run with console log but the updated results (in my case decrypted results) are not returned.
<img width="564" alt="strapi_afterFind" src="https://user-images.githubusercontent.com/14211437/85499003-5d0d2d80-b613-11ea-9c2c-b3bb9633fc7f.png">

**Code snippets**
- use any encrypt and decrypt library to encrypt a field inside any model
- e.g. `models/xxxUser.js`
```
module.exports = {
  /**
   * Triggered before user creation.
   */
  lifecycles: {
    beforeCreate: async model => {
      const encryptedString = encrypt(model.email);
      model.email = encryptedString;
    },
    afterFind: async (results, params, populate) => {
      const decryptedRes = results.map(res => {
        return { ...res, email: decrypt(res.email) }
      })
      results = decryptedRes;
    }
  },
};
```

**System**

- Node.js version: v12.16.0
- NPM version: v6.4.1
- Strapi version: v3.0.1
- Database: Postgres
- Operating system: macOS Catalina

**Additional context**
- `npm run develop` to start localhost

**Comment by alexandrebodin** [comment]
Hello, As described in the documentation you need to mutate the result not reassign it. If you want to change the result you need to do:

```js
module.exports = {
  /**
   * Triggered before user creation.
   */
  lifecycles: {
    beforeCreate: async model => {
      const encryptedString = encrypt(model.email);
      model.email = encryptedString;
    },
    afterFind: async (results, params, populate) => {
      results.forEach(res => {
        res.email = decrypt(res.email)
      })
    }
  },
};
```

**Comment by pympyy** [comment]
>     afterFind: async (results, params, populate) => {
>       results.forEach(res => {
>         res.email = decrypt(res.email)
>       })
>     }

not working =(

**Comment by lucasff** [comment]
I want to persist (update the DB) a mutation done on afterFind. Then I encounter a loop where afterFind is being called over and over. How to solve this?

**Comment by khocef** [comment]
> I want to persist (update the DB) a mutation done on afterFind. Then I encounter a loop where afterFind is being called over and over. How to solve this?

same here 

`
module.exports = {
  async afterFindOne(event) {
    const { result, params } = event;
    await strapi.entityService.update("api::car.car", result.id, {
      data: {
        views: result.views + 1,
      },
    });
  },
};

`

**Comment by Sathyanarayanan-Dhanuskodi** [comment]
> > I want to persist (update the DB) a mutation done on afterFind. Then I encounter a loop where afterFind is being called over and over. How to solve this?
> 
> same here, the code below cause an infinite loop
> 
> ```js
> module.exports = {
>   async afterFindOne(event) {
>     const { result, params } = event;
>     await strapi.entityService.update("api::car.car", result.id, {
>       data: {
>         views: result.views + 1,
>       },
>     });
>   },
> };
> ```

is it resolved? It is running in endless loop. I cannot get the populated data of the relational field in afterFindOne
