### ISSUE TITLE
Performance of Media Library is very slow for Large size Videos from S3 Bucket

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#6791]
**Describe the bug**
1. Performance of Media Library is very slow for preview/streaming Large size Videos from S3 Bucket.
2. Video preview is taking very long time to show up
3. Streaming large size MP4 Video's ( >70mb ) doesn't work at all

**Steps to reproduce the behavior**

1. Go to  Media Library
2. First upload few large size (around 100mb) MP4 Videos 
3. After uploading, open Media Library
4. Try to load/open all those Videos and see

**Observed behavior**
1. Performance of Media Library is very slow for Large size Videos from S3 Bucket
2. It's taking very long time to show the Video Preview for large size MP4 Video's ( >70mb ). 
3. Each time when you try to open these videos, It's first trying to download each time to show the preview, causing it to take long time to show the preview
4. Video streaming doesn't work at all for large size MP4 Video's ( >70mb ). 

**Expected behavior**
1. Performance of Media Library should be faster for Large size Videos from S3 Bucket
2. Video preview should be faster
3. Video streaming should be faster

**System**

Node version: `v10.15.3`
NPM version: `6.4.1`
Strapi version: `3.0.0-beta.20.3`
Database: Mongo & S3 File storage for File uploads
Operating system: `MAC`

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this.
I ping @soupette to see when he will have time to inspect that and try to improve the way we are managing that.

**Comment by raphaelsoul** [comment]
if it is totally networking issue, try this
```
// config/plugins.js
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      region: 'us-east-1',
      useAccelerateEndpoint: true,
      params: {
        Bucket: 'some-buccket',
      },
    },
  }
});

```

**Comment by vinod77** [comment]
Looks it's totally networking issue as you mentioned @raphaelsoul 
It's working fine for us now. We were able to upload 400mb Video in around 2 minutes.
Thank you!

**Comment by lopermo** [comment]
Hi! I'm still dealing with that issue. I activated accelerateEndpoint, but it still won't show any video's streaming and it's virtually impossible to upload any video larger than 50MB (on top of everything there's no percentage indicator, so it's hard to tell specially for non-technical users when they try to upload videos.
Any solution regarding this topic?

**Comment by gu-stav** [comment]
I believe this issue is fixed in strapi v4. If not, please ping me and I'll re-open.
