### ISSUE TITLE
Unable to get raw request body

### ISSUE THREAD

**Issue by jonpalmisc** [strapi/strapi#6794]
**Describe the bug**
I am trying to obtain the raw request body to I can verify it using Stripe's library. This question was previously asked #4720, but the solution the user posted no longer seems to work.

**Steps to reproduce the behavior**

1. Create a `config/env/**/request.json` with the following content:
```json
{
  "parser": {
    "enabled": true,
    "multipart": true,
    "includeUnparsed": true
  }
}
```
2. Import the `unparsed` symbol helper from `koa-body`
```js
const unparsed = require('koa-body/unparsed.js'); 
```

3. Attempt to access the unparsed body.
```js
async index(ctx) {
  const unparsedBody = ctx.request.body[unparsed];
  console.log(unparsedBody) // undefined
}
```

**Expected behavior**
I would have received the unparsed body.

**Screenshots**
N/A

**Code snippets**
config/env/development/request.json
```json
{
  "parser": {
    "enabled": true,
    "multipart": true,
    "includeUnparsed": true
  }
}
```

api/test/controllers/test.js
```js
"use strict";

const unparsed = require("koa-body/unparsed.js");

module.exports = {
  async test(ctx) {
    console.log("\n==== Environment =======================");
    console.log(`NODE_ENV=${process.env.NODE_ENV}`);

    console.log("\n==== Requests Config ===================");
    console.log(strapi.config.request);

    console.log("\n==== Unparsed Symbol ===================");
    console.log(unparsed);

    console.log("\n==== Unparsed Body =====================");
    console.log(ctx.request.body[unparsed]);

    console.log("");

    return {};
  },
};
```

Output:
```
==== Environment =======================
NODE_ENV=development

==== Requests Config ===================
{ parser: { enabled: true, multipart: true, includeUnparsed: true } }

==== Unparsed Symbol ===================
Symbol(unparsedBody)

==== Unparsed Body =====================
undefined
```

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4 (Yarn 1.22.4)
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: macOS 10.15.5

**Comment by jonpalmisc** [comment]
Added example code snippets.

**Comment by derrickmehaffy** [comment]
Not that it will help in this case but can you test using a fresh project on the latest release as your version `Strapi version: 3.0.1` is not. (I don't expect this will help but always good to double check)

**Comment by jonpalmisc** [comment]
Tried on Strapi 3.0.5. Issue persists.

**Comment by jonpalmisc** [comment]
If you have any ideas for temporary workarounds too, they are welcome, as this is causing a holdup for a project I'm working on. I'd also be happy to submit a PR if you might know where the bug is in the code.

**Comment by jonpalmisc** [comment]
It is worth noting that this issue means that it is impossible to verify the signature of webhooks sent to a Strapi instance by Stripe or any other service.

**Comment by arteagabriel** [comment]
I'm having the same issue although I followed a different approach per the documentation: https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations

I have a config/middleware.js with
```
module.exports = {
  settings: {
    parser: {
      enabled: true,
      includeUnparsed: true
    }
  }
};
```

But still can't seem to get the raw request body. I think I am running into the same issue as you @jonpalmisc with connecting to Stripe after a webhook trigger. Unfortunately I'm not familiar enough with Koa to know which direction to look to fix this.

**Comment by jonpalmisc** [comment]
@arteagabriel Thank you for sharing - going to try out your method just in case. If I find anything that works I’ll definitely share. This is obviously a huge issue for being able to launch the platform I’m working on.

**Comment by arteagabriel** [comment]
@jonpalmisc Not sure what changed between yesterday and today but it seems to be working just fine now.

Here's my stripe webhook code for reference:

controller
```
const unparsed = require('koa-body/unparsed.js'); 

module.exports = {
  created: async ctx => {
    const unparsedBody = ctx.request.body[unparsed];
    const secret = process.env.STRIPE_CREATED_SECRET;
    const signature = ctx.request.headers['stripe-signature'];
    let event;
  
    try {
      event = await strapi.services.stripe.webhooks.constructEvent(unparsedBody, signature, secret);
    } catch (error) {
      ctx.throw(400);
    }
```

config/middleware.js
```
module.exports = {
  settings: {
    cors: {
      enabled: true
    },
    parser: {
      enabled: true,
      multipart: true,
      includeUnparsed: true
    }
  }
};
```

config/hook.js
```
module.exports = {
  settings: {
    stripe: {
      enabled: true,
      secretKey: process.env.STRIPE_SECRET_KEY
    },
  },
};
```

hooks/stripe/index.js
```
const stripe = require('stripe');

module.exports = strapi => {
  return {
    async initialize() {
      const { secretKey } = strapi.config.get('hook.settings.stripe');

      strapi.services.stripe = stripe(secretKey);
    },
  };
};
```

**Comment by jonpalmisc** [comment]
The issue was that I was not using `config/middleware.js`, rather, I was using `config/env/development/request.json`, the proposed solution in #4720. I am now able to retrieve the unparsed body as expected. You really saved me here, thank you so much! You have no idea how relieved I am to have this working now. @arteagabriel

**Comment by alexandrebodin** [comment]
Hello, Happy to hear this is solved. Closing this issue

**Comment by olso** [comment]
Maybe this will help someone in the future https://github.com/stripe/stripe-node/issues/396#issuecomment-653691205

**Comment by okwme** [comment]
this answer doesn't seem to work anymore : \

I'm using `"strapi": "3.4.1"`

 I've got `/config/middleware.js` that looks like this:
```js
module.exports = {
  settings: {
    parser: {
      enabled: true,
      includeUnparsed: true
    }
  }
};
```
my controller looks like:
```js
const stripe = require('stripe')(process.env.STRIPE_API_KEY);
const unparsed = require("koa-body/unparsed.js");

module.exports = {
  stripeWebhook: async ctx => {
    const unparsedBody = ctx.request.body[unparsed]
    const sig = ctx.request.headers['stripe-signature'];
    let event;

    try {
      event = stripe.webhooks.constructEvent(unparsedBody, sig, process.env.STRIPE_WEBHOOK_SECRET);
    } catch (err) {
      console.log({err})
      ctx.response.status = 400
      ctx.response.send(`Webhook Error: ${err.message}`);
    }
    return {received: true}
  }
}
```
I've checked the key and secret are the same and I'm getting the following error:
```
Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
```

I found the following three ([1](https://github.com/poland20/p20-backend/blob/21dd3f995646ca537f4c60b722fbfd2ec5fc9916/api/order/controllers/Order.js), [2](https://github.com/jacklansing/usfsc/blob/4c2de2f0d899f1dd973fd7e0fa224890a0657fae/pages/api/webhooks/membership-payment.ts), [3](https://github.com/NRD89/next-rouse/blob/75a36644e8342a31b0bdb1f229df42558c8a2ffa/pages/api/handle-stripe-webhooks.js)) example repos and tried all of their techniques, none of them worked.

**Comment by okwme** [comment]
nm i figured it out, had `middleware.js` in the wrong `config` directory 🤦‍♂️
