### ISSUE TITLE
'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by keyus4** [strapi/strapi#680]
I tried to rebuild my admin area using npm run build in my ./admin folder.

this is the error i get

 strapi-admin@3.0.0-alpha.10.1 build C:\Projects\strapi\ngRide\admin
> APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress

'APP_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.10.1 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.10.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2018-02-21T19_18_01_228Z-debug.log

**Comment by derrickmehaffy** [comment]
likely related to project created without --dev

**Comment by keyus4** [comment]
@derrickmehaffy. I actually created another project with --dev and i was able to do npm install in the ./admin folder but when i tried to do npm start, i also got this error

C:\Projects\strapi\ngRide\admin>npm start

> strapi-admin@3.0.0-alpha.10.1 start C:\Projects\strapi\ngRide\admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server

module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Projects\strapi\ngRide\admin\node_modules\strapi-helper-plugin\node_modules\.bin\cross-env'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.10.1 start: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.10.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2018-02-22T13_55_05_627Z-debug.log

**Comment by keyus4** [comment]
I tried installing the set up development environment but i got this error

C:\strapi-master>npm run setup

> @3.0.0-alpha.10.2 setup C:\strapi-master
> npm run clean:all && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.10.2 clean:all C:\strapi-master
> npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules


> @3.0.0-alpha.10.2 removesymlinkdependencies C:\strapi-master
> node ./scripts/removeSymlinkDependencies.js

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.10.2 clean:all: `npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.10.2 clean:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2018-02-27T16_55_00_467Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.10.2 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.10.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2018-02-27T16_55_00_683Z-debug.log

**Comment by lauriejim** [comment]
Okay can you replace `rm -rf` with `rmdir /s /q` and test again.
We will have to move it in a script to be more `os` agnostic.

**Comment by keyus4** [comment]
am not sure i understand what u meant by replace rm -rf with rmdir /s /q. 
Please can you be more specific about how to do that. 

From the documentation
Note: If the installation failed, please remove the global packages related to Strapi. The command npm ls strapi will help you to find where your packages are installed globally.

I also did C:\WINDOWS\System32\strapi>npm ls strapi
@3.0.0-alpha.10.2 C:\WINDOWS\System32\strapi
`-- (empty)

There's no info on how to remove the global package

Thanks

**Comment by derrickmehaffy** [comment]
@keyus4 that is a linux command, Being as your on windows (powershell) the command your looking for is `rd -r "path to folder or directory"`

This would also apply in the CMD window however I believe it only applies to folders: `rd /s /q "path to folder"`

**Comment by keyus4** [comment]
@derrickmehaffy Thanks for your response. I guess it isn't an issue I can fix on my own so I just have to wait until the solution is made available?

I thought the development environment can be set up on windows s well. I really wish I could get it to work right now

**Comment by derrickmehaffy** [comment]
@keyus4 unless your well adept at working with scripts like this, it is probably better to wait.

Although in my opinion setting up a virtual machine either locally or remotely to develop on linux is a very easily solution.

**Comment by keyus4** [comment]
@derrickmehaffy I used git-bash cmd to run the npm run setup and it worked but the setup failed when it got to linking strapi-admin

this is the error

 OLUWASEUN@OLUWASEUN-PC MINGW32 /c/windows/system32/strapi (master)
$ npm run setup

> @3.0.0-alpha.10.2 setup C:\windows\system32\strapi
> npm run clean:all && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.10.2 clean:all C:\windows\system32\strapi
> npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules


> @3.0.0-alpha.10.2 removesymlinkdependencies C:\windows\system32\strapi
> node ./scripts/removeSymlinkDependencies.js

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> pre-commit@1.1.3 install C:\windows\system32\strapi\node_modules\pre-commit
> node install.js


> spawn-sync@1.0.13 postinstall C:\windows\system32\strapi\node_modules\spawn-sync
> node postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
added 1070 packages in 371.777s

�  The setup process can take few minutes.

�  Linking strapi-utils...
:white_check_mark:  Success

�  Linking strapi-generate...
:white_check_mark:  Success

�  Linking strapi-generate-api...
:white_check_mark:  Success

�  Linking strapi-helper-plugin...
:white_check_mark:  Success

�  Linking strapi-admin
�  Building...
'APP_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.10.2 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.10.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OLUWASEUN\AppData\Roaming\npm-cache\_logs\2018-03-02T11_51_57_297Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.10.2 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.10.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OLUWASEUN\AppData\Roaming\npm-cache\_logs\2018-03-02T11_51_57_552Z-debug.log.

Any clue on what might be wrong?

**Comment by derrickmehaffy** [comment]
@keyus4 looks like in this error the script is trying to call the variable `$APP_PATH` but being as this is being done on windows that variable might not have been set (not sure even git-bash works like that on windows)

**Comment by keyus4** [comment]
@derrickmehaffy yea I guess that's where the issue lies. I have been trying to locate the $APP_PATH in the code and find a way to fix the issue but I haven't been able to get it right. The npm run setup command only runs using git-bash on windows but it doesn't solve the $APP_PATH issue either. I don't know why this issue isn't marked as a priority yet. I can't make any progress on my project since I encountered this issue. I really need to get the development setup running on my computer. This is just sad

**Comment by LinhTran1** [comment]
On windows, you should run commands under clean:all separately and then remove "npm run clean:all && " from value of setup in package.json

**Comment by keyus4** [comment]
@LinhTran1 nothing changed. I've been able to use git bash to run the setup but when it gets to a point, it breaks with an error 

OLUWASEUN@OLUWASEUN-PC MINGW32 /c/windows/system32/strapi (master)
$ npm run setup

@3.0.0-alpha.10.2 setup C:\windows\system32\strapi
npm run clean:all && npm install && node ./scripts/setup.js && npm run clean

@3.0.0-alpha.10.2 clean:all C:\windows\system32\strapi
npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages//package-lock.json && rm -rf packages//node_modules

@3.0.0-alpha.10.2 removesymlinkdependencies C:\windows\system32\strapi
node ./scripts/removeSymlinkDependencies.js

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

pre-commit@1.1.3 install C:\windows\system32\strapi\node_modules\pre-commit
node install.js

spawn-sync@1.0.13 postinstall C:\windows\system32\strapi\node_modules\spawn-sync
node postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
added 1070 packages in 371.777s

� The setup process can take few minutes.

� Linking strapi-utils...
✅ Success

� Linking strapi-generate...
✅ Success

� Linking strapi-generate-api...
✅ Success

� Linking strapi-helper-plugin...
✅ Success

� Linking strapi-admin
� Building...
'APP_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.10.2 build: APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.10.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\OLUWASEUN\AppData\Roaming\npm-cache_logs\2018-03-02T11_51_57_297Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.10.2 setup: npm run clean:all && npm install && node ./scripts/setup.js && npm run clean
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.10.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\OLUWASEUN\AppData\Roaming\npm-cache_logs\2018-03-02T11_51_57_552Z-debug.log.

**Comment by Aurelsicoko** [comment]
The solution could be to use Shell.js instead of running Linux commands in the `package.json` scripts. We would be happy to merge a PR to make it work. We know this issue is blocking for Windows users who want to edit the administration panel. We are too busy right now to make a proposal...

**Comment by keyus4** [comment]
@Aurelsicoko please can you paste an example code of how to use Shell.js in the package.json scripts?

**Comment by Aurelsicoko** [comment]
@keyus4 You need to create a separate JS file like we already did here:

https://github.com/strapi/strapi/blob/master/packages/strapi-admin/package.json#L23
https://github.com/strapi/strapi/blob/master/packages/strapi-admin/scripts/setup.js

**Comment by keyus4** [comment]
@Aurelsicoko I just forked the strapi repository afresh and the changes made in https://github.com/strapi/strapi/blob/master/packages/strapi-admin/package.json#L23
https://github.com/strapi/strapi/blob/master/packages/strapi-admin/scripts/setup.js did not make any difference. Still the same APP_PATH not recognized error 

OLUWASEUN@OLUWASEUN-PC MINGW32 /c/strapi
$ npm run setup

> @3.0.0-alpha.11.1 setup C:\strapi
> npm run clean:all && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.11.1 clean:all C:\strapi
> npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules


> @3.0.0-alpha.11.1 removesymlinkdependencies C:\strapi
> node ./scripts/removeSymlinkDependencies.js

npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 71.709s

�  The setup process can take few minutes.

�  Linking strapi-utils...
✅  Success

�  Linking strapi-generate...
✅  Success

�  Linking strapi-generate-api...
✅  Success

�  Linking strapi-helper-plugin...
✅  Success

�  Linking strapi-admin
�  Building...
'APP_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.11.1 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.11.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OLUWASEUN\AppData\Roaming\npm-cache\_logs\2018-03-21T09_45_37_864Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.11.1 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.11.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OLUWASEUN\AppData\Roaming\npm-cache\_logs\2018-03-21T09_45_38_183Z-debug.log

**Comment by jikotw74** [comment]
same issue here with APP_PATH error

**Comment by keyus4** [comment]
@jikotw74 please can you give more info on how you resolve the APP_PATH issue before you encountered another error issue.
you said you resolved it with 

cross-env APP_PATH=$APP_PATH npm run build:dll ......

how exactly?

**Comment by jikotw74** [comment]
use cross-env
`npm install cross-env -g`

replace all `node ./node_modules/SOME/PATH cross-env` with `cross-env` in stripts of package.json

**Comment by keyus4** [comment]
@jikotw74 I have also tried using cross-env. After installing npm install cross-env -g and effecting the changes inside package.json, I also got this error

XXXX@XXXX-PC MINGW32 /c/strapi
$ npm run setup

> @3.0.0-alpha.11.1 setup C:\strapi
> npm run clean:all && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.11.1 clean:all C:\strapi
> npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules


> @3.0.0-alpha.11.1 removesymlinkdependencies C:\strapi
> node ./scripts/removeSymlinkDependencies.js

npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 32.956s

�  The setup process can take few minutes.

�  Linking strapi-utils...
✅  Success

�  Linking strapi-generate...
✅  Success

�  Linking strapi-generate-api...
✅  Success

�  Linking strapi-helper-plugin...
✅  Success

�  Linking strapi-admin
�  Building...
C:\strapi\packages\strapi-helper-plugin\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.11.1 build:dll: `cross-env APP_PATH=$APP_PATH cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.dll.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.11.1 build:dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2018-04-01T02_55_09_498Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.11.1 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.11.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2018-04-01T02_55_09_633Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.11.1 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.11.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2018-04-01T02_55_09_839Z-debug.log

**Comment by derrickmehaffy** [comment]
Just as a small suggestion if you plan on developing on Windows and are using Windows 10 I would highly recommend using the WSL for ubuntu or whatever distro.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

Its not a clean and clear cut way to work on strapi on windows but should cut out most of these issues until they setup proper windows support.

**Comment by jikotw74** [comment]
I did try Ubuntu on Windows.
But there are still problems. 
@derrickmehaffy Thank you.

**Comment by RyanSusana** [comment]
I am having this issue as well

**Comment by jikotw74** [comment]
@XcrossD It works. thank you!

**Comment by lauriejim** [comment]
I close this issue. Resolved with https://github.com/strapi/strapi/issues/680#issuecomment-381018295

We will work on windows improvement in fews weeks.

**Comment by hamedhossani** [comment]
> @derrickmehaffy I used git-bash cmd to run the npm run setup and it worked but the setup failed when it got to linking strapi-admin
> 
> this is the error
> 
> OLUWASEUN@OLUWASEUN-PC MINGW32 /c/windows/system32/strapi (master)
> $ npm run setup
> 
> > @3.0.0-alpha.10.2 setup C:\windows\system32\strapi
> > npm run clean:all && npm install && node ./scripts/setup.js && npm run clean
> 
> > @3.0.0-alpha.10.2 clean:all C:\windows\system32\strapi
> > npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/_/package-lock.json && rm -rf packages/_/node_modules
> 
> > @3.0.0-alpha.10.2 removesymlinkdependencies C:\windows\system32\strapi
> > node ./scripts/removeSymlinkDependencies.js
> 
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> 
> > pre-commit@1.1.3 install C:\windows\system32\strapi\node_modules\pre-commit
> > node install.js
> 
> > spawn-sync@1.0.13 postinstall C:\windows\system32\strapi\node_modules\spawn-sync
> > node postinstall
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> added 1070 packages in 371.777s
> 
> � The setup process can take few minutes.
> 
> � Linking strapi-utils...
> ✅ Success
> 
> � Linking strapi-generate...
> ✅ Success
> 
> � Linking strapi-generate-api...
> ✅ Success
> 
> � Linking strapi-helper-plugin...
> ✅ Success
> 
> � Linking strapi-admin
> � Building...
> 'APP_PATH' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! strapi-admin@3.0.0-alpha.10.2 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the strapi-admin@3.0.0-alpha.10.2 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\OLUWASEUN\AppData\Roaming\npm-cache_logs\2018-03-02T11_51_57_297Z-debug.log
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @3.0.0-alpha.10.2 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @3.0.0-alpha.10.2 setup script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\OLUWASEUN\AppData\Roaming\npm-cache_logs\2018-03-02T11_51_57_552Z-debug.log.
> 
> Any clue on what might be wrong?

Hello  
I have this error too  
``` npm run setup error 'APP_PATH' is not recognized as an internal or external command```  
i use windows 10 x64 and ```npm``` version ```6.4.1``` and ```MongoDB``` shell version ```v4.0.10```.  
I have Error on ```admin/scripts/setup.js```.  
my problem **Solved** by added ```set``` key to commands(two line)  
```
" && APP_PATH="${appPath}" npm run build`
``` 
to
```
" && set APP_PATH="${appPath}" npm run build`
```

**Comment by Dhrumit14** [comment]
> am not sure i understand what u meant by replace rm -rf with rmdir /s /q.
> Please can you be more specific about how to do that.
> 
> From the documentation
> Note: If the installation failed, please remove the global packages related to Strapi. The command npm ls strapi will help you to find where your packages are installed globally.
> 
> I also did C:\WINDOWS\System32\strapi>npm ls strapi
> @3.0.0-alpha.10.2 C:\WINDOWS\System32\strapi
> `-- (empty)
> 
> There's no info on how to remove the global package
> 
> Thanks

To be more clear on this : You have to replace 'rm -rf' in package.json with 'rimraf'. 

And If you have not installed rimraf package. I would recommend first install this package: npm install rimraf -g
