### ISSUE TITLE
required checkbox missing for relation field in collection

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#6800]
**Describe the bug**
i have a collection called `ticket` in it is a field `relation` to `user`. i want this to be a required field but the required checkbox is not provided in `advanced settings`

**Steps to reproduce the behavior**
see screenshot

**Expected behavior**
i would expect that all fields would have the `required` checkbox

**Screenshots**
![relation-missing-required](https://user-images.githubusercontent.com/1257358/85621182-86f33e00-b66d-11ea-9533-83319cf1f4ff.png)

**Code snippets**
none

**System**
Node.js version: v10.16.3
NPM version: 6.9.0
Strapi version: Strapi v3.0.5
Database: mongo v4.0.12
Operating system: ubuntu 18.04

**Additional context**
Thank you!

**Comment by derrickmehaffy** [comment]
closing as duplicate: https://github.com/strapi/strapi/issues/557

**Comment by hkovacs** [comment]
> closing as duplicate: #557

cool!
