### ISSUE TITLE
Strapi doesn't warn about expired authentication when saving collection type item

### ISSUE THREAD

**Issue by sam-cross** [strapi/strapi#6815]
**Describe the bug**
When submitting a new item in a Collection Type, if the user waits too long to save it, Strapi will simply do nothing and instead remain on the same page.

**Steps to reproduce the behavior**

1. Fire up a Strapi instance and create a new Collection Type
2. Make a new item in that type and add some info to it (if you want)
3. Wait for auth to expire (30m?)
4. Attempt to save the item

**Expected behavior**
Strapi should either:

* **(Preferred)** Save the current state of all input fields and ask the user to log in again
* Tell the user to copy information to a local document and direct the user to log back in
* **(Least preferable)** Simply warn the user that the document remains UNSAVED, and that they need to log back in

**System**

- Node.js version: Latest 12.x (according to Heroku docs)
- NPM version: Unknown
- Strapi version: v3.0.1
- Database: Postgresql
- Operating system: Linux (on Heroku)

**Additional Context**

This issue also occurred when running locally in development mode.

**Comment by derrickmehaffy** [comment]
This isn't directly a problem with Strapi but is with Heroku. When Heroku doesn't see any activity, it will kill the dyno. When you go to save again Heroku pulls the code from Github, reinstalls, rebuilds, and restarts in which your initial request to save fails.

My suggestion would be don't use Heroku.
