### ISSUE TITLE
Cancel button to delete media does not work

### ISSUE THREAD

**Issue by juliensl** [strapi/strapi#6818]
Hi everybody !

**Describe the bug**
When you are in the Media Library and click on the bin to delete the media, you have a modal which says : "Are you sure..."
If you click on *Delete* the media is deleted, but if you click on *Cancel* the media is deleted too :laughing: 

**Steps to reproduce the behavior**

1. Go to the media library panel
2. Click on a media
3. Click on the bin
4. Click on Cancel on the warning

**Expected behavior**
It should not delete the media 

**System**

- Node.js version: 12.18.1
- NPM version: 6.14.5
- Strapi version: 3.0.2
- Database: MongoDB Atlas
- Operating system: Ubuntu 18.04

Thank you

**Comment by lauriejim** [comment]
Hello! I just tried with the latest version of Strapi 3.0.5 and it works fine.
Here is what I did - https://www.loom.com/share/db01c9e366544a1ca83018ad5230abe7
Let me know if I miss something.

**Comment by NegativeIQ** [comment]
Cannot reproduce on Strapi 3.0.5 and MariaDB
Cancel works as intended and does not delete anything.

**Comment by juliensl** [comment]
Ok, no problem today...
I tried with Google Chrome and Firefox and it works... it's weird :thinking:  

Sorry for this useless issue.

Have a good day :)
