### ISSUE TITLE
PUTting results in a 500 error even if successful

### ISSUE THREAD

**Issue by joeinnes** [strapi/strapi#682]
**Node.js version**:
9.4.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
macOS

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When PUTting, the update is made successfully, but the response from the endpoint is 500, and there's an error in the logs.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. I created an API named 'like'
2. I added a few records
3. I PUT to the like/:id endpoint

**What is the expected behavior?**
Update should be made successfully, and a 200/204 response should be delivered.

Console output:
```
ERROR (CastError/23810 on SteelyGlint.local): Cast to ObjectId failed for value "<Buffer 5a 8d ed c9 ad da 68 58 f9 8a c3 b3>" at path "_id" for model "Like"
  CastError: Cast to ObjectId failed for value "<Buffer 5a 8d ed c9 ad da 68 58 f9 8a c3 b3>" at path "_id" for model "Like"
```
NB: the :id I am PUTting to is 5a8dedc9adda6858f98ac3b3

I have removed and reinstalled node_modules. Any ideas?

**Comment by lauriejim** [comment]
Can you give me your model and the body of your PUT request to try to reproduce your issue.

**Comment by joeinnes** [comment]
Yup, model is:
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "like",
    "description": "Store likes from a user"
  },
  "attributes": {
    "user": {
      "model": "user",
      "via": "likes",
      "plugin": "users-permissions"
    },
    "likes": {
      "collection": "film",
      "via": "liked by"
    },
    "dislikes": {
      "collection": "film",
      "via": "disliked by"
    },
    "seen": {
      "collection": "film",
      "via": "seen by"
    }
  }
}
```

The 'PUT' was an array of film IDs, but I don't actually still have the record of it. If you can't reproduce, then let's close.

**Comment by lauriejim** [comment]
Don't really understand:
> but I don't actually still have the record of it 

What is the body of your request ? 

Something like that ?
```
{
  "seen": [
    "123",
    "456"
  ] 
}
```

**Comment by lauriejim** [comment]
Hi @joeinnes can you give me more details please.

**Comment by joeinnes** [comment]
Hi,

Afraid not. I gave up.

Best regards,

Joe

http://joeinn.es
