### ISSUE TITLE
Email not sending with mailgun [resolved]

### ISSUE THREAD

**Issue by david-soyez** [strapi/strapi#6821]
If you installed the plugin `strapi-provider-email-mailgun`  and your mails are not sending, well that's because the domain is missing in the documentation following the mailgun-js documentation you can find here: https://www.npmjs.com/package/mailgun-js

This is the correct configuration:
```
module.exports = ({ env }) => ({
  // ...
  email: {
    provider: 'mailgun',
    providerOptions: {
      apiKey: env('MAILGUN_API_KEY'),
      domain: env('MAILGUN_YOUR_DOMAIN')
    },
    settings: {
      defaultFrom: 'myemail@protonmail.com',
      defaultReplyTo: 'myemail@protonmail.com',
    },
  },
  // ...
});
```

**Comment by lauriejim** [comment]
[resolved] - is there an issue?

**Comment by derrickmehaffy** [comment]
@lauriejim user edited their response so I assume so. Marking as closed.

**Comment by david-soyez** [comment]
It was a documentation issue.

**Comment by SalahAdDin** [comment]
> It was a documentation issue.

Which kind of issue?
