### ISSUE TITLE
Fields dont pass default value in database config causing application to fail on startup, or fail to add content

### ISSUE THREAD

**Issue by sam899** [strapi/strapi#6824]
**Describe the bug**
When adding a new field, if you set a default value, the default is enforced on the front-end, but not set in the database config.

This leads to a couple of issues (i've used a boolean as an example here for ease of explaining).

1. If you add a boolean to an existing model (with data), checking the required flag, and setting a default value (let's say, TRUE), when you then try to build strapi, it will fail to build, because the database builder will add the column as NOT NULL, but not provide the DEFAULT TRUE. Therefore, database spits out error saying you cant have null values (ie all the existing data in the database wont get the default value, just null)

2. If you add a boolean to a new or existing model with a default value (let's say TRUE) and required set to true, then save it (ie db gets created). If you then remove this boolean, the database does not get cleaned up (ie column still exists). When you now try to add some more content, the database will throw an error because you are not giving the (now deleted) boolean column a value.

I have bundled these 2 sytems into one issue, because i believe they will be (mostly) fixed by the same change.

**Steps to reproduce the behavior**

**Issue 1**
1. Create a new collection type - (eg Restaurant)
2. Add a field to that collection type, (e.g Name), then Save
3. Create a new Restaurant, (eg name: "Restaurant 1"), then Save
4. Now go back and add a new boolean field - (e.g IsEnabled). Make it Required, with default True. Then Save
5. Strapi will not start, because "Restaurant 1" has null value for field IsEnabled.

**Issue 2**
1. Create a new collection type - (eg Restaurant) with a name text field.
2. Add a boolean field (e.g IsEnabled). Make it Required, with default True. Then Save
3. Create a new Restaurant, (eg name: "Restaurant 1", isEnabled: True), then Save
4. Now go back and remove the boolean field isEnabled. Then Save
5. Now try to add another restaurant "Restaurant 2", Press save
5. Strapi will fail to save the content, because the database field isEnabled still exists, with no default value set. The UI cannot set a value as its removed

**Expected behavior**
When building a model, I should be able to add a remove fields without strapi failing to start, or failing to add content because of a stale / incorrect database.

If i set a default value for a boolean (or any type for that matter), I expect that default to be applied to all previous data in the database, and all future data.

If I remove a field, I should not be negatively affected by its persistence in the database. The data should either be removed, or constraints relaced (ie remove the not null constraint)

**System**

- Node.js version: v12.18.1
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: postgres
- Operating system: Tested on MacOS, Docker, Ubuntu

**Additional context**
I believe this will be mostly fixed by simply passing the default the user sets to the database field settings.
However, for issue 2, if a default is not set, but not null is, either removing the field, or removing the NOT NULL constraint on the field will be needed upon deleting a field from strapi.

**Comment by derrickmehaffy** [comment]
> If you add a boolean to a new or existing model with a default value (let's say TRUE) and required set to true, then save it (ie db gets created). If you then remove this boolean, the database does not get cleaned up (ie column still exists). When you now try to add some more content, the database will throw an error because you are not giving the (now deleted) boolean column a value.

#1114

**Comment by lauriejim** [comment]
Hello! Thank you for this clean report.
You are mentioning 2 different issues that are already in the GitHub issues and also in our roadmap.
So I will close this issue.
After that, it was a good formatted issue and thank you for that.
