### ISSUE TITLE
Relation dropdown is disabled in case of polymorphic relation

### ISSUE THREAD

**Issue by Limonische** [strapi/strapi#6831]
**Describe the bug**
I am aware that as of now polymorphic relations using model: * do not work, so i opted to use collection: *. But after i created one-to-many polymorphic relation, the dropdown in admin ui is disabled.

**Steps to reproduce the behavior**

1. Create two models (in my case post and menu-item)
2. Establish a one-to-many polymorphic relation as described in docs
3. Open admin panel
4. Create a couple of entries for each of those models
5. Go to either of those content types
6. See that relation dropdown is disabled

**Expected behavior**
Dropdown should be enabled and you should be able to select and save polymorphic relationships.

**Screenshots**
![image](https://user-images.githubusercontent.com/47951826/85923875-50990700-b897-11ea-8995-c85d8700e504.png)

![image](https://user-images.githubusercontent.com/47951826/85923897-71615c80-b897-11ea-91c7-499938331165.png)

**Code snippets**
menu-item.settings.json
```
{
    "kind": "collectionType",
    "collectionName": "menu_items",
    "info": {
        "name": "MenuItem"
    },
    "options": {
        "increments": true,
        "timestamps": true
    },
    "attributes": {
        "title": {
            "type": "string",
            "required": true
        },
        "element": {
            "type": "dynamiczone",
            "components": ["menu.post", "menu.tag"],
            "max": 1,
            "min": 1
        },
        "menu_items": {
            "collection": "menu-item",
            "via": "menu_item"
        },
        "menu_item": {
            "model": "menu-item",
            "via": "menu_items"
        },
        "entities": {
            "collection": "*",
            "filter": "field"
        }
    }
}
```

post.settings.json
```
{
    "kind": "collectionType",
    "collectionName": "posts",
    "info": {
        "name": "Post"
    },
    "options": {
        "increments": true,
        "timestamps": true
    },
    "attributes": {
        "title": {
            "type": "string",
            "required": true,
            "unique": true
        },
        "slug": {
            "type": "string"
        },
        "nameAndDescription": {
            "type": "component",
            "repeatable": false,
            "component": "content.name-and-description",
            "required": true
        },
        "content": {
            "type": "dynamiczone",
            "components": ["content.text", "content.rich-text"]
        },
        "image": {
            "type": "component",
            "repeatable": false,
            "component": "content.image"
        },
        "tags": {
            "collection": "tag",
            "via": "posts",
            "dominant": true
        },
        "menu-item": {
            "model": "menu-item",
            "via": "entities"
        }
    }
}
```

**System**

- Node.js version: 14.4.0
- NPM version: 6.14.4
- Strapi version: 3.0.5
- Database: mySQL
- Operating system: macOS Catalina

**Comment by lauriejim** [comment]
Hello! Thank you for this issue.
I agree, we should be able to manage polymorphic relations in the admin.
But this is not possible. It's not a bug, it's simply that we didn't developed it for now.
I pinged the product team about that last week.

**Comment by derrickmehaffy** [comment]
Duplicate: https://feedback.strapi.io/customization/p/manage-polymorphic-relations-in-the-admin
