### ISSUE TITLE
Permissions are not syncronized when collection is renamed

### ISSUE THREAD

**Issue by jblevins1991** [strapi/strapi#6837]
**Describe the bug**

When renaming a collection, the permission is not renamed. Because this is happening, the endpoint for that collection is also not updated to reflect changes to the collection. In my example I created a collection named 'Blogs' but later renamed it 'Post'. Below are URLs for the collection.

**Steps to reproduce the behavior**

1. Go to [my old collection name](http://161.35.3.173/blogs)
2. Observe that an empty collection with a status code of 200 is provided
3. Go to [my new collection name](http://161.35.3.173/post)
4. Observe that a 404 status code is provided

**Expected behavior**
I expect that the permissions and endpoints be renamed to reflect the changes to the collection.

**System**

- Node.js version: 
- NPM version: N/A
- Strapi version: N/A
- Database: Postgres
- Operating system: Ubuntu

**Additional context**
I installed strapi using the 1 click install on digital ocean.

**Comment by jblevins1991** [comment]
I decided to delete the collection and make a new one called Post. This is still an issue that is easy to reproduce though. Those links in the steps no longer are relevant though.

**Comment by lauriejim** [comment]
Hello! We are aware about that, I think this is the wanted behaviour.
I ping @alexandrebodin about that.
I found it weird too.

**Comment by alexandrebodin** [comment]
Hello @jblevins1991 Renaming is mearly an action of change the display name. We should be clearer in the UI. 

This does not change the routes or the db table name to avoid breaking something if you started creating data.

A full rename is a file system an database operation. It is really destructive so we want to make sure the user does not make a mistake and uses the delete action. We could all this action in a CLI command maybe.

**Comment by jblevins1991** [comment]
I think there should be an option to rename both. I understand the benefit to not immediately renaming the endpoint as the work might not be planned within the same sprint the collection was renamed. However, most teams will not be happy with the added confusion and will want to align the endpoints with the collections.

**Comment by tmikaeld** [comment]
I just tried with renaming the display name and the collection name under advanced, then going into permissions and "Public". It still says the old name, even after restart.

Version 3.1.1

**Comment by alexandrebodin** [comment]
> I just tried with renaming the display name and the collection name under advanced, then going into permissions and "Public". It still says the old name, even after restart.
> 
> Version 3.1.1

What model are you trying to rename ?

**Comment by jblevins1991** [comment]
I also just don't understand the point of not renaming the table in the database or the registered api endpoint. It just feels like this will lead to confusion between those who write content and the people developing the website. While this might be "intended behavior" it makes me feel like the product is somewhat immature. The endpoint, database table, and label in the permissions should serve as feedback that let's the content manager know that their changes in strapi were successful. I honestly thought that strapi had a bug in it or just didn't work when I saw that none of these things had changed, so I decided to go another route for my content management needs. I would be happy to contribute to the project, but I can't realistically contribute to something that the strapi team sweeps under the rug like "it's a feature, not a bug".

**Comment by alexandrebodin** [comment]
@jblevins1991 I'm sorry you feel this way. Let me give more context on how we see it. 

Allowing a technical rename (file rename / database migration) through the UI makes it really hard to do the right operation as the server is still running (and connected to the db). We cannot simply create a new table and migrate while the app is running. This kind of operation makes a lot more sense as a CLI operation and would give more control. 

That being said, We think that changing the display name should always be possible as in some cases it can just give more details in the UI without needing to change the unerdelying endpoint or db.

We must certainly make it clearer in the UI so people don't get confused.

**Comment by tmikaeld** [comment]
@alexandrebodin I assume that versioning is on the way as well, so it would make sense to have an overlap when changing API endpoints, as to now break previously versioned API paths.

**Comment by alexandrebodin** [comment]
> @alexandrebodin I assume that versioning is on the way as well, so it would make sense to have an overlap when changing API endpoints, as to now break previously versioned API paths.

Sorry I'm not sure I understood your comment ?

**Comment by tmikaeld** [comment]
@alexandrebodin 
Say we have an api URI: `/v1/events`

And we change `events` to `happenings` in a new version.

So we'll then have URI: `/v2/happenings`

While still keeping v1 like it was.

**Comment by alexandrebodin** [comment]
Ok I see your point. This is a whole other set of issues to solve but it is related :)

**Comment by derrickmehaffy** [comment]
Closing this in favor of the https://portal.productboard.com/strapi/1-public-roadmap/c/17-versioning

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/renaming-component-category-after-already-creating-data/4548/1

**Comment by FitFingers** [comment]
> Renaming is mearly an action of change the display name. We should be clearer in the UI.
> This does not change the routes or the db table name to avoid breaking something if you started creating data.

I'm trying to rename my components and their categories and this does not appear to be the case.

When I curl `1337/content-manager/components` and find the component, I can see that it has an info Object which contains the labelling used in the Strapi UI while the key for the database stays the same after renaming, however I don't see anything of the sort for the categories.

I agree with the point that only the display name should change to avoid breaking data that was already created, but I think that if this approach is taken then we should aim to do it for all fields that may be renamed. Is there a plan to do this at some point or am I missing something somewhere?

**Comment by derrickmehaffy** [comment]
> > Renaming is mearly an action of change the display name. We should be clearer in the UI.
> > This does not change the routes or the db table name to avoid breaking something if you started creating data.
> 
> I'm trying to rename my components and their categories and this does not appear to be the case.
> 
> When I curl `1337/content-manager/components` and find the component, I can see that it has an info Object which contains the labelling used in the Strapi UI while the key for the database stays the same after renaming, however I don't see anything of the sort for the categories.
> 
> I agree with the point that only the display name should change to avoid breaking data that was already created, but I think that if this approach is taken then we should aim to do it for all fields that may be renamed. Is there a plan to do this at some point or am I missing something somewhere?

It's planned in the Strapi v4 with schema migrations for now you have to modify the database manually to make changes like that.

**Comment by abhaymaniyar** [comment]
Hey @derrickmehaffy ,
is this issue been fixed now? If yes, is it present in the latest update?

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy ,
> is this issue been fixed now? If yes, is it present in the latest update?

No, this is something that will likely be addressed in our v4 version coming at the end of September but no promises there.
