### ISSUE TITLE
Create-strapi-app stuck in older version of Strapi

### ISSUE THREAD

**Issue by jiv-e** [strapi/strapi#6839]
**Describe the bug**
Create-strapi-app installs older than current Strapi version. 

**Steps to reproduce the behavior**

1. Install Strapi 3.0.0-beta.17.4 globally. npm install strapi@^3.0.0-beta.17.4 -g
2. Uninstall Strapi globally. npm uninstall strapi -g
3. Run: npx create-strapi-app my-project --quickstart
4. Check the version create-strapi-app installed.
5. Strapi version 3.0.0-beta.17.4 is installed.

**Expected behavior**
Current version of Strapi is installed.

**System**

- Node.js version: 12.14.1
- NPM version: 6.13.6
- Operating system: OSX

**Additional context**
I also tried to install Strapi 3.0.0-beta.18 globally instead of beta.17. Create-strapi-app is still stuck in beta.17. Is the Strapi version cached somewhere?

**Comment by jiv-e** [comment]
Maybe related: #6655

**Comment by derrickmehaffy** [comment]
This is not an issue with Strapi but the users in environment. Moving to a discussion
