### ISSUE TITLE
Sendgrid is not being displayed in email-plugin in strapi

### ISSUE THREAD

**Issue by Ermal45** [strapi/strapi#6841]
![sendgridblank](https://user-images.githubusercontent.com/62566277/85948180-ab8e3500-b94f-11ea-85b4-4b0d61fe3c45.png)

I don't know if this is a bug or anything i just submitted this as a bug,bc its not working for some reason.I installed the package from npmjs.com with --save in the end and still doesn't show up i am using strapi v3.0.0-beta.20.3

**Comment by derrickmehaffy** [comment]
`v3.0.0-beta.20.3` Beta is no longer supported and you are using an older version of the plugin as the AdminUI no longer shows the providers as they are now using files for configs. See: https://github.com/strapi/strapi/issues/6710

(as a side note, questions should be directed towards discussions, issues require a proper template)

**Comment by Ermal45** [comment]
yeah my bad this was my first time asking a question in github and i just went through, again thanks for the answer.
