### ISSUE TITLE
Lifecycles Hook beforeUpdate get error id: "entry.notFound",

### ISSUE THREAD

**Issue by swina** [strapi/strapi#6843]
**Lifecycles Hooks beforeUpdate error**
Assigning a new value to a content field beforeUpdate getting the following error: 
`{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"entry.notFound","message":"entry.notFound"}]}],"data":[{"messages":[{"id":"entry.notFound","message":"entry.notFound"}]}]}`

**Expected behavior**
A content field should be updated with the new value

**Code snippets**
Path — ./api/article/models/article.js.
```
module.exports = {
    lifecycles : {
        beforeUpdate: async (data) => {
            data.slug = 'some-text'
        }
   }
}
```
Data submitted
```
------WebKitFormBoundarye1E1TIkcBcfMdE88
Content-Disposition: form-data; name="data"

{
"excerpt":"ASDASDASDASDasd",
"published_at":"2020-06-27",
"created_at":"2020-06-27T15:35:16.000Z",
"slug":"my-new-article",
"gallery":[],
"updated_at":"2020-06-29T00:42:02.000Z",
"title":"My New Article",
"tags":[5,4],
"content":null,
"id":3,
"image":null,
"seo":[],
"category":2
}
------WebKitFormBoundarye1E1TIkcBcfMdE88--
```

**System**

- Node.js version:  14.4.0 
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: mySQL 5.7
- Operating system: Win10

**Comment by derrickmehaffy** [comment]
`"id":3,` you don't send the ID in the update request (as that isn't a field you can directly modify)

Your ID is appended to URL query `localhost:1337/yourModel/3` and as a side point you should only send what you intend to change.

**Comment by swina** [comment]
Ok but when the form is submitted it sends the ID as fom data. I noticed also that the Save on a existing record instantiate a PUT method. Since is an update maybe a PATCH method could solve the beforeUpdate hook with the ID

**Comment by lauriejim** [comment]
Thank you for this report - I confirm, it doesn't work and I have the same error message.
I ping @alexandrebodin about that.

**Comment by alexandrebodin** [comment]
Hello, Did you read the doc ? 

The beforeUpdate function takes to arguments `params` and `data` you are modifying the params thus trying to edit and entry with this slug and it doesn't find it.

**Comment by alexandrebodin** [comment]
You can find the doc here: https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

**Comment by bsautron** [comment]
Hey @alexandrebodin, I still use the v3, and the like you share 404.
What did it say ?

**Comment by derrickmehaffy** [comment]
https://docs-v3.strapi.io/developer-docs/latest/development/backend-customization.html#lifecycle-hooks
