### ISSUE TITLE
Unable to use session middleware with graphql plugin

### ISSUE THREAD

**Issue by janokacer** [strapi/strapi#6850]
**Describe the bug**
I am unable to use session middleware with graphql plugin because graphqlContext.context.session is not correctly populated.

**Steps to reproduce the behavior**

1. install graphql plugin
2. enable session middleware
3. extend graphql schema (api/user/config/schema.graphql.js)
```js
module.exports = {
  query: `
    getUser: Int!
  `,
  resolver: {
    Query: {
      getUser: {
        resolverOf: 'application::user.user.getUser',
        resolver: async function getUserHandler(obj, args, {context}) {
          context.session.ctr = (context.session.ctr || 0) + 1
          console.log('check counter', context.session.ctr)

          return context.session.ctr
        },
      },
    },
  },
}
```

4. call graphql query getUser
```graphql
query {
  getUser
}
```

**Expected behavior**
Increment counter in session.

**System**

- Node.js version: v12.18.0
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: sqlite3
- Operating system: WSL 2, windows 10

**Comment by lauriejim** [comment]
Hello! According to the code source of the session middleware
I think you should use `ctx.state.session` - https://github.com/strapi/strapi/blob/1cb92daa77980c54c94adec6b6f550978beba433/packages/strapi/lib/middlewares/session/index.js#L131

**Comment by janokacer** [comment]
Hello! Thanks for your response. Unfortunately, it didn't help.

```javascript
console.log(context.state.session) // prints undefined
console.log(context.session) // prints always new empty session object for each request
```

**Comment by derrickmehaffy** [comment]
> Hello! Thanks for your response. Unfortunately, it didn't help.
> 
> ```js
> console.log(context.state.session) // prints undefined
> console.log(context.session) // prints always new empty session object for each request
> ```

it would be `ctx.state.session` not `context`
