### ISSUE TITLE
Model can't be found error with Bookshelf + MySql

### ISSUE THREAD

**Issue by daxyonis** [strapi/strapi#6855]
**Describe the bug**
My Strapi is linked to mysql database and I created several content types. When I try to access the bookshelf model for creating custom query I have an error : **The model [...]can't be found.** There is no error with SQLite DB.

**Steps to reproduce the behavior**

1. Create Communication Collection Content type with subject field = text
2. Give public role access to find, findOne
3. Create 2-3 communications with various subjects
4. In /api/communication/services/communication.js, extend method find(params,populate) and try accessing the ORM model:
` const model = strapi.query('communication', 'bookshelf').model;`
5. Call find API using Postman and request GET http://localhost:1337/communications?subject_contains=Math

**Expected behavior**
I expected to get the model (which it does when sqlite is used).

**Code snippets**
`find(params, populate) {        
          const model = strapi.query('communication', 'bookshelf').model;        
          return model.query(qb => {
            qb.where('subject', 'LIKE', `Math%`)            
          }).fetchAll()                
    },`

**System**

- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version:  3.0.0
- Database: MySql 8.0
- Operating system: Windows 10
![strapiBug](https://user-images.githubusercontent.com/16484367/86077690-6b67a900-ba5a-11ea-9866-8145c8850868.png)

**Comment by derrickmehaffy** [comment]
you don't need the `bookshelf` part in `const model = strapi.query('communication', 'bookshelf').model;` that is only used for Strapi plugins such as `users-permissions` or `content-manager`.
