### ISSUE TITLE
Options provided in knex (strapi-connector-bookshelf) doesn't work for PG-compatible DBs (CockroachDB)

### ISSUE THREAD

**Issue by virgil9306** [strapi/strapi#6857]
**Describe the bug**

Trying to connect to CockroachDB gives 

```
/srv/app/node_modules/knex/lib/dialects/postgres/index.js:146
        resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
                                                                    ^

TypeError: Cannot read property '1' of null
    at Query.<anonymous> (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:146:69)
    at Query.handleReadyForQuery (/srv/app/node_modules/pg/lib/query.js:129:12)
    at Connection.<anonymous> (/srv/app/node_modules/pg/lib/client.js:266:19)
    at Connection.emit (events.js:315:20)
    at /srv/app/node_modules/pg/lib/connection.js:109:10
    at Parser.parse (/srv/app/node_modules/pg-protocol/dist/parser.js:42:17)
    at TLSSocket.<anonymous> (/srv/app/node_modules/pg-protocol/dist/index.js:8:42)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Steps to reproduce the behavior**

1. Connect to CockroachDB using the method to connect to Posgres (Bookshelf)

**Expected behavior**

Default options provided should be enough for Strapi to work with Postgres **and** Postgres-compatible DBs because `knex` is compatible with those. However, there are some missing options that would otherwise make it work.

**Steps to resolve???**

This error occurs because Strapi uses `knex` which requires additional parameters to use Postgres-compatible DBs such as CockroachDB.

The official way to solve this according to https://github.com/knex/knex/issues/2892 is to follow these options: https://github.com/knex/knex/wiki/Recipes (_"Using non-standard database that is compatible with PostgreSQL wire protocol (such as CockroachDB)"_)

Actually it is just adding the `version` parameter (`9.5` in the case of latest CockroachDB)

If the option can be included, then Strapi will be able to support not just Postgres but also PostgreSQL wire-compatible DBs.

**Unfortunately there's nowhere in the config to override these options that I am aware of so I couldn't figure out how to test it locally after Strapi is already built**

**Screenshots**
N/A

**Code snippets**
* Need to add options here: https://github.com/strapi/strapi/blob/7123a11444b41d93c2a110822229cd46aadc49e3/packages/strapi-connector-bookshelf/lib/knex.js#L131
* Options for `knex` should follow something like this pattern for CockroachDB to work (according to their docs):

```
const knex = require('knex')({
  client: 'pg',
  version: '7.2',
  connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  }
});
```

so the missing parameter is just `version`.

**System**

- Node.js version: 12.18
- NPM version: 6.4.14
- Strapi version: 3.0.5
- Database: CockroachDB (Postgres wire-compatible)
- Operating system: OSX 10.15 Catalina

**Other information**

* CockroachDB is compatible with PostgreSQL 9.5 (https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html)

**Comment by derrickmehaffy** [comment]
CockroachDB is not a supported database, on straight PostgreSQL is supported.

**Comment by derrickmehaffy** [comment]
@alexandrebodin can you confirm and I can close this out?

**Comment by virgil9306** [comment]
Thanks @derrickmehaffy .

To my understanding `knex` handles it as compatible, so if Strapi has Postgres tests then it means it is working with `knex` with Postgres?

Obviously that is not a solution to say "we support CockroachDB" but since the feature of version override is supported by `knex` is there at least a way to pass this parameter to it?

**Comment by alexandrebodin** [comment]
have you tried something like this ?: 

```js
module.exports = {
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        database: 'strapi',
        username: 'strapi',
        password: 'strapi',
        port: 5432,
        host: 'localhost',
      },
      options: {
        version: '10.1'
      },
    },
  },
};


```

**Comment by virgil9306** [comment]
Thanks @alexandrebodin .

Will try that now and report back.

**Comment by derrickmehaffy** [comment]
@virgil9306 Glad you found something that works out for you, regardless if knex directly supports other databases doesn't inherently mean Strapi will. Strapi "supported" databases means that every commit, every pull request, every release has been properly tested on that **specific** database. Likewise if we list it as "supported" that means users with bugs on that database can submit bugs, ect for it and the same applies to Operating systems.

Knex for instance supports Microsoft SQL server but Strapi does not, I would love to see more databases added but for the moment Strapi have stated they currently are not looking to support *any* new databases other than the core ones listed on the README.

**Comment by virgil9306** [comment]
That makes sense @derrickmehaffy . Thanks for your help. I will strongly consider moving to an officially supported database. I've closed this issue. I hope others looking for CockroachDB support will find some useful info and information to decide on.

**Comment by lgs** [comment]
CockroachDB +1
