### ISSUE TITLE
Boom catches error before Sentry

### ISSUE THREAD

**Issue by XuluWarrior** [strapi/strapi#6863]
In the [documentation](https://strapi.io/documentation/v3.x/guides/error-catching.html#handle-errors) it says that the Sentry middleware should be added at the beginning of the middleware stack.

However, when my config is `before: ['sentry']` I have found that the boom middleware catches the error before it reaches Sentry.

So I've found that I need to set my config to `before: ['boom', 'sentry']`

Is this a bug in the documentation, boom or my understanding?

**Comment by derrickmehaffy** [comment]
See: https://github.com/strapi/strapi/pull/6430/files

`Make sure your middleware is added at the beginning of the middleware stack.` It does state it needs to be at the beginning.

**Comment by XuluWarrior** [comment]
@derrickmehaffy It is by putting `sentry` at the beginning that causes it not to work.
I have to put it after `boom`

Or am I misreading the `before` syntax?  I assumed it reads items on the left are "before" items on the "right".

In the example, `sentry` is leftmost but I have to put it to the right of `boom`

**Comment by XuluWarrior** [comment]
@derrickmehaffy It feels like you closed this issue without acknowledging that it was by following the documentation changes that both of us referred to, errors don't actually get caught by the `sentry` middleware.

I've just read the comments of #6430 and I can see that I am not the only person that feels the documentation is wrong.

I am happy to make a PR if somebody can confirm that my understanding is correct.  I'm also happy to be shown wrong :)

@Froelund Is there something I'm missing that means that `sentry` can be the first `before`?

**Comment by derrickmehaffy** [comment]
@XuluWarrior please feel free

**Comment by laurenskling** [comment]
Correct, the documentation is wrong since https://github.com/strapi/strapi/pull/6430 . I guess it was merged because it's easy to _assume_ that documentation is right, but it doesn't work. I'm no expert in middleware, so I don't know what the perfect place is. All I know is that the current documentation is wrong. I'd be happy to test out a correct documentation @XuluWarrior can make

**Comment by XuluWarrior** [comment]
I've created the PR.  Apologies for the delay.
