### ISSUE TITLE
Removing content-type from admin is not removing custom controller and related route.

### ISSUE THREAD

**Issue by fanixus96** [strapi/strapi#6864]
After removing content type with admin, api/removed_content_type/config/routes.json (with single route added by me) and 
api/removed_content_type/controllers/controller_added_be_me with its content still exist.

**Steps to reproduce the behavior**

1. Create content_type
2.Create custom controller and route for it
3.Remove content_type with admin

**Expected behavior**
Every file related to removed_content_type should be deleted.

**System**

- Node.js version: v12.16.3
- NPM version:6.14.4
- Strapi version: 3.0.5
- Database: default
- Operating system: macos

**Comment by Ryuk-hash** [comment]
I can suggest a solution - if you're using mysql db, install its workbench then connect to the respective local db, there you can see a list of tables. You can delete the entire table from there. Unsure if it will work - always solved the same problem for me though.

**Comment by fanixus96** [comment]
Unfortunately I'm looking for a production solution that will be more automatic :) I hope it is possible to extend delete script and fix it someway.

**Comment by lauriejim** [comment]
Hello! This is the wanted behaviour.
On the Strapi side, how we can know that everything is related to your Content Type and that the custom code you added is related to something else.
In fact we can't, that's the reason why we decided to not delete stuff you customised.
