### ISSUE TITLE
Multiple image uploads to Media Library consuming huge memory results in Server restarts on DEV/UAT

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#6869]
**Describe the bug**
Multiple image uploads randomly throwing `502 Bad Gateway` error & consuming huge memory, results in Server restart on deployed environments (DEV or UAT).

Earlier we were having `512 MB` memory allocated to our `Strapi` app on DEV/UAT/PROD until Strapi version: `3.0.0-beta.19.3` and it worked fine . 

Now we are trying to upgrade Strapi to `3.0.0-beta.20.3` which is a major upgrade of `Media Library`. 

On `3.0.0-beta.20.3` It looks this issue is happening due to memory leak. Now we are using 1 GB memory for `Strapi`  app on any deployed environments but still this memory is not sufficient, which leads to server restarts.

**Note:** This issue is not at all happening on Local (my machine has 16gb memory).

**Blocker:** **This is actually a major issue for us which is blocking our Release**

**Steps to reproduce the behavior**

1. Go to: Media Library on Strapi v`3.0.0-beta.20.3`
2. Try to upload multiple uploads (you can use Images with size: 2-3mb & Videos 50-100mb)
3. See error: It throws `502 Bad Gateway` error & results in server restart (due to memory leak/usage of excessive memory)

**Expected behavior**
1. Strapi's Media Library should work as expected with multiple uploads (Images/Videos)
2. There should not be any memory Leak on DEV/UAT/PROD
3. 512mb should be sufficient to this App (Since we were using 512mb earlier)

**System**

Node version: `v10.15.3`
NPM version: `6.4.1`
Strapi version: `3.0.0-beta.20.3` with `Media Library`
Database: `Mongo` & `S3` File storage for File uploads
Operating system: `MAC`
Allocated memory for App on Deployed environments: `1gb`

**Additional context**

**Comment by markjlaney** [comment]
I am experiencing the same issue. Unfortunately it causes our server to continually restart and is a huge blocker for us. We can't upgrade until this issue is resolved and is a high priority bug.

**Comment by vinod77** [comment]
Hi..
Looks this memory leak issue is causing by the Buffer.

https://github.com/strapi/strapi/blob/v3.0.0-beta.20.3/packages/strapi-plugin-upload/services/Upload.js#L82 

The default Strapi code uses `fs.readFile`  which uses Buffer, leads to memory leak.. So I wrote my own code, using `fs.createReadStream` which reads/streams the file from the file Storage (S3) itself, in this case there won't be any memory leak.

`fs.readFile` uses Buffer that holds/leaks the memory space to read the files but `fs.createReadStream` doesn't.

And i have also removed `generateThumbnail`: https://github.com/strapi/strapi/blob/v3.0.0-beta.20.3/packages/strapi-plugin-upload/services/Upload.js#L125 which takes huge time to generate thumb

**Comment by jasonprado** [comment]
On a related note, I think `strapi.plugins["upload"].services["upload"].uploadFileAndPersist` should support streams as well as buffers. I have an endpoint that fetches a 100mb file from a remote server and right now it has to be pulled into a `Buffer`, which I believe has to be in-memory.

Should a Stream API for uploads be a separate issue or should the discussion stay here?

**Comment by lynndylanhurley** [comment]
@derrickmehaffy were you able to find a workaround? I have a client yelling at me over this

**Comment by derrickmehaffy** [comment]
@lynndylanhurley I have not but it's in our backlog for this month: https://github.com/strapi/strapi/issues/6432#issuecomment-686568499

**Comment by AryanGharshi** [comment]
Any updates?

**Comment by derrickmehaffy** [comment]
They are looking into it @AryanGharshi but no ETA yet.

**Comment by derrickmehaffy** [comment]
Closing this in favor of: https://github.com/strapi/strapi/issues/6432
