### ISSUE TITLE
Can't install dependencies with custom .npmrc

### ISSUE THREAD

**Issue by nonameolsson** [strapi/strapi#6873]
**Describe the bug**

I have my personal license key for FortAwesome in `~/.npmrc`. This is because I use it in other projects at work. But when I try to install the Strapi project, it complains about not being authorized to download packages from FortAwesome. 

If I rename the `~/.npmrc` before installing the packages then everything works.

**Steps to reproduce the behavior**

1. Make sure you have a license key(doesn't need to be valid) in `~/.npmrc`. 
2. Clone https://github.com/nonameolsson/timeline-backend
3. `yarn`
4. Boom, error.

**Expected behavior**
The packages should be installed.

**Code snippets**
```
❯ yarn
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-brands-svg-icons/-/5.13.0/free-brands-svg-icons-5.13.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/andreasolsson/Code/GitHub/timeline-backend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  ~/Code/GitHub/timeline-backend on   temp ❯
```

**System**

- Node.js version: 12.18.2 
- NPM version: 6.14.5
- Strapi version: 3.0.1 
- Database: sqlite
- Operating system: MacOS 10.15.5

**Comment by derrickmehaffy** [comment]
Based on this: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

It requires a different registry, and this has different package names than what is normally used within the project. I'm marking this as closed as it's not directly a bug with Strapi and you will need to make whatever changes to packages you need to use the alt font package. You will need to setup some package alias for the alt registry or setup your own npm package proxy to pull from both npm and fontawesome's registry.

**Comment by derrickmehaffy** [comment]
see:

https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#how-do-i-customize-a-plugin
https://strapi.io/documentation/v3.x/admin-panel/customization.html#customize-the-strapi-admin-package

**Comment by nonameolsson** [comment]
Thanks, it helped me.
