### ISSUE TITLE
Error after upgrade. "plugin "users-permissions" failed... Cannot read property 'id' of null"

### ISSUE THREAD

**Issue by kauaicreative** [strapi/strapi#6874]
**Describe the bug**
The following error started appearing after upgrading from 3.0.0-beta.20.3 to 3.0.5 and deploying to Heroku
```
error Bootstrap function in plugin "users-permissions" failed 
error TypeError: Cannot read property 'id' of null
at C:\dev\node\gym-cms\node_modules\strapi-plugin-users-permissions\services\UsersPermissions.js:270:59
```

**Steps to reproduce the behavior**

1. Followed instructions to upgrade
2. Upgraded Strapi from 3.0.0-beta.20.3 to 3.0.5. 
3. Initially everything worked locally
4. Once I deployed to Heroku app crashed
5. At this point the following error started appearing both locally and on Heroku.

**Screenshots**
Error with object log for context:
![WindowsTerminal_S2VdJx4Bvr](https://user-images.githubusercontent.com/127033/86201540-d46c2100-bb2d-11ea-9562-2e03eb4ae3c3.png)

The effected table and null roles:
![image](https://user-images.githubusercontent.com/127033/86201617-0bdacd80-bb2e-11ea-8756-e41a99d867cc.png)

**System**

- Node.js version: v12.13.1
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: postgres
- Operating system: Windows 10

**Question**
The app will no longer run. What is the fix? Should I modify the null role columns?

**Comment by kauaicreative** [comment]
If anyone has this issue in the future I was able to get the app running again by replacing the role column `null` values with `1`

**Comment by lauriejim** [comment]
Hum that's really weird... 
thank you for the fix, I'm closing the issue.
