### ISSUE TITLE
Error in installation on Linux

### ISSUE THREAD

**Issue by officialrj18** [strapi/strapi#6877]
### Error while installation on Linux

**Steps to reproduce the behavior**
1. yarn create strapi-app my-project --quickstart
2. See error

**Code snippets**
`npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained

> sharp@0.24.1 install /home/normal/Desktop/strapi-test/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://hostname/path/libvips-8.9.0-linux-x64.tar.gz
ERR! sharp getaddrinfo ENOTFOUND hostname
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
make: Entering directory '/home/normal/Desktop/strapi-test/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:25:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:135: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/normal/Desktop/strapi-test/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/home/normal/.nvm/versions/node/v12.14.1/bin/node" "/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/normal/Desktop/strapi-test/node_modules/sharp
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN strapi-connector-bookshelf@3.0.5 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.24.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/normal/.npm/_logs/2020-07-01T07_38_32_472Z-debug.log

[2020-07-01T07_38_32_472Z-debug.log](https://github.com/strapi/strapi/files/4856386/2020-07-01T07_38_32_472Z-debug.log)

`

**System**
- Node.js version:  v12.14.1
- NPM version: v6.13.4
- Operating system: MX Linux

**_Solutions that didn't work for me_**

- i have tried with different node versions
- removed node modules and ran `npm install` again
- tried with yarn too

**Comment by derrickmehaffy** [comment]
ensure you install the `build-essential` and `libpng-dev` packages.

**Comment by officialrj18** [comment]
> ensure you install the `build-essential` and `libpng-dev` packages.

@derrickmehaffy , just checked, they are already installed.

**Comment by derrickmehaffy** [comment]
It would appear that you have some kind of resolution problem with libvips, I can't reproduce this on Linux mint. Although I did notice your mom version is a tad high, did you install node v14 then downgrade to v12? It's possible you have an issue with that npm version that ships with v14

**Comment by officialrj18** [comment]
> It would appear that you have some kind of resolution problem with libvips, I can't reproduce this on Linux mint. Although I did notice your mom version is a tad high, did you install node v14 then downgrade to v12? It's possible you have an issue with that npm version that ships with v14

@derrickmehaffy i didn't install node v14, i am in node v12 and i have tried by downgrading it too but didn't work. Is there anywork around to solve this resolution issue if it is the main cause.

**Comment by derrickmehaffy** [comment]
I don't have much of any guidance for issues with sharp/node-gyp. I ran a virtual machine of the latest mx linux with node 12 and didn't hit any issues. Something had to have been changed or something on your own install is throwing problems but it's not a bug of Strapi.

**Comment by officialrj18** [comment]
> I don't have much of any guidance for issues with sharp/node-gyp. I ran a virtual machine of the latest mx linux with node 12 and didn't hit any issues. Something had to have been changed or something on your own install is throwing problems but it's not a bug of Strapi.

updated mx linux to latest 19.2 (was on 19.1) .tired to make new project and this what i got again.

`yarn create strapi-app strapiPrj --quickstart
yarn create v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-strapi-app@3.0.5" with binaries:
      - create-strapi-app
Creating a new Strapi application at /home/normal/strapiPrj.

Creating a quickstart project.
Creating files.
⠋ Installing dependencies: warning url-loader@1.1.2: Invalid bin field for "url-lo⠙ Installing dependencies: warning url-loader@1.1.2: Invalid bin field for⠹ Installing dependencies: warning url-loader@1.⠸ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠼ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠴ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠦ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠧ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠇ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠏ Installing dependencies: warning url-loader@1.1.2: Inval⠋ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠙ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠹ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠸ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠼ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠴ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠦ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠧ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠇ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠏ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠋ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠙ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠹ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠸ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠼ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠴ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠦ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠧ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠇ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠏ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠋ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠙ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠹ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠸ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠼ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠴ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠦ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠧ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠇ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠏ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠋ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠙ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠹ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠸ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠼ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠴ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠦ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠧ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠇ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠏ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠋ Installing dependencies: warning url-loader@1.1.2: Invalid bin fi⠙ Installing dependencies: warning url-loader@1.1.2⠹ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠸ Installing dependencies: warning url-loader@1.1.2: Invalid bin fie⠼ Installing dependencies: warning url-loader@1.1.2: ⠴ Installing dependencies: warning url-loader@1.1.2: Invalid bin fiel⠦ Installing dependencies: warning url-loader@1.1.2: Invalid bin fiel⠧ Installing dependencies: warning url-loader@1.1.2: In⠇ Installing dependencies: warning url-loader@1.1.2: Invalid bin field⠏ Installing dependencies: warning url-loader@1.1.2: Inv⠋ Installing dependencies: warning url-loader@1.1.2: Inv⠙ Installing dependencies: warning url-loader@1.1.2: Inv⠹ Installing dependencies: warning url-loader@1.1.2: Inv⠸ Installing dependencies: warning url-loader@1.1.2: Inv⠼ Installing dependencies: warning ⠴ Installing dependencies: warning url-loader@1.1.2: In⠦ Installing dependencies: warning url-loader@1.1.2: Inv⠧ Installing dependencies: warning url-loader@1.1.2: Invalid bin⠇ Installing dependencies: warning url-loader@1.1.2: Invalid b⠏ Installing dependencies: warning url-load⠙ Installing deError while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning strapi-admin > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > react-intl > @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
warning strapi-admin > react-virtualized > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning strapi-admin > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning strapi-plugin-content-manager > draft-js > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-plugin-users-permissions > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning url-loader@1.1.2: Invalid bin field for "url-loader".
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning "strapi-admin > @buffetjs/core > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
warning "strapi-plugin-users-permissions > grant-koa@5.2.0" has unmet peer dependency "koa@>=2.0.0".
warning " > strapi-connector-bookshelf@3.0.5" has incorrect peer dependency "knex@^0.20.0".
error /home/normal/strapiPrj/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/normal/strapiPrj/node_modules/sharp
Output:
info sharp Downloading https://hostname/path/libvips-8.9.0-linux-x64.tar.gz
ERR! sharp getaddrinfo ENOTFOUND hostname
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.14.1 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v12.14.1/node-v12.14.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.14.1/node-v12.14.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.14.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.14.1/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/normal/strapiPrj/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/normal/.cache/node-gyp/12.14.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/normal/.cache/node-gyp/12.14.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/normal/.cache/node-gyp/12.14.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/normal/strapiPrj/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/normal/strapiPrj/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:25:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:135: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/normal/strapiPrj/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/home/normal/.nvm/versions/node/v12.14.1/bin/node" "/home/normal/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/normal/strapiPrj/node_modules/sharp
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

 Keep trying!             

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd /home/normal/strapiPrj && yarn install

error Command failed.
Exit code: 1
Command: /home/normal/.yarn/bin/create-strapi-app
Arguments: strapiPrj --quickstart
Directory: /home/normal
`

**Comment by derrickmehaffy** [comment]
This issue is outside of Strapi control based on reading through https://github.com/lovell/sharp/issues/1882

I'm going to mark this as closed, please refer to sharp and likewise libvips https://github.com/libvips/libvips

As this is a user environment issue and not a bug with Strapi (I am completely unable to reproduce this on over 18 tests with 8 different operating systems)

**Comment by thisispete** [comment]
same problem following the steps for strapi using mongo atlas and heroku, it installs but it throws these errors on push to heroku, the app runs but it's missing buttons under create content type, its basically useless after install. `remote:        warning "strapi-admin > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
remote:        warning "strapi-admin > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".`

**Comment by thisispete** [comment]
explicitly adding
`  "jquery": "^3.5.1",
    "koa": "^2.13.0",
    "popper.js": "^1.16.1",`
to package.json and re-pushing to heroku silences warnings but the admin still doesn't work properly (missing buttons to add new content types, etc)

everything works locally, just not on heroku.

**Comment by derrickmehaffy** [comment]
In your package.json for `engine` try setting that to a static version, it's quite likely that heroku is taking the `engine` default setting from Strapi and is trying to use node v14 (which isn't supported yet). Why in the world heroku tries to use a non-LTS version I have no idea, but v14 doesn't go LTS until October.

**Comment by thisispete** [comment]
thanks. I also didn't know content type modeling wasn't supported on production, everything probably was working on 14 after I installed those extra packages, I was expecting it to look the same as my localhost, but now I see that isn't expected behavior.. just set my engine to "node": "12.18.3" and it builds without warnings.

**Comment by niclaspallin** [comment]
I just got this issue, and managed to resolve it. I was using strapi/base in the docker file, which always takes the latest version - and it uses node 14. 

TDLR;
I resolved it by changing to **strapi/base:12-alpine.**

**Comment by ashiishme** [comment]
Here's a work around if anyone is facing the project installation due to incompatible node version:

Use `npx` rather than `yarn` so that the engine checks will not block the project creation. It will show the error but the project will be created.

You can then ignore the engines when installing the deps.

Example:

`npx create-strapi-app my-app --quickstart`

Now, install the deps by ignoring the engine:

`yarn --ignore-engines install`

You should ignore the engine everytime using the yarn commands.

`yarn --ignore-engines develop`

OR, get rid of `--ignore-engines` by updating your **yarn config**.

`yarn config set ignore-engines true`

But I would rather prefer **nvm** and use compatible node version. :smile:
