### ISSUE TITLE
The admin panel doesn't show matching results when searching for entries in collection

### ISSUE THREAD

**Issue by dimozaprianov** [strapi/strapi#6878]
**Describe the bug**
The admin panel doesn't show matching results when searching for entries in collection

**Steps to reproduce the behavior**

1. Go to Admin
2. Click to edit a collection with more than 10 entries
3. Go to the last page
4. Click on Search for entries... and start typing a string that should match at least one of the entries
5. When you have just a few matches, the interface indicates it has found entries but shows nothing in the list

**Expected behavior**
Always show matches in the list when there are such

**Screenshots**
![image](https://user-images.githubusercontent.com/1011810/86221399-871f9c00-bb8d-11ea-89be-666c43b9a0c1.png)

**System**

- Node.js version: 12.16.1
- NPM version: 
- Strapi version: 3.0.5
- Database: SqlLite
- Operating system: Windows 10

**Comment by soupette** [comment]
The issue will be fixed when #6999 will be merged.

**Comment by MattieBelt** [comment]
@soupette same here ;) (wrongly mentioned)
