### ISSUE TITLE
Media Library files stop working

### ISSUE THREAD

**Issue by Fdom92** [strapi/strapi#6879]
**Describe the bug**
I'm using the default flow to upload Media to Strapi. I have a Content Type with a cover photo and video, I add the videos and images to Media Library by uploading assets button. 

At the start all works fine, I can see the images and videos on Media Library and my Content Type has the correct cover and video, but after some time the content on Media Library stop working. The Content Type start getting 404 for the cover and video, also on the Media Library I see the images and videos not loading and not working.

**Expected behavior**
The Media images and videos should work always

**Screenshots**
<img width="251" alt="Captura de pantalla 2020-07-01 a las 11 28 08" src="https://user-images.githubusercontent.com/7361737/86227920-0319e400-bb8e-11ea-9fc1-41ea115162df.png">
<img width="248" alt="Captura de pantalla 2020-07-01 a las 11 28 28" src="https://user-images.githubusercontent.com/7361737/86227927-0614d480-bb8e-11ea-91a8-398c405f8c2e.png">

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20
- Database: MongoDB

**Comment by alexandrebodin** [comment]
Hello, do you also get the error on the stable version ? If so, can you give steps to reproduce ?

**Comment by soupette** [comment]
Hello @Fdom92 are you getting the error in production or in development?

**Comment by Fdom92** [comment]
In Production, I'm deploying to Heroku

**Comment by soupette** [comment]
@Fdom92 when you deploy your app to Heroku you need to change your upload provider here is our [documentation](https://github.com/strapi/strapi/pull/7046#issuecomment-660087574) about it.

**Comment by alexandrebodin** [comment]
Closing as there is nothing to do on Strapi side here.
