### ISSUE TITLE
Incorrect Examples Value on Documentation Plugin

### ISSUE THREAD

**Issue by joelbqz** [strapi/strapi#6881]
**Describe the bug**
On documentation plugin examples on some endpoints are showing "foo": string

**Steps to reproduce the behavior**

1. Create a new Strapi project using --quickstart
2. Install documentation plugin
3. Open documentation and go to UserPermissions - User
4. See example value on: `/auth/local` `/auth/forgot-password` `/auth/reset-password` etc

**Expected behavior**
Example Value:
```
{
  "foo": "string"
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/19965325/86259866-2e96d180-bb82-11ea-80be-509508cce3d1.png)

**System**

- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.5
- Database: SQLite
- Operating system: macOS Catalina 10.15.5

**Comment by nonameolsson** [comment]
Why was this issue closed? The key is still `foo`. When generating API clients based on the OpenAPI standard till will result in errors.

![image](https://user-images.githubusercontent.com/1493018/91656250-ab2d2a00-eab7-11ea-8c00-5e2222bd12f0.png)
