### ISSUE TITLE
Foreign relationship shows up as blank in admin panel with autoPopulate: false

### ISSUE THREAD

**Issue by mizvyt** [strapi/strapi#6883]
**Describe the bug**
Let's say we have a system of Topics and Articles within them. An Article has a single Topic, but the Topic does not show up when editing this Article if "autoPopulate" on "topic" within "article" is set to false. This issue requires me to set the property to "private" instead, but then I don't get the ID of the Topic returned in REST of course...

**Steps to reproduce the behavior**

1. Create two collection types, Topic and Article
2. Add a "has many" relationship between these two ( "articles" in Topic, "topic" in Article)
3. Set the "topic" field in Article to "autoPopulate: false"
4. Go to the admin panel and create a new Article, **make sure to assign a Topic** to this article (as I know, Strapi still does not support `required` for related objects, so as a side note, I'd love to hear when that's planned to be available)
5. Save
6. Edit the same Article again
7. Look at the Topic field on the right - it will be blank
8. Clicking on the Topic field "Details" will throw an error

**Expected behavior**
The Topic field should be populated in the admin panel whether or not "autoPopulate" is set to false.

**Screenshots**
![image](https://user-images.githubusercontent.com/43022287/86306951-1db09380-bc48-11ea-8ea6-d55d44b64e5e.png)

If we click "Details" on the above, we get a nasty error in the dashboard, as it's trying to navigate to `help-topic/undefined`.

**System**

- Node.js version: v12.15.0
- NPM version: 6.14.4
- Strapi version: 3.0.5
- Database: PostgreSQL 12
- Operating system: Ubuntu 18.04.4 LTS

**Comment by lauriejim** [comment]
Thank you for reporting this.
Related issue: https://github.com/strapi/strapi/issues/4630

@alexandrebodin @soupette The fact that we set `autoPopulate: false` affect every query even from the admin panel.
Do we have to do an exception here?

**Comment by alexandrebodin** [comment]
Yep that's an issue. We should not account for the autoPopulate with the contentManager. Will be tackled in the db layer refactor

**Comment by derrickmehaffy** [comment]
For context, the DB Refactor: https://portal.productboard.com/strapi/1-roadmap/c/73-database-layer-v4

**Comment by ViachaslauBohdan** [comment]
@alexandrebodin 
Yep, the same problem for many-to-many relations

`autoPopulate: true`

![image](https://user-images.githubusercontent.com/29509675/94271803-6b385600-ff42-11ea-8356-1a03a04fead7.png)



`autoPopulate: false`

![image (1)](https://user-images.githubusercontent.com/29509675/94271832-7a1f0880-ff42-11ea-84e6-451d79c57183.png)

**Comment by derrickmehaffy** [comment]
should be fixed in v4, closing
