### ISSUE TITLE
/user/me and ctx.state.user doesn't return OneToMany relations properly

### ISSUE THREAD

**Issue by TheWebsDoor** [strapi/strapi#689]
**Node.js version**:
8.9.3
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
MacOS 10.13.3

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Hi !
When we have a OneToMany relation in the user with other entities, the current user in `ctx.state.user` will not display all the relations properly. Instead, it will return the last object related id in the list instead of an array of objects. We have the same problem with the `/user/me` route (because it uses the `state.user` in context too).
On the other hand, when we call the route `/user/:id`, all the related entities will be returned so the problem is related to the `ctx.state.user`.

<img width="531" alt="capture d ecran 2018-02-22 a 14 46 09" src="https://user-images.githubusercontent.com/3693028/36561053-9d496f36-17e0-11e8-80c2-7d6c877265ff.png">
<img width="531" alt="capture d ecran 2018-02-22 a 14 46 18" src="https://user-images.githubusercontent.com/3693028/36561054-9d64fe22-17e0-11e8-93ba-2120d8bdbfe1.png">

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Create an entity an create a relation OneToMany between the User object and this entity.
Add one or many entries of the entity just created.
Call the `/user/me` route or the `ctx.state.user` in a controller and you will see that the linked entity returns only the id of the last entry previously created instead of an array.

**What is the expected behavior?**
`/user/me` or `ctx.user.state` should return the same content than `/user/:id` (all the user object with all the related objects in arrays and not only the id of the last created entry).

**Fix proposal**
I've been investigate and in order to fix that quickly, I've changed the way you fetch the user infos in `/strapi-plugin-users-permissions/config/policies/permissions.js` on line 10.
I've replace this : 
`ctx.state.user = await strapi.query('user', 'users-permissions').findOne({ _id, id }, ['role']);`
By this : 
`ctx.state.user = await strapi.plugins['users-permissions'].services.user.fetch({ _id, id }, ['role']);`
Maybe there's a problem with the strapi.query.findOne function ?

**Comment by lauriejim** [comment]
In this case we force to populate just `role` relation. If we inspect findOne query of mongoose https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/queries/mongoose.js#L19 we can see, if we remove `['role']` as second argument, the query with populate with all relation.

So you can remove `['role']` and it will works. 
Can you make this change and submit a pull request please.

**Comment by EricVanDerDijs** [comment]
Hi! I have rencently read that ctx.state.user no longer populates data, therefor **/users/me** no longer brings all the other user's related data, is this the intended behavior?

**Comment by derrickmehaffy** [comment]
> Hi! I have rencently read that ctx.state.user no longer populates data, therefor **/users/me** doesn't bring all the other user's related data, is this the intended behavior?

It is intended yes, you will need to use extensions to override this @EricVanDerDijs 

Locking this issue as it's quite old.
