### ISSUE TITLE
ManyToOne relations are considered as OneToOne in Content Type Builder

### ISSUE THREAD

**Issue by TheWebsDoor** [strapi/strapi#690]
**Node.js version**:
8.9.3
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
MacOS 10.13.3

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Hi (it's me again),
I've found another critical issue... In the Content Type Builder, when I edit my relations on the interface of Strapi all the ManyToOne relations are considered as OneToOne relations. The problem is that when we edit informations on the entity, ManyToOne relation will be changed into a OneToOne (because the wrong relation is selected).

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Create a Test entity and create a relation ManyToOne with User entity (User can have many Tests) : 
![capture d ecran 2018-02-22 a 16 25 24](https://user-images.githubusercontent.com/3693028/36565071-5da006e4-17ed-11e8-972b-8e1850af576b.png)
Click on Save and refresh the page. You should see that the ManyToOne relation has become a OneToOne relation : 
![capture d ecran 2018-02-22 a 16 25 40](https://user-images.githubusercontent.com/3693028/36565155-9f011c0e-17ed-11e8-9cd7-fcf0eab1b3f3.png)
It's just a display bug. When I check my json files, all is ok and when I try to add or edit entries in the Content Manager, all is ok. **But this display bug will change the relation if we save again our model and that's the problem.**

**What I figured out**
When I go to my entities JSON files, I see that in a OneToMany, the attribute will be a collection. On the other side, the ManyToOne relation will be a simple model (which is the expected behaviour).
But the problem is when the platform parse the JSON files, on the OneToMany side it will see that it's a collection and check the nature of the relation on the other side and see that it's a simple model. So it deduce that it's a OneToMany relation and it's ok.
But in the other way, it doesn't work. When it parses the ManyToOne relation, it sees only a simple model. It didn't check on the other side if it's a collection. It will deduce that it's a OneToOne relation and selects the wrong relation in the view.
**When we go back on the edition of the entity, if we don't check the broken relation, the ManyToOne will be turned into a OneToOne.**

**What is the expected behavior?**
Because the relations are bidirectional, when a OneToMany relation is created, it automatically creates the ManyToOne relation on the other entity. Relations have to remain the same. Otherwise, if we don't pay attention to re-edit relation in order to pass them into ManyToOne, all of these relations will be changed to OneToOne.

**Comment by lauriejim** [comment]
@TheWebsDoor Thank you for this issue.
To give you more info about this issue. This case happen just where a relation is made with a plugin model (User of Users and Permission in this case). It will works fine with api relations

**Comment by TheWebsDoor** [comment]
Hello @lauriejim :)
You right, I didn't check but it seems to work when object have no relation with User indeed.
Good catch !

**Comment by lauriejim** [comment]
After pulling `master` I tried to reproduce the issue but it works fine. I think @Aurelsicoko fixed it working on polymorphic relations

**Comment by TheWebsDoor** [comment]
That's right, it's working like a charm now :) You can close the issue 😉
