### ISSUE TITLE
Sentry middleware is not catching the error when throwing an error in custom controllers

### ISSUE THREAD

**Issue by abumalick** [strapi/strapi#6901]
**Describe the bug**

Sentry middleware is not catching the error when throwing an error in custom controllers. I followed official documentation to configure the sentry middleware: https://strapi.io/documentation/v3.x/guides/error-catching.html#handle-errors

**Steps to reproduce the behavior**

I made a  reproduction repository here: https://github.com/abumalick/strapi-sentry-error

1. Bootstrap a new strapi app
2. Implement the strapi middleware:  https://github.com/abumalick/strapi-sentry-error/commit/6fabf20ffdf4c1185db20764c6648a40f9671f9b
3. Add a custom controller to test the error handling: https://github.com/abumalick/strapi-sentry-error/commit/f296ec050bd0a744498fbc7a4a7137a179c3a673
4. Call the endpoint to trigger the error ( http://localhost:1337/test-error )

**Expected behavior**
In sentry middleware `await next();` should throw and the catch block should be executed to send the error to sentry.

**Current behavior**
In sentry middleware the catch block is never executed

**Screenshots**

**Code snippets**
```js
const Sentry = require("@sentry/node");
console.log("INITIALIZING SENTRY");
Sentry.init({
  dsn:
    "https://77ac1ecb19d4446cafa3f1590221db6b@o415410.ingest.sentry.io/5306847",
  environment: strapi.config.environment,
});

module.exports = (strapi) => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        try {
          console.log("Waiting for next");
          await next();
          console.log("NEXT passed");
        } catch (error) {
          console.log("SENDING EXCEPTION TO SENTRY");
          Sentry.captureException(error);
          throw error;
        }
      });
    },
  };
};
```

**Output in console**
```
yarn develop                                                                                                                             ░▒▓ INT х 
yarn run v1.22.4
$ strapi develop
INITIALIZING SENTRY

 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Fri Jul 03 2020 10:30:47 GMT+0100 (GMT+01:00)    │
│ Launched in        │ 669 ms                                           │
│ Environment        │ development                                      │
│ Process PID        │ 60374                                            │
│ Version            │ 3.0.5 (node v14.5.0)                             │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available                                                            

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

Waiting for next
[2020-07-03T09:31:01.114Z] error Error: This error should be sent to sentry
    at Object.index (/path/to/my/project/api/test-error/controllers/test-error.js:9:11)
    at dispatch (/path/to/my/project/node_modules/koa-compose/index.js:44:32)
    at next (/path/to/my/project/node_modules/koa-compose/index.js:45:18)
    at dispatch (/path/to/my/project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at /path/to/my/project/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:28
    at dispatch (/path/to/my/project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at /path/to/my/project/node_modules/strapi-utils/lib/policy.js:52:11
    at dispatch (/path/to/my/project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at /path/to/my/project/node_modules/strapi/node_modules/koa-compose/index.js:34:12
    at dispatch (/path/to/my/project/node_modules/koa-compose/index.js:44:32)
    at next (/path/to/my/project/node_modules/koa-compose/index.js:45:18)
    at /path/to/my/project/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/path/to/my/project/node_modules/koa-compose/index.js:44:32)
    at next (/path/to/my/project/node_modules/koa-compose/index.js:45:18)
    at serve (/path/to/my/project/node_modules/koa-static/index.js:59:11)
    at dispatch (/path/to/my/project/node_modules/koa-compose/index.js:44:32)
[2020-07-03T09:31:01.122Z] debug GET /test-error (15 ms) 500
NEXT passed

```

**System**

- Node.js version: v14.5.0
- NPM version: 6.14.5
- Strapi version: strapi@3.0.5
- Database: default
- Operating system: macOS

**Additional context**
Nothing

**Comment by derrickmehaffy** [comment]
The middleware isn't triggered because the controller doesn't return anything, meaning it doesn't work back up the call tree. Try adding a `return { okay: false }` to the controller

**Comment by abumalick** [comment]
@derrickmehaffy If I add a return statement after throwing an error the return statement will never get triggered.
```js
module.exports = {
  index: async (ctx, next) => {
    throw new Error("This error should be sent to sentry");
    return { okay: false }
  },
};
```

**Comment by XuluWarrior** [comment]
@abumalick You may be experiencing the same issue I had #6863

**Comment by abumalick** [comment]
Yes it seems related. Maybe it is happening because of boom, I don't know. 

The official documentation is not working with controllers as we can see in the reproduction repository that I posted.

**Comment by XuluWarrior** [comment]
I just took a look at your repo and loading `boom` before `sentry` allows `sentry` to catch exceptions in your controller.
Checkout my PR - https://github.com/abumalick/strapi-sentry-error/pull/1

**Comment by abumalick** [comment]
Good work finding out that fix. Maybe we should update official documentation with your change.

**Comment by raphaelsoul** [comment]
step into same problem following official docs🤣

**Comment by lauriejim** [comment]
Hello! The guide says:
```
It's important to call throw(error); 
```

In your code you are not using `throw(error);` but `throw new Error("This error should be sent to sentry");`

If you call the correct function like this `throw("This error should be sent to sentry");` it will work.

**Comment by XuluWarrior** [comment]
@lauriejim Did you try raising a string exception?
Yes, in the example given the `sentry` middleware will receive an error.  But only because the `boom` middleware raises an `assert` error due to a string being thrown rather than an `Error`

```
  AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at new AssertionError (internal/assert.js:269:11)
      at Object.exports.assert (/Development/strapi-sentry-error/node_modules/hoek/lib/index.js:559:11)
      at Function.boomify (/Development/strapi-sentry-error/node_modules/boom/lib/index.js:107:14)
      at formatBoomPayload (/Development/strapi-sentry-error/node_modules/strapi/lib/middlewares/boom/index.js:47:22)
      at strapi.app.use (/Development/strapi-sentry-error/node_modules/strapi/lib/middlewares/boom/index.js:84:36)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have created a branch which demonstrates using your proposed code
https://github.com/XuluWarrior/strapi-sentry-error/tree/string-error
