### ISSUE TITLE
Swagger Generate Components Name wrong

### ISSUE THREAD

**Issue by Marcosul** [strapi/strapi#6905]
hello,

Look screenshot. All components name are same first components in Swagger. Only Swagger.

![image](https://user-images.githubusercontent.com/4714018/86476327-ae58a380-bd1c-11ea-9cb8-0b923eb1eff3.png)

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
