### ISSUE TITLE
setting a fallback for 'uri' in server.js results in that fallback being baked into javascript

### ISSUE THREAD

**Issue by matschundbrei** [strapi/strapi#6907]
We noticed a strange behaviour on the current release. (3.0.5).

We are running a small instance in AWS ECS and we like to configure the url according to the environment the container is being launched in.

So I have set the url config in the latest version to:
`url: env('APP_URL', 'http://localhost:1337')`

when visiting the admin endpoint on our instance, we just saw a spinner and looked in several points, but then we noticed that the interface was trying to do a request to http://localhost:1337/users-permissions/init.

We were searching for a while until I set the fallback value for env() to http://weirdhost:1337 and we thus confirmed, that the fallback value was used, despite the fact, that we were setting APP_URL in the environment to the external address.

We also confirmed, that the container we were using had the fallback value baked into `build/main.2d146793.chunk.js`, which clearly is not intended.
```shell
bash-5.0# grep -l -r 'weirdhost' *
build/main.2d146793.chunk.js
config/server.js
```
### reproduce
Use the 'strapi/base:10-alpine' image to build a strapiapp in which you have set the url config parameter with a fallback.

**Expected behavior**
settings in config/server.js should be honored on both `yarn build` and `yarn start`

**System**

- Node.js version: v10.21.0
- NPM version: 6.14.4
- Strapi version: 3.0.5
- Database: postgresql
- Operating system: alpine

### Workaround
The workaround is to neither set the variable you want to use for url via the environment nor use a fallback, in our case:
`url: env('APP_URL')`

**Comment by derrickmehaffy** [comment]
`do not use this configuration parameter in static files generated within the app` That won't be possible, due to how the build happens, Strapi's Admin uses react, and it serves the "built" react static files. So this host needs to be set when you build. React is a client side rendered framework, so that URL is what tells it where to send requests.

**Comment by matschundbrei** [comment]
@derrickmehaffy:
My claim is, that if I can set parameter on runtime, it does not make sense to include that parameter on buildtime, it should be included only on runtime.

If there' s a need to have this parameter built into static-files, then it should be done on `yarn start`  after the container boots and not when the container is build.

Maybe my wording wasn' t exactly perfect to begin with, so I tried to be more clear in the latest edit.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy:
> My claim is, that if I can set parameter on runtime, it does not make sense to include that parameter on buildtime, it should be included only on runtime.
> 
> If there' s a need to have this parameter built into static-files, then it should be done on `yarn start`  after the container boots and not when the container is build.
> 
> Maybe my wording wasn' t exactly perfect to begin with, so I tried to be more clear in the latest edit.

I think your missing the point that the Strapi backend doesn't -have- to actually serve the admin, it could be prebuilt and served statically by the upstream proxy while your backend is scaled to meet demand without worrying about the admin.

Generally speaking you would define this in a .env so you don't have to declare it on the CLI either during build nor run time, but if it's not in the .env you will have to declare it on both. This won't change, I am 100% sure on that.

**Comment by matschundbrei** [comment]
> I think your missing the point that the Strapi backend doesn't -have- to actually serve the admin, it could be prebuilt and served statically by the upstream proxy while your backend is scaled to meet demand without worrying about the admin.

I don't think that I am missing this point and at no point in this discussion do I ever argue that this specific functionality should be altered.

> Generally speaking you would define this in a .env so you don't have to declare it on the CLI either during build nor run time, but if it's not in the .env you will have to declare it on both. This won't change, I am 100% sure on that.

This also was never argued and/or asked by me.

> To clarify not everyone is using docker, and nothing in Strapi is specifically built for docker, it's built to be used by any platform, and if docker needs something specific, then it's up to the user to handle that.

Again, this is fully understood and completely fine with me.

I do understand the differences in CSR and SSR and I would really appreciate if you stop explaining to me how they differ. 

With that being said, I would really appreciate if you could accept, that the behaviour of strapi's env() is confusing to users in **this particular instance**.

A fix to this does not necessarily need to be in the code. It would be completely ok to point out that this behaviour is special to the `uri` in `server.js` parameter (as it for example differs from everything set in `database.js`) in the documentation and this 4 hour long debugging run for two people would have never happened.

Maybe I am still not being clear enough:

The thing that was confusing to us is: while 99% of all .env/env variables are honored on `yarn start`, this one particular instance (`url`) is only honored when not previously set during `yarn build` and even this is not true for the whole application, only for **this particular instance**, where `url` is written to a static-file upon build time.

All you (@derrickmehaffy) have done so far is argued that I am to unexpierienced/stupid to understand why that is the case and I am telling you, this is not only condescending, it is also not true.

**Comment by derrickmehaffy** [comment]
> The thing that was confusing to us is: while 99% of all .env/env variables are honored on yarn start, this one particular instance (url) is only honored when not previously set during yarn build and even this is not true for the whole application, only for this particular instance, where url is written to a static-file upon build time.

- `yarn develop` => If there is no build folder, build with whatever environment is specified, if none then development
- `yarn start` => Run the application as is, if there is no build folder, it runs without it and thus no admin interface

When doing a `yarn start` it does not rebuild the admin, you need to build the admin with `yarn build`. When Strapi is running, it will only serve the static files for the admin from the build and thus the URI for the backend has to be compiled into the static files as the admin is CSR.

This is intended, as yes that variable is used in other places such as with upload, email, and auth providers. But in the case of the admin, it has to be specified when the admin is built.

I'm marking this issue as closed, as the current usecase is the intended usecase.
