### ISSUE TITLE
Email confirmation send wrong auth link

### ISSUE THREAD

**Issue by HonzaVrkota** [strapi/strapi#6909]
**Describe the bug**
When new user register, user receive email with link for confirmation of the account. 
But the link is sent without url and looks like this: _/auth/email-confirmation?confirmation=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNTkzODA2MjMzLCJleHAiOjE1OTYzOTgyMzN9.U3V_bVVnE7UnMq_8RNs_rdW7-uQmIStdBqNvDyEeReo_

**Steps to reproduce the behavior**

1. Go to your strapi dashboard
2. Roles & Permissions
3. Advanced Settings tab
4. Set Enable email confirmation to "ON"
6. Register a user via your frontend app
7. Receive unclickable link without the url of strapi
8. Try the link in brower with added url - works!

**Expected behavior**
In previous version was sent confirmation link with complete link: _http://localhost:1337/auth/email-confirmation?confirmation=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNTkzODA2MjMzLCJleHAiOjE1OTYzOTgyMzN9.U3V_bVVnE7UnMq_8RNs_rdW7-uQmIStdBqNvDyEeReo_ 

**System**

- Node.js version: `v12.16.3`
- NPM version: `16.14.3`
- Strapi version: `3.0.1`
- Database: `sqlite`
- Operating system: `Windows 10`

**Additional context**
I tried to console log `strapi.config.server.url` - this is set in `settings.message` url. It console log `undefined`

**Comment by derrickmehaffy** [comment]
Do you have the url setting set in the `config/server.js` ?

**Comment by HonzaVrkota** [comment]
```
// config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
});
```

**Comment by derrickmehaffy** [comment]
That would be your problem: https://strapi.io/documentation/v3.x/concepts/configurations.html#server

The `url` setting is what tells the rest of the Strapi application what your "public" URL is.

**Comment by derrickmehaffy** [comment]
@petersg83 @alexandrebodin can you confirm it's intended to have no prefix before the path, I think a lot of the confusing is that it doesn't automatically prefix with `http://${host}:${port}`

**Comment by HonzaVrkota** [comment]
Yes now it works.
I think in the docs can be specified also the url with vars host and port. I didnt notice the url param in the table under the example.
http://${host}:${port}
```
// config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: `http://localhost:1337`,
});
```

**Comment by petersg83** [comment]
For now, there is no prefix but soon it will take by default (if `url` doesn't exist) `http://${host}:${port}` :)

**Comment by coderdix** [comment]
I'm getting a 
REGISTRATION ERROR:  TypeError [ERR_INVALID_URL]: Invalid URL: /auth/email-confirmation 

My request is also responding with a 400 error "Email already taken"

I have email confirmation setting on and some custom fields in my registration. Am I missing something? I've spent a couple days on this now and read through various issue threads - I'm stumped 

server js is 
`module.exports = ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  url: "http://localhost:1337",
});
`

registration is 
`onSubmit={async (values, { setSubmitting }) => {
              const registrationUrl = `${process.env.STRAPI}/auth/local/register`;
              const confirmationUrl = `${process.env.STRAPI}/auth/send-email-confirmation`;

              const data = {
                username: values.username,
                role: values.role,
                firstName: values.firstName,
                lastName: values.lastName,
                email: values.email,
                phone: values.phone,
                password: values.password,
              };

              try {
                await axios.post(registrationUrl, data);
              } catch (error) {
                console.log("wtf", error);
                setError({
                  isError: true,
                  msg: error.response.data.messsage[0].messages[0].message,
                });
                setSubmitting(false);
              }

              try {
                await axios.post(confirmationUrl, { email: data.email });

                router.push("/thank-you");
              } catch (error) {
                setError({
                  isError: true,
                  msg: error.response.data.message,
                });
                setSubmitting(false);
              }
            }}`

**Comment by akhilmhdh** [comment]
@coderdix are u using sendmail. If its sendmail then i dont think it will work in local host. Use sendgrid.

**Comment by coderdix** [comment]
Using sendgrid :-) 

My other email areas work (forgot & reset password, as well as, the newsletter (marketing contacts) submissions to sendgrid. 

Does the code look good?

**Comment by coderdix** [comment]
@akhilmhdh hey there! Any insights?

**Comment by akhilmhdh** [comment]
@coderdix hey there. Wait a sec which strapi version are you using.

**Comment by coderdix** [comment]
@akhilmhdh  Thanks for your reply - no problem :-) I'm using version: 3.0.5

**Comment by akhilmhdh** [comment]
damn couldn't find any issues. Well are u having any required as the custom fields. Can u try removing that as required and checked it.

**Comment by coderdix** [comment]
I did (from when the initial comment was made) - but after reading through some other threads I removed the required values and it was still giving an error. 

... trying again now however....

Get the follow errors from browser > [dev. tools] > network > xhr: 
![Screen Shot 2020-07-12 at 2 52 19 PM](https://user-images.githubusercontent.com/8751224/87255320-7e617c80-c44f-11ea-9762-7b51c72c3d9b.png)

And this error from the server log:
![Screen Shot 2020-07-12 at 2 52 42 PM](https://user-images.githubusercontent.com/8751224/87255321-7efa1300-c44f-11ea-8ad8-08995c0df71c.png)

**Comment by akhilmhdh** [comment]
@coderdix Ohhh man. I totally misunderstood. Ok so the issue is your workflow. Here by attaching a prev issue. Read through it. It clearly explains the workflow. (Apologies again for late msg)
"https://github.com/strapi/strapi/issues/4700"

**Comment by petersg83** [comment]
Hi,
I updated the doc (not online yet) in this PR : https://github.com/strapi/strapi/pull/7054.
Please tell me if it's clearer for you :)

**Comment by coderdix** [comment]
Sorry guys I got sick :-( 
reading through now - thanks for all your help

**Comment by coderdix** [comment]
@akhilmhdh so i read through everything I still feel like I'm totally lost and getting the same error. is the email suppose to send automatically without making an explicit request on the front end? Here's my submit code now

` onSubmit={async (values) => {
              try {
                await axios.post(`${strapi}/auth/local/register`, {
                  username: values.username,
                  role: values.role,
                  firstName: values.firstName,
                  lastName: values.lastName,
                  email: values.email,
                  phone: values.phone,
                  password: values.password,
                });
              } catch (error) {
                console.log("registration didnt work");
                setError({
                  isError: true,
                  msg: error.response.data.messsage[0].messages[0].message,
                });
              }
            }}`

**Comment by akhilmhdh** [comment]
@coderdix ok so if you have enabled confirmation required in settings. The confirmation mail is send automatically to the email. The confirmation mail will have a code and link to strapi to confirm it and you need to set a redirect url after confirmation in settings. Thus after confirmation user is sent to a confirmed screen. You dont need to sent email to it.

**Comment by coderdix** [comment]
@akhilmhdh that's what i thought but i'm still getting 400 error even with just the simple post req. 
REGISTRATION ERROR:  TypeError [ERR_INVALID_URL]: Invalid URL: /auth/email-confirmation

**Comment by akhilmhdh** [comment]
@coderdix beacause you dont need to apply a post request over there.

**Comment by coderdix** [comment]
I now only have the single one to register not the email confirm.

**Comment by akhilmhdh** [comment]
So now did you check the db has the email or not already registered while testing in prev states

**Comment by akhilmhdh** [comment]
@coderdix now then try to redo it by setting the confirmation url off state. If its working fine now. Meaning user gets authenticated and res is 200 with db creation it means ur sendgrid which u said is your configured one is not properly setuped.

**Comment by coderdix** [comment]
K had to run out but will do when get back. All the other emails in the system are working fine though with sendgrid

**Comment by akhilmhdh** [comment]
ohhhh...well then that's weird i would say. Anyways check it out also update to latest version if possible.

**Comment by coderdix** [comment]
@akhilmhdh so i updated to the latest version 3.1.3 & registration worked with a 200 code without the email confirmation. However with it, right back to the same error.

**Comment by coderdix** [comment]
Oh got it working for anyone else who had the issue by updating to 
URL: `${getAbsoluteServerUrl(strapi.config)}/auth/email-confirmation` 

I had to modify my Auth file and it still had the old: 
 URL: new URL("/auth/email-confirmation", strapi.config.url).toString()
