### ISSUE TITLE
Content Type: JSON field

### ISSUE THREAD

**Issue by Caryyon** [strapi/strapi#691]
**Node.js version**: v8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.10.2

**Operating system**: 10.13.3 (17D47)

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** When add a JSON field to a custom content type it appears to simply add a string field

**If the current behavior is a bug, please provide the steps to reproduce the problem** Create a content type and then add the json field and hit save. Then go to your new content type and create a new item of that type. Then add some JSON and hit save. Call or load that endpoint's data and you will see the JSON field returning as a string.

**What is the expected behavior?** Add JSON in a field and when called it responds accordingly to it's type.

**Comment by lauriejim** [comment]
I close this issue, please follow this issue https://github.com/strapi/strapi/issues/496
