### ISSUE TITLE
Put the SQLite database file is in folder not named .tmp

### ISSUE THREAD

**Issue by dimozaprianov** [strapi/strapi#6910]
**Describe the bug**
The SQLite database file lives in folder named .tmp. Probably .database or something like that will be more appropriate, as .tmp may lead you to believe you can delete the folder.

**System**

- Node.js version: 12.16.1
- NPM version: 6.14.4
- Strapi version: 3.0.5
- Database: SQLite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
You can change where it's stored in the `config/database.js` file.

Marking as closed.

**Comment by dimozaprianov** [comment]
I know it can be changed. The problem is with the default value, which is misleading. The folder is anything but temporary and I think the default name should reflect that. In my case I wanted to clean the cache after some error and I see a folder that is named .tmp. I know it wasn't very wise of me to delete something that I don't know what exactly is, but on the other hand it is called .tmp, right. I think it is an issue of polish.
