### ISSUE TITLE
Wrong flag is shown for swedish language.

### ISSUE THREAD

**Issue by tspvivek** [strapi/strapi#6912]
**Describe the bug**
When swedish language is enabled and selected, the flag shown in admin panel header is wrong. Its showing el-salvador's flag instead of sweden's flag. Seems like a confusion between language code and country code. Language code 'SV' is correct but country code should be 'SE' instead of 'SV'.

**Steps to reproduce the behavior**

1. Enable swedish language (sv)
2. Select the language in admin panel.
3. Flag shown will be wrong

**Expected behavior**

Path for image should be 
`https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/flags/4x3/se.svg`
Instead of
`https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/flags/4x3/sv.svg`

**Comment by vincentdoerig** [comment]
The issue here is that the localisation file for swedish is wrongly named. It should be `se.json` instead of [`sv.json`](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/sv.json). I can submit a PR if needed.

**Comment by soupette** [comment]
@vincentdoerig if you could submit a PR it would be great!

**Comment by tspvivek** [comment]
@vincentdoerig Thanks for the PR.
