### ISSUE TITLE
Status 500 Error message not clear for constraint validation

### ISSUE THREAD

**Issue by FreTimmerman** [strapi/strapi#6915]
related to #1175
**Informations**

- **Node.js version:**
 12.14.0
- **npm version:**
 6.13.4
- **Strapi version:**
 3.0.4
- **Database:**
SQlite (default)
- **Operating system:**
Linux version 3.10.105

**What is the current behavior?**
The returned error message isn't clear

**Steps to reproduce the problem**
Post an object that is already exist and the field that we insert duplicate data is "unique"
We get (returned response):

```
{
   "statusCode":500,
   "error":"Internal Server Error",
   "message":"An internal server error occurred"
}
```
Strapi console:
```
error Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: members.email 
debug POST /[path]/ (27 ms) 500 
```
**What is the expected behavior?**
To return a better message to know if the data is duplicated or if the server occurred a real error. 

**Suggested solutions**
Change the returned error messages, pass the SQlite error along

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/custom-error-handling/199/2

**Comment by jozefcipa** [comment]
I run into the same problem, trying to fix it here https://github.com/strapi/strapi/pull/8367
