### ISSUE TITLE
Delete images do not clear all sizes on AWS S3

### ISSUE THREAD

**Issue by Torone** [strapi/strapi#6931]
**Describe the bug**
I'm uploading images on AWS S3 using the plugin `strapi-provider-upload-aws-s3` version **3.0.5** and with the Strapi **Enable responsive friendly upload** `on`.

It is uploading correctly the images into my Bucket and it save, for each image, 4 files: original, small, medium and large version. Good!

When I delete the files: `DELETE` `/upload/files/:id` it removes only the "generated" ones but not the original.
So after I delete one image, on my bucket I don't see anymore the small, medium and large, but I keep seeing the original file.

**Steps to reproduce the behavior**

1. Enable the Strapi feature: `Enable responsive friendly upload`;
1. Upload images on your AWS S3 Bucket;
2. Delete one of your images;
3. You should see one image not deleted.

**Expected behavior**
It should clear all images

**Code snippets**
Upload:
``` Javascript
// The payload is FormData
this.$axios.$post('/upload', payload, {
        headers: {
                'content-type': 'multipart/form-data'
        }
}
```

Delete:
``` Javascript
this.$axios.$delete(`/upload/files/${id}`)
```

**System**

- Node.js version: 12.16.1
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: MongoDB
- Operating system: Mac OS Mojave 10.14.6

**Additional context**
It would be nice to know if I'm doing something wrong or if it is a bug. Thanks!

**Comment by lauriejim** [comment]
Hello! I just tried with the latest version of Strapi `3.1.3` and everything is working well.
Can you please upgrade your project and see if it works.
I will close since it's working on the latest version.
I will open it again if the upgrade doesn't fix your stuff.

**Comment by ScottEAdams** [comment]
@lauriejim I am seeing this on 3.1.4 for the original file on a custom path and I have a feeling it may be related to the issue I posted not long ago where path isnt saved for original file #7742

**Comment by ScottEAdams** [comment]
Just to be clear, the thumbnail IS deleted but not the original.

**Comment by derrickmehaffy** [comment]
@ScottEAdams can you please create a new issue for this and just reference this one per our Contributor guide: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
