### ISSUE TITLE
Add authSource & ssl options to MongoDB connector

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#694]
**Node.js version**: v8.9.1
**npm version**: v5.6.0
**Strapi version**: v3.0.0-alpha.10.2
**Operating system**: macOS

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

I can't connect to MongoDB.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

I need to send some params to the MongoDB connection, if not it fails in the `strapi new project`.

* In the MongoDB URL: `?authSource=admin&ssl=true`
* In the MongoDB CLI: `--ssl --sslAllowInvalidCertificates --authenticationDatabase admin`

**What is the expected behavior?**

I should able to connect to MongoDB.

Thanks in advance!

**Comment by abdonrd** [comment]
Meanwhile, I was able to connect using the `uri` field:

```
"uri": "mongodb://username:password@host:port/database?authSource=admin&ssl=true"
```

**Comment by lauriejim** [comment]
Hello @abdonrd thank you for this issue.
Bug ? yes and no, it's actually not implemented in Strapi.

If you want to help us on this point.
You can investigate on how work the database form here https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/before.js#L63
and how we test the database connection for mongoose here https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/utils/connectivity.js

**Comment by lauriejim** [comment]
Hey @abdonrd ! @mtringuyen make some update to get ssl option, maybe you can help him for this PR and add authoSource https://github.com/strapi/strapi/pull/738

**Comment by abdonrd** [comment]
@lauriejim done at #753! :)
