### ISSUE TITLE
Having a config/plugins.js~ within the config directory has strange side effect 

### ISSUE THREAD

**Issue by hauben** [strapi/strapi#6943]
Having a joe's backup file config/plugins.js~ within the config directory has the side effect that a correct plugins.js within the same directory does not get loaded at all.

**Steps to reproduce the behavior**

1. Create a strapi project from the scratch
2. Define i.e. a sendgrid plugin description within config/plugins.js
3. cp config/plugins.js config/plugins.js~
4. npx strapi console
5. strapi.plugins['email'].config
6. you will see something like that 
```
{
 functions: { bootstrap: [AsyncFunction] { __filename__: 'bootstrap.js' } },
 routes: [
  {
   method: 'POST',
   path: '/',
   handler: 'Email.send',
   config: [Object]
  }
 ],
 __filename__: 'settings.js',
 provider: 'sendmail',
 providerOptions: {},
 settings: { defaultFrom: 'Strapi <no-reply@strapi.io>' }
```

**Expected behavior**
the console log should show the correct loaded sendgrid configuration and simply having a config/plugins.js~ should not affect the plugins.js loading process 
```
{
  functions: { bootstrap: [AsyncFunction] { __filename__: 'bootstrap.js' } },
  routes: [
    {
      method: 'POST',
      path: '/',
      handler: 'Email.send',
      config: [Object]
    }
  ],
  __filename__: 'settings.js',
  provider: 'sendgrid',
  providerOptions: {
    apiKey: 'apikey'
  },
  settings: {
    defaultFrom: 'email',
    defaultReplyTo: 'email'
  }
}
```

**System**

- Node.js version:  12.16.3
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: MongoDB 4.2.6
- Operating system: Linux Ubuntu

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
That's weird because we are using `(js|json)` in the regexp to load files so 🤔 
Ping @alexandrebodin

**Comment by alexandrebodin** [comment]
hum maybe the char is removed with somehow in the parsing phase. Will have a look

**Comment by alexandrebodin** [comment]
Ok so path.extname('plugins.js~') is equal to path.extname('plugins.js'). this means we parse both files to the same plugins key and the ~ is overridding the main one.

**Comment by derrickmehaffy** [comment]
Should have been fixed in v4 via https://github.com/strapi/strapi/pull/13336
