### ISSUE TITLE
new generator Unexpected token ...

### ISSUE THREAD

**Issue by koljakutschera** [strapi/strapi#695]
**Node.js version**:
v8.1.2
**npm version**:
maybe 5.6.0

**Strapi version**:
3.0.0-alpha.10.2

**Operating system**:
OSX

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Invalid `new` generator.
/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:125 ...databaseChoice.value
Unexpected token ...

**If the current behavior is a bug, please provide the steps to reproduce the problem**
strapi new my-project

**What is the expected behavior?**
Should create new project

** Solution
Generator works after updating node to: v8.9.4 but not with v8.1.2. In docs you say: Node.js >= 8... see https://strapi.io/documentation/getting-started/installation.html and https://strapi.io/getting-started ...

Thx for strapi!

**Comment by lauriejim** [comment]
Please use node 9

**Comment by lauriejim** [comment]
I have updated the website and the documentation. Thank you for this issue.
