### ISSUE TITLE
Possible mistake about database file name in the docs (version 3.x)

### ISSUE THREAD

**Issue by umutbozdag** [strapi/strapi#6954]
**Describe the bug**
In [this](https://strapi.io/documentation/v3.x/guides/databases.html#mongodb-installation) page, in the step 5 there is a mistake about database file name and i am confused about that when reading it. Isn't it should be **database.js** instead of **database.json**?

**Steps to reproduce the behavior**
1. Go to [this](https://strapi.io/documentation/v3.x/guides/databases.html#mongodb-installation) link
2. Go to the step 5 in that page
3. You will see that there is a mistake about database.js file name (it's database.json) in both **description** and **note** section.

**Comment by derrickmehaffy** [comment]
That is correct, can you make a pull request?

**Comment by umutbozdag** [comment]
> That is correct, can you make a pull request?

Yeah i can do that.
