### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by NegativeIQ** [strapi/strapi#6960]
If strapi cannot connect to database it does not show error and npm say it failed to start.

1. Install strapi with mysql database (i think it will work with any other database except with sqlite - maybe even with it if you remove read/write privileges)
2. After you installed strapi and created admin account, shut it down.
3. Try to start strapi, in my case i used `npm run develop`
4. Strapi will fail to start, npm will say to check log and that its probably npm's fault. (and its not npm's fault)

**Expected behavior**
Show error in console and hang or gracefully shut down (best way would be to show error and wait for any key before shutting down).

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.5 (at least that's in package.json)
- Database: MariaDB 10.4.10 (from WAMP package)
- Operating system: Windows 7 Ultimate SP1 x64 

**Additional context**
Probably not exactly a bug, but i think it is important enough to report connection error since it may be a pain to notice real issue (specially if you are transferring to another machine).

**Comment by NegativeIQ** [comment]
Sorry for not clarifying problem a bit more. After double checking, indeed, strapi does show error in log, but it is kind of buried in the log. If your sql server is down, you have wrong credentials or server just refuses connection, strapi will return error, and then fail to start. Last thing you see on screen is NPM error:

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moviex@0.1.0 start: `strapi start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the moviex@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.`

And that can make life painful since database connection error is not error in code itself. It should be visible when starting strapi. Like i said in my first post, it should be visible in console (not 10-20 lines above), or at least gracefully shutdown so that npm does not report it as ERROR (since its not code error). Best solution would be to show error and freeze app until user presses any key.

**Comment by derrickmehaffy** [comment]
@petersg83 I believe Knex/Bookshelf provide support for relaying database errors back to the user, not sure on mongoose but is this something we could possibly add?

**Comment by lauriejim** [comment]
Hello!
I just tested each error case and here are the error messages I have.
I used a PG database here.
And messages are pretty clear I think.

If I'm using the wrong password:
```
$ strapi develop
[2020-08-18T08:24:18.641Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-18T08:24:18.642Z] error error: password authentication failed for user "strapi"
```

If I'm using the wrong username:
```
$ strapi develop
[2020-08-18T08:25:02.645Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-18T08:25:02.645Z] error error: password authentication failed for user "straapi"
```

If I'm using a database name that doesn't exist:
```
$ strapi develop
[2020-08-18T08:25:40.855Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-18T08:25:40.856Z] error error: database "strapia" does not exist
```

Ans finally the wrong port (so the same as if the database is not running ):
```
$ strapi develop
[2020-08-18T08:26:20.878Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-18T08:26:20.879Z] error Error: connect ECONNREFUSED 127.0.0.1:5431
```

**Comment by derrickmehaffy** [comment]
I just tested on MariaDB and MySQL and I get the same @lauriejim so it looks like those log relays were already implemented, @NegativeIQ can you try testing with a fresh project? It's possible in this case it was just hitting a code error.

**Comment by NegativeIQ** [comment]
Ok i just got some time and i can actually see database error.

**Comment by Gherciu** [comment]
@NegativeIQ @lauriejim @derrickmehaffy @albatrocity @thomaspockrandt  Did you resolved that? I'm getting the same errors even with never versions of strapi it happens only in prod mod
