### ISSUE TITLE
Required validation return error 500

### ISSUE THREAD

**Issue by Torone** [strapi/strapi#6964]
**Describe the bug**
I created a Content Type with a few properties, after a few days of testing creating new records I decided to add one more required property to the model.
Going back to the created control panel on the UI (not the Strapi admin panel, but the proper web application that consume Strapi endpoints), I tried to update the "item" with the new created property.
The result was error 500 saying the following: `ValidationError: product validation failed: durability: Path `durability` is required.`
Checking at the payload of the `PUT` request (that should be a `PATCH` by the way...) I can correctly see all the required information including the new created one.
Suddenly the API doesn't recognise it and trigger the validation error (That shouldn't be 500, but maybe a 400)

**Steps to reproduce the behavior**

1. Create a Content-Type with some properties
2. Save a few records using the new created Content-Type
3. Update the Content-Type with a new required property
4. Update one of the previously created records with the new property set
5. A Validation error with status 500 should trigger making the update request failing

**Expected behavior**
The record should be correctly updated including all the new created properties in the Content-Type

**System**

- Node.js version: 12.16.1
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: MongoDB
- Operating system: Mac OS Mojave 10.14.6

**Additional context**
I always consume the Strapi endpoints from the web application, I don't use to create/update my records using the Strapi control panel.
Sometimes doing operations through the Strapi Control Panel is fine, but this should be reflected when consuming the API.
So please, in order to test it, don't use the Strapi Control Panel. Thanks

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/6292

> This is a templated message
