### ISSUE TITLE
Public endpoint returns 403 during testing

### ISSUE THREAD

**Issue by sa-ma** [strapi/strapi#6980]
**Describe the bug**
I am trying to test an endpoint created with Strapi. When a request is made to a public endpoint it returns 403 as status instead of 200. The endpoint returns 200 as status if the app is running in the development environment but returns 403 as status in the test environment.

**Steps to reproduce the behavior**
1. Create a Content-Type
2. Set a Public role for the content type
3. Write a test for the endpoint

**Expected behavior**
The public endpoint should return 200 as status for a GET request.

**System**

- Node.js version: v12.18.0 
- NPM version: 6.14.4
- Strapi version: 3.0.5
- Database: sqlite
- Operating system: Ubuntu 20 (WSL)

**Comment by derrickmehaffy** [comment]
Are you sending a JWT in an authorization header to an endpoint that only has public permissions?

**Comment by sa-ma** [comment]
I am not. This is a snippet of the test
```
it('gets the list of all todos', (done) => {
  chai
    .request(app.server)
    .get('/todos')
    .end((error, response) => {
      expect(response.status).to.equal(200);
      done();
    })
});
```

**Comment by sa-ma** [comment]
I found the error, the Content-Type Builder adds a config property to the routes in the `routes.json` of the API removing it solved my problem.
It should be this:
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/heartbeats",
      "handler": "heartbeat.index"
    },
}
```
as opposed to this:
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/heartbeats",
      "handler": "heartbeat.index",
      "config": {
        "policies": []
      }
    },
}
```

**Comment by fredycampino** [comment]
Hi, i had the same problem, and solve by remove 
```
"config": {
        "policies": []
      }
```
I lost alot of time untill find this post, thansk @sa-ma,  still, i belive that it is a issue, the behavior is diferent  depending of env.
