### ISSUE TITLE
Getting intermittent issue with opening CMS admin page

### ISSUE THREAD

**Issue by pitstranslation** [strapi/strapi#6981]
Dear StrAPI CMS,

Sometimes CMS Admin login page wasn't loading and it only showing the progress loading gif .When I debug more I found the below URL showing 500 internal error.

Request URL: http://10.10.1.212:1340/content-type-builder/autoReload
Request Method: GET
Status Code: 500 Internal Server Error

Request URL: http://10.10.1.212:1340/users-permissions/init
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 10.10.1.212:1340
Referrer Policy: no-referrer-when-downgrade

This issue is happening intermittently and it will works after I restart the strAPI using the pm2 tool.Kindly let me know why we are come across this issue?
How we can solve this permanently.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
