### ISSUE TITLE
.env file is not respected #3558

### ISSUE THREAD

**Issue by ishan123456789** [strapi/strapi#6983]
**Describe the bug**
Related to https://github.com/strapi/strapi/issues/3558 the issue is locked so I had to create a separate bug. The .env still doesn't work automatically so either update the documentation to include 
```
const dotenv = require("dotenv");
dotenv.config();
```
in `config/functions/bootstrap.js`

**Steps to reproduce the behavior**

1. add a .env define any_variable=random
2. console.log(process.env.any_variable) logs undefined

**Expected behavior**
Should automatically include the .env or update the docs with that.

**System**

- Node.js version: 10.16.3
- NPM version: 6.13.7
- strapi: "3.0.0-beta.20.3",
- strapi-admin: "3.0.0-beta.20.3",
- strapi-connector-mongoose: "3.0.0-beta.20.3",

**Comment by derrickmehaffy** [comment]
>strapi: "3.0.0-beta.20.3"

The beta version is no longer supported and the stable will automatically load the .env, please update to the stable release.
