### ISSUE TITLE
I'm getting error while installing strapi locally with npx - Oh, it seems that you encountered errors while installing dependencies in your project

### ISSUE THREAD

**Issue by Alidhuniya** [strapi/strapi#6991]
# complete log:

C:\Users\alidhuniya>npx create-strapi-app strapidemo --quickstart
npx: installed 84 in 32.267s
Creating a new Strapi application at C:\Users\alidhuniya\strapidemo.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
info sharp Using cached C:\Users\alidhuniya\AppData\Roaming\npm-cache\_libvips\libvips-8.9.0-win32-x64.tar.gz
info sharp Creating C:\Users\alidhuniya\strapidemo\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\alidhuniya\strapidemo\node_modules\sharp\vendor\lib to C:\Users\alidhuniya\strapidemo\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=14.2.0 runtime=node arch=x64 libc= platform=win32)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\alidhuniya\\AppData\\Local\\Volta\\tools\\image\\node\\14.2.0\\node.exe" "C:\\Users\\alidhuniya\\AppData\\Local\\Volta\\tools\\image\\node\\14.2.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\alidhuniya\strapidemo\node_modules\sharp
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.2.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN strapi-connector-bookshelf@3.0.5 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.24.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alidhuniya\AppData\Roaming\npm-cache\_logs\2020-07-13T17_48_30_846Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd C:\Users\alidhuniya\strapidemo && npm install

# After typing npm install I'm getting error too below are logs:

alidhuniya@DESKTOP-1J9H7QP MINGW64 ~/Desktop/strapidemo
$ npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> sharp@0.24.1 install C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\alidhuniya\AppData\Roaming\npm-cache\_libvips\libvips-8.9.0-win32-x64.tar.gz
info sharp Creating C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp\vendor\lib to C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=14.2.0 runtime=node arch=x64 libc= platform=win32)

C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\alidhuniya\AppData\Local\Volta\tools\image\node\14.2.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\alidhuniya\\AppData\\Local\\Volta\\tools\\image\\node\\14.2.0\\node.exe" "C:\\Users\\alidhuniya\\AppData\\Local\\Volta\\tools\\image\\node\\14.2.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.2.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN strapi-connector-bookshelf@3.0.5 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.24.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`      
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alidhuniya\AppData\Roaming\npm-cache\_logs\2020-07-13T17_57_38_228Z-debug.log

**Comment by derrickmehaffy** [comment]
```
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
```

You don't have python installed, this isn't directly an issue with Strapi but with node-gyp/sharp which is used for building.

**Comment by derrickmehaffy** [comment]
> > ```
> > gyp ERR! find Python You need to install the latest version of Python.
> > gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> > ```
> > 
> > 
> > You don't have python installed, this isn't directly an issue with Strapi but with node-gyp/sharp which is used for building.
> 
> so I have to install python in order to run but nowhere in docs I have read, you need python to install strapi

Because it's not a requirement of Strapi, it's one of Sharp and Node-Gyp. The error you gave above clearly defines the error. On both Mac and Linux python is already included in standard build tools, I'm guessing that windows it's not, although I myself also test on all 3 platforms and never had issues.

As a side point based on the log you gave:

```
gyp ERR! cwd C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

You are also using a version of node that isn't currently supported. Node v14 doesn't go into LTS until October, please use the current LTS version v12

**Comment by Alidhuniya** [comment]
> > > ```
> > > gyp ERR! find Python You need to install the latest version of Python.
> > > gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> > > ```
> > > 
> > > 
> > > You don't have python installed, this isn't directly an issue with Strapi but with node-gyp/sharp which is used for building.
> > 
> > 
> > so I have to install python in order to run but nowhere in docs I have read, you need python to install strapi
> 
> Because it's not a requirement of Strapi, it's one of Sharp and Node-Gyp. The error you gave above clearly defines the error. On both Mac and Linux python is already included in standard build tools, I'm guessing that windows it's not, although I myself also test on all 3 platforms and never had issues.
> 
> As a side point based on the log you gave:
> 
> ```
> gyp ERR! cwd C:\Users\alidhuniya\Desktop\strapidemo\node_modules\sharp
> gyp ERR! node -v v14.2.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok
> ```
> 
> You are also using a version of node that isn't currently supported. Node v14 doesn't go into LTS until October, please use the current LTS version v12

Thanks for your reply and let me switch to the current LTS node version.

**Comment by derrickmehaffy** [comment]
Based on: https://www.npmjs.com/package/sharp

> Most modern macOS, Windows and Linux systems running Node.js v10+ do not require any additional install or runtime dependencies.

Meaning for some reason your Windows install does not have python or a substitute to work with sharp, thus the error is not directly a problem with Strapi, but is with Sharp.

**Comment by Alidhuniya** [comment]
> Based on: https://www.npmjs.com/package/sharp
> 
> > Most modern macOS, Windows and Linux systems running Node.js v10+ do not require any additional install or runtime dependencies.
> 
> Meaning for some reason your Windows install does not have python or a substitute to work with sharp, thus the error is not directly a problem with Strapi, but is with Sharp.

so what can I do to fix this problem? Do  I need to reinstall windows? I'm installing stapi again and installing dependencies stage going on. let's see what I will get this time

**Comment by derrickmehaffy** [comment]
First, I'd say start by install python and downgrading your node to the supported LTS version. Further issues though you should make an issue with Sharp.

**Comment by Alidhuniya** [comment]
> First, I'd say start by install python and downgrading your node to the supported LTS version. Further issues though you should make an issue with Sharp.
> 
> Strapi only uses sharp in the upload plugin to resize images, the actual install of sharp is something that should be handled automatically (sharp ships with precompiled binaries, meaning those binaries are not working on your system for some reason)

Problem solved. I got http://localhost:1337/admin/auth/register

**Comment by derrickmehaffy** [comment]
Glad to hear it :)

**Comment by alangeek** [comment]
@Alidhuniya how did you solve it, am i getting the same problem?

**Comment by Alidhuniya** [comment]
> @Alidhuniya how did you solve it, am i getting the same problem?

make sure you're using the node LTS version on your machine.

2. Why does your strapi installation fail?
In my case, it fails with a bunch of errors and I open a GitHub issue and strapi employee address this issue very well. Check this github issue post I'm getting an error while installing strapi locally with npx

Basically, check your nodeJS version on your system and make sure you're running node 12 which is the LTS version. I use volta.sh for managing and switching nodeJS version Switch back to node 12 and run the installation command again and you'll see it's working.

full article: https://dev.to/alidhuniya/how-i-build-a-school-website-with-strapi-cms-using-vanilla-js-2k57

**Comment by jonathanstanley** [comment]
for those on Apple Silicon M1, this issue was showing as first search result.  see resolution for apple m1 here:

https://github.com/strapi/strapi/issues/9121#issuecomment-760199811

**Comment by alexkess101** [comment]
I just had this same issue. The Apple Silicon M1 computers running Monterey come with python3 and python2 is required to node-gyp and sharp to compile. I downloaded python2 [here](https://www.python.org/downloads/release/python-2716/) and it started working

**Comment by BrianRuizy** [comment]
found solution from [Strapi forum](https://forum.strapi.io/t/strapi-does-not-run-on-mac-m1/15563). 

> Install NVM,
use NVM to install nodejs 14
Run strapi with nodejs 14.
Strapi works on my M1 like this

Follow this to install nvm (Mac) https://tecadmin.net/install-nvm-macos-with-homebrew/
