### ISSUE TITLE
Media Library - add multilanguage support for alternative text and caption

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#6994]
At the moment there is only one text field for alternative text and one for caption.
It would be great to have the possibility to add fields for other languages. Something like a component.
Something like an add button. Clicking will add 3 fields to the list of alternative and caption text: 

1. select language
2. alternative text
3. caption

**Comment by derrickmehaffy** [comment]
@pointout can you please edit this with the Feature Request template?

**Comment by derrickmehaffy** [comment]
Please see the following FR: https://portal.productboard.com/strapi/1-public-roadmap/c/19-content-internationalization-ce-ee-v4

**Comment by felixhagspiel** [comment]
@derrickmehaffy in the current strapi version (3.6.3) I see no option to translate the fields for the media uploads (alternative text, caption). Is there any plan to implement this? This is crucial for SEO

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy in the current strapi version (3.6.3) I see no option to translate the fields for the media uploads (alternative text, caption). Is there any plan to implement this? This is crucial for SEO

Currently no but I'll let @sam-pires confirm what the plans are for v4

**Comment by sam-pires** [comment]
Hello @felixdenoix,

There is a workaround. With the i18n feature you can localize the media fields in a CT. 
If you create one version of your asset for each locale, with translated metadata, you can then have the corresponding translated asset in each locale of your content.

We'll look into improving it later to avoid having to upload several times the same asset but not ETA for the moment.

**Comment by ferdynator** [comment]
Is there any update on this? The provided Link above does not work and there is currently still no option to add translations for these fields
