### ISSUE TITLE
Please maintain a SMTP email provider for better developer experience

### ISSUE THREAD

**Issue by roschaefer** [strapi/strapi#6998]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I can see that you maintain several proprietary email providers including
Mailgun, Sendgrid and Amazon:
https://github.com/strapi/strapi/tree/master/packages
 As a default, you use sendmail. I plead in favour of maintaining a SMTP capable email provider.

There are two main advantages:
* SMTP is better for data privacy and GDPR-compliance
* There is now a ton of unmaintained or outdated email providers for SMTP:
  https://www.npmjs.com/search?q=strapi-provider-email-
  Therefore it would improve the developer experience a lot to avoid this
  confusion.

It took me a whole day to get my head through all the version conflicts and I
have now sent a PR to a V3-compatible fork of `strapi-provider-email-nodemailer`:
https://github.com/Saunved/strapi-provider-email-nodemailer/pull/1

I have requested that the npm package with the most obvious name should merge
this v3-compatible fork and release a new major version:
https://github.com/yutikom/strapi-provider-email-nodemailer/issues/9

The ideal solution in my opinion is that the Strapi community maintains a
nodemailer provider out-of-the-box just as it does for the other proprietary
email-providers, already. You can see here, it's not too much code to maintain:
https://github.com/roschaefer/strapi-provider-email-nodemailer/blob/master/lib/index.js

The effort is small and the benefit would be to save a lot of people a lot of
headache.

Best,
Robert

**Comment by derrickmehaffy** [comment]
@Aurelsicoko thoughts? Do you think we should try and contact the maintainer of https://github.com/yutikom/strapi-provider-email-nodemailer & https://www.npmjs.com/package/strapi-provider-email-nodemailer and see if they would be interested in merging with the core mono-repo?

(I do support us naively offering an SMTP package)

**Comment by roschaefer** [comment]
Update: Together with @veitbjarsch and @saunved we updated `strapi-provider-email-nodemailer` here:
https://github.com/yutikom/strapi-provider-email-nodemailer/pull/14 and it has been released: https://github.com/yutikom/strapi-provider-email-nodemailer/releases/tag/v3.0.0

**Comment by bass3l** [comment]
Check this out as well: [https://www.npmjs.com/package/strapi-provider-email-smtp](https://www.npmjs.com/package/strapi-provider-email-smtp)

**Comment by derrickmehaffy** [comment]
Going to mark this as closed as the package has been picked up and is being maintained.

**Comment by roschaefer** [comment]
@derrickmehaffy that's good news! But I can't find it here: https://github.com/strapi/strapi/tree/master/packages could you show me what has changed?

**Comment by derrickmehaffy** [comment]
Sorry @roschaefer I meant to specify that as it is being maintained under https://github.com/yutikom/strapi-provider-email-nodemailer

Not that we have merged it into the core repo, though if the owners of that repo are willing to submit a PR I'm sure we could look at it again.

**Comment by roschaefer** [comment]
That was the whole point of this issue: I wanted to ask Strapi to maintain (aka move code into this monorepo) a SMTP capable email provider, because you suggest 3rd party providers in your [docs](https://strapi.io/documentation/v3.x/plugins/email.html#configure-the-plugin), which may not keep pace with the version of strapi. In my opinion strapi should maintain SMTP for the reasons above :point_up: 

@veitbjarsch @saunved @yutikom what about making @strapi a package owner of https://www.npmjs.com/package/strapi-provider-email-nodemailer?

**Comment by derrickmehaffy** [comment]
If you guys all agree, I can reopen and you can submit a PR to be looked at by our maintainers :)

**Comment by yutikom** [comment]
This is fine with me since I don't have time at all to maintain it.

Regards,
Yurii Tykhomirov (aka Yutikom)

пт, 23 окт. 2020 г., 01:40 DMehaffy <notifications@github.com>:

**Comment by roschaefer** [comment]
Just opened https://github.com/strapi/strapi/pull/8459

FYI @veitbjarsch @Saunved
