### ISSUE TITLE
`Improve this page` Documentation links to master branch

### ISSUE THREAD

**Issue by RileyMShea** [strapi/strapi#7002]
**Describe the bug**
On the documentation website, links to `improve this page`  link to the master branch instead of documentation branch.  

From the PR template it states that documentation updates should be submitted to the documentation branch.  

**Steps to reproduce the behavior**

This is a single example but the linking to master seems consistent across all `improve this page` links.

1. Go to 'https://strapi.io/documentation/v3.x/content-api/parameters.html#start'
2. Click on `improve this page` at the bottom of page.
3. User is sent to https://github.com/strapi/strapi/edit/master/docs/v3.x/content-api/parameters.md instead of https://github.com/strapi/strapi/edit/documentation/docs/v3.x/content-api/parameters.md
4. To correctly make a PR  the User must then:
- read the template and notice that doc updates should be made to documentation branch, not master.
- change their current address to https://github.com/strapi/strapi/edit/documentation/docs/v3.x/content-api/parameters.md

**Expected behavior**
Expected to be sent to the `documentation` branch of file to perform edits.

**Screenshots**
![image](https://user-images.githubusercontent.com/10238802/87324440-1453e080-c4fe-11ea-8e44-5a1eea8e831b.png)

**Comment by derrickmehaffy** [comment]
Closing this as it's no longer a problem since we moved the documentation to it's own repo.
