### ISSUE TITLE
Filter not respected when using search + filter and mongoose connector

### ISSUE THREAD

**Issue by admosity** [strapi/strapi#7003]
**Describe the bug**
When search is used it appears that filter options are being ignored and the search query results are included.

**Steps to reproduce the behavior**

Through Admin UI:
1. Goto strapi admin 
2. Perform a string query
3. Add a filter option

Using the service/controller `find` also produces the same result.

**Expected behavior**
Expect filter options to take precedence.

**Screenshots**
![image](https://user-images.githubusercontent.com/4655972/87337301-3c990a80-c511-11ea-83f3-191fd9a37e08.png)

Query of "wef" returns two emails here with that string included, but with a filter of size 8 applied (8 and 9) is on this list. Should be a single record here.

**System**

- Node.js version: v12.11.1
- NPM version: 6.11.3
- Strapi version:
```json
    "strapi": "3.0.5",
    "strapi-admin": "3.0.5",
    "strapi-connector-mongoose": "3.0.5",
    "strapi-plugin-content-manager": "3.0.5",
    "strapi-plugin-content-type-builder": "3.0.5",
    "strapi-plugin-email": "3.0.5",
    "strapi-plugin-graphql": "3.0.5",
    "strapi-plugin-upload": "3.0.5",
    "strapi-plugin-users-permissions": "3.0.5",
    "strapi-provider-email-mailgun": "3.0.5",
    "strapi-provider-email-sendgrid": "3.0.5",
    "strapi-provider-email-sendmail": "3.0.5",
    "strapi-provider-upload-cloudinary": "3.0.5",
    "strapi-utils": "3.0.5",
```
- Database: Mongodb (MongoDB server version: 4.0.7) with strapi mongoose connector
- Operating system: MacOS 10.15.5 (19F96)

**Comment by derrickmehaffy** [comment]
Will be added once v3.0.6 is released (should be sometime this week): https://github.com/strapi/strapi/pull/6865
