### ISSUE TITLE
404 in documentation, deployment section

### ISSUE THREAD

**Issue by fellz** [strapi/strapi#7007]
Hello
"Strapi does have a One-Click deployment option for DigitalOcean" leads to 404 error with this 
[link](https://strapi.io/documentation/v3.x/installation/digitalocean-one-click)
Can you update url ?

**Comment by rogeliorv** [comment]
https://strapi.io/documentation/3.0.0-beta.x/installation/digitalocean-one-click.html

**Comment by lauriejim** [comment]
The `.html` is missing in your url @fellz .
Where did you find this link ?
Here the correct one - https://strapi.io/documentation/v3.x/installation/digitalocean-one-click.html
