### ISSUE TITLE
Media library 500 error

### ISSUE THREAD

**Issue by jessjohnstonuk** [strapi/strapi#7009]
When opening the media library, Strapi seems unable to get the required api response in order to populate the media library with my uploads when using `strapi develop`.

I get a 500 error in the console.

![Screenshot 2020-07-14 at 13 13 02](https://user-images.githubusercontent.com/17690946/87424511-f953a000-c5d3-11ea-98c6-17420c4e99d4.png)

Below is my `package.json`, should it be needed for debugging purposes.

```json
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.0.5",
    "strapi-admin": "3.0.5",
    "strapi-utils": "3.0.5",
    "strapi-plugin-content-type-builder": "3.0.5",
    "strapi-plugin-content-manager": "3.0.5",
    "strapi-plugin-users-permissions": "3.0.5",
    "strapi-plugin-email": "3.0.5",
    "strapi-plugin-upload": "3.0.5",
    "strapi-connector-bookshelf": "3.0.5",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "f06fe40b-f1be-4ae0-aa01-b6611e75ac75"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**Comment by MattieBelt** [comment]
Hey @jessjohnstonuk can you share your console logs from the terminal, to give us more info on the error that occurred. 500 error means _Internal Server Error_, so we need to know the error from the server.

And update your Issue with [the template](https://github.com/strapi/strapi/issues/new?template=BUG_REPORT.md).

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
