### ISSUE TITLE
Additional documentation for Application Level Permissions

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#701]
**Do you want to request a *feature* or report a *bug*?**
Feature-ish request

**If the current behavior is a bug, please provide the steps to reproduce the problem**
There doesn't appear to be any documentation for v3.0.0 in regards to the changed permission system, as the v1.x.x docs don't follow the same format.

**What is the expected behavior?**
Generate detailed documentation on how the user permissions system works in Strapi v3.0.0-alpha and what each permission enables. One of the confusing permissions that many users have discussed on the slack is what permissions are required for users to access the admin panel to enter/delete/update data. 

The permissions system seems fairly straight forward with regards to using the generated API endpoints but not for modifying the data from non-admins on the backend admin panel. (Given of course the admin panel sounds like its only for admins though I assume that is not quite the case.)

**Comment by derrickmehaffy** [comment]
Updated based on response on Slack, its likely there is no permission that allows for non "root" or "admin" users to access the panel and this feature will be implemented later in `Admin Panel ACLs` Current permission system is in place to manage API Endpoints.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/36681406-c6ece6fe-1ad5-11e8-814f-d603e9187bd6.png)

**Comment by lauriejim** [comment]
@derrickmehaffy did you upvote your feature on https://strapi.io/vote ?

**Comment by derrickmehaffy** [comment]
@lauriejim I did yes, thank you

**Comment by storm1er** [comment]
Ref #672 As this is linked about databased config, especially permission since alpha10.1.
