### ISSUE TITLE
services.uid.checkUIDAvailability return always false except if collection is empty

### ISSUE THREAD

**Issue by theo-stocchetti** [strapi/strapi#7014]
**Describe the bug**
I want generate UID for a import system. I use **strapi.plugins['content-manager'].services.uid.checkUIDAvailability** for checking if the UID already exist. Currently the service return only **true** for the first record element on an empty collection.

**Steps to reproduce the behavior**

1. Generate entries with **UID** ( in my case it's a slug with **slugify**) in an empty collection
2. Use **checkUIDAvailability** for checking if the UID already exist
3. If the **UID** already exist or not the return value is always **false** however you have an SQL UNIQUE error constraint if the UID already exist.

**Expected behavior**
-> **checkUIDAvailability** must be return **true** if the **UID** is available and **false** if is already exist ?

**Screenshots**
![strapi_uid](https://user-images.githubusercontent.com/53647925/87470748-853dea00-c61d-11ea-952d-7df594841bd6.jpg)

**Code snippets**
```
    const uid = slugify(value, { separator: '-' });
    const avaible = await strapi.plugins['content-manager'].services.uid.checkUIDAvailability({contentTypeUID, field, uid });
    console.log('uid -> '+ uid, ' ||| services.uid.checkUIDAvailability -> : ', avaible);
```

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.4
- Strapi version: v3.0.5
- Database: SQLITE
- Operating system: WSL2

**Additional context**

**Comment by alexandrebodin** [comment]
Hi, You are not calling the function with the right parameters. it is expecting `{ contentTypeUID, field, value }` not `{ contentTypeUID, field, uid }`

FYI, ou are using internal code this can break on any given release.

Closing :)
