### ISSUE TITLE
GraphQL does not preserve order of many-to-many relational data.

### ISSUE THREAD

**Issue by iapain** [strapi/strapi#7015]
**GraphQL does not preserve order of relational data stored in array**
If we have a many-to-many relation then strapi stores data in an array of relationships, array preserves order and it works as expected via REST endpoint and in admin UI. However, when using graphql then array of relationship returns populated data sorted by `_id` instead of order which is supposed to be preserved in array.

**Steps to reproduce the behavior**

1. Here are an example models:
Posts
```json
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "posts",
  "info": {
    "name": "Post"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "description": {
      "type": "richtext"
    },
    "slug": {
      "type": "uid",
      "required": true,
      "targetField": "name"
    },
    "tags": {
      "collection": "tags",
      "via": "units",
      "dominant": true
    }
  }
}

```

Tags
```json
{
  "kind": "collectionType",
  "collectionName": "tags",
  "info": {
    "name": "Tags"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "label": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "post": {
      "via": "tags",
      "collection": "posts"
    }
  }
}
```
2. Create some post and tags
3. Associate tags to the post and shuffle the order.
4. Populate tags in `query Posts {...}` graphql.
5. They will appear in different order than they are stored in array.
   

**Expected behavior**
Array of relationship should be populated in order as arrays are stored in database.

**System**

- Node.js: 12.18.0
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: MongoDB 4.1.x
- Operating system: MacOS 10.15.5

**Comment by derrickmehaffy** [comment]
Please see the following FAQ entry: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#relations-aren-t-maintaining-their-sort-order

At this time, there is no plans to keep sort ordering for relations as the load to do so on the database is not worth the trade off. If this is something you need you will need to implement it yourself on your own project.
