### ISSUE TITLE
rate limit issue

### ISSUE THREAD

**Issue by antony989** [strapi/strapi#7016]
- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: mongoose
- Operating system: ubuntu 18.04

![screenshot 2020-07-15 pm5 42 24](https://user-images.githubusercontent.com/24715755/87523990-942aa800-c6c2-11ea-80dc-d7f5cd3e7b52.png)

if select the rate limit option in Public role,
a lot of requests are made regardless of the client, all clients return a 429 error.

Is this normal behavior?

**Comment by ByungJun25** [comment]
Hello strapi Team,

I also want to know about this function.
Is there any document?

**Comment by lauriejim** [comment]
Hello! here is the code source of the rate limit policy.
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js
This is based on the IP address not on the client, your issue can come from here I think.

**Comment by antony989** [comment]
> Hello! here is the code source of the rate limit policy.
> https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js
> This is based on the IP address not on the client, your issue can come from here I think.

hmm understand.
Need to modify that plugin itself? [from node_modules]
Or is it possible to fix it in the strapi project ex) api/[some route]/services ??

**Comment by petersg83** [comment]
Yes :) You can do the same as in the example: https://github.com/strapi/strapi/tree/master/examples/getstarted/extensions/users-permissions/config/policies

You can add a custom policy or change the one that already exist. On the second case you just need to name your file `rateLimit.js`, it will overwrite the existing one

**Comment by antony989** [comment]
> Yes :) You can do the same as in the example: https://github.com/strapi/strapi/tree/master/examples/getstarted/extensions/users-permissions/config/policies
> 
> You can add a custom policy or change the one that already exist. On the second case you just need to name your file `rateLimit.js`, it will overwrite the existing one

gooood thank you!

**Comment by petersg83** [comment]
You're welcome :)
I'm closing this issue then :)

**Comment by antony989** [comment]
> 천만에요. :)
> 이 문제를 해결하고 있습니다. :)

I am using Cloud Flare
i have temporarily fixed the problem as follows:
`
let aip = ctx.request.header["x-forwarded-for"]
let origin = aip.split(",")
...
prefixKey: `${ctx.request.path}:${origin[0]}`,
`
