### ISSUE TITLE
Strapi logout url

### ISSUE THREAD

**Issue by kperveen** [strapi/strapi#702]
**Node.js version**:
v8.6.0

**npm version**:
5.3.0

**Strapi version**:
3.0.0-alpha.10.2

**Operating system**:
Ubuntu 14.04

I am trying to do simple authentication using Nuxt as my front-end and strapi as my backend. Its working well with login and authentication but I am not sure which url to use for logout.
I went through the authentication documents too but I did not find any logout feature there either
Is there a logout url provided by the default authentication mechanism in strapi?

**Comment by soupette** [comment]
Hi @kperveen there is no logout route for the moment...

**Comment by lauriejim** [comment]
You will have to remove the `jwt` from your user session to logout your users. 
If you don't store your users's jwt (in a redis database for exemple), you will not be able to reject them to logout your user.

**Comment by kperveen** [comment]
@soupette is there a specific reason for this?

**Comment by piere129** [comment]
I'm curious about this as well, it seems like writing a dedicated url route for logging out could save a lot of confusion

**Comment by n8tb1t** [comment]
Hi, I have the same issue how I can invalidate the old JWT tokens?

**Comment by lauriejim** [comment]
Hum the easiest way could be to create a content type named JWT.
In this content type you add a will be able to add your JWTs you want to invalidate.

Then you will have to customize the code that check the JWT.
You will have to use this concept https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html

Here is the file you will have to update https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js

You will have to add a code block to find JTWs (in your content types) and check if one entry match with the current jwt.

Here is the code to query your data - https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html

**Comment by pherm** [comment]
hey @lauriejim any new about logout user by invalidate jwt? I don't solve this problem

**Comment by derrickmehaffy** [comment]
> hey @lauriejim any news about logout user by invalidate jwt? I don't solve this problem

Right now there is no plan to support this natively.
