### ISSUE TITLE
Changing the url in server.js breaks requests (/users-permissions/init)

### ISSUE THREAD

**Issue by michisp** [strapi/strapi#7024]
**Describe the bug**
I've changed the url in the server.js to '/strapi' so the page gets served under localhost:1337/strapi. After that /strapi/admin isn't able to load. The requests also get prepended with '/strapi' and respond with a 404 .

**Steps to reproduce the behavior**

1. Open  /config/server.js
2. Add url: '/strapi'
3. Build Strapi
4. Run yarn start / npm start
5. See the page is served under "http://localhost:1337/strapi/admin"
6. Navigate to the Admin

**Expected behavior**
The _/users-permissions/init_ request shouldn't be prepended with the url set in the server.js.

**Screenshots**
![image](https://user-images.githubusercontent.com/19972795/87560216-832a6880-c6bb-11ea-9036-66d99d4921aa.png)

The 404 request comes from /strapi/admin. The 200 request was just to show that the endpoint is still available

**System**

- Node.js version: 12.18
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: sqlite
- Operating system: Mac OS 10.15.5

**Comment by derrickmehaffy** [comment]
Strapi itself will not prefix any routes, to use that key properly you will need to use a proxy software such as Nginx. This is intended, as the config docs state that key is only for upstream support of an application proxy. 

```
Url of the server. Enable proxy support such as Apache or Nginx, example: https://mywebsite.com/api. The url can be relative, if so, it is used with http://${host}:${port} as the base url.
```
