### ISSUE TITLE
Setting a datetime in a component as an entry title causes a react error when setting the datetime

### ISSUE THREAD

**Issue by MatthewSbar** [strapi/strapi#7027]
**Describe the bug**

Setting a datetime's value inside of a component using the calendar UI causes a react error if the datetime is the entry title for the component.

**Steps to reproduce the behavior**

(Using the admin panel UI)

1. Create a content type
2. Create a piece of content using that type
3. Create a component.
4. Add a datetime to the component
5. Go to the content created in step 2
6. Using the "edit the view" button, edit the component's layout
7. Change the entry title to the datetime added in step 4
8. Go back to edit the content created in step 2
9. In the component, attempt to set the dateTime
10. React error: https://imgur.com/a/9WYX3UY 

**Expected behavior**

The date is set and the entry title updates accordingly.

Node.js version: 12.14.1
NPM version: 6.13.4
Strapi version: Strapi v3.0.0
Database: Postgres
Operating system: ubuntu 18.04.04 lts

**Comment by soupette** [comment]
Hi @MatthewSbar I am unable to reproduce your issue. Can you add a small video on how to reproduce the issue?

**Comment by Jassu225** [comment]
Same issue here.

Adding a new field to a repeatable component after referencing it in a table is causing the issue for me.

Node.js version: 12.16.0
NPM version: 6.14.5
Strapi version: Strapi v3.1.1
Database: mysql
Operating system: macOS Catalina version: 10.15.6

**Comment by Jassu225** [comment]
@soupette Happening only when timestamps option is set to false.

**Comment by lauriejim** [comment]
@Jassu225 I will close the `MatthewSbar` issue because of no answer base on `Soupette` question.
Can you please open a new one with all information and step to reproduce, please.
This will be easier to help you.
Thank you.
