### ISSUE TITLE
Cannot use other port in deployement

### ISSUE THREAD

**Issue by juliensl** [strapi/strapi#7033]
Hi everybody !

**Describe the bug**
I'm trying to deploy a new instance of strapi on my VM.

I have already a strapi instance, working with pm2 on the 1337 port.
So, I'm trying to deploy a new strapi on the 1338 port.
I have install it on my local, connected my mongoDB, created the new admin user, configured the provider, tried to use it on 1338 localhost port, everything works.

I uploaded the folder on my VM, deleted the `node_modules`, `build/` and `.cache` folders, made an install, changed uri, tried a `npm run develop`.
The server launched without any bugs, but I cannot access with the link to strapi, it's loading, loading, loading.... nothing in the browser console, nothing in the browser network console.
So, I stoped my first instance on pm2, and launched the second one on the port 1337 and tada ! It works fine !

**Steps to reproduce the behavior**

Try to have 2 instances of strapi on the same vm, using the same url but with 2 different ports, one 1337 and an other.

**Expected behavior**
Have 2 instances with 2 different ports.

**Code snippets**
my /config/server.js file : 
```
module.exports = ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: 1338,
  url: "http://my_url:1338",
  admin: {
    autoOpen: false,
  },
});
```

**System**

- Node.js version: 12.18.1
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: mongoDB
- Operating system: Ubuntu 18.04

Thank you for your help !

**Comment by dalbitresb12** [comment]
Hi there!

First of all, I should say that I'm not a member of the Strapi team, but I think I can help.

I've been using a setup with Nginx > Strapi on port 1337. I have a virtual host setup with a domain and it works all fine. Here is my `./config/server.js`:

```js
module.exports = ({ env }) => ({
  host: '127.0.0.1',
  port: 1337,
  url: 'https://abig.local/api/',
  admin: {
    url: 'https://abig.local/dashboard/',
  },
});
```

Then, I tried starting another Strapi instance, but using another port (1338). Here is the `./config/server.js`:

```js
module.exports = ({ env }) => ({
  host: '127.0.0.1',
  port: 1338,
  url: 'https://strapi.local/api/',
  admin: {
    url: 'https://strapi.local/dashboard/',
  },
});
```

I setup another virtual host on Nginx for `strapi.local`, and then tried starting both instances at the same time.

![image](https://user-images.githubusercontent.com/7624090/87869377-f60a3c80-c964-11ea-83b8-69f03da9f9f0.png)

![image](https://user-images.githubusercontent.com/7624090/87869380-fc98b400-c964-11ea-8e12-d4e8e36ff26a.png)

They both work perfectly fine. The admin panel and everything works completely fine.

I haven't tried it, but maybe the fact that you also added the port on the `url` value is what is preventing both of your instances from working.

Hope something here helps!

**Comment by juliensl** [comment]
Hi @dalbitresb12 !

I just succeed to solve my problem.
The reason ? I forget to open the port 1338 on Azure........ I hate me :laughing: 

Thank you for your help and sorry to annoy you with a non-issue ><

have a good day :) 

Julien

**Comment by dalbitresb12** [comment]
No worries, @juliensl! I'm glad you solved your problem.
