### ISSUE TITLE
Media files are populated ignoring populate parameter

### ISSUE THREAD

**Issue by weidox** [strapi/strapi#7034]
const entities = await strapi.query('entity').find(ctx.query, [{ path: 'parent1', select: 'id field1 field2' }]);
It nicely strips all fields from parent1 except the asked id, field1, field2, then _id which was not asked, and then it leaves the one Media type field with all it's huge json which was the primary reason I was trying to strip data.

Strapi 3.0.5.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
