### ISSUE TITLE
Failing to increase maxFileSize to upload files larger than 200 MB

### ISSUE THREAD

**Issue by Hellwest** [strapi/strapi#7035]
When I try to configure upload max file size it's always stuck at default value of 200 MB

**Steps to reproduce the behavior**
https://github.com/Hellwest/strapi-failing-upload-max-size (see commit history)

1. Initialize Strapi app with docker (I'm using PostgreSQL database)
2. Try to adjust your configurations in config/request.js 

```bash
module.exports = {
  parser: {
    enabled: true,
    multipart: true,
    formidable: {
      maxFileSize: 900 * 1024 * 1024,
    },
  },
}
```

It fails.
3. Try to configure in extensions/upload/config/config.js

```bash
module.exports = {
  enabled: true,
  provider: "local",
  providerOptions: {
    sizeLimit: 900 * 1024 * 1024,
  },
}
```

It fails.

**Expected behavior**
I can upload a 700MB mp4 video file

**Actual behavior/Screenshots**
![image](https://user-images.githubusercontent.com/16734469/87666148-27beb000-c779-11ea-8512-1c8859fbc9e1.png)

You can see maxFileSize is still ~200 MB on the screen

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: PostgreSQL
- Operating system: Ubuntu 18.04/Linux Mint 19.3/Linux Mint 20

**Additional context**
Similar issues: https://github.com/strapi/strapi/issues/4156, https://github.com/strapi/strapi/issues/1975, https://github.com/strapi/strapi/issues/1906 and maybe https://github.com/strapi/strapi/issues/2737 (Suggested solutions don't work. I'm not using nginx, it's a clean repository, so body size can't be configured any other way)

**Comment by GiovanniFrigo** [comment]
I somehow managed to fix this by doing two things:

1. Putting the configuration for the formidable maxFileSize in `extensions/upload/middlewares/upload/defaults.json` (as somehow hinted here: https://strapi.io/documentation/v3.x/plugins/upload.html#configuration)
2. Freezing the formidable resolved version to "1.1.1" as the later versions seem to have some issues (https://github.com/node-formidable/formidable/commit/39f27f29b2824c21d0d9b8e85bcbb5fc0081beaf#commitcomment-28221459)

So, in practice:

1. create or edit the file `extensions/upload/middlewares/upload/defaults.json` with the following content (insert your own `maxFileSize` here, mine was 10 GB:

```
{
  "upload": {
    "enabled": true,
    "multipart": true,
    "formidable": {
      "maxFileSize": 10737418240
    }
  }
}
```

2. add the following lines to your `package.json` file:
```
 "resolutions": {
    "formidable": "1.1.1"
  }
```
then run `yarn && yarn build` to apply these settings.

This is most probably not the best way to solve this, but hey! it works ;)

**Comment by emmajhyde** [comment]
I tried your approach @GiovanniFrigo and still getting 
```
                                                                                                                                            
strapi_1  | [2020-07-20T15:38:04.779Z] error Error: maxFileSize exceeded, received 209780592 bytes of file data
strapi_1  |     at Stream.<anonymous> (/srv/node_modules/formidable/lib/incoming_form.js:222:19)
``` 
I have tried pretty much everything that seems to be on the docs, I really can't figure it out. I am not OP, but I've been struggling with this same issue all night! I cannot even remotely tell where this config is supposed to go. It is driving me insane.

**Comment by Hellwest** [comment]
@GiovanniFrigo worked for me

**Comment by GiovanniFrigo** [comment]
@emmajhyde I honestly do not know what's fixing the thing anymore. I later deleted the `extensions/upload/middlewares/upload/defaults.json`, cleared the cache and rebuild (`rm -rf .cache/ build && yarn build`) and still is working.. so I'm now not sure anymore where the configuration lives ¯\_(ツ)_/¯ 

In the trial and error phase that preceded my posting here, I experimented with many different config files (see them all here: https://gist.github.com/GiovanniFrigo/499e4ab1774d21eb6e9c8670eaaf943a) in a dumb attempt to try and find a way of setting the upload size.. but again, I'm not sure any of them is correct anymore.

Waiting for some maintainer to help us out.

**Comment by emmajhyde** [comment]
@GiovanniFrigo I have no idea which config file gets used (I have so many at this point), but I noticed that NPM does not offer dependency version locks in the same way as yarn. I switched all my npm install & npm run builds to yarn & yarn builds, and did a yarn start. It appears that it's working! I would say that it's clear that the formidable version is a huge factor.

**Comment by jeanverster** [comment]
Thanks for this @GiovanniFrigo , worked for me 🎉

**Comment by RileyMShea** [comment]
@GiovanniFrigo I will try this shotgun approach and see what sticks.

**Comment by modjke** [comment]
For anybody struggling with where to put your config for upload middleware, use `config/middleware.js`
Contents:
```javascript
module.exports = ({ env }) => {
  return {
    settings: {
      parser: {
        enabled: true,
        multipart: true,
        formidable: {
          maxFileSize: 10737418240 
        }
      }
    }
  }
}

```

**Comment by RyanPrentiss** [comment]
Was this issue resolved?

With or without middleware.js, I found through testing I can upload up to approximately 900MB, but nothing more, whether it be locally (Windows 10) or the Heroku deployment.

    //version 3.1.1
    module.exports = {
      settings: {
          parser: {
            enabled: true,
            multipart: true,
            formidable: {
              maxFileSize: 5 * 1024 * 1024 * 1024,
            },
          },
        },
      };

**Comment by silveur** [comment]
Had same issue until I specified a correct size in bytes in the middleware.js such as  1073741824 or like the above `5 * 1024 * 1024 * 1024`
Then run `npm run build`

**Comment by gustawdaniel** [comment]
In my case

+ solution of @modjke works
+ solution of @GiovanniFrigo does not works
+ no yarn build / npm run build was required

**Comment by maertz** [comment]
for anyone who comes from 2021
https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#create-providers

**Comment by TimLanzi** [comment]
I've copied the solution given by @modjke and it does not appear to be working with really big files (around 2GB)

**Comment by modjke** [comment]
> I've copied the solution given by @modjke and it does not appear to be working with really big files (around 2GB)

That's odd, official doc says that it should work
https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#configuration

**Comment by TimLanzi** [comment]
> That's odd, official doc says that it should work https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#configuration

Yes. I looked in the docs first and it didn't work. Increasing the size does work for uploading files larger than the default 200MB, but once I tried to upload a 2GB .zip file, it still gave me the "file to big" error.

**Comment by sweleck** [comment]
Just a small hint. If you updated your strapi from an older version, you need to remove 
` config/middleware.json`
before your changes in 
` config/middleware.js`
are applied

**Comment by kacperkurek** [comment]
> Yes. I looked in the docs first and it didn't work. Increasing the size does work for uploading files larger than the default 200MB, but once I tried to upload a 2GB .zip file, it still gave me the "file to big" error.

I have the same problem with video file 1,8GB.

**Comment by tongnick** [comment]
@TimLanzi & @kacperkurek 

I believe the reason we are able to upload files larger than 200MB but smaller than 1GB is because there is another limit (sizeLimit) capping the effective maximum file size.

In addition to setting `maxFileSize` for **formidable**, it appears we must also set `sizeLimit` for **strapi-plugin-upload** ( node_modules/strapi-plugin-upload/config/config.json ).

Once upping both **formidable** `maxFileSize` and **strapi-plugin-upload** `sizeLimit` I am able to upload files over 2GB up to the chosen limit.

**Comment by TimLanzi** [comment]
@tongnick Thank you! This did it! In addition to making the specified updates from the Strapi docs, I created this file at `extensions/upload/config/config.json`:

```json
{
  "enabled": true,
  "provider": "local",
  "providerOptions": {
    "sizeLimit": 5368709120
  },
  "actionOptions": {}
}
```

**Comment by antokhio** [comment]
Hi, anyone else struggle with this:
`/config/plugins.ts`
```ts
export default {
  upload: {
    config: {
      providerOptions: {
        sizeLimit: 1500 * 1024 * 1024,
      },
    },
  },
};
```

**Comment by tuoxiansp** [comment]
for anyone who comes from 2023 with strapi version >= v4.6.1
```
export default {
  upload: {
    config: {
      sizeLimit: 250 * 1024 * 1024 // 256mb in bytes
    },
  }
}
```


links: 
- documentation: https://docs.strapi.io/dev-docs/plugins/upload/#max-file-size
- migrate from v4.5.1+ to v4.6.1+: https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.5.1-to-4.6.1#updating-the-sizelimit-provider-configuration
