### ISSUE TITLE
Invalid host: admin on create-strapi-app --quickstart

### ISSUE THREAD

**Issue by tacomanator** [strapi/strapi#7042]
**Describe the bug**
After creating a new project with --quickstart (as indicated in [Quick Start Guide](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html)) the project starts up but the admin interface will not load (http://localhost:1337/admin reports "Invalid Host: admin").

**Steps to reproduce the behavior**

1. Create a new project with:

```
$ npx create-strapi-app my-project --quickstart
```

2. The project is started and admin interface opened automatically (showing error)

**Expected behavior**
No error, able to continue on (create admin user)

**Screenshots**

<img width="1196" alt="Screen Shot 2020-07-17 at 9 02 38" src="https://user-images.githubusercontent.com/63794/87734019-5a65b880-c80c-11ea-9ceb-133fd200d739.png">

<img width="919" alt="Screen Shot 2020-07-17 at 8 20 51" src="https://user-images.githubusercontent.com/63794/87734034-68b3d480-c80c-11ea-8866-abc357f191aa.png">

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.6
- Database: Sqlite3 3.28.0
- Operating system: MacOS 10.15.5 (19F101)

**Comment by derrickmehaffy** [comment]
Do me a favor and try to open the admin in an incognito tab or window, because that looks like some extension is trying to inject something and it's causing a problem.

**Comment by tacomanator** [comment]
sorry for the late reply. I tried in an incognito window but still a no go 😢 

<img width="720" alt="Screen Shot 2020-07-19 at 16 41 34" src="https://user-images.githubusercontent.com/63794/87869991-1f67ae80-c9df-11ea-8d65-923f85d2c7ba.png">
<img width="1123" alt="Screen Shot 2020-07-19 at 16 43 24" src="https://user-images.githubusercontent.com/63794/87869995-22629f00-c9df-11ea-9151-737bacc97b9e.png">

**Comment by tacomanator** [comment]
Tried different versions of node and reinstalling this and that with no luck, but ultimately the problem was solved by a complete erase and OS reinstall.

**Comment by derrickmehaffy** [comment]
> Tried different versions of node and reinstalling this and that with no luck, but ultimately the problem was solved by a complete erase and OS reinstall.

Quite the task, so something was borked in your user environment. 🤔 

Glad you got it fixed.

**Comment by CallMeLaNN** [comment]
Probably there is another node service using the port. In my case if Blockstack app (on Mac) is running I got this error until I close the app.

**Comment by tacomanator** [comment]
Indeed Blockstack was running. I assumed port in use would be checked on startup, but the CLI gave no such warning.
