### ISSUE TITLE
Incorrect 'All your modifications will be lost' warning

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7045]
**Describe the bug**
Content type with datetime field shows 'Are you sure you want to leave this page? All your modifications will be lost' warning even if no changes has been made.

**Steps to reproduce the behavior**

1. Create new content type with datetime field
2. Create new entry & fill value in datetime field
3. Visit that record edit page again & go back without making any changes
4. See the warning

**Expected behavior**
It should not show any warning.

**System**

- Node.js version: 12.x 
- NPM version: NA
- Strapi version: 3.0.6 
- Database: Mongo
- Operating system: Mac OS 10.15.6

**Additional context**
Its because ISO date string from db is converted to Moment object on page load, so lodash's isEqual will return false.

**Comment by soupette** [comment]
@aksdevac I am closing this issue as I have opened another one in the [Buffet.js](https://github.com/strapi/buffet) repository.
