### ISSUE TITLE
NOTICE: Mandrill Service Provider Not working in 3.0.5

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#7047]
**- Node.js version: 12.16.3
- NPM version:6.14.4
- Strapi version: 3.0.5
- Database:mongodb
- Operating system:Ubunto**

Hello i have configured mandrill settings in config/plugins.js. But on sending email i am getting following error.

![errorr](https://user-images.githubusercontent.com/47749809/87774911-e09cf180-c842-11ea-9ed8-83b039a19c9f.png)

**Comment by alexandrebodin** [comment]
Hi @iamwebdev what package did you use ? we do not maintain any mandrill package you should will have to report this in the dedicated repository. 

Closing for now. Feel free to ask for reopeing if you think there is sth to do on the main repo :)

**Comment by iamwebdev** [comment]
Hello please open this issue again..I have used https://www.npmjs.com/package/strapi-provider-email-mandrill this provider which is mentioned in providers list on strapi's official site.

**Comment by derrickmehaffy** [comment]
@iamwebdev no that provider was not build by Strapi: https://github.com/jayakusumah/strapi-provider-email-mandrill

All providers built and maintained by Strapi are located here: https://github.com/strapi/strapi/tree/master/packages
