### ISSUE TITLE
mandrill not working

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#7049]
- Node.js version: 12.6.3
- NPM version:6.14.4
- Strapi version: 3.0.5
- Database:mongodb
- Operating system:ubunto

I have used mandrill email service provider(https://www.npmjs.com/package/strapi-provider-email-mandrill) for sending emails which is listed in supported email service providers list on strapi's official site.
I have configured manndrill setting in config/plugins.js
On sending email i am getting following error

![errorr](https://user-images.githubusercontent.com/47749809/87778333-aa627080-c848-11ea-8d84-ecaabe9e905b.png)

**Dont close this issue without resolving it, its very urgent**

**Comment by alexandrebodin** [comment]
Hello @iamwebdev. As already said in the previous issue you opened,

This issue is coming from a pacakge we do not maintain nor publish on npm. you need to go open an issue there. You can check in the npm description that this is not pointing to this repository. We do not have a mean to change the code in the original repository to upgrade it ourselves. Go to https://github.com/jayakusumah/strapi-provider-email-mandrill and open an issue there.

**Comment by iamwebdev** [comment]
Is it avaible in 3.0.6 version ? Which version then i should then to use mandril ?

**Comment by iamwebdev** [comment]
It is working fine on 3.0.0-beta.17.5 , but i want to use stable version. So thats why i upgraded to 3.0.5 as it is stable version i guess

**Comment by alexandrebodin** [comment]
We do not maintain any mandrill provider in this repository so there is no specific version to use. The maintainer of this package will need to upgrade before you can upgrade.

**Comment by alexandrebodin** [comment]
You can patch this by implemeting a custom provider un the meantime with this documentation https://strapi.io/documentation/v3.x/plugins/email.html#create-new-provider

**Comment by iamwebdev** [comment]
Can i get an example to create one.

**Comment by alexandrebodin** [comment]
You can look at this provider https://github.com/strapi/strapi/blob/master/packages/strapi-provider-email-sendgrid/lib/index.js

**Comment by iamwebdev** [comment]
settings option is also not visible, where can i open below window
![UgGZg](https://user-images.githubusercontent.com/47749809/87782625-873bbf00-c850-11ea-90af-69a654db12e0.png)

**Comment by alexandrebodin** [comment]
This changed in the stable release. You can find the doc in the migration guide https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html#email-plugin-settings

**Comment by alexandrebodin** [comment]
From your last comment I'm guessing you didn't configure the email provider with the migration. The mandrill provider might still work fine.

**Comment by alexandrebodin** [comment]
I just verifie and the provider still works:

Here is the configuration you should be using

`./config/plugins.js`
```
module.exports = {
  email: {
    provider: "mandrill",
    providerOptions: {
      mandrill_api_key: "",
      mandrill_default_from_email: "no-reply@your-domain",
      mandrill_default_from_name: "whatever",
      mandrill_default_replyto: "no-reply@your-domain",
    }
  },
};

```

**Comment by iamwebdev** [comment]
Hello, I have tried your above-mentioned suggestion, but still getting the same error.

**Comment by alexandrebodin** [comment]
this error means the email provider is having errors you can try adding a dirty console.log in the node module temporarily to log the actual mandrill error you are getting.

**Comment by iamwebdev** [comment]
Yes , i checked there is some issue with from email. But i have used @gmail.com account.
![errrr](https://user-images.githubusercontent.com/47749809/87790854-df79bd80-c85e-11ea-83f0-61e1c2a9a130.png)

**Comment by iamwebdev** [comment]
Thank you Alex for your time, now it is working fine. I have checked that default email i was passing in plugin file was wrong.

module.exports = {
  email: {
    provider: "mandrill",
    providerOptions: {
      mandrill_api_key: "",
      mandrill_default_from_email: "no-reply@your-domain",
      mandrill_default_from_name: "whatever",
      mandrill_default_replyto: "no-reply@your-domain",
    }
  },
};

This actully helps me alot.

**Comment by alexandrebodin** [comment]
I'll let you close the issue if this works for you now

**Comment by derrickmehaffy** [comment]
Marking as closed as user stated it was working.
