### ISSUE TITLE
SQLITE_ERROR: no such column in Custom Query

### ISSUE THREAD

**Issue by Rirax** [strapi/strapi#7053]
Hello,

I try to create a custom query to perform an AND query but not working.

I have accomodation and amenities models.
Each accomodation have many amenities.

I would like to request the accommodations that have amenity 1 AND amenity 2.

For this I have created a custom endpoint with this controller :
/api/test/controllers/Test.js

```
module.exports = {
  index: async ctx => {
    console.log(ctx.query);
    const result = await strapi
      .query('accomodation')
      .model.query(qb => {
        qb.where('amenities', [1, 2]);
      })
      .fetch();
  },
};
```

In dev environment I get error:
**Error: SQLITE_ERROR: no such column: amenities**
Note that the code
`const result = await strapi.query('accomodation').find({ _limit: 10, amenities_in: [1, 2] });`
does return a result (but not possible to do AND query with this)

So what do I have to do to make the request work? And which operator to use for AND query ?
Bookshelf doc is not helping me :(

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
