### ISSUE TITLE
Admin build with custom HOST, PORT, PROXY_URL broken in 3.0.6 due to my PR

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7059]
**Describe the bug**
`strapi build` does not use variables from .env file

**Steps to reproduce the behavior**

1. try to make admin build with custom HOST, PORT & PROXY_URL, it will use fixed localhost:1337 url always

**System**

- Node.js version: 12.x 
- NPM version: NA
- Strapi version: 3.0.6 
- Database: MongoDB
- Operating system: Mac OS 10.15.6
 
**Additional context**
 This https://github.com/strapi/strapi/blob/cd710d34e0f88ab96100840b68dfb1a562c5f721/packages/strapi/lib/commands/build.js#L8
line loads config directly from /app-configuration but my PR #6701 moved(dotenv init) it to `Starpi.js`, not sure about best way to handle this, so someone from core team should fix it, or should revert my change.
@alexandrebodin

**Comment by alexandrebodin** [comment]
Thanks for reporting this. Will make a fix.
