### ISSUE TITLE
Adding Locales support

### ISSUE THREAD

**Issue by UserGalileo** [strapi/strapi#706]
**Do you want to request a *feature* or report a *bug*?**
Feature

Hi guys!
Is there a "Locales" feature planned? It'd be really useful to have our content types translated in multiple languages. Thanks!

**Comment by lauriejim** [comment]
Hello @UserGalileo , thanks for this issue.
Actually not planned to implement and UI in admin for that but you already use i18n with strapi https://strapi.io/documentation/guides/i18n.html

We are drive by the community for next feature, submit or upvote yours here https://strapi.io/vote

**Comment by UserGalileo** [comment]
Hi @lauriejim, maybe I put it down wrong, I'm talking about actually setting, for example, english and italian as active languages, and if I have an entry of type "Article" with a "Title" field, when the admin inserts a new article he will be able to fill the two input fields: "Title (en)" and "Title (it)".
Exactly what Contentful does :)

**Comment by lauriejim** [comment]
Ho okay I see. 
Can you upvote `Plugin - Content Internalization` on https://strapi.io/vote page please

**Comment by cawoodm** [comment]
Can't find any such idea on your votes page so I've submitted the idea.
