### ISSUE TITLE
Koa app.proxy not set when using sub-folder-split config

### ISSUE THREAD

**Issue by dalbitresb12** [strapi/strapi#7061]
**Describe the bug**
I've been trying to use secure cookies instead of saving JWT to localStorage. I've used the [plugin extension](https://strapi.io/documentation/v3.x/concepts/customization.html#plugin-extensions) concept to modify the users-permissions plugin so that it sets the JWT on a cookie and then it reads it from there (code snippets below, adapted from [this](https://talke.dev/strapi-user-permissions-jwt-cookies/) guide). 

The problem is when trying to set the cookies as secure cookies. Koa fails to set a secure cookie due to not knowing about the proxy (Nginx). `app.proxy` should be set to true so that cookies can be set as secure cookies (see [this](https://github.com/pillarjs/cookies#secure-cookies) and [this](https://koajs.com/#settings)).

**Steps to reproduce the behavior**

1. Use the code snippets provided below.
2. Create user (using admin or API, doesn't matter).
2. Try to POST `/api/auth/local` with user credentials.
3. See error: `Cannot send secure cookie over unencrypted connection`.

**Expected behavior**
There should be a way to set `app.proxy` so that Koa knows it's behind a proxy and trusts it.

**Screenshots**
I added a logger before the cookies are set so that the value of `strapi.app` is visible.

![image](https://user-images.githubusercontent.com/7624090/87850835-d584a880-c8b8-11ea-9b6c-8d3766a3f641.png)

**Code snippets**
Change else statement on line 131 in [`./extensions/users-permissions/controllers/Auth.js`](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L131):
```js
} else {
  const token = strapi.plugins['users-permissions'].services.jwt.issue({
    id: user.id,
  });

  strapi.log.info("strapi.app:", strapi.app);
  ctx.cookies.set("token", token, {
    signed: true,
    httpOnly: true,
    sameSite: "lax",
    secure: true,
    maxAge: 1000 * 60 * 60 * 24 * 14,
    domain: process.env.PRODUCTION_URL,
  });

  ctx.send({
    status: "Authenticated",
    user: sanitizeEntity(user.toJSON ? user.toJSON() : user, {
      model: strapi.query('user', 'users-permissions').model,
    }),
  });
}
```

Add this after line 4 (`let role;`) in [`./extensions/users-permissions/config/policies/permissions.js`](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js#L4):
```js
if (ctx.request && ctx.request.header && !ctx.request.header.authorization) {
  const token = ctx.cookies.get("token");
  if (token) {
    ctx.request.header.authorization = "Bearer " + token;
  }
}
```

On `./config/server.js`:
```js
module.exports = ({ env }) => ({
  host: 127.0.0.1,
  port: 1337,
  url: 'https://abig.local/api/',
  admin: {
    url: 'https://abig.local/dashboard/',
  },
});
```

Nginx server config:
```
server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name abig.local;

  ssl on;
  ssl_certificate /path/to/cert.pem;
  ssl_certificate_key /path/to/server.key;

  location /dashboard/ {
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:1337/dashboard/;
  }

  location /api/ {
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:1337/;
  }

  location / {
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:8080/;
  }

  location ~ /\.ht {
    deny all;
  }
}
```

**System**

- Node.js version: v12.18.1
- NPM version: v6.14.5
- Strapi version: v3.0.5
- Database: MySQL 5.7.30-0ubuntu0.18.04.1
- Proxy: nginx/1.14.0 (Ubuntu)
- Operating system: Ubuntu 18.04 on WSL 2 (Windows 10 2004)

**Additional context**
I'm pretty new to using Strapi, so I'm sorry if there's something I'm missing that is preventing Koa from trusting Nginx. Also, sorry if there's any typo, English isn't my native language.

**Comment by derrickmehaffy** [comment]
Yup I can confirm this is an issue, @dalbitresb12 if you feel confident, can you submit a PR?

**Comment by dalbitresb12** [comment]
@derrickmehaffy I would submit a PR, but honestly I have no idea where I should fix this. I would totally do it if I knew.

**Comment by dalbitresb12** [comment]
Okay, I think I figured it out. I'm going to document my findings here so that everyone can get help from this.

First of all, I tried adding this [here](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/Strapi.js#L46):

```js
this.app.proxy = true;
console.log(this.app.inspect());
```

This actually set the proxy to true on Koa as you can see from the `console.log` (it probably should read this from a config file, but this was just trying to find how it could work).

![image](https://user-images.githubusercontent.com/7624090/87868890-61054480-c960-11ea-8889-b5fdcbe40bdf.png)

Then I tried to POST `https://strapi.local/api/auth/local/`, but it also failed. I then realized that Nginx wasn't setting the `X-Forwarded-Proto` header. So I added `proxy_set_header X-Forwarded-Proto https;` on every location block on the Nginx conf. For example, in the `/api/` block it was like this:

```
location /api/ {
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header X-Forwarded-For $remote_addr;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto https; # Added so that Koa knows it is using HTTPS
  proxy_redirect off;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_pass http://127.0.0.1:1337/;
}
```

After this, setting a secure cookie works perfectly fine.

![image](https://user-images.githubusercontent.com/7624090/87869051-e9d0b000-c961-11ea-95a5-22ab7db7cdaf.png)

![image](https://user-images.githubusercontent.com/7624090/87869067-1b497b80-c962-11ea-947c-6feaf79b2046.png)


I think it's just that Strapi needs to set the proxy property on the Koa instance depending on some value on the configuration files or an environment variable and it's also important to set the `X-Forwarded-Proto` header on the proxy.

@derrickmehaffy, how would this be?
