### ISSUE TITLE
TypeError: Cannot read property 'Component' of null

### ISSUE THREAD

**Issue by dawnerd** [strapi/strapi#7067]
**Describe the bug**
Created a Page type with a dynamic zone that (for now) just contains a rich text component. It works when running locally but when I deploy to production I get the error. Error pops up the moment I select the component.

**Screenshots**
![image](https://user-images.githubusercontent.com/24781/87860236-9ffbb180-c8f0-11ea-8717-b594589096e6.png)

![image](https://user-images.githubusercontent.com/24781/87859888-a0467d80-c8ed-11ea-94f6-00eaec872d80.png)
![image](https://user-images.githubusercontent.com/24781/87859900-ba805b80-c8ed-11ea-88cf-49890c11c839.png)
![image](https://user-images.githubusercontent.com/24781/87859903-c66c1d80-c8ed-11ea-94f6-d49c31936778.png)
![image](https://user-images.githubusercontent.com/24781/87859917-d8e65700-c8ed-11ea-95c1-da95889ebaa4.png)
(after clicking the component)

**Code snippets**
<details>
<summary>dockerfile</summary>

```dockerfile
FROM strapi/base as production

WORKDIR /srv/app

COPY ./app .

ENV NODE_ENV production

RUN yarn install
RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
```

</details>

<details>
<summary>config/routes.json</summary>

```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/pages",
      "handler": "page.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/pages/count",
      "handler": "page.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/pages/:id",
      "handler": "page.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/pages",
      "handler": "page.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/pages/:id",
      "handler": "page.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/pages/:id",
      "handler": "page.delete",
      "config": {
        "policies": []
      }
    }
  ]
}

```
</details>

<details>
<summary>controllers/page.js</summary>

```js
'use strict';

/**
 * Read the documentation (https://strapi.io/documentation/v3.x/concepts/controllers.html#core-controllers)
 * to customize this controller
 */

module.exports = {};

```
</details>

<details>
<summary>models/page.js</summary>

```js
'use strict';

/**
 * Read the documentation (https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks)
 * to customize this model
 */

module.exports = {};

```
</details>

<details>
<summary>models/page.settings.json</summary>

```js
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "Page"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Title": {
      "type": "string",
      "required": true
    },
    "Slug": {
      "type": "uid",
      "targetField": "Title",
      "required": true
    },
    "Content": {
      "type": "dynamiczone",
      "components": [
        "content.rich-content"
      ]
    }
  }
}

```
</details>

<details>
<summary>services/page.js</summary>

```js
'use strict';

/**
 * Read the documentation (https://strapi.io/documentation/v3.x/concepts/services.html#core-services)
 * to customize this service
 */

module.exports = {};

```
</details>

<details>
<summary>components/content/rich-content.json</summary>

```json
{
  "collectionName": "components_content_rich_contents",
  "info": {
    "name": "Rich Content",
    "icon": "align-left"
  },
  "options": {},
  "attributes": {
    "Text": {
      "type": "richtext"
    }
  }
}

```
</details>

**System**

- Node.js version: from `strapi/base` (v12.18.2)
- Node env: production
- NPM version: strapi/base
- Strapi version: 3.0.6
- Database: mongo:4.2.8
- Operating system: from `strapi/base`

**Comment by derrickmehaffy** [comment]
Can you please test this outside of docker

**Comment by dawnerd** [comment]
That took some effort on the prod environment but running outside of docker produces the same error. Weird thing, doesn't happen on my mac, even using the docker image built for production. Safari did output a slightly more detailed error:

```
TypeError: null is not an object (evaluating 'a("media-library").Component')

    in d
    in u
    in n
    in div
    in styled.div
    in p
    in n
    in m
    in FormattedMessage
    in O
    in O
    in div
    in div
    in div
    in styled.div
    in div
    in div
    in div
    in styled.div
    in form
    in b
    in u
    in w
    in w
    in t
    in t
    in Suspense
    in p
    in t
    in t
    in Suspense
    in Unknown
    in _
    in A
    in n
    in div
    in p
    in p
    in t
    in t
    in div
    in styled.div
    in div
    in div
    in styled.div
    in ie
    in n
    in A
    in injectIntl(Connect(n))
    in t
    in d
    in t
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in l
    in x
    in A
    in t
    in t
    in IntlProvider
    in n
    in A
    in Li
    in l
```

If I remove the rich text field it works again. Something weird going on with that

**Comment by soupette** [comment]
Well it's seems related to the the media library component. Somehow it does not exist in your app.

**Comment by dawnerd** [comment]
Okay yep that was the issue. In case anyone else stumbles across this, make sure `strapi-plugin-upload` is in your package.json.

Must have been missed in a yarn add or something, I had it locally which explains why it worked there.

Anyways, thanks for the assist :)

**Comment by domantasjurkus** [comment]
Any suggestions on how to resolve the issue without installing the plugin?
