### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by jmaferreira** [strapi/strapi#7069]
**Describe the bug**

When I start Strapi it always outputs the following warnings:

```
(node:16838) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:16838) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:16838) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:16838) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:16838) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
```

Should I be worried that my code has a leak? Is there anyway to disable these warnings?

**Steps to reproduce the behavior**

Just run `strapi dev` on the project folder.

**Expected behavior**

I would expect it not to output these warnings.

**Screenshots**

<img width="1382" alt="Screenshot 2020-07-18 at 22 54 11" src="https://user-images.githubusercontent.com/3181302/87862583-9b171c00-c949-11ea-866d-d4e7b34f9c9e.png">

**System**

- Node.js version: v12.16.3
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: mongodb
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
Can you please provide any additional info to allow us to reproduce this issue.

**Comment by jmaferreira** [comment]
Sure.

Judging from your answer, I guess this is not happening to everyone... so I've run some tests:

1. I've created a new Strapi app to check if the warning appeared on an empty project. Everything ok.
2. Installed the documentation plugin. Everything ok.
3. I've had some code in the bootstrap module. Cleaned it and the error went away.

I was something in one of the external modules I was using.

Cheers. All good.
