### ISSUE TITLE
Files Upload settings in plugins not showing up after installing cloudinary plugin

### ISSUE THREAD

**Issue by officialrj18** [strapi/strapi#7075]
On following the heroku deployment installation instructions on the website I am supposed to go to the Plugins page and enter the Files Upload plugin settings as described .But It does not show up for me.

**Steps to reproduce the behavior:**
Create a simple quickstart project 
Follow instructions from heroku deployment
Simply install  cloudinary plugin.

**Expected behavior:**
It should appear in the plugins list and allow different settings for each environment.

 **System**
Node: 12.18.2 
Yarn: 1.21.1 
npm: 6.14.5 
database: postgress
Strapi: v3.0.5
OS : Linux

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/6710
