### ISSUE TITLE
"gatsby clean" broke my site

### ISSUE THREAD

**Issue by kylewetton** [strapi/strapi#7080]
**Describe the bug**
My starter build was working as the example was, no problem. I added a new Single Type and that too was working. I changed some content inside Strapi and the site didn't update the content, so I ran 'gatsby clean' to be sure that it wasn't a caching issue. I now can't build the site. I get this error

`Cannot query field "strapiArticle" on type "Query".

If you don't expect "strapiArticle" to exist on the type "Query" it is most likely a typo.
However, if you expect "strapiArticle" to exist there are a couple of solutions to common problems:`

**Steps to reproduce the behavior**

1. Build starter blog
2. Run 'gatsby clean' on front end
3. Attempt to start the front end again with `npm run develop`

**System**

- Node.js version: v14.0.0
- NPM version: 6.14.4
- Strapi version: "3.0.0"
- Operating system: iOS Catalina

**Additional context**
I have checked that the permissions are (still) correct. However, I'm not seeing any Users. One would expect to see your own user account under users, seeing as you're prompted to create one when you first launch the back end. Is this not the case?

**Comment by kylewetton** [comment]
I have also ensured that the two starter blog posts have categories assigned

**Comment by lauriejim** [comment]
Hello! Witch starter are you talking about.
We need more information to reproduce and help you.
Thank you.

**Comment by derrickmehaffy** [comment]
As we have no updated information from the user, marking as closed.
