### ISSUE TITLE
apollo-server-koa should be updated due to security advisory

### ISSUE THREAD

**Issue by IkeLutra** [strapi/strapi#7085]
**Describe the bug**

`apollo-server-koa` has a security advisory https://github.com/advisories/GHSA-w42g-7vfc-xf37 for the fixed version of `2.9.12`. This should be updated to version constraint that satisfies the fix.

**Steps to reproduce the behavior**

None

**Expected behavior**

Strapi GQL Plugin depends on a version of Apollo Server without the security advisory.

**Screenshots**

None

**Code snippets**

It is set in `packages/strapi-plugin-graphql/package.json`

**System**

N/A

**Additional context**

I will create a PR shortly to change this.

**Comment by derrickmehaffy** [comment]
Thank you for the PR @IkeLutra I will ping @alexandrebodin about this just to make it visible.
