### ISSUE TITLE
strapi stuck in installing dependencies

### ISSUE THREAD

**Issue by Bakumegusta** [strapi/strapi#7091]
![strapi](https://user-images.githubusercontent.com/14792048/87996014-b5e6bd80-cb0e-11ea-8212-5aded7d48af0.JPG)

**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by petersg83** [comment]
Can you please fill the issue template so we can better understand and reproduce the issue.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
