### ISSUE TITLE
file.isFile is not a function

### ISSUE THREAD

**Issue by Dhakshan** [strapi/strapi#7094]
Hi, 

I am facing the below issue when creating strapi project. Please tell me if something i am missing

npm run develop

> api@0.1.0 develop D:\Clients\strapi\starter-pack\api
> strapi develop

Error while running command develop: file.isFile is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dhakshinamurthy\AppData\Roaming\npm-cache\_logs\2020-07-21T05_34_22_744Z-debug.log

**Comment by nsilvah** [comment]
I have the same problem.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

**Comment by calpa** [comment]
Same problem here

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by calpa** [comment]
I think this problem is solved via upgrade node and npm version to minimum required version, so no need to create new issue.

Problem solved!
