### ISSUE TITLE
An error occurred during models config fetch 

### ISSUE THREAD

**Issue by abulbisht** [strapi/strapi#710]
**Node.js version**:
v 9.6.1
**npm version**:
5.0.3
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
Windows 8.1 

**Do you want to request a *feature* or report a *bug*?**
I'm facing this error once i deploy the project to heroku , 
**What is the current behavior?**
After creating new Content Type , once I've open the new Type , it rejects and says go back to Content Type builder  
**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by lauriejim** [comment]
Can you be more precise on your issue please. I don't understand.

**Comment by abulbisht** [comment]
Actually the problem was with the remote database , not with the strapi 

Thanks

**Comment by ianrose** [comment]
@abulbisht what did you do to solve the issue?
