### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by vinkovsky** [strapi/strapi#7107]
Hi! Your  [documentation](https://strapi.io/blog/nextjs-react-hooks-strapi-restaurants-2) seems to display incorrectly:
please see below
![image](https://user-images.githubusercontent.com/66293881/88133799-2411aa00-cc0d-11ea-8aa1-061e0944e401.png)

It just worked fine yesterday

**Comment by alexandrebodin** [comment]
Hi @vinkovsky Thanks for the heads up. We are goign to fix this asap :) Closing this so we keep only issues with the repo here ;)

**Comment by vinkovsky** [comment]
Yes, ofcourse! Thanks so much
