### ISSUE TITLE
OneToOne relation only deleted on one side after edit

### ISSUE THREAD

**Issue by TheWebsDoor** [strapi/strapi#711]
**Node.js version**:
8.9.3
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.10.2
**Operating system**:
MacOS 10.13.3

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When we save an object which have a OneToOne relation with another, the relation is saved on both sides the first time but when we go back on the object and try to edit (with keeping the relation), it will delete relation on one side (strange but on the other entity, the relation is keeped but not on the edited one).

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Create two entities (for example Book and Category) and create a OneToOne relation between them.
Add a new Category.
Add a new Book with the Category previously created.
Edit the book just created. You'll notice that the relation with its category is good. But try now to edit the name of the book, keep the relation and click on save.
Edit it again, you'll see that the relation disappeared. And even if I try to put it back, it won't work anymore... I have to delete the book to re-create it if I want the relation back.

Category created:
![capture d ecran 2018-02-27 a 19 05 07](https://user-images.githubusercontent.com/3693028/36762408-510341a0-1bf1-11e8-90c6-db530feeb8e6.png)

Add new book:
![capture d ecran 2018-02-27 a 19 05 16](https://user-images.githubusercontent.com/3693028/36762414-5acd6cc4-1bf1-11e8-8fd5-0b925485c399.png)

First time edit just created book:
![capture d ecran 2018-02-27 a 19 05 24](https://user-images.githubusercontent.com/3693028/36762419-62a7ad38-1bf1-11e8-97d6-e9bfff113520.png)

Click on Save.

Then, we I try to edit it again, relation disappeared...
![capture d ecran 2018-02-27 a 19 05 33](https://user-images.githubusercontent.com/3693028/36762429-708d8634-1bf1-11e8-9801-1781a87367c5.png)

That is strange is that the relation still exists on the Category object... And it's not just a front display bug because even in the api we have the relation on only one side.

**What is the expected behavior?**
When we edit an object with a relation, the relation have to remain the same.

**Comment by lauriejim** [comment]
Okay, on entry creation the content manager can detect the category by its id and make the relation but fail on update and add null for the relation.

**Comment by lauriejim** [comment]
After pulling master I tried to reproduce the issue but it works fine. I think @Aurelsicoko fixed it working on polymorphic relations.
Maybe you will confirm it work on your side too.

**Comment by FabAdrien** [comment]
Seems to be good for me. I've got another issue with relations but it's not related to this ticket.
For the moment I can't explain it, @Aurelsicoko is aware of it but I try to find to reproduce it for you guys. Thanks !

**Comment by TheWebsDoor** [comment]
Seems to be good for me. I've got another issue with relations but it's not related to this ticket.
For the moment I can't explain it, @Aurelsicoko is aware of it but I try to find to reproduce it for you guys. Thanks !

**Comment by pedrosimao** [comment]
@lauriejim Polymorphic relations are already working? I am trying this on my models but it won't work. Can I have access to the fix? I could help you with testing and debugging of polymorphic relations.

**Comment by TheWebsDoor** [comment]
@pedrosimao You can pull the `feature/upload` branch. They're still working on it but it's functional :)

**Comment by lauriejim** [comment]
@pedrosimao @Aurelsicoko will answer you on your issue https://github.com/strapi/strapi/issues/750

**Comment by pedrosimao** [comment]
@TheWebsDoor I just saw the branch was merged with the master branch. But I have installed strapi from npm install command. How can upgrade it directly from the github repo, and also what files should I substitute in my "on going" project?

**Comment by TheWebsDoor** [comment]
In order to work on the project, you shouldn't use npm. You have to clone the strapi repo on a distinct folder and build your app in dev mode (setup : [](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md)) 
After that, you'll be able to make changes in the plugins by editing files in packages folder (helper-plugin, content-manager, users-permissions, etc.)

**Comment by pedrosimao** [comment]
@TheWebsDoor thanks. I will try to make some contributions. I have also taken a look at the upgrade guides. To implement the last changes made from "upload" feature branch I just need to copy the "admin" folder of the newDevelopmentProject to my old v3.alpha10.03 project? Or is there anything else that I should substitute?

**Comment by TheWebsDoor** [comment]
Yes you can do that or I think that you can do a symbolic link of the admin folder inside your project
