### ISSUE TITLE
Strapi admin roles&permissions no longer able to click anywhere on row to get into edit screen

### ISSUE THREAD

**Issue by weidox** [strapi/strapi#7112]
Version 3.1.0, worked in 3.0.5.
Now being forced to click on the small edit icon which is next to delete icon - each time feels intimidating. In Collection Types clicking anywhere on row still works to edit.
Maybe this bug should be filled for plugin? Don't know which part is responsible for UI behavior.

**Comment by aksdevac** [comment]
yes it is introduced with new permission change, role support for admin users,  row click should be allowed as edit button is very small & cursor changes to pointer on hover but nothing happens on click.

**Comment by derrickmehaffy** [comment]
@soupette I take it this is what I had mentioned to you in slack.

**Comment by VinitSarvade** [comment]
This seems to be working fine in 3.1.4

**Comment by soupette** [comment]
This issue has been fixed with #7467 . It will be released soon
