### ISSUE TITLE
Impossible to create administrator after upgrading to 3.1.0

### ISSUE THREAD

**Issue by MickaelFondation** [strapi/strapi#7116]
Hi, 

I just upgraded strapi from 3.0.6 to 3.1.0 and I tried to create an administrator through this url **http://localhost:1337/admin/auth/register-admin**

Then when i fill all the fields and validate, nothing append and when I look in the navigator console I have this : 
`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`

So I look into the container log and I have this 
```
[2020-07-22T13:24:23.170Z] error Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/srv/app/node_modules/jsonwebtoken/sign.js:107:20)
    at Object.createJwtToken (/srv/app/node_modules/strapi-admin/services/token.js:32:14)
    at Object.registerAdmin (/srv/app/node_modules/strapi-admin/controllers/authentication.js:133:44)
    at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:76:22
    at async /srv/app/node_modules/strapi-utils/lib/policy.js:68:5
    at async /srv/app/node_modules/strapi/lib/middlewares/xss/index.js:26:9
```

**Comment by derrickmehaffy** [comment]
`error Error: secretOrPrivateKey must have a value`

@MickaelFondation did you add the Admin JWT Secret from the migration guide: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html#_2-define-the-admin-jwt-token

**Comment by MickaelFondation** [comment]
Ha My bad, I couldn't find the document about migration to 3.1.0
Thank you a lot

**Comment by derrickmehaffy** [comment]
No problem 😃
