### ISSUE TITLE
Migrating Model Templates from v.1 to v.3

### ISSUE THREAD

**Issue by pedrosimao** [strapi/strapi#712]
**Strapi version**:
v3 / v1

**Do you want to request a *feature* or report a *bug*?**
I am not sure if you are willing to implement Model Template on v.3.So, I am not sure if this a feature request or just a question.

**What is the current behavior?**
I did build a model in v.1 that had many different "templates". This was very very handy in my use case, since I could relate many different templates type to another table. I have tried to do the same in v.3 but I can't find a way. I was investigating polymorphic relations, but also it is not supported natively by Strapi.

**What is the expected behavior?**
Been able to perfectly migrate Model with many templates to V.3. Eventually could be using polymorphic relations...

**Comment by Aurelsicoko** [comment]
@pedrosimao Did you find a way to do that using the polymorphic relations? It's not in our plan to propose a way to migrate from v1 templates to the v3 in the next weeks. If you really need the template system, you should stay on v1 which is stable and production-ready.
