### ISSUE TITLE
lifecycle hook beforeFindOne(params, populate) cannot alter populate; params works properly.

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#7121]
**Describe the bug**
The lifecycle hook beforeFindOne accepts two arguments;  params, populate. Both should be able to be altered, however when populate comes in as undefined it can’t be changed since [undefined is a primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive).

**Steps to reproduce the behavior**
1. Create a Model using the strapi backend; let’s call it Location. Add an attribute (text) called "label". There are other relations but for the purposes of this bug report they don’t matter.
2. Use the Strapi backend to create a new Locations entry, note the ID of the created content.
3. Implement the beforeFindOne lifecycle method as defined [here](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks); beforeFindOne, See **Code snippets** below to cut and paste.
4. Add two console.log() (or conditional breakpoints) in node_modules/strapi-database/lib/queries/create-query.js here: 
```js
// @ line 64:
const createQueryWithLifecycles = ({ query, model, connectorQuery }) => async (params, ...rest) => {
  // ... [omitted] ...
  if(model.modelName === 'location') { console.log(queryArguments); } // add this line
  await executeBeforeLifecycle(query, model, ...queryArguments);
  if(model.modelName === 'location') { console.log(queryArguments); } // add this line
  // ... [omitted] ...
};
```
5. Using the id you got from step 2 use the Swagger UI to load up the ID: http://localhost:1337/documentation/v1.0.0#/Location/get_locations__id_ 

**Expected behavior**
Both params and populate should be altered by the beforeFindOne(params,populate) lifecycle implementation, only params will be.

**should be**:
```log
# from create-query.js
[{_id: "5ea9c7c22347fb4120555b7d" },undefined] 
# from api/location/models/Location.js
{_id: "5ea9c7c22347fb4120555b7d", label_nin: "some label"}
["contacts.users"] 
# from create-query.js
[{_id: "5ea9c7c22347fb4120555b7d", label_nin: "some label"},['contacts.users']] 
```
**is**: 
```log
# from create-query.js
[{_id: "5ea9c7c22347fb4120555b7d" },undefined] 
# from api/location/models/Location.js
{_id: "5ea9c7c22347fb4120555b7d", label_nin: "some label"} 
["contacts.users"] 
# from create-query.js
[{_id: "5ea9c7c22347fb4120555b7d", label_nin: "some label"},undefined] 
```

**Code snippets**
File: api/location/models/Location.js
```js
module.exports = {
  lifecycles: {
    beforeFindOne: async (params, populate) => {
      _.set(params,'label_nin','some label');
      if(!_.isArray(populate)) { populate = []; }
      populate.push('contacts.users');
      console.log(params);
      console.log(populate);
    },
  }
}
```

**System**

- Node.js version: v12.18.0 
- NPM version: 6.14.4
- Strapi version: 3.0.6 
- Database: MongoDB, 4.0.3
- Operating system: macOS, 10.15.6

**Additional context**
I'm guessing that the spread operator isn’t working as expected with ```..rest``` at line 64 then 67 in create-query.js causing populate to come in as undefined? Then since populate comes in as a [primitive value](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) (undefined) it can’t be altered within the beforeFindOne() implementation.

Thanks for taking a look at this guys. Please let me know if you need any clarification or further input to help you get to the bottom of this.

**Comment by cube-dan** [comment]
Some more info for you guys. 

I can monkey patch in a line right before the call to executeBeforeLifecycle() like so:
```js
  if (queryArguments[1] === undefined) { queryArguments[1] = []; }
  await executeBeforeLifecycle(query, model, ...queryArguments);
```
which allows me to alter the populate arg within my beforeFindOne() implementation properly. 

The only problem ... doing so causes an additional error to raise its ugly head, which I'm not going to bother reporting here since it deserves it's own bug report. ... But if you're all curious now here's the text: "MissingSchemaError: Schema hasn't been registered for model "location". Maybe this is because I'm wiping out the defaultPopulate value that gets set in strapi-connector-mongoose/lib/queries.js?

Anyway, I'm not wanting to derail this bug report with another bug ... forget I said anything about my monkey patch.

**Comment by alexandrebodin** [comment]
Hi @cube-dan thank you fro reporting this !

A way to allow this would be to accept a return array that would be the new arguments I think. This would not be a breaking change but we need to check if it could work.

**Comment by cube-dan** [comment]
Thanks Alex, and thanks for looking at this one. I'm working around the issue right now but It would be nice to be able to fiddle with populate before the findOne has been run. 

**NOTE:** For anyone else hitting a wall with populate in beforeFindOne() I'm cheating by appending the data I need populated to {result} in [afterFindOne(result, params, populate)](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks) using an additional [strapi.query('your-model').find()](https://strapi.io/documentation/v3.x/concepts/queries.html#queries) call.

**Comment by tudorilisoi** [comment]
@cube-dan can you share your model, please?

**Comment by derrickmehaffy** [comment]
should be fine in v4
