### ISSUE TITLE
Admin panel email could be case insensitive

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7128]
**Describe the bug**
Earlier login using username was allowed in strapi admin
**Steps to reproduce the behavior**

1. try login with username & password

**Expected behavior**
It should allow login with username/pass.
Also email should be case insensitive.

**System**

- Node.js version: 12.x 
- NPM version: NA
- Strapi version: 3.1.0 
- Database: MongoDB
- Operating system: Mac

**Additional context**
it was working in previous version.

**Comment by alexandrebodin** [comment]
Hello @aksdevac, 

This change is intended so user don't have to use a username (it is optional) and the real user identifier is the email. We could certainly make the email case insensitive

**Comment by aksdevac** [comment]
@alexandrebodin ok if it is intended then the username field is not useful, I don't see any point of keeping this field in db.

**Comment by derrickmehaffy** [comment]
> @alexandrebodin ok if it is intended then the username field is not useful, I don't see any point of keeping this field in db.

I believe it is more so backwards compatibility with versions pre v3.1.0 as you can still set it in the admin after you login, but it is no longer a required attribute.

+1 to allowing login with it though as a FR

**Comment by aksdevac** [comment]
Yes if login is allowed using it, it would to useful.

**Comment by derrickmehaffy** [comment]
all emails are lowercased in v4, closing
