### ISSUE TITLE
DigitalOcean Droplet image error: secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by nvaken** [strapi/strapi#7135]
**Describe the bug**
Using a new DigitalOcean Droplet with the Strapi image. When opening Strapi for the first time you need to register your super admin. When doing so, the submit button does not seem to respond, when looking at the response of the AJAX request in Chrome's network tab when clicking it another time it tells me that you can't register another super user. So the admin has been created the first time apparently... Weird but okay. 

When then trying to login, the form will present me with a `An internal server error has occurred`. When inspecting the AJAX request again in the Network tab I notice that the response is indeed a 500 HTTP code and no other information is given. Then, when inspecting the logs by using `pm2 logs strapi-development` I notice that there's an error that appears on submit: `secretOrPrivateKey must have a value`. 

I've been using [the documentation](https://strapi.io/documentation/3.0.0-beta.x/installation/digitalocean-one-click.html#controlling-the-strapi-service-and-viewing-logs) but this has not been of help. After a lot of searching through the code in Github, I've found [this migration guide](https://github.com/strapi/strapi/blob/35aafde2288e6858a9b1757cf2555a8561421140/docs/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.md#2-define-the-admin-jwt-token) which fixed my issues.  

**Steps to reproduce the behavior**

1. Setup a new Droplet with the Strapi image on DigitalOcean
2. Register the super admin with the first form (and probably note on this form as well that the submission will fail at this point)
3. Try to login at this point, submit the login form and note that the login fails. 
4. Check the errors in the logs with `pm2 logs strapi-development` and note that the error `Error: secretOrPrivateKey must have a value` will trigger.

**Expected behavior**
The Strapi forms should submit.

**Code snippets**
Complete error with backtrace from logs:

```
0|strapi-development  | [2020-07-23T09:45:44.703Z] error Error: secretOrPrivateKey must have a value
0|strapi-development  |     at Object.module.exports [as sign] (/srv/strapi/strapi-development/node_modules/jsonwebtoken/sign.js:107:20)
0|strapi-development  |     at Object.createJwtToken (/srv/strapi/strapi-development/node_modules/strapi-admin/services/token.js:32:14)
0|strapi-development  |     at /srv/strapi/strapi-development/node_modules/strapi-admin/controllers/authentication.js:35:46
0|strapi-development  |     at dispatch (/srv/strapi/strapi-development/node_modules/koa-compose/index.js:42:32)
0|strapi-development  |     at /srv/strapi/strapi-development/node_modules/strapi-admin/controllers/authentication.js:27:16
0|strapi-development  |     at callback (/srv/strapi/strapi-development/node_modules/koa-passport/lib/framework/koa.js:93:25)
0|strapi-development  |     at Strategy.strategy.success (/srv/strapi/strapi-development/node_modules/passport/lib/middleware/authenticate.js:219:18)
0|strapi-development  |     at verified (/srv/strapi/strapi-development/node_modules/passport-local/lib/strategy.js:83:10)
0|strapi-development  |     at /srv/strapi/strapi-development/node_modules/strapi-admin/middlewares/auth/index.js:16:43
```

**System**

- Node.js version: v12.18.1
- NPM version: 6.14.5
- Strapi version: v3.1.0
- Database: _Trouble with fetching this data_
- Operating system: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-112-generic x86_64)

**Additional context**
N/a

**Comment by alexandrebodin** [comment]
@derrickmehaffy You might need to upgrade the DO droplet

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy You might need to upgrade the DO droplet 

Yup, missing admin hey secret

**Comment by derrickmehaffy** [comment]
@nvaken to quickly fix this, while as the service user navigate to the Strapi project folder and edit the `./config/server.js` then follow these instructions: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html#_2-define-the-admin-jwt-token

After that you should be able to register and admin.

**Comment by nvaken** [comment]
Thanks for the quick acknowledgement and fix!

@derrickmehaffy Thanks, I already found that page as mentioned in the OP and indeed fixed the issue for now.

**Comment by derrickmehaffy** [comment]
High all, I have submitted an updated package to DigitalOcean for review, after they review it you should see it shortly. The version number that will show on the marketplace is `3.1.0` once it's released.

**Comment by Egornator** [comment]
I have the same error after migrating to 3.1.1 per the above-mentioned instructions. I am still on my local development server and not DigitalOcean however.

**Comment by selfagency** [comment]
I am getting this same error locally on my Mac after a fresh install of Strapi 3.1.1 and I've got a token specified in my `.env`.

```
[2020-07-25T18:54:22.187Z] debug POST /admin/login (108 ms) 500
[2020-07-25T18:54:26.125Z] error Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/jsonwebtoken/sign.js:107:20)
    at Object.createJwtToken (/Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/strapi-admin/services/token.js:32:14)
    at /Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/strapi-admin/controllers/authentication.js:35:46
    at dispatch (/Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/koa-compose/index.js:42:32)
    at /Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/strapi-admin/controllers/authentication.js:27:16
    at callback (/Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/koa-passport/lib/framework/koa.js:93:25)
    at Strategy.strategy.success (/Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at verified (/Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/passport-local/lib/strategy.js:83:10)
    at /Users/daniel/code/clients/wisephilanthropy/cms.wisephilanthropy.institute/node_modules/strapi-admin/middlewares/auth/index.js:16:43
```

**Comment by selfagency** [comment]
Sorry I just saw the above comment about migrating to 3.1.

**Comment by lauriejim** [comment]
Thank you @derrickmehaffy for that.

**Comment by tmikaeld** [comment]
I just tried the latest version, package.json says 3.1.1 - the issue is still there.

**Comment by derrickmehaffy** [comment]
> I just tried the latest version, package.json says 3.1.1 - the issue is still there.

Sorry I should clarify, the DO marketplace will show the `3.1.0`, I will be reaching out to DO today to see what the hold up is on replacing our updated version. Currently it's still showing the `3.0.0`

https://marketplace.digitalocean.com/apps/strapi
![image](https://user-images.githubusercontent.com/8593673/88565816-f8663980-cfe9-11ea-8a95-a5323c84c93e.png)

**Comment by derrickmehaffy** [comment]
New release is live, please let us know if you notice any issues:

![image](https://user-images.githubusercontent.com/8593673/88671833-9fef7480-d09b-11ea-8b08-0a1a4d5427af.png)

**Comment by derrickmehaffy** [comment]
Tested myself and seems to work great, going to mark this as closed for now, but if you hit issues please feel free to respond.

**Comment by tmikaeld** [comment]
Thanks, I'll test it myself again later today

**Comment by adigitalthing** [comment]
I ran into the same issue when trying to register the admin user for the first time - **strapi 3.5.0** on a DO droplet (not the 1-click droplet).
- upon registration submit no form feedback is received but the user is registered
```
0|strapi   | [2021-02-24T08:46:49.557Z] debug GET /admin/runtime~main.444d1cb0.js (2 ms) 200
0|strapi   | [2021-02-24T08:46:52.855Z] debug GET /admin/init (4 ms) 200
0|strapi   | [2021-02-24T08:46:52.972Z] debug GET /admin/07109cdae9f760e8d97c89788c9dc9df.png (2 ms) 200
0|strapi   | [2021-02-24T08:46:53.003Z] debug GET /admin/842e7845f3f8e943ff712a39617b6b70.svg (8 ms) 200
0|strapi   | [2021-02-24T09:05:05.009Z] error Error: secretOrPrivateKey must have a value
0|strapi   |     at Object.module.exports [as sign] (/home/stakwe/ami-strapi/node_modules/jsonwebtoken/sign.js:107:20)
0|strapi   |     at Object.createJwtToken (/home/stakwe/ami-strapi/node_modules/strapi-admin/services/token.js:33:14)
0|strapi   |     at Object.registerAdmin (/home/stakwe/ami-strapi/node_modules/strapi-admin/controllers/authentication.js:143:44)
0|strapi   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|strapi   |     at async /home/stakwe/ami-strapi/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
0|strapi   |     at async /home/stakwe/ami-strapi/node_modules/strapi-utils/lib/policy.js:68:5
0|strapi   |     at async /home/stakwe/ami-strapi/node_modules/strapi/lib/middlewares/parser/index.js:48:23
0|strapi   |     at async /home/stakwe/ami-strapi/node_modules/strapi/lib/middlewares/xss/index.js:26:9
0|strapi   | [2021-02-24T09:05:05.011Z] debug POST /admin/register-admin (1417 ms) 500
0|strapi   | [2021-02-24T09:05:18.532Z] debug POST /admin/register-admin (11 ms) 400
```
- upon login: Internal server error
```
0|strapi   | [2021-02-24T09:26:09.303Z] debug GET /admin/main.be4a4234.chunk.js (3 ms) 200
0|strapi   | [2021-02-24T09:26:11.883Z] debug GET /admin/init (45 ms) 200
0|strapi   | [2021-02-24T09:26:11.976Z] debug GET /admin/07109cdae9f760e8d97c89788c9dc9df.png (6 ms) 200
0|strapi   | [2021-02-24T09:26:12.058Z] debug GET /admin/842e7845f3f8e943ff712a39617b6b70.svg (3 ms) 200
0|strapi   | [2021-02-24T09:26:15.418Z] error Error: secretOrPrivateKey must have a value
0|strapi   |     at Object.module.exports [as sign] (/home/stakwe/ami-strapi/node_modules/jsonwebtoken/sign.js:107:20)
0|strapi   |     at Object.createJwtToken (/home/stakwe/ami-strapi/node_modules/strapi-admin/services/token.js:33:14)
0|strapi   |     at /home/stakwe/ami-strapi/node_modules/strapi-admin/controllers/authentication.js:43:46
0|strapi   |     at dispatch (/home/stakwe/ami-strapi/node_modules/koa-compose/index.js:42:32)
0|strapi   |     at /home/stakwe/ami-strapi/node_modules/strapi-admin/controllers/authentication.js:35:16
0|strapi   |     at callback (/home/stakwe/ami-strapi/node_modules/koa-passport/lib/framework/koa.js:93:25)
0|strapi   |     at Strategy.strategy.success (/home/stakwe/ami-strapi/node_modules/passport/lib/middleware/authenticate.js:219:18)
0|strapi   |     at verified (/home/stakwe/ami-strapi/node_modules/passport-local/lib/strategy.js:83:10)
0|strapi   |     at /home/stakwe/ami-strapi/node_modules/strapi-admin/services/passport/local-strategy.js:15:43
0|strapi   | [2021-02-24T09:26:15.419Z] debug POST /admin/login (127 ms) 500
```
I fixed it with the token-generation workaround but I had to also add `const dotenv = require('dotenv'); dotenv.config();` to `server.js` because for some reason the `.env` variable wasn't being read (probably not strapi related).

**Comment by derrickmehaffy** [comment]
That is quite odd the .env wasn't loaded as we added that feature quite some time back :thinking: 

@adigitalthing if you can find the reproduction steps please do let me know.
