### ISSUE TITLE
Wrong conversion of `error` to a boolean value

### ISSUE THREAD

**Issue by agigleux** [strapi/strapi#7141]
Hello,

I scanned the code with [SonarCloud](https://sonarcloud.io/project/issues?id=agigleux_strapi&open=AXN66dJIfJQuxM4e6Z1r&resolved=false&rules=javascript%3AS3403&types=BUG) and discovered this pattern is often used:

`const hasError = error && error !== null;`

I found it complicated to understand and I believe the code is not doing what you expect, especially when `error` is null or undefined.
I think the code could be change to:

`const hasError = !!error;`
or
`const hasError = Boolean(error);`

Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean#:~:text=Do%20not%20use%20a%20Boolean

Reproducer:

```
 var error = {"description": "blabla", "code": 2};
 var hasError = error && error !== null;
 console.log(hasError); // true

 var error = "blabla";
 var hasError = error && error !== null;
 console.log(hasError); // true

 var error = null;
 var hasError = error && error !== null;
 console.log(hasError); // null: while false is expected

 var error;
 var hasError = error && error !== null;
 console.log(hasError); // null: while false is expected
 

 var error = {"description": "blabla", "code": 2};
 var hasError = !!error;
 console.log(hasError); // true

 var error = "blabla";
 var hasError = !!error;
 console.log(hasError); // true

 var error = null;
 var hasError = !!error;
 console.log(hasError); // false

 var error;
 var hasError = !!error;
 console.log(hasError); // false
```

**Comment by soupette** [comment]
Thanks a lot @agigleux for spotting these kind of improvements. Do you mind creating a PR to fix them?
