### ISSUE TITLE
Erro update admin user.

### ISSUE THREAD

**Issue by enovati** [strapi/strapi#7147]
**Expected behavior**
Ideally these field password and password repeats, should not accept autofill on this screen.

**Describe the bug**
On the screen of edit admin user, is auto filling the password, so I need to clear the field before saving, because it ends up saving with the wrong password, or presents error of passwords not equal.  caused by auto-filling the password. .

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by petersg83** [comment]
Hello, thanks for the issue!

Can you please tells us your strapi version?

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
