### ISSUE TITLE
Incorrect datetime type generated in the Documentation plugin

### ISSUE THREAD

**Issue by adi90i7** [strapi/strapi#7149]
**Description**
When generating swagger documentation using strapi-plugin-documentation, we see that for data type "Datetime" swagger documentation generated is also "datetime". This instead according to [OpenAPI](https://swagger.io/specification/#oas-document) standards should be "date-time"

**Steps to reproduce the behavior**

1. Using content-type buider create new data type with a datetime field
2. Build strapi with  strapi-plugin-documentation configured

**Expected behavior**
Should generate swagger documentation with `date-time`

**Screenshots**
![image](https://user-images.githubusercontent.com/10310123/88368646-c9a05700-cd8e-11ea-89c5-0ac4cf907197.png)
![image](https://user-images.githubusercontent.com/10310123/88368805-0ec48900-cd8f-11ea-83b6-cd1c3469d2dd.png)

**System**

- Strapi version: 3.0.0
- strapi-plugin-documentation version: 3.0.0

**Comment by lauriejim** [comment]
Hello! In your screenshot, I can see `datetime` so it's correct no?

**Comment by adi90i7** [comment]
There's a hyphen in between.. it should be `date-time` instead of `datetime` according to openAPI standards.

**Comment by lauriejim** [comment]
OKay thank you for this detail.
Can you please have a look at how the plugin works and submit a PR to fix it.
I will be happy if you can help on this issue.
Thank you.
