### ISSUE TITLE
Renamed collection-type not available in Roles and Permissions

### ISSUE THREAD

**Issue by samOpenforce** [strapi/strapi#7153]
**Description**
Renaming a collection-type in the Admin Panel (in both `Base Settings: Display Name` and `Advanced Settings: Collection Name`) does not provide renamed collection as option in Roles and Permissions, however the collection-type is still present in Roles and Permissions with it's old name.

**Steps**
1. Create collection-type (eg. name: collection-original)
2. Server restart
3. Set Public permissions (find, find-one)
4. Change collection-type name in both Base Settings and Advanced Settings (eg name: collection-renamed)
5. Server restart
4. Check roles and permissions - collection-renamed not shown, collection-original is shown

**Expected behavior**
Renaming a collection-type allows access to the renamed collection-type from roles and permissions

**System**
Official Strapi Docker instance

Happy to provide more detail if required.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
Here is the same topic - https://github.com/strapi/strapi/issues/6837
I m closing this one.
Have a good day.

**Comment by samOpenforce** [comment]
@lauriejim Sorry! I did a search before posting, didn't see this dupe.

**Comment by lauriejim** [comment]
No problem ;)
