### ISSUE TITLE
Strapi: Server wasn't able to start properly.

### ISSUE THREAD

**Issue by Manishkumar2019** [strapi/strapi#7154]
I am facing some problem to connect my MongoDB atlas database to strapi server while creating a flutter related project.

<img width="905" alt="1" src="https://user-images.githubusercontent.com/46292851/88380891-1a32a700-cdc5-11ea-82ea-03f84549b5cc.png">

<img width="921" alt="2" src="https://user-images.githubusercontent.com/46292851/88380915-261e6900-cdc5-11ea-9c3c-adb4b2ecc30a.png">

I have tried many similar issue's solution from the github like changing the host address, timeout setting, etc. 
But none of that worked. 

How can this issue be solved??

**Comment by lauriejim** [comment]
Hello! This is due to the version - 3.6 or later.
There is a warning message into the documentation about that - https://strapi.io/documentation/v3.x/guides/databases.html#mongodb-installation
You must use Version: 2.2.12 or later.
