### ISSUE TITLE
Bug when creating custom plugin : bad config for menu

### ISSUE THREAD

**Issue by filol** [strapi/strapi#7162]
**Describe the bug**

When i generate a new plugin he doesn't appear in menu. The automated configuration file contain a mistake

**Steps to reproduce the behavior**

1. strapi new my-project --quickstart
2. cd my-project && strapi generate:plugin my-plugin
3. yarn develop --watch-admin

No plugin in menu

**Expected behavior**

I should see my new plugin in menu

**Code snippets**
In my-plugin/admin/src/index.js

The menu snippet : 
```
menu: {
      pluginsSection: [
        {
          destination: `/plugins/${pluginId}`,
          icon,
          label: {
            id: `${pluginId}.plugin.name`,
            defaultMessage: name,
          },
          name,
          permissions: [
            // Uncomment to set the permissions of the plugin here
            // {
            //   action: '', // the action name should be plugins::plugin-name.actionType
            //   subject: null,
            // },
          ],
        },
      ],
    },
```

But **pluginsSection** isn't right, it should be **pluginsSectionLinks**

**System**

- Node.js version: v12.4.0
- NPM version: 6.9.0
- Strapi version: 3.1.1
- Database: SQLite
- Operating system: W10

**Comment by lauriejim** [comment]
Thank you for reporting that!
I fixed it.

**Comment by alanhr** [comment]
I'm facing the same problem
