### ISSUE TITLE
Content manager plugin API returns 403

### ISSUE THREAD

**Issue by kcouliba** [strapi/strapi#7172]
**Describe the bug**
Since we upgraded to version 3.1.0, we receive a response 403 when hitting route `/content-manager/explorer/:model` (and subsequently any subroute)

**Steps to reproduce the behavior**
1. Start a fresh install (using docker for example)
2. Have at least one content type
3. Provide a role of your choice with all Contentmanager permissions in the Content Manager section
![image](https://user-images.githubusercontent.com/6125608/88461714-2a6e8300-cea6-11ea-94fd-4728ac30af2b.png)
4. Save the changes
5. Try hitting on your content type `/content-manager/explorer/:model` where model is your content type uid
6. Receive a 403 error code

**Expected behavior**
API call should return a list of content (maybe an empty list if there are no data in the targeted content type)

**Screenshots**
![image](https://user-images.githubusercontent.com/6125608/88461787-e7f97600-cea6-11ea-9712-dd8405b549af.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.0
- Database: Postgres SQL
- Operating system: ubuntu 20.04

**Comment by lauriejim** [comment]
Hello thank you for reporting this.
I suspect something about that...

@alexandrebodin since we introduced admin permission on plugins route (so for the admins) 
what happen if I open Content Manager route to a user?
Look like I will be blocked. Can you confirm it's related to that point?

**Comment by alexandrebodin** [comment]
Yes these routes require an admin user to be logged in to be called. 

They should not be listed in the users-permissions plugin and will eventually be removed as this are dedicated to the admin panel.

**Comment by kcouliba** [comment]
Thanks for the explanation, that was very convenient since it allowed us to have permissions on about most content in the app.
