### ISSUE TITLE
Mongoose push method is not working for the arrays, which created using JSON input field.

### ISSUE THREAD

**Issue by tmKamal** [strapi/strapi#7175]
**Describe the bug**
I have tried to add an element to an existing array created by JSON input field. Push method works as expected and the element is also added to the array without any errors. but when saving, it doesn't save in the MongoDB database and also no error is shown in the console. All other updated fields successfully store in the DB. Then I tried to update repeatable components using push() method. it works fine for the repeatable components. 

**Steps to reproduce the behavior**

1.  Create a new collection type.
2.  Add a JSON data field to it.
3.  Create a new entry using this created collection type. (Inhere, create a simple array in the JSON data field.)
4. Then create a custom controller to handle the update method of this collection type.

**Expected behavior**
Successfully updated array in the MongoDB database.

**Code snippets**

controller
```js
const { sanitizeEntity } = require("strapi-utils");

module.exports = {
  /**
   * Retrieve records.
   *
   * @return {Array}
   */

  async up(ctx) {
    const { id } = ctx.params;
    const result = await strapi.query("test").model.findById(id).exec();

    if (result) {

        console.log(result.jsonArr);
        let added = result.jsonArr.push("three");
        console.log(result.jsonArr);
        console.log(added);
        result.description=ctx.request.body.description;
        await result.save();
 
    }
    return result;
  },
};
```

model
```js
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "name": "test"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "jsonArr": {
      "type": "json"
    },
    "description": {
      "type": "text"
    }
  }
}
```
**Screenshots**

Collection type
![03](https://user-images.githubusercontent.com/37587194/88465320-9faa7a00-cedf-11ea-90cf-4c6d1638844e.PNG)

Console output
![06](https://user-images.githubusercontent.com/37587194/88465420-8229e000-cee0-11ea-9972-71b72a0ea846.PNG)

Update Request [Postman]
![01](https://user-images.githubusercontent.com/37587194/88465339-d6809000-cedf-11ea-9ecc-4e90d28c2650.PNG)

find Request [Postman}
![2](https://user-images.githubusercontent.com/37587194/88465354-f1eb9b00-cedf-11ea-9d47-d12d8f8e83bd.PNG)

MongoDB
![04](https://user-images.githubusercontent.com/37587194/88465365-15aee100-cee0-11ea-8299-ee104b4f86fa.PNG)

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: MongoDB Atlas
- Strapi-connector-mongoose: 3.0.5,
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! 

If you are doing something like this, doest it work?

```js
const { sanitizeEntity } = require("strapi-utils");

module.exports = {
  /**
   * Retrieve records.
   *
   * @return {Array}
   */

  async up(ctx) {
    const { id } = ctx.params;
    const result = await strapi.query("test").findOne({id});

    if (result) {
        let added = result.jsonArr.push("three");
        result.description = ctx.request.body.description;
        await strapi.query("test").update({id}, result);
    }

    return result;
  },
};
```

Here you are using pre-build `query` functions to findOne and update.

**Comment by tmKamal** [comment]
@lauriejim, Thank you for your quick reply.
Your solution works like a charm. 
From now on, I will focus on pre-build query functions more!

**Comment by derrickmehaffy** [comment]
Marking as closed, as @tmKamal confirmed the solution.
