### ISSUE TITLE
Not possible to login to admin. 500 internal server error

### ISSUE THREAD

**Issue by ssuvorov** [strapi/strapi#7176]
**Can't login on /admin page after an update**
We use Heroku + postgres.

With old dependencies: To log in we used a username "root"
I updated libs, deployed. After the page was reloaded now an email is requested instead of a username.
Even if I enter an email or use a reset psw functionality it doesn't work.

Log in returns 500 An internal server error occurred 
Reset psw returns 400.

old deps: 
```json
"dependencies": {
    "editorjs-html": "^2.0.0",
    "knex": "<0.20.0",
    "pg": "^8.2.1",
    "strapi": "3.0.0",
    "strapi-admin": "3.0.0",
    "strapi-connector-bookshelf": "3.0.0",
    "strapi-plugin-content-manager": "3.0.0",
    "strapi-plugin-content-type-builder": "3.0.0",
    "strapi-plugin-email": "3.0.0",
    "strapi-plugin-upload": "3.0.0",
    "strapi-plugin-users-permissions": "3.0.0",
    "strapi-utils": "3.0.0"
  },
```

new deps
```json
"dependencies": {
    "editorjs-html": "^2.0.0",
    "knex": "^0.21.2",
    "pg": "^8.2.1",
    "strapi": "^3.1.1",
    "strapi-admin": "^3.1.1",
    "strapi-connector-bookshelf": "^3.1.1",
    "strapi-plugin-content-manager": "^3.1.1",
    "strapi-plugin-content-type-builder": "^3.1.1",
    "strapi-plugin-email": "^3.1.1",
    "strapi-plugin-upload": "^3.1.1",
    "strapi-plugin-users-permissions": "^3.1.1",
    "strapi-utils": "^3.1.1"
  },
```

that's the only difference.

**System**
"node": ">=13.0.0",
"npm": ">=6.0.0"

**Comment by lauriejim** [comment]
Hello! Did you followed the migration guide?
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html
there is a section that talk of the JWT for the admin. An update is required.
And yes now you have to use the email to login to the admin.

**Comment by ssuvorov** [comment]
@laurenskling Ah, thanks. I expected something like that. Checked releases. There is no **Breaking changes** section :(
Also was trying to find a migration manual, but couldn't.

I'll try to do a migration

<img width="522" alt="Screenshot 2020-07-26 at 00 05 50" src="https://user-images.githubusercontent.com/3448821/88467133-fe69f680-ced3-11ea-9a61-b011b14a616b.png">

**Comment by ssuvorov** [comment]
Works! Thanks
