### ISSUE TITLE
RichText Double Quote not escaped

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [strapi/strapi#7182]
**Describe the bug**
RichText Double Quote not escaped, causing client to have errors when calling api data.

**Steps to reproduce the behavior**

1. Go to Admin
2. Click on Add Content Field (which uses richText)
3. See Error 

description: "...work tirelessly to bring **"the Martian"** home, while his crewmates concurrently plot a daring, if not impossible rescue mission. As these stories of incredible bravery unfold, the world comes together to root for Watney's safe return. ",

**Expected behavior**
Anything typed with double quote in the richText should have escape like this:  **to bring \\"the Martian\\" home,**

**Screenshots**
N/A 

**Code snippets**
N/A

**System**

- Node.js version:  v12.13.0
- NPM version: 6.14.6
- Strapi version:  3.0.6
- Database: Prosgres
- Operating system: LinuxMint 20

**Additional context**
Is there any trick to fix this, such as installing extra library or plugin that I don't know yet?

**Comment by lauriejim** [comment]
Hello I just tried with the last version of Strapi `3.1.1` + Postman as client and it's escaped.
It's the same in my browser. I think you will have to manage that in your front end side.
The lib will depend of your frontend tech. But you will be able to find a lid to escape everything.
