### ISSUE TITLE
Entries can't be saved when boolean field is set as required

### ISSUE THREAD

**Issue by stiveurkel** [strapi/strapi#7186]
**Describe the bug**
Whenever I edit an entry where the collection has a boolean field with `required: true`, I can't save the entry.
I get the error message "This field is required", I try to toggle it with no success. Then if I change the boolean field to `required: false` it works.

Note: I didn't change the model and it worked before migrating

**Steps to reproduce the behavior**

1. Go to a collection list view
2. Click on any entries to edit the data
3. Edit a field
4. Try to save
5. You get an error that the boolean field is a required field, even though it is selected

**Expected behavior**
The entry is supposed to be saved because the boolean field was already selected when attempted to save the entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/42664988/88485892-0aa88f00-cf7a-11ea-8eba-616496a08918.png)

**System**
- Node.js version: v12.13.1
- NPM version: 6.14.6
- Strapi version: 3.1.1
- Database: Postgresql 12.3
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
I can confirm this on v3.1.1

- Create a new project with a model (at least 1 bool set required, any default)
- Make an entry with any bool value
- Save then try to edit and change bool value
- See error

**Comment by derrickmehaffy** [comment]
[testbool_project.zip](https://github.com/strapi/strapi/files/4978185/testbool_project.zip)

Attached a test project

**Comment by pjamieson** [comment]
Issue remains in 3.1.2.
