### ISSUE TITLE
Migration from 3.0.6 to 3.1.1 caused custom user controllers error:  Error creating endpoint post /users: handler not found

### ISSUE THREAD

**Issue by andylacko** [strapi/strapi#7196]
### Describe the bug

this is how my `api/user/controllers/user.js` looks like

```javascript
'use strict';

module.exports = {
  getUser: async ctx => {
    ctx.send('controlled by GraphQl')
  },
  getPortalSession: async ctx => {
    ctx.send('controlled by GraphQl')
  },
}
```

after upgrading to **3.1.1** can't start server, error
```
Error creating endpoint post /users: handler not found "user.create"
```
is shown also when cleaned cache. It seems like it's not extending the object, but replacing with custom defined by me

### Steps to reproduce the behavior

1. npx strapi generate:controller user 
2. create custom controller function
3. run server

### Expected behavior
to run server and be able to set permissions in admin

### System

- Node.js version: 14.6.0
- NPM version: 6.14.7
- Strapi version: 3.1.1
- Database: sqlite
- Operating system: Mac Os

**Comment by derrickmehaffy** [comment]
`Node.js version: 14.6.0`

Please downgrade your node version to the latest supported LTS (v12) and test again

**Comment by andylacko** [comment]
downgraded to `v12.18.3`, still ``` error Error creating endpoint post /users: handler not found "user.create"
``` shows, no difference

**Comment by lauriejim** [comment]
Thank you for reporting this issue. Related to the API name probable - conflicting with the User model in the Users & Permissions plugin I guess.

@alexandrebodin Can you please confirm it's related to that.
I can confirm it was possible before.
Should we convert this as an issue @alexandrebodin ?

**Comment by alexandrebodin** [comment]
@andylacko do you have a routes.json file to share ?

**Comment by andylacko** [comment]
@alexandrebodin , I have no `routes.json` file inside `user/config` folder, we only use graphQl

**Comment by alexandrebodin** [comment]
OK @andylacko I can make a fix for this issue but I would still recommend you rename the controller to my-user.js to avoid any conflict with the admin users :)

**Comment by andylacko** [comment]
oh nice, I see what you mean, will rename it 👌
