### ISSUE TITLE
strapi-plugin-users-permissions: unable to configure jwtSecret using .env variables

### ISSUE THREAD

**Issue by haschu** [strapi/strapi#7199]
**Describe the bug**
Using environment variables in `extensions/users-permissions/config/jwt.js` fails with:

*Error creating endpoint get /xyz: Could not find policy "plugins::users-permissions.permissions"*

**Steps to reproduce the behavior**

Update `extensions/users-permissions/config/jwt.js` from:

```js
module.exports = {
  jwtSecret: process.env.JWT_SECRET || 'generated-secret-string'
};
```

to:

```js
module.exports = ({ env }) => ({
  jwtSecret: env('USER_JWT_SECRET')
});
```
and add `USER_JWT_SECRET` to `.env`

**Expected behavior**
It should use the jwtSecret from the `.env`-File

**System**

- Node.js version: 
- NPM version: v6.13.4
- Strapi version: 3.1.1
- Database: PG v12.3
- Operating system: macOS

**Comment by alexandrebodin** [comment]
Hello @haschu  you cannot use this syntax outside of the config folder. You need to keep the first implementation. And you will be able to access any variable in the .env just not with env() 

Closing as it is normal. Let us know if you still cannot make it work :)

**Comment by haschu** [comment]
Ah, okay. I thought that this syntax can be used in any config directory. Thanks anyway :)

**Comment by alexandrebodin** [comment]
If you want to you can move this config to a ./config/plugins.js file so you can use the syntax btw.

You would need to create:

`./config/plugins.js
```js
module.exports = ({ env }) => ({
 'users-permissions': {
     jwtSecret: env('USER_JWT_SECRET')
 }

});
```

**Comment by haschu** [comment]
Thanks for that tipp!
