### ISSUE TITLE
hook:mongoose takes too long to load

### ISSUE THREAD

**Issue by rroblik** [strapi/strapi#720]
**Node.js version**:
`v8.9.4`

**npm version**:
`5.6.0`

**Strapi version**:
`3.0.0-alpha.9.2`

**Operating system**:
`Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux `
(inside Vmware, Windows 8 host, shared folder)

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`strapi start` sometimes return ERROR `(hook:mongoose) takes too long to load` on my (a little) slow machine

**What is the expected behavior?**
`strapi start` return no ERROR, even on a slow machine (like mine!) thanks to a `timeout` parameter (or something similar) 
```bash
strapi start --timeout=60
```

Regards

**Comment by Aurelsicoko** [comment]
@rroblik Try to update the `./config/hook.json` file like that:

```json
{
  "timeout": 100000,
  "load": {
    "order": [
      "Define the hooks' load order by putting their names in this array in the right order"
    ]
  }
}
```

**Comment by rroblik** [comment]
Oops did I missed a documentation about that ?
**With that now it's working fine :)** 

I think this issue can be closed, except is an inline parameter can be useful (?).

Regards
