### ISSUE TITLE
Policy not running after GraphQL resolver, only before

### ISSUE THREAD

**Issue by romanmandryk** [strapi/strapi#7202]
**Describe the bug**
This started  as a discussion - https://github.com/strapi/strapi/discussions/6692#discussioncomment-42619
Basically in REST API policies behave like composable middleware - you can run code before the resolver, then `await next()` and run other code after resolver. With GraphQL, the behaviour is different - policies run only before the resolver. The problem is [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/resolvers-builder.js#L48) (and other 3 similar occurences)

**Steps to reproduce the behavior**

1. Create a simple global policy `mypolicy.js`
```
module.exports = async (ctx, next) => {
  console.log('before');
  await next();
  console.log('after');
};
```
2. Apply this policy to any GraphQL route in schema.graphql.js. E.g. on user:
```
module.exports = {
  resolver: {
    Query: {
      users: {
        policies: ['global::mypolicy'],
        resolver: 'plugins::users-permissions.User.find'
      }
  }
}
```
3. add `console.log('resolver')` in `User.find` controller
4. Execute the query

**Expected behavior**
See the sequence of logs. It should be **before, resolver, after**. Instead it's **before, after, resolver**

**Screenshots**
N/A

**Code snippets**
See above

**System**

- Node.js version: v12.16.2
- NPM version: 6.14
- Strapi version: 3.1.1
- Database: Postgres
- Operating system: Mac

**Additional context**
N/A

**Comment by alexandrebodin** [comment]
Hi @romanmandryk thank you for reporting this. Indeed this is not how the policies work with graphql for now. We these policies have a koa like syntaxe this wouldn't work correctly with graphql like the typical graphql middlewares. 

We will need to make changes to the policies so they behave the same for REST and GRAPHQL or split them into two different kinds of policies. Right now there is no easy solution.

**Comment by acarrera94** [comment]
I believe this is related: [discussion](https://forum.strapi.io/t/sharing-context-ctx-between-middleware-and-policies-and-controllers-6692/1771/2)

**Comment by derrickmehaffy** [comment]
fixed in v4
