### ISSUE TITLE
strapi.io blog does not work (504)

### ISSUE THREAD

**Issue by super-kamil** [strapi/strapi#7203]
https://strapi.io/blog/announcing-strapi-4m-seed-funding-round -> 504 ERROR

**Comment by alexandrebodin** [comment]
hi @super-kamil  Thank you for reporting but this not really the place for it. Make sure to notify us on slack for these kind of things ;) 
We fixed it

**Comment by super-kamil** [comment]
I tried to use the contact form on the website but there was too much data needed :)
