### ISSUE TITLE
Impossible to use a new custom authentication provider

### ISSUE THREAD

**Issue by madarche** [strapi/strapi#7206]
**Describe the bug**

Impossible to use a new custom authentication provider.

I have followed the documentation https://strapi.io/documentation/v3.x/plugins/users-permissions.html#adding-a-new-provider-to-your-project

The code of my custom authentication provider is available in the repository https://github.com/madarche/my-project with each step in a separated commit (https://github.com/madarche/my-project/commits/master) :

1. Initial commit
2. Copy from `node_modules`
3. Add missing file from the documentation
4. Add new custom OIDC provider

Related discussions, but with no replies:
* https://github.com/strapi/strapi/discussions/6455
* https://github.com/strapi/strapi/discussions/6584

Related issue:
* https://github.com/strapi/strapi/issues/891 with the associated
  repository https://github.com/abdonrd/strapi-demo but obsolete because it's 2 years old

The fact that there are people having problems creating such a new authentication provider, with no online example of a working new custom authentication provider can be seen as an issue in itself. Understanding *Purest* REST API Configuration is hard. But maybe the issue is not only the need for more doc, maybe is there a bug behind?

**Steps to reproduce the behavior**

1. Setup the new authentication provider as specified by the doc
2. See that the new provider is successfully available in http://localhost:1337/admin
3. Enable the new provider
4. Then with a browser visit URL http://localhost:1337/connect/myoidc
5. See browser being redirected to
http://localhost:1337/auth/myoidc/callback?error=Grant%3A%20missing%20or%20misconfigured%20provider
with the following JSON response:

    ```
    statusCode	400
    error	"Bad Request"
    message
    message	"No access_token."
    data
    message	"No access_token."
    ```

**Expected behavior**

The authentication provider should be contacted and the browser should be redirected to the provider's login form.

**Screenshots**

[The new provider is successfully available in http://localhost:1337/admin](https://github.com/madarche/my-project/blob/master/Screenshot_2020-07-26-Strapi-Roles_Permissions.png)

**Code snippets**

https://github.com/madarche/my-project

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.1
- Database: SQLite
- Operating system: Debian GNU-Linux 9 (stretch)

**Additional context**

Before creating this issue I've been trying to use a custom authentication provider with different versions of Strapi: 3.0.x, 3.1.0. 3.1.1 without success.

My custom authentication provider is an *OpenID Connect* provider, but that has no impact whatsoever since this *OpenID Connect* provider is never contacted by Strapi.

I've been able to successfully access the GitHub login form without problem when I enabled the bundled `GitHub` provider.

**Comment by petersg83** [comment]
Hi,
Just to enrich the discussion. I've made 2 PRs to clarify the doc and to simplify the example app. Maybe it can help.
You can see them there: 
- https://github.com/strapi/strapi/pull/7132
- https://github.com/strapi/strapi-examples/pull/164

**Comment by madarche** [comment]
Thanks @petersg83! Your PRs are clearly addressing this issue!

**Comment by madarche** [comment]
@petersg83 do you know how I could easily recreate a Strapi project using your https://github.com/strapi/strapi/tree/fix/loginProviders branch?

**Comment by petersg83** [comment]
Nice :)
Yes, in the root directory run `yarn setup`, then `cd examples/getstarted/` and `yarn develop`.
And if you want to better see the doc, `cd docs`, `yarn install`, `yarn dev`

**Comment by madarche** [comment]
Hello @petersg83! Thanks a lot for the detailed instructions :+1: I've done just that and I can test Strapi directly from your `fix/loginProviders` branch. Very useful! Thanks again :pray: 

Now the sad news: I've got the exact same error on the `fix/loginProviders` branch as with Strapi  3.0.x, 3.1.0. 3.1.1, :cry: 

```
statusCode	400
error	"Bad Request"
message
message	"No access_token."
data
message	"No access_token."
```

And again my authentication provider located at https://myoidc.local.test/ is **never** accessed/contacted by Strapi.

The problem lies with a needed `access_token` …

**Comment by madarche** [comment]
@petersg83 I've had already read your improvements to the doc in the diffs, and it looks even better when the doc is built. That will help many developers for sure :+1:

**Comment by petersg83** [comment]
Thank you :)

Can you please show the requests made in the network console of your browser when you try to connect?
And can you add a log here : https://github.com/madarche/my-project/blob/master/extensions/users-permissions/services/Providers.js#L408 to show the value of the access token?

**Comment by madarche** [comment]
@petersg83 the `access_token` error stems from here https://github.com/madarche/my-project/blob/master/extensions/users-permissions/services/Providers.js#L30. The program doesn't have the chance to go beyond and up to https://github.com/madarche/my-project/blob/master/extensions/users-permissions/services/Providers.js#L408

And here is a screenshot of the network console:
https://github.com/madarche/my-project/blob/master/network_console.png

**Comment by madarche** [comment]
I'm a bit puzzled that an `access_token` is needed at https://github.com/madarche/my-project/blob/master/extensions/users-permissions/services/Providers.js#L30 so early in the authentication process…

Based on https://github.com/strapi/strapi/blob/fix/loginProviders/docs/v3.x/plugins/users-permissions.md#understanding-the-login-flow, I'm indeed stuck at point *"2. The frontend redirect the tab to https://strapi.website.com/connect/github that calls the backend"*, while the `access_token` should come into play only later at point *"5. The backend uses the given code to get from Github an access_token"*…

**Comment by petersg83** [comment]
Thank for the details.
Would you mind recording the problem while you're having it and showing the details from each network request?
Or maybe we can have a call while you're showing me so we can spot what's wrong? You can send me an email to schedule it at pierre.noel@strapi.io :)

**Comment by madarche** [comment]
@petersg83 about "recording the problem", would an [HAR export](https://en.wikipedia.org/wiki/.har) do the job?

**Comment by madarche** [comment]
As seen with @petersg83 today (thanks again :+1: ) the temporary conclusion is:

It's possible to add custom authentication providers to Strapi **but only as long as they are in the [Grant](https://github.com/simov/grant) predefined providers.**

So I think this issue should stay open, because it's impossible to use a totally custom (and for example private or not known to the public) authentication provider.

Now I'll see if it's possible to do a work-around and potentially make a PR, and I'll report here.

**Comment by petersg83** [comment]
Thanks for this conclusion :)
I think something can be done with https://github.com/simov/grant-oidc or with the conf variables of the `Authorization server` part there: https://github.com/simov/grant#configuration-description.

In the meantime i'll update the doc to specify that only grant supported providers are handled.
If it's ok for you, for clarity, can you open a new issue as a "feature request" ? And I would close this issue :)

**Comment by madarche** [comment]
Yes I'm investigating on https://github.com/simov/grant-oidc and https://github.com/simov/grant#configuration-description!

And OK to close this issue :+1:

**Comment by petersg83** [comment]
Thanks :)

**Comment by veerjainATgmail** [comment]
Hello All, Im facing the same issue.. "{"statusCode":400,"error":"Bad Request","message":{"message":"No access_token."},"data":{"message":"No access_token."}}" with github provider.  (fetch('http://localhost:1337/auth/github/callback?)

https://github.com/strapi/strapi/blob/master/docs/v3.x/plugins/users-permissions.md
In the documentation
1) Google configuration - not able to configure for localhost:3050. Google insisting without ports. I guess, the workflow has changed after the earlier doc.
2) 
![image](https://user-images.githubusercontent.com/13132206/89608088-bebaeb80-d891-11ea-906a-8510d517978c.png)

this example is outdated. Good to see new application example is in progress.

**Comment by madarche** [comment]
@petersg83 I've finished to investigate and test, and Strapi **actually does work with any custom authentication provider**, even if it is not a *Grant* predefined provider.

I have updated https://github.com/madarche/my-project to document this for all interested parties.

The less obvious part was to totally define the *Grant* config as it is not an existing predefined *Grant* config:
https://github.com/madarche/my-project/commit/f7a5a337ebe252922110ebbb454572457da27cf0

I'll be happy to proof-read and update the Strapi documentation on this subject in your MR or after your MR is merged. Please tell me.

**Comment by petersg83** [comment]
Thanks for your digging!
@derrickmehaffy @lauriejim A documentation update may be needed for the next users wanting to use the authentication provider for providers other than Grant predefined providers. Can I let you handle this? I can help if some more explanation is needed

**Comment by derrickmehaffy** [comment]
@petersg83 @lauriejim we can certainly include some additional documentation for it, but the current docs:

https://strapi.io/documentation/v3.x/plugins/users-permissions.html#adding-a-new-provider-to-your-project

> Only providers handled by grant are supported.

We mention that only grant provided ones **are supported** meaning for bug reports or issues with providers that grant doesn't support, is that something we should be. I'm looking at this from the perspective from other providers we have for other systems (email, upload, ect) we only support our packages and not custom ones by the community (I'm using support here in the context of github issues, ect. Not that they wouldn't work, but that we can't help with them).

@madarche did you have some thoughts on what you would like to see in the docs update or if you want to you can open a PR to give us some idea?

**Comment by baermathias** [comment]
@derrickmehaffy I think the following url should be mentioned in order to indicate that it is possible to create **real custom providers**: https://github.com/simov/grant#misc-custom-providers 

Maybe also the wording should be different: 

`Custom Providers` --> for completely custom providers (https://github.com/simov/grant#misc-custom-providers ), which would include to add a key for it in the configuration etc. Also a working example with a little explanation of what those keys mean would be great!

`Grant OAuth Proxy Providers` or `Pluggable Providers` --> to point out this list https://github.com/simov/grant#200-supported-providers--oauth-playground

**Comment by derrickmehaffy** [comment]
@baermathias we are hesitant to really put a lot of time investment into the grant/purest documentation simply because we plan to move the users-permissions plugin over to passport.js and ditch grant/purest entirely. For the moment we are only "holding" out until the Strapi product/eng team can dedicated the time to do the major refactoring to that plugin.

**Comment by baermathias** [comment]
@madarche I have the same problem even after defining the `access_url` like you did in your project https://github.com/madarche/my-project/commit/f7a5a337ebe252922110ebbb454572457da27cf0.

In my case I have also the problem, that `Providers.js` doesn't console log anything. If I put the following line into the code, I see nothing in the console even if it should fire when I visit `localhost:1337/connect/myprovider`, correct?

```
const getProfile = async (provider, query, callback) => {
  console.log('Providers.js getProfile before access_token')
  // ...
```

**Comment by baermathias** [comment]
@madarche I am facing the same challange and I am stuck at step 5 of the login flow (https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers):
> 5. The backend uses the given code to get from Github an access_token that can be used for a period of time to make authorized requests to Github to get the user info (the email of the user of example

`my_custom_provider` intiates the callback as follows:
http://localhost:1337/connect/my_custom_provider/callback?code=z71D3Sz83hTctv84WBwD

Then the strapi backend redirects me to the frontend, where I want to handle further steps, but it passes an error instead of the access_token:
http://localhost:8080/auth/my_custom_provider/callback?error=invalid_request&error_description=not%20all%20parameters%20set&error_uri=none

@derrickmehaffy @madarche could you help me to find the place inside the strapi code, where according to step 5 the `code=z71D3Sz83hTctv84WBwD` is exchanged against an `access_token`?

**Comment by baermathias** [comment]
> @baermathias we are hesitant to really put a lot of time investment into the grant/purest documentation simply because we plan to move the users-permissions plugin over to passport.js and ditch grant/purest entirely. For the moment we are only "holding" out until the Strapi product/eng team can dedicated the time to do the major refactoring to that plugin.

@derrickmehaffy Just wanted to hear if there are any news on moving the users-permissions plugin over to passport.js ?

**Comment by derrickmehaffy** [comment]
> > @baermathias we are hesitant to really put a lot of time investment into the grant/purest documentation simply because we plan to move the users-permissions plugin over to passport.js and ditch grant/purest entirely. For the moment we are only "holding" out until the Strapi product/eng team can dedicated the time to do the major refactoring to that plugin.
> 
> @derrickmehaffy Just wanted to hear if there are any news on moving the users-permissions plugin over to passport.js ?

No news yet, but we do still want to just not sure if we will have time right now with the v4 development starting (lots of work to do).

Most likely it won't happen until we develop the native API-token feature which will become the default auth method for end-users and making the users-permissions plugin optional. To do that we would need to rewrite/refactor the users-permissions plugin which would be the best opportunity to swap that out.
