### ISSUE TITLE
Unable to use different connections with created_by and updated_by attributes

### ISSUE THREAD

**Issue by dustinkremer** [strapi/strapi#7209]
**Describe the bug**

When using a different connection for a custom collection, it is not possible to query or add new objects to the collection because of the following error message: 
_MissingSchemaError: Schema hasn't been registered for model "AdminUser"._

My goal is to have a database connection for my custom collections, separated from the database which contains strapis default collections (such as users/roles/etc.)

**Steps to reproduce the behavior**

1. Create a clean new strapi application **(3.1.1)**
2. In "/config/database.js" create a second database connection (i.e. "secondary")
3. Create a new collection type (i.e. "contractor")
4. In "/api/contractor/models/contractor.settings.json" add a property "connection" with value "secondary"
5. Restart server and open the admin UI. Then try to add an object to the collection "contractor"
6. The following error is returned to the client:

`{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Schema hasn't been registered for model \"AdminUser\".\nUse mongoose.model(name, schema)","message":"Schema hasn't been registered for model \"AdminUser\".\nUse mongoose.model(name, schema)"}]}],"data":[{"messages":[{"id":"Schema hasn't been registered for model \"AdminUser\".\nUse mongoose.model(name, schema)","message":"Schema hasn't been registered for model \"AdminUser\".\nUse mongoose.model(name, schema)"}]}]}`

**System**

- Node.js version: 12.6.1
- NPM version: 6.13.4
- Strapi version: 3.1.1
- Database: MongoDB Atlas
- Operating system: Windows/Google Cloud Run

**Additional context**
While digging deeper into the mongoose connector for mongo and mongoose itself I was asking myself the question why the newly added associations for "created_by" and "changed_by" are obviously referencing an **ADMIN** user and not a user from the **users-permissions** plugin?

**Comment by alexandrebodin** [comment]
Hi @dustinkremer. We never really consider your usecase until now. Cross DB relations is not really something easy or even possible. We could maybe try to allow disabling the created_by and updated_by fields but this won't be easy...

created_by and updated_by are new fields added to support the role based access control in the Admin panel hence the realtion to admin user and not users-permissions users. 

Hope this helps understanding how it works. 

I'll mark this as a feature request for now so we can consider how we could support this.

**Comment by dustinkremer** [comment]
Hi @alexandrebodin. Thanks for your quick reply! I understand that cross db functionality is not an easy topic which needs to be tackled for different databases.

As far as I understand from the mongoose documentation [cross database populates](https://mongoosejs.com/docs/populate.html#cross-db-populate) are supported in general and would maybe only need a change within the schema definition you are generating in the strapi-connector-mongoose plugin. That could be a quick win? :-)

As you've already marked this as a feature request, I'd like to not only ask for cross database relations, but also for cross application relations in order to support micro service architectures (using the anti-corruption layer pattern).

Just disabling the relation won't help in our case because we'd also like to use the creation based authorization later using strapi EE and I'm pre-evaluating basic micro service functionality.

**Comment by alexandrebodin** [comment]
That is a really interesting comment :D I'll check the specific inside mongoose :) For the micro service approach I think that this could be really great but will need a huge architecture revisit :D I will keep that in mind for future major version ;)

**Comment by dustinkremer** [comment]
Thank you, that would be much appreciated 👍 
Is there maybe another option right now I've overseen which supports some kind of application structuring, like i.e. sub modules? I'm struggling to put all of my collections into one database as that complicates maintenance and development.

**Comment by alexandrebodin** [comment]
What do you think about when you say sub modules ?

**Comment by gtamas** [comment]
@alexandrebodin 
For me, the ability of turning these fields on and off would be enough. (created_by, updated_by).
Is this possible somehow? I can't see any API / options for this in the docs

**Comment by alexandrebodin** [comment]
@gtamas Turning these fields of would break the admin panel as we introduce the permission feature we need to have those infos sadly. DO you need them to be remove or just not present in the API responses ?

**Comment by gtamas** [comment]
I just don't want them to be in the response. They also appear now everywhere in the docs (Swagger), but those don't actually exist in my data models. So it's kinda confusing. I mean, now Swagger shows them in all models.

**Comment by alexandrebodin** [comment]
> I just don't want them to be in the response. They also appear now everywhere in the docs (Swagger), but those fields don't actually exist in my data models. So it's kinda confusing. I mean, now Swagger shows them in all models.
> @alexandrebodin

Ok I understand. We can improve this to remove them from the APIs at some point for sure :)

**Comment by alexandrebodin** [comment]
Closing in favor of https://github.com/strapi/strapi/issues/7177 so we keep things clean in the issues
