### ISSUE TITLE
Admin User Fails to Delete Normal User

### ISSUE THREAD

**Issue by christroutner** [strapi/strapi#722]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.8.3

**Operating system**: Ubuntu 16.04 LTS

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
500 internal server error when admin user tries to delete normal user.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Wipe MongoDB to ensure you are starting with a clean environment:

* `mongo`
* `use strapi;`
* `db.dropDatabase();`
* `exit;`

2. Clone the test application that I use to reproduce this problem:

`git clone https://github.com/christroutner/sample-strapi-app`

3. Since this is an evolving repo, checkout the version that was current when this issue was reported:

`git checkout 65735ca167a19b32cdf2d18cb40d40ee2771aa1c`

4. Run the test:

`npm install`

`npm run test`

5. Notice the last test involving the DELETE command has the following output, followed by a `500 internal error`:

```
ERROR (13580 on trout): You can't call the query method without passing the model's name as a first argument.
ERROR (13580 on trout): Cannot read property 'findOne' of undefined
    TypeError: Cannot read property 'findOne' of undefined
        at Object.delete (/home/trout/work/p2pvps/sample-strapi-app/plugins/content-manager/services/ContentManager.js:48:62)
        at Object.remove (/home/trout/work/p2pvps/sample-strapi-app/plugins/users-permissions/services/User.js:106:80)
        at destroy (/home/trout/work/p2pvps/sample-strapi-app/plugins/users-permissions/controllers/User.js:143:74)
        at dispatch (/home/trout/work/p2pvps/sample-strapi-app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/trout/work/p2pvps/sample-strapi-app/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
```

**What is the expected behavior?**

I'm starting with an empty database. Through trial-and-error I've figured out that the first account created becomes an Admin user. Let me know if that understanding is incorrect.

So my script creates two users: an admin first, a test user second. At the end of the test I use the admin users JWT to delete the test user. I'm getting a 500 `An internal server error occurred` error.

**Comment by lauriejim** [comment]
Hello @christroutner !

Your `sample-strapi-app` repo is a fork of this one https://github.com/strapi/sample-strapi-app ?
Can you please try with `node 9` and test with last version of Strapi.

Same for this issue https://github.com/strapi/strapi/issues/728
