### ISSUE TITLE
How to name our Users/Roles sections and pages?

### ISSUE THREAD

**Issue by sam-pires** [strapi/strapi#7229]
Hello everyone!

We (the team at Strapi) are working on making the **users-permissions plugin** settings accessible through Strapi's global settings instead of in the main menu.
We are working on the wording and would like to have some feedback from the community.

<img width="351" alt="Capture d’écran 2020-07-28 à 11 34 09" src="https://user-images.githubusercontent.com/54801383/88648425-443ae080-d0c7-11ea-8f04-16f823a03a27.png">

**Context:**
On one hand, we have our **Admin Users** & their Roles, they're entitled to do stuff on the Strapi panel
On another hand, we have the **End-users** who are using the website, mobile app, blog, etc.

**Problem:**
We need two different sections to manage settings for both types of users and their roles/permissions. 
We've made some suggestions here, do you find them clear enough? 
How can we improve them? Do you have any advice or suggestion? Does something look wrong?

Any feedback is good to take from both tech and non-tech Strapi users.

Thanks in advance!

**Comment by petersg83** [comment]
Hi, good question. It will feel good to have a proper wording :)
What I see on the screenshot makes sense to me. Does it mean that if you click on "Admin Members", the wording you'll see will also be "members" instead of "users"? Like "Create a member" ?

The end-users are the settings that related to the Users & Permissions and permission plugin? Why is the name "END-USERS" instead of "Users & Permissions"? If other plugins have settings, would we find them in this menu too or would there handle it on their own?

**Comment by alexandrebodin** [comment]
So our users understand better I would keep the title the same as the plugin name: 

`Users & Permissions plugin` vs `Administration Panel`

**Comment by Convly** [comment]
Hi, excellent question indeed!

I'm not sure about the "end-user" term. On the one hand, it helps differentiate admins from regular users. Still, on the other hand, it introduces another new word (alongside member (from "admin members")), and I'm afraid (new) Strapi users could feel lost with all this specific vocabulary).

IMO we should stick to basic terms such as "Admin/Administrators" and "Users" for the sake of simplicity and comprehension.

As of the titles name, I agree with @alexandrebodin

**Comment by MattieBelt** [comment]
I agree with the simple usage of _"Admin/Administrators" and "Users"_.

Will the collection-type _Users_ be removed from the list? 
Putting them together (as in the example) should make it more clearly that there is a difference between them. 
Since 3.1.x I have spoken with a few (new) Strapi users and they were a bit confused about the differences.

What very the choice will be, new docs need to be added to clarify the difference between the two and the feature RBAC in whole.

**Comment by IPWright83** [comment]
So I'm a fairly new Strapi user and I'll admit I've found it a little confusing! 

I like the `Administration Panel` suggestion, I think that really works and highlights what they're able to do. `End Users` is pretty good, although 2 weeks ago I'd have been wondering what does "End User" mean? I'd potentially suggest `API User`, as essentially it's someone who is only interacting with Strapi through one of the API's.

**Comment by derrickmehaffy** [comment]
> I agree with the simple usage of _"Admin/Administrators" and "Users"_.
> 
> Will the collection-type _Users_ be removed from the list?
> Putting them together (as in the example) should make it more clearly that there is a difference between them.
> Since 3.1.x I have spoken with a few (new) Strapi users and they were a bit confused about the differences.
> 
> What very the choice will be, new docs need to be added to clarify the difference between the two and the feature RBAC in whole.

You grabbed my exact question also, pulling the users link from the left menu.

**Comment by alexandrebodin** [comment]
Eventually we will move the Users collection to this section too but it requires more work so not at first

**Comment by sam-pires** [comment]
Hi all,
Thank you for your feedback!

After a discussion based on these feedback, we decided to go with:

ADMINISTRATION PANEL
- Users
- Roles

USERS & PERMISSIONS PLUGIN
- Roles
- Users _(<= will be added later to this menu)_
- Providers
- Email templates
- Advanced settings

---
For more clarity we are going to "administration panel",  but keep the subsections as they are today to avoid modifying all the wording and confusing existing users.

We are going to use the name of the plugin for the corresponding section's title "Users & Permissions plugin", and here too keep the same names for the subsections to avoid confusion.

Let us know if you have any thoughts on this 🙂 

Thanks again!

**Comment by izznatsir** [comment]
Maybe add some hover tips to clear the confusions. I like @IPWright83 suggestion about making it clear that Users under Users & Permission plugin can only access through the API not admin panel. Mentioning some other aliases in the hover tip may also helps.
