### ISSUE TITLE
 Relation field shows "No permission to view this field" for super-admin

### ISSUE THREAD

**Issue by scopsy** [strapi/strapi#7232]
**Describe the bug**
After upgrading to strapi 3.1 when trying to create a new entry with a relation field inside a repetable component. The field shown with a "No permission to view this field". Even tho i'm a super admin. Checked the settings page and the super admin seem to have access to the relation table.

**Steps to reproduce the behavior**

1. Create content list with a repeatable component that has a relation field
2. Uograde to strapi 3.1
3. try to create a new entry, the relation field will be disabled

**Expected behavior**
I was expectin to be able to modify the relation field as usual.

**Screenshots**
<img width="1217" alt="Screen Shot 2020-07-28 at 17 07 14" src="https://user-images.githubusercontent.com/8872447/88677428-effb2500-d0f5-11ea-995c-49c1cb3e4697.png">

**System**

- Node.js version: v12.18.0
- NPM version: 6.14.4
- Strapi version: 3.1.1
- Database: Mongo DB
- Operating system: Mac OS

**Comment by lauriejim** [comment]
Hello! Can you please share your data structure, models and components, this will help us to reproduce the issue.
@petersg83 maybe related to a migration script?

**Comment by scopsy** [comment]
```
{
  "kind": "collectionType",
  "collectionName": "recipes",
  "info": {
    "name": "Recipes"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "title_en": {
      "type": "string"
    },
    "recipe_phases": {
      "type": "component",
      "repeatable": true,
      "component": "recipes.recipe-phases"
    },
    "author": {
      "model": "authors"
    }
  }
}
```

Component:
```
{
  "collectionName": "components_recipes_recipe_phases",
  "info": {
    "name": "recipe_phases",
    "icon": "allergies"
  },
  "options": {},
  "attributes": {
    "title_en": {
      "type": "string"
    },
    "recipe_phase": {
      "model": "recipe-phases"
    },
    "steps": {
      "type": "component",
      "repeatable": true,
      "component": "recipes.steps"
    }
  }
}
```

the broken part is:
```
  "recipe_phase": {
      "model": "recipe-phases"
    },
```

**Comment by lauriejim** [comment]
How did you create this relation?

**Comment by scopsy** [comment]
<img width="1157" alt="Screen Shot 2020-07-29 at 14 46 36" src="https://user-images.githubusercontent.com/8872447/88796475-6194ab00-d1aa-11ea-87b2-e42b78f64ac4.png">

In the content editor, as usual

**Comment by petersg83** [comment]
Hi! Thanks for the issue. There are no migration scripts involved in this. I tried but I couldn't reproduce it. Do you have the problem when you follow the steps you wrote?
Can you rewrite them with as much details as possible so I can do the exact same things as you? This easiest way is maybe to record your screen from the moment you create the strapi project to the moment you experience the problem.

**Comment by dawnerd** [comment]
Seems related to #7325?

**Comment by robinsimonklein** [comment]
Hi everyone ! I had the same problem. 
When I added new fields in a collection type from the "Content-Types Builder", those fields were hidden for the users with the role "Editor" or "Author".
<img width="1024" alt="Capture d’écran 2020-08-15 à 23 05 03" src="https://user-images.githubusercontent.com/36634414/90321655-f8ec5300-df4b-11ea-8360-cdfcbf00d6f2.png">

After looking, I noticed that the checkboxes's appearance had changed in the permission settings of the other Roles (in settings → permissions → Roles → Editor
<img width="1067" alt="Capture d’écran 2020-08-15 à 23 08 35" src="https://user-images.githubusercontent.com/36634414/90321718-8c258880-df4c-11ea-8021-8ba4316ad48b.png">

Clicking on the first checkbox fixed the problem, but I have to repeat this operation each time I edit a collection type...
<img width="616" alt="Capture d’écran 2020-08-15 à 23 15 57" src="https://user-images.githubusercontent.com/36634414/90321795-5f25a580-df4d-11ea-9442-346c8f62324c.png">

I think it remains an issue :/

**Comment by JabStrapi** [comment]
Hi everyone, This is not properly an issue. We had to make a choice regarding the default behavior when adding a field in a content type: would it be automatically included in the default roles' permissions set or not....?  We decided it would not and that the permissions would have to be updated each time the content model to manage would evolve (the opposite choice would have come with the same amount of drawbacks). Therefore, each time you are updating a content type model with a field, make sure to grant access to it updating the roles' permissions. I hope that helps.

**Comment by robinsimonklein** [comment]
Ok, that makes sense. Thank you for the clarification ! 🙌

**Comment by kiwimahk** [comment]
Hi, I also ran into this issue despite having permissions set correctly (I am following the tutorial here https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi ). 

In my case it resolved itself when I added a second category and clicked save, triggering a server restart. 

Therefore my best guess is that something went wrong during server restart after saving my first category. Just posting in case it helps anyone else in my situation, with correct permissions but no ability to edit relation field.

**Comment by dawnerd** [comment]
> each time you are updating a content type model with a field, make sure to grant access to it updating the roles' permissions. I hope that helps.

Why would we have to do this if were an admin? Considering I had this similar this as a super admin makes me think there’s something else going on.

**Comment by lodisy** [comment]
Also have this issue as a **superadmin**. Add a new field to the category content type and have no access to edit that field.

**Comment by petersg83** [comment]
Hi, the **superadmin** should indeed have access to everything yes. I followed the steps of @lodisy but everything works find on my side. Can you please give more details ?

```
    Node.js version: 
    NPM version: 
    Strapi version: 
    Database: 
    Operating system: 
```

**Comment by lodisy** [comment]
> Hi, the **superadmin** should indeed have access to everything yes. I followed the steps of @lodisy but everything works find on my side. Can you please give more details ?
> 
> ```
>     Node.js version: 
>     NPM version: 
>     Strapi version: 
>     Database: 
>     Operating system: 
> ```

Node.js version: 12.14.1
NPM version: 6.13.4
Strapi version: 3.1.4
Database: MongoDB
Operating system: Ubuntu 18.04.3 LTS

**Comment by dawnerd** [comment]
I also attached information in the issue I linked above. Also only happens in production mode.

**Comment by lodisy** [comment]
> > Hi, the **superadmin** should indeed have access to everything yes. I followed the steps of @lodisy but everything works find on my side. Can you please give more details ?
> > ```
> >     Node.js version: 
> >     NPM version: 
> >     Strapi version: 
> >     Database: 
> >     Operating system: 
> > ```
> 
> Node.js version: 12.14.1
> NPM version: 6.13.4
> Strapi version: 3.1.4
> Database: MongoDB
> Operating system: Ubuntu 18.04.3 LTS
> 
> I do not have issue locally, this happes on my VPS (with separated admin panel) whether in dev or production mode.

**Comment by petersg83** [comment]
Can you please show me the entry in your database that correspond to the super-admin user ?
It should look to something like that:
```
{
    "_id" : ObjectId("5f3bf84872b113bd976f57c9"),
    "name" : "Super Admin",
    "code" : "strapi-super-admin",
    "description" : "Super Admins can access and manage all features and settings.",
    "createdAt" : ISODate("2020-08-18T15:48:24.482Z"),
    "updatedAt" : ISODate("2020-08-18T15:48:24.482Z"),
    "__v" : 0
}
```

Alos, do you have any warning in the logs when you start the server?

**Comment by dawnerd** [comment]
```
> db.getCollection('strapi_role').find({})
{ "_id" : ObjectId("5f276fda8a83ae0a07e79302"), "name" : "Super Admin", "code" : "strapi-super-admin", "description" : "Super Admins can access and manage all features and settings.", "createdAt" : ISODate("2020-08-03T02:00:58.957Z"), "updatedAt" : ISODate("2020-08-03T02:00:58.957Z"), "__v" : 0 }
{ "_id" : ObjectId("5f276fda8a83ae0a07e79303"), "name" : "Editor", "code" : "strapi-editor", "description" : "Editors can manage and publish contents including those of other users.", "createdAt" : ISODate("2020-08-03T02:00:58.967Z"), "updatedAt" : ISODate("2020-08-03T02:00:58.967Z"), "__v" : 0 }
{ "_id" : ObjectId("5f276fda8a83ae0a07e79304"), "name" : "Author", "code" : "strapi-author", "description" : "Authors can manage and publish the content they created.", "createdAt" : ISODate("2020-08-03T02:00:58.976Z"), "updatedAt" : ISODate("2020-08-03T02:00:58.976Z"), "__v" : 0 }
```

```
yarn run v1.22.4
$ strapi start
[2020-08-18T16:50:42.596Z] debug [Cache] Mounting LRU cache middleware
[2020-08-18T16:50:42.597Z] debug [Cache] Storage engine: mem
[2020-08-18T16:50:42.599Z] debug [Cache] Caching route /attractions/:id* [maxAge=604800000]
[2020-08-18T16:50:42.599Z] debug [Cache] Caching route /companies/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /manufacturers/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /parks/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /resorts/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /static-pages/:id* [maxAge=604800000]
[2020-08-18T16:50:43.269Z] error An index error happened, it wasn't applied.
        - Index with name: username_1 already exists with different options

 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Tue Aug 18 2020 16:50:43 GMT+0000 (Coordinated … │
│ Launched in        │ 3553 ms                                          │
│ Environment        │ production                                       │
│ Process PID        │ 23144                                            │
│ Version            │ 3.1.4 (node v12.18.2)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://0.0.0.0:1337/admin

To access the server ⚡️, go to:
http://0.0.0.0:1337
```

**Comment by derrickmehaffy** [comment]
```
[2020-08-18T16:50:42.596Z] debug [Cache] Mounting LRU cache middleware
[2020-08-18T16:50:42.597Z] debug [Cache] Storage engine: mem
[2020-08-18T16:50:42.599Z] debug [Cache] Caching route /attractions/:id* [maxAge=604800000]
[2020-08-18T16:50:42.599Z] debug [Cache] Caching route /companies/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /manufacturers/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /parks/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /resorts/:id* [maxAge=604800000]
[2020-08-18T16:50:42.600Z] debug [Cache] Caching route /static-pages/:id* [maxAge=604800000]
[2020-08-18T16:50:43.269Z] error An index error happened, it wasn't applied.
        - Index with name: username_1 already exists with different options
```

Just a side point I see you are using the community `strapi-middleware-cache` wanted to just make sure there is no conflict, can you temporarily disable that middleware?

**Comment by lodisy** [comment]
> abase that correspond to the super-admin user ?
> It should look to something like that:

```
{
	"_id" : ObjectId("5f3070d75dd9161e5c5d40a7"),
	"name" : "Super Admin",
	"code" : "strapi-super-admin",
	"description" : "Super Admins can access and manage all features and settings.",
	"createdAt" : ISODate("2020-08-09T21:55:35.072Z"),
	"updatedAt" : ISODate("2020-08-09T21:55:35.072Z"),
	"__v" : 0
}
{
	"_id" : ObjectId("5f3070d75dd9161e5c5d40a8"),
	"name" : "Editor",
	"code" : "strapi-editor",
	"description" : "Editors can manage and publish contents including those of other users.",
	"createdAt" : ISODate("2020-08-09T21:55:35.083Z"),
	"updatedAt" : ISODate("2020-08-10T07:56:56.784Z"),
	"__v" : 0
}
{
	"_id" : ObjectId("5f3070d75dd9161e5c5d40a9"),
	"name" : "Author",
	"code" : "strapi-author",
	"description" : "Authors can manage and publish the content they created.",
	"createdAt" : ISODate("2020-08-09T21:55:35.091Z"),
	"updatedAt" : ISODate("2020-08-10T07:57:30.855Z"),
	"__v" : 0
}
```


```
> db.strapi_administrator.find().pretty()
{
	"_id" : ObjectId("5f308143ef4743500d23122f"),
	"isActive" : true,
	"blocked" : false,
	"roles" : [
		ObjectId("5f3070d75dd9161e5c5d40a7"),
		ObjectId("5f3070d75dd9161e5c5d40a8"),
		ObjectId("5f3070d75dd9161e5c5d40a9")
	],
	"username" : "michael@neonse.com",
	"registrationToken" : null,
	"firstname" : "Jie",
	"lastname" : "Wang",
	"email" : "michael@neonse.com",
	"password" : "$2a$10$6VgP6OB5jbUGT8lnYN5g6.z5L2hGBPX6REN4cZrJT88VTQU7CbhNu",
	"createdAt" : ISODate("2020-08-09T23:05:39.620Z"),
	"updatedAt" : ISODate("2020-08-10T08:27:12.270Z"),
	"__v" : 0
}
```

**Comment by derrickmehaffy** [comment]
Ah

```
	"roles" : [
		ObjectId("5f3070d75dd9161e5c5d40a7"),
		ObjectId("5f3070d75dd9161e5c5d40a8"),
		ObjectId("5f3070d75dd9161e5c5d40a9")
	],
```

@petersg83 I'm wondering if that's the problem, one of the other roles overriding the super admin one?

**Comment by lodisy** [comment]
> Ah
> 
> ```
> 	"roles" : [
> 		ObjectId("5f3070d75dd9161e5c5d40a7"),
> 		ObjectId("5f3070d75dd9161e5c5d40a8"),
> 		ObjectId("5f3070d75dd9161e5c5d40a9")
> 	],
> ```
> 
> @petersg83 I'm wondering if that's the problem, one of the other roles overriding the super admin one?

Super! It is resolved after removed the editor and author roles(need to logout and re-login). 

But it's a bit confusing to me, when I submit a post, I need to asign the author, but the supera dmin does not show in the user(collection) list, so I need to creat one with the same email etc. So how about the role of this new created user?

**Comment by petersg83** [comment]
I was able to reproduce it! Thanks a lot :)
I hear the confusion, maybe @JabStrapi can help making it clearer

**Comment by derrickmehaffy** [comment]
I think in this case @petersg83 if an admin user is apart of the `super admin` role, the others should be completely ignored (since you cant change the super admin permissions anyway)

**Comment by kauaicreative** [comment]
Restarting the server and re-logging in allows super-admin to access the new field

**Comment by boristomas** [comment]
Also had the issue as superadmin, logging out and then re-login worked for me
