### ISSUE TITLE
Unexpected config.server.url option behaviour 

### ISSUE THREAD

**Issue by debagger** [strapi/strapi#7233]
**Describe the bug**
config.server.url

**Steps to reproduce the behavior**

1. Run `npx create-strapi-app server-url-bug --quickstart`
2. When script is finished, register admin (register form showed in bowser automaticaly). Admin panel will be opened and worked correclty.
3. Stop application.
4. Add `url: '/api'` in `./config/server.js` file.
5. Remove .`cache` and `build` folder for guaranteed clean build at next step.
6. Start application again with `npm run develop` command.
7. Go to admin panel at `http://localhost:1337/api/admin` as suggested in the console prompt.
8. See infinite spinner in browser.

**Expected behavior**
As described in documentation here https://strapi.io/documentation/v3.x/concepts/configurations.html#server
> Url of the server. Enable proxy support such as Apache or Nginx, example: https://mywebsite.com/api. The url can be relative, if so, it is used with http://${host}:${port} as the base url.

As far as I understand the application should work at this address: `http://localhost:1337/api/admin`

**System**

- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version: 3.1.1
- Database: sqlite
- Operating system: Windows 10

**Linked issues**
#6695

**Comment by derrickmehaffy** [comment]
@petersg83 I think we need to describe this a bit better on the docs, I've seen this come up a few times in Slack as well.

@debagger Strapi itself will not prefix the routes, what this does in terms of support is generally for the Admin and any providers (upload/auth/ect) and will set how they are publicly accessed.

When you build the admin, it generates a URL to access the backend APIs (say `/admin/plugins/users-permissions/roles`) and what this setting does is simple add in the `/api` prefix to that generated route. What it's really expecting is your upstream proxy (like nginx) to handle this routing. If you take a look at this doc: https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html#sub-folder-unified

Specifically the line in the Nginx config `rewrite ^/api/(.*)$ /$1 break;` is cutting that prefix off before sending the request to Strapi (as the backend won't understand the prefix). Generally speaking that root server.url key should be a FQDN similar to the examples at the bottom of the Nginx guide: https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html#sub-folder-unified-strapi-config

There is no way currently to prefix the routes in Strapi to the point where you could call them directly with that prefix without going through some kind of proxy application (Nginx, HAProxy, Apache, Traefik, Caddy, ect).

**Comment by debagger** [comment]
I found a workaround for this problem. This code must be added to `./config/functions/bootstrap.js`:
```javascript
const prefix = strapi.config.server.url;
  if (prefix) {
    strapi.router.stack.forEach((i) => (i.path = i.path.replace(prefix, "")));
    strapi.router.prefix(prefix);
    strapi.app.middleware.forEach((i) => i.router && i.router.prefix(prefix));

    strapi.app.use(async (ctx, next) => {
      if (
        ctx.request.url === prefix + "/_health" &&
        ctx.request.method === "HEAD"
      ) {
        ctx.set("strapi", "You are so French!");
        ctx.status = 204;
      } else {
        await next();
      }
    });
  }
```
After do it and rebuild app all work as me expected.

Perhaps I misunderstand the purpose of this option, but at least the console prompt displays incorrect information.

**Comment by debagger** [comment]
@derrickmehaffy Thanks for the quick and detailed answer. I think that it is necessary to clarify this point in the documentation in more detail, give a link to examples of Nginx configuration. The command line prompt that doesn't work as expected is also confusing. I spent a lot of time figuring out what the problem is.

**Comment by skourismanolis** [comment]
Just fell to the same issue, thanks a lot for the fix @debagger!
Maybe the workaround should be added to the docs? along with a clarification that the code provided should run in the bootstrap.js exported function (for any beginners like me).

**Comment by debagger** [comment]
@skourismanolis 
Here is full content of my bootstrap.js
```javascript
"use strict";

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/v3.x/concepts/configurations.html#bootstrap
 */

module.exports = () => {
  const prefix = strapi.config.server.url;
  if (prefix) {
    strapi.router.stack.forEach((i) => (i.path = i.path.replace(prefix, "")));
    strapi.router.prefix(prefix);
    strapi.app.middleware.forEach((i) => i.router && i.router.prefix(prefix));

    strapi.app.use(async (ctx, next) => {
      if (
        ctx.request.url === prefix + "/_health" &&
        ctx.request.method === "HEAD"
      ) {
        ctx.set("strapi", "You are so French!");
        ctx.status = 204;
      } else {
        await next();
      }
    });
  }
  // strapi.router.stack.forEach((i) => console.log(i.path));
  // strapi.app.middleware.forEach(
  //   (i) => i.router && i.router.stack.forEach((j) => console.log(j.path))
  // );
};
```
You can uncomment last lines for list all routes.

**I also want to make it clear that this is all a dirty hack and I would not recommend using it in a production environment.**

**Comment by derrickmehaffy** [comment]
`I also want to make it clear that this is all a dirty hack and I would not recommend using it in a production environment.`

Thank you for that, and yes in a production level environment you should be using a proxy application but for a local development environment it makes sense.

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed for now but we will be reviewing all the documentation over the next few months and almost completely restructuring it. :)

**Comment by debagger** [comment]
@skourismanolis 
I improved the code for my workaround. In the previous version, loading assets did not work. Now the contents of the `bootstrap.js`:
```javascript
"use strict";

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/v3.x/concepts/configurations.html#bootstrap
 */

module.exports = () => {
  const prefix = strapi.config.server.url;
  if (prefix) {
    strapi.router.stack.forEach((i) => (i.path = i.path.replace(prefix, "")));
    strapi.router.prefix(prefix);
    strapi.app.middleware.forEach((i) => i.router && i.router.prefix(prefix));

    strapi.app.use(async (ctx, next) => {
      if (
        ctx.request.url === prefix + "/_health" &&
        ctx.request.method === "HEAD"
      ) {
        ctx.set("strapi", "You are so French!");
        ctx.status = 204;
      } else {
        await next();
      }
    });
    fixUploads(prefix);
  }
  // Uncomment next lines for print list of all routes. 
  // strapi.router.stack.forEach((i) => console.log(i.path));
  // strapi.app.middleware.forEach(
  //   (i) => i.router && i.router.stack.forEach((j) => console.log(j.path))
  // );
};
function fixUploads(prefix) {
  const uploads = strapi.router.stack.find(
    (i) => i.path == prefix + "/uploads/(.*)"
  );
  const serve_ix = uploads.stack.findIndex((i) => i.name == "serve");
  const serve = uploads.stack[serve_ix];

  uploads.stack[serve_ix] = (ctx, next) => serve(Object.assign(ctx, { path: ctx.path.replace(prefix, "") }), next);
}
```
