### ISSUE TITLE
Referencing 5590, we are getting the exact same issue as strapi failure to initalize . Is cosmos db supported to work with strapi?

### ISSUE THREAD

**Issue by deepakmoses** [strapi/strapi#7236]
We are getting the exact same error mentioned in defect 5590 " strapi failure to initialize with a connection refused message from mongo api of Azure cosmos db .We use mongoose driver from strapi to talk to the mongo 3.6 api  for azure cosmos db. We would need a confirmation at your end if this is a supported configuration. Is strapi supported to work with azure cosmos db 3.6?
Your response would be greatly appreciated .

**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
@deepakmoses no CosmosDB is not officially Mongo and thus is not a supported DB, usage of it comes with an "at your own risk" for now.
