### ISSUE TITLE
Roles & Permission is throwing error

### ISSUE THREAD

**Issue by proloyhcs** [strapi/strapi#7240]
When I click on "Roles & Permission", the page is throwing error.
![role_](https://user-images.githubusercontent.com/38790883/88763570-fbe7f500-d190-11ea-9a91-384ee1e667c7.png)

Here is chrome API screenshot:
![chrome2](https://user-images.githubusercontent.com/38790883/88765569-4b7bf000-d194-11ea-9d9d-5106406122b2.png)

Here is JSON response:
`{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Not found"}]}],"data":[{"messages":[{"id":"Not found"}]}]}`

Environment:
Node: 12.16.1
NPM: 6.13.4
OS: Windows 10 & Azure Linux VM
HTTP: NGINX on Azure Linux VM (Used setting as suggested in documentation)
DB: Azure CosmosDB for MongoDB
Strapi: 3.1.0 & 3.1.1

Version 3.0.6 is working fine. Problem is with new installation of 3.1.0 & 3.1.1. It also happen when migrating from 3.0.6 to 3.1.1 / 3.1.0. I followed migration documentation.

**Comment by lauriejim** [comment]
Hello! Did you followed the migration guide?
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html

**Comment by proloyhcs** [comment]
> Hello! Did you followed the migration guide?
> https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html

Yes @lauriejim I followed the migration guide. It also happens with in installation.

**Comment by lauriejim** [comment]
Do you have any error on your server-side?
Quite hard to help on this one...

**Comment by derrickmehaffy** [comment]
Indeed @proloyhcs we need more information to be able to reproduce the issue and assist you here.

**Comment by derrickmehaffy** [comment]
Closing as user has provided no new information.
