### ISSUE TITLE
Media Library throwing error

### ISSUE THREAD

**Issue by proloyhcs** [strapi/strapi#7242]
When I click on Media Library I see below error. My uploaded media are not getting displayed.
![upload](https://user-images.githubusercontent.com/38790883/88766199-3e133580-d195-11ea-8e59-4cec387a994b.png)

Here is chrome dev tool screenshot:
![chrome](https://user-images.githubusercontent.com/38790883/88766229-4b302480-d195-11ea-9e78-e0b905215f6a.png)

Response JSON:
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

Environment:
Node: 12.16.1
NPM: 6.13.4
OS: Windows 10 & Azure Linux VM
HTTP: NGINX on Azure Linux VM (Used setting as suggested in documentation)
DB: Azure CosmosDB for MongoDB
Strapi: 3.1.0 & 3.1.1

Version 3.0.6 is working fine. Problem is with new installation of 3.1.0 & 3.1.1. It also happen when migrating from 3.0.6 to 3.1.1 / 3.1.0. I followed migration documentation.

**Comment by lauriejim** [comment]
Same message than your other issue - 
Did you followed the migration guide?
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html

**Comment by machiaveli88** [comment]
I get the same error. As media library I use Cloudinary.

**Comment by machiaveli88** [comment]
The error seems to occur only on the first page of the media library.

**Comment by proloyhcs** [comment]
> Same message than your other issue -
> Did you followed the migration guide?
> https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html

Yes @lauriejim I followed the migration guide. It also happens with in installation.

**Comment by MakingStuffs** [comment]
> The error seems to occur only on the first page of the media library.

This is very weird as it happens on the last page for me: https://github.com/strapi/strapi/issues/7160

**Comment by derrickmehaffy** [comment]
Closing as duplicate of https://github.com/strapi/strapi/issues/7160
