### ISSUE TITLE
Incorrectly flagging required fields during validation

### ISSUE THREAD

**Issue by IPWright83** [strapi/strapi#7248]
**Describe the bug**
I have modified my content type to mark some fields as required. Whenever I edit an entry for this content type the fields are marked with a validation error when I attempt to save, despite the fields being already populated.

**Steps to reproduce the behavior**

1. Create a new content type with a `datetime` field and a string field.
2. Create a new entry for this content type with both fields populated
3. Edit the content type to mark the `datetime` field as required (within advanced settings)
3. Goto the entry for this content type to edit the string field.
4. Hit save - at this point a validation error occurs

**Expected behavior**
The record saves correctly

**Screenshots**
![Strapi Bug](https://user-images.githubusercontent.com/1374775/88803454-622a4300-d1a4-11ea-95a0-422e09a3c53e.gif)

![image](https://user-images.githubusercontent.com/1374775/88803432-58a0db00-d1a4-11ea-8584-45ed55af8b62.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.1
- Database: Postgres
- Operating system: Ubuntu 18.04.4

**Comment by derrickmehaffy** [comment]
Can you update and test with the latest release (made today) `3.1.2`, it should resolve these issues.

**Comment by IPWright83** [comment]
@derrickmehaffy confirmed fixed in `3.1.2`
