### ISSUE TITLE
Custom routes created for users-permissions plugin aren't working, but other custom routes are

### ISSUE THREAD

**Issue by cjpdee** [strapi/strapi#7251]
**Describe the bug**
I'm trying to create a route to update only the logged in user.

app/extensions/users-permissions/config/routes.json:
```
{
  "routes": [
    {
      "method": "PUT",
      "path": "/wtf",
      "handler": "User.updateMe",
      "config": {
        "policies": []
      }
    }
  ]
}
```

in app/extensions/users-permissions/controllers/User.js:
```
async updateMe(ctx) {
    console.log('what');
}
```
(There is other stuff of course but I just want the route to work)

If I name the handler something other than updateMe, it complains on startup so it seems to exist.
However when I try to consume the route I only get 'Method not allowed'.

I've tried lots of variations, the user I'm doing this from is authenticated and has permission to use this method.

From the documentation it seems like this should be pretty simple, so I'm stumped as to why it's not working.

Worth noting I used this guide to implement httpOnly JWT cookies, so auth is done that way: https://talke.dev/strapi-user-permissions-jwt-cookies

Also, I created a custom route to clear that cookie in api/Custom and that works perfectly.

**Steps to reproduce the behavior**

1. Create new route in app/extensions/users-permissions/config/routes.json
2. Create a method to match it in User.js
3. Authenticate a user
4. Consume newly created route

**Expected behavior**
Route should return something

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.1
- Database: postgre
- Operating system: MacOS

**Comment by nicksp** [comment]
I use the following route config that works as expected (just tested with new Strapi `v3.1.2`):

```js
{
      "method": "PUT",
      "path": "/profiles/me",
      "handler": "profile.updateMe",
      "config": {
        "policies": ["global::validation"]
      }
    }
```

The problem you experience is most likely to do with not set permissions for the `user=spermissions` plugin which you seem to extend. Remember to update allowed actions for the Authenticated user.

ANyways, the question doesn't relate to Strapi itself and should be asked on Stackoverflow as it's more of a userland use-case.

**Comment by lauriejim** [comment]
Hello! I just tested and it works fine on my side.

Try to return some data in your function.

`PUT /users-permissions/wtf`
