### ISSUE TITLE
Migration v3.1.2 | Error : Schema hasn't been registered for model "user"

### ISSUE THREAD

**Issue by devaublanc** [strapi/strapi#7252]
**Describe the bug**
Since the migration that I did perfectly https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html 
I got this error **GraphQL error : Schema hasn't been registered for model "user"**  When I try to execute an authenticated requests with graphql. ⚠️ This error is also reproducible on the REST API.

**Steps to reproduce the behavior**

1. Install GraphQL plugin
2. Create a collection "ex trip"
3. Configure Roles & Permissions, In "Authenticated" role check trip>find
4. Go to http://localhost:1337/graphql
5. Get a fresh token by executing the login mutation
```
mutation login($identifier: String!, $password: String!) {
  login(input: { identifier: $identifier, password: $password }) {
    jwt
    user {
      id
      username
      email
    }
  }
}
```
6. In the console set HTTP headers with jwt token generated by the mutation above
```
{
  "Authorization":"Bearer XXX"
}
```
7. Execute this query 
```
query trips{
  trips{
    title
  }
}
```

**Expected behavior**
Should return a result

**Screenshots**
![Capture d’écran 2020-07-29 à 19 47 36](https://user-images.githubusercontent.com/12794277/88834679-7ab25180-d1d4-11ea-80ec-7ab5014b2881.png)

![Capture d’écran 2020-07-29 à 19 50 09](https://user-images.githubusercontent.com/12794277/88834880-bf3ded00-d1d4-11ea-901e-a9f9d75183eb.png)

**Additional context**
- I did the same test by using the REST api endpoints (http://localhost:1337/auth/local) then (http://localhost:1337/trips) same behavior

- I also did the test on a fresh install of strapi v3.1.2 same behavior

**System**

- Node.js version:v12.13.0
- NPM version: 6.14.6
- Strapi version: v3.1.2
- Database: mongo
- Operating system: mac OS X

**Comment by devaublanc** [comment]
mmm with a fresh new install it's works what's going wrong with the migration ?

**Comment by mikelmi** [comment]
+1
The same bug after installing the new version

**Comment by phamquocthinh** [comment]
Any one got the error code 401 with message `The model administrator can't be found.`?

**Comment by devaublanc** [comment]
Nop

**Comment by devaublanc** [comment]
> Any one got the error code 401 with message `The model administrator can't be found.`?

Nop

**Comment by nikitindiz** [comment]
Same for `/users/me` route.

Response:
```
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Schema hasn't been registered for model \"user\".\nUse mongoose.model(name, schema)"
}
```

**Comment by NiharZanwar** [comment]
I too got the same error message - using v3.1.2. In fact, I tried to replicate the exact same settings for v3.1.1, which works fine and does not throw the above response. I am using the HTTP API and not GraphQL.

**Comment by RileyMShea** [comment]
I am also getting this error with mongodb and graphql on v3.1.2. Have not tried REST endpoint yet.  It seems I will need to downgrade to v3.1.1 until a patch is out.

**Comment by luvpack** [comment]
Yes, I have a similar problem for /users/me

`{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Schema hasn't been registered for model \"user\".\nUse mongoose.model(name, schema)"
}`
