### ISSUE TITLE
Not possible to use an absolute directory as public path

### ISSUE THREAD

**Issue by janlelis** [strapi/strapi#7257]
**Describe the bug**

Hey there, thank you for strapi, it's awesome!

After updating from beta to the latest stable (3.1.2) it seems that using absolute paths as the public directory breaks file uploads (which used to work before) :confused:

**Steps to reproduce the behavior**

1. Go to 'config/middleware.js'
2. Edit option 'settings.public' as described here https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations
3. Enter an `/absolute/path`
4. Upload a file
5. See error message

   error Error: ENOENT: no such file or directory, open '/path/to/strapi/absolute/path/uploads/<filename>'

**Expected behavior**

File upload should work

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.1.2
- Database: MySQL
- Operating system:

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
@soupette probably something hardcoded somewhere 🤔

**Comment by petersg83** [comment]
Hi :)
What was your version before?
I can make a fix for that. Out of curiosity, why do you use an absolute path?

**Comment by janlelis** [comment]
Hi @petersg83 - I upgraded from beta19.5 to the latest stable (3.1.2)

I am putting all uploaded assets into a folder which the web server has access to (and which is part of the Front-end application) so that the web server can serve them directly to the users.

**Comment by petersg83** [comment]
Ok, thanks :)
