### ISSUE TITLE
error=Grant: missing session or misconfigured provider

### ISSUE THREAD

**Issue by lancevo** [strapi/strapi#726]
**Node.js version**: 9.6.1

**npm version**: 5.6.0

**Strapi version**: 3@apha 10.2

**Operating system**:
Mac Os, Linux

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when validating token returned by provider like google against /connect/google/callback, grant return this error "error=Grant: missing session or misconfigured provider"

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Use this example from soupette https://medium.com/strapi/protected-routes-and-authentication-with-react-and-node-js-d31d234644cd
The bug is also discussed here https://stackoverflow.com/questions/48974818/strapi-returns-invalid-token-using-google-provider

**What is the expected behavior?**
strapi should returns a jwt and register new user

**Comment by simov** [comment]
This error is only thrown inside the internal `connect` and `callback` routes in [Grant](https://github.com/simov/grant), and only when the provider was either misconfigured from the start or the session got lost during the OAuth flow redirects. Hope that helps.

**Comment by simov** [comment]
@lancevo from your comment in SO:

> I made a request to `/connect/google/callback${query}` per the example

This is internal route used by Grant only, and you should only use it when specifying the redirect URL of your OAuth App in the Google's web UI.

Probably you want to make request to this URL instead: `/auth/${provider}/callback${search}` found in the linked article on Medium.

**Comment by Aurelsicoko** [comment]
@lancevo I had the same issue when I reproduced the tutorial wrote by @soupette! I figured out it's due to a small change we did a few weeks ago.

Set the `host` key to `localhost` instead of `127.0.0.1` in the `./config/environments/*/server.json` file. 

```json
{
  "host": "localhost",
  "port": 1337,
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": false
  }
}
```

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/aws-cognito-as-authentication-provider-grant-missing-session-or-misconfigured-provider-error/1471/2

**Comment by HarryPhillips** [comment]
After experiencing this particular error on/off a fair few times, I finally found the cause for me. As a note to my future self (and perhaps others too, from Google):

The Redirect URL you set in the third-party provider's dev portal *has* to match that of which you define in your server.js config (or in my case, a .env file). If you're using a custom local URL (such as http://my-app.local) then you must also use that too, instead of `localhost`. It seems obvious in hindsight but this threw me for a loop for a long while.

If this isn't done, the `koa.sess` cookie does not get saved correctly upon authorization and you'll be redirected to this error page.

**Comment by RyanCwynar** [comment]
I'm getting this error, but only on mobile.

I'm using auth0's sms login, and I have a custom endpoint that sends the user off to auth0, and when the come back on desktop it works fine, but when they return to the site on mobile, I get this error.
