### ISSUE TITLE
Is there some API for creating custom notification message on admin panel?

### ISSUE THREAD

**Issue by ByungJun25** [strapi/strapi#7262]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Hello strapi, 

firstly, Thank you for your passion.
And It can be possible that I miss some document or I misunderstand something,
If something is wrong in my idea, please let me know. :)

Okay, then I will explain my idea now.

Well, How about creating custom notification message API in strapi for admin panel?

As you know, strapi make us to genereate several data type via Cotent-types Builder.
Sometimes we need a some special logic for checking data not only validation of type, and we can implement this log via model's lifecycles. That is awesome.

However, if the data is not correct for this special logic, we want to show the error message for admin user.
Of course, we can create custom frontend and make a some function to show the message. but this solution is just making duplicated admin panel... Another solution is that we can use Error object, but If we use Error object, the system writes error log also...

Therefore If there is some API for creating custom notification message, then we can more easily create custom validation code.

For example, as I mentioned, we can use this new API for custom validation logic and more, if someone want to make notification function which creates the notification message when the admin user create or update data.

What do you think about this? :)
Is there something wrong, then please let me know. :)

Thank you.
Byungjun Woo

**Comment by lauriejim** [comment]
Today notifications that are displayed in the admin are triggered because of a success request (for success messages) and in this case, the code is managed in the front-end of the plugins/admin.
The second case is because the response of the request is an error. and in this case, the notification content is managed by the response of the failed request.
In both cases, this is managed by the response of the request.
So in your case, if you want to display an error message, you will have to customize the error message body of the request.
No API exists to trigger a notification on the fly in the backend.

**Comment by ByungJun25** [comment]
Hello @lauriejim, 

Thank you for answer about my issue. 👍 

Ah, Okay, I understand now, the admin panel creates the notification message by response of request. :)

is there any API that I can create custom response of each request? 

Because if I just throw the Error from model's lifecycle, although it shows error message well, a content-manager module always writes error log...

You can see the code here: [CodeLink](https://github.com/strapi/strapi/blob/97922f99ae858e1e3f4f792bb8d6a829adb82649/packages/strapi-plugin-content-manager/controllers/ContentManager.js#L210)

```
try {
   const result = await contentManagerService.edit(
      { id },
      { data: { ...sanitize(_.omit(data, ['created_by'])), updated_by: user.id }, files },
      { model }
    );

    ctx.body = pm.sanitize(result, { action: ACTIONS.read });
} catch (error) {
    strapi.log.error(error);
    ctx.badRequest(null, [
      {
          messages: [{ id: error.message, message: error.message, field: error.field }],
          errors: _.get(error, 'data.errors'),
      },
    ]);
}
```

But I don't want to write error log about users mistake... Is there some interrupt API for creating response? :)

Thank you.
Byungjun Woo

**Comment by lauriejim** [comment]
There is no API to manage that.
But if you don't want that, it's really easy to customize your plugin to change the way that's managed.
Here is the documentation to follow - https://strapi.io/documentation/v3.x/concepts/customization.html

**Comment by ByungJun25** [comment]
Thank you @lauriejim 

I will try to customize it. :D

**Comment by ioannisGiak89** [comment]
Hello @lauriejim , could we not use https://strapi.io/documentation/3.0.0-beta.x/plugin-development/frontend-development.html#api the notification object for this?

**Comment by derrickmehaffy** [comment]
(wrong docs link: https://strapi.io/documentation/v3.x/plugin-development/frontend-development.html#api)

You won't be able to throw an error and stop the request within the current query lifecycles as they are handled async, meaning when the beforeX lifecycle is finished the query will go through regardless of throwing an error. Instead what you will need is some kind of middleware to intercept the error message and reformat it for the Admin panel requests.
