### ISSUE TITLE
watch-admin doesn't trigger a build as documentation says

### ISSUE THREAD

**Issue by ventouris** [strapi/strapi#7264]
**Describe the bug**
I try to change a few things in admin homepage. I follow the guide from the latest documentation version, but regardless that, when I run `npm run develop --watch-admin` it doesn't watch for file updates. I have to build manually to get the updated version.

Documentation available here: [https://strapi.io/documentation/v3.x/guides/custom-admin.html#introduction](url)

**Steps to reproduce the behavior**

1. Create a file `index.js` as in the path `/admin/src/containers/HomePage/index.js`
2. Copy paste the content from the same path of strapi-admin in node-modules
3. Change anything that will affect the layout
4. Nothing happens
5. Keep `npm run develop --watch-admin` run in terminal and in another one run `npm run build`
6. Visit admin homepage and the change is there

**Expected behavior**
Whenever I do a change in the index.js file, I expected to have an automatic rebuild on the code

**System**

- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.1.1
- Database: mySQL
- Operating system: MacOS 10.15.5

**Comment by lauriejim** [comment]
@soupette I can confirm this issue.
But it's only with npm, this will work if you use yarn.
Why... I don't know :/

**Comment by henrych4** [comment]
From [npm doc](https://docs.npmjs.com/cli-commands/run-script.html#description:~:text=npm%20will%20pass%20all%20the%20arguments%20after%20the%20%2D%2D%20directly%20to%20your%20script), you have to add "--" before any command line arguments.
So it should be `npm run develop -- --watch-admin`

**Comment by derrickmehaffy** [comment]
@henrych4 can you point to the docs that mention it's usage and/or submit a PR to add that please?

**Comment by henrych4** [comment]
I am thinking if it is ok to add the npm command next to yarn command in the doc as a reference, like [here](https://strapi.io/documentation/v3.x/guides/custom-admin.html#eject-the-file:~:text=To%20run%20your%20application%2C%20you%20will%20have%20to%20run%20the%20yarn%20develop%20%2D%2Dwatch%2Dadmin%20command.,-If%20you%20visit%20the%20admin%2C)

**Comment by chris-makaio** [comment]
I don't get this. I'm trying to customize the admin UI so I use 
yarn run develop --watch-admin

But I can see that in develop.js, the admin folder is actually ignored:
```javascript

 const watcher = chokidar.watch(dir, {
    ignoreInitial: true,
    ignored: [
      /(^|[/\\])\../, 
      /tmp/,
      '**/admin', // HUH?!
      '**/admin/**',
      'extensions/**/admin',
      'extensions/**/admin/**',
      '**/documentation',
      '**/documentation/**',
      '**/node_modules',
      '**/node_modules/**',
      '**/plugins.json',
      '**/index.html',
      '**/public',
      '**/public/**',
      '**/*.db*',
      '**/exports/**',
      ...watchIgnoreFiles,
    ],
  });
```

I tried to comment the ignores, but although the server does restart, it doesn't show the changes.

**Comment by bonnzer** [comment]
It has worked for me on v3.4.6 by `yarn develop --watch-admin` (didn't check npm). 
Now trying on v3.5.1 - doesn't work.

**Comment by soupette** [comment]
Can you try with this command : `npm run strapi develop --watch-admin` or if you are using yarn `yarn run strapi develop --watch-admin` ?

**Comment by bonnzer** [comment]
Still doesn't work
- `npm`: back-end started, no front-end build occur
- `yarn`: both started, but no front-end changes detected. But interesting thing - previous changes are detected and applied. To be clear examples with full pathes: 

1. `<project>/extensions/content-manager/admin/src/components/CustomTable/*` and `<project>/extensions/content-manager/admin/src/containers/EditView/*` works, changes detected and applied
2. `<project>/extensions/content-manager/admin/src/components/LeftMenu/*` and `<project>/extensions/content-manager/admin/src/containers/HomePage/*` doesn't work

**System**

- Node.js version: v14.16.0
- NPM version: 6.14.11
- Strapi version: 3.5.1
- Database: MongoDB
- Operating system: Linux 5.4.0-66

**Comment by soupette** [comment]
Well, the components you are trying to override are not located in the correct path.

If you want to change the left menu you need to override the `strapi-admin` package.


When customising the `strapi-admin` package you need to put your files in the `my-app/admin/src/<path-to-file>` whereas when in a plugin it should go under the `extensions` folder.

**Comment by bonnzer** [comment]
Oh, I see. Thank you so much, my fault. 
I'll dislike my comments )

**Comment by soupette** [comment]
I am closing this issue then
