### ISSUE TITLE
"help button" on bottom right cover the pagination button

### ISSUE THREAD

**Issue by espansione8** [strapi/strapi#7265]
**Describe the bug**
the floating round button with "?" that opens the "GET STARTED VIDEOS" covers the pagination arrow 

**Steps to reproduce the behavior**
1. insert more than 20 documents in the collection
2. set 20 ( or more ) entries per page
3. Scroll down to the end of the table
4. See the help button covering the pagination arrow and can't click on it

**Expected behavior**
button on a higher place than pagination

**Screenshots**
![screen](https://user-images.githubusercontent.com/16583356/88924046-f8c53580-d272-11ea-8620-3d4c5d90740a.JPG)

**System**
- Node.js version: 14.5.0
- NPM version: 6.14.5
- Strapi version: 3.1.0
- Database: mongoDb
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! Thank you for reporting that.
Feel free to submit a PR to fix that. This should not be really complicated and a really good first issue to fix :)

**Comment by espansione8** [comment]
somebody else already did it :)
