### ISSUE TITLE
create project installation fail

### ISSUE THREAD

**Issue by vickylance** [strapi/strapi#7267]
**Describe the bug**
I followed the docs to create a new strapi project. Both 
`yarn create strapi-app my-project --quickstart`
and
`npx create-strapi-app strapi-project --quickstart`
But both of them failed in the following error.

**Steps to reproduce the behavior**

1. create a strapi project using yarn or npm on a MacOS

**Expected behavior**
All dependency Installation should happen flawlessly

**Screenshots**
![image](https://user-images.githubusercontent.com/5861833/88941789-114f4300-d2a7-11ea-8873-b665ab482711.png)
![image](https://user-images.githubusercontent.com/5861833/88941813-1b714180-d2a7-11ea-92ba-7aa55054dbf8.png)
Using yarn,
![image](https://user-images.githubusercontent.com/5861833/88941891-304dd500-d2a7-11ea-8851-257c7f628a4c.png)
Using npm,
![image](https://user-images.githubusercontent.com/5861833/88942021-55dade80-d2a7-11ea-8864-c0c301665ad3.png)

**Code snippets**
NA

**System**

- Node.js version:  v12.14
- NPM version: 6.14.5
- Strapi version: 3.1.2
- Database: sqlite
- Operating system: Mac OS Catalina

**Additional context**
This problem although related to the sharp library I believe the problem is present in the create-strapi-project because I am able to install the sharp library standalone just fine. I think this project is using an older version of sharp updating it might resolve.

**Comment by derrickmehaffy** [comment]
Similar [related issue](https://github.com/strapi/strapi/issues/6991#issuecomment-657515338) with a windows user, the issue here is with Sharp yes and how it ships a precompiled binary, I wasn't able to reproduce it on my Mac, Windows, or Linux machine so there is certainly an issue in the environment. :thinking:

**Comment by vickylance** [comment]
@derrickmehaffy  Can you tell me what OS version your mac is running on? Node version, npm version and yarn version?

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/88949859-ad962d00-d248-11ea-8e8f-59da98f1003c.png)

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/88950160-17aed200-d249-11ea-9695-306be80ec6b0.png)

**Comment by vickylance** [comment]
@derrickmehaffy  Ok I fixed it. I had to first install xcode command line tools
`xcode-select --install`
and then install the vips library.
`brew install vips`
and then finally create the strapi project.
`npx create-strapi-app strapi-project --quickstart`
