### ISSUE TITLE
Configure the view - not saved on git 

### ISSUE THREAD

**Issue by Acika00mk** [strapi/strapi#7271]
**Describe the bug**
When we change the view of the components, the changes are not saved on git. 

**Steps to reproduce the behavior**

1. Go to any collection type'
2. Click on any field
3. Change description and/or placeholder
4. Click Save
5. Check GIT status
6. No items changed

**Expected behavior**
To save the fields placeholder and description 

**Screenshots**
<img width="920" alt="Screen Shot 2020-07-30 at 11 18 55 PM" src="https://user-images.githubusercontent.com/4304026/88975781-1c13d300-d2bb-11ea-9c7f-3132be6295b8.png">

**System**

- Node.js version: v10.14.0
- NPM version:6.4.1
- Strapi version: 3.1.1
- Database: MySql/SQLLITE
- Operating system: MAC OS 

**Additional context**
If we deployed the project on another instance, the view will not be saved, nor placeholders saved

**Comment by derrickmehaffy** [comment]
Hello,

This is intended as you can change the view while in production (which isn't possible with things like the content-type-builder). There is a built in command to dump your content-manager views into a file and restore them.

Please see the following documentation for that: [dump](https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-configuration-dump-config-dump) and [restore](https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-configuration-restore-config-restore)

**Comment by derrickmehaffy** [comment]
Related to this, there is an entry in the FAQ that talks more about this: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#can-i-store-my-content-manager-layout-configurations-in-the-model-settings

**Comment by Acika00mk** [comment]
Thanks for the info, 
now it is easier with dump and restore. 
```
"dump:config": "strapi configuration:dump -f dump.json",
"restore:config" : "strapi configuration:restore -f dump.json"
```

**Comment by omaksi** [comment]
@derrickmehaffy I think it would make sense to make a `view configuration` section in the documentation. This important piece of info is a bit hidden in the FAQs.

**Comment by derrickmehaffy** [comment]
Hi @omaksi we are planning a massive rework/restructure of the documentation over the next few months and part of it is related to things like this.
