### ISSUE TITLE
Forgot password email settings stuck on defaults

### ISSUE THREAD

**Issue by lschjeide** [strapi/strapi#7272]
Hello, thank you so much for all the great work happening at Strapi!

I found an issue in 3.1.0 that is also occurring on 3.1.2.  To reproduce:

1. I added Sendgrid plugin following the instructions here: https://strapi.io/documentation/v3.x/plugins/email.html#configure-the-plugin
2. I attempted to add a custom email template and "from" "replyTo" using the instructions here: https://strapi.io/documentation/v3.x/admin-panel/forgot-password.html#customize-forgot-password-email
3. I did a simple POST /auth/forgot-password with {"email": "myemail@gmail.com"} and got the following error:
`{
  "statusCode": 400,
  "error": "Bad Request",
  "message": {
    "message": "Forbidden",
    "code": 403,
    "response": {
      "headers": {
        "server": "nginx",
        "date": "Fri, 31 Jul 2020 00:26:32 GMT",
        "content-type": "application/json",
        "content-length": "281",
        "connection": "close",
        "access-control-allow-origin": "https://sendgrid.api-docs.io",
        "access-control-allow-methods": "POST",
        "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
        "access-control-max-age": "600",
        "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html"
      },
      "body": {
        "errors": [
          {
            "message": "The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements",
            "field": "from",
            "help": null
          }
        ]
      }
    }
  },
  "data": {
    "message": "Forbidden",
    "code": 403,
    "response": {
      "headers": {
        "server": "nginx",
        "date": "Fri, 31 Jul 2020 00:26:32 GMT",
        "content-type": "application/json",
        "content-length": "281",
        "connection": "close",
        "access-control-allow-origin": "https://sendgrid.api-docs.io",
        "access-control-allow-methods": "POST",
        "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
        "access-control-max-age": "600",
        "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html"
      },
      "body": {
        "errors": [
          {
            "message": "The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements",
            "field": "from",
            "help": null
          }
        ]
      }
    }
  }
}`

I was able to curl successfully to sendgrid so I knew my email address was correctly verified so I inspected the message sent from strapi-provider-email-sendgrid/lib/index.js and it was using from: 'Administration Panel <no-reply@strapi.io>'.  The reply to address **was actually the one** I had set using the instructions.  The email was **not** the template I had created.

The template and default from appears to be coming from the bootstrap.js file in strapi-plugin-users-permissions where it is looking for configured JWT but not any config related to email from or template overrides.  I think this may be a regression from the new major changes introduced in 3.1.0.  Thanks in advance for looking into it or updating the docs as to where to put the overriding values.

**Comment by lschjeide** [comment]
OMG... this is in the UI.  I'm closing but I think the docs should be updated since it still says to create an email template file that is actually never used.

**Comment by dobregons** [comment]
@lschjeide I'm not sure how did you solve the issue but I am currently having the same problem :disappointed:
