### ISSUE TITLE
CORS issue - Strapi 3.0.4

### ISSUE THREAD

**Issue by M4r-t1n4** [strapi/strapi#7279]
**Describe the bug**
Hello,
i have this problem with CORS.
In my REACT project I have a GET request with axios but this request generates this error: 

_Access to XMLHttpRequest at 'http://localhost:1337/contents?kind=Resource' from origin 'http://localhost:8089' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response._

In the Strapi project I created the middleware.js file in the /config folder:

```
module.exports = {`
  `settings: {`
    `parser: {`
     ` enabled: true,`
      `multipart: true,`
      `includeUnparsed: true`
    `},`
    `cors: {`
    `enabled: true,`
      `origin: '*',`
      `credentials: true,`
      `methods: [`
      `"GET",`
      `"POST",`
      `"PUT",`
      `"PATCH",`
      `"DELETE"`
    `],`
      `headers: [`
       `"Origin",`
      `"Content-Type",`  
      `"Authorization"`
    `],`
    `},`
  `}`
`};
```

but the problem is not solved.
Do you have any suggestions to solve the problem?

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.6
- Strapi version: 3.0.4
- Database: MongoDB

**Comment by aksdevac** [comment]
`Access-Control-Allow-Origin` header is set on server you don't need to pass it from client, default cors config should work for most cases, you don't need to specify it in middleware json, for me its working out of the box with this config:
```js
module.exports = {
  load: {
    before: ['timer', 'responseTime', 'logger', 'cors', 'responses', 'gzip'],
    order: [],
    after: ['parser', 'router'],
  },
  settings: {
    timer: {
      enabled: true,
    },
  },
};
```
Your issues seems to be on client side just remove `Access-Control-Allow-Origin` header from client code.
