### ISSUE TITLE
User can not update their information

### ISSUE THREAD

**Issue by christroutner** [strapi/strapi#728]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.8.3

**Operating system**: Ubuntu 16.04 LTS

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
401 Unauthorized response when logged in user tries to update their own information.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Reproducing this bug uses the same repo used in Issue #722 

1. Wipe MongoDB to ensure you are starting with a clean environment:

* `mongo`
* `use strapi;`
* `db.dropDatabase();`
* `exit;`

2. Clone the test application that I use to reproduce this problem:

`git clone https://github.com/christroutner/sample-strapi-app`

3. Since this is an evolving repo, checkout the version that was current when this issue was reported:

`git checkout c8e6106684ca62e73a6ddfc5cc68a3f7aa95a1b6`

4. Run the test:

`npm install`

`npm run test`

5. Notice the last test involving the PUT command is getting an unexpected output. The logged in user should be able to change their own email address, but are instead getting a `401 Unauthorized` reponse.

**What is the expected behavior?**
The logged in user should be able to change their own email address, and they should receive a `200` response.

**Comment by lauriejim** [comment]
You have to check if your user can make this action. Update the role permissions he has in the admin pannel. By default guest user can't update an user.

isOwner policy to be able to update his own entries is coming.
