### ISSUE TITLE
 error Error: listen EACCES: permission denied 0.0.0.0:1337

### ISSUE THREAD

**Issue by alvics** [strapi/strapi#7285]
Started getting this error? Strapi won't run anymore? Everything was working fine the day before, nothing's changed on my end?
Tried running it in a different terminal as admin, still without success.
Not sure why it's not playing all of a sudden, has been a smooth run until now?
Using:
Windows 10
Starpi 3.0.6
sqlite3
localhost
------------
Error log
```
yarn run v1.22.4
$ strapi start
[2020-07-31T22:41:48.860Z] error Error: listen EACCES: permission denied 0.0.0.0:1337
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by aksdevac** [comment]
its EACCES error may be another process is using that port, or run as admin issues.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
