### ISSUE TITLE
Cannot create a new app

### ISSUE THREAD

**Issue by tiavina-mika** [strapi/strapi#7286]
I have this error when creating new app with mongodb

`Connection test failed: Cannot find module 'C:\Users\ASUS\AppData\Local\Temp\strapi8b97a083d50c\node_modules\strapi-connector-mongoose\lib\utils\connectivity.js'`

npm@6.14.7
strapi@3.1.0-beta.0
create-strapi-app@3.1.0-beta.0
node@12.14.0

**Comment by lauriejim** [comment]
Hello! What is the command you ran?

**Comment by tiavina-mika** [comment]
npx create-strapi-app my-project then select mongo

**Comment by lauriejim** [comment]
So why `3.1.0-beta.0`? I don't understand.
Do you have `strapi` install globally on your computer?

**Comment by tiavina-mika** [comment]
It's globally installed by `npm install -g strapi@beta`, I've already tried with `npm install -g strapi` and even uninstall it but I've always got the same error.

**Comment by lauriejim** [comment]
Can you please delete Strapi on your global stuff. 
Then clean your npm cache.
And then re-run this command `npx create-strapi-app my-project`
