### ISSUE TITLE
Please add MobX tutorial and docs too

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#729]
Please provide MobX integration guide. All of the tutorial and docs is based on Redux :disappointed:

**Comment by soupette** [comment]
Hi @mnlbox I will try to add a boilerplate with MobX in the [strapi-examples](https://github.com/strapi/strapi-examples) if I have the time...

**Comment by mnlbox** [comment]
@soupette Thanks man. It's fantastic news if we can use MobX as a first class citizen here in Strapi?

**Comment by soupette** [comment]
I'm not sure that the Admin will work with MobX for the moment...

**Comment by mnlbox** [comment]
What about using MobX in plugin level? Is it possible now?

**Comment by soupette** [comment]
I honestly don't know I haven't tried yet but in theory it should be.
