### ISSUE TITLE
strapi-admin  final client bundle size is 6.2MB ,event compile with production mode!

### ISSUE THREAD

**Issue by guanghw** [strapi/strapi#7290]
strapi-admin  final client bundle size is 6.2MB ,event compile with production mode!Am I the only one who thinks the final compiled file is too big?

**Comment by alpha771** [comment]
I think it is because the font awesome, i look the font awesome take almost the half of the size of bundle size

**Comment by lauriejim** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.

Then for this topic, I ping @soupette
