### ISSUE TITLE
Date type shows as day prior

### ISSUE THREAD

**Issue by simpleauthority** [strapi/strapi#7293]
**Describe the bug**
When you create a `date` type (not `datetime`, not `time`) and then apply a value, the displayed date is the day prior to the selected date.

I.e. if you choose October 1st, 2020, then the displayed date will be September 30th, 2020. It will still be saved as October 1st, 2020 in the data source.

**Steps to reproduce the behavior**

1. Go to 'Content-Types Builder'
2. Click `+ Create new component`
3. Enter a name, a category, and choose an icon. These don't matter
4. Add a `Date` field
5. Enter any name and choose `date` as the type
6. Click finish and save
7. Click `+ Create a new single type`
8. Enter any name and press continue
9. Add a `Component` field
10. Choose `Use an existing component` and press continue
11. Enter any name, choose the previously created component, and choose single or repeating
12. Finish and save
13. Choose the single type in the far left sidebar
14. Add an entry
15. Choose any date and press save
16. Refresh (if not automatic) and notice how the date is the day prior
17. Check the database and notice the date is the day chosen (problem in view layer only?)

**Expected behavior**
I expect to, for example, choose August 4th 2020 and see August 4th 2020 (not August 3rd 2020). I should not have to choose August 5th 2020 to see August 4th 2020.

**Screenshots**
DB: 
![db](https://i.imgur.com/rUErPX6.png)

UI:
![ui](https://i.imgur.com/FRXzC7g.png)

**System**

- Node.js version: was 14.7.0 (current), switched to 12.18.3 (LTS); no change
- NPM version: was 6.14.7 (current), switched to 6.14.6 (LTS); no change
- Strapi version: 3.1.3
- Database: MariaDB 10.5.4
- Operating system: Arch Linux (5.7.10-arch1-1)

**Additional context**
DB is running in docker. Let me know if I can provide more context.

**Comment by simpleauthority** [comment]
Cross-linking to slack thread https://strapi.slack.com/archives/C0BNGCDNH/p1596361843460300

**Comment by lauriejim** [comment]
Hello can you please check the date format that is sent in your request. To make sure there is no timezone conflict between your file system (computer), your browser and your database timezone configuration.

**Comment by simpleauthority** [comment]
@lauriejim How should I check that? This happens in the admin dashboard.

I will try and look at the outgoing network requests in the developer console.

**Comment by simpleauthority** [comment]
Sorry, I see what you meant. I just edited the job again, and set the date to **October 1 2017** and end date **February 2 2019**

According to dev tools, this is the (relevant part of) the request payload:
```
{
  "professional_experience": [
    {
      "start_date":"2017-10-01T19:00:00.000Z",
      "end_date":"2019-02-01T20:00:00.000Z"
    }
  ]
}
```

(I removed the id and other bits)...

And the response (again other bits removed)
```json
{
  "professional_experience": [
    {
      "start_date":"2017-09-30",
      "end_date":"2019-01-31"
    }
  ]
}
```

Interestingly, the request includes time info but the response does not...

**Comment by simpleauthority** [comment]
The database, hosted in Docker, was using UTC. My local system where I am testing strapi was using PDT.

Thus, when accessing Strapi, Strapi was showing the dates as PDT even if they were stored UTC in the db.

So, I solved this by editing `package.json` and changing the `develop` script to:
```json
"scripts": {
    "develop": "TZ=UTC strapi develop"
}
```

**Comment by lauriejim** [comment]
Awesome thank you for this update.
