### ISSUE TITLE
GraphQL createUser queries not working on 3.1.3

### ISSUE THREAD

**Issue by bbrez1** [strapi/strapi#7295]
**Describe the bug**

I have a fresh install of Strapi.

I'm just trying to create a new user using GraphQL Playground. Using simple queries from the tutorial.

**Code snippets**
`mutation {
  createUser(input: { data: { username: "John", email: "john@doe.com" } }) {
    user {
      username
      email
    }
  }
}`

Cannot return null for non-nullable field UsersPermissionsUser.username.

I'm getting the above error. Can create users in the admin dashboard without any issues.

**System**

- Node.js version: v12
- Strapi version: Latest (3.1.3)
- Database: MongoDB Atlas
- Operating system: Windows 10

**Comment by bbrez1** [comment]
I changed the required attribute on the username field to false and now I get the same error for email.

Cannot return null for non-nullable field UsersPermissionsUser.email.

**Comment by derrickmehaffy** [comment]
`Strapi version: Latest` Please actually clarify what "latest" means from your package.json

**Comment by bbrez1** [comment]
3.1.3

**Comment by bbrez1** [comment]
I have just tried with a new install (quick start option) and I still get the same issue with graphql.

**Comment by lauriejim** [comment]
Hello! when you create a user, you should have a `password` key.
I tried adding this `password` key and it works fine.

**Comment by woohoou** [comment]
Hi @lauriejim!, when I create a user with an existing username or email I have the same error message.
I already have the password key as a query variable, if I add the password key into the mutation I have the message
`Cannot query field "password" on type "UsersPermissionsUser".`

This is a bug? Or am I doing something wrong?.

**Comment by derrickmehaffy** [comment]
@woohoou we will need more information as I just tested as Jim did, and it appears to working fine. Do you have any extensions done to the users-permissions plugin (other change changing required)

**Comment by woohoou** [comment]
Thank you for the quick response @derrickmehaffy.

Yes, the user model has another extra text element, and the database is a migration coming from beta. Do you think this could be related?

**Comment by derrickmehaffy** [comment]
I'm not sure, for us to be able to fix a bug we actually need to be able to reproduce it. So we need clear steps on how to reproduce the bug locally

**Comment by onsombal** [comment]
If it helps, below is a playground example for creating a user. 

```
mutation
  createUser($input: createUserInput!) {
    createUser(input: $input) {
      user {
        username
        email
      }
    }
  }
```
QUERY VARIABLES:
```
{
  "input": {
    "data": {
      "username": "jim@gmail.com",
      "email": "jim@gmail.com",
      "password": "123456"
    }
  }
}
```

HTTP HEADERS
```
{
  "authorization": "Bearer eyJhbGciOiJIU... _use your token_"
}
```
