### ISSUE TITLE
Can't fix CORS blocking 

### ISSUE THREAD

**Issue by Antoine-lb** [strapi/strapi#7296]
**Describe the bug**
Don't think is a bug but I just can't fix the CORS issue.

**Steps to reproduce the behavior**

1. Add:
```
{
  "cors": {
    "enabled": true,
    "origin": "*"
  }
}

```
in `config/security.json`
2. Re-lunch server (on localhost:1337)
3. Lunch frontend (Gatsby on localhost:8000)
4. Try a POST request
5. Get Blocked by CORS (Chromium and Firefox)

**Code snippets**
Front-end fetch:
```
    const response = await fetch(`${process.env.STRAPI_SERVER}/orders`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    })
      .then(async () => {
        const order = await response.json()
        setSuccess(true)
      })
```

**System**

- Strapi version: 3.0.5

**Additional context**
Some of the errors from the browsers:

Firefox:
```
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://myapp.herokuapp.com/orders. Raison : échec de la réponse de pré-vérification des requêtes CORS.
```
```
...
Raison : échec de la requête CORS.
```

Chromium:
```
Access to fetch at 'http://localhost:1337/orders' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```
```
Access to XMLHttpRequest at 'http://localhost:61708/socket.io/?EIO=3&transport=polling&t=NEp78Vl' from origin 'http://localhost:8000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
``` 

I think I'm writting the config file wrong and the parameters are not being taken into account. `GET` works well, the problem happens with `POST`.

Thanks for the help!

**Comment by lauriejim** [comment]
Hello! I'm not sure the way you managed the cors config is the right.
According to this docs - https://strapi.io/documentation/v3.x/concepts/middlewares.html#configuration-and-activation
Please can you check that format and tell me is the issue persists.

**Comment by Antoine-lb** [comment]
`./config/security.js`
```
module.exports = {
  settings: {
    cors: {
      enabled: false, // tried true and false
      origin: "*",
    },
  },
};

```

`./config/middleware.js`
```
module.exports = ({ env }) => ({
  load: {
    before: [
      "boom",
      "sentry",
      "responseTime",
      "logger",
      "cors",
      "responses",
      "gzip",
    ],
  },
  settings: {
    sentry: {
      dsn: env("SENTRY_DSN"),
      enabled: true,
    },
    cors: {
      enabled: false, // tried true and false
      origin: "*",
    },
  },
});

```

Same result, can you spot something weird so I can dig into it? It should be in the `middleware` or the `security` config?

**Comment by derrickmehaffy** [comment]
The `./config/security.js` isn't used, those settings should be in that `middleware.js` file

**Comment by Antoine-lb** [comment]
Never mind, got environments messed up, thanks for the help

**Comment by derrickmehaffy** [comment]
No problem, glad you figured it out :)

**Comment by Antoine-lb** [comment]
Hello again,
So it is working on local (it wasn't before). But when I deploy it to Heroku the CORS issue appears again.

Production built on my local computer works. Actually I can't even break it, cors enabled or disabled everything still works.

Even tried creating a differente env folder but nothing happens.

I'm not able to reproduce the error on my computer, only happens on Heroku.

Can it be because I'm using a `.herokuapp.com` domain name?
How can I check if the proper config file got executed?

**Comment by derrickmehaffy** [comment]
@Antoine-lb is your code somewhere public such as a Github or Gitlab repo that I can take a look?

**Comment by Antoine-lb** [comment]
@derrickmehaffy [here](https://github.com/Antoine-lb/bc-backend/)

**Comment by derrickmehaffy** [comment]
Based on your config structure you shouldn't be getting an issue with CORS in production (do note though that your `./config/environments/*` folder will be ignored as that structure no longer applies, I assume this is just left over from before you migrated, there is a new system for the stable release).

The default CORS middleware settings should not throw any issues in any environment as it pretty much allows for anything.

**Comment by lauriejim** [comment]
Now it's `config/env` and not `config/environments` this could help I think.

**Comment by Antoine-lb** [comment]
I tried everything, but nothing worked. Migrated from 3.0.5 to 3.1.3 and it worked.

**Comment by lauriejim** [comment]
Thank you for the update.

**Comment by hongsw** [comment]
strapi 3.0.0 is not work.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by akshaybilani** [comment]
Hi
I am facing CORS blocking I am not able to fix this problem
Front end-Ionic 3 App
Server Strapi( 3.1.3)
It is running in local and working fine postmen
I used all instruction  according to git hub but I am not able to find a solution, please help me
APP-
Request URL: http://localhost:1337/auth/local/register
Referrer Policy: strict-origin-when-cross-origin
Request Headers
Provisional headers are shown
Accept: application/json, text/plain, */*
Content-Type: application/json
Referer: http://localhost:8100/
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR4.170623.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Mobile Safari/537.36
x-clientapp: outstaycustomer
server -
[2020-10-03T11:23:37.113Z] debug OPTIONS /auth/local/register (11 ms) 204
App error-
Access to XMLHttpRequest at 'http://localhost:1337/auth/local/register' from origin 'http://localhost:8100' has been blocked by CORS policy: Request header field x-clientapp is not allowed by Access-Control-Allow-Headers in preflight response. (edited)

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by hariangr** [comment]
I am at strapi 3.2.5 and still can't make it work
config/security.js
```
module.exports = {
  settings: {
    cors: {
      enabled: true, // tried true and false
      origin: "*",
    },
  },
};
```

config/middleware.js
```
module.exports = ({ env }) => ({
  settings: {
    cors: {
      enabled: true, // tried true and false
      origin: "*",
    },
  },
});
```

Can anyone give me an update? tried to PUT to https://crowdcycle-stg.herokuapp.com//organizations/avatar, with FormData (Image) won't work

Btw I don't know if it's relevant, but doing POST (Without embedding files) works fine

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by vladislav-puzyrev** [comment]
+1

**Comment by ruturajsolanki230** [comment]
This issue can be fix by simply adding
`cors: { enabled: true, headers: '*' }`
in `./config/middleware.js`

**Comment by hsian** [comment]
> This issue can be fix by simply adding
> `cors: { enabled: true, headers: '*' }`
> in `./config/middleware.js`



> This issue can be fix by simply adding
> `cors: { enabled: true, headers: '*' }`
> in `./config/middleware.js`

worked for me! thanks for the help

**Comment by ninjanoir** [comment]
check the JWT secret have to be different than the ADMIN secret key at the ENV variables

**Comment by XaFaK-01** [comment]
How to fix No ‘Access-Control-Allow-Origin’ header is present on requested resource?

I am using strapi 3.6.10 and here's the ./config/middleware.js configuration:

`module.exports = {
  settings: {
    cors: {
      enabled: true,
      origin: '*',
      headers: [
        'Content-Type',
        'Authorization',
        'Origin',
        'Accept',
        'Cache-Control',
      ],
    },

    parser: {
      textLimit: '10mb',
      formLimit: '10mb', // modify here limit of the form body
      jsonLimit: '10mb', // modify here limit of the JSON body
      formidable: {
        maxFileSize: 100 * 1024 * 1024, // multipart data, modify here limit of uploaded file size
      },
    },
  },
};
`

I am facing this issue on the production version of the code hosted on heroku.
