### ISSUE TITLE
A 'configure the view' button doesn't work correctly in Content-Types Builder.

### ISSUE THREAD

**Issue by ByungJun25** [strapi/strapi#7301]
**Describe the bug**
A 'configure the view' button doesn't work correclty in Content-Types Builder.

**Steps to reproduce the behavior**

1. Go to 'Content-Types Builder'.
2. Select any Collection types and click Configure the view. (First trying works well)
3. Click back button.
4. Select other collection types and click Configure the view.
5. See error.

**Expected behavior**
The function should show the correct view of what user select.

**Screenshots**
![bug](https://user-images.githubusercontent.com/10557621/89194565-d3ecfd00-d5a7-11ea-8406-23232046effa.gif)

**Code snippets**
Nothing.

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.5
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Windows 10 / Docker

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for the bug report, I was able to reproduce this on the latest version (v3.1.3) as you specified. For this issue I will ping @soupette and @HichamELBSI . If you would like to help by submitting a pull request you can. If you aren't sure where to start, no problem we will take a look into this ASAP.

**Comment by ByungJun25** [comment]
Hello, @derrickmehaffy 

Well, I find a reason now, but @soupette solves it before 24 minutes. ;D

Thanks strapi Teams! :D

Bynungjun Woo
