### ISSUE TITLE
Correlation ID concept. 

### ISSUE THREAD

**Issue by vejandla** [strapi/strapi#7308]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
how can I access ctx globally?

**Why?** I would like to assign a unique request id to every incoming request and wanted to use that request id whenever I log a request, So I can trace what a specific user is doing as part of the request. 

I already have my authentication middleware which fills claims to the ctx as part of the middleware, I can also add a requestId too. But, I do not want to pass context to my logger function for everycall. Is there a way to access the ctx globally, So I can add the requestId and user info along with every log. 

Hoping I'm not reinventing the wheel here. If so, Please let me know what I should be using for this functionality. 

Thanks in advance.

**Comment by derrickmehaffy** [comment]
Hello, I'm going to mark this as closed as you already have an open discussion: https://github.com/strapi/strapi/discussions/7307

Lets keep the discussion there. Thank you!
