### ISSUE TITLE
Strapi CLI always requires database user and password arguments

### ISSUE THREAD

**Issue by msgeissler** [strapi/strapi#732]
**Node.js version**:
8.9.4
**npm version**:

**Strapi version**:
3.0.0-alpha.10.1
**Operating system**:
Alpine Linux

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When using arguments to define the database, the strapi CLI (https://strapi.io/documentation/cli/CLI.html) requires a database user and password to be provided, even if the database does not need any authentication.
**If the current behavior is a bug, please provide the steps to reproduce the problem**
Setup a database without authentication, as is the default e.g. for the official mongodb Docker image, and try to create a new strapi project using the CLI arguments. Using empty values for _--dbusername_ and _--dbpassword_ does not work, neither does leaving out those argmunets.

> Some database arguments are missing. Required arguments list: dbclient,dbhost,dbport,dbname,dbusername,dbpassword

**What is the expected behavior?**
I can define a database connection using the CLI and arguments without requiring a user and password if the database does not require one.

Not using any form of authentication is definitely not something you want to do (in production), but for (fast) local development and testing of strapi and with a database that supports it, it should definitely be possible.

**Comment by msgeissler** [comment]
Not sure if I made a mistake or if it actually works using a different syntax.
I just found the updated docker image and the repository for it. The image actually works without a user and password but is also using a different CLI syntax.
Was this perhaps already changed or is that a result of the different syntax used?
https://github.com/strapi/strapi-docker/blob/master/strapi.sh

**Comment by lauriejim** [comment]
You can actually let an empty string in `username` and `password` input if you don't require authentication. It should work.

**Comment by msgeissler** [comment]
The problem I see is that with the way you show how to use the CLI parameters in https://strapi.io/documentation/cli/CLI.html, the empty username should actually cause the password to become the username (unless you have some special handling for that in strapi):
`--dbname <dbname> --dbusername <dbusername> --dbpassword <dbpassword>`

In https://github.com/strapi/strapi-docker/blob/master/strapi.sh @lucaperret is actually using
`--dbusername=$DATABASE_USERNAME --dbpassword=$DATABASE_PASSWORD` to assign the values. Note the additional "=".

Here are some examples:
No user and password:
> strapi new test --dbclient mongo --dbhost mongo --dbport 27017 --dbname test
INFO (1 on 06b1c63a12ec): Creating your application... It might take a few seconds.
WARN (1 on 06b1c63a12ec): Some database arguments are missing. Required arguments list: dbclient,dbhost,dbport,dbname,dbusername,dbpassword

Empty user and password:
> strapi new test --dbclient mongo --dbhost mongo --dbport 27017 --dbname test --dbusername --dbpassword
INFO (1 on 0de0bc27a48f): Creating your application... It might take a few seconds.
WARN (1 on 0de0bc27a48f): Some database arguments are missing. Required arguments list: dbclient,dbhost,dbport,dbname,dbusername,dbpassword

Using the other syntax to define user and password:
> strapi new test --dbclient mongo --dbhost mongo --dbport 27017 --dbname test --dbusername= --dbpassword=
INFO (1 on 82c220486043): Creating your application... It might take a few seconds.
INFO (1 on 82c220486043): Lets configurate the connection to your database:
INFO (1 on 82c220486043): Database determined by CLI args: mongo
INFO (1 on 82c220486043): Testing database connection...

I think the documentation should be changed to show the syntax using "=", unless there is a mistake in my tests.
I will do a PR for that part of the documentation in a few minutes, but maybe you can check for other parts that should be changed as well.

**Comment by lucaperret** [comment]
LGTM
