### ISSUE TITLE
Typo on custom admin guide in documentation

### ISSUE THREAD

**Issue by diwakersurya** [strapi/strapi#7322]
**Describe the bug**
There is a typo on custom admin page in guides section where it show wold! instead of world!

**Steps to reproduce the behavior**

1. Go to https://strapi.io/documentation/3.0.0-beta.x/getting-started/introduction.html
2. Click on "custom admin" submenu under "guides" menu item
3. Click on section "Update the admin home page"
4 Search for "Wold!"

**Expected behavior**
It should be World! instead of Wold!

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
Hello as of right now we are not updating the beta documentation as the beta versions are no longer supported.

I will mark this issue as closed, but thank you for creating one.
