### ISSUE TITLE
Can't access bookshelf in bootstrap.js

### ISSUE THREAD

**Issue by nnennajohn** [strapi/strapi#7326]
**Describe the bug**

Can't access bookshelf in bootstrap.js as described in docs (https://strapi.io/documentation/v3.x/concepts/configurations.html#database-orm-customization)

Also unrelated, please tell how to get rid of APOLLO_KEY error, as I've added that key in my .env file, yet the error persists.

**Steps to reproduce the behavior**

Add (bookshelf, connection) as params in bootstrap func, and console.log it. It shows undefined in both.

**Expected behavior**
Access bookshelf so you can load plugin.

**Screenshots**

<img width="1139" alt="Screen Shot 2020-08-04 at 1 07 58 PM" src="https://user-images.githubusercontent.com/1761197/89340171-2c79d400-d654-11ea-86f3-3465cfaee43d.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
V12
- NPM version:
6.14.6
- Strapi version: 
3.1.2
- Database: Postgres
- Operating system:
MacOS

**Additional context**

**Comment by derrickmehaffy** [comment]
Just to clarify, you are referring to this guide correct? https://strapi.io/documentation/v3.x/concepts/configurations.html#database-orm-customization

**Comment by nnennajohn** [comment]
@derrickmehaffy correct. Updated. Thanks.

**Comment by derrickmehaffy** [comment]
Can you please try adding the `const bookshelf = require('bookshelf') to the top of that file? then proceed as normal with any other custom configurations.

**Comment by lauriejim** [comment]
Hello! Warning the related documentation talk about a file named `./config/functions/bookshelf.js` and not `./config/functions/bootstrap.js`.

**Comment by nnennajohn** [comment]
Thanks @lauriejim . will check that.
