### ISSUE TITLE
The js file is too large and the page opens very slowly

### ISSUE THREAD

**Issue by xiaoer3301** [strapi/strapi#7329]
![00006D6D6F593DB00A859C2F8F604137](https://user-images.githubusercontent.com/49556560/89378336-27855500-d726-11ea-982c-eb687b8874b9.jpg)

Can developers optimize this file? Even if max-age=2592000, sometimes it still needs to be reloaded.
When the network is slow, it really takes a long time.
After some people pack it, main.js even exceeds 10M.

**Comment by petersg83** [comment]
Hi, thanks for the issue :)

How did you build it?
If it was built using `yarn develop` the build is not optimized.
If you do `yarn build`, the build is optimized.
Can you compare the two version sizes please?

**Comment by lauriejim** [comment]
Hello! I'm closing this issue, related to this discussion.
https://github.com/strapi/strapi/discussions/7290
