### ISSUE TITLE
Getting started has a faulty tutorial page link

### ISSUE THREAD

**Issue by msgeissler** [strapi/strapi#733]
**Browser version**:
Chrome 64.0.3282.186

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Going to the tutorial from the getting started page leads to a "buggy" tutorial page. None of the links work (as they seem to lack _/documentation_ in their path). The reason seems to be a missing slash at the end of the URL that is used on that page.
Getting started tutorial link: https://strapi.io/documentation/tutorials <- does not work properly and generates wrong URLs for other pages
Documentation tutorial link: https://strapi.io/documentation/tutorials/ <- does work
**If the current behavior is a bug, please provide the steps to reproduce the problem**
Open the [getting started page](https://strapi.io/getting-started) and click on tutorial at the bottom of the page.
**What is the expected behavior?**
The tutorial page linked in the getting started section works properly.

**Comment by msgeissler** [comment]
For https://strapi.io/documentation (which is also used on the getting started page) there seems to be an automatic redirect on the server to https://strapi.io/documentation/.
There is no such redirect for https://strapi.io/documentation/tutorials.

**Comment by lauriejim** [comment]
Hi @msgeissler thank you for this issue.
