### ISSUE TITLE
Load testing with thousands of concurrent requests

### ISSUE THREAD

**Issue by yogesh-dalvi** [strapi/strapi#7332]
**Load testing with thousands of concurrent requests**

If Load tested the application with **Jmeter** with 300-400 concurent requests then the application renders every requests but when the number of requests are increased to >500 then the appliction rejects most of the requests.

**Steps to reproduce the behavior**

1) Download Jmeter.
3) Create a new test plan and a new Thread group.
2) Increase number of threads to more than 500 in thread group
3) Set ramp-up period to 0 
4) Set loop count to 1
5) Test a Strapi post request by adding Sampler > HTTP Request
6) Add A LIstner> View results in table as Chlld to the Http request.
7) Simultate the test plan. Most of the requests are getting rejected.

For a normal Restful Nodejs application having a post method the requests are not rejected.
Is there any way by which the above scenario can be handled?

**Comment by derrickmehaffy** [comment]
We need more information here.

Strapi version, host OS, Database type, Database location (local/remote), type of deployment (IE where is it deployed).

In this case there is too many unknown variables to say for sure.
