### ISSUE TITLE
Can't add bootshelf plugin

### ISSUE THREAD

**Issue by francescofact** [strapi/strapi#7339]
Hi, i'm trying to add a plugin to my bookshelf.
i installed the plugin with 
`npm install --save bookshelf-simplepaginate`
then i created the file in _config/functions/bookshelf.js_
with:
```
'use strict';

module.exports = (bookshelf, connection) => {
  bookshelf.plugin(require('bookshelf-simplepaginate'));
};
```

But strapi goes in bootloop saying:
```
0|Strapi  | [2020-08-05T15:54:33.294Z] debug ⛔️ Server wasn't able to start properly.
0|Strapi  | [2020-08-05T15:54:33.301Z] error TypeError: require(...) is not a function
0|Strapi  |     at Object.keys.filter.map.connectionName (/home/pi/strapi/node_modules/strapi-connector-bookshelf/lib/index.js:62:36)
0|Strapi  |     at Array.map (<anonymous>)
0|Strapi  |     at Object.initialize (/home/pi/strapi/node_modules/strapi-connector-bookshelf/lib/index.js:46:8)
0|Strapi  |     at Object.initialize (/home/pi/strapi/node_modules/strapi-database/lib/connector-registry.js:30:25)
0|Strapi  |     at DatabaseManager.initialize (/home/pi/strapi/node_modules/strapi-database/lib/database-manager.js:36:27)
0|Strapi  |     at Strapi.load (/home/pi/strapi/node_modules/strapi/lib/Strapi.js:297:19)

```

What am i doing wrong?

**Comment by derrickmehaffy** [comment]
@alexandrebodin @lauriejim do you have any suggestions here?

**Comment by alexandrebodin** [comment]
bookshelf.plugin must be called with a string not a required module :) try bookshelf.plugin('bookshelf-simplepaginate')

**Comment by derrickmehaffy** [comment]
> bookshelf.plugin must be called with a string not a required module :) try `bookshelf.plugin('bookshelf-simplepaginate')`

Ah so our documentation is wrong: https://strapi.io/documentation/v3.x/concepts/configurations.html#database-orm-customization

I'll submit a PR to fix this, @alexandrebodin can you confirm if they need to require this package anywhere or just adding the name of the plugin and installing it into their package.json is enough?

**Comment by alexandrebodin** [comment]
it is enough yes
