### ISSUE TITLE
Add some custom filed to user profile

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#734]
I want add some custom fields to users profile (all user except admin), for example simple fields like `name`, `family`, `gender`, ... or more complex fields like `company` (that a relation to another content type). When I add these fields to `/plugins/user-permission/models/User.setting.json` my app not working at all with error's like this:
```
Something went wrong in the model 'User' with the attribute 'userCompany'
```

Can you guide me to do this with Strapi

**Comment by lauriejim** [comment]
Hello @mnlbox I can't reproduce it on my machine with mast version of Strapi.
I cant make relations and add new fields.

Can you share your models please.

**Comment by mnlbox** [comment]
@lauriejim sorry I see your comment now. What model file you need?
Please reopen this man. :wink:

**Comment by mnlbox** [comment]
@lauriejim I'm searching a way to split my custom field on user profile from core code. Anyway for this now? Or is it in roadmap?

**Comment by lauriejim** [comment]
It's a part of the plugin extension, it's in the roadmap.
But actually not possible to did it.

**Comment by ht10vn** [comment]
Hello @mnlbox, I have the same issue with you, need to add some custom fields to users profile. 
I created new Content Type "extra_user" with some extra fields: name, family, gender,..., user_id - which user_id has relationship 1:1 to Users. So you can manage your extra user info.
