### ISSUE TITLE
3.1.3, Admin is unable to log into admin panel

### ISSUE THREAD

**Issue by Maris1984** [strapi/strapi#7343]
I've migrated to 3.1.3 and got stuck upon admin login, where the form now requires an email instead of an admin username. Had multiple users registered with the same e-mail address, so the reset password did not work.

Deleted admin user from SQLite table "strapi_administrator" and was able to register a new admin user, however - every time I try to login with the new admin user, it keeps redirecting me back to the login page.

Console shows that `/admin/users/me/permissions` and `/content-manager/content-types` responds with 401 Unauthorized.

Is there anything I can do to be able to log in again?

**UPDATE.**
Node version: 12.16.1
Npm version: 6.13.4
Strapi version: 13.1.3
Database: SQLite (created by quickstart)
OS: Mac OSX 10.11.6

The only extension that I have implemented - JWT storage in HttpOnyl cookie, as per [this guide](https://talke.dev/strapi-user-permissions-jwt-cookies).

**Comment by derrickmehaffy** [comment]
I will ping @alexandrebodin to explain in more detail if I'm missing something, but with the v3.1.x we had to change the identifiers that are allowed to be used to login to the admin as we have changed over to using passport.js in the admin panel.

Currently it only allows for and checks for the email, code from the admin for that: https://github.com/strapi/strapi/blob/7113f7f11f391c571a317004b63b3daf5fc5e25e/packages/strapi-admin/middlewares/auth/index.js#L6-L20

And the username field is now marked as not required and is no longer unique either, it's an optional field. You won't be able to have multiple administration users with the same email in this case. Currently that code I linked cannot be modified using the normal extensions system and the `strapi-admin` package would need to be forked to change how it works.

**Comment by Maris1984** [comment]
I'm perfectly fine with having a one admin user only, however, I'm for some reason unable to log in with that user, even after registering a new admin user with a unique email address that's never used by any other user.

**Comment by derrickmehaffy** [comment]
That is certainly something we should dig into @Maris1984 can you please update your original bug post and follow the bug template so we can try to reproduce it, normally we would close issues that don't follow the template as it provides us enough information to at least attempt to reproduce it.

**Comment by alexandrebodin** [comment]
I think the issue might be coming from using extensions on the users-permissions plugin

**Comment by Maris1984** [comment]
Updated the original post with some additional info.
Let me know, if there's anything else I can share, to help you determine the cause.

**Comment by Berend-Kalberg** [comment]
Same issue coming from 3.0.5. When I test the version locally. `[2020-08-10T10:14:55.608Z] debug GET /users-permissions/init (2 ms) 404`. Its is stuck on the loading animation. When I test on my production server I get past the loading animation but get an internal server error message at the top of the login fields when I use the right email address. When I use wrong credentials I get an error for wrong credentials. So it has something to do after using the right credentials.

Had to revert to 3.0.5 for now.

**Comment by alexandrebodin** [comment]
Do you have a custom implementation of the permissions.js policy inside the extensions/users-permissions/config/policies ? If so you need to update your extension accordingly after any upgrade as this can break internal code.

**Comment by Berend-Kalberg** [comment]
I have not done anything custom to my Strapi backend. All I did was create an admin user after create-strapi-app. Nothing custom at all. All I have in extensions/user-permissions/config (I dont have a policies folder) is a jwt.js file with some sort of key in there.

`module.exports = {
  jwtSecret: process.env.JWT_SECRET || 'KEY'
};`

**Comment by Maris1984** [comment]
> Do you have a custom implementation of the permissions.js policy inside the extensions/users-permissions/config/policies ? If so you need to update your extension accordingly after any upgrade as this can break internal code.

I indeed had custom implementation in permissions.js policy. 
Updated the code accordingly and the login now succeeds.
Thank you!

**Comment by derrickmehaffy** [comment]
Thank you for the update @Maris1984 I'm going to mark this as closed as you solved your issue (related to using extensions to the permissions policy)

**Comment by vince1995** [comment]
@alexandrebodin you should note that in the migration guide. 😅

**Comment by alexandrebodin** [comment]
@vince1995 this is the first warning of the migration guide :)
