### ISSUE TITLE
Subsequent Content Type creates fail with a PostgreSQL database

### ISSUE THREAD

**Issue by brondhaish** [strapi/strapi#7346]
**Describe the bug**
Post install of Strapi, I was able to create a Content Type (Collection) via the web Builder. Returning to my deployment at a later stage where I tried to create another Content Type (either Collection or Single). I was met with disappointment after clicking on it in the sidebar, under "Collection Types" heading.

**Steps to reproduce the behavior**
It cannot be as trivial as the steps below, but that's more or less all that was done from a user perspective.
 
1. Create a Content-Type.
2. Populate some data for that Content-Type.
3. Create another Content-Type after some restarts.
4. Navigate to it in the "Collection Types".

The same behavior is observed if attempting to create it via the CLI.

**Expected behavior**
Content-Type created successfully, can be viewed through the menu bar and user able to populate it with data normally.

**Screenshots**
![error-pop-up](https://user-images.githubusercontent.com/40338108/89463804-507a0a00-d767-11ea-93fb-f6f312ad4c26.png)

**System**

- Node.js version: v12.16.1
- NPM version: 6.14.6
- Strapi version: 3.1.3
- Database: PostgreSQL 11.8
- Operating system: CentOS 8.2.2004 (via Docker). Observe the same on OS X Catalina 10.15.6.

**Additional context**
*Debug Log File* [output.txt](https://github.com/strapi/strapi/files/5031057/output.txt)

The core of the problem is that the table for the Content Type is not being created. Naturally, Strapi fails to select from a non-existent table, upon the user selecting the Content Type from side-bar. 

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 10 ],
  __knexQueryUid: 'b7545ce8-9018-4ee8-a34e-f597672250e3',
  sql: 'select "buggies".* from "buggies" order by "id" asc limit ?'
}
[2020-08-05T20:45:12.473Z] error error: relation "buggies" does not exist
    at Parser.parseErrorMessage (/Users/lololol/Projects/strapi-cms/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/lololol/Projects/strapi-cms/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/lololol/Projects/strapi-cms/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/lololol/Projects/strapi-cms/node_modules/pg-protocol/dist/index.js:8:42)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23
```

A row IS inserted in `core_store` with key `plugin_content_manager_configuration_content_types::application::buggy.buggy`.

**Database configuration file**

```
var fs = require('fs');

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: 'db-host.com',
        port: 25060,
        database: 'cms',
        username: 'strapi',
        password: 'my_strapi_password',
        schema: 'public',
        ssl: {
          ca: fs.readFileSync('/Users/lololol/Projects/strapi-cms/psql.pem').toString(),
        } 
      },
      options: {
        debug: true,
        useNullAsDefault: true,
        autoMigration: false,
        pool: {
          min: 5,
          max: 5
	}
      },
    },
  },
});
```

**Comment by derrickmehaffy** [comment]
@brondhaish is your project somewhere public like github that we can test with?

**Comment by brondhaish** [comment]
I can look to put an archive together/create a repo. What exactly is required that would be of help to you? The whole /strapi directory? Unfortunately DB access is not something I can provide you with, but perhaps a dump of the tables of interest would suffice?

**Comment by brondhaish** [comment]
One more, potentially crucial, point I realised I failed to mention is that originally I installed version 3.1.1 and hit this issue. After doing some debugging, I upgraded to 3.1.3, by updating the package.json file, deleted the `build` directory and started again with `npm run develop`. Funny enough, I was able to create a new Content Type upon starting 3.1.3, but then trying to create one more afterwards failed (as was the case with 3.1.1).

**Comment by brondhaish** [comment]
@derrickmehaffy I played with the `database.js` section `options`, namely by removing `useNullAsDefault: true` and `autoMigration: false`. It began working as expected.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I played with the `database.js` section `options`, namely by removing `useNullAsDefault: true` and `autoMigration: false`. It began working as expected.

That is extremely odd :thinking:

**Comment by kcouliba** [comment]
I am currently encountering the pretty same issue except for that error pops up when I try searching for any content-type.
Unfortunately, I can't give more details on what causes the issue.

![image](https://user-images.githubusercontent.com/6125608/89965270-b3c6d900-dc4c-11ea-8351-4070c2dfd485.png)

**Comment by derrickmehaffy** [comment]
@kcouliba can you try updating to the latest release v3.1.3

**Comment by kcouliba** [comment]
Upgrading to version 3.1.3 resolves my issue. Thanks @derrickmehaffy

**Comment by vnitMendapara** [comment]
i am facing same error **error: relation "X" does not exist .**
i have version 3.1.4 installed on my machine.
i tried to debug and found that it is not creating Postgres table for content-type when i am creating new content-type via admin UI. any solution for that?

**Comment by derrickmehaffy** [comment]
@vnitMendapara can you please provide a link to your project code? We still have not been able to reproduce this locally, and without any steps to reproduce we cannot track down the source of the problem.

Alternatively if you can provide a fresh project where you have successfully reproduced the issue, that would also be quite helpful

**Comment by vnitMendapara** [comment]
i just updated strapi using migration guide and i am facing this issue.

sorry but i cant share current project as this is client's project.

in fresh installation it works fine.

**Comment by derrickmehaffy** [comment]
If it works in a fresh installation then it appears the bug is at your own project level, we will need more information to be able to assist, as it's not likely an issue with Strapi itself.

**Comment by derrickmehaffy** [comment]
Closing as user has provided no new information.

**Comment by madkarlsson** [comment]
I ran into this just now. 

It happened when I tried to create a second content type (collection) and the server refused to restart after saving, with the message:

```
error: update "<collection_name>" 
set "published_at" = "created_at" where "published_at" is null - relation "<collection_name>" does not exist
```
_<collection_name> could be anything_

However, indifference from https://github.com/strapi/strapi/issues/7346#issuecomment-670169627 it wasn't until I set the Knex options `useNullAsDefault` to true (this seems undocumented in your docs btw) that it was fixed (`autoMigration` is default and specified at all in my config).

This leads me to believe that it had something to do with the "required" field setting I used on some fields in the new content type (the old content type don't have that) but haven't looked into it further.

**Comment by Louvki** [comment]
> I ran into this just now.
> 
> It happened when I tried to create a second content type (collection) and the server refused to restart after saving, with the message:
> 
> ```
> error: update "<collection_name>" 
> set "published_at" = "created_at" where "published_at" is null - relation "<collection_name>" does not exist
> ```
> 
> _<collection_name> could be anything_
> 
> However, indifference from [#7346 (comment)](https://github.com/strapi/strapi/issues/7346#issuecomment-670169627) it wasn't until I set the Knex options `useNullAsDefault` to true (this seems undocumented in your docs btw) that it was fixed (`autoMigration` is default and specified at all in my config).
> 
> This leads me to believe that it had something to do with the "required" field setting I used on some fields in the new content type (the old content type don't have that) but haven't looked into it further.
> 
> Using Postgres and Knex before I do remember that `useNullAsDefault` was kind of important but I do not quite remember why. On Strapi 3.4.3.

+1 Just went through it as well!

**Comment by Louvki** [comment]
@madkarlsson +1 
Just hapened to me as well. Using Postgres.
