### ISSUE TITLE
Installer script fails on Windows

### ISSUE THREAD

**Issue by srsgores** [strapi/strapi#7347]
**Windows Installation Fails**
Using the latest Node `14.7.0` on WIndows 10, installation fails using custom settings.  More specifically, `node-gyp` fails to compile its native binaries, even when `windows-build-tools` are installed:

> Error while installing dependencies:
> npm WARN npm npm does not support Node.js v13.12.0
> npm WARN npm You should probably upgrade to a newer version of node as we
> npm WARN npm can't make any promises that npm will work with this version.
> npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10.
> npm WARN npm You can find the latest version at https://nodejs.org/
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
> npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
> npm WARN deprecated buildmail@3.10.0: This project is unmaintained
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.0/libvips-8.9.0-win32-x64.tar.gz
> info sharp Creating C:\Users\user\github\strapi-test\node_modules\sharp\build\Release
> info sharp Copying DLLs from C:\Users\user\github\strapi-test\node_modules\sharp\vendor\lib to C:\Users\user\github\strapi-test\node_modules\sharp\build\Release
> ERR! sharp ENOENT: no such file or directory, scandir 'C:\Users\user\github\strapi-test\node_modules\sharp\vendor\lib'
> prebuild-install WARN install \\?\C:\Users\user\github\strapi-test\node_modules\sharp\build\Release\sharp.node is not a valid Win32 application.
> prebuild-install WARN install \\?\C:\Users\user\github\strapi-test\node_modules\sharp\build\Release\sharp.node
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: 14640:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677:
> gyp ERR! stack
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\user\github\strapi-test\node_modules\sharp
> gyp ERR! node -v v13.12.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN strapi-connector-bookshelf@3.1.3 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
> npm WARN bootstrap@4.5.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sharp@0.24.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sharp@0.24.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 

**Reproduction Steps**

Ran the following:

> npx create-strapi-app strapi-test

> ? Choose your installation type
> ? Choose your installation type Custom (manual settings)
> ? Choose your default database client
> ? Choose your default database client postgres
> ? Database name: (strapi-test)
> ? Database name: strapi-test
> ? Host: (127.0.0.1)
> ? Host: 127.0.0.1
> ? Port: (5432)
> ? Port: 5432
> ? Username: postgres
> ? Username: postgres
> ? Password: *****
> ? Password: *****
> ? Enable SSL connection: (y/N) n
> ? Enable SSL connection: No

**Expected behaviour**
App installations succeeds

**System**

- Node.js version: `14.7.0`
- NPM version: `6.0.0`
- Strapi version: `3.1.3`
- Database: postgres
- Operating system: Windows 10 x64

**Comment by derrickmehaffy** [comment]
Hello!

`Node.js version: 14.7.0` We do not currently support Node versions that are not LTS, v14 doesn't go LTS until October, so I would recommend you downgrade to v12.

**Comment by afilp** [comment]
I have a similar problem while I do have `nodejs v12` (through `nvm`):

```
PS D:\r> yarn create strapi-app iqz-strapi --quickstart
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-native-asset@2.0.0" has unmet peer dependency "react-native@^0.60.0".
[4/4] Building fresh packages...
[1/3] ⠂ puppeteer                                                                                                       [2/3] ⠂ ndb-node-pty-prebuilt                                                                                           warning Error running install script for optional dependency: "C:\\Users\\afil\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ndb-node-pty-prebuilt: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: C:\\Users\\afil\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ndb-node-pty-prebuilt
Output:
C:\\Users\\afil\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ndb-node-pty-prebuilt>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
```

I am not sure what I should do in Windows to make this work. I run it in Powershell, as admin.

Thanks a lot!

**Comment by derrickmehaffy** [comment]
> I have a similar problem while I do have `nodejs v12` (through `nvm`):
> 
> ```
> PS D:\r> yarn create strapi-app iqz-strapi --quickstart
> yarn create v1.22.4
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.2.4: The platform "win32" is incompatible with this module.
> info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning " > react-native-asset@2.0.0" has unmet peer dependency "react-native@^0.60.0".
> [4/4] Building fresh packages...
> [1/3] ⠂ puppeteer                                                                                                       [2/3] ⠂ ndb-node-pty-prebuilt                                                                                           warning Error running install script for optional dependency: "C:\\Users\\afil\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ndb-node-pty-prebuilt: Command failed.
> Exit code: 1
> Command: node scripts/install.js
> Arguments:
> Directory: C:\\Users\\afil\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ndb-node-pty-prebuilt
> Output:
> C:\\Users\\afil\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ndb-node-pty-prebuilt>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
> gyp info it worked if it ends with ok
> ```
> 
> I am not sure what I should do in Windows to make this work. I run it in Powershell, as admin.
> 
> Thanks a lot!

It appears you don't have python installed which is a sub-requirement of the `sharp` package

**Comment by afilp** [comment]
Thanks, 

I do have Python 2.7 installed, should I upgrade to Python 3.8?

I had to have 2.7 due to react-native and other deps, not sure if this is a requirement now though.

**Comment by afilp** [comment]
I think it is OK now, I reinstalled `windows-build-tools` and worked.

https://www.npmjs.com/package/windows-build-tools

Thanks!

**Comment by pablolucio97** [comment]
I'm with the same issue here:

```⛔️ Connection test failed: Cannot find module 'C:\Users\Usuario\AppData\Local\Temp\strapi6207f074ccc3\node_modules\strapi-connector-mongoose\lib\utils\connectivity.js'```

I ready did updated windows-build-tools, I have Python 3.9, Node 14.17.0 and this doesn't works. Only working when passing --quickstart instalation.
