### ISSUE TITLE
Set user default role

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#735]
How we can set default role for strapi user that register with `http://localhost:1337/auth/local/register`?

**Comment by lauriejim** [comment]
We plan to add it in setting pannel.

But if you want to custom it yourself, you will have to custom this action https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L211

**Comment by mnlbox** [comment]
@lauriejim I can wait for you to add it to setting panel. Is it in short term milestone?

**Comment by lauriejim** [comment]
Okay. It's will probably done in 2 or 3 weeks.

**Comment by andrescristi** [comment]
Correct me if I'm wrong, but I think he would only need to edit line 244 of
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L211, and replace guest with the role he want.

**Comment by lauriejim** [comment]
That is true !

**Comment by projectn3xt** [comment]
Hi I changed,

plugins/users-permissions/controllers/Auth.js line 273 to this  

params.role = (params.role)?params.role: role._id || role.id;

**Comment by indatawetrust** [comment]
@projectn3xt thanks
