### ISSUE TITLE
Webhook for fetch API calls

### ISSUE THREAD

**Issue by basavarajdodamani** [strapi/strapi#7352]
Hello, 
Q1: Do we have an option to send event for a fetch call on the API. As i understand webhook is at the global level. 

Q2:I also would like to know if triggering of events can be controlled as per collection type. 

Q3: I somehow cant get below implementation working mentioned in: https://strapi.io/blog/strapi-webhooks 
I think URL mentioned in the custom.js is to be invoked when there is a post call on the collection type? 

A quick response on any of theses, is highly appreciated!

**Comment by derrickmehaffy** [comment]
Hi @basavarajdodamani in this case I think it would probably be better to custom build your own webhook process based on the model lifecycles: https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

These are triggered when a `query` action happens (only the default queries are support, not custom ones), so in this case any time a service calls a `strapi.query()` action you will have two lifecycles:

- Before the query is fired
- After the query is fired

You can find more information on how to use these in the documentation I linked, but all queries are supported (the default ones)

- beforeFind/afterFind
- beforeFindOne/afterFindOne
- beforeCreate/afterCreate
- beforeUpdate/afterUpdate
- beforeDelete/afterDelete
- beforeCount/afterCount
- beforeSearch/afterSearch
- beforeCountSearch/afterCountSearch
