### ISSUE TITLE
Auto logging out and deleting all elements

### ISSUE THREAD

**Issue by VelrinBlack** [strapi/strapi#7355]
**Describe the bug**
I've just installed new strapi project. I came to admin panel, signed up, created some content types and added some elements into it. The problem is, from time to time, when I open admin panel I am logged out and have to Sign up. When I do it with the (with the same data as previous) I don't have any elements, but I have content types.

**Expected behavior**
Content is not deleting and strapi is not automatic logging me out.

**System**
- Node.js version: 14.7.0
- NPM version: 6.14.7
- Operating system: Ubuntu 20.04
- Database: SQLite
- Strapi version: 3.1.3

Am I doing something wrong or it is strapi bug?

**Comment by derrickmehaffy** [comment]
Can you please edit your issue to follow our template? It gives us vital information to reproduce your issue.

Also are you using Heroku, and if so did you use `--quickstart` when you created the project. Please see the following FAQ: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

**Comment by VelrinBlack** [comment]
> Can you please edit your issue to follow our template? It gives us vital information to reproduce your issue.
> 
> Also are you using Heroku, and if so did you use `--quickstart` when you created the project. Please see the following FAQ: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

Thank you very much @derrickmehaffy 
I read what you sent me and decided to use MongoDB instead of SQLite. But there is a problem with deploying it. In strapi docs, there is talking about these paths: `./config/env/development/database.js`, `./config/env/development/database.js` to set up database config. But the problem is, in current version of strapi, there's not `env` directory in `config` so I think the documentation is not up to date.
Does anyone know, how can I set database settings?

**Comment by derrickmehaffy** [comment]
Hello.

They are not created by default, you create them yourself if you need them.

**Comment by VelrinBlack** [comment]
@derrickmehaffy 
Ok, so I created them and it is still not working.

----
My file structure:

![Screenshot from 2020-08-07 15-54-33](https://user-images.githubusercontent.com/57812209/89653031-b335e780-d8c6-11ea-9d4d-d924106d35f1.png)


---
`env/development/database.js`
```
module.exports = ({ env }) => ({
    defaultConnection: 'default',
    connections: {
      default: {
        connector: 'mongoose',
        settings: {
          host: env('DATABASE_HOST'),
          port: env.int('DATABASE_PORT'),
          database: env('DATABASE_NAME'),
          username: env('DATABASE_USERNAME'),
          password: env('DATABASE_PASSWORD'),
        },
        options: {},
      },
    },
  });
```
---
`env/production/database.js`
```
module.exports = ({ env }) => ({
    defaultConnection: 'default',
    connections: {
      default: {
        connector: 'mongoose',
        settings: {
          uri: env('DATABASE_URI'),
        },
        options: {
          ssl: true,
        },
      },
    },
  });
```
---
`env/database.js`
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        uri: env('DATABASE_URI'),
      },
      options: {
        ssl: true,
      },
    },
  },
});
```
---

I ran:
`git add .`
`git commit -m "Database Setup"`
`git push heroku master`


And when I open application, I see this:

![Screenshot from 2020-08-07 16-03-09](https://user-images.githubusercontent.com/57812209/89653557-8930f500-d8c7-11ea-82fe-73317201be93.png)


**_Do you have any idea?
Thanks in advance_**

**Comment by derrickmehaffy** [comment]
There could be a problem with the URI you are using for the production, or your Atlas database may not have the correct security settings.

**Comment by VelrinBlack** [comment]
@derrickmehaffy 
Thanks very much! Thanks to you I figured out, that I have to use URI for older version of node in order to connect to strapi.
Huge thanks one more time!
