### ISSUE TITLE
Unable to authenticate user with Google API

### ISSUE THREAD

**Issue by fellz** [strapi/strapi#7358]
Hi
I follow this guide to add Google provider for authentication. 
[https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers](https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers)

**Describe the bug**
Got Authorization Error from google. Error 400: invalid_request.
Invalid parameter value for redirect_uri: Missing scheme: /connect/google/callback.

**Steps to reproduce the behavior**
I added **https://api.mydomain.com/connect/google/callback** to Google "Authorized redirect URIs".
Added **https://mydomain.com/connect/google** as callback page on the site.
Then i call "api.mydomain.com/connect/google" to authorize on Google and get authentication window.

**Expected behavior**
Should see Google authentication window without errors. 

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.0.6
- Database: sqlite
- Operating system: ubuntu 18.04

**Additional context**

**Comment by derrickmehaffy** [comment]
Hello, in this case you need to set the `url` key within `./config/server.js` to tell the auth provider and your frontend what the public accessable URL is to contact Strapi.

So in your case that URL key should be `https://api.mydomain.com`

After you set this, you do need to rebuild the admin panel

**Comment by fellz** [comment]
> Hello, in this case you need to set the `url` key within `./config/server.js` to tell the auth provider and your frontend what the public accessable URL is to contact Strapi.
> 
> So in your case that URL key should be `https://api.mydomain.com`
> 
> After you set this, you do need to rebuild the admin panel

thanks,  i got correct Authentication page **but**  i got redirects to this page again and again if i choose account to authenticate. Something need to be added or fixed.

**Comment by derrickmehaffy** [comment]
There was a recently merged PR that will address some of the confusion within the docs an our examples here: https://github.com/strapi/strapi/pull/7132

There was also some code changes that should fix some common issues that will be released in v3.1.4

**Comment by fellz** [comment]
ok thanks will check 3.1.4 version for fix.
