### ISSUE TITLE
Permissions disappear

### ISSUE THREAD

**Issue by wi4er** [strapi/strapi#736]
**Node.js version**: 9.6.1

**npm version**: 5.7.1

**Strapi version**: 3.0.0

**Operating system**: Ubuntu 16.04

**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Sometimes I have loosing records from users-permissions_permission table.
normally there suppose to be 150 records, but I loosing 12 records.
After restarting strapi everything fixed, but I suppose to reenter some permissions. 

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Just working with project and sometimes after serverside errors its happens.

**What is the expected behavior?**

**Comment by lauriejim** [comment]
Hi @wi4er strange issue .... if it happen randomly it will be hard to reproduce and fix ..

**Comment by wi4er** [comment]
I happens with custom controller, with routes.json like 
{
  "routes": [
    {
      "method": "GET",
      "path": "/",
      "handler": "Index.find",
      "config": {
        "policies": []
      }
    }
]
}

**Comment by wi4er** [comment]
I try in alpha 11.1, problem slill there.

**Comment by lauriejim** [comment]
Okay but we have to definitively find a way to reproduce this weird thing !!

**Comment by keyus4** [comment]
I am also having the same issue. User permission disappears and doesn't save even when i re-add the permissions. so frustrating

**Comment by sorob** [comment]
This happens when you do npm install. I think the roles and permission plugin re-inserts its 200 something records to mongo every time without checking if they already exist.

**Comment by Aurelsicoko** [comment]
@sorob To make sure I understand it correctly, you run `npm install <dependency>` in your project, then you start the server and some permissions disappear?

**Comment by Aurelsicoko** [comment]
I also tried to run `npm install` at the root of the project with the `node_modules` already existing or not. It works fine as well. It's driving me crazy... 🤯

**Comment by Aurelsicoko** [comment]
I've some news about this issue. I've fixed another one #977 and the [PR](https://github.com/strapi/strapi/pull/1103) could also solve this one.
