### ISSUE TITLE
Field missing in API response for components in related content type

### ISSUE THREAD

**Issue by MatthewSbar** [strapi/strapi#7360]
**Describe the bug**
The bug is described here https://github.com/strapi/strapi/discussions/5769, but that issue was converted to a discussion despite it being a bug which has not been fixed.

Essentially, when getting data for a content type which has a relation to another content type, fields for components in the related content type are not returned in the API response. Fields which aren't nested in components are included.

**Steps to reproduce the behavior**

1. Create a content type called Slide
2. Add a component to Slide called images
3. Add a field named imageUrl to the images component
4. Create two slides with different images
5. Create a content type called Landing Page
6. Add a repeatable component called slideshow to Landing Page
7. Add a one-to-one relation to Slides in the slideshow component
8. Create a landing page
9. Add both slides to the landing page
10. Navigate to /landing-pages to fetch the data for landing pages
11. In the response, the slides are included, but the images component is not included

**Expected behavior**
In step 11, the images field would be included.

**System**

Node.js version: 12.14.1
NPM version: 6.13.4
Strapi version: Strapi v3.0.0
Database: Postgres
Operating system: ubuntu 18.04.04 lts

**Comment by derrickmehaffy** [comment]
I can confirm this, I've included a test project: 
[test7360.zip](https://github.com/strapi/strapi/files/5037644/test7360.zip)

**Comment by rowdyrabouw** [comment]
The same happens in your example of creating a menu (https://www.youtube.com/watch?v=cvL204xus1w). You don’t get the dropdown items returned (label + link), only a reference to the dropdown. The dropdown is a component.

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/7454

**Comment by pkogler-tgm** [comment]
And how exaclty can you fix this right know.
Is there any way i can come around this.
[https://www.youtube.com/watch?v=VBNjCgUokLk&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=17&t=0s](url)
this video shows how to extend populate behaviour of a content type.

How would you achieve this in a component with a relation?

**Comment by derrickmehaffy** [comment]
@pkogler-tgm we don't currently have a fix at the moment

**Comment by Stun3R** [comment]
I had the same problem just after migrating from v3.0.2 to v3.2.4. I tried to downgrade to 3.1.7 and finally it worked to populate with component !

**Comment by a1tem** [comment]
Hi guys is there any solution? I have faced the same issue with components in the hasOne relation. We do need to populate the component data, in order to avoid making a new query.

**Comment by MatthewSbar** [comment]
@a1tem There are three ways out of this if you want to keep using Strapi

1. Find the bug in the source code and fix it.
2. Because this bug only applies to components, you can either
A. "flatten" all your components. Instead of using components, create new fields that have the same fields that the component would've, and update whatever is consuming the data to expect it in the different format - if you do this, you'll have to re-populate all those fields for whatever content already exists, so depending on how much content you have available, this isn't a good solution. It's also not a good solution, because, components are the only way to include a list, so if you need a list in any content type that is a child, you can:
B. Use the ID to re-request the individual piece of content again with a separate request, or request all the content of that type and stitch the missing data back in. Both are not scalable solutions in many scenarios.

**Comment by DavoMyan** [comment]
Alright so I started getting this problem couple days ago too and @MattieBelt managed to find a solution for me on Slack, it is a workaround and I will post a couple other solutions here at the bottom of this post, but first I'll explain the problem I had.

(Also, I think I found the culprit for why this bug started happening)

I have 1 content type called Character with a component inside of it.
My user has a component with inside of it 1 boolean and 1 relation pointing to Character, as I said this Character has 1 component with additional stuff inside, doesn't matter what.
When Getting the User through logging in or users/me, the response JSON does not include the component that is inside the Character of my user.

The workaround to this is to just loop through the characters and manually add them upon requesting users/me:

In `extensions/users-permissions/controllers/User.js`
```js
'use strict';

/**
 * User.js controller
 *
 * @description: A set of functions called "actions" for managing `User`.
 */

const { sanitizeEntity } = require('strapi-utils');

const sanitizeUser = user =>
    sanitizeEntity(user, {
        model: strapi.query('user', 'users-permissions').model,
    });

module.exports = {

    /**
     * Retrieve authenticated user.
     * @return {Object|Array}
    */

    async me(ctx) {
        const user = ctx.state.user;
        if (!user) {
            return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
        }
        //User -> Repeatable component called character -> relation with content type character -> character has 1 component called Skill1
        //Component inside character does not show up when getting the User.

        //temporary solution
        for (let i = 0; i < user.character.length; i++) {
            user.character[i].character = await strapi.services.character.findOne({ id: user.character[i].character.id });
        }
        ctx.body = sanitizeUser(user);
    },
};
```

There is a catch to this ^ though and I think that is also the root of this bug; the content type with the component you wish to populate (Characters) must be published. You don't need to use this workaround if you revert to an older version of Strapi, because that just works normally, the Draft and Publish system starting from v3.2 is the culprit I think, that's why @Stun3R got it working by reverting to an older version of Strapi.
(disabling the draft/publish feature also doesn't work, you still have to use the workaround here above^)

2nd solution: Just use a JSON field, components are pretty much JSON's but with a fancy UI for the admin panel (But I love the fanciness so I can't let it go)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/a-repeatable-component-inside-a-relation-in-a-component-doesnt-return-anything-in-the-user/1978/7

**Comment by a1tem** [comment]
Hi @DavoMyan.
This solution is good, but it creates additional queries to the database.
`
for (let i = 0; i < user.character.length; i++) {
            user.character[i].character = await strapi.services.character.findOne({ id: user.character[i].character.id });
        }
`
I have solved this by creating 1 query before the loop 
`
await strapi.services.character.find
`

and then inside of the loop I just use array.find(item => item.id === user.character[i].character.id)

**Comment by DavoMyan** [comment]
> Hi @DavoMyan.
> This solution is good, but it creates additional queries to the database.
> `
> for (let i = 0; i < user.character.length; i++) {
>             user.character[i].character = await strapi.services.character.findOne({ id: user.character[i].character.id });
>         }
> `
> I have solved this by creating 1 query before the loop 
> `
> await strapi.services.character.find
> `
> 
> and then inside of the loop I just use array.find(item => item.id === user.character[i].character.id)

Yes that is indeed more performant, I actually had that answer but I forgot to include that in my version

**Comment by MOHAMMADHMEAD** [comment]
Last week  when trying to handle the same issue populate case, I'm use mh-populate it's populated array in few seconds
You can find more details on npm package 

npm: https://www.npmjs.com/package/mh-populate

you can populate more than 1700 items in few seconds

**Comment by derrickmehaffy** [comment]
> Do you know if there is any fix planned for this @derrickmehaffy? We need to use custom components inside repeatable relations extensively to interlink different pages on our website.

Most likely not in v3

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/nested-data-in-a-component/12575/2

**Comment by krzysiekHero** [comment]
Apart from the components, the both field is not shown in the API

**Comment by derrickmehaffy** [comment]
No longer an issue in v4 as nothing is populated by default and you can control population at request time

**Comment by VinaySarilla** [comment]
I am using v4 and still encountered the bug where I am not able to see relational fields in my response.

**Comment by derrickmehaffy** [comment]
> I am using v4 and still encountered the bug where I am not able to see relational fields in my response.

This is intended in v4, see our documentation on population: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#component-dynamic-zones

**Comment by derrickmehaffy** [comment]
I'm locking these, if you still have questions. Read the docs and hop in our community platforms. They are listed on the main readme.
