### ISSUE TITLE
Manage external GraphQL API

### ISSUE THREAD

**Issue by sedubois** [strapi/strapi#737]
**Do you want to request a *feature* or report a *bug*?**
Feature

Sorry for the newbie question but does Strapi allow, or plan to allow managing one's own GraphQL API? I have generated an API with Graphcool Prisma (with their new beta service Prisma Cloud) and am now looking for a solution to manage the content exposed by this API. Thanks 🙏

**Comment by lauriejim** [comment]
Hi @sedubois Yes we plan to have graphql support.
Please upvote this feature on https://strapi.io/vote
