### ISSUE TITLE
Gatsby & Strapi(deployed on Heroku): Request failed with status code 400

### ISSUE THREAD

**Issue by girafffene** [strapi/strapi#7377]
**Describe the bug**
After deploying my project's Strapi server to Heroku I went to log into my Strapi admin page as prompted, however, when I entered my credentials it returned "An internal server error occurred".

![Screen Shot 2020-08-07 at 2 00 10 PM](https://user-images.githubusercontent.com/59903380/89688668-86c69f00-d8b7-11ea-8a2b-668acc16a581.png)

At first I thought my credentials were wrong, so i went to "forgot password". The link that was emailed to me did not work. 

![Screen Shot 2020-08-07 at 1 57 09 PM](https://user-images.githubusercontent.com/59903380/89688658-83331800-d8b7-11ea-82a7-58d155dc29e1.png)

After that, I ran "gatsby build" to see what errors would populate and it kicked back "ERROR #11321: gatsby-source-strapi: Request failed with status code 400"

<img width="633" alt="Screen Shot 2020-08-07 at 1 59 27 PM" src="https://user-images.githubusercontent.com/59903380/89688663-84fcdb80-d8b7-11ea-9b7d-1eb7adb58710.png">

**Expected behavior**
Be able to log into strapi server admin. 

**Code snippets**

* Strapi: "./config/database.js"
```javascript
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
      },
      options: {
        ssl: false,
      },
    },
  },
});
```

* Gatsby: "./gatsby-config.js"
```javascript
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `https://prime-trust-v3.herokuapp.com/`,
        queryLimit: 1000, 
        contentTypes: [`client-logos`, `teams`, `solutions`, `logos`, `articles`],
      },
    },
```

**System**

- Node.js version:  v14.7.0
- NPM version: 6.14.7
- Strapi version:  3.1.0-alpha.5
- Database: postgresql
- Operating system: Catalina 10.15.6

**Comment by derrickmehaffy** [comment]
`3.1.0-alpha.5` Can you please update to the latest v3.1.x release (v3.1.3 as of writing) and also can you provide your `./config/server.js`

**Comment by lauriejim** [comment]
And you will find here video resources:
https://www.youtube.com/watch?v=HHnRsZwFmR8&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=21&t=0s
https://www.youtube.com/watch?v=Qd-xpaT0c48&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=26&t=0s

And here the documentation to deploy your app on Heroku:
https://strapi.io/documentation/v3.x/deployment/heroku.html

All these resources should help you.
