### ISSUE TITLE
Relation not created after collection update

### ISSUE THREAD

**Issue by JustBeYou** [strapi/strapi#7384]
**Describe the bug**
I created a `user-profile` collection type and I am trying to add a one-to-one relation between it and `user` (from `user-permissions`). The logic is that when a new user is registered, a `user-profile` object will be created and linked with the user. I used `strapi.query(...).update(...)` inside the `afterCreate` hook of `user`, but it seems that the update has no effect, the relation stays empty.

As a double-check, I did the same update on the `role` field and it seems to work and that's pretty confusing. 

**Steps to reproduce the behavior**

1. Create a new clean Strapi project
2. Go to the Admin panel and create a collection, name it as you want (I will use `test` for my example) and add a field
3. Create a one-to-one relation between the `test` collection and `user`
4. Add the following code to `extensions/users-permissions/models/User.js`:
```
module.exports = {
    lifecycles: {
        async afterCreate(result, data) {
            // create the test object
            const test = await strapi.query('test').create({
                title: 'this is a test title',
            });
            
            // update the just registerd user
            await strapi.query('user', 'users-permissions').update({
                id: result.id,
            }, {
                role:{id:2}, // hardcoded relation update on roles (it works)
                test:{id:test.id}, // relation update with the newly created object (it does not work)
            });

            // print the registered user and see that the update did not work, but you can also look in the admin panel
            const updated = await strapi.query('user', 'users-permissions').findOne({id: result.id});
            console.log(result);
            console.log(updated);
        }
    }
}
```
5. Start the server and send the following JSON request using some tool like Postman to `http://localhost:1337/auth/local/register`:
```
{
    "username": "testuser",
    "email": "testuser@gmail.com",
    "password": "qwerty123456"
}
```

6. Sample output:
```
{
  id: 12,
  username: 'testuser',
  email: 'testuser@gmail.com',
  ... other fields ...
  role: { <- id = 1 (the default value)
    id: 1,
    name: 'Authenticated',
    description: 'Default role given to authenticated user.',
    type: 'authenticated',
    created_by: null,
    updated_by: null
  },
  test: null, <- null before update
  ... ... ...
}
{
  id: 12,
  username: 'testuser',
  email: 'testuser@gmail.com',
  ... ... ...
  role: {
    id: 2, <- the update worked
    name: 'Public',
    description: 'Default role given to unauthenticated user.',
    type: 'public',
    created_by: null,
    updated_by: null
  },
  test: {}, <- empty object after update
  ... ... ...
}
```

**Expected behavior**
The relation reference should not be empty.

**System**

- Node.js version: tested on v14.7.0 and v12.18.3
- NPM version: 6.14.7 and 6.14.6
- Strapi version: 3.1.3
- Database: default
- Operating system: Linux fedora

**Comment by juandl** [comment]
Question, why are u sending `test:{id:test.id}` that is an object, for make a relationship should be a string type ID, also I'm not sure why "role:{id:2}" works, shouldn’t work too 🤔

**Comment by JustBeYou** [comment]
@juandl it's the default db, Sqlite I think. 
Also, could you give a concrete example of how a relation should be made? I couldn't find anything specific in the docs, that's why I tried the above thing.

**Comment by juandl** [comment]
@JustBeYou Well normally I made the relations with the "id"

Like

`test:"5ef2613ff7e26b4329cc000a"`

**Comment by JustBeYou** [comment]
@juandl well, thank you. 
I see that there is an example in the docs here https://strapi.io/documentation/v3.x/concepts/queries.html#api-reference in the `create` tab. I did not see it as it is at the bottom and not indexed by the search. Maybe it will be a good thing to state it explicitly somewhere, I could do a PR if you find it reasonable enough too.

**Comment by juandl** [comment]
Hi @JustBeYou, I hope everything works now well, about your request making explicit the instructions of relations, i think is already clear, we just need t read careful 😅.
