### ISSUE TITLE
`strapi new` fail

### ISSUE THREAD

**Issue by storm1er** [strapi/strapi#739]
**Node.js version**: v8.9.4
**npm version**: 5.6.0
**Strapi version**: on master eab59ad3 (most recent)
**Operating system**: Ubuntu 17.10

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/9821946/36969106-d59699c2-2064-11e8-93d9-f9a29c617b55.png)

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Simply install strapi `npm run setup` from main repo, then create an api through `strapi new my-project`

**What is the expected behavior?**
Api creation without error.

**Comment by derrickmehaffy** [comment]
@storm1er I believe Node 9 is required, based on the changes to the documentation: https://strapi.io/documentation/getting-started/installation.html

I believe this was changed for alpha-3.00-v10.1 or 10.2 so I would imagine the latest master build also requires it.

**Comment by storm1er** [comment]
Oops, my bad, it works now. Thanks :+1:
