### ISSUE TITLE
Referenced Content type columns to be show

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#7398]
**db: mongo
strapi: 3.1.0
os:linux
node:12**

Hello as per my knowledge, strapi admin's content type listing comes with only fileds which are added while creating content type.But what if i want to show some additional columns in listing? I have on content type bids where i have added a realtion with another content type "Property". So currenlty on "Bids" content type listing, i am able to see only bids's fileds, but "property id" is stored in bids collection. So i want to show some details like property name on bids content type listing.

![Bids](https://user-images.githubusercontent.com/47749809/89772792-474ebb80-db20-11ea-8166-b9675f10238d.png)
![property](https://user-images.githubusercontent.com/47749809/89772789-461d8e80-db20-11ea-8330-ac5c3520d6e3.png)

**Comment by derrickmehaffy** [comment]
Hello, please see the following RFCs:

https://github.com/strapi/rfcs/issues/8
https://github.com/strapi/rfcs/issues/7

Currently this feature is not available, and work hasn't been started on it yet. We are actually looking for an outside contributor while we work on other higher priorities or until we get some time to work on it.
