### ISSUE TITLE
Documentation plugin will always write to full_documentation.json

### ISSUE THREAD

**Issue by gh0stsh0t** [strapi/strapi#7399]
**Describe the bug**
Every time strapi-plugin-documentation/config/functions/bootstrap.js runs, it will write to full_documentation.json even if no update is created.

**Steps to reproduce the behavior**

1. create a new project with users-permissions and documentation plugin installed 
2. start the server 
3. it should edit full_documentation.json but only changing the`x-generation-date` info

**Expected behavior**
If no update has been made, it should not write to the file

**Screenshots**

![image](https://user-images.githubusercontent.com/20282317/89776024-a110af00-db3b-11ea-81d2-dc29ac5a0109.png)
![image](https://user-images.githubusercontent.com/20282317/89776120-d3baa780-db3b-11ea-8f24-1de12a8b810d.png)

**Code snippets**
when bootstrap.js runs, it will almost always enter this condition
```js
// strapi-plugin-documentation/config/functions/bootstrap.js: line 101
if (!isMergedDocumentationExists || shouldUpdateFullDoc) {
    // Create the folder
    services.createDocumentationDirectory(documentationPath);
    // Write the file
    fs.writeFileSync(
      path.resolve(documentationPath, 'full_documentation.json'),
      JSON.stringify(fullDoc, null, 2),
      'utf8'
    );
}
```

as caused by checkIfPluginDocNeedsUpdate returning true when checking the "users-permissions" plugin, as it has 2 tags: UsersPermissions - User and UsersPermissions - Role
```js
// strapi-plugin-documentation/config/functions/bootstrap.js: line 38
const needToUpdatePluginDoc = services.checkIfPluginDocNeedsUpdate(plugin);
```

this happens because createDocObject() uses _.merge() which doesnt work if there is a property that contains an array, as it will override the array. Thus only one tag can appear in the object. To fix that the function should be changed to mergeWith that has a customizer for array values
```js
// strapi-plugin-documentation/services/Documentation.js
// from
createDocObject: array => {
    return array.reduce((acc, curr) => _.merge(acc, curr), {});
},

// to 
createDocObject: array => {
    function forArray(objValue, srcValue) {
      if (_.isArray(objValue)) {
        return objValue.concat(srcValue);
      }
    }
    return array.reduce((acc, curr) => _.mergeWith(acc, curr,forArray), {});
},
```

however this raises another error in the `areObjectsEquals()` function as it simply does `return JSON.stringify(obj1) === JSON.stringify(obj2);` to check for equality and will fail if the arrays don't have the exact same order

**System**
- Docker image: strapi/strapi:3.1.3
- Node.js version: v12
- NPM version:
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Linux

**Comment by lauriejim** [comment]
Thank you for reporting it. Really happy to see you created a PR to fix that.
We will review it as soon as possible.
Have a good day.

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/google-app-engine-readonly-vs-plugin-api-documentation-generation/468/2

**Comment by thiboot** [comment]
As Google App Engine is a readOnly filesystem. The generation of the API documentation at launch block the entire strapi app. => Could not use documentation plugin with Google App Engine...

**Comment by MattieBelt** [comment]
Maybe by disabling the file write on staging and prod this could resolve the no write permissions problem. Instead of writing it could give an warning in the console, that the docs need to be regenerated (locally). This will also not result is a failing start if you intentionally don't want to regenerate the docs.

**Comment by talazenkot** [comment]
Any news regarding this? it's a blocker :(

**Comment by derrickmehaffy** [comment]
No updates, if anyone has fixes, please feel free to submit a PR

**Comment by gh0stsh0t** [comment]
@derrickmehaffy #7420 requesting a review

**Comment by derrickmehaffy** [comment]
Thanks @gh0stsh0t we are fairly far behind on PR reviews, lots of people on Holidays

**Comment by shoryavj** [comment]
Any update on the bug?

**Comment by derrickmehaffy** [comment]
@shoryavj a fix was merged a month ago and already released.
