### ISSUE TITLE
Email confirmation doesn't work with nodemailer

### ISSUE THREAD

**Issue by fellz** [strapi/strapi#7412]
**Describe the bug**
I don't recieve any confirmation emails when user is created. 

**Steps to reproduce the behavior**
I follow this guide [https://strapi.io/documentation/v3.x/plugins/email.html](https://strapi.io/documentation/v3.x/plugins/email.html)
I installed this email plugin [https://www.npmjs.com/package/strapi-provider-email-nodemailer-v3](https://www.npmjs.com/package/strapi-provider-email-nodemailer-v3).
Then i turned **on** Enable email confirmation and i got no emails. 

**Expected behavior**
I should receive confirmation email.

**System**
- NPM version: 6.14.6
- Node.js version: 12.16.1 
- Strapi version:  1.3.06
- Database: sqlite
- Operating system: ubuntu/window

**Additional context**
I tested nodemailer with this function `strapi.plugins['email'].services.email.send()` in custom controller it worked perfectly. So plugin works and i guess it's something with strapi and registration controller/action.

**Comment by derrickmehaffy** [comment]
Hello @fellz we actually didn't create, nor manage that provider as it comes from: https://github.com/Saunved/strapi-provider-email-nodemailer. This is likely an issue you will need to talk to the provider maintainer about.

**Comment by fellz** [comment]
> Hello @fellz we actually didn't create, nor manage that provider as it comes from: https://github.com/Saunved/strapi-provider-email-nodemailer. This is likely an issue you will need to talk to the provider maintainer about.

Provider works fine, strapi not sending emails.

**Comment by derrickmehaffy** [comment]
@fellz I tested the package locally on Windows, Linux, and Mac and was not able to reproduce this. Do you have any other information that may help reproduce the issue?

**Comment by fellz** [comment]
Ok how i tested.

1. Installed plugin **nodemailer-v3**

1. Added 
```
 {
      "method": "GET",
      "path": "/hello",
      "handler": "hello.index"
    },
```
to the routes

2. Added handler

```
module.exports = {
  index: async (ctx)=>{
    const result = await strapi.plugins['email'].services.email.send({
      to: 'someemail@gmail.com',
      from: 'info@mysite.com',
      replyTo: 'info@mysite.com',
      subject: 'Confirmation email',
      html: '<h4>Welcome to our site !</h4>',
    });
    ctx.send(result)
  }
};
```
got result in my to inbox ( someemail@gmail.com) and in system messages "response: "250 2.0.0 Ok:"

3. Added Email confirmation **On** in Admin panel. 
Result -> I didn't recive any emails after registration. I used the same email `someemail@gmail.com` i used in test.

**Comment by derrickmehaffy** [comment]
Thank you @fellz I will try and test this again today, Just for reference so I can try to build an environment as close to yours as possible. Are you working on a hosted server/locally and what type of SMTP email server are you using?

**Comment by fellz** [comment]
> Thank you @fellz I will try and test this again today, Just for reference so I can try to build an environment as close to yours as possible. Are you working on a hosted server/locally and what type of SMTP email server are you using?

I try to send from local machine. I use smtp.yandex.ru and 25 port and then provide username ( wich is email that i registered at yandex.ru) and password. I guess gmail.com also will work.

**Comment by fellz** [comment]
So any thoughts ? @derrickmehaffy @alexandrebodin ?

**Comment by lauriejim** [comment]
Hello! Can you please check your Strapi version `1.3.06` is not matching the current version of Strapi witch is `3.1.3`.
Then I just tried the email confirmation feature and it works fine.
Here is what I did : https://www.loom.com/share/5b7bca29b0164141ab2193244408c2a8
I used another provider to make sure "the feature" works. So your issue can come from the provider (which is not managed by us, the strapi team)
So please contact the owner of this provider.

**Comment by fellz** [comment]
Solution! I was using wrong url to register users `/users`. Correct url is `auth/local/register`.  It's strange that there are two ways to register a user.

**Comment by lauriejim** [comment]
One it to `create` a user, the other is to `register` a user.
It's not the same action.
