### ISSUE TITLE
Error: Blocked by CORS when connect by google provider from Nextjs web app.

### ISSUE THREAD

**Issue by VInhHuong** [strapi/strapi#7415]
Hello everyone, sorry for my bad English.
I am trying to login by google auth from my nextjs blog, when I open "https://strapiDomain/connect/google" in my browers it's wroking, but when I call from nextjs app I catch error "Access to fetch at 'https://accounts.google.com/o/oauth2/auth?client_id=clientId&response_type=code&redirect_uri=redirectToStrapiCallback&scope=email' (redirected from 'https://strapiDomain/connect/google') from origin 'https://my_blog.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
Please help me! Thask you for support.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

Second thing, please check existing issues and discussions related to CORS, you will probably find the solution to your problem.
