### ISSUE TITLE
Provide npx installation docs rather than npm

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#742]
I think `npx` is very awesome now and tools like **Strapi** can use it's power. So maybe `npx` installation and usage guide is more better than npm. :wink:

**Comment by mnlbox** [comment]
@lauriejim I suggest this because now strapi is working heavy on new release and with npx I need less strapi package update manually.

**Comment by soupette** [comment]
@mnlbox `npx -p strapi@alpha strapi new my-app && strapi start` should work. Maybe we need to update the doc

**Comment by mnlbox** [comment]
@soupette Any news about update documentation??
What is Strapi next step after "bulk action"?
I check https://strapi.io/vote and It seems next step are:
* Admin - Permissions 
* Real-time 
* Documentation 
Right?

**Comment by lauriejim** [comment]
Hi @mnlbox !
Priority low about this issue. It's not a priority for us. We will not work on it for next months.

Next steps for us will be to work on JSON fields and GraphQL improvements.

**Comment by mnlbox** [comment]
JSON fields is good. @lauriejim So please publish new blog post about next months roadmap. Thanks :+1:

**Comment by lauriejim** [comment]
@Aurelsicoko is already writing it 😄

**Comment by lauriejim** [comment]
@mnlbox the roadmap article has been published.
And feel free to add it in the documentation. Easy contribution to do.

**Comment by lauriejim** [comment]
Hello @mnlbox, we can close this issue.
Feel free to submit a PR if you think it's important for the community to have this information now.
