### ISSUE TITLE
Collections relationship sub component field for view selection

### ISSUE THREAD

**Issue by robinComa** [strapi/strapi#7435]
**Steps to reproduce the behavior**

1. Create component Seo a title field as string
2. Create OfferGroup collection with a seo Seo field
3. Create Offer collection with a offer group relationship 1-*
4. Manage form view of Offer collection
5. Select the OfferGroup field seo.title when you want to attach an OfferGroup to an Offer => not possible

**Expected behavior**
Sub componant field should be selected on the form view

**Screenshots**
![image](https://user-images.githubusercontent.com/2729768/89995193-7b91bb80-dc89-11ea-902f-1546fad552f3.png)
![image](https://user-images.githubusercontent.com/2729768/89995348-a2e88880-dc89-11ea-952e-af9b9406cde4.png)
![image](https://user-images.githubusercontent.com/2729768/89995514-db886200-dc89-11ea-8a76-d5a755747a29.png)
![image](https://user-images.githubusercontent.com/2729768/89995436-bdbafd00-dc89-11ea-91b6-9df9ab2e227f.png)

**Code snippets**
n/a

**System**

- Node.js version: 12.4.0
- NPM version: 6.14.4
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Mac OS

**Additional context**
n/a

**Comment by lauriejim** [comment]
Hello! Can you please provide an application with your data structure, it will be easier to debug.
Thank you.

**Comment by robinComa** [comment]
Hello, sure !

### Offer collection

```json
{
  "kind": "collectionType",
  "collectionName": "offers",
  "info": {
    "name": "Offer"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "seo": {
      "type": "component",
      "repeatable": false,
      "component": "seo.open-graph-basic",
      "required": true
    },
    "content": {
      "type": "richtext",
      "required": true
    },
    "duration": {
      "type": "string",
      "required": true
    },
    "budget": {
      "type": "string",
      "required": true
    },
    "team": {
      "type": "string",
      "required": true
    },
    "offer_group": {
      "model": "offer-group",
      "via": "offers"
    },
    "slug": {
      "type": "uid",
      "required": true
    }
  }
}

```

### Offer group collection

```json
{
  "kind": "collectionType",
  "collectionName": "offer_groups",
  "info": {
    "name": "OfferGroup"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "seo": {
      "type": "component",
      "repeatable": false,
      "required": true,
      "component": "seo.open-graph-basic"
    },
    "offers": {
      "via": "offer_group",
      "collection": "offer"
    }
  }
}
```

### SEO component

```json
{
  "collectionName": "components_seo_open_graph_basics",
  "info": {
    "name": "Open Graph Basic",
    "icon": "address-card"
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "maxLength": 60,
      "minLength": 3
    },
    "description": {
      "type": "string",
      "required": true,
      "maxLength": 200,
      "minLength": 40
    },
    "image": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images"
      ],
      "plugin": "upload",
      "required": true
    },
    "icons": {
      "collection": "file",
      "via": "related",
      "allowedTypes": [
        "images"
      ],
      "plugin": "upload",
      "required": false
    },
    "profile": {
      "model": "profile"
    }
  }
}

```

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
