### ISSUE TITLE
Knex version does not match bookshelf

### ISSUE THREAD

**Issue by heri16** [strapi/strapi#7437]
https://github.com/strapi/strapi/blob/8d0c6848ba421680570e974e5d8606314735de3e/packages/strapi-generate-new/lib/utils/db-client-dependencies.js#L19

https://github.com/strapi/strapi/blob/97922f99ae858e1e3f4f792bb8d6a829adb82649/packages/strapi-connector-bookshelf/package.json#L29

**Comment by derrickmehaffy** [comment]
@heri16 can you make a pull request for this?

**Comment by XuluWarrior** [comment]
@derrickmehaffy 
I created a PR for this (#7479) as it was bothering me too ;)

**Comment by derrickmehaffy** [comment]
No longer a problem as we removed bookshelf
