### ISSUE TITLE
Rename the users-permissions tables to conform the GraphQL and SQL naming standard. 

### ISSUE THREAD

**Issue by EAdeveloper** [strapi/strapi#7446]
<!--
Hello 👋 Strapi  team,
 
Please rename the following tables to conform the GraphQL and SQL naming standard.

1. **users-permissions_permission** should be rename to **users_permissions_permission**
2. **users-permissions_role** should be rename to **users_permissions_role**
2. **users-permissions_user** should be rename to **users_permissions_user**

![image](https://user-images.githubusercontent.com/21114220/90042137-4345a980-dc98-11ea-85de-ada80bbded65.png)

![image](https://user-images.githubusercontent.com/21114220/90042781-21005b80-dc99-11ea-8857-f28072b99369.png)

`{
  "kind": "collectionType",
  "collectionName": "users_permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
}`

**Comment by alexandrebodin** [comment]
Hello This issue does not follow the issue templates and cannot be triaged. Please update the issue description so we reopen it

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by EAdeveloper** [comment]
> w the issue templates and cannot be triaged. Please update the issue description so w

Where are the issue templates ?

**Comment by derrickmehaffy** [comment]
When you create a new issue the template is added automatically or you can use this link: https://github.com/strapi/strapi/issues/new?template=BUG_REPORT.md
