### ISSUE TITLE
Wrong route redirection when 'Configure the view' button is pressed

### ISSUE THREAD

**Issue by umutbozdag** [strapi/strapi#7448]
**Describe the bug**
When i click 'Configure the view' button it redirects me to the wrong collection type view settings. But when i change the url manually i can view the desired page

You can see more in here:

![screen-capture-_6_ (1)](https://user-images.githubusercontent.com/43722871/90065366-d90f2200-dcf4-11ea-9327-bdb7c651a831.gif)
**Expected behavior**
Seeing the desired content type view settings

**System**
- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.1.3
- Database: mongodb
- Operating system: windows 10

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI related to the other bug or is this already fixed just pending 3.1.4 release?

**Comment by MakeBasic** [comment]
have the same problem

**Comment by HichamELBSI** [comment]
@umutbozdag @derrickmehaffy This one is already fixed for the 3.1.4

**Comment by derrickmehaffy** [comment]
Since v3.1.4 was released today, going to mark this as closed. Thank you @HichamELBSI
