### ISSUE TITLE
s3 upload 

### ISSUE THREAD

**Issue by eibrahim** [strapi/strapi#745]
I see a PR https://github.com/strapi/strapi/pull/684 for S3 but there is no documentation on how to use it..

I basically want to add an "image" field to my content type and have that be an image hosted in S3.  I want to be able to upload and delete the image from the dashboard as well...  is there a plugin for that or any future plans for it?

**Comment by lauriejim** [comment]
Hi @eibrahim, our upload plugin is not finished and not published on npm so it's no actually possible to did it. Obviously documentation will be write when we are done with that.

It's coming in few days (before the end of the week)

**Comment by ChunAllen** [comment]
@lauriejim do we already have a documentation for this? Is there a way I can upload an image using the Strapi web?

<img width="1680" alt="screenshot 2018-10-15 16 41 47" src="https://user-images.githubusercontent.com/2100728/46939587-3dc9a900-d099-11e8-9ede-073bfcbcb83d.png">

**Comment by lauriejim** [comment]
Follow the documentation https://strapi.io/documentation/3.x.x/guides/upload.html#install-providers

**Comment by 422vishal** [comment]
Is there any documentation for hosting images on s3 using strapi ?

**Comment by davidkartuzinski** [comment]
yes there is.  https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws - these should help you. @422vishal

**Comment by 422vishal** [comment]
This link explains how to configure aws for s3. How would I configure strapi to allow upload to happen on s3 ?

**Comment by davidkartuzinski** [comment]
@422vishal - You're totally correct.  This step is missing from the docs.  We are updated the docs right this second.  If you're following the existing docs, these steps occur:

**During the Prepare and clone Strapi project to server**

After:

`npm install pg`

Run:

`npm install strapi-provider-upload-aws-s3`

Then push to your GitHub Repo.  

**Just after Prepare and clone Strapi project to server**

### Configure Strapi Provider AWS S3 plugin

The next steps involve configuring Strapi to connect to the AWS S3 bucket.

1. Locate your `IPv4 Public IP`:

- Login as your regular user to your `EC2 Dashboard`
- Click on `1 Running Instances`.
- Below, in the **Description** tab, locate your **IPv4 Public IP**

2. Next, create your **Administrator** user, and login to Strapi:

- Go to `http://your-ip-address:1337/`
- Complete the registration form.
- Click `Ready to Start`

3. Configure the plugin with your bucket credentials:

- From the left-hand menu, click `Plugins` and then the `cog` wheel located to the right of `Files Upload`.
- From the dropdown, under **Providers**, select `Amazon Web Service S3` and enter the configuration details:
  **Note:** You can find the **Access API Token** and **Secret Access Token** in the **configuration.csv** file you downloaded earlier or if you saved them to your password manager.
  - **Access API Token**: This is your _Access Key ID_
  - **Secret Access Token**: This is your _Secret Access Key_
    Navigate back to your **Amazon S3 Dashboard**:
  - **Region**: Is your selected region, eg. `EU (Paris)`
  - **Bucket**: Is your bucket name, eg. `my-project-name-images`
  - Set your **Maximum size allowed(in MB)** to a value: eg. _10mb_
  - Select `ON`, for **Enable File Upload**
  - Click the `Save` button.

You may now test the image upload, and you will find your images being uploaded to **Amazon AWS S3**.

Note: You have to run Strapi in production.  There was another error in the Docs, after saving the **ecosystem.config.js**, start your project like this:

```
cd ~
pm2 start ecosystem.config.js
```

I will shortly have a branch for you to follow and look at in sequence.  Meanwhile please let me know if this solves it for you?

**Comment by Nauman440** [comment]
@eibrahim I was also having confusion while connecting S3 bucket with my strapi project because it's not properly explained in documentation. 
First of all you have to create an S3 account and then install the external provider for S3. 
You can follow this articles, it explains each and every step clearly.

https://www.mstweaks.com/how-to-connect-the-aws-s3-bucket-with-strapi-for-storing-data/
