### ISSUE TITLE
Mark select input as not editable has no effect on update existed entity

### ISSUE THREAD

**Issue by yaroslavyal** [strapi/strapi#7455]
**Describe the bug**

I have a collection with the field of the Relation type. After upgrading to the latest version, disabling relational fields no more works.

**Steps to reproduce the behavior**

1. Create two collections
2. Add a relational type field to one of the collections.
3. Save the new record to the collection with the relational field.
3. Go to 'Configure the view' in Content-Manager plugin.
4. Select a relational field and mark it not editable.

**Expected behavior**
The data in the relational field is unable to change.

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.7
- Strapi version: 3.1.3
- Database: PostgresSQL
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Hi @yaroslavyal I tested on the latest release today (v3.1.4) and could not reproduce the issue:

![image](https://user-images.githubusercontent.com/8593673/90192761-70698900-dd78-11ea-96c3-388929b71cf4.png)

**Comment by yaroslavyal** [comment]
Hi @derrickmehaffy ,  I've upgraded to the v3.1.4 and able to reproduce the bug. The disabling relational field works properly on creating a new entry. But after that when I go to update a saved entry, the relational field is not disabled.
I think this [condition](https://github.com/strapi/strapi/blob/331b73801f7e8fc3e4747b39aa1295f1964448ef/packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js#L210) is the reason for the problem.

**Comment by lauriejim** [comment]
Hello! Thank you for these details.
I confirm the issue is on the edit not on the create action.
Ping @soupette.
Can you please make sure the code you highlighted is the right one and submit a PR to fix this issue. Thank you.

**Comment by abdonrd** [comment]
I have the same issue with the lastest version!
