### ISSUE TITLE
Quickstart Strapi Project Fails - "Cannot find module './_baseHas'"

### ISSUE THREAD

**Issue by iCianan** [strapi/strapi#7457]
**Describe the bug**
Following the quickstart guide the following command results in an error:
npx create-strapi-app my-project --quickstart

**Steps to reproduce the behavior**

1. Open a terminal
2. Enter the command: npx create-strapi-app my-project --quickstart

**Expected behavior**
Strapi starts and admin gui is reachable 

**Screenshots**
![fail](https://user-images.githubusercontent.com/35161020/90175206-11eedb80-dd75-11ea-9879-28f345227c6a.PNG)
![fail1](https://user-images.githubusercontent.com/35161020/90175227-1adfad00-dd75-11ea-839a-1a4df217ebdc.PNG)

**System**
- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database:
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@iCianan I was not able to reproduce this on my systems:
- Windows 10 (build 2004)
- Linux Mint 19.3 (Ubuntu 18.04)
- macOS Catalina 

This appears to be an environment issue.

**Comment by iCianan** [comment]
Seems to be a problem with yarn. Wouldnt install all the dependencies for some reason.  Updating to node 14.x and using npm install and now strapi is starting as expected.
