### ISSUE TITLE
Can't edit an asset from SELECT section when it's not loaded in the BROWSE section

### ISSUE THREAD

**Issue by wesselvanderlinden** [strapi/strapi#7458]
**Describe the bug**
When I try to edit an already uploaded file from within the "selected assets" view, I get a JS error indicating it can't find my selected file.

**Steps to reproduce the behavior**

1. Go to a content type with a "multiple media" field
2. Click on the "+" icon to "add a new file"
3. Click on the "selected" tab
4. Click on the edit icon of a selected image

**Expected behavior**
I expect an edit view on the selected file to open where I can edit the files name, alternative text etc.

**Screenshots**
![Screenshot_20200813_205528](https://user-images.githubusercontent.com/11271614/90175245-6ca12b00-dda7-11ea-969e-cd7ab5dbb0dd.png)
![Screenshot_20200813_205823](https://user-images.githubusercontent.com/11271614/90175460-c0ac0f80-dda7-11ea-9c0e-93b94c8c7c91.png)

**System**

- Node.js version: v14.5.0
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: Manjaro linux

**Comment by derrickmehaffy** [comment]
Please try to run a `yarn build --clean` or `npm run build --clean` as I was not able to reproduce on v3.1.4 on Linux Mint 19.3

**Comment by wesselvanderlinden** [comment]
That doesn't work for me unfortunately.

I think it has to do with the images loaded in the "browse" tab. If a selected image is not in there, the edit button will break.

**Comment by lauriejim** [comment]
Hello did I miss something?
Here is the video of what is did and it's working fine.
https://www.loom.com/share/17d9274537bb4de1849f6c4a5bd971b7

**Comment by wesselvanderlinden** [comment]
Here is a video to show how you can reproduce it: https://streamable.com/97dy0f
Note that the image I select to edit in the "Selected" tab is not loaded in the "Browse" tab

**Comment by lauriejim** [comment]
Can you confirm that this image is still in your media lib? Just not in the first page.

**Comment by wesselvanderlinden** [comment]
@lauriejim yes it is, but on the third page in the "Browse" tab

**Comment by lauriejim** [comment]
Can you try to go on the third page (to load the file) and then click on the button that shows trigger the error.
So, if the issue comes from the load of the image, you should not have the issue in this case.
Can you confirm that?

**Comment by wesselvanderlinden** [comment]
Yes I can confirm: https://streamable.com/

It only happens when the image is not in the Browser tab, if it is it works just fine.

**Comment by lauriejim** [comment]
Thank you for helping us to identify the source of the issue.
I will really appreciate your help if you can submit a PR to fix the issue.
It's the summer and a vast part of the team is OOO.
Thank you for your time.
