### ISSUE TITLE
Unable to get secretToken in new 3.1.4.

### ISSUE THREAD

**Issue by fellz** [strapi/strapi#7468]
**Describe the bug**
I am trying to login to admin panel `http://localhost:1337/admin/auth/login` after updating to 3.1.4 and get error 
**Error: secretOrPrivateKey must have a value**
`\node_modules\jsonwebtoken\sign.js:107:20)`

I do have a key in `/extensions/user-permissions/config/jwt.js`

**Steps to reproduce the behavior**

1. changed version of the packages to 3.1.4 in packages.json
2. deleted .cache and build folders
3. re-built admin with strapi build
4. run yarn develop
5. Go to admin got redirect to admin login
6. Enter credentials got an error 500

**Expected behavior**
Should open admin panel after login 

**Code snippets**
From debbuging i see that strapi.config.get('server.admin.auth', {}); returns empty object {} so secret is **undefined**

```
const getTokenOptions = () => {
  const { options, secret } = strapi.config.get('server.admin.auth', {});

  return {
    secret,
    options: _.merge(defaultJwtOptions, options),
  };
};
```

**System**

- Node.js version: 12.6.1
- NPM version:  6.14.6
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: windows

**Comment by alexandrebodin** [comment]
Hello, It seems you didn't follow the migration guide. You need to add a config var :) 
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html
