### ISSUE TITLE
Connector for DynamoDb AWS

### ISSUE THREAD

**Issue by tonihauptcc** [strapi/strapi#747]
I want to achieve connecting to a dynamoDB from AWS, is there some quick woprkaround or some instructions how to make this possible?

**Comment by lauriejim** [comment]
Hi @tonihauptcc .

It's actually not possible. We don't developed connector for this database.

If you want to checkout how connectors works, look `strapi-bookshelf` and `strapi-mongoose` (and good luck !)

**Comment by tonihauptcc** [comment]
how can we hook into the install process?

**Comment by lauriejim** [comment]
You will have to create duplicate of `strapi-mongoose` node module (you call it `strapi-dynamodb` for example) then you update your `config/environments/.../database.json` and update the connector.

Then you have to write your connector for DynamoDB

**Comment by zfedoran** [comment]
Has anyone looked into how much `mongoose` the `strapi-mongoose` needs? I wonder if `dynamoose` would work as a drop in replacement. 

Might be worth looking into..

**Comment by tonihauptcc** [comment]
Sounds like a good way. Will deep dive into it

**Comment by santiagopampillo** [comment]
Did you succesfully connect Starpi to dynamo?

**Comment by Vadorequest** [comment]
Also interested

**Comment by ericbharding** [comment]
Also interested in a Dynamo connector

**Comment by dylan-westbury** [comment]
Also would be interested in dynamo connected

**Comment by pbn04001** [comment]
Want to keep this thread alive, any news on a dynamoDB connector?

Side Note: always working towards a fully serverless solution, would love exposed its logic in such a way I could plug it into lambda functions that the ui would hook into.

**Comment by derrickmehaffy** [comment]
@pbn04001 it's unlikely that Strapi themselves will take up this database, it will likely be up to the community to build and publish a hook for this.

**Comment by albertpak** [comment]
👍

**Comment by santhosh34** [comment]
Also interested....

**Comment by jpmayorga** [comment]
Any news about this?

**Comment by derrickmehaffy** [comment]
Nothing new from Strapi on this that I am aware of, someone in the community will likely need to build, publish, and manage it

**Comment by dmportella** [comment]
i would consider building this is it basically just mimicking the moongoose plugin and replacing it with aws dynamodb specific things?

**Comment by pedreviljoen** [comment]
@dmportella 
Have you made progress on this?

**Comment by derrickmehaffy** [comment]
> i would consider building this is it basically just mimicking the moongoose plugin and replacing it with aws dynamodb specific things? If i were to do this, i would like to push to main line not interested on running a public repo myself.

Right now @dmportella Strapi is not entertaining additional DB connectors in the main repo, as they don't want to maintain them.

**Comment by rvigneshw** [comment]
> i would consider building this is it basically just mimicking the moongoose plugin and replacing it with aws dynamodb specific things? If i were to do this, i would like to push to main line not interested on running a public repo myself.

Have you made any progress in developing that?

**Comment by pupubird** [comment]
Interested!

**Comment by jeanlescure** [comment]
Really interested

**Comment by truancylounge** [comment]
Anyone interested in developing a dynamo connector or if anyone has started working on the connector let me know I can help out with the development.

**Comment by ajoslin103** [comment]
I'd be interested in collaboration, but I'm new to strapi so I'd not be able to lead.

**Comment by jaqsparow** [comment]
Any update?

I am also interested in dynamodb as strapi backend.

**Comment by derrickmehaffy** [comment]
Locking thread, please move discussion to our forum: https://forum.strapi.io
