### ISSUE TITLE
Reference or Embed other Collections rows on Mongo

### ISSUE THREAD

**Issue by pedrosimao** [strapi/strapi#748]
**Strapi version**:
v.3

**Do you want to request a *feature* or report a *bug*?**

I decided to give MongoDB a shot since Strapi v.3 support for MySQL is a bit unstable at the moment. So I was wondering how to reference other Collections without the default (one-to-one, many-to-one etc) relations, since they don't quite fit my needs.
I would like to reference Collection rows, like seen here:
https://alexanderzeitler.com/articles/mongoose-referencing-schema-in-properties-and-arrays/

Or eventually embed one Collection inside another. 
What's the best way to achieve this on Strapi?

Thanks a lot!

**Comment by Aurelsicoko** [comment]
@pedrosimao The references (one-to-one, many-to-one, etc) should fit your needs. We are doing the exact same things as in the blog post. However, we don't support nested references as they do in the blog post

```js
var PostSchema = new mongoose.Schema({
    title: String,
    postedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    comments: [{
        text: String,
        postedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User'
        }
    }]
});
```

To do the same thing using Strapi, you'll have to create a `Comment` model.

```js
// Comment
{
  ...,
  attributes: {
    "text": {
      "type": "text"
    },
    "postedBy": {
      "model": "user",
      "via": "comments"
    }
  }
}

// Post
{
  ...,
  attributes: {
    "title": {
      "type": "string"
    },
    "postedBy": {
      "model": "user"
    },
    "comments": {
      "collection": "comment",
      "via": "postedBy"
    }
  }
}
```
