### ISSUE TITLE
500 Error cannot create admin after successful deployment (Heroku, PostgreSQL)

### ISSUE THREAD

**Issue by martinditzel** [strapi/strapi#7480]
**Describe the bug**
After deploying my app successfully to Heroku, I cannot register a new admin & receive a 500 error (slug: '/admin/auth/register-admin'). This issue appears only after deploying (no admin issues in local development).

**Steps I took to fix it**
1. Given that I use the Heroku Postgres addon, I reset the addon & installed + configured a new db.
2. I followed the migration guide mentioned in #7176 https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html
3. Tried if #7343 applies, but I don't have any _custom implementation of the permissions.js policy_.

**Steps to reproduce the behavior**
1. Deploy application on Heroku with fresh database
2. Access the "register admin" site 
3. Fill out information & check box
4. Click submit button & no redirect happens
5. Check console & see 500 (Internal Server Error) for every click

**Expected behavior**
Successful creation of new admin user & access to strapi dashboard.

**System**
- Node.js version: 14.7.0
- NPM version: 6.14.7
- Strapi version: 3.1.3
- Database: PostgreSQL (Heroku Postgres addon)
- Operating system: Mac OS Catalina 10.15.5

**Additional context**
No extensions installed

Thank you for your help! :)

**Comment by lauriejim** [comment]
Hello! Can you try with a fresh new project, just to make sure it comes from the migration of your app.
Thank you.

**Comment by martinditzel** [comment]
Tried with fresh project and it works - so the issue originates from the migration. I'll just work with a fresh project, so I'll close the ticket. Thanks!
