### ISSUE TITLE
Incorrect code comment on users-permission register controller.

### ISSUE THREAD

**Issue by psikoi** [strapi/strapi#7481]
**Describe the bug**
Nothing major, this is probably a typo or an outdated code comment:

```javascript
    // Throw an error if the password selected by the user
    // contains more than two times the symbol '$'.
    if (strapi.plugins['users-permissions'].services.user.isHashed(params.password)) {
      return ctx.badRequest(
        null,
        formatError({
          id: 'Auth.form.error.password.format',
          message: 'Your password cannot contain more than three times the symbol `$`.',
        })
      );
    }
```

Link to snippet: https://github.com/strapi/strapi/blob/331b73801f7e8fc3e4747b39aa1295f1964448ef/packages/strapi-plugin-users-permissions/controllers/Auth.js#L415

As you can see, the comment says **two times**, while the error message AND the `isHashed` function say **three** is the correct amount.

This seems to still be in `master` code as of this post.

**Comment by lauriejim** [comment]
Thank you, can you please submit a PR to update this comment.
Thank you.

**Comment by psikoi** [comment]
Will do.

**Comment by derrickmehaffy** [comment]
Fixed in above PR

**Comment by borm** [comment]
@derrickmehaffy, can u explain please why user cant have more than two times the symbol '$' in his password?
any security risks?

**Comment by derrickmehaffy** [comment]
I'm not aware of that limitation, I would offer a guess to the cause as being the regex we use to validate the password. Can you open a new bug report @borm

**Comment by jscottsf** [comment]
It's being use to detect whether the password has been bcrypted. hashPassword calls isHahsed which does the check. Even worse, the validation is not done in resetPassword so a user could type in a password with enough dollar signs to "appear" hashed and inadvertently set their password to null.

Overall this feels wonky and inconsistent. Hmmm.
