### ISSUE TITLE
Reset password and username

### ISSUE THREAD

**Issue by fjkiani** [strapi/strapi#7493]
**Describe the bug**
Hi there,

I keep receiving an "Invalid Credentials" message when the credentials I am using are correct. When I click "reset password", a reset link is never sent to me either. 

Can someone please help on how I can reset these credentials?

**Steps to reproduce the behavior**

1. Go to https://strapi-mongodb-database.herokuapp.com/admin/auth/login
2. Click on username and password 
3. Invalid credentials

**Expected behavior**
Invalid credentials are displayed. When I click reset password, no credentials are sent to me with any link

**Code snippets**
https://github.com/fjkiani/shop/tree/master/mongoDB-strapi

**System**

- Node.js version: 
- NPM version: v11.2.0
- Strapi version: 3.0.0-beta.19.3
- Operating system: MacOS

**Additional context**
I tried to use the documentation below, but after I type the last command, I get three dots on the bottom and don't know how to proceed

https://github.com/fjkiani/shop/tree/master/mongoDB-strapi

**Comment by derrickmehaffy** [comment]
Hello, the Strapi version you specified `Strapi version: 3.0.0-beta.19.3` is no longer supported, please update the latest stable release v3.1.4.

To see supported versions you can refer to our [Security Policy](https://github.com/strapi/strapi/security/policy)

To see migration guides to update your project you can refer to our documentation: https://strapi.io/documentation/v3.x/migration-guide/

**Comment by lauriejim** [comment]
Hello! If you never receive an email, probably because you are using the default email provider.
I suggest you install a third party provider like SendGrid to send emails.
The default one can fail because it's not using a proper SMTP server...
Then when you installed and setup the email provider, you will be able to receive your link.
Here is the docs - https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#install-new-providers

**Comment by derrickmehaffy** [comment]
@fjkiani in this case you can open the database in some kind of client (DBeaver on Win, Linux, Mac or HeidiSQL on Windows) and delete the existing user from `strapi_administrators` which will prompt your local app to register a new admin user.

**Comment by TheMangoTrain** [comment]
**Manual password reset (via database)**

If it helps anyone, you can keep everything as-is and just manually place a new temporary admin password into the database.

For example: I couldn't login to my local Strapi instance; invalid credentials for some reason. No email service set up yet, so I couldn't get a password reset email. So, using phpmyadmin, I went to my Strapi db and then the table `strapi_administrator` and pasted in a new password.

The pasted password must be encrypted the same way of course. The encryption is **bcrypt**, and here's a sample temporary password:

1. **Encrypted password (to place into the database):**
`$2a$10$MeCkt3/uZnh0tZh6NDTO5uvxiSw1z3TbuNPkTPRIO1r6Agq1Ak/SS`

2. **Password text (when you re-attempt login):**
`somelongpassword`

3. **Once logged in, go to your profile page and set a new password.**

This article here covers a more comprehensive way (for Mongo DB) and is where I found the bcrypt sample:
https://hashinteractive.com/blog/strapi-change-admin-password-in-mongo-database/

Previous to this, I attempted this reset solution, but none of the commands worked in Strapi console:
https://medium.com/@marudhupandiyang/notes-on-strapi-local-password-reset-63a76c7098cb

**Comment by derrickmehaffy** [comment]
We also added a reset password CLI command: https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-admin-reset-user-password
