### ISSUE TITLE
Unit testing error: EBUSY: resource busy or locked, unlink

### ISSUE THREAD

**Issue by BrunoApparecido** [strapi/strapi#7494]
**Describe the bug**
I running test and throwing this error: "EBUSY: resource busy or locked, unlink"

**Steps to reproduce the behavior**

1. npx create-strapi-app test-app
2. Configurate testing (https://strapi.io/documentation/v3.x/guides/unit-testing.html)
3. npm test

**Screenshots**
![image](https://user-images.githubusercontent.com/13833928/90354263-2c4be200-e01f-11ea-863b-f356bf80148d.png)

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: SQLite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
This appears to be an issue with windows locking interactions with the SQLite file :thinking: Can you please test this with one of the other databases? 

- PostgreSQL
- MySQL
- MariaDB
- MongoDB

**Comment by BrunoApparecido** [comment]
I debugged the code and found that this problem happens when the test tries to delete the database file 

`fs.unlinkSync(tmpDbFile);`

I did a test inside a linux container and the process worked normally

it may be a problem with windows and sqlite

**Comment by derrickmehaffy** [comment]
That is my guess as well @BrunoApparecido windows appears to be locking the sqlite file. @lauriejim do you have any suggestions here. My only thought it putting a notice on the docs that the guide won't work with SQLite and Windows.

**Comment by lauriejim** [comment]
Hello! Yes can you please update the documentation according to that @derrickmehaffy . Thanks.

**Comment by derrickmehaffy** [comment]
Closing as PR merged
