### ISSUE TITLE
Erros while trying to implement Polymorphic model

### ISSUE THREAD

**Issue by pedrosimao** [strapi/strapi#750]
**Node.js version**:
9.7.1
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.3
**Operating system**:
Ubuntu

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Get server errors after I tried to implement a Polymorphic model.

I get the following error message:

> TypeError: Cannot read property 'globalId' of undefined
>     at _.forEach (/home/adesias/adesias_strapi/node_modules/strapi-mongoose/lib/index.js:252:143)
>     at /home/adesias/adesias_strapi/node_modules/lodash/lodash.js:4917:15 
>     ....

 
**If the current behavior is a bug, please provide the steps to reproduce the problem**
I have two models, one containing attributes:
`"childTempade": { "model": "static01", "via": "parentPage"}`
an another containing:
`"parentPage": { "model": "lesson", "via": "childTemplate"}`

When I change `"model": "static01" to "model": "*"` the bug appears.
I tried to follow the Polymorphic examples given in the documentation but it does not work.
It would be nice to implement Polymorphic models via the Strapi UI interface also. But this would be a feature request. I would be happy enough to see the bug fixed.

**What is the expected behavior?**
Being able to create a Polymorphic problem without any issue.

**Comment by pedrosimao** [comment]
I have also noted that if I use "collection": "*", instead of "model": "*" the server doesnt even start, saying something is wrong with the model. This is the error message:

> Something went wrong in the model `Lesson` with the attribute `childTemplate`

Maybe this might give you a clue from where the bug comes from?

**Comment by pedrosimao** [comment]
This is not "help wanted" issue. It is a real bug.
Do you need me to record a video with the bug and share all my code?
I tried to apply the exact recommendations of Polymorphic models given in the v.3 Documentation, and it doesn't work.
Why are you ignoring this issue?

**Comment by lauriejim** [comment]
As @TheWebsDoor told you here https://github.com/strapi/strapi/issues/711 . It's done on a specific branch, will be release at the end of the day or tomorrow. So it's actually normal if it doesn't work.

I will ping you on this issue when it will be released to ask you to test it again with `alpha.11` version.

**Comment by pedrosimao** [comment]
@lauriejim Thanks a lot. I was not sure if the "upload" feature would fix the entire bug. That's why I insisted. Count on me for extensive testing! I actually plan to put Polymorphic model live on a real application very soon. So I will do everything needed to make it work.

**Comment by pedrosimao** [comment]
Finally it would be nice if Polymorphic model could be chosen from Admin interface directly. I think this would guarantee maximum compatibility.

**Comment by pedrosimao** [comment]
@Aurelsicoko have you seen this bug with multiple "Content Types" using the same collection?
