### ISSUE TITLE
Add "Display name" to entities and their properties

### ISSUE THREAD

**Issue by sebqq** [strapi/strapi#7505]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Hello guys.

I was thinking about this feature where admin (during content-type building process) could assign something like "**Display name**" property.

_Especially older clients in my country (English is not native language here) keep asking me about why they have to work with "English entities" inside of admin dashboard. It simply takes more of their time to use admin panel and create content that they need._

This feature request would allow developers to set "Display name" **for every entity and it's properties**. After that, the admin panel would show Display name instead of entity/property name across whole dashboard (if Display name was not set we could safely fallback to entity's name).

This way, I (as developer) am able to fetch API using real entity's name and clients are free to use and work with featured "Display names".

_Feature could have also another positive impact. In admin dashboard we can avoid these "mechanical" like names of content types like "BlogPost" and/or "FAQ" and we can use more user-centric and natural names like "Blog Post" and/or "F.A.Q" if you know what I mean._ 

I (and devs from other countries where not all clients knows English) consider this feature as "critical" but I know to lots of you (native speakers) it could be just "nice to have".

Please, let me know if there is something I can do to help you with this feature.

Thank you so much!

**Comment by lauriejim** [comment]
Thank you for this message, I'm pretty sure we already had it a few times.
Ping @JabStrapi @Aurelsicoko

**Comment by aksdevac** [comment]
I think Its already supported you can click Edit icon besides collection type name to edit display name, & you can use different display name & collection name(in advance settings at time of create)

<img width="957" alt="edit-display-name" src="https://user-images.githubusercontent.com/2557058/90500881-206c3700-e169-11ea-9ea6-fdef512175bf.png">

**Comment by bernhardw** [comment]
@aksdevac The problem is, the "Display name" as shown in your screenshot is pluralized based on English rules. 

In German for example the plural of events is "Veranstaltungen" and Strapi automatically adds an "s" to the end => "Veranstaltungen**s**" - which is not correct.

**Comment by sebqq** [comment]
Then maybe display name shouldn't be pluralized at all. 

Also, it is already possible to assign display name to properties?

**Comment by aksdevac** [comment]
@sebqq yes using configure the view button, you can set label for property, there is different settings for Edit page & table view, so you might need to Edit at both place, below screenshot it for Edit page

<img width="1086" alt="property-label" src="https://user-images.githubusercontent.com/2557058/90503075-7db5b780-e16c-11ea-9b91-498eda3c497b.png">

**Comment by sebqq** [comment]
@aksdevac @lauriejim So if I change these settings (Add labels and display names) and afterwards use `git status` on project, no changes were made in folders that are not included in my project's `.gitignore` file.

So that means that changes were performed only in `build/` folder and these settings will be deleted whenever I make a fresh build. Am I right?

Thanks!

**Comment by derrickmehaffy** [comment]
@sebqq these changes are stored in the database, specifically the `core_store` table/collection.

**Comment by sebqq** [comment]
I'm sorry. Changes were made for Entities display names. However, changes were not made for properties labels.

**Comment by sebqq** [comment]
@derrickmehaffy So even labels from properties are written directly into the database?

I'm sorry I'm working with docker for first time in my life so I'm not able to look directly inside my db right now. Firstly, I will need to find out how to access container's database :D

**Comment by derrickmehaffy** [comment]
All of the display names are stored within the database (any of those "configure the view" options) they are not saved to the model settings. 

This was largely a workaround for now due to https://github.com/strapi/strapi/issues/1114 and related to this FAQ article that explains it in more detail: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#can-i-store-my-content-manager-layout-configurations-in-the-model-settings

As for connecting to your database inside the container, you will have to pass the port from the container to your host system instead of just over the docker network.

https://docs.docker.com/config/containers/container-networking/

**Comment by sebqq** [comment]
@derrickmehaffy well, I'm feeling as a dumb right now. I should check a documentation first before taking your time. Thank you very much!

**Comment by sebqq** [comment]
So the only thing that left is probably to let developers choose if they would like to use plural form of collection display name or not as mentioned earlier.

> @aksdevac The problem is, the "Display name" as shown in your screenshot is pluralized based on English rules.
> 
> In German for example the plural of events is "Veranstaltungen" and Strapi automatically adds an "s" to the end => "Veranstaltungen**s**" - which is not correct.

**Comment by derrickmehaffy** [comment]
This is a topic that we have discussed internally but not come to a conclusion, I'm wondering if this would be better suited to open up an RFC on to discuss properly.

https://GitHub.com/Strapi/rfcs

**Comment by derrickmehaffy** [comment]
Thank you @sebqq
