### ISSUE TITLE
x-generation-date gets updated on every server restart

### ISSUE THREAD

**Issue by RileyMShea** [strapi/strapi#7509]
**Describe the bug**

In the `./extensions/documentation/documentation/vx.x.x/full_documentation.json` file, the `x-generation-date` field under `info` gets updated every time the server is restarted.  This happens even when there has been no change to the documentation or any other code in the project's codebase. 

This causes problems because git tracks this file, so I am constantly committing this file for this `x-generation-date` field or I am forced to manually stage/unstage it from the rest of my changes.

**Steps to reproduce the behavior**

1. Have a strapi server running in development mode w/ the documentation plugin installed
2. restart the strapi server, again in development mode,  with no changes made to codebase
3. observe change in `x-generation date` 

**Expected behavior**
I would expect the `x-generation-date` to only update when a change or update to documentation occurs.

**Screenshots**
This is a git diff of the only line in the only file in the entire project that changes when the server gets restarted:

![image](https://user-images.githubusercontent.com/10238802/90508458-c8f8a780-e125-11ea-9025-e615919f2d36.png)

**System**

Docker-Compose Stack
- Node.js version: lts v12
- NPM version: 6
- Strapi version: strapi/strapi:3.1.1-node12
- Database: mongoDb
- Operating system: Ubuntu

**Additional context**
This occurs every time I restart the docker-compose stack.
- The stack runs my strapi project code in a mounted volume
- The strapi server is run in development mode

**Comment by derrickmehaffy** [comment]
I will ping @alexandrebodin and @petersg83 as this shouldn't be regenerated unless it's missing on the filesystem or the manual generation is triggered in the doc plugin admin menu.

**Comment by pondpiu** [comment]
I'm annoyed by this issue as well and have look into it a bit to find out that when strapi-plugin-documentation/config/functions/bootstrap.js is triggered, checkIfPluginDocNeedsUpdate will always return true on checking plugin `strapi-plugin-users-permissions` due to how createDocObject in documentation.js is defined

i proposed a fix in #7598

**Comment by lauriejim** [comment]
Thank you for your PR, the tech team will review it as soon as possible!
I really appreciate your contribution on this issue.

**Comment by victorigualada** [comment]
This is happening again. Every time there is a file change, the `x-generation-date` gets updated, generating conflicts in each PR.

**Comment by aliataf** [comment]
Commenting here as [17643](https://github.com/strapi/strapi/issues/17643) is locked.

You can use the `mutateDocumentation` method mentioned in the [docs](https://docs.strapi.io/dev-docs/plugins/documentation#providing-replacement-documentation)

> The Documentation plugin’s configuration also accepts a mutateDocumentation function on info['x-strapi-config']. This function receives a draft state of the generated documentation that be can be mutated. It should only be applied from an application and has the final say in the OpenAPI schema.

For example, to delete the x-generation-date property, you can update your `config/plugins.(js|ts)` file as follows:

```typescript
export default () => ({
        documentation: {
            enabled: true,
            config: {
                'x-strapi-config': {
                    mutateDocumentation: (documentation) => {
                        // override the draft documentation object
                        delete documentation.info['x-generation-date'];
                        return documentation;
                    }
                },
            }
        }
});
```
