### ISSUE TITLE
Blog post returns "502 Bad Gateway"

### ISSUE THREAD

**Issue by sandoche** [strapi/strapi#7510]
This page I found on twitter does not work and returns 502
https://blog.strapi.io/content-internationalization-with-strapi/

Twitter link:
https://twitter.com/strapijs/status/1041613814209421313?lang=en

Screenshot:
![image](https://user-images.githubusercontent.com/3635348/90511259-1a1f9000-e154-11ea-952d-b674a36ff5de.png)

**Comment by lauriejim** [comment]
I'm not able to find the article based on the slug.
blog.strapi.io is now strapi.io/blog
So migration issue probably.
Guys are mentioned here so they will receive a notification to manage that.
To keep the open issues related to the Strapi project (not on the blog or website) I'm closing this issue.
In any case, thank you for reporting this issue.

**Comment by yvesdo** [comment]
It was actually an article that we took down, because the workaround caused more worries than solutions.

**Comment by sandoche** [comment]
At the end I managed to find a clone of this article on medium:
https://medium.com/strapi/content-internationalization-with-strapi-507ef5869c15

So maybe you should take it down aswell.
I ended up following this data model architecture: https://dev.to/astagi/how-to-build-a-jamstack-multi-language-blog-with-nuxt-js-3gah
