### ISSUE TITLE
Cannot get data through the API using valid token

### ISSUE THREAD

**Issue by koskokos2** [strapi/strapi#7512]
**Describe the bug**

I'm using `gatsby-source-strapi` to get data from Strapi API and it was failing for me with 403 (fails on this line `https://github.com/strapi/strapi/blob/1e67421668a8a8528d03e09a52057bae35534e03/packages/strapi-admin/middlewares/auth/index.js#L42`).

I can see that `/auth/local` is successful and token that is passed to the data endpoint (`GET /data-type`) is valid (is it passing this line successfully `https://github.com/strapi/strapi/blob/1e67421668a8a8528d03e09a52057bae35534e03/packages/strapi-admin/middlewares/auth/index.js#L37`). 

Digging into the code I realised that this middleware `https://github.com/strapi/strapi/blob/master/packages/strapi-admin/middlewares/auth/index.js` is looking for users in `strapi_administrator` and that table does not contain users from `/admin/plugins/content-manager/collectionType/plugins::users-permissions.user` page. 

I also tried to use token returned from `/admin/login` to get data through the API but it responds with 401.

As a workaround I created a user in `strapi_administrator` (new permission system) with id that matches user from `/admin/plugins/content-manager/collectionType/plugins::users-permissions.user` page and was able to get data through the API that way.

**Steps to reproduce the behavior**

1. Create user on `/admin/plugins/content-manager/collectionType/plugins::users-permissions.user`
2. Use that user to login and get token through using `POST /auth/local`
3. Try to get data from the API using `GET /data-type`
4. Observe successful login but 403 instead of data

**Expected behavior**

`gatsby-source-strapi` should be able to get data.

**System**

- Node.js version: 12
- NPM version:
- Strapi version: 3.1.4
- Database: Postgres
- Operating system: Debian

**Comment by derrickmehaffy** [comment]
Is this for `gatsby-source-strapi` or is this via something like postman?

**Comment by koskokos2** [comment]
Needed it for `gatsby-source-strapi` and while I was debugging the route cause I checked on requests it is doing and was debugging through Postman

**Comment by lauriejim** [comment]
Hello! The first question is, did you migrate your app, or is it a fresh new one?
I highly suppose you migrated it and you use the same `jwtSecret` from the users-permission for the admin.
If it's the case, the reason come from there. You should have 2 differents value.

**Comment by derrickmehaffy** [comment]
Marking as closed since @koskokos2 stated it was working :)
