### ISSUE TITLE
Collection title not well pluralized

### ISSUE THREAD

**Issue by sandoche** [strapi/strapi#7520]
I have a collection named `Post` pluralized properly to `Posts` and another one called `PostTranslated` it has been pluralized  to `PostTranslateds` instead of `PostsTranslated`

![image](https://user-images.githubusercontent.com/3635348/90633894-c6c64400-e21e-11ea-8e55-759d56492366.png)

Is there a way to override this value? I couldn't find this in the documentation.

**Comment by lauriejim** [comment]
Hello! That's not really possible to customize that.
Please, check if `translatedPost ` works for you.

**Comment by sandoche** [comment]
I changed to `PostTranslation` and it works.
Thanks.

**Comment by derrickmehaffy** [comment]
Marking as closed per @sandoche
