### ISSUE TITLE
Updating a content type to have a required field with existing data fails at the database level, causes crash

### ISSUE THREAD

**Issue by projodesign** [strapi/strapi#7526]
**Describe the bug**
This has happened twice, first time I had to do a fresh install and lost a lot of data I'd input into Strapi. 
Using the one click solution provided by Digital Ocean, I get Strapi up and running without issues. Then suddenly I'll make a change that requires Strapi to restart itself - this is normally fine and it does it. However, twice it has told me "it's taking longer than expected" but never actually restarts. 

If I try to hit any the admin or any of my endpoints I just get NGINX 502 Bad Gateway. 

When trying to hit the endpoints etc, the Error Logs states: *7 connect() failed (111: Connection Refused) while connecting to Upstream Client: {my_ipaddress}).

Restarting NGINX doesn't resolve the issue.

I've not touched any configs at all, this is the out the box install Digital Ocean offers.

If it helps, the error log states the upstream is http://127.0.0.1:1337/{endpoint}.

**Steps to reproduce the behavior**

The change that caused this was adding a new field to a Content Type. The content type already had entries in it, and the new field I made a required one. 

**System**
Node Version- 12.18.3
NPM Version - 6.14.6
Server: / 2 GB Memory / 50 GB Disk / LON1 - Strapi 3.1.0 on Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
Can you please update your issue and follow the issue template: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

The reason for this template is it provides us with useful system information to be able to reproduce the issue, in your case stuff like the node version.

In your case I take it you are using the One-click, are you able to ssh in and read the logs from the one-click documentation: https://strapi.io/documentation/v3.x/installation/digitalocean-one-click.html#accessing-the-service-account

(You will need to change to the service `strapi` account after you SSH in to see the logs)

**Comment by projodesign** [comment]
Updated original post with Node Version.

I am actually able to recreate the issue.

I recreated my droplet from backup and it was working fine, so I added a "long text" field (allergies) to a Content Type (Recipes) that already had 3 recipes in it. This worked fine.

I then created another "long text" field (dietary info), but made this field a "Required" field. This crashed the server again and I get Bad Gateway again. 

Can you only create required fields on "empty" Content Types?

Thanks for the pointers on logs - here's what was output:

<img width="907" alt="Screenshot 2020-08-19 at 19 22 08" src="https://user-images.githubusercontent.com/20710402/90675250-1d994100-e252-11ea-8e8f-10fa5d1482f6.png">
<img width="882" alt="Screenshot 2020-08-19 at 19 25 35" src="https://user-images.githubusercontent.com/20710402/90675263-212cc800-e252-11ea-9be9-feb9aa8a17c5.png">

**Comment by derrickmehaffy** [comment]
The issue is as you said, the database is throwing an error because it applies a `not null` constraint to the table (or tries to) and even if you set a default in Strapi, that default isn't set on the database, so we end up in a catch 22 (chicken and egg problem).

I'll mark this as a bug and see if @alexandrebodin or @petersg83 have a suggested workaround until a proper fix can be made.

For now restore from your backup, create the new field without required, set the values on the other entries, then update the new field as required, please do let me know if you have any issues

**Comment by demangejeremy** [comment]
Same problem on my side. A fix would be great!

**Comment by pmrotule** [comment]
I had the same issue:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/10983258/92025911-7e4f7000-ed60-11ea-9296-ca4d7c0dd922.png">

Then I looked at my database and the new field was not there yet which means it crashes when it **tries** to add it. I simply discarded the changes I had on the model settings file (the new attribute definition), restarted my server and it solved the issue. So no need to restore your database. The other steps are still needed though:

> create the new field without required, set the values on the other entries, then update the new field as required

Would be great to have a proper fix anyway. Personally, I would always allow null in the database and only make it required within Strapi. That's how presence validation works in Rails models for instance which allow you to add a presence validation later on even if you have thousands of entries violating it. You will simply not be able to update an entry anymore unless you provide a value for the newly required attribute.

**Comment by acao** [comment]
also seeing this issue, yikes!

**Comment by acao** [comment]
@pmrotule confirmed that removing the field from the model file did the trick!

**Comment by alexandrebodin** [comment]
@pmrotule This is precisely what we are going to be doing in the upcoming version :)

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/6292
