### ISSUE TITLE
Records with NULL ROLE in "users-permissions_role" database

### ISSUE THREAD

**Issue by tudislei** [strapi/strapi#7536]
I start my strapi like usual , it throws an error:

```
 error TypeError: Cannot read property 'id' of null
    at \node_modules\strapi-plugin-users-permissions\services\UsersPermissions.js:267:62
```

so I checked that line of code and then my database with this command , and something very wierd are there:

```
SELECT * FROM "users-permissions_permission"
WHERE ROLE IS NULL
```
there are 16 records whose "ROLE" values are null ,
I didn't delete any role for sure.
These records are  "auth changepassword" and "email updatesettings" and "email getsettings"

Is this a known bug and how to fix it? Thank you so much

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

Please see the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
