### ISSUE TITLE
Can't run Strapi v3.1.4 app when using existing/old Mongo DB

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#7540]
**Describe the bug**
Can't run Strapi v3.1.4 app when using existing/old Mongo DB with same login credentials (using email only, not just username)

**Steps to reproduce the behavior**

1. Install Strapi v3.1.4 app with MongoDB, following this doc: https://strapi.io/documentation/v3.x/guides/databases.html#mongodb-installation
 Can use this command: ` npx create-strapi-app@3.1.4 my-project`
2. Build & run the app -- It works as expected, with MongoDB used while creating the Strapi App
3. Now try to switch MongoDB & use existing/old DB on `/config/database.js`
4. Now try to run the app - Not able to login at all,`/admin/login` is throwing 400 error.

**Expected behavior**
App should work as expected even switching/using old mongoDB

**Observed behavior**
Not able to login Strapi v3.1.4 app, with same login credentials & `/admin/login` is throwing 400 error.

**Note**: 
It works as expected when i switch to new MongoDB back again.

**It works with this:**

 ` module.exports = ({ env }) => ({`
  `defaultConnection: 'default',`
  `connections: {`
    `default: {`
      `connector: 'mongoose',`
      `settings: {`
        `host: env('DATABASE_HOST', '127.0.0.1'),`
        `srv: env.bool('DATABASE_SRV', false),`
        `port: env.int('DATABASE_PORT', 27017),`
        `database: env('DATABASE_NAME', 'strapi-default-app-3-1'),`
        `username: env('DATABASE_USERNAME', ''),`
        `password: env('DATABASE_PASSWORD', ''),`
      `},`
      `options: {`
       ` authenticationDatabase: env('AUTHENTICATION_DATABASE', null),`
        `ssl: env.bool('DATABASE_SSL', false),`
     ` },`
  `  },`
  `},`
`}); `

**It Breaks with this:**

 `module.exports = ({ env }) => ({`
  `defaultConnection: 'default',`
`  connections: {`
    `default: {`
      `connector: 'mongoose',`
     ` settings: {`
       ` host: env('DATABASE_HOST', '127.0.0.1'),`
    `    srv: env.bool('DATABASE_SRV', false),`
       ` port: env.int('DATABASE_PORT', 27017),`
      `  database: env('DATABASE_NAME', 'strapi-default-app'),`
       ` username: env('DATABASE_USERNAME', ''),`
       ` password: env('DATABASE_PASSWORD', ''),`
      `},`
      `options: {`
        `authenticationDatabase: env('AUTHENTICATION_DATABASE', null),`
       ` ssl: env.bool('DATABASE_SSL', false),`
     ` },`
   ` },`
 ` },`
});
`

**System**

Node version: v10.15.3
NPM version: 6.4.1
Strapi version: 3.1.4
Database: Mongo DB `v4.0.3`
Operating system: MAC

**Comment by derrickmehaffy** [comment]
Can you please add the contents of the 400 error, with your reproduction steps we cannot reproduce the error

**Comment by vinod77** [comment]
This issue is due to case sensitive Email .. as it'a a mongoose implementation. 
Working when using all small case. Good to Close
