### ISSUE TITLE
Count issue filtering on "1 to many" relationships

### ISSUE THREAD

**Issue by FlorentPalomares** [strapi/strapi#7547]
Hello,

The count value returned by Strapi engine seems invalid (too high) when I'm filtering on multiple values on a field with a "1 to many" relationship.

Example: entity "product" is related to many entity "size".
```
{
  "kind": "collectionType",
  "collectionName": "products",
  "attributes": {
    "sizes": {
      "collection": "size"
    },
  }
}
```

And size is a simple entity, with a name:
```
{
  "kind": "collectionType",
  "collectionName": "sizes",
  "attributes": {
    "title": {
      "type": "string"
    },
  }
}
```

I have a single product, related to sizes "1month" and "3months".

But REST API (graphql awsell) returns a count value 2.
Here the query:
/products/count?_where[sizes.title_in]=1month&_where[sizes.title_in]=3months
https://iepf-strapi.herokuapp.com/products/count?_where[sizes.title_in]=1mois&_where[sizes.title_in]=3mois

I would expect having 1.

For information, I really just have 1 product:
https://iepf-strapi.herokuapp.com/products/count
=> value is 1

And, when I list products, it is OK:
/products/?_where[sizes.title_in]=1month&_where[sizes.title_in]=3months
https://iepf-strapi.herokuapp.com/products/?_where[sizes.title_in]=1mois&_where[sizes.title_in]=3mois
=> it shows only the product once

I guess this issue is related to SQL joins, and a missing DISTINCT during sql COUNT().

I'm using Strapi v3.1.3, and locally MacOS + MariaDB v10.4.
And I'm reproducing the bug on Heroku aswell (links provided).

**Comment by neudysrd** [comment]
Hi @derrickmehaffy 

I have exactly the same problem. I had published it in the forum a few days ago, I have detailed step by step and I have placed the use cases to reproduce it.

Check it https://forum.strapi.io/t/inconsistency-in-the-counts-fields-of-the-query-connector/974

**Comment by derrickmehaffy** [comment]
I have been able to reproduce the issue when using deep filtering on the aggregate count.

Short term workaround if you only need count is to use our guide to add the custom count option, which pulls from the count controller:

https://strapi.io/documentation/v3.x/guides/count-graphql.html#setup-the-application

**Comment by iksent** [comment]
@derrickmehaffy, hello! I have tried your solution, but there is another problem when counting items not by ID, but by another column:

![2020-11-13_16-36-35](https://user-images.githubusercontent.com/32956521/99068573-93e9dd00-25ce-11eb-8f81-e97d134e737d.png)

Am I doing something wrong or do I need to open bug report for this problem?

**Comment by iksent** [comment]
Any updates on this?

There is probably no solution now for fetching "relational" items with count (neither with `aggregate.count,` nor with [this guide](https://strapi.io/documentation/v3.x/guides/count-graphql.html#setup-the-application) due [to the bug](https://github.com/strapi/strapi/issues/7547)).

So it's impossible to create paginated lists.
