### ISSUE TITLE
/auth/forgot-password - an email is sent when requesting, but no URL is included in the email

### ISSUE THREAD

**Issue by cjpdee** [strapi/strapi#7548]
**Describe the bug**
When I use the /auth/forgot-password route, I receive the email to reset but that email contains only the code to reset - with no URL attached. The email looks like this:

`We heard that you lost your password. Sorry about that!

But don't worry! You can use the following link to reset your password:

?code=stringofnumbersandletters`

I am not sure if there is somewhere I need to explicitly set my app's URL, but I've not been able to find it so far online.

**Steps to reproduce the behavior**

1. Start new strapi installation
2. Create user
3. Test /auth/forgot-password with new user's email
4. Receive email with missing URL

**Expected behavior**
The email to include a URL

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.1
- Database: PostgreSQL
- Operating system: MacOS (running strapi in a x64 linux container)

**Comment by neumann-d** [comment]
I have the same problem.

With the 'Email adress confirmation' template the url is included, but with 'Reset password' it isn't.
Both templates contain the placeholder `<%= URL %>`

**Comment by derrickmehaffy** [comment]
Going to close this one for now, let us know if you need more help.

**Comment by Moorst** [comment]
@cjpdee did you manage to resolve this? I'm seeing the same issue and have defined a url in server.js.

I'm trying to include a url to reset the password on the frontend side, e.g. localhost:3000/auth/reset. 

Defining a url both with the request and in server.js seems to have no effect.
