### ISSUE TITLE
Add healthcheck API

### ISSUE THREAD

**Issue by msgeissler** [strapi/strapi#755]
The analytics and monitoring plugins are currently still WIP, but at least the analytics plugin will not be available for free. If the plan for the monitoring plugin is the same, I would like to suggest a separate / dedicated API for healthchecks that will be available for free (or make parts of the analytics / monitoring API available).
This way strapi can still be monitored for failure programmatically using a proper API. This does not mean that a full blown Prometheus integration is needed or all stats have to be available (if you intend to make the monitoring plugin subject to a charge as well), but some aggregated information on the current status can be enough (e.g. # of errors in the past x minutes; average response time over the past x minutes).

**Comment by msgeissler** [comment]
As mentioned by @Aurelsicoko in https://github.com/strapi/strapi-docker/issues/6#issuecomment-372236317 there is already a route that checks the current health of strapi. This should be enough to do basic monitoring of strapi using external tools.

What I would like to add to the discuss is a possible extension of the healtchcheck that includes the database as well. Otherwise the current API will return a positive status code but if the database is down strapi is actually "dead" for the most part.

**Comment by lauriejim** [comment]
That is interesting 👍

**Comment by msgeissler** [comment]
For the database check a very simple select on the smallest table would be enough, no big healthcheck of the database system.

**Comment by Aurelsicoko** [comment]
@msgeissler It's okay for us to make two routes, one for checking that the server is okay and another one for the database. However, if you're sending more information we need to double-check if it won't affect the future business model to make the open-source part sustainable.

**Comment by rkristelijn** [comment]
@see https://github.com/rkristelijn/strapi-health-plugin
