### ISSUE TITLE
Constraints (except required) on components always pass

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#7550]
**Describe the bug**
Constraints on components (except required) always pass.

**Steps to reproduce the behavior**

1. Create a component `comp` with a text field `name` that have constraint `max length` to `5`.
2. Create a content-type `article` with this compo named `myCompo`, non-repeatable
3. Make request:
```
POST http://localhost:1337/articles

body: {
  myCompo: {
    name: "a name that exceeds the max length"
  }
}
```
4. See that the new entry is correctly saved and returned

**Expected behavior**
The request should respond with an error 400 instead of 200.

**System**

- Node.js version: v10.21.0
- NPM version: 6.14.4
- Strapi version: 3.1.4
- Database: SQLite
- Operating system: macOS

**Additional context**
The only constraint that works is `required` because it is set directly in the database.
You can't see this bug if you use the admin panel because some validators run in the frontend.

**Comment by alexandrebodin** [comment]
The entity validator was initiatied but not finished for all the different types. 
We introduce it to fix some of the existing bugs. The components are not the only missing validators btw

**Comment by sam-pires** [comment]
I close the issue has it has been fixed with https://github.com/strapi/strapi/pull/7853
