### ISSUE TITLE
attribute array type didn't async to graphql definition

### ISSUE THREAD

**Issue by jackyang1984** [strapi/strapi#7556]
**Describe the bug**
I have define a array type in model setting, everything is ok, data can insert and update to db, but can't use graphql query, i check the graphql schema, the filed type did't async

**Expected behavior**
field definition in Model and graphql is async.

**Code snippets**

Address Model setting is
```
"attributes": {
"coordinates": {
"type": "array"
}
}
```

Graphql schema is
```
type Address {
coordinates: String
}
```

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Ubuntu (18.04)

**Comment by derrickmehaffy** [comment]
Closing as `array` is not a valid field type.
