### ISSUE TITLE
Double Access-Control-Allow-Origin on the API

### ISSUE THREAD

**Issue by bsthomsen** [strapi/strapi#756]
**Node.js version**:
9.7.1
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.11.0
**Operating system**:
Ubuntu

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Double Access-Control-Allow-Origin headers

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Make a request to /auth/local

**What is the expected behavior?**
One Access-Control-Allow-Origin header

The issue seem to be related these lines:
https://github.com/strapi/strapi/blob/7fdbee5dd49953628c5cc171aaf5a3c8e9cc2c2c/packages/strapi/lib/middlewares/cors/index.js#L34
https://github.com/strapi/strapi/blob/7fdbee5dd49953628c5cc171aaf5a3c8e9cc2c2c/packages/strapi/lib/middlewares/cors/index.js#L39

It looks like the AllowHeaders gets the origin too due to:
https://github.com/strapi/strapi/blob/3.0.0-alpha.11/packages/strapi-generate-new/files/config/environments/development/security.json#L52

Should this just be removed?

**Comment by bsthomsen** [comment]
Hey @lauriejim I'm sorry just found out this was caused by misconfigured nginx that overwrote the settings :(

**Comment by lauriejim** [comment]
Perfect :D
