### ISSUE TITLE
Strapi exits on fs.writeFile()

### ISSUE THREAD

**Issue by RyanPrentiss** [strapi/strapi#7561]
**Describe the bug**
When writing new files to the system via `fs.writeFile()`, Strapi exits returning the following error:

```
\node_modules\strapi\lib\commands\develop.js:87
            strapiInstance.server.destroy(() => {
                                  ^

TypeError: strapiInstance.server.destroy is not a function
```

**Steps to reproduce the behavior**

1. Create Custom Plugin `strapi generate:plugin my-plugin`
2. Via `{my-plugin}/config/function/bootstrap.js`
```javascript
fs.writeFile(`${__dirname}/../../models/testfile.txt`, "Test File Here.", (e) => e);
```
3. `yarn develop`

**Expected behavior**
File should be written to system without Strapi exiting.

**System**

- Node.js version: v12.16.3
- NPM version: 6.14.7
- Strapi version: 3.1.3
- Database: PostgreSQL 12.3
- Operating system: Windows 10 Home 1909

**Comment by derrickmehaffy** [comment]
For this let me ping @petersg83 or @alexandrebodin as I'm not sure of the best case here, I believe in this case you are trying to edit another models lifecycles file correct?

**Comment by RyanPrentiss** [comment]
> For this let me ping @petersg83 or @alexandrebodin as I'm not sure of the best case here, I believe in this case you are trying to edit another models lifecycles file correct?

That is correct. I'm am attempting to dynamically create a model-js file which includes a lifecycle event for a plugin.

**Comment by RyanPrentiss** [comment]
The same error occurs when executing `exec('echo > test.txt')`; however, `exec('strapi generate:model ...')` works perfectly within the _bootstrap.js_.

I've submitted a request for an update to allow `strapi generate:model` to accept an object via a `--lifecycles` flag.

**Comment by RyanPrentiss** [comment]
I've since narrowed down the issue. Whether using `echo` or `fs.write...`, the error only seems to occur via _bootstrap.js_. I have not yet encountered any errors when writing files to the system following bootstrap.

**Comment by alexandrebodin** [comment]
the bug is coming because the server instance is not completely instantiated before the boostrap function runs. We need a small fix to check if the server exists before trying to destroy it in the cause of early errors.
