### ISSUE TITLE
Misleading documentation for timestamp model option

### ISSUE THREAD

**Issue by spenweb** [strapi/strapi#7562]
Collection type admin page breaks after setting `timestamps` to false (a valid value per the [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/models.html#model-options)).

1. For example, I have a model called `order`. I change the timestamps option to false in this file `api/order/models/order.settings.json`:
![image](https://user-images.githubusercontent.com/46385475/90967461-69d3c380-e494-11ea-91c3-d54f3e170368.png)
1.I then navigate to the corresponding `order` collection types page here: http://localhost:1337/admin/plugins/content-manager/collectionType/application::order.order
1. I inspect the admin page error in development mode by running `strapi develop --watch-admin`.
1. This allows me to see a more detailed error message which reports: 
```
Something went wrong.
Details
TypeError: timestamps.includes is not a function
```

![image](https://user-images.githubusercontent.com/46385475/90967526-304f8800-e495-11ea-80fa-d3013e35ebe4.png)

**Expected behavior**
I expect that setting the `options.timestamps` value to false in a model will remove timestamps in the model as well as not produce errors in the admin panel.

**Temporary solution** 
Remove the `options.timestamps` property from the model settings.

**System**

- Node.js version: v12.17.0
- NPM version: 6.14.4
- Strapi version: 3.1.1
- Database: mongoDB
- Operating system: Mac 10.15.5

**Comment by derrickmehaffy** [comment]
Closing as no new information from the user
