### ISSUE TITLE
Media field results in errors

### ISSUE THREAD

**Issue by andrujoh** [strapi/strapi#757]
**Node.js version**:
v9.7.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.11
**Operating system**:
Windows 10 Home

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

 Trying to add new media type field in content type and pressing add new image/media results in blank screen and errors in the browser console.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

Add new field of media in content type builder and try to add content

**What is the expected behavior?**
Ability to add media

**Comment by abdonrd** [comment]
I have the same issue with `v3.0.0-alpha.11`.

**Comment by joja-agency** [comment]
Getting an error on adding new record for entity that contains "Media" field type. 
On clicking "Add new Product":

![screen shot 2018-03-09 at 14 44 57](https://user-images.githubusercontent.com/37141428/37208048-8cd49dd2-23a8-11e8-8a8e-84ea292f6a2a.png)

Full React error:
Element ref was specified as a string (inputFile) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

**Comment by soupette** [comment]
This issue has been fixed in https://github.com/strapi/strapi/pull/760
