### ISSUE TITLE
Multiple `is not` filter don't work

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#7575]
**Describe the bug**
Multiple `is not` filter don't work the way they should work. 
If you use only one `is not` filter, then everything except the used value is hidden (like it should be). But if you use more than one, they don't work. See the following screenshot:
![Screenshot from 2020-08-23 21-44-14](https://user-images.githubusercontent.com/45003352/90987261-dbda0480-e589-11ea-9185-f81e65679705.png)

**Steps to reproduce the behavior**
1. Create some content type with some values
2. Use multiple `is not` filters

**System**
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
Let me poke the frontend team @soupette and @HichamELBSI about this, I believe this will need to be changed to the new $or complex filtering

**Comment by soupette** [comment]
> Let me poke the frontend team @soupette and @HichamELBSI about this, I believe this will need to be changed to the new $or complex filtering

We should also let the ability to use multiple is not filters I think. However, this issue seems to be related to the back-end. 
@petersg83 or @Convly can you take a look at it if you find some time?

**Comment by petersg83** [comment]
It's be because of the implicit $or : https://strapi.io/documentation/v3.x/content-api/parameters.html#implicit-or-operator.
It's possible to avoid that with the front using the `_where`parameter (which was introduced few months ago) : https://strapi.io/documentation/v3.x/content-api/parameters.html#using-where

**Comment by petersg83** [comment]
For example :

`?_where[0][name_ne]=France&_where[1][name_ne]=Italy`

instead of:
`?name_ne=France&name_ne=Italy`

**Comment by derrickmehaffy** [comment]
Should be fixed in v4

**Comment by petersg83** [comment]
I confirm
