### ISSUE TITLE
Can't upload images to content type with media field.

### ISSUE THREAD

**Issue by ajayzestard** [strapi/strapi#758]
**Node.js version**:
  v8.9.3 
**npm version**:
  5.5.1
**Strapi version**:
  3.0.0-alpha.11
**Operating system**:
   Ubuntu 17.04

**Do you want to request a *feature* or report a *bug*?**
  Bug
**What is the current behavior?**
   Created a content type with media field and tried to upload image but content manager screen crashes
**If the current behavior is a bug, please provide the steps to reproduce the problem**
  Create a content type(any name) and add media field type to it. try to add image to it. the content manager screen crashes and shows some error on console.
**What is the expected behavior?**
  User should be able to upload image to content type with media field.

**Comment by abdonrd** [comment]
Duplicate from #757?
