### ISSUE TITLE
Having over 3 000 users will result in a "Payload Too Large" error

### ISSUE THREAD

**Issue by MostafaHassan** [strapi/strapi#7584]
Having over 3000 users will result in a "payload to large" error when changing permissions on the role that the users have.

**Step by step to get the error**
1. Go to Content type builder
2. Create a collection type
3. Make it a relation to users, so the collection has and belongs to many users
4. Now create a script that creates 3000 + users
5.  Go to roles and permissions
6. Select the role that all users now have
7. Make a change to something and press save
8. See error

_PUT https://HOSTURL/users-permissions/roles/ID
Error code: 413 (Payload Too Large)
main.a25116ef.chunk.js:1 Error: Payload Too Large
    at main.a25116ef.chunk.js:1_

**System**

- Node.js version: v 10.15.1
- NPM version: v 6.13.7
- Strapi version: v 3.1.4
- Database: mongodb
- Operating system: debian

**EDIT:**
Creating a collection type is not needed for this error to occur. So you can skip step 1-3.

**Comment by derrickmehaffy** [comment]
@MostafaHassan do you happen to have the script you used so I can test with it?

**Comment by MostafaHassan** [comment]
@derrickmehaffy yes, thanks. 
I created a test script for you to test.  

[payloadErrorScript.zip](https://github.com/strapi/strapi/files/5123436/payloadErrorScript.zip)

Info:
Create a role that has access to:
	 auth/register
create a user with username: automationUser
and password: testPassword
set role to the one that you created

Run script

if you get following error:
{"message":[{"messages":[{"id":"Auth.form.error.ratelimit","message":"Too many attempts, please try again in a minute."}]}]}

Then change “max” in node_modules/strapi-plugin-users-permissions/config/request.json to ex 500


Lastly select the role that has all the users (authenticated) and make a change to the role and press save.
Error!

![error](https://user-images.githubusercontent.com/7292785/91169522-cc68d180-e6d7-11ea-84e8-6e38dabbc186.PNG)

**Comment by soupette** [comment]
@derrickmehaffy we might need to test if this [PR](https://github.com/strapi/strapi/pull/7467) fixes the issue.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy we might need to test if this [PR](https://github.com/strapi/strapi/pull/7467) fixes the issue.

Will do, I'll test it out to confirm the issue, and the PR to see if that fixes. If so I'll set this issue to be closed when the PR is.

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI testing the linked PR does not fix the issue, the Request still stalls out.

**Comment by MostafaHassan** [comment]
@soupette supernice, that was fast :)

**Comment by jyotipawar-sys** [comment]
I am facing similar issue, for  Strapi version: "3.5.4".

I tried updating request.json, middleware but no luck. Can someone help?  I gone through the Documentation, but doesn't help.

**Comment by derrickmehaffy** [comment]
> I am facing similar issue, for Strapi version: "3.5.4".
> 
> I tried updating request.json, middleware but no luck. Can someone help? I gone through the Documentation, but doesn't help.

We no longer use the `request.json` config file, instead you should be modifying/creating a `./config/middleware.js` as per our documentation: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#middlewares

**Comment by jyotipawar-sys** [comment]
@derrickmehaffy I tried with middleware as well. But still no luck. is there any other work around? Thanks for the reply.

**Comment by derrickmehaffy** [comment]
Can you move this topic over to our forum @jyotipawar-sys 

https://forum.strapi.io
