### ISSUE TITLE
Unable to save models with custom fields in strapi content builder

### ISSUE THREAD

**Issue by sam899** [strapi/strapi#7593]
**Describe the bug**
I have collection types with custom fields inside, as per https://strapi.io/documentation/v3.x/plugin-development/frontend-field-api.html#registering-a-new-field

When trying to make a change in the content types builder to a collection type, component, or single type with a custom field in, the model cannot be saved.

The following errors are printed in the console:

```
components[0].attributes.Icon field cannot have keys not specified in the object shape
"components[0].attributes.Icon.type must be one of the following values: media, string, text, richtext, json, enumeration, password, email, integer, biginteger, float, decimal, date, time, datetime, timestamp, boolean, component"
```

This used to work on v3.0.5 of strapi, and is broken since i updated to v3.1.4

**Steps to reproduce the behavior**

1. Create a plugin with a custom field as per https://strapi.io/documentation/v3.x/guides/registering-a-field-in-admin.html#setup
2. Add the custom field type to a collection type
3. Try to make a change in content type builder and save

**Expected behavior**
Custom fields should be supported by content type builder, as they used to be

**System**

Node.js version: v12.18.1
NPM version: 6.14.5
Strapi version: 3.1.4
Database: postgres
Operating system: MacOS

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI I believe currently until the new plugin API/Database refresh is done, actual custom fields won't work unless you are replacing an existing one yeah?

**Comment by soupette** [comment]
@derrickmehaffy currently you can create custom fields, the issue that you will face is that those custom fields cannot be used in the content type builder plugin as the front-end and back-end are not developed. 
However, if you create a custom field in `<ModelName>.settings.json` and you follow the guide provided on how to create a custom field in the admin panel the content manager will be able to use it. The counterpart though, as stated, is that the content type builder will be unusable for this specific content type as it won't pass the validations.

**Comment by sam899** [comment]
Thats @soupette @derrickmehaffy 

Totally understand that we cant manage the specific custom field in content builder, but when I created the custom fields, I used to be able to save other changes to the model (e.g add another non-custom field to that type, or tweak an existing field)

At some point between v3.0.5 and v3.1.4, it looks like there was a regression that no longer lets me manage/save a whole model if it contains a custom field.

**Comment by iksent** [comment]
How can we solve it now?
I have registered a new field with my custom type, and all works fine until I try to save model attributes: I am getting the next error:

```
payload:
error:
contentType.attributes.helper_12: ["contentType.attributes.helper_12 field cannot have keys not specified in the object shape"]
contentType.attributes.helper_12.type: Array(1)
0: "contentType.attributes.helper_12.type must be one of the following values: media, string, text, richtext, json, enumeration, password, email, integer, biginteger, float, decimal, date, time, datetime, timestamp, boolean, uid, component, dynamiczone"
length: 1
```

**Comment by iksent** [comment]
I managed to solve it by using "timestamp" field:

```
  strapi.registerField({ type: "timestamp", Component: Helper });
```

This field is probably can't be added through the admin panel, and Strapi saves model attributes OK with it:

```
    "helper_clinics": {
      "type": "timestamp",
      "private": true
    },
```

OMG, what the hack am I using?!

**Comment by H-Nguyenx** [comment]
After debugging, I've found that you need to add your new type to this file in order for strapi to validate:
![image](https://user-images.githubusercontent.com/33373945/107232840-7e147880-6a54-11eb-9c21-1a1749c6a4ae.png)
Add your new type to the VALID_TYPES array

Or
![image](https://user-images.githubusercontent.com/33373945/107232964-a2705500-6a54-11eb-8676-a0ebc3642221.png)
Add your new type to the DEFAULT_TYPES array

**Comment by Quocnamit** [comment]
> After debugging, I've found that you need to add your new type to this file in order for strapi to validate:
> ![image](https://user-images.githubusercontent.com/33373945/107232840-7e147880-6a54-11eb-9c21-1a1749c6a4ae.png)
> Add your new type to the VALID_TYPES array
> 
> Or
> ![image](https://user-images.githubusercontent.com/33373945/107232964-a2705500-6a54-11eb-8676-a0ebc3642221.png)
> Add your new type to the DEFAULT_TYPES array

Add in node_modules ? so how can you keep the content every time you build on server ?

**Comment by derrickmehaffy** [comment]
Extensions system: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#how-do-i-customize-a-plugin

**Comment by derrickmehaffy** [comment]
It's just `extensions/content-type-builder/services/constants.js` you exclude the `strapi-plugin-` part

**Comment by tablufc88** [comment]
Spent the last couple of hours trying to implement the [colorpicker](https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms) but the value isn't posting to my pg database. Everything else works fine on the front end with no errors.

Been reading through the docs & also tried registering the plugin in the initializer but this didn't work either. If anyone could tell me if I'm missing something it would be appreciated as it seems like I'm missing something simple!

The only change I have made worth noting is the columnType to text rather than longText:

`    "color": {
      "type": "colorpicker",
      "columnType": "text"
    }`
    
    
Running 3.6.5 (node v14.17.0)

**Comment by mandi05** [comment]
I finally got my content builder to save my Custom-Type.

I believe the `type` validation is triggered by `strapi-plugin-content-type-builder/controllers/ContentTypes.js`.  I followed all requires by relative path and copied them into my `extensions/content-type-builder` directory. 

These are the contents of my `extensions/content-type-builder`:
![Screen Shot 2021-08-25 at 6 26 46 AM](https://user-images.githubusercontent.com/6452865/130782615-90f5bd99-e4f2-4868-83c7-5bffb526fb4b.png)

I think this directory structure is the minimum required to extend this functionality. Make sure to copy the file location, file name and file contents correctly for all files, you can get them from: https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-type-builder.


Then, to actually get your `content-type` to save, modify the `VALID_TYPES` const from `extensions/content-type-builder/controllers/validation/content-type.js` to something like:

```
/**
 * Allowed types
 */
const VALID_TYPES = [...DEFAULT_TYPES, 'uid', 'component', 'dynamiczone', '<your-custom-type>'];
```

### **NOTE**
You'll need to re-copy these files every time the Strapi team releases a new version of them. 

I might build a script to do this automatically later.

**Comment by ssyberg** [comment]
Huh, followed all the instructions above, still can't save anything:
![image](https://user-images.githubusercontent.com/1661046/143161047-971cc855-3eb5-40c2-9be2-6ab7d2f2865a.png)

![image](https://user-images.githubusercontent.com/1661046/143161060-9f5c22fa-335d-440b-a9e3-d6ad3100b11e.png)

**Comment by derrickmehaffy** [comment]
If you are using custom fields, it's no longer possible to use the Content-Type Builder, you will have to manage the model through the json files until we add custom fields.

**Comment by ssyberg** [comment]
> If you are using custom fields, it's no longer possible to use the Content-Type Builder, you will have to manage the model through the json files until we add custom fields.

Got it, so what is currently the best way to add something like a color picker to v4?

**Comment by digitaledge-git** [comment]
Im even trying to add a color picker to v4... got the component shown so far (manually added to the schema). But the edited data is lost after saving. Some advice (or more detailed docs) would be great

**Comment by PatrykBuniX** [comment]
I'm using v4 (4.0.0) and have the same issue. I've created custom field using `schema.json` file. I'm able to change its value but after saving the entry, value of the field is `null`. Has anybody found a solution for that in v4?

**Comment by katyrumble** [comment]
> Im even trying to add a color picker to v4... got the component shown so far (manually added to the schema). But the edited data is lost after saving. Some advice (or more detailed docs) would be great

I'm experiencing the same issue [v4]. One thing I noticed was that after I made the schema changes to include my custom field type, the database didn't populate a new column for the new attribute. This seems to be a legitimate bug in v4.
