### ISSUE TITLE
Dynamic Components cannot have the enum fields with same names

### ISSUE THREAD

**Issue by lodisy** [strapi/strapi#7595]
**Describe the bug**

Components cannot have the enum fields with the same name

**Steps to reproduce the behavior**

1. Go to components, create new component named Gallery
2. Add fields images(media) and template(enum)
3. Create another component called Slider with the same fields
4. Assin them to the post content type as dynamic components
5. Add some data, write query in the playground
6. Shows error

```
[
  {
    message: 'Fields "template" conflict because they return conflicting types ENUM_COMPONENTMEDIASLIDER_TEMPLATE and ENUM_COMPONENTMEDIAGALLERY_TEMPLATE. Use different aliases on the fields to fetch both if this was intentional.',
    locations: [ [Object], [Object] ],
    extensions: { code: 'GRAPHQL_VALIDATION_FAILED', exception: [Object] }
  }
]
```

**Expected behavior**
There shall be no confilts as they belong to different componets
**Screenshots**

![Screenshot 2020-08-25 at 17 33 22](https://user-images.githubusercontent.com/8101584/91195539-62f9ba80-e6f9-11ea-91ea-6aaad2f9b50a.jpg)

**Code snippets**
# Write your query or mutation here
```
{
  post(id: 21) {
    content {
      ... on ComponentTextParagraph {
        __typename
        id
        paragraph
      }
      ... on ComponentMediaSlider {
        __typename
        id
        images {
          url
          caption
        }
        source {
          name
          link
        }
        theme _# here I have to change the field name from template to theme_ 
      }
      ... on ComponentMediaGallery {
        __typename
        id
        images {
          url
          caption
        }
        source {
          name
          link
        }
        template
      }
    }
  }
}
```

**System**

- Node.js version: 14.4.0
- NPM version: 6.14.7
- Strapi version: 3.1.4
- Database: SQLite
- Operating system: macOS 10.15.5

**Additional context**

**Comment by derrickmehaffy** [comment]
@lodisy We are currently looking into this internally and we will get back to you. Thanks!

**Comment by sebqq** [comment]
I'm also encountering this issue. An ugly hack to use for now is to use gql aliases:

```gql
... on Component1 {
        __typename
        richText
    }
... on Component2 {
        __typename
        richText      // --> this causes the error 
    }
```

to 

```gql
... on Component1 {
        __typename
        richText
    }
... on Component2 {
        __typename
        secondRichText: richText      // --> really ugly hack to make it work....
    }
```

**Comment by derrickmehaffy** [comment]
Going to close this one in favor of: https://github.com/strapi/strapi/issues/10034
