### ISSUE TITLE
[API] Nested filtering

### ISSUE THREAD

**Issue by maximilianofried** [strapi/strapi#7596]
Hello i want to know what is the way to do an api request using nested filter.

For example my Article object look like this:

`[
    {
        "status": "published",
        "country": "germany",
        "categories": [
            {
                "_id": "5f3a57a84916ca0337385653",
                "name": "Start page",
                "createdAt": "2020-08-17T10:10:48.135Z",
                "updatedAt": "2020-08-17T10:10:48.135Z",
                "__v": 0,
                "id": "5f3a57a84916ca0337385653"
            },
            {
                "_id": "5f2930774916ca0337385630",
                "name": "Science",
                "createdAt": "2020-08-04T09:55:03.068Z",
                "updatedAt": "2020-08-20T13:59:03.455Z",
                "__v": 0,
                "link": "/science",
                "id": "5f2930774916ca0337385630"
            }
]`

How can i build my url? Somethink like

http://myurl.com/articles?categories[name]=Art

**Comment by derrickmehaffy** [comment]
Hi @maximilianofried yes we do support deep filtering (though usage of it is advised against as it doesn't have very good performance at the moment)

http://myurl.com/articles?categories.name=Art

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
