### ISSUE TITLE
Unable to create list of numeric values. 

### ISSUE THREAD

**Issue by ivanji** [strapi/strapi#7600]
**Describe the bug**
Unable to create a list of numeric values. Enum fields don't allow numbers as values, which is the only way of creating fields with a list of values

**Steps to reproduce the behavior**

1. Add enum field to a collection type
2. insert digits as values such as 
```
1
2
3
```
3. Attempt to save the field

4. See error: **The value does not match the regex.**

**Expected behavior**
Enums should be allowed to have numeric values OR create new field type to allow this. Alternatively, please explain a way to accomplish this.

**System**

- Node.js version: 12.8.2
- NPM version: 6.14.5
- Strapi version: 3.1.3
- Database: MongoDB Atlas
- Operating system: MacOSx

**Comment by derrickmehaffy** [comment]
Hi @ivanji there has been a very long discussion on this topic (here: https://github.com/strapi/strapi/discussions/4780) and for now we don't have any plans to allow this as it would break usage of GraphQL. We will continue the discussion and likely try to come up with a decision sometime later this year or early next year. For the moment I would suggest you use JSON type to save an array of values or you can use a manyWay relation (bit overkill for just a few integers).

**Comment by ivanji** [comment]
Thanks mate for the fast reply and recommendation. I'll keep a watch the other issue.

**Comment by TheMangoTrain** [comment]
Any movement on this? The linked discussion is a 404 now.
I don't use GraphQL at all, but hitting this limitation.

**Comment by drashtikheni** [comment]
> Any movement on this? The linked discussion is a 404 now. I don't use GraphQL at all, but hitting this limitation.

me too.
