### ISSUE TITLE
Can't place test files in paths under api/

### ISSUE THREAD

**Issue by jasonprado** [strapi/strapi#7604]
**Describe the bug**
When you place a test file, e.g. `my-object.test.js`, in the application source tree at a location like `api/my-object/services/__tests__/my-object.test.js`, the code in `my-object.test.js` is loaded when Strapi server starts.

One example of a glob that loads all JS files, including in directories called `__tests__` is here: https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/load-apis.js#L18

**Steps to reproduce the behavior**

1. Create a collection type called `my-object`
2. Place a test file at ``api/my-object/services/__tests__/my-object.test.js`

**Expected behavior**
The test file is ignored by the production server

**System**

- Node.js version: v12
- Strapi version: 3.0.5
- Database: N/A
- Operating system: N/A

**Comment by derrickmehaffy** [comment]
I will ping @alexandrebodin and @petersg83 about this as we should probably set some default ignores here.

**Comment by alexandrebodin** [comment]
Hello, we cannot realy force certain patterns to be ignored as some users might have exceptions (even if not good practices) and will want to load files in a test folder. Something we can do is add an option for the glob patterns that load files. this would go well with the current discussion about typescript support

**Comment by derrickmehaffy** [comment]
While we don't allow directly a `test` folder within the API folder directly you can add a test folder inside of a content-type or a test folder under src:

![image](https://user-images.githubusercontent.com/8593673/230126930-ccb290e8-1654-4b27-b5aa-49e2a823ba40.png)

Marking this as closed as we do have valid workarounds
