### ISSUE TITLE
'SQLITE_READONLY: attempt to write a readonly database' when I try to edit or add something In Strapi Admin

### ISSUE THREAD

**Issue by FiddlePlus** [strapi/strapi#7608]
This error only shows up in "production" mode. Meaning, after this command - 'NODE_ENV=production npm run build'
And because of it, I can't edit or add new "projects" (or "categories")
If I run Strapi in "develop" mode, this issue goes away. 

![90985205-db466b80-e593-11ea-89d5-a557fde786bc](https://user-images.githubusercontent.com/43990716/91285675-f4733600-e7a6-11ea-9673-2c451deea147.png)

Could it be issue with the ssl? Because I've noticed when I run strapi in dev env (and edit stuff) my next.js app (for front-end) isn't accessible through assigned url. I don't have ssl installed yet

**Comment by joelbqz** [comment]
Hello, this error happened to me, in my case, it was because the current user server didn't have correct permissions to edit the file.

https://stackoverflow.com/questions/1518729/change-sqlite-database-mode-to-read-write

**Comment by derrickmehaffy** [comment]
The response by @joelbqz is most likely correct, but for additional troubleshooting, please properly fill out our required bug report template.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
