### ISSUE TITLE
Unable to save model on Content Type Builder after adding index option to model field

### ISSUE THREAD

**Issue by gimoteco** [strapi/strapi#7617]
**Describe the bug**
I'm no able to save a model through content type builder after I added a JSON field with an index with "2dsphere" value (I'm using mongoose connector).

**Steps to reproduce the behavior**

1. Create a JSON field in some model through admin UI
2. Edit the `ModelName.settings.json` and add `"index":  "2dsphere"` to the previously created field
3. Restart the server
4. Try to add another field (any kind)
5. An error message should appear on screen 

**Expected behavior**
Save without problems

**Screenshots**

**Code snippets**
Here is a repo with this problem.
https://github.com/gimoteco/strapi-bug-report

**System**

- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.1.4
- Database: MongoDB
- Operating system: MacOS 10.15.6

**Additional context**
I tried to remove the index option and add a new index through a migration but when strapi starts it removes the previously created index.

**Comment by derrickmehaffy** [comment]
@gimoteco I'll leave this open, but in the future please ensure you follow our [Contributor guidelines for issues](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue) and use the bug report template.

**Comment by gimoteco** [comment]
Thank you for the feedback, I updated the issue text

**Comment by derrickmehaffy** [comment]
Fixed in Strapi v4 but we do have another bug with the option deleting and recreating the indexes in: https://github.com/strapi/strapi/issues/13654

Gonna mark this one as closed (though we do need to document this experimental feature)
