### ISSUE TITLE
User-API should never expose password hashes

### ISSUE THREAD

**Issue by msgeissler** [strapi/strapi#762]
**Node.js version**:
8.9.4
**Strapi version**:
3.0.0-alpha.10.1

**Do you want to request a *feature* or report a *bug*?**
security risk
**What is the current behavior?**
If a user-object is returned by the API it includes **all** fields, including the **password hash**.
**If the current behavior is a bug, please provide the steps to reproduce the problem**
Follow the steps defined in the [blog tutorial](https://hackernoon.com/building-a-static-blog-using-gatsby-and-strapi-8b5acfc82ad8) and access the articles.
**What is the expected behavior?**
Password hashes are not exposed.

A malicious user could use the hash and rainbow tables to find the original password. Because the API is exposing this data itself, the data is "leaked by design", so no attack on the API or database is necessary (monitoring for malicious access is very hard).

If this is not considered a security risk, can you please point me in the right direction on how this can be overriden by e.g. a plugin?

**Comment by lauriejim** [comment]
Hi @msgeissler . 
@Aurelsicoko make a mask system to hide sensitive data https://github.com/strapi/strapi/pull/613
We break it in our last release. So it's in our backlogs to fix it.

**Comment by msgeissler** [comment]
Ah awesome. I probably used the wrong search terms so I didn't find the original issue.

**Comment by Aurelsicoko** [comment]
It seems fixed 👍 

I tried to reproduce but the hashes password are never exposed as you described. If it happens again, please re-open the issue!
