### ISSUE TITLE
what's the point of authorizedKeys?

### ISSUE THREAD

**Issue by neverbe10** [strapi/strapi#7632]
https://github.com/strapi/strapi/blob/48a818041ece8930202b43d8327ff2c27e4c5870/packages/strapi-plugin-users-permissions/controllers/validation/email-template.js#L6

I want to pass in USER.name or USER.firstname in the email template and I think it's perfectly acceptable.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by renanblamas** [comment]
I had the same problem with the authorizedKeys on the Reset Password email template. I needed to send another user attribute on the email and the Strapi Panel was refusing with the error "Invalid template".
So I had to duplicate the User-Permisions and the email-template inside de validation folder to customize them and allow another user attribute on the email.
