### ISSUE TITLE
Deep Filtering Error Response "$in requires an array as a second argument, found: missing"

### ISSUE THREAD

**Issue by sebastianjung** [strapi/strapi#7637]
**Describe the bug**

When deep filter querying the users which have a many to many to my custom UserPermissions model via GraphQL Playground, i get "$in requires an array as a second argument, found: missing" as response from the server.

**Steps to reproduce the behavior**

EDIT:
Also throws error on REST-Endpoint when doing 
``axios.get(`users?userRoles.uid=supereditor`);``
so following graphql steps might be skipped.

1. Create content type "UserRole" with field "name" of type String and many-to-many relationship to user.
![image](https://user-images.githubusercontent.com/17472892/91587933-ba956180-e957-11ea-807d-ca0f374519e0.png)

3. (optional?) create some users. Some with Roles assigned and some don't

4. install strapi graphql plugin

5. open /graphql playground

6. query something like this (doesn't matter really what the name of the role is or if one exists)

```
{
  users (where: { userRoles: { name: "moderator"}}){
    id
    username
  }
}
```

**Expected behavior**
Get users with role of moderator.

**System**

- Node: 10.15.1
- NPM version: 6.6.0
- Strapi version: 3.1.4
- Database: MongoDB 4.0.11 win32 x68
- Operating system: Windows 10

Any help is very much appreciated!

**Comment by derrickmehaffy** [comment]
Tested on MySQL (screen below), PostgreSQL, and MongoDB and could not reproduce the issue.

![image](https://user-images.githubusercontent.com/8593673/91750024-3c170a80-eb77-11ea-8157-d9a2cbd111b2.png)

`./api/user-role/models/user-role.settings.json`

```json
{
  "kind": "collectionType",
  "collectionName": "user_roles",
  "info": {
    "name": "userRole"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "uid": {
      "type": "uid",
      "targetField": "name"
    },
    "users": {
      "via": "user_roles",
      "plugin": "users-permissions",
      "collection": "user"
    }
  }
}
```

`./extensions/users-permissions/models/User.settings.json`

```json
{
  "kind": "collectionType",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "user_roles": {
      "collection": "user-role",
      "via": "users",
      "dominant": true
    }
  }
}
```

**Comment by sebastianjung** [comment]
@derrickmehaffy Thanks for investigating! I can not reproduce it myself with a fresh strapi project. Seems to be some error in my working project. I'll let you guys know what it was if i ever find out.

For now i close this issue. Thanks!

**Comment by derrickmehaffy** [comment]
Thank you!

**Comment by sethpkendall** [comment]
I was getting this error because I had changed a relation field from a "Has and belongs to many" to "Has many." 
I needed to clear out the old records to fix the issue. If one had data that could not be simply deleted like I did you probably just need to update the existing records to match the changed field type's expected data structure.

**Comment by sebastianjung** [comment]
@sethpkendall 
Thank you for responding!

Indeed i had old users not having at least an empty array on the user roles field which caused the error.

Deleting those records fixed the issue! 

Now it looks like this and it works:

![image](https://user-images.githubusercontent.com/17472892/93326766-a12a5b80-f819-11ea-992b-b19f7173f4be.png)

Thanks a lot!

**Comment by tbanys** [comment]
This problem only occurs for MongoDB databases when you update relationships between content types.

When you update relationship from any other type (One-to-One, One-to-Many etc.) to **Many-to-Many,** then old database records of updated content type has to have atleast an empty array of this relational field.

Also, behind the scenes, for NoSQL databases Strapi adds **dominant** key to relational fields. (The dominant key defines which table/collection should store the array that defines the relationship) So, only this collection with dominant key, has to have atleast empty array for relation field.

Summary: for NoSQL databases all Many-to-Many relational fields, which are dominant in collection, has to have atleast empty array as a value. If one of the fields, which are dominant, won't be in the document, then you will always get "$in requires an array as a second argument, found: missing" error, even if you are trying to deep filter by different dominant field in collection.

**Comment by derrickmehaffy** [comment]
@tbanys can you create a new bug report to lay this issue out?
