### ISSUE TITLE
Display relations fileds in content manager list

### ISSUE THREAD

**Issue by ajayzestard** [strapi/strapi#764]
**Node.js version**:
  v8.9.3 
**npm version**:
  5.5.1
**Strapi version**:
  3.0.0-alpha.11.1
**Operating system**:
   Ubuntu 17.04

**Do you want to request a *feature* or report a *bug*?**
  Bug

**What is the current behavior?**
   When you create a content type with media field and it lets you add images in that content type. But on content manager screen, field name(column name) does not appear of media type. All other field type like string,email,date shows. 

![screenshot from 2018-03-10 12-06-01](https://user-images.githubusercontent.com/35491379/37239115-85513df0-245b-11e8-8427-c1effa70cff1.png)

![screenshot from 2018-03-10 12-06-10](https://user-images.githubusercontent.com/35491379/37239117-8ae3046a-245b-11e8-8f37-b973ae12da5e.png)

![screenshot from 2018-03-10 12-09-09](https://user-images.githubusercontent.com/35491379/37239136-e19e8162-245b-11e8-9954-24cd5bd21fa6.png)

**If the current behavior is a bug, please provide the steps to reproduce the problem**
  Create content type with media field and open content manager of that content type. We cannot fieldname in table.

**What is the expected behavior?**
  Fieldname should be displayed.

**Comment by lauriejim** [comment]
We don't display relations on this table. Media field is a polymorphic relation with File content type.

**Comment by soupette** [comment]
@lauriejim what should I do then?

**Comment by lauriejim** [comment]
Actually nothing. It's not in our roadmap to implement relationships display in this list.

**Comment by geosigno** [comment]
Is this still not planned? I think this could very useful to be able to filtering items on manager list depending of relational fields.

I give you an example:
I have a "course" content type. This "course" has a relation with a "Level" content type. Currently I have no way to find which course has which level on the manager list. Nor filtering courses that are in the level 2 for example.

**Comment by derrickmehaffy** [comment]
https://portal.productboard.com/strapi/1-public-roadmap/c/49-display-relational-field-in-list-view

**Comment by geosigno** [comment]
nice, thanks (y)

**Comment by baumannalexj** [comment]
This feature is in high demand! We are using Strapi to decompose our monolithic CMS app. This feature would ensure a smooth transition and many use cases.

**Comment by derrickmehaffy** [comment]
Please see the following RFC requests:

https://github.com/strapi/rfcs/issues/8
https://github.com/strapi/rfcs/issues/7
