### ISSUE TITLE
Strapi admin user and data is reseted after heroku dynos are reset

### ISSUE THREAD

**Issue by AbdallahAbis** [strapi/strapi#7641]
**Describe the bug**
I have created a new project using `--quickstart` flag, after finishing the project locally I deployed it to **Heroku** using `PostgreSQL`, and everything is good, I can create a new user and add content and media, but once the dynos are reset on Heroku the user and data are lost, and **I have to re-register and add the content again**.

**Steps to reproduce the behavior**

1. I created a new Strapi project using yarn create my-project --quickstart.
2. I registered and added content types, changed user permissions ...
3. I followed the instructions here to deploy the project on Heroku [using PostgreSQL](https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html).
4. I added Heroku Postgres Addon and configured the environment variables.
5. I updated the database.json file and added pg dependency.
6. I committed changes and pushed the project to Heroku and opened it without any problem.
7. after Heroku dynos are reset/ app goes to sleep, the admin user and all data are lost, and I have to recreate a new user and add new content.

**Expected behavior**
the user and content should remain the same even after the dynos are reset.

**Screenshots**
### Heroku Vars
![Heroku](https://i.imgur.com/Qfhau6O.png  "Heroku")

### Database Credentials
![Database Credentials](https://i.imgur.com/wl1dQsg.png "Database Credentials")

### Strapi register again
![ Strapi register again](https://i.imgur.com/bzzq02f.png " Strapi register again")

**Code snippets**
You can check the code here [on GitHub](https://github.com/AbdallahAbis/Shopse-cms)

**System**

- Node.js version: v14.3.0
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: MacOS Catalina 10.15.6

**Comment by derrickmehaffy** [comment]
Please see the updated documentation, the guide you are referencing is for, the now unsupported, beta version.

https://strapi.io/documentation/v3.x/deployment/heroku.html#heroku

Going to mark this as closed for now but reply if you have more issues.

Thanks!

**Comment by NLeRoy917** [comment]
I'm having this issue as well after following the above docs to set up my Heroku production environment. If I re-register all the content-types are still there, but why must I re-register each time I deploy? Is there a way to avoid this?

**Comment by derrickmehaffy** [comment]
> I'm having this issue as well after following the above docs to set up my Heroku production environment. If I re-register all the content-types are still there, but why must I re-register each time I deploy? Is there a way to avoid this?

You likely aren't passing the `NODE_ENV` variable with the value of `production` meaning it's starting the application in the `development` environment => thus SQLite and not PostgreSQL

**Comment by NLeRoy917** [comment]
I've got `NODE_ENV` set to production on Heroku... I shouldn't do this locally right?

**Comment by derrickmehaffy** [comment]
No just remotely, excluding any private details can you give the output of `heroku config` (if you are using the Heroku CLI), just be sure to blur out any private information.

**Comment by NLeRoy917** [comment]
```
DATABASE_HOST:     ******
DATABASE_NAME:    ******
DATABASE_PASSWORD: ******
DATABASE_PORT:     ******
DATABASE_URL:      ***********
DATABASE_USERNAME: *******
NODE_ENV:          production
```

**Comment by derrickmehaffy** [comment]
It looks like you are using the old configuration system, can you check https://strapi.io/documentation/v3.x/deployment/heroku.html#_3-set-database-variables-automatically
and
https://strapi.io/documentation/v3.x/deployment/heroku.html#_4-create-your-heroku-database-config-file-for-production

**Comment by NLeRoy917** [comment]
Okay - I was writing out a long post about my process only to realize I made a dumb error and had my directory set up as:
`./config/env/production/database.js/database.js` instead of `./config/env/production/database.js`...

I guess this is what I get for working straight out of the terminal and not in VSCode.

**Comment by derrickmehaffy** [comment]
> Okay - I was writing out a long post about my process only to realize I made a dumb error and had my directory set up as:
> `./config/env/production/database.js/database.js` instead of `./config/env/production/database.js`...
> 
> I guess this is what I get for working straight out of the terminal and not in VSCode.

Hahahaha, it's all good, it happens to the best of us. I take it you got it all working?

**Comment by NLeRoy917** [comment]
**The re-register issue is gone, yes!** So that's good. The only thing that is off right now is that when I add content locally - it isn't reflected in production. I assume content-types are defined outside the `./tmp/data.db`, but the content itself is stored there?

I tried to solve this myself and point the development server at the postgre db by editing `./config/database.js` to contain: 
```
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: config.host,
        port: config.port,
        database: config.database,
        username: config.user,
        password: config.password,
      },
      options: {
        ssl: false,
      },
    },
  },
});
```
However, when I do this I cant start the development server and get this error:

```
Error while running command develop: Could not load js config file /Users/nathanleroy/Documents/projects.nosync/nathanleroy-io-cms/config/database.js: Cannot read property 'charAt' of undefined
```

It's not a critical issue, but it would be nice to have both the development server and the production server reflect the content identically just like they do the content types.

I know this is now beyond the scope of this issue - so I can open another one if need be.

**Comment by derrickmehaffy** [comment]
@NLeRoy917 it would probably be better to discuss this on a forum thread and not a github issue: https://forum.strapi.io/
