### ISSUE TITLE
User password added/updated via admin panel not hashed

### ISSUE THREAD

**Issue by dorelljames** [strapi/strapi#765]
**Node.js version**: v.8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: OSX macOS Sierra 10.12.6

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
Using the admin panel, any added/updated user sets the password as plain string and not hashed. This makes it impossible to authenticate. Creating the user via API call though do hash the password well and works without problem.

**If the current behavior is a bug, please provide the steps to reproduce the problem** 
1. Login to admin panel.
2. Click **Users** > **Add New User**.
3. Input necessary fields and **Save**
4. OBSERVED.

**What is the expected behavior?**
The password field should be hashed just like how it's via API call at https://strapi.io/documentation/guides/authentication.html#usage

See screenshot below:
![screen shot 2018-03-10 at 8 11 10 pm](https://user-images.githubusercontent.com/977413/37242150-5083bbe0-249f-11e8-86d1-a400f3a01f93.png)

**Comment by lauriejim** [comment]
It's fixe on master follow the next release.

**Comment by tapvt** [comment]
@lauriejim, is this resolved on `alpha.11.2`?

Just upgraded my staging server to that version and still encountering the plaintext password when I query the DB directly, so I suppose it is not?

**Comment by lauriejim** [comment]
Did you update your `users-permission` plugin following the migration guide (in the documentation) ?
