### ISSUE TITLE
Provide organization unit management feature

### ISSUE THREAD

**Issue by Goxiaoy** [strapi/strapi#7652]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Provide organization unit management feature
1. manage organization unit as tree structure, like 
```
-Product team
  -Product A team
  -Prodcut B team
-Engineer team
  -Engineer A team
  -Engineer B team
```

2. Assign users to this organization unit

**Comment by dtrikannad** [comment]
How many tiers can your plugin support? 

Given your example above, can it support one more tier like below? 

-Business Unit 
  -Product Team
     -Product A Team
        -Product A Member 1
        -Product A Member 2

**Comment by Goxiaoy** [comment]
> How many tiers can your plugin support?
> 
> Given your example above, can it support one more tier like below?
> 
> -Business Unit
> -Product Team
> -Product A Team
> -Product A Member 1
> -Product A Member 2

There is not limitation currently, but you may get performance issue especially  when you move a parent node which have  deep children. Because the plugin use pre-calculated 'code' to achieve query like 'find all children of one node'

**Comment by lauriejim** [comment]
But here is the plugin you created for that @Goxiaoy - https://github.com/Goxiaoy/strapi-plugin-users-organizationunits
