### ISSUE TITLE
 A limit of 20 items to choose from for relation

### ISSUE THREAD

**Issue by ulaDEVEL** [strapi/strapi#766]
**Node.js version**:
8.10.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.11.1
**Operating system**:
Ubuntu 16.04

**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When i add new content which have setup relation, stapi fetch only 20 items (look at request):
http://localhost:1337/content-manager/explorer/configuratorsteps/?limit=20&source=content-manager
**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Add new model "A".
2. Add more than 20 items to model "A".
3. Add new model "B" with many-to-many relation "A".
4. Add new item to model "B".
5. Click "select..." on the right side, see you can only choose from 20 elements on list.
**What is the expected behavior?**
There should be all elements when you click "select..."

**Comment by soupette** [comment]
https://github.com/strapi/strapi/pull/974
