### ISSUE TITLE
Autofill overwrites fields when editing users.

### ISSUE THREAD

**Issue by votemike** [strapi/strapi#7666]
**Describe the bug**
Chrome Autofill overwrites the username and password when editing a user.

**Steps to reproduce the behavior**

1. Login to the Strapi admin panel using Chrome. Get Chrome to save your username and password.
2. Go to /admin/settings/users and edit a user
3. Notice that the Username and Password fields are prefilled with your information.

**Expected behavior**
I go in to edit a user and it is **their** username in the Username field and an empty Password field.

**System**

- Strapi version: 3.1.2
- Operating system: Mac OS and Chrome

**Additional context**
Could possibly be a problem in other browsers too.

**Comment by derrickmehaffy** [comment]
Can you please confirm this issue on the latest release `v3.1.4` Thanks!

**Comment by votemike** [comment]
> Can you please confirm this issue on the latest release `v3.1.4` Thanks!

It seems to still happen in 3.1.4
