### ISSUE TITLE
Error 500 on upload files related to an entry

### ISSUE THREAD

**Issue by WilliamTraoreee** [strapi/strapi#7667]
Hello,

I have on issue when I want upload a file related to an entry.
No problem for upload a media but when I specified the field value, I have an error 500.

I'm using Angular 9 and Strapi v3.0.0

This is how I format my data 

``` const formData = new FormData();
    formData.set('files', image);
    formData.set('refId', result.id);
    formData.set('ref', 'communities');
    formData.set('field', 'Image'); 
```

And how I send data 

```
const config = {
      headers: new HttpHeaders({
        Authorization: 'Bearer ' + token
      })
    };
return this.http.post(`${environment.apiUrl}/upload`, formData, config);
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
