### ISSUE TITLE
Error when using mysql database NO_ZERO_DATE

### ISSUE THREAD

**Issue by adispartadev** [strapi/strapi#767]
**Node.js version**: v8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.10.1

**Operating system**: ubuntu 16.04 LTS

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Some bug on ubuntu when I user mysql as database. 

**If the current behavior is a bug, please provide the steps to reproduce the problem**

When I start the project for the first time, I know strapi creating new tabel in my database, but it give an error, the sql query didn't run perfectly.
```
TABLE `core_store` DOESN'T EXIST

CREATE TABLE `core_store` (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  key text,
  value text,
  environment text,
  type text,
  tag text
);

ALTER TABLE `core_store` ADD COLUMN `parent` integer, ADD FOREIGN KEY (`parent`) REFERENCES `core_store`(`id`);
```

I think the problem is in your sql field name, like the field **key** is a mysql reverse word so it didn't work on my machine. I think your sql query must be like this:

```
CREATE TABLE `core_store` (
  `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 ` ke` text,
  `value` text,
 `environment` text,
  `type` text,
  `tag` text
);

ALTER TABLE `core_store` ADD COLUMN `parent` integer, ADD FOREIGN KEY (`parent`) REFERENCES `core_store`(`id`);
```

I try to run your sql query manual from phpmyadmin and after the tabel created and I run the strapi project again, it also give and warning like this : 

```

(node:9451) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: insert into `core_store` (`environment`, `key`, `tag`, `type`, `value`) values ('', 'plugin_users-permissions_email', '', 'object', '{\"reset_password\":{\"display\":\"Email.template.reset_password\",\"icon\":\"refresh\",\"options\":{\"from\":{\"name\":\"Administration Panel\",\"email\":\"no-reply@strapi.io\"},\"response_email\":\"\",\"object\":\"­Reset password 🔑 \",\"message\":\"<p>We heard that you lost your password. Sorry about that!</p>\\n\\n<p>But don’t worry! You can use the following link to reset your password:</p>\\n\\n<p><%= URL %>?code=<%= TOKEN %></p>\\n\\n<p>Thanks.</p>\"}}}') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x94\x91 "...' for column 'value' at row 1
(node:9451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
WARN (9451 on spartan-X441UV): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (9451 on spartan-X441UV): Perhaps you forgot to call it?


```

And strapi freeze after that warning message

**Comment by lauriejim** [comment]
Hi @adispartadev thank you for this issue. It's true, we have to use ` for key.

**Comment by adispartadev** [comment]
And how about the second bug? this warning message

```
(node:9451) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: insert into `core_store` (`environment`, `key`, `tag`, `type`, `value`) values ('', 'plugin_users-permissions_email', '', 'object', '{\"reset_password\":{\"display\":\"Email.template.reset_password\",\"icon\":\"refresh\",\"options\":{\"from\":{\"name\":\"Administration Panel\",\"email\":\"no-reply@strapi.io\"},\"response_email\":\"\",\"object\":\"­Reset password 🔑 \",\"message\":\"<p>We heard that you lost your password. Sorry about that!</p>\\n\\n<p>But don’t worry! You can use the following link to reset your password:</p>\\n\\n<p><%= URL %>?code=<%= TOKEN %></p>\\n\\n<p>Thanks.</p>\"}}}') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x94\x91 "...' for column 'value' at row 1
(node:9451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
WARN (9451 on spartan-X441UV): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (9451 on spartan-X441UV): Perhaps you forgot to call it?
```

**Comment by jobn123** [comment]
i got this error

```
(node:22986) UnhandledPromiseRejectionWarning: Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x94\x91 "...' for column 'value' at row 1
```

**Comment by piere129** [comment]
I found the solution:

I think the reason it gives you the` Incorrect string value: '\xF0\x9F\x94\x91 "...' for column 'value' at row 1` error is because strapi is configured to use UTF-8, however the 🔑 icon is not supported in UTF-8. I deleted the 🔑 icon in the errormessage (located at .\plugins\users-permissions\config\functions\bootstrap.js). After that it worked!

**Comment by sapkra** [comment]
Is there a pull-request for it?

**Comment by pakulin** [comment]
3.0.0-alpha.11.2
@lauriejim same error with mysql

also would be nice to add migration command and not throw at people SQL in console
and in _new_ command what the purpose of asking db connection params if it then asks to run queries? Db init should be moved to separate command with db create query and not stop project creation

**Comment by lauriejim** [comment]
Hi @pakulin can you fix it and submit a PR as did @sapkra for previous issue.
Tank you :D

**Comment by piere129** [comment]
Can we re-open this issue until the fix is in master branch?

**Comment by lauriejim** [comment]
Fixed here https://github.com/strapi/strapi/pull/969
