### ISSUE TITLE
Bootstrap function in plugin "users-permissions" failed

### ISSUE THREAD

**Issue by adrianwix** [strapi/strapi#7671]
Hi, I am trying to do Unit Testing in Strapi.  I am following the documentation but the test are not running. When trying to run the tests I get the following errors

```
[2020-09-01T10:46:51.491Z] error Bootstrap function in plugin "users-permissions" failed
[2020-09-01T10:46:51.492Z] error undefined
  ●  process.exit called with "1"

       7 |     if (!instance) {
       8 |         /** the following code in copied from `./node_modules/strapi/lib/Strapi.js` */
    >  9 |         await Strapi().load()
         |         ^
      10 |         instance = strapi // strapi is global now
      11 |         await instance.app
      12 |             .use(instance.router.routes()) // populate KOA routes

      at Strapi.stop (node_modules/strapi/lib/Strapi.js:263:13)
      at node_modules/strapi/lib/Strapi.js:391:16
          at async Promise.all (index 4)
      at Strapi.runBootstrapFunctions (node_modules/strapi/lib/Strapi.js:394:5)
      at Strapi.load (node_modules/strapi/lib/Strapi.js:326:5)
      at setupStrapi (tests/helpers/strapi.js:9:9)
      at Object.<anonymous> (tests/app.test.js:6:5)

Process finished with exit code 1
```

**Steps to reproduce the behavior**

1. Install Strapi
2. Follow the docs for unit testing until [here](https://strapi.io/documentation/v3.x/guides/unit-testing.html#test-strapi-instance)
3. yarn run test

**Expected behavior**
Test should be passing

**Screenshots**

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Yarn version: 1.22.0
- Strapi version: 3.1.4
- Database: sqlite
- sqlite3: 5.0.0
- Operating system: Windows 10
- Jest: 26.4.2
- supertest: 4.0.2

**Comment by saulmmendoza** [comment]
same but on linux ubuntu, even when using gitlab CI with the strapi/base docker image

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7811
