### ISSUE TITLE
Error 500 on upload files related to an entry

### ISSUE THREAD

**Issue by WilliamTraoreee** [strapi/strapi#7675]
**Describe the bug**

I have on issue when I want upload a file related to an entry.
No problem for upload a media but when I specified the field value, I have an error 500.

**Screenshots**

![Strapi Error](https://image.noelshack.com/fichiers/2020/36/2/1598967833-strapierror.png)

**Code snippets**

This is how I format my data 

``` const formData = new FormData();
    formData.set('files', image);
    formData.set('refId', result.id);
    formData.set('ref', 'communities');
    formData.set('field', 'Image'); 
```

And how I send data 

```
const config = {
      headers: new HttpHeaders({
        Authorization: 'Bearer ' + token
      })
    };
return this.http.post(`${environment.apiUrl}/upload`, formData, config);
```

**System**

- Node.js version: 12.18.0
- NPM version: 6.14.4
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
Can you please include the content of the 500 error from the server (500 errors will always generate something on the server logs, 400 will be on the client/browser side)

**Comment by WilliamTraoreee** [comment]
Sorry, I forgot that. This is the error from the server 

![Error](https://image.noelshack.com/fichiers/2020/36/2/1598973493-strapierror2.png)

**Comment by derrickmehaffy** [comment]
It would appear the field you are referring to in the post doesn't exist, do you have the model settings file for the `communities` model? It should be located in `./api/communities/models/communities.settings.json`

**Comment by WilliamTraoreee** [comment]
I found the issue ! 
The problem is my content type is "Community" and the collection name is "communities". I just change communities by Community and it works perfectly.

Thanks for the help !
