### ISSUE TITLE
OR condition in custom query

### ISSUE THREAD

**Issue by sharmarahul17** [strapi/strapi#7677]
**Requirement**: OR condition in custom query

Trying to follow solution given in issue #4293  https://github.com/strapi/strapi/issues/4293

**Strapi Documentation** : https://strapi.io/documentation/v3.x/concepts/queries.html#api-reference

**My code snippet**: 
`      await strapi
        .query("violation")
        .model.query((qb) => {
          qb.where(note_contains, searchText).orWhere(
            ticketNumber_contains,
            searchText
          );
        })
        .fetch();`

**Error**: `api/controllers/module.searchTypeError: strapi.query(...).model.query is not a function`

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.1.4

Thank you for your help.

**Comment by derrickmehaffy** [comment]
Currently in the process of trying to reproduce this issue.

**Comment by derrickmehaffy** [comment]
I've tested and it appears our documentation example may be slightly out of date. @alexandrebodin , @petersg83 , or @Convly can either of you provide a good example and I can update our docs?

**Comment by alexandrebodin** [comment]
Hello, you are mixing the Strapi queries API and the Bookshelf API :) 
`field_contains` doesn't exist as a bookshelf filter you will need to create sth like:

```js
qb.where('note', 'LIKE', '%searchText%');
```

**Comment by derrickmehaffy** [comment]
As no response from the user, marking as closed
