### ISSUE TITLE
EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by navvvidi** [strapi/strapi#768]
**Node.js version**: 8.9.3

**npm version**: 5.5.1

**Strapi version**: 3.0.0-alpha.10.3

**Operating system**: Windows

**I'm trying to deploy Strapi on a "Windows Host" managed by "Plesk 12" and this error accured:**

```
Application has thrown an uncaught exception and is terminated:
Error: EPERM: operation not permitted, unlink 'C:\...admin\admin\src\config\plugins.json'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at fs.access.err (C:\Inetpub\vhosts\...\node_modules\strapi\lib\core\plugins.js:76:16)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**do you think this is an npm bug?**

**Comment by lauriejim** [comment]
It looks coming from your os permissions. Don't think it's related to Strapi.

**Comment by lauriejim** [comment]
How you install and setup your Strapi app on this server ?

**Comment by pierreburgy** [comment]
Please try to downgrade to npm 5.3 (`npm install -g npm@5.3`): https://github.com/npm/npm/issues/18380.

**Comment by navvvidi** [comment]
@lauriejim thanks!

yes it was the problem with the OS permissions, solved. sorry for the dump question, i'm prety new to windows hosts.

@pierreburgy thank you!

**Comment by mdocter** [comment]
>  
> yes it was the problem with the OS permissions, solved. sorry for the dumb question, i'm prety new to windows hosts.
> 

@navvvidi Can you remember what you changed? Which OS permissions was this? I still have the same problem.
