### ISSUE TITLE
Firefox will remove strapi.injectSaga in the next major release

### ISSUE THREAD

**Issue by SorinGFS** [strapi/strapi#7688]
**Describe the bug**
Accessing Strapi from Firefox latest version shows the following warning in console:
`Warning: strapi.injectSaga will be removed in the next major release. 
 Please update your code.`

**Comment by derrickmehaffy** [comment]
Can you please include your Strapi version? Also @soupette and @HichamELBSI is this something easy for us to migrate?

**Comment by soupette** [comment]
@derrickmehaffy it's intended towards plugins developers, the redux-saga dependency will be removed at some point.

**Comment by SorinGFS** [comment]
> 
> 
> Can you please include your Strapi version? Also @soupette and @HichamELBSI is this something easy for us to migrate?

Version is 3.1.4

**Comment by soupette** [comment]
@SorinGFS in the next major release of Strapi not Firefox.
I am closing this issue as it is intended.
