### ISSUE TITLE
How to set domain for Strapi Admin Panel path on Heroku?

### ISSUE THREAD

**Issue by faizananwerali** [strapi/strapi#7692]
Recently I deployed my Strapi app on Heroku. If you look into routes https://example.herokuapp.com/ is for API and https://example.herokuapp.com/admin is for Admin Panel. Now I have my domain [example.com][1] and subdomain [api.example.com][3] and [admin.example.com][4] at Cloudflare which I can add in setting page. How can I use that [admin.example.com][4] domain in place of https://example.herokuapp.com/admin path and [api.example.com][3] domain in place of https://example.herokuapp.com/? So whenever client visit [admin.example.com][4] it open admin panel and not show [herokuapp.com][2] domain. Maybe using nginx anyone?

https://stackoverflow.com/q/63698871/3774282

  [1]: https://example.com
  [2]: https://herokuapp.com
  [3]: https://api.example.com
  [4]: https://admin.example.com

**Comment by derrickmehaffy** [comment]
closing as discussion already open: https://github.com/strapi/strapi/discussions/7686

@faizananwerali Please don't cross post into issues unless asked, thank!
