### ISSUE TITLE
Author can select relational content that another user created.

### ISSUE THREAD

**Issue by Naxos84** [strapi/strapi#7696]
**Describe the bug**
When a user has the role "author" he can only see and edit the content that was created by the user.
When a content-type contains a relation field to another content-type then the user can select an entry that was not created by him.

**Steps to reproduce the behavior**

1. create 2 users. (Author A, Author B)
2. assign both users the Author role.
3. create 2 content-types (A and B)
3.1 add a relation field in A of type B
4. add at least 1 content entry of type B with Author B
5. add a content entry of type A with Author A
6. expand the dropdown for the relational field and see the entry that Author B created.

**Expected behavior**
Author A should not be able to select relational content that was not created by himself.

**Screenshots**
![Authorbug1](https://user-images.githubusercontent.com/17813025/91969674-c5187800-ed16-11ea-89df-0eb73f4c3597.png)
![Authorbug2](https://user-images.githubusercontent.com/17813025/91969677-c5b10e80-ed16-11ea-90f9-bb1ba0986555.png)
![Authorbug3](https://user-images.githubusercontent.com/17813025/91969679-c649a500-ed16-11ea-8a4b-8f4d2025b641.png)
![Authorbug4](https://user-images.githubusercontent.com/17813025/91969680-c649a500-ed16-11ea-8028-7d4f2739b8d6.png)

**Code snippets**
//shop.settings.json
```
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "shops",
  "info": {
    "name": "Shop"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "pages": {
      "via": "shops",
      "collection": "page",
      "dominant": true
    },
    "identifier": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "name": {
      "type": "string",
      "required": true
    },
  }
}
```

//page.settings.json
```
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "pages",
  "info": {
    "name": "Page"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "slug": {
      "type": "string",
      "required": false,
      "unique": false
    },
    "metaTitle": {
      "type": "string"
    },
    "title": {
      "type": "string",
      "required": true
    },
    "shops": {
      "collection": "shop",
      "via": "pages"
    }
  }
}
```

**System**

- Node.js version: v12.16.0
- NPM version: 6.13.4
- Strapi version: 3.1.3
- Database: sqlite
- Operating system: windows 10

**Additional context**
None

If you need more information please let me know.

In the meantime: Is it possible to implement the expected filter behaviour on my end via Controller/Services?

**Comment by derrickmehaffy** [comment]
Currently this is the intended as you can select the relation but you can only see the field selected for that relation, it will not allow the user to access the related information.

We don't currently have the option to restrict selecting relations the user owns at the moment, I've set this as an enhancement for now after confirming with our engineering team.

For now we do not have a workaround for this.

**Comment by Naxos84** [comment]
hey derrickmehaffy.

Thank you very much for the response and the explanation.

When this enhancement will get implemented: Is this issue used for that? (in order to be able to keep track of it?)

**Comment by itsMattShull** [comment]
Just adding my voice to this ticket to follow along.  Really useful feature!  Also if anyone has thought of a workaround please share :-)

**Comment by itsMattShull** [comment]
@Naxos84 I found a workaround.  The use case being that any role other than Super Admin should only see entries they created in the relation list.  Super Admin's should still be able to see all entries of a relation list.

In the `strapi-plugin-content-manager` package you'll find a file called `ContentManager.js`.  In the strapi project you can find it at `node_modules/strapi-plugin-content-manager/controllers/ContentManager.js`.

Inside the file you'll find an async function called `findRelationList`.  At the top of the function you'll want to add `const { user } = ctx.state;`.  This will provide you with all the info about the user making the request for the relation list.

Then further down the function, right under `let entities = [];`, you'll want to add the following:
```
// START CUSTOM CODE
    // FILTERS RELATION LISTS FOR AUTHORS TO ONLY SHOW ENTRIES THEY HAVE CREATED
    if (user.roles[0].code !== 'strapi-super-admin') {
      query['created_by'] = `${user.id}`;
    }
    // END CUSTOM CODE
```
This if statement takes checks to see if the User's role is Super Admin, and if not it will add `created_by` as a parameter to the filter that Strapi uses to fetch the relation list.

If you want to filter the relation list for all the roles, including Super Admin, then you only need to add the following right under `let entities = [];`:
```
query['created_by'] = `${user.id}`;
```
There wouldn't be a need to get the user info or the if statement.

I know it's not an official fix, but hopefully it's a good work around for you too!  Would still love this ability built into the platform.

**Comment by itsMattShull** [comment]
@derrickmehaffy I'm new to strapi, but would the proper way to make this change so that when it upgrades it doesn't break be to use Extensions?  So I created `extensions/strapi-plugin-users-permissions/services/User.js` in my root folder and use the code I discussed above?

If so, I understand that any time I update Strapi I'd need to make sure that file I created is similar to `node_modules/strapi-plugin-users-permissions/services/User.js` or it'll break.

**Comment by derrickmehaffy** [comment]
> If so, I understand that any time I update Strapi I'd need to make sure that file I created is similar to node_modules/strapi-plugin-content-manager/controllers/ContentManager.js or it'll break.

Yes exactly, it's the downside to the extensions system as it requires you to keep that part of the code in sync with our version. We are planning some changes to the v4 with more programmatic hooks into various parts of the code so you don't need to override whole files or functions.

**Comment by brooth** [comment]
Why is this low priority ticket? It completely ruined my work for weeks as it allows my customers to see other user entities. It's a security hole and it must be high severity!

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/author-is-reading-other-authors-items-by-the-related-field/2920/2

**Comment by silasaragozo** [comment]
I'm new to strapi, I started this same topic on the forum! in version 3.5.0, I can't find the file, `node_modules / strapi-plugin-content-manager / controllers / ContentManager.js`

No solution so far!

**Comment by derrickmehaffy** [comment]
@silasaragozo that file was broken down into multiple new files: https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/controllers

**Comment by silasaragozo** [comment]
very good!  you would have an example of what file and what that file would look like after the modification!  I'm new to strapi, I did some tests on these files, but I didn't get the expected result!

**Comment by derrickmehaffy** [comment]
I'm not sure as I have not reviewed these files lately, it's been quite a busy quarter so hard to keep up with custom modifications and workarounds right now.

**Comment by silasaragozo** [comment]
I understand! thank you very much for pointing a north in my research! I will look for a solution!

**Comment by thopedam** [comment]
Hi,
I was looking for exactly into this issue. The file which needs to be modified is `node_modules / strapi-plugin-content-manager / controllers / relations.js`. I implemented this using an extension (like @itsMattShull mentioned) at `extensions / content-manager / controllers / relations.js`. Simply copy the plugin file there and adjust it to your needs. Keep in mind: `require("../utils");` needs to be changed to `require("strapi-plugin-content-manager/utils");`

Thanks.

**Comment by silasaragozo** [comment]
Hello, I tried to execute but I was not successful, the items are not loaded, it is in constant looding.
![image](https://user-images.githubusercontent.com/37216500/109211697-524ffd00-778d-11eb-992f-bc16bb32fe48.png)

**Comment by thopedam** [comment]
You see what is wrong when you look at your Terminal. Every Call to the Server is logged there. For me this sounds like a code error

**Comment by silasaragozo** [comment]
can you share your relations.js file so i can study it?

**Comment by thopedam** [comment]
You can find it [here](https://gist.github.com/thopedam/31e65be1f757c68fc3230b6de82b6b98) Good Luck!

**Comment by silasaragozo** [comment]
thank you so much!

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/define-a-collection-content-to-be-global-for-all-auth-users/3575/4

**Comment by PatrykBuniX** [comment]
Any updates / work-arounds on this in v4?

**Comment by imphillipzissou** [comment]
@PatrykBuniX Seems like a low-priority issue, so unlikely to be fixed anytime soon. I did notice that a [Data Ownership](https://portal.productboard.com/strapi/1-roadmap/c/44-data-ownership) ticket was on the Roadmap thought. I'm hoping this would address the issue. The work around above still works, however just needs some tweaks for v4. Here's my `relations.js` adaptation:

```
"use strict";

const { has, prop, pick, concat } = require("lodash/fp");
const { PUBLISHED_AT_ATTRIBUTE } = require('@strapi/utils').contentTypes.constants;

const { getService } = require('../utils');

module.exports = {
  async find(ctx) {
    const { model, targetField } = ctx.params;
    const { _component, ...query } = ctx.request.query;
    const { idsToOmit } = ctx.request.body;
    const { user } = ctx.state;

    if (!targetField) {
      return ctx.badRequest();
    }

    const modelDef = _component ? strapi.getModel(_component) : strapi.getModel(model);

    if (!modelDef) {
      return ctx.notFound("model.notFound");
    }

    const attribute = modelDef.attributes[targetField];
    if (!attribute || attribute.type !== 'relation') {
      return ctx.badRequest("targetField.invalid");
    }

    const target = strapi.getModel(attribute.target);

    if (!target) {
      return ctx.notFound("target.notFound");
    }

    if (idsToOmit && Array.isArray(idsToOmit)) {
      query.filters = {
        $and: [
          {
            id: {
              $notIn: idsToOmit,
            },
          },
        ].concat(query.filters || []),
      };
    }

    if (user.roles[0].code !== 'strapi-super-admin') {
       query.filters = {
         $and: [{
           'createdBy': `${user.id}`
         }].concat(query.filters || [])
       };
    }

    const entityManager = getService('entity-manager');

    const entities = await entityManager.find(query, target.uid, []);

    if (!entities) {
      return ctx.notFound();
    }

    const modelConfig = _component
      ? await getService("components").findConfiguration(modelDef)
      : await getService("content-types").findConfiguration(modelDef);

    const field =
      prop(`metadatas.${targetField}.edit.mainField`, modelConfig) || "id";
    const pickFields = [field, "id", target.primaryKey, PUBLISHED_AT_ATTRIBUTE];

    ctx.body = entities.map(pick(pickFields));
  },
};
```

**Comment by MSid01** [comment]
@imphillipzissou Isn't is high priority issue. 
I have relational field where Garage **has and belongs to** one Address. If first Author created Address content and selected Garage for it or vice versa. Second Author can select the address content, the first author created/selected and now for the first Author address is unselected.

**Comment by MSid01** [comment]
> Any updates / work-arounds on this in v4?

Have you found any workaround in V4?

**Comment by simongloor** [comment]
Since this looks like it will take a while to actually be implemented, here a few hints that threw me off.

I took the code of @imphillipzissou but I had to update the require link like @thopedam wrote. Also, in Strapi v4 we need to override the controller in the strapi-server.js (like shown in my screenshot)

![image](https://user-images.githubusercontent.com/43432178/173865511-70233406-4537-4491-813e-68ac8a0c7679.png)

**Comment by engineers-dope** [comment]
My workaround for v4.5.5, hope this helps whoever is facing the same issue

`src/extensions/content-manager/strapi-server.js`

```
"use strict";

const { prop, isEmpty } = require('lodash/fp');
const { hasDraftAndPublish } = require('@strapi/utils').contentTypes;
const { PUBLISHED_AT_ATTRIBUTE } = require('@strapi/utils').contentTypes.constants;

const { getService } = require('@strapi/plugin-content-manager/server/utils');
const { validateFindAvailable } = require('@strapi/plugin-content-manager/server/controllers/validation/relations');

const addFiltersClause = (params, filtersClause) => {
  params.filters = params.filters || {};
  if (params.filters.$and) {
    params.filters.$and.push(filtersClause);
  } else {
    params.filters.$and = [filtersClause];
  }
};

module.exports = (plugin) => {
    plugin.controllers.relations.findAvailable = async (ctx) => {
      const { userAbility } = ctx.state;
      const { model, targetField } = ctx.params;
  
      await validateFindAvailable(ctx.request.query);
  
      // idsToOmit: used to exclude relations that the front already added but that were not saved yet
      // idsToInclude: used to include relations that the front removed but not saved yes
      const { entityId, idsToOmit, idsToInclude, _q, ...query } = ctx.request.query;
  
      const modelSchema = strapi.getModel(model);
      if (!modelSchema) {
        return ctx.badRequest("The model doesn't exist");
      }
  
      const attribute = modelSchema.attributes[targetField];
      if (!attribute || attribute.type !== 'relation') {
        return ctx.badRequest("This relational field doesn't exist");
      }
  
      const isComponent = modelSchema.modelType === 'component';
  
      // RBAC checks when it's a content-type
      // TODO: do RBAC check for components too
      if (!isComponent) {
        const permissionChecker = getService('permission-checker').create({
          userAbility,
          model,
        });
  
        if (permissionChecker.cannot.read(null, targetField)) {
          return ctx.forbidden();
        }
  
        if (entityId) {
          const entityManager = getService('entity-manager');
  
          const entity = await entityManager.findOneWithCreatorRoles(entityId, model);
  
          if (!entity) {
            return ctx.notFound();
          }
  
          if (permissionChecker.cannot.read(entity, targetField)) {
            return ctx.forbidden();
          }
        }
      } else {
        // eslint-disable-next-line no-lonely-if
        if (entityId) {
          const entity = await strapi.entityService.findOne(model, entityId);
  
          if (!entity) {
            return ctx.notFound();
          }
        }
      }
  
      const targetedModel = strapi.getModel(attribute.target);
  
      const modelConfig = isComponent
        ? await getService('components').findConfiguration(modelSchema)
        : await getService('content-types').findConfiguration(modelSchema);
      const mainField = prop(`metadatas.${targetField}.edit.mainField`, modelConfig) || 'id';
  
      const fieldsToSelect = ['id', mainField];
      if (hasDraftAndPublish(targetedModel)) {
        fieldsToSelect.push(PUBLISHED_AT_ATTRIBUTE);
      }
  
      const queryParams = {
        sort: mainField,
        ...query,
        fields: fieldsToSelect, // cannot select other fields as the user may not have the permissions
        filters: {}, // cannot filter for RBAC reasons
      };
  
      if (!isEmpty(idsToOmit)) {
        addFiltersClause(queryParams, { id: { $notIn: idsToOmit } });
      }
  
      // searching should be allowed only on mainField for permission reasons
      if (_q) {
        addFiltersClause(queryParams, { [mainField]: { $containsi: _q } });
      }
  
      if (entityId) {
        const subQuery = strapi.db.queryBuilder(modelSchema.uid);
  
        const alias = subQuery.getAlias();
  
        const where = {
          id: entityId,
          [`${alias}.id`]: { $notNull: true },
        };
  
        if (!isEmpty(idsToInclude)) {
          where[`${alias}.id`].$notIn = idsToInclude;
        }
  
        const knexSubQuery = subQuery
          .where(where)
          .join({ alias, targetField })
          .select(`${alias}.id`)
          .getKnexQuery();
  
        addFiltersClause(queryParams, { id: { $notIn: knexSubQuery } });
      }
  
      const { user } = ctx.state;
      if (user.roles[0].code !== 'strapi-super-admin') {
        addFiltersClause(queryParams, { createdBy: user.id }); // filter created by user id or change it to anything you want to filter by
      }
      ctx.body = await strapi.entityService.findPage(targetedModel.uid, queryParams);
    }

    return plugin
  };
```

**Comment by akdenied** [comment]
@engineers-dope but this script restricts the user's ability to view admin created content as well in the relation dropdown

**Comment by derrickmehaffy** [comment]
mostly related to this as it will be a pre-req for adding this control ability: https://feedback.strapi.io/customization/p/parent-child-relationshipfield
