### ISSUE TITLE
Swagger Documentation not generating fields .

### ISSUE THREAD

**Issue by kshitijsubedi** [strapi/strapi#7698]
**Describe the bug**
Generated Swagger Documentation generated is broken. Most of the body and responses field are foo:'string'. Used to work previously but upgrading to 3.1.0 got this. 

**Steps to reproduce the behavior**

1. Go to 'Admin Panel'
2. Click on 'Documentation' , Click on Regenerate 
3. Check generated api fields.

**Expected behavior**
Should have generated respective fields and response body.

**Screenshots**
![Screenshot_2020-09-02-36_1920x1080](https://user-images.githubusercontent.com/20613798/91980118-7f73a380-ed46-11ea-9214-c3db7e5e9b37.png)
![Screenshot_2020-09-02-20_1920x1080](https://user-images.githubusercontent.com/20613798/91980126-83072a80-ed46-11ea-91e9-10f2e5c37ad6.png)

**System**

- Node.js version: 14.8.0
- NPM version: 6.14.7
- Strapi version: 3.1.0
- Database: MongoDB atlas
- Operating system: Arch Linux

**Comment by alexandrebodin** [comment]
Hi, you are displaying the auth/local route. this route doesn't have a model related to it so the default doc is foo: string. Have you check on of the content types ? I cannot seem to reproduce

**Comment by kshitijsubedi** [comment]
Yes on other content types, its there.
Well your answer [` this route doesn't have a model related to it so the default doc is foo: string `] clarifies this issue. Thank you
Closing this issue
