### ISSUE TITLE
CORS wildcard with credentials include

### ISSUE THREAD

**Issue by luwes** [strapi/strapi#7702]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I'm doing authentication via a httpOnly cookie and there is a case where I think the CORS config falls short if you want to make your API public and also take advantage of the user's session.

This Chrome error illustrates the problem:
>  The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

This is not allowed, the solution here is to pass an origin header but it can't be the wildcard `*`.
It must be the origin of the requester which you might not know upfront so it's a dynamic value for each request. 

How can this be implemented currently?

Maybe it should be allowed to set a callback function as the `origin` property?

**Comment by jcoyle37** [comment]
I would think a configuration like the following in `./config/middleware.js` would be a reasonable approach, but it doesn't seem to work for me; my _Access-Control-Allow-Origin_ header remains set to * in the response:

```
cors: {
  enabled: true,
  headers: '*',
  origin: ['http://localhost:8080']
}

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
