### ISSUE TITLE
"Content Types" using the same Collection get mixed up

### ISSUE THREAD

**Issue by pedrosimao** [strapi/strapi#771]
**Node.js version**:
9.7.1
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.11
**Operating system**:
Ubuntu

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I create several "Content Types"/ APIs that share the same Collection name, the database get mixed up. If I create an item for one API the same item will appear on the others API/Content Types that use the same collection name. This bug started in version alpha 11 (with file upload). I have reported it in another issue but I found it to be a good idea to open a new bug report just for this specific issue. Hope this will help you better organize the project.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. "Content Type Builder" >> "Add Content Type" >> "Advanced Settings" >> Choose a Collection Name like "new" >> Create any fields wanted in the Content Type.
2. Repeat "1" steps and give the "Content Type" a different name but use the same Collection Name "new"
3. Click on newly created Content Type on left menu >> insert any data and save >> head to the second newly created Content Type and you will see the information you have inserted in the first Content Type.

**What is the expected behavior?**
When creating a new item, this item should not appear on other API/ Content Types sharing the same mongodb Collection.

**Comment by asharamseervi** [comment]
In my case with Heroku Apps, I'm really not able to make any entries to the database with Content Types. Whenever, I'll create Content Type, it'll be shown up in left navigation but, the input will be missed whatever I had added while creating Content Types.

**Sharing following screenshot:**

- I'm able to create Content Type & Added 2 inputs for APIs.
![showing-created-in-left](https://user-images.githubusercontent.com/5942572/37285445-06976220-2625-11e8-9552-953f3dfdbf23.PNG)

&

- On hitting refresh, or just navigating to recently created Content Type. It'll be broken.
![on-hitting-refresh-isgone-from-nav](https://user-images.githubusercontent.com/5942572/37285464-112c33b4-2625-11e8-8a29-00ce94808163.PNG)

**Comment by pedrosimao** [comment]
@asharamseervi I don't think your issue has any relation with the mentioned bug. Items can be created with no problem. The bug I mentioned is just related to Content Types using same Collection name.
I think a similar issue have been opened here #770

**Comment by asharamseervi** [comment]
Hmm, you can say. But, reason behind commenting here, is same property issue i.e. Content Type. I think, on Heroku (as mentioned) stuff not working as expected. Please try to login official Heroku Demo as described on [Strapi Blog](https://blog.strapi.io/deploying-a-strapi-api-on-heroku/).

URL: https://strapi-heroku-app.herokuapp.com
USER: demo@strapi.io
PASS: demo

& you'll notice some issues regarding Content Type. Might be there are some errors, while fixing your bug, may remove/help to this fix as well.

**Comment by pedrosimao** [comment]
@asharamseervi I am pretty sure the issue you are talking about is not related to the issue I have opened. Relation one thing to the other  can make issue solving confusing, for the developers.
I am pretty sure your issue is only related to Heroku and not to shared Collection names.
If you feel like doing so, please open a separate issue.

**Comment by asharamseervi** [comment]
Great. I will.

**Comment by lauriejim** [comment]
Hi @pedrosimao this is not an issue, it's normal. 
`Collection name` is just the `collection` or `table` where you will CRUD data. So if two of your model are linked to the same data source they will share there data.

**Comment by pedrosimao** [comment]
@lauriejim If this is not a bug it is a poor design choice and it is actually inconsistent with you previous Strapi versions. Not to say it pretty much feels like it is a bug when you see same data being displayed randomly across different Content Types. 

The most annoying part of this issue is that on earlier versions of Strapi (even on v3 alpha10) this would not happen. So, I was building my app with many APIs sharing the same Collection name, because this was a smart choice for me to organize the project that way. And the data was not mixed up. Each item would appear for each individual API no matter if they use the same Collection. This behavior only started on alpha v11. Do you believe me on that at least?

Now I have to completely redesign my APIs and queries, because you randomly change behavior of Strapi from version to version. And it is no longer possible to put different model in the same Collection, which can be a very good idea performance wise, for example.

**Comment by lauriejim** [comment]
As we discuss on Slack you get weird behavior but your case can't happen on v3 of Strapi.
