### ISSUE TITLE
Conditional data restriction

### ISSUE THREAD

**Issue by Wiz-Amit** [strapi/strapi#7710]
**Describe the bug**
Data restriction (e.g. article) based on some condition (e.g. status = "Published") is not well documented

**Steps to reproduce the behavior**
I have tried to create a draft system by following [this Strapi document](https://strapi.io/documentation/v3.x/guides/draft.html)

**Expected behavior**
It should restrict unpublished articles. But this is not restricting articles if I use GraphQL. I have tried to restrict data in the service layer, but that fails if I fetch a category and its related articles. In that case, all articles get send irrespective of their status. I think more documentation is required to have this kind of data restriction.

**System**
- Strapi version: v3

**Comment by MattieBelt** [comment]
@Wiz-Amit, I do agree it isn't the complete picture, it's more a guide to point you in the right direction. But the Strapi team is currently working on a new feature that will include draft & publish functions by default. Check out the current development in the branch: [features/draft-publish](https://github.com/strapi/strapi/tree/features/draft-publish). I'm not sure when it will be released, but I think it will be before the end of the month.

**Comment by derrickmehaffy** [comment]
> @Wiz-Amit, I do agree it isn't the complete picture, it's more a guide to point you in the right direction. But the Strapi team is currently working on a new feature that will include draft & publish functions by default. Check out the current development in the branch: [features/draft-publish](https://github.com/strapi/strapi/tree/features/draft-publish). I'm not sure when it will be released, but I think it will be before the end of the month.

"Very soon" (tm) :wink: 

I'm going to close this issue for now as it doesn't follow our required templates rule defined in our [Contributor Code of Conduct](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md).

But I do believe we plan to remove that manual guide once we release the feature.
