### ISSUE TITLE
single type controller - doc typo?

### ISSUE THREAD

**Issue by amirc** [strapi/strapi#7718]
Hi,
In the documentation: https://strapi.io/documentation/v3.x/concepts/controllers.html#core-controllers there is an example how to overwrite a single type controller:

```
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  /**
   * Retrieve the record.
   *
   * @return {Array}
   */

  async find(ctx) {
    const entity = await strapi.services.restaurant.findOne();
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
};
```

I believe that the function call on line 11 should be "find" and not "findOne".

Thanks,
Amir.

**Comment by MattieBelt** [comment]
Hey @amirc, it indeed should be `find()`. 
The default SingleType service doesn't have an `findOne()` function [only](https://github.com/strapi/strapi/blob/5b338782c4186d5e270ac99cee1ef6c550e29069/packages/strapi/lib/core-api/service.js#L28) `find()`.
Feel free to submit a PR that [improves the docs](https://github.com/strapi/strapi/edit/documentation/docs/v3.x/concepts/controllers.md).

**Comment by alexandrebodin** [comment]
PR merged, closing :)

**Comment by fadhilx** [comment]
also for the service,
ive made a PR#8764
