### ISSUE TITLE
Allow passing custom populate in update query

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7731]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Allow passing custom populate or no populate in `query.update` method.
Currently as per this: https://strapi.io/documentation/v3.x/concepts/queries.html#api-reference
update query returns full updated object with all relational models, but I don't want to populate all the relations.
Also for mongodb (Only checked for it) it executes `await model.findOne(params);` before updating the entry (it will populate all relational data), so if model has so many relations it might be slower than mongoose update query.

**Comment by alexandrebodin** [comment]
you can already use [] in the find just not the update :)

**Comment by iapain** [comment]
@alexandrebodin Sorry let me explain, What about relational data or component/dz data ;) will it respect that? If we expose it in model schema then it can be implemented at ORM layer to delivery consistent behavior. Moreover, it make it easier for developers to maintain, which data should be exposed via REST API and GraphQL. My proposal is like this:

```
...
 "categories": {
      "collection": "category",
      "via": "cakes",
      "dominant": true,
      "populate": {
          "find": ["name"], // only populate name field in rest api,
          "findOne": ["name", "description", "parent"],
          "update": []
          ...
      }
  },
...
```
Same goes to components and dynamic zones.

**Comment by aksdevac** [comment]
Noticed same issue with `create` also, it also returns full object with all populated relations.

**Comment by weidox** [comment]
I have also noticed that findOne call which populates everything in update method in entity-service.js. Pointless waste of resources and so simple to fix.

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
