### ISSUE TITLE
Strapi CMS for Mobile

### ISSUE THREAD

**Issue by codeWonderland** [strapi/strapi#7738]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

I would like for the Strapi CMS to be usable on mobile. Currently, the left nav stays open and collapses the editor pane to a small strip of the screen, which doesn't allow for any updates of content to happen. I have attached a screenshot below

![image](https://user-images.githubusercontent.com/22084929/92257595-7f3cea80-eea3-11ea-8deb-0f8f4a16a14f.png)

Ideally, the left column would either go to a hamburger nav or be collapsable on the left. Then the table would be structured to work on mobile, which wouldn't be a major lift. I'm going to play around with making a PR for this feature as I am trying to get this done for a client ASAP

**Comment by derrickmehaffy** [comment]
Hello we don't currently support mobile browsers for the moment but thank you for the feature request.

**Comment by MattieBelt** [comment]
I Would like to notice a possible duplication of #5094 & #463 and the exiting of [Administration - Responsive](https://portal.productboard.com/strapi/1-roadmap/c/20-administration-responsive).

**Comment by derrickmehaffy** [comment]
Thank you @MattieBelt you are correct this is a duplicate :wink: 

Closing in favor of https://portal.productboard.com/strapi/1-roadmap/c/20-administration-responsive
