### ISSUE TITLE
Date field sets incorrectly

### ISSUE THREAD

**Issue by locopati** [strapi/strapi#7739]
**Describe the bug**
When I set a date field in a new item, the date is off by days (3.0) or weeks (3.1)

**Steps to reproduce the behavior**

1. Create a new item that has a date field
2. Set a date value to today
3. Save the item

**Expected behavior**
The date is unchanged

**Actual**
The date is days or weeks in the future

**System**

- Node.js version: 14.5
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: mongo 4.2.5
- Operating system: Arch Linux

**Additional context**
Saving edits does not change the date. Only the first save saves it incorrectly.

**Comment by MattieBelt** [comment]
Hey @locopati, node 14 [isn't supported](https://strapi.io/documentation/v3.x/installation/cli.html#step-1-make-sure-requirements-are-met).
Can you try with node 12.x>

**Comment by derrickmehaffy** [comment]
(Also please note that if the date field is not within the primary model, such as a component or a relation, as the core model wasn't update nor will it's automated created_at/updated_at either be updated)

**Comment by derrickmehaffy** [comment]
@locopati have you tested on node v12?
