### ISSUE TITLE
path missing on original file with strapi-provider-upload-aws-s3

### ISSUE THREAD

**Issue by ScottEAdams** [strapi/strapi#7742]
**Describe the bug**
When using strapi-provider-upload-aws-s3 their is a useful `formats.[your-format].path`, however this is missing for the original file.

**Steps to reproduce the behavior**

1. Install strapi-provider-upload-aws-s3
2. Upload an image
3. Get the image at upload/files/:id

**Expected behavior**
I would have expected the path on the original image also/instead of in formats. Maybe it is only needed on the original image instead of within the formats as all formats will have that path?

**Code snippets**
```
{
  "id": 8,
  "name": "whatever.jpeg",
  "alternativeText": null,
  "caption": null,
  "width": 2762,
  "height": 2762,
  "formats": {
    "thumbnail": {
      "ext": ".jpeg",
      "url": "https://mybucket.s3.eu-north-1.amazonaws.com/custompath/thumbnail_whatever_be121ced.jpeg",
      "hash": "thumbnail_whatever_be121ced",
      "mime": "image/jpeg",
      "name": "thumbnail_whatever.jpeg",
      "path": "custompath",
      "size": 2.55,
      "width": 156,
      "height": 156
    }
  },
  "hash": "whatever_be121ced",
  "ext": ".jpeg",
  "mime": "image/jpeg",
  "size": 257.61,
  "url": "https://mybucket.s3.eu-north-1.amazonaws.com/custompath/whatever_be121ced.jpeg",
  "previewUrl": null,
  "provider": "aws-s3",
  "provider_metadata": null,
  "created_by": null,
  "updated_by": null,
  "created_at": "2020-09-05T01:17:50.258Z",
  "updated_at": "2020-09-05T01:17:50.258Z",
  "related": [
    null
  ]
}
```

**System**

- Strapi version: 3.1.4

**Comment by derrickmehaffy** [comment]
Let me poke the backend team, as I'm not sure why it was built this way, but I'm guessing it was only needed on the file optimizations.

@alexandrebodin @petersg83 @Convly

**Comment by alexandrebodin** [comment]
The path option cannot be set in the original image because of the data strucutre not having a path field. the formats being saved in a json field we persist the path. These are the kind of info we should perisist in a json metada field so it can allow extensions without changing the db schema
