### ISSUE TITLE
Add support for default path in AWS S3

### ISSUE THREAD

**Issue by BRoy98** [strapi/strapi#7744]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I have been using strapi-provider-upload-aws-s3 for a while now. As I can see on the plugin source, there is a way to define a path for each file by adding `file.path`. But if I want to upload all files from Strapi under a specific path by default, I think there is no way to do that. 

It will be a nice feature to have, If we can define a default path(optional) on the configuration file like this:

```
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: 'aws-s3',
    providerOptions: {
     // ...
      params: {
        // ...
        DefaultPath: env('AWS_DEFAULT_PATH'),
      },
    },
  },
  // ...
});
```
By doing this, all files should be uploaded under `/${AWS_DEFAULT_PATH}/...` on the S3 bucket.

**Comment by roelbeerens** [comment]
@BRoy98 Check out the provider we created for adding a path for all uploads here: https://github.com/gravitybv/strapi-provider-upload-aws-s3-path. You can download the package and place it in the `providers` folder in the root. The NPM package can than be set like this: `"strapi-provider-upload-aws-s3-path": "file:providers/strapi-provider-upload-aws-s3-path"`.

I do however think this would be a great addition to the main aws s3 provider.

**Comment by BRoy98** [comment]
> @BRoy98 Check out the provider we created for adding a path for all uploads here: https://github.com/gravitybv/strapi-provider-upload-aws-s3-path. You can download the package and place it in the `providers` folder in the root. The NPM package can than be set like this: `"strapi-provider-upload-aws-s3-path": "file:providers/strapi-provider-upload-aws-s3-path"`.
> 
> I do however think this would be a great addition to the main aws s3 provider.

@roelbeerens it looks good but I think there are few restrictions on this library.
1. you can not use `config.path` and `file.path` at the same time. Which should be like `config.path/file.path/filename.ext`.
2. It adds an `/uploads/` directory if `config.path` is used.

But anyway, nice work!

**Comment by roelbeerens** [comment]
> > @BRoy98 Check out the provider we created for adding a path for all uploads here: https://github.com/gravitybv/strapi-provider-upload-aws-s3-path. You can download the package and place it in the `providers` folder in the root. The NPM package can than be set like this: `"strapi-provider-upload-aws-s3-path": "file:providers/strapi-provider-upload-aws-s3-path"`.
> > 
> > I do however think this would be a great addition to the main aws s3 provider.
> 
> @roelbeerens it looks good but I think there are few restrictions on this library.
> 1. you can not use `config.path` and `file.path` at the same time. Which should be like `config.path/file.path/filename.ext`.
> 2. It adds an `/uploads/` directory if `config.path` is used.
> 
> But anyway, nice work!

Your probably right here. This is pretty much custom tailored to our situation but you could probably use it to create your own provider ;)

**Comment by BRoy98** [comment]
@lauriejim kindly check if this is the correct behavior for setting up a default path:

1. All the Files will get uploaded under `config.defaultPath/` directory: `config.defaultPath/filename.ext`
2. If `file.path` is mentioned, it will go under `config.defaultPath/file.path/filename.ext`

It'll make it easy for the community to open a PR with the changes. 😃

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/add-support-for-logical-file-upload-folder-paths
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
