### ISSUE TITLE
Error message response - two arrays that only returning single object

### ISSUE THREAD

**Issue by sebasptsch** [strapi/strapi#7749]
Users and Permissions plugin returns arrays with only a single error inside, inside another array which only has a single object.
**Describe the bug**

Instead of returning a simple string as an error message the User Auth plugin returns several arrays  within each other. As a result of this it's more difficult to understand for an entry level user and unclear how to parse errors from the plugin.

**Steps to reproduce the behavior**

Send a web request  to https://example.com/auth/${props.providerName}/callback${props.location.search} with the required variables. If a user uses an existing email a response message with the formatting issue is returned.

**Expected behavior**

Instead of the first code snippet it should return the second which is more easily parsed by clients.

**Screenshots**
![image](https://user-images.githubusercontent.com/32213671/92322154-ea88e700-f072-11ea-9ecd-d34ae8f326aa.png)

**Code snippets**
### Before
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": [{
      "messages": [{
          "id": "Auth.form.error.email.taken"
        }]
    }],
  "data": [{
      "messages": [{
          "id": "Auth.form.error.email.taken"
        }]
    }]
}
```
### After (suggested solution)
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "messages": [{"id": "Auth.form.error.email.taken"}],
  "data": {
      "messages": [{"id": "Auth.form.error.email.taken"}]
    }
}
```

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.7
- Strapi version: 3.1.3
- Database: MongoDB (mongoose)
- Operating system: Windows 10 (WSL Ubuntu 20.04)

**Comment by derrickmehaffy** [comment]
Hello!

Thank you for reporting this behavior.

Something I would greatly appreciate is if you can try to submit a PR to fix this issue.

The topic you are pointing out has to be fixed and it could be done by someone from the Community (you 🤗).

Here is the [contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to help you to getting started for contributions to Strapi.

Do not hesitate to reach us if you have any questions regarding the contribution.

Thank you and have a good day.

**Comment by henrych4** [comment]
I can help working on this

**Comment by sebasptsch** [comment]
Thanks for the offer @henrych4 I'm afraid I'm not quite sure where to start. You probably have a better idea than I do.

**Comment by alexandrebodin** [comment]
Hi we rebuilt the error handling in v4 so I'll go ahead and close this issue :)
