### ISSUE TITLE
language display error

### ISSUE THREAD

**Issue by myesn** [strapi/strapi#775]
**Node.js version**:
v9.5.0
**npm version**:
5.7.1
**Strapi version**:
3.0.0-alpha.11.1
**Operating system**:
windows 10 64bit

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Language is confused and I cannot switch languages.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
open this url:
```
http://localhost:1337/admin
```
![image](https://user-images.githubusercontent.com/18598579/37321913-a1f8d5f6-26b5-11e8-851c-5d21b3755331.png)

![image](https://user-images.githubusercontent.com/18598579/37321898-96ad67b6-26b5-11e8-94c4-a54467b7cc08.png)

**What is the expected behavior?**
Can switch languages, thanks.

**Comment by soupette** [comment]
Hi! the missing translation files have been added [see](https://github.com/strapi/strapi-plugin-analytics/tree/master/admin/src/translations). However, the traductions will be missing for the `zh` locales but we have a fallback to `en` so it won't break the UI
