### ISSUE TITLE
Admin UI : clicking the Public (or any) Role does not navigate to edit page

### ISSUE THREAD

**Issue by daxyonis** [strapi/strapi#7752]
**Describe the bug**
On page http://localhost:1337/admin/plugins/users-permissions/roles, when I click on the Public or Authenticated Role, the edit page is not displayed (as if there is no working link).

**Steps to reproduce the behavior**

1. Go to page http://localhost:1337/admin/plugins/users-permissions/roles
2. Click on Authenticated or Public role
3. Nothing happens

**Expected behavior**
Should navigate to http://localhost:1337/admin/plugins/users-permissions/roles/edit/2

**System**

- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: 3.1.4
- Database: sqlite3
- Operating system: Windows10

**Additional context**
I did a fresh Strapi install  `npx create-strapi-app cupcake-shop --quickstart` and I was surprised to get this bug since it used to work pretty well before.

**Comment by aksdevac** [comment]
may be related to this #7112, try clicking on small edit icon.

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI I believe Jim and I both mentioned something about this a while back :stuck_out_tongue:

**Comment by soupette** [comment]
It has already been merged on the master branch with the update of the plugin. It will be released with `3.1.5`. 

I believe that we should close this issue.

**Comment by derrickmehaffy** [comment]
Awesome thanks @soupette marking as closed pending release in v3.1.5
