### ISSUE TITLE
strapi-provider-upload-aws-s3 with custom path, original not deleted

### ISSUE THREAD

**Issue by ScottEAdams** [strapi/strapi#7770]
**Describe the bug**
New issue as requested in #6931.
I'm uploading images on AWS S3 using the plugin strapi-provider-upload-aws-s3 with custom paths. When deleting the image, the original file on a custom path is not deleted.

**Steps to reproduce the behavior**

1. Upload an image with a custom path. This will create original and thumbnail at a minimum.
2. Delete image.
3. Thumbnail is deleted, original is still around.

**Expected behavior**
Deletion of all formats including original.

**Additional context**
Related to #7742 perhaps?

**System**
- Node.js version: 13.7
- NPM version: 6.13.6
- Strapi version: 3.1.4
- Database: pg
- Operating system: osx

**Comment by derrickmehaffy** [comment]
@ScottEAdams while probably not needed, can you still add the following to your original post (edit)

```
**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

**Comment by ScottEAdams** [comment]
Yeah, sorry. Me being in a rush/lazy!

**Comment by derrickmehaffy** [comment]
I was able to confirm this using an S3 Bucket and a Strapi instance running in EC2.

If no `path` is provided, images are created and entirely deleted just fine
If adding a `path` such as `test`, files are created fine and all but the original image is deleted properly

Uploaded to the `test` path:
![image](https://user-images.githubusercontent.com/8593673/93141297-cba0db00-f698-11ea-99fb-864b8b17d11b.png)

And after deleting through the media library:
![image](https://user-images.githubusercontent.com/8593673/93141359-e1160500-f698-11ea-8476-5a3cd0cea8a8.png)

**Comment by sercanov** [comment]
I can confirm when deleting via `strapi.plugins.upload.services.upload.remove({ id })`
`file.provider` doesn't exist, manually sending `provider` parameter is a workaround

```javascript
async remove(file) {
    const config = strapi.plugins.upload.config;


    // execute delete function of the provider
    if (file.provider === config.provider) {
      await strapi.plugins.upload.provider.delete(file);

      if (file.formats) {
        await Promise.all(
          Object.keys(file.formats).map(key => {
            return strapi.plugins.upload.provider.delete(file.formats[key]);
          })
        );
      }
    }
```

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/13744
