### ISSUE TITLE
Media library breaks when replacing a media

### ISSUE THREAD

**Issue by BRoy98** [strapi/strapi#7776]
**Describe the bug**

The Media Library has an option called "Replace Media". I wanted to replace one image from there. The first time I clicked on "Replace Media" and select an image. Then I clicked on "Replace Media" again by mistake so I just wanted to close the "choose file" popup. As soon as I close it, the dashboard break and shows "Something went wrong" as you can see on the screenshot below.

**Steps to reproduce the behavior**

1. Go to 'Media Library'
2. Upload one image
3. Click on that image after the upload is done
4. Now click "Replace Media"
5. Select one media from the local disk
6. Again click on "Replace Media"
7. This time do not choose any media and close the select media dialog
8. It will break at this point

**Expected behavior**
It should ignore the "choose media" dialog event and the previously selected image should be there.

**Screenshots**
![Annotation 2020-09-07 215821](https://user-images.githubusercontent.com/12197521/92406565-f4374b00-f155-11ea-95b9-d42c63d66061.png)

**Code snippets**
N/A

**System**

- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: 3.1.4
- Database: tested on MongoDB and SQLite
- Operating system: tested on ubuntu and windows

**Comment by Leonvdk** [comment]
![image](https://user-images.githubusercontent.com/22657711/135857600-e7cc4f79-74cf-4666-864a-714e812f18a0.png)
Same thing happened here!

**Comment by joechipjoechip** [comment]
the crop & replace is buggy as well .. thumbnail/small/medium/large are not regenerated :/
