### ISSUE TITLE
Strapi v3.1.4 fails for new user login

### ISSUE THREAD

**Issue by karthiks** [strapi/strapi#7777]
**Describe the bug**
After successfully registering a new user that gets assigned the default Authenticated role in strapi. When I try to log-in with the new user id as per the [doc](https://strapi.io/documentation/v3.x/plugins/users-permissions.html#login), I see "400 : Bad Request" error message.

**Steps to reproduce the behavior**

1. Sign-in with code below to get the above error message
2. It blows up with with ERROR HTTP RESPONSE 400 (Bad Request)

**Expected behavior**
I should get the jwt token.

**Screenshots**

**Code snippets**
```javascript
import axios from 'axios';
axios.defaults.baseURL = "http://localhost:1337";
axios.defaults.headers.post['Content-Type'] = 'application/json';
try{
    const response = await axios.post('/auth/local',{username, password});
    console.log("I AM NOT LOGGED!!..")
    ...
} catch(err) {
    console.log(err); //I AM LOGGED
}
```

The HTTP response is as below:
```
{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.form.error.email.provide","message":"Please provide your username or your e-mail."}]}],"data":[{"messages":[{"id":"Auth.form.error.email.provide","message":"Please provide your username or your e-mail."}]}]}
```

Used Username: username1
Used Password: username1

**System**

- Node.js version: v12.18.3 (LTS version)
- NPM version: 6.14.6
- Strapi version: v3.1.4
- Database: MongoDB Atlas
- Operating system: Ubuntu 20 (WSL 2 on Windows 10)

**Additional context**
When I see the development logs of strapi, I see the following upon sign-in request
```
Mongoose: users-permissions_role.find({ '$and': [ { type: 'public' } ] }, { skip: 0, limit: 1, projection: {} })
Mongoose: users-permissions_permission.find({ '$and': [ { role: ObjectId("5f532dd4ecf20945dbc40a8f") }, { type: 'users-permissions' }, { controller: 'auth' }, { action: 'callback' }, { enabled: true } ]}, { skip: 0, limit: 1, projection: {} })
Mongoose: core_store.find({ '$and': [ { key: 'plugin_users-permissions_grant' }, { environment: '' }, { tag: '' } ]}, { skip: 0, limit: 1, projection: {} })
[2020-09-07T17:26:14.529Z] debug POST /auth/local (109 ms) 400
```

Question: See 1st line of log. Why is it searching for `type: 'public'`, when it should be 'authenticated'? **Is this the cause for issue?**

**Comment by karthiks** [comment]
Damn!, I mis-interpreted the docs. The [doc](https://strapi.io/documentation/v3.x/plugins/users-permissions.html#login) reads, "The identifier param can either be an email or a username.". 

That led me to interpreting that `identifier` is a placeholder for `username` or `email` attributes. And so I was passing `username` as param instead of `identifier`. I realized this after reading the code for the returned error in the [file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L36)

I'm relieved of this unwarranted pain.. and hope you too are :P 

Thank you for Strapi :)

**Comment by TheDarkStrix** [comment]
I would consider passing it specifically as below : 
`const response = await axios.post('/auth/local',{identifier:username, password:password});`
