### ISSUE TITLE
Why Node 8.9 LTS is not compatible? Why you choose a non LTS version for the minimum requirement?

### ISSUE THREAD

**Issue by renatomattos2912** [strapi/strapi#778]
**Node.js version**: 8.9

**npm version**: 5.5

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: CentOS 7

Why Node 8.9 LTS is not compatible? Why you choose a non LTS version for the minimum requirement?

There are any known issues related to use strapi in node 8.9?

**Comment by abdonrd** [comment]
I am also interested in this!
I think I'll be limited to using LTS. 😕

**Comment by Aurelsicoko** [comment]
If my memories are correct, it's because some parts of the code are not compatible. We are using object spread for example. But, we could easily replace/patch these parts. Can someone (@renatomattos2912, @abdonrd) try to run Strapi using Node 8.9, make the necessary changes and open a pull request?

**Comment by renatomattos2912** [comment]
Yes, for now i'm using node 8.9 without problems, if i find any problem i will try to solve and open a pull request. But i think that is important to keep this project compatible with LTS version cause it make the project more acceptable. Think in a case where the strapi will run in the same server as other APIs and Apps and all this other projects needs latest LTS version, this will be a good reason to not use strapi and in small projects and teams this is a common scenario.
