### ISSUE TITLE
Identifier or password invalid

### ISSUE THREAD

**Issue by shawnnolanjr** [strapi/strapi#7784]
**Describe the bug**
When logging into strapi api via postman it fails, but when hitting the `admin` url to login into strapi dashboard it works fine.

**Steps to reproduce the behavior**

1. in postman hit "http://localhost:1337/auth/local" with creds
`{
    "identifier": "username",
    "password": "password"
 }`

and get error
`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.invalid",
                    "message": "Identifier or password invalid."
                }
            ]
        }
    ],
    "data": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.invalid",
                    "message": "Identifier or password invalid."
                }
            ]
        }
    ]
}`

**Expected behavior**
When trying to login, shouldn't see errors. Logging into admin works fine. But hitting the api endpoint does NOT work.

**Screenshots**
![Screen Shot 2020-09-07 at 9 27 08 PM](https://user-images.githubusercontent.com/8684308/92433125-0c589b80-f151-11ea-862d-9fba2712f355.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v10.16.0
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: mongo
- Operating system: macOS catalina v10.15.6

**Additional context**
Register works fine, but login does not.

**Comment by derrickmehaffy** [comment]
Admin users and normal API users do not share the same login (one cannot be used for the other). For more information please see: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#user-can-t-login-to-the-admin-panel

You will need your normal Admin account to use the Admin panel and another if you plan to use the user generated APIs, eventually we do plan to add an auth provider to the `users-permissions` plugin to allow admin panel users to auth that way but currently there is no option for that.

I'm marking this as closed, but let me know if this is not clear or you believe it was closed in error.

**Comment by shawnnolanjr** [comment]
Ah thanks for the clarification. That being said, this also happens with users that were also registered through the `/auth/local/register` endpoint. I should be able to hit `auth/local` with newly registered users right? Because I also get the same error :(

**Comment by derrickmehaffy** [comment]
I wasn't able to reproduce this using postman on 3.1.4, do you have any other steps to assist in reproducing the issue?

**Comment by shawnnolanjr** [comment]
I don't. The only thing i can think of is that im using mongo locally, NOT via atlas, could there be some differences between that causing admin/login to be different?

**Comment by derrickmehaffy** [comment]
No that wouldn't cause it and I just tested again with a local mongodb database and had no issues. We will need more information to reproduce the bug, can you please try with a fresh project and a fresh database?

**Comment by shawnnolanjr** [comment]
Yeah I suppose I can try a fresh install. Or dig into why this is happening for me more. Thx for the info though.

**Comment by shawnnolanjr** [comment]
ok @derrickmehaffy confirmed this is working with a registered user, not admin. Thanks.
