### ISSUE TITLE
Custom controllers did not work out 

### ISSUE THREAD

**Issue by panyasi** [strapi/strapi#7786]
I've defined an `index` action in the `resources.js` controller, then in `./api/resources/config/routes.json`, when the route path goes to `/resources/index`, the request is 404 not found, but it did work out when the route like `/index` or `/resourses/index/:id`, it is weird that the custom route had to be either without `/resourses` as prefix or with `/resourses` prefix and `:id`.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
