### ISSUE TITLE
Execute bootstrap function before store gets initialized 

### ISSUE THREAD

**Issue by VivekanandanS** [strapi/strapi#7791]
Is it possible to run the bootstrap function before DB are initialized, 
Even before strapi comes online, needs to connect to a remote server to retrieve config and secure strings

**Comment by MattieBelt** [comment]
Hey @VivekanandanS, have you tried to [run strapi from a file](https://strapi.io/documentation/v3.x/getting-started/deployment.html#application-configuration) (server.js), this way you could first retrieve the config and set the ENVs programmatically through `process.env.*`.

For example: 

```js
// server.js

const strapi = require('strapi');

fetch(/* ... */)
  .then(() => {
    process.env.JWT_SECRET = 'secure_string';
    strapi().start();
  });
```

**Comment by VivekanandanS** [comment]
Thank you @MattieBelt  that helps
