### ISSUE TITLE
Strapi Stopped, while using & mapping relations which is not even present in database.

### ISSUE THREAD

**Issue by asharamseervi** [strapi/strapi#780]
**Node.js version**: v9.8.0

**npm version**: v5.6.0

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: Ubuntu

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Strapi is not getting starting. After updating some fields to Content Builder.

**If the current behavior is a bug, please provide the steps to reproduce the problem** I created some Content Field & APIs, I updated existing one to try relations. So, I put some name & selected one to one or one to many, and put some that name which might not exist as a field in selected APIs. On saving, Strapi get restarted & got 502 Bad Gateway errors.

While having looking at terminal, what I see is, here is the screenshot.
![strapi-stopped-502-issue](https://user-images.githubusercontent.com/5942572/37456192-d4c531c2-2864-11e8-939b-45fbc3251616.PNG)

**What is the expected behavior?**
Should input/inserted category or anything is present or not, should validate if it existing or not & produce validation message without executing query.

**Comment by lauriejim** [comment]
Hi @asharamseervi.

You don't make manual update of your models ?

Actually the best way is to go in your Entertainment model file and delete attribute category (and go in you category model and delete the relation to entertainment)

Can you give me the exact steps you did to get this error to be able to reproduce it on my computer.
