### ISSUE TITLE
Issue with graphql plugin

### ISSUE THREAD

**Issue by vinkovsky** [strapi/strapi#7807]
Hello! I`m facing with the problem described in this [article](https://github.com/strapi/strapi/issues/4469) 
When i trying to send query to server, i got different errors. For example for query:
![image](https://user-images.githubusercontent.com/66293881/92548348-ff3aca00-f280-11ea-9ad0-3779f3202cf1.png)
I expect:
![image](https://user-images.githubusercontent.com/66293881/92548357-095cc880-f281-11ea-8536-d5adf55825b4.png)
But after multiple queries i got:
![image](https://user-images.githubusercontent.com/66293881/92548434-3315ef80-f281-11ea-85af-f5ba518bda47.png)

Another example. For query: 
![image](https://user-images.githubusercontent.com/66293881/92548503-59d42600-f281-11ea-870a-1c7c8f35abf9.png)

I expect this behavior
![image](https://user-images.githubusercontent.com/66293881/92548523-6bb5c900-f281-11ea-842a-9dd15c3dc6c5.png)

But got:
![image](https://user-images.githubusercontent.com/66293881/92548547-81c38980-f281-11ea-8099-8befb14467e0.png)

Please, help. This is very annoying

**Comment by vinkovsky** [comment]
If helpful, this is my content type
![image](https://user-images.githubusercontent.com/66293881/92548661-d109ba00-f281-11ea-992c-c15e1b666841.png)
![image](https://user-images.githubusercontent.com/66293881/92548669-d961f500-f281-11ea-92dc-2e5bfadc4316.png)

**Comment by onsombal** [comment]
I'm encountering a similar problem on Strapi-3.1.4 for "query me", but with a slightly different error: "errors": [{"message": "Cannot return null for non-nullable field UsersPermissionsMe.id.",

The GET /users/me endpoint works perfectly. I originally posted this on a closed discussion in "Discussions".

<img width="1426" alt="Screen Shot 2020-09-13 at 7 21 23 PM" src="https://user-images.githubusercontent.com/1588266/93127047-36ebac80-f69b-11ea-9275-1a0b234eb31d.png">

**Comment by derrickmehaffy** [comment]
@onsombal can you please open up a new issue for your bug. Though it may seem similar to this one, you should open up a new bug report following the bug report template.

**Comment by onsombal** [comment]
will do!

**Comment by derrickmehaffy** [comment]
@vinkovsky I was not able to reproduce this, is your project code somewhere we can we take a look? I believe the issue is your `title` is set to required but somewhere in your database you have an entry missing that.

**Comment by onsombal** [comment]
Sorry, I posted this "resolution" shown below on another thread.

I discovered the cause of my issue. My using Firebase for authentication was not adding the newly created User to Strapi. Thus, if there's no User, there's no "me". Sorry for wasting your time. I closed the case I opened on issues.

**Comment by derrickmehaffy** [comment]
Unrelated to this issue @onsombal :wink:

**Comment by vinkovsky** [comment]
Hi! Strage behavior, but when i install strapi from scratch, now queries works fine. However, thanks for the response, i will close this topic
