### ISSUE TITLE
Disable CSRF by default in production environment

### ISSUE THREAD

**Issue by renatomattos2912** [strapi/strapi#782]
**Node.js version**: 8.9

**npm version**: 5.5

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: CentOS 7

**Do you want to request a *feature* or report a *bug*?**
Maybe it is a Bug.

**What is the current behavior?**
I'm not able to create a user in production environment cause i'm getting an "CSRF is required" message.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1 - Run strapi in production mode.
2 - Try to create a user using API or Admin (the same error occurs in both) 
3 - The response error is like bellow:
{
    "message": "CSRF token mismatch: CSRF token mismatch",
    "statusCode": 403,
    "error": "Forbidden"
}

So, what can i do to solve this? I know that i can disable csrf, but there is a better way? Why csrf is requested even in an API call?

**What is the expected behavior?**
I wan't to be able to create users in production.

**Comment by lauriejim** [comment]
Hi @renatomattos2912 Actually the best way for you is to disable `CSRF` option.

**Comment by renatomattos2912** [comment]
Hi @lauriejim, i made the request from both sources (Admin and API) and i had the same CSRF error, but yes, for now i disabled csrf until i understand how to use this correctly.

**Comment by Aurelsicoko** [comment]
The CRSF security is interesting for the users which are using the views and the session system. If you're using the JWT as the authentication system, you're not concerned by the CRSF attack.
