### ISSUE TITLE
Add support order option like CONVERT(field USING bgk) in mysql

### ISSUE THREAD

**Issue by apades** [strapi/strapi#7823]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
The default mysql ordering chinese is messy，but mysql support `select * from table order by convert(cnField using gbk);` to ordering chinese is orderly. I wish the url query '_sort' can bring some option

**Comment by derrickmehaffy** [comment]
Thank you for the suggestion!

**Comment by derrickmehaffy** [comment]
We currently do not plan to add native support for this at this time.

Marking as closed as discussed with @Aurelsicoko
