### ISSUE TITLE
Misleading errormessage "Something went wrong in the model `X` with the attribute `Y`"

### ISSUE THREAD

**Issue by Naxos84** [strapi/strapi#7828]
# Setup
I have to models.
- Page
- Shop

They have a many to many relation to each other.
Each Shop can have multiple pages and each page can be used in multiple shops.

I accidentally removed the `collection`field of the `pages` attribute in `shops` Model
```
//shop.settings.json
{
  ...
  "attributes": {
    "pages": {
      "via": "shops",
      "dominant": true
    }
    ...
  }
}
```

```
//page.settings.json
{
  ...
  "attributes": {
    "shops": {
      "collection": "shop",
      "via": "pages",
    }
    ...
  }
}
```

The error message stated: 
"Something went wrong in the model `Page` with the attribute `shops`"

So I expected that `page.settings.json` has an issue.
But that was not the case.
Luckily the documentation https://strapi.io/documentation/v3.x/concepts/models.html#relations showed me that both attributes needed a `collection` property.

# I expect
 the error message to be the other way round
--> "Something went wrong in the model `Shop` with the attribute `pages`"

**Comment by derrickmehaffy** [comment]
I do agree with this, though I've marked it as an enhancement for now. In this case the page was shown to have an error because it was parsed first, in which it checked for the related field on the related model and found an issue hence the parsing stopped at pages and threw the error there.
