### ISSUE TITLE
Not able to register new users when one user is already created.

### ISSUE THREAD

**Issue by renatomattos2912** [strapi/strapi#783]
**Node.js version**: 8.9

**npm version**: 5.5

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: CentOS 7

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When i try to open the "register new user" page, i'm redirecting to login page.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1 - Run strapi in production mode.
2 - Create your first admin user.
3 - Create a new role and set some authorizations.
4 - Create a new user inside admin (In this case i'm able to create the user but i'm not able to create the password, and if i try to logout and use the "forgot password" flow and try to login with this new user, it put me in a loop of login and logout and i can't really login).
5 - Make a logout and try to create a new user using the register page (In this case, the register page not open, it always redirect to login page.)

**What is the expected behavior?**
I want to create a new user in admin and set the password in this window, or an e-mail needs to send to user to create the pass, i don't know, but now there is nothing happening when i create a new user in admin, cause i don't know how this user set a password.

I want that the register page works and create new users like it should do.

**Comment by 99darwin** [comment]
Same issue here only difference for me is that I'm running on an Ubuntu Digital Ocean instance.

**Comment by daytonmills** [comment]
Same issue here

**Comment by soupette** [comment]
Hi! Currently, the register page on the admin is only accessible if there is no admin user.
You're right we have an issue with the password when you create a user directly from the content manager, it seems that the password is not hashed.


However, until we fix the issue you can either create a new user using POSTMAN 
the endpoint should be (http://localhost:1337/auth/local/register)

```
{
 "username": "username",
 "email": "me@me.com",
 "password": "secure123"
}
```

And then if you set his role as admin in the content manager, the newly created user should be able to login

**Comment by soupette** [comment]
Sorry I didn't mean to close the issue

**Comment by renatomattos2912** [comment]
thanks @soupette , but how can i set a role to this user using postman?

**Comment by Velua** [comment]
I've also found that when modifying a User account in the admin portal created via Postman I'll get a "
An error occurred during record update." toaster notification.

It appears it's making a PUT request to an undefined ID
`http://localhost:1337/content-manager/explorer/user/undefined?source=users-permissions `
This isn't the case when modifying a user in the admin portal, created by the admin portal.
`http://localhost:1337/content-manager/explorer/user/5ab4f069ce90df673b8a1e1e?source=users-permissions`

Will create a proper issue.

**Comment by lauriejim** [comment]
We fixed it and we release it today.

**Comment by 99darwin** [comment]
This is not fixed in 3.0.0-alpha.11.2

**Comment by lauriejim** [comment]
You can now define default role in > Roles & Permissions > Advanced settings > Default role for authenticated users.

So when you use register route, it will automatically apply this role to your new users

**Comment by 99darwin** [comment]
Under Advanced Settings I see two options:
1. One account per email address (on/off switch) currently switched "ON"
2. Enable sign-ups (on/off switch) currently switched "ON"

I'm pretty confident I upgraded from 11.1 to 11.2 correctly as my log prints ```debug Version: 3.0.0-alpha.11.2 (node v8.10.0)``` but maybe I missed something?

**Comment by lauriejim** [comment]
It has been released in alpha.11.3

**Comment by 99darwin** [comment]
I'll wait for 11.3 to be released then. Thank you.

**Comment by lauriejim** [comment]
Oups @99darwin it's `alpha.11.2`.
Can you try to create a new project with `alpha.11.2` and check advanced settings of Role & Permissions

**Comment by 99darwin** [comment]
Yes I see that in a new project, but how do I see it in the one I'm currently working on? Or is there some way to migrate everything from my current project to a new one seamlessly?

**Comment by lauriejim** [comment]
You can check migration guides on the documentation. But be careful if you did update in plugins.

**Comment by commentatorboy** [comment]
Just wanted to add to this current problem.
Because even when I use postman and try to login it does not work.
Please refer to the pictures

![image](https://user-images.githubusercontent.com/1793964/39551816-dcee84ca-4e66-11e8-9e2f-5976c5e93dbe.png)

![image](https://user-images.githubusercontent.com/1793964/39551825-e816907c-4e66-11e8-8329-e08a23dd385a.png)

**Comment by lauriejim** [comment]
@commentatorboy Can you user `raw` format.
Check your permissions in admin panel. Public role have to be authorized to create new user.

**Comment by commentatorboy** [comment]
@lauriejim 
What do you mean by raw format? The input parameters is in json in the body, when I send my request.
I login as an admin while I create a new user.
You can see the first picture, that I login as an admin (which is the first user I created)
The funny thing is that it works when I login through the login page, but not here.

**Comment by lauriejim** [comment]
Did you follow this guide https://strapi.io/documentation/guides/authentication.html ?

**Comment by commentatorboy** [comment]
Yeah it works, but did not want to use ajax calls and just wanted to test it through postman.
But nevermind that. I might have done something wrong in the postman configurations.

**Comment by vaskort** [comment]
What worked for me when trying to create a user through Postman.

1. Login to the admin portal normally.
2. Open Postman and on the Authorization tab choose No Auth
3. Choose Post and the url should be `http://localhost:1337/auth/local/register`
4. On the Body tab click raw and choose application/json (see image below)

<img width="645" alt="screen shot 2018-07-31 at 12 16 31" src="https://user-images.githubusercontent.com/4882345/43456504-a22fbaca-94bb-11e8-88c0-ca18b71858ee.png">

5. Paste your data in the following format:

```json
{
	"username": "test@test.com",
	"email": "test@test.com",
	"password": "test"
}
```

**Comment by scottbarrow** [comment]
documentation is stale as it describes having the username, email, password in a `data` object.
https://strapi.io/documentation/guides/authentication.html#usage has a different JSON shape than above (which works as expected on latest version)

**Comment by shalabh2016** [comment]
Hello,

I think this issue is again visible. After creating first user I am unable to register a new user through JSON api to ".../auth/local/register" and getting error:

`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                }
            ]
        }
    ]
}`

**Comment by lauriejim** [comment]
Hello! If you follow the `registration` documentation you will see you can only send 3 params.
Here you are trying to `create` a user so you will have to use the `POST /users` route instead.
