### ISSUE TITLE
error Error: Duplicated collection name: `strapi_administrator`.

### ISSUE THREAD

**Issue by PhantomxJoker** [strapi/strapi#7838]
After updating from version 3.0.0 to 3.1.4 I got the next error:

error Error: Duplicated collection name: `strapi_administrator`.

Looking into node_modules, i found that collectionName is the same for users and administrators

Somebody have the same issue?

**Comment by derrickmehaffy** [comment]
@PhantomxJoker did you follow the migration guides?


---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
