### ISSUE TITLE
There is no ability to configure the label for repeatable components

### ISSUE THREAD

**Issue by yoshiwarab** [strapi/strapi#7839]
Yes, there is a real difference between...

<img width="237" alt="Screenshot 2020-04-07 at 23 43 14" src="https://user-images.githubusercontent.com/237556/78726315-2d5a5d80-7921-11ea-91c8-297fdfda9a16.png">

... and ...

<img width="443" alt="Screenshot 2020-04-07 at 22 30 23" src="https://user-images.githubusercontent.com/237556/78726353-48c56880-7921-11ea-829c-daed55005dba.png">

In terms of self-explanation. The pain is the ID-for-label when you really want the title of the child relationship to trickle up, if this workaround is to really work.

_Originally posted by @janbaykara in https://github.com/strapi/strapi/issues/2616#issuecomment-610656605_

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
