### ISSUE TITLE
Allow Array field type

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#784]
It would be great to have the `Array` type.

More references:
* https://github.com/strapi/strapi/issues/761: Allow Array of relations objects field type
* https://github.com/strapi/strapi/issues/1169: Error with the Array field type

**Comment by soupette** [comment]
@abdonrd you mean the enum field?

**Comment by abdonrd** [comment]
@soupette no, I mean the `Array` data type from MongoDB:

https://docs.mongodb.com/manual/reference/operator/query/type/#available-types

**Comment by lauriejim** [comment]
You can try to do it yourself updating https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/utils/index.js file to allow `Array` and use it manually in your models. Will not be available in frontend but in backend it's will be OK

**Comment by abdonrd** [comment]
I just sent https://github.com/strapi/strapi/pull/796 so that it is at least supported in the backend.

**Comment by lauriejim** [comment]
Thank you, I let this issue open for the frontend part.

> Merge of your PR is coming

**Comment by abdonrd** [comment]
@lauriejim yes, please! Thanks! 🙂

**Comment by ChristopherJohnson25** [comment]
What's the status on this? Would love to have this flexibility.

**Comment by soupette** [comment]
@ChristopherJohnson25  thanks to @abdonrd the backend supports it but the admin not yet.
There is two parts for the admin to supports this functionality :
- creating a new field type in the `content-type-builder` plugin
- modifying the `content-manager` so it will display the correct form.

If you feel like so maybe you can submit a pull request for the `content-manager`, the plugin has been entirely re-coded in order to make contributions a lot easier which is not yet the case for the `content-type-builder`.

**Comment by abdonrd** [comment]
Add more references in the first post:

* https://github.com/strapi/strapi/issues/761: Allow Array of relations objects field type
* https://github.com/strapi/strapi/issues/1169: Error with the Array field type

**Comment by Torone** [comment]
Well, @soupette even `enum` option would be really nice to have. Thanks

**Comment by derrickmehaffy** [comment]
@Torone enum is enabled on the backend and somewhat on the frontend, you just can't modify the enum in the content type builder. However it seems there are no restrictions or checks on the enum. (At least not with MySQL)

**Comment by abdonrd** [comment]
@lauriejim I don't think is solved, an Enumeration is not and Array...

**Comment by derrickmehaffy** [comment]
Technically @lauriejim adding enum won't fix this issue, this is something that would need some consideration on. Enumeration only allows for a single value which for MySQL is stored as a string.

**Comment by AwakenTheJaken** [comment]
I have been strongly considering using Strapi for some of our future projects and the only thing holding me up from jumping into Strapi is this missing feature. Allowing for matrix type fields is a deal breaker for our team. If I knew more about Node and had more time I would love to help with this, but I unfortunately don't. 

Anyways, just wanted to chime in here and say I too would love to see this feature in a future release!

**Comment by lauriejim** [comment]
@abdonrd Yes that can be a good improvement. 
@soupette can maybe tell us if it's an easy thing to do or not.

**Comment by abdonrd** [comment]
@soupette what do you think? Would it be easy?

**Comment by soupette** [comment]
@abdonrd I can easily develop something like this if @Aurelsicoko agrees

![screen shot 2018-07-27 at 16 47 44](https://user-images.githubusercontent.com/13311463/43327869-de0f3414-91bc-11e8-8899-9675fa12991f.png)

**Comment by abdonrd** [comment]
@soupette sounds great!

And how would you show it if the elements were not a string? Example:

```javascript
[
  {
    "writerId": ObjectId("5aa1efaef2a732375cb64a80"),
    "companyId": ObjectId("5aa1f259fc33c43e5fa8a6f5")
  },
  ...
]
```

**Comment by soupette** [comment]
I didn't thought of that, so yes we should use the inputJSON but it needs to be customised to handle this

**Comment by derrickmehaffy** [comment]
Just figured out that I need this as well. @soupette what are your thoughts on implementing this?

**Comment by Aurelsicoko** [comment]
@derrickmehaffy We need to design the input first. For the first iteration, I think we should only handle static values. The case (proposed by @abdonrd) with the array of IDs which are references to others models is a new kind of relation `manyMorphWay`. I'm not sure we can implement it with Bookshelf...

**Comment by Aurelsicoko** [comment]
@derrickmehaffy I remembered another discussion where I was making sense to not consider this input as a relation. The example was a list of ingredients for a recipe. The array looked like:

- Tomatoes (500g)
- Chocolat (120g)
- Cucumber (1/2)

The diversity of the ingredients is too big to be handled like a relation and the details like 500g or 1/2 make it really impossible. Sometimes it's better the repeat yourself and rewrites (Tomatoes 500g) on every recipe instead of trying to create a relation with tomatoes.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko nice example :laughing: 

But yes for the Array data type I feel as though it should be simple and not over-complicate it as you stated, this should be a standard field type. Although some minor constraints such as allowed data, ect should be considered. I know validations is still a bit out in terms of the roadmap, but I wouldn't want someone sending `Dog poop (1000g)` in a post to my recipe. :wink:

**Comment by Aurelsicoko** [comment]
@derrickmehaffy I can't remember who shared this example, but it killed me. It's almost impossible to find arguments against it 😂

**Comment by derrickmehaffy** [comment]
@Aurelsicoko :wink: now you see my point on how important constraints are lol. Validations are great and all but we shouldn't even offer the option to send bad data including while using the AdminUI :stuck_out_tongue:

**Comment by derrickmehaffy** [comment]
I just noticed btw, the `array` field type was not built into bookshelf? @Aurelsicoko @lauriejim @soupette @abdonrd is this correct?

Was it implemented in mongoose though?

**Comment by Aurelsicoko** [comment]
IMO, the array field is a repeatable-field with only one string (in the repeatable schema). We won't implement two different field types for the same usage. I'm closing the issue, I think I have enough use cases. Please upvote the feature on Product Board (https://portal.productboard.com/strapi/c/24-list-components-repeatable-field) 👍

**Comment by tarikakyol** [comment]
I believe this ticket should be open

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/how-to-iterate-on-all-strapi-js-enum-in-gatsby-and-graphql/521/4

**Comment by RebootGG** [comment]
> IMO, the array field is a repeatable-field with only one string (in the repeatable schema). We won't implement two different field types for the same usage. I'm closing the issue, I think I have enough use cases. Please upvote the feature on Product Board (https://portal.productboard.com/strapi/c/24-list-components-repeatable-field) 👍

We still don't have a clean solution for this and I can't find the feature on your board :(

**Comment by derrickmehaffy** [comment]
Reopening as a feature request

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/allow-array-or-multi-select-field-type
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
