### ISSUE TITLE
Whitespace in user folder name causes problems with plugin installation

### ISSUE THREAD

**Issue by alexsteele110** [strapi/strapi#785]
**Node.js version**: 9.8.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: Windows 10

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Currently unable to install plugins on initial build or through the admin marketplace. Believe it has to do with there being whitespace in my users folder. The folder name is Alex Work and it seems to be looking for just Alex.

The code below happens for each plugin:
```

[2018-03-15T23:55:29.305Z] info Installing content-manager...
module.js:545
    throw err;
    ^

Error: Cannot find module 'C:\Users\Alex'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
[2018-03-15T23:55:29.948Z] debug POST /admin/plugins/install (700 ms)
[2018-03-15T23:55:29.957Z] debug GET f5605e1347775a7276c42bee1847195f.svg (6 ms)
```

**Comment by lauriejim** [comment]
We have to fix this one (about white space) https://github.com/strapi/strapi/issues/709 and it probably fix yours.

I link here an issue on plugin management https://github.com/strapi/strapi/issues/727

**Comment by lauriejim** [comment]
Hi @alexsteele110 can you please give us an update about this.

**Comment by alexsteele110** [comment]
Updated to version 3.0.0-alpha.11.2 and still getting the same error as before

**Comment by alexsteele110** [comment]
`C:\Users\Alex Work\projects\strapi\my-strapi-app`

**Comment by lauriejim** [comment]
Also probably linked to https://github.com/strapi/strapi/issues/724 too

Come from path resolver I think.
