### ISSUE TITLE
Webhooks possibly exposing sensitive user data.

### ISSUE THREAD

**Issue by David-Melo** [strapi/strapi#7856]
**Describe the bug**

When a strapi webhooks is triggered, included in the payload is the user's hashed password. The field is marked as "private", however it seems the webhook process is not respecting the field as being marked "private" and including it in the outgoing payload.

```
{
    "event": "entry.create",
    "created_at": "2020-09-11T19:20:17.384Z",
    "model": "clients",
    "entry": {
        "id": 1,
        "name": "Client 1",
        "created_by": {
            "id": 1,
            "firstname": "Bob",
            "lastname": "Johnson",
            "username": null,
            "email": "bob@test.com",
            "password": "$2a$10$Y0/DBgptZ89vQsU7QCp8jezxs6ZC8RHGzZYtTqakOIp65UCnguFlW",
            "resetPasswordToken": null,
            "registrationToken": null,
            "isActive": true,
            "blocked": null
        },
        "updated_by": {
            "id": 1,
            "firstname": "Bob",
            "lastname": "Johnson",
            "username": null,
            "email": "bob@test.com",
            "password": "$2a$10$Y0/DBgptZ89vQsU7QCp8jezxs6ZC8RHGzZYtTqakOIp65UCnguFlW",
            "resetPasswordToken": null,
            "registrationToken": null,
            "isActive": true,
            "blocked": null
        },
        "created_at": "2020-09-11T19:20:17.333Z",
        "updated_at": "2020-09-11T19:20:17.349Z"
    }
}
```

**Steps to reproduce the behavior**

1. Load a service like https://webhook.site/ to test webhooks
2. Get the test webhook url from the above service.
3. Create a new Strapi Webhook in "Settings > Webhooks" with the test url.
4. In the webhook settings select "Events > Entry > Create"
5. Save the webhook.
6. Create a new entry in any type.
7. Review the payload sent to the test url.

**Expected behavior**

Sensitive user information like "password", should not be included in the webhook payload. Or any field marked as "private" in strapi should not be included.

**Code snippets**

See example json payload above

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: Postgres
- Operating system: Linux Alpine

**Comment by derrickmehaffy** [comment]
Closing as already fixed and will be released shortly: https://github.com/strapi/strapi/pull/7629
