### ISSUE TITLE
Two step (factor) authentication

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#786]
Hi guys,
I think two step (factor) authentication can be very useful for many applications. I recently implement this in LoopBack based on below article:
https://jordankasper.com/two-factor-authentication-with-loopback/

and use this library:
https://github.com/speakeasyjs/speakeasy

Lets talk about this here and add this to https://strapi.io/vote page if other want's this feature too.

**/CC:** @lauriejim @soupette @Aurelsicoko

**Comment by mnlbox** [comment]
It can be a new feature with some setting in admin panel or maybe just a step-by-step tutorial in docs. What's your idea guys?

**Comment by Aurelsicoko** [comment]
It could be integrated as an option in the Users & Permissions plugin. I like the idea but we need to know if the community is asking for this feature or not. We need to keep the product easy to use and simple. If there are only a few people asking for it writing a step-by-step tutorial in the documentation should be enough.

**Comment by mnlbox** [comment]
@Aurelsicoko so I think it's better to add this to https://strapi.io/vote page for vote from community. :thinking: 
Are you agree?

**Comment by Aurelsicoko** [comment]
@mnlbox Yes, @pierreburgy added it 👍

**Comment by lauriejim** [comment]
We link the vote page to this issue.
We will reopen this issue when we will work on it. I you want this feature, feel free to vote on https://strapi.io/vote

**Comment by lauriejim** [comment]
I don't have update this issue and it's not plan. We don't have time for doing this now.

**Comment by derrickmehaffy** [comment]
@mnlbox since its on the vote page I'm sure as its up-voted more it might be considered then.

**Comment by mnlbox** [comment]
Maybe useful: https://passwordless.net/

@Aurelsicoko @lauriejim

**Comment by Pritoj** [comment]
Hey guys,
Can it be done with the user permissions plugin? I would like to help out if I can. I'll probably take some time though :P

P.S. - I realized @mnlbox is the creator for this.. Weird coincidence huh?

**Comment by mnlbox** [comment]
@Pritoj I like this scenario. :wink: 
For testing purpose I think we need print 2FA code on console and a setting option for example called `send 2FA code by:` to select gateway for send 2FA code (for example we can suggest some option here: send 2FA code through mail plugin, web hook call, sms, ...)

**Comment by Pritoj** [comment]
I'm thinking we'll just do it for Authenticator apps first and the later we can figure out how to do it for the rest.

**Comment by Aurelsicoko** [comment]
@mnlbox @Pritoj Don't forget to handle both cases (with and without 2FA)... Nice work btw 👍

**Comment by mnlbox** [comment]
@Pritoj I think this library is more better than other :thinking: 
Take a look to it :wink:

**Comment by mnlbox** [comment]
Also I think it's good if we have two setting for 2FA:
* One system wide setting that admin can set through admin panel.
* And one setting that can be set through API for each user and save in user profile.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko should probably add this to productboard for API Design, I think it will fit in nicely with the purposed changes to the providers and such.

**Comment by Aurelsicoko** [comment]
The card has been created, please upvote it and give us more insights (https://portal.productboard.com/strapi/c/43-support-2fa-via-users-permissions-plugin). I'm closing the issue but feel free to comment on it.

**Comment by tavindersingh** [comment]
> It could be integrated as an option in the Users & Permissions plugin. I like the idea but we need to know if the community is asking for this feature or not. We need to keep the product easy to use and simple. If there are only a few people asking for it writing a step-by-step tutorial in the documentation should be enough.

Is there a tutorial about 2FA in strapi?

**Comment by lauriejim** [comment]
There is nothing about this for now.
We have a ticket here in our roadmap https://portal.productboard.com/strapi/1-public-roadmap/c/43-2fa-via-users-permissions-plugin
Feel free to send a feedback there.

**Comment by ferasallaou** [comment]
Anyone interested in a small fix, I wrote a tutorial about how to enable 2-Step verification
https://medium.com/@FerasAllaou/using-twilio-to-enable-2-step-verification-in-strapi-f9cdeb9f1b46

**Comment by ehtasham89** [comment]
How we can enable 2FA in strapi version 4? Or is their anyway we can generate JWT in our custom collections so we can build our own logic?

**Comment by mpuxted** [comment]
> Anyone interested in a small fix, I wrote a tutorial about how to enable 2-Step verification https://medium.com/@FerasAllaou/using-twilio-to-enable-2-step-verification-in-strapi-f9cdeb9f1b46

Is anyone able to confirm whether this workaround still works? I've read other bits that suggest that Strapi locked everything down when they released the Enterprise edition of Strapi

**Comment by rantoniuk** [comment]
I don't see this being implemented in the non-enterprise tier - and no, not everyone needs SSO.

I see the productboard no longer exists but I could find this on the https://feedback.strapi.io/security/p/support-2fa-via-users-permissions-plugin, but I feel like this issue should be re-opened on the Github open-source issue tracker side, especially given  how old this report is.
