### ISSUE TITLE
Consider moving docs folder to separate repo

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7860]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Recently I cloned strapi's repo for making pull request. it downloaded around `269 MB` data, 
& most of large data seem to be coming from `docs` folder, docs folder size after pull is `232.6 MB`.
So if docs can be moved to another repo, this repo size will decrease & clone will be faster.
Also If you think this is not a right place for this issue, it can be closed.

**Comment by derrickmehaffy** [comment]
@lauriejim @meganelacheny Literally what we just talked about on Friday 🤣 

@aksdevac This is something we are looking into, won't have any decision right away but we will try to keep this issue updated and let everyone know.

There are a number of factors we are looking at besides just the size such as the following:
- Different type of contributor agreement
- Pull request review process
- Documentation review/add requests and flow

Thank you for the suggestion though!

**Comment by derrickmehaffy** [comment]
Closing per:

- https://github.com/strapi/documentation
- https://github.com/strapi/strapi/issues/8898
