### ISSUE TITLE
Forgot localhost password doesn't work: 400

### ISSUE THREAD

**Issue by leoniedarois** [strapi/strapi#7863]
**Describe the bug**
I forgot my password.
In production I used "Forgot password?" and I received an email with which I was able to modify my lost password. However, I cannot do the same with my localhost. He tells me that my address is not valid even though it is since it is the same as in production. It gives me a "400 Bad Request" error with the response "Auth.form.error.email.invalid"

**Steps to reproduce the behavior**

1. Go to http://localhost:1338/admin/auth/forgot-password
2. Enter your email
3. Click on Send Email
4. Devtool : network

**Expected behavior**
Send an email to change the password

**Screenshots**
![image](https://user-images.githubusercontent.com/50202798/92997142-52c34700-f511-11ea-91e8-cdbae9c233b9.png)

**System**

- Node.js version: v12.16.0
- NPM version: 6.13.4
- Strapi version:  Strapi v3.0.0-beta.20
- Database: GraphQL
- Operating system: Windowss

**Additional context**
only in localhost

**Comment by derrickmehaffy** [comment]
`Strapi version: Strapi v3.0.0-beta.20` You are using an unsupported Strapi version, at this time we only suppose the stable releases which are the `v3.0.x` and `v3.1.x`

Please update and test with the latest version and let me know if you still have issues, please note however that the default email provider uses sendmail which needs to be able to send email out on port 25, most residential ISPs block outbound port 25 to prevent spam.
