### ISSUE TITLE
Can't upload file to entity

### ISSUE THREAD

**Issue by francescofact** [strapi/strapi#7866]
Hi, i'm trying to upload an image to one entity.
My model called "agenzie" includes:
```
    "Avatar": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false
    },
```
Then my controller has:
```
               let me = ctx.state.user.idEntita;  //this is the ID of the entity in the table agenzie
		const { data, files } = parseMultipartData(ctx);
		if (files) {
			  await uploadFiles(me, files, { model: strapi.models.agenzie })
                }
```
It is all ok, i find my file in Strapi's "Media Library", but not in my entity.
The file is sent with the name "files.Avatar"

What am i doing wrong?
Thank you

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by francescofact** [comment]
updated

**Comment by derrickmehaffy** [comment]
`Operating system: raspbian` isn't a naively supported operating system due to it's arm architecture and known issues with `libvips`.

Due to this I can officially help you, but can you provide some steps to reproduce and more information about your raspberry pi configuration and I can try to reproduce it locally on one my own?

**Comment by francescofact** [comment]
I think that my code is wrong, but a real bug in the software. 
Is it correct to upload a photo in that way?

**Comment by derrickmehaffy** [comment]
I can't see exactly what type of request you are making to know for sure, can you provide a bit more information?

**Comment by francescofact** [comment]
I'm making a custom controller for updating my avatar of an entity.
I have the entity ID and I post the file with mutipart data request. The file is being correctly received by strapi.
The snipped of code is the part of the controller who takes the entity's id and upload the file to the entity field "Avatar"

**Comment by derrickmehaffy** [comment]
Can you provide the full controller code you are using?

**Comment by francescofact** [comment]
`

'use strict';
const { parseMultipartData, sanitizeEntity } = require('strapi-utils');
const uploadFiles = require('strapi/lib/services/utils/upload-files');

module.exports = {

	async update(ctx) {
		let me = ctx.state.user.idEntita;
		const { data, files } = parseMultipartData(ctx);
		let user = await strapi.query("agenzie").findOne({id:me});
		var post = strapi.services.sanitizer.everythingJSON(data);
		let required = ["nome", "addr", "citta", "cap", "telefono", "descrizione"];
		if (checkNotNull(post, required)){		
		    if (files) {
			  var upp = await uploadFiles(me, files, { model: strapi.models.agenzie })
			
			}
			let query =  await strapi.query("agenzie").update({id: me},{Nome: post.nome, Indirizzo: post.addr, Citta: post.citta, CAP: post.cap, Telefono: post.telefono, Descrizione: post.descrizione});
			return {"message":"ok"};
		} else {
			ctx.throw(400, "Inserire tutti i campi");
		}
	}
};

`

**Comment by francescofact** [comment]
Ok, i found out a working method:
```
if (files) {
	await strapi.entityService.uploadFiles(entity_id, files, {
		model: "agenzie"
	});
}
```
