### ISSUE TITLE
Generated Policy function is not called and 403 response on custom Route

### ISSUE THREAD

**Issue by PrasannaSRK07** [strapi/strapi#7869]
**Generated Policy function is not called and 403 response on custom Route**
I created a new route and attached a policy to it. The policy function contains only console.log(). Still, I get a Forbidden 403 response. If the config object for the route is empty, I get a 200 response

**Steps to reproduce the behavior**

1. Add a new route to routes.json.
2. Generate a new Policy.
3. Attach the policy to the created route. 
4. Send a request to the endpoint and get a 403 response. Also, the Policy function has not been executed. 

**Expected behavior**
The policy function should be executed and the response should be 200. 

**Code snippets**

new route

`{
      "method": "GET",
      "path": "/user/handshake",
      "handler": "user.handshake",
      "config": {
        "policies": ["global::isAdmin"]
      }
    }`

Policy function

`module.exports = async (ctx, next) => {
    console.log("isAdmin")
    return await next();
  };`

**System**

- Node.js version: v12.14.1
- NPM version: 6.4.4
- Strapi version: 3.1
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Have you enabled the route within the users-permissions plugin?

**Comment by PrasannaSRK07** [comment]
> Have you enabled the route within the users-permissions plugin?

No, I did not. Sorry. My bad. I wasn't aware that this should be done on a custom route too. Expected behavior achieved. Thank you.

**Comment by derrickmehaffy** [comment]
Marking as closed then, just a heads up that all routes are by default protected and no permissions are set to allow.

Security is a priority for us. 😉
