### ISSUE TITLE
strapi: command not found

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#787]
**Node.js version**:
v8.9.4
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.11.1
**Operating system**:
Linux Mint 18.1

I have Strapi in another system and it's working successfully but today I try install it in my new laptop. It seems it's installed successfully (because I have a strapi folder in `/home/mnlbox/.npm-global/lib/node_modules/strapi`) but when I run strapi commands like `strapi --version` or `strapi new <project_name>` it's return bellow error:
```
strapi: command not found
```

What's the problem? :thinking: 

**Maybe related:** https://github.com/strapi/strapi/issues/5

**/CC:** @ogrotten

**Comment by lauriejim** [comment]
Are you using `nvm` or another node version manager ?

**Comment by mnlbox** [comment]
No I don't use NVM or other similar tools. I just run this:
```
npm install strapi@alpha -g
```

I run it again now and this is output:
```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/strapi failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
/home/mnlbox/.npm-global/bin/strapi -> /home/mnlbox/.npm-global/lib/node_modules/strapi/bin/strapi.js
+ strapi@3.0.0-alpha.11.1
updated 1 package in 175.111s
```

**Comment by msgeissler** [comment]
@mnlbox Just to make sure: are other global packages working? Maybe there is a problem with the setup and the global packages are not correctly added to your PATH?`(e.g. https://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found)

**Comment by lauriejim** [comment]
Hi @mnlbox you still have your issue ?

**Comment by mnlbox** [comment]
@lauriejim No I can install Strapi successfully now but I have two other issue with CLI tool: #794, #893

**Comment by MMHossaini** [comment]
Try other modules to see if they work. example `ng new app`  It might not be strapi module alone and it might be your operating system..

**Comment by arilishu** [comment]
i have installed strapi, and it's great.
I stopped the service to install graphQL..
Now I try to run npm start but the content type is not updating.
it's says that i have to run strapi develop, but this message appear: The term 'strapi' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ strapi develop
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (strapi:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by srujan12** [comment]
npm install -g strapi@beta

**Comment by derrickmehaffy** [comment]
> npm install -g strapi@beta

We do not recommend installing it globally, if you are trying to create a new project:
`yarn create strapi-app my-project`
`npx create-strapi-app@latest my-project`

If you are trying to run strapi cli commands:
`npm run strapi version`
`yarn strapi version`
(replace `version` with whatever your strapi command is)

**Comment by bastianhilton** [comment]
i had the same issue for Strapi latest 3.4.5. I ran npm install and it fixed the issue.

**Comment by kostikovmu** [comment]
`
sudo npm install strapi@alpha -g
strapi version
`

**Comment by derrickmehaffy** [comment]
> `sudo npm install strapi@alpha -g` `strapi version`

Do not install Strapi globally, this is a practice we haven't recommended since 2017.

Use either `yarn strapi` or `npm run strapi`

**Comment by Saadkc** [comment]
> derrickmehaffy
i run this command now 
how to remove?

I also run npm run strapi but not working

**Comment by HelaGone** [comment]
Have same issue. Using yarn strapi <command> and it always send error command not found. 
I'm using latest version of strapi and yarn

**Comment by derrickmehaffy** [comment]
You need to be in the folder of your project, please use our community channels to ask these types of questions.

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
