### ISSUE TITLE
The plugin strapi-provider-email-sendgrid does not working

### ISSUE THREAD

**Issue by cassianogr** [strapi/strapi#7870]
**Describe the bug**
I'm trying test the email settings for my project.
What I done:

- Set the Roles to enable Email Confirmation
- Installed the plugin by sendgrid, following the documentation
```js
module.exports = ({ env }) => ({
  email: {
    provider: 'sendgrid',
    providerOptions: {
      apiKey: env('SENDGRID_API_KEY'),
    },
    settings: {
      defaultFrom: 'xx',
      defaultReplyTo: 'xx',
    },
  },
});
```
- my .env with APIkey is ok.
- http://localhost:1337/email, is working very good. I receive the email, by POST on /email.
- BUT I dont receive the email when I create a new user, or when I try use forgot password

Should I implements it ? Or Should it is automatic?

- Node.js version: v12.18.3
- NPM version: 6.14.7
- Strapi version: 
```json
"dependencies": {
    "lodash": "^4.17.20",
    "strapi": "3.1.4",
    "strapi-admin": "3.1.4",
    "strapi-connector-mongoose": "3.1.4",
    "strapi-plugin-content-manager": "3.1.4",
    "strapi-plugin-content-type-builder": "3.1.4",
    "strapi-plugin-email": "3.1.4",
    "strapi-plugin-upload": "3.1.4",
    "strapi-plugin-users-permissions": "3.1.4",
    "strapi-provider-email-sendgrid": "^3.1.4",
    "strapi-provider-upload-aws-s3": "^3.1.4",
    "strapi-utils": "3.1.4"
  },
```
- Database: MongoDB
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
Hello,

I have tested this using sendgrid, please ensure your confirmation email template is setup properly with a sendgrid verified sender, example below:

http://localhost:1337/admin/plugins/users-permissions/email-templates
![image](https://user-images.githubusercontent.com/8593673/93108577-d3945700-f667-11ea-92a7-2034cd6fd5a7.png)

![image](https://user-images.githubusercontent.com/8593673/93108690-f6267000-f667-11ea-9238-ed72ae86149f.png)

**Comment by cassianogr** [comment]
Hi!

These config in the email templates were empty (default).

After set these configurations, it not works yet.

No messages log.
No messages anywhere.

Remebering that it works through API, with my sendgrid email account (sender) and this "sender" is not a Gmail account.
![image](https://user-images.githubusercontent.com/39930247/93139091-855a7480-f6b6-11ea-808d-4ac6670f6ce5.png)

![image](https://user-images.githubusercontent.com/39930247/93139198-a8852400-f6b6-11ea-885b-a976bcaddec7.png)


Please, help me.

**Comment by derrickmehaffy** [comment]
We need more information to be able to reproduce your issue, I've followed our documentation to the letter and running a register POST request against my `localhost:1337/auth/local/register` it works fine (as you also mentioned, directly sending an email works fine also)

**Comment by derrickmehaffy** [comment]
As no new information has been provided, marking as closed

**Comment by baganaakh** [comment]
I Have same issue 
Error: Couldn't send test email: Unauthorized.
