### ISSUE TITLE
CreateReadStream is not a function

### ISSUE THREAD

**Issue by Thando-James** [strapi/strapi#7878]
Hi I'm trying to upload a file using GraphQL and I'm getting the following error

```
Error: GraphQL error: createReadStream is not a function
    at new ApolloError (bundle.esm.js:63)
    at Object.next (bundle.esm.js:1004)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at bundle.esm.js:866
    at Set.forEach (<anonymous>)
    at Object.next (bundle.esm.js:866)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
```

The following is my mutation

```
mutation UploadProfile($file: Upload!) {
  upload(file: $file) {
    id
  }
}
```
And the following is how I post my image

```
client.mutate<UploadProfile, UploadProfileVariables>({
        mutation: UploadProfileMutation,
        variables: {
          file: profileProperties.file,
        },
        context: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
      })
```

I don't know why it's not working and I'm not finding the solution on the internet. Please help

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
