### ISSUE TITLE
Could this be a security flaw?

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#7880]
**Describe the bug**
I have a Content Type called “**Campaign**” and it has a one-to-many relationship with another Content-Type called “**Lead**”.
I have configured Campaign to have public graphql access and Lead to have authenticated access

If I query Campaign without passing access token, I get the results as expected. All good.
`
query {
  campaigns (where: {published: true}, sort: "start_date"){
    id
    name
    published
    start_date
    end_date
    description
  }
}
`

If I query Lead without passing access token, I get Forbidden as expected. All good.
`
query {
  leads {
    id
    name
    description
  }
}
`

But if I query starting with Campaign as root and Lead as a child query then I get the Campaign and Leads data even though Lead is marked for authenticated access only.
`
query {
  campaigns (where: {published: true}, sort: "start_date"){
    id
    name
    published
    start_date
    end_date
    description
    leads {
      id
      name
    }
  }
}
`

I should not be getting Leads data.

**System**

- Node.js version: v10.15.3
- NPM version: 6.12.0
- Strapi version: 3.0.1
- Database: PostgreSQL v11.3
- Operating system: Ubuntu 1404 (via vagrant vbox)

**Additional context**

**Comment by derrickmehaffy** [comment]
I believe this topic has come up before but I am having trouble finding the related issue :sweat_smile: 

I'll ping @alexandrebodin to confirm, but currently permissions aren't handled on nested relations like that at the moment. (Gets very complex with deeply nested relation checking.

**Comment by alexandrebodin** [comment]
Yes this is the current intended behaviour. Adding nested permissions is in our ideas for the future. It will certainly be considered when we will start working on the API Token feature.

**Comment by laportem** [comment]
Understood! So the only way to handle this issue right now is make both the Campaign and Lead accessible only for authenticated user.

**Comment by basavarajdodamani** [comment]
> 
> 
> Understood! So the only way to handle this issue right now is make both the Campaign and Lead accessible only for authenticated user.

Hi @laportem , if i may divert a little from your actual question, would you mind sharing the authentication method that you are using, just curious, even i am in need of implementing something similar and cannot adopt JWT token approach. 
Many thanks in advance.
Kind Regards,
Basu

**Comment by laportem** [comment]
@basavarajdodamani 
If you use REST, the Strapi documentation explained how to implement this quite well here
https://strapi.io/documentation/3.0.0-beta.x/guides/auth-request.html#introduction

I use flutter(dart) and graphql. It is simple to do but the coding is a few lines longer. Will share example code on github fairly soon. Still unit testing

**Comment by derrickmehaffy** [comment]
Going to mark this as closed, as the current action is intended (@laportem please still feel free to provide an example if you want)
