### ISSUE TITLE
[Users-Permission Plugin] Permissions should not be case-sensitive

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#7889]
In the plugin users and permissions, if you create a role and go check the permissions, you'll see permissions "findOne" and "findone". Only one should exist.

Also, Role's permissions are automatically created and after that, the front can delete them all if the keys are not defined in the `put` request. The update should not make the permission cease to exist.

**Comment by derrickmehaffy** [comment]
*Grumbles in support process about missing issue template* but it's you @petersg83 I'll let it slide **this time** :wink:

**Comment by sam-pires** [comment]
To give more info. You see "findOne" on the create view (when creating a role), and "findone" in the edit view (when viewing and existing role)

**Comment by alexandrebodin** [comment]
Going to close this as it's not valid anymore in v4
