### ISSUE TITLE
Link creation might not be intuitive in RichText fields

### ISSUE THREAD

**Issue by sam-pires** [strapi/strapi#7890]
**Describe the bug**
In a RichText editor, when creating a link after selecting some content, the default behavior is that it takes the selected content and put it in the (), and not in the [].

[video here](https://drive.google.com/file/d/1onPW5fMa14IzF2nJQBrHYLIk_0EZZ73_/view?usp=sharing
)
The () is where to put the URL
The [] is where to put the text that is going to be linked

The default behavior works well if you first write the URL then add the text, but it's not that great the other way around

**Steps to reproduce the behavior**
1. Create a new entity of a CT which has a RichText field
2. Write some content in the RichText field
3. Select some text to link
4. Click on the link icon in the top of the editor
5. See the behavior

**Expected behavior**
I propose we change it to do it the other way around as it is today. 
when selecting content and creating a link, the content will be put in the [] and a placeholder will be put in the () (ex: https://www.url.com)

But before that, I need to know if it's really something that could help people or if the current behavior is preferred.
What do you think Community and Strapi team? Let me know in the comment?

**System**
- Strapi version: tested on v3.0.0 beta 20 & v3.1.3

**Comment by MattieBelt** [comment]
I agree that the selected text should go into the `[ ]`. You are applying the markup onto the text, just like **Bold**, so the link _applies_ to the text. I have quickly tested a few other markup editors, they al use it the way you suggested.

**Comment by iriekun** [comment]
hello! for me when I view the content from frontend and click the link, the link is appended to my base_url which make the link not working. Is there any solution to this?
