### ISSUE TITLE
Same email of user and admin downgrades admin to a user.

### ISSUE THREAD

**Issue by litehacker** [strapi/strapi#7891]
**Describe the bug**
This is a logic problem in Strapi. When I register authenticated user with the same email address the admin has, the admin loses his authorization as a root admin and becomes the only authenticated user, who can not update content-types. This might also be considered as a security issue. If the admin email is registered as authenticated, to log in as an authenticated user in order to test the functionality, the admin directly downgrades because of email and never becomes root again.

**Steps to reproduce the behavior**

1. create your admin after a quick install.
2. register a new user with the same email as the root user here `http://localhost:1337/auth/local/register/`.
3. try to login as root in `/admin/login`.
4. check if you can add a new content type.

**Expected behavior**
If the admin tries to become a user, they shouldn't lose the authorization.
**System**

- Node.js version: v12.18.1
- NPM version: 6.14.8
- Strapi version: 3.1.4
- Database: SQLite
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment]
Hello, I just tested this on a fresh v3.1.4 application. Here is what I did:

- created a new project using `npx create-strapi-app@latest test7891 --quickstart`
- registered my admin user
- logged out of admin user
- registered by normal user (success)
- logged in as admin user (admin panel)
- created my `article` model with a single field `title` 
- no issue found

![image](https://user-images.githubusercontent.com/8593673/93100999-a0999580-f65e-11ea-9d41-259553ae4be8.png)

**Comment by derrickmehaffy** [comment]
I would suggest you ensure you don't have some global environment variable that starts the Strapi application in production mode, you could try and forcefully use `NODE_ENV=development yarn develop` but to check you can run `yarn strapi console` which will open an interactive shell then run `strapi.config.environment`

![image](https://user-images.githubusercontent.com/8593673/93101253-e6eef480-f65e-11ea-904a-8cd79b593fdb.png)

**Comment by litehacker** [comment]
Hello, thank you for your try. I could not reproduce it. If possible put this issue on hold.

**Comment by derrickmehaffy** [comment]
I'll leave it open for a few days, if you can reproduce it I would love to know :wink:

**Comment by litehacker** [comment]
I managed to reproduce!
`npm install` + `npm start`

**Comment by derrickmehaffy** [comment]
That is intended, the CTB (Content-Type Builder) is disabled unless you have two very specific things:

- `NODE_ENV=development` which is the default if you don't specify an environment
- `develop` command which allows for hot-reloading since model settings are stored in files

the `start` command should only be used in a production or staging environment.

Marking as closed as the action listed as the cause is intended.

**Comment by derrickmehaffy** [comment]
See the following docs:

- https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-develop-dev
- https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-start

**Comment by derrickmehaffy** [comment]
For more information as to why the CTB is disabled in `production` or `staging` environments (likewise with `start` command) see: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
