### ISSUE TITLE
Allow '-' & '/' in enumeration type in content type builder

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7896]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Currently enum type regex is like `new RegExp('^[_A-Za-z][_0-9A-Za-z]*$')`, but in our project there is requirement of having '/' & '-' characters in possible values (like 'C-AR/A'), currently I have added it by manually editing model's json file & it seems to be working. I hope that it would not create any issue with future updates.

**Comment by derrickmehaffy** [comment]
Closing in favor of the tracking issue linked
