### ISSUE TITLE
Custom PUT call returns "Not Found" error even though update is successful

### ISSUE THREAD

**Issue by basavarajdodamani** [strapi/strapi#7897]
PUT call returns "Not Found" error even though update is successful, it works fine with existing PUT method and handler. But for the custom PUT that is used to update the collection based on a custom field, returns Not found upon successful update.

1. Write below route definition:
.......{
      "method": "PUT",
      "path": "/updatedepartments/:department_id",
      "handler": "departments.updateall",
      "config": {
        "policies": []
      }
    },....

2. Controller logic:
const { parseMultipartData, sanitizeEntity } = require('strapi-utils');
module.exports = {
	
	
	async updateall(ctx) {
    const { department_id } = ctx.params;
    console.log(ctx.params);
    let entity;
    if (ctx.is('multipart')) {
      const { data, files } = parseMultipartData(ctx);
      entity = await strapi.services.departments.update({department_id}, data, {
        files,
      });
    } else {
      entity = await strapi.services.departments.update({department_id}, ctx.request.body);
    }

   return sanitizeEntity(entity, { model: strapi.models.departments });
  },
  
};

3. Error:
![image](https://user-images.githubusercontent.com/69140968/93174765-26dfd580-f74c-11ea-842d-e8c6a3c9b471.png)

4. Collection update:
![image](https://user-images.githubusercontent.com/69140968/93174665-fdbf4500-f74b-11ea-8367-af89215b9a39.png)

**Expected behavior**
Same is tested with NodeJS 14.7.0 version, which returns success message.

**Screenshots**
Added above

**Code snippets**
Added above

**System**

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: MONGODB
- Operating system: Windows 10/Windows server 2019

As NodeJS says that most stable version is 12.18.3 we can not upgrade to latest version or 14.7.0. Could you help us resolving this issue at STRAPI side by providing a fix or a patch?

Your inputs are highly appreciated on this.

**Comment by derrickmehaffy** [comment]
Make sure when you created the custom route your custom PUT is above the `:id` one in your routes.json

**Comment by derrickmehaffy** [comment]
As no new information from the user, marking as closed
