### ISSUE TITLE
Default Strapi API is limiting to maximum 100 records only

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#7898]
**Describe the bug:**
Default Strapi API is limiting to maximum 100 records only. We have a Content-Type with more than 100 records but since Strapi has default limit of 100,  the API is only returning max 100 records.

We actually want to make this change on the Strapi app itself, so we don't need to use this [limit param:](https://strapi.io/documentation/v3.x/content-api/parameters.html#limit) on the Front-end..since we have many API's, we don't want to make lot of changes.

**Steps to reproduce the behavior:**

1. Create more than 100 records for any Content-Type
2. See how many records that API is returning
3. It will return only max 100 records

**Expected behavior:**
**There should be a way to configure/overwrite the API limit ourself in the Strapi app.**

**System:**

- Node.js version: `v14.8.0`
- NPM version: `v6.14.7`
- Strapi version: `3.0.6`
- Database: `Mongo`
- Operating system: `MAC`

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/4931

**Comment by kouroshtajalliepour** [comment]
hi has anyone found a soloution for this problem ?

**Comment by derrickmehaffy** [comment]
> hi has anyone found a soloution for this problem ?

Pass a `_limit` and/or `_start` to page through the entries, you can customize the default via a config file: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#api

There is no setting to default to list all of them as that is **highly** advised against for performance reasons, if anything we suggest you *lower* the limit to say default to 20 instead of 100. Use paging: 

https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#limit
https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#start

**Comment by luishk807** [comment]
is it possible we could have this optional? i mean, it should be up to the user to decide the pages or at least provide a way for user to fetch "all" the data they want.

**Comment by derrickmehaffy** [comment]
> hi, is it possible we could have this optional? i mean, it should be up to the user to decide the pages or at least provide a way for user to fetch "all" the data they want.

sure, just pass the `_limit=-1` and it will return everything but we are not going to add that as a configuration option as it's extremely destructive to performance. Else you are welcome to fork the packages to implement it yourself.

**Comment by dogunbound** [comment]
For anyone else, this is where the strapi documentation on this issue lies at:
https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/api.html

**Comment by dogunbound** [comment]
For anyone else who stumbles upon this thread looking mindlessly for the correct solution for a GET request, here is how to do it:
`urlToStrapiApp/collection?_limit=-1`

**Comment by dientran2991** [comment]
> For anyone else who stumbles upon this thread looking mindlessly for the correct solution for a GET request, here is how to do it: `urlToStrapiApp/collection?_limit=-1`

Your solution does not work with Strapi version >=4.0

**Comment by derrickmehaffy** [comment]
> > For anyone else who stumbles upon this thread looking mindlessly for the correct solution for a GET request, here is how to do it: `urlToStrapiApp/collection?_limit=-1`
> 
> Your solution does not work with Strapi version >=4.0

Please see our configuration documentation and the REST reference documentation. They both show how you can change the default/max limits and how to use pagination with v4
