### ISSUE TITLE
Tracking issue - Enumeration values limited by GraphQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#7904]
## **Describe the bug**

This is a tracking issue for all the various references to the limitations of the enumeration field. All other issues, feature requests, and discussions will be closed and redirected here.

## **Context**

Currently within Strapi, the enumeration field is a literal usage of the definition of `enumeration` data type defined [here](https://en.wikipedia.org/wiki/Enumerated_type) in which generally speaking a `boolean` data type is also considered an enumeration type with the value options of `true` and `false`.

For Strapi, due to us supporting GraphQL, we have restricted the types of values that can be used based on the following regex **provided by Facebook, whom built GraphQL**:

> Name :: /[_A-Za-z][_0-9A-Za-z]*/
> GraphQL query documents are full of named things: operations, fields, arguments, directives, fragments, and variables. All names must follow the same grammatical form. Names in GraphQL are case‐sensitive. That is to say name, Name, and NAME all refer to different names. Underscores are significant, which means other_name and othername are two different names. Names in GraphQL are limited to this ASCII subset of possible characters to support interoperation with as many other systems as possible.

http://facebook.github.io/graphql/#sec-Names

## **Current behavior**

Using the above provided regex `/[_A-Za-z][_0-9A-Za-z]*/` values for enums are limited to:

- Must start with a letter, lower or upper **OR** and underscore `_`
- May have an infinite sane length
- May only contain upper or lowercase letters, numbers, and underscores

## **Expected behavior**

Requests from users (though not limited to, this will be updated over time)

- Spaces
- Dashes `-`
- Special characters for different languages
- Alternative symbols

Currently none of the above are allowed, and manually setting them via the model settings *may work* if you don't have the GraphQL plugin installed, **but are not supported** and you do so at your own risk until we find a valid replacement.

## **Related Issues, Feature requests, Discussions, and Forum threads**

Please note, the below are not the limit and additional entries may be linked to this issue, you can find them referenced in the comments.

- Original Discussion (very long): https://github.com/strapi/strapi/discussions/4780
- https://github.com/graphql/graphql-js/issues/936#issuecomment-349887156
- https://github.com/strapi/strapi/issues/4250
- https://github.com/strapi/strapi/issues/3921
- https://github.com/strapi/strapi/issues/3340
- https://github.com/strapi/strapi/issues/2494
- https://github.com/strapi/strapi/issues/1698
- https://github.com/strapi/strapi/discussions/7208
- https://github.com/strapi/strapi/issues/7896
- https://github.com/strapi/strapi/issues/7873
- https://github.com/strapi/strapi/issues/7600
- https://github.com/strapi/strapi/issues/7234
- https://github.com/strapi/strapi/issues/6328
- https://github.com/strapi/strapi/issues/5343

More will be shown below

## **Possible workarounds depending on the use case**

- Using relations such as `oneWay` with a storage model for the values (single select)
- Using relations such as `manyWay` with a storage model for the values (multi select)
- Use a standard enum that fits the regex and map these values out on your frontend (what is currently expected)

### To be very clear, we have no ETA on this, please do not reply asking for one.

**Comment by aksdevac** [comment]
Hi, I think it can be solved if we allow values for enum like shown below (& add it in model's json file) & for displaying in select dropdown value can be used & in db key can be stored.
```ts
enum Locale {
  en_US = "en-US",
  en_GB = "en-GB"
}
```

**Comment by derrickmehaffy** [comment]
yup that was a suggestion made in the original discussion @aksdevac and I think it's a good idea, but we may get some push-back from the rest of the core team about display names within the model settings.

In this case I agree because you can't change these non-display values in production anyway. This solves the issue in the admin, but we also need to figure out how we return these to the user via REST/GraphQL as I'd hazard a guess some will want the display value which GraphQL won't do.

**Comment by aksdevac** [comment]
@derrickmehaffy yes query will return value which is stored in db, but front end can have same mapping. 
& for normal/custom rest service server can also return display name, & as you said it will at-least solve issue within admin.

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/strapi-enumeration-regex/450/2

**Comment by finfa** [comment]
Looks like there is no way in Strapi to create a simple dropdown of human-readable options without the need of extra database tables and joins. Right?

**Comment by derrickmehaffy** [comment]
> Looks like there is no way in Strapi to create a simple dropdown of human-readable options without the need of extra database tables and joins. Right?

Currently no, not yet.

**Comment by iksent** [comment]
Is there any workaround, so we can translate enum's strings directly to Strapi UI for admins/editors/...?

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/how-to-use-russian-symbols/1694/3

**Comment by derrickmehaffy** [comment]
> Is there any workaround, so we can translate the enum's strings directly to Strapi UI for admins/editors/...?
> Maybe use a mapping somewhere in the code?

There is no work around for this right now, other than using relations as mentioned above, in which case you could have a "display field" for those values and a programmatic value

**Comment by finex** [comment]
Hi, I want to add that it could be interesting to behave like Drupal list field type: currently you can insert one value per line for the keys. You could also add the labels separated by a pipe.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/enumeration-field-does-not-allow-spaces/7281/2

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/how-can-i-put-space-and-especial-caracters-in-enumeration-field/10860/2

**Comment by dgutierrez-cafeto** [comment]
Hey guys! I'm facing the same problem and there's a workaround you can use:

Just create a collection type with the options, and use the relation field(one to one or one to many) instead of the enum type.

**Comment by jprudent** [comment]
> Just create a collection type with the options, and use the relation field(one to one or one to many) instead of the enum type.

That's almost good ... What I'm facing now is to make this relation required  but this is not provided out of the box https://github.com/strapi/strapi/issues/557. I have 2 choices : 
1) Following this comment : https://github.com/strapi/strapi/issues/557#issuecomment-752152042 Which works but the error message is "ValidationError"
2) Implementing custom code that does the check with custom error message like in there https://forum.strapi.io/t/required-relation-field/624/2

**Comment by willnode** [comment]
Sorry for necroposting, I like to create a new issue for this but turns out there's a lot of duplicate issues so I wanted to write this up.

This limitation is one of the inconveniences of Using Strapi. But anyway I managed to bypass this filter just by directly modifying its JSON schema. But that also means I no longer can edit using the content-type builder. One example of actual usage from my production web (sorry it's not English)

![image](https://user-images.githubusercontent.com/20214420/148671053-d98fecde-c708-4aba-bac4-fc8c1f525114.png)

It just seems working fine to me and I wonder why there's a filter required until I come to read this issue. Well, you know not everyone is using GraphQL (I don't either) so can you (the Strapi team) make a condition such that if I disable GraphQL, I can bypass this regex filter?

**Comment by derrickmehaffy** [comment]
> 

We originally had this and removed it because of the number of users who complained when they wanted to later use GraphQL and hit issues installing the plugin and running Strapi after.

We opted for this logic following that, it's unlikely we would revert this decision. We are working on a system that would allow a display value in the admin but keeping the regex requirements.

**Comment by willnode** [comment]
Right, didn't think that.

To keep it easy, you might want to create a function where it automatically strips away all invalid characters and save it as a "key" (to somewhere in memory/cache) only for GraphQL querying purposes. Either REST or GraphQL API responses wouldn't have to follow this regex limitation. I don't know if you have any better solution than this.

**Comment by derrickmehaffy** [comment]
> Right, didn't think that.
> 
> To keep it easy, you might want to create a function where it automatically strips away all invalid characters and save it as a "key" (to somewhere in memory/cache) only for GraphQL querying purposes. Either REST or GraphQL API responses wouldn't have to follow this regex limitation. I don't know if you have any better solution than this.

Logically I agree with the regex as "enumeration" is a very specific type of value that should be treated as "machine safe", other use-cases likely should have new field types or usage of relations instead (the manyWay is great for this).

If the issue revolves around the display of the value in the admin then we know how to handle that using a display value vs regular value and do plan to add it. We just didn't have time during the initial v4 development. The plans are already complete on that and it just needs to be built basically.

**Comment by cloakedninjas** [comment]
Strapi could do a better job with the error messaging at least... 

`The value does not match the regex.` doesn't tell me how to fix the issue, so I have to go Google it

**Comment by derrickmehaffy** [comment]
fixed by: https://github.com/strapi/strapi/pull/12200
