### ISSUE TITLE
Field names can clash with API code, causing errors when creating records

### ISSUE THREAD

**Issue by tcrammond** [strapi/strapi#791]
**Node.js version**:

`9.8.0`

**npm version**:

`5.7.1`

**Strapi version**:

`3.0.0-alpha.11.1`

**Operating system**:

OSX El Capitan

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If you make a field with a name that clashes with a Model/orm method or property _(might be something else, this is a guess)_, you will be unable to create records using the content type UI. 

In my case, I was trying to use a field named "set" on one of my content types. I could not create any more records. Updates still worked fine.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

1) using the content type builder, create a content type with a field named "set". Field type doesn't matter, string will work.
2) Try to create a record using the content type UI. The UI will show flash message "An error occurred during record creation"

The server console reports:

`error: undefined`

The http response reports:

```
{"statusCode":400,"error":"Bad Request","message":[{"messages":
[{"id":"This this,set,is,not,a,function is already taken","field":["this","set","is","not","a","function"]
}]}]}
```

**What is the expected behavior?**

Either field names like this are prevented from clashing with API code, or are not allowed to be entered in the content type manager at all.

**Comment by lauriejim** [comment]
Hi @tcrammond thank you for this reporting.
