### ISSUE TITLE
Media window crashes when modifying images in Select tab

### ISSUE THREAD

**Issue by PkerUNO** [strapi/strapi#7914]
**Describe the bug**
I've come across a bug when modifying existing images from within a "Create an entry page", causing the whole page to crash and needing a full refresh, losing any unsaved input.

**Steps to reproduce the behavior**

1. Have some images already in the media library
2. Click on a Collection Type that has a Media field set to allow multiple images
3. Open the Media window to select some images
4. Search for a string and select some of the images that are filtered
5. Click on the "selected" tab
6. Edit the first image, changing its name
7. Edit the second image
8. Error appears

**Expected behavior**
I expect to be able to edit the images I am about to select for my collection type

**Screenshots**
Step 2:
<img width="1436" alt="Screenshot 2020-09-16 at 00 07 51" src="https://user-images.githubusercontent.com/4022491/93273915-ed8d8100-f7b0-11ea-867d-2b9a6c59f937.png">

Step 5:
<img width="1436" alt="Screenshot 2020-09-16 at 00 08 32" src="https://user-images.githubusercontent.com/4022491/93273949-ff6f2400-f7b0-11ea-9a23-b3b31f4631b2.png">

Step 8:
<img width="1436" alt="Screenshot 2020-09-16 at 00 05 17" src="https://user-images.githubusercontent.com/4022491/93273963-07c75f00-f7b1-11ea-83a3-d8edebb77fc6.png">

**System**

- Node.js version: 12.8.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: PostgreSQL
- Operating system: MacOS 10.15.6/Safari 13.1.2

**Additional context**
This only happens inside the "Selected" tab, which I'm using because editing one photo resets the search - so I'd like to pick out all the photos I want first, then head to the Selected tab to edit them before adding them to the new entry.

**Comment by soupette** [comment]
This issue has been fixed with the `3.1.5` release can you try to upgrade your app and check if the problem persists?

**Comment by PkerUNO** [comment]
@soupette That fixed it. Thank you very much!
