### ISSUE TITLE
Special characters are not allowed in enum fields values

### ISSUE THREAD

**Issue by vynarim** [strapi/strapi#7919]
I want to create a component with enumerated field
If the values of the enumerated fields contains special characters (such as French accents) there is an error message. If I remove the special characters, I can create the field

![image](https://user-images.githubusercontent.com/20367460/93334431-38e17700-f825-11ea-8305-3e96d125bfb6.png)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7904
