### ISSUE TITLE
Api Documentation Plugin 404 (Not Found)

### ISSUE THREAD

**Issue by eliasko** [strapi/strapi#7928]
**Describe the bug**
I installed the API documentation plugin as described at the Strapi docs. Installation works fine and the plugin appears in the admin panel. The thing is, when i hit the "Open Documentation" button, it leads to a "Not Found" page.

![Bildschirmfoto 2020-09-17 um 01 00 41](https://user-images.githubusercontent.com/8115668/93400946-4593b880-f881-11ea-9918-a32b170d79a9.png)

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: MariaDB
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
Uhhhh `Strapi version: 1.3.4` are you sure that's the correct version? That version hasn't been supported in over 3 years...

**Comment by eliasko** [comment]
Sorry, it was a typo. I mean 3.1.4

**Comment by lauriejim** [comment]
Hello! Can you please give us a procedure to reproduce your issue.
I created a fresh new app, installed the plugin and everything is working fine.
So I suppose you did something special that caused this issue.
To be able to help you, I will need more information

**Comment by derrickmehaffy** [comment]
It would appear the docs weren't built? @eliasko do you have a link to your project somewhere?

**Comment by eliasko** [comment]
Sorry, the project is private. I can't provide a link. To be honest, I don't know what i did special. The thing is, on my local enviroment it works. Pushing it online, everything works as on my local machine except the documentation.

**Comment by derrickmehaffy** [comment]
If you navigate to the documentation plugin on the left menu there should be an option to regenerate the docs.

**Comment by derrickmehaffy** [comment]
As no new information from the user, marking as closed.

**Comment by xantiagoma** [comment]
Hi @derrickmehaffy 
I'm having this same issue.
The `full_documentation.json` is working as expected and I can load it to an external Swagger client.
the change I did that brokes documentation was changing a controller to
```js
const _ = require('lodash');

module.exports = {
  async find(ctx) {
    // const { request, response, app, originalUrl, req, res, socket } = ctx;
    const results = await strapi.services.label.find(ctx.query);

    const byLang = _.groupBy(results, 'lang');

    const values = _.mapValues(byLang, list => {
      const byKey = _.groupBy(list, 'key');

      return _.mapValues(byKey, '[0].value');
    });

    return values;
  }
};

```
so it returns data in this way:
```json
{
   "en":{
      "app":"Aplicación 2",
      "label":"Label",
      "v":"3.2.0"
   },
   "es":{
      "name":"Nombre",
      "app":"Aplicacion"
   }
}
```
The model is simple just has:
![Screen Shot 2021-02-02 at 7 49 13 PM](https://user-images.githubusercontent.com/1217807/106682092-c680f180-658f-11eb-9ce2-84346e1988f9.png)

**Comment by derrickmehaffy** [comment]
@xantiagoma for cases like this you will probably need to manually override the documentation for that control and construct the expected response. My examples are probably outdated as I haven't reviewed them in a long time but here is a hobby project where I am making some modifications:

https://github.com/canonn-science/CAPIv2-Strapi/blob/development/api/apreport/documentation/2.4.0/overrides/apreport.json

We have a section in the documentation that covers this: https://strapi.io/documentation/developer-docs/latest/plugins/documentation.html#overriding-the-suggested-documentation
