### ISSUE TITLE
Keycloak Provider login results in request-compose timeout error

### ISSUE THREAD

**Issue by inafis** [strapi/strapi#7929]
When our users attempt to login to our application using Keycloak as the provider, Strapi throws the following error:

/callback/oauth?error=request-compose%3A%20timeout

This happens on an inconsistent basis, basically every other login attempt. 

In our setup Strapi is running within a container on a Kubernetes cluster. We've debugged on the Nginx ingress side to increase proxy buffers as we previously saw the length of the id/access token being returned from keycloak was causing issues there. 

What we believe is happening now is that the Strapi http server may also be timing out as indicated by that error. We would like to leverage the strapi.server.setTimeout method to turn this off however we've come across conflicting/confusing information on how to do so. 

Per #5869 one method of doing this is to call the strapi.start() method inside of config/server.js and update the timeout in the callback. This works in that it updates the timeout but causes subsequent issues with our pipeline, preventing us from testing. 

The primary issue is that calling the start method inside of server.js of course attempts to start strapi, which we don't want during our jenkins builds as it tries to connect to a database and fails. Secondly, adding this start method in server.js and then running for example strapi start results in a conflict because two instance of strapi are trying to start. 

What is the correct way to access the strapi server object AFTER the server has already started so that the timeout can be updated? & Are we on the right track debugging the request-compose timeout to begin with.

Any guidance is greatly appreciated, thanks!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
