### ISSUE TITLE
Support for Mysql 8 password encryption (caching_sha2_password)

### ISSUE THREAD

**Issue by gustawdaniel** [strapi/strapi#7930]
In MySQL 8 there is a changed the manner of encryption password:

When I use password encrypted in a new way then I have error:

```
error Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client at Handshake.Sequence._packetToError (/home/daniel/pro/up/strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
```

For legacy MySQL 5.x passwords it works great.

There is a fragment of docs about it

> https://docs.oracle.com/cd/E17952_01/mysql-8.0-en/mysql-nutshell.html

> https://docs.oracle.com/cd/E17952_01/mysql-8.0-en/upgrading-from-previous-series.html#upgrade-caching-sha2-password

So `mysql_native_password` was replaced by `caching_sha2_password` and Strapi is not compatible with it.

**Comment by gustawdaniel** [comment]
I found that this is no problem with Strapi but MySQL package:

> https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0

There is an open pull request:

https://github.com/mysqljs/mysql/pull/1962

**Comment by derrickmehaffy** [comment]
Yes it's an issue with the mysql package (due to mysql having closed source providers) and also with Knex.js
