### ISSUE TITLE
env() on plugin's config file breaks whole plugin

### ISSUE THREAD

**Issue by darron1217** [strapi/strapi#7935]
**Describe the bug**
I was trying to use `env()` on plugin's config file.
On project root's config file, we can retrieve `env` depedency. But when I try it on plugin's config file, the whole plugin's REST api stops working. (returns 404)

**Steps to reproduce the behavior**

1. Create plugin `strapi generate:plugin test`
2. Create config file `./plugins/test/config/sms.js` with content below
```
module.exports = ({ env }) => ({
  senderNumber: env('SMS_SENDER_NUMBER', '010-1234-1234'),
  provider: env('SMS_SERVICE_PROVIDER', 'ncp'),
});
```
3. From now, cannot access to routes defined on plugin
ex)
routeConfig
```
    {
      "method": "GET",
      "path": "/",
      "handler": "test.index",
      "config": {
        "policies": []
      }
    },
```
GET request `/test` returns 404 not found
(This should return 401 forbidden or 200 ok)

**Expected behavior**
I expected plugin's config folder work as same as root's config folder

**Screenshots**
None

**Code snippets**
I provided sample code above

But whenever I change the content of config file as below, it works
```
module.exports = {
  senderNumber: '010-1234-1234',
  provider: 'ncp',
}
```

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: mongo@latest
- Operating system: macOS Catalina

**Additional context**

**Comment by derrickmehaffy** [comment]
Please properly fill out the issue template and please try to provide us more information so we can assist you.

Closing for now and will reopen when you have updated with more information.

**Comment by darron1217** [comment]
I was in a hurry, sorry for not being specific

I've updated issue, please check

**Comment by derrickmehaffy** [comment]
Ah now I understand, the `env()` function only works within the root `./config` directory and for plugins you will still need to use `process.env.YOUR_VAR` instead.

**Comment by derrickmehaffy** [comment]
@alexandrebodin maybe we can bind this function to the global Strapi so it can be used elsewhere?

**Comment by alexandrebodin** [comment]
Due to the loading order this will not work properly. Right now prefer adding your config to the ./config/plugins.js file to use the env and not in the extensions anymore.

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
