### ISSUE TITLE
Additional "Add to Dynamic Zone" buttons for ease of entry on longer documents 

### ISSUE THREAD

**Issue by MRDRMUFN** [strapi/strapi#7940]
_Didn't see this on the roadmap._

Requesting the ability to add a dynamic zone component between existing components in the list and at the very least a button at the top to prepend the component.

Current dynamic zone behavior requires that components be added at the end, and on longer documents, this results in having to chase the component to the top. Hopefully, you didn't need more than one component and didn't make any misclicks when bringing it to the top.

**Comment by derrickmehaffy** [comment]
Closing in favor of https://github.com/strapi/strapi/issues/7941 as they are similar and the other issue contains more information.
