### ISSUE TITLE
Hide or exclude fields in query

### ISSUE THREAD

**Issue by Rupacerupesh** [strapi/strapi#7944]
I get all the properties and i would like to remove the unwanted properties like created_by,updated_by and timestamps.How to hide or exclude fields in query?

`{
    "client_ip": "Velit quo libero sun",
    "verifier": "Voluptas ut sit sun",
    "created_by": {
        "id": 1,
        "firstname": "admin",
        "lastname": "admin",
        "username": null
    },
    "updated_by": {
        "id": 1,
        "firstname": "admin",
        "lastname": "admin",
        "username": null
    }
}`

**Comment by derrickmehaffy** [comment]
Closing as duplicate: https://github.com/strapi/strapi/issues/7177
