### ISSUE TITLE
Hierarchical relation

### ISSUE THREAD

**Issue by arnorhs** [strapi/strapi#795]
**Node.js version**:
8.10.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.11.1

**Operating system**:
ubuntu 16 LTS

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when i add a relation on an existing content type referencing the same content type, the server fails to restart.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. create a content type
2. save it with a field
3. edit the content type again
4. add a relation field called "parent" with a many-to-1 relationship with the same content type
5. save

after this the server never restarts and my console just says 
[2018-03-17T16:16:51.603Z] error Something went wrong in the model `Categories` with the attribute `parent`
[2018-03-17T16:16:51.607Z] error Cannot read property 'nature' of undefined

**What is the expected behavior?**
server restarts and content type works as expected

**Comment by lauriejim** [comment]
Hello @arnorhs . I would like to try your use case to give you to give you the best answer. Actually I don't have the time for it. I will do my best to did it rapidly.

**Comment by arnorhs** [comment]
ok, it can be reproduced in the latest version as well. i can also push a repro case to a remote branch on my fork if that would be easier for you.

**Comment by arnorhs** [comment]
i'm guessing nobody has gotten around to this - i might have a swing at it myself if i have some time this weekend.

**Comment by arnorhs** [comment]
Hey there, no I had some desperate attempt at looking at it, but I wasn't familiar with the structure of strapi yet, so I got nowhere.

I just tried on the latest version of strapi and the issue seems to be resolved, and this ticket is closed, so I'm happy! Thanks!
