### ISSUE TITLE
Internal server error when uploading to media library

### ISSUE THREAD

**Issue by AryanGharshi** [strapi/strapi#7955]
I deployed the strapi project to google cloud following the strapi documentation. I have a number of collection types and I tested text input. it works fine, however an error is thrown whenever I try to upload images. I get a 500 Post error, and this is what the chrome console says: 

![Screenshot 2020-09-19 145212](https://user-images.githubusercontent.com/24868059/93667756-91fd1500-fa88-11ea-87a4-c87392eb2f75.png)
![Screenshot 2020-09-19 145212](https://user-images.githubusercontent.com/24868059/93667626-bb697100-fa87-11ea-9190-9921fc9d92fe.png)

edit: 
I accessed the google platforms logging system and see that the error is caused by the fact that the file system is read-only. I don't really recall setting such permissions when following the documentation so I'm kind of stumped. any help would be greatly appreciated. 
here is the error:
![console error](https://user-images.githubusercontent.com/24868059/93672309-3cd1fb00-faaa-11ea-8a22-62654e324291.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by justinjamesp1988** [comment]
got the solution for above issue ? i'm facing the same !!

**Comment by marino696** [comment]
me too. i need a solution. i tried setting up aws s3 and loading up all the vars into heroku to no avail.
