### ISSUE TITLE
Unable to PUT by unique field other than ID on Mongoose

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#7956]
**Describe the bug**
When running `await strapi.services.myAwesomeModel.update({ myOwnUniqueField }, input)`, it works fine until I start trying to save relationships. 

I will get the error: 
```
TypeError: Cannot read property 'myRelationshipField' of null
    at ..../node_modules/strapi-connector-mongoose/lib/relations.js:90:33
```

**Steps to reproduce the behavior**

1. create a model with a unique field _and_ a relationship field
2. from a service, `.update()` the model
3. give it in the first param an object containing your unique field (and not `id`)
4. set an array of ID's on the relationship
5. see that it crashes

**Expected behavior**
I'd expect I can update my model from other fields as to only `id` without it throwing errors

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:v12.18.3
- Strapi version: 3.1.4
- Database: mongo 4.2 (Atlas)
- Operating system: macOS

**Additional context**
When I find for the strapi `id` first and update with that, the relationship saves just fine. But now I have to call `findOne` before `update` which is overhead and prone to bugs.

**Comment by derrickmehaffy** [comment]
This is intended for now, you can't save/update/create relational data from the parent, when creating/updating a parent, all relational fields must use IDs (either directly for one2one/ect or an array)

Please ensure you follow the bug report templates, I know they can be annoying and don't apply half the time, but it is a hard requirement within our [Contributor's guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I'm going to mark as closed for now, please do let me know if you need more information.

**Comment by laurenskling** [comment]
I'm sorry for not using the template, that's me being lazy. Not very nice of me. I'll do better next time :)

My bug is actually a bit different from your answer, I am not creating the data, I'm setting the IDs.

So I'm updating my model via my `myOwnUniqueField` field, which works, but when `input` contains:

```
{
  title: "example",
  myRelationshipField: ["5f65f23d1c6d2f0656354495"]
}
```

this will crash with the given mongoose error. When I don't use my own field on the parent model (`myOwnUniqueField`) but `id` the same code will not crash

**Comment by laurenskling** [comment]
I rewrote my issue into the format @derrickmehaffy :)

**Comment by derrickmehaffy** [comment]
Indeed appears I misread the issue, reopened

**Comment by derrickmehaffy** [comment]
I was able to get this to work fine with a custom controller/route:

**PATH:** `./api/article/config/routes.json`

```
// New PUT route
    {
      "method": "PUT",
      "path": "/articles/test/:test",
      "handler": "article.updateTest",
      "config": {
        "policies": []
      }
    },
// Below this is the existing PUT route
    {
      "method": "PUT",
      "path": "/articles/:id",
      "handler": "article.update",
      "config": {
        "policies": []
      }
    },
```

**PATH:** `./api/controllers/article.js`

```js
'use strict';
const { parseMultipartData, sanitizeEntity } = require('strapi-utils');

module.exports = {
  /**
   * Update a record.
   *
   * @return {Object}
   */

  async updateTest(ctx) {
    const { test } = ctx.params; // Changed id to test as the unique field in my model is called test

    let entity;
    if (ctx.is('multipart')) {
      const { data, files } = parseMultipartData(ctx);
      entity = await strapi.services.article.update({ test }, data, { // Again here changed id to test
        files,
      });
    } else {
      entity = await strapi.services.article.update({ test }, ctx.request.body); // Again here changed id to test
    }

    return sanitizeEntity(entity, { model: strapi.models.article });
  },
};
```

In doing so I am able to call `localhost:1337/articles/test/art1` with the payload of:

```
{
    "comments": [1,2,3]
}
```

Which properly updates the information (tested using SQLite but about to swap over to mongo to confirm as well)

![image](https://user-images.githubusercontent.com/8593673/93686830-e0e98100-fa6d-11ea-9ccd-753a7c6e18e7.png)

Swapping out the relations to `[4,5,6]`:
![image](https://user-images.githubusercontent.com/8593673/93686846-f78fd800-fa6d-11ea-8fdc-36503efb35df.png)

**Comment by derrickmehaffy** [comment]
Further testing with Mongoose using the following:

URL: `PUT localhost:1337/articles/test/art1`

Payload:

```json
{
    "comments": ["5f6653858bdc7f8841d6520b", "5f6653898bdc7f8841d6520c", "5f66538d8bdc7f8841d6520d"]
}
```

Yields an error:

```
[2020-09-19T18:57:39.915Z] error TypeError: Cannot read property 'comments' of null
    at /home/dmehaffy/Development/test7956/node_modules/strapi-connector-mongoose/lib/relations.js:90:33
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/home/dmehaffy/Development/test7956/node_modules/strapi-connector-mongoose/lib/relations.js:89:68)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.update (/home/dmehaffy/Development/test7956/node_modules/strapi-database/lib/queries/helpers.js:15:18)
    at async Object.update (/home/dmehaffy/Development/test7956/node_modules/strapi/lib/services/entity-service.js:91:17)
    at async Object.updateTest (/home/dmehaffy/Development/test7956/api/article/controllers/article.js:21:16)
    at async /home/dmehaffy/Development/test7956/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async module.exports (/home/dmehaffy/Development/test7956/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:86:3)
    at async /home/dmehaffy/Development/test7956/node_modules/strapi-utils/lib/policy.js:68:5
    at async /home/dmehaffy/Development/test7956/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-09-19T18:57:39.915Z] debug PUT /articles/test/art1 (11 ms) 500
```

But if I use the normal PUT route with the objectID it works fine with the same payload, so the bug here is the query is not functioning properly when not using an objectID, and only happens on mongoose.

**Comment by laurenskling** [comment]
Thanks for diving in deep! <3

**Comment by darron1217** [comment]
I've encountered same issue here.

In my opinion, the code below contains 2 problems.
1. It plucks only primary key as query condition (which might be null in this case). Therefore result is also null.
2. `entry` variable (the result of findOne query) can be null even if it is UPDATE action. The code below should handle if `entry` is null.

https://github.com/strapi/strapi/blob/16a7be23de19b75b2bf667ecf26748971da1a477/packages/strapi-connector-mongoose/lib/relations.js#L84-L91

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
