### ISSUE TITLE
Quick Start Guide not matching the UI

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#7963]
**Describe the bug**
The document at https://github.com/strapi/strapi/blob/documentation/docs/v3.x/getting-started/quick-start.md#2-create-an-administrator-user states  **` Click Ready to start.`**, while it should be **`> CREATE YOUR FIRST CONTENT-TYPE`**

**Screenshots**

![image](https://user-images.githubusercontent.com/2712405/93716583-a7cd1180-fb3e-11ea-9fc0-f75d5cb94d04.png)

**Additional context**
Please note that the workflow from his point on has also been changed - the click on the **`> CREATE YOUR FIRST CONTENT-TYPE`** results with the **`Create a collection type`** pop-up automatically:

![image](https://user-images.githubusercontent.com/2712405/93717047-35a9fc00-fb41-11ea-94a7-2b6001c981d4.png)

This changed behavior is the reason I did not create a PR - describing this workflow could be someone's strong opinion

**Comment by adriatic** [comment]
It seems that you decided to ignore the second part of my bug report (repeated below). This is your prerogative, so I am bringing it up again for the unlikely case that you missed it 😄 


**Additional context**
Please note that the workflow from his point on has also been changed - the click on the **`> CREATE YOUR FIRST CONTENT-TYPE`** results with the **`Create a collection type`** pop-up automatically:

![image](https://user-images.githubusercontent.com/2712405/93717047-35a9fc00-fb41-11ea-94a7-2b6001c981d4.png)

This changed behavior is the reason I did not create a PR - describing this workflow could be someone's strong opinion

**Comment by derrickmehaffy** [comment]
This is intended, a collection type is a content-type

- Content type
  - Collection Type
  - Single Type
  - Component
  - Dynamic Zone

**Comment by adriatic** [comment]
You misunderstood me, sorry for being in sufficiently precise: I am pointing out that the dialog with the prompt “create collection type” pops up automatically, while the document tells you that you need to invoke it. There is no need to continuing to maintain this discrepancy between the guide and the actual behavior.
