### ISSUE TITLE
Guide for deployment to Heroku is wrong

### ISSUE THREAD

**Issue by Devalo** [strapi/strapi#7964]
**Describe the bug**
Following the docs at https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html#_2-login-to-heroku-from-your-cli
at step 4, we need to replace the content of our database.db file at config/environments/production/database.json.
This file does not exist. Trying to add the file with the correct content from the guide doesn't work.

If we follow the guide from A to Z, the application will store data in sqlite instead of postgres.
This means the database will be wiped whenever the heroku dyno restarts.
The guide most likely belong to an older version.

**Expected behavior**

The file we need to edit is database.js in config/
The file consists of a JS-object that looks the same as the JSON in the guide.
We need to replace or edit this file with the postgres content. 

**Code snippets**
This code is an example which solves the problem, and let me use sqlite for dev, and heroku postgres for prod.

``` 
if (process.env.NODE_ENV === 'development') {
  module.exports = ({ env }) => ({
    defaultConnection: 'default',
    connections: {
      default: {
        connector: 'bookshelf',
        settings: {
          client: 'sqlite',
          filename: env('DATABASE_FILENAME', '.tmp/data.db'),
        },
        options: {
          useNullAsDefault: true,
        },
      },
    },
  });
} else {
  module.exports = () => ({
    defaultConnection: "default",
    connections: {
      default: {
        connector: "bookshelf",
        settings: {
          client: "postgres",
          host: process.env.DATABASE_HOST,
          port: process.env.DATABASE_PORT,
          database: process.env.DATABASE_NAME,
          username: process.env.DATABASE_USERNAME,
          password: process.env.DATABASE_PASSWORD,
          ssl: { 
            rejectUnauthorized: false 
          } 
        },
        options: {}
      }
    }
  });
}
```

**System**

- Node.js version: 12.18.0
- NPM version:6.14.4
- Strapi version: 3.1.4
- Database: sqlite and Postgres
- Operating system: mac and heroku dyno

**Comment by derrickmehaffy** [comment]
Hello, I'm guessing you found the guide: https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html#_2-login-to-heroku-from-your-cli from a Google search, you are looking at an old beta guide and the updated one is located here: https://strapi.io/documentation/v3.x/deployment/heroku.html

I'm going to mark this as closed, but do feel free to respond if you have more issues :)
