### ISSUE TITLE
Strapi API creation

### ISSUE THREAD

**Issue by bjcodetesting** [strapi/strapi#7971]
I am trying to build an API using Strapi and  which has the fallowing json structure.
[
"someValues" : {
    "valuesMeta": [
      {
        "id": "id1",
        "title": "Titile1",
        "type": "type1"        
      }
    ]
  }
]

I am able to create different JSON structure but the above I am not able to create above. can someone please let me know how to create it using Strapi Collection type.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
