### ISSUE TITLE
Error 'field cannot have keys not specified in the object shape' when trying to update a Content type

### ISSUE THREAD

**Issue by kpirumyan** [strapi/strapi#7974]
**Describe the bug**
Cannot save a content type if it has an indexed field at *collection.settings.json* file. 

Strapi fields have some validation rules. See https://strapi.io/documentation/v3.x/concepts/models.html#validations. I found that index validation is absent in the code (/node_moduels/strapi-plugin-content-type-builder/validations/types.js). And this throws the error on CT 'Save'. To solve this issue I patched the module and added validation rule for indexes. 

[content-type-builder-index-validation.txt](https://github.com/strapi/strapi/files/5256378/content-type-builder-index-validation.txt)

**Steps to reproduce the behavior**

1. Create a content type
2. Create a field (for example, a Text field)
3. Manually add {"index": true} to the attribute of this field in *collection.settings.json*.

```
{
  "kind": "collectionType",
  "collectionName": "customers",
  "info": {
    "name": "customer"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "index": true
    }
  }
}
```
4. Add a new field.

**Expected behavior**
The type should be saved and the index should be created in mongodb.

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: MongoDB 4.2.3
- Operating system: Win 10

**Comment by lauriejim** [comment]
Hello thank you for reporting this, 
Can you please create a pull request and link it to you issue.
Thank you.
We will review the PR soon as possible.

**Comment by kpirumyan** [comment]
Hi,

Here is the link to pull request #8022.

I have another question. Should strapi support indexing for relational fields? It doesn't work right now, because when I add the {"index": true} record to the *collection.settings.json* file and then update the content type, that record is deleted.

**Comment by lauriejim** [comment]
I ping @alexandrebodin to answer this question.

**Comment by lauriejim** [comment]
And thank you for creating the PR, I really appreciate it.

**Comment by alexandrebodin** [comment]
We are already talking on the PR :)

**Comment by dawnerd** [comment]
I'm running into this issue when adding custom indexes and see the PR was closed. Is there any plans to fix this?

**Comment by alexandrebodin** [comment]
Hi @dawnerd we are goign to be fixing this in an upcoming feature but it might will take a few week to release. If you want you can make a PR. I gave some details in the PR but the contributor didn't hav time to finish so if you want to work on it let me know ;)
