### ISSUE TITLE
Server won't start (windows and sharp)

### ISSUE THREAD

**Issue by julienvedebe** [strapi/strapi#7979]
**Describe the bug**

Script failed to start after a create project using strapi.

**Steps to reproduce the behavior**

1.Create a project with yarn create nameofproject I choose custom with mongodb and my correct configurations, everything works correctly
2. Go to project folder
3. Launch it : yarn develop
4. Errors occurs : Something went wrong installing the "sharp" module

**Expected behavior**
Script should launch strapi.

**Screenshots**
See screenshots

**System**

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.1.5
- Database: Mongodb (local)
- Operating system: Windows 10

**Additional context**
I saw some similar issues but reporter explain that he fixes his issue with installing again windows-build-tools, I installed again node and have it install all necessary tools (python ...)
![strapi_issue](https://user-images.githubusercontent.com/12135264/93823163-a7796700-fc61-11ea-8483-257953533cb5.PNG)

**Relative issue**
https://github.com/strapi/strapi/issues/7267

**Comment by derrickmehaffy** [comment]
Have you followed the steps it gave to you?

**Comment by julienvedebe** [comment]
Hello sorry but wich steps do you mean ?

**Comment by derrickmehaffy** [comment]
These specifically: 

![image](https://user-images.githubusercontent.com/8593673/93932301-d0870f80-fcd4-11ea-9654-c81f9e4901ef.png)

As I believe this issue to be one with Sharp and not directly with Strapi itself. I was unable to reproduce the issue on any of my Mac, Linux, or Windows machines

**Comment by julienvedebe** [comment]
Hello, yes I did that but the issue is not on the installation part but on the usage so removing and installing again works and then fail on start as you can see on my screenshot it mention "the parameter is incorrect" with a path.

**Comment by derrickmehaffy** [comment]
Out of curiosity are you using WSL?

**Comment by julienvedebe** [comment]
I was in the past but remove it, just use node.js shell for now.

**Comment by derrickmehaffy** [comment]
I've tried to spend some time checking on ways to reproduce this and I am currently unable to (even with a fresh windows 10 install on a virtual machine)

**Comment by julienvedebe** [comment]
Thanks you, can I help on my side any debug that I can do ? or simply remove using of that lib ?

**Comment by julienvedebe** [comment]
I finally found the issue I install again sharp lib with unsafe perm : npm install --unsafe-perm and now it is working.

Thanks for help
