### ISSUE TITLE
Select coherent items/entries fast

### ISSUE THREAD

**Issue by MostafaHassan** [strapi/strapi#7988]
It would be nice to be able to select coherent items/entries fast by selecting one item and then holding down shift before selecting another.

Especially because it is so easy to miss that checkbox and then having to start all over again.

**Comment by alexandrebodin** [comment]
Hi thanks for the insight. You can submit your ideas here: https://portal.productboard.com/strapi/1-roadmap/tabs/2-under-consideration :)

**Comment by derrickmehaffy** [comment]
Going to close this one, but please feel free to create the feature request here: https://feedback.strapi.io/
