### ISSUE TITLE
Text overflow in roles and permissions

### ISSUE THREAD

**Issue by zeroby0** [strapi/strapi#799]
**Strapi version**:
3.0.0-alpha.11.1

**Do you want to request a *feature* or report a *bug*?**
CSS bug.

**What is the current behavior?**
![screen shot 2018-03-18 at 12 30 57 pm](https://user-images.githubusercontent.com/16903044/37563511-5955f49a-2aa8-11e8-8298-938ed4655123.png)

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Add a very long description and it overflows. Also, while trying to shorten the description, I found out that all of the fields are non editable. And the cancel button does nothing. This is understandable because it's still in Alpha.

Is there a list where users can report bugs in alpha, so you guys can easily find them later?

**Comment by soupette** [comment]
Thanks @zeroby0 for reporting this if you see other stuff like this don't hesitate to report it!
