### ISSUE TITLE
Media Library - Cropped images are heavy

### ISSUE THREAD

**Issue by octoduchilli** [strapi/strapi#7990]
Hello,

When images are cropped with strapi, it is normal that they are heavy ?
Strapi blog example: [video](https://www.loom.com/share/10789baf57844ac49f52a3dc305494cf)
In this video, the base image size is 451Kb and the cropped size is 4Mb.

Thanks !

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by octoduchilli** [comment]
**Describe the bug**
When I crop an image, the cropped one is heavy

![image](https://user-images.githubusercontent.com/38497518/93988091-9e36ea00-fd88-11ea-8845-74d296eccede.png)

In this exemple my original image size is 168Kb and the cropped one size is 2Mb

**Steps to reproduce the behavior**

1. Install strapi quickstart
`npx create-strapi-app my-project --quickstart`

2. Go to
[http://localhost:1337/admin/plugins/upload](http://localhost:1337/admin/plugins/upload)

3. Upload an image.jpg

4. Crop (whatever the size) and duplicate the previous image.jpg

**System**

Node.js version: 12.18.4
yarn version: 1.22.5
Strapi version: 3.1.5
Database: SQLite
Operating system: MacOS

**Package.json**

```
{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.1.5",
    "strapi-admin": "3.1.5",
    "strapi-utils": "3.1.5",
    "strapi-plugin-content-type-builder": "3.1.5",
    "strapi-plugin-content-manager": "3.1.5",
    "strapi-plugin-users-permissions": "3.1.5",
    "strapi-plugin-email": "3.1.5",
    "strapi-plugin-upload": "3.1.5",
    "strapi-connector-bookshelf": "3.1.5",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "3b2a2d52-8efa-4910-bf75-489e3ff1df13"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

Thanks !

**Comment by alexandrebodin** [comment]
@octoduchilli do you mind verifying the real file size on disk ? I think we might have a conversion issue in the size attribute 🤔

**Comment by octoduchilli** [comment]
@alexandrebodin Of course I checked, and its the real size ! 🤷‍♂️

The original : 
![image](https://user-images.githubusercontent.com/38497518/93998141-73eb2980-fd94-11ea-8cc5-be891757b802.png)
The cropped one : 
![image](https://user-images.githubusercontent.com/38497518/93998189-81a0af00-fd94-11ea-9523-0e89d64226eb.png)

**Comment by alexandrebodin** [comment]
@petersg83 if you can have a look while you are check the upload plugin ;)

**Comment by petersg83** [comment]
Thank for sharing your issue ! I created a fix for it, it should be good for the next release :)
