### ISSUE TITLE
WTF? Rich Text is backwards!?

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#7991]
As stated, when I create a Rich Text type it starts out writing from right to left!? I'm not in the bleedin' middle east here ... I'm in Denmark.

And I can't for the life of me figure out HOW to reverse it ... this simply lacks any kind of great UX experience.

I'm out ... this is lame!

**Comment by derrickmehaffy** [comment]
Thank you for the feedback, but I have trimmed out some of your message as it does not follow our [Code of Conduct](https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md). If you are willing to, please provide a detailed bug report and it can be looked at.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by blaasvaer** [comment]
I’m in a hurry, so have no time to spend debugging your ’system’. I was expecting to get things done … and not ending up providing free debugging support.

So, if you’re not willing to look into ‘What could cause the editor to start out in RTL mode’ then I can’t be of more help.

A small hint though:

1. Create a Page type
2. Add a Text field and a Rich Text field
3. Save

Now, create a New Page … fill in the title and TAB (a lot of times) until you enter the Rich Text field … and BAM there’s your RTL bug!

Good luck.

Mvh / Best Regards

Sam Blåsvær
Senior Fullstack Architect
20 70 33 60
sam@blaasvaer.dk

Ådiget 16
2610 Rødovre

www.blaasvaer.dk
