### ISSUE TITLE
Category (many to many relation) produce 10MBytes+ response (admin dashboard and front-end)

### ISSUE THREAD

**Issue by immunity20** [strapi/strapi#7994]
Hello, I have genres and movies collections with many to many relation between them.
I used strapi tutorial to install strapi and create collections.

**The problem:** I have genres (20 documents) and movies (11.000 docs) with many to many relation between them (I created just like strapi tutorial suggests). So when I try to query strapi for movies or genres the responses weights around 10MBytes because (as I've just found out) strapi autoPopullate

**Reproduce**: Follow strapi tutorial to create strapi project, collections and relations and add 10K docs.

Front end or back end queries to fetch movies or genres takes too long time and from request details as you can see it downloads 10MBytes+ of data

Also in front-end when i try to fetch only 10 movies i still get too many MB of data downloaded (the response json contains an array of 10 movies which have a property genres with id of all the movies (~ 10000 movies) so its 10*10000 and thats probably what cause the issue.

~Is there a way to avoid that?~
I have added autoPopullate: false  in movie model and this fix the problem. Is this the correct solution for project with many docs?

![category_problem](https://user-images.githubusercontent.com/17274326/93934965-90537b80-fd2c-11ea-9ae2-d1a39776cecc.png)

**Comment by derrickmehaffy** [comment]
Can you please follow the bug report template (sorry I should have mentioned it)

**Comment by immunity20** [comment]
> Can you please follow the bug report template (sorry I should have mentioned it)

Hey I found out how to speed up the requests and reduce the size. It's the autoPopullate feature of strapi ( I have added false to movies model and now it loads fast (the movies collection))

So for project with many docs in a collection (which has many to many relation with another collection) this is the way to go? canceling the default autoPopullate ?

**Comment by alexandrebodin** [comment]
Hi, Yes for now this is the way to go. We will review the REST API to make it more performant. There are multiple options we will discuss like:

- limiting the retruned data in the relations
- not default populate and sub routes e.g /movies/1/categories
- a query parameter to specify the fields or populate you want e.g /movies?fields=id,categories or /movies?populate=categories(limit:50) ...

**Comment by derrickmehaffy** [comment]
This should be fixed in v4 already on the list view, we are working on a relations perf fix right now in the edit view that will change the relations loading to a lazy loading method but this issue specifically references the list view so gonna mark it as closed for now.
