### ISSUE TITLE
admin login page asks me an email adress instead of a username

### ISSUE THREAD

**Issue by Nic0mrt** [strapi/strapi#7995]
Expected behavior : login on my admin development page.

Screenshots : 
asks me an email instead of a username as usual.

<img width="493" alt="Capture d’écran 2020-09-22 à 23 54 38" src="https://user-images.githubusercontent.com/62882251/93941650-2ee0dc00-fd2f-11ea-9106-3aae14e485d0.png">

System

    Node.js version: '12.16.3'
    NPM version: '6.14.7'
    Strapi version: 3.1.5
    Database: MongoDB
    Operating system: MAC OS

Since the beginning i was logging with a username and now it asks me to fill in an email. When i try to recover my password nothing happens...

**Comment by aksdevac** [comment]
This change was introduced from 3.1.x, username support is dropped now see #7128, have you checked 3.1 migration guide?
[see guide](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html#migration-guide-from-3-0-x-to-3-1-x)

**Comment by Nic0mrt** [comment]
Thx I saw that it was intended. But now even if i put my email adress I have the message "Invalid credentials" and when i try to recover my password, i don't get any message in my email so it's still impossible for me to connect..

**Comment by aksdevac** [comment]
@Nic0mrt ok if you have access to database check using robo 3t or any other client or check using mongo shell (`db.getCollection('strapi_administrator').find({})`), also email is now case sensitive, & also verify `isActive` & `blocked` field values.

**Comment by Nic0mrt** [comment]
I have access on mongo Atlas online is it also ok ? 
isActive is true and blocked is false..
still invalid credentials when i copy/paste email...

**Comment by aksdevac** [comment]
ok are you connecting to live db on Atlas from your local ? make sure it is using correct database,
it should work if email & password is correct.

**Comment by derrickmehaffy** [comment]
`isActive` should be true. Related to the lack of email, if you are running it locally, the default email provider `sendmail` uses outbound port 25 to send email and most consumer ISPs block this port to prevent spam.

**Comment by Nic0mrt** [comment]
thx for your answers.. I'm ok now it helped me alot !
