### ISSUE TITLE
 Cannot send email with mailgun provider

### ISSUE THREAD

**Issue by Rigel772** [strapi/strapi#7998]
**Describe the bug**
While trying to send an email I am geting error:
```
[2020-09-23T05:59:55.792Z] error Error: Forbidden
    at IncomingMessage.<anonymous> (/strapi-mail/node_modules/mailgun-js/lib/request.js:327:17)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2020-09-23T06:01:18.599Z] debug GET /contact-form (1181 ms) 500

```
**It is not clear to me how to activate the email provider... In strapi 3.1.5 there is no "cog" icon on email plugin UI.**

**Steps to reproduce the behavior**

1. Install strapi quickstart
`npx create-strapi-app my-project --quickstart`
2. install mailgun plugin
`yarn add strapi-provider-email-mailgun `
3. create config/plugins.js file:
```module.exports = ({ env }) => ({
    // ...

    email: {
        provider: 'mailgun',
        providerOptions: {

            apiKey: 'c28db76b7f88e05337XXXXXXXXXXXXX-cb3791c4-1c8079b3',
            domain: 'my.domain', //Required if you have an account with multiple domains
           
        },
        settings: {
//             defaultFrom: 'email@email.com',
//             defaultReplyTo: 'email@email.com',
        },
    },
    // ...
});`

```
4. add Public role permissions
(in my case is a custom plugin, but when I try the /email endpoint I got an 404)
`[2020-09-23T06:18:15.524Z] debug GET /email (3 ms) 404
`

5. execute
 ```
   await strapi.plugins['email'].services.email.send({
      to: 'to@emal.com',
      from: 'oskar@my.domain',
      subject: 'Hello world',
      text: 'Hello world',
      html: `<h4>Hello world</h4>`
    });
```

**Expected behavior**
I expect an email to be sent

**System**

- Node.js version: 12.13.1
- yarn version:1.22.5
- Strapi version: 
- Database:SQLite
- Operating system: Linux Manjaro

**package.json**
```
{
  "name": "strapi-mail",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "sqlite3": "latest",
    "strapi": "3.1.5",
    "strapi-admin": "3.1.5",
    "strapi-connector-bookshelf": "3.1.5",
    "strapi-plugin-content-manager": "3.1.5",
    "strapi-plugin-content-type-builder": "3.1.5",
    "strapi-plugin-email": "3.1.5",
    "strapi-plugin-upload": "3.1.5",
    "strapi-plugin-users-permissions": "3.1.5",
    "strapi-provider-email-mailgun": "^3.1.5",
    "strapi-utils": "3.1.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "190b1738-6a52-4736-940b-00b95d2dc10f"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by alexandrebodin** [comment]
Hello, you config is the right one. Now you configure in the files and there is no need to go in the interface. The forbidden means your credentials are not good. Make sure you are using the right domain and not the sandbox to send emails ?

**Comment by Rigel772** [comment]
Thanks for reply.
I think I know where the problem is...
I am in Europe, when you are using mailgun from EU you need to modify the url.
When I test it with curl:
**this is forbiden**

 ```
curl -s --user 'api:c28XXXXXXXXXXXXXXXX8079b3' \
    https://api.mailgun.net/v3/my.domain/messages \
    -F from='Excited User <mailgun@my.domain>' \ 
    -F to=person@gmail.com \  
    -F subject='Hello again' \
    -F text='Testing some Mailgun awesomeness!'
Forbidden%  
```
**and this works fine**
 ```
curl -s --user 'api:c28db7XXXXXXXXXXXXXX91c4-1c8079b3' \
    https://api.eu.mailgun.net/v3/my.domain/messages \
    -F from='Excited User <mailgun@my.domain>' \
    -F to=person@gmail.com \
    -F subject='Hello again' \
    -F text='Testing some Mailgun awesomeness!'
{
  "id": "<20200923133254.1.XXXXXXXXXXX@my.domain>",
  "message": "Queued. Thank you."
}%   
```
pay attention to the **eu** in url
`https://api.eu.mailgun.net/v3/my.domain/messages`
I guess the url is hardcoded in the mailgun provider plugin somewhere for US... how can I change it to EU?

**Comment by Rigel772** [comment]
It works now.
Users from EU need to add another option in config/plugins.js:
**host: 'api.eu.mailgun.net'**
 // ...

    email: {
        provider: 'mailgun',
        providerOptions: {

            apiKey: 'c28db76b7f88e05337XXXXXXXXXXXXX-cb3791c4-1c8079b3',
            domain: 'my.domain', //Required if you have an account with multiple domains
            host: 'api.eu.mailgun.net'
           
        },
        settings: {
//             defaultFrom: 'email@email.com',
//             defaultReplyTo: 'email@email.com',
        },
    },
    // ...
});`

Thanks for pointing me in right direction ;)
