### ISSUE TITLE
Unable to change host

### ISSUE THREAD

**Issue by Luukth** [strapi/strapi#800]
**Node.js version**: v8.10.0

**npm version**:  5.6.0

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: Ubuntu 16.04.4 LTS

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I edit the config file "server.json" in the development or production folder. The host option doesn't get applied. When I enter a domain, strapi will still say it started on `http://localhost:1337` Also the files-upload plugin gets affected by this. When I click the little eye icon. A new tab opens and directs me to `http://localhost:1337/uploads/ab16c0bc34874dd69d4daeced2aa503c.png` instead of the domain.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Change host in "server.json" 
2. Restart strapi

**What is the expected behavior?**
Strapi should output the correct host name in the console not `http://localhost:1337`. Also the file-upload plugin should direct users to `<host>/uploads/ab16c0bc34874dd69d4daeced2aa503c.png` not `http://localhost:1337/uploads/ab16c0bc34874dd69d4daeced2aa503c.png`

**Comment by garytube** [comment]
same issue here... 

you need to set a process.env HOST = 'your-domain.com'

and restart the server

**Comment by Luukth** [comment]
I can confirm that @garytube workaround works.

**Comment by Luukth** [comment]
@lauriejim should I close this issue?

**Comment by lauriejim** [comment]
Yes please :) @Luukth
