### ISSUE TITLE
Preview of audios and videos is not rendering

### ISSUE THREAD

**Issue by prernagp** [strapi/strapi#8004]
**Describe the bug**
I am trying to make a blog post using Strapi editor. When I upload media files like image, audio, video etc, then it gets displayed as a markdown. 

```
> audio
![mozart_2.mp3](https://spl-cms.s3.amazonaws.com/mozart_2_3b7ed7b864.mp3)

> video

![videoplayback.mp4](https://spl-cms.s3.amazonaws.com/videoplayback_a85dd9c12d.mp4)
```

But when I switch to preview for the same all I can see the preview as broken links.

audio
![mozart_2.mp3](https://spl-cms.s3.amazonaws.com/mozart_2_3b7ed7b864.mp3)

video
![videoplayback.mp4](https://spl-cms.s3.amazonaws.com/videoplayback_a85dd9c12d.mp4)

**Steps to reproduce the behavior**

1. Go to "rich text editor"
2. Click on 'add media in editor'
3. Add audio and video in editor.
4. Click on "switch to preview" button. 
4. See error :- You will not be able to see the preview of audio and video files.

**Expected behavior**
Just like images, the editor should be able to preview audio and video files.

**Screenshots**
![Screenshot from 2020-09-23 15-45-49](https://user-images.githubusercontent.com/16304668/93999944-14047b00-fdb4-11ea-98fa-ca9e0b8d3fd7.png)

![Screenshot from 2020-09-23 15-48-05](https://user-images.githubusercontent.com/16304668/94000084-49a96400-fdb4-11ea-8449-939884a95be3.png)

**System**

- Node.js version: 14.11.0
- NPM version: 6.14.8
- Strapi version:     "strapi": "3.1.4",
- Database: postgresql
- Operating system: Ubuntu 18.04.5

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI AFAIK there isn't much we can do on this can we since those are stored in AWS-S3, the client would need to fetch the files and cache them locally to actually see the preview?

**Comment by soupette** [comment]
There's not much we can do, reading audio and video files in markdown is kinda not supported. I have found a plugin for markdown-it : [markdown-it-video](https://www.npmjs.com/package/markdown-it-video) that enables youtube videos and more that a user can install in the editor but that's all what's supported.

However, you can read audio file with html:

<img width="1136" alt="Screenshot 2020-09-24 at 09 43 46" src="https://user-images.githubusercontent.com/13311463/94115750-76a85600-fe4a-11ea-9915-906af65e39e7.png">

**Comment by derrickmehaffy** [comment]
This may be something when we move over to an actual rich-text style field, I know @alexandrebodin had some ideas in the past but I'm not sure when we plan to implement something besides markdown (though I remember something about us avoiding storing HTML directly in the database)

**Comment by soupette** [comment]
I remember addressing the issue of script injection such as
```
<script>alert('Hello Soupette')</script>
```

But the lib we are using as an option to prevent such behaviour and also supports some HTML so the preview is a bit better than it used to be. However, audio and video preview is not very common in markdown for instance the GitHub md preview that we are currently using does not support it.

I think that we can close this issue, don't you @derrickmehaffy ?

**Comment by derrickmehaffy** [comment]
Yeah for now will mark as closed until we have a larger discussion about rich text in general.
