### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Terrybrar32** [strapi/strapi#8014]
**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
Closing as there is no information in the bug report
