### ISSUE TITLE
Configure the view redirect to the first content type

### ISSUE THREAD

**Issue by sebapag** [strapi/strapi#8021]
Hi, I'm currently working with strapi 3.1.3. When I run the server in develop mode and I try to configure the view for a generic content type with the appropriate button sometimes it loads a completely different content type.

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Windows local machine

Thanks in advance for your support!

**Comment by soupette** [comment]
This issue has been fixed can you upgrade your app to the latest stable version (3.1.5)?

**Comment by sebapag** [comment]
Yes! It works, thank you very much for your support!

**Comment by alexandrebodin** [comment]
Closing then :)
