### ISSUE TITLE
[Media Library] upload duplicates + endless loading

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#8023]
**Describe the bug**
I have a third-party provider (aws here).
1) On Chrome: When I upload a large file (400Mo) it loads indefinitely. If I wait long enough and refresh, the file is correctly shown in the ML

2) On Firefox: When I upload a large file (400Mo) it loads indefinitely. If I wait long enough and refresh, the file is shown twice in the ML

**Steps to reproduce the behavior**
1. Setup the aws upload provider
2. Upload a large file (let say 400 Mo)
3. See that the upload never ends
4. Refresh the app after a while, see that the file is correctly there (but twice is you use firefox)

**Expected behavior**
I expect the upload to be finished at some point and to not have duplicates

**Possible bug cause**
The backend don't send the response fast enough, the front, then, ends the connection and never receives the response.

In the Firefox case, because its doesn't have the response fast enough, the browser "retry" the request, thus upload the same file twice.

**Bug fixes propositions**
- Use axios instead of request in the front, and set a bigger timeout
   **Edit:** I tried with axios but it doesn't seem to change anything
- Make the back send 200 after it received the file from the front and before it uploaded it to the provider. (Downsides: 1) the user won't see the file in the ML right away 2) if the upload fails the user won't know. Upsides: 1) the interface if faster)

**System**
- Node.js version: 10.21
- NPM version: 6.14.4
- Strapi version: 3.1.5
- Database: SQLite
- Operating system: macOS

**Comment by soupette** [comment]
@petersg83 I am really not in favour of the option 2 : 
> Make the back send 200 after it received the file from the front and before it uploaded it to the provider. (Downsides: 1) the user won't see the file in the ML right away 2) if the upload fails the user won't know. Upsides: 1) the interface if faster)

as it can create bugs in the both the client's application and also the admin panel. Take the following case: A user uploads a files correctly to the server so the server sends the 200 and then start uploading the file to the provider. In the meantime the user saves an entry where this file should be attached, at some point there's an error when uploading from the server to the provider which will result in linking a file to entry that does not exists. If the client's application does not have a way to handle the case where an entry might not contain a file his app will crash.

**Comment by petersg83** [comment]
Actually the entry is saved in strapi only after the upload to the provider is done, so this case would not be possible.
However I agree option 2 takes more work

**Comment by derrickmehaffy** [comment]
I believe this is fixed in v4 but if not we can reopen it.
