### ISSUE TITLE
Absolutely IMPOSSIBLE to find information on how to SWITCH to using MySql!?

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#8024]
**Describe the bug**
Can find no information in the docs on how to switch from the default 'sqlite' to 'mysql' anywhere.

**Comment by alexandrebodin** [comment]
Hello, please follow the issue templates when opening issues so we can respond in the best possible way.
You can also have a look at our [code of conduct](https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md) too so you understand better what is expected when opening issues and discussing on this github repository :) 

FYI, you can change the configuration in your `config/database.js` file to match the mysql options like showed in this examples: https://strapi.io/documentation/v3.x/concepts/configurations.html#database. 

Closing as issue is solved
