### ISSUE TITLE
Need an advise about a model data organisation

### ISSUE THREAD

**Issue by mrikirill** [strapi/strapi#803]
Hi there!

I have 5 tables: Vehicle, Driver, Account, Company, User[Strapi system table]
Table User is linked (1:1) with Account.  
I want to create that users of the same account can see only their "account's data".
For example User1 and User2 linked with Account1 they can see vehicles, drivers, companies associated with Account1.
Should I create relationships for each tables with Account (1:m) for example:
- Account 1:m Driver, 
- Account 1:m Vehicle
- Account 1:m Company

And for every request to api get accountID from User and than to return the data which are linked with this accountID.

Please suggest me a good solution for this case.

**Comment by lauriejim** [comment]
Hello @mrikirill ! What are relation between Drivers Vehicles and Companies ?

You will probably have to customize the query to get you accounts with a deep populate.
Check this link  http://mongoosejs.com/docs/populate.html#deep-populate.

**Comment by mrikirill** [comment]
Hi @lauriejim 

>What are relation between Drivers Vehicles and Companies ?

The potencial database scheme should be like that [please see the screenshot](https://screencast.com/t/sXQzYRYjp)
What do you think, I'm right to link every tables with Account or I need to connect only User table ?

>You will probably have to customize the query to get your accounts with a deep populate.

It looks what I'm looking for.

**Comment by lauriejim** [comment]
I think your relation between account and drivers is not necessary.
In fact it's really depend of your use case. And what look like your organization.

**Comment by mrikirill** [comment]
>I think your relation between account and drivers is not necessary.
>In fact it's really depend of your use case. And what look like your organization.

I think so, thanks fro ideas.

Could you suggest, which modifications I should do for that case:
1) User authorised via api and received JWT
2) By using JWT in the header open "GET /companies"

In current case it will return all rows from Company table.
I need to return only rows which have the same AccountId like authorised user has.
I think I should modify a model of "GET /companies" endpoint or middleware🤷🏼‍♂️
Could you suggest where this logic should be located in strapi ?

**Comment by lauriejim** [comment]
@mrikirill sorry for delay (lot of work), but you can use `/user/me` with JWT to get you user infos and then do something like that`GET /companies?AccountId=user.id`.
In this case `AccountId` is your relation key in company model.
