### ISSUE TITLE
Incorrect instructions for deploying to Google App Engine flexible environment

### ISSUE THREAD

**Issue by akerekes** [strapi/strapi#8035]
**Describe the bug**
The instructions at https://strapi.io/documentation/3.0.0-beta.x/deployment/google-app-engine.html work for App Engine standard environment, but doesn't work for flexible environment.

**Steps to reproduce the behavior**

1. Follow guide
2. See error when executing `gcloud app deploy app.yaml --project myapi-123456`

**Expected behavior**
The deploy is successful.

**System**
_Not relevant_

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**
The app.yaml for flexible environment has incorrect runtime, it should be `nodejs` instead of `nodejs10`, the latter leads to deployment failure with error message `ERROR: (gcloud.app.deploy) Unable to resolve a builder for runtime: [nodejs10]`

Also adding `app.yaml` .gcloudignore will cause the build to fail with the following error: `Application detection failed: Error: The file app.yaml does not exist`

**Comment by derrickmehaffy** [comment]
Hi @akerekes it would appear you are looking at our docs for a depreciated version (beta) can you please test again with the current version's documentation: https://strapi.io/documentation/v3.x/deployment/google-app-engine.html

**Comment by sebastian-voyavoy** [comment]
I've noticed the same issues exist with your instructions for the current version.

**Comment by derrickmehaffy** [comment]
Can you please explain a bit more @sebastian-voyavoy

**Comment by derrickmehaffy** [comment]
As no new information has been provided, marking as closed.

**Comment by akerekes** [comment]
I have reviewed the documentation at the current version it's still incorrect wrt App Engine flexible environment. Please take a look at the bug report, I clearly described what needs to be changed under **Additional context**

**Comment by derrickmehaffy** [comment]
@akerekes can you submit a PR to make the needed changes?

**Comment by derrickmehaffy** [comment]
closing as PR was merged in new docs repo
