### ISSUE TITLE
Generate types for GraphQL where filters

### ISSUE THREAD

**Issue by wesbos** [strapi/strapi#8037]
Right now when trying to filter items via graphql, it just tells you it's a JSON type. 

It would be great if we could generate the types automatically based on their field type (number, string, array, etc..)

So if we have two fields:  `name` (string), and `age` (number)  it would automatically give us:

```
name_contains: Contains.
name_containss: Contains sensitive.
age_ne: Not equals.
age_lt: Lower than.
age_lte: Lower than or equal to.
age_gt: Greater than.
age_gte: Greater than or equal to.
```

**Comment by derrickmehaffy** [comment]
Already done in the v4, marking as closed
