### ISSUE TITLE
Add staging environment

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#804]
What do you think about adding staging environment?

I think it's usual to have a staging environment before deploying to production.

**Comment by lauriejim** [comment]
Yap that's could be more interesting than `test` environment. 
Probably just have to rename the `test` environment.

**Comment by abdonrd** [comment]
Is there a test environment? 😮 
With the last release, I only have `development` & `production` in `config/environments`.

**Comment by lauriejim** [comment]
Yes https://github.com/strapi/strapi/tree/master/packages/strapi-generate-new/files/config/environments

**Comment by Aurelsicoko** [comment]
It's okay for me! Let's do it :)

**Comment by abdonrd** [comment]
Why the `test` folder is not created with the `strapi new projectName`?

**Comment by lauriejim** [comment]
Ho you are right ! It's because of the `.npmignore` of `strapi-generate-new`.
`test` folder is ignored so don't publish on npm. It will work on local dev mode but not from npm.
We will rename the test folder in `staging` and it's will fix this problem.
