### ISSUE TITLE
Content Type Builder shows hidden File collection type [3.2.0-beta]

### ISSUE THREAD

**Issue by MattieBelt** [strapi/strapi#8040]
**Describe the bug**
When creating a new project on `v3.2.0-beta.0` the Content Type Builder shows the (normally hidden) _File_ collection type.

**Steps to reproduce the behavior**

1. Create a new `v3.2.0-beta.0` project with: `npx create-strapi-app@beta project --quickstart`
2. Create your first admin user
3. Go to _Content-Types Builder_ plugin
4. Get shown/redirect to the File collection-type even though it isn't displayed in the _COLLECTION TYPES_ list. (see screenshot).

**Expected behavior**
To not be shown the normally hidden _File_ collection type, but instead the first one  in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662805/94206518-f0315a00-fec5-11ea-97d8-96c72c214d7e.png)

**System**
- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2.0-beta.0
- Database: SQLite
- Operating system: Ubuntu 20.04

**Additional context**
When having at least one non-default collection type, it doesn't show _File_.

**Comment by MattieBelt** [comment]
Closing this and pointing to the right place to report beta bugs.

[Strapi Community Forum (thread)](https://forum.strapi.io/t/strapi-v3-2-0-beta-0-draft-and-publish-testing/123)

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v3-2-0-beta-0-draft-and-publish-testing/123/4
