### ISSUE TITLE
Getting 500 error code after a POST request but the object is created 

### ISSUE THREAD

**Issue by sebapag** [strapi/strapi#8044]
Hi,
I'm trying to implement a POST request to a generic endpoint named /flyers. This content type is configure with a lookup to another content type, stores. I try to call it with an invalid store reference and I get the following error 

[2020-09-25T06:58:52.725Z] error CastError: Cast to ObjectId failed for value "100023" at path "stores"

And a 500 error code that seems pretty good. The problem is that the object has been created even if I had a 500 error code in my response. Is something that works for you or a bug? I expect that if I get a 500 error code in the response no object should be created inside the db. 

Many thanks in advance!

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.15
- Database: MongoDB
- Operating system: Windows Desktop

**Comment by derrickmehaffy** [comment]
Possible duplicate: https://github.com/strapi/strapi/issues/7872

**Comment by faisal212** [comment]
have you find the solution?

**Comment by opti21** [comment]
Getting the same error
