### ISSUE TITLE
Can not save changed properties of Guest Account

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#806]
**Node.js version**:
9.8
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.11
**Operating system**:
Windows 10

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I try to edit the guest account permissions or name, and press save it doesn't save my changed settings. Permissions of the plugins like the content-manager do get saved. It seems the properties related to the guest (like name) and the application settings aren't saved when pressing save. Another weird bug: the guest user seems to be the same over multiple projects.. I created a new project and the project properties from the first project were visible inside the guest account of the new project. Yet when I try to add a new user (not administrator or guest) and edit something in there, everything works perfectly. 

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1) git clone strapi and npm install strapi@alpha
2) strapi new project (with mysql database) 
3) login with user account 
4) go to guest account in admin ui and edit something from application / name / description 
5) save

**What is the expected behavior?**
it should save the changes but it doesn't. I can't save the permissions for my custom routing, thus rendering my application useless for guests.

**Comment by lauriejim** [comment]
Hello @piere129 !

We fix this bug on master. Will be release soon.

About persistent roles informations, it's probable because you use the same database between your projects.

**Comment by piere129** [comment]
Okay great, thank you! Any idea when the release is scheduled? :)

**Comment by lauriejim** [comment]
It's release 👍
