### ISSUE TITLE
Better error message on adding News  as a Collection Type

### ISSUE THREAD

**Issue by vanduc1102** [strapi/strapi#8060]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

While I am trying to save a collection named `News`

![image](https://user-images.githubusercontent.com/3014017/94336099-9b4b2c00-000a-11eb-94d1-56491d239f74.png)

Error in console

`Content Type name `News` cannot be pluralized. ↵Suggestion: add Item after the name (e.g News -> NewsItem).`

**Comment by derrickmehaffy** [comment]
Closing as duplicate: https://github.com/strapi/strapi/issues/1198
