### ISSUE TITLE
dropdown field type with data source from db

### ISSUE THREAD

**Issue by YakoobHammouri** [strapi/strapi#8061]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
create a dropdown field type like enumeration but the data can select from a specific column in the table, to add more dynamic for content

**Comment by derrickmehaffy** [comment]
In this case @YakoobHammouri it's recommended that you use a `oneWay` or `manyWay` relation to handle this.

The two have been highlighted below: 

![image](https://user-images.githubusercontent.com/8593673/94467534-f64e6180-0177-11eb-8de9-5868a178e81b.png)


For now I'm going to mark this as closed as this is our recommended solution.
