### ISSUE TITLE
Your account has been suspended when migrating 3.0.5 to 3.1

### ISSUE THREAD

**Issue by GabrielLiade** [strapi/strapi#8062]
**Describe the bug**
Hi everyone, 
After migrating to 3.1.0 from 3.0.5, following the migration guide, all admin accounts were suspended.
Indeed when I try to connect to my panel I have the following message error : "Your account has been suspended"

and an error 400 in the terminal : 
debug POST /admin/login (125 ms) 400

What I did to migrate to 3.1 : 

npm audit fix what updates my dependencies in the package.json : 

```
"dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.3.3",
    "sqlite3": "^4.2.0",
    "strapi": "^3.1.6",
    "strapi-admin": "^3.1.6",
    "strapi-connector-bookshelf": "^3.1.6",
    "strapi-plugin-content-manager": "^3.1.6",
    "strapi-plugin-content-type-builder": "^3.1.6",
    "strapi-plugin-email": "^3.1.6",
    "strapi-plugin-upload": "^3.1.6",
    "strapi-plugin-users-permissions": "^3.1.6",
    "strapi-provider-upload-aws-s3": "^3.0.5",
    "strapi-utils": "^3.1.6"
  },
```

then I create a .env file with a JWT token : 
.env file : 

```
ADMIN_JWT_SECRET=wg89B3K9hJjKL5A3V9Cokb/8/7bbMMXb0QXEM57mAhgSh2qidr23qwNXJPeVPLggwRs8oyQySX2i2c9sSs4c3Q==
```

and finally I update the server.js file : 

```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET'),
    },
  },
});
```

**Steps to reproduce the behavior**

1 - Local install of Strapi 3.0.5
2- Create admin account
3 - Migrate to 3.1.0 following the guide
4 - Try to login with same admin account
5 - Redirects to 'Oops the account is suspended....'

**System**

- Node.js version: 
- NPM version: 6.14.8
- Strapi version: 3.0.5 -> 3.1
- Database: Sqlite /   "sqlite3": "^4.2.0",
- Operating system: Catalina 10.15.6 MacOS

thank with advance for your support

**Comment by derrickmehaffy** [comment]
> npm audit fix

I would strongly advise against using this as it can cause quite a few problems, we recommend that you manually update your package.json, and for all Strapi packages you should not use `^`

> following the migration guide

In this case you will need to manually update your database and change the boolean `isActive` to `1` or `true` and ensure that `blocked` is either `null` or `0`/`false`

See this example from DBeaver (a Database client that supports SQLite):

![image](https://user-images.githubusercontent.com/8593673/94454103-50dec200-0166-11eb-84d2-de88e8d881d7.png)

**Comment by derrickmehaffy** [comment]
As no new information has been provided, marking as closed

**Comment by GabrielLiade** [comment]
sorry I didn't see your answer, indeed I manually updated my package.json and it work fine ;)
