### ISSUE TITLE
Roles and Permissions not showing

### ISSUE THREAD

**Issue by RispyCZ** [strapi/strapi#8063]
**Describe the bug**
When I install Strapi with Mysql. I can't see section with "Roles and Permissions" and when I check plugins Roles and Permissionssions plugin is installed.

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.6
- Strapi version: v3.16
- Database: Mysql 
- Operating system: Windows 10

**Comment by merijnponzo** [comment]
I have the same problem.
New install with --quickstart

Nodejs v12.18.4
NPM 6.14.6
strapi v3.1.6
Mac Os Catelina

<img width="543" alt="Screenshot 2020-09-27 at 10 54 40" src="https://user-images.githubusercontent.com/23075300/94360714-dfdcd300-00af-11eb-992d-57ec308f42cc.png">

**Comment by JelmerV-WFC** [comment]
@RispyCZ @merijnponzo Users & Permissions on the left menu has been moved into the Settings menu. Can you check if it is visible there?

**Comment by merijnponzo** [comment]
@JelmerV-WFC thanks Jelmer, I found it within the settings 
That solves this issue ;-)

**Comment by RispyCZ** [comment]
Oo thak you very much @JelmerV-WFC  😄
