### ISSUE TITLE
strapi refuses to upload files when configured with MongoDB -- bug in mongoose 5.10.7

### ISSUE THREAD

**Issue by jlsjonas** [strapi/strapi#8066]
**Describe the bug**
```error ValidationError: file validation failed: size: this[documentIsSelected] is not a function
    at new ValidationError (/path/to/project/node_modules/strapi-connector-mongoose/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/path/to/project/node_modules/strapi-connector-mongoose/node_modules/mongoose/lib/document.js:2428:32)
    at p.doValidate.skipSchemaValidators (/path/to/project/node_modules/strapi-connector-mongoose/node_modules/mongoose/lib/document.js:2277:17)
    at /path/to/project/node_modules/mongoose/lib/schematype.js:1225:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
when trying to upload an image

**Steps to reproduce the behavior**

1. Use the mongoose database connector (connecting to an Atlas db in my case)
2. Try to upload an image (either via a collection, or directly from the Media Library)
3. Notice an internal server error.

**Expected behavior**
Upload to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/932193/94361644-2b927b00-00b6-11eb-9496-02d3e822a39a.png)

**Code snippets**
If applicable, add code samples to help explain your problem.
Reproduced on quick-starter with `config/database.js` updated to the following:
```module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        uri: env('MONGODB_URI')
      },
      options: {
        ssl: true,
      },
    },
  },
});
```
(MONGODB_URI provided via `.env`)

**System**

- Node.js version:  12.18.4
- NPM version:
- Strapi version:  3.1.6
- Database: Mongo Atlas, mongoose connector (following [the docs](https://strapi.io/documentation/v3.x/guides/databases.html#mongodb-installation)
- Operating system: Ubuntu 20.04

**Additional context**

**Comment by derrickmehaffy** [comment]
Can you please add more information as I wasn't able to replicate this

**Comment by jlsjonas** [comment]
I just discovered it's a regression between 3.1.5 & 3.1.6
I had a quick start from a few days ago of 3.1.5 which did not have this issue.

1. ```bash
    $ npx create-strapi-app my-test --quickstart
    $ cd my-test/
    ```

2. Add `.env` and update `database.js` to reflect OP
3. ```bash
    $ npm i -S strapi-connector-mongoose
    $ npm run develop
    ```
4. Try to upload an image via the admin panel
5. ```
    [2020-09-27T17:03:08.374Z] debug GET /upload/files/count? (210 ms) 200
    [2020-09-27T17:03:08.379Z] debug GET /upload/files?_limit=10&_start=0&_sort=updatedAt:DESC (216 ms) 200
    [2020-09-27T17:03:14.583Z] error ValidationError: file validation failed: size: this[documentIsSelected] is not a function
        at new ValidationError (/path/to/my-test/node_modules/strapi-connector-mongoose/node_modules/mongoose/lib/error/validation.js:31:11)
        at model.Document.invalidate (/path/to/my-test/node_modules/strapi-connector-mongoose/node_modules/mongoose/lib/document.js:2428:32)
        at p.doValidate.skipSchemaValidators (/path/to/my-test/node_modules/strapi-connector-mongoose/node_modules/mongoose/lib/document.js:2277:17)
        at /path/to/my-test/node_modules/mongoose/lib/schematype.js:1225:9
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
    ```

**Comment by jlsjonas** [comment]
It seems that the issue occurs when 
```strapi-plugin-users-permissions@3.1.6
  └─┬ koa2-ratelimit@0.9.0
```
uses `mongoose@5.10.7` instead of `mongoose@5.10.6`; globally requiring 5.10.6 resolved the upload issue; to be followed up upstream.

**Comment by derrickmehaffy** [comment]
@jlsjonas can you submit a PR to downgrade the mongoose version until a fix can be made upstream?

**Comment by jlsjonas** [comment]
After discussions on the PR itself, the team decided not to release a _temp patch_.
Workaround:
Ensure that mongoose resolves to `5.10.6` for koa2-ratelimit.
1. Use `resolutions:` when using yarn or similar package manager ([diff](https://github.com/fluid-desi/strapi/commit/35069803561cf1031144b58148c0acf506a4f64c))
2. Add `mongoose` as a direct dependency strictly on `5.10.6`, this should also change the resolve within koa2-ratelimit

Leaving this ticket open for now while keeping track of the issue upstream

**Comment by jlsjonas** [comment]
Update: [resolved upstream](https://github.com/Automattic/mongoose/issues/9449#issuecomment-702322025), the underlying issue is (most likely) version mismatches, a mongoose model instance being passed to a different instance, where the schema might not exist yet.

**Comment by derrickmehaffy** [comment]
@jlsjonas so we can close out this issue since it's been fixed upstream?

**Comment by jlsjonas** [comment]
@derrickmehaffy I'd recommend checking that the Strapi issue is also resolved this way. I'll report back in a few days (after the fix is packaged & released upstream, so it can be verified as fixed)

**Comment by derrickmehaffy** [comment]
Cool thank you, I'll keep an eye out for your check and will close it out once you can confirm :)

**Comment by jlsjonas** [comment]
@derrickmehaffy Upstream has released a new version, it does look like dependabot didn't catch up with it yet; making it likely to receive 5.10.7 instead of 5.10.8
f.e. https://github.com/strapi/strapi/blob/5a77b560e333604d052bfa83ad774769b5d6bc2e/packages/strapi-connector-mongoose/package.json#L19

**Comment by derrickmehaffy** [comment]
@jlsjonas can you submit a PR to jump that version to 5.10.8?
