### ISSUE TITLE
Default value not working for collection fields

### ISSUE THREAD

**Issue by ahmett** [strapi/strapi#8070]
**Describe the bug**
When I try to set the default values for specific fields on the collection, the content type builder saving it successfully, but changes do not affect the database.

**Steps to reproduce the behavior**

1. Go to `Content-Types Builder`
2. Create a new collection type named `test` for example.
2. Add fields as a type of text, integer, boolean. ( I didn't try other types )
3. Set the default values for each of them.
4. Click save and check the table structure from MySQL CLI using `DESCRIBE tests;`

**Expected behavior**
The collection field's default value changes must affect its database table.

**Screenshots**
![image](https://user-images.githubusercontent.com/12511137/94369649-d70df080-00f3-11eb-9d2c-0638f452bb20.png)

**Code snippets**
N/A

**System**

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.1.6
- Database: MySQL 5.7.31
- Operating system: macOS Catalina 10.15.6

**Additional context**
N/A

**Comment by derrickmehaffy** [comment]
This is related to #1114 but isn't exactly the same thing, leaving open as a feature request.

@alexandrebodin is this something we are planning in the database refresh in Q4?

**Comment by alexandrebodin** [comment]
We don't plan to use default values in DB but add a better support for default value sin the database layer. Setting default values in the DB layer creates issues when migrating data so this might be possible with additional option specific to DB but the default behaviour will be programmatic only

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed

**Comment by manan-upadhyay** [comment]
Hello @derrickmehaffy , I am still facing this issue in v4. The default values are not reflected in the db, although I can see the same in the Strapi admin UI. I am facing the same issue for the maxlength field. Can you please help me with that? Am I missing something?

**Comment by derrickmehaffy** [comment]
> Hello @derrickmehaffy , I am still facing this issue in v4. The default values are not reflected in the db, although I can see the same in the Strapi admin UI. I am facing the same issue for the maxlength field. Can you please help me with that? Am I missing something?
> 
> CC: @alexandrebodin @ahmett

As part of Strapi v4 we don't set them in the DB but do it at the Strapi level, there is an experimental feature you can manually apply to your strapi schema to allow setting of the default values in the db: https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#database-validations-and-settings
