### ISSUE TITLE
strapi.query("aaa").update() only change one data

### ISSUE THREAD

**Issue by mtrucc** [strapi/strapi#8089]
**Describe the bug**
strapi.query("aaa").update() only change one data

**Steps to reproduce the behavior**
```
      await strapi
        .query("aaa")
        .update({ type:oldType }, { type: newType });
```
Only the first piece of data is updated, other data whose type is oldType is not updated

**Expected behavior**
Update all data whose type is oldType to newType

**System**

- Node.js version: 12.18.0
- NPM version: 6.14
- Strapi version: 
- Database: default
- Operating system: Win10

**Comment by mtrucc** [comment]
Do I have to use find() and use for loop to change data?

**Comment by mtrucc** [comment]
https://sequelize.org/master/class/lib/model.js~Model.html#static-method-update

I want to 

> Update multiple instances that match the where options.

**Comment by derrickmehaffy** [comment]
Yes, you will need to find and loop, we do not have any bulk create or update routes.

Closing as this is intended.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/upload-image-url/3484/4
