### ISSUE TITLE
Hello I have a question, when I send a post to create a new record and the record already exists (after I set it to be unique) it returns me err 500 does anyone know how to return an error that says it is not possible to insert a duplicate record?

### ISSUE THREAD

**Issue by outboxltd** [strapi/strapi#8091]
**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
Closing, please ask questions on our forum: https://forum.strapi.io/
