### ISSUE TITLE
Change width of fields on Edit page

### ISSUE THREAD

**Issue by ventouris** [strapi/strapi#8094]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

What I miss from Strapi admin is a way to customise the edit page from a certain post. In specific, I can move around the fields, but most of them times, the width is preselected. So, if I have 3 fields that I want to put next to each other on the same row, I cannot do it, unless the system let me to do.

In a similar framework as Strapi, I could choose the length either by % of predefined class names. That would be nice

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/change-width-of-fields-on-edit-page/181/3
