### ISSUE TITLE
Support CAS OIDC Sign-in

### ISSUE THREAD

**Issue by hdeadman** [strapi/strapi#8095]
I submitted a PR that adds support for CAS sign-in. CAS is supported by grant but the grant context needs to include a `subdomain` property with the specific domain and path for a particular CAS deployment being targeted (PR adds this field to provider pop-up). We are using this currently as a strapi extension but it would be nice if it could be included in a future release so we don't have to override as many files in our extension. 

PR is #8058 

When I get a chance I hope to create a CAS overlay docker image that someone could run locally with a local deployment of strapi and test OIDC login with everything running locally. 

Looking for feedback about whether this is something that can eventually be merged.

**Comment by derrickmehaffy** [comment]
Hi @hdeadman lets keep the discussion scoped to the PR you linked. I know it's been a few days since you submitted it, and I promise we will take a look at. :wink:
