### ISSUE TITLE
strapi-provider-upload: file values (name, alt, caption) are not persisted when uploading from a component

### ISSUE THREAD

**Issue by meck93** [strapi/strapi#8097]
**Describe the bug**
When attempting to edit the fields (i.e. name, description, caption) of a new media object (e.g., image) before uploading it, the values are not persisted. This only happens when a media object is uploaded directly via a component (e.g., from inside a Restaurant component which contains a media field). If the media object is uploaded via the Media Library, the values of the fields are correctly persisted and will be passed to the upload function. 

**Steps to reproduce the behavior**
1. Go to any content type of your choice that contains **a media field**
2. Click on an existing entry
3. Press the "Add" Icon on the media field
4. Press the button "Add more assets"
5. Press the button "Browse files" and select a random image
6. Press the "Edit" Icon on the image preview
7. Enter text into the fields **Alternative text, Caption** or change the **File name**
8. Press the button "Finish"
9. Press the "Edit" Icon on the image preview (again)
10. Notice that the text enter previously is missing (i.e. has not been stored)

**Expected behavior**
The changed values are persisted such that they can be provided before uploading the media object. 

**Possibly Affected Files**
The reducer code for the case `"ON_CHANGE"` is different between the following two files: 
- /strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/reducer.js
- /strapi-plugin-upload/admin/src/containers/ModalStepper/reducer.js

The `InputModalStepperProvider` uses the **lodash** `set` function and a `draftState`: 
`set(draftState.fileToEdit, action.keys.split('.'), action.value);`
The `ModalStepper` calls the function `state.updateIn(['fileToEdit', ...action.keys.split('.')], () => action.value);`.

**Screenshots**
I'm not sure if the screenshot is of much help. But my guess was that it might have something to do with the `state.fileInfo` being updated. But the name of the image remains the same in `state.file.name`.  
![image](https://user-images.githubusercontent.com/22457755/94585958-f8501780-0280-11eb-87cb-5e8f1a789033.png)

**System**
- Node.js version: v12.8.4
- NPM version: 6.14.6
- Strapi version: 3.1.6
- Database: Postgres
- Operating system: Linux

**Additional Information**
I would be happy to provide a fix if someone could guide me or someone has an idea what might be the issue. Thanks a lot for the feedback and investigating!

**Comment by derrickmehaffy** [comment]
Was able to reproduce, data isn't saved to the image until you save the entire model entry

**Comment by meck93** [comment]
@derrickmehaffy do you have an idea, what might be the reason? I would be happy to help fix the issue. Anyway, I will spend some more time debugging the root cause.

**Comment by derrickmehaffy** [comment]
It's most likely a UI thing and not firing the data over til it's in a certain state, we will need to talk to @soupette or @HichamELBSI

**Comment by meck93** [comment]
Hi @soupette and @HichamELBSI if you could give me a pointer for where to start digging further, I'd be thankful. do you have some idea what the root cause might be? thanks!
