### ISSUE TITLE
Can't install Strapi v3.1.6 using quickstart guide

### ISSUE THREAD

**Issue by zoutiyx** [strapi/strapi#8098]
**Describe the bug**
Can't install strapi using the quickstart guide command (`yarn create strapi-app my-project --quickstart`).

`yarn create strapi-app my-project --quickstart`
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 2.8s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 3.07s

Creating a new Strapi application at /Users/xyz/Strapi/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd /Users/xyz/Strapi/my-project && yarn install

**Side note**: _"mentionned" in the error message should be "mentioned"_

**Steps to reproduce the behavior**

1. Run `yarn create strapi-app my-project --quickstart` in the terminal

**Expected behavior**
A new strapi project called my-project should be created successfully on natural termination of command

**System**

- Node.js version: I tried both LTS version v12.18.4 and the latest v14.12.0
- NPM version: 6.14.8
- Strapi version: 3.1.6
- Database: any
- Operating system: macOS Catalina version 10.15.6

**Comment by derrickmehaffy** [comment]
Can you provide some more information on the actual error?

**Comment by derrickmehaffy** [comment]
Can't reproduce on a similar Mac:

![image](https://user-images.githubusercontent.com/8593673/94598567-fa47b580-0243-11eb-89f4-2084d36034df.png)
![image](https://user-images.githubusercontent.com/8593673/94598603-0af82b80-0244-11eb-8499-9af7cc931c78.png)

**Comment by zoutiyx** [comment]
Turns out, Yarn (berry) isn't supported. Node v12 (LTS) + Yarn 1.22.5 did it.

**Comment by derrickmehaffy** [comment]
Likely related to Node v14 and the new yarn then. Can you do some testing and post up whatever information you can on https://github.com/strapi/strapi/issues/7921 ?
