### ISSUE TITLE
GraphQL sorting on manyWay relation does not do anything

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#8099]
**Describe the bug**
Applying a `sort: field:direction` does not work in a GraphQL query that is attempting to sort on a `manyWay` relation.

**Steps to reproduce the behavior**

1. Create two models: Article and Comment
2. Create a many way relation between them where "Article has many Comments"
3. Using the playground, attempt to query all articles and try to sort the comments by one of the fields in any direction
4. See no change has occurred and the sort isn't passed into the Knex Query

**Expected behavior**
A sort param is passed into Knex and thus the result is sorted

**Screenshots**

![image](https://user-images.githubusercontent.com/8593673/94601982-1f8af280-0249-11eb-94e2-07d73c7ad8aa.png)

![image](https://user-images.githubusercontent.com/8593673/94602004-287bc400-0249-11eb-95c1-30e32d453122.png)

**Code snippets**

GraphQL Query

```
query {
  articles {
    id
    title
    body
    comments (sort: "text:asc"){
      id
      text
    }
  }
}
```

Article Model

```json
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "name": "article"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "body": {
      "type": "richtext"
    },
    "comments": {
      "collection": "comment"
    }
  }
}
```

Comment Model

```json
{
  "kind": "collectionType",
  "collectionName": "comments",
  "info": {
    "name": "comment"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "text": {
      "type": "string"
    }
  }
}
```

**System**

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.6
- Database: SQLite
- Operating system: Linux Mint 20 - ulyana (Ubuntu 20.04)

**Additional context**

Knex log for sort by `text:asc`

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 100 ],
  __knexQueryUid: '8b7c8ac2-6a72-4eaa-88aa-466fa5588dd1',
  sql: 'select `articles`.* from `articles` limit ?'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '68705428-42f4-45e8-9c1b-425ec6d7061c',
  sql: 'select distinct `comments`.*, `articles__comments`.`article_id` as `_pivot_article_id`, `articles__comments`.`comment_id` as `_pivot_comment_id` from `comments` inner join `articles__comments` on `articles__comments`.`comment_id` = `comments`.`id` where `articles__comments`.`article_id` in (?)'
}
```

Knex log for sort by `text:desc`

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 100 ],
  __knexQueryUid: '6110d263-d52f-452a-b49e-99f599677dc6',
  sql: 'select `articles`.* from `articles` limit ?'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '6ef13c28-01d1-4bc6-b057-7a8ec32bbb97',
  sql: 'select distinct `comments`.*, `articles__comments`.`article_id` as `_pivot_article_id`, `articles__comments`.`comment_id` as `_pivot_comment_id` from `comments` inner join `articles__comments` on `articles__comments`.`comment_id` = `comments`.`id` where `articles__comments`.`article_id` in (?)'
}
```

**Comment by derrickmehaffy** [comment]
Modifying the relation to `oneToMany` in where "One Article has many Comments" yields the proper results:

![image](https://user-images.githubusercontent.com/8593673/94602393-a50ea280-0249-11eb-8887-b5a5118100ff.png)

![image](https://user-images.githubusercontent.com/8593673/94602415-acce4700-0249-11eb-9131-3d1514e6a2cb.png)

**Comment by georgekarapi** [comment]
Same problem for me, any workarounds?

**Comment by derrickmehaffy** [comment]
None currently @georgekarapi

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/default-sort-order-match-api-with-admin-8077/1750/2

**Comment by derrickmehaffy** [comment]
fixed in v4
