### ISSUE TITLE
Header for allowed actions for the application plugin not high enough

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#8102]
**Describe the bug**

The picture is worth more than the description

![image](https://user-images.githubusercontent.com/2712405/94628915-44a25400-028f-11eb-96b2-c4a067b6cd5a.png)

**Expected behavior**
This behavior is a function of the overall browser width, so I was lucky to trigger this problem, trying to save screen space.

**System**

- Node.js version: v12.18.2 
- NPM version: 6.14.8
- Strapi version:  3.1.6 
- Database:
- Operating system: Windows 10 Pro

**Additional context**

**Comment by derrickmehaffy** [comment]
Closing as duplicate, feature is already on our roadmap: https://portal.productboard.com/strapi/1-roadmap/c/20-administration-responsive

Currently the react based admin panel is not responsive, we are aware but have not set it a priority at the moment as it is quite a big task to resolve. Closing for now in favor the roadmap entry.

**Comment by adriatic** [comment]
Good call - at the moment, this is just esthetics, with the caveat that it looks as carelessness 😃
