### ISSUE TITLE
Unable to select a component in admin UI select

### ISSUE THREAD

**Issue by beltranrengifo** [strapi/strapi#8105]
**Describe the bug**
The select component seems to have a problem in the UI

**Steps to reproduce the behavior**

1. Create some components
2. Try to add one to a content type
3. The select shows bad UI

**Expected behavior**
A list of items

**Screenshots**
![image](https://user-images.githubusercontent.com/19485114/94655312-a9e15e00-02fe-11eb-82ad-f9d91e8c9985.png)

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.0.5
- Database: Atlas
- Operating system: MacOSX 10.15.6

**Comment by beltranrengifo** [comment]
Tested in this browsers:

Chrome Versión 85.0.4183.121 (Build oficial) (64 bits)
Firefox 80.0.1 (64-bit)
Safari Versión 14.0 (15610.1.28.1.9, 15610)

**Comment by soupette** [comment]
@beltranrengifo can you upgrade your app to the latest version the issue has been fixed.

**Comment by soupette** [comment]
I am closing the issue

**Comment by beltranrengifo** [comment]
TheI can see the issue in version 3.1.6
![image](https://user-images.githubusercontent.com/19485114/94666842-4828f000-030e-11eb-9a25-d396f5f058e8.png)

**Comment by beltranrengifo** [comment]
I tried to setup the development environment to fix the issue, but I enconter an infinite loading problem in localhost:4000 (https://github.com/strapi/strapi/discussions/6477)
Just in case you have this problem identified, please let me know. Thanks in advance
