### ISSUE TITLE
Should be able to redirect to the content's detail page with a valid userToken

### ISSUE THREAD

**Issue by prernagp** [strapi/strapi#8106]
My application is showing the list of all the content that is being created in Strapi. Whenever a user gets logged in my application, he can see the list. But when he wants to see/edit a particular content, I navigate the user to the Strapi portal. But, as Strapi does not maintain the session, due to which user needs to log in every time he visits the Strapi portal. There should be a mechanism via which my application can pass the Strapi user's JWT token to the Strapi portal, which in turn creates the session for the user, and then that user can successfully redirect to a particular content's detail page.

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
