### ISSUE TITLE
Running strapi in production mode does not allow to create or edit structures

### ISSUE THREAD

**Issue by Ant-V** [strapi/strapi#8109]
Running strapi in production mode does not allow to create or edit structures

Is this is a bug or a weird feature of some sort?

**Comment by derrickmehaffy** [comment]
Please see: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

Marking as closed due to intended action and lack of proper template
