### ISSUE TITLE
Sign in link on the Register-admin dialog is not functional

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#8116]
Running **`npx create-strapi-app ig-backend --quickstart`** command will create the standard Strapi application, and instantiate it in the browser, prompting the user to **create** the initial administrator:

![image](https://user-images.githubusercontent.com/2712405/94715678-d48ddf80-031b-11eb-8c57-45e6b8b40d2f.png)

The **`Sign in`** link should invoke the alternative to the **`Register admin`** dialog, prompting for just userID and password. Instead one gets to see:

![image](https://user-images.githubusercontent.com/2712405/94716153-6eee2300-031c-11eb-94c8-96106a7d6bb7.png)

**Expected behavior**
Once the admin account was created, any successive invocation of the app, should being with the login prompt, instead of creating  the account dialog and placing the cursor on the **`First name`** text entry

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.8
- Strapi version: 3.1.6
- Database:
- Operating system: Windows 10 Pro

**Comment by alexandrebodin** [comment]
Hello, we already merged a fix :) it will be released in the upcoming release

**Comment by adriatic** [comment]
@alexandrebodin - the speed you respond to the problem reports is enviable. I am assuming that @derrickmehaffy plays a lion's role in triaging and fixing some as well. Please keep up a great job; except for a really wanted new features, fixing bugs is ranked on top of your customers' list,
