### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#8125]
- Node.js version: 12
- NPM version:6.14
- Strapi version: 3.1.0
- Database:mongo
- Operating system:linux

Hello my email service is setup on godaddy and working fine on outlook and when im sending email with same setting and credentials , i am getting a warning
**"messages": [
                {
                    "message": "Message failed: 550 <> Sender Rejected - MAILFROM must be a valid domain. Ensure the mailfrom domain: \"\" has a valid MX or A record."
                }
            ]**

**Comment by gustawdaniel** [comment]
Error message is quite clear. This is not problem with strapi but with config of your mailbox.

Please check your domain by tools like:

https://dnschecker.org/mx-lookup.php

or similar.

**Comment by iamwebdev** [comment]
it is present in list
