### ISSUE TITLE
Bug with "has same role as creator" with custom roles

### ISSUE THREAD

**Issue by MickaelFondation** [strapi/strapi#8129]
Hi, I created a role custom then I give two users this same role and I set Has same role as creator. When I added something with one user the other one can see something new on the list but everything inside is empty. I think this is a bug

**Describe the bug**
It look likes the parameter "define condition" "Has same role as creator" doesn't work properly. When it's set to a specific Collection Types (on read condition for example). The number of elements correspond but in the liste there is "-" character at the place of datas and when I click to modify every field are empty.

**Steps to reproduce the behavior**

1. Having two user with the same custom role
2. Create an entry in a collection type with one of the users
3. As an administrator go to Permission then Roles
4. Edit the role of the two previous user 
5. Click on parameters who is display on mouseover on the collection types who correspond of the one you created before
6. Select "Has same role as creator" next to CAN READ WHEN
7. Apply
8. Go to the right collection type on the main menu
9. The entry appear on the list but with no data (only '-' character on the list)

**Expected behavior**
The right behavior is to see datas on the list and when i edit the collection types entity.

**Screenshots**
<img width="1411" alt="bugstrapirole" src="https://user-images.githubusercontent.com/68648961/94827880-38da9d00-0409-11eb-9c7b-29c1bff2dfde.png">

**System**

Strapi self hosted 3.1.3

**Comment by derrickmehaffy** [comment]
Can you clarify which roles you are referring to? I assume you mean the Admin panel roles. Are you an EE user as the CE version is limited only to the 3 predefined roles.

**Comment by MickaelFondation** [comment]
It's a custom role I just created
<img width="1088" alt="customerolestrapiexemple" src="https://user-images.githubusercontent.com/68648961/94834235-67a84180-0410-11eb-9ec9-e221a0d4d2f0.png">
Exactly it's admin panel not api role.
I am no longer limited to 3 predefined roles since I paid for bronze plan (I can create 30 roles)

**Comment by derrickmehaffy** [comment]
Ah perfect that makes more sense, let me get a license key and do some testing and I'll get back to you shortly ;)

**Comment by MickaelFondation** [comment]
Great thank you :)

**Comment by MickaelFondation** [comment]
Any news?

**Comment by derrickmehaffy** [comment]
Apologies I didn't get to this last week, I have license in hand and will be taking a look today :)

**Comment by derrickmehaffy** [comment]
I can confirm this on v3.1.7 with the following steps to reproduce:

- Create a new model called `article` with two fields
  - `title` - string
  - `body` - richtext
- Create a new role `test`
- Assign all field permissions but apply custom conditions
  - Can Create => Anytime
  - Can Read => is same role
  - Can Update => is owner
  - Can delete => is owner
- Create 2 test users
- Create an article on one
- Attempt to read on the other

See both the list and edit views are empty for user two. As a side point, trying to update as user 2 just yield a giant "SERVER ERROR" message. **NOTE** to test you need an EE License of any type.

Test project attached. 
[test8129.zip](https://github.com/strapi/strapi/files/5329202/test8129.zip)

```
Super User Login
test@test.com
Test1234!

User 1 Login
test1@test.com
Test1234!

User 2 Login
test2@test.com
Test1234!
```
