### ISSUE TITLE
Login misunderstood

### ISSUE THREAD

**Issue by wi4er** [strapi/strapi#815]
**Node.js version**: 9.6

**npm version**: 5.7

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: Ubuntu 16.04

**Do you want to request a *feature* or report a *bug*?**
Some misunderstood

**What is the current behavior?**
I had repeat all guides about authentication. Registration works fine, loggin works fine aslo. But I dont understand, what I suppose to do after getting auth token? How to work with app without ajax requests?

**Comment by soupette** [comment]
The token you retrieve is needed to access the data of your api if you have permissions set.

What do you mean by `how to work with app without ajax requests`?

Did you take a look at the [strapi-examples apps?](https://github.com/strapi/strapi-examples)?

**Comment by mrikirill** [comment]
@wi4er 

After authentication you will receive a [JWT](https://jwt.io/introduction/)
Use this JWT in the header of your requests: Authorization: Bearer **Your JWT** to access to api endpoints.

**Comment by wi4er** [comment]
Yes, I understand this. But I have a couple landing pages in my app. And they suppose to have different markup for customers and guests. And I dont know how to render this pages in the backend, because I cant know user role in first request only after ajax. But this way dont satisfy my  superior. 

P.S. I need to get balance beetween performance and SEO.

**Comment by soupette** [comment]
Well, once you authenticate your user you have access to its role. So, maybe it could be a good start to render different markup in your case directly in the front-end.

**Comment by wi4er** [comment]
Unfortunately cant choose this way. My SEO managers have different point of view on web apps.

**Comment by wi4er** [comment]
I see only one solution. Is it possible to pass the access token through the cookie and then process it?

**Comment by lauriejim** [comment]
To did it you will have to update the policy `permission.js` of user and permission plugin.
And get your cookies with `ctx.cookies.get(...)`
