### ISSUE TITLE
strapi version

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#816]
**Node.js version**:
v9.8.0

**npm version**:
5.7.1

**Strapi version**:
3.0.0-alpha.11.1

**Operating system**:
Windows 10

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
"strapi version" command outputs blank line whereas "strapi --version" outputs version

**What is the expected behavior?**
According to https://strapi.io/documentation/cli/CLI.html#strapi-version the "strapi version" command should output some kind of extended version information?

**Comment by lauriejim** [comment]
Hello @nurikabe .

I'm not able to reproduce this issue.
Are you in dev mode ? Have you an error ?

Can you try to run `npm install strapi@alpha -g` again then `strapi --version` please. Maybe your strapi install fail previously

**Comment by nurikabe** [comment]
Just tried reinstalling.  In Cygwin on Windows this works:
````
$ strapi --version
3.0.0-alpha.11.1
````
This does not:
````
$ strapi version
````

Is there a reason there are two ways to check version?

Do you have more details on dev mode?  I didn't see anything in the quick start docs.

**Comment by lauriejim** [comment]
Ho okay ! 
Yes it doesn't work.
You can fix it here https://github.com/strapi/strapi/blob/master/packages/strapi/bin/strapi.js#L41
`program.versionInformation` look return null so can you try to find a way to display the good version and submit a PR.

Could be super cool to have you as Strapi contributor !

**Comment by nurikabe** [comment]
Haven't done much node development so not sure if this is the right approach, but how about this?:

https://github.com/strapi/strapi/pull/820

**Comment by tutorgeeks** [comment]
Can we identify the Strapi version by visiting the Strapi installation URL? https://strapi-endpoint/admin/strapiVersion
Will this work?
