### ISSUE TITLE
problem to query data from  strapi using graphql

### ISSUE THREAD

**Issue by Gabriel-Andy** [strapi/strapi#8166]
hello everyone.
it is my first time opening an issue on github.
I am building my portfolio website with gatsby.js and strapi.
I set all my contentTypes and data  on strapi.
I open two terminals, one for strapi and one for gatsby.
to test everything, I ran the command "npm run develop " on strapi and I have a status 200.
this is the response https://www.screencast.com/t/YcIiZv9n
also, I made a request by typing http://localhost:1337/jobs and I got my data back from strapi
this is the link that point to my response https://www.screencast.com/t/lwFXPjY3w.
I opened another terminal to run "gatsby develop"
this is the response I get back https://www.screencast.com/t/hsjVmM0CYFb
now when I try to access http://localhost:8000/___graphql
what I got returned is that "no schema available ".
this is the link that point to it https://www.screencast.com/t/0FYKHxgn
when I console.log to figured out what is happening
this is what I got on my console.log https://www.screencast.com/t/Zo0MSeEnDU

Gatsby CLI version: 2.12.101
Gatsby version: 2.24.7

"strapi": "3.1.6",
"strapi-admin": "3.1.6",
in summary, I can access my resource on strapi but when I request the same data using graphql like this
http://localhost:8000/___graphql nothing comes back. I basically have as returned "no schema is available
this is the gatsby repository https://github.com/Gabriel-Andy/my-portfolio-site
this is the strapi repository https://github.com/Gabriel-Andy/portfolio-api
I look forward to hearing from you  back
thanks

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to our [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Thank you

**Comment by Gabriel-Andy** [comment]
thanks I fix it
I just updated the version and magically things work correctly
