### ISSUE TITLE
Create-strapi-app not creating roles & permissions tab

### ISSUE THREAD

**Issue by markbayor** [strapi/strapi#8170]
**Describe the bug**
I used "yarn create-strapi-app app-name --quickstart" a while ago and it worked perfectly out of the box. However now when I do the same thing, creates the AdminUI without the Roles & Permissions tab. If I go to "localhost:1337/admin/plugins/users-permissions" I get a React error from the bundle. I cannot think why this could be, as it's happening in my Ubuntu machine as well as OSX on a freshly created app.

**Expected behavior**
Get a tab and page for Roles & Permissions plugin

**Screenshots**
<img width="1373" alt="Screen Shot 2020-10-03 at 8 39 22 PM" src="https://user-images.githubusercontent.com/58964745/94999302-76186980-0586-11eb-919a-c86d9ccb86d3.png">
<img width="1402" alt="Screen Shot 2020-10-03 at 8 39 28 PM" src="https://user-images.githubusercontent.com/58964745/94999305-7a448700-0586-11eb-9a99-13c16648397e.png">

**System**

- Node.js version: 12.14.7
- NPM version: 6.14.7
- Strapi version: 3.1.7
- Database: SQLite
- Operating system: Ubuntu / MacOS Catalina

**Comment by derrickmehaffy** [comment]
See: https://github.com/strapi/strapi/releases/tag/v3.1.5

> Note: Please note that the Users & Permissions on the left menu has been moved into the Settings menu per PR: #7467

Marking as closed as this is intended
