### ISSUE TITLE
SelectBox UI glitch when assigning a component

### ISSUE THREAD

**Issue by sebqq** [strapi/strapi#8175]
**Describe the bug**

Whenever I have bigger number of components created and I'm trying to assign component to any collection/single-type/another component, There are some graphical issues in Select box. You can see this UI glitch in following gif video.

![2020-10-04 10 54 11](https://user-images.githubusercontent.com/33039909/95011324-255d4b00-0630-11eb-98b8-840f79e9ad9e.gif)

**Steps to reproduce the behavior**

1. Add bigger number of components
2. Try to create a new component field to any collection/singletype
3. See error

**Expected behavior**

I expect Select field to display labels and vlaues properly.

**System**

- Tested in Chrome
- Node.js version: 12.6.1
- NPM version: 6.14.5
- Strapi version: 3.1.7 CE
- Database: mongodb
- Operating system: docker strapi/base

**Comment by derrickmehaffy** [comment]
Unable to reproduce this on v3.1.7 or v3.2.0-beta.0

Do you have a link to your project code somewhere?

**Comment by sebqq** [comment]
Hello and thanks. Tomorrow, I will try to prepare a reproducible demo.

**Comment by derrickmehaffy** [comment]
Sounds good, thank you @sebqq
