### ISSUE TITLE
maybe replace "/graphql" of strapi's internal middleware parser with a setting of parser

### ISSUE THREAD

**Issue by wubolin** [strapi/strapi#8177]
when i use /api as my graphql endpoint, i cannot upload file by apollo-client.

through debugging,  i found the problem is at [strapi/middlewares/parder/index.js 43 line](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/parser/index.js) . 

` if (ctx.url === '/graphql') {` .  because i can't use '/graphql',  body of request can't not by apollo server parsing, so emit error.

`module.exports = strapi => {
  return {
    /**
     * Initialize the hook
     */
    initialize() {
      strapi.app.use(async (ctx, next) => {
        // disable for graphql
        // TODO: find a better way later
        if (ctx.url === '/graphql') {
          return next();
        }`

maybe replace ` if (ctx.url === '/graphql') {` with  ` if (ctx.url === strapi.config.middleware.settings.parser.apolloPath) {`.

thx.

**Comment by derrickmehaffy** [comment]
Thank you for reporting the error, but please follow the bug report template.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
