### ISSUE TITLE
media upload terminates for using too much memory

### ISSUE THREAD

**Issue by AryanGharshi** [strapi/strapi#8178]
**Describe the bug**
After installing the google upload-provider and uploading the project to gcloud, uploading media works very inconsistently. some files are uploaded just fine while others for some reason produce an error. I've tried with both large (4mb) and small (150kb) images in png and jpg format. the error happens to any file size once every 5-6 pictures. After checking the logs on google cloud, the error message reads: 

"Exceeded soft memory limit of 2048 MB with 2148 MB after servicing 28 requests total. Consider setting a larger instance class in app.yaml."

"While handling this request, the process that handled this request was found to be using too much memory and was terminated. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may have a memory leak in your application or may be using an instance with insufficient memory. Consider setting a larger instance class in app.yaml."

I've tried editing the instance class in app.yaml all the way up to F4_1G but the problem persists. I wonder if the error is because it serves 28 requests? is that supposed to be so many? 

here is the full error log:
`protoPayload: {
@type: "type.googleapis.com/google.appengine.logging.v1.RequestLog"
appId: "e~lucid-sonar-290314"
versionId: "20201004t113120"
requestId: "5f79981900ff0cd2578eb19e270001657e6c756369642d736f6e61722d3239303331340001323032303130303474313133313230000100"
ip: "80.203.79.126"
startTime: "2020-10-04T09:38:33.840279Z"
endTime: "2020-10-04T09:39:15.670193Z"
latency: "41.829914s"
megaCycles: "64501"
method: "POST"
resource: "/upload"
httpVersion: "HTTP/1.1"
status: 500
referrer: "https://lucid-sonar-290314.ew.r.appspot.com/admin/plugins/content-manager/collectionType/application::gallery-entry.gallery-entry/create"
userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
urlMapEntry: "auto"
host: "lucid-sonar-290314.ew.r.appspot.com"
instanceIndex: -1
finished: true
instanceId: "00c61b117cddbd67030265c2b7adc1c71b61d8b341a4956ad63a09098f4497037c84e28b46c09f"
line: [
0: {
time: "2020-10-04T09:39:15.669916Z"
severity: "CRITICAL"
logMessage: "Exceeded soft memory limit of 2048 MB with 2148 MB after servicing 28 requests total. Consider setting a larger instance class in app.yaml."
}
1: {
time: "2020-10-04T09:39:15.670007Z"
severity: "WARNING"
logMessage: "While handling this request, the process that handled this request was found to be using too much memory and was terminated. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may have a memory leak in your application or may be using an instance with insufficient memory. Consider setting a larger instance class in app.yaml."
}
]
appEngineRelease: "1.9.71"
traceId: "e55848e929a26f5941301e6609a66db6"
first: true
}
insertId: "5f799843000a3ae7b12456cc"
httpRequest: {
status: 500
}
resource: {
type: "gae_app"
labels: {
zone: "eu6"
project_id: "lucid-sonar-290314"
module_id: "default"
version_id: "20201004t113120"
}
}
timestamp: "2020-10-04T09:38:33.840279Z"
severity: "CRITICAL"
labels: {
clone_id: "00c61b117cddbd67030265c2b7adc1c71b61d8b341a4956ad63a09098f4497037c84e28b46c09f"
}
logName: "projects/lucid-sonar-290314/logs/appengine.googleapis.com%2Frequest_log"
operation: {
id: "5f79981900ff0cd2578eb19e270001657e6c756369642d736f6e61722d3239303331340001323032303130303474313133313230000100"
producer: "appengine.googleapis.com/request_id"
first: true
last: true
}
trace: "projects/lucid-sonar-290314/traces/e55848e929a26f5941301e6609a66db6"
receiveTimestamp: "2020-10-04T09:39:15.672098828Z"
}`

**Steps to reproduce the behavior**

1. install gcloud upload provider as instructed in documentation
2. upload project to gcloud as instructed in documentation
3. attempt to upload images to library

**Expected behavior**
I expect all images to upload without errors

**System**
Node.js version 10
Npm version 6.14.6
Strapi version 3.1.5
Database: PostgreSQL
Operating system: windows 10

**Comment by derrickmehaffy** [comment]
closing as duplicate:

https://github.com/strapi/strapi/issues/6432
https://github.com/strapi/strapi/issues/6869
