### ISSUE TITLE
[Strapi v3.1.7] Error connecting to the Mongo database

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#8181]
**Describe the bug**

After update from `v3.1.6` to `v3.1.7`, we have this error:

>[2020-10-05T09:56:22.769Z] debug ⛔️ Server wasn't able to start properly.
>[2020-10-05T09:56:22.771Z] error Error connecting to the Mongo database. self signed certificate in certificate chain

**Steps to reproduce the behavior**

Our `database.js` is:

```javascript
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        uri: env('DATABASE_URI'),
      },
    },
  },
});
```

And the `DATABASE_URI` is:

`
mongodb://username:password@host1:port1,host2:port2/database?authSource=admin&replicaSet=replset&ssl=true
`

**Expected behavior**

Working, as previous version.

**System**

- Node.js version: `v12.17.0`
- NPM version: `v6.14.8`
- Strapi version: `v3.1.7`
- Database: MongoDB
- Operating system: macOS

**Comment by alexandrebodin** [comment]
We upgraded the mongoose version and didn't have any breaking changes (and the changelog didn't mention any). do you have the rest of the error message ?

**Comment by abdonrd** [comment]
Thanks for the quick response, @alexandrebodin!

The full log is:

```
➜  project-name git:(master) ✗ npm run develop                                      

> project-name@2.0.0 develop /Users/abdonrd/Work/.../project-name
> strapi develop

[2020-10-05T09:56:22.769Z] debug ⛔️ Server wasn't able to start properly.
[2020-10-05T09:56:22.771Z] error Error connecting to the Mongo database. self signed certificate in certificate chain
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-name@2.0.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project-name@2.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdonrd/.npm/_logs/2020-10-05T09_56_22_785Z-debug.log
```

**Comment by alexandrebodin** [comment]
Are you connecting to your mongodb or a hosted one ?

**Comment by abdonrd** [comment]
@alexandrebodin hosted at IBM Cloud.

**Comment by aksdevac** [comment]
May be this can help: 
https://github.com/Automattic/mongoose/issues/9147#issuecomment-653597444

**Comment by alexandrebodin** [comment]
I can't find any mention of changes regarding ssl certificates in the mongoose changelog :/ what @aksdevac links might be realted as the latest mongoose version use the latest mongodb drivers too.

**Comment by abdonrd** [comment]
@aksdevac @alexandrebodin Yes, it works if I add the `&tlsInsecure=true` to the URI!

**Comment by derrickmehaffy** [comment]
@abdonrd you good with me closing this?

**Comment by franciscone14** [comment]
Anyone manage to connect to MongoDB hosted in a cloud service with the certificate ? I used the sslCA option to provide the certificate but I still get the same error as listed in this issue.

FYI: Using tlsInsecure is not an option as the mongodb docs warns that this creates vulnerabilities.
