### ISSUE TITLE
The link button in the rich text/markdown editor puts text in the wrong place

### ISSUE THREAD

**Issue by josh-unwin** [strapi/strapi#8184]
**Describe the bug**
The rich text editor's link shortcut button puts the text in the wrong place. In my opinion, most users will be writing out their text, then wanting to add a link to it, not the other way around. In it's current state, it is working in the opposite fashion to other tools like Google Docs etc.

### Before clicking the 'link' button:
<img width="596" alt="Screenshot 2020-10-05 at 14 30 28" src="https://user-images.githubusercontent.com/49525488/95085968-d094ff80-0717-11eb-9904-b3d5cb2fda7d.png">

### After clicking the link button:
<img width="575" alt="Screenshot 2020-10-05 at 14 30 37" src="https://user-images.githubusercontent.com/49525488/95086010-e0acdf00-0717-11eb-8492-ede976346a22.png">

The highlighted text gets put in the URL portion of the markdown syntax rather than the text portion.

**Steps to reproduce the behavior**

1. Highlight text you want to add a link to using the rich text editor.
2. Click the link button.

**Expected behavior**
The highlighted text should be put within the text portion of the link markdown syntax `[HERE]()` rather than `[](HERE)`

**System**

- Node.js version: 12.18.4
- Strapi version: v3.1.6
- Database: mySQL

**Comment by soupette** [comment]
Hi!

Can you upgrade your app to the latest version the issue has already been fixed.

**Comment by josh-unwin** [comment]
Wow that was quick, I've only just upgraded to the version I'm on now! Great stuff.

**Comment by MattieBelt** [comment]
Linking PR for reference: https://github.com/strapi/strapi/pull/8071
