### ISSUE TITLE
Creator firstname and lastname available in REST API but not available in Graphql Query

### ISSUE THREAD

**Issue by jahidanowar** [strapi/strapi#8187]
```
**System**

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: Postgress / SQLite
- Operating system: Ubuntu
```

I am creating a blog so I have created a Post content type when I am viewing the Rest API I can see the created_by and updated_by fields with Creator First name and last name. But when I am trying to fetch the same using graphql it's not working.

My Model Options
```js
  "options": {
    "increments": true,
    "timestamps": true,
    "privateAttributes": ["id", "created_at"],
    "populateCreatorFields": true
  },
```
Here is my Graphql Query

```gql
query Posts {
  posts {
    id
    updated_at
    slug
    Title
    content
    Image {
      url
    }
    created_by{
      firstname
      lastname
    }
    categories {
      id
      Name
    }
    comments {
      Name
      Content
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
@jahidanowar normally I'd close this for not using the GitHub issue template but I'll let it slide this time if you can just provide the following info:

```
**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

@Convly did we test the `populateCreatorFields` with GraphQL?

**Comment by Convly** [comment]
Hi,

We did test the `populateCreatorFields` with GraphQL.

Here is the output for the following `Category.settings.json` options
```json
"options": {
    "increments": true,
    "timestamps": true,
    "privateAttributes": ["id", "created_at"],
    "populateCreatorFields": true
},
```
![image](https://user-images.githubusercontent.com/25851739/95114615-82e2bc00-0744-11eb-8f79-e264b35738cf.png)

Using strapi **v3.1.7**, node **v12.18.4**

**Comment by derrickmehaffy** [comment]
@jahidanowar can you provide a sample project that can reproduce this issue or provide a link to your project?

**Comment by amitav13** [comment]
Facing this in my project as well. 

Here's it reproduced in a sample project: https://github.com/amitav13/strapi-graphql-error

Note that I:
- Added the content type through the admin panel
- Created a user through the admin panel
- Logged in with the user via graphql to get a JWT
- Used the JWT in a `createProduct` call

![Screenshot 2020-10-06 at 11 39 41 AM](https://user-images.githubusercontent.com/7059002/95165062-de568d80-07c8-11eb-8cb0-7ca059c7fc74.jpg)
 
Version - 3.1.7 (node v12.16.3)
Database - SQLite (but am seeing this on Postgres as well)
OS - Mac 10.15.6

**Comment by Convly** [comment]
Did you created the entry with an admin user **through the admin panel** or using the generated REST/GraphQL endpoints?
RBAC is an administrator feature and is handled by the content-manager, not the generated APIs.

**Comment by amitav13** [comment]
Ah makes sense. I do need to be able to capture this information though, at least the user that's creating the item via the API. Where in the stack should I be checking this/adding it manually? `beforeCreate` doesn't pass on this in the `data`.

**Comment by jahidanowar** [comment]
> 
> 
> @jahidanowar can you provide a sample project that can reproduce this issue or provide a link to your project?

Here is my project https://github.com/jahidanowar/jampappbackend

**Comment by Convly** [comment]
@jahidanowar your project uses Strapi **v3.1.4**. The AdminUser GraphQl type has been updated in **v3.1.7** (alongside the introduction of `populateCreatorFields`).
You can try to upgrade to the latest version and see if it fix the issue. (see https://github.com/strapi/strapi/pull/8052)

**Comment by jahidanowar** [comment]
The Bug has been fixed in **v3.2.0**

**Comment by amitav13** [comment]
> I do need to be able to capture this information though, at least the user that's creating the item via the API. Where in the stack should I be checking this/adding it manually?

@Convly is there a way to set this manually in the model's controller? This is what I'm trying currently in `./api/product/controllers/product.js:
```js
async create(ctx) {
    let entity;
    const { id } = ctx.state.user;
    if (ctx.is("multipart")) {
      const { data, files } = parseMultipartData(ctx);
      const productObj = {
        ...data,
        created_by: id,
        updated_by: id,
      };
      entity = await strapi.services.product.create(productObj, {
        files,
      });
    } else {
      const productObj = {
        ...ctx.request.body,
        created_by: id,
        updated_by: id,
      };
      entity = await strapi.services.product.create(productObj);
    }
    return sanitizeEntity(entity, { model: strapi.models.product });
  },
```
I'm able to get the user's `id` fine, but the `entity` returned from `strapi.services.product.create` strips out the IDs that I add in. Any ideas?

**Comment by Convly** [comment]
Hello, `created_by` & `updated_by` are fields used internally by Strapi to manage roles & permissions for RBAC among other things.

Those fields are meant to be populated with specific models (administrators) and are not open to customization. If you try to populate them with different models such as users from the Users & Permissions plugin, it'll probably break other features.

If you really want to have authors relationships between your content and users (Users & Permissions), you can do so by updating your model and add a relationship field, then customize your controllers to automatically populate this fields with the `ctx.state.user`.

Hope it helps you

**Comment by atazmin** [comment]
This worked for me in v4, src/index.js

```
"use strict";

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register({ strapi }) {
    const extensionService = strapi.plugin("graphql").service("extension");

    const extension = ({ nexus }) => ({
      types: [
        nexus.objectType({
          type: "Creator",
          name: "Creator",
          definition(t) {
            t.int("id");
            t.string("firstname");
            t.string("lastname");
          },
        }),
        nexus.extendType({
          type: "Post",
          definition(t) {
            t.field("createdBy", {
              type: "Creator",
              async resolve(root) {
                const query = strapi.db.query("api::post.post");
                const post = await query.findOne({
                  where: {
                    id: root.id,
                  },
                  populate: ["createdBy"],
                });

                return {
                  id: post.createdBy.id,
                  firstname: post.createdBy.firstname,
                  lastname: post.createdBy.lastname,
                };
              },
            });
          },
        }),
      ],
    });

    extensionService.use(extension);
  },
  // register(/*{ strapi }*/) {}, // orig

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap(/*{ strapi }*/) {},
};
```
