### ISSUE TITLE
Allow overriding database connectors, similar to plugin & admin extensions with "extensions" and "admin".

### ISSUE THREAD

**Issue by joonamakinen** [strapi/strapi#8189]
I currently cannot configure mongoose connector to use custom SSL Certificate for SSL-secured MongoDB connection. Since one cannot override connector like plugins, it would get extremely fiddly to override node packages with local folders.

Example: SSL certificate support for mongoose connector (by inserting "server" key if exists)

**connectors/mongoose/utils/connectivity.js**
```js
'use strict';

module.exports = async ({ connection }) => {
  console.log("Custom mongoose connector registered")
  const Mongoose = require('mongoose');

  const { username, password, srv } = connection.settings;
  const { authenticationDatabase, ssl, server={} } = connection.options;

  const connectOptions = {};

  if (username) {
    connectOptions.user = username;

    if (password) {
      connectOptions.pass = password;
    }
  }

  if (authenticationDatabase) {
    connectOptions.authSource = authenticationDatabase;
  }

  connectOptions.ssl = ssl ? true : false;
  connectOptions.useNewUrlParser = true;
  connectOptions.dbName = connection.settings.database;
  connectOptions.server = server

  return Mongoose.connect(
    `mongodb${srv ? '+srv' : ''}://${connection.settings.host}${
      !srv ? `:${connection.settings.port}` : ''
    }/`,
    connectOptions
  ).then(
    () => {
      Mongoose.connection.close();
    },
    error => {
      Mongoose.connection.close();
      throw error;
    }
  );
};
```

**Comment by derrickmehaffy** [comment]
@alexandrebodin this should be something made easier by the[ database refresh](https://portal.productboard.com/strapi/1-roadmap/c/73-database-layer-v4) yeah?

**Comment by alexandrebodin** [comment]
Helo, we won't make the connector overwritable like with the extensions as we want to move away from this unmaintanable way of extending the code. You can always fork the connector as it is the cleanest way to keep up to date we the repo code and customize it. 

In the refresh we can certainly expose the connection a bit more to make it customizable though ;)

**Comment by joonamakinen** [comment]
I'll manage by loading local version of the module `strapi-connector-mongoose` for now. I suppose this issue can be closed once related database refresh git issue is linked. Whatever you see fit 👍

**Comment by jankrumrey** [comment]
After updating "strapi-connector-mongoose" from 3.1.6 to 3.1.7, all connections to AWS documentDB cluster (engine version 3.6, tls enabled) fail with 'Error connecting to the Mongo database. unable to get local issuer certificate'.
It works when I add `connectOptions.sslValidate = false;` directly in the strapi-connector-mongoose package, so I guess I have to use a similar approach as @joonamakinen to make ssl validation work. 
We **definitely** need a way to pass in additional options used for database connections!

**Comment by derrickmehaffy** [comment]
Connector system no longer exists in v4, marking as closed
