### ISSUE TITLE
Create new request lifecycles in addition to the current query lifecycles

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#8193]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Based on https://github.com/strapi/strapi/discussions/6871#discussioncomment-90811

Creating a feature request for this, we should be passing the ctx into the model lifecycles for various reasons. Off the top of my head I could see some usage in say beforeX to compare new data to old data (maybe some kind of version history or audit log or something).

Yes this could be done via a custom controller but it's far easier to build a model lifecycle in most users cases.

---

Edited based on https://github.com/strapi/strapi/issues/8193#issuecomment-703805133

A rough breakdown per my convo with @alexandrebodin will be something like this (a small part of the new request layer we are planning)

![image](https://user-images.githubusercontent.com/8593673/95121700-42634e00-0704-11eb-9dc5-8a7cb7fbd011.png)

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/auto-fill-created-by-field/293/4

**Comment by alexandrebodin** [comment]
As discussed already in the core team. Passing the koa context into the database lifecycles will not happen as it is not the role of the database ot handle http request data. 

We need to add a new set of lifecycles at the request level (e.g Rest or GraphQL) that will receive the good context according to the context.

**Comment by derrickmehaffy** [comment]
I've added a sample from some of our internal planning docs, just note that image isn't set in stone as we are still planning the new request layer. (This sits above the query layer which is more DB focused)

**Comment by derrickmehaffy** [comment]
This will also apply to throwing errors with custom messages into the Admin, as the current DB lifecycles do not handle this well.

**Comment by jordankittle** [comment]
I too would like to set the author based on the current user using lifecycle hooks.

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed

You should use route middlewares

**Comment by Frankiamme** [comment]
@derrickmehaffy , could you give an example of this. I've tried implementing a workaround on v4 from the route middlewares but the ctx.state.user object isn't being passed down to the beforeCreate lifecycle

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy , could you give an example of this. I've tried implementing a workaround on v4 from the route middlewares but the ctx.state.user object isn't being passed down to the beforeCreate lifecycle

Not sure what your asking, how to do what?
