### ISSUE TITLE
Passing any undefined parameter in query method `findOne` returns first record from collection

### ISSUE THREAD

**Issue by RicardsRikmanis** [strapi/strapi#8201]
**Describe the bug**
Passing any undefined parameter in query method `findOne` returns first record from collection instead of no records.

**Steps to reproduce the behavior**

1. Use following or similar code
 ```
    const id = undefined;
    const environment = await strapi.query('environment', 'environment').findOne({ id });
    // or
    const noSuchParamInModel = undefined;
    const environment = await strapi.query('environment', 'environment').findOne({ noSuchParamInModel });
```
2. `environment` contains first record from collection instead of no records

**Expected behavior**
`findOne` should only return record that is found based on the passed parameters.

**System**

- Node.js version: v12.18.4
- NPM version: v6.14.6
- Strapi version: 3.1.6
- Database: MongoDB
- Operating system: Ubuntu

**Comment by MattieBelt** [comment]
Hey @RicardsRikmanis,

I did some testing, not sure if it desired behavior, in some way it could be. That to the team to decide.
For example:

1)
```js
   const environment = await strapi.query('environment', 'environment').findOne();
```
Simply returns the first result because no params are given.

2)
```js
   const environment = await strapi.query('environment', 'environment').findOne({ noSuchParamInModel: 'anyValue' });
```
Gives back a error: `Error: Your filters contain a field 'noSuchParamInModel' that doesn't appear on your model definition nor it's relations`

3) 
```js
   const environment = await strapi.query('environment', 'environment').findOne({ noSuchParamInModel: undefined });
```
Looks for any result that doesn't have the field, this because the param value is `undefined`. 
Because the field doesn't exist on the the model, every entry will have this field as undefined, so it simply returns the first one. 

This could in some way be seen as a bug, but also a logical way of handling the find params. 
But as expected, like in example 2, it should return an Error about a none existing field, whatever the value might be.

**Comment by derrickmehaffy** [comment]
In the 3rd option it should return the same error as the 2nd.

Poking @alexandrebodin to confirm

**Comment by MattieBelt** [comment]
Also as @RicardsRikmanis mentioned 
```js
const environment = await strapi.query('environment', 'environment').findOne({ id: undefined }) 
   
// and also
   
const environment = await strapi.query('environment', 'environment').findOne({ anyParamInModel: undefined })
```
Should not return the first result, but rather none and throw an error.

**Comment by alexandrebodin** [comment]
Hey, 

undefined id should return null and unknow params should return the filter error. the field must be check to be truthy or ingored in the code I also think it should be stricter

**Comment by derrickmehaffy** [comment]
(Set priority as low as there isn't a security risk here)

**Comment by dwarf666** [comment]
Any update on this issue? We have a related bug to this, where the id is set in the database, but when searching for `null` or `undefined` it will return the first object (which again causes internal issues). 

E.g: 
`const client = await strapi.services.clients.findOne({ mollie_id: undefined });`

Then `console.log(client)` will return something like this: 
`{
  id: 1,
  mollie_id: 'mtd_XXXX',
  subscription_id: 'sub_XXXXX',
  start_date: '2020-12-08'
}`

As you can see the field `mollie_id` is set, whereas the filter is `undefined` (or `null`, same effect).

**Comment by rkok** [comment]
I ran into the same issue as described by @dwarf666 

@derrickmehaffy In my opinion this bug deserves higher priority. A programmer who is not aware of this behaviour would assume that `findOne` only returns rows that __match__ the filter.

**Comment by MattieBelt** [comment]
Any update on #8490 @alexandrebodin?

**Comment by alexandrebodin** [comment]
@MattieBelt we have a PR that is changing this code soon so we will ping you to update the PR when possible :)
