### ISSUE TITLE
Database error after migrating from 3.1.5 to 3.2.0

### ISSUE THREAD

**Issue by YannickMol** [strapi/strapi#8212]
**Describe the bug**
After migrating from 3.1.5 to 3.2.0 succefully on my local machine, I have deployed to production on Amazon EC2 and RDS. I am getting a database error (PostgreSQL), stating that "model_def_strapi::core-store" and all other "model_def_strapi" keys are not getting an ID assigned. See attachment for the error log. I have to manually set the id in the core_store table to allow for null values, after which the "model_def_strapi" keys are inserted in the table, with a null value in the id field however.

**Steps to reproduce the behavior**
1. Deploy to production using NODE_ENV=production npm run build --clean and following the Amazon deployment instructions in the Strapi docs.
2. Try to access the Strapi admin environment.
3. Receive a 502 internal error - the Amazon RDS error log can be found under Screenshots below.

**Expected behavior**
Clean insertion of the new "model_def_strapi" keys into the database, so that the error does not occur.

**Screenshots**
![amazonrds](https://user-images.githubusercontent.com/13256289/95266857-573eff00-0834-11eb-91ac-ebcfb5faf671.PNG)

**System**
- Node.js version: 12.18.4
- NPM version: 6.14.8
- Strapi version: 3.2.0
- Database: PostgreSQL 10
- Operating system: Ubuntu Server 18.04 LTS (HVM), SSD Volume Type

**Comment by YannickMol** [comment]
@derrickmehaffy hereby the bug, as discussed over Slack, would you or anyone else be able to help out?

**Comment by derrickmehaffy** [comment]
@YannickMol we have a similar issue (different error message) but related to the `all other "model_def_strapi" keys are not getting an ID assigned`

See: https://github.com/strapi/strapi/issues/8227 

In my test project I locally linked a modified `strapi-connector-bookshelf` package, can you try that in your project and test to see if that also resolves your issue?

If so then the bug will be fixed tmrw via: https://github.com/strapi/strapi/pull/8232

**Comment by YannickMol** [comment]
Thanks, it did!

**Comment by derrickmehaffy** [comment]
Perfect, for now @YannickMol I'm going to close this one in favor of the other issue I linked. For now you can use that workaround and tmrw I believe we will release v3.2.2 hotfix that you can revert the workaround and just update to.

**Comment by YannickMol** [comment]
Just confirming that this issue was solved after upgrading to v3.2.2.

**Comment by laportem** [comment]
I have just installed a fresh 3.2.4 and are having the same issue
