### ISSUE TITLE
Creator (created_by and updated_by) fields are not filled via API

### ISSUE THREAD

**Issue by weidox** [strapi/strapi#8216]
**Describe the bug**
Creator (created_by and updated_by) fields are not filled when using API endpoints or service methods. Does work only via Admin. Checked regular API and also tried to override Upload plugin, same behavior.

**Steps to reproduce the behavior**
1. Modify the section of "any-your-model.settings.json" file, by adding "populateCreatorFields" option, like:
```
  "options": {
    "increments": true,
    "timestamps": true,
    "populateCreatorFields": true
  }, 
```
2. Set up users-permissions that "create" method on /any-your-models endpoint requires authentication, so you don't miss to send JWT token. Send a POST request to /any-your-models endpoint with JWT token to have user logged in, with just {} as contents for simplicity. Then do a GET request to same /any-your-models endpoint and see that the newly created object looks like this, missing creator fields: 
```
    {
        "_id": "5f7d66746617ed3fa0740691",
        "createdAt": "2020-10-07T06:55:48.511Z",
        "updatedAt": "2020-10-07T06:55:48.511Z",
        "__v": 0,
        "id": "5f7d66746617ed3fa0740691"
    }
```
3. Now create a new entry in collection via Strapi Admin. Then do a GET request to same /any-your-models endpoint and now see that the newly created object looks like this, this time having creator fields: 
```
    {
        "_id": "5f7d6619e980c087049900d7",
        "createdAt": "2020-10-07T06:54:17.294Z",
        "updatedAt": "2020-10-07T06:54:17.310Z",
        "__v": 0,
        "created_by": "5f6c7af033c39684949fe2b5",
        "updated_by": "5f6c7af033c39684949fe2b5",
        "id": "5f7d6619e980c087049900d7"
    },
```

**Expected behavior**
Creator fields should be filled in all cases (except when there is no logged in user / no JWT token).

**Screenshots**
Not required.

**Code snippets**
Not required, can be done just though REST API.

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.7
- Database: MongoDB
- Operating system: Windows

**Additional context**
Guess issue could be related to MongoDB as it was already weird that date fields created_at/updated_at are named differently on MongoDB as createdAt/updatedAt. Don't know how it worked before, but also guess it could be spoiled by #7177.

**Comment by alexandrebodin** [comment]
Hello @weidox  this is actually the expected behavior.
The administration panel users and the users-permissions plugin users are two different collections. The created_by and updated_by fields are a relation to the admin panel users and cannot be link to the user-permissions plugin users. This is why in the API you cannot set them. 

 If you want to link your data to the user you manager with the users-permission plugin you will need to add fields in your models for it and add some code to set them in the API. This is up to you :)

Closing as ressolved

**Comment by weidox** [comment]
Am I supposed to extend File data model from Upload plugin? I want to have creator field directly on Media type property, but there's no way to modify the model easily (unlike say User model which is accessible via content types builder). I tried to copy File.settings.json from plugin into extensions directory the same path, but adding new fields did not allow to persist them in database. Maybe there is some guide on how to do that?

**Comment by alexandrebodin** [comment]
You can extend the File model with the extensions yes :) indeed it is not exposes in the content type builder so you will need to do it manually. You can have a look at this thread to learn more https://github.com/strapi/strapi/issues/8069

**Comment by weidox** [comment]
Sadly that does not work, it just ignores new fields. I found in plugin Upload.js, there's method "formatFileInfo", which explicitly takes only the few known fields. And overriding that one seems to be very complex.

**Comment by alexandrebodin** [comment]
You can't set the creator fields manually via the API this would be a security issue. This needs to be done in code. I suggest you go to our slack or the forum to get some help for this usecase ;)

**Comment by weidox** [comment]
Not, I tried to add my custom field, named "owner". Managed to do it actually, but had to copy and override a bit of plugin service code, to handle "owner" property in the "formatFileInfo" function I mentioned.

**Comment by darron1217** [comment]
I'm experiencing same issue but I've logged in with AdminUser token.
I'm currently using GraphQL endpoint with AdminUser token.

`created_by` and `updated_by` fields are not updating. (Even I tried manually passing AdminUser id as parameter)

**Comment by derrickmehaffy** [comment]
@darron1217 those fields are -only- filled by the admin panel and not the user REST/GraphQL endpoints (they are relations to the `strapi-admin` package's administrators model)

Locking thread as this is intended.
