### ISSUE TITLE
Split project setup process

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#822]
Extract the dependencies installs of the project and in each plugin from the `npm run setup` and move it to `npm install`. Also add three new build npm scripts.

* `npm install`: install all the dependencies (project & plugins)
* `npm run build:admin`: Build only the admin.
* `npm run build:plugins`: Build only the plugins.
* `npm run build`: `npm run build:admin && npm run build:plugins`.

Reference: https://github.com/strapi/strapi/issues/798#issuecomment-374502785 & https://github.com/strapi/strapi/issues/798#issuecomment-374544589

**Comment by Aurelsicoko** [comment]
Can you make the necessary changes in the PR https://github.com/strapi/strapi/pull/705? We need to update the documentation as well.

**Comment by abdonrd** [comment]
I'm afraid that in the short term, no. 😕

(I'm out on vacation 😅)

**Comment by Aurelsicoko** [comment]
Oops... No worries, we will handle that. Let's this issue open and when we (or you) will have time we will make the changes!

**Comment by soupette** [comment]
I'm closing this issue.

Here's the command that have been set:

- `npm run setup:build` (in the monorepo, it will build all the plugins)
- `npm run setup` (in the monorepo, it will just install the dev environment)
- `npm run setup` (in a project, it will only build the admin)
- `npm run setup --plugins` (in a project, it will build all the plugins)
