### ISSUE TITLE
Cannot publish draft record when component field is null (v3.2.0)

### ISSUE THREAD

**Issue by charlatan154** [strapi/strapi#8220]
**Describe the bug**

After upgrading from 3.1.6 to 3.2.0 and testing new Draft/publish system, i cannot publish draft record when component field is null.

**Steps to reproduce the behavior**

1. Create a new collection type, with Draft/publish system enabled.
2. Add a text field and a component field.
3. Create a new record of that type. (Component field is optional, so it can be null)
4. Cannot publish this record, until component field has a value.

**Expected behavior**

Publish record even if component field is empty.

**Screenshots**
The issue seems to be with administration panel.

Console log error
![Screenshot 2020-10-07 at 1 16 25 PM](https://user-images.githubusercontent.com/1842448/95318617-79ba3200-089f-11eb-9ac6-ef015981ce50.png)

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.2.0
- Database: mongodb
- Operating system: MacOs

**Comment by hadynz** [comment]
I have traced this issue to the [`getDraftRelations`][1] method introduced in https://github.com/strapi/strapi/commit/5a6d9a89b8986ec89097cdffd811ba32b86faf95 which is not handling nulls.

[1]: https://github.com/strapi/strapi/blob/442f38a4ba37baaf314f5958243169406b6b1823/packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils/getDraftRelations.js#L5
