### ISSUE TITLE
Remove unneeded files from new generated project

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#823]
There are some files necessary for the development and npm publication, but they are not necessary for the end users of Strapi.

For example:
* `.npmignore`
* `admin/.editorconfig`
* `admin/.gitattributes`
* `admin/.npmignore`
* `admin/admin/.npmignore`
* `plugins/**/.editorconfig`
* `plugins/**/.gitattributes`
* `plugins/**/.npmignore`
* `plugins/**/admin/.npmignore`

Reference: https://github.com/strapi/strapi/issues/798#issuecomment-374505241 & https://github.com/strapi/strapi/issues/798#issuecomment-374544589

**Comment by Aurelsicoko** [comment]
As I already said in another issue, you can make the changes in the current PR #705, we will improve them 👍

**Comment by lauriejim** [comment]
@abdonrd Can we close this issue since we merged your PR #1122 ?

**Comment by abdonrd** [comment]
@lauriejim I think it can stay open. There are still files that could be deleted like the `.npmignore`s.

**Comment by abdonrd** [comment]
@lauriejim with the last version (`v3.0.0-alpha.17`), I see a new `.snyk` file. :😅
