### ISSUE TITLE
Emails stored in mixed case when created with provider login/registration

### ISSUE THREAD

**Issue by bglidwell** [strapi/strapi#8235]
**Describe the bug**
When logging in with a provider (Microsoft for example), a user account is automatically created if there is not one already. When this account is created, the username/email can be mixed case from the provider (Test_User@domain.com). If you then modify this user account, the admin user-edit function will save as lowercase email (which is what should happen). However, when the user tries to log in again, it compares the received email (mixed case) to the stored email in the database (lowercase) and will not match. 

**Steps to reproduce the behavior**

1. Create user with OAuth provider that has mixed case email (Microsoft)
2. Note that user is created in database with mixed case email and username
3. User should be able to login to system
4. Open user account in admin panel and edit any parameter (role for example)
5. Notice user's email is now lowercase
6. User is no longer able to login to system

**Expected behavior**
There's one of two routes Strapi can go on this, but it needs to be consistent and global:
1. ALL emails and usernames should ALWAYS be stored lowercase so the comparison can always be done with lowercased strings
2. Whenever querying the database for username/email, the LOWER()/UPPER() should ALWAYS be used on the field and value before comparison
- SELECT * FROM sometable WHERE UPPER(email) = UPPER('value') 

**Screenshots**
When user created by logging in with provider
![image](https://user-images.githubusercontent.com/14822908/95392851-1a6c1a00-08bf-11eb-9182-d05a3f9b617d.png)
After editing role for user
![image](https://user-images.githubusercontent.com/14822908/95392983-543d2080-08bf-11eb-8317-58d7c4ff3da9.png)

**System**

- Node.js version: 14.13.0
- NPM version: 6.14.8
- Strapi version: 3.2.0
- Database: Heroku Postgres
- Operating system: Heroku dyno

**Comment by lascapi** [comment]
Hi, we got the same problem in production. There is any workaround to wait for the fix #8247 ? 
Thank's.

**Comment by derrickmehaffy** [comment]
> Hi, we got the same problem in production. There is any workaround to wait for the fix #8247 ? 
> Thank's.

@lascapi you will have to use extensions to modify the users-permission per https://github.com/strapi/strapi/pull/8247

I would also suggest running a database migration and convert all existing emails in your database to lowercase.

**Comment by devpascoe** [comment]
I'm using AWS Cognito. I ended up creating a lambda in the Pre Token Generation trigger. Something like this...
```
exports.handler = (event, context, callback) => {
    if (event?.request?.userAttributes?.email) {
        event.response = {
            "claimsOverrideDetails": {
                "claimsToAddOrOverride": {
                    "email": event.request.userAttributes.email.toLowerCase()
                }
            }
        };
    }
    callback(null, event);
};
```
Now the email attribute in the jwt is lowercase and matches nicely to strapi.

**Comment by derrickmehaffy** [comment]
fixed in v4 in the above pr ^
