### ISSUE TITLE
Optimize the build process time

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#824]
Right now the build process is quite long.

Also I don't know if it would make sense to share a single script for the plugins build instead of each plugin having its own.

Reference: https://github.com/strapi/strapi/issues/798#issuecomment-374505594 & https://github.com/strapi/strapi/issues/798#issuecomment-374544589

**Comment by soupette** [comment]
I'm working on migrating to webpack 4 it should reduce the building time a bit.
Also, I'm implementing the build of each plugin in async wich should also decrease the time.

**Comment by abdonrd** [comment]
Sounds really great, thanks @soupette! 👏

**Comment by soupette** [comment]
See #1033
