### ISSUE TITLE
[2020-10-08T15:33:46.300Z] error Error: getaddrinfo ENOTFOUND x86_64-conda_cos6-linux-gnu  and temporary solution 

### ISSUE THREAD

**Issue by lemarcgagnon** [strapi/strapi#8252]
**Describe the bug**

After any install of strapi with sqlite ( i never could installed any other db yet) I get this message:

(base) marc@mintmarc:~/Desktop/strapi/project-name$ yarn develop
yarn run v1.22.5
$ strapi develop
[2020-10-08T15:33:46.300Z] error Error: getaddrinfo ENOTFOUND x86_64-conda_cos6-linux-gnu
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)

**Steps to reproduce the behavior**

either installing with :

yarn create strapi-app my-project --quickstart or
npx create-strapi-app my-project --quickstart and even 
Installing using Docker

will cause this issue

**Expected behavior**

not to loose acces to localhost

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v12.13.1
- NPM version: 6.14.5
- Strapi version:  (npm info scrapi version gave me 0.1.0 but i used 
 
Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Thu Oct 08 2020 15:31:03 GMT+0000 (Coordinated … │
│ Launched in        │ 9892 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 205                                              │
│ Version            │ 3.2.1 (node v12.18.2)                            │
│ Edition            │ Community  

- Database: all but the sqlite
- Operating system: Mint Linux 19.3

**Additional context**

TO SOLVE THIS ISSUE:

I have to pass this command:
(base) marc@mintmarc:~/Desktop/strapi/project-name$ export HOST=localhost

How can I fix this for good?

Thanks,

Marc

**Comment by derrickmehaffy** [comment]
@lemarcgagnon I was not able to reproduce this on Linux Mint 20 (My daily, but I previously used LM 19.3)

By default we attempt to bind on `0.0.0.0` or all interfaces (including localhost). This is something to do with your local environment that we need more information on to reproduce.

**Comment by lemarcgagnon** [comment]
I read somewhere on the net that anaconda was messing with this... and I have anaconda installed... it might be that... thanks for the help!

Marc
