### ISSUE TITLE
[3.2.1] Draft & Publish, getting not published content by fetching related content type

### ISSUE THREAD

**Issue by janKo29** [strapi/strapi#8259]
**Describe the bug**
Having two Content Types in relation to each other, Draft & Publish feature working not well.

**example:**
I have two content types: "events" and "locations" in relation to each other, location can have many events. Some events are not published and it works fine if im getting data by "strapi/events", but if im getting data by "strapi/locations/1" i recieve all events, wich are in relation with this location, even if they are not published.

**Expected behavior**
Not published content is unavailibel from all endpoints

**Comment by alexandrebodin** [comment]
Hello, this was fixed and released in 3.2.2 this morning. Can you update and check again ?

**Comment by janKo29** [comment]
Hello, works great after the update to 3.2.2, thanks!

**Comment by cwray-tech** [comment]
Hey @alexandrebodin I am having this issue as well even after updating to 3.2.2. Do all my models need to have the draft/publish feature enabled?

**Comment by alexandrebodin** [comment]
Hello @cwray-tech, no need. it should work just fine. Can you reproduce it with a new project (wondering if the version bumped worked well) ?  If yes can you give us the steps to reproduce this (e.g the model structure ;))

**Comment by cwray-tech** [comment]
@alexandrebodin I got it to work. I had updated the MongoDB connection package as well, so I went back to the version i had before and it worked. I think is what the issue was. haha. Maybe? who knows? anyways it is working fine now.
