### ISSUE TITLE
Wrong CSS overflow for Windows

### ISSUE THREAD

**Issue by altteo** [strapi/strapi#826]
**Node.js version**:
8.10.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.11.1

**Operating system**:
Windows 10, Windows Server 2008 R2, maybe all other Windows versions.
Any browser.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Vertical scrollbar is always visible in the LeftMenuLinkContainer

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Login to /admin on Windows system in any browser

**What is the expected behavior?**
The problem is because of the CSS
```
leftMenuLinkContainer { /* stylelint-ignore */
  ...
  overflow-y: scroll;
}
```
should be overflow-y: auto;

**Comment by lauriejim** [comment]
Hi @altteo can you submit a PR to fixe it please.
