### ISSUE TITLE
Forgot password API fetch returning 400 error

### ISSUE THREAD

**Issue by Dezzign** [strapi/strapi#8266]
Strapi Version │ 3.2.2 (node v12.18.4)

Hi, the Forgot password fetch never works and returns 400 bad request all the time.

Regarding public user permissions etc - every single user role permission is set to enabled/allow etc (just for debugging).

Via a simple JS fetch like so:
```
fetch{'http://localhost:1337/auth/forgot-password',
        method: 'POST',
        body: JSON.stringify( {
        email: 'abc@example.com'
    }),
    headers: {
       'Content-type': 'application/json; charset=UTF-8'
     }
 })
     .then(response => {
     if (response.ok) {
        // success.classList.add('show-success');
      }
 })
    .catch(function (error) {
         // return console.warn('Something went wrong.', error);
     });
```

And exactly the same issue when attempting the same fetch via Postman:
{
    "email": "james@hotmail.com"
}

All that is returned is:
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {},
    "data": {}
}

And yes the reset password page has been defined in the Strapi admin:
Reset password page
http://localhost:1337/reset-password.html
(URL of your application's reset password page)

It's exact same issue as this Git comment here: [Same as this issue](https://github.com/strapi/strapi/issues/6440#issuecomment-698013885)

Thanks

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by DevStores** [comment]
Hi,

I'have the same issue. 400 Bad Request.

**Comment by derrickmehaffy** [comment]
@DevStores please open a new issue. Thanks!
