### ISSUE TITLE
Unable to add Discord Login

### ISSUE THREAD

**Issue by mtrucc** [strapi/strapi#8267]
**Describe the bug**
Unable to add Discord Login
https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers

**Steps to reproduce the behavior**
Follow the steps exactly
https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers
But
http://localhost:1337/connect/discord/callback?code=TT4c0ltCdDtCejvvVIDnJkB43FFIz9
to
http://localhost:3000/connect/discord/redirect?error=request-compose%3A%20timeout
return 302 error

**Expected behavior**
Can ues Discord Login

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.18.0
- NPM version: 6.14
- Strapi version: 3.2.1
- Database: default
- Operating system: Win10

**Additional context**
I think the error comes from the grant module

**Comment by derrickmehaffy** [comment]
`Strapi version:` Please add your Strapi version.

**Comment by mtrucc** [comment]
I just confirmed that Strapi uses the Grant library, this library uses request-compose, in some cases it cannot be used normally.
This problem should be fixed by grant

**Comment by naturalvoicer** [comment]
I also encountered the same problem
![image](https://user-images.githubusercontent.com/70963486/105633143-ee869b80-5e91-11eb-8abb-d9b439f15c74.png)
