### ISSUE TITLE
Schedule to publish a draft version

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#8268]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Schedule to publish a draft version.

**Comment by derrickmehaffy** [comment]
User is looking for a built in option, my previous link is a work around to do it per-project.

**Comment by derrickmehaffy** [comment]
Closing this in favor of: https://feedback.strapi.io/customization/p/content-scheduling

We are considering this, if those who have commented are still interested in this can you please go log your vote on the feedback page (we are trying to clean up issues so we can fix bugs a little faster :smiley: )
