### ISSUE TITLE
Specify publication state in request headers

### ISSUE THREAD

**Issue by pmrotule** [strapi/strapi#8274]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I was really looking forward to the Draft and Publish feature and now it's here 🎉 (amazing, thanks!!). One thing that bothers me though is the fact that you need to specify the desired `publicationState` in [every request](https://strapi.io/documentation/v3.x/plugins/graphql.html#filters). Not sure how most people intend to use the feature, but in my case, I would like to always fetch the draft versions on my staging website (locally as well) and fetch only the published versions on production. Considering the current implementation, it means I need to always think about including the `publicationState` in every single request I make and base it on my current environment.

I'm used to do it with Contentful by calling different endpoints (`preview.contentful.com` includes the drafts and `cdn.contentful.com` includes the published versions only). Since Strapi is self-hosted, it could be done by specifying a "publication-state" header which would be very handy with GraphQL as it would be tied to your Apollo client (same as the authorization header) and therefore provided in each request. Passing the `publicationState` filter in a specific request could still override that header if necessary. What do you guys think?

**Comment by derrickmehaffy** [comment]
I really like this idea, going to poke @JabStrapi and @Aurelsicoko to get their thoughts on it.
