### ISSUE TITLE
Unable to upload to media library (500 Internal Server Error) in production

### ISSUE THREAD

**Issue by royketelaar** [strapi/strapi#8275]
**Describe the bug**
When trying to upload anything to the media library in production I'm getting a 500 Internal Server Error, for some reason it just works in develop so I'm thinking it maybe has something to do with postgres (which I use on production, instead of SQLite locally).

**Steps to reproduce the behavior**
1. Go to 'Media Library'
2. Try to upload a file
3. Get 500 Internal Server Error

**Expected behavior**
Upload works

**Screenshots**
![Screenshot 2020-10-10 194602](https://user-images.githubusercontent.com/2485534/95661673-64f4cd00-0b31-11eb-9a3c-a2c72ee03721.png)

**Code snippets**
If I check the log with `pm2 logs` on my server it also gives me these error messages:

```
error Error: EACCES: permission denied, open '/srv/strapi/my-project/public/uploads/testimage.jpg'
error Error: Internal Server Error
at convertToStrapiError (/srv/strapi/my-project/node_modules/strapi-plugin-upload/errors.js:36:26)
at Object.upload (/srv/strapi/my-project/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
debug POST /upload (416 ms) 500
```

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.2.3
- Database: Postgres
- Operating system: Unix/Linux on a Digitalocean droplet

**Additional context**
Only thing I did that I think maybe could have an impact on this error is that I dropped the strapi postgres database (to clear some data) and recreated it afterwards. Every other thing besides media upload works like adding posts with text.

My dependancies:

```
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.3.0",
    "slugify": "^1.4.5",
    "sqlite3": "latest",
    "strapi": "3.2.3",
    "strapi-admin": "3.2.3",
    "strapi-connector-bookshelf": "3.2.3",
    "strapi-plugin-content-manager": "3.2.3",
    "strapi-plugin-content-type-builder": "3.2.3",
    "strapi-plugin-email": "3.2.3",
    "strapi-plugin-graphql": "3.2.3",
    "strapi-plugin-responsive-image": "^0.2.0",
    "strapi-plugin-upload": "3.2.3",
    "strapi-plugin-users-permissions": "3.2.3",
    "strapi-utils": "3.2.3"
  },
```

Anyone had this problem before and maybe know a direction or solution to where the problem possibly lies?

**Comment by laurenskling** [comment]
Looks like you are using local folder for uploads and the folder isn't writable (so the image isn't uploaded, thus throwing an error later on)

**Comment by TasTing** [comment]
use providers instead of local folder.

Enabling the provider
To enable the provider, create or edit the file at ./config/plugins.js

```
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      region: 'aws-region',
      params: {
        Bucket: 'my-bucket',
      },
    },
  },
});
```

Make sure to read the provider's README to know what are the possible parameters.

**Comment by derrickmehaffy** [comment]
Yeah based on the error `error Error: EACCES: permission denied, open '/srv/strapi/my-project/public/uploads/testimage.jpg'`

One of two things is happening:
- You are on a read-only filesystem => Use a provider
- Your permissions for the `./public/uploads` is somehow restricted (not owned by the correct user/group, or it's directory/file permissions aren't)

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed for now, please provide some additional information and if it can be reproduced we can reopen this. Else if you would like, you can open up a question on our forum to discuss more.

https://forum.strapi.io/

**Comment by royketelaar** [comment]
I fixed the problem indeed by adding a provider. Thanks @TasTing

**Comment by ktpones** [comment]
I was having the same issue 

![image](https://user-images.githubusercontent.com/5227618/98739867-22444000-23d0-11eb-8b19-9d8c006032c2.png)

What I did, I update my `package.json` & change build command to `strapi build --clean`. After that I was able to upload the file to `AWS` as well `cloudinary`.

![image](https://user-images.githubusercontent.com/5227618/98740055-6e8f8000-23d0-11eb-9f56-1a3744dabbc9.png)

**Comment by bipulpoudel** [comment]
I have changed the permission of the folder and the error is solved. You can go to the server CLI and use command:

chmod -R 777 path/to/directory/

Hope this helps!

**Comment by PeCrio** [comment]
chmod -R 777 path/to/directory/ worked for me, thanks @bipulpoudel

**Comment by derrickmehaffy** [comment]
`chmod -R 777`

Would advise against just a general 777 chmod

**Comment by PeCrio** [comment]
Hi @derrickmehaffy, can you please elaborate why and possibly advise a safer option?

**Comment by derrickmehaffy** [comment]
https://pimylifeup.com/chmod-777/

Unless you absolutely need 777 (and that's very rare) you should clearly define what permissions you need.

And if you are running Strapi properly as a service user whom owns the directory you should not need to chmod anything, just a simple chown.

**Comment by oguzdurmaz-dev** [comment]
Please check your time-zone

**Comment by aegirorn** [comment]
I am having the same problem using Cloudinary and Heroku. My plugins.js contains this:

`module.exports = ({ env }) => ({
  upload: {
    provider: "cloudinary",
    providerOptions: {
      cloud_name: env("CLOUDINARY_NAME"),
      api_key: env("CLOUDINARY_KEY"),
      api_secret: env("CLOUDINARY_SECRET"),
    },
  },
});
`

Can some one explain better how to apply fixes suggested here? @oguzdurmaz-dev suggests checking the time-zone. How and where is that done?

**Comment by aegirorn** [comment]
I apologize. Looking at the Heroku log revealed my problem which was a wrong value in the CLOUDINARY_KEY.

Everything works fine now.

**Comment by EdsonSilva-SternTI** [comment]
Muito obrigado galera, eu estava sem entender o problema que estava ocorrendo com um sistema que utiliza o strapi e o problema era justamente a falta das variáveis de ambiente no heroku. Esse tópico me ajudou muito.
