### ISSUE TITLE
Component Field strange behavior

### ISSUE THREAD

**Issue by onsombal** [strapi/strapi#8276]
Hi, 

I'm using Strapi-3.2.3 and MongoDB Atlas. I imported a JSON file into MongoDB Atlas. I defined a Strapi collection with field names identical to the MongoDB Atlas database field names.

**Describe the bug**
I created a **Component Field** with two text fields. I then added this component field to one of my Collections. I tested the Component both as a **Non-Repeatable** and **Repeatable field**. 

1. The Non-Repeatable field caused Strapi to return an empty Component Field. GraphQL returned "null" values for the Component Field.
2. The Repeatable field caused Strapi to error and never return a view of the Collection. GraphQL returned "null" values for the Component Field.

The remaining examples focus on the Non-Repeatable Component Field since it did not return an error on the Strapi User I/F

The MongoDB Atlas displays the "imported" Non-Repeatable Component Field as follows:
``` 
patch: Object
  small: "https://images2.imgbox.com/9a/96/nLppz9HW_o.png"
  large: "https://images2.imgbox.com/d2/3b/bQaWiil0_o.png"
```
I then manually entered values for the blank Component Field for one of my Collection records. 

- The Strapi User Interface and GraphQL both showed the Component Field as one would expect to see the data.
- The MongoDB Atlas displayed the Component Field as an Array Object that was entirely unlike the imported data views.

```
patch: Array
  0: Object
     _id: 5f82751801d8d4410b656b36
     kind: "ComponentLinksPatch"
     ref: 5f82751801d8d4410b656b35
```
**QUESTION**:  Why is the "ComponentLinksPatch" not returning "small" and "large" attributes in standard JSON format as a Non-Repeatable Object?

Below are the configurations Strapi created for the Component Field.

/models/launch.settings.json
```
    "patch": {
      "type": "component",
      "repeatable": false,
      "component": "links.patch"
    }
```
/components/patch.json
```
{
  "collectionName": "components_links_patches",
  "info": {
    "name": "patch",
    "icon": "rocket"
  },
  "options": {},
  "attributes": {
    "small": {
      "type": "string"
    },
    "large": {
      "type": "string"
    }
  }
}
```

**Steps to reproduce the behavior**

1. Import JSON data with a Component Field
2. Create a Component Field in Strapi User I/F
3. Test to see if imported values for Component Field are returned or null.
4. Manually enter values for the Component Field. View the database to see how these values are stored.

**Expected behavior**
I expected to see all the imported Component Field values returned and visible.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v12.14.1
- NPM version: 6.14.5
- Strapi version: 3.2.3
- Database: MongoDB Atlas
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment]
This likely relates to the structure how we store component data. If possible can you provide a sample export in the same structure you are using?

**Comment by onsombal** [comment]
@derrickmehaffy,

I attached a .txt file that you will need to change to a .json file -- i.e. change to "flights.json".

I then used the following MongoDB Atlas command to import this .json file:
`mongoimport --uri mongodb+srv://<username>:<password>@clusterNAME.mongodb.net/flightsDB--collection flights --type json --jsonArray --file  ~/Downloads/flights.json`

`collection flights` in the command above is the Strapi Collection Name that I created with matching field names. The remaining variables in the command above align with the Strapi database.js as shown below. 
```
settings: {
        host: env('DATABASE_HOST', 'clusterNAME.mongodb.net'),
        srv: env.bool('DATABASE_SRV', true),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'flightsDB'),
        username: env('DATABASE_USERNAME', '<username>'),
        password: env('DATABASE_PASSWORD', '<password>'),
      },
```
The issue I'm encountering is my nested JSON field, named "patch" imports null values for its two text fields; _not what I was anticipating_. If I enter the field values for this component field inside the Strapi UI, Strapi stores those fields in MongoDB Atlas as shown below. AND, when entered via the Strapi UI, the component field values are retrievable in both the Strapi UI and GraphQL. I'm at a loss how to decipher this object for importing into MongoDB Atlas without understanding the magic used by Strapi to create the Array Object below:
```
patch: Array
  0: Object
     _id: 5f82751801d8d4410b656b36
     kind: "ComponentLinksPatch"
     ref: 5f82751801d8d4410b656b35
```
[flights.txt](https://github.com/strapi/strapi/files/5375053/flights.txt)

**Comment by derrickmehaffy** [comment]
> It would be great if Strapi could simply handle "nested" json imports into the database. I'm assuming I won't be the only one wishing to import a large nested database to be used by Strapi.

There have been previous discussions about this, I will poke @strapi/maintainers about this topic but the short and sweet of it is simply that Strapi largely bases it's database model around relational databases, while MongoDB is not a relational DB, it's more or less being treated as such. Swapping to a more nested MongoDB structure will require an enormous amount of effort to keep Strapi agnostic, AFAIK we aren't planning to do so *yet*.

---

As I'm not super familiar with Mongo I'll need to do some exploring and I'll use your test data to see if I can find a solution but you are correct in your assumption that you'll need to make multiple imports unless you develop a custom script that can parse the data and split it properly.

**Comment by onsombal** [comment]
@derrickmehaffy, 

Thank you for your quick replies to my questions as well as helping me to better understand the "why" behind the issue I'm experiencing -- i.e. Strapi's team being more oriented toward SQL than NoSQL. But — _and you likely knew I was going to offer a_ "but" — Strapi is being promoted as a "headless" CMS and API tool. Thus, I would think that ease of programmability would have some degree of precedence over Strapi's GUI frontend, which by the way is excellent.

I think Strapi is amazing, and I'm committed for the long haul. IMHO, the growing influence and adoption of Jamstack and managed cloud databases suggests that Strapi must become the Swiss army knife for supporting both SQL and NoSQL databases.

**Comment by derrickmehaffy** [comment]
I do agree with your points, as you stated we need to be more flexible with regards to noSQL vs SQL RDS.

I think this requires a larger discussion topic opened up on our [Forum](https://forum.strapi.io/c/discussions/6). I sit within the majority in that I myself am more preferential towards a strict schema relational database in my own personal usage of Strapi, but I agree at a company and project level, if we are to be agnostic we do need to take into considerations the other connector.

The reason why it was done the way it is; is very simple, to cut development time and code complexity, if we simply mirrored the same logic from SQL over to noSQL we didn't have to spend the time to develop every feature in two different ways. Going forward we can't do that and maintain proper support. I invite you to open up the discussion and provide your feedback, for this specific issue though I'm going to close this.
