### ISSUE TITLE
Disable eslint indent rule in favor of prettier

### ISSUE THREAD

**Issue by O4epegb** [strapi/strapi#8282]
I just tried to clean up some files, remove `eslint-disable` statements and make them look nice and pretty, but there are several things that tripped me off, one of them is clash between eslint and prettier.

Should we disable eslint "indent" rule in favor of prettier and let prettier decide what to do with indentation?

`eslint/prettier` actually does this automatically but right now there is custom `indent` rule inside `.eslintrc.front.js` which in its turn overrides `eslint/prettier`. 

If that's ok I could make PR.

**Comment by soupette** [comment]
@O4epegb sure you can try to fix it! I would love to see a PR.

**Comment by kefimochi** [comment]
@O4epegb Any updates on this?

**Comment by O4epegb** [comment]
Just made PR.

There was one strange thing, two `extends` fields and only last one was active, I decided to merge them, not sure if that's ok
