### ISSUE TITLE
Outdated info in Quickstart tutorial

### ISSUE THREAD

**Issue by asia-t** [strapi/strapi#8287]
I was setting up a basic strapi app and I came across an issue with the tutorial - basically all videos and blog posts are showing the `Roles and Permissions` link in the left hand side menu. 

I've now found where the options live in the latest version, but having never seen strapi before I spent a few hours troubleshooting my installation before trying to look for the content elsewhere.

Can you add a label to the quick start video here just stating the `Roles and Permissions` now moved elsewhere? Maybe it'd save someone else some time and frustration.
https://www.youtube.com/watch?v=zd0_S_FPzKg&t=2m47s

**Comment by derrickmehaffy** [comment]
Hello, we are currently reaching out to a resource to get a new video made, no ETA currently but it is in the works :wink: 

(Confirmation made by @lauriejim via Slack)

**Comment by JosephMart** [comment]
Where does the option live in the latest version? Currently having the frustration of it not being where the video shows it should be.

**Comment by JosephMart** [comment]
For those in the future it is under `Settings > USERS & PERMISSIONS PLUGIN > Roles`
![image](https://user-images.githubusercontent.com/18429369/96213660-2a2ed280-0f3f-11eb-8997-dfadb62f6084.png)

**Comment by derrickmehaffy** [comment]
Fixed already in the v4 docs :)
