### ISSUE TITLE
GraphQL default resolver can't handle Array of ID properly when using Mongoose connector

### ISSUE THREAD

**Issue by cardmaster** [strapi/strapi#8288]
**Describe the bug**
when query with filter of Array of IDs, the default resolver can't handle properly and result in error in mongoose connector.

**Steps to reproduce the behavior**

the error happens when query with Array as graphql options:

```graphql
query defaultresovler($condition:JSON){
  articles (where:$condition) {
     refspec
  }
}
```

```JSON
{
  "condition": {"category": ["...." ]}
}
```

```JSON
{
  "errors": [
    {
      "message": "Cast to ObjectId failed for value \"{\n  '0': '5f15c89f0e65bd35c202794f',\n  '1': '5f15c8cc0e65bd35c2027950',\n  '2': .....
```

**Expected behavior**
This issue is gone on a customized resolver function, which call service directly.

```javascript
        articleSearch: {
            description: 'Do text search based on Article Databse',
            policies: ['plugins::users-permissions.isAuthenticated'],
            resolverOf: "application::article.article.find",
            resolver: async (obj, options, ctx) => {
                let where = options.where;
                const {sort:_sort, limit:_limit, start:_start} = options;
                const definedValues = (obj)=> {
                    return Object.keys(obj).filter((k)=>obj[k]!==undefined)
                        .reduce((acc, k)=>Object.assign(acc, {[k] : obj[k]} ), {})
                }
                const params = Object.assign({_where:where}, definedValues({_sort, _limit, _start}) )
                return await strapi.api.article.services.article.find(params);
            }
       }
```

**Code snippets**
Bad things happens in this function, packing options into ctx.query will loose the Array type:

```javascript
const buildQueryContext = ({ options, graphqlContext }) => {
  const { context } = graphqlContext;
  const _options = _.cloneDeep(options);

  const ctx = cloneKoaContext(context);

  // Note: we've to used the Object.defineProperties to reset the prototype. It seems that the cloning the context
  // cause a lost of the Object prototype.
  const opts = amountLimiting(_options);

  ctx.query = {
    ...convertToParams(_.omit(opts, 'where')),
    ...convertToQuery(opts.where),
  };

  ctx.params = convertToParams(opts);

  return { ctx, opts };
};
```
from debug console:
```
Array.isArray(ctx.query.category)
false
Array.isArray(_options.where.category) 
true
ctx.query.category 
{0: '5f15c89f0e65bd35c202794f', 1: '5f15c8cc0e65bd35c2027950',
_options.where.category
(475) ['5f15c89f0e65bd35c202794f', '5f15c8cc0e65bd35c2027950',
```

Then mongoose connector utility will failed to covert that Object typed value into BSON ids, as Array.isArray will return false.
Code of graphql default resolver, file strapi-plugin-graphql/services/resolvers-builder.js

file strapi-connector-mongoose/lib/utils/index.js
```javascript
  const valueToId = value => {
    if (Array.isArray(value)) return value.map(valueToId);

    if (isMongoId(value)) {
      return mongoose.Types.ObjectId(value);
    }

    return value;
  };
```

it use buildQueryContext before calling api controller.find
action, by default is 'application::article.article.find' now
```javascript
  return async (root, options = {}, graphqlContext) => {
    const { ctx } = buildQueryContext({ options, graphqlContext });

    // duplicate context
    await policiesMiddleware(ctx);

    const values = await action(ctx);
    const result = ctx.body || values;

    if (_.isError(result)) {
      throw result;
    }

    return result;
  };
```

The graphql default resolver will pack gql query options into ctx[request][query] before using api controller.
in the setter of ctx['request']['query'] the input Array option will become an object with keys 0,1 ... n

//koa/lib/request.js
```javascript
  set query(obj) {
    this.querystring = qs.stringify(obj);
  },

```

** System Information **
 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Mon Oct 12 2020 15:01:58 GMT+0800 (China Standa… │
│ Launched in        │ 5289 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 14456                                            │
│ Version            │ 3.1.4 (node v12.17.0)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

**Comment by derrickmehaffy** [comment]
`"condition": {"category": ["...." ]}`

Can you please try `"condition": {"category_in": ["...." ]}`

**Comment by derrickmehaffy** [comment]
Tested using the _in filter with no issues:

![image](https://user-images.githubusercontent.com/8593673/97225192-8f7c9200-178f-11eb-9b7d-f7d971a1bb24.png)

If you are intending to use the complex `AND` query then yes that does have an issue: 
![image](https://user-images.githubusercontent.com/8593673/97226313-08301e00-1791-11eb-9891-6196bb0d2ed4.png)

**Comment by derrickmehaffy** [comment]
Can you please specify your intent with the query so I can better understand if your bug report relates to the former or the latter.

**Comment by cardmaster** [comment]
sorry for late reply.
I want to query with category filter for more then 20 input parameters.
the reproduce condition is give more then **20** input into both '<connection>_in' filter or '<connection>' filter, and use **Mongoose** connector.

My findings are:
If filter value is an array, mongoose connector could parse into correct query condition.
But array value will be converted into number index object during converting into query object.
Like this:
```
//expected filter value, (Array) in my custom resolver.
_options.where.category
(475) ['5f15c89f0e65bd35c202794f', '5f15c8cc0e65bd35c2027950',

//filter value in default resolver, will have error for more then 20 input IDs.
ctx.query.category 
{0: '5f15c89f0e65bd35c202794f', 1: '5f15c8cc0e65bd35c2027950',

```

and some code I pasted before inside mogoose connector:

in file strapi-connector-mongoose/lib/utils/index.js
```javascript
  const valueToId = value => {
    if (Array.isArray(value)) return value.map(valueToId);

    if (isMongoId(value)) {
      return mongoose.Types.ObjectId(value);
    }

    return value;
  };
```

**Comment by cardmaster** [comment]
Update, ** Can not reproduce now **
I remove all my custom schema, and can not reproduce that error.


```javascript
const _ = require("lodash");

const convertToParams = params => {
    return Object.keys(params).reduce((acc, current) => {
        const key = current === 'id' ? 'id' : `_${current}`;
        acc[key] = params[current];
        return acc;
    }, {});
};
  
const convertToQuery = params => {
    const result = {};

    _.forEach(params, (value, key) => {
        if (_.isPlainObject(value)) {
            const flatObject = convertToQuery(value);
            _.forEach(flatObject, (_value, _key) => {
                result[`${key}.${_key}`] = _value;
            });
        } else {
            result[key] = value;
        }
    });
    return result;
};
resolver: {
 articles: {
            resolverOf: "application::article.article.find",
            resolver: async(obj, options, ctx) => {
                let query = {
                    ...convertToParams(_.omit(options, 'where')),
                    ...convertToQuery(options.where),
                }
                return await strapi.api.article.services.article.find(query);
            }
        },
}
```

**Comment by derrickmehaffy** [comment]
@cardmaster for the _in the default limit should be 100, and you can adjust this under the parser middleware: 

https://strapi.io/documentation/v3.x/concepts/middlewares.html#request-middlewares

What your looking for I believe should be `queryStringParser.arrayLimit: 250` (using 250 as an example)
