### ISSUE TITLE
[WEBSITE] Links to docs in pricing not working

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#8291]
**Describe the bug**
When trying to get more information about RBAC from pricing page, the link is `https://strapi.io/https://strapi.io/`

**Steps to reproduce the behavior**

1. Go to 'https://strapi.io/pricing'
2. Hover `i` next to RBAC
3. Click on the link
4. See error ("an unxpected error occured")

**Expected behavior**
It should point to the appropriate section of the doc 

**Screenshots**
![image](https://user-images.githubusercontent.com/21955112/95726020-acd23c00-0c78-11eb-873f-43e40be57a7c.png)

**Code snippets**
N/A

**System**
N/A

**Additional context**
N/A

**Comment by derrickmehaffy** [comment]
I believe this issue has been fixed, marking as closed. Thank you @8byr0 for letting us know!
