### ISSUE TITLE
Can't access to users & permissions settings

### ISSUE THREAD

**Issue by Fred-ihu** [strapi/strapi#8295]
Hi, i just finish my school and i try to make some fake project, this one is a blog with nextjs + strapi

ps: Sorry for my spelling mistakes, i'm not english

**Describe the bug**
After deploy my back-end on Heroku, i can't access to my public role on Users & Permissions plugin (need to access it because my request get a 403 status)

**Steps to reproduce the behavior**

1. Go to the admin panel 
2. Click on Settings / Roles (users & permissions plugin tab) / Public to edit and accept find, findOne etc..
3. Get a blank page and this error in console : Error: Minified React error #130;

**Expected behavior**
I expect to be able to access to permissions edition

**Screenshots**
![image](https://user-images.githubusercontent.com/62298131/95743258-c469ee80-0c91-11eb-86ce-38088e9f2cb2.png)

edit: i got this in build log of Heroku, may be its a part of my problem
![image](https://user-images.githubusercontent.com/62298131/95759218-b45e0900-0ca9-11eb-928d-9edb28961a95.png)

**Code snippets**
I've changed the database.js file, because heroku deploy couldnt work with the commented code. Don't know if there is a connection
```
module.exports = ({ env }) => ({
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "host": env('DATABASE_HOST'),
        "port": env('DATABASE_PORT'),
        "database": env('DATABASE_NAME'),
        "username": env('DATABASE_USERNAME'),
        "password": env('DATABASE_PASSWORD'),
        "ssl": { "rejectUnauthorized": false }
      },
      "options": {
        "debug": true
      }
    }
  }
});

// module.exports = ({ env }) => ({
//   "defaultConnection": "default",
//   "connections": {
//     "default": {
//       "connector": "bookshelf",
//       "settings": {
//         "client": "postgres",
//         "host": "${process.env.DATABASE_HOST}",
//         "port": "${process.env.DATABASE_PORT}",
//         "database": "${process.env.DATABASE_NAME}",
//         "username": "${process.env.DATABASE_USERNAME}",
//         "password": "${process.env.DATABASE_PASSWORD}",
//         "ssl": { "rejectUnauthorized": false }
//       },
//       "options": {
//         "debug": true
//       }
//     }
//   }
// });
```

**System**

- Node.js version: 10.16.0 at start, but actually with version 12.19.0
- NPM version: 6.14.8
- Strapi version: 3.1.6
- Database: PG
- Operating system: Ubuntu 20.04

**Additional infos**

I've seen this issue : https://github.com/strapi/strapi/issues/6528 but couldn't fix my problem, don't know if i'm doing something wrong..

Thanks !

**Comment by derrickmehaffy** [comment]
Please try updating your application to v3.2.3.

I'm currently unable to reproduce the issue.

**Comment by TasTing** [comment]
There is a template nextjs + strapi shared on strapi's repo

https://github.com/strapi/strapi-starter-next-blog

To deploy backend on heroku. you will need to create a environment folder and add database config in production environment.
In your case, it is pg database. 

```
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        host: env("DATABASE_HOST", "localhost"),
        port: env.int("DATABASE_PORT", 5432),
        database: env("DATABASE_NAME", "strapi"),
        username: env("DATABASE_USERNAME", "strapi"),
        password: env("DATABASE_PASSWORD", "strapi"),
        schema: "public",
        ssl: { rejectUnauthorized: false }
      },
      options: {}
    }
  }
});
```

Remember to add config variables on heroku.

On template nextjs frontend. you will need to add an API adress of your backend to config variables

**Comment by Fred-ihu** [comment]
Hi, i've done a new install of Strapi, to get v3.2.3, its working :+1: 
Thanks !

**Comment by derrickmehaffy** [comment]
Thank you for the confirmation @Fred-ihu going to mark as closed then :)

**Comment by DonikaV** [comment]
3.2.5 and same error... :(

**Comment by derrickmehaffy** [comment]
> 3.2.5 and same error... :(

Just as a follow up since @DonikaV has posted an issue for it. We moved the U&P interface into the settings menu on the left side.
