### ISSUE TITLE
error when add collections in mongodb when use content-type-builder

### ISSUE THREAD

**Issue by pooooriya** [strapi/strapi#8301]
hello !when i want to add new collection to my database in content type builder after saving my collection i got an error and i have to start server manually

[2020-10-12T19:51:21.602Z] debug ⛔️ Server wasn't able to start properly.
[2020-10-12T19:51:21.608Z] error MongoError: indexes of target collection ** changed during processing.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
