### ISSUE TITLE
strapi skips over destroy method for custom user controller

### ISSUE THREAD

**Issue by VEDA95** [strapi/strapi#8303]
**Describe the bug**
I'm trying to create a custom controller for users under the user-permissions plugin in order handle stripe customer integration. The custom create and update methods I have written for the controller seem to work as intended. However, the custom destroy method doesn't seem to work. I even tried including a call to both `console.log` and `strapi.log.debug` but nothing happens, it's like strapi skips over the method entirely when deleting users. I can further confirm this as the strapi user will get deleted, but the stripe customer account still shows up if I log into the stripe dashboard. I'm not really sure what it is that i'm doing wrong as this code should work from what i've seen reading through the documentation so far.

**Steps to reproduce the behavior**

1. Create custom controller in `<project_dir>/extensions/user-permissions/controllers/User.js`
2. Write cusom controller methods that includes custom integrations for stripe
3. Create user in admin panel to test.
4. Delete user in admin panel to test.

**Expected behavior**
Both the strapi user account and the corresponding stripe customer should be deleted.

**Code snippets**
```
'use strict';

/**
 * A set of functions called "actions" for `user`
 */

const _ = require('lodash'),
      { sanitizeEntity } = require('strapi-utils'),
      stripe = require('stripe')('<SK_HERE>'),
      sanitizeUser = (user) => sanitizeEntity(user, {model: strapi.query('user', 'users-permissions').model}),
      formatError = (error) => [{ messages: [{ id: error.id, message: error.message, field: error.field }] }];

module.exports = {
  async create(ctx) {
    const advanced = await strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
      key: 'advanced'
    }).get();

    const { email, username, firstName, lastName, password, role } = ctx.request.body;

    if (!email) return ctx.badRequest('missing.email');
    if (!username) return ctx.badRequest('missing.username');
    if (!password) return ctx.badRequest('missing.password');
    if (!firstName) return ctx.badRequest('missing.firstName');
    if (!lastName) return ctx.badRequest('missing.lastName');

    const userWithSameUsername = await strapi
      .query('user', 'users-permissions')
      .findOne({ username });

    if (userWithSameUsername) {
      return ctx.badRequest(
        null,
        formatError({
          id: 'Auth.form.error.username.taken',
          message: 'Username already taken.',
          field: ['username'],
        })
      );
    }

    if (advanced.unique_email) {
      const userWithSameEmail = await strapi
        .query('user', 'users-permissions')
        .findOne({ email: email.toLowerCase() });

      if (userWithSameEmail) {
        return ctx.badRequest(
          null,

          formatError({
            id: 'Auth.form.error.email.taken',
            message: 'Email already taken.',
            field: ['email'],
          })
        );
      }
    }

    const user = {
      ...ctx.request.body,
      provider: 'local',
    };

    user.email = user.email.toLowerCase();

    if (!role) {
      const defaultRole = await strapi
        .query('role', 'users-permissions')
        .findOne({ type: advanced.default_role }, []);

      user.role = defaultRole.id;

    }

    try {
      const customer = await stripe.customers.create({name: `${firstName} ${lastName}`, email: email});

      user.stripeId = customer.id;
      
      const data = await strapi.plugins['users-permissions'].services.user.add(user);

      ctx.created(sanitizeUser(data));

    } catch (error) {
      ctx.badRequest(null, formatError(error));

    }

  },
  async update(ctx) {
    const advancedConfigs = await strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
      key: 'advanced',
    }).get();

    const { id } = ctx.params;
    const { email, username, password, firstName, lastName} = ctx.request.body;

    const user = await strapi.plugins['users-permissions'].services.user.fetch({id});

    if (_.has(ctx.request.body, 'email') && !email) {
      return ctx.badRequest('email.notNull');
    }

    if (_.has(ctx.request.body, 'username') && !username) {
      return ctx.badRequest('username.notNull');
    }

    if (_.has(ctx.request.body, 'firstName') && !firstName) {
      return ctx.badRequest('firstName.notNull');
    }

    if (_.has(ctx.request.body, 'lastName') && !lastName) {
      return ctx.badRequest('lastName.notNull');
    }

    if (_.has(ctx.request.body, 'password') && !password && user.provider === 'local') {
      return ctx.badRequest('password.notNull');
    }

    if (_.has(ctx.request.body, 'username')) {
      const userWithSameUsername = await strapi
        .query('user', 'users-permissions')
        .findOne({ username });

      if (userWithSameUsername && userWithSameUsername.id != id) {
        return ctx.badRequest(
          null,
          formatError({
            id: 'Auth.form.error.username.taken',
            message: 'username.alreadyTaken.',
            field: ['username'],
          })
        );
      }
    }

    if (_.has(ctx.request.body, 'email') && advancedConfigs.unique_email) {
      const userWithSameEmail = await strapi
        .query('user', 'users-permissions')
        .findOne({ email: email.toLowerCase() });

      if (userWithSameEmail && userWithSameEmail.id != id) {
        return ctx.badRequest(
          null,
          formatError({
            id: 'Auth.form.error.email.taken',
            message: 'Email already taken',
            field: ['email'],
          })
        );
      }
      ctx.request.body.email = ctx.request.body.email.toLowerCase();
    }

    let updateData = {
      ...ctx.request.body,
    };

    if (_.has(ctx.request.body, 'password') && password === user.password) {
      delete updateData.password;
    }

    if(email != null || firstName != null || lastName != null) {
      let stripeUpdate = {};

      if(email != null && (email !== user.email)) stripeUpdate = {...stripeUpdate, email: email};
      if((firstName != null && (firstName !== user.firstName)) || (lastName != null && (lastName !== user.lastName))) stripeUpdate = {
        ...stripeUpdate,
        name: `${firstName != null && (firstName !== user.firstName) ? firstName : user.firstName} ${lastName != null && (lastName !== user.lastName) ? lastName : user.lastName}`
      };

      if(Object.keys(stripeUpdate).length > 0) {
        const customerUpdate = await stripe.customers.update(user.stripeId, stripeUpdate);

      }

    }

    const data = await strapi.plugins['users-permissions'].services.user.edit({ id }, updateData);

    ctx.send(sanitizeUser(data));
  },
  async destroy(ctx) {
    console.log('test...');
    strapi.log.debug('test...');

    const { id } = ctx.params,
          user = await strapi.plugins['users-permissions'].services.user.fetch({id}),
          customerDelete = await stripe.customers.del(user.stripeId),
          data = await strapi.plugins['users-permissions'].services.user.remove({id});

    ctx.send(sanitizeUser(data));

  }
};
```

**Screenshots**
This was a screenshot I was able to take of the log output strapi provides in the terminal.

![Screenshot from 2020-10-12 22-05-31](https://user-images.githubusercontent.com/16213182/95807154-737ce900-0cd7-11eb-9935-9917709dfb10.png)

**System**

- Node.js version: 10.19.0
- NPM version: 6.14.4
- Strapi version: 3.2.0
- Database: postgres
- Operating system: pop-OS (20.04 LTS)

**Comment by MattieBelt** [comment]
Hey @VEDA95,

You have overwritten the controller that handles the REST API/graphQL request from end-users. The content-manager plugin has it's own API to handle CRUD, if I'm not mistaken. Using [Lifecylce Hooks](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks) on the user model is probably a better solution. This way you also don't need to check any modification to the `controller.js` on every update. You can add Lifecycle Hooks in the `./extensions/user-permissions/models/User.js` file. Hopefully this works for you.

**Comment by VEDA95** [comment]
@MattieBelt except that still doesn't make any sense. In my testing my custom create and update methods for the user controller still get called when using the content-manager. I've been able to confirm this by looking at the custome list in stripe's dashboard.

Here's some screenshots showing what I mean

![image](https://user-images.githubusercontent.com/16213182/95837215-5adbf580-0d0e-11eb-840a-db4cf2857511.png)
![image](https://user-images.githubusercontent.com/16213182/95837548-b7d7ab80-0d0e-11eb-9a2d-b1131f10963f.png)

**Comment by MattieBelt** [comment]
Okay, i'm not so sure about that first part then :grin:, but I'll still recommend you to move the code to lifecycle hooks just so you don't need to check for any modification in the `controller.js` and it works for the admin panel as well as for the end-users.

Maybe I found something, how did you delete the user? From the list view, by checking the check-boxes, or from the edit view?
The 'batch-delete' uses an different endpoint and a different controller probably:
`Request URL: http://localhost:1337/content-manager/explorer/deleteAll/plugins::users-permissions.user?0=1`

**Comment by VEDA95** [comment]
I tried deleting using both methods (the list and edit views) and got the same result actually. 

Also i'll give moving my code to lifecycle hooks a shot. With that being I would still like to try and understand how to get this working with the content-manager. The client i'm working on this project for might have situations where she might have work with user accounts manually (Add, update, delete, all that jazz) for customers that call in.

**Comment by MattieBelt** [comment]
Lifecycle hooks work for both for Admin panel as for the REST API. Did you manage to make it work in the lifecycle hooks?

**Comment by derrickmehaffy** [comment]
I have been able to reproduce the issue with lifecycles.

Creating the following file: 

**Path**: `extensions/users-permissions/User.js`

```js
module.exports = {
  /**
   * Triggered before user creation.
   */
  lifecycles: {
    async beforeDelete(params) {
      console.log('BEFORE DELETE');
      console.log(params);
    },
    async afterDelete(result, params) {
      console.log('AFTER DELETE');
      console.log(result);
      console.log(params);
    }
  },
};
```

Creating and deleting a user via the Admin panel doesn't fire the standard lifecycle callbacks for the query `strapi.query('user', 'users-permissions').delete()` 

![image](https://user-images.githubusercontent.com/8593673/95909429-55ed6500-0d53-11eb-87ea-5ca84ea02fb9.png)

**Comment by Stun3R** [comment]
@derrickmehaffy The lifecycles should be in **Path**: `extensions/users-permissions/models/User.js`
instead of **Path**: `extensions/users-permissions/User.js`

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/11828
