### ISSUE TITLE
No loading indicators

### ISSUE THREAD

**Issue by iksent** [strapi/strapi#8307]
**Describe the bug**
There are not loading indicators while:

1. Adding new role
2. Deleting existing role

And I can't understand, is something hapenning or just an error occurred.

**Steps to reproduce the behavior**

1. Go to 'Roles & Permissions'
2. Try to add new role
![2020-10-13_13-10-50](https://user-images.githubusercontent.com/32956521/95834107-f775b600-0d55-11eb-96f3-acedcdf80ff2.png)
3. Or try to remove existing role
![2020-10-13_13-11-11](https://user-images.githubusercontent.com/32956521/95834111-f9d81000-0d55-11eb-9223-d4aab9141cdf.png)

**Expected behavior**
Any loading spinners should be displayed while action is hapenning and the action-button should be disabled (since you will get an error when you click on it again):
```
...
debug POST /users-permissions/roles (1520 ms) 400
error Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: users-perm
issions_role.type
    at Client_SQLite3._query
...
```

**System**

- Node.js version: v12.14.0
- NPM version: 6.14.7
- Strapi version: 3.2.3
- Database: Local
- Operating system: Windows

**Comment by MattieBelt** [comment]
Hey @iksent, 

Can you check your version again? The screenshots appear to not be from `v3.2.3` as the user-permissions plugin tab has been moved to the settings tab.

**Comment by iksent** [comment]
Hello, @MattieBelt!

Sorry, forgot to run `yarn build` after upgrade. Works perfectly now, just as expected, thanks a lot!
