### ISSUE TITLE
Image size validation

### ISSUE THREAD

**Issue by VivekanandanS** [strapi/strapi#8310]
I need to validate image dimension per collection before saving the data,
I tried using the lifecycle hook before insert, but strapi-plugin-upload does not export the service layer.

Any way to validate image dimension per collection before save operation 

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.2.1
- Database: mongo
- Operating system: MAC

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Sumit-Chakole** [comment]
If anyone is still looking for a solution to this, we’ve built a Strapi plugin specifically for this use case.

It validates image dimensions during upload and rejects the image if it doesn’t match the expected dimensions.

You can check it out here: https://community.strapi.io/marketplace/image-dimension-validation
