### ISSUE TITLE
Your filters contain a field '_publicationState' that doesn't appear on your model definition nor it's relations

### ISSUE THREAD

**Issue by hidayat3676** [strapi/strapi#8313]
Hi,

I'm getting error on GET APi's when I deployed  project on aws on local everything works fine 

All GET Routes give me below error
for sample call like 
[http://host:1337/products](http://host:1337/products)
I have not used anywhere "_publicationState" in my query nor does I add any field with name to my models
 
`{"statusCode":400,"error":"Bad Request","message":"Your filters contain a field '_publicationState' that doesn't appear on your model definition nor it's relations"}`

**Node version 12.19.0
npm version 6.14.8
strapi 3.2.2**

Any one who have solution to this please reply.

Thanks

**Comment by alexandrebodin** [comment]
This parameter is used in strapi version 3.2.0+ but you are saying you are on the 3.1.7. This means you are using mismatching version of strapi. can you share your package.json file ?

**Comment by hidayat3676** [comment]
@alexandrebodin Sorry, I am using  3.2.2 I updated my question 

Here my package.json file content

`{
  "name": "nafas",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "mysql": "^2.18.1",
    "sqlite3": "latest",
    "strapi": "^3.2.2",
    "strapi-admin": "3.1.7",
    "strapi-connector-bookshelf": "3.1.7",
    "strapi-plugin-content-manager": "3.1.7",
    "strapi-plugin-content-type-builder": "3.1.7",
    "strapi-plugin-documentation": "^3.1.7",
    "strapi-plugin-email": "3.1.7",
    "strapi-plugin-graphql": "^3.2.3",
    "strapi-plugin-upload": "^3.2.2",
    "strapi-plugin-users-permissions": "3.1.7",
    "strapi-utils": "3.1.7"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "caf7610b-fe8c-43c3-b15c-883e698282f8"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
`

**Comment by alexandrebodin** [comment]
You have juste updated the strapi packge but you need to update all the strapi package ;)

**Comment by hidayat3676** [comment]
@alexandrebodin  What to do I run npm update but the error still exists?

**Comment by alexandrebodin** [comment]
@hidayat3676 You will need to change the version in your package json manually :) You can follow this guide here https://strapi.io/documentation/v3.x/guides/update-version.html

**Comment by hidayat3676** [comment]
@alexandrebodin Thanks, It resolved my issue.
