### ISSUE TITLE
Unable to remove roles

### ISSUE THREAD

**Issue by jud3v** [strapi/strapi#8318]
**Describe the bug**

Hello we are unable to remove roles / making custom roles, because community have 3 roles, yeah but we want too custom roles 😅.

**Steps to reproduce the behavior**

1. Go to Settings ( Paramètre for French guys )
2. Click on roles in administration panel`section
3. Click on `delete icon 🗑` and we will see the modal `need to upgrade to enterprise edition`.
4. But what I want is to remove one roles an making my own needed roles 😁

**Expected behavior**

I expected to delete one roles and making my own roles 😅

**Screenshots**
[![Capture-d-cran-2020-10-13-15-59-45.png](https://i.postimg.cc/mDtdV7YR/Capture-d-cran-2020-10-13-15-59-45.png)](https://postimg.cc/1n1c3n7Y)
**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2.3
- Strapi admin version: 3.2.3
- Strapi utils version: 3.2.3
- Database: mysql
- Database version: mysql  Ver 15.1 Distrib 10.5.5-MariaDB, for osx10.15 (x86_64) using readline 5.1
- Operating system: Mac OS X 10.15.7

**Additional context**

**Comment by derrickmehaffy** [comment]
Within the Admin panel roles you cannot add or delete these as it requires an EE license, the CE license doesn't allow new roles, or to delete the existing.

You can find our pricing here: https://strapi.io/pricing

For now I'm going to mark this as closed, as what you see is intended, but please do feel free to provide feedback.

**Comment by sam-pires** [comment]
Hello @jud3v 
As @derrickmehaffy said the feature has been built this way.

Can you tell us more about what limits you in the pre-defined roles and which role you want to create and why?
That would be awesome 🙏

**Comment by derrickmehaffy** [comment]
Please see this thread and give us some feedback: https://forum.strapi.io/t/rbac-role-based-access-control-feature-discussion/433
