### ISSUE TITLE
Plugin file isn't overloaded 

### ISSUE THREAD

**Issue by VivekanandanS** [strapi/strapi#8325]
**Describe the bug**
I'm trying to override the **_strapi-plugin-upload_** : index.js file 

**Steps to reproduce the behavior**

1. Created a dir under extensions folder with plugin id as _upload_
2. Added index.js
```
const { errors } = require('./errors');
const { fetch } = require('./services/Upload');

module.exports = {
  errors,
  fetch
};

```
**Expected behavior**
In model life cycle hooks, I'm trying to use fetch function exported via index.js
But is still undefined 

**Screenshots**
![Screenshot 2020-10-14 at 11 12 36 AM](https://user-images.githubusercontent.com/15701695/95948542-5a2a8880-0e0e-11eb-9780-2930cddbf57c.png)

**Code snippets**
extensions/upload/index.js

```
const { errors } = require('./errors');
const { fetch } = require('./services/Upload');

module.exports = {
  errors,
  fetch
};
```

api/sample/models/sample.js

```
const upload = require('strapi-plugin-upload')
module.exports = {
    beforeCreate: async model => {
        // fetch is undefined
        var image = await upload.fetch({ _id: model['imageUrl'] });
    }
}
```

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.2.1
- Database: Mongo
- Operating system: MAC OS X

**Comment by alexandrebodin** [comment]
Hi, extensions do not work this way :) You can only overwrite the services / controllers and config from a plugin and access it via strapi.plugins[pluginName] not by requiring it. In your case you can overwrite the upload service and add a method of your choice and it can be accessed via strapi.plugins.upload.services.upload.yourMethod.

Going to close this issue as it matches what is documented :) Let me know if you could make it work
