### ISSUE TITLE
Add json database support

### ISSUE THREAD

**Issue by distributev** [strapi/strapi#8326]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Add low.db database support in addition to the existing databases which are supported. 

https://github.com/typicode/lowdb
https://github.com/typicode/json-server

The benefit would be that, for users which will need this, the database will be stored in a plain json file like a db.json which means it will be easy to add to source control the data also in addition with the app code and the app configurations. Adding to source control data stored in a classical database like MySQL is more difficult. 

I believe this is also in the spirit of the "headless" and "lighter" CMS which strapi is trying to be (vs. classical database / MySQL driven CMS software packages like WordPress).

**Comment by Delfshkrimm** [comment]
+1! Would really appreciate it :) for fast prototyping or really light apps, in conjunction with docker volumes this is a great feature imo!

**Comment by ampirzadeh** [comment]
+1
Need this feature and was looking for it when I found this issue

**Comment by derrickmehaffy** [comment]
We currently do not plan to add native support for this at this time as JSON database is not supported by Knex.js.

Marking as closed as discussed with @Aurelsicoko
