### ISSUE TITLE
Extensions : Methods are not included in strapi.plugins

### ISSUE THREAD

**Issue by VivekanandanS** [strapi/strapi#8338]
**Describe the bug**
I'm trying to add a function under strapi-plugin-upload but it's not getting exported 
Followed the steps here , https://strapi.io/documentation/v3.x/concepts/customization.html#plugin-extensions

**Steps to reproduce the behavior**

1. Create a folder after plugin id under extension, in my case I have created dir name `upload`
2. Added a file with few functions

**Expected behavior**
1. Functions are expected to be present under strapi. plugins, but its empty object 

**Screenshots**
![Screenshot 2020-10-15 at 12 08 08 PM](https://user-images.githubusercontent.com/15701695/96085925-253a3680-0edf-11eb-94b5-2dde50e7d00b.png)

**Code snippets**
```
console.log(global.strapi.plugins)
```

**Output**
{}

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.2.1
- Database: Mongo
- Operating system: OS X

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/customization-of-strapi-upload-plugin-logic/472/3

**Comment by MattieBelt** [comment]
Hey @VivekanandanS,

It should be avaible with: 
```js
strapi.plugins['upload'].services.hello
```

Steps to reproduce:
1. Create an fresh project `yarn create strapi-app test-8338 --quickstart`
2. Create `./extensions/upload/services/hello.js`:
```js
module.exports = {
  sayHi() {
    strapi.log.debug('hi');      // console.log('hi');
  },
};
```
3. `Use strapi.plugins['upload'].services.hello.sayHi();`
4. ![image](https://user-images.githubusercontent.com/31662805/96089669-7a6a4e00-0ec7-11eb-9e16-72e0300393e2.png)

**Comment by MattieBelt** [comment]
A handy tool to use is [the strapi console](https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-console): `yarn strapi console`. 
It helps a lot with checking the structure (services & controllers) of the `strapi` object. 
For example I used it to executed the function (see image from step 4).

**Comment by VivekanandanS** [comment]
Thanks @MattieBelt
