### ISSUE TITLE
Mongoose query leads to undefined `uid` error in dynamic zones

### ISSUE THREAD

**Issue by iapain** [strapi/strapi#8342]
**Mongoose query leads to undefined `uid` error in dynamic zones**
When using mongoose query on model, strapi expects to include all dynamic zones fields. However, during query it should be possible to select few fields (which is leverages by mongoose ORM). I found problem in [mount-model](https://github.com/strapi/strapi/blob/master/packages/strapi-connector-mongoose/lib/mount-models.js#L244)

**Steps to reproduce the behavior**

1. Create a strapi model with one of the field as dynamic zone.
2. Use mongoose query like `strapi.query(model).model.find({}, ['-dynamiczonefield'])` by excluding dynamic zone field.
3. Error
```
 error TypeError: Cannot read property 'uid' of undefined
    at /home/.../coss_prototype/node_modules/strapi-connector-mongoose/lib/mount-models.js:230:64
    at Array.map (<anonymous>)
```

**Expected behavior**
It should omit dynamic zone fields if it's not included in query just like relations.

**System**

- Node.js version:  v12.18.0
- NPM version: v6.14.4
- Strapi version: v3.1.3
- Database: MongoDB 4.2.x
- Operating system: MacOS 10.15.8

**Comment by iapain** [comment]
@alexandrebodin If it's valid. I can send a PR.

**Comment by alexandrebodin** [comment]
Hi @iapain Looks like we can fix it by ignoring the passed param if we don't know what to do with it instead of throwing an error yes. If you are up for it a PR would be nice :)
