### ISSUE TITLE
beforeUpdate data is not reflected after saving in admin form

### ISSUE THREAD

**Issue by u007** [strapi/strapi#8346]
**Describe the bug**

ive added beforeUpdate hook , and console log to ensure the call is being called and it works!
but the form did not reflect after its been saved. But refresh the form does show the updated value...

**Steps to reproduce the behavior**

1. edit a data and save
2. form revealed with old field data
3. refresh
4. form shows correct updated data

**Expected behavior**

expect the form to reveal correct data after save

```
const onSaveOrder = async function (id, data) {
  console.info('!!!!!!!order b4save', id, data);
  // let sales_total = 0.0;
  data.order_id = makeid(10);
}

module.exports = {
  lifecycles: {
    async beforeUpdate(id, data) {
      return onSaveOrder(id, data);
    },
    async beforeCreate(data) {
      return onSaveOrder({}, data);
    },
  },
};
```
**System**

- Node.js version:  v12.18.4
- NPM version: 6.14.6
- Strapi version: "3.2.3",
- Database: mongoose
- Operating system: wsl ubuntu 20.04

**Comment by derrickmehaffy** [comment]
Hi @u007 `return onSaveOrder(id, data);` in this case you won't want to use a return, simply assigning the values to the data object is enough here (possibly using an await).

For something like this though please post questions about usage to our [Forum](https://forum.strapi.io/), I know in your case this looked like a bug. I'm going to mark this one as closed, but please do feel free to respond. :smiley:

**Comment by u007** [comment]
hi,
ive added await and did not return, and still, its not reflecting in the form until i refresh it

**Comment by u007** [comment]
hi, can reopen this ticket? it seems not solved

**Comment by derrickmehaffy** [comment]
@u007 it's not really a "bug" per say, instead can you please post on our [Forum](https://forum.strapi.io/) and we can take a look together there

**Comment by u007** [comment]
alright, posted here https://forum.strapi.io/t/changing-form-value-in-beforeupdate-does-not-reflect-value-in-form-until-refresh/663

thank you

**Comment by derrickmehaffy** [comment]
> alright, posted here https://forum.strapi.io/t/changing-form-value-in-beforeupdate-does-not-reflect-value-in-form-until-refresh/663
> 
> thank you

Thank you, I'll try and get an answer soon, currently working through my notification backlog

**Comment by frosato-dev** [comment]
@derrickmehaffy I'm surprise of this behavior and why this is not considered as a bug.

Let's consider a `person` entity with 3 text attributes 
- `firstname` 
- `lastname`
- `fullname` - I want this one to be read-only since it will be computed from the two previous values in lifecycles hooks.

```
module.exports = {
  lifecycles: {
    async beforeUpdate(event) {
      const { firstname, lastname } = event.params.data
      event.params.data.fullname = `${firstname} ${lastname}`
    },
    async beforeCreate(data) {
      const { firstname, lastname } = event.params.data
      event.params.data.fullname = `${firstname} ${lastname}`
    },
  },
};
```

When I save the "person" creation form in the admin with valid `firstname` and `lastname` values, I expect to have `fullname` input to be filled after the loading finish. 
Reloading the page to reflect the real state of my person entry after hitting the save button sounds "buggy" and like a bad UX.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I'm surprise of this behavior and why this is not considered as a bug.
> 
> Let's consider a `person` entity with 3 text attributes
> 
> * `firstname`
> * `lastname`
> * `fullname` - I want this one to be read-only since it will be computed using the two previous ones in lifecycles hooks.
> 
> ```
> module.exports = {
>   lifecycles: {
>     async beforeUpdate(event) {
>       const { firstname, lastname } = event.params.data
>       event.params.data.fullname = `${firstname} ${lastname}`
>     },
>     async beforeCreate(data) {
>       const { firstname, lastname } = event.params.data
>       event.params.data.fullname = `${firstname} ${lastname}`
>     },
>   },
> };
> ```
> 
> When I save the "person" creation form in the admin with valid `firstname` and `lastname` values, I expect to have `fullname` input to be filled after the loading finish. Reloading the page to reflect the real state of my person entry after hitting the save button sounds "buggy" and like a bad UX.

I agree with you for sure, those lifecycles need a bit of refactoring and we are discussing adding lifecycles elsewhere but at a core level either we make the user refresh or we hold them on a loading page while we wait for the request to finish

Strapi uses React, aka CSR so all communication happens over REST APIs between the admin and the backend. There is no web-socket connection currently. The only way to do this without a refresh is hit save => show user loading screen => wait for response and rerender the page or to use something like sockets.

**Comment by derrickmehaffy** [comment]
So thus it's not really a "bug" but more of a feature or enhancement.
