### ISSUE TITLE
GraphQL login throwing 400 error 

### ISSUE THREAD

**Issue by JamMaster1999** [strapi/strapi#8347]
Hi, do you think you can explain why graphql is giving a 400 error?

I’m following the documentation mentioned here: https://github.com/strapi/strapi/issues/5304

```
mutation login($input: UsersPermissionsLoginInput!) {
  login(input: $input) {
    jwt
    user {
      id
      email
    }
  }
}
```
With my variables being (it’s not UIAdmin account I’m trying to access)

```
{
  "input": {
    "identifier": "sina",
    "password": "1234567890"
  }
}

The error I get is: 400 Bad Request. Internal Server Error. "id": "Auth.form.error.invalid", "message": "Identifier or password invalid."
```
Interestingly enough when I try running the script without graphql variables, everything works fine

```
mutation login {
        login(input: {
          identifier: "sina",
          password: "1234567890"
          }
        ){
          jwt
          user{
            username
          }
        }
}
```

The result from the above code: 
```
"login": {
            "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODc5YWU4NmI0OThmMjVlN2M5NDNkOSIsImlhdCI6MTYwMjc5OTQwNiwiZXhwIjoxNjA1MzkxNDA2fQ.PILsxbi2_8seA4fgBHaCL4qkescaeBTRZxRq-Sa7pgM",
            "user": {
                "username": "sina"
```
I need the variables so I can dynamically pass in user and password from the incoming form. If there's a way around that please let me know. 

**System**

- Node.js version: 12.8
- NPM version: 6.0
- Strapi version: 3.2 Community
- Database: MongoDB
- Operating system: Mac

**Comment by derrickmehaffy** [comment]
Tested on v3.2.5 with both username and email login and works fine:

![image](https://user-images.githubusercontent.com/8593673/97227184-5a257380-1792-11eb-821e-99b1807783be.png)

![image](https://user-images.githubusercontent.com/8593673/97227201-601b5480-1792-11eb-94f1-474874b801c7.png)

Can you please ensure the account you are trying to sign in with is from the `users-permissions` plugin and **not** the admin panel as the users are separate and admin panel users cannot login via GraphQL nor can the JWT provided access REST/GraphQL routes unrelated to the admin panel

**Comment by eric-gardyn** [comment]
getting the same error

**Comment by derrickmehaffy** [comment]
Marking as closed as original author has not provided any reproduction steps. @eric-gardyn if you can provide reproduction steps we can look at reopening this.
