### ISSUE TITLE
Editing dates manually via the text input is difficult in the admin UI

### ISSUE THREAD

**Issue by robclouth** [strapi/strapi#8360]
### Describe the bug

When editing dates in the admin UI via the text input, the date keeps reseting and you end up with malformed years. Setting via the calendar popup works but to select a date that is a long time in the past takes ages, because you can only move one month at a time.

### Steps to reproduce the behavior

1. Edit a date in the admin UI with the text input

### Expected behavior

Setting the date via the text input is possible.

### System

- Node.js version: v12
- Strapi version: 3.1.3
- Database: postgres
- Operating system: MacOS

**Comment by abdonrd** [comment]
Related: https://github.com/strapi/buffet/issues/104

**Comment by soupette** [comment]
We have changed the date picker with the new design system of the v4. Upgrading your app should fix this issue.

**Comment by derrickmehaffy** [comment]
Fixed in v4, closing
