### ISSUE TITLE
[Roles and Permissions Plugin] Store Roles and Permissions configuration in a separate file

### ISSUE THREAD

**Issue by raveesh-me** [strapi/strapi#8368]
## Feature request
Our workflow goes from dev to staging to production and we have to enable the user permissions manually for all the roles.
We would like this configuration to be persisted on a file so we could include these in our Dockerfiles and thus not need to manually edit permissions for all the routes on every deployment.

If there already is one, please help us locate that file.

- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**
- [X] **I have created my request on the Product Board before I submitted this issue**

**Comment by aksdevac** [comment]
You don't have to do it manually 
See this: https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-configuration-dump

**Comment by derrickmehaffy** [comment]
FYI that configuration dump doesn't dump the roles and permissions only the `core_store` table
