### ISSUE TITLE
Lifecycle hook isnt executed in API call

### ISSUE THREAD

**Issue by VivekanandanS** [strapi/strapi#8369]
### Describe the bug

Model's lifecycle hook (beforeCreate,beforeUpdate) is executed only when it's saved from strapi admin panel, but API exposed does not execute the lifecycle hook. But afterfind is executed in API 

### Steps to reproduce the behavior

1. Create a lifecycle hook for a mode, in my case I have `afterFind`,`beforeCreate`,`beforeUpdate`
2. Add few contents from the dashboard, you can see beforeCreate,beforeUpdate  getting executed
3. Expose API as public and add data to the collection via POST call, lets say the collection is flowers  POST:http://localhost:1337/flowers
4. `beforeCreate` and `beforeUpdate` are not executed

### Expected behavior

`beforeCreate` and `beforeUpdate` should be executed when POST:/<collection> is called

### System

Node.js version: v12.16.1
NPM version: 6.13.4
Strapi version: 3.2.1
Database: Mongo
Operating system: OS X

**Comment by derrickmehaffy** [comment]
Can you please provide a link to your project or some means of reproducing the issue?

I've tested a fresh project on v3.2.4 and could not reproduce the issue.
