### ISSUE TITLE
User list on click pagination is broken

### ISSUE THREAD

**Issue by wonknu** [strapi/strapi#837]
Node.js version: nvm with node v9.2.0

npm version: 5.6.0

Strapi version: 3.0.0-alpha.11.1

Operating system: macos

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When i have more than 10 users on the backend, if i click on pagination element like left arrow, 1, 2, 3 ..., right arrow the source is missing in the url which redirect to a blank page

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Click on pagination elements on user list page

**What is the expected behavior?**
the url should contains `&source=content-manager`

**Comment by lauriejim** [comment]
Fixed here https://github.com/strapi/strapi/pull/851/commits/37eedd5747cb383865aaecd50a3aa3092c56175a
