### ISSUE TITLE
 iterate on all Strapi.js enum in Gatsby and Graphql

### ISSUE THREAD

**Issue by robertjohnson22** [strapi/strapi#8370]
I have a field on my Strapi.js admin called category.

![CRS](https://user-images.githubusercontent.com/73020931/96335106-8c571700-10a8-11eb-961f-38816509559b.png)

I tried to research on how to get all the values of category, I did tried this:

`Object.values(category);`

But this did not work instead it threw me a bunch of `Module Errors`.

```
export const query = graphql`
  {
    allStrapiWorks {
      nodes {
        id
        name
        slug
        category
        stack {
          stack_name
          id
        }
        featured_image {
          childImageSharp {
            fluid {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    }
  }
`

```

If I called `works.category` it will just show `undefined `but if I map through the `works `it will show each category per piece not as a collection along with all other fields within an object.

Is there anyway to map or iterate through all of the enums on strapi.js?

Please help!

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
