### ISSUE TITLE
Strapi-plugin-graphql dependency issue after upgrading to ver 3.2.4

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#8374]
### Describe the bug

It seems like graphql-tools version is conflicting with graphql version 15. An upgrade is required. See temporary solution below.

### Steps to reproduce the behavior

1. upgrade from strapi v3.1.6 to v3.2.4
2. See error 
```js
Error: Must provide Source. Received: undefined
    at devAssert (node_modules/graphql/jsutils/devAssert.js:13:11)
    at new Parser (node_modules/graphql/language/parser.js:82:67)
    at Object.parse (node_modules/graphql/language/parser.js:35:16)
    at Object.<anonymous> (node_modules/graphql-tools/dist/stitching/introspectSchema.js:39:42)
```

### System

- Node.js version: v12.18.1
- NPM version: 6.14.5
- Strapi version: 3.2.4
- Database: Postgresql v11
- Operating system: Debian Buster

### Additional context

I ran the following to see resolutions:
`yarn why graphql-tools` 

It seems `strapi-plugin-graphql` uses:
```json
"graphql-tools": "4.0.6"
```

which causes issue as `graphql-tools` tries to use `graphql` v14 syntax that was deprecated.

So I resolved dependencies to latest `graphql` version manually as follows in package.json and it worked:
```json
  "resolutions": {
      "graphql-tools": "^4.0.8"
  },
```

delete node_module dir and reinstall Strapi:
 `rm -fv yarn.lock && rm -rfv node_modules/ && yarn install && rm -rfv build && yarn build && yarn develop`
everything worked fine.

hope this helps someone and is useful for updating `strapi-plugin-graphql`.

**Comment by derrickmehaffy** [comment]
Can you submit a PR to resolve the issue globally? :pray:

**Comment by nicolashmln** [comment]
I still have this error in strapi 3.3.2, even though the PR above has been merged. Anyone else?
Note: lock file and node_modules deleted before updating, and tested with npm 6.14.4 and yarn 1.22.10

**Comment by emahuni** [comment]
@nicolashmln can you try to do the resolutions things in package.json. generally follow what I said. If it works then thePR may not have updated the particular packages that matter. Sorry I'm under the bus to do the PR Derrick.

**Comment by nicolashmln** [comment]
@emahuni found the problem for my project, when I was trying your solution it wasn't working, so I tried to understand why. At the end it was because of `graphql-toolkit` (which is deprecated now). I was using this package for custom code. Somehow it was interfering with strapi. With the newer version of this package and with strapi 3.3.3 everything is working now 🤙 Thank you for your time

**Comment by derrickmehaffy** [comment]
@emahuni can you confirm if you are having a similar problem as @nicolashmln ?

**Comment by emahuni** [comment]
Mine is working after I did what I just wrote up there. I have no issues. I think the thing is that there are some tools that are conflicting with the lower versions. As long as this was updated in Strapi, we should be fine. The only thing that needs to be done is to just delete lock files and update other tools that project may be using since Strapi is now fine.

**Comment by derrickmehaffy** [comment]
Just wanted to check before I closed out this issue. If there is still a problem that needs to be addressed let me know and I can reopen this.
