### ISSUE TITLE
The Admin UI takes 1.6 minutes to load, but REST is so fast

### ISSUE THREAD

**Issue by nauvalazhar** [strapi/strapi#8375]
### Describe the bug

First of all, thank you for making Strapi which makes my job easier.

I have a problem with the Strapi admin UI. It took 1.6 minutes to load, even though it's not the first time it loads. However, REST and GraphQL are fine.

I didn't install any plugins other than the internal ones. I've also done a production build. I've read some similar issues here, but there's no clear solution.

Is something missing? thanks.

### Expected behavior

The page loads in just a few seconds.

### Screenshots

![image](https://user-images.githubusercontent.com/14899175/96351332-d100a380-10e4-11eb-8d8b-7b27de396b16.png)

### System

- Node.js version: v10.16.0
- NPM version:6.9.0
- Strapi version: 3.1.2
- Database: MySQL
- Operating system: Ubuntu 16.04

**Comment by derrickmehaffy** [comment]
Are you on Heroku?

**Comment by nauvalazhar** [comment]
No, I'm using DigitalOcean with 2GB RAM.

**Comment by derrickmehaffy** [comment]
That's quite odd :thinking: I just spun up one of our one-click's and couldn't really see a difference. Do you have a slower internet connection or are a long distance from the region you selected on DO?

**Comment by nauvalazhar** [comment]
My internet connection is fine. I also have a few Node apps, but not this slow. BTW, I am using Nginx and reverse proxy. I also had several other Strapi installations on the same server, and they were all slow too.

**Comment by jozefcipa** [comment]
Not sure if relevant, but I had a similar problem with frontend UI when running on Netlify. Once I switched to Firebase hosting the problem with loading was gone. So maybe you could try to deploy it to a different service?

**Comment by derrickmehaffy** [comment]
I haven't been able to replicate, we will need more information to see if this a Strapi bug or an environment issue.

**Comment by M-erb** [comment]
My team is seeing this as well ever since we updated to from strapi v3.1.4(loading the adminui was completely fine here) to now on v3.2.3(takes about 30s to load which is an eternity to our content managers)

Node.js version: v12.18.4
NPM version: 6.14.6
Strapi version: 3.2.3
Database: MySQL
Operating system: Ubuntu 18.04.5
Reverse Proxy: Nginx 1.14

We are running on our own servers through a local data center. It seems to be hanging on a main.#####.chunk.js file that is transfered at 1.09MB

**Comment by M-erb** [comment]
Found a solution for me! #7439 @albatrocity suggested disabling Brotli compression which was recently added to Strapi.

In ```/config/middleware.js```

FROM:
```javascript
gzip: {
  enabled: true
}
```

TO:
```javascript
gzip: {
  enabled: true,
  options: {
    br: false
  }
}
```

Can read more about it from the linked issue and in the middleware config docs here: https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations

Once this config was pushed to our servers the loading issue went away. Hope this helps someone out there!

**Comment by albatrocity** [comment]
@nauvalazhar this sounds like what I was running into, and what @M-erb posted was the solution for me. A note about this was added to the [Heroku guide](https://strapi.io/documentation/v3.x/deployment/heroku.html#gzip) since that's where I was experiencing it, so it's good to know it's an issue on DO as well. I'll make a PR that updates the Digital Ocean guide if you can confirm that disabling Brotli resolves your issue.

If it's also happening on your own managed servers, I think it's worth discussing if `koa-compress@5` is an appropriate default for the community.

**Comment by derrickmehaffy** [comment]
Indeed it appears Brotli compression appears to be causing some issues.

@alexandrebodin should we disable this by default?

**Comment by nauvalazhar** [comment]
Hi, thanks for the reply. I tried @M-erb solution and I think it solved my problem.

First time:
![image](https://user-images.githubusercontent.com/14899175/96733263-7072ae80-13e3-11eb-8f37-8f50225e0237.png)

Second time:
![image](https://user-images.githubusercontent.com/14899175/96733298-77012600-13e3-11eb-85ce-752e626f45a4.png)

Apart from that I also use the CORS configuration, so, my current configuration is like this:
```
module.exports = {
  //...
  settings: {
    cors: {
      origin: ['http://localhost:3000', 'https://name.tld', 'https://api.name.tld'],
    },
    gzip: {
      enabled: true,
      options: {
        br: false
      }
    }
  },
};
```

Thank you @M-erb and all the Strapi team!

**Comment by derrickmehaffy** [comment]
Dug a little bit and the default for Gzip is defaulted to off:

https://github.com/strapi/strapi/blob/983c61c1440268a618f8e516c0f211f8f29bbe39/packages/strapi/lib/middlewares/gzip/defaults.json#L1-L6

And as we already have a warning on the docs: https://strapi.io/documentation/v3.x/concepts/middlewares.html#response-middlewares

I think we can safely close this for now. Thank you everyone :+1:

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/admin-on-heroku-not-opening-even-after-disabling-brotlin-in-config-middleware-js/4479/1

**Comment by matsinvasion** [comment]
Am the creator of the above issue. still experiencing the problem.

**Comment by yura2100** [comment]
After a brief research, I also found two things that can make things a bit better.

Firstly, you may want to delete all languages except English, see [this](https://strapi.io/documentation/developer-docs/latest/development/admin-customization.html#customization-options). It saved me up to 0.6MB.

Secondly, a custom webpack configuration can split your main chunk into smaller chunks. To do so in your **src** create **admin/admin.config.js** and paste this code. Before I had one 8.5MB chunk after 6.5Mb and 2MB that loads simultaneously
```js
module.exports = {
    webpack: (config, webpack) => {
        config.optimization = {
            splitChunks: {
                chunks: 'all'
            }
        }
        
        return config
    }
}
```

**Comment by matsinvasion** [comment]
What i did was redeploy the app to heroku following different steps from the documentation.

**Comment by chenkang084** [comment]
my solution:
1. build as production environment: `NODE_ENV=production strapi build` 
2. deploy as production environment: `NODE_ENV=production strapi start` 
3. enable gzip and js cache , create middlewares.js in `config/middlewares.js`
```
module.exports = ({ env }) => ({
  settings: {
    gzip: {
      enabled: true,
      options: {
        br: false
      }
    },
    public: {
      maxAge: 1000 * 3600 * 24 * 30, // cache 30days
      path: './public'
    }
  }
})
```
