### ISSUE TITLE
Your filters contain a field '_publicationState' that doesn't appear on your model definition nor it's relations

### ISSUE THREAD

**Issue by rvigneshw** [strapi/strapi#8379]
### Describe the bug

When i try to access the strapi running on my clound run instance "https://grockapi-evzrb22h2q-de.a.run.app/products"
It gives me this error
`{"statusCode":400,"error":"Bad Request","message":"Your filters contain a field '_publicationState' that doesn't appear on your model definition nor it's relations"}`

### Steps to reproduce the behavior

1. deploy strapi on cloud run using cloud build using dockerfile
Dockerfile I'm using

FROM node:12-slim
WORKDIR /usr/src/app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm install --only=production
COPY . ./
RUN npm run build
CMD [ "npm", "start" ]

### Expected behavior

print data as json

### Actual O/P

`{"statusCode":400,"error":"Bad Request","message":"Your filters contain a field '_publicationState' that doesn't appear on your model definition nor it's relations"}`

### System

- Node.js version: 12
- NPM version:6.9
- Strapi version: 3.1.3
- Database:mongodb atlas

### Additional context

I was experimenting with deploying strapi to cloud run which is much more better than app engine.

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.1.3`

The Draft and publish feature was released in v3.2.x, please update your application. I'm going to mark this as closed for now, feel free to reply if you still have issues after updating.

**Comment by holyduke** [comment]
Hello, I am having the same issue, however I do not use Docker. I cloned repository from github and tried to run locally, got the same error 
` "message": "Your filters contain a field '_publicationState' that doesn't appear on your model definition nor it's relations"`

**Comment by derrickmehaffy** [comment]
@holyduke it would probably be better for you to post on our [Forum](https://forum.strapi.io/) and provide as much info as you can.

**Comment by rvigneshw** [comment]
> `Strapi version: 3.1.3`
> 
> The Draft and publish feature was released in v3.2.x, please update your application. I'm going to mark this as closed for now, feel free to reply if you still have issues after updating.

That worked for me, thanks!

**Comment by rvigneshw** [comment]
> pls help me to fix this, I am running strapi 3.2.4

Please check all your strapi dependencies are version 3.2.4

**Comment by holyduke** [comment]
thanks it helped @rvigneshw
