### ISSUE TITLE
Remove dependency on `node-machine-id`

### ISSUE THREAD

**Issue by zurfluh** [strapi/strapi#8389]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

I have not created a request on the Product Board because I think it requires prior discussion.

### Summary

Remove dependency on `node-machine-id` to enable distroless Docker containers.

### Why is it needed?

If we remove the NPM dependency on `node-machine-id` [1] then, on a linux distro, we do not depend on the shell and we can build a distroless Docker container.

[1] `node-machine-id` under the hood uses the shell command `cat` to determine the machine id.

### Suggested solution(s)

Replace node packages that (transitively) depend on `node-machine-id`.

### Related issue(s)/PR(s)

_none_

**Comment by derrickmehaffy** [comment]
This package is required to generate the `UUID` for the Strapi project (package.json) for our telemetry, do you know of a replacement package for docker so we can check the node environment variable for `isDocker` and use a different package instead for docker containers?

**Comment by zurfluh** [comment]
Can you use [uuid](https://www.npmjs.com/package/uuid) to generate a UUID?

**Comment by derrickmehaffy** [comment]
I'll poke @alexandrebodin to confirm

**Comment by derrickmehaffy** [comment]
fixed by: https://github.com/strapi/strapi/pull/12173
