### ISSUE TITLE
400 error on uploading a file (Axios Post)

### ISSUE THREAD

**Issue by tomyoungbloods** [strapi/strapi#8391]
Hi,

I'm having a problem. When I try to make a post request (axios), i've got a 400 error.

```
imageSubmit(){
          console.log(event.target.files[0]);

          axios.post('http://localhost:1337/upload', event.target.files[0])
          .then(response => {
            console.log(response);
          });

        },


```

![Screenshot 2020-10-19 at 20 34 46](https://user-images.githubusercontent.com/55536419/96498081-e5ab7b80-124b-11eb-8d2e-81a415764ed2.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
