### ISSUE TITLE
How can I put the code in the reset password url into my request 

### ISSUE THREAD

**Issue by GabrielLiade** [strapi/strapi#8393]
### Describe the bug
I want to set up a reset password feature. I send an email containing a link with a code in the url. Something like this : 

http://localhost:8000/resetpassword/?code=8d8291822810f46ad2a54a8b7fbc06b586ddf2d5acc1ad65ed8c5875f730d3e4afbcc98816de64cf307004c261a2ab9eb8b8a3354ed448f08a6a8ac712f472cf

But now, according to the documentation, I have to paste the url code into my back request, but I don't know how to add dynamically this url code into the request (maybe is something like this : $(urlCode)) : 

 axios
    .post('https://whentocop-back.herokuapp.com/auth/reset-password', {
      code: 'UrlCode', **_<= I need the url code here_**
      password: 'userNewPassword32',
      passwordConfirmation: 'userNewPassword32',
    })
    .then(response => {
      console.log("Your user's password has been reset.");
    })
    .catch(error => {
      console.log('An error occurred:', error.response);
    });
}

### Steps to reproduce the behavior

Follow the Strapi authentification plugin documentation 

### Expected behavior

No 403 response :)

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2
- Database: pg
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by GabrielLiade** [comment]
ok
