### ISSUE TITLE
Reset Password permission is disabled error 403

### ISSUE THREAD

**Issue by GabrielLiade** [strapi/strapi#8395]

**Comment by derrickmehaffy** [comment]
Make sure you aren't sending a bearer token in that request

**Comment by GabrielLiade** [comment]
indeed I don't sending a bearer token in the request, by the way is working when I add the user JWT token in the bearer token... but in my case the user not suppose to be connected 😓
<img width="1094" alt="Capture d’écran 2020-10-20 à 01 00 53" src="https://user-images.githubusercontent.com/66065611/96520594-b73f9780-126f-11eb-83ef-981d851a6341.png">

**Comment by GabrielLiade** [comment]
knowing my app is deploy on heroku
