### ISSUE TITLE
data is not re populated after updating an collection entry

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#8400]
### Describe the bug

If an update to an entry of a collection is done and fields are manipulated by a lifecycle hook, the data in the form is not showing the manipulations after saving.

### Steps to reproduce the behavior

1. add an entry to a collection with fields that are manipulated with a lifecycle hook (beforeUpdate) and save it.
2. the form is not showing the changes done by the lifecycle hook, although they are done. They are shown if you exit and re enter the form.

### Expected behavior

 @soupette mentioned in the forum: "The bug is indeed the following one, we should have an submit success case where we should re populate the form with the data that was just submitted."

### System

- Node.js version: 12.18.4
- Strapi version: 3.2.4

### Additional context

https://forum.strapi.io/t/reload-data-after-saving-update/548

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/reload-data-after-saving-update/548/4

**Comment by sam-pires** [comment]
Fixed by https://github.com/strapi/strapi/pull/8456
