### ISSUE TITLE
GraphQL includes error

### ISSUE THREAD

**Issue by wityan** [strapi/strapi#8409]
### Describe the bug

The App does not start after I installed the Graphql plugin.

### Steps to reproduce the behavior
1. npm run develop (with graphql plugin installed)

### Expected behavior

Application starts

### Screenshots

![image](https://user-images.githubusercontent.com/20127773/96620306-9296fe80-1307-11eb-8155-388b7215cdb8.png)

### System

- Node.js version: 12.19
- NPM version: 6.14.8
- Strapi version: 3.1.4
- Database: Postgress
- Operating system: Mac Os

### Additional context
It worked before installing graphql plugin

**Comment by derrickmehaffy** [comment]
Can you please include a link to your project or a sample project that you have reproduced the issue on?

Unable to reproduce on the current latest version 3.2.4

**Comment by Hyun2** [comment]
I got the same error.
I think that it happens because graphql plugin version and other strapi packages version are not same.

before changing, my package.json 
```json
"dependencies": {
    "knex": "<0.20.0",
    "pg": "^7.18.2",
    "strapi": "3.1.3",
    "strapi-admin": "3.1.3",
    "strapi-connector-bookshelf": "3.1.3",
    "strapi-plugin-content-manager": "3.1.3",
    "strapi-plugin-content-type-builder": "3.1.3",
    "strapi-plugin-documentation": "^3.1.3",
    "strapi-plugin-email": "3.1.3",
    "strapi-plugin-graphql": "^3.1.3",
    "strapi-plugin-upload": "3.1.3",
    "strapi-plugin-users-permissions": "3.1.3",
    "strapi-utils": "3.1.3"
  },
```

after changed, my package.json
```json
"dependencies": {
    "knex": "<0.20.0",
    "pg": "^7.18.2",
    "strapi": "^3.2.4",
    "strapi-admin": "^3.2.4",
    "strapi-connector-bookshelf": "^3.2.4",
    "strapi-plugin-content-manager": "^3.2.4",
    "strapi-plugin-content-type-builder": "^3.2.4",
    "strapi-plugin-documentation": "^3.2.4",
    "strapi-plugin-email": "^3.2.4",
    "strapi-plugin-graphql": "^3.2.4",
    "strapi-plugin-upload": "^3.2.4",
    "strapi-plugin-users-permissions": "^3.2.4",
    "strapi-utils": "^3.2.4"
  },
```

and I install npm packages, it worked for me.

**Comment by wityan** [comment]
Thx @Hyun2 this worked

**Comment by derrickmehaffy** [comment]
`^3.2.4` Be careful with the `^`, that may cause some issues for you in the future (on Strapi packages)
