### ISSUE TITLE
It should be possible to link an existing file to an entity

### ISSUE THREAD

**Issue by TheWebsDoor** [strapi/strapi#841]
**Node.js version**:
8.9.3
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.11.1
**Operating system**:
MacOS 10.13.3

**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
If we want to attach an uploaded file to an entity, it's only possible in one way : first step is to create the entity and the second is to upload the file and pass the created entity `refId`. But if we want to upload the file first and attach it to a new entity in that order, I can't do it.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
It's not a bug I think but to reproduce it, I've tried to upload my file first then after I tried to create my entity and in the file field, I tried to put the file id but it didn't work.

**What is the expected behavior?**
It should be possible to pass the id of the file in the field we create the new entry of the entity.

**Comment by lauriejim** [comment]
@Aurelsicoko told me it's possible. I let him answer you.

**Comment by Aurelsicoko** [comment]
This behaviour will be handled by the Media Library plugin. It wasn't the goal of the Upload plugin to manage the links between entities and files. However, we anticipated it, that's all we did.

**Comment by lauriejim** [comment]
@TheWebsDoor Have you update about this point ?

**Comment by TheWebsDoor** [comment]
I didn't try to reproduce it since the last time, I'll check it tonight and I'll let you know !

**Comment by fodkastir** [comment]
@TheWebsDoor  Have you figure out how to link an existing file to an entity?

**Comment by TheWebsDoor** [comment]
@fodkastir I have to admit that it's been a while and I don't really remember if I came up with something. @lauriejim have you done something about this since last time? Let me know if you want me to investigate a bit more!

**Comment by lauriejim** [comment]
This feature will be available in this feature card - https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities
For now, you can only `Upload` file related to an entry. That is the reason why the feature name that is available is named **Upload**

**Comment by francescofact** [comment]
I tried to upload the file to the entity, but i can't get it on the entity. I find it in the Media Library but the field "Avatar" of the entity is empty.
`await uploadFiles(me, files, { model: strapi.models.agenzie })`
this is my code, where "me" is the ID of the entity in the table _agenzie_ and "files" is obtained by _parseMultipartData(ctx)_
Am i missing something?
