### ISSUE TITLE
I am getting error when am installing strapi locally with both npx and yarn

### ISSUE THREAD

**Issue by Ibraheem-adeyemo** [strapi/strapi#8411]
#7715 

 Bug report
success Installed "create-strapi-app@3.2.4" with binaries:
- create-strapi-app
Creating a new Strapi application at C:\Users\developer\Documents\work\Personal\practice\Nodejs\strapi\projects\food_vendor.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi-admin > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning strapi-admin > react-intl > @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
warning strapi-admin > react-intl > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > react-intl > intl-messageformat > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning strapi-admin > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-plugin-users-permissions > request@2.88.2: request has been deprecated, see request/request#3142
warning strapi-plugin-users-permissions > request > har-validator@5.1.5: this library is no longer supported
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see request/request#3142
warning url-loader@1.1.2: Invalid bin field for "url-loader".
error An unexpected error occurred: "https://registry.yarnpkg.com/@formatjs/intl-unified-numberformat/-/intl-unified-numberformat-3.3.7.tgz: ESOCKETTIMEDOUT".

Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd C:\Users\developer\Documents\work\Personal\practice\Nodejs\strapi\projects\food_vendor && yarn install

error Command failed.
Exit code: 1
Command: C:\Users\developer\AppData\Local\Yarn\bin\create-strapi-app
Arguments: food_vendor --quickstart
Directory: C:\Users\developer\Documents\work\Personal\practice\Nodejs\strapi\projects
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
PS C:\Users\developer\Documents\work\Personal\practice\Nodejs\strapi\projects>

** 1.do npx create-strapi-app project_name --quickstart **
** 2. or yarn create strapi-app project_name --quickstart **

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed as it doesn't currently follow our Contributing guide for making bug reports.

But based off the error: `error An unexpected error occurred: "https://registry.yarnpkg.com/@formatjs/intl-unified-numberformat/-/intl-unified-numberformat-3.3.7.tgz: ESOCKETTIMEDOUT".` you either have a slow connection to the yarn registry or your internet is dropping during some of the package installs. 

Once the project has been bootstrapped (and after you get this error) you can move into the project directory and use something like `yarn install --network-timeout 1000000000` which should allow the packages to be installed.
