### ISSUE TITLE
Strapi does not recognice plugins.js file as stated in the docs

### ISSUE THREAD

**Issue by lsliwaradioluz** [strapi/strapi#8418]
I had some problems configuring my Sendgrid e-mail provider in Strapi v.3.2.4. Sending an email with proper body was returning an Internal Server Error (500). It turned out it was due to naming my config file "plugins.js" as mentioned in the documentation. Renaming the file to "plugin.js" worked as expected. 

Steps to reproduce: 
1. Create a new strapi project using the quick start option
2. Install sendgrid e-mail provider using "npm install strapi-provider-email-sendgrid --save" command
3. Create new sendgrid account on https://app.sendgrid.com/ and get an API Key
4. Configure your email plugin in ./config/plugins.js, use the newly created API Key
5. Try to send an email via localhost:1337/email using Postman 
6. Rename ./config/plugins.js file ti plugin.js
7. Try to send an email via localhost:1337/email using Postman

**Comment by derrickmehaffy** [comment]
Tested using v3.2.4 and the built in email confirmation: 

![image](https://user-images.githubusercontent.com/8593673/96776402-db999200-139d-11eb-8b3b-00f59423b651.png)

No issue found with `./config/plugins.js`

---

Tested with the /email route:

![image](https://user-images.githubusercontent.com/8593673/96777295-046e5700-139f-11eb-84ab-45e61cfffcc4.png)

Yields the same result, the actual file that should be used is `./config/plugins.js` OR any of the environment specific override files

- `./config/env/staging/plugins.js`
- `./config/env/production/plugins.js`
- `./config/env/anythingyouwant/plugins.js` <-- In this case the `NODE_ENV` would be `anythingyouwant` AKA `NODE_ENV=anythingyouwant`

I'm going to mark this as closed as it is intended but I do invite you to share your sample application to see if maybe I'm missing something? Thank you!

**Comment by lsliwaradioluz** [comment]
The problem is, I tested it with a totally fresh install of Strapi 3.2.4 (quick start) and it behaved that way.  I'm gonna make a loom video asap and show how it works in my environment.

**Comment by derrickmehaffy** [comment]
My test was done the same way with a fresh project on the latest release
