### ISSUE TITLE
Dependency version in docs but not available in npm ["strapi-hook-bookshelf": "3.0.6"]

### ISSUE THREAD

**Issue by alatella87** [strapi/strapi#8421]
### Please describe your feature request

- [x] **It would be good to have the correct npm version mentioned in the Strapi docs, see https://strapi.io/documentation/v3.x/guides/update-version.html#upgrading-your-dependencies**

### Summary

Quick summary what's this feature request about.

### Suggested solution(s)

Temporarily refer to an existing and tested version

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Going to mark this as closed as it doesn't properly use our templates but I have a PR open to fix the doc issue.
