### ISSUE TITLE
Required fields are not enforced upon creating new content

### ISSUE THREAD

**Issue by AlexVanK** [strapi/strapi#8423]
### Describe the bug

Required fields are not enforced upon saving.

### Steps to reproduce the behavior

1. Go to Content-Types Builder > Collection Types
2. Edit one of your Collection Types and put one of the fields as required
3. Try to create a new entry in your Collection Types panel leaving that required field blank
4. Save if you can.

### Expected behavior

The creation of a new item in the collection type should be prevented because some of the required fields are missing.

### Screenshots

![image](https://user-images.githubusercontent.com/56647386/96731774-9f5a3780-1385-11eb-9659-8e27dc1fa066.png)
![image](https://user-images.githubusercontent.com/56647386/96731944-d2043000-1385-11eb-9ede-97dcb106f0d4.png)

### System

- Node.js version: 10.16.3 
- NPM version: 6.9.0
- Strapi version: 3.2.4
- Database: SQLite
- Operating system: Windows Server 2016

### Additional context

I recently updated Strapi from 3.1.6 to 3.2.4 and I am not sure if this is what caused the issue. 
Also I have been changing the requirement property of some fields on and off, I am not sure if this contributed to the issue as well.

**Comment by derrickmehaffy** [comment]
Hello,

This is intended while in a draft state, see the following issue: https://github.com/strapi/strapi/issues/8394

As this is a duplicate I'm going to mark as closed.
