### ISSUE TITLE
Can't add Arabic values in Enumeration fields

### ISSUE THREAD

**Issue by ajj-siraj** [strapi/strapi#8426]
### Describe the bug

I can't add Arabic values. It gives me a "The value does not match the regex" error as shown in the screenshot below. I presume that's because only English is supported? But I want to make sure it's not because of any settings or something I need to configure that I didn't. I didn't see anything in the docs regarding this so if there's a setting I need to change please let me know. I'm using the default strapi quick starter.

### Steps to reproduce the behavior

1. Add an Enum type field to any collection or single type.
2. Add Arabic values separated by new lines.
3. Click finish.

### Expected behavior

That it would add normally.

### Screenshots

https://ibb.co/RbzVjGx

### System

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: Default (PostrgreSQL)
- Operating system: Windows 10

### Additional context

I'm using Strapi as the headless CMS for a bilingual website so I need to add two of every field for the two languages I support.
Since I want to give the client the freedom to add/remove categories as they see fit in the future. I don't want to hardcode anything in my application so I need to have the name of the category for each item in both languages.

**Comment by derrickmehaffy** [comment]
Hello please see: https://github.com/strapi/strapi/issues/7904
