### ISSUE TITLE
query.update() doesn't return updated record if the supplied filters no longer match

### ISSUE THREAD

**Issue by flaki** [strapi/strapi#8431]
### Describe the bug

When a an update() query affects one of the properties the update filter is predicated on the update is performed but no results are returned which is very confusing and misleading behavior.
[In the documentation](https://strapi.io/documentation/v3.x/concepts/queries.html#api-reference) only `{ id: X }` filters are used for `update()`, but there is no indication that more complex filtering (like that in `find()`) would be unsupported.

### Steps to reproduce the behavior

- Have a record with unique `id` fields and a string/enum `status` field.
- `strapi(model).update( {id: ID, status: CURRENT_STATUS }, { status: NEW_STATUS })`
- When ID and CURRENT_STATUS matches a record its status is correctly updated to NEW_STATUS
- Yet the `update()` query returns `null` indicating no update has taken place

### Expected behavior

I would expect the `update()` query to return changed (matched) rows even if the updated rows don't match the original filter query:

- I want to update the `status` of a record for a certain ID only if the current `status` matches my expectation of CURRENT_STATUS.
- If there is a match on ID & CURRENT_STATUS, the update is performed and I want the new state (incl. the changed NEW_STATUS) to be returned.
- If `status` doesn't have the expected value I expect `update()` to return NULL.

### Code snippets

Here is a debug log of the queries being executed:

```javascript

// Strapi fetches the record id
sql: 'select "passes".* from "passes" where "reference" = ? and "status" = ? limit ?';
bindings: [ 'c25ece...', 'pending', 1 ];
// This returns the record id 199

// Strapi uses the returned record id to update the record
sql: 'update "passes" set "status" = ?, "updated_at" = ? where "id" = ? returning *';
bindings: [ 'confirmed', '2020-10-22T...', 199 ];
// The status value is now changed

// For some reason instead of reusing the id 199 and returning the changed value, Strapi
// queries the original filter again, which of course doesn't return any rows any more
sql: 'select distinct "passes".* from "passes" where "passes"."reference" = ? and "passes"."status" = ? limit ?';
bindings: [ 'c25ece...', 'pending', 1 ];
```

**System**

- Node.js version: `v12.18.4`
- NPM version: `v12.18.4`
- Strapi version: 3.2.4
- Database: postgres
- Operating system: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-26-generic x86_64)

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.1.4

Hi @flaki just to ensure the bug can be confirmed can you please test on the latest version `v3.2.4`

**Comment by flaki** [comment]
@derrickmehaffy oops, actually that was a typo, the production server *is* actually on 3.2.4 (fixed above).

**Comment by derrickmehaffy** [comment]
Should be fixed in v4
