### ISSUE TITLE
Can't clear an input date from the admin panel

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#8434]
### Steps to reproduce the behavior

1. Create an entry of a model with an input date.
2. Edit that entry removing the input date.
3. Try to save. You can't 😢 

### Expected behavior

Allow to clear the input date.

### System

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.2.4
- Database: MongoDB
- Operating system: macOS

**Comment by Fedos2589** [comment]
same problem

**Comment by sam-pires** [comment]
FYI - Design and logic needed

**Comment by abdonrd** [comment]
Fixed in v4.
