### ISSUE TITLE
 How to call stored procedure in strapi? 

### ISSUE THREAD

**Issue by ShubhamKT1060** [strapi/strapi#8435]
I want to call the store procedure in strapi. I have already developed tables in (oracle, etc) I want to call this store procedure in strapi? can you please suggest the procedure to call my store procedure in strapi

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
