### ISSUE TITLE
Custom controllers not respecting access rules if policies not explicitly set

### ISSUE THREAD

**Issue by abanchev** [strapi/strapi#8438]
## Bug report
If we follow the guide to create a custom controller, the resulting controller will not respect the role access rules set in strapi.
### Describe the bug

Controller endpoints become accessible to everyone no matter the role.

### Steps to reproduce the behavior

1.Follow the steps outlined in the documentation:
https://strapi.io/documentation/v3.x/concepts/controllers.html#core-controllers
- strapi generate:controller restaurant
- modify the restaurant.js to add a index method
```
module.exports = {
  // GET /hello
  async index(ctx) {
    ctx.send('Hello World!');
  },
};
```
- add an endpoint 
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/hello",
      "handler": "restaurant.index"
    }
  ]
}
```

### Expected behavior

Public user should not have access to the endpoint

### System

- Node.js version: 12
- NPM version: 6.14.8
- Strapi version: 3.2.4
- Database: mysql
- Operating system: linux

### Additional context

adding empty policies to the route, fixes the issue
```
      "config": {
        "policies": []
      }
```

**Comment by derrickmehaffy** [comment]
Closing as fixed docs in above PR
