### ISSUE TITLE
Renaming Collection Type Doesn't Reach "Users & Permissions" Plugin

### ISSUE THREAD

**Issue by ngreve** [strapi/strapi#8444]
### Describe the bug

When renaming collection types, the name in `Roles->Edit Role->Permissions` does not get updated.

### Steps to reproduce the behavior

1. Create new Collection Type and give it a `Display name` with at least one field (type doesn't matter). Save it.
2. Rename the created Collection Type (`Display name` and  `Collection name`) 
3. Go to `Settings->Users&Permissions Plugin->Roles->Edit->Permissions->Application` still has the old name defined in step 1

### Expected behavior

Update the name defined in step 2.

### Screenshots
In the side navigation you can see the collection type `Posts` which was named `Restaurant` earlier.
On the right site in the `Applications` dropdown, `Restaurant` was not updated to `Posts`.
![image](https://user-images.githubusercontent.com/18660100/96889930-65715a00-1487-11eb-881c-43f2fddb3fd0.png)

### System

- Node.js version: v12.19.0
- NPM version: 6.14.8
- Strapi version: 3.2.4
- Database: sqlite (Environment: development)
- Operating system: Arch Linux 5.9.1-arch1-1

**Comment by derrickmehaffy** [comment]
(Wrong issue for labels sorry)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/6630

**Comment by ngreve** [comment]
Sorry, but I do not understand why this is closed exactly. The referenced issue was closed because the creator of the issue was not using the template and did not explained the issue well enough.
Did i make the same mistake in some way? Is the reported behavior wanted? Because now both are closed and the issue is not visible to any developer ...

**Comment by derrickmehaffy** [comment]
Ah my appologies @ngreve I linked the wrong issue: https://github.com/strapi/strapi/issues/6837

See this comment: https://github.com/strapi/strapi/issues/6837#issuecomment-665505159

**Comment by mpgoulet** [comment]
Please reopen this issue if possible. Renaming content types does not work in 3.4.4. As OP said, the collection name (Advanced tab), is not reflected in the name throughout the system.

Note url containing old name, catalog_item, which was later renamed to collection item.
![image](https://user-images.githubusercontent.com/36751696/106032408-704b1480-609e-11eb-9ac1-59474ad0da4d.png)

**Comment by derrickmehaffy** [comment]
> Please reopen this issue if possible. Renaming content types does not work in 3.4.4. As OP said, the collection name (Advanced tab), is not reflected in the name throughout the system.
> 
> Note url containing old name, catalog_item, which was later renamed to collection item.
> ![image](https://user-images.githubusercontent.com/36751696/106032408-704b1480-609e-11eb-9ac1-59474ad0da4d.png)

@mpgoulet as I mentioned before, this issue is a duplicate of #1114 we won't reopen duplicate issues. **Both** renaming and deleting content-types or fields all related to the same issue => database migrations => #1114
