### ISSUE TITLE
why disable browser cache in media library? 

### ISSUE THREAD

**Issue by a1029382825** [strapi/strapi#8452]
Why disable browser in media library? Each time I browse the media library, the preview takes a long time to load.
I found that no ‘withFileCaching={false}’ prop in ‘strapi-plugin-upload/admin/src/components/List/index.js’.
Can the cache be turned on, and what will happen if it is turned on?

**Comment by harrykc** [comment]
same for me, takes long time to load.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
