### ISSUE TITLE
Nested components don't have __component property in REST API

### ISSUE THREAD

**Issue by kilianso** [strapi/strapi#8453]
## Context

We are using dynamic zones to be able to add components to collection-types and single-types. As an example, an editor can choose from several different components e.g.`teaser-media` and then decide, if the chosen component should have a link to a certain article, another page, or even an external URL. To avoid redundancy, we created a `link-relation` component and nested it within all related components. 

### Describe the bug

When accessing the REST API we receive the `__component` property only on the first-level but not for nested components. So within the dynamic zone the object "components" have everything we need to dynamically determine the corresponding frontend component. However, the nested `link-relation` within `teaser-media` only returns the `id` and the content fields but not `__component`. This makes it extremely hard to deal with it on the frontend side. It's impossible to determine which component this is without such a field.

### Steps to reproduce the behavior

1. Go to Strapi Backend
2. Create two components (e.g. `teaser-media` and `link-relation`) - add at least one content field like a "title" to each component.
3. In the left sidebar, click on the `teaser-media` component and add a new field > component > call the field "link", choose the already created `link-relation` component and add it.
4. Create a collection type called `articles` with a short-text-field (e.g. called "title") and dynamic zones called `components` and add `teaser-media` and `link-relation` to it.
5. Create a new article, fill in the title, and add `teaser-media` and `link-relation` below each using the dynamic zones UI. Then save/publish this article.
6. Now access the REST API and check the response. There will be two entries below `components`. One `teaser-media` and  one`link-relation` and both have the `__component` property.
7. Now expand `teaser-media`and look for the "link" field. Expand that and you'll see that there are just content fields but no `__component` property which makes it impossible to tell that this is a component.

### Expected behavior

Output the `__component` field in the REST API for nested components. Or provide another solution to distinguish nested components from plain content. We also tried adding a custom text-field "componentName" to each component and set its name as the default value. But this always remains NULL in the REST response. And as far as we saw it in the documentation, we cannot solve this by adding the field using lifecycle functions as we could do for content-types.

### Screenshots

Strapi structure

![nested_components](https://user-images.githubusercontent.com/15088651/96990103-f2b7bb80-1526-11eb-9ad9-9a4953946204.png)

Response

<img width="625" alt="response" src="https://user-images.githubusercontent.com/15088651/96990143-006d4100-1527-11eb-8f0e-323d25516858.png">

### System

- Node.js version: 12.8.4
- NPM version: 6.14.6
- Strapi version: 3.2.3
- Database: SQLite
- Operating system: MacOS Catalina 10.15.7

**Comment by LucaNerlich** [comment]
Similar issue here: https://forum.strapi.io/t/dynamiczone-different-property-names-graphql-vs-rest/523

**Comment by VMonsch** [comment]
Hey @kilianso, I think this isn't a bug as static components don't need the __component property as you know what to expect.

The property is however essential in dynamic zones in which contributors can pick and choose the object's fields isn't this specific to nested dynamic zones and not nested components ? As static components don't need a __component property since you know what to expect.

I don't understand the issue here, if you have a "teaser.teaser-media" component then for sure you'll have a Link field group in it.

Any update on this since then ?

**Comment by kilianso** [comment]
Hey @VMonsch 

Thanks for your answer. In our case, we wanted to do a recursive loop over everything coming from the Strapi API, retrieve the value of the __components property, and render the corresponding component in the frontend. So as long as every component on every nesting level in the response has this property, it works just great. However, as you said, static components don't have it. Therefore we needed to know what to expect at certain levels of the response and had to create additional checks on the frontend side.

What is the reason not to use the __component property also for static components?

**Comment by opsidao** [comment]
Any news on this? We want to implement something similar to what @kilianso described in 2021 and found the same limitation...

**Comment by ainformatico** [comment]
Was about to write in the Discourse group and just found this ticket. Any progress?

**Comment by nathan-pichon** [comment]
> Was about to write in the Discourse group and just found this ticket. Any progress?

Hello
Sorry for the late reply.
We will take a look at this issue, it is currently in our backlog.

**Comment by nathan-pichon** [comment]
Hello,
I apologize for the delay in my response and thank you for bringing this issue to our attention. Your interest in improving Strapi is much appreciated.

Our engineering team has had a thorough discussion on this issue and we have decided not to add the __component attribute in nested components. We believe that having more data than necessary in content-api is not ideal and can affect rendering performance. We recommend fetching the schema before rendering an entity data.

We value your contribution and appreciate your effort to improve Strapi. If you have any further questions or suggestions, please feel free to reach out to us.
