### ISSUE TITLE
Cannot add JSON field named "attributes"

### ISSUE THREAD

**Issue by lodisy** [strapi/strapi#8458]
### Describe the bug

Cannot add JSON field named "attributes" for product content type

### Steps to reproduce the behavior

1. Go to Content-Type Builder
2. Click content type "product"
3. Click add another field, select JSON
4. Input "attributes" for the name, click finish
5. Error "This name cannot be used in your content type as it might break other functionalities" pops 

### Expected behavior

No error

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.19.0
- NPM version: 6.14.8
- Strapi version: 3.2.3
- Database: NoSQL
- Operating system: macOS

**Comment by MattieBelt** [comment]
Hey @lodisy,

As the _Error_ implies, this is to prevent that a functionalities of Strapi might break, this is intended. 
No [model attribute](https://strapi.io/documentation/v3.x/concepts/models.html#define-the-attributes) can have the name `attributes`, whatever the type might be.

To solve this you simple you could use a different name (`features`, `properties` or `productAttributes`).

**Comment by lodisy** [comment]
Thanks. Got it. 

Please close the issue.

**Comment by MattieBelt** [comment]
You will need to do it or someone from the team.

I'm not part of @strapi/maintainers :)
