### ISSUE TITLE
Data relation creation from front-end application

### ISSUE THREAD

**Issue by tranthebao** [strapi/strapi#846]
**Node.js version**:
v8.9.4
**npm version**:
v5.6.0
**Strapi version**:
3.0.0-alpha.11.1
**Operating system**:
windows 8.1 64bit
Database : mysql
**Do you want to request a *feature* or report a *bug*?**
relation the table `author` and `book`(one-many). Front end, i'm create a form. When input data and submit. Data not insert two tables
**What is the current behavior?**
Can not insert record multi table with relation (one-many)
**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**
I'm want submit form insert data two table author and book.
`CREATE TABLE author (
	id int NOT NULL AUTO_INCREMENT,
	name varchar(30) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB AUTO_INCREMENT=13;

CREATE TABLE book (
	id int NOT NULL AUTO_INCREMENT,
	author int NOT NULL,
	title varchar(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=5;`
thank you alot of.

**Comment by tranthebao** [comment]
so. i cant example it. you can support it. thanks!

**Comment by lauriejim** [comment]
Hi @tranthebao don't really understand your issue

**Comment by lauriejim** [comment]
This PR (https://github.com/strapi/strapi/pull/1025) will help to fix your issue
