### ISSUE TITLE
Files uploaded to cloudinary lose their extension

### ISSUE THREAD

**Issue by catalina-cimpanu** [strapi/strapi#8462]
Hi! 

I am using strapi as CMS for gatsby and I find both really cool. Thank you for making available such awesome technologies.

### Describe the bug

I stumbled into this issue though, and I don't know if I did something wrong or it's something already known:
I am uploading svg's as images for some posts, and 
1. They don't show as preview in strapi (i found this [https://github.com/strapi/strapi/issues/5788](https://github.com/strapi/strapi/issues/5788) but I don't really see the solution)
2. They don't get fetched correctly from gatsby (they get fetched without the .svg extension and they are not recognized as images)

### Steps to reproduce the behavior

1. Upload an svg in the media library in strapi 
2. Check the media library => no preview
3. Query the image with graphql in gatsby (using publicURL and not gatsbyImageSharp) => the file will arrive in the `/static` folder of gatsby, but without an extension => is not recognized as image (about that I am sure, because I manually changed the extension of the file in the static folder and I concatenated the publicURL with .svg in the img element I am trying to access it, and then it worked)

### Expected behavior

1. I see the preview images correctly in strapi
2. I receive the images WITH the svg extension from strapi in gatsby 

### Screenshots

![strapi-media-library](https://user-images.githubusercontent.com/67892765/97049452-0b9e8c00-157c-11eb-80cd-ca76453bce12.png)
![no-svg-ext](https://user-images.githubusercontent.com/67892765/97049474-135e3080-157c-11eb-87c1-b3a9fab567c8.png)
)

### Code snippets
Code that doesn't import the image correctly (cardImg is the queried variable name for my image): 
```
<CardImage
          src={cardImg.publicURL}
          alt={`${cardTitle} word cloud`}
        />
```
Result: 
![card-no-svg-ext](https://user-images.githubusercontent.com/67892765/97049945-d21a5080-157c-11eb-88b4-90bc1e861607.png)

If I add the svg extension manually, like so:
![manually-added-svg-ext](https://user-images.githubusercontent.com/67892765/97050186-36d5ab00-157d-11eb-80e5-93ca109ac391.png)
and use the following code: 
```
<CardImage 
        src={`${cardImg.publicURL}.svg`} 
        alt={`${cardTitle} word cloud`} 
/>
```
then it works:
![card-manually-added-svg-ext](https://user-images.githubusercontent.com/67892765/97050398-8fa54380-157d-11eb-9ffa-cea4ed920117.png)

### System

- Node.js version: v12.18.3
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: mongoDB (Atlas)
- Operating system: Windows10

**Comment by derrickmehaffy** [comment]
Can you please provide some sample SVGs that you have noticed have issues? Generally we have seen issues with SVG only when it's missing the XML head `xmlns="http://www.w3.org/2000/svg"` and the package we use to determine the file type fails to detect it's an SVG.

**Comment by catalina-cimpanu** [comment]
Yes sure. Here, from cloudinary:
[https://res.cloudinary.com/skizzo-cloud/raw/upload/v1603385646/general_76cd914420](https://res.cloudinary.com/skizzo-cloud/raw/upload/v1603385646/general_76cd914420)
[https://res.cloudinary.com/skizzo-cloud/raw/upload/v1603385647/headache_2204e13f05](https://res.cloudinary.com/skizzo-cloud/raw/upload/v1603385647/headache_2204e13f05)

I just noticed that also on cloudinary they don't have the svg extension. If you download the files and add the `.svg` extension they work fine. Maybe it is related to cloudinary? I used `strapi-provider-upload-cloudinary` in the initial project. It was the first time I tried to import svgs. 

Meanwhile, I am redoing the project entirely, because I simply couldn't solve these image issues and after 2 days of failed debugging, I got to the conclusion it is just faster to redo everything,since my project is also not that huge and i can copy part of it. And this time I chose to use `strapi-provider-upload-local`. Now the svgs are previewed correctly in strapi, but I didn't yet test the importing to gastby. 

Should I let you know how that works? 

![svg ok](https://user-images.githubusercontent.com/67892765/97221652-801c3980-17cd-11eb-8ee4-cafe81040b6b.png)

**Comment by derrickmehaffy** [comment]
I'm testing the images now, but digging into their XML code, the two examples provide include the required svg struct tag:
`<svg viewBox="0 0 926 572" fill="none" xmlns="http://www.w3.org/2000/svg">`

**Comment by derrickmehaffy** [comment]
I can confirm local provider works fine, images are uploaded with their proper file ext:

![image](https://user-images.githubusercontent.com/8593673/97229129-2009a100-1795-11eb-9a96-1a13c90b7297.png)

And I can confirm the bug with cloudinary
![image](https://user-images.githubusercontent.com/8593673/97229724-061c8e00-1796-11eb-9da8-9f43048e98b2.png)

**Comment by catalina-cimpanu** [comment]
Thank you for taking a look 👍 
For now, I can keep my project locally. I will let the strapi team take care of this then :)
Have a good day!

**Comment by derrickmehaffy** [comment]
Additional information related from the linked issue, this appears to happen on multiple file types not just SVGs
