### ISSUE TITLE
Create strapi-app hangs on stapi-connector-bookshelf dependency

### ISSUE THREAD

**Issue by ljdatasci** [strapi/strapi#8463]
### Describe the Bug

When you run either the `npx create-strapi-app my-project --quickstart` command or `yarn create strapi-app my-project --quickstart`  , the installation hangs on the strapi-connector-bookshelf dependency.  It sets up the project directory, but all of the project dependencies may not be installed.

### Steps to reproduce

1.  Run `npx create-strapi-app my-project --quickstart` or `yarn create strapi-app my-project --quickstart`

### Expected Behavior

Running either command will install strapi starter project

### Screenshots

![strapi-install-error-102420](https://user-images.githubusercontent.com/52286551/97083316-205f3c00-15dd-11eb-9f98-c72925608048.png)

### System
- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version: latest
- Database: none
- Operating System: Windows 10

**Comment by ljdatasci** [comment]
Strapi hangs on "stapi-connector-bookshelf" peer dependency with either yarn or npx.  When you run "create strapi-app" command, the installation starts, but then hangs on the dependency.

**Comment by MattieBelt** [comment]
Hey @ljdatasci,

Did you already clean your [yarn](https://classic.yarnpkg.com/en/docs/cli/cache/) and [npm](https://docs.npmjs.com/cli-commands/cache.html) cache?

Also `npx create-strapi-app@latest my-project` might work.

**Comment by MattieBelt** [comment]
Also use the bug template so devs from Strapi can verify it isn't a system/environment problem.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by ljdatasci** [comment]
## Bug Report

### Describe the Bug

When you run either the `npx create-strapi-app my-project --quickstart` command or `yarn create strapi-app my-project --quickstart`  , the installation hangs on the strapi-connector-bookshelf dependency.  It sets up the project directory, but all of the project dependencies may not be installed.

### Steps to reproduce

1.  Run `npx create-strapi-app my-project --quickstart` or `yarn create strapi-app my-project --quickstart`

### Expected Behavior

Running either command will install strapi starter project

### Screenshots

![strapi-install-error-102420](https://user-images.githubusercontent.com/52286551/97083316-205f3c00-15dd-11eb-9f98-c72925608048.png)

### System
- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version: latest
- Database: none
- Operating System: Windows 10

**Comment by MattieBelt** [comment]
@ljdatasci for how long did you wait?
Do you have a stable internet connection?

You could also install them manually afterwards.
```batch
cd petstore

yarn
// or 
npm install
```

**Comment by derrickmehaffy** [comment]
Unable to reproduce on the latest version (v3.2.5) with Linux Mint 20, MacOS Catalina, and Windows 10.

**Comment by ljdatasci** [comment]
It's a network issue.  I will fix it on my end.

**Comment by derrickmehaffy** [comment]
Thanks for the confirmation @ljdatasci going to mark as closed for now, but please do let us know if you need more help.
