### ISSUE TITLE
Upload during entity creation does not support path, alternativeText, caption, etc.

### ISSUE THREAD

**Issue by reppard** [strapi/strapi#8467]
### Describe the bug

When uploading files *during* entity creation, strapi doesn't send `fileInfo` or `metas` to the uploadService. This makes it impossible to set `alternativeText` or `caption` for a given file.  It also removes the ability set `path` for custom paths using the S3 upload provider.

### Steps to reproduce the behavior

https://github.com/strapi/strapi/blob/b2b4515d9bf51060e6ae34ec9fef5099af19da62/packages/strapi/lib/services/utils/upload-files.js#L65

Upload a file during entity creation. Path, alternativeText, and caption will be ignored.

### Expected behavior

Should be able to append `fileInfo` and `metas` to FormData so attributes like `path`, `alternativeText`, and `caption` can be set *during* entity creation.

### Code snippets

https://github.com/strapi/strapi/blob/b2b4515d9bf51060e6ae34ec9fef5099af19da62/packages/strapi/lib/services/utils/upload-files.js#L57-L67

```javascript
// strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L355-L372
  async uploadToEntity(params, files, source) {
    const { id, model, field } = params;

    const arr = Array.isArray(files) ? files : [files];
    const enhancedFiles = await Promise.all(
      arr.map(file => {
        return this.enhanceFile(
          file,
          {}, // fileInfo could be provider here
          {   // could be added here
            refId: id,
            ref: model,
            source,
            field,
          }
        );
      })
    );

    await Promise.all(enhancedFiles.map(file => this.uploadFileAndPersist(file)));
  },
```

**Comment by derrickmehaffy** [comment]
Was able to confirm on v3.2.5

**Comment by reppard** [comment]
> Was able to confirm on v3.2.5

Thanks for confirming @derrickmehaffy

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/s3-custom-path-relative-to-bucket-while-uploading-during-entry-creation/581/10

**Comment by reppard** [comment]
@lauriejim I just updated that thread to point to this issue :joy:

**Comment by reppard** [comment]
I came up with a temporary work around for setting the `path`.  This is really only useful if the path isn't dynamic.  Using extensions we can hardcode the path in the uploadToEntity function:


```javascript
//extensions/upload/services/Upload.js
...
async uploadToEntity(params, files, source) {
    const { id, model, field } = params;

    const arr = Array.isArray(files) ? files : [files];
    const enhancedFiles = await Promise.all(
      arr.map(file => {
        return this.enhanceFile(
          file,
          {},
          {
            refId: id,
            ref: model,
            source,
            field,
            path: 'folder_in_bucket'
          }
        );
      })
    );

    await Promise.all(enhancedFiles.map(file => this.uploadFileAndPersist(file)));
  }
...
```

There are obvious limitations to this approach and it doesn't solve the alternativeText and captions bit

**Comment by derrickmehaffy** [comment]
> @lauriejim I just updated that thread to point to this issue

That's a bot, we need to change it off Jim's account

**Comment by thalesagapito** [comment]
I just opened a draft PR to discuss what would be needed to fix this. It's my first PR here so any feedback is welcome.  
Would a change like this fix the issue?

**Comment by thalesagapito** [comment]
This problem can be easily worked around by overriding the `uploadToEntity` method in the Upload service:

```js
// my-app/extensions/upload/services/Upload.js

'use strict';

/**
 * Upload.js service
 *
 * @description: A set of functions similar to controller's actions to avoid code duplication.
 */
module.exports = {
  async uploadToEntity(params, files, source) {
    const { id, model, field } = params;

    const arr = Array.isArray(files) ? files : [files];
    const enhancedFiles = await Promise.all(
      arr.map(file => {
        return this.enhanceFile(
          file,
          {
            alternativeText: file.alternativeText,
            caption: file.caption,
            name: file.name,
          },
          {
            refId: id,
            ref: model,
            source,
            field,
          }
        );
      })
    );

    await Promise.all(enhancedFiles.map(file => this.uploadFileAndPersist(file)));
  },
};
```

**Comment by Marc-Roig** [comment]
This seems to be implemented in v4, you should have access to path, alternativeText, and caption fields in the upload service.

In case you need more flexibility, you can override parts of the upload service for it :)
