### ISSUE TITLE
Lost all data 2 times in content types with unknown reason

### ISSUE THREAD

**Issue by WillyDolly** [strapi/strapi#847]
**Node.js version**: 8

**npm version**: >5

**Strapi version**: 3.0.0-alpha.10.3
In all of the sudden, I lost all data in strapi admin, but content type builder still keeps schema. In second times, strapi even resets user permission as well. I think strapi is not stable framework to count on. Anyone knows the cause and solution? Thanks

**Operating system**:

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by soupette** [comment]
Strapi is still in alpha, therefore, you might face some weird behaviors..

Could you please update your issue so we can reproduce the steps and fix the bug?

**Comment by WillyDolly** [comment]
Hi soupette! 
First of all, thanks for your team's work. 
Now there are 2 major problems:
1. Data loss but schema remains intact. I had to recreate database. Not sure when the pain will come back.
2. In the same content type, I can not view or edit some records, only white page shown
If strapi keeps shaking like this, I have no choice but use Botman as replacement. 
Hope you guys fix it up ASAP.

**Comment by soupette** [comment]
Do you have any error shown in the console?

**Comment by WillyDolly** [comment]
For problem #2, browser inspected : 
 a.Could not locate webpack:///main.js specified in source map https://coca.chatbot.exnodes.vn/admin/users-permissions/main.js.map.
 b. can not get property "id" in plugins/content-manager/admin/build/main.js at row 21619

My solution for b: replace t.value.id by constant = 1. It solved the problem #2 but I didn't know why. When I got t.value.id back in place, problem #2 again

**Comment by lauriejim** [comment]
@WillyDolly can you try with the latest version of Strapi.

**Comment by wpayush07** [comment]
@lauriejim I'm also having the same error and I'm using Strapi (latest version) with Postgres database and have deployed it on railway.app.
