### ISSUE TITLE
Get related content of the current authenticated user

### ISSUE THREAD

**Issue by zorox-1** [strapi/strapi#8470]
**_Strapi v3.2.5 — Community Edition_** 

i have a content type called "**appointment**".
relation of appointments to users is "**Many-to-one**" where Each authenticated user can have multiple "**appointments**"
im trying to get the appointment of the logged in user using **Graphql**

it works when i try via user id:

`query {
  user(id: "5f9550f9192ad40cb6362e69") {
    appointments {
      Title,
      Date
    }
  }
}`

however, when i try with "**_me_**",

`query {
  me {
    appointments {
      Title,
      Date
    }
  }
}`

 it gives an error :
**"Cannot query field \"appointment\" on type \"UsersPermissionsMe\"."**

Help please ???

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
