### ISSUE TITLE
Date picker component bug report

### ISSUE THREAD

**Issue by nikita-lipnyagov** [strapi/strapi#8475]
Dear colleagues, have some issues while working with date picker component in strapi.

### Bug description
It is impossible to remove previously settled date and time from date picker component. In any case the value is sent in request body.

### Steps to reproduce the behavior

1. Add datetime component in content-types builder to any collection.
2. Create an item in collection and set date and time.
3. Open created item again and try to update it by clearing date and time.

An example of field data that is sent after update: `"start_date":"2020-10-29T22:00:00.000Z"`

### Expected behavior

1. Data from picker is deleted without any problems.
2. The request to back-end is sent with null value in this field.

### Additional info

Also I suggest to warn the user or make some hint when he wants to set the time without date, because in this case the current date is set. For many people this logic is unobvious.

### Screenshots

Example of the component that I try to update:

![image](https://user-images.githubusercontent.com/20063800/97149440-6e0eac80-1775-11eb-8cbc-c4ce69d76b1d.png)

### System

- Node.js version: v12.18.4
- Npm version: 6.14.6
- Strapi version: 3.1.6
- Database: Postgresql
- Operating system: Ubuntu 18.04,3 LTS

**Comment by MattieBelt** [comment]
Related #8434

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8434
