### ISSUE TITLE
confirmation email redirect to the wrong URL

### ISSUE THREAD

**Issue by GabrielLiade** [strapi/strapi#8478]
## Bug report
I set into my backend (such as for the reset password page which worked well) the email confirmation URL : 

<img width="673" alt="Capture d’écran 2020-10-26 à 12 21 30" src="https://user-images.githubusercontent.com/66065611/97166571-c3eb5080-1785-11eb-84e7-567ad71c227a.png">

but the email in the email is still with the default url : 

<img width="849" alt="Capture d’écran 2020-10-26 à 12 18 57" src="https://user-images.githubusercontent.com/66065611/97166604-d1a0d600-1785-11eb-89ab-df80dd7f8329.png">

### Steps to reproduce the behavior

set email confirmation

### Expected behavior

I want my frontend url in the email 

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.1.6
- Database: pg
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment]
Can you please change your server.js file under `./config.js` or in one of your environment files `./config/env/*/server.js` and add the `url` key.

See: https://strapi.io/documentation/v3.x/concepts/configurations.html#server

Strapi should redirect after visiting the API I believe.

**Comment by derrickmehaffy** [comment]
(also testing should be done on the latest release, v3.2.5)

**Comment by GabrielLiade** [comment]
Yes, I'm updating Strapi, I will try in a moment, but I have a question, knowing my app is deployed on heroku (so it has his own url ) I have to set the url like this : 
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET'),
    },
  },
  url: `http://localhost:1337`,
});


or like this : 

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET'),
    },
  },
  url: `myHerokuAppUrl`,
});  


thank you so much ☺️
