### ISSUE TITLE
Permissiosn is saved but not saved 

### ISSUE THREAD

**Issue by SunD004** [strapi/strapi#8483]
Permissiosn is saved but not saved
When i save my permissions for the role in my project in the front i have the pop sucess but when i reload my page permissions is not saved and no code changes in the project

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
