### ISSUE TITLE
Uploading multiple files with REST Api fails if more than one fileInfo is sent

### ISSUE THREAD

**Issue by abanchev** [strapi/strapi#8484]
## Bug report
If we use the REST api to upload multiple files, there is no way to send more than one fileInfo (for the first file)

### Describe the bug

if we send multiple fileInfo strings the server reports 400 error

`fileInfo must be a object type, but the final value was: null (cast from the value ["\"{\"alternativeText\":\"EditorFile,\"}\"", "\"{\"alternativeText\":\"EditorFile,\"}\""]). If "null" is intended as an empty value be sure to mark the schema as .nullable()"`

### Steps to reproduce the behavior
Create a form with multiple file select, select 2 images, and for each of them add a fileInfo input with some alternative text.

### Expected behavior

We should be able to batch upload files and set the meta data at the same time.

### Code snippets

```
<Form id={id} onSubmit={submit}>
      <FormGroup>
        <Label className="w-100">{label}</Label>
        <ButtonGroup size="sm" className="w-100" {...btnGroupProps}>
          <Button onClick={handleClick}>
            {state ? ((state.length <= 1) ? ("Selected " + state[0].name) : (state.length + " files selected")) : "Select files"}
          </Button>
          <Button color="primary">
            Upload
          </Button>
        </ButtonGroup>
        <input multiple={multiple} type="file" name={"files"} ref={hiddenFileInput} style={{ display: 'none' }}
          onChange={handleChange} />
        {Object.keys(state || {}).map(r => <input type="hidden" name="fileInfo" value={JSON.stringify({ alternativeText: "EditorFile," })} />)}
      </FormGroup>
    </Form>
```

### System

- Node.js version: 12
- NPM version: 6.14.8
- Strapi version: 3.2.4
- Database: mysql
- Operating system: linux

### Additional context

Tried sending one fileInfo with JSON containing multiple objects, same issue

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
