### ISSUE TITLE
Models name part of the .gitignore file

### ISSUE THREAD

**Issue by llanas** [strapi/strapi#8485]
### Describe the bug

I created a model named "Icon" which is declared inside the .gitignore file.
As the result, on the remote host  (based on github branch) i had the following error : 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'globalId' of undefined
    at _.forEach (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:345:141)
    at /opt/dashboard/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/opt/dashboard/node_modules/lodash/lodash.js:2996:24)
    at /opt/dashboard/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/opt/dashboard/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:301:15)
    at /opt/dashboard/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/opt/dashboard/node_modules/lodash/lodash.js:2996:24)
    at /opt/dashboard/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/opt/dashboard/node_modules/lodash/lodash.js:9344:14)
    at mountModels (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:250:13)
    at _.forEach (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:449:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It was pretty hard to find out because my local app had no error even with production conf.

Thank's!

### Steps to reproduce the behavior

Create any model with a name declared in the generated .gitignore file

### System

- Node.js version: v12.18.3
- NPM version: 6.14.1
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Am able to confirm this on v3.2.5, very few instances but still should be a blocked model name.

**Comment by MattieBelt** [comment]
Related: #6761

**Comment by derrickmehaffy** [comment]
I've added it to our experimental issue board test to have the engineers take a look to figure out how best to handle it.

**Comment by AlexStansfield** [comment]
We ran into same issue that took about 6 hours to figure out. We're creating a insurance plan CMS and have a component called "coverage" no one could work out why it ran fine on the machine of the original developer but cloning from github it would always fail.

Turns out the gitignore (at more than 110 lines) is extremely eager to cover pretty much ever use case you can think of including test case coverage.

Possibly the gitignore could be reduced to cover strapi specific cases and let developers pick what other things they need to ignore depending on their needs?

**Comment by Boegie19** [comment]
closing this issue since it should be part of tracking issue https://github.com/strapi/strapi/issues/16222
