### ISSUE TITLE
Strapi doesn't work behind a reverse proxy

### ISSUE THREAD

**Issue by cawoodm** [strapi/strapi#8487]
### Describe the bug

Strapi does not work properly behind a reverse proxy. If you configure `admin.url` to be `/cms/strapi/admin` then the admin build process still generates `/admin" URLs.

The [example](https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html) given for running strapi behind a reverse proxy works only because the reverse proxy host is serving all paths so `/admin` is served by strapi.

### Steps to reproduce the behavior
1. Configure `admin.url` to `/cms/strapi/admin`
2. Build the admin UI (delete build and .cache directories first)
3. Notice that build/main.***.chunk.js still contains `/admin`, `/plugins`, `/content-types` and many other URLs
4. Run the NGINX configuration below to see that strapi calls `/admin` and gets a 404

### Screenshots

![image](https://user-images.githubusercontent.com/498834/97406832-1f3e4f80-18fa-11eb-9797-b203be3ea015.png)

### System

- Node.js version: v12.2.0
- NPM version: 6.9.0
- Strapi version: 1.3.6
- Database: Postgres
- Operating system: Windows 10, CentOS

### NGINX Config
```
location /cms/strapi/admin {
    proxy_pass http://127.0.0.1:1337/cms/strapi/admin;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass_request_headers on;
}
```

### config/server.js
```
module.exports = ({env}) => ({
  host: '0.0.0.0',
  port: env.int('PORT', 1337),
  admin: {
    url: '/cms/strapi/admin',
    autoOpen: false
  }
});
```

Note if you go behind the reverse proxy to http://127.0.0.1:1337/admin it works and http://127.0.0.1:1337/cms/strapi/admin also works because strapi is serving `/admin` URLs.

The best solution would be to stop using absolute URLs (which start with `/`) and use relative URLS `./`.
Alternatively please fix the build process to generate only URLs prefixed with `admin.url`.

**Comment by derrickmehaffy** [comment]
Can't reproduce on the latest version (v3.2.5).

Can you please follow our bug report template?

**Comment by cawoodm** [comment]
I've updated the original post. As you can see the admin UI is making calls to `/admin/init` and these URLs are clearly visible in the `main.****.chunk.js`:

![image](https://user-images.githubusercontent.com/498834/97408105-f3bc6480-18fb-11eb-95c6-4afb1ea85875.png)

**Comment by cawoodm** [comment]
How can I switch off the minification of the source code for main...chunk.js?

**Comment by cawoodm** [comment]
Config which works accidentally (because strapi answers to `/admin/init`:
```
events {
  worker_connections 1024;
}

http {
	upstream strapi {
	  server localhost:1337;
	}

  server {
    listen 8070;

    location / {
      proxy_pass http://strapi;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_pass_request_headers on;
    }
  }
} 
```
![image](https://user-images.githubusercontent.com/498834/97422757-8ebe3a00-190e-11eb-8d4d-9e149014ab92.png)

**Comment by cawoodm** [comment]
Config which doesn't work (because `/admin/init`) is called:
```
events {
  worker_connections 1024;
}

http {
	upstream strapi {
	  server localhost:1337;
	}

  server {
    listen 8070;

    location /cms/strapi/admin {
      proxy_pass http://strapi/cms/strapi/admin;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_pass_request_headers on;
    }
  }
}
```

![image](https://user-images.githubusercontent.com/498834/97422942-cfb64e80-190e-11eb-86ec-0a84cb22bc94.png)

**Comment by derrickmehaffy** [comment]
Digging into this again, thanks for the additional information!

**Comment by dalbitresb12** [comment]
Hi there @cawoodm.

Have you tried adding the `url` property as described [here](https://strapi.io/documentation/v3.x/concepts/configurations.html#server)? I believe that the `/admin` endpoint is part of the API. Correct me if I'm wrong (@derrickmehaffy), but I remember that `admin.url` is only used for the files needed for the admin panel to load (JS, CSS).

**Comment by cawoodm** [comment]
As I posted:
![image](https://user-images.githubusercontent.com/498834/97846107-d1f12200-1ced-11eb-8ae5-810e4365493d.png)
We have tried using local absolute `/` and fully qualified `https://...` URLs.

**Comment by dalbitresb12** [comment]
@cawoodm I was referring to the `url` property, not `admin.url`. Also, it is better if you use a fully qualified domain name. Example:

```javascript
module.exports = ({env}) => ({
  host: '0.0.0.0',
  port: env.int('PORT', 1337),
  url: 'https://strapi.local/api/', // I was referring to this one
  proxy: true, // This makes Strapi (and therefore the Koa instance) aware of the proxy.
  admin: {
    url: 'https://strapi.local/dashboard/',
    autoOpen: false
  }
});
```

I would also add the `proxy` property to make Strapi aware of the proxy. This is only needed if you need for example secure cookies (#7061) or another option that needs Koa to trust the proxy.

You will also need to proxy the endpoint assigned in the `url` property using Nginx. Example:

```
location /api/ {
  # Strapi doesn't do any routing for the API
  proxy_pass http://127.0.0.1:1337/;

  # More nginx options...
}

location /dashboard {
  # It does change the route for the admin panel
  proxy_pass http://127.0.0.1:1337/dashboard/;

  # More nginx options...
}
```

All the previous config is working fine:

![image](https://user-images.githubusercontent.com/7624090/97890565-af660580-1cfb-11eb-98db-2ab61fd9bf39.png)

![image](https://user-images.githubusercontent.com/7624090/97890756-ee945680-1cfb-11eb-8a74-fbc9f3d17a32.png)

Then I tried changing it to `/cms/strapi/admin` for the admin panel and `/cms/strapi/api` for the API. That's when I found a possible bug that maybe someone on the Strapi team could check since this may be somewhere in the Strapi internals.

Changing it to that endpoints make the admin panel completely inaccessible. The server returns 404 for the following paths (I don't know if I missed another one):

- `/admin`
- `/cms/strapi/admin`
- `/cms/strapi/api/cms/strapi/admin` (it showed like this in a previous test, when not using FQDN).

The API endpoint does work at the root (`/`) and also checking `/admin/init` returns the server info correctly, but all the other ones that could work for the admin panel return a 404.

Any help here @derrickmehaffy?

**Comment by dalbitresb12** [comment]
Nevermind, I've got it working with this configuration on `./config/server.js`:

```javascript
module.exports = ({ env }) => ({
  host: '0.0.0.0',
  port: env.int('PORT', 1337),
  url: '/cms/strapi/api', // Absolute path here
  admin: {
    url: 'https://strapi.local/cms/strapi/admin/', // FQDN here
    autoOpen: false,
  },
});
```

I'm not sure why it isn't working with a FQDN in the `url` property.

**Comment by dalbitresb12** [comment]
I also tried using just absolute paths, but it causes the server to do this:

![image](https://user-images.githubusercontent.com/7624090/97894721-d7a43300-1d00-11eb-9645-168e46681888.png)

It actually returns the admin panel using `http://localhost:1337/cms/strapi/api/cms/strapi/admin`, but it doesn't load because it is trying to use the API at `http://localhost:1337/cms/strapi/api/admin/init`. Probably using nginx you could fix the problem, but I don't think it's ideal.

**Comment by derrickmehaffy** [comment]
@cawoodm I am still having problems reproducing your issue directly.

Can you please give me your expected results?
- What domain/path do you want to accept API requests on? (ex: https://domain.com/cms/strapi/articles => json API response)
- What domain/path do you want to accept Admin UI requests on? (ex: https://domain.com/cms/strapi/admin => Admin Panel)
- If you are using GraphQL, what do you want your /graphql path on? (ex: https://domain.com/cms/strapi/graphql => GraphQL UI and endpoint for the query POST requests)

Generally speaking the the `server.js` **url** param should be absolute, and the **admin.url** is typically relative. If you can provide the 3 requirements I will construct an Nginx virtual host config file for you.

**Comment by cawoodm** [comment]
Our strapi **API** is working fine behind a proxy and we don't really want to change it. This ticket is only about the **admin panel**. Your suggestion to change the `url` property (which affects the API) makes no sense to me.

It really doesn't matter which URL or reverse proxy you take: you can view this behaviour directly on port :1337 without a reverse proxy:
![image](https://user-images.githubusercontent.com/498834/97961556-d8e26800-1db3-11eb-98f9-536830a07b0a.png)

This call to `/admin/init` is what is breaking everything. It works ONLY when strapi listens on `1337:/*`.

Adding `proxy: true` makes no difference. Adding `admin.url` as a fully qualified name makes no difference (it just calls `http://fullyqualifieddomain/admin/init`.

So my question is: WHY is the admin panel making calls OUTSIDE of `admin.url`? This is surely a bug.

**Comment by cawoodm** [comment]
How can I switch off the minification of the source code for main...chunk.js? If I could read the source I could debug these calls.

**Comment by derrickmehaffy** [comment]
So I tried to replicate your use-case under the information you provided. I used one of my testing domains, and was a little too lazy to setup HTTPS.

- Domain: http://strapi.guru (where I left a little note for you all)
- API URL: http://strapi.guru/cms/strapi/articles (added a test article)
- Admin URL: http://strapi.guru/cms/strapi/admin

Here is the Admin login so you can check it yourself:
```
test@test.com
Test1234!
```
**Note that I will delete this VPS in a few days**

Now onto the configs, which I have symlinked into the Strapi public folder so you can see them:
`./config/env/production/server.js`: http://strapi.guru/cms/strapi/server.js
`/etc/nginx/sites-enabled/strapi.conf`: http://strapi.guru/cms/strapi/nginx-strapi.conf

These examples were taken directly from: https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html using the "Sub-folder unified" examples.

Using the above configs yield the expected requests:
![image](https://user-images.githubusercontent.com/8593673/97996733-5baff680-1da5-11eb-9a49-cdc6d8a8945a.png)
![image](https://user-images.githubusercontent.com/8593673/97996825-76826b00-1da5-11eb-90d7-366bb0c90db9.png)
![image](https://user-images.githubusercontent.com/8593673/97996852-81d59680-1da5-11eb-89ee-dd87f5559166.png)

The only specifics required in my case are specifying the `NODE_ENV=production` during both my `yarn build` and my pm2 start command as I am using the `./config/env/production/server.js` and not the `./config/server.js`

![image](https://user-images.githubusercontent.com/8593673/97996986-b1849e80-1da5-11eb-838a-a880f753a377.png)

**Comment by derrickmehaffy** [comment]
@cawoodm the server.js `url` key (not the admin.url) will not work unless you are using a proxy, Strapi itself doesn't handle the route prefix **and expects your proxy application to strip it from the request** all it does it change a few variables both in the react admin and various plugins to give them the public URL to access the backend (3rd party auth, upload providers, ect)

**It does not modify the Koa-router** The requests you were making look like they are directly on the Strapi server and not through a proxy like Nginx

See this line in my nginx config:
```
    location /cms/strapi/ {
        rewrite ^/cms/strapi/(.*)$ /$1 break;   <---- Right here, I strip the /cms/strapi/ and convert it to /
        proxy_pass http://strapi;
```

And as you can see in the Strapi logs, it is indeed stripped:
![image](https://user-images.githubusercontent.com/8593673/97998306-299f9400-1da7-11eb-9f08-ebb844313432.png)

**Comment by cawoodm** [comment]
Guys, I think we are talking past each other. You are showing me it **can** work which I already believe. In fact, I've seen it working. The issue I am having is the Admin Panel generating URLs **outside** of the defined `admin.url` route. In your example the URLs are all generating URLs **inside** the `/cms/strapi` path. In your example you have `/cms/strapi/admin/init`:
![image](https://user-images.githubusercontent.com/498834/98000881-48c11480-1ded-11eb-8b8b-844513ada9eb.png)

In my case I have `/cms/strapi/` URLs mixed with `/admin/init` URLs:
![image](https://user-images.githubusercontent.com/498834/98000990-668e7980-1ded-11eb-9eb8-f70c7178b86b.png)

All I need is the admin panel to stick to `admin.url` and stop generating URLs outside of this path.

**Comment by derrickmehaffy** [comment]
> All I need is the admin panel to stick to admin.url and stop generating URLs outside of this path.

Then you need to use the normal `url` and not just the `admin.url` 

The `admin.url` is only **for the admin itself**, there are other calls that made from the admin to the backened that need to know where the actual backend is living and this is where the `url` key is used.

Short answer:
`admin.url`: User <=> Admin Panel
`url`: Admin Panel <=> Strapi backend

**Comment by dalbitresb12** [comment]
> In my case I have /cms/strapi/ URLs mixed with /admin/init URLs:

@cawoodm In the example you showed, you're not using a reverse proxy. You're connecting **directly** to the Strapi server (on `localhost:1337`). As @derrickmehaffy said, the reverse proxy (nginx, for example) needs to remove the route prefix and send it to the root on `localhost:1337`.

> Our strapi API is working fine behind a proxy and we don't really want to change it. This ticket is only about the admin panel. Your suggestion to change the url property (which affects the API) makes no sense to me.

You actually don't need to change the API that you say that works fine. It's just that you **need** to tell Strapi where will the API public endpoint will be serving requests when behind the reverse proxy so that it can embed it in your admin panel build. That's why you need to also set `url` (not `admin.url`) to the path on which your API will be receiving requests when it is behind the reverse proxy.

> Adding proxy: true makes no difference.

As I said, `proxy: true` will just make the Koa instance aware of the reverse proxy so that it trusts it. It was just a recommendation when using a reverse proxy. It will not help you with your issue since it won't change any routing.

**Comment by derrickmehaffy** [comment]
Yup it's exactly as you said @dalbitresb12 in the use-case of the `admin.url` it's really only for changing the url path of the admin itself (generally for renaming `/admin` to say `/dashboard` or `/admin-panel` or something).

It's extremely rare that you would only ever use `admin.url` without the `url` and more often then not you shouldn't need the `admin.url` at all.

**Comment by derrickmehaffy** [comment]
As we have had no new updates in a week, going to mark this as closed. It appears to be working as intended.

**Comment by nba9898** [comment]
hi guys. i'm new to strapi. i installed it on a windows server 2016. strapi is running  properly when i load 127.0.0.1:1337 on my server. I applied a reverse proxy on my server using the iis url rewrite. Accessing the strapi through the domain works. i can login and all. but when i click on the users tab, an error appears saying "an error occured during models config fetch" but when i clicked users on 127.0.0.1:1337, it is displaying the users list without errors. using the domain i can add users but when it tries to refresh the users list, the same error appears. i'm uisng strapi version 3.3.4 (node v14.15.1). is there a way to fix it so I can view the users list through the domain?

**Comment by derrickmehaffy** [comment]
> I applied a reverse proxy on my server using the iis url rewrite

We strongly suggest avoiding IIS for proxying. I would recommend Nginx or HAProxy.

**Comment by cawoodm** [comment]
Sorry, I was unable to look into your suggestions for some time. I think I can see what the problem is - Strapi always assumes that the `admin.url` is under the `url`. This means that if you want tot run the API and the Admin as siblings (i.e. `/cms/strapi/api` and `/cms/strapi/admin`) it will never work or will never work behind and in front of of proxy.

As you can see when I set only `admin.url` to `/cms/strapi/admin` (`url` left empty) strapi starts up with:
```
Welcome back!
To manage your project �, go to the administration panel at:
http://localhost:1337/cms/strapi/admin

To access the server ⚡️, go to:
http://localhost:1337
```
Which is incorrect.

If I now set `url: '/cms/strapi/api'` it starts with:
```
Welcome back!
To manage your project �, go to the administration panel at:
http://localhost:1337/cms/strapi/api/cms/strapi/admin

To access the server ⚡️, go to:
http://localhost:1337/cms/strapi/api
```
Which is more than incorrect.

I think Strapi is making a fundamental design mistake in assuming that it must know how the final URLs are going to look. A good web application works behind and infront of a reverse proxy without needing to modify response bodies (HTML) because it uses relative URLs. If you say the admin panel needs to know where the API is that is fine but it should be something relative and not something added together.

**Comment by cawoodm** [comment]
Can someone explain why Strapi will not start with this configuration?
```
  proxy: true,
  url: '/cms/strapi',
  admin: {
    url: 'admin',
```
It looks fine on the backend:
```
Welcome back!
To manage your project �, go to the administration panel at:
http://localhost:1337/cms/strapi/admin

To access the server ⚡️, go to:
http://localhost:1337/cms/strapi
```

But the Strapi Admin Panel just shows the loading icon but never starts (no JS errors or network errors):
![image](https://user-images.githubusercontent.com/498834/101494608-dd2c1300-3967-11eb-83d8-c9baa15c888d.png)

**Comment by derrickmehaffy** [comment]
> Can someone explain why Strapi will not start with this configuration?
> ```
>   proxy: true,
>   url: '/cms/strapi',
>   admin: {
>     url: 'admin',
> ```
> It looks fine on the backend:
> ```
> Welcome back!
> To manage your project �, go to the administration panel at:
> http://localhost:1337/cms/strapi/admin
> 
> To access the server ⚡️, go to:
> http://localhost:1337/cms/strapi
> ```
> 
> But the Strapi Admin Panel just shows the loading icon but never starts (no JS errors or network errors):
> ![image](https://user-images.githubusercontent.com/498834/101494608-dd2c1300-3967-11eb-83d8-c9baa15c888d.png)
> 
> 
> 

You need a proxy application in front of Strapi as that url key doesn't modify the Koa router (so Strapi's backend is still expecting the requests to be made on the root, not the prefix)

Also generally the URL should be a fully qualified domain path, the relative option generally won't help.

**Comment by nba9898** [comment]
i did the change as requested. the admin page loads but its stuck on the loading icon. when i check the server i'm getting a 405 error for POST /cms/strapi/admin/renew-token

what should i do to fix this?

**Comment by cawoodm** [comment]
> You need a proxy application in front of Strapi as that url key doesn't modify the Koa router (so Strapi's backend is still expecting the requests to be made on the root, not the prefix)
> 
> Also generally the URL should be a fully qualified domain path, the relative option generally won't help.
Not, a reverse proxy does not help. I wonder if we mean the same thing by "reverse proxy".
![image](https://user-images.githubusercontent.com/498834/101595993-9afce300-39f4-11eb-97ad-d53ee80b0c3d.png)

I've tried with every Nginx configuration you've posted and several of my own. Your config:
```
location /cms/strapi/ {
  rewrite ^/cms/strapi/(.*)$ /$1 break;
  proxy_pass http://127.0.0.1:1337;
```
with server.js
```
  url: '/cms/strapi',
  admin: {
    url: 'http://localhost:8080/cms/strapi/admin',
```
results in 404 hits to http://localhost:8080/cms/strapi/admin/ though /cms/strapi/ works fine.
![image](https://user-images.githubusercontent.com/498834/101596360-34c49000-39f5-11eb-9812-335bd1b1baa8.png)

My nginx configuration with the same server.js results in no 404 and no admin pane though again /cms/strapi works fine:
```
location /cms/strapi/ {
  proxy_pass http://127.0.0.1:1337;
```
![image](https://user-images.githubusercontent.com/498834/101596448-5d4c8a00-39f5-11eb-94f3-3e239dc319d1.png)

Again, maybe strapi CAN work behind a reverse proxy but it doesn't seem to understand what a reverse proxy is for. A reverse proxy rewrites URL paths and the application behind that proxy should NOT have to know what those external paths are.

**Comment by cawoodm** [comment]
/cms/strapi/admin/
![image](https://user-images.githubusercontent.com/498834/101596637-c0d6b780-39f5-11eb-823e-f20b7456939e.png)

/cms/strapi/admin/init:
![image](https://user-images.githubusercontent.com/498834/101596679-d0ee9700-39f5-11eb-89ff-454208402b86.png)

**Comment by cawoodm** [comment]
Looks like /cms/strapi/admin/init is returning HTML instead of JSON which could explain the stalling.

**Comment by nba9898** [comment]
My apologies. i have a new problem. i installed nginx and its running fine on the localhost. i set it to port 8180 (i also set the nginx server to the domain.) the reason i set to port 8180 is because I also have iis running (Post 80) because i have other projects running on the same machine and i don't want to disrupt that. when i load the domain remotely, its somehow loading the iis server instead of the nginx server. is there a way to specify to go directly to nginx instead of iis?

**Comment by cohrs** [comment]
Having the same exact results as @cawoodm 

I want to host this in a subfolder and have other applications running on root domain. Setting the URL to something different and the 'admin/init' returns a 404. setting the admin.url to something different returns HTML, not the config object expected.

**Comment by derrickmehaffy** [comment]
@cohrs your issue is this one: https://github.com/strapi/strapi/issues/8616

@nba9898 it would appear your IIS is accepting requests on that port. Without understanding the structure of your server. Best to take that discussion over to the forum: https://forum.strapi.io/

**Comment by tafm** [comment]
I the same problem with reverse proxy to /admin/* and fixed it by adding also /content-manager/* pointing to strapi backend

**Comment by M4TH76** [comment]
As @tafm suggested I added all folders to the proxy (next.config.js)
`module.exports = {
    async rewrites() {
        return [
            {
                source: '/uploads/:path*',
                destination: 'http://localhost:1337/uploads/:path*',
            },
            {
                source: '/admin/:path*',
                destination: 'http://localhost:1337/admin/:path*',
            },
            {
                source: '/content-manager/:path*',
                destination: 'http://localhost:1337/content-manager/:path*',
            },
            {
                source: '/i18n/:path*',
                destination: 'http://localhost:1337/i18n/:path*',
            },
            {
                source: '/api/:path*',
                destination: 'http://localhost:1337/:path*',
            }
        ]
    }
}`

**Comment by JensLincke** [comment]
thanks, this fixed it for me... and then I figured that there should be another way... and it turned out I forgot to `yarn build`. Maybe this should be mentioned in https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/nginx-proxy.html#configuration. Now it works with simply proxying api and amin

**Comment by M4TH76** [comment]
Yes I did a `yarn build` and everything worked!

config/server.js:
```module.exports = ({ env }) => ({
	host: env('HOST', '0.0.0.0'),
	port: env.int('PORT', 1337),
	url: "https://mysite.com/cms",
	proxy:true,
	admin: {
		auth: {
			secret: env('ADMIN_JWT_SECRET', 'sseeecreeettt'),
		},
	},
});
```
Proxy settings for Next.js (next.config.js):
```
module.exports = {
    async rewrites() {
        return [
           
            {
                source: '/uploads/:path*',
                destination: 'http://localhost:1337/uploads/:path*',
            },
            {
                source: '/cms/:path*',
                destination: 'http://localhost:1337/:path*',
            },            
        ]
    }
}
```

**Comment by fatehMohamed14** [comment]
> I had the same problem with reverse proxy to /admin/* and fixed it by adding also /content-manager/* pointing to strapi backend

Hello, can you share your nginx config

**Comment by bvoigtlaender** [comment]
Just a little heads up for anyone running into this issue: if you change the url in the server or admin config you have to rebuild the UI with `npm run build` afterwards.

**Comment by tmonk79** [comment]
facing the same issue in dockerized strapi, I am using the subfolder split as explained in this doc;

https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/optional-software/nginx-proxy.html#nginx-virtual-host

`domain: xyz.co.in` -> servs frontend
`admin: xyz.co.in/cms/admin` -> strapi admin

I have one server block in the default nginx config as described in the link, `/cms/` is proxy passed to backend `strapi` server.

admin pane loads up on `xyz.co.in/cms`
when I click open admin, I see an error and a few failed requests namely, `http://localhost:3337/admin/init`

The admin/init url is still pointing to `localhost`, it should be pointing to the url as per the config

<img width="1581" alt="Screenshot 2022-06-14 at 10 57 23 AM" src="https://user-images.githubusercontent.com/99247529/173500044-e39deda6-fef9-47a1-a1cf-7c26be705f2a.png">

If I run `yarn build` from the strapi container it starts working! I am running in `dev` mode.

**Comment by cawoodm** [comment]
> Yes you need to build the admin when the URL is changed and you need to change the URL to proxy.

Like I said: Strapi doesn't work behind a reverse proxy. A good web application makes no assumptions (hardcoded or otherwise) about it's path. It may be served behind one or more different paths.

**Comment by derrickmehaffy** [comment]
Thanks for your opinion, strapi does work behind a reverse proxy, as the admin panel is CSR it needs an absolute url at build time as you can serve the admin from any other host (not always with/by the strapi backend)

I'm locking this issue as GH issues are not the place for this type of discussion.
