### ISSUE TITLE
WYSIWYG control buttons get scroll bars on smaller screens

### ISSUE THREAD

**Issue by JuliaSterkeberg** [strapi/strapi#8489]
### Describe the bug

If you want to edit content on a tablet or small screen , the markdown editor controls get scroll bars so you can't press all buttons without scrolling, like this:
![Screenshot 2020-10-27 at 11 37 07](https://user-images.githubusercontent.com/65682734/97290860-6e787780-1849-11eb-8b51-c4e37c324ffa.png)

### Steps to reproduce the behavior

1. Use the WYSIWYG editor somewhere
2. Make your screen smaller

### Expected behavior

You shouldn't have to scroll to use the buttons on smaller screens, but they should appear next or underneath each other, like this:
![Screenshot 2020-10-27 at 11 37 40](https://user-images.githubusercontent.com/65682734/97291059-b1d2e600-1849-11eb-8dbe-1a6ecfd0f97b.png)

### Code snippets

.controlsContainer {
flex-wrap: wrap;
}

### System

Node.js version: 12.18.2
NPM version: 6.14.5
Strapi version: 3.1.1
Database: mysql: "^2.18.1
Operating system: Open Suse LEAP 15 and MacOS 10.15.6

**Comment by soupette** [comment]
This one is fixed with the current v4.

**Comment by derrickmehaffy** [comment]
Fixed in v4, closing
