### ISSUE TITLE
miss important things on strapi-provider-email-mailgun documentation

### ISSUE THREAD

**Issue by pedropcruz** [strapi/strapi#8492]
### Describe the bug

If you are using EU servers, you need to specify the host. And it's not mentioned in the documentation.

### Steps to reproduce the behavior

only need to add host as a property on `providerOptions`

### Expected behavior

Users can send and receive emails using mailgun, and it's not working correctly with the info from the documentation.

### Code snippets

```
module.exports = ({ env }) => ({
  // ...
  email: {
    provider: 'mailgun',
    providerOptions: {
      apiKey: env('MAILGUN_API_KEY'),
      domain: env('MAILGUN_DOMAIN'), //Required if you have an account with multiple domains
      host: env('MAILGUN_HOST') // we have only 2 options here. api.mailgun.net for US servers, api.eu.mailgun.net for EU Servers.
    },
    settings: {
      defaultFrom: 'myemail@protonmail.com',
      defaultReplyTo: 'myemail@protonmail.com',
    },
  },
  // ...
});
```

### System

- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version:  3.2.5
- Database: MySQL
- Operating system: using WSL

**Comment by derrickmehaffy** [comment]
fixed in v4, see https://github.com/strapi/strapi/tree/master/packages/providers/email-mailgun
