### ISSUE TITLE
Accept info parameters when uploading file through GraphQL

### ISSUE THREAD

**Issue by darron1217** [strapi/strapi#8493]
## Feature request
I found that there's no way to put file info (name, alternativeText, caption) when uploading file.
Yes we can do it with `updateFileInfo` mutation.
But then, we should send request twice.

### Please describe your feature request
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary
Accept info fields when uploading file through GraphQL

### Why is it needed?
To send http request lesser.

### Suggested solution(s)
Add info field on schema and pass it to file formatting method.

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/pull/8494

**Comment by derrickmehaffy** [comment]
Can you please provide some more information, not sure I understand the feature request

**Comment by darron1217** [comment]
Info field means below.
![Strapi_-_Content_Manager](https://user-images.githubusercontent.com/8064923/97376589-1604b100-1901-11eb-81e7-411f7272fd1b.png)

Currently `upload` mutation accept parameters below.
![Playground_-_http___localhost_1337_graphql](https://user-images.githubusercontent.com/8064923/97376656-464c4f80-1901-11eb-999f-2ed0407d28b4.png)

Currently `updateFileInfo` mutation accept parameters below.
![Playground_-_http___localhost_1337_graphql](https://user-images.githubusercontent.com/8064923/97376701-6976ff00-1901-11eb-9e59-afb58e87fb25.png)

I want to make `upload` mutation to accept `info : FileInfoInput` parameter (which is already exists in `updateFileInfo` mutation)

**Comment by derrickmehaffy** [comment]
Ahhh okay thank, that makes sense.
