### ISSUE TITLE
[UI] Missing scroll indicator

### ISSUE THREAD

**Issue by richardhj** [strapi/strapi#8495]
## Bug report

My Strapi installation was missing some collections types that I created before. I was looking through different issues including #2213 and spent some time figuring out the problem.

Turns out, the collection types were present all the time but not shown because the list is limited to 5 collections with no indicator to scroll.

Same problem for the list in the Collection Creator plugin.

## Proposed solution

Do not limit the list in height.

![2020-10-27 15 46 16](https://user-images.githubusercontent.com/1284725/97318095-caec8e80-186b-11eb-8389-3bc4e5a97e5f.gif)

**Comment by maevalienard** [comment]
Hello! Thanks for mentioning that bug :) 

Can I ask which browser you're using please?

**Comment by richardhj** [comment]
I am on Firefox/Mac. Other browsers like Safari do not show the scroll bar as well.
If one removes the height limit and make the sidebar scrollable as a whole, it would be an improvement IMHO :)

**Comment by maevalienard** [comment]
Good to know. I'll check with the team if we can make that scrollbar visible on every browser. That would be a great first step I guess. We were also thinking of having an unclear separation to indicate you'd have to scroll? What do you think?

**Comment by richardhj** [comment]
I guess there are two points that make the current navigation element problematic:

1. The box with the navigation items lacks outer constraints, and such the element is not seen as a box. But in fact, the box is limited in height (max-height: 180px).
2. The box does not indicate there is more content.

Possible solutions for 1:

- Giving the box outer constraints, like a border.
- Not limiting the box in height. This results in the sidebar being scrollable as a whole. Then, the height of the browser window is the outer bounding constraint indicating to scroll :)

Possible solution for 2 (only necessary when not removing max-height):

- To indicate that there are more items, it is possible to show a shadow gradient overlay (that hides part of the list), 
- or showing only 4 and a half items, which is a precise indicator scrolling :)

Sorry for this long description. I am aware that this issue is low-priority and this issue only affects new users, but in fact I was affected ;-)

**Comment by aksdevac** [comment]
> I am on Firefox/Mac. Other browsers like Safari do not show the scroll bar as well.
> If one removes the height limit and make the sidebar scrollable as a whole, it would be an improvement IMHO :)

It is visible on Safari Version 14.0 on Mac OS 10.15.7, not checked on Firefox.

**Comment by richardhj** [comment]
Ok, looks like the hidden scrollbar is more specific to Firefox.

**Comment by maevalienard** [comment]
> It is visible on Safari Version 14.0 on Mac OS 10.15.7, not checked on Firefox.

Thanks for that information! It's good to know :)

> Sorry for this long description. I am aware that this issue is low-priority and this issue only affects new users, but in fact I was affected ;-)

Thanks for explaining everything. This kind of "long" description is really important to us to properly understand your pain points and find a solution :) I totally agree with your solutions for the second point. Sounds interesting to me to follow that path. 
For the first one, it might be not currently possible. In terms of scalability, if we don't make any subsections, that'd make it a very huge scrollbar and I'm not sure that'd be better in terms of readability. Also, I'm not sure about making options to determine how many entries you want to see. At least for now because we planned to update our product design and will come with a new solution that might patch that issue for a short time. What I can propose you, is working on finding a good solution as soon as we can to solve your issue and to improve your (and other users) experience. What I can think of for now and is planned on our roadmap is to give more customizable options to users to personalize their own menu :)

I hope that answers a bit your questions. Let's work on that :D

**Comment by ImaCrea** [comment]
Hi there, was affected by that issue too on FF 87 mac 10.14.5.
I thought some items were missing :/ 

I won't suggest any solution. You're in better place than me for that, I don't know your context and I trust you'll find something elegant. ;)

++

**Comment by maevalienard** [comment]
> Hi there, was affected by that issue too on FF 87 mac 10.14.5.
> I thought some items were missing :/
> 
> I won't suggest any solution. You're in better place than me for that, I don't know your context and I trust you'll find something elegant. ;)
> 
> ++

Hello! Which Strapi version do you use? :)

**Comment by ImaCrea** [comment]
> > Hi there, was affected by that issue too on FF 87 mac 10.14.5.
> > I thought some items were missing :/
> > I won't suggest any solution. You're in better place than me for that, I don't know your context and I trust you'll find something elegant. ;)
> > ++
> 
> Hello! Which Strapi version do you use? :)

3.5.3

**Comment by FV-Valraiso** [comment]
Hi, I'm not having the original problem.
But I agree Richardhj on this point :
> I guess there are two points that make the current navigation element problematic:
> The box with the navigation items lacks outer constraints, and such the element is not seen as a box. But in fact, the box is limited in height (max-height: 180px).
> The box does not indicate there is more content.

I think you shouldn't limit the max height of the collection types container in the left bar menu :
![Capture d’écran 2021-04-30 à 15 17 28](https://user-images.githubusercontent.com/1353509/116701211-ecb80100-a9c7-11eb-9fbc-8e38f6b83819.jpg)
You already have a global scrollbar on the left bar menu that makes the job when your browser window is not very high.

It also works with collection types menu when you are in the Content-Types Builder, you already have a scrollbar for the overall white edition container :
![Capture d’écran 2021-04-30 à 15 24 16](https://user-images.githubusercontent.com/1353509/116701489-3dc7f500-a9c8-11eb-8fd8-1ffda8cb8a5a.jpg)

**Comment by maevalienard** [comment]
We took your comments into consideration and this problem will be patched when our new design system/branding will be out. I know how inconvenient it is and I'm sorry for that :(

**Comment by FV-Valraiso** [comment]
> We took your comments into consideration and this problem will be patched when our new design system/branding will be out. I know how inconvenient it is and I'm sorry for that :(

Great, thanks :-)

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
