### ISSUE TITLE
[UI] Button mutation 

### ISSUE THREAD

**Issue by richardhj** [strapi/strapi#8496]
### Describe the bug

The button which is used to arrange fields mutates when hovering. I often delete the field instead of editing 

### Proposed solution

Giving the two buttons/actions two distinct areas.

![2020-10-27 15 49 39](https://user-images.githubusercontent.com/1284725/97318750-7990cf00-186c-11eb-9db7-d20bd1ebc8da.gif)

**Comment by maevalienard** [comment]
Oh wow, thanks for mentioning this! You're totally right, let's make some changes to improve that :)

**Comment by derrickmehaffy** [comment]
Should be fixed in v4
