### ISSUE TITLE
Try to infinite scroll pagination

### ISSUE THREAD

**Issue by GabrielLiade** [strapi/strapi#8499]
Hi, everyone, I'm trying to do an infinite scroll (at least a load more) function in my app using graphql and Apollo nevertheless the Apollo documentation is around Offset-based pagination method or Cursor-based pagination but Strapi allowed us to use only start and limit parameters, 

How can I do a  an infinite scroll or a load more function with start and limit parameters ? 

Is there a way to have access to Offset, cursor or other pagination arguments ? 

### Steps to reproduce the behavior

launch a Strapi project and try to implement infinite scroll 

### Expected behavior

implement infinite scroll 

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2.5
- Database: pg
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
