### ISSUE TITLE
Migration Token Prevents Proper Auth Flow on Strapi Admin 

### ISSUE THREAD

**Issue by nabeelvalley** [strapi/strapi#8503]
### Describe the bug

After following the migration guide [here](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html#_2-define-the-admin-jwt-token) my admin login seems to fail as follows:

1. Create new admin/log in
2. Redirected back to login page, authentication unsuccessful

### Steps to reproduce the behavior

1. Delete all admins from DB
2. Replace the token in the `server.js` as shown in the migration guide
3. Start Strapi in develop
4. Create new admin
5. After admin creation user is redirected to the main login screen again

> Note that the login still works as expected via the GraphQL endpoint using the token from `auth/local`, just not from the admin panel

### Expected behavior

Login works correctly

### Screenshots

None

### Code snippets

The initial `server.js` file looks like so:

```js
module.exports = ({ env }) => ({
  host: env("STRAPI_HOST", "localhost"),
  port: env.int("STRAPI_PORT", 1337),
  admin: {
    auth: {
      secret: env(
        "STRAPI_ADMIN_JWT_SECRET", "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"
      ),
    },
  },
})
```

After step `2` it looks more like this

```js
module.exports = ({ env }) => ({
  host: env("STRAPI_HOST", "localhost"),
  port: env.int("STRAPI_PORT", 1337),
  admin: {
    auth: {
      secret: env(
        "STRAPI_ADMIN_JWT_SECRET", "<BASE64 AS GENERATED>"
      ),
    },
  },
})
```

### System

- Node.js version:  12.18.2
- NPM version: 6.14.6
- Strapi version: 3.2.4
- Database: MongoDB
- Operating system: Windows

### Additional context

None

**Comment by derrickmehaffy** [comment]
Did you rebuild the admin panel with `npm run build` or `yarn build`?

**Comment by MattieBelt** [comment]
Hey @nabeelvalley, May I ask from which version you upgraded and to which one? 
Your two code snippets don't differ that much, only the env fallback string. Weren't you already on a version > `v3.1.0`?

**Comment by nabeelvalley** [comment]
@derrickmehaffy I did rebuild, I used `yarn build --clean` if I remember correctly, but between switching back from the Base64 token and the old token (when it started working again) I didn't do another build

@MattieBelt I'm not totally sure which migration I added the env fallbacks in, but it was prior to this migration. During this migration, I was going from 3.0.0 to 3.2.4. I had previously been running on 3.0.0 with the env fallbacks

**Comment by nabeelvalley** [comment]
@derrickmehaffy I will try to attempt a reproduction if I have some time

**Comment by derrickmehaffy** [comment]
Make sure your `ADMIN_JWT_SECRET` and your `JWT_SECRET` are not the same token.

**Comment by nabeelvalley** [comment]
@derrickmehaffy I am getting the error if they're different tokens, if they're the same then everything seems to work fine

**Comment by nabeelvalley** [comment]
@derrickmehaffy thanks so much, that fixed the issue - is it something that's in the docs or does it need to be added?

**Comment by derrickmehaffy** [comment]
It needs to be added or we need to add in check on this.

**Comment by nabeelvalley** [comment]
I also noticed that if using a custom token as per [this doc](https://strapi.io/documentation/v3.x/guides/api-token.html#api-tokens), the overall `permissions.js` file needs to be updated to match the new one [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js) as (from my testing) the new admin login is impacted if this is not done

Would be a useful note in the migration guide as well (not sure which version added the admin roles functionality)

**Comment by derrickmehaffy** [comment]
@nabeelvalley on all of our migration guides we put a warning at the top to clarify that if you are using extensions you need to sync your version with ours: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.2.3-to-3.2.4.html

![image](https://user-images.githubusercontent.com/8593673/97711463-5b002300-1a7a-11eb-8130-9fc19419e836.png)
