### ISSUE TITLE
Allow option to set publicationState in graphql mutation

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#8507]
### Describe the bug

By default , when you create a record using the Admin Panel, the publicationState is set to **Draft**
On the other hand, when you create a record using the graphql mutation, the publicationState is set to **Published**

_**An inconsistency here**_

Is there a way to set or defaulted publicationState = Draft in a graphql mutation or better the ability to set the publicationState in the graphql mutation

### Steps to reproduce the behavior

1. Create a record in Admin Panel and check the State field. Value is defaulted to Draft
2. Submit a record using Graphql . Value is defaulted to Published

### Expected behavior

Creating a record either via the Admin Panel or Graphql should have the same initial publicationState = Draft.
Also we need the ability to set or update the publicationState in Graphql mutation

### System

- Node.js version: v12.17.0
- NPM version: 6.14.4
- Strapi version: 3.2.5
- Database: PostgreSQL v13.0
- Operating system: Ubuntu 20.04 (via vagrant vbox, host is windows 10 Pro)

**Comment by derrickmehaffy** [comment]
@JabStrapi / @sam-pires 

@laportem thank you for the issue, I'm marking it as a feature request just because the current implementation is the planned one, but we did bring this up internally and decided not to add it. I do think this is a good idea and have poked our product team to share the feedback with.

**Comment by ssuvorov** [comment]
not sure, but I'm able to create a draft with graphql by modifying a `create` service

```js
// api/article/services/article.js
async create(ctx) {
    async create(ctx) {
    let user_id;
    try {
      const authData = await strapi.plugins[
        'users-permissions'
        ].services.jwt.getToken(ctx);
      user_id = authData.id;
    } catch (err) {
      console.log(err.stack);
      ctx.status = 401;
      return {};
    }

    try {
      const article = await strapi.query('article').create({
        title: 'title',
        content: ctx.request.body.content,
        status: null,
        published_at: null,
        user: user_id
      })

      ctx.created(article)
    } catch (err) {
      console.log(err.stack);
      ctx.status = 400;
      return {};
    }
  }
};
```

**Comment by iksent** [comment]
Temporary solution: https://stackoverflow.com/a/65037642/6909322

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed

You just need to set published_at to null to create a draft.
