### ISSUE TITLE
Uploaded files no longer have sha256 field

### ISSUE THREAD

**Issue by bmollot-indeed** [strapi/strapi#8508]
### Describe the bug

In recent versions of Strapi uploaded Files do not have a query-able sha256 field derived from their content.
This field seems to have been removed in https://github.com/strapi/strapi/commit/02d042769f49cb759f1d43e4eedd08a51d71c298.

### Steps to reproduce the behavior

1. Use a version of Strapi since the above commit was merged
2. Upload a file via the File Upload plugin
3. Query that file's sha256 field

### Expected behavior

I expect the sha256 field to exist and contain the sha256 hash of the uploaded file's contents.

### System

- Node.js version: v12
- NPM version: 6.14.8
- Strapi version: 3.2.5 (exists for every version >=beta.20)
- Database: Mongo
- Operating system: Linux

### Additional context

The field was removed in a Beta version, but was quite useful to me. The commit message suggests that it was removed because the value stored was not actually a sha256 hash (it was actually a "niceHash" modified sha256). I don't specifically care that this "niceHash" be restored, but would like a content-hash of some kind to be available for files.

**Comment by derrickmehaffy** [comment]
Thank you @bmollot-indeed I've set it as a feature request to re-add.

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/developer-experience/p/add-sha256-field-to-media-library-uploads
