### ISSUE TITLE
Using components from the strapi-plugin-content-manager

### ISSUE THREAD

**Issue by nicolashmln** [strapi/strapi#8527]
### Describe the bug

I'd like to customize the homepage of strapi and show a list of articles. Rather than create the list my self I looked at how the content types are made and I found the `CustomTable` component. I've created the file `./admin/src/containers/HomePage/index.js` and I tried to import the component like that:

```js
import CustomTable from 'strapi-plugin-content-manager/admin/src/components/CustomTable';
```

I launched the `npm run develop` command and I've got the error:

```
 ERROR  Failed to compile with 1 errors 

 error  in ./node_modules/strapi-plugin-content-manager/admin/src/components/CustomTable/index.js

Module parse failed: Unexpected token (37:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const content =
|     data.length === 0 ? (
>       <TableEmpty>
|         <td colSpan={colSpanLength}>
|           <FormattedMessage
```

The admin pages seems to work fine, is there something I do wrong or it requires a specific webpack build? 

Thank you

### System

- Node.js version: 12
- NPM version: 6.14.4
- Strapi version: 3.2.5
- Operating system: macOs

**Comment by dzcpy** [comment]
Also experinced this issue. Has anyone found the solution?

**Comment by dzcpy** [comment]
I've found a solution for `v4`
// ./src/admin/webpack.config.js
```js
const { resolve } = require('path')

module.exports = (config, webpack) => {
  const rule = config.module.rules.find(rule => /babel-loader/.test(rule?.use?.loader))
  if (rule && rule.include) {
    rule.include.push(resolve('./node_modules/@strapi/admin/admin/src'));
  }
  return config;
};

```
