### ISSUE TITLE
Permissions reset for all SINGLE TYPES

### ISSUE THREAD

**Issue by jalal246** [strapi/strapi#8528]
### Describe the bug

It acts so wired, reset permissions for all `SINGLE TYPES` which causes an error each time I run `build`. (i have no clue why this happens)

```
 ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 403



  Error: Request failed with status code 403

  - createError.js:16 createError
    [ronyar.net]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [ronyar.net]/[axios]/lib/core/settle.js:18:12

  - http.js:202 IncomingMessage.handleStreamEnd
    [ronyar.net]/[axios]/lib/adapters/http.js:202:11

  - task_queues.js:84 processTicksAndRejections
    internal/process/task_queues.js:84:21
```

### Screenshots
It's always unmarked even when I check the boxes to `find`

![image](https://user-images.githubusercontent.com/19228730/97742424-ee723c00-1aec-11eb-87ba-e81f5116413b.png)

### System

- Node.js version: v12.18.4
- NPM version: v7.0.0
- Strapi version: ^3.2.4
- Database: `mongodb` using `"strapi-connector-mongoose": "^3.2.4"` 
- Operating system: Windows 10

### Additional context

I just ran into a similar issue accessing `SINGLE TYPES` and got  `you are not allowed to see this document`. I logged out, then in and it worked!

**Comment by derrickmehaffy** [comment]
Currently the gatsby-source-strapi repo is not maintained, but I believe this issue to be directly related to it. Can you please open the issue there? https://github.com/strapi/gatsby-source-strapi

I'm going to mark this as closed for now, but please feel free to respond back if you think the issue is unrelated.

**Comment by jalal246** [comment]
@derrickmehaffy  But that doesn't explain why the permission disappearing from Strapi which is related to reading form DB rather than fetching data.

**Comment by derrickmehaffy** [comment]
If possible I'd like to take a look but can we move this over to the forums (as I don't think it's directly a bug with Strapi itself as it seems more environmental)

Also just as a side point, your version of npm has been known to cause issues and it's shipped with Node v15 which we don't support. Node 10, 12, and 14 should all come with npm 6.

Once we can reproduce the issue reliably we will know it's a bug with Strapi, but our engineering team are trying to limit the scope of GitHub issues strictly to bugs that deal with the Strapi code base and require changes. If we can't confirm its a code bug but may also be an environmental issue we want to direct people to the forums for that.
