### ISSUE TITLE
Use npx in package's npm scripts

### ISSUE THREAD

**Issue by lucaperret** [strapi/strapi#853]
A lot of binaries are call with their full path in the package.json ([example](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/package.json#L11)).

In case you have the same dependency in the package itself and in the `strapi-helper-plugin`: it may be relevant if the package version of the called binary is different.
It's not the case in most of places, is there another reason of calling the binaries with their full path ?

It can be less verbose by using the new npm package runner called `npx`...
[npm's blog post about npx](http://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner).

**Comment by mnlbox** [comment]
Maybe Related: #742

**Comment by lucaperret** [comment]
ok, so mine is duplicated.
