### ISSUE TITLE
Media library throws error after directly deleting content types without removing their media files

### ISSUE THREAD

**Issue by lodisy** [strapi/strapi#8530]
## Bug report

This seems not fixed for months. I used to get the same error a long time ago.

Have to re-create the deleted content type with the same name, and then all previous images would show up. Just like the issue stated [here](https://stackoverflow.com/questions/60546776/how-to-fix-the-error-the-target-polymorphic-type-components-compnent-name-is-n)

### Steps to reproduce the behavior

1. First mistype the product content type as proudct (unnoticed)
2. Add some "proudcts" with images
3. Delete the "proudct" content type, even in the data base
4. Go to media library, error showed up
5. Re-create the content type 'proudct' with images (same as previous) field
6. Go to media library, then able to delete all previous images
7. Delete the "proudct" content type

### Expected behavior

No error when go to media library / erasing all its data when delete a content type

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.4.0
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: NoSQL
- Operating system: macOS

**Comment by lodisy** [comment]
It's duplicated, also seen in [https://github.com/strapi/strapi/issues/6973](#6973)

**Comment by derrickmehaffy** [comment]
closing as duplicate, issue mentioned above
