### ISSUE TITLE
DigitalOcean 

### ISSUE THREAD

**Issue by anas-aw** [strapi/strapi#8532]
when i access to vps DigitalOcean ssh 
i dont see any files 
how to access to strapi files 
and how to access to PostgreSQL 
i use DigitalOcean One-click

and if i not change to production mode what is the  different

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
