### ISSUE TITLE
Adding a relation of a collection type with itself using the same field name

### ISSUE THREAD

**Issue by cgonzalezsan** [strapi/strapi#8540]
## Feature request

Adding a relation within a collection type with itself using the same field name

### Please describe your feature request

I’m trying to set up a relation of a collection type (`Articles`) with the same collection type (`Articles`). I would like to have the same field name (` Related Articles`) for such relation but if I use the same name on both ends of the relation, it will say that “This value is already used.“. See attached screenshot.

Please note that I need to have the same field on both sides of the relation, not different ones. Also, the relation needs to be visible on sides, so `has many` won't work either.

### Why is it needed?
I need to add a new relation field` Related Articles` within the `Articles` collection type with itself, so as a user I can link one article with `N articles`, and that relation is available on all articles (sides of the relation) with the same field name 

![](https://user-images.githubusercontent.com/6850051/97604430-c5c74500-1a0d-11eb-9456-2e9ef2918c6b.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by cgonzalezsan** [comment]
This is a feature request as it's not possible to add the above relation unless I'm missing something?
