### ISSUE TITLE
Add folderName option for cloudinary and awss3 providers

### ISSUE THREAD

**Issue by jhenriquevissotto** [strapi/strapi#8541]
These two libs are very good:
https://www.npmjs.com/package/strapi-provider-upload-cloudinary
https://www.npmjs.com/package/strapi-provider-upload-aws-s3

But don't offers the option for upload the assets for a specific folder.

This becomes really complicated when you want download all assets from root directory, specially in Cloudinary.

In the other hands, is too much easy download a folder with all assets inside.

------------------------------------------------
#### 1) Cloudinary

```javascript
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: 'cloudinary',
    providerOptions: {
      cloud_name: env('CLOUDINARY_NAME'),
      folder_name: env('CLOUDINARY_FOLDER'), // <---- new option
      api_key: env('CLOUDINARY_KEY'),
      api_secret: env('CLOUDINARY_SECRET'),
    },
  },
  // ...
});

```

#### 2) AWS

```javascript
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      region: env('AWS_REGION'),
      params: {
        Bucket: env('AWS_BUCKET'),
        Folder: env('AWS_FOLDER'), // <----- new option
      },
    },
  },
  // ...
});

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/2972

**Comment by kgaurav-ts** [comment]
Is there any way to upload images for different content-types to a different folders (media assets for collection_type1 should be uploaded to assets_collection_type1 folder, media assets for collection_type2 should be uploaded to assets_collection_type2 folder in s3 bucket and so on).
This really helps us to keep the assets for different collection types organised.

**Comment by Aadilhassan** [comment]
@kgaurav-ts  did you find any solutions?

**Comment by kgaurav-ts** [comment]
they made an update where you can make folders on the dashboard part, but that won't change the structure on the s3 bucket (i.e. there won't be different folders in the s3 bucket).
