### ISSUE TITLE
Unable to login in production behind a proxy using nginx

### ISSUE THREAD

**Issue by mploux** [strapi/strapi#8544]
### Describe the bug

In production if I go to `http://{IP}:1337/admin` the login page shows up and I can login.
When I added a proxy to `https://admin.domaine.com/` when trying to connect it reloads the same page and does nothing. There are no errors in the console.

### Steps to reproduce the behavior

1. Configure url in `/config/server.js`
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '###'),
    },
  },
  url: 'https://admin.domain.com'
});
```
2. Build for production
3. Start the server for production
4. Go to `http://{IP}:1337/admin` and login (It should work)
5. Configure the nginx config
```
# Handle https redirection above
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name admin.domaine.com;
        ssl_certificate /etc/letsencrypt/live/admin.domaine.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/admin.domaine.com/privkey.pem;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'HIGH:!aNULL:!MD5';

        auth_basic           "Admin";
        auth_basic_user_file /opt/admin/.htpasswd;

        location /  {
                proxy_pass              http://localhost:1337;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_pass_request_headers on;
        }
}
```
6. Restart nginx
7. Go to https://admin.domaine.com/admin and try to login. In my case it reloads the page and goes back to login without any messages or error. Here is the console:
![Screenshot_4](https://user-images.githubusercontent.com/17877331/97829860-84fc5400-1ccb-11eb-9019-ac87d407e511.png)

### Expected behavior
I should login and have the dashboard displayed

### System
- Node.js version: v12.19.0
- npm version: v6.14.8 (I use Yarn)
- Yarn version: v1.21.1
- Strapi version: Community v3.2.3
- Database: sqlite
- Operating system: Ubuntu 16.04.6 LTS

**Comment by mploux** [comment]
EDIT: I found the problem and it turns out it's because I'm using nginx auth

**Comment by derrickmehaffy** [comment]
Thanks for the update @mploux but as the issue isn't with Strapi itself, please move questions to Strapi usage and errors that happen during runtime like this on our forums: https://forum.strapi.io/

We try to limit the scope of GitHub issues to that of confirmed bugs that require a code change on the Strapi side, for that I'm going to mark this as closed, if you are still having issues with Nginx I'll be happy to help you on the forum. Thanks!
