### ISSUE TITLE
Database conector MSSQL

### ISSUE THREAD

**Issue by genthalili** [strapi/strapi#855]
**Node.js version**:
v9.9.0
**npm version**:
5.8.0
**Strapi version**:
strapi@3.0.0-alpha.11.1
**Operating system**:
ProductName:	Mac OS X
ProductVersion:	10.13.3

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
It there a way to connect strapi with Microsoft SQL Server database? If yes, can anyone share information how can I quickstart?

**Comment by piere129** [comment]
I did it using the following in MySQL: 

1) create strapi app with MySQL database and specify db config when asked (database name, port, ...)
2) create a content type (f.e. : 'product') which contains a field (f.e. : a string called 'name');
3) As Strapi is currently configured, you MUST create the table for your new content-type yourself. There are a few things to keep in mind for this:
- creating a table should include created_at and updated_at fields, as those are included by default 
- it needs an auto-incremented id field
- the names of the fields must be the same as the ones you entered in the admin ui (so a string called 'name')
- the name of the table, should be the same as the collectionName specified at api/product/models/product.settings
4) After creating your table, go to admin ui again, ensure you are connected with the database, and try creating a new product. It should now be working.

This is how i got it to work for me. Hope it helps

**Comment by wcorrea** [comment]
Also, for MySQL, 
use lowercase letters only for columns names
SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';
to avoid problems with updated_at and created_at columns when getting populated
