### ISSUE TITLE
Sort Collections by created_at by Default for REST/GraphQl endpoints

### ISSUE THREAD

**Issue by cwray-tech** [strapi/strapi#8551]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

This would change the default sort order of collections to be by the created_at or published_at timestamp so that the most recent content is returned first, making editing of recently created content easier.

This seems like this should be the default way of sorting as this is what most sites would want I assume.

IF not default, then there should be an option to enable this feature for a collection, so that all content returned is ordered this way if desired.

### Why is it needed?

Right now, in the admin area collection items are sorted in ascending order by default, which means that older content is always the first item in the collection returned. 

This makes finding new posts a pain as you need to view more pages to see /edit recent posts. 

### Suggested solution(s)

I would suggest making this a part of the default controller API, and giving people the option of either enabling this or not.

**Comment by derrickmehaffy** [comment]
@cwray-tech can you clarify if this FR is for the Admin (which is already possible) or the REST/GraphQL API?

**Comment by cwray-tech** [comment]
@derrickmehaffy I am primarily meaning for the REST/GraphQl endpoints so that everywhere(including the admin) returns that way by default, but I did not realize that the admin can already do this. Is this in the collection settings somewhere?

**Comment by derrickmehaffy** [comment]
It is not a model settings config, but a model view config (thus stored in the database):

![image](https://user-images.githubusercontent.com/8593673/97917380-a08a4d80-1d11-11eb-8773-6e28c99eda31.png)

![image](https://user-images.githubusercontent.com/8593673/97917439-b435b400-1d11-11eb-9190-0a96edb111d8.png)

I will however leave the feature request open to add an option into the model settings as a default response for REST/GraphQL, the admin itself however won't use this setting and it would still be handled by the Content-Type manager settings as the Admin has it's own internal REST API used to fetch data.

**Comment by cwray-tech** [comment]
@derrickmehaffy that is cool and is definitely nice to have and I will use that. 
I primarily was wanting this in the API, and then realized it should be in the admin as well. The reason I would like this in the API is because if you are trying to limit posts, then the oldest are always returned first, making it necessary to add a param for the sort as well.

If it is okay, I may try to implement this feature. Is that okay with you? Any recommendations?

**Comment by derrickmehaffy** [comment]
For the moment it will most likely require an RFC: https://github.com/strapi/rfcs if you want to implement it as it requires a core code base change.

In the short term if you just want to apply this to your APIs, you could create a policy like:

Path: `./config/policies/somepolicy.js`
```js
module.exports = async (ctx, next) => {
  console.log(ctx.query)
  if (!ctx.query['_sort']) {
    // If SQL
    ctx.query['_sort'] = 'created_at:desc'

    // If Mongo
    //ctx.query['_sort'] = 'createdAt:desc'
  }
  await next()
};
```

Then assign the policy to the routes via the `./api/somemodel/config/routes.json` like so:
```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/clients",
      "handler": "client.find",
      "config": {
        "policies": ["global::somepolicy"]
      }
    },
....
}
```

**Comment by cwray-tech** [comment]
Whoa. I like that. Will implement that. Also wrote a blog on how to do this in the controller, but will def update it to be that way.

**Comment by derrickmehaffy** [comment]
Yup it can be done in the controller, but the policy is more fluid and can be assigned to any route where needed without duplicating code. Much easier on updates also :P 

But I still agree we should add a default sort in the model settings also.

**Comment by cwray-tech** [comment]
I am closing this issue, because after thinking about this more, I think that the way that the collections are returned by default is more accurate, and really should be done via a policy as @derrickmehaffy suggested. 

I may try to build a drop in plugin for this (if I have the chance.)
