### ISSUE TITLE
columnsToAlter on strapi-database-schema is no awaited before use

### ISSUE THREAD

**Issue by JuanmanDev** [strapi/strapi#8560]
Hello!
I think I found a possible bug, or at least unreachable code.

getColumnsWhereDefinitionChanged is an async function, that always return a promise.
On strapi-connector-bookshelf/lib/build-database-schema.js the function is called without await.
So, the length of columnsToAlter  will be always undefined.
https://github.com/strapi/strapi/blob/3c78413d9ce3ffd753c37837c4d08e60fe74b63a/packages/strapi-connector-bookshelf/lib/build-database-schema.js#L305-L311

![image](https://user-images.githubusercontent.com/5569316/97979066-d6d9d280-1dce-11eb-95ee-c9fe20af1799.png)
![image](https://user-images.githubusercontent.com/5569316/97979102-e3f6c180-1dce-11eb-8c4e-31927d745bd9.png)

I could make a PR, but I prefer someone on the team check that the code we are going to make reachable is safe (beacuse contains DROP)

Thanks!

**Comment by JuanmanDev** [comment]
@petersg83 could you check it, please?
https://github.com/strapi/strapi/commit/d84284faf2b166a2430575ec391b882de0340209

**Comment by derrickmehaffy** [comment]
Normally I would close issues that don't follow our template but I will leave this one open as it does appear to be a bug. I will let @petersg83 confirm

**Comment by petersg83** [comment]
Hello @JuanmanDev you are right and the tests did detect it. I'll fix it :) Thanks !
