### ISSUE TITLE
GraphQL count API requires the `find` permission but should only require `count`

### ISSUE THREAD

**Issue by Acidic9** [strapi/strapi#8569]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

When making a count query to the GraphQL API, you require the `find` permission. The `count` permission does not seem to apply in this case.

Example query:
```
{
  ordersConnection {
    aggregate {
      totalCount
    }
  }
}
```

### Why is it needed?

I want to expose the `count` permission, but not the `find` permission to the public.

### Suggested solution(s)

Allow the above query to return the count when the `count` permission is active, not the `find` permission.

### Related issue(s)/PR(s)

None that I could find.

**Comment by derrickmehaffy** [comment]
The aggregate count is functionally different than a normal count. If you need just a count on GraphQL see the following article: https://strapi.io/documentation/v3.x/guides/count-graphql.html

Closing as the intended permissions is applied.
