### ISSUE TITLE
Filter suffix eq lacks case sensitivity control similar to say contains and containss

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#8570]
### Summary

Filter equals doesn't seem to have any way of turning on/off case sensitivity. We can't find records that exist and meet query criteria, but with different text case, which we can't modify. 

### Why is it needed?

Trying to find an entry that is equal to the exact text, regardless of case. 
EG: we may not know how a name was saved (case-wise), but we need the **exact match**. 
Let's say we want to find a record with name === `Peter` and don't know whether it was saved as `Peter` or `peter` or even `peTer`.
- We cannot use `contains`, becoz this will match partial strings in DB. ie `name_contains: 'peter'` will match: `DePeter`, `Peter` and `Peteros`. 
- And `name_eq: 'peter'` will match `peter` **only if it was saved as such** and _nothing_, because of case sensitivity, if `Peter` or `peTer`, etc was used; though this was the correct query to use for the **exact match** need.

### Suggested solution(s)

No suffix or `eq`: Equals - should be case **insensitive** and `eqs` should be case **sensitive**
- `name_eq: 'peter'` or `name: 'peter'` will match `Peter` or `peter` in DB
- and `name_eqs: 'peter'` will only match `peter` and NOT `Peter` in DB.
- same for the inverses `name_neq: 'peter'` will NOT match `Peter` or `peter` in DB and `name_neqs: 'peter'` will IGNORE `peter` only.

**Comment by derrickmehaffy** [comment]
Can you please tell me what database you are using?

**Comment by emahuni** [comment]
Hi Derrick

I am using Postgresql.

**Comment by derrickmehaffy** [comment]
Thank you, yes you are correct our SQL database connector doesn't perform case-sensitive lookups with this filter, I've added it as a feature request pending review by our engineering team.

**Comment by nguyenchauhuyen** [comment]
the same issue with MongoDB

**Comment by borisflesch** [comment]
Hi,
I am facing the same issue. In the meantime, here is a small workaround which works pretty well to perform an "equal" research which is not case sensitive within custom methods:

```js
const searchVal = 'peTer';
const resAll = await strapi.query('<collection>').find({ '<field>_contains': searchVal }); // Will fetch all results that contains peTer, not case sensitive
const res = resAll.find(e => e.<field>.toLowerCase() === searchVal.toLowerCase()); // Find the exact match, not sensitive
```

It is definitely **not the most optimised nor the cleanest way** to handle non case sensitive research (especially in huge collections), but it can certainly help 😉

**Comment by PradhumnaPancholi** [comment]
> Hi, I am facing the same issue. In the meantime, here is a small workaround which works pretty well to perform an "equal" research which is not case sensitive within custom methods:
> 
> ```js
> const searchVal = 'peTer';
> const resAll = await strapi.query('<collection>').find({ '<field>_contains': searchVal }); // Will fetch all results that contains peTer, not case sensitive
> const res = resAll.find(e => e.<field>.toLowerCase() === searchVal.toLowerCase()); // Find the exact match, not sensitive
> ```
> 
> It is definitely **not the most optimised nor the cleanest way** to handle non case sensitive research (especially in huge collections), but it can certainly help wink

Thanks for the workaround, worked like a charm. Looking forward to the feature.

**Comment by derrickmehaffy** [comment]
Filtering has been reworked in v4 and now largely depends on the capabilities of knex.js and/or the database sitting behind it.

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering

**Comment by kg05** [comment]
@derrickmehaffy is this feature working now, can we use the filter for case insensitive case?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy is this feature working now, can we use the filter for case insensitive case?

Depends on the database I believe.

**Comment by QuarkAgency** [comment]
Case insensitive still not working for Postgres
