### ISSUE TITLE
Filter by "publicationState" in Queries Connectors

### ISSUE THREAD

**Issue by neudysrd** [strapi/strapi#8574]
### Summary

Filter by "publicationState" in Query Connectors

### Why is it needed?

Being able to filter by the status in the query connectors allows me to show lists of items making use of the count and totalCount that the query connectors provide in their aggregate.

### Suggested solution(s)
![a4691fc5bd91ef9d457e6863b2baf469128550cc](https://user-images.githubusercontent.com/71604744/98137978-ff2e0380-1e98-11eb-9eda-162476c33010.png)
![bceceb5de659cfbdf76b7e0e234df004cfd4229f](https://user-images.githubusercontent.com/71604744/98137984-005f3080-1e99-11eb-9257-8ae4bf7eff3b.png)

Add the functionality of "publicationState" in the aggregation option in GraphQL so that they are available in the query connectors.

### Related issue(s)/PR(s)

I have not found anything related directly, regarding functionality if I found this issue #8507  regarding adding it in the mutations.

**Comment by derrickmehaffy** [comment]
Can you please add the information to that issue you linked so we don't have duplicate info for very similar requests.

Marking as duplicate for now.
