### ISSUE TITLE
npm run setup doesn't work in 3.0.0-alpha.12

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#858]
**Node.js version**: v9.8.0
**npm version**: 5.8.0
**Strapi version**: 3.0.0-alpha.11.2
**Operating system**: macOS

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

<img width="1031" alt="screen shot 2018-03-27 at 20 03 22" src="https://user-images.githubusercontent.com/1007051/37985904-562d04a8-31fa-11e8-9bcc-b8111925cd0b.png">

**If the current behavior is a bug, please provide the steps to reproduce the problem**

`strapi new strapi-demo`
`cd strapi-demo`
`npm run setup`

**What is the expected behavior?**

The setup working.

**Comment by abdonrd** [comment]
@lauriejim but I have had this issue using Node v9.8.0.

**Comment by abdonrd** [comment]
Only as suggestion, I propose to move it to `v3.0.0-alpha.11.3`, because it starts to fail in `v3.0.0-alpha.11.2`. With `v3.0.0-alpha.11` works well.

**Comment by abdonrd** [comment]
Maybe the bug is from #773, since it is the moment in which file `strapi-plugin-users-permissions/services/UsersPermissions.js` was edited.

**Comment by bugvish** [comment]
Quick and dirty hack:

Change Line 140 of /strapi/packages/strapi-helper-plugin/node_modules/babel-core/lib/transformation/file/index.js to:
      plugins: ["jsx","flow","objectRestSpread"]

**Comment by L8NiteOwl** [comment]
Thanks, @bugvish! I was really scratching my head on this one. This temporary hack worked perfectly for me.

**Comment by abdonrd** [comment]
I just tried with the new version (`v3.0.0-alpha.12`) and it still happens.

**Comment by soupette** [comment]
#1033
