### ISSUE TITLE
Can't access to users & permissions settings strapi 3.2.5

### ISSUE THREAD

**Issue by DonikaV** [strapi/strapi#8581]
Hello, just installed first time Strapi to try it.
In the first 10 minutes everything was fine but then I got this error and nothing can help me
Tried to re-install
create new project
remove node modules and install again

### Steps to reproduce the behavior

1. Install strapi
2. Click on http://localhost:1337/admin/plugins/users-permissions/
3. See error

### Expected behavior

See roles settings

### Code snippets

The basic,  the code is from **strapi new** 

### System

- Node.js version: v12.19.0
- NPM version: 6.14.8
- Strapi version: 3.2.5

![image](https://user-images.githubusercontent.com/26111842/98232838-d411e580-1f66-11eb-8a69-a6b2c0eee2ae.png)

**Comment by derrickmehaffy** [comment]
Please confirm you are trying to access it via the settings menu on the left as we move them in there in v3.1.5.

Also if you just recently updated, make sure you rebuilt your admin panel.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by DonikaV** [comment]
@derrickmehaffy i did rebuild -- clean and etc... 
I just installed it from scratch, then run the app. And after a couple of minutes, it stops working.

**Comment by derrickmehaffy** [comment]
That link you provided doesn't look right, did you get that from somewhere specific?

**Comment by DonikaV** [comment]
![image](https://user-images.githubusercontent.com/26111842/98249983-94a3c300-1f7f-11eb-8b04-bbfc9dfb60e5.png)

![image](https://user-images.githubusercontent.com/26111842/98250035-a4230c00-1f7f-11eb-9a2a-27f2a6b39e3a.png)

**Comment by MattieBelt** [comment]
Does http://localhost:1337/admin/settings/users-permissions/roles work or `Dashboard > Settings > USERS & PERMISSIONS PLUGIN`.

**Comment by DonikaV** [comment]
So, after a couple of hours, i am able to go http://localhost:1337/admin/settings/users-permissions/roles/

But, I still can not see this URL in sidebar.

**Comment by DonikaV** [comment]
I mean i didn't changed anything... just stopped the app 3 hours ago and now started and it works... :D 

:magic:

**Comment by MattieBelt** [comment]
Nice, but could you tell us where you found that incorrect/outdated link, so it could be fixed. As @derrickmehaffy said the plugin settings have been moved recently, but there are still some incorrect links around :/

**Comment by DonikaV** [comment]
No, it was just my mistake. Forget about it.... I mean I tried with correct one with **http://localhost:1337/admin/settings/users-permissions/roles/** and this page was with errors.

**Comment by DonikaV** [comment]
No, it was just my mistake. Forget about it.... I mean I tried with correct one with **http://localhost:1337/admin/settings/users-permissions/roles/** and this page was with errors.

**Comment by DonikaV** [comment]
Ok, thanks, guys. For now, it works, I will re-open / report if it will crash again. I am going to continue my learning :)

**Comment by DonikaV** [comment]
@derrickmehaffy  @MattieBelt 
I found! 
https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_7-set-roles-and-permissions here, in tutorial. The link goes to http://localhost:1337/admin/plugins/users-permissions/roles 
Also following the guide, I can not see my Content type that I just created permissions settings :|

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy @MattieBelt
> I found!
> https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_7-set-roles-and-permissions here, in tutorial. The link goes to http://localhost:1337/admin/plugins/users-permissions/roles

https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_7-set-roles-and-permissions
vs
https://strapi.io/documentation/v3.x/getting-started/quick-start.html#_7-set-roles-and-permissions

:wink: You were looking at the older beta documentation instead of the current. We know there is an issue with the Google search and SEO stuff and we are planning to remove the beta documentation entirely since it's for a version we no longer support.

**Comment by paulovieira** [comment]
Hello! I'm also trying strapi for the first time and I also end up blocked by this issue (not finding "Roles and Permissions" in the left  menu). The problem is that the video in the Quick Start Guide is not yet updated (right?), so it's a bit misleading.

https://strapi.io/documentation/v3.x/getting-started/quick-start.html

**Comment by derrickmehaffy** [comment]
@paulovieira Yup it hasn't been updated yet, we are working to get a new one made.
