### ISSUE TITLE
render a blank page on importing CKEditor document as plugin

### ISSUE THREAD

**Issue by ctrngk** [strapi/strapi#8585]
Hi all,
First of all, step by step **ckeditor5-build-classic** works as expected. 

Ckeditor5 offer a more powerful version **ckeditor5-build-decoupled-document**, however it is not compatible with [offical strapi docs](https://strapi.io/documentation/v3.x/guides/registering-a-field-in-admin.html). When I add the following  
```js
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
```
in plugins/wysiwyg/admin/src/components/CKEditor/index.js

The server (localhost:8000 or localhost:1337) just render a blank page

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by msglab** [comment]
here are a couple of posts in the forums related to this:

https://forum.strapi.io/t/tuto-change-the-wysiwyg-with-ckeditor-ckeditor-errors/923

https://forum.strapi.io/t/add-ckeditor-plugins/855
