### ISSUE TITLE
forgot password got bad request 400 response strapi v3.2.5 — Community Edition

### ISSUE THREAD

**Issue by ElanSetiawan** [strapi/strapi#8588]
**Describe the bug**
Test user forgot password.
the Forgot password fetch never works and returns 400 bad request all the time.

Regarding public user permissions etc - every single user role permission is set to enabled/allow etc (just for debugging).
It gives me a "400 Bad Request"

**Steps to reproduce the behavior**

Go to http://localhost:1338/auth/forgot-password
Enter your email
Click on Send Email
Expected behavior
Send an email to change the password

<img width="891" alt="Screen Shot 2020-11-07 at 12 37 43" src="https://user-images.githubusercontent.com/30363332/98433017-233a5080-20f6-11eb-874c-59318df8c48f.png">

email not get too

and email send-email-confirmation not work too

<img width="882" alt="Screen Shot 2020-11-07 at 13 08 49" src="https://user-images.githubusercontent.com/30363332/98433525-731b1680-20fa-11eb-9d70-a817fe6ffa36.png">

server.js
module.exports = ({ env }) => ({
  host: env('HOST', '127.0.0.1'),
  port: env.int('PORT', 1337),
  url: env('', 'http://localhost:1337'),
});

**System**

Node.js version: v12.10.0
NPM version: 6.10.3
Strapi version: Strapi v3.2.5 — Community Edition
Database: postgres
Operating system: macOs

**Comment by soroka41** [comment]
https://www.spamhaus.org/lookup/ Check Ip because of this there may be troubles

**Comment by danielharven** [comment]
Same here, getting similar response

**Comment by soroka41** [comment]
postman  ->raw ->json

**Comment by derrickmehaffy** [comment]
> postman ->raw ->json

Yes this is correct, please try testing with raw/json in postman



> https://www.spamhaus.org/lookup/ Check Ip because of this there may be troubles

This is also extremely likely (with any provider) as the default solution provides no way for mail receivers to validate the sender, it's also quite likely if testing on a consumer ISP that port 22 will be blocked by your ISP and most cloud providers also block outbound port 22 to prevent email abuse. You should check with your hosting provider to ensure they aren't blocking the emails.

**Comment by ElanSetiawan** [comment]
1. try with raw:
<img width="885" alt="Screen Shot 2020-11-13 at 09 22 42" src="https://user-images.githubusercontent.com/30363332/99020770-e0fb8e00-2591-11eb-830e-7ee65713f2f7.png">

2. 
<img width="933" alt="Screen Shot 2020-11-13 at 09 21 43" src="https://user-images.githubusercontent.com/30363332/99020828-ea84f600-2591-11eb-8b8b-abf8c7f84a8c.png">

**Comment by derrickmehaffy** [comment]
@ElanSetiawan that IP range is a private range and isn't accessible on the public internet. The entire 192.168.0.0 - 192.168.255.255 (65,536 IP addresses) is private hence why you won't ever find those in spamhaus, you will need to check your public IP.

**Comment by OmarMtya** [comment]
> @ElanSetiawan that IP range is a private range and isn't accessible on the public internet. The entire 192.168.0.0 - 192.168.255.255 (65,536 IP addresses) is private hence why you won't ever find those in spamhaus, you will need to check your public IP.

So you need to have an IP whitelisted to DEVELOP the forgot-password feature in localhost????
Strapi should add the feature of provide an email address and the smtp server without using any other module.

**Comment by derrickmehaffy** [comment]
@OmarMtya we just recently took over maintaining an SMTP provider here: https://github.com/strapi/strapi/tree/master/packages/strapi-provider-email-nodemailer

It is not the default as without an SMTP server you can't send emails. Strapi's default uses sendmail which works for testing if your local environment doesn't block the email requests (or your receiving provider). You are welcome to use the nodemailer email provider.

I'm going to mark this as closed until we can get more information or you are also welcome to move this over to our [forum](https://forum.strapi.io/) as I don't believe this to be a bug with Strapi itself but an issue in the user environment (I'm unable to reproduce the bug locally using my own personal email server)

**Comment by ElanSetiawan** [comment]
Thanks

It's oke, I'm done using sendgrid,
Thanks for answers

**Comment by Bhogster** [comment]
Hi @ElanSetiawan ,
It would be great if you can list down the steps as to how you achieved to send a forgot password mail (with the token) using Sendgrid.
Thanks in advance.

**Comment by KogayIrina** [comment]
Hi @ElanSetiawan ,
How you solved this problem? I have the same problem now.

**Comment by Muzamil132** [comment]
Hey I am also  having this problem any one help me please

**Comment by KogayIrina** [comment]
Hi @Muzamil132 ! I solved this problem using the nodemailer-plugin. Also, you need to check email settings -> reset password  in Strapi (you need to change default shipper email)

**Comment by DeividVeloso** [comment]
Hey, I am also having this problem anyone help me, please?

I am using `strapi-provider-email-nodemailer: 3.6.11` and strapi v3

And I installed the `maildev` with this config to run in localhost:

```
module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'nodemailer',
      providerOptions: {
        host: 'localhost',
        port: 1025,
        ignoreTLS: true,
      },
    },
  },
});
```

Postman is very slow and after some time it returns this for VALID email:

![image](https://user-images.githubusercontent.com/16343871/235773051-31e16afd-4de3-49ff-8d9b-7cb8eb5dacf9.png)
