### ISSUE TITLE
schema.graphql.js in extensions/ folder loaded twice

### ISSUE THREAD

**Issue by darron1217** [strapi/strapi#8589]
### Describe the bug
I tried to extend plugin's graphql config. I found that `schema.graphql.js` config loaded twice.

### Steps to reproduce the behavior

1. Create file `extensions/users-permissions/config/schema.graphql.js`
2. Add `console.log('test')` to the file
3. Run server
4. server prints `test` twice

### Expected behavior
This config should load once.

### Screenshots
![image](https://user-images.githubusercontent.com/8064923/98433579-b7fb7900-210b-11eb-8a21-74e36b5ea1f1.png)

### Code snippets
I found that there are two scripts which loads extension's config

*Strapi core*
https://github.com/strapi/strapi/blob/60bf24ce8b4b68959cdab9c350bf5e78efc8f378/packages/strapi/lib/core/load-extensions.js#L23

*strapi-graphql-plugin*
https://github.com/strapi/strapi/blob/60bf24ce8b4b68959cdab9c350bf5e78efc8f378/packages/strapi-plugin-graphql/hooks/graphql/load-config.js#L25-L26

### System

- Node.js version: v12.18.3
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: MongoDB
- Operating system: Mac OS Catalina

**Comment by darron1217** [comment]
I found that graphql schema duplication error is not related to this issue.
It is solved by updating graphql-tools version to `4.0.8`. 
Please merge this PR https://github.com/strapi/strapi/pull/8461.

Anyway loading config twice is also a problem. So I'll left this issue open.

**Comment by derrickmehaffy** [comment]
@darron1217 do you feel like making a PR for this? It should be a fairly straight forward fix. Thanks :smiley:

**Comment by darron1217** [comment]
@derrickmehaffy Unfortunately, I can't predict the side effects of removing one of them.
So I hope this issue to be handled by Strapi Core Developers 😂

**Comment by derrickmehaffy** [comment]
No problem, I can't promise a fix anytime soon but it's in their list.

**Comment by alexandrebodin** [comment]
Hey, This issue does not exist in v4 and v3 is now End of Life. I'll close it :)
