### ISSUE TITLE
Custom primaryKey on MySQL

### ISSUE THREAD

**Issue by jvanegasv** [strapi/strapi#859]
**Node.js version**: v8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.11.2

**Operating system**: OSX 10.13.3

I already have a MySQL database with tables that don't follow the convention 'id' for primary, how can I indicate the appropriate idAttribute for the table into the model definition (table.settings.json) and also how to indicate it into the relationships with other tables...

**Comment by Aurelsicoko** [comment]
Try to add the `primaryKey` attribute in your model, it should work
```js
{
  "connection": "default",
  "primaryKey": "<your-key",
  "attributes": {
     ...
  }
}
```
