### ISSUE TITLE
Unable to Start After DB Import (error: relation X already exists)

### ISSUE THREAD

**Issue by Jessinra** [strapi/strapi#8592]
## Unable to Start After DB Import (error: relation X already exists)
Hi, I have the **same strapi app** deployed on multiple environments (local, Heroku, etc) and I'm trying to move the data from one to the other.

I followed this docs [1] (https://devcenter.heroku.com/articles/heroku-postgres-import-export) and exported the Postgres database I use for strapi in the Heroku environment, I successfully exported the DB.
After I tried to import the data into the local Postgres database (also referring docs [1]), my local strapi won't start. (check logs below)

it always shows `error: relation X already exists`. X = one of the relations defined

### Things I tried & the result
- (**failed**) I tried to drop the database then recreate a new one, follow docs [1] to restore, and run strapi local => can't start, same logs.

- (**failed**) 
I tried to use `heroku pg:pull` method (https://blog.heroku.com/push_and_pull_databases_to_and_from_heroku), to pull data from Heroku to the local DB, the pull process succeed, but the local strapi won't start (same logs).

- (**somewhat successful**) 
I tried to drop the database =>  recreate a new one => run **npm run develop** (start strapi on development env) => strapi initialize the database with tables =>  then I follow the docs [1] => result: the data partially imported (some type has no data, or partially imported)

### Logs
```
Server wasn't able to start properly.
[2020-11-08T10:32:43.724Z] error error: relation "core_store" already exists
    at Parser.parseErrorMessage (/Users/jessinra/Code/Project/skadi/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/jessinra/Code/Project/skadi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/jessinra/Code/Project/skadi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/jessinra/Code/Project/skadi/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
From previous event:
    at Client_PG._query (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/runner.js:135:36)
    at Runner.<anonymous> (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/runner.js:228:25)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Runner.queryArray (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/runner.js:227:12)
    at /Users/jessinra/Code/Project/skadi/node_modules/knex/lib/runner.js:37:25
From previous event:
    at Runner.run (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/runner.js:25:16)
    at SchemaBuilder.Target.then (/Users/jessinra/Code/Project/skadi/node_modules/knex/lib/interface.js:14:43)
```

### Describe the bug

Can't run strapi after database import

### Steps to reproduce the behavior

1. export (dump) strapi database from heroku
2. import dump into strapi database
3. run `npm run develop` / start 

### Expected behavior

Strapi runs successfully, all data loaded successfully 

### Screenshots

<img width="858" alt="Screen Shot 2020-11-08 at 18 05 38" src="https://user-images.githubusercontent.com/32489864/98463336-22381a80-21ed-11eb-9279-10f079748bca.png">

### System

- Node.js version: v14.11.0
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: postgres
- Operating system: ubuntu 18.04

- Other dependencies (package.json)
```
    "knex": "<0.20.0",
    "node-fetch": "^2.6.1",
    "patch-package": "^6.2.2",
    "pg": "^8.3.3",
    "sqlite3": "latest",
    "strapi": "3.2.5",
    "strapi-admin": "3.2.5",
    "strapi-connector-bookshelf": "3.2.5",
    "strapi-plugin-content-manager": "3.2.5",
    "strapi-plugin-content-type-builder": "3.2.5",
    "strapi-plugin-documentation": "3.2.5",
    "strapi-plugin-email": "3.2.5",
    "strapi-plugin-graphql": "3.2.5",
    "strapi-plugin-upload": "3.2.5",
    "strapi-plugin-users-permissions": "3.2.5",
    "strapi-provider-upload-cloudinary": "3.2.5",
    "strapi-utils": "3.2.5"
```

really appreciate if someone could reach out soon
thank you very much in advance!

**Comment by derrickmehaffy** [comment]
Hi @Jessinra can you please open a forum thread for this, as the issue in this case is not with Strapi but is a usage and migration of content between databases in different environments.

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Jessinra** [comment]
Okay I'll try to post in forum as well, thanks.

Are you sure it's `not with Strapi` ?

**Comment by derrickmehaffy** [comment]
> Okay I'll try to post in forum as well, thanks.
> 
> Are you sure it's `not with Strapi` ?

As we don't directly support database migrations and I haven't been able to reproduce I am fairly confident it's not anything in the Strapi code-base

**Comment by StianOvrevage** [comment]
I'm just hitting this when trying to create a new environment with existing data (copied over to new database).

When researching how to actually migrate I came over several claims to just copy the data over as long as the schema is the same. And that is what I did (at least I think, it's a hairy process).

If you say you don't directly support database migrations. Are you saying there is no way of setting up a new strapi container and connect it to an existing database?

**Comment by derrickmehaffy** [comment]
> I'm just hitting this when trying to create a new environment with existing data (copied over to new database).
> 
> When researching how to actually migrate I came over several claims to just copy the data over as long as the schema is the same. And that is what I did (at least I think, it's a hairy process).
> 
> If you say you don't directly support database migrations. Are you saying there is no way of setting up a new strapi container and connect it to an existing database?

We don't have the tooling within Strapi to handle the migrations, nor can we currently construct the models from a database schema.

We are looking into the former in early Q1/Q2 of 2021 (migrations of the DB schema ans possibly data) and the latter doesn't have an ETA but we would like to do something with that, same for creating tooling to migrate from other platforms to Strapi.

For the moment we don't recommend connecting Strapi to an existing database, but construct your Strapi model schema as close as needed to the old database, allow Strapi to build out the database, and finally import the data.

**Comment by StianOvrevage** [comment]
Ok. That works. But what is the process of exporting and importing the data correctly? That is what I've been unsuccessfully trying to find.

**Comment by derrickmehaffy** [comment]
Largely depends on the database being used, typically I see users dumping into a standard format (json, csv, tsv, ect) and either directly importing into the database or, in smaller cases, just writing a quick script to parse the files and push the data into Strapi via the REST API.

**Comment by julesrenaud** [comment]
Not sure it applies here, but I had a similar problem. After creating a postgres database on a new server and importing all the tables created by Strapi (on a different server), I had the same error. What I ended up doing is deleting the database and creating it again, start Strapi and give it this "bare" database, stoping Strapi and then importing the tables from the database dump. Everything runs fine this way and the content is present in the new Strapi instance.
