### ISSUE TITLE
Unique field not working

### ISSUE THREAD

**Issue by kmabadshah** [strapi/strapi#8595]
On strapi 3.2.5, selecting a field as unique doesn't work and the consumer is able to duplicate that field. It wasn't an issue on an earlier version(I can't remember what it was). Please fix this issue. I'm using postgresql 12.4 as the database

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
