### ISSUE TITLE
Multiple relationships on different models with the same name is not allowed

### ISSUE THREAD

**Issue by oeddyo** [strapi/strapi#860]
**Node.js version**:
9.0.0
**npm version**:
5
**Strapi version**:
3.0.0-alpha.11.2
**Operating system**:
Mac OS 10.12

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
A model "Brand" has many "Bag" (1:N), with "producer" and "bags" respectively 
then I'm adding a "family" type
A family has many Bags too. (family: bag is 1:N)
but when i'm trying to create 1:N relationship on bag with "family" and "bags", it says:
![image](https://user-images.githubusercontent.com/1943146/38010617-8873a70e-328c-11e8-97fa-1f87d0877556.png)

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**
I expect to be able to "bags" field on Family even when Brand has already a "bags" property

**Comment by oeddyo** [comment]
[api.zip](https://github.com/strapi/strapi/files/1854677/api.zip)

here's the api zip

**Comment by lauriejim** [comment]
Hey @oeddyo sorry for the delay but actually no time to investigate on this issue. I hope I will be able soon to work on it.

Appreciate your help if you can check in `admin/src` folder of the `content-type-builder` plugin where the match is apply.

**Comment by oeddyo** [comment]
Thanks @lauriejim 
missed your msg.

do you want me to upload the folder? or how shall I help checking admin/src?

**Comment by oeddyo** [comment]
oh i saw #1022 did you fix it already?

**Comment by soupette** [comment]
Hi @oeddyo you need to edit this [file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-type-builder/admin/src/containers/Form/utils/attributeValidations.js) and rebuild the plugin.

**Comment by oeddyo** [comment]
Trying to setup dev env. Following the guide but getting:


> ➜  admin git:(master) npm start

> strapi-admin@3.0.0-alpha.12 prestart /Users/exie/workspace/strapi/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js


> strapi-admin@3.0.0-alpha.12 start /Users/exie/workspace/strapi/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server


Strapi plugin succesfully started in development mode. ✓

-----------------------------------
Access URL: http://localhost:4000/admin
-----------------------------------
Press CTRL-C to stop

webpack built 395a2e61c045eded74f9 in 44308ms

ERROR in /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/NotFoundPage/index.js
Module not found: Error: Can't resolve 'components/NotFound' in '/Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/NotFoundPage'
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/NotFoundPage/index.js 25:16-46
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers ^\.\/.*\.js$
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/routes.js
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/app.js

ERROR in /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/App/index.js
Module not found: Error: Can't resolve 'react-router-dom' in '/Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/App'
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/App/index.js 35:22-49
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/app.js

ERROR in /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/routes.js
Module not found: Error: Can't resolve 'routes.json' in '/Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src'
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/routes.js 12:14-36
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/app.js

ERROR in /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/HomePage/index.js
Module not found: Error: Can't resolve 'utils/injectReducer' in '/Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/HomePage'
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/HomePage/index.js 38:21-51
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/App/index.js
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/app.js

ERROR in /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/HomePage/index.js
Module not found: Error: Can't resolve 'utils/injectSaga' in '/Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/HomePage'
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/HomePage/index.js 42:18-45
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/admin/src/containers/App/index.js
 @ /Users/exie/workspace/fix-strapi-fork/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/app.js

Any idea how shall I proceed?

**Comment by lauriejim** [comment]
@oeddyo We update the contributing guide. You have to link `strapi-helper-plugin` in analytics plugin. Or you have to remove the analytics plugin.
