### ISSUE TITLE
strapi develop --watch-admin does not reflect changes on reload

### ISSUE THREAD

**Issue by insivika** [strapi/strapi#8606]
### Describe the bug
The custom admin UI does not reflect changes I'm making on hot reload. I have to manually reload the page to see changes.

### Steps to reproduce the behavior

1. I have set the `develop` script in my package.json file to `"develop": "strapi develop --watch-admin",`
2. I run `npm run develop` 
3. My server config is set to:
```
module.exports = ({env}) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  admin: {
    auth: {
      secret: env("ADMIN_JWT_SECRET", "xxx"),
    },
    host: "localhost", // only used along with `strapi develop --watch-admin` command
    port: 3001,
  },
});
```
4. I've copied the original homepage to `admin/src/containers/HomePage/index.js`
5. When I make changes to the file the watch gets triggered but the changes do not automatically show in the browser.
6. The changes only show after I hard re-fresh the page

See recording here: https://www.loom.com/share/9dcc395573334bbf985f6ca3ad4e2e6b

### Expected behavior

It should just show me my changes without having to refresh the page.

- Node.js version: v14.12.0
- NPM version: 6.14.8
- Database: MongoDb
- Operating system: Catalina

**Comment by insivika** [comment]
Hey @derrickmehaffy have you been able to reproduce this issue. I'm still facing this problem :/

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy have you been able to reproduce this issue. I'm still facing this problem :/

I haven't yet, sorry been quite busy but I will be taking a look here shortly

**Comment by derrickmehaffy** [comment]
I can confirm this on v3.3.3 attempting to modify the https://raw.githubusercontent.com/strapi/strapi/master/packages/strapi-admin/admin/src/containers/HomePage/index.js

- I created the override file at `admin/src/containers/HomePage/index.js` (while using the `--watch-admin`)
- Removed all but one of the objects in `SOCIAL_LINKS` 
- Noted the page didn't auto refresh and I had to do some manually

**Comment by InfiniteEchoDev** [comment]
I'm afraid this may be happening again.  At least, I am experiencing the same issue as @derrickmehaffy using the same repro steps.  I'm having to stop and restart the dev server (with the `npm run develop -- --watch-admin` command) every time I make an update to see the changes.

- Strapi Community v.3.6.8, running on Ubuntu Linux inside WSL with Postgresql db
