### ISSUE TITLE
sanitizeEntity returns null for parent in a polymorphically associated relation

### ISSUE THREAD

**Issue by ishwinder** [strapi/strapi#8607]
## Bug report

I have a following setup to define a polymorphic relation. Various entities in the system can have multiple articles associated with them.

relation definition in entity model(e.g campaign)

in entity model(entity.settings.json)

```
"articles": {
      "collection": "article",
      "via": "parent"
    }
```

in article model(article.settings.json)
```
"parent": {
      "collection": "*",
      "filter": "field"
    }
```
### Describe the bug

Fetching the article using the endpoint(e.g /articles/1) gives the null values in the parent. This happens because the sanitizeEntity here https://github.com/strapi/strapi/blob/442f38a4ba37baaf314f5958243169406b6b1823/packages/strapi-utils/lib/sanitize-entity.js#L60 tries to fetch the model and model in case is a string '*'. This results in `nextOptions.model` to be undefined and this line then returns null for polymorphically associated parent. https://github.com/strapi/strapi/blob/442f38a4ba37baaf314f5958243169406b6b1823/packages/strapi-utils/lib/sanitize-entity.js#L29

### Steps to reproduce the behavior

1. Create a polymoprhic relation e.g article is polymorphically associated with entity.
2. Call the endpont to fetch article .. /articles/1
3. You will see all the parent model attributes are set to null e.g in my case above, `/articles/1` gives the out like:

```
{
"title" : "First Article Title",
"parent" : [
null
]
}
```

### Expected behavior

Proper attributes for the parent should be returned like they are returned for other relations.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.2.4
- Database: postgres
- Operating system: Linux/Mac

**Comment by derrickmehaffy** [comment]
Can't confirm at this time due to the following bug: https://github.com/strapi/strapi/issues/5348

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/5348
