### ISSUE TITLE
Admin UI improvements

### ISSUE THREAD

**Issue by iksent** [strapi/strapi#8608]
### 1. Click !== Hover effect, which is not comfortable.

![hover](https://user-images.githubusercontent.com/32956521/98630235-77cf0d00-233c-11eb-9623-6d3a61ca840a.png)

**Expected behavior:** Hover only at icon OR click available on the whole area.

### 2. Incorrect alignment for multiline repeatable component

![repeatable](https://user-images.githubusercontent.com/32956521/98630370-c67ca700-233c-11eb-96f4-a17eb7c40e7c.png)

**Expected behavior:** Text should be left-aligned

### 3. Not user-friendly notification when saving item with existing slug

![slug-1](https://user-images.githubusercontent.com/32956521/98630420-ea3fed00-233c-11eb-9590-89793eb40da4.png)
![slug-2](https://user-images.githubusercontent.com/32956521/98630425-edd37400-233c-11eb-8226-f258ab2b828c.png)

**Expected behavior:** Probably text should be more user-friendly.

### 4. It's really hard to find items, which are started with the same words, because they are truncated with only 1 line:

![truncated](https://user-images.githubusercontent.com/32956521/98630503-21160300-233d-11eb-8ee9-a8002baa38e4.png)
![truncated-col](https://user-images.githubusercontent.com/32956521/98630509-23785d00-233d-11eb-89e2-fb3dbee3ee26.png)
![truncated-list](https://user-images.githubusercontent.com/32956521/98630516-25422080-233d-11eb-8f60-e797ec491461.png)

**Expected behavior:** Probably we need some settings to show/hide full texts.

### 5. Also text is truncated incorrectly:

![truncated-list-2](https://user-images.githubusercontent.com/32956521/98630596-4c98ed80-233d-11eb-892f-7bbc4e59f45d.png)

**Expected behavior:** There are a lot of space for this text and it should be truncated at the end of line.

### 6. Oh! Truncated description, what for? 👎 

![2020-11-12_11-36-05](https://user-images.githubusercontent.com/32956521/98904422-607a5600-24db-11eb-99a8-4b3d63e1cac5.png)

**Expected behavior:**  All descriptions should be fully visible.

### 7. Too wide ID column

![id-column](https://user-images.githubusercontent.com/32956521/98630678-7d792280-233d-11eb-8968-8fd9cc09c64e.png)

**Expected behavior:**  ID column can be less wide, so other columns will be more wide - that will be better.

### System

- Node.js version: 12.14.0
- NPM version: 6.14.7
- Strapi version: 3.3.1
- Database: MySQL
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
@iksent would it be possible for you to split some of these up into different issues?

Some do appear to be duplicates of other issues and we prefer to tag PRs against the issue numbers to automatically close them.

**Comment by iksent** [comment]
Hello, yes, but please specify exactly which of these I should take into separate issues.

**Comment by hasibweb** [comment]
Also, Admin UI should be Responsive.

**Comment by iksent** [comment]
@hasibweb, yes

But at least it should have min-width for html to use it at mobile devices with scaling.

All these small problems, that can be fixed very quickly, really degrade the overall impression of such a cool CMS!

**Comment by soupette** [comment]
@iksent thanks for your issue however here are some pieces of information but we start fixing them:

Issues 1 and 2 are fine we should fix them, it's an easy one and we would love if someone from the community could open a PR so it would be nice if you could split them into 2 separate issues instead of a big one.

> 3 Not user-friendly notification when saving item with existing slug
Well this is more of a global response format that now the admin cannot really handled and display correctly. We plan to handle the errors soon but we also big topics to develop first but be assured that we know the problem but we have to find a way to manage the errors globally.


> 4.It's really hard to find items, which are started with the same words, because they are truncated with only 1 line
We should probably add a tooltip (@maevalienard ?)

> ### 7. Too wide ID column

Well, the columns are dynamic as you can configure which columns you want to see so I don't want to add more complexity to the codebase in order to reduce the width of the id column. I am guessing you want to gain space for the table so you have more room to display other columns. Maybe we should instead make the table horizontally scrollable.

**Comment by iksent** [comment]
Hello, @soupette!

> 1 and 2

Okay, I'll split them into separate issues.

> 4. It's really hard to find items, which are started with the same words, because they are truncated with only 1 line

What about showing 2 truncated lines for long texts?

Also please take a look at https://react-select.com/home, there are about 8 options are visible by default inside Select's dropdowns. But Strapi shows only 3 options in Selects and this is really uncomfortable.

> 5 and 6

What about these issues?

> 7. Too wide ID column

Can ID Column have something, that is so wide? Aren't identifiers always short or can they be a unid strings?
If not, why not make this column shorter by default?

Also what do you think about reducing horizontal padding of the columns, so that more text could be seen? There are only 2 words are visible and only 1 line (but 3 lines can be easily displayed), and this is so unusable in real projects...

**Comment by maevalienard** [comment]
Hello @iksent, thanks for letting us know all of those points. We'll try to find a solution to avoid (or at least improve) truncated lines, we know it's a huge pain for users. We've thought about adding tooltips at first to give a possibility to see the whole text, the implementation of that is planned. In a second time we'll work on a redesign on some components of the product so we'll try to improve the readability of the list view. This one can include a lot of potential data so we try to improve it the best way :)

**Comment by iksent** [comment]
@maevalienard @derrickmehaffy @soupette
Points 4, 5 and 6: Can I fix truncated lines somehow by myself with overriding components (like [at the example](https://strapi.io/documentation/3.0.0-beta.x/guides/custom-admin.html#introduction))?
All these components are just cannot be used with these truncated texts and my client is really complaining about this.

**Comment by iksent** [comment]
I was able to successfully fix everything for my needs [thanks to this guide](https://strapi.io/documentation/v3.x/guides/custom-admin.html#update-the-admin-home-page).
Perfect customization feature.

**Comment by derrickmehaffy** [comment]
@iksent am I good to close this out or are there still pending issues?

**Comment by iksent** [comment]
I know that point 1 was fixed in 3.3.4

The remaining points (2 - 7) apparently have not yet been resolved.

**Comment by derrickmehaffy** [comment]
Gotcha, thank you

**Comment by Aurelsicoko** [comment]
Hi @sebqq, about your second point, it seems that there is an alternative available by hovering the truncated title of the media to display the full title. See the screenshot below

<img width="698" alt="Screenshot 2021-03-30 at 10 57 02" src="https://user-images.githubusercontent.com/4144726/112962586-d4459400-9146-11eb-81da-1873d8706eea.png">

**Comment by derrickmehaffy** [comment]
Dude to age of issue and now that v4 is live gonna close this. New split issues can be created for any that remain
