### ISSUE TITLE
Possible to use numerical (sequential) id?

### ISSUE THREAD

**Issue by oeddyo** [strapi/strapi#861]
I understand if the underlying db is mongodb, it might be difficult to use numerical id. but it would be SEO friendlier. Just wondering if this is possible (didnt find it in admin panel)

**Comment by Aurelsicoko** [comment]
We are not going to handle this, it's too specific for us. However, there is a solution to this issue https://docs.mongodb.com/v3.0/tutorial/create-an-auto-incrementing-field/
