### ISSUE TITLE
Nested GraphQL request does not work

### ISSUE THREAD

**Issue by ksk-waqs** [strapi/strapi#8610]
### Describe the bug
![5e8b749f1a439a92277b0fc7819260a2339972c9](https://user-images.githubusercontent.com/3883054/98680354-5721aa00-2372-11eb-9fa6-f6c571b2eea6.png)

If I use an un-nested query, everything works correctly.

![0faf2e6a16bb8e644b05f79b6bf98504729cf6d0](https://user-images.githubusercontent.com/3883054/98680366-5c7ef480-2372-11eb-8e90-c80308831179.png)

### System

- Node.js version: 12.18.4
- Yarn Version: 1.22.4
- Strapi version: 3.2.4
- Database: SQLite
- Operating system: Windows 10

### Additional context
**DMehaffy** could reproduce the problem, which is confirmed in this forum topic:
https://forum.strapi.io/t/nested-request-does-not-work/893/4

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/nested-request-does-not-work/893/5

**Comment by nsoticek** [comment]
I have the same problem. It is only possible to filter by id. Nested where conditions are not possible.

This throws an error:
query {
  listingsCount(where: {city: {name: "Bludesch"}})
}

Error (take a look at the where condition of the query):
"message": "select distinct count(*) as \"count\" from \"listings\" left join \"immodb\".\"public\".\"cities\" as \"cities_1\" on \"cities_1\".\"id\" = \"listings\".\"city\" where \"cities_1\".\"id\" = $1 - ungültige Eingabesyntax für Typ integer: »{\"name\":\"Bludesch\"}«",

Is there a workaround?

**Comment by nsoticek** [comment]
> I have the same issue. It is only possible to filter by id. Nested where conditions are not possible.
> 
> This throws an error: query { listingsCount(where: {city: {name: "Bludesch"}}) }
> 
> Error (take a look at the where condition of the query): "message": "select distinct count(*) as "count" from "listings" left join "immodb"."public"."cities" as "cities_1" on "cities_1"."id" = "listings"."city" where "cities_1"."id" = $1 - ungültige Eingabesyntax für Typ integer: »{"name":"Bludesch"}«",
> 
> Is there a workaround?

Found a solution [here ](https://github.com/strapi/strapi/issues/8880#issuecomment-812530192)

**Comment by derrickmehaffy** [comment]
should not be an issue in Strapi v4 but if others do hit this in v4 let us know.
