### ISSUE TITLE
unable to change table name from user-permissions* to user_permissions*

### ISSUE THREAD

**Issue by rvigneshw** [strapi/strapi#8611]
### Describe the bug

unable to change table name from user-permissions* to user_permissions* only user_permissions_user is changed not user_permissions_components it remains user-permissions_components

### Steps to reproduce the behavior

1. Go to 'User.settings.json'
2. Change "collectionName": "users-permissions_user", to "collectionName": "users_permissions_user",

### Expected behavior

Change in all related table names

strapi v. 3.2.5 (node v12.18.3)

**Comment by derrickmehaffy** [comment]
Hi @rvigneshw per #1114 Strapi won't automatically rename the table, can you shutdown your server, delete the new table for users, and rename the existing one?

Please let me know if that works.

**Comment by rvigneshw** [comment]
Yeah, that works!
