### ISSUE TITLE
Can't use Strapi v3.3.0 at Google App Engine

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#8614]
### Describe the bug

After upgrading from `v3.2.5` to `v3.3.1` we have a server error:

>Error while running command start: EROFS: read-only file system, open '/workspace/.strapi-updater.json.2714151597'

### Steps to reproduce the behavior

Deploy app to Google App Engine.

### Expected behavior

Working...

### System

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.3.1
- Database: MongoDB
- Operating system: macOS

**Comment by alexandrebodin** [comment]
You can disable the feature using the env var `STRAPI_DISABLE_UPDATE_NOTIFICATION` documented here: https://strapi.io/documentation/v3.x/concepts/configurations.html#environment-variables

**Comment by abdonrd** [comment]
Thanks @alexandrebodin! But still not working:

<img width="1050" alt="Screenshot 2020-11-10 at 17 58 33" src="https://user-images.githubusercontent.com/1007051/98705806-660e5980-237e-11eb-8812-dd48c5254c86.png">

**Comment by petersg83** [comment]
You’re right, the error throws at the very beginning when the configstore is intanciated. We will need to wait for the fix to be merged and released then

**Comment by derrickmehaffy** [comment]
@abdonrd can you try to patch this in manually and test in your env? (use the local modules part of the package.json)

**Comment by derrickmehaffy** [comment]
(For those unsure how do to this in testing):

https://stackoverflow.com/questions/14381898/local-dependency-in-package-json

basically copy the strapi package folder from node_modules into something like ./packages at the root of the project. Then set the "version" to something like:
`"strapi": "file:./packages/strapi"`

This way you can "test" in a "deployable" environment

**Comment by abdonrd** [comment]
@derrickmehaffy yeah, it works now!
