### ISSUE TITLE
Adding support for MySQL relationships? 

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#862]
**Node.js version:**
9.8
**npm version:**
5.5.1
**Strapi version:**
3.0.0-alpha.11
**Operating system:**
Windows 10

**Do you want to request a feature or report a bug?**

request a feature

**What is the current behavior?**

Relationships added to content-types are always two-way and requires the specification of 2 variables, one for each of the content-types. I assume these are supposed to be the arrays or variables in which the content-type is stored. However this gives a lot of issues when working with a MySQL database. I currently can only use MySQL with seperate tables, and default data types like strings. This is my table creation script for product content-type, and it currently works (just not with relationships):

`CREATE TABLE 'items' (
  'id' mediumint(9) NOT NULL AUTO_INCREMENT,
  'created_at' varchar(255) NOT NULL,
  'name' varchar(255) NOT NULL,
  'updated_at' varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) 
`

**What is the expected behavior?**

Adding support for MySQL relationships, or documentation on how to map relationships in a mysql database. Perhaps rendering a table creation script for the user to implement in his server after creating a new content-type?

**Comment by ArkhipovK** [comment]
You also may use one-to-one relation. But it is impossible to render realtion fields now.

**Comment by Aurelsicoko** [comment]
@piere129 I'm closing this issue. The solution proposed by @ArkhipovK is working perfectly (one-way relationship).

**Comment by piere129** [comment]
@ArkhipovK @Aurelsicoko  could you explain how you got this to work? I am struggling to understand how exactly to configure the json to handle this one-way relation. I get how adding new attributes works with the json for strings & booleans etc. , but not how to link an attribute to another content-type.

**Comment by Aurelsicoko** [comment]
@piere129 If you want to make a one-way relationship, for example, an article has an author, you've to update your `Article.settings.json` model like this:

```js
// Article.settings.json
{
  "connection": "default",
  "collectionName": "article",
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "multiple": false
    },
    "content": {
       "type": "text"
    },
    "author": {
      "model": "user",
      "plugin": "users-permissions"
    }
  }
}
```

However, you won't be able to retrieve all the articles related to a user. To do that, you've to make a one-to-many relationship between Article and User.

```js
// Article.settings.json
{
  "connection": "default",
  "collectionName": "article",
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "multiple": false
    },
    "content": {
       "type": "text"
    },
    "author": {
      "model": "user",
      "via": "articles",
      "plugin": "users-permissions"
    }
  }
}
```

```js
// User.settings.json
{
  "connection": "default",
  "collectionName": "user",
  "attributes": {
    "username": {
      "type": "string",
      "required": true
    },
    "email": {
       "type": "email"
    },
    "articles": {
      "collection": "article",
      "via": "author"
    }
  }
}
