### ISSUE TITLE
Upload of large files fails on AWS deployment

### ISSUE THREAD

**Issue by nicolam1** [strapi/strapi#8620]
##  Bug report
When uploading a large video (mp4) file the request gets aborted.
The file I'm trying to upload is less than the 200MB configured for formidable
The request fails as a `502 bad gateway`

### Logs from the server
```
2020-11-11T03:27:23.336-05:00	at IncomingMessage.<anonymous> (/strapi/apps/strapi/node_modules/formidable/lib/incoming_form.js:122:19)
2020-11-11T03:27:23.336-05:00	at IncomingMessage.emit (events.js:314:20)
2020-11-11T03:27:23.336-05:00	at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2020-11-11T03:27:23.336-05:00	at abortIncoming (_http_server.js:533:9)
2020-11-11T03:27:23.336-05:00	at socketOnClose (_http_server.js:526:3)
2020-11-11T03:27:23.336-05:00	at Socket.emit (events.js:326:22)
2020-11-11T03:27:23.336-05:00	at Socket.EventEmitter.emit (domain.js:483:12)
2020-11-11T03:27:23.336-05:00	at TCP.<anonymous> (net.js:676:12)
```

### Steps to reproduce the behavior
1. Go to 'Media Library'
2. Click on 'Upload Assets'
3. Select a video file that is larger than 20MB
3. Click on 'Upload 1 asset to the library'
4. Wait and see the upload fail.

### Expected behavior
Should work

### System
- Node.js version: 12.18
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database:  Postgres
- Operating system: Linux

### Additional context
Initially it was failing due to a timeout at the load balancer level in AWS but that's not the issue anymore. Now the file makes it to the node logic but it gets aborted. `parser` is enabled and configured correctly based on the documentation.
We are also using the s3 upload plugin. Locally everything works correctly.

**Comment by derrickmehaffy** [comment]
Can you provide your parser config, also can you test with a fresh project on the latest version? (Current latest is v3.3.2)

**Comment by nicolam1** [comment]
@derrickmehaffy this is what I have

```
module.exports = {
  settings: {
    request: {
      session: {
        enabled: true,
        client: `cookie`,
        key: `strapi.sid`,
        prefix: `strapi:sess:`,
        secretKeys: [
          `mySecretKey1`,
          `mySecretKey2`,
        ],
        httpOnly: true,
        maxAge: 86400000,
        overwrite: true,
        signed: false,
        rolling: false,
      },
      logger: {
        level: `debug`,
        exposeInContext: true,
        requests: true,
      },
      parser: {
        enabled: true,
        multipart: true,
        includeUnparsed: true,
      },
    },
....
```

**Comment by derrickmehaffy** [comment]
Thank you, I'll do some testing myself, but please also test in your environment with a fresh latest version as we don't generally troubleshoot bugs on older versions unless they can reproduced on the latest version.

Fixes are also not backported, so if the bug is confirmed it will be in the release after the PR is merged (meaning you will have to update to it anyway)

**Comment by derrickmehaffy** [comment]
I am able to reproduce the issue, either we have a bug or our documentation is lacking. I'm reached out to our backend engineers to clarify.

Just as example this is what I'm currently using (not working):

**Path:** `./config/plugins.js`

```js
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      sizeLimit: 536870912,
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      region: env('AWS_REGION'),
      params: {
        Bucket: env('AWS_BUCKET'),
      },
    },
  },
  // ...
});
```

**Path:** `./config/middleware.js`

```js
module.exports = {
  parser: {
    enabled: true,
    multipart: true,
    jsonLimit: "16mb",
    formLimit: "512mb",
    formidable: {
      maxFileSize: 536870912
    }
  },
}
```

**Comment by derrickmehaffy** [comment]
Actually I just realized that I am blind :see_no_evil: 

The parser settings need to be in a `settings` object like so:

```js
module.exports = {
  settings: {
    parser: {
      enabled: true,
      multipart: true,
      jsonLimit: "16mb",
      formLimit: "512mb",
      formidable: {
        maxFileSize: 536870912,
      },
    },
  },
};
```

After that the upload worked fine:
![image](https://user-images.githubusercontent.com/8593673/99558997-8b542680-2981-11eb-9a0c-be46f24ece40.png)

**Comment by derrickmehaffy** [comment]
Marking as closed but adding this as feedback to refactor/cleanup the middleware documentation

**Comment by nicolam1** [comment]
> I am able to reproduce the issue, either we have a bug or our documentation is lacking. I'm reached out to our backend engineers to clarify.
> 
> Just as example this is what I'm currently using (not working):
> 
> **Path:** `./config/plugins.js`
> 
> ```js
> module.exports = ({ env }) => ({
>   // ...
>   upload: {
>     provider: 'aws-s3',
>     providerOptions: {
>       sizeLimit: 536870912,
>       accessKeyId: env('AWS_ACCESS_KEY_ID'),
>       secretAccessKey: env('AWS_ACCESS_SECRET'),
>       region: env('AWS_REGION'),
>       params: {
>         Bucket: env('AWS_BUCKET'),
>       },
>     },
>   },
>   // ...
> });
> ```
> 
> **Path:** `./config/middleware.js`
> 
> ```js
> module.exports = {
>   parser: {
>     enabled: true,
>     multipart: true,
>     jsonLimit: "16mb",
>     formLimit: "512mb",
>     formidable: {
>       maxFileSize: 536870912
>     }
>   },
> }
> ```

I think this part would be great to add to the documentation because it's not what's online right now. I will test and confirm it works. Thank you for helping on this

**Comment by derrickmehaffy** [comment]
It is now :) https://strapi.io/documentation/v3.x/plugins/upload.html#configuration

But yes we do plan a major refactoring of the middleware documentation itself.

**Comment by nicolam1** [comment]
@derrickmehaffy I've actually tried this configuration and deployed it to AWS. The error is still exactly the same no changes at all. I see from your screenshot you are testing this locally. But I never had issues running this locally either.
Below is my current middleware configuration:

```
module.exports = {
  settings: {
    request: {
      session: {
        enabled: true,
        client: `cookie`,
        key: `strapi.sid`,
        prefix: `strapi:sess:`,
        secretKeys: [
          `mySecretKey1`,
          `mySecretKey2`,
        ],
        httpOnly: true,
        maxAge: 86400000,
        overwrite: true,
        signed: false,
        rolling: false,
      },
      logger: {
        level: `debug`,
        exposeInContext: true,
        requests: true,
      },
    },
    response: {
      gzip: {
        enabled: true,
      },
      responseTime: {
        enabled: false,
      },
      poweredBy: {
        enabled: true,
        value: `Strapi <strapi.io>`,
      },
    },
    security: {
      csp: {
        enabled: true,
        policy: [`block-all-mixed-content`],
      },
      p3p: {
        enabled: true,
        value: ``,
      },
      hsts: {
        enabled: true,
        maxAge: 31536000,
        includeSubDomains: true,
      },
      xframe: {
        enabled: true,
        value: `SAMEORIGIN`,
      },
      xss: {
        enabled: true,
        mode: `block`,
      },
      cors: {
        enabled: true,
      },
      ip: {
        enabled: false,
        whiteList: [],
        blackList: [],
      },
    },
    cors: {
      origin: ['*'],
    },
    parser: {
      enabled: true,
      multipart: true,
      jsonLimit: "16mb",
      formLimit: "512mb",
      formidable: {
        maxFileSize: 536870912,
      },
    },
  },
}
```

and s3 plugin configuration

```
upload: {
      provider: 'aws-s3',
      providerOptions: {
        sizeLimit: 536870912,
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_SECRET_ACCESS_KEY'),
        region: env('S3_REGION'),
        params: {
          Bucket: env('MEDIA_BUCKET'),
        },
      },
    },
```

Am I missing something?

**Comment by derrickmehaffy** [comment]
No that config should be working fine (btw your middleware.js, those configs don't need to be inside of `request` / `response` / `security` object. You also don't need to define them if you aren't changing the defaults)

**Comment by Tyronwilliam** [comment]
Hi 3 years after, i have the same issue with AWS and Strapi hosting on Railway 
It seems to be an issue when uploading large amount of picture for my website or video 

Let me know, if someone manage to find a solution 

![image](https://github.com/strapi/strapi/assets/70233964/c28452ef-afaf-4639-985c-0e736848430f)
![image](https://github.com/strapi/strapi/assets/70233964/76f0fc8e-b139-48d0-82b8-cb8625dfea47)
![image](https://github.com/strapi/strapi/assets/70233964/95dae22b-6229-4dad-a071-a175d86c9d44)
