### ISSUE TITLE
I am not able to set custom path in S3 provider provided by Strapi

### ISSUE THREAD

**Issue by xcorman** [strapi/strapi#8626]
I am following this [docs](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters) but even after  I add path to the configuration, still uploaded files uploads to the root of the S3 bucket.

here is the JSON file of my `settings.json`
```{
  "provider": "aws-s3",
  "providerOptions": {
    "accessKeyId": "ACCESS_KEY",
    "secretAccessKey": "SECRET_KEY",
    "region": "us-east-1",
    "params": {
      "Bucket": "BUCKET_NAME",
      "path": "uploads/"
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by xcorman** [comment]
Node.js version: v14.15.0
NPM version: 6.14.8
Strapi version: 3.3.2
Database: MongoDB Atlas
Operating system: Windows 10 x64

**Comment by derrickmehaffy** [comment]
@xcorman 

> "path": "uploads/"

That's not a valid configuration option, you define the path when you upload a file. I don't think we have this option inside the Admin Upload plugin UI and I'll have to confirm, but for specific paths you can see this in the following documentation:

https://strapi.io/documentation/v3.x/plugins/upload.html#upload-files-related-to-an-entry

**Comment by beingsaumyadeep** [comment]
@derrickmehaffy how to set the request parameters mentioned here for S3 https://strapi.io/documentation/v3.x/plugins/upload.html#request-parameters? 
I need to add a path to my bucket location.

**Comment by xcorman** [comment]
@derrickmehaffy how to set the request parameters mentioned here for S3 https://strapi.io/documentation/v3.x/plugins/upload.html#request-parameters?
I need to add a path to my bucket location.

**Comment by derrickmehaffy** [comment]
If you are uploading the file via REST you just set the folder path to the `path` key in your formdata.

**Comment by xcorman** [comment]
@derrickmehaffy this was written in the request parameter https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters. And I was uploading from Media Library not via REST API. If you can figure it out then it would be easier for me, 
Thanks

**Comment by derrickmehaffy** [comment]
@xcorman currently we don't support them in the Media Library, see: https://github.com/strapi/strapi/issues/8612

**Comment by ekfn** [comment]
Hi! Can we reopen this? There are folders now in Media Library, but seems like s3 provider doesn't use them.

**Comment by derrickmehaffy** [comment]
> Hi! Can we reopen this? There are folders now in Media Library, but seems like s3 provider doesn't use them.

Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
