### ISSUE TITLE
Nested Dynamic Zones with Components and Relations GraphQL Populate

### ISSUE THREAD

**Issue by surgeharb** [strapi/strapi#8628]
### Describe the bug

I have a collection type `Pages` containing dynamic zone content.
Inside this dynamic zone I have a component which has `one to many relation` to a collection type `Grid Components`.
Inside `Grid Components` collection type I have a dynamic zone `content` that has data.
This last dynamic zone is always returning null in GraphQL and not returned in REST at all.

### Steps to reproduce the behavior

1. Setup Strapi locally
2. Create collection type `Grid Components` with field dynamic zone with any component
3. Create component `X` with field Relation `one to many Grid Components`
4. Create collection type `Pages` with field dynamic zone containing component `X`
5. Fill all the nested data (at least 1 item in each collection type and dynamic zones)
6. Try to populate all the nested dynamic zone's data in GraphQL then the issue in the screenshot appears.

### Expected behavior

The last dynamic zone should not return null in GraphQL, instead it should return populated data (using GraphQL for this expected behavior initially)

### Screenshots

Notice second object inside `Sections` has `components` that all its objects has content `null`.

<img width="1436" alt="Screen Shot 2020-11-12 at 11 52 57 AM" src="https://user-images.githubusercontent.com/22060043/98924718-d1227200-24dd-11eb-8a45-59ec30cb334e.png">

### System

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.2.5
- Database: Postgres v12
- Operating system: MacOS Catalina

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7454

Thank you for the additional information.
