### ISSUE TITLE
strapi-plugin-documentation: settings.json can't override property "components"

### ISSUE THREAD

**Issue by andreamarchetti** [strapi/strapi#8629]
### Describe the bug
Default property `"components"` is not modified by custom `settings.js` file as [described here](https://strapi.io/documentation/3.0.0-beta.x/plugins/documentation.html#settings) 

### Steps to reproduce the behavior

1. open file `./extensions/documentation/config/settings.json`
2. add a entry in `"securitySchemes"` under `"components"` (for instance)
3. reboot/regenerate documentation
4. open generated file `./extensions/documentation/documentation/1.0.0/full_documentation.json`
5. search for `securitySchemes`
6. see error: only default entry `bearerAuth` securityScheme is available.

### Expected behavior

Custom securitySchemes should be available in generated documentation.

### What happens

Default components is appendend to output JSON as-is

in file `services/Documentation.js`
```javascript
const defaultComponents = require('./utils/components.json');
```
then
```javascript
    const fullDoc = _.merge(
      appDoc.reduce((acc, current) => {
        return _.merge(acc, current);
      }, defaultSettings),
      defaultComponents
      // { tags },
    );
```

Moreover, default settings are overrided only for properties set in default file

```javascript
const defaultSettings = require('../config/settings.json');

// keys to pick from the extended config
const defaultSettingsKeys = Object.keys(defaultSettings);
```
and `../config/settings.json` doesn't contain a `"components"` property (since at the moment it specified in `components.json`) 

### A possible solution

- Remove `'./utils/components.json` and move its entries to `../config/settings.json`
- Add other missing properties to `../config/settings.json` as [described here](https://strapi.io/documentation/3.0.0-beta.x/plugins/documentation.html#settings) 
- Remove references to `defaultComponents` (line `13` and `506` in file `services/Documentation.js`)

**Comment by derrickmehaffy** [comment]
@andreamarchetti thank you, if you are willing to submit a PR please do.

Was able to confirm this on v3.3.3

**Comment by jokaio** [comment]
Hi @andreamarchetti could you please create an up-to-date PR including your fix commit?

**Comment by bogdanrn** [comment]
I've come across this issue as well, but the solution i found is quite simple. The main problem why the user defined settings are ignored is because [defaultSettingsKeys](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/services/Documentation.js#L19) are initialised without the `components` property on them. 

Later on in the code ([line 510](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/services/Documentation.js#L510)) 

```
   const defaultSettings = _.cloneDeep(
      _.pick(strapi.plugins.documentation.config, defaultSettingsKeys)
    );
```

User defined settings are stripped of any `components` specified and reinitialised with the default values. 

My solution is to just add an empty 
``` 
...
"components": {},
...
```` 
to the default [settings.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/config/settings.json), rest of the code will work as initially intended, but it will now take into consideration user inputs.

**Comment by bogdanrn** [comment]
@jokaio i did a PR from a cloned master branch, but the lint is failing for something related to CSS which i did not touch. What should i do in this situation?

**Comment by derrickmehaffy** [comment]
@bogdanrn it's not an issue with your PR, it was related to another issue. We already created a patch: https://github.com/strapi/strapi/pull/9560

I'll manually retrigger your PR's tests

**Comment by bogdanrn** [comment]
I fixed and synced the PR, thanks!

**Comment by gilmarllen** [comment]
> I've come across this issue as well, but the solution i found is quite simple. The main problem why the user defined settings are ignored is because [defaultSettingsKeys](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/services/Documentation.js#L19) are initialised without the `components` property on them.
> 
> Later on in the code ([line 510](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/services/Documentation.js#L510))
> 
> ```
>    const defaultSettings = _.cloneDeep(
>       _.pick(strapi.plugins.documentation.config, defaultSettingsKeys)
>     );
> ```
> 
> User defined settings are stripped of any `components` specified and reinitialised with the default values.
> 
> My solution is to just add an empty
> 
> ```
> ...
> "components": {},
> ...
> ```
> 
> to the default [settings.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/config/settings.json), rest of the code will work as initially intended, but it will now take into consideration user inputs.

In my case I'd like to add some global components on config/settings.json . So I've tried to insert a components field as you mentioned but with some components definitions inside it. But it didn't work, these components weren't added in the full_documentation.json file. Should I change something else to make it work?

**Comment by semiaddict** [comment]
@gilmarllen, did you add `"components": {}` into the default settings file "_node_modules/strapi-plugin-documentation/config/settings.json_" ? You also need to rebuild afterwards.
This works for me, but should not really be done on production as the change will be overridden when you update the plugin.
The only real option for now is to wait for the pull request to be merged.
