### ISSUE TITLE
Filtering on request url doesn't work

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#863]
**Node.js version**:
9.8
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.11
**Operating system**:
Windows 10

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

creating an url request with a filter (f.e.: `/product?name=bike`) gives the following error:
`[2018-03-28T08:44:04.103Z] error The operator "undefined" is not permitted
[2018-03-28T08:44:04.103Z] debug GET \product?name=bike (13 ms)
`

Sorting with 'product?_sort=name' works as expected. My guess is that there needs to be an operator for filters like = or _gte, a bit like the sorting happens by first calling _sort in the query.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

1) create new GET API request by editing the request url from its' default form to one with parameters as in the example stated above
2) strapi throws new error, also stated above, no products get returned. 

**What is the expected behavior?**

API request filters the results and returns only the products whose names are 'bike'

**Comment by piere129** [comment]
My bad, I forgot to mention that I use MySql server! I'll update my Strapi to see if it works

**Comment by piere129** [comment]
Update: I installed the newest Strapi version and tried again. Unfortunately the error persists. Is it possible using a MySQL database causes this? As I stated before, using the _sort, _limit or _start operators works like it should.

**Comment by lauriejim** [comment]
I think it's probably coming from bookshelf models.

Can you log `convertedParams` in your api service fetchAll function. It's possible the bug come from here.

It's could be great if you are able to find with logs where the bug come from, fix it and submit a PR.

**Comment by bugvish** [comment]
Quick fix:
For each API (aka "Content Type") generated through the Content Type Builder, edit line 28 of /api/{content-type}/services/{content-type}.js as follows:

Replace
        qb.where(key, where.symbol, where.value);
with
        qb.where(key, where[0].symbol, where[0].value);

**Comment by lauriejim** [comment]
@piere129 or @bugvish The issue come from this function https://github.com/strapi/strapi/blob/master/packages/strapi-utils/lib/models.js#L443
That render an array for bookshelf where `type === "="`

The good way to fix it is to investigate here https://github.com/strapi/strapi/blob/master/packages/strapi-bookshelf/lib/index.js#L601
And send an object instead of array.

**Comment by lauriejim** [comment]
@piere129 Fixed here https://github.com/strapi/strapi/pull/895 will be publish on the next version of Strapi
