### ISSUE TITLE
Error from strapi-plugin-graphql/services/build-aggregation.js

### ISSUE THREAD

**Issue by kibong-moon** [strapi/strapi#8630]
[gql-error-result.json.txt](https://github.com/strapi/strapi/files/5530045/gql-error-result.json.txt)

### Describe the bug

Hi,

I'm implementing cursors using connection queries that are auto-generated by Strapi.
Fetching data with limit and start argument incrementally is okay.
But I found avg resolver on number fields in the aggregate might be problematic because the first fetch was okay but next fetch reports error though there was no change.

### Steps to reproduce the behavior

1. Testing environment
1.1. The project is created with quickstart mode and using SQLite3 as its backend database.
1.2. I've created a new collection type as follows:

```json
{
  "kind": "collectionType",
  "collectionName": "comments",
  "info": {
    "name": "comment",
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "content": {       "type": "text"     },
    "writer": {
      "plugin": "users-permissions",
      "model": "user",
      "via": "comments"
    },
    "article": {
      "model": "article",
      "via": "comments"
    },
    "rating": {
      "type": "integer"
    }
  }
}
```

1.3. You need to have another collection type called "article" to be referenced by the above "comment".
1.4. Created 11 comments.
2. Go to GraphQL Playground
```
query getCommentsOnArticleByConnection(
  $limit: Int = 10, $start: Int, $where: JSON!
	) {
  commentsConnection (limit: $limit, start: $start, where: $where) {
    values {
      id
      content
    }
    aggregate {
      count
      totalCount
      avg {
        rating
      }
    }
  }
}
```

Set query variables like this:

```json
{
  "limit": 3,
  "start": 0,
  "where": {"article": "1"}
}
```

Run the query and it shows the result as I expect.

3. Change the value of the "start" variable to 3 or whatever and run the query again.
4. See error like the attached file.

### Expected behavior

Because there is no change in the query variables except "start", the avg value should be the same. And there is no 'null' values in my collection. So the error is weird to me.

### Screenshots

The first fetch result is okay as you see from the screenshot.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/32530522/98931671-ac4fee00-2521-11eb-9355-1ed00b664dd7.png">

But the second fetch is not.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/32530522/98931845-e91be500-2521-11eb-8073-df26fc56c3c2.png">

### Code snippets

N/A

### System

- Node.js version: v14.15.0
- NPM version: 6.14.8
- Strapi version: 3.2.4
- Database: sqlite
- Operating system: macOS Catalina v10.15.7

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7547

But thanks for the additional info
