### ISSUE TITLE
Cannot read property 'confirmed' of null when sending email confirmation

### ISSUE THREAD

**Issue by tqwewe** [strapi/strapi#8633]
### Describe the bug

When making a request to `/auth/send-email-confirmation` with an email address that has not been registered, the following error is thrown:

> Cannot read property 'confirmed' of null

### Steps to reproduce the behavior

1. Enable `sendemailconfirmation` to the public API
2. Make a POST request to `/auth/send-email-confirmation` with a body of `{"email":"invalidemail@invalid.com"}`
3. See error in terminal

### Expected behavior

There should be a check in place in case the user does not exist.

### Screenshots

N/A

### Code snippets

N/A

### System

- Node.js version: v14.4.0
- NPM version: v14.4.0
- Strapi version: 3.2.5
- Database: postgres
- Operating system: Mac OSX

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Can confirm this on v3.3.3 but we shouldn't be leaking the information if a user is registered or not. Simply replying with "if this email is registered, you will get an email" (this would normally be done on the frontend side, so for us probably just an `okay` response)

**Comment by Acidic9** [comment]
Just did an upgrade to v3.3.3 and the error still persists.

**Comment by cvyankatesh** [comment]
Facing the same issue

**Comment by derrickmehaffy** [comment]
Will need testing in v4

**Comment by alexandrebodin** [comment]
This was fixed in v4 :) Going to close this issue.
