### ISSUE TITLE
Slugify not working with unpublishing content

### ISSUE THREAD

**Issue by pedrolaxe** [strapi/strapi#8635]
## Bug report

Slugify is not working with unpublishing content, when i tried to unpublish, shows error 500

### Steps to reproduce the behavior
Slugify is correct installed on version 1.4.6, but not change posts to unpublished.

### Screenshots
![](https://i.imgur.com/82ubPbF.png)
### Slug on models.js
![](https://i.imgur.com/BOLaKzp.png)
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.3.2
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
