### ISSUE TITLE
multisite support

### ISSUE THREAD

**Issue by cocodrino** [strapi/strapi#8636]
I think that a multisite support would be perfect for strapi because due to its headless nature you could, from a single instance, deploy to multiple sites, for example, if I want to create 5 stores, instead of installing strapi in separate instances, with the subsequent consumption of resources, I cold choose to just have a strapi instance running and deploy to 5 sites in gatsby, it is cheap and efficient to management  it what do you think about this?

thank you so much

**Comment by derrickmehaffy** [comment]
Duplicate: https://portal.productboard.com/strapi/1-roadmap/c/36-multi-tenancy

Thank you for the additional feedback :smiley:
