### ISSUE TITLE
Admin UI bug: Text in buttons in the admin dashboard isn't vertically centered on Ubuntu 20.04

### ISSUE THREAD

**Issue by anotherssa** [strapi/strapi#8638]
### Describe the bug

Text in buttons isn't vertically centered. See the screenshot below.

### Steps to reproduce the behavior

1. Go to the admin dashboard 
2. Look at the buttons
3. See the bug

### Expected behavior

Text in buttons vertically centered.

### Screenshots

![image](https://user-images.githubusercontent.com/18227850/99011707-5f860a80-2555-11eb-879c-604ed7624b87.png)

### System

- Strapi version: 3.3.2
- Operating system: Ubuntu 20.04

**Comment by vczb** [comment]
I believe the problem of aligning button content is Buffett's. What do you think ?

![Captura de tela de 2021-06-19 18-30-28](https://user-images.githubusercontent.com/51221635/122655909-a1e77980-d12c-11eb-8b66-9d3678319c45.png)

https://buffetjs.io/storybook/?path=/story/components--button

**Comment by derrickmehaffy** [comment]
should be fixed in v4 with the design-system
