### ISSUE TITLE
Forgot password doesn't work: 502

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#864]
**Node.js version**: v9.8.0
**npm version**: 5.8.0
**Strapi version**: 3.0.0-alpha.11
**Operating system**: macOS

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Forgot password doesn't work.

After 2min waiting for `POST /auth/forgot-password`, the response is:
> 502 Bad Gateway: Registered endpoint failed to handle the request.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

1. Go to: domain.com/admin/plugins/users-permissions/auth/forgot-password
2. Enter your email and click the button.
3. Check the network on Dev Tools.

**What is the expected behavior?**

Forgot password working.

**Comment by lauriejim** [comment]
Okay @abdonrd, I will check that :shipit: !

**Comment by lauriejim** [comment]
@abdonrd Did you check what is the response of the email plugin service.
I think it could coming from the node module we use.

**Comment by abdonrd** [comment]
@lauriejim I have to investigate it better since I have just verified that it works locally.
Where it fails is in the online version (on IBM Cloud).

**Comment by lauriejim** [comment]
We use `sendmail` node modules by default in `email` plugin. But it doesn't use SMTP server and I think your email are blocked.

So for production application I suggest to use something like `nodemailer` and set an approved SMTP server.

**Comment by abdonrd** [comment]
@lauriejim for that it is necessary to modify the plugin itself, right? I don't see any configuration option.

**Comment by lauriejim** [comment]
Yes that's it.

**Comment by dsheyp** [comment]
hi

for evaluation purposes I installed strapi for the first time, then created a user for the admin tool etc. etc... and the next day I had forgotten username and password. what I remembered was the email I had provided. so I went through the reset password process, got an email with a link which I followed. This brought me back to the login form, where I was asked to enter username and password.... which of course I didn't remember.
-> It seems the "reset Password" functionality doesn't do a useful thing.

After that I deleted the test project and recreated it with the same name. My previous user persisted this process, so I still wasn't able to login. What finally helped was to go to the mongodb users-permissions_user table and read the username. This also led me to my password, as I had it chosen to be almost the same as the username.

Just thought I share my experience with resetting my password. I had expected being provided with the possibility to just enter/repeat a new password during the process and then coming back to my existing account. This didn't happen. May be a bug? Or just my installation/setup?

Best
dsheyp

**Comment by Kinzi** [comment]
I have a similar issue. 

When trying to reset the password I get: "This email is invalid." (400 from API) BUT it's the exact same email as in the db document here: `collections/users-permissions_user`

strapi 3.0.0-alpha.12.1.2
node 10

**Comment by yummyelin** [comment]
Using postman will get 400.
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.invalid"
                }
            ]
        }
    ]
}
```

I am sending email to a zoho email. so the error message is:
The error is coming from (/plugins/email/services/Email.js: line 32)

```
Error: SMTP code:550 msg:550 Mail rejected by <Zoho Mail> for policy reasons. 
We generally do not accept email from dynamic IP's as they are typically used to deliver 
unauthenticated SMTP e-mail to an Internet mail server. http://www.spamhaus.org 
maintains lists of dynamic and residential IP addresses. If you are not an email/network 
admin please contact your E-mail/Internet Service Provider for help. Email/network 
admins, please contact <support@zohomail.com> for email delivery information and 
support
```

As discussed above, I guess I need to modify plugin 'email'.

**Comment by yummyelin** [comment]
Go to /plugins/email, `npm install --save nodemailer`

Open /plugins/email/services/Email.js
```
const nodemailer = require('nodemailer');
const EMAIL_SENDER_USER = 'xxx@gmail.com';
const EMAIL_SENDER_PASS = 'xxx';
```

```
      // Send the email.
      // sendmail({
      //   from: options.from,
      //   to: options.to,
      //   replyTo: options.replyTo,
      //   subject: options.subject,
      //   text: options.text,
      //   html: options.html
      // }, function (err) {
      //   console.log(err);
      //   if (err) {
      //     reject([{ messages: [{ id: 'Auth.form.error.email.invalid' }] }]);
      //   } else {
      //     resolve();
      //   }
      // });

      const transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
          user: EMAIL_SENDER_USER,
          pass: EMAIL_SENDER_PASS,
        },
      });

      transporter.sendMail(options)
        .catch(err => reject([{ messages: [{ id: 'Auth.form.error.email.invalid' }] }]));
```

**Comment by guillermodoghel** [comment]
@yummyelin that works great, thanks!

some nice to have would be to put the smtp config inside a json or something

**Comment by lauriejim** [comment]
We are working on it https://github.com/strapi/strapi/issues/911 and PR here https://github.com/strapi/strapi/pull/1255

**Comment by fedecarg** [comment]
The fix provided by @yummyelin no longer works. I was unable to find the call to sendmail() inside `service/Email.js`.
