### ISSUE TITLE
Admin UI bug: Hover for single component

### ISSUE THREAD

**Issue by iksent** [strapi/strapi#8640]
### Describe the bug

This is a bug №1 from https://github.com/strapi/strapi/issues/8608

### Steps to reproduce the behavior

1. Add single (not repeatable) component for item
2. Go to item and try to add this component
3. Click area does not match hover effect area

![hover](https://user-images.githubusercontent.com/32956521/98630235-77cf0d00-233c-11eb-9623-6d3a61ca840a.png)

### Expected behavior

Hover only at icon OR click available on the whole area (better as for me).

### System

- Node.js version: 12.14.0
- NPM version: 6.14.7
- Strapi version: 3.3.1
- Database: MySQL
- Operating system: Windows

**Comment by akhilmhdh** [comment]
@derrickmehaffy Hey there, I can fix it for you and I am already finishing up. But just a doubt which one is preferred
1. Hover to button: just a small css change is need, but I think user expects it to be the whole part as clickable better
2. Need to change the click event from inside button to outside container

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI thoughts?

**Comment by derrickmehaffy** [comment]
Also @maevalienard

**Comment by maevalienard** [comment]
That would be best in my opinion to allow the click on the whole area to make profit of it :)

**Comment by iksent** [comment]
I can confirm that was fixed in 3.3.4 and now works fine, thanks!
