### ISSUE TITLE
Admin UI bug: Problems with long text at repeatable component

### ISSUE THREAD

**Issue by iksent** [strapi/strapi#8641]
### Describe the bug

This is a bug №2 from #8608

### Steps to reproduce the behavior

1. Add a repeatable component for item
2. Go to item and add this component with long text
3. See the overflowing and text-alignment problems:

![repeatable](https://user-images.githubusercontent.com/32956521/98630370-c67ca700-233c-11eb-96f4-a17eb7c40e7c.png)
![2020-11-13_10-15-48](https://user-images.githubusercontent.com/32956521/99031612-4f901a00-2599-11eb-8c4a-d009def7f42d.png)

- Also take a look, that icon's width are also broken, probably need to add `min-width`

### Expected behavior

Text should be left-aligned and may be truncated by ellipsis into 2 lines.

### System

- Node.js version: 12.14.0
- NPM version: 6.14.7
- Strapi version: 3.3.1
- Database: MySQL
- Operating system: Windows

**Comment by vczb** [comment]
Hello, I tried to reproduce the problem and I managed only with short text, not with long. I sent a PR correcting the problem in Short Text

Thank you

**Comment by derrickmehaffy** [comment]
Should be fixed in v4
