### ISSUE TITLE
Add information about accessibility with strapi

### ISSUE THREAD

**Issue by mgifford** [strapi/strapi#8649]
## Feature request

In many communities it is a bug, but I couldn't find anything about accessibility in Strapi from searching the documentation.  Is the authoring interface accessible with people with disabilities? Does it follow WCAG 2.x or as a publishing tool ATAG 2.0

### Please describe your feature request

I'd like a basic description of what work has been done or is planned in Strapi.

### Summary

Is there any testing that has been done with tools like the WAVE Toolbar, or keyboard only testing? What about with screen readers or other assistive technology. 

### Why is it needed?

Because 20% of the population has some form of permanent disability and 100% of the population faces temporary or situational disabilities. It's a requirement for many projects and working with a solid system can greatly assist the work. 

### Suggested solution(s)

I'd like to have a /accessibility page that highlights what is being done on https://strapi.io/accessibility 

I'd like to see an accessibility tag in the github issue queu

I'd like to see several pages in the documentation that outline best practices when using Strapi.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Tagging @Aurelsicoko @sam-pires @JabStrapi

**Comment by sam-pires** [comment]
Hello @mgifford 
Thanks for your interest in Accessibility and how to improve it at Strapi.
That's an important topic for us and we try to make our best to make Strapi the most accessible possible, clearly there is room for improvement here.

I like you suggestions to share more information about it. We'll take them into account!

That would be huge for us if you could help us better identifying accessibility needs and how to improve them. Would you be willing to contribute to Strapi that way?

Right now I am thinking about first creating a space for discussions to collect and centralize feedback about it. I could be on the forum and/or via a RFC (Request for Comments, accessible on a dedicated repository: https://github.com/strapi/rfcs)
What do you think of it?

**Comment by mgifford** [comment]
I can definitely try..  It's not the way I'm used to doing things with other projects, but can at least line up a next step.

**Comment by dbowling** [comment]
It looks like this issue is going a little stale. I'm very new to Strapi, just kicking the tires really, but I have a background in web accessibility and want to do more open source contributions so I think I can help out here if that would be useful. I'd be happy to work on an RFC to start the conversation if it's not going on some other place (I don't see it in strapi/rfcs.)

Happy new year!

**Comment by derrickmehaffy** [comment]
> It looks like this issue is going a little stale. I'm very new to Strapi, just kicking the tires really, but I have a background in web accessibility and want to do more open source contributions so I think I can help out here if that would be useful. I'd be happy to work on an RFC to start the conversation if it's not going on some other place (I don't see it in strapi/rfcs.)
> 
> Happy new year!

We have already started and integrated a lot of accessibility into Strapi v4 but there is still more that can be done. Please feel free to write an RFC and submit it on strapi/rfcs

**Comment by derrickmehaffy** [comment]
Will close this in favor of the author working on an RFC instead
