### ISSUE TITLE
[GraphQL] Add AdminUser type on Morph

### ISSUE THREAD

**Issue by darron1217** [strapi/strapi#8650]
# Feature request
Currently we can add AdminUser as relation.

But it's not available on Polymorphic relation.

### Summary
Adding AdminUser on Morph type would allow us to have admin user on polymorphic relation

**Comment by derrickmehaffy** [comment]
Can you please provide an example use-case for this (how are you planning to use it?)

**Comment by darron1217** [comment]
This issue https://github.com/strapi/strapi/issues/8651 contains my use-case.

I was trying to add `sender` field on `message` model.
The message can be sent by both 'UsersPermissionsUser' and 'AdminUser'.

message.settings.json
```
    "sender": {
      "model": "*",
      "filter": "field"
    }
```
User.settings.json (from `users-permissions` plugin)
```
    "messages": {
      "collection": "message",
      "via": "sender"
    }
```

**Comment by derrickmehaffy** [comment]
Thank you for the information :hugs:
