### ISSUE TITLE
Issues facing with CKEditor for replacing WYSIWYG 

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#8662]
### Describe the bug

We are trying to replace WYSIWYG with CKEditor following this Strapi doc: https://strapi.io/documentation/v3.x/guides/registering-a-field-in-admin.html#introduction

**Issues we are facing:**
1. Slow performance for large size content (mainly for API docs).
2. When uploading Media, it's not converting the media to `md` tag like WYSIWYG field does. (I want the Media to be converted to `md` tag & not just loading Image as it is on the field)
3. Cannot upload `Video` or any other media except `Image`
4. There is no `md` preview system where you can switch between `markDown` & `Preview` like WYSIWYG has.

### Steps to reproduce the behavior

1. Follow this doc for replacing WYSIWYG with CKEditor: https://strapi.io/documentation/v3.x/guides/registering-a-field-in-admin.html#introduction
2. Add `MediaLIb` to it
3. Try to do the above operations and see (add large size content, upload media, try to see md preview)
4. Observe the issues

### Expected behavior

We need CKEditor to have 
1. Better performance for large size content as well.
2. Uploaded media should be converted to `md` tag (not just loading the images as it is)
3. We should be able to upload `Video` & all other media's like how WYSIWYG does (CKEditor only accepting Image)
4. It should has `md` preview system to switch between `md` & `Preview`

### Screenshots

None

### Code snippets

Folloing Strapi docs: https://strapi.io/documentation/v3.x/guides/registering-a-field-in-admin.html#introduction

**System**

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo
- Operating system: MAC

**Additional context**

**Comment by derrickmehaffy** [comment]
Can you try using https://github.com/TechQuery/strapi-plugin-ckeditor 

It's a community plugin that we have listed here: https://github.com/strapi/awesome-strapi

**Comment by soupette** [comment]
Also, I am not sure this is an issue as the guide is more an introduction into how to replace the WYSIWYG in Strapi and then more extended behaviour or needs must be implemented on your side.

**Comment by derrickmehaffy** [comment]
> Also, I am not sure this is an issue as the guide is more an introduction into how to replace the WYSIWYG in Strapi and then more extended behaviour or needs must be implemented on your side.

Agreed, going to mark as closed
