### ISSUE TITLE
Email confirmation link is broken

### ISSUE THREAD

**Issue by sandiprb** [strapi/strapi#8663]
### Describe the bug

The email confirmation link seems to be broken in the latest version while opening the link the below error is received 

``` json
{
     "statusCode":400,
     "error":"Bad Request",
     "message":"Your filters contain a field 'confirmationToken' that doesn't appear on your model definition nor it's relations"
}
```

### Steps to reproduce the behavior

1. Enable email verification for new users
2. Send a signup post request
3. Email is received on registered email address 
4. Click on the confirmation link

### Expected behavior

User should be redirected to email confirmation redirection link after email verification

### Screenshots

![image](https://user-images.githubusercontent.com/18263041/99301233-a6d10b80-2873-11eb-9a63-c3b4c6fb5ec1.png)

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.3.3
- Database: Postgres
- Operating system: Ubuntu 18.03

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.3.3`

Did you follow the migration guide from v3.2.3 to v3.2.4?

https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.2.3-to-3.2.4.html#migration

**Comment by sandiprb** [comment]
That helped. Thanks @derrickmehaffy
