### ISSUE TITLE
Collection doesn't properly update until I exit the "Create entry" screen

### ISSUE THREAD

**Issue by XBShu** [strapi/strapi#8676]
## Bug report
New entries don't get added until I exit the create entry screen. Adding another entry right after only results in the last entry being added to the database. For example, adding "one", "two", and "three" will result in only "three" being added to the collection.

### Steps to reproduce the behavior

1. Click on a collection on the side bar (e.g. "Restaurants") and select "add new restaurant"
2. Fill out data and click save (notification will appear on top of screen)
3. Without exiting the page, fill out data for another restaurant and click save. (notification will appear again)
4. Click on "Restaurants on the sidebar again. Only the second restaurant is present.

### Expected behavior

Both restaurants should have been added to the database

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.3.3 (node v12.18.4) 
- Database: mySQL
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
@XBShu we don't start a new entry now when you save, you will need to back to the list view and hit "add new restaurant" again.

This was changed quite a while ago, per user request.

Marking as closed as functionality is intended.

**Comment by XBShu** [comment]
Thank you for your answer. Is there a way to modify it so that it automatically reroutes the user to the restuarant list once "save" is clicked?
