### ISSUE TITLE
Obscure error message after 'unique' validation fail

### ISSUE THREAD

**Issue by burlakko** [strapi/strapi#8677]
### Describe the bug

The error message for uniqueness validation fail looks like this 
![Screenshot from 2020-11-17 18-50-08](https://user-images.githubusercontent.com/4548361/99423329-1cd38200-2909-11eb-9c88-1c3942c6d8e1.png)
On one hand it's not really a bug, on the other clear validation messages are crucial for any CMS. End user just won't understand what it means.
Also there is no error and no highlight on form field itself, so end user will have no clue why the data is not saved. 

### Steps to reproduce the behavior

1. Sign up `unique` validation to any model attribute in content-types builder.
2. Edit that model so the `unique` validation fails.
3. See the user unfriendly error message.

### Expected behavior

Ideally a clear and concise error message alongside the failed form field and 'error' highlighting the field

### System

- Node.js version: 12.19.0
- NPM version: 6.14.8
- Strapi version: 3.2.1
- Database: Mongo
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8664

**Comment by burlakko** [comment]
@derrickmehaffy It's related but not a duplicate. On v3.2.1 I get 400 response. This issue is about unclear error representation which doesn't give user a clue.

**Comment by derrickmehaffy** [comment]
In that case @burlakko It's likely related to these:

https://github.com/strapi/strapi/issues/6598

We know the error messages that show up in the admin aren't very clear and we plan to dig into this sometime in early 2021.
