### ISSUE TITLE
When is an H1 Ever Relevant for Body Content

### ISSUE THREAD

**Issue by mgifford** [strapi/strapi#8678]
### Describe the bug

H1's shouldn't be used in body text.  Editors can be trained not to use the H1, but why have it in the interface. 

H1's are defined by the title of the article/blog/page.

H2-H6 should be all that is presented. Otherwise we know authors are going to be starting with H1 & there will be multiple H1's in a page because it "looks right".

https://www.nomensa.com/blog/2017/how-structure-headings-web-accessibility
https://www.w3.org/WAI/tutorials/page-structure/headings/
https://developer.paciellogroup.com/blog/2020/03/headings-accessibility/

This would help with ATAG 2.0 compliance. 

### Steps to reproduce the behavior

1. Go to http://localhost:1337/admin/plugins/content-manager/collectionType/application::article.article/4 - this is just a startup from a sample apge
2. Click on "Add a Title"
3. See error

Actually, why is it called a Title?  How many titles are there in a page?  Usually there's just the 1 & the rest are headings. 

Should be just Heading 2 to Heading 6 to make it clear in the text. 

### Expected behavior

You should just see H2-H6 as options for users.

### Screenshots

![List of headings in editor](https://user-images.githubusercontent.com/116832/99427639-a8322080-28d3-11eb-9168-c1a3b5af5e60.png)

![Titles & Titles - The language should change](https://user-images.githubusercontent.com/116832/99428249-62298c80-28d4-11eb-9b2e-eb4563fa9544.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by mgifford** [comment]
I just changed that question to a statement.  Mostly wanted to link it to https://github.com/strapi/strapi/issues/8649

**Comment by derrickmehaffy** [comment]
@mgifford we would rather not limit the editor options at the project level as we are not the ones to make this choice for our users. There are alternatives out there that allow the user to swap out the WYSIWYG editor for others (and customize it to the owners needs).

See: https://github.com/strapi/awesome-strapi

Specifically 

- https://github.com/fagbokforlaget/strapi-plugin-wysiwyg-toastui
- https://github.com/TechQuery/strapi-plugin-ckeditor

It's also quite easy to customize per project by simply editing the following and removing the H1 from here: https://github.com/strapi/strapi/blob/a7156c94717e12d6a4be4e3088907a2327043e3a/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/constants.js#L1-L9

This can be done with our [extensions system](https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#how-do-i-customize-a-plugin)

**Comment by mgifford** [comment]
Hey @derrickmehaffy - thanks again for this.

I'm pretty familiar with working with projects on a global project level. I've been spearheading Drupal's accessibility efforts for much of the last 12 years.  It's a big challenge to build not just for your use case, but for all of the other use cases you know about (or don't know about). 

It's great that you can swap in/out other editors.  Also nice to see that you can just swap it out there in my local install.

When thinking globally it is more important than ever to think about W3C standards.  Your code might work in the browsers you test in, but by Designing with Web Standards (wow that book first came out in 2003), you are making your code more future compatible and flexible for everyone. 

This is an open source project, so just as I'm not limited to taking out `{ id: 'components.Wysiwyg.selectOptions.H1', value: '#' },` someone else isn't limited to add it in if they wanted it there.  The thing is, why would someone want to have it in the body of your CMS. If the community can't come up with some good use cases for having it there, remove it because we know it's making it harder for authors to produce accessible content.

**Comment by mgifford** [comment]
Also, @derrickmehaffy I'm just experimenting here. This isn't a "hill i'd die on", but it's an interesting way to explore this community, how the software is set up and how we might want to work together to make it more robust.  I appreciate your exchanges and understand that this is a closed issue.  

Should this issue ever move ahead, H1 should be removed from the translations (it is there in a number of places).   This shouldn't cause a problem but is cruft that should be cleaned up.  I also didn't find a test for this function, but may have overlooked it. I'm not great at unit testing at the best of times, but didn't find a reference that would flag the change when reviewing the code.
