### ISSUE TITLE
I am getting an error "error occur during record fetch" in strapi ,please help me out

### ISSUE THREAD

**Issue by pawanqualtech** [strapi/strapi#8680]
### Describe the bug
I am getting the error "an error occur during record fetch" in strapi.
I have already deleted the related data from everywhere it is used from database, still getting error.

- Node.js version: 12.19.0
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: moongodb
- Operating system: windows 10

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
