### ISSUE TITLE
Missing file users-permissions/admin/src/components/PopUpForm/index.js

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#8682]
## Bug report
I am following this guide to configure a custom auth provider: [https://strapi.io/documentation/v3.x/plugins/users-permissions.html#adding-a-new-provider-to-your-project](https://strapi.io/documentation/v3.x/plugins/users-permissions.html#adding-a-new-provider-to-your-project)  
And according to it, I have to add PopUpForm/index.js to my files, but there is no PopUpForm inside `extensions/users-permissions/admin/src/components`

### Describe the bug
Can't copy PopUpForm/index.js

### Steps to reproduce the behavior

Go to and see if there is PopUpForm https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-users-permissions/admin/src/components

### Expected behavior

Being able to copy the file

**Comment by derrickmehaffy** [comment]
Thank you @baermathias you are right we changed the structure a bit, you can take a look at the following PR to see what was needed to add a new provider:

https://github.com/strapi/strapi/pull/8362

But I will work with our frontend team and get some updated documentation.

**Comment by baermathias** [comment]
I see that `Providers.js` and `bootstrap.js` are the relevant files. If PopUpForm is not needed anymore, keep in mind that you mention it also here:
https://strapi.io/documentation/v3.x/plugins/users-permissions.html#configure-frontend-for-your-new-provider
https://strapi.io/documentation/v3.x/plugins/users-permissions.html#add-language-translation

**Comment by derrickmehaffy** [comment]
Yup I've added it to our issue board to have our frontend/backend teams clarify this documentation as it does need to be updated.

**Comment by baermathias** [comment]
@derrickmehaffy I don't know how far you are with the clarification of the docs, but there is also another issue, which is a bit confusing. 
`Understanding the login flow` (https://strapi.io/documentation/v3.x/plugins/users-permissions.html#understanding-the-login-flow) at point 4 states:

> Once done, Github redirects the tab to the **backend URL**: https://strapi.website.com/connect/github/callback?code=abcdef

Then you scroll down to 
`Setting up the provider example` (https://strapi.io/documentation/v3.x/plugins/users-permissions.html#setting-up-the-provider-examples) and choose `Github configuration` and there you are told to configure the Authorization callback URL, which is the **frontend** application callback URL??  

So when is Github redirecting to the backend and when is it redirecting to the frontend? And what happens there? IMO there is some missing information.

**Comment by derrickmehaffy** [comment]
Closing as we had a PR to remove the outdated docs on changing files that no longer exist.
