### ISSUE TITLE
strapi-provider-upload-cloudinary - upload_stream requires upload_preset to be passed through.

### ISSUE THREAD

**Issue by cur8s** [strapi/strapi#8685]
### Describe the bug

When using the `cloudinary.uploader.upload_stream` method, Cloudinary ignores the `upload_preset` if set in the `config` variable into `cloudinary.config(config)`.

Instead it would appear that the `upload_stream` method needs it to be passed in explicitly, see [Cloudinary GitHub Reference](https://github.com/cloudinary/cloudinary_npm/issues/174).

When I pass the parameter in (see below "My hacky bodge") the files act as expected. I'm not confident my way is the appropriate way to fix so would rather someone with more confidence went about making the appropriate change.

### Steps to reproduce the behavior

1. Create a cloudinary upload_preset with for example a folder set in it.
2. Add it to plugins
```
module.exports = ({ env }) => ({
    upload: {
        provider: env("MEDIA_PROVIDER", "cloudinary"),
        providerOptions: {
            cloud_name: env("CLOUDINARY_NAME"),
            api_key: env("CLOUDINARY_KEY"),
            api_secret: env("CLOUDINARY_SECRET"),
            upload_preset: env("CLOUDINARY_PRESET", "local"),
        },
    },
});
```

3. Add media, through admin works fine.

### Expected behavior

The media to sit in the folder set through the preset.

#### Default behaviour:
```
//...
    upload(file, customConfig = {}) {
        return new Promise((resolve, reject) => {
          const upload_stream = cloudinary.uploader.upload_stream(
            { resource_type: 'auto', public_id: file.hash, ...customConfig },
            (err, image) => {
              if (err) {
                if (err.message.includes('File size too large')) {
                  return reject(errors.entityTooLarge());
                }
                return reject(errors.unknownError(`Error uploading to cloudinary: ${err.message}`));
              }
//...
```

#### My hacky bodge:
```
//... 
   upload(file, customConfig = {}) {
        return new Promise((resolve, reject) => {
          const upload_stream = cloudinary.uploader.upload_stream(
            { resource_type: 'auto', public_id: file.hash, upload_preset: config.upload_preset, ...customConfig },
            (err, image) => {
              if (err) {
                if (err.message.includes('File size too large')) {
                  return reject(errors.entityTooLarge());
                }
                return reject(errors.unknownError(`Error uploading to cloudinary: ${err.message}`));
              }
//...
```

### System

- Node.js version: 14.13.0
- NPM version: 6.14.8
- Strapi version: 3.3.3
- Database: mysql
- Operating system: Windows 10

**Comment by wommy** [comment]
i think im running into this issue too,

im porting a clients data from a different service, which asked for an upload folder for cloudinary 

im having trouble, because strapi posts in the default directory, and also makes 5 different sized images

previously i uploaded one full size image and used a query to resize thru cloudinary's endpoint 

gonna tinker some more

**Comment by alexandrebodin** [comment]
Hi, 

You can set a per method config to pass to the api like so:

`config/plugin.js`
```js
module.exports = {
  upload: {
    enabled: true,
    config: {
      provider: 'cloudinary',
      providerOptions: {
        cloud_name: '***************',
        api_key: '***************',
        api_secret: '***************',
      },
      actionOptions: {
        uploadStream: {
          upload_preset: 'preset_id',
        },
        upload: {
          upload_preset: 'preset_id',
        },
        delete: {},
      },
    },
  }
}
```
