### ISSUE TITLE
Long space-separated collection type names break the UI

### ISSUE THREAD

**Issue by mijorus** [strapi/strapi#8688]
### Describe the bug

This bug happens in the content-type builder UI, when creating a collection type with a long name
(is pretty bad if the C.T was created by a plugin as it adds markup) 

### How to fix

It is just a matter of adding `white-space: nowrap`, however I can't find the component to send a PR because React uses random class names, making it very hard to find, sorry

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
