### ISSUE TITLE
Issues running swagger-stats as middleware with a dockerized Strapi

### ISSUE THREAD

**Issue by iboudaoud** [strapi/strapi#8691]
### Describe the bug

I'm trying to use swagger-stats as middleware for Strapi's observability. While this module is working fine locally, I'm having an issue running it with a dockerized strappi (If I disable the swagger-stats middleware, everything works fine) 

### Steps to reproduce the behavior

1. Add a middleware for swagger-stats 

Create a file `middlewares/swaggerstats/index.js` with the following code 

```javascript
const swStats = require('swagger-stats'); 
const e2k = require('express-to-koa');
module.exports = strapi => {
  return {
    initialize() {
      strapi.app.use(e2k(swStats.getMiddleware()));
    },
  };
};
```

2. Enable the middleware in the config 

```javascript
module.exports = {
    settings: {
      swaggerstats: {
        enabled: true,
      },
    },
  };
```
3. Add `swagger-stats` module in `package.json`
4. Build and deploy the image using docker with this dockerfile 
```
FROM strapi/base
RUN yarn global add strapi
WORKDIR /srv/app
COPY package.json ./
COPY package-lock.json ./
RUN yarn install
EXPOSE 1337
```
### Expected behavior

The strapi image should be up and running with swagger-stats as middleware. 
Instead, strapi fails to start with the error message below

### Screenshots
![image](https://user-images.githubusercontent.com/5217251/99592074-f9cfcd80-29ef-11eb-9c12-d8e2e7c99007.png)

### Code snippets

N/A

### System

- Node.js version: Using strapi/base docker image
- NPM version: 
- Strapi version: 3.1.1
- Database: mongodb
- Operating system: Linux

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Hi @iboudaoud since swagger-stats is not a Strapi package, please ask questions related to things like that on our forum:

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by iboudaoud** [comment]
Hi @derrickmehaffy, thanks for your reply. I posted this issue beceaus I think there is a  bug in the custom middlewares support while using a dockerized strapi (it's not really related to swagger-stats). But I can try the forum if you think it's more relevant to be posted there. 

Thanks !
