### ISSUE TITLE
Timeout when uploading large video file

### ISSUE THREAD

**Issue by scopsy** [strapi/strapi#8695]
### Describe the bug

When trying to upload a large video file from the media screen the upload timeout after 2 minutes exactly.

### Steps to reproduce the behavior

1. Media
2. Click on upload new media item
3. Try to upload a large video file (80MB) 
4. Upload will timeout after 2 minutes

### Expected behavior

Expecting the file to finish upload correctly by extending the timeout

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2.5
- Database: Mongodb
- Operating system: MacOS

### Additional context

Using the cloudinary image provider

**Comment by derrickmehaffy** [comment]
Tested locally but couldn't reproduce it, I assume it requires a very slow internet connection to upload 80mb in more than 2 minutes :/

**Comment by derrickmehaffy** [comment]
closing as no new information has been provided.
