### ISSUE TITLE
/env for subdirectories like functions

### ISSUE THREAD

**Issue by bglidwell** [strapi/strapi#8696]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Ability to use /env/ scoping for config subdirectories like functions. Allows users to set things like bootstrap.js by environment

### Why is it needed?

bootstrap.js and cron.js may be different depending on environment. Currently only top level js and json files are loaded by environment

### Suggested solution(s)

Recursive directory tree walking for file loading in config loader

**Comment by derrickmehaffy** [comment]
100% agree it would be nice to have bootstrap for environments

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
