### ISSUE TITLE
License? ee/ directory

### ISSUE THREAD

**Issue by guettli** [strapi/strapi#8699]
The License talks about a `ee` directory.

https://github.com/strapi/strapi/blob/master/LICENSE

Maybe it makes sense to update the license since this directory does not exist.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/tree/master/packages/strapi-admin/ee

The license is set globally in all of our repos to keep it simple such as: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/LICENSE

Thank you though :)
