### ISSUE TITLE
Moving Strapi to a Different Hosting

### ISSUE THREAD

**Issue by 360views** [strapi/strapi#8709]
How do you move Strapi deployed at one hosting to another hosting?

How do you export data and configuration for the deployment? Is there an automated solution for that? Any guides on this? This is a killer pain to setup Strapi on another hosting provider.

Please advise.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
