### ISSUE TITLE
Tutorial - Creating an Admin User link on deployment/heroku.html gives 404

### ISSUE THREAD

**Issue by harshil1712** [strapi/strapi#8710]
### Describe the bug

The link to [Tutorial - Creating an Admin User](https://strapi.io/documentation/v3.x/getting-started/quick-start-tutorial.html#_3-create-an-admin-user) on the [deployment/heroku](https://strapi.io/documentation/v3.x/deployment/heroku.html#_9-deploy) page gives a 404.

### Steps to reproduce the behavior

1. Go to [deployment/heroku](https://strapi.io/documentation/v3.x/deployment/heroku.html#_9-deploy)
2. Click on the `Tutorial - Creating an Admin User`
3. The link results in a 404 page.

### Expected behavior

The link should take the user to the tutorial page.

**Comment by derrickmehaffy** [comment]
Closing as issue was resolved in above PR
