### ISSUE TITLE
Problem about CORS policy

### ISSUE THREAD

**Issue by Eldenn** [strapi/strapi#8712]
### Description

Hello everyone !

I created a React app using Strapi for backend and I don't understand how to setup CORS policy.
Strapi is on my online server, and I run React app on my local computer. When I tried to send a request with Axios, there is this problem : 

![Capture d’écran (111)](https://user-images.githubusercontent.com/39029744/99883628-f5dac000-2c28-11eb-87a6-4343923f2cb7.png)

I created the middleware.js file at config folder as it says in the documentation : https://strapi.io/documentation/v3.x/concepts/middlewares.html#configuration-and-activation

```js
module.exports = {
  load: {
    before: ['timer', 'responseTime', 'logger', 'cors', 'responses', 'gzip'],
    after: ['parser', 'router'],
  },
  settings: {
    cors: {
      enabled: true,
      origin: ['*']
    },
  },
};
```

I've looked at all the forums and articles on the subject, I couldn't solve the problem.

### System

- Node.js version: v15.2.1
- Strapi version: 3.3.2 (Community)

**Comment by akhilmhdh** [comment]
Can you just remove that origin option. By default it allows everything and I am assuming it should be `"*"` and not `['*']`

**Comment by Eldenn** [comment]
I tried with that, but unfortunately this did not solve this issue :(

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
