### ISSUE TITLE
Creating a collection type named "series" returns an error

### ISSUE THREAD

**Issue by kemosabe73** [strapi/strapi#8713]
I can create a collection type "serie" but not series. Are there certain rules with plural words I am unaware of or is series a reserved word?

node v12.18.3
npm v6.14.8
strapi v3.3.3

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1198

**Comment by kemosabe73** [comment]
> duplicate: #1198

sorry for the duplicate and thank you for the response

**Comment by derrickmehaffy** [comment]
> > duplicate: #1198
> 
> sorry for the duplicate and thank you for the response

No problem, it can be a little difficult to search for some of the older issues. We are aware of the pluralization issues and plan to address them in v4. :)
