### ISSUE TITLE
Count endpoint issue (pusblishedState)

### ISSUE THREAD

**Issue by ronny35** [strapi/strapi#8721]
hello,

I have inconsistency response from count endpoint api when I used Draft System.
Indeed, the /count route does not take into account the _publicationState=preview param because the same value is always the same with or whithout this arg.

Thanks in advance for your Help.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
