### ISSUE TITLE
Remove strapi-plugin-sentry from npm

### ISSUE THREAD

**Issue by jorisw** [strapi/strapi#8722]
### Describe the bug

When Googling "strapi sentry plug-in", an npm package seemingly owned by the Strapi team, comes up, but the GitHub repo doesn't exist, and the codebase downloaded from npm is empty, except for a `packages.json` and `README.md`

### Steps to reproduce the behavior

1. Go to Google
2. Search for 'strapi sentry plugin'
3. Go to the top result (npmjs.com)
4. Click on the GitHub link in the right panel

### Expected behavior

For the repo on GitHub to exist, or for the npmjs.com package not to exist

**Comment by derrickmehaffy** [comment]
Hi @jorisw we plan to launch a sentry plugin. There are various npm packages where we have reserved their names as we plan to release packages on them.

Currently I don't have an ETA for the sentry package, but we are spinning up a new integrations team internally and this will be one of their new projects.

Going to mark as closed for now, but thank you for the reminder.

**Comment by jorisw** [comment]
Perhaps a placeholder notice could be added to such npm packages?

**Comment by derrickmehaffy** [comment]
Short term if you want to implement just a sentry middleware we do have a guide for that: https://strapi.io/documentation/v3.x/guides/error-catching.html

Also you can take a look at one of my personal projects that I have customized the middleware a bit: https://github.com/canonn-science/CAPIv2-Strapi/blob/development/middlewares/sentry/index.js

**Comment by derrickmehaffy** [comment]
> Perhaps a placeholder notice could be added to such npm packages?

I'm actually pinging our engineering team about that right now to see if we can add some placeholder README info. :wink:

**Comment by jorisw** [comment]
Thanks for the links, we picked https://www.npmjs.com/package/strapi-middleware-sentry

**Comment by derrickmehaffy** [comment]
Ah yeah perfect @zoltanradics is an awesome Strapi community member :)

**Comment by zoltanradics** [comment]
@derrickmehaffy Big up sir! ... An awesome but recently very busy therefore inactive community member. :)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Big up sir! ... An awesome but recently very busy therefore inactive community member. :) I hope this can change in the future.

All good @zoltanradics :smile: I know the feeling of being busy.
