### ISSUE TITLE
GraphQL schema doesn't respect the policy settings of routes defined in routes.json while using `resolverOf`

### ISSUE THREAD

**Issue by geekdada** [strapi/strapi#8728]
### Describe the bug

In the GraghQL section of Strapi's doc, there's an example showing the meaning of using `resolverOf`.

```js
{
  resolverOf: 'application::restaurant.restaurant.findByCategories', // Will apply the same policy on the custom resolver as the controller's action `findByCategories`.
}
```

But in reality, this behavior never takes effect, I believe the cause to this problem is in [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/resolvers-builder.js#L169-L198). It only populates the controller, ignoring the policy settings.

I'm not sure if it's a typo in documentation or hasn't got implemented yet.

### Steps to reproduce the behavior

See above.

### Expected behavior

Policies defined in routes.json should show in GraphQL's schema.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.19.1 
- NPM version: v6.14.8
- Strapi version: v3.4.4 
- Database: MySQL
- Operating system: macOS 10.15.7

**Comment by derrickmehaffy** [comment]
Hi @geekdada 

For GraphQL you need to manually define the policy in the schema. See: https://strapi.io/documentation/v3.x/plugins/graphql.html#execute-a-policy-before-a-resolver

We also have a note about this listed in the policy documentation: https://strapi.io/documentation/v3.x/concepts/policies.html#usage

Going to mark as closed as we are aware of this and plan to handle it automatically once we refactor the GraphQL plugin in v4.
