### ISSUE TITLE
Graphql plugin - oneToMany relationship error in DataLoader - Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by ralphsomeday** [strapi/strapi#8731]
### Describe the bug

I created a Person content type and a Property content type. A Person has one to many relation with property and a property belongs only to one person. When using the following graphql query in the playground I am getting the error `Cannot read property 'toString' of undefined"`

```graphql
query personbyuuid {
    personByUuid(uuid: "xxxx") {
      	uuid
        firstname
    	properties {
           label
           value
      }
    }
}
```

error:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'toString' of undefined",
      "locations": [
        {
          "line": 16,
          "column": 5
        }
      ],
      "path": [
        "personByUuid",
        "properties"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'toString' of undefined",
            "    at Object.extractIds (/.../node_modules/strapi-plugin-graphql/services/data-loaders.js:131:46)",
            "    at /.../node_modules/strapi-plugin-graphql/services/data-loaders.js:91:24",
            "    at Array.map (<anonymous>)",
            "    at Object.mapData (/.../node_modules/strapi-plugin-graphql/services/data-loaders.js:69:24)",
            "    at /.../node_modules/strapi-plugin-graphql/services/data-loaders.js:56:23"
          ]
        }
      }
    }
  ],
  "data": {
    "personByUuid": {
      "uuid": "xxxx",
      "firstname": "John"
      },
      "properties": null
    }
  }
}
```

it looks like the `person` attribute within the `property` content type is causing the issue as it seems to have an empty array of ids in the `createLoader` function located in file
`.../node_modules/strapi-plugin-graphql/services/data-loaders.js` at line 56

### Steps to reproduce the behavior

1. Create Person content type and Property content type.
2. Create a Relation in the Property content type that points to the Person content type with one to Many relation
3. Add some data in the Person content type
4. Add some data in the property content type and link it to the newly added person
5. Run the graphql query in the playground to retrieve a specific person and adding the properties attribute in the query in order to retrieve all the properties linked to that person in the graphql response

### Expected behavior

No error message and the properties attribute shows the list of all the properties that belongs to that person.

### System

- Node.js version: v12
- Strapi version: v3.3.3
- Database: Mysql 5.7

**Comment by derrickmehaffy** [comment]
Where did you get the `personByUuid` as that isn't a resolver that we add by default?

**Comment by ralphsomeday** [comment]
@derrickmehaffy just use the normal person query then i have the same issue.

**Comment by derrickmehaffy** [comment]
@ralphsomeday I wasn't able to reproduce: https://www.loom.com/share/ced580096762450aa1e4112e6cddbcec

**Comment by ralphsomeday** [comment]
It seems to work when running this in the strapi container. I have added a specific schema.graphql configuration to the person content type it might be the reason why this is showing that error. Will investigate further and come back.

**Comment by ralphsomeday** [comment]
The issue was coming from the fact that I had put the `id` field of my content type as a private attribute in the settings.json file. When I removed it then all works.
