### ISSUE TITLE
Impossible to change labels for dynamic zones in content manager

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#8732]
### Describe the bug

When I try to change label names for dynamic zones in content manager, nothing happens and Strapi fetches displaying name from model settings, not from label.

### Steps to reproduce the behavior

1. Go to Content Type builder and create a dynamic zone.
2. Click on Content Type in left panel and try to add or edit an entry.
3. Click on "Configure the view" button and change label name for dynamic zone.
4. Return to Content Manager and check a plus button of dynamic zone. This is an error

### Expected behavior

I expect it to change on a label name. Same applies to components in dynamic zones - you simply can't change their label names at all.

### Screenshots

![image](https://user-images.githubusercontent.com/20924122/100164137-4ae83180-2ec8-11eb-9005-c18a643ccc03.png)
![image](https://user-images.githubusercontent.com/20924122/100164149-54719980-2ec8-11eb-8e26-b9da0d1ca59a.png)

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.3.3 EE
- Database: PostgreSQL
- Operating system: Ubuntu 18.04

**Comment by eriskhan** [comment]
So after 3.4.1 update (or maybe I missed it on 3.4) labels are finally showing up! Thanks to Strapi team for solving it :)

**Comment by darokviana** [comment]
I'm facing similar issue in versions 4.2.0 and 4.2.2. When trying to edit the Dynamic Zone display name and description, no options are displayed.

When trying to change directly via "Schema", the change is simply ignored.

**Comment by joh-sch** [comment]
> I'm facing similar issue in versions 4.2.0 and 4.2.2. When trying to edit the Dynamic Zone display name and description, no options are displayed.
> 
> When trying to change directly via "Schema", the change is simply ignored.
> 
> ![image](https://user-images.githubusercontent.com/37381417/176504091-ebcb4e82-70d8-4482-9135-1e1ec681e0c9.png)

I'm having the same issue with Strapi 4.1.7

**Comment by derrickmehaffy** [comment]
As this has already been patched in v4.3.x you will need to update.
