### ISSUE TITLE
[graphql] controller bypassed when querying nested relations

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#8735]
### Describe the bug

When using custom processing in a model controller to filter nested relations, it's bypassed by graphql plugin.

### Steps to reproduce the behavior

1. Create a model `B`
2. Create a model `A` with a field `entities` (one to many : `B`)
3. Edit `api/A/controllers/a.js` and add a custom `findOne` controller (but same behaviour with all controllers) : 
```js
module.exports = {
    lifecycles: {
        async findOne(ctx) {
           const data = // query data
           data.entities = [];
           return data;
        }
    }
}
```

4. query you model via graphql
```graphql
query MyModelA {
  projectState(id:"azertyuiop"){
        id
  	entities {
          id
        }
    }
}
```

### Expected behavior

The data returned by graphql plugin should be the one returned by controller:
```json
{
  "data": {
    "a": {
      "id": "azertyuiop",
      "entities": []
    }
  }
}
```
Instead we receive this: 
```json
{
  "data": {
    "a": {
      "id": "azertyuiop",
      "entities": [
        {
          "id": "abcdefgh",
        },
        {
          "id": "ijklmnop",
        },
      ]
    }
  }
}
```
### Screenshots

N/A

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 10.19.0
- YARN version: 1.22.5
- Strapi version: 3.3.3
- Database: Mongo DB
- Operating system: Ubuntu 20.04

### Additional context

After investigating a bit, it seems that graphql plugin queries manually nested relations without using controller for each queried relation:
```js
    // strapi-plugin-graphql/services/data-loader.js:159
    return strapi.plugins['content-manager'].services['contentmanager'].fetchAll(modelUID, params);
```

This results in a query to ORM model (mongoose, here) instead of controller.

I'm not really familiar with apollo server and the way it's been implemented here but wouldn't it be possible to query nested relations via their controller ?

**Comment by 8byr0** [comment]
Maybe somehow related to https://github.com/strapi/strapi/issues/8671

**Comment by derrickmehaffy** [comment]
Thank you @8byr0 I'll test it either today or tomorrow :+1:

**Comment by derrickmehaffy** [comment]
@8byr0 you are correct that our GraphQL plugin has it's own population code, In a case like this you will likely need to create your own custom queries/resolvers.

To give a bit of context on how everything works, I'll share a part of one of our engineering diagrams (we plan to change this in the future but no ETA)

![image](https://user-images.githubusercontent.com/8593673/100788334-c87cd780-33c9-11eb-8a13-115991d7b927.png)

**Comment by 8byr0** [comment]
Thanks for your reply and explanations.
The problem with your suggestion of using custom query/resolver is that these pieces do not have access to query context. 
So when you want to implement a custom logic based on user role / id or any other request params, this is just impossible. 

The only solution I see to solve this is to use a depth of 0 but let's use REST then... Have you got other ideas to bypass the plugin's limitations? 

And is there a particular reason why this has been designed like this ? Would a PR replacing calls to resolvers with calls to controllers for population be accepted ?

**Comment by derrickmehaffy** [comment]
> And is there a particular reason why this has been designed like this ? Would a PR replacing calls to resolvers with calls to controllers for population be accepted ?

To the why, I think the goal was just to make it simple, we weren't planning for the future. We have some plans to modify this and make it far more efficient.

As to the PR question I'll point that at @alexandrebodin.

**Comment by sebastian-ludwig** [comment]
@derrickmehaffy Could you give us some more information about your future plans regarding this issue please?
I see the problem, when we do not use Controllers and policies for nested relations, there is the risk, that one can access restricted data: 
```graphql
// everyone should do this
query AllComaniesWithJobs {
  companies {
    id
    jobs {
      id
      position
    }
  }
}
```
```graphql
// only Company-Admins should do this
query AllComaniesWithApplicants {
  companies {
    id
    jobs {
      id
      users_permissions_user {
        id
        email
      }
    }
  }
}
```
Have you got a solution for restricting the second request?

**Comment by derrickmehaffy** [comment]
@sebastian-ludwig I don't currently have any information on it as our v4 is still in it's design phase (we haven't even finished the RFC yet to release for comment). I'm not sure if something like this will be implemented in the initial v4 or not.

cc @alexandrebodin / @sam-pires / @JabStrapi

**Comment by sebastian-ludwig** [comment]
Thanks @derrickmehaffy. Any feedback or advice would be appreciated, because currently I see a big GraphQL security issue, when all nested relations are accessible to the requester without any policy checks.
Or can I intercept those nested resolvers somehow?

**Comment by bschelling** [comment]
This is a terrible security issue.  It took us days to figure out how to deal with this. There is no way to delete or modify fields from a nested relation - neither in custom resolvers, custom controllers or hooks. The only way I found to filter out private information was using a middleware, loading it after router and manipulating the response. I honestly do not understand why this issue was marked with severity low.

**Comment by sebastian-ludwig** [comment]
@derrickmehaffy Are there any plans to change / improve this in v4?

**Comment by alexandrebodin** [comment]
@sebastian-ludwig In v4 you will be able to configure policies or graphql middlware for any resolver in your schema. This will make it possible to prevent this yes.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-beta-is-live/11623/31

**Comment by derrickmehaffy** [comment]
should be fixed in v4
