### ISSUE TITLE
Ability to change admin panel users fields

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#8737]
### Please describe your feature request

- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

It would be great to be able to change fields for administrators.

### Why is it needed?

Well, there are many examples of such usage. For example, we will be able to bind make a relation between an admin panel user and an entry in content type (for example, a controller which logs who and when made an edit to some field).

### Suggested solution(s)

1. Implement a Content Type "User (from admin-users-permissions) in Content Type Builder
2. Develop Content-Type-Builder-like page in Settings -> Administration Panel

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/4838
