### ISSUE TITLE
The server restart doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#875]
**Informations**
- **Node.js version**: v9.10.0
- **npm version**: v5.8.0
- **Strapi version**: 3.0.0-alpha.11.1
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The server restart doesn't work.
I had never seen the server restart until your [blogpost](https://blog.strapi.io/release-v3-alpha-11-file-upload/) gif.

**Steps to reproduce the problem**

![mar-28-2018 16-06-08](https://user-images.githubusercontent.com/1007051/38086704-a84a9f0a-3355-11e8-88b0-6561f384ce66.gif)

**What is the expected behavior?**

![strapi-upload-single](https://user-images.githubusercontent.com/1007051/38086701-a5031b74-3355-11e8-90e4-02db1a73c6e3.gif)

- [x] I'm sure that this issue hasn't already been referenced

**Comment by ackro** [comment]
I can reproduce this by using `npm start` instead of `strapi start`. Behaviour is same as shown in the issue gif. Sometimes the restart message overlay does appear briefly, other times is not visible (perhaps removed too quickly).

---
* **Node.js version**: 9.6.1
* **npm version**: 5.8.0
* **Strapi version**: 3.0.0-alpha.11.3
* **Database**: MongoDB
* **Operating system**: MacOS

**Comment by abdonrd** [comment]
Yep! It works if I use `strapi start`, but not if I use `npm start`.

**Comment by Luukth** [comment]
When using pm2 start strapi server.js the same happens. No restart and quick flash of server restarting.

**Comment by lauriejim** [comment]
@abdonrd did you use pm2 to start your project or npm start

If it's the case check this issue https://github.com/strapi/strapi/issues/1008

**Comment by abdonrd** [comment]
@lauriejim if I use `npm start` the server restart doesn't work. If I use `strapi start` it works.

**Comment by lauriejim** [comment]
Okay, it's normal check my comments for #1008 issue.

**Comment by abdonrd** [comment]
@lauriejim I just see the:

> @bartoszgajda55 you can replace `"start": "node_modules/strapi/bin/strapi.js start"`, in your `package.json` and then start the app with `pm2 start npm -- start`

But in my `package.json`, the `start` script is `"start": "node server.js",`

**Comment by bartoszgajda55** [comment]
@abdonrd You have to replace `"start": "node server.js"` with `"start": "node_modules/strapi/bin/strapi.js start"` in your `package.json` file, and then you can run it with PM2 `pm2 start npm -- start`

**Comment by ujal** [comment]
@lauriejim pm2 works just fine with the `--no-pmx` flag - `pm2 start strapi --no-pmx -- start`

**Comment by krestaino** [comment]
@ujal That works, but it's not loading Strapi in production. I tried `NODE_ENV=production pm2 start strapi --no-pmx --name="example.com" -- start` which loads it in production, but then I get the same error where the server isn't restarting correctly after adding new content types with fields.

Any suggestions?

**Comment by ujal** [comment]
@krestaino Try the latest strapi@alpha. The error msgs got more descriptive.

**Comment by max-ivaneychyk** [comment]
![Screenshot from 2019-05-06 19-10-18](https://user-images.githubusercontent.com/16804848/57238816-f43fac00-7032-11e9-88e3-3faaecccee78.png)

or try enable flag autoreload
