### ISSUE TITLE
Strapi Admin Onboarding Thumbnail filesize too large

### ISSUE THREAD

**Issue by dneckel** [strapi/strapi#8750]
### Describe the bug

Huge PNGs get loaded as Video Thumbnails in the Strapi Admin Onboarding component.
"Previews" are 2560x1440 and PNG which makes them way to large for the purpose.
These files end up taking almost 1.2 MB and make the admin interface unnecessary slow at first load.
Since these are loading via a request to https://strapi.io/videos this cannot be solved via a pull request but rather in CMS.

### Steps to reproduce the behavior

1. Go to 'Strapi Admin'
2. Look at network requests
3. Click on Question Mark on lower right
3. See Thumbnails beeing diplayed for videos in tiny size.

### Expected behavior

As the Video Wrapper Thumbnail has a maximum size of 55x38 preview thumbnails should be around that size and also be JPG compressed since there is no transparency.

### System

- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.2.3
- Database: MySQL
- Operating system: Win 10

**Comment by derrickmehaffy** [comment]
fixed on v4
