### ISSUE TITLE
Strapi takes around 15-20 seconds to load data

### ISSUE THREAD

**Issue by AryanGharshi** [strapi/strapi#8753]
### Describe the bug
The graphQL data takes very long to load into my applications. I have two separate web applications at www.ariangarshi.no and eskilnormannsaetre.com 
both take very long to load the first time the website is loaded but once the data is cached, it goes very fast. 
### Steps to reproduce the behavior

1. create strapi application
2. fill with data
3. host on google app engine
4. Send graphql query to the API
5. wait too long to get data back

### Expected behavior
I expect it to not take this long

### System
Node.js version 10
Npm version 6.14.6
Strapi version 3.1.5
Database: PostgreSQL
Operating system: windows 10

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/8552

**Comment by AryanGharshi** [comment]
> duplicate: #8552
Not true. I tried using normal fetch as well. it also took 12.20 seconds to load just 16.7kb of data
![image](https://user-images.githubusercontent.com/24868059/100792234-a19ac180-341a-11eb-86cc-0899c824c916.png)

**Comment by Jbmanllr** [comment]
Strapi in general is sadly not optimized at all, use it as a sole CMS, build your own direct to db queries or own API.

**Comment by Boytobeaman** [comment]
same problem, strapi gets very slow that I cannot bear it
