### ISSUE TITLE
Disable graphql queries and mutations other than the CRUD one does not work in users-permissions and upload plugins

### ISSUE THREAD

**Issue by ralphsomeday** [strapi/strapi#8754]
### Describe the bug

The strapi documentation [https://strapi.io/documentation/v3.x/plugins/graphql.html#disable-a-query-or-a-type](https://strapi.io/documentation/v3.x/plugins/graphql.html#disable-a-query-or-a-type) gives some good instructions on how to disable some queries and mutations for a content type. But it seems to only work for CRUD type endpoints but not for other queries or mutations that are available in the users-permissions and upload plugin.

### Steps to reproduce the behavior

1. Go to the `Extensions` folder in strapi and create a `users-permissions` folder and within that folder a `config` folder
2. In the config folder create a file and name it schema.graphql
3. Put the following code in that file:

```javascript
module.exports = {
  resolver: {
    Query: {
      users: false,
      user: false,
      roles: false,
      role: false,
      permissions: false,
      permission: false,
      me: false
    },
    Mutation: {
      login: false,
      register: false,
      forgotPassword: false,
      resetPassword: false,
      emailConfirmation: false,
      createUser: false,
      updateUser: false,
      deleteUser: false,
      createRole: false,
      updateRole: false,
      deleteRole: false,
      createPermission: false,
      updatePermission: false,
      deletePermission: false
    }
  }
}
```

All the endpoints are gone from the graphql docs available at http://localhost:1337/graphql except the following one: login, register, forgotPassword, resetPassword, emailConfirmation and me.

### Expected behavior

All the mutations and queries that are marked as false should not be available in the schema.graphql that is located in the export folder in the strapi project

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12
- Strapi version: v3.3.3
- Database: MySQL v5.7

**Comment by ralphsomeday** [comment]
@derrickmehaffy were you able to reproduce it?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy were you able to reproduce it?

Not yet @ralphsomeday it's on my list

**Comment by ralphsomeday** [comment]
@derrickmehaffy  any update on this one?

**Comment by derrickmehaffy** [comment]
Confirmed, but I'm not sure when we be able to get to this issue to fix the bug. If anyone is willing to submit a PR, please do.

**Comment by pimsomeday** [comment]
i'll submit a PR later today

**Comment by derrickmehaffy** [comment]
closing as PR merged
