### ISSUE TITLE
Heroku : The client `pg` is not installed.

### ISSUE THREAD

**Issue by baptisteArnaud** [strapi/strapi#8759]
Hello friends,
I followed the guide to deploy my backend to Heroku with a Postgres DB, the build is succesful but on app start, I got this error :
```
[2020-11-27T11:08:14.513Z] error The client `pg` is not installed.
```

It is in my package.json and package-lock.json. I tried to clear the Heroku cache. There is nothing that works

Here is my package.json:
```
{
  "name": "backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {
    "pg": "^8.5.1"
  },
  "dependencies": {
    "knex": "<0.20.0",
    "pg-connection-string": "^2.4.0",
    "sqlite3": "latest",
    "strapi": "3.3.4",
    "strapi-admin": "3.3.4",
    "strapi-connector-bookshelf": "3.3.4",
    "strapi-plugin-content-manager": "3.3.4",
    "strapi-plugin-content-type-builder": "3.3.4",
    "strapi-plugin-email": "3.3.4",
    "strapi-plugin-upload": "3.3.4",
    "strapi-plugin-users-permissions": "3.3.4",
    "strapi-provider-upload-aws-s3": "^3.3.4",
    "strapi-utils": "3.3.4"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "cc456458-b815-4a55-ab9f-2786be9ddb5e"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by bglidwell** [comment]
Have you tried putting pg in dependencies instead of devDependencies?

**Comment by Stun3R** [comment]
@baptisteArnaud I'm using Heroku for my project and everything work well.

But, I remember I had this issue too with my first deploy to Heroku and It was something related to the pg version pkg. In my package.json I have pg in the dependencies part like this : `"pg": "^8.0.3",`

**Comment by baptisteArnaud** [comment]
> Have you tried putting pg in dependencies instead of devDependencies?

Indeed, that was the trick 🤔, In the documentation it seems to insist that you need to save the dependency as a Dev one

**Comment by derrickmehaffy** [comment]
Going to mark this one as closed then.
