### ISSUE TITLE
Change "unique" fields to non unique will update the model but not the MondoDB collection index

### ISSUE THREAD

**Issue by pedrosimao** [strapi/strapi#876]
**Informations**

- Node v9.7.1
- npm 5.6.0
- Strapi 3.0.0-alpha.11
- MongoDB
- Ubuntu

**What is the current behavior?**
When changing a field from unique to non-unique the change is not made on the MongoDB schema. So whenever we try to POST a new document with same field value as an existant document MongoDB will reject the query, even though Strapi allows it.

**Steps to reproduce the problem**
1 - Create a field in a "Content Type" with "unique" checked. (I have used with an integer)
2 - Create a document and put some random value in the unique field.
3 - Now go back in Content Type Editor and uncheck the "unique" box of this field. Save.
4 - Try to POST a new document with the same value of the unique field.
5 - MongoDB will reject the insert.

**What is the expected behavior?**
That Strapi changes MongoDB "index" to non-unique.

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hi @pedrosimao.

The way to fix it for your app is to update you MongoDB collection schema manually.

Actually, we are not updating mongodb or sql database advanced settings like required, unique... (we just did it on mongodb when you create your content type)

Fill free to implement this feature on Strapi and submit a PR

**Comment by Aurelsicoko** [comment]
@pedrosimao What do you think about launching the index build every time there is a change in the unique key of an attribute? We have access to the previous state and the next state of the attribute, so we could easily do that. However, if you have a lot of data in your database it could take some time to rebuild the index. But, you're not changing this kind of validation every day so when it's done, it's done.

Could you make a PR for this?

**Comment by pedrosimao** [comment]
@Aurelsicoko ok, thanks for your guidance. I will look into that this weekend! =)

**Comment by Aurelsicoko** [comment]
Awesome, I'm looking forward to seeing your PR!

**Comment by lauriejim** [comment]
Hello @pedrosimao have you an update on this point ?

https://github.com/strapi/strapi/issues/876#issuecomment-384925213 Did you do something about it ?

**Comment by lauriejim** [comment]
I link to this issue to handle all database in the same time https://github.com/strapi/strapi/issues/1189
