### ISSUE TITLE
Support for node 15.1.0

### ISSUE THREAD

**Issue by mihirpipermitwala** [strapi/strapi#8761]
## Bug report

```
yarn create strapi-app firststrapi
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error strapi-generate-new@3.3.4: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "15.1.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### Screenshots
<img width="986" alt="Screenshot 2020-11-28 at 1 32 49 AM" src="https://user-images.githubusercontent.com/65561886/100481297-aceba580-3119-11eb-9ee1-766855536690.png">

### System

- Node.js version: v15.1.0
- NPM version: 7.0.8
- Operating system: macOS Big Sur

**Comment by eriskhan** [comment]
https://strapi.io/documentation/v3.x/getting-started/deployment.html#recommended-requirements
Node LTS (v12 or V14) Note that odd-number releases of Node will never be supported (e.g. v13, v15).

**Comment by derrickmehaffy** [comment]
Closing as Strapi will never support development versions (odd numbers).

The next version we support will be v16 in October 2021.
