### ISSUE TITLE
No confirmation email and "Bad Request" error on response after registering user with POST /auth/local/register

### ISSUE THREAD

**Issue by eitelkrauss** [strapi/strapi#8767]
### Describe the bug

I don't receive a confirmation email after registering user and get "Bad Request" error in the response.
User entry is created though.

### Steps to reproduce the behavior

1. POST /auth/local/register
2. Response error 400 "Bad Request"

### Expected behavior

Expect to receive the confirmation email and 200 ok status

### System

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.3.4
- Database: Postgresql
- Operating system: Ubuntu 20.04

### Additional context

Running strapi in --production

**Comment by shuntastic** [comment]
@eitelkrauss were you able to resolve your issue? Had the same problem happen for me last night while testing with Postman.

**Comment by eitelkrauss** [comment]
@shuntastic it's working fine now.. no errors and confirmation email works.. I was sending an "identifier" instead of "username" with the POST request, I think maybe that was it, but I'm not sure because I had changed it before and it wasn't working.. so I dont know, but working fine for now.

**Comment by shuntastic** [comment]
Okay cool, thank you for the info. I'm thinking it's something related to the confirmation email for me.

**Comment by derrickmehaffy** [comment]
@shuntastic and @eitelkrauss feel free to open up a Q&A on the forum if you are still hitting issues.

https://forum.strapi.io/
