### ISSUE TITLE
Nested type (with File) returns null in API

### ISSUE THREAD

**Issue by oeddyo** [strapi/strapi#877]
BUG

**Informations**
- **Node.js version**:9.0.0
- **npm version**: 5.0.0
- **Strapi version**: 3.0.0-alpha.11.2
- **Database**: Mongo
- **Operating system**: Mac OS 10.12

**What is the current behavior?**
I created a model 

Picture
and the intention is to include a "description" field in it so I can describe the image file. 

However when I'm getting the Picture object nested in another model, it returns null

**Steps to reproduce the problem**
download my model and create a Bag with a Picture associate with it. Then query the api like:
http://localhost:1337/bag/5abb15bce0d8c3a0ccdef5bf

(replace the id with your bag of course)

![image](https://user-images.githubusercontent.com/1943146/38129381-6af25378-3431-11e8-9881-0476b8c59ddc.png)

**What is the expected behavior?**
The field 

picture.image shouldn't be null since i do have uploaded a file with it

- [Y] I'm sure that this issue hasn't already been referenced

**Comment by oeddyo** [comment]
[api 2.zip](https://github.com/strapi/strapi/files/1862985/api.2.zip)

my model attached

**Comment by lauriejim** [comment]
Hi @oeddyo you will have to update your API service and update the way we populate data.
You will have to handle a deep populate.

Check the MongoDB documentation http://mongoosejs.com/docs/populate.html#deep-populate

**Comment by oeddyo** [comment]
hmm... I dont think currently I have the bandwidth or knowledge to do that. maybe someone more knowledgable can take this : )

BTW I guess the other fields for File shall be editable from admin? Otherwise there's no point adding "ext" etc fields in File. Can we add those fields editable in admin instead? If so I don't need this nested populate for now which would be awesome

**Comment by lauriejim** [comment]
You will have to do something like that:

```
Bag.find().populate({
    path: 'familly',
    populate: { path: 'famillyBags' }
  })
```

**Comment by XcrossD** [comment]
@lauriejim I'm trying to solve this issue, but I can't wrap my head around it. Can you give me some hints? Thank you.

I have 1 to many relation - one product has many productfeatures, and I want to populate the image in productfeature when I obtain product data.

So far I have gotten to `myProject/api/product/controllers/Product.js` and `myProject/api/product/services/Project.js` (maybe the same files in `productfeature` are related as well). 

I have tried the following in `myProject/api/product/services/Project.js`
```
fetchAll: (params) => {
    const convertedParams = strapi.utils.models.convertParams('product', params);
    
    return Product
      .find()
      .where(convertedParams.where)
      .sort(convertedParams.sort)
      .skip(convertedParams.start)
      .limit(convertedParams.limit)
      // new populate
      .populate({
        path: 'productfeatures',
        populate: {
          path: 'image',
        }
      })
      .populate(_.keys(_.groupBy(_.reject(strapi.models.product.associations, {autoPopulate: false}), 'alias')).join(' '));
  },
```

Also the following in `myProject/api/productfeature/services/Productfeature.js`
```
fetchAll: (params) => {
    const convertedParams = strapi.utils.models.convertParams('productfeature', params);

    return Productfeature
      .find()
      .where(convertedParams.where)
      .sort(convertedParams.sort)
      .skip(convertedParams.start)
      .limit(convertedParams.limit)
      // new populate
      .populate({
        path: 'image',
      })
      .populate(_.keys(_.groupBy(_.reject(strapi.models.productfeature.associations, {autoPopulate: false}), 'alias')).join(' '));
  },
```
```
fetchAll: (params) => {
    const convertedParams = strapi.utils.models.convertParams('productfeature', params);

    return Productfeature
      .find()
      .where(convertedParams.where)
      .sort(convertedParams.sort)
      .skip(convertedParams.start)
      .limit(convertedParams.limit)
      // append 'image' to the string passed to populate
      .populate(_.keys(_.groupBy(_.reject(strapi.models.productfeature.associations, {autoPopulate: false}), 'alias')).join(' ') + ' image');
  },
```
None of them work. I'm thinking the correct way is to use existing .populate() but I have absolutely no idea what is in `strapi.models.productfeature.associations`.

**Comment by lauriejim** [comment]
Hello guys @oeddyo @XcrossD can you update your Strapi version and tall me if it's still happen.

**Comment by Dronozavr** [comment]
As for me I have the same behavior! Thanks.

**Comment by lauriejim** [comment]
@Dronozavr what is your Strapi version ?

**Comment by Dronozavr** [comment]
@lauriejim Now it is okay! Thanks! Sorry for annoying! Keep pushing guys, Strapi is pretty cool. Merci beaucoup

**Comment by jdus** [comment]
Should this be fixed in '3.0.0-alpha.12.2'? I still have this problem.

I have an object 'photo', as well as an object 'photoset'. 'Photoset' has a 'belongs to many' relation to 'Photo'.

If I query 'photo' directly I get the correct values in the 'file' attribute, if I query 'photoset', which gives me a list of photo sets with nested photo objects, I get 'null' as value. Is this intentional and I need to adapt the controller or has this bug been fixed/feature been added by now?

**Comment by Dronozavr** [comment]
@jdus Hi, yes the version '3.0.0-alpha.12.2' solved my problem; But it is not populates nested values by default (from the box, as to speak). If you follow this issue from the beginning , you ll notice the `.populate` method, which you have to apply to make your nested media types available.

`      .populate({
        path: 'mentors',
        populate: { path: 'image' }
      });`

**Comment by jdus** [comment]
@Dronozavr, thanks your answer :) I figured out how to adapt the service, but I just wasn't sure if it should still be needed...

**Comment by nao360** [comment]
See https://github.com/strapi/strapi/issues/1783 for a more detailed summary of how to resolve this. Good luck 👍
