### ISSUE TITLE
Add poll option support to develop command

### ISSUE THREAD

**Issue by PaulWeinsberg** [strapi/strapi#8771]
## Problem

File changes isn't detected inside a container.

## Reproduce

This problem appear when you run npm commands (develop for example) inside custom node container.

OS : MacOSX
Docker container : node:14.15.1-stretch (volume NFS)

## Quick fix

Fixed with process env variable

```
CHOKIDAR_USEPOLLING=true npm run $task
```

## Idea for strapi team

It's possible to solve it easily for strapi team :

line 120 in node_modules/strapi/lib/commands/develop.js for example, with additional option.

```javascript
  const watcher = chokidar.watch(dir, {
    ignoreInitial: true,
    usePolling: true, // Option to add
    ignored: [
      /(^|[/\\])\../,
      /tmp/,
      '**/admin',
      '**/admin/**',
      'extensions/**/admin',
      'extensions/**/admin/**',
      '**/documentation',
      '**/documentation/**',
      '**/node_modules',
      '**/node_modules/**',
      '**/plugins.json',
      '**/index.html',
      '**/public',
      '**/public/**',
      '**/*.db*',
      '**/exports/**',
      ...watchIgnoreFiles,
    ],
  });
```

We can imagine a cli flag that active or not this feature. Something like --poll

## Related issues

https://github.com/strapi/strapi/issues/596
https://github.com/strapi/strapi/issues/1008

Thanks !

**Comment by derrickmehaffy** [comment]
Can you submit a pull request?

**Comment by PaulWeinsberg** [comment]
https://github.com/strapi/strapi/pull/8773

(Small error in commit title flag this is --polling not --poll)
