### ISSUE TITLE
npx create-strapi-app my-app FAILS

### ISSUE THREAD

**Issue by JeffWScott** [strapi/strapi#8779]
## Bug report

create-strapi-app fails to install dependancies. 

### Describe the bug

Creating a new Strapi application at /Users/user/Documents/sites/my-app.
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.3.4
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.3.4" from the root project

### Steps to reproduce the behavior

1. npx create-strapi-app my-app
2. select quickstart

### Expected behavior

A fresh install of Strapi 

### System

- Node.js version: v15.3.0
- NPM version: 7.0.14
- Strapi version: No idea.. using  create-strapi-app
- Database: quickstart
- Operating system: masOs 10.15.7

**Comment by derrickmehaffy** [comment]
> Node.js version: v15.3.0

We don't support Node v15 and never will. See: https://github.com/strapi/strapi/issues/8761#issuecomment-735031906
and
https://github.com/strapi/strapi#-requirements => `NodeJS >= 10.16 <=14`

> npm ERR! Could not resolve dependency:

Can you run `npm config get registry` and make sure you get `https://registry.npmjs.org/` back?

**Comment by JeffWScott** [comment]
Yes I get https://registry.npmjs.org

I'll see about downgrading.
