### ISSUE TITLE
I'm trying to sign in using Facebook, getting a status code = 401

### ISSUE THREAD

**Issue by mohamed-reda** [strapi/strapi#8780]
### Describe the bug
 I want to sign in using Facebook provider in a Flutter App, getting a status code = 401

### Steps to reproduce the behavior

1. I'm getting the token correctly from flutter_facebook_login library (https://pub.dev/packages/flutter_facebook_login)
2. tried to use that token to create a new user at Strapi API. 
3. the result is status code = 401

### Code snippets

```
final result = await facebookLogin.logIn(['email']);
final token = result.accessToken.token; 
final response = http.get(
          '{myUrl}/auth/facebook/callback',
          headers: {'Authorization': 'Bearer $token'}
);
```

> {statusCode: 401, error: Unauthorized, message: Invalid token.}

### System

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.3
- Database: Mongodb
- Operating system: Windows

What command that I should send to the server to create a new account using sign in with Facebook provider?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by mohamed-reda** [comment]
> > This is a templated message
> 
> Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> A proper issue submission let's us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue with the template and we can reopen this report.
> 
> Thank you.

ok. I did that.

**Comment by derrickmehaffy** [comment]
@mohamed-reda have you looked at the login-react example to see how the flow is handled for authentication?

https://github.com/strapi/strapi-examples/tree/master/login-react

**Comment by mohamed-reda** [comment]
Yes, at this project, it gets the token from Facebook API and use it directly with Strapi API.
I want to ask about something, should I write the URL at the field of "The redirect URL to your front-end app" at Strapi server?
I wrote it at the Front end app, but should I write it at Strapi server?

![image](https://user-images.githubusercontent.com/15935347/101611283-fd181100-3a11-11eb-9fed-d725823d6176.png)

**Comment by derrickmehaffy** [comment]
It should be your frontend application. (IIRC)

**Comment by mohamed-reda** [comment]
Can you just write the model that I should send here because I couldn't found it at the docs?

**Comment by derrickmehaffy** [comment]
closing as old issue, facebook provider has been confirmed working since.
