### ISSUE TITLE
Videos uploading bug report

### ISSUE THREAD

**Issue by nikita-lipnyagov** [strapi/strapi#8782]
Dear colleagues, have some issues while working with **upload** pugin in strapi.

### Bug description
It is impossible to upload video with following formats: MPEG, WMV. AVI, FLV. The endless video loading is shown.

### Steps to reproduce the behavior

1. Open **Media Library**.
2. Click on **Upload asset** in the top right corner.
3. Select video in MPEG, WMV. AVI, FLV formats.
4. Click on **Upload asset to the library**.

### Expected behaviour
Video is uploaded to the library successfully

### Actual behaviour
The endless video loading is shown. It is impossible to play it.

### Video samples
[link to google drive with video samples](https://drive.google.com/drive/folders/1cMwSaRNVWvEam6Kxke1_TzFyKZdBZxu7?usp=sharing)

### System

- Node.js version: v12.18.4
- Npm version: 6.14.6
- Strapi version: 3.1.6
- strapi-plugin-upload: 3.1.6
- Database: Postgresql
- Operating system: Ubuntu 18.04,3 LTS

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.1.6

Can you please test on the latest release? Your version is a few months behind.

**Comment by nikita-lipnyagov** [comment]
@derrickmehaffy Updated to version 3.3.4, have the same issue:

![Screenshot from 2020-12-02 17-31-54](https://user-images.githubusercontent.com/20063800/100893998-a6b44b00-34c4-11eb-8f70-8f483cd6a7bc.png)

![Screenshot from 2020-12-02 17-36-35](https://user-images.githubusercontent.com/20063800/100894254-f6931200-34c4-11eb-9f0c-87942c764d07.png)

**Comment by derrickmehaffy** [comment]
Are you using a 3rd party provider?

**Comment by derrickmehaffy** [comment]
Regardless, I tested on the local provider and could reproduce the issue:

![image](https://user-images.githubusercontent.com/8593673/100897513-fff88c00-347c-11eb-86c3-de0dd63ba76b.png)

**Comment by soupette** [comment]
Hello, the formats of your videos are not supported by the HTML5 player, you will need to convert to another format. I don't think that this is an issue that we could fix.

**Comment by mfrachet** [comment]
Hello 👋🏻 

A fix has been merged on master and will be available on a future release. In the meantime, I will close this issue.

Feel free to reopen if you feel that it has not been addressed correctly.

Thank you for your interest and your help in the project 🙏🏻
