### ISSUE TITLE
French wording needs to be checked and clean (extra space) when adding a relational field to a CT in the CTB

### ISSUE THREAD

**Issue by sam-pires** [strapi/strapi#8796]
### Describe the bug

There is an extra space in the French wording in the modal to add a single unilateral relation in the CTB. But I also wonder if the wording is actually correct: for the 2 first relationship types we use "[CT1] a un [CT2]".

See video: https://www.loom.com/share/95e8b07f2dff4dc3801624dd9d6bafc4

### Steps to reproduce the behavior

1. In dev env, Go to the CTB
2. Put the Admin in French
3. Open a CT
4. Add a field, a relation
5. Click on the 2 first types of relations and see error

### Expected behavior

Regarding the extra space in the first relationship type: No extra space
Regarding the wording: See the comment below (cc @maevalienard )

### System
- Strapi version: 3.3

**Comment by maevalienard** [comment]
Thanks @sam-pires for bringing up this bug. I noticed the wording isn't correct in French for the 2nd, 3rd et 5th type of relation. Here are my propositions:

<img width="72" alt="Capture d’écran 2020-12-04 à 12 07 06" src="https://user-images.githubusercontent.com/54801383/101156780-66221200-3629-11eb-9325-1c4836a09f38.png">

"CT1 a et appartient à un CT2"

<img width="62" alt="Capture d’écran 2020-12-04 à 12 07 09" src="https://user-images.githubusercontent.com/54801383/101156799-6b7f5c80-3629-11eb-9213-ec861f0fab19.png">

"CT1 appartient à plusieurs CT2"

<img width="50" alt="Capture d’écran 2020-12-04 à 12 10 52" src="https://user-images.githubusercontent.com/54801383/101157028-c913a900-3629-11eb-8d84-0a97a792596a.png">

"CT1 a et appartient à plusieurs CT2"

**Comment by croatian91** [comment]
@maevalienard done! Please do check out the PR associated
