### ISSUE TITLE
Restarting strapi will remove the collection indexes we created in the mongodb

### ISSUE THREAD

**Issue by virtualkitchenco** [strapi/strapi#8799]
### Describe the bug

Restarting strapi will remove the collection indexes we created in the mongodb.
We created this index on one of our relation field in the collection.
I don't think strapi's XXX.settings.json supports index on relation field, so I have to create the index on mongodb.com.
For example:
"order": {
      "via": "items",
      "model": "order",
      "index": true
    },

### Steps to reproduce the behavior

1. Create collection indexes in cloud.mongodb.com
2. Restart strapi server
3. Collection indexes get removed

### Expected behavior

Expected being able to create index for relation field in Strapi

### System

- Node.js version: node:11.1.0-alpine
- NPM version:
- Strapi version:  Strapi v3.0.0-beta.20
- Database: mongodb
- Operating system:

**Comment by derrickmehaffy** [comment]
`Strapi v3.0.0-beta.20` This version of Strapi is no longer supported. Are you sure this is a beta project? (Check your versions in your package.json)

**Comment by virtualkitchenco** [comment]
For some reason, we get stuck from upgrading  Strapi v3.0.0-beta.20 to Strapi v3. We have hard time following the migration guide.

However, the relation field index creation issue might not be related to Strapi version.
I guess my question is what is the best practice to create an index for a relation field. Thanks in advance.

**Comment by derrickmehaffy** [comment]
@virtualkitchenco on the latest versions we handle this at the model level: https://strapi.io/documentation/v3.x/concepts/models.html#validations

If you are having issues updating, make sure you are following all of the guides (in order): https://strapi.io/documentation/v3.x/migration-guide/#instructions

Going to mark as closed for now, in the future please use our [Forum](https://forum.strapi.io/) for asking questions

**Comment by locvfx** [comment]
I encounter the same issue, Strapi removed all my indexes
Using Strapi latest version, Fresh installation Feb 2021.

**Comment by catalint** [comment]
seems someone documented this deletion via a comment here https://github.com/strapi/strapi/blob/master/packages/strapi-connector-mongoose/lib/mount-models.js#L279

as it has a strong impact I think it requires a proper word about it in the strapi documentation

will it work with things like compound indexes? https://github.com/strapi/strapi/issues/5972 

seems to me this syncIndexes that auto-deletes some indexes without an option to disable needs one
 @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> Note, I can't figure out how to add index in the Strapi back-end UI :(

There are various options that are not available in the content-type builder UI yet, they have to be added manually.

@catalint yes you are correct

**Comment by ksaitor** [comment]
This problem still remains. How do i prevent Strapi from modifying my collection indexes? Especially compound indexes, that were manually created.

**Comment by sercanov** [comment]
This is a buzz kill. I need to go to Mongo Atlas and create unique compound index every time after deployment

**Comment by derrickmehaffy** [comment]
Keep in mind: https://github.com/strapi/strapi/issues/10186

For SQL databases we are adding in additional options for creating indexes with a Knex pre-boot migration tooling system

**Comment by parakhgoel** [comment]
I used below code in bootstrap.js as a workaround

`const { MongoClient } = require('mongodb');
const client = new MongoClient(process.env.DATABASE_URI);

//boostrap.js
module.exports = async () => {

    await client.connect();
    console.log('Connected successfully to server');
    const db = client.db(process.env.DATABASE_NAME);
    db.collection('post_search_metrics').createIndexes({ field_name: "text", field_name_2: "text"});
}`

**Comment by bportman** [comment]
Does anyone have a solution that doesn't require recreating the indexes every time strapi is restarted?

**Comment by bjorniveTekZence** [comment]
Found the cause in: node_modules\strapi-connector-mongoose\lib\mount-models.js
if (strapi.app.env !== 'production') {
      // Ensure indexes are synced with the model, prevent duplicate index errors
      // Side-effect: Delete all the indexes not present in the model.json
      Model.syncIndexes(null, handleIndexesErrors);"
}

Comment out the Model.syncIndexes and it will stop deleting indexes on start.

Probably a good idea to not use any index feature in strapi and rather add the directly in Mongodb.
