### ISSUE TITLE
list of content types does not fit on the screen

### ISSUE THREAD

**Issue by AlexCraftt** [strapi/strapi#880]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.11.2
- **Database**: MongoDB
- **Operating system**: windows 10.0.16299

**What is the current behavior?**
without changes: list of content types does not fit on the screen
**Steps to reproduce the problem**
create this issue
**What is the expected behavior?**
list of content types should be displayed on the screen,
add a scroll bar to the list
**Suggested solutions**
suggest correcting this)
![image](https://user-images.githubusercontent.com/11230165/38140113-0aa81354-343b-11e8-9737-e34e4aaded52.png)

**Comment by AlexCraftt** [comment]
screen resolution 1920x1080 pix

**Comment by Aurelsicoko** [comment]
Wow! We never imagined an API with so many models... It should be easy to handle with some front-end updates.

**Comment by AlexCraftt** [comment]
total number of content types in content type builder - 38 units

**Comment by AlexCraftt** [comment]
я бы хотел добавить еще )

**Comment by AlexCraftt** [comment]
browser: Google Chrome 65.0.3325.181 (Official assembly), (64 bit)

**Comment by AlexCraftt** [comment]
This is a test build for the site about works of art. You can watch it on the github: https://github.com/AlexCraftt/vg

**Comment by AlexCraftt** [comment]
This is a test build for the site about works of art. You can watch it on the github: https://github.com/AlexCraftt/vg

**Comment by AlexCraftt** [comment]
I think that in "combat conditions" many more types of content (models) can be used, but I will try to optimize it. I'm interested in the project, while I'm testing, trying to understand the limits of possibilities

**Comment by AlexCraftt** [comment]
I would like to see the inheritance of models in the API, use content types as parent and child )

**Comment by oeddyo** [comment]
+1
thanks for bringing this up. We also experienced this : )
