### ISSUE TITLE
Cannot return null for non-nullable field for graphql nested query type

### ISSUE THREAD

**Issue by ryankauk** [strapi/strapi#8804]
### Describe the bug

When I do a nested graphql query somewhere along the line the strapi connector bookshelf doesn't seem to populate the nested value. I'm unsure if this has to do with dynamic zones / components or just nested types in general. 

I'm unsure how bookshelf resolves the withRelated but after looking through the code it doesn't seem like graphql passes any info regarding relations into the find query methods instantiated by controllers. From my debugging it seems like the withRelated is created by association definitions automatically.

### Steps to reproduce the behavior

1. Using query
```graphql
query {
  pages(where:{slug:"/index"}){
    id
    content{
      __typename
      ...on ComponentGlobalPageLinks{
        pages(limit: 1){
          id
          content{
            __typename
          }
        }
      }
    }
  }
}
```
2. model page.settings.json
```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "Page",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "content": {
      "type": "dynamiczone",
      "components": [
        "global.page-links"
      ],
      "required": true
    }
  }
}

```
components/global/page-links.json
```json
{
  "collectionName": "components_global_page_links",
  "info": {
    "name": "Page Links",
    "icon": "pager"
  },
  "options": {},
  "attributes": {
    "pages": {
      "collection": "page"
    }
  }
}
```
strapi related dependencies
```json
{
  "dependencies":{
    "strapi": "3.3.4",
    "strapi-admin": "3.3.4",
    "strapi-connector-bookshelf": "3.3.4",
    "strapi-plugin-content-manager": "3.3.4",
    "strapi-plugin-content-type-builder": "3.3.4",
    "strapi-plugin-email": "3.3.4",
    "strapi-plugin-graphql": "3.3.4",
    "strapi-plugin-upload": "3.3.4",
    "strapi-plugin-users-permissions": "3.3.4",
    "strapi-provider-upload-cloudinary": "3.3.4",
  }
}
```
3. when I call that query I get error "Cannot return null for non-nullable field Page.content."

### Expected behavior

Should be able to populate nested fields.

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.3.4
- Database: bookshelf with postgres
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
should be fixed in v4
