### ISSUE TITLE
Cannot save collection in Content Type Builder (language issue)

### ISSUE THREAD

**Issue by Gamsake** [strapi/strapi#8806]
hello, i'm using 3.3.4 (recent version)

I found a problem that Content Type Builder cannot saved when the collection's name is not english.

<img width="346" alt="스크린샷 2020-12-06 오후 6 26 33" src="https://user-images.githubusercontent.com/3098296/101276534-e777d100-37f0-11eb-9d4f-69c07944bf1e.png">

<img width="269" alt="스크린샷 2020-12-06 오후 6 26 31" src="https://user-images.githubusercontent.com/3098296/101276527-d3cc6a80-37f0-11eb-8d5e-f2da90385ae5.png">

If a collection's name is not english, it causes the error.

<img width="814" alt="스크린샷 2020-12-06 오후 6 26 55" src="https://user-images.githubusercontent.com/3098296/101276564-3de50f80-37f1-11eb-82d2-dae502eec3c5.png">

So I have to edit it in model json file.

Thanks in advance.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
