### ISSUE TITLE
Issue with Strapi using IIS reverse proxy

### ISSUE THREAD

**Issue by nba9898** [strapi/strapi#8811]
hi guys. i'm new to strapi. i installed it on a windows server 2016. strapi is running properly when i load 127.0.0.1:1337 on my server. I applied a reverse proxy on my server using the iis url rewrite. Accessing the strapi through the domain works. i can login and view the menu's on the left. But when i click on the users tab, an error appears saying "an error occurred during models config fetch" but when i clicked users on 127.0.0.1:1337, it is displaying the users list without errors. using the domain i can add users but when it tries to refresh the users list after adding the user, the same error appears. i'm using strapi version 3.3.4 (node v14.15.1). is there a way to fix it so I can view the users list through the domain?

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.3.4 
- Database: MySql
- Operating system: Windows Server 2016

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
