### ISSUE TITLE
fields in nested relation return null

### ISSUE THREAD

**Issue by anthonymartin** [strapi/strapi#8814]
### Describe the bug

When querying to retrieve the property values of nested relations the graphql response returns null for the selected properties.

### Steps to reproduce the behavior

Query: 
```
{
  products {
    productSets {
      products {
        code
      }
    }
  }
}
```

Data Model: 

Product
```
{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "name": "product",
    "description": ""
  },
  "attributes": {
   "code": {
      "type": "text"
    },
    "productSets": {
      "collection": "product-set"
    }
  }
}
```

ProductSet:
```
{
  "kind": "collectionType",
  "collectionName": "product_sets",
  "info": {
    "name": "ProductSet",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "products": {
      "collection": "product"
    },
  }
}
```

### Expected behavior

With the given data model and relations whereby a Product has many ProductSets and ProductSets have many Products, when querying for the Products belonging to the ProductSets which belong to a Product, the nested product properties should be populated with their respective values. 

### Observed Behavior

The properties of the nested Product are being returned as null.

### Screenshots

![Screen Shot 2020-12-06 at 8 42 01 PM](https://user-images.githubusercontent.com/949506/101290784-abe70200-3804-11eb-89ad-983cb821c8be.png)

### System

- Node.js version: 12.18.0
- NPM version: 6.14.4
- Strapi version: 3.3.4 (also affects 3.2.5)
- Database: MongoDB
- Operating system: MacOS X

**Comment by steveDL** [comment]
I have the same issue this is a real blocker :(

**Comment by derrickmehaffy** [comment]
Can you please share a test project with the model structure?

**Comment by derrickmehaffy** [comment]
Couldn't reproduce on v3.4.4 and user has not provided an example project with the model structure (trying to reproduce with provided models don't seem to cause the issue)
