### ISSUE TITLE
Duplicated records / entries if you press buttons quickly

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#8827]
### Describe the bug
When you create a new content and press in "+ Add New {content}" if you press twice or more times quickly, you can create duplicate records.

### Steps to reproduce the behavior
Go to create a new content and press in "+ Add New {content}" twice or more times quickly.
### Expected behavior
Multiple Save to be Controlled Or Progressing symbol to be shown to avoid the user from clicking twice
### Code snippets

If applicable, add code samples to help explain your problem.

### System
Node.js version: Node v10.14.2
NPM version: npm v6.4.1
Strapi version: Strapi 3.0.0-alpha.16
Database: Mongodb 4.0.4
Operating system: Ubuntu 18.04
(Optional) Link to your Project
### Additional context

Ref : https://github.com/strapi/strapi/issues/2515

**Comment by sunithakarthikeyan** [comment]
This is not low priority Issue.

**Comment by soupette** [comment]
@sunithakarthikeyan can you upgrade your app to the latest version which is 3.3.4. The bug has been fixed.

I am closing this issue as we don't maintain the alpha version anymore.

**Comment by sunithakarthikeyan** [comment]
Can u reply which version has this fix and the Source Code(issue ref) ...as
we want to integrated the fix without  upgrade

**Comment by sunithakarthikeyan** [comment]
Can u please share the Bug No - So that we can integrate the Fix alone - [Version - 3.0.2]
