### ISSUE TITLE
Mixed Content error when uploading image in the admin dashboard

### ISSUE THREAD

**Issue by stat1k** [strapi/strapi#8831]
### Describe the bug

When I'm uploading an image in the admin dashboard, I get this error : 

> Mixed Content: The page at 'https://subdomain.domain.com/admin/plugins/content-manager/collectionType/application::product.product/71' was loaded over HTTPS, but requested an insecure resource 'http://subdomain.domain.com/upload/'. This request has been blocked; the content must be served over HTTPS.

Everything is working great except when I'm uploading an asset to the library

### Steps to reproduce the behavior

1. Upload asset to the library

### Expected behavior

No Mixed Content error, so the request must be in https no http

### System

- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.1.1
- Operating system: Ubuntu

### Additional context

Here is the Response Headers of the request : 

> content-length: 194
content-type: text/html
date: Tue, 08 Dec 2020 12:47:01 GMT
location: http://subdomain.domain.com/upload/
server: nginx/1.10.3 (Ubuntu)

**Comment by derrickmehaffy** [comment]
> location: http://subdomain.domain.com/upload/

What is your `url` key set to in your `./config/server.js` ?

**Comment by stat1k** [comment]
Hello, thanks for the quick response ! 
This is my `./config/server.js` : 

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: "https://subdomain.domain.com",
  admin: {
    auth: {
      secret: "SECRET",
    }
  }
});
```

**Comment by stat1k** [comment]
Hi @derrickmehaffy , do you have any idea about my problem ?
Thanks

**Comment by derrickmehaffy** [comment]
It would appear you aren't doing http => https redirection. If the URL key is set to https, you have to use https (likewise in the reverse)

**Comment by derrickmehaffy** [comment]
I'm going to mark this one as closed as I don't believe it's a Strapi code issue, but user environment. To continue the discussion if you are still having issues. Please open a thread on our forum: https://forum.strapi.io/
