### ISSUE TITLE
Unable to upload file from node JS

### ISSUE THREAD

**Issue by Jbmanllr** [strapi/strapi#8833]
### Describe the bug

When trying to upload a file from node js (i need to bulk upload images for thousands of entries), i get an error 
'(node:38011) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'fileInfo' of 'data' as it is undefined.
    at Object.upload (/Users/jbm/Dev/whatgear/backend/node_modules/strapi-plugin-upload/services/Upload.js:128:13)'

Note that the documentation is very confusing and only show code for upload via frontend:
https://strapi.io/documentation/v3.x/plugins/upload.html#upload-files-related-to-an-entry

### Steps to reproduce the behavior

So i searched for hours on end and only found few resources about uploading via node js, most f them being obsolete / for old api, etc..

I ended up with  this code:

(Readir from a local folder containing the pictures, i did not include the rest of the code (iterating through filenames to match the related entity id, etc..)
```

const form = new FormData();
                
const fileStream = fs.createReadStream('./path/to/myfile.jpg')

form.append('files', fileStream, 'myfile.jpg');

form.append('data', JSON.stringify({
    ref: 'collection',
    refId: entity.id,
    field: 'pictures',
}));

await strapi.plugins['upload'].services.upload.upload(form, {
    headers: form.getHeaders()
});

```
                `

It throw me this error 
'(node:38011) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'fileInfo' of 'data' as it is undefined.
    at Object.upload (/Users/jbm/Dev/project/backend/node_modules/strapi-plugin-upload/services/Upload.js:128:13)'

### Expected behavior

Should upload file for related entry

### System

- Node.js version: 14.15.1
- NPM version: 6.14.9
- Strapi version: 3.3.4
- Database: postgres
- Operating system: mac os Catalina

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
