### ISSUE TITLE
3.3.4 is regarded as latest version when using 3.4.0-beta.0

### ISSUE THREAD

**Issue by darron1217** [strapi/strapi#8840]
### Describe the bug
![image](https://user-images.githubusercontent.com/8064923/101557954-5f1c4a80-3a01-11eb-8356-c26c40044c90.png)

![image](https://user-images.githubusercontent.com/8064923/101557977-65122b80-3a01-11eb-8d42-8022a6a84e36.png)

### Steps to reproduce the behavior

1. Install 3.4.0-beta.0
2. Go to `/admin` and see the message

### Expected behavior

3.3.4 should be ignored when using beta release.

### Screenshots

Above

**Comment by derrickmehaffy** [comment]
Fixed in: https://github.com/strapi/strapi/pull/8910
