### ISSUE TITLE
Improvements to database layer for third-party database connectors

### ISSUE THREAD

**Issue by brettwillis** [strapi/strapi#8841]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

There is an issue with the database `count()` API, and `/count` endpoint when it comes to the bahaviours of other databases. I am aware that you are reimplementing the database layer and connector API to support community connectors, so I provide my insights from the perspective of the Cloud Firestore database (note: Firestore is billed based on usage, read/write operations).

Consider that not all databases support counting very well. For example, the Cloud Firestore database, to count a collection actually requires reading the entire collection. This incurs a read operation for every document in the collection. For large collections, such as users, this is absolutely disasterous for cost, quota usage, and latency (consider hundreds of thousands or millions of users).

Secondly, the `start` and `limit` method of pagination is inefficient for Firestore cost, quota usage, and latency (it incurs a read operation for every document from `0` through to `start + limit`). For efficiency, Firestore recommends using page cursors (where the first query would return a cursor that should be used to retrieve the next page).

### Why is it needed?

When allowing Strapi to be expanded with other databases and third-party connectors in the future, these are critical considerations in the design of the connector API which should be considered from the beginning.

#### Point 1 - lazy counting
The Strapi Admin front end attempts to `/count` the entire collection every time the list is viewed, in order to determine the total number of pages. This is simply a disasterous idea for collections like Firestore. Instead, the Strapi Admin front-end should use a lazy loading technique, i.e. to lazily fetch the next page upon request, and notify the user when they reach the end (indefinite page numbers until they find the end). Instead of counting the entire collection every time.

Perhaps this behaviour could be configurable based on a flag provided by the connector to indicate whether lazy loading should be used?

#### Point 2 - pagination with cursors
The new database API should support pagination with cursors, rather than start/offset, and the format/function of the cursor would be controlled by each particular connector.

And cursors should of course be used by default in the content manager front end when progressing through pages.

### Related issue(s)/PR(s)

See arrowheadapps/strapi-connector-firestore#33

**Comment by aksdevac** [comment]
This might make strapi behave differently for Firestore connector, pagination can't work properly without count & it is not possible to store count for each filter condition or search.
Firestore should add support for O(1) count query,
See: googleapis/google-cloud-python#5731

**Comment by brettwillis** [comment]
I'm not an expert on all the different databases, but it seems to me that count operations are O(n) complexity for many databases? I haven't seen any indication that Firestore intends to support O(1) count, and like many databases, it is probably because of fundamental design of distributed and/or NoSQL databases (?).

> This might make strapi behave differently for Firestore connector, pagination can't work properly without count

This actually what I'm suggesting - change/expand the behaviour of pagination to support lazy loading (i.e. undefined count) for database connectors which indicate that they don't support counting. This is something that will only become more necessary as the community implements more database connectors.

Without such a behaviour change, the only protection for for such databases is to force a limit on the query/count size, which will *definitely* cause unexpected behaviour for Strapi...

**Comment by aksdevac** [comment]
Ok I meant O(1) cost (firestore should count is as 1 read) for count, internal complexity may be O(n). & Even if some database stores internal count, but with filter condition it will be O(n).
