### ISSUE TITLE
GraphQL relationship args don't work

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#8846]
### Describe the bug

Having a relationship in a model creates GraphQL args like `limit` and `sort` but none of these work.

### Steps to reproduce the behavior

Create a model (dealer) that has a relationship on another model (criteria). 
Install GraphQL
Go to the playground
query:
```
{
  dealer(id:"5fbc1fb81740b2002cf9deb1") {
    id
    criteria(limit: 1) {
      id
    }
  }
}
```

### Expected behavior

The `limit` should make only 1 criterion be returned

### Screenshots

<img width="1440" alt="Schermafbeelding 2020-12-09 om 14 20 23" src="https://user-images.githubusercontent.com/6753724/101635380-30ff3080-3a2a-11eb-9db6-fdb145ac58ba.png">

### System

- Node.js version: 12.19.1
- NPM version: 
- Strapi version: 3.3.3
- Database: mongodb atlas
- Operating system: macos

### Additional context

Hope this hasn't been reported before, I couldn't find any issues like this.

**Comment by tarnacious** [comment]
I can add that I'm also running into this bug using a postgres database.

**Comment by laurenskling** [comment]
I'm actually getting correct results while upgrading to `4.3.2`, might be that https://github.com/strapi/strapi/pull/9046 helped?

**Comment by tarnacious** [comment]
Yay, I updated to from 3.4.0 to 3.4.3 and the sorting is fixed for me too (I don't have tests for the limits).

**Comment by derrickmehaffy** [comment]
Going to mark as closed as this issue should be fixed. If you still hit the issue please let us know and we can reopen.
