### ISSUE TITLE
Strapi Development server is constantly restarting.

### ISSUE THREAD

**Issue by acalvino4** [strapi/strapi#8848]
### Describe the bug

My Strapi development server is constantly (multiple times a minutes) restarting with message
```
[2020-12-09T15:55:42.872Z] info File changed: /Users/acalvino4/Code/gem/sb-admin/db/pg_wal/000000010000000000000001
[2020-12-09T15:55:42.874Z] info The server is restarting
```

### Steps to reproduce the behavior

1. `npm run develop`
2. wait. without making any changes, the server keeps restarting

### Expected behavior

Since I am not making any changes, the database wal file shouldn't be noted as changed

### System

- Node.js version: 14.8.0
- NPM version: 6.14.9
- Strapi version: 3.2.5
- Database: postgres (via docker)
- Operating system: macOS

### Additional context

If have tried reseting the database completely, so it seems the problem is on the strapi end.

**Comment by 8byr0** [comment]
It is not a bug, your DB is in a path which is watched by strapi (any fs event will trigger a restart).

You should move your DB data outside of strapi folder or add it to your `.gitignore` like this:
```
./db
```

**Comment by acalvino4** [comment]
my .gitignore does have `db` in it. Does the strapi dev server use .gitgnore to know what files to (not) watch?

**Comment by 8byr0** [comment]
My bad, gitignore has nothing to do with strapi. 

FYI strapi uses https://github.com/paulmillr/chokidar under the hood and watch your cwd (strapi app dir).

The following files are ignored (`strapi/lib/commmands/develop.js:119`)
```js
{
ignored: [
      /(^|[/\\])\../, // dot files
      /tmp/,
      '**/admin',
      '**/admin/**',
      'extensions/**/admin',
      'extensions/**/admin/**',
      '**/documentation',
      '**/documentation/**',
      '**/node_modules',
      '**/node_modules/**',
      '**/plugins.json',
      '**/index.html',
      '**/public',
      '**/public/**',
      '**/*.db*',
      '**/exports/**',
      ...watchIgnoreFiles,
    ]
}
```

So if you want your db to be ignored:
- move it elsewhere (best option IMHO)
- match any of the pattern below for the name of the db folder


Most of my strapi projects are running inside docker and what I usually do is:
```
Project directory
|-- strapi app directory
|-- db directory
|-- docker-compose.yml
```

**Comment by acalvino4** [comment]
Thank you for this excellent reply. this gives me the background to move forward.

**Comment by rajratnamaitry** [comment]
add  path  in 'watchIgnoreFiles ' as array  element in server.js file
`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'http://localhost:8888/service-catalog',
  admin: {
    watchIgnoreFiles : [
    '**/info.log',
    '**/error.log'
    ],
    url:'http://localhost:8888/dashboard',
    auth: {
      secret: env('ADMIN_JWT_SECRET', '1231231'),
    },
  },
});
`

**Comment by johnone** [comment]
> My bad, gitignore has nothing to do with strapi.
> 
> FYI strapi uses https://github.com/paulmillr/chokidar under the hood and watch your cwd (strapi app dir).
> 
> The following files are ignored (`strapi/lib/commmands/develop.js:119`)
> 
> ```js
> {
> ignored: [
>       /(^|[/\\])\../, // dot files
>       /tmp/,
>       '**/admin',
>       '**/admin/**',
>       'extensions/**/admin',
>       'extensions/**/admin/**',
>       '**/documentation',
>       '**/documentation/**',
>       '**/node_modules',
>       '**/node_modules/**',
>       '**/plugins.json',
>       '**/index.html',
>       '**/public',
>       '**/public/**',
>       '**/*.db*',
>       '**/exports/**',
>       ...watchIgnoreFiles,
>     ]
> }
> ```
> 
> So if you want your db to be ignored:
> 
> * move it elsewhere (best option IMHO)
> * match any of the pattern below for the name of the db folder
> 
> Personally, most of my strapi projects are running inside docker and what I usually do is:
> 
> ```
> Project directory
> |-- strapi app directory
> |-- db directory
> |-- docker-compose.yml
> ```

Hey there, thank you for this explanation. I am having the same problem, the docker container keeps restarting. Can you tell me what I have to do exactly to "move the db to somewhere else, so that it will be ignored" ? I would appreciate any help. Thanks in advance, Johnny

**Comment by johnone** [comment]
Hey there, thank you for this explanation. I am having the same problem, the docker container keeps restarting. Can you tell me what I have to do exactly to "move the db to somewhere else, so that it will be ignored" ? I would appreciate any help. Thanks in advance, Johnny

**Comment by flav1o** [comment]
A bit late to the party, but this "problem" still happens when using Postgres in Strapi v4.  Adding this line `watchIgnoreFiles: ["**/db"]```  to the admin.ts will stop the repeated server restarts.

**Comment by michelegranatiero** [comment]
When you run strapi in dev mode the admin panel is served separately on port 5173 by default. In strapi 5 there is no simple way to change this behavior I belive. I managed to solve the problem by using `npm run dev -- --no-watch-admin` which should disable hot reloading for the admin panel

**Comment by Tobvl** [comment]
I can't resolve this error in my docker compose :'( any advice?
EDIT: got it working with this config
`services:
  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: development
    volumes:
      - ./strapi/public/uploads:/opt/app/public/uploads
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapibackend

  postgres:
    container_name: postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapibackend
      
networks:
  strapibackend:
    name: strapibackend
    driver: bridge`
the project inside a /strapi folder and outside that, a .env and compose file
