### ISSUE TITLE
Use yarn workspace

### ISSUE THREAD

**Issue by caoer** [strapi/strapi#885]
Just a suggestion, is there any plan to use yarn workspace, it does look promising.
Here is some related references:

* [How to use yarn workspaces with Create React App and Create React Native App (Expo) to share common…](https://medium.com/viewsdx/how-to-use-yarn-workspaces-with-create-react-app-and-create-react-native-app-expo-to-share-common-ea27bc4bad62)
* [Workspaces | Yarn](https://yarnpkg.com/lang/en/docs/workspaces/)
* [Workspaces in Yarn | Yarn Blog](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/)
* [nohoist in Workspaces | Yarn Blog](https://yarnpkg.com/blog/2018/02/15/nohoist/)
* [Behind the Scenes: Improving the Repository Infrastructure - React Blog](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html)

**Comment by abdonrd** [comment]
From https://github.com/strapi/strapi/issues/972#issue-315762164:

> > Workspaces are a new way to setup your package architecture that’s available by default starting from Yarn 1.0. It allows you to setup multiple packages in such a way that you only need to run `yarn install` once to install all of them in a single pass.
> 
> Reference: https://yarnpkg.com/lang/en/docs/workspaces/
> 
> Reference at `Yarn Workspaces` of [One vs. many — Why we moved from multiple git repos to a monorepo and how we set it up](https://hackernoon.com/one-vs-many-why-we-moved-from-multiple-git-repos-to-a-monorepo-and-how-we-set-it-up-f4abb0cfe469).

**Comment by lauriejim** [comment]
Feel free to submit a PR to make it possible. We will not work on it.

**Comment by Aurelsicoko** [comment]
I'm closing the issue because we don't plan to use Yarn workspace for now.

**Comment by AndreCox** [comment]
Is there any chance this issue will be revisited as strapi works somewhat with workspaces right now but fails when working with plugins
