### ISSUE TITLE
POST /upload Unauthorized

### ISSUE THREAD

**Issue by M4r-t1n4** [strapi/strapi#8852]
Hello,
I have this problem when I upload a file like this:

```

  var formData = new FormData();
     formData.append("files", file);

    axios.post('http://localhost:1337/upload',formData, {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
}   )
            .then((response) => {
      callback(response.data);
    })
    .catch(function (error) {
      callback(null);
    });
```

The error is 

POST http://localhost:1337/upload 401 (Unauthorized).
Do you have any suggestions to solve the problem?

System

Node.js version: 13.7.0
Strapi version: 3.3.3
Database: MongoDB

**Comment by melihoeztuerk** [comment]
Did you enabled the route in admin dashboard? Settings > Roles and Permission > Roles search for Upload then check the POST /upload route for the specific Role. If you select it for the authenticated user then you shoud also send credentials like jwt token.

**Comment by M4r-t1n4** [comment]
I have enabled the route in admin dashboard. 
With Postman the request is ok.
![Schermata del 2020-12-09 19-37-55](https://user-images.githubusercontent.com/8268384/101672445-2b1f4480-3a56-11eb-8757-167b369015d4.png)

**Comment by aksdevac** [comment]
If its working with Postman then its not a strapi's issue, make sure you are passing correct token in auth header

**Comment by M4r-t1n4** [comment]
But in Postman I don't insert authorization

**Comment by aksdevac** [comment]
Means its public route? Try code which is generated from Postman.
