### ISSUE TITLE
Production app often cashes and only show table Users

### ISSUE THREAD

**Issue by pntech20** [strapi/strapi#8854]
Hello Strapi team 👋 Thank you for great work.
## Bug report
Production app often cashes and only show table Users

### Describe the bug
I'm using Strapi for a project as backend and ReactJS as frontend.
Also, I'm using Github Actions for CI/CD.

The deployment work well but sometime the app crashes on admin panel.
It only show the User table although I have some others.

### Screenshots

<img width="240" alt="Screen Shot 2020-12-10 at 10 20 26" src="https://user-images.githubusercontent.com/63446025/101725329-fefdd500-3ae2-11eb-8670-8cf5adcbd72c.png">

### System

- Node.js version: 14.15.1
- NPM version: 6.14.8
- Strapi version: 3.3.4
- Database: MongoDB
- Operating system: AWS EC2 instance, t2.small, Ubuntu 20.4

**Comment by derrickmehaffy** [comment]
Please provide steps to reproduce or share an example application that you can replicate the issue.

Marking as closed as we have no reproduction steps.

**Comment by pntech20** [comment]
For others who may get into this trouble in future:
After upgrading the instance type from **t2.small** to **t3 medium** the issue has gone.
So the problem is the old server was not strong enough to run Strapi smoothly.
