### ISSUE TITLE
Loose relations one to many relation

### ISSUE THREAD

**Issue by XcrossD** [strapi/strapi#886]
**Informations**
- **Node.js version**: 
9.8.0
- **npm version**: 
5.6.0
- **Strapi version**: 
3.0.0-alpha.11.1
- **Database**: 
MongoDB
- **Operating system**: 
Windows 10

**What is the current behavior?**
One to many relation is causing error on saving.

**Steps to reproduce the problem**

1. Create content type "product"
![product](https://user-images.githubusercontent.com/6669029/38189521-3bde3f02-3693-11e8-8692-85cb560ae08a.PNG)

2. Create content type "productspecification"
![productspecificationbefore](https://user-images.githubusercontent.com/6669029/38189523-4131ac6e-3693-11e8-9140-d6a683641afc.PNG)

3. Add relation to "productspecification"
![addrelation](https://user-images.githubusercontent.com/6669029/38189505-215f7d62-3693-11e8-9dbd-7a861d91b937.PNG)
**Side note: there is a UI bug here. Whenever choosing which content type to add a relation to, its name will disappear**
![productspecificationpage](https://user-images.githubusercontent.com/6669029/38189580-6ffb3a06-3693-11e8-9324-4a9e25145d68.PNG)
**I think (from:) is weird here.**
4. Save
5. Error appears
![errormessage](https://user-images.githubusercontent.com/6669029/38189533-4b2a5298-3693-11e8-911e-7d5a1c753fe3.PNG)

**What is the expected behavior?**
Strapi should restart without error. I read a few of the issues other people have, and I'm sure I used all lowercase and the relation should be one to many. A product has many specifications, but each specification should only link to one product.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @XcrossD I reproduce step by step your case and it work fine on my side.

Can you try with the last version of Strapi (alpha.11.3) and reproduce step by step your case and tell me if it works on your side.

Don't know where it can come from.

**Comment by lauriejim** [comment]
I think this is a duplicate on this one https://github.com/strapi/strapi/issues/795

**Comment by XcrossD** [comment]
It is the same error that I saw. The difference is that I am adding a relation from another content type, not from itself. I don't know if that counts as the same error.

I updated to alpha.11.3 and the issue is still not resolved. Hopefully the gif video will help a bit - at least you can see it is really going wrong.
![recording1](https://user-images.githubusercontent.com/6669029/38475791-eacd21e2-3bdc-11e8-9d9e-2a703f5f42e5.gif)

**Comment by lauriejim** [comment]
@XcrossD can you share with me your models (maybe it's coming from here). I probably will be able to reproduce it to help you.

**Comment by XcrossD** [comment]
@lauriejim Can you tell me exactly what is the necessary data for you to reproduce, and where to find it? I know it's best if you have all the data but we are building this website for a client, and I don't think they will be too happy if we leak out their data.

**Comment by lauriejim** [comment]
I need all your models.settings.json files. Don't need any database data.

If you are agree to share it with me, you can join our Slack (https://slack.strapi.io) and send me these files. Will stay confidential with your shared files.

**Comment by lauriejim** [comment]
@XcrossD I create a new application and use your `api` folder and I wasn't able to reproduce your issue. I follow step by step your case.

Can you also try on your computer with new application and use just your `api` folder.

**Comment by XcrossD** [comment]
@lauriejim I just tried using a new application but the error still persists. What I did was `strapi new test`, copy api folder to "test", `strapi start`. I also noticed that my global strapi version is still at alpha.11.1, so I updated to alpha.11.3, created a new application again, but it still doesn't work. Are there any other tests that I can do?

**Comment by cece95** [comment]
I'm experiencing the very same issue

-**Node.js version:**
9.10.1
-**npm version:**
5.6.0
-**Strapi version:**
3.0.0-alpha.11.3
-**Database:**
MongoDB
-**Operating system:**
Ubuntu 14.04

**Comment by Aurelsicoko** [comment]
@XcrossD I can't reproduce it too. I followed the GIF and it works well on my machine. Can you test with the latest release alpha.12?

**Comment by XcrossD** [comment]
@Aurelsicoko Tested again with alpha.12, no luck. Same setup with the [permission ticks issue](https://github.com/strapi/strapi/issues/977)

**Comment by Aurelsicoko** [comment]
@XcrossD Maybe [this change](https://github.com/strapi/strapi/pull/1052) has fixed this issue as well?

**Comment by XcrossD** [comment]
@Aurelsicoko This is a browser issue. I updated to alpha.12.0.1 and it works on chrome but not on firefox. I'm really out of luck using firefox as my main development browser. Maybe I should switch to chrome.

**Comment by Aurelsicoko** [comment]
Oh damn! I tried on Chrome, Safari and Opera, I forgot to test on Firefox. I'm going to check again on this browser and make a PR to fix it.

**Comment by Aurelsicoko** [comment]
@XcrossD It fixed https://github.com/strapi/strapi/pull/1081

**Comment by indiecore-fm** [comment]
I am still having this issue as of 12.2

**Comment by Velua** [comment]
I'm also having this issue at 12.2, same as described.

**Comment by Velua** [comment]
It doesn't appear to happen if I make the relationship from the other model. 
E.g. instead of editing the blogPost model and referencing a relationship with categorie
I edit the categorie model and reference a relationship with the blogPosts model.

**Comment by Aurelsicoko** [comment]
Can someone give us a very detailed step by step tutorial to reproduce this one (@indiecore-fm, @Velua)?

**Comment by gammanano** [comment]
Hi @Aurelsicoko 

I get the same issue at 13.0.1. For the reproduce this issue, simply you just create 2 model (ex: Product and Category) then you create relation for them, in the relation GUI, you select any models several times. The title in Model selected will disappear (except: Permission, User, Role model) then you click continue and save. This issue will make server down when you refresh page.

**Comment by lauriejim** [comment]
Look to be good in last version of strapi. Will reopen if needed with steps to reproduce
