### ISSUE TITLE
An error occurred on new collection type creation

### ISSUE THREAD

**Issue by nalumachurakesh** [strapi/strapi#8862]
Hi,

I created a new strapi project using **npx create-strapi-app my-project --quickstart** and I created the admin user. When I save the new collection type application prompted a "An error occurred" message and found some console errors. I have attached the console screenshot.

![console error](https://user-images.githubusercontent.com/13477420/101782678-50986680-3ac7-11eb-8a24-e8db54798e7f.PNG)

These are the end points logged in console as error

http://localhost:1337/admin/users/me/permissions 
http://localhost:1337/content-manager/content-types 

Got this message on api invocation - {"statusCode":403,"error":"Forbidden","message":"Forbidden"}

Please let me know how to fix that.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
