### ISSUE TITLE
User dropdown (User from Admin table)

### ISSUE THREAD

**Issue by kantan-florian** [strapi/strapi#8863]
## User dropdown not populated in admin

When I set a relation to the user table (Admin user!) in any collection type, i don't see any names in the dropdown inside the strapi admin ui.

### Steps to reproduce the behavior

1. Create collection data type
2. Add relation to user (admin) table
3. Open single edit of one of these collection type entries of 1.
4. Open the user relation dropdown

### Expected behavior

See the Names or E-Mails of the admin users.

### Screenshots

![image](https://user-images.githubusercontent.com/16814675/101787336-44300000-3aff-11eb-9533-855614f47b50.png)
![image](https://user-images.githubusercontent.com/16814675/101787460-66298280-3aff-11eb-8d15-44b444887952.png)

### System

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.3.4
- Database: mysql
- Operating system: windows

**Comment by sebqq** [comment]
You can try to:

1. Press "Configure the view" button inside of your collection.
2. Press on your `Author` field to edit relation field.
3. Set different "Entry title" field to represent `Author` in your collection (for example username or email).

**Comment by kantan-florian** [comment]
Hi Seb,

i already tried, it looks like that:
![image](https://user-images.githubusercontent.com/16814675/102482694-e9008f00-4063-11eb-83e8-1d7a529f294b.png)

Florian

**Comment by sebqq** [comment]
@kantan-florian Does your Author collection have at least 1 required text-type field defined in it's schema?

**Comment by kantan-florian** [comment]
@sebqq Author is related to the admin user table:
![image](https://user-images.githubusercontent.com/16814675/102484562-bc9a4200-4066-11eb-84a7-7dc5be080780.png)

**Comment by kantan-florian** [comment]
@sebqq 
this is my own user (admin):
![image](https://user-images.githubusercontent.com/16814675/102484929-3af6e400-4067-11eb-88c3-4ef2b4e719ab.png)

is it possible that in the view when linking against admin users the username is hardcoded somewhere for the dropdowns?

**Comment by sebqq** [comment]
Hmm. I've never done relation with admin user table before. Maybe there could be some permission problems?

**Comment by kantan-florian** [comment]
I just double checked: when I set the username of an admin, i see the username in this dropdown. now the question is, since username got killed couple of weeks ago... it would be great to fix the "entry title" dropdown in the configure view settings, cause then we could configure it not to use the username field.

**Comment by kantan-florian** [comment]
Can somebody direct me to the right file? Maybe I can create a fix.

**Comment by pelumiojebode** [comment]
Thanks
Please fix it up
😖

**Comment by kantan-florian** [comment]
@pelumiojebode I am not a strapi developer, I need some guidance ;)

**Comment by soupette** [comment]
@kantan-florian you can change the mainField of your entry in your model's configuration view so it display the firstname instead of the username.

**Comment by JabStrapi** [comment]
I'll close this issue since @soupette answered it.
