### ISSUE TITLE
Strapi & sendgrid forgot password request issue: 400 error Bad Request

### ISSUE THREAD

**Issue by forexlit** [strapi/strapi#8875]
Strapi version: **3.3.4**
Node version: **v12.18.4**
Sendgrid version: **^3.3.4**

I have issues with sending emails. What I'm trying to do is to send forgot password email and I get 400 error Bad Request. I've already installed Sendgrid, and created a file config/plugins.js and added my credentials. Credentials are correct, because I've tried them by creating a simple node app to send the email. Email address is correct as well and  a user with such email exists. I'v'e also changed shipper and response emails in email template settings. I don't know what else can I do... It looks like Strapi does not take my credentials from config/plugins.js. Any ideas?

This is what I get in postman:
![Screenshot 2020-12-11 at 23 30 06](https://user-images.githubusercontent.com/19687950/101956983-39fa2880-3c09-11eb-8fc2-a2e013008135.png)

This is what I get in console:

<img width="1068" alt="Screenshot 2020-12-11 at 23 34 27" src="https://user-images.githubusercontent.com/19687950/101957092-729a0200-3c09-11eb-8e9c-af3a9c9bcfea.png">

This is how my sendgrid settings looks like:
<img width="660" alt="Screenshot 2020-12-11 at 23 35 11" src="https://user-images.githubusercontent.com/19687950/101957179-9d845600-3c09-11eb-960c-10a541f65ce8.png">

I would really appreciate your help, thanks!

**Comment by derrickmehaffy** [comment]
Please check your actual from/replyTo in the users-permissions settings advanced settings (in the templates). Those two values are for the internal email API and the email endpoints.

**Comment by derrickmehaffy** [comment]
Closing as no new information

**Comment by FaijanSaifi99** [comment]
> templates

it worked. thanks a lot.
