### ISSUE TITLE
Empty query results when Has Many field is empy

### ISSUE THREAD

**Issue by frvasquezjaquez** [strapi/strapi#8877]
### Describe the bug

When I try to make a query using the _**_ne**_ filter on a **_Has Many_** field, it returns null if the related field is empty.

### Steps to reproduce the behavior

1. Create a collection called _**Entity Notification Event**_
2. Create a field called **_ReadBy_** related to the _**user-permission.user**_ collection as **_Has Many_**.
3. Create an Entity Notification Event record without any user in the ReadBy.
4. Create a Graphql Query who execute the following code:
`   const hasUnreadNotifications = await strapi.query('entity-notification-event').find({
      'readBy.id_ne': currentUser.id
    });
`
### Current behavior:

The hasUnreadNotifications value is an empty array.

### Expected behavior

The hasUnreadNotifications value should be all the Entity Notification Event records where ReadBy field doest have with the current user in list, even if the ReadBy field is empty.

### Code snippets

**Custom method to test**

```  
  async me(ctx) {
    const user = ctx.state.user;

    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
    }
    let currentUser = sanitizeUser(user);


    const hasUnreadNotifications = await strapi.query('entity-notification-event').find({
      'readBy.id_ne': currentUser.id
    });
 
    return hasUnreadNotifications
    
  },
```

### System

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.2.5
- Database: Postgresql 13.0
- Operating system: Linux Debian (docker)

### Additional context

After enable the Postgresql query log, i could see that the following query is executed

```
SELECT DISTINCT "entity_notification_events".*
FROM   "entity_notification_events" 
       LEFT JOIN "pidb"."public"."entity_notification_events__read_by" AS 
                 "entity_notification_events__read_by_1" 
              ON "entity_notification_events__read_by_1"."entity_notification_event_id" = "entity_notification_events"."id" 
       LEFT JOIN "pidb"."public"."users-permissions_user" AS 
                 "users-permissions_user_1" 
              ON "entity_notification_events__read_by_1"."user_id" =  "users-permissions_user_1"."id" 	 
WHERE "entity_notification_events__read_by_1"."user_id" != $1  <---PARAM: Relace it with the current user id
```

I think the issue is as "entity_notification_events__read_by_1"."user_id" is null the SQL engine avoid the result.

**Comment by derrickmehaffy** [comment]
Can you please test with a simple `readBy_nin: currentUser.id`

**Comment by frvasquezjaquez** [comment]
I got the same result. It works if the readBt field has at least one value, but if that field is empty it doesnt work

**Comment by derrickmehaffy** [comment]
should be fixed in v4
