### ISSUE TITLE
 debug ⛔️ Server wasn't able to start properly.

### ISSUE THREAD

**Issue by Developer-Anjan** [strapi/strapi#8879]
I was trying to upload my project to aws following the guide available on strapi documentation but getting the following error: 

**debug ⛔️ Server wasn't able to start properly.
error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
 |     at /home/ubuntu/estate/node_modules/knex/lib/client.js:318:17
|     at tryCatcher (/home/ubuntu/estate/node_modules/bluebird/js/release/util.js:16:23)
|     at /home/ubuntu/estate/node_modules/bluebird/js/release/catch_filter.js:17:41
|     at tryCatcher (/home/ubuntu/estate/node_modules/bluebird/js/release/util.js:16:23)
|     at Promise._settlePromiseFromHandler (/home/ubuntu/estate/node_modules/bluebird/js/release/promise.js:547:31)
|     at Promise._settlePromise (/home/ubuntu/estate/node_modules/bluebird/js/release/promise.js:604:18)
|     at Promise._settlePromise0 (/home/ubuntu/estate/node_modules/bluebird/js/release/promise.js:649:10)
|     at Promise._settlePromises (/home/ubuntu/estate/node_modules/bluebird/js/release/promise.js:725:18)
|     at _drainQueueStep (/home/ubuntu/estate/node_modules/bluebird/js/release/async.js:93:12)
|     at _drainQueue (/home/ubuntu/estate/node_modules/bluebird/js/release/async.js:86:9)
|     at Async._drainQueues (/home/ubuntu/estate/node_modules/bluebird/js/release/async.js:102:5)
|     at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/estate/node_modules/bluebird/js/release/async.js:15:14)
|     at processImmediate (internal/timers.js:461:21)**

### Here is my package.json file

**{
  "name": "v-1",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.5.1",
    "sqlite3": "latest",
    "strapi": "3.3.3",
    "strapi-admin": "3.3.3",
    "strapi-connector-bookshelf": "3.3.3",
    "strapi-plugin-content-manager": "3.3.3",
    "strapi-plugin-content-type-builder": "3.3.3",
    "strapi-plugin-documentation": "^3.3.3",
    "strapi-plugin-email": "3.3.3",
    "strapi-plugin-upload": "3.3.3",
    "strapi-plugin-users-permissions": "3.3.3",
    "strapi-provider-email-console": "0.0.1",
    "strapi-provider-upload-aws-s3": "^3.3.4",
    "strapi-utils": "3.3.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "93637095-f354-41b4-8f62-8e0787319ce7"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}**

I have tried every possible solutions that are available on internet but nothing has solved  the issue. Can anybody kindly point me out what I am doing wrong ?

**Comment by alp-ex** [comment]
not sure but it might be related to #8865

**Comment by aksdevac** [comment]
See: https://stackoverflow.com/questions/40435315/knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing
Update your knex version if you are using Node 14.

**Comment by Developer-Anjan** [comment]
Thanx for your valuable reply but nothing has worked for me. So I installed Postgres in EC2 and use that as my database and it works for me very well. 

Thank you

**Comment by Developer-Anjan** [comment]
So I am closing this issue also as we have an alternative to avoid this issue. But if someone knows exactly why this issue arise kindly let us know. Thank you

**Comment by jieliu218** [comment]
I had the same issue

**Comment by derrickmehaffy** [comment]
Any of you with the issue, look at the knee pooling options and provide your `options` object in your database.js

https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#database

**Comment by Developer-Anjan** [comment]
1st check whether AWS_SECRET_ID, KEY, DB_NAME, USERNAME, PASSWORD is correct or not. If correct and still not working then go for @derrickmehaffy and @aksdevac solution. If still it is not working go for my solution. Thank you.
