### ISSUE TITLE
graphql groupBy nested keys

### ISSUE THREAD

**Issue by megetron** [strapi/strapi#8884]
graphql groupBy queries currently supports displaying the key and the connection itself.
if the key is a nested one and you would like to show a nested fields you cannot - which is a common usecase.

for example a **brand** has many **phones**
the following query shows how many phones per brand key:

```
query {
  phonesConnection {
    groupBy {
      brand {
        key <-----------------------
        connection {
          aggregate {
            count
          }
        }
      }
    }
  }
}

```

it would be a common thing to collect the group by key as a nested one so you can show the brand name in the results.
something like this:

```
query {
  phonesConnection {
    groupBy {
      brand {
        key{name}  <-----------------------
        connection {
          aggregate {
            count
          }
        }
      }
    }
  }
}

```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
