### ISSUE TITLE
Cannot create mutual relation from entity to itself via Content-Types-Builder

### ISSUE THREAD

**Issue by YochayCO** [strapi/strapi#8886]
### Describe the bug

I try to add a mutual relation from a collection to itself, such as "friends" or "friend" (so that each person could have a list of friends, and if B is a friend of A then A is a friend of B

### Steps to reproduce the behavior

1. Go to 'Content-Types-Builder'
2. Click on 'Add another field'
3. Fill data like in the screenshot
4. See "This value is already used."

### Expected behavior

Relation will be created, and when I add a friend to a person's friends list, this person will appear in his friend's friends list

### Screenshots
![image](https://user-images.githubusercontent.com/15094937/102060719-35956180-3dfb-11eb-8cee-049b46d5bb8c.png)

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.3.4
- Database: not connected yet I think
- Operating system: windows

**Comment by derrickmehaffy** [comment]
This is functioning as intended, you can't have two fields with the same name. This type of relation requires two names (thus two columns).

In your case, an intern table/model will likely need to be used.
