### ISSUE TITLE
Migrated from SQLite to PostgreSQL: Empty side menu

### ISSUE THREAD

**Issue by baptisteArno** [strapi/strapi#8888]
I had this issue : #7214 using SQLite locally. So I decided to migrate to a postgres DB and I loaded the existing `data.db` file into my newly created postgres database using [pgloader](https://pgloader.readthedocs.io/en/latest/quickstart.html#migrating-from-sqlite). I changed the local connection config to:
```
connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        host: "localhost",
        port: 5432,
        database: "new-db",
        username: "baptistearnaud",
      },
      options: {
        ssl: false,
      },
    },
  }
```
I get no errors at all but the menu is empty:
![CleanShot 2020-12-14 at 11 29 37](https://user-images.githubusercontent.com/16015833/102070656-b0f91200-3dff-11eb-9d53-aac57fa7dc79.png)

---
I'm planning on contributing to the documentation if it can work 💪

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
