### ISSUE TITLE
Remove Google indexing of 3.0.0-beta docs and/or redirect them to correct 3.x.x page

### ISSUE THREAD

**Issue by jorisw** [strapi/strapi#8896]
### Describe the bug

When Googling for anything Strapi related, the search results take you to the `3.0.0-beta` docs. This is confusing if you don't immediately notice the outdated notice in the top of the page.

Then, when you click the link in the top of the page that says there's more updated docs, you're taken to the homepage of the docs, meaning you're lost, and need to navigate to a page that you haven't navigated to before (because you entered from Google).

Please set `noindex` headers on the 3.0.0-beta docs. They are severely outdated (considering we're at `3.2.x` at present) and hurt the developer experience (of which Googling into the docs is a big part).

### Steps to reproduce the behavior

1. Go to https://www.google.com
2. Type in 'strapi graphql mutation'
3. Click on the most relevant looking result
4. Get taken to a `3.0.0-beta` related page
5. Click on the link in the top left that says there are `3.x.x` docs now
6. End up on the homepage of the `3.x.x`, not knowing where to go from there

### Expected behavior

I expect `3.x.x` or whatever the latest docs are, to show up in Google, rather than outdated docs.

I expect to be deeplinked from Google to the latest relevant doc page when having Googled a specific topic.

I expect `3.0.0-beta` pages to no longer be indexed by Google. This can be controlled through `noindex` headers or `robots.txt`. 

I expect the `3.0.0-beta pages` to be considered outdated such that they are better off being 301 redirected to whatever the current equivalent page is (not the Strapi docs home page).

### Screenshots

![image](https://user-images.githubusercontent.com/30017/102195991-95edd700-3ebf-11eb-9dd4-31b52a1c26a2.png)

# ↓

![image](https://user-images.githubusercontent.com/30017/102196031-a30ac600-3ebf-11eb-9ba5-6af36814b2c1.png)

# ↓

![image](https://user-images.githubusercontent.com/30017/102196062-ac942e00-3ebf-11eb-969e-074c920d01ab.png)

**Comment by derrickmehaffy** [comment]
Fixed with the new documentation :smile: :)

https://github.com/strapi/documentation

**Comment by jorisw** [comment]
Just curious but how does it fix the issue? Are you moving to a new documentation site? If so will you unindex the old docs from Google?

**Comment by derrickmehaffy** [comment]
> Just curious but how does it fix the issue? Are you moving to a new documentation site? If so will you unindex the old docs from Google?

We didn't index them to begin with, but yes its a "new site" and the old documentation no longer exists but is properly redirected to the new one.

In time Google will crawl the new site and update.
