### ISSUE TITLE
Service find by `created_by` not work

### ISSUE THREAD

**Issue by borm** [strapi/strapi#8905]
### Returned all entries, no filter by entry owner

```
async find(created_by) {
  return strapi.query(COLLECTION_NAME).find({ 'created_by': created_by }, [])
},
```

### Works correct, return only entries by created_by
```
const { default: knex } = strapi.connections;

return knex(COLLECTION_NAME).where('created_by', created_by);
```

### System

- Node.js version: 12.16.3
- Strapi version: 3.3.4
- Database: sqlite
- Operating system: macOs

**Comment by derrickmehaffy** [comment]
Works perfect on v3.4.1:

![image](https://user-images.githubusercontent.com/8593673/102936391-f13e3d00-445c-11eb-8eda-9ad4184247c7.png)

Using the following code:

```js
'use strict';
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  async findBy(ctx) {
    const { created_by } = ctx.query

    let entities = await strapi.query('source').find({ created_by }, []);

    return entities.map(entity => sanitizeEntity(entity, { model: strapi.models.source }));
  }
};
```

and the route:

```json
{
  "routes": [
  ...
    {
      "method": "GET",
      "path": "/sources/find/custom",
      "handler": "source.findBy",
      "config": {
        "policies": []
      }
    },
  ...
  ]
}
```

See the following response with the default find

![image](https://user-images.githubusercontent.com/8593673/102936541-32cee800-445d-11eb-9aa1-8c0ed4ad2806.png)

And the data in the database

![image](https://user-images.githubusercontent.com/8593673/102936693-77f31a00-445d-11eb-97d4-cad3a474876c.png)

Marking as closed.
