### ISSUE TITLE
Cannot read property '_id' of null in UsersPermissions.js after restoring a database to a fresh installation

### ISSUE THREAD

**Issue by mrzapp** [strapi/strapi#8907]
## Bug report

Similar to #2874, although the proposed solution did not work for me.

### Describe the bug

After restoring the database of an existing project to a fresh installation, the app crashes with an unhandled null reference exception.

```
TypeError: Cannot read property '_id' of null
at /srv/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:263:59
at Array.map (<anonymous>)
at Object.updatePermissions (/srv/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:262:46)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async module.exports (/srv/app/node_modules/strapi-plugin-users-permissions/config/functions/bootstrap.js:186:3)
at async Promise.all (index 5)
at async Strapi.runBootstrapFunctions (/srv/app/node_modules/strapi/lib/Strapi.js:407:5)
at async Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:339:5)
at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:193:9)
```

### Steps to reproduce the behaviour

1. Perform a `mongodump` on the database of an existing Strapi installation
2. Restore the database to a fresh Strapi installation with `mongorestore`

### Expected behaviour

A restored project similar to the one that was dumped

### Proposed solution

Include a null check. No matter what the problem with the data is, it's best practice to always perform null checks absolutely everywhere, so the app will fail gracefully and properly inform the user of exactly what the problem is.

### System

* Ubuntu sever 20.04
* Strapi 3.3.4 Docker image
* NPM 6.14

**Comment by ghonchesefidi** [comment]
I have the same problem Strapi version 3.4.0

**Comment by ghonchesefidi** [comment]
> I have the same problem but I got '_id' undefined.
> [2020-12-18T13:34:48.295Z] error Bootstrap function in plugin "users-permissions" failed
> [2020-12-18T13:34:48.296Z] error TypeError: Cannot read property '_id' of undefined
> I just migrated my database to a new fresh Strapi install
> I'm using Strapi version 3.4.0 and Mongodb
> I also tried to remove package-lock.json and build the admin again as @lauriejim mentioned in the previously closed issue.

I was able to solve my problem using this suggestion : [link](https://github.com/strapi/strapi/issues/6640#issuecomment-697222483)

**Comment by alexzaganelli** [comment]
This seems to happen when the JWT_SECRET change. It's embarrassing.

**Comment by derrickmehaffy** [comment]
dupliate: https://github.com/strapi/strapi/issues/6640
