### ISSUE TITLE
404 URL for strapi's blog articles

### ISSUE THREAD

**Issue by gramsco** [strapi/strapi#8911]
## Bug report

Strapi Blog's articles point to 404 URL within any strapi project's admin panel that display them. Not a vital issue, I guess :)

### Describe the bug

When going to the /admin panel in strapi, you see articles from Strapi's blog but the url is 404 (NextJS default 404 page).

I believed they might exist but are not published and/or the website is not rebuilt automatically on a new publication.  Or the slug might be invalid (?). 

Examples (on December 16th, 2020) :

ex_1 : https://strapi.io/blog/jamstack-in-2020
ex_2 : https://strapi.io/blog/change-the-default-wysiwyg-by-toast-ui-editor

I'm reporting it because I saw this behavior a few weeks ago...

### Steps to reproduce the behavior

1. Go to localhost:1337/admin or yourdeployedstrapi/admin
2. Click on any article
3. See NextJS default 404 page

### Expected behavior

It should redirect to... a non-404 page 😄 

### System

I believe it's system agnostic ; french locale on admin panel (but a URL is a URL, right)

### Possible fixes

Fix could probably be one of the following: 

- to use a fallback for getStaticPaths that allow the loading at run time
- to rebuild on every new publication (with a webhook)

**Comment by derrickmehaffy** [comment]
Hi @gramsco 

We are aware of an issue where some draft articles are showing in the admin panel, for the moment we are still working on fix, but thank you for letting us know.

The articles should be released soon :wink: 

Going to mark this as closed as it's not an issue with the code-base but is upstream within our infrastructure.
