### ISSUE TITLE
Upload of multiple images directly into Rich Text Field fails

### ISSUE THREAD

**Issue by acalvino4** [strapi/strapi#8914]
## Bug report

When uploading multiple images to a Rich Text Field, all images are added to media library, but only one gets selected for addition to the field.

### Steps to reproduce the behavior

1. Create Collection type with Rich Text Field
2. Click the icon to add images to Text Field
3. Click "Add more assets"
4. Browse local files, Select multiple images, then open them
5. Click "Add _ assets to library"

When finished, only one of the assets is added to the rich text field. All are added to library

### Expected behavior

I expect all the images to be added to the text field

### Screenshots

I have a screencast of the issue, but not sure best way to share here (60MB)

### Code snippets

NA

### System

- Node.js version: 14.8.0
- NPM version: 6.14.9
- Strapi version: 3.3.4
- Database: Postgres
- Operating system: MacOS 11.1

**Comment by acalvino4** [comment]
happy to look into the code and submit a PR if someone can point me to the appropriate area of the codebase

**Comment by derrickmehaffy** [comment]
@acalvino4 It will be in the content-manager plugin, not sure what file exactly but at least a point in the right direction.
