### ISSUE TITLE
German l8n uses the english plural forms for collection types

### ISSUE THREAD

**Issue by joergp** [strapi/strapi#8915]
## Bug report
In the German translation the plural names of the collection types are incorrect.
### Describe the bug
It does not work to add an "s" to a singular to make it plural in German.
### Steps to reproduce the behavior

Enter a German collection name like "Buch" (book). It shows up as "Buches" in the collection types.

### Expected behavior

Should read "Bücher". But it will be hard the create the correct German plural in every single case. Better don't use plurals for German or let the admin enter a plural form in collection settings.

**Comment by rlvk-vk** [comment]
I have the exact same issue for danish. Can't seem to find a good solution anywhere.

**Comment by joergp** [comment]
Quite embarrassing to be honest. Had a pitch for a large Alexa project today and had to explain the possible client why the plurals are that strange.

**Comment by rlvk-vk** [comment]
I found this workaround, but I still think it would be nice with a more native solution.

[](https://stackoverflow.com/questions/60815181/how-to-disable-plural-suffix)

**Comment by rlvk-vk** [comment]
I actually just figured out a more simple way to solve this issue.

I looked trough the code and found that this package: [https://www.npmjs.com/package/pluralize](https://www.npmjs.com/package/pluralize) is used for the pluralization. It has a build in method to add new rules. So what I did, is that I added the word/words from my local language (danish), which are getting translated wrong in this file: `/config/functions/bootstrap.js` which is executed before the app starts.

Like this:
```
'use strict';

const pluralize = require('pluralize')

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/v3.x/concepts/configurations.html#bootstrap
 */

module.exports = () => {
    // Add danish plural versions of collection names
    pluralize.addPluralRule('side', 'sider')
    pluralize.addPluralRule('aktivitet', 'aktiviteter')
};
```

And then just let the server restart.

**Comment by joergp** [comment]
Thanks a lot! This is solving my problems! Still it does not work if singular and plural are the same (throwing an error), but you could rename the plural. However, it feels strange to mess around with singular and plural in such a technical product.

**Comment by rlvk-vk** [comment]
Yeah, kinda. But it would also be more bloated if the core maintainers had to keep track of all singular/plural versions of words for all the supported languages.

But for words that are the same in singular and plural forms, you can use one of these two functions from the pluralize package:
```
pluralize.addIrregularRule('irregular', 'regular')
pluralize.addUncountableRule('paper')
```

I hope it helps.

**Comment by joergp** [comment]
Great, thanks – will give it a try. I didn't mean the core maintainers should add all singular/plurals but simply don't use plurals at all. It would have been better to have no plurals than wrong ones.

**Comment by Ortimis** [comment]
This is also listed and discussed here https://github.com/strapi/rfcs/issues/18

**Comment by smorrin28** [comment]
I've tried this, but Strapi always tells me that an error occured. The exact response is that strapi tells me that the name cannot be pluralized, even though I've set everything up correctly and when I try to pluralize a string in the bootstrap.js file, it works without any problems, it just somehow fails when creating a new collection.

**Comment by hondem** [comment]
@rlvk-vk This is what I was looking for! Nice job there! :) You saved me (and I think that not only me) a lot of time!!! Many thanks! :)

**Comment by rlvk-vk** [comment]
> @rlvk-vk This is what I was looking for! Nice job there! :) You saved me (and I think that not only me) a lot of time!!! Many thanks! :)

I'm glad it helped others as well 😊
