### ISSUE TITLE
Fresh install always fails

### ISSUE THREAD

**Issue by AndreasFaust** [strapi/strapi#8916]
### Describe the bug
Setting up a fresh install does not work. 
It fails when building the admin-UI at 68–70 %.  

### Steps to reproduce the behavior
`yarn create strapi-app my-project --quickstart`

### Expected behavior
Install a fresh version of Strapi and open the admin-panel.

### Screenshots
<img width="1450" alt="Bildschirmfoto 2020-12-17 um 00 29 52" src="https://user-images.githubusercontent.com/15075587/102419090-5e864400-3fff-11eb-9b76-3ba67fd259d9.png">

### System
- Node.js version: v14.15.2
- NPM version: 6.14.9
- Strapi version: latest
- Database: SQLite
- Operating system: Mac OSX 10.15.7 Catalina

**Comment by derrickmehaffy** [comment]
Delete the following files and folders, then reinstall node modules and rebuild. You have outdated cached packages in one of your lock files.

node_modules
build
.cache
package-lock.json
yarn.lock

**Comment by derrickmehaffy** [comment]
Going to mark as closed, but please feel free to respond if that doesn't work.

**Comment by AndreasFaust** [comment]
Thank you for the quick response. I tried it out but it did not work. 
Also reinstalled node. How can I have outdated cached packages in a lock file at a completely fresh install?

I recently updated to OSX Catalina. Could the error emerge from permission problems? I tried this without success:
https://www.catalinaosx.com/how-to-fix-permissions-issue-on-catalina-osx/

**Comment by AndreasFaust** [comment]
The installation with Yarn on OSX Catalina throws another error with `node-gyp` which is described here:
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md

Besides that, the installation still does not work at all. It has to do with my local OSX, because on the cloud dev-environment `Gitpod` it works just fine.

**Comment by derrickmehaffy** [comment]
It would appear you are missing the build tools on your Mac, it is a common issue during the upgrade to Catalina. 

https://www.theverge.com/2019/10/12/20908567/apple-macos-catalina-breaking-apps-32-bit-support-how-to-prepare-avoid-update

**Comment by AndreasFaust** [comment]
Thank you for help! I found out, that creating another `user` solves the problem. 
It must have to do with `outdated cached packages`, as you said, but my attempts to delete `node`, `npm`, `yarn` and all their dependent folders did not help. Reinstalling the commandline-tools did not either (and did not solve the `node-gyp` error).

**Comment by AndreasFaust** [comment]
To finally close this: The whole error originated from the uncautious update to Mac OSX Catalina. 
After trying out everything I could possibly find on the internet, I had to create a new user and move all my setup. 
Thank you, @derrickmehaffy, for your help. 

Strapi works fine and I created a library to conveniently consume and render responsive, resized images with `react`: 
https://github.com/AndreasFaust/react-strapi-img

**Comment by derrickmehaffy** [comment]
> To finally close this: The whole error originated from the uncautious update to Mac OSX Catalina. 
> After trying out everything I could possibly find on the internet, I had to create a new user and move all my setup. 
> Thank you, @derrickmehaffy, for your help. 
> 
> Strapi works fine and I created a library to conveniently consume and render responsive, resized images with `react`: 
> https://github.com/AndreasFaust/react-strapi-img

No problem glad I could help, that Mac update messed up a lot of stuff for a lot of people. Glad you solved it though.
