### ISSUE TITLE
[3.4.0] Slugs reset when editing an entry

### ISSUE THREAD

**Issue by JeremieLeblanc** [strapi/strapi#8926]
### Describe the bug

After upgrading to Strapi 3.4.0 the slug field gets reset to default after opening an entry to edit it.
It also won't let you change it back to what it was because it is marked "Unavailable".

### Steps to reproduce the behavior

1. Update to Strapi 3.4.0
2. Add an entry that has a slug field
3. Click on the entry you just created
4. Notice that the slug field flashes and resets to the default value

### Expected behavior

I would expect the slug to remain the same when editing a record

### Screenshots

![Image of screenshot](https://image.prntscr.com/image/0uctK-kmScG1YaYw8VGK2A.png)

### System

- Node.js version: 14.15.0 and 12.20.0
- NPM version: 6.14.8
- Strapi version: 3.4.0
- Database: SQLite and Postgres
- Operating system: Mac and Linux
- Browser: Chrome and Firefox

**Comment by soupette** [comment]
Hello @JeremieLeblanc, I am having a hard understanding your issue. Can you provide us with the detailed steps to reproduce the bug? 

We will need your collection type data structure.

**Comment by JeremieLeblanc** [comment]
1. Start a brand new project using `npx create-strapi-app backend --template https://github.com/strapi/strapi-template-blog`
2. Click on the Articles Collection
3. Add "slug" to the "Displayed Fields" by clicking the cogwheel in the top right
3. Take note of the current slugs
3. Click on an article to open the editing page
4. Notice that the slug has changed back to the default slug (the name of the collection)
5. Try to change the slug back to its original value
6. It will give you an error saying that the slug is Unavailable because it is already in use

Because of this it is practically impossible to make edits to a collection that has slugs.

**Comment by philliprognerud** [comment]
Also getting this issue.

**Comment by eulervoid** [comment]
Same issue here.

**Comment by derrickmehaffy** [comment]
fixed with: https://github.com/strapi/strapi/pull/8935 closing
