### ISSUE TITLE
Strapi deploy on c-panel causing cors issue

### ISSUE THREAD

**Issue by ahsanahmed321** [strapi/strapi#8927]
Hi there, recently I was trying to deploy Strapi app on c-panel but getting the cors issue when using any of the APIs . On searching I have found a way to enable cors

module.exports = {
  //...
  settings: {
    cors: {
      origin: ['http://localhost', 'https://mysite.com', 'https://www.mysite.com'],
    },
  },
};

Added these line in config / middleware.js but still no success

Note : The same app is working fine with heroku

**Comment by sunnysonx** [comment]
You should add also the enabled property:

```
module.exports = {
  //...
  settings: {
    cors: {
      enabled: true, //<--
      origin: ['http://localhost', 'https://mysite.com', 'https://www.mysite.com'], // ['*'] to allow all origins
      headers: ['Content-Type', 'Authorization', 'X-Frame-Options', 'x-csrf-token'], // ['*'] to allow all headers
    },
  }
  //...
};

```

Please note that request headers can also cause cors problems. If you will send some **Extra** headers that are not allowed in CORS, then your request will be blocked. You can also use ['*'] for headers. But I would recommend adding them manually.

**Comment by ahsanahmed321** [comment]
this is my latest middleware.js file 

odule.exports = {
  settings: {
    cors: {
      enabled: true,
      headers: "*",
      origin: "*",
      methods: "*",
    },
  },
};

although I am getting the data but on post request it is showing

Access to XMLHttpRequest at 'http://studio.dersepa.com//contacts' from origin 'http://dersepa.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
