### ISSUE TITLE
[3.4.0] Date/Time not showing in record view

### ISSUE THREAD

**Issue by bglidwell** [strapi/strapi#8928]
### Describe the bug
I have a field called TestDate on a collection type. When I go to list view for that collection, I see the TestDate rendered fine. 
![image](https://user-images.githubusercontent.com/14822908/102543973-b82b5480-4079-11eb-8b41-27f1d132cd1d.png)

However, when I click on any record, the Date/Time field is not populated
![image](https://user-images.githubusercontent.com/14822908/102544018-c9746100-4079-11eb-9370-67d8e8a0fcee.png)

Even if I create a new record, enter the Test Date and Time fields, then click save, it wipes the data from the field when I loads the saved record.

### Steps to reproduce the behavior

1. Create Collection Type with a Date/Time field or find existing 
2. Open Record View and see Date/Time field is missing data populated

### Expected behavior

Date/Time should populate data no differently than list view does

### System

- Node.js version: 14.15.2
- NPM version: 6.14.9
- Strapi version: 3.4.0
- Database: Postgres
- Operating system: Linux/Heroku

### Additional context

I have tried this with multiple environments and I am seeing this issue on all systems currently. Migration script was run and confirmed on local dev with sqlite3 and still seeing this bug.

**Comment by ksaetern03** [comment]
I just upgraded to 3.4.0 and noticed the same issue.

**Comment by eriskhan** [comment]
Same problem here

**Comment by EAdeveloper** [comment]
I just upgraded to v3.4.0 and noticed the same issue also required fields can be skipped.

**Comment by soupette** [comment]
@EAdeveloper required fields can be skipped only for draft records.

**Comment by derrickmehaffy** [comment]
fixed with https://github.com/strapi/strapi/pull/8935 closing
