### ISSUE TITLE
[3.4.0] JSON fields show up empty in Strapi record view

### ISSUE THREAD

**Issue by Ravanger** [strapi/strapi#8930]
### Describe the bug

When trying to view a JSON field in Strapi record view, it shows up empty.
When querying the API endpoint, the JSON data shows up.

### Steps to reproduce the behavior

1. Start new Strapi quickstart project (or open existing project)
2. Create a new Content Type with a JSON field
3. Create new Item in new collection type (or open existing item)
4. Enter JSON data and save
5. Refresh page or visit the item again
6. JSON data disappears

### Expected behavior

The JSON data appears in the field

### Screenshots

![image](https://user-images.githubusercontent.com/814853/102563306-f3904800-40a6-11eb-9237-e3b2ac13da7c.png)
![image](https://user-images.githubusercontent.com/814853/102563388-263a4080-40a7-11eb-917f-33efdf360422.png)

### Code snippets

N/A; used project quick-start

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Yarn version: 1.22.5
- Strapi version: 3.4.0
- Database: sqlite
- Operating system: Windows 10

**Comment by bglidwell** [comment]
Maybe related to #8928 ?

**Comment by sunnysonx** [comment]
Confirming. Reproduced this issue.

JSON is present in DB and is returned with GET request, but it is not displayed in the field.

DB:
![image](https://user-images.githubusercontent.com/14160283/102593084-11988f80-411d-11eb-947e-4008c1e33063.png)
GET request with findOne from Admin (**/content-manager/collection-types/application::articles.articles/3**):
![image](https://user-images.githubusercontent.com/14160283/102593212-37259900-411d-11eb-8dc2-c6cf2fee6e8c.png)

**Comment by jseb2520** [comment]
It's happening to me too. I have several entries where there's data in json input format and they're not displaying the data on /admin after upgrading from 3.3.4 to 3.4.0.

![Screen Shot 2020-12-19 at 1 09 42 PM](https://user-images.githubusercontent.com/25942141/102696317-775b4900-41fb-11eb-8518-6d570a690bb1.png)

![Screen Shot 2020-12-19 at 1 12 44 PM](https://user-images.githubusercontent.com/25942141/102696384-e46ede80-41fb-11eb-9f2d-181cbbcd7a9a.png)

**Comment by philliprognerud** [comment]
Getting the same issues here:

-  JSON field, cant view it, but it's in the database
- Date field, cant view it, but it's in the database
- Slug field, getting re-autogenerated into name of the collection

These are all just view layer issues it seems, the data itself is fine and saved properly.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/datetime-picker-not-showing-value-in-edit-view/1736/2

**Comment by fagyikaa** [comment]
Just some little remark i noticed: these fields show up correctly if wrapped in a component even if it's alone in that.

**Comment by ludovicraymond** [comment]
I have the same issue with relation which contains json fields.
"could not identify an equality operator for type json"

The issue comes from the SQL Query (postgres) :
`Select distinct "MyTable".*, ........`
Need to replace .* by .id
