### ISSUE TITLE
[3.4.0] Invalid SQL generated for sorting relationship on filtered list view

### ISSUE THREAD

**Issue by bglidwell** [strapi/strapi#8931]
### Describe the bug

Getting "An error occurred during models config fetch" when trying to sort a relationship column on a filtered list view. 
It appears an invalid Postgres SQL statement is being generated for this specific use case. 

### Steps to reproduce the behavior
1, Have postgres database connector setup on strapi 3.4.0 
2. Setup collection type with any relationship
3. Setup a list view to display that relationship
4. Should be able to sort that relationship fine
5. Now do a filter or search on that list view
6. Again try to sort the list, you will receive an error

### Expected behavior

Should just sort the filtered list

### Screenshots

Error received in list view: 
![image](https://user-images.githubusercontent.com/14822908/102574467-753ba200-40b6-11eb-82bc-dfcb74e5cae8.png)

Filter applied, and relationship sorted:
![image](https://user-images.githubusercontent.com/14822908/102574501-8b496280-40b6-11eb-997e-abf064c6eed9.png)

Error from backend:
![image](https://user-images.githubusercontent.com/14822908/102574534-9ef4c900-40b6-11eb-8c48-ee6cc3484175.png)

### SQL snippets (error description)

Invalid Postgres raw SQL generated:
```
'select distinct "test_results".* from "test_results" left join "dbname"."public"."products" as "products_1" on "products_1"."id" = "test_results"."soil" where "test_results"."Score" = ? order by "products_1"."Name" desc limit ?'
```

### Reason for error: ###
The ORDER BY clause can only be applied after the DISTINCT has been applied. Since only the fields in the SELECT statement are taken into consideration for the DISTINCT operations, those are the only fields may be used in the ORDER BY.

In the above SQL statement, products_1.Name is not available to "order by" because it was never selected in the select statement. 

### System

- Node.js version: 14.15.2
- NPM version: 6.14.9
- Strapi version: 3.4.0
- Database: Postgres
- Operating system: Linux/Heroku

### Additional context

It's appears this is valid syntax for SQLite, but Postgres can be more strict about this.

**Comment by sunnysonx** [comment]
Confirming. Reproduced this issue.

Applying sort on relation field + using any filter = error

Get request from admin with sorting on **category.name** & filter for **id** = 1
/content-manager/collection-types/application::articles.articles?page=1&pageSize=10&_sort=category.name:ASC&_where[0][id]=1

Results:
ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'strapi_db.categories_1.name' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by petersg83** [comment]
Hi,
I can confirm the issue. FYI, I used a many-to-one relation.
