### ISSUE TITLE
new version 3.4.0 dont show JSON filed in admin panel

### ISSUE THREAD

**Issue by Marcosul** [strapi/strapi#8940]
new version 3.4.0 dont show JSON filed in admin panel

is saving data, but dont show JSON field in admin.

i using mysql

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/102631245-582cc080-4102-11eb-9c92-674f79ecc479.png)

**Comment by derrickmehaffy** [comment]
Issue confirmed and will be fixed in: https://github.com/strapi/strapi/pull/8935

**Comment by Marcosul** [comment]
Thank you !!!

Att,

Marco Sulzbacher
(48) 9 9683-9045


Em sex., 18 de dez. de 2020 às 13:00, DMehaffy <notifications@github.com>
escreveu:

**Comment by Marcosul** [comment]
how to update my app?

Em sex., 18 de dez. de 2020 às 14:05, Marco Sulzbacher <marcosul@gmail.com>
escreveu:
