### ISSUE TITLE
[3.0.4] Cannot find 'kind' of undefined when using custom plural displayName

### ISSUE THREAD

**Issue by danestves** [strapi/strapi#8943]
After we made te migration for Strapi 3.4.0 everything looks good but at the moment of show de Collection Types and Single Types gives an error that `kind` cannot be found

1. Go to `admin/src/containers/LeftMenu/utils/generateModelsLinks.js` and paste this code:

```js
import { chain, get } from "lodash";

const generateLinks = (links) => {
  return links
    .filter((link) => link.isDisplayed)
    .map((link) => {
      return {
        icon: "circle",
        destination: `/plugins/content-manager/${link.kind}/${link.uid}`,
        isDisplayed: false,
        label:
          link && link.info.displayName
            ? link.info.displayName
            : link.info.label,
        permissions: [
          {
            action: "plugins::content-manager.explorer.create",
            subject: link.uid,
          },
          {
            action: "plugins::content-manager.explorer.read",
            subject: link.uid,
          },
          {
            action: "plugins::content-manager.explorer.update",
            subject: link.uid,
          },
        ],
      };
    });
};

const generateModelsLinks = (models) => {
  const [collectionTypes, singleTypes] = chain(models)
    .groupBy("kind")
    .map((value, key) => ({ name: key, links: value }))
    .sortBy("name")
    .value();

  return {
    collectionTypesSectionLinks: generateLinks(
      get(collectionTypes, "links", [])
    ),
    singleTypesSectionLinks: generateLinks(get(singleTypes, "links", [])),
  };
};

export default generateModelsLinks;
export { generateLinks };
```

After that rebuild your admin panel with:

```bash
# npm
npm run build --clean

# yarn
yarn build --clean
```

And with that solution your admin panel should work 👍

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by adin234** [comment]
was this issue even resolved?

**Comment by derrickmehaffy** [comment]
@adin234 we don't review bug reports that don't provide enough information to reproduce the issue. In this case the user did not provide the environmental information and this particular issue is regarding customization and not Strapi built/supported code.

Questions like these need to go to our forum: https://forum.strapi.io per the following notice: https://github.com/strapi/strapi/issues/9230
