### ISSUE TITLE
Admin UI filter breaks when trying to filter by relation field (mongodb)

### ISSUE THREAD

**Issue by gabriel-godoy** [strapi/strapi#8948]
### Describe the bug
I am getting error when trying to filter by a relation field of other collection.

Only happens when I set **mongodb** as my database, works fine with sqlite and mysql. 
And it seems to happen only when there a lot of entries to filter on the collection.

### Steps to reproduce the behavior
1. Create a project based on **mongodb** 
2. Create a collection with some string field
3. Create another collection with a relation field to the first collection
4. Go to that second collection internal page (List page)
5. Try to filter by the relation field defined ([Field] is "something")
6. Error arises `"Something went wrong" => Cannot read property 'id' of null`

### Expected behavior
They filter should've worked.

### Screenshots

Filtering by relation field:
<img width="738" alt="Screen_Shot_2020-12-19_at_03_20_49" src="https://user-images.githubusercontent.com/61797650/102682610-ac3eb000-41a9-11eb-98b9-4a3bb3ec1365.png">

Error:
<img width="594" alt="Screen Shot 2020-12-19 at 02 45 22" src="https://user-images.githubusercontent.com/61797650/102682126-cc6c7000-41a5-11eb-8278-963d40c38bf7.png">

**Comment by petersg83** [comment]
Hi, thanks for letting us know. Some other people have reported a similar issue but I couldn't reproduce it.
Do you have more info on how I can reproduce it from a fresh install? Did you steps work with a fresh install?

**Comment by gabriel-godoy** [comment]
Yes, I was able to always reproduce it with a fresh install, by choosing mongodb as db.

And then I followed this steps:

- Create a collection with some string field
- Create another collection with a relation field to the first collection
- Go to that second collection internal page (List page)
- Try to filter by the relation field defined ([Field] is "something")
Error arises "Something went wrong" => Cannot read property 'id' of null

**Comment by soupette** [comment]
@gabriel-godoy can you provide us with your models structure? What kind of relations did you make between them?

**Comment by gabriel-godoy** [comment]
Hi @soupette 

I've created a sample repo with a basic Strapi configuration, based on mongodb:
https://github.com/gabriel-godoy/strapi-sample

There is also a mongodb dump for the db `words` with the entries I've created (Problem seems to happen only with a lot of entries `> 500`)
https://github.com/gabriel-godoy/strapi-sample/tree/master/dump/words

Credentials to enter admin page:
email: `gabrielgodoyon@gmail.com`
password: `Pass123456`

The project basically has 2 collection types:
- `Language`
    - Has string field `name`, meaning the name of the language, example: `english`

- `Words`
    - Has string field `name`, meaning the word, example: `Accolade`
    - Also has a a relation field called `language`, referring to the field `name` on Language collection type.

**Comment by soupette** [comment]
Thanks a lot I did manage to reproduce the issue with your dump. It seems that the back-end is sending some null values. I am not sure though, if you have migrated your app correctly or if it is an issue on our side. I'll let @petersg83 investigate.
