### ISSUE TITLE
[3.4.0] Content manager table freezing when scrolling after upgrading to 3.4.0

### ISSUE THREAD

**Issue by jseb2520** [strapi/strapi#8951]
### Describe the bug

The content manager table which displays the entries of a collection is freezing when scrolling down after upgrading to Strapi version 3.4.0. Seemed like a performance issue so i downgraded to Strapi version 3.3.4 and this is not happening even having the same amount of entries and data in the collections. Besides, it causes clicks to select a specific entry to take much longer time than before. 

### Steps to reproduce the behavior

1. Upgrade to Strapi version 3.4.0
2. Click on a collection with many entries.
3. Scroll down

### Expected behavior

In previous versions, scrolling never stops or seems to freeze at any point.

### Screenshots

Because this problem only happens when scrolling down the table, I can't upload an screenshot.

### System

- Node.js version: v15.3.0
- NPM version: v7.0.14
- Strapi version: 3.4.0
- Database: SQLite
- Operating system: MacOS Catalina 10.15.7
- Browsers: Safari (Version 14.0.2), Google Chrome (Version 87.0.4280.88 (Official Build) (x86_64))

**Comment by derrickmehaffy** [comment]
'Node.js version: v15.3.0'

We do not support node development releases. Please confirm the issue also happens on a supported node version.

**Comment by jseb2520** [comment]
> 'Node.js version: v15.3.0'
> 
> We do not support node development releases. Please confirm the issue also happens on a supported node version.

Hello derrick. The issue is happening in my production server too. That server has Node.js v12.18.4 and NPM v6.14.6.

**Comment by derrickmehaffy** [comment]
Do you have any extensions? I have a test model I have added 60 fields to (and populated) and can't reproduce.

**Comment by jseb2520** [comment]
> Do you have any extensions? I have a test model I have added 60 fields to (and populated) and can't reproduce.

No, I don't have any extensions apart from the available on the Strapi marketplace. I have not made any changes to the extension's code either. It's very strange this behavior because if I downgrade the Strapi version, it immediately starts working flawlessly. The data is still the same: a collection with +100 entries and default entries per page is 50.

**Comment by derrickmehaffy** [comment]
> > Do you have any extensions? I have a test model I have added 60 fields to (and populated) and can't reproduce.
> 
> No, I don't have any extensions apart from the available on the Strapi marketplace. I have not made any changes to the extension's code either. It's very strange this behavior because if I downgrade the Strapi version, it immediately starts working flawlessly. The data is still the same: a collection with +100 entries and default entries per page is 50.

Is this on the list view or edit view?

**Comment by jseb2520** [comment]
> > > Do you have any extensions? I have a test model I have added 60 fields to (and populated) and can't reproduce.
> > 
> > 
> > No, I don't have any extensions apart from the available on the Strapi marketplace. I have not made any changes to the extension's code either. It's very strange this behavior because if I downgrade the Strapi version, it immediately starts working flawlessly. The data is still the same: a collection with +100 entries and default entries per page is 50.
> 
> Is this on the list view or edit view?

On the list view.

**Comment by soupette** [comment]
@jseb2520 I think I have managed to reproduce your issue. To do so, I have followed these steps:

1. Created 400 records
2. Clicked on the collection type
3. Changed the layout of the listview so all fields are displayed (I also have relations)
4. Slowdowned the CPU by 4x
5. Changed the limit so I fetch 100entries at a time

I can confirm that the view freezes at some point, I have just made a fix but until it is released can you try to display 10 entries at a time to see if the problem persists?

**Comment by jseb2520** [comment]
> @jseb2520 I think I have managed to reproduce your issue. To do so, I have followed these steps:
> 
> 1. Created 400 records
> 2. Clicked on the collection type
> 3. Changed the layout of the listview so all fields are displayed (I also have relations)
> 4. Slowdowned the CPU by 4x
> 5. Changed the limit so I fetch 100entries at a time
> 
> I can confirm that the view freezes at some point, I have just made a fix but until it is released can you try to display 10 entries at a time to see if the problem persists?

Hello @soupette. Sure, I can display 10 entries at a time for now and test out its behavior. Thanks for your answer and good work! 👍🏻
