### ISSUE TITLE
 Knex: Timeout acquiring a connection. Server wasn't able to start properly.

### ISSUE THREAD

**Issue by jieliu218** [strapi/strapi#8952]
### Describe the bug

0|strapi  | [2020-12-19T22:56:19.076Z] debug ⛔️ Server wasn't able to start properly.
0|strapi  | [2020-12-19T22:56:19.080Z] error KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
0|strapi  |     at Client_PG.acquireConnection (/home/ubuntu/strapi/node_modules/knex/lib/client.js:348:26)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/heroku-error-knextimeouterror-knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing-a-transacting-trx-call/2618/2

**Comment by w3cj** [comment]
For anyone else that comes across this error while attempting to deploy to heroku, here is how I fixed it.

I added the line `ssl: { rejectUnauthorized: false }` to the database connection settings.

It looks like the official strapi documentation now includes this, but I was attempting to deploy a legacy application that did not have this config. https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#example

```js
return {
  connections: {
    default: {
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 5432),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', 'strapi'),
        password: env('DATABASE_PASSWORD', 'strapi'),
        schema: 'public',
        ssl: { rejectUnauthorized: false }, // this line is required
      },
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
It always kind of existed but was never documented (since it comes from Knex and not Strapi itself) but yes I added this to the documentation a while ago :wink:
