### ISSUE TITLE
Repeatable component title overflows if it is too long

### ISSUE THREAD

**Issue by sebqq** [strapi/strapi#8959]
Hello I've noticed following bug:

<img width="766" alt="Screenshot 2020-12-21 at 09 10 58" src="https://user-images.githubusercontent.com/33039909/102754016-99c0a400-436c-11eb-861c-8376026b24a9.png">

IMHO, good enough solution would be to truncate string, if it is too long and provide tooltip for users to let them see full string to achieve proper UX.

It could be also solved without tooltip. A string could just be collapsible -> in opened state (show full string) when repeatable item is expanded and vice versa. 

Thanks!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
