### ISSUE TITLE
Media Library - Name truncating can cause bad UX when multiple files are using same prefix

### ISSUE THREAD

**Issue by sebqq** [strapi/strapi#8960]
Hello there.

In addition to issue #8608 (Admin UI improvements) I'm creating now separate issue for Media Library name truncating readability problem.

---

# User should be able to see file's full name

So, tooltip would be really usefull in Media Library items grid view and "Add from Media Library" widget in Collections. File names are also truncated, which make it hard to decide, which file I would like to assign when two different files are using same name prefix. It really becomes a pain when we are dealing with non-image file types like documents, which always has same presentation icon.

## Story

I would like to assign document to XY collection's item. Documents within MediaLib uses same Icon (_It is not such a problem when dealing with Images because Image preview is most of the time good enough to distinguish between files_). Many documents in my MediaLib use same prefix (they are related to each other). So I'm going to follow these steps:

1. In collection's item with file field I'm gonna try to assign file by clicking "+" button.
2. I will search for my relevant document using string search field.
3. I got maybe 4-5 related documents (they have same naming convention -> using same prefix).
4. Name is truncated so I can see only repeated prefix and it (**at this step it is not possible to distinguish between these files**).
5. They have no tooltip so I need to manually open "Edit file" icon to see full name of the file.
6. I can see full name now, but I've opened wrong document at this try, so I "Go back".
7. Previously created string search filter is gone and I need to enter and apply search string once-again again.
8. Continues with steps 3. until I find the right file.

So I can see two wrong things here (in terms of UX): 

1. Name is truncated so I need to manually open files one-by-one to find the right one.
2. During process of file lookup, the search query string is reseted and I lost any of my "progress" so I need to enter query string and search for relevant files once again. _(NOTE: this is not case of Media Library screen, where we can press "x" button to save search string, but it is problem in "Select files" Widget)_.

Hope it does make sense.

Thanks!

**Comment by gustavpursche** [comment]
Connected to: https://github.com/strapi/strapi/issues/8608 where a couple more cases are mentioned, where user generated content is truncated and causes problems.

**Comment by dirq** [comment]
A table view, along side the card view, would solve this.

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/better-uiux-for-files-in-media-lib-that-share-the-same-prefix
