### ISSUE TITLE
Error: read ECONNRESET     ---- fresh install sqlite

### ISSUE THREAD

**Issue by Oldwo1f** [strapi/strapi#8965]
First i want to mention that everything works fine in my local environment.

I pushed all my strapi project onto a brand new server (Ubuntu 18.04),  I installed all the package and i can run strapi in developement mode (yarn develop). Everything looks like normal so far
![Capture d’écran du 2020-12-21 18-39-55](https://user-images.githubusercontent.com/4490467/102849827-43a93a80-4418-11eb-873d-974bdfc761da.png)

But when i rty to reach a page i got this error
![Capture d’écran du 2020-12-21 18-42-18](https://user-images.githubusercontent.com/4490467/102849928-7ce1aa80-4418-11eb-8210-cc6e6db60367.png)

i assumed that it was an error from mongodb so i reinstalled it. But the problem persist and after hours of searching i decided to reinstall a brand new strapi project with SLQLite using `yarn create strapi-app my-project --quickstart`
Surprisingly, i get the exact same error :
![Capture d’écran du 2020-12-21 18-42-18](https://user-images.githubusercontent.com/4490467/102849928-7ce1aa80-4418-11eb-8210-cc6e6db60367.png)

So this ECONNRESET error doesnt looks related to mongodb.

I then try different version of node.js including `12.13.0 `and `14.15.3` but i stil have the same error

So now i am out of idea and i still cant deploy my strapi project.
Any help would be really appreciated

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
