### ISSUE TITLE
Cant' debug with source maps files in development mode

### ISSUE THREAD

**Issue by aminta** [strapi/strapi#8975]
### Describe the bug

Cant' debug with source maps files in development mode

### Steps to reproduce the behavior

1. npm run strapi develop
2. open Google Developer Tools Console
3. logs and errors appears with references to files like "main.757d28c1.chunk.js" and not to original JS files

### Expected behavior

logs and errors should be appear with references to original JS files

### System

- Node.js version: 12.19.1
- NPM version: 6.14.8
- Strapi version: 3.4.0
- Database: mongoDB
- Operating system: MacOS 11.1

**Comment by derrickmehaffy** [comment]
@aminta can you please provide more information as I'm not sure what you are referring to. Going to mark as closed for now as we can't reproduce something we have no context on.
