### ISSUE TITLE
Uid field value in model update form updates by itself

### ISSUE THREAD

**Issue by burlakko** [strapi/strapi#8978]
## Bug report

Value of `uid` field value automatically becomes a name of the model that being updated

### Describe the bug

After 3.4.0 upgrade `uid` fields started to behave weird. I have a dozen of models, in most of them I have `slug` attribute which is `uid` dependent from `title` field. After upgrade to Strapi 3.4.0 when you enter an update form `slug` field value is automatically changed to model name. For some reason this affects only some of models, though all of them are nearly identical.

All of the affected fields have `required` flag on, though not all fields with this flag on are affected, so not sure if it's connected.

### Steps to reproduce the behavior

I'm not sure if it can be easily reproduced. I experience it only on some of models. But here are steps with screenshots, i hope that'll help

1. Go to model Category list view. This model has attribute slugs and we can see their normal values.
![Screenshot_2020-12-22 Strapi - Content Manager](https://user-images.githubusercontent.com/4548361/102903085-83077380-4478-11eb-9ac7-0ae11f7de2c2.png)

2. Click on one of items an go to update form.
3. `Slug` field value automatically updated with 'category' value
![Screenshot_2020-12-22 Strapi - Content Manager(1)](https://user-images.githubusercontent.com/4548361/102903699-5f90f880-4479-11eb-9963-f98aa9d13f48.png)

### Expected behavior

Form fields should not be changed without user action

### Screenshots

Added in Steps to reproduce section

### Code snippets

`category.settings.json` file contents:
```
{
  "kind": "collectionType",
  "collectionName": "categories",
  "info": {
    "name": "category",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "slug": {
      "type": "uid",
      "targetField": "title",
      "required": true
    },
    "articles": {
      "collection": "article",
      "via": "category"
    },
    "priority": {
      "type": "integer",
      "required": true,
      "default": 1
    }
  }
}

```

### System

- Node.js version: 12.9.0
- NPM version: 6.14.8
- Strapi version: 3.4.0
- Database: Mongo
- Operating system: Ubuntu

### Additional context

After downgrading to 3.3.4 the problem has gone.

**Comment by derrickmehaffy** [comment]
@burlakko can you test with the release of v3.4.1 we did today?

**Comment by burlakko** [comment]
It's gone in v3.4.1. Closing the issue. Thank you!
