### ISSUE TITLE
[v3.4.1] Datetime pickers values are not displaying in the Edit view in the admin panel.

### ISSUE THREAD

**Issue by EAdeveloper** [strapi/strapi#8979]
## Bug report

Datetime pickers values are not displaying in the Edit view in the admin panel.

### Describe the bug

After we upgraded to v3.4.1 from v3.4.0 because the bug listed was described as fixed in the latest release [v3.4.1](https://github.com/strapi/strapi/releases/tag/v3.4.1) from the bug in v3.4.0, the Time picker was fixed and is displaying but the Dates are not displaying yet.

### Steps to reproduce the behavior

1. Go to a collection type with datetime fields
2. Click on the create or edit a collection
3. Select the date and time from the datetime picker and click save and publish the new collection.
4. Go back to the new created collection and the date will not show in the Edit view from the Admin panel, depside being saved in the database and it is showing in the API response as well.

### Expected behavior

Author must be able to see what are the saved dates on the dates fields when they return to the Edit view.

### Screenshots

![image](https://user-images.githubusercontent.com/21114220/102927339-c6f07d80-4464-11eb-9446-5b5a1ac81a9b.png)

### API response

![image](https://user-images.githubusercontent.com/21114220/102927523-277fba80-4465-11eb-8f89-77532769ea6b.png)

### List View
![image](https://user-images.githubusercontent.com/21114220/102927649-57c75900-4465-11eb-909a-49b5f58d55af.png)

### System

- Node.js version: v14.10.0
- NPM version: 6.14.8
- Strapi version: 3.4.1
- Database: Postgres
- Operating system: WSL

**Comment by derrickmehaffy** [comment]
Did you rebuild the admin panel?

**Comment by EAdeveloper** [comment]
> Did you rebuild the admin panel?

Hi @derrickmehaffy ,
trust you are well. 🚀

Yes, the admin panel was rebuilt -> yarn build --clean

**Comment by derrickmehaffy** [comment]
@EAdeveloper I can't reproduce at all:

https://www.loom.com/share/4f43597d5d1e4b1d986df44c8a2a91ab

So there is something going on with your project, can you please test in a fresh project?

**Comment by EAdeveloper** [comment]
Hello @derrickmehaffy my apologies and thank you for follow up.

I setup a fresh new strapi --quickstart project and it is working.

I guess the issue with my project was that the "**.cache**" was not being deleted while running -> **yarn build --clean,** only the "build" folder was deleted.

Solution was:
1. Remove the **.cache**, **build** and **node_modules** folders.
2. Run > yarn build
3. Run > yarn develop 🚀🚀🚀✔
