### ISSUE TITLE
Strapi content-type doesn't return entries

### ISSUE THREAD

**Issue by Perdixo75** [strapi/strapi#8980]
### Describe the bug
I wanted to test out Strapi. So i've created a project, content types, set the permissions for my content type to find and findone, but when i try to get data it doesn't return nothing..

### Steps to reproduce the behavior
Here are the steps i've done :

 - Use the following commande to create a strapi project : `npx create-strapi-app my-project --quickstart`
 - Created my account, and created a new Content-type called "actualites" that contains a title, rich text and an image
 - Created 2 entries in my "actualites" content-type
 - I've tried to go to `http://localhost:1337/actualites` but i've had a 403 error
 - So i went to Roles/Public and checked the permissions for "find" and "findone" for my content-type
 - When i went back to `http://localhost:1337/actualites` , well.. i just have an empty array, my entries don't show ..

### Expected behavior
When going to `http://localhost:1337/actualites`, i should be able to see my entries.

### Code snippets
Here is my package.json file :
```
{
  "name": "backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.4.1",
    "strapi-admin": "3.4.1",
    "strapi-utils": "3.4.1",
    "strapi-plugin-content-type-builder": "3.4.1",
    "strapi-plugin-content-manager": "3.4.1",
    "strapi-plugin-users-permissions": "3.4.1",
    "strapi-plugin-email": "3.4.1",
    "strapi-plugin-upload": "3.4.1",
    "strapi-connector-bookshelf": "3.4.1",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "116525e6-88bf-4b09-820a-37df0cb4c17d"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

### System
My current node version was 15.4.0 , but i've had an error the first time i tried to install the project, so using nvm i've set my node to 14.15.3. But it doesn't change nothing

- Node.js version: 
- NPM version: 6.14.9
- Strapi version: 3.4.1
- Operating system: Max OSX Catalina 10.15.7

**Comment by derrickmehaffy** [comment]
By default the draft and publish feature is enabled on all new content types.

You can do one of three things to see your entries:

- publish them
- [turn off](https://strapi.io/documentation/developer-docs/latest/concepts/draft-and-publish.html#activating-or-deactivating-the-draft-and-publish-feature) draft and publish (publish them first or they will be deleted)
- use the [filter](https://strapi.io/documentation/developer-docs/latest/content-api/parameters.html#publication-state) to see draft entries

Marking as closed, but if any of the three options don't work, reply back and I can help further.
