### ISSUE TITLE
Description saved using CKEditor is not getting populated from database

### ISSUE THREAD

**Issue by nalumachurakesh** [strapi/strapi#8981]
Hi,

I upgraded default rich text editor to CKEditor in version 3.3 and it is working fine. I migrated strapi from 3.3 to 3.4, then the description is not getting populated from the database but it is getting pulled from db on the api execution. 

Please let me know how to resolve this.

Thanks in advance.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
