### ISSUE TITLE
Description saved using CKEditor is not getting populated from database

### ISSUE THREAD

**Issue by nalumachurakesh** [strapi/strapi#8984]
### Describe the bug

I upgraded default rich text editor to CKEditor in version 3.3 by referring to the steps in the [link](https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html) and it is working fine. I migrated strapi from 3.3 to 3.4, then the description is not getting populated in the UI from the database but it is getting from db in the api response.

### Steps to reproduce the behavior

1. Please follow this [link ](https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#introduction)to setup CKEditor
2. Save content using CKEditor 
3. Reload the application and to pull the saved content in the CKEditor

### Expected behavior

Formatted saved content should be displayed when it is opened.(Screenshot is before saving and expected should be same way after reloading and opening the saved content)
![expected](https://user-images.githubusercontent.com/13477420/103002665-492c8080-44fd-11eb-97c1-3a0be09b38a5.PNG)

### Screenshots

After opening the saved content, it is not getting displayed. If I paste any content in the CKEditor, save button is not getting enable to save.
![issue](https://user-images.githubusercontent.com/13477420/103002707-63665e80-44fd-11eb-8594-e1aecf052bbf.PNG)

### System

- Node.js version: v12.13.0
- NPM version: v6.12.0
- Strapi version: v3.4.1
- Database: sqlite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Please check your extensions to the admin and compare them with the core code from the mono-repo.

While a small guide is written in our documentation (planned to be removed in favor of an alternative) we don't directly offer Ckeditor support.

You may also check with the existing community plugin: 

https://github.com/TechQuery/strapi-plugin-ckeditor

**Comment by roslovets** [comment]
I modified code of [this](https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#setup) example to make CKEditor display text on intialization. It solved problem for me in strapi v3.4.1.

Modified code of `./plugins/wysiwyg/admin/src/components/CKEditor/index.js`:

```js
import React from 'react';
import PropTypes from 'prop-types';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import styled from 'styled-components';

const Wrapper = styled.div`
  .ck-editor__main {
    min-height: 200px;
    max-height: 400px;
    > div {
      min-height: 200px;
      max-height: 400px;
    }
  }
`;

const configuration = {
  toolbar: [
    'heading',
    '|',
    'bold',
    'italic',
    'link',
    'bulletedList',
    'numberedList',
    '|',
    'indent',
    'outdent',
    '|',
    'blockQuote',
    'insertTable',
    'mediaEmbed',
    'undo',
    'redo',
  ],
};

const Editor = ({ onChange, name, value }) => {
  return (
    <Wrapper>
      <CKEditor
        editor={ClassicEditor}
        config={configuration}
        data={value}
        onReady={editor => {
          if (value) {
            editor.setData(value);
          }
        }}
        onChange={(event, editor) => {
          const data = editor.getData();
          onChange({ target: { name, value: data } });
        }}
      />
    </Wrapper>
  );
};

Editor.propTypes = {
  onChange: PropTypes.func.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
};

export default Editor;
```

**Comment by nalumachurakesh** [comment]
> ```js
> <CKEditor
>         editor={ClassicEditor}
>         config={configuration}
>         data={value}
>         onReady={editor => {
>           if (value) {
>             editor.setData(value);
>           }
>         }}
>         onChange={(event, editor) => {
>           const data = editor.getData();
>           onChange({ target: { name, value: data } });
>         }}
>       />
> ```

It worked. Thank you.

**Comment by roslovets** [comment]
Checkout the new CKEditor 5 plugin for Strapi that works prefect with Strapi 3.4.0+ out of the box without coding:
https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5
