### ISSUE TITLE
[BUG] Page Marketplace not working in PT-BR

### ISSUE THREAD

**Issue by leandroatallah** [strapi/strapi#8987]
### Describe the bug

Page _Marketplace_ not working in PT-BR.

### Steps to reproduce the behavior

1. Open admin painel
2. Click on marketplace menu link
3. See error

### Screenshots
![image](https://user-images.githubusercontent.com/19499413/103026875-94618600-4533-11eb-8129-d239f6856b2b.png)

### System

- Node.js version: 14.15.1
- NPM version: 6.14.8
- Strapi version: Strapi v3.1.0-alpha.5
- Database: Local file
- Operating system: Windows 10 (WSL2)

**Comment by derrickmehaffy** [comment]
Marketplace link is throwing 500 error regardless of lang code: https://marketplace.strapi.io/plugins

Confirmed and raising to high priority

**Comment by derrickmehaffy** [comment]
Issue resolved, server had an error but was fixed.

Marking as closed.
