### ISSUE TITLE
Unable to connect MySQL DB

### ISSUE THREAD

**Issue by Sambhrama754** [strapi/strapi#8989]
┌─[sambhrama@parrot]─[~]
└──╼ $npx create-strapi-app basaveshwar_hardwares
Creating a new Strapi application at /home/sambhrama/basaveshwar_hardwares.

? Choose your installation type Custom (manual settings)
? Choose your default database client mysql
? Database name: DONTWANTOSHOW
? Host: DONTWANTOSHOW
? Port: 3306
? Username: DONTWANTOSHOW
? Password: DONTWANTOSHOW
? Enable SSL connection: Yes

⛔️ Connection test failed: Command failed: npm install --prefix /tmp/strapi0b7729a9623f strapi-connector-bookshelf@3.3.4 knex@<0.20.0 mysql@latest
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /tmp/strapi0b7729a9623f
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/tmp/strapi0b7729a9623f'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sambhrama/.npm/_logs/2020-12-24T06_39_22_428Z-debug.log

Retrying...
? Choose your default database client (Use arrow keys)
❯ sqlite 
  postgres 
  mysql 
  mongo

**Comment by Sambhrama754** [comment]
pls help me

**Comment by Sambhrama754** [comment]
USING InfinityFree

**Comment by sunnysonx** [comment]
@Sambhrama754 
Can you run the command: `npx create-strapi-app --version` ? What version it displays?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by Sambhrama754** [comment]
3.3.4
________________________________
