### ISSUE TITLE
Strapi migration issue 3.3.4 to 3.4.1

### ISSUE THREAD

**Issue by arimathi14** [strapi/strapi#8990]
I am trying to migrate strapi 3.3.4 to 3.4.1. I got the following error

TypeError: Cannot read property 'findConfiguration' of undefined
    at run (migrate-3.4.0.js:51:45)

**Comment by sunnysonx** [comment]
You should first install the new strapi version(v3.4.1), with `yarn install` or `npm install` commands.

The migration script should be run in the **Final** step.

**Comment by arimathi14** [comment]
Thanks for the information
