### ISSUE TITLE
Programmatic update of components doesn't work

### ISSUE THREAD

**Issue by aminta** [strapi/strapi#8993]
### Describe the bug

When I try to programmatically update a record based on a content type that has components as fields, If i try to update also the components I get an error and the related components are deleted from Database. When I try to load the record I get an infinite spinner.

### Steps to reproduce the behavior

See code below

### Expected behavior

The record should be correctly updated.

### Code snippets

```
// task structure

{
 name: "Test",
 places: Array of components (each component it's an array of components)
}
```

```
let task =  await strapi.services.tasks.findOne({ id: 1 })
let contentOfOriginalTask = {...task}
contentOfOriginalTask.places.map(place => {
return {testfield: 'Hello', ...place}
}
let updatedTask = await strapi.services.tasks.update({ id: 1 }, contentOfOriginalTask ); // doesn't work
let updatedTask = await strapi.services.tasks.update({ id: 1 }, {name: "Test2"} ); // works
````

### System

- Node.js version:  v12.19.1
- NPM version: 6.14.8
- Strapi version:  3.4.0
- Database: MongoDb
- Operating system: MacOS 11.1

### Additional context

I' ve tried to run this code in a "afterUpdate" cycle hook of another content type.

**Comment by iagocalazans** [comment]
The components are recreated every time you update, so if you don't specify the ID it will delete and re-create the entry and you will see the ID value change.

[Check it here](https://strapi.io/documentation/developer-docs/latest/concepts/models.html#components)

**Comment by aminta** [comment]
> They should be in an array and, If you don't specify the ID it will delete and re-create the entry and you will see the ID value change.
> 
> [Check it here](https://strapi.io/documentation/developer-docs/latest/concepts/models.html#components) on the [update] tab

They are in array. As from my code, I map the array, adding only one field but leaving the others, ID included.

**Comment by aminta** [comment]
Ok, I've understood, with 
```
contentOfOriginalTask.places.map(place => {
 return {testfield: 'Hello', ...place}
}
```

I was passing the original data simple as they are, but you must not, you have to pass the data as from models rules.
