### ISSUE TITLE
GraphQL and REST responses differ with custom controller logic

### ISSUE THREAD

**Issue by jurij** [strapi/strapi#8995]
### Describe the bug

Response of REST API and GraphQL differs with custom controllers

#### REST

Request:

```bash
curl --location --request PUT 'https://localhost:1337/listings/8' \
--header 'Authorization: Bearer MY_TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{
  "Name": "name1",
  "Description": "desc1"
}'
```

Response (Status Code: 401):

```json
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "You can't update this entry"
}
```

GraphQL Request:

```graphql
mutation {
  updateListing (input: {
    data: {
      Name: "updated",
      Description: "# header"
    }
    where: {
      id: "8"
    }
  }) {
    listing {
      Name
    }
  }
}
```

Response (Status Code: 200):

```json
{
  "data": {
    "updateListing": {
      "listing": {
        "Name": null
      }
    }
  }
}
```

### Expected behavior

GraphQL response should be identical to REST response (same status code, etc...)

### Code snippets

api/listing/controllers/listing.js (based on https://strapi.io/documentation/developer-docs/latest/guides/is-owner.html#limit-the-update)

```js
  async update(ctx) {
    const { id } = ctx.params;

    let entity;

    const [listing] = await strapi.services.listing.find({
      id: ctx.params.id,
      "user.id": ctx.state.user.id,
    });

    if (!listing) {
      ctx.response.status = 401;
      return ctx.unauthorized(`You can't update this entry`);
    }

    if (ctx.is("multipart")) {
      const { data } = parseMultipartData(ctx);
      entity = await strapi.services.listing.update({ id }, data);
    } else {
      entity = await strapi.services.listing.update({ id }, ctx.request.body);
    }

    return sanitizeEntity(entity, { model: strapi.models.listing });
  },
```

### System

- Node.js version: v14.15.1
- NPM version:
- Strapi version: v3.4.0
- Database:
- Operating system:

**Comment by LeBenLeBen** [comment]
I also encounter this issue, the response returned is not compatible with GraphQL schema and throws "Cannot return null for non-nullable field" (same as in #9052)

I changed the following:

```js
return ctx.unauthorized(`You can't update this entry`);
```

With:

```js
throw strapi.errors.unauthorized(`You can't update this entry`);
```

It still returns a server error but at least GraphQL isn’t getting a malformed response but a proper error which I can handle in the Apollo Error link.

Inspired by the user permissions plugin: https://github.com/strapi/strapi/blob/b7bd30b9187244611bb7a283894f7c9f383debdf/packages/strapi-plugin-users-permissions/config/policies/permissions.js

**Comment by derrickmehaffy** [comment]
That guide is not correct (hasn't been updated in some time), you should be using a policy but much like @LeBenLeBen mentioned the boom methods don't work properly in GraphQL (you have to use the throw).

Here is a sample project that has a poorly written policy but shows how to handle REST and GraphQL.

[test8995.zip](https://github.com/strapi/strapi/files/6339176/test8995.zip)

**Comment by derrickmehaffy** [comment]
Shouldn't be an issue in v4
