### ISSUE TITLE
Multiple Relationship not working

### ISSUE THREAD

**Issue by leningradspb** [strapi/strapi#8999]
Hello 👋 

I have multiple relationships content types. It's Leagues->Games->Events.
Everything ok with games in leagues, but events in games not showing. But if I do request Games (without leagues) it works perfect. Or if I replace events into leagues also works correct.

Just try do get requests http://104.236.24.61/leagues and after http://104.236.24.61/games

### Expected behavior

Multiple relationships works correctly.

### System

- Strapi version: 3.1.0
OS Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
