### ISSUE TITLE
Model and service with name in CamelCase

### ISSUE THREAD

**Issue by k20human** [strapi/strapi#90]
Hi,

I have some model with a name in CamelCase name like ChecklistEmployee or RoleRight.
When i try to access to these models in my controllers i have this error  

>  ReferenceError: RoleRight is not defined

After some research in strapi code i find the `globalId` property. I add `globalId: "RoleRight"` in my model definition (js file) and it's seem work.

I have the same problem with services with a CamelCase name, but i haven't find any solutions (my workaround is to rename in lowercase the file)

Is it a bug ? I've done something wrong ?

**Comment by loicsaintroch** [comment]
Hey @k20human, I'm not sure to understand your issue.The `globalID` and the `name` are not the same ones?

**Comment by k20human** [comment]
For a better understanding there is my ChecklistEmployee.js model file. If i don't add `globalId: "ChecklistEmployee"` and i try to start Strapi i have this error : 

> ReferenceError: RoleRight is not defined

```
'use strict';

/**
 * Module dependencies
 */

// Public node modules.
const _ = require('lodash');

// Settings for the checklistEmployee model.
const settings = require('./ChecklistEmployee.settings.json');

/**
 * Export the person model
 */

module.exports = {

	/**
	 * Basic settings
	 */

	globalId: "ChecklistEmployee",

	// The identity to use.
	identity: settings.identity,

	// The connection to use.
	connection: settings.connection,

	// Do you want to respect schema?
	schema: settings.schema,

	// Merge simple attributes from settings with those ones.
	attributes: _.merge(settings.attributes, {}),

	// Do you automatically want to have time data?
	autoCreatedAt: settings.autoCreatedAt,
	autoUpdatedAt: settings.autoUpdatedAt
};
```

**Comment by Aurelsicoko** [comment]
@k20human: This behavior is right, the model name are capitalized ([see here](https://github.com/wistityhq/strapi/blob/master/lib/configuration/hooks/waterline/index.js#L177)), so the right global variable to access to your model should be `Roleright` or `Checklistemployee` in your second example.

**Comment by k20human** [comment]
Is it possible to change change this behaviour in future release ?

**Comment by Aurelsicoko** [comment]
@k20human: I thought about this issue a lot, and I am hesitating a little bit on the right decision to make.

Four scenarios are possible:
* Uppercase the first letter: 
   * `roleright` would become `Roleright`
   * `roleRight` would become `RoleRight`
   * `Roleright` would become `Roleright`
   * `RoleRight` would become `RoleRight`
* Camelcase: 
   * `roleright` would become `roleright`
   * `roleRight` would become `roleRight`
   * `Roleright` would become `roleright`
   * `RoleRight` would become `roleRight`
* Capitalize (current): 
   * `roleright` would become `Roleright`
   * `roleRight` would become `Roleright`
   * `Roleright` would become `Roleright`
   * `RoleRight` would become `Roleright`
* Uppercase first letter + Camelcase (current):
   * `roleright` would become `Roleright`
   * `roleRight` would become `RoleRight`
   * `Roleright` would become `Roleright`
   * `RoleRight` would become `RoleRight`

The last one seems to be the right one to me. What do you think about that? It will be included in the v3.0.

**Comment by k20human** [comment]
Hi,

I think the best solution is the last one : Uppercase first letter + Camelcase

**Comment by Aurelsicoko** [comment]
@k20human: Perfect! I will do it in the next days. Thanks.
