### ISSUE TITLE
How can I set the user’s custom role role upon registration?

### ISSUE THREAD

**Issue by KMS74** [strapi/strapi#9003]
How can I set the user’s custom role role upon registration?
like this in postman 
{
  "username" : "username",
  "email" : "email",
   "password" : "password",
  "role" :  putting the ID of the custom role  
  }

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
