### ISSUE TITLE
Textarea content not displayed when saving modification

### ISSUE THREAD

**Issue by mJehanno** [strapi/strapi#9004]
### Describe the bug

Text erased when saving data with textarea.

### Steps to reproduce the behavior

1. Create a type with textarea field
2. Create a new entry of that type
3. Write text in the textarea field
4. Save result
5. Text is not displayed anymore (even if you exit en re-edit)

### Expected behavior

The text should still be displayed when saving result. 

### Screenshots

![empty-textarea](https://i.ibb.co/b2Wv4sG/Screenshot-2020-12-27-at-17-34-25.png)

As you can see my textarea is empty.

![filled-preview](https://i.ibb.co/w7RBhPV/Screenshot-2020-12-27-at-17-34-33.png)

Yet when I go to the preview section my text is displaying. The problem is that first I wrote a long text and thought it was not saved correctly (as nothing was displayed in the textarea in edit mode) so I wrote something in again and it erased the previous entry ....

### System

- Node.js version:  12.13.0 
- NPM version: 6.14.8
- Strapi version: 3.4.X (some part of my app (bottom of sidebar) is saying 3.4.0 but settings are saying 3.4.1) 
- Database: default
- Operating system: MacOs BigSur

### Additional context

It might only happens while saving in preview mode or whith publish feature. I can't reproduce it on every textarea of my app

**Comment by derrickmehaffy** [comment]
Rebuild your admin, this was fixed in v3.4.1
