### ISSUE TITLE
Document action naming convention for camelCased collection types

### ISSUE THREAD

**Issue by jorisw** [strapi/strapi#9008]
### Describe the bug

When using camelCased names for content types, the Users & Permissions plug-in fails to find permissions for them, causing queries for them over GraphQL, to fail with a Forbidden message.

### Steps to reproduce the behavior

1. Create a content type with a camelCased name such as recommendedBook
2. Enable the GraphQL plug-in
3. Enable find and findOne permissions on recommendedBook for the Public role
4. Add a custom resolver to `api/recommended-book/config/schema.graphql.js`:
```js
module.exports = {
    resolver: {
      Query: {
        recommendedBooks: {
          description:
            'Return a list of books reformatted as something else',
          resolverOf: 'application::recommendedBook.recommendedBook.find',
          resolver: (obj, options, { context }) => {
            return []
          },
        },
      },
    },
  }
```
5. Try and query `recommendedBooks` from the GraphQL playground

You will get: 

```
"stacktrace": [
    "Error: Forbidden",
    "    at handleErrors (node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:92:28)",
    "    at module.exports (node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:79:12)",
    "    at async node_modules/strapi-utils/lib/policy.js:68:5",
    "    at async node_modules/strapi-plugin-graphql/services/resolvers-builder.js:97:7",
    "    at async node_modules/strapi-plugin-graphql/services/type-definitions.js:53:19"
]
```

### Expected behavior

Would expect an array of items to be the response, or whatever the custom resolver returns.

### Code snippets

I have added some debug directly to `node_modules/strapi-plugin-users-permissions/config/policies/permissions.js` to see how permissions are queried and which ones are found. Turns out the controller name is malformed in querying for permissions to access the content type:

Looks for, and fails to find:

```js
{
  role: 2,
  type: 'application',
  controller: 'recommendedbook',
  action: 'find',
  enabled: true
}
```

Should have found:

```js
[
    {
      id: 536,
      type: 'application',
      controller: 'recommended-book',
      action: 'find',
      enabled: true,
      policy: '',
      role: 2,
      created_by: null,
      updated_by: null
    },
]
```

### System

- Node.js version: 14.1
- Yarn version: 1.22.5
- Strapi version: 3.4.1
- Database: MySQL
- Operating system: macOS 11.1

**Comment by jorisw** [comment]
The problem actually goes away if I change:

```
        resolverOf: 'application::recommendedBook.recommendedBook.find',
```

to: 

```
        resolverOf: 'application::recommended-book.recommended-book.find',
```

Would suggest adding documentation for action naming convention to the [custom resolvers guide](https://strapi.io/documentation/developer-docs/latest/plugins/graphql.html#customize-the-graphql-schema).

**Comment by pelumiojebode** [comment]
On Mon, Dec 28, 2020 at 12:44 PM Joris W <notifications@github.com> wrote:

> The problem actually goes away if I change:
>
>         resolverOf: problems
>
>
'application:Bitpay,MOFAIC
>
> :recommendedBook Bible
>
>
.recommendedBook Quran .
>
>
find‘ Solutions

**Comment by derrickmehaffy** [comment]
Fixed in v4 as we have programmatic names now
