### ISSUE TITLE
Misleading message: The provider package isn't installed.

### ISSUE THREAD

**Issue by alesanchezr** [strapi/strapi#9012]
I was trying to install and use the `strapi-provider-upload-google-cloud-storage,` but I had an issue with the JSON syntax for the google cloud key. When I was running strapi, I was getting this error: 

```
error Bootstrap function in plugin "upload" failed
[2020-12-28T19:55:56.180Z] error Error: The provider package isn't installed. Please run `npm install strapi-provider-upload-google-cloud-storage`
```
Triggered because of this [try..catch](https://github.com/strapi/strapi/blob/dd1817680d9ec4b9c04d835135d3c2fe35d01557/packages/strapi-plugin-upload/config/functions/bootstrap.js#L51): 

```js
  try {
    const providerInstance = require(`strapi-provider-upload-${provider}`).init(providerOptions);

    return Object.assign(Object.create(baseProvider), {
      ...providerInstance,
      upload: wrapFunctionForErrors(providerInstance.upload.bind(providerInstance)),
      delete: wrapFunctionForErrors(providerInstance.delete.bind(providerInstance)),
    });
  } catch (err) {
    strapi.log.error(err);
    throw new Error(
      `The provider package isn't installed. Please run \`npm install strapi-provider-upload-${provider}\``
    );
  }
```

But the real problem was not related to the missing installation of the plugin; the real problem was[ triggered during the bootstrapping of the google-cloud plugin](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/Strapi.js#L337).

I think it's better to just say "There was a problem during the initialization of the strapi-provider-upload-${provider} upload plugin".

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
