### ISSUE TITLE
Boolean fields being null appear to be false in content manager

### ISSUE THREAD

**Issue by pmrotule** [strapi/strapi#9013]
### Describe the bug

When adding a boolean field to a collection type, you can define the default value which can either be `True`, `Null`, or `False`.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/10983258/103244990-fc163780-495e-11eb-9359-64cb57b71a4c.png">

but when you look at a specific entry in the content manager, the boolean field has suddenly different possible values: `Off` and `On`. In my opinion, that's inconsistent, but still not a bug. The actual issue is down to the fact that even when the value of the field is `null`, it appears to be `false` which is misleading since it is sometimes important to know if the value has been set or not when the field is optional.

### Steps to reproduce the behavior

1. Create a new boolean field in a collection type and keep the default advanced settings
2. Create a new entry of this collection type and don't click on the input toggle of that field to keep the null value
3. Check in your database the value of that field (should be NULL)
4. Check the entry you created in the content manager again
5. Notice that it appears to be `Off` (a.k.a. false) instead of `Null`

### Expected behavior

The field in the content manager should be `TRUE`/`FALSE` instead of `OFF`/`ON` to be consistent with the advanced settings. Moreover, the background color should be white for both true and false when the value is null (+ a 1px border in between).

Regarding renaming `OFF`/`ON` to `TRUE`/`FALSE`, I just think it would make more sense since one would always name a boolean to be a fact being true or false, not a switch being on or off. I often end up with funny combinations (i.e. `isMarried` -> off 🤔).

### Screenshots

Not that useful, but this is how it looks when the value is null.

<img width="160" alt="image" src="https://user-images.githubusercontent.com/10983258/103244817-7a260e80-495e-11eb-8b95-a5c669823f3b.png">

### System

- Node.js version: 12.18.3
- Yarn version: 1.22.5
- Strapi version: 3.4.1
- Database: postgresql
- Operating system: macOS Big Sur 11.1

**Comment by ThewBear** [comment]
The `null` state is introduced in https://github.com/strapi/strapi/issues/4059#issuecomment-537581923.  However, two use cases mentioned in that issue is not implemented properly.

> 1. Those who want it to default to `false` and require a value (`false`/`true`), can do so.
> 2. Those who expect Strapi to accurately show all possible DB states (null/false/true) + anyone who may want to allow a field to remain unset during initial entry, such as by a data entry person who needs to skip a field because they don't yet know the value, also can do so.

Here are the issues:
1. The UI boolean element still shows `false` when the value coming from the DB is actually `null`. This will be fixed in PR ___.
2. The `is required` validation error never show up. This will be fixed in PR __.

**Comment by soupette** [comment]
I am closing this issue as a PR that fixes the issue as already been merged.
