### ISSUE TITLE
[3.4.1] JSON field not saving data when pasting it directly to editor

### ISSUE THREAD

**Issue by jseb2520** [strapi/strapi#9016]
### Describe the bug

After the mentioned bug of v3.4.0 where JSON fields were not displaying the saved data (issue #8930 ), i'm now having an issue when i paste a JSON data into the editor and save without making any other changes to the JSON fields pasted. It simply disappears just like in the issue mentioned, but this time the data saved is _null_.

### Steps to reproduce the behavior

1. Create a JSON field on a content-type.
2. Create a new entry on content-type with JSON field created.
3. Paste any JSON-like data without modifying anything else.
4. Click on save button.
5. See JSON field empty and a _null_ API response.

### Expected behavior

The expected behavior should be to keep the changes pasted on the JSON field as they were pasted and not modified.

### Screenshots

Pasted data on JSON field and clicked on "save" button:

![Screen Shot 2020-12-30 at 1 18 35 AM](https://user-images.githubusercontent.com/25942141/103333798-22aaa000-4a3d-11eb-805e-83cae7057395.png)

Result after save:

![Screen Shot 2020-12-30 at 1 19 01 AM](https://user-images.githubusercontent.com/25942141/103333809-2e966200-4a3d-11eb-80e5-b8208a54cd4e.png)

API response after save:

![Screen Shot 2020-12-30 at 1 19 15 AM](https://user-images.githubusercontent.com/25942141/103333828-3b1aba80-4a3d-11eb-9bc9-6e1663cd34ce.png)

### System

- Node.js version: v12.18.4
- NPM version: v6.14.6
- Strapi version: 3.4.1
- Database: SQLite
- Operating system: MacOS Catalina 10.15.7

### Additional context

To bypass this bug for now, i had to paste the data and then make any kind of modification (add space, comma or any other character and then removing it). After saving, data will be same as input in the API response and won't disappear from editor.

**Comment by derrickmehaffy** [comment]
Was able to confirm on v3.4.1

**Comment by shtelzerartem** [comment]
@derrickmehaffy Ran into this bug too. Actually it happened, because value property is set only once, on component mount. But component is rerendered once again with passed value after. It's needed only to fix ```setInitValue``` function in InputJSON component. Can I create PR request with fix?

**Comment by derrickmehaffy** [comment]
Absolutely
