### ISSUE TITLE
Cannot access route with prefix 'admin'

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#9017]
### Describe the Bug
I made a content type with name AdminPanel , which has endpoint admin-panels to access its routes. 
But when i use its api it redirects me to admin login page . Hitting Get url "http://localhost:1337/admin-panels" redirects me to admin panel login page instead of fetching the results.

### Steps to reproduce the behavior

1. Make a content type with name AdminPanel, for which the slug will be admin-panels

### Screenshots

![image](https://user-images.githubusercontent.com/71498747/103336731-09d2d680-4a9f-11eb-9e51-91d007ae366b.png)

### System

- Node.js version: v14.15.0
- NPM version: 6.14.5
- Strapi version: 3.4.1
- Database: sqlite
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
confirmed on v3.4.1, issue likely related to koa-router regex matching the `/admin*` => `/admin`
