### ISSUE TITLE
Limit "files" type allowed in allowedTypes

### ISSUE THREAD

**Issue by hadifarnoud** [strapi/strapi#9019]
if I want to allow uploads of images and pdfs only, I have to choose images and files for `allowedTypes` which means user can upload all kind of zip, pptx, etc. files.

it would be great if there were a way to customise that to file extension level. something like this:

```
allowedTypes: [
   "images",
   ".pdf",
]
```

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by hadifarnoud** [comment]
there is a "feature request" for issues. I guess you have to remove that too

**Comment by derrickmehaffy** [comment]
I can reopen it as a feature request, the way this was worded didn't look like one, and appears you didn't use the feature request template.
