### ISSUE TITLE
Mongo models fetch strips empty object properties

### ISSUE THREAD

**Issue by doublemarked** [strapi/strapi#902]
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.11.2
- **Database**: mongo
- **Operating system**: MacOS

**What is the current behavior?**
I have a content type that contains a JSON property, an array of objects. The objects in this array contain a property "options" which is initialized as blank, i.e.  something like:
```
   { 
     "_id": "deadbeef", 
     "steps": [ { "name": "Step 1", "options": {} } ],
     // ... other stuff ...
   }
```

The record stored in mongodb is as written above with an empty "options" property. However, when I fetch the record from Strapi the results have this options property stripped out. Other properties are not stripped. So the record received looks like this:

```
   { 
     "_id": "deadbeef",
     "steps": [ { "name": "Step 1" } ],
     // ... other stuff ...
   }

```

**Steps to reproduce the problem**
1. Create a model with a JSON property and store a record similar to the sample above
2. Confirm via mongo cli that the record is stored correctly and completely
3. Fetch the record via the REST API, or directly call `strapi.services.[model].fetch(...)`
4. Observe that the results do not have an "options" property.

**What is the expected behavior?**

Empty properties should be preserved.

**Suggested solutions**

---
- [x] I'm sure that this issue hasn't already been referenced

I searched a bit and could not find any other references to this.

**Comment by lauriejim** [comment]
Hi @doublemarked.

- Did you use the content manager to create/save your data or you use generated API ?
- The data in your mongo document have the key `options` with empty object ?

Can you take a look if the problem is coming from mongoose. By writing a small script to test it.

**Comment by doublemarked** [comment]
Hello @lauriejim !

1. This was via the generated API
2. Yes, the mongo document has the key options with empty object
3. Good idea. So I've done that and then done a bunch of debugging. 

Here's the result: first, I as mistaken in saying that `fetch` is returning the wrong data. `fetch` actually works fine, but the result returned to the browser is missing the data. I've tracked that down to the strapi-mongoose override of toJSON: https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/index.js#L169

This override lacks `minimize: false`, which causes the default value of `minimize: true` to be applied, which strips empties. Do you think it would be reasonable to set `minimize: false` on your override? I'm not familiar enough with Strapi to advise whether that's a good idea or not.

**Comment by lauriejim** [comment]
Sorry for delay.

You can make the same as this line https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/index.js#L180 but for `minimize` settings.

I think it's could be great to update the way we set models `options` in schema to make it more modular. With a loop attribution.

**Comment by Aurelsicoko** [comment]
@doublemarked I think we should use the `options` attributes in the models.

```js
{
  "connection": "default",
  "info": {
    "name": "file",
    "description": ""
  },
  "options": {
    "timestamps": true,
  },
  "attributes": {
    "name": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    ...
  }
}
```

**Comment by doublemarked** [comment]
@Aurelsicoko thank you very much!
