### ISSUE TITLE
GraphQL plugin does not return more than 100 users

### ISSUE THREAD

**Issue by kaanguru** [strapi/strapi#9023]
### limit does not return more than 100 users

graphql plugin does not return all users

### Steps to reproduce the behavior

1. Add users more than 1000
2. Request users with a limit higher than 100
3. Only 100 users will return

### Expected behavior
GraphQL should return more than 100 users

GraphQL can not get all users at once while using GraphQL?

It just returns first 100 users while using GraphQL but works fine with a GET request.

```
{
  users(limit: 200) {
    id
    username
  }
}
```

### Screenshots

![resim](https://user-images.githubusercontent.com/47606404/103415673-4a604c00-4b94-11eb-85ce-ff371be6e1cd.png)

### Result

![resim](https://user-images.githubusercontent.com/47606404/103415682-53511d80-4b94-11eb-805f-978e1b9e20d5.png)

### Code snippets
```
{
      users(limit: -1) {
        id
        username
      }
    }
```
returns just first 100 users

### System

    **Strapi Version**:3.4.1

    **Operating System**: Windows, Ubuntu

    **Database**: Mysql, PostgreSQL

    **Node Version**: 14.15.3

    **NPM Version**: 6.14.9

    **Yarn Version**: 1.22.5

### Additional context

**limit can't get assigned more than 100 or -1**

https://github.com/strapi/strapi/blob/c6f0902c30bed3970919d029087c6922aef51473/packages/strapi-plugin-graphql/services/data-loaders.js#L154

**Comment by alexandrebodin** [comment]
Hi, 
the maximum limit is defined in the configuration to avoid fetching too much data. You can configure this max limit witht the `amountLimit` setting. Here is the documentation on graphql configuration where it is mentionned https://strapi.io/documentation/developer-docs/latest/plugins/graphql.html#configurations
