### ISSUE TITLE
Google OAuth Login redirecting to Facebook

### ISSUE THREAD

**Issue by raphaelcps** [strapi/strapi#9028]
### Describe the bug

I'm following the instruction in https://strapi.io/documentation/developer-docs/latest/plugins/users-permissions.html#what-you-have-to-do-in-your-frontend for Facebook and Google providers. The facebook one worked well, but the google login is failling. In the step in wich is expected strapi to redirect back to the front-end (FRONTEND_URL/connect/google/redirect), it is returning to facebook url and also returning a error with it: `error[error][message]=Missing redirect_uri parameter.&error[error][type]=OAuthException&error[error][code]=191&error[error][fbtrace_id]=AL4bdQaoN5Yeat_sl7PdOoq`

### Steps to reproduce the behavior

1. Enable google provider
2. Fill in the client id and secret from Google
3. Add the redirect URL to front-end (http://localhost:4200/auth/google/redirect)
3. Add the redirect URL to Google application configurations
4. Click the link to login in app (http://localhost:1337/connect/google)
5. Choose your Google account

### Expected behavior

The strapi should call FRONTEND_URL/connect/google/redirect instead of FRONTEND_URL/connect/facebook/redirect

### System

- Node.js version: v12.20.0
- NPM version: 6.14.8
- Strapi version: v3.4.1
- Database: Mongodb
- Operating system: Windows 10

**Comment by raphaelcps** [comment]
I just changed the login link from localhost:1337 to my ngrok.io address and it started working (from http://localhost:1337/connect/google to https://***.ngrok.io/connect/google)

**Comment by derrickmehaffy** [comment]
Certain hosts do not allow localhost as a valid callback, I believe Google is one of these. Marking as closed.
