### ISSUE TITLE
Strapi keeps throwing 'error occured' after creating collection-type, unable to create component

### ISSUE THREAD

**Issue by Galvotas** [strapi/strapi#9029]
### Describe the bug

So it was a long time I've been struggling with some 'error occurred' on save, in strapi. But It worked until I needed to do some more customization. 
My problem is that whenever i create a new collection type with some fields and press save, the window starts loading and throws multiple 'error occurred' at the top of the window, and sometimes it will load just endlessly until manual refresh. After reloading manually, new collection type do usually appear on the list.
Another strange behavior is when I try to create a component inside strapi, I start entering name, everything seems well, but when filling the 'Select a category or enter a name to create a new one' field, value from the field immediately disappear. 

What can cause this behavior?

### Steps to reproduce the behavior

I tried multiple times and multiple resources, from strapi docs to random people, and every project I'm deploying has the same issue.
This is the video I've been following last time : https://www.youtube.com/watch?v=0PLoSxnxdVA&t=248s

1. Go to 'strapi development'
2. Click on 'create new collection type'
3. Add fields
4. Press save
5. See error

### Expected behavior
  
To save new items inside strapi without errors.

### System

- Node.js version:  v14.15.3
- NPM version: 6.14.10
- Strapi version: 3.4.1
- Database: MongoDB
- Operating system: Windows

### Additional context

After a few saves my console gets really red with this error: Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by jimmerk** [comment]
Having the same issue when trying to create a new collection.

**Comment by Galvotas** [comment]
To add to the main cake, I started getting this message too: 'An error occurred during models config fetch.' just on random attempt to move from one collection-type to other.

**Comment by Galvotas** [comment]
Update: I have updated my strapi version to 3.4.1 and created a new project from scratch. I still do get some 'error occurred' time to time, but 'models config fetch' fortunately disappeared.
