### ISSUE TITLE
Upload File Non Nullable

### ISSUE THREAD

**Issue by csprance** [strapi/strapi#9040]
### Describe the bug

When creating an image field and marking it as required and using the GraphQL plugin it is not marked as a non nullable field.

### Steps to reproduce the behavior

1. Create a collection
2. Add a field of image type to the collection
3. Mark the image field as required in advanced settings
4. Look at graphQL schema to see it is required but not marked as non nullable

### Expected behavior

I would expect the generated GraphQL schema from a model named Portfolio looking like this

```json
...
"featuredImage": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images"
      ],
      "plugin": "upload",
      "required": true
    },
...
```
to generate a schema that looks like 
```gql
type Portfolio {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  published_at: DateTime
  featuredImage: UploadFile!
  ...
}
```

However the schema generated looks like
```gql
type Portfolio {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  published_at: DateTime
  featuredImage: UploadFile
  ...
}
```

Notice there is no ! after the UploadFile which means it is not non-nullable which means if I generate typings using something like apollo-codegen it will make the code I write be much more verbose because of all the checks for undefined/nulls I need to do even though I know there will always be a value there.

Keep up the amazing work with Strapi! Really digging the Dynamic Content Zones!

### System

- Node.js version: v14.5.0
- NPM version: 6.14.5
- Strapi version: v3.4.1
- Database: Sqlite
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/557
