### ISSUE TITLE
Connection test failed: no such file or directory /tmp/strapi... [Ubuntu 18]

### ISSUE THREAD

**Issue by dataexcess** [strapi/strapi#9042]
Hi everyone,

I have an active postgres database running and after I try to connect it by following the installation wizzard in the 'strapi new ...' command I get the following error:

Please help me :'( 

```
    ⛔️ Connection test failed: Command failed: npm install --prefix /tmp/strapi25244c20243f strapi-connector-bookshelf@3.4.1 

    knex@<0.20.0 pg@latest
    npm ERR! code ENOENT
    npm ERR! syscall lstat
    npm ERR! path /tmp/strapi25244c20243f
    npm ERR! errno -2
    npm ERR! enoent ENOENT: no such file or directory, lstat '/tmp/strapi25244c20243f'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent 

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-01-05T12_20_14_416Z-debug.log
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
