### ISSUE TITLE
Improve the relation item spacing

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#9043]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Improve the relation spacing. Right now the `+`/`-` icon has too much space:

![relation](https://user-images.githubusercontent.com/1007051/103651917-94fe1180-4f62-11eb-845d-c3adcd48e6b8.png)

### Suggested solution(s)

Reduce the `+`/`-` icon left spacing.

**Comment by abdonrd** [comment]
@soupette if you can guide me, I can try to send a PR. Or if you see that it is easy and you want to take it yourself, go ahead!

**Comment by abdonrd** [comment]
@soupette if I just add a `width: auto;` in the `div` that surrounds the icon... It works!

<img width="378" alt="Screenshot 2021-06-17 at 13 20 43" src="https://user-images.githubusercontent.com/1007051/122387135-d9102c00-cf6e-11eb-9148-ba1cd44bf642.png">

How we should do it in the Strapi core? To create a PR. Thanks!

**Comment by soupette** [comment]
@abdonrd you can make a PR [here](https://github.com/strapi/strapi/blob/c7c549aee613511f4abeccbf5c8885cc38a0f1ba/packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js#L75-L77) is the file/component you are looking for:

It might be worth to create a component instead of adding some inline style.

**Comment by abdonrd** [comment]
@soupette thanks! 👏

Since I have no experience with React, I am going to make the option easier: #10503. I guess it can always be improved later.
