### ISSUE TITLE
Stream in a Firebase way

### ISSUE THREAD

**Issue by dleurs** [strapi/strapi#9044]
## Feature request

I would be fantastic to have the possibility to access our data with stream in a firebase / socket.io way.<br/>
For example, if I want to develop a chat, it seems to be a must-have. <br/>
How would you do a chat with the actual version of strapi ? Refreshing every 5 seconds with a GET to see if there is new messages ?<br/>

Thank you for your time<br/>
Stay safe

**Comment by derrickmehaffy** [comment]
There are quite a number of resources with using Socket.io and Strapi:

https://medium.com/strapi/strapi-socket-io-a9c856e915a6
https://forum.strapi.io/t/strapio-the-ez-to-use-socket-io-configurator/414
https://www.youtube.com/watch?v=yS1g7Veg2Vk
https://tsh.io/blog/socket-io-tutorial-real-time-communication/

Going to mark this as closed as this isn't really a feature request and is more of a question, questions should be asked on our forum: https://forum.strapi.io

**Comment by dleurs** [comment]
Thank you very much<br/>
Sorry, I looked in the strapi forum for "stream" but could not find something relevent :<br/>
https://forum.strapi.io/search?q=stream
