### ISSUE TITLE
Unable to open Strapi admin page

### ISSUE THREAD

**Issue by matheosct** [strapi/strapi#9049]
Right after I installed Stripe and switched the permissions of user to "find", "findOne" and "create" I couldn't edit my strapi dashboard anymore and when I tried to login I just got a blank page, not the form.

When I inspec the console I get this:

_main.917de9e2.chunk.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Cl (main.917de9e2.chunk.js:1)
    at f (main.917de9e2.chunk.js:1)
    at h (main.917de9e2.chunk.js:1)
    at main.917de9e2.chunk.js:1
    at Oi (main.917de9e2.chunk.js:1)
    at vc (main.917de9e2.chunk.js:1)
    at sl (main.917de9e2.chunk.js:1)
    at cl (main.917de9e2.chunk.js:1)
    at Xc (main.917de9e2.chunk.js:1)
    at main.917de9e2.chunk.js:1_

I tried to uninstall stripe, erased every new code I added but still couldn't access the panel.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by baermathias** [comment]
@matheosct You have probably did some customization to you admin area and then updated your Strapi version. Had a similar error here https://github.com/strapi/strapi/issues/10031
