### ISSUE TITLE
Add `enum` type in admin panel (content type builder & content manager)

### ISSUE THREAD

**Issue by oeddyo** [strapi/strapi#905]
*FEATURE REQUEST TEMPLATE*  
Add category (enum) type
**What is the expected behavior?**
This seems like a very common use case. For instance, I'd like to add the field "type" to my "Computer" class. They can be "Laptop", "Mainframe" or "PC" but not anything else.

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by soupette** [comment]
This issue has already been [referenced](https://github.com/strapi/strapi/issues/578).

**Comment by oeddyo** [comment]
Thanks @soupette that's great
But I guess I was trying to say support in admin since it's the editors who need to assign the enum values to the instances : )

**Comment by mnlbox** [comment]
I think something like wordpress tag and category system as a separate module can be useful for many projects.

**Comment by derrickmehaffy** [comment]
Its also related to my closed issue: https://github.com/strapi/strapi/issues/566

I believe you can edit ones created in the CLI but you cannot add them through the admin panel.

**Comment by dsibaja-dnamyc** [comment]
But are we still gonna get and admin way to add enum types? because that would be so neat.

**Comment by derrickmehaffy** [comment]
I believe it is on their to-do list but not very high right now I'd imagine.

**Comment by soupette** [comment]
Currently you can't add the enu type from the `content-type-builder` however if you set it manually the `content-manager` plugin will display it

**Comment by lauriejim** [comment]
Duplicate - https://github.com/strapi/strapi/issues/905

**Comment by abdonrd** [comment]
@lauriejim you link to the same issue. 😅
