### ISSUE TITLE
Links to Strapi Blog broken on Strapi Admin Pages

### ISSUE THREAD

**Issue by sanjaysanjel019** [strapi/strapi#9056]
## Bug report
Links to the Strapi Blog is broken in the Admin page and showing 404 Error .
### Describe the bug

After we run our Strapi app in development mode, we get redirected to Strapi Admin page and we are greeted with a text and links to blog. However the links are broken and redirect us to 404 Page.

The post that shows in my admin feed are:
1) Jamstack in 2020
2) Change the default WYSIWYG by Toast UI editor

Both of the above links are broken as they redirect me to a 404 page. 

### Steps to reproduce the behavior

1. Go to 'localhost:{PORT_NO}/admin'
2. Click on the links that are present just below the message "Hi".
3. Blog links are broken  and gets redirected to 404 page.

### Expected behavior

As expected the links to each anchor should redirect to their original blogpost which are published on  strapi.io/blog.

### Screenshots

![Strapi 404 Error ](https://i.imgur.com/sr9igFB.png)

**Comment by MattieBelt** [comment]
Can confirm this on `v3.4.1`, regarding these two links:

https://strapi.io/blog/jamstack-in-2020

https://strapi.io/blog/change-the-default-wysiwyg-by-toast-ui-editor

**Comment by derrickmehaffy** [comment]
Issue is we don't currently have D&P enabled on our own internal Strapi instance. We have a work around to fix the issue but to answer the question of what's going on here. These are unpublished articles that will be made available in the future.

Marking as closed as we are well aware of the issue. Thank you.
