### ISSUE TITLE
Migration Issue: Cannot find module node_modules/strapi-plugin-content-manager/utils/parse-multipart

### ISSUE THREAD

**Issue by vks-ahamilton** [strapi/strapi#9059]
Hello, 
I am having some migration issues to 3.4.1 for some reason everytime I run npm install one of the packages in package-lock.json will not update to the new version which seems to be causing errors for the migration. Also I believe a missing node modules document is not being installed either. here is an image of the issues, my package-lock.json file of the package causing the error and not updating. Also below will be an error log:

Please let me know if you need any information or if you need to reproduce the code to see the real issue.

1 verbose cli [
1 verbose cli   '/home/vksappc/lib/node_modules/node/bin/node',
1 verbose cli   '/home/vksappc/bin/npm',
1 verbose cli   'audit'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v14.5.0
4 verbose npm-session 9ccab78f8612a39c
5 verbose stack Error: Errors were found in your package-lock.json, run  npm install  to fix them.
5 verbose stack     Invalid: lock file's strapi-provider-upload-custom@file:https:/registry.npmjs.org/strapi-provider-upload-local/-/strapi-provider-upload-local-3.1.3.tgz does not satisfy strapi-provider-upload-custom@file:providers/strapi-provider-upload-custom
5 verbose stack     at /home/vksappc/lib/node_modules/npm/lib/audit.js:184:19
6 verbose cwd /home/vksappc/public_html/new_site_staging/backend
7 verbose Linux 3.10.0-1127.18.2.el7.x86_64
8 verbose argv "/home/vksappc/lib/node_modules/node/bin/node" "/home/vksappc/bin/npm" "audit"
9 verbose node v14.5.0
10 verbose npm  v6.14.7
11 error code ELOCKVERIFY
12 error Errors were found in your package-lock.json, run  npm install  to fix them.
12 error     Invalid: lock file's strapi-provider-upload-custom@file:https:/registry.npmjs.org/strapi-provider-upload-local/-/strapi-provider-upload-local-3.1.3.tgz does not satisfy strapi-provider-upload-custom@file:providers/strapi-provider-upload-custom
13 verbose exit [ 1, true ]

![Screenshot 2021-01-07 083211](https://user-images.githubusercontent.com/69636266/103912723-a582c900-50d5-11eb-82c5-9c46e6850671.png)
![Screenshot 2021-01-07 094414](https://user-images.githubusercontent.com/69636266/103912777-b7fd0280-50d5-11eb-8479-64e7f93d4115.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by Ayo91** [comment]
I have the same issue
