### ISSUE TITLE
Error: relation "x" does not exist

### ISSUE THREAD

**Issue by anthonyatp** [strapi/strapi#9062]
### Describe the bug

In dev environment, I create a new content-type called "jobs". When I select the newly created content type, I get this error message:
```
An error occurred during models config fetch.
```
and in the terminal:
```
error: relation "jobs" does not exist
```

I just upgraded to 3.0.0 stable but this was also happening before I upgraded (beta-19). I don't understand the error message. Can someone help me understand why this is failing?

### Steps to reproduce the behavior

I'm not sure if this will reproduce the error but the steps I took were:

1. Go to 'Content-Types builder'
2. Click on '+ Create new collection type'
3. Input 'job' as display name and click continue
4. Add text field with name 'jobTitle' and click finish
5. Click 'Save'
6. Once server restarts - click on 'Jobs' under 'Collection types'
7. Error message pops up and following error in terminal:
```
error: select "jobs".* from "jobs" order by "jobTitle" asc limit $1 - relation "jobs" does not exist
```

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.0.0
- Database: postgresql
- Operating system: mac

**Comment by anthonyatp** [comment]
The issue was that I had autoMigrate set to false in the db config, so the relation was not being created.

Closing issue

**Comment by luciditydreamss** [comment]
My database.js looks like this:
```
module.exports = ({ env }) => ({
    connection: {
        client: 'postgres',
        connection: {
            connectionString: env('DATABASE_PRIVATE_URL')
        },
        pool: { min: 0 }
    }
});
```

How can I set automigrate to true?
