### ISSUE TITLE
Date format is different after a date is selected

### ISSUE THREAD

**Issue by shilohpcg** [strapi/strapi#9064]
Hi,

I tried to search if this issue exists but I can't find anything. 

Has anyone encountered this? 
![image](https://user-images.githubusercontent.com/68865902/103967813-62057a80-5128-11eb-83d1-789b69379e41.png)
![image](https://user-images.githubusercontent.com/68865902/103967835-692c8880-5128-11eb-8430-54c58b972116.png)

Please advise. Thanks!

**Comment by soupette** [comment]
Hello @shilohpcg the issue you are reporting is an intended behaviour, the format changes when the input is focused so you can change the date manually, which is easier when you want to change the year.

**Comment by shilohpcg** [comment]
Thanks for your reply @soupette. Is there a way / setting in the admin panel where you can change this behavior? For ex. just show the same format 01/07/2021.

**Comment by derrickmehaffy** [comment]
shouldn't be an issue in v4 as we have unified the format I think
