### ISSUE TITLE
Not Able to Access Any Page/Model

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#9067]
Node.js version: v10.0.0
npm version: 6.0.0
Strapi version: 3.1.7
Database: MongoDB
Operating system: Linux

On accessing any page/model i am getting following error:

![err](https://user-images.githubusercontent.com/47749809/103985119-64121c80-51ae-11eb-83cc-a284cfa3e9b7.png)

**Comment by aksdevac** [comment]
Minimum required NodeJS version is 10.16, Try & see if you can regenerate on current latest Strapi & newer NodeJS version.
