### ISSUE TITLE
Please allow use numbers at enum

### ISSUE THREAD

**Issue by borm** [strapi/strapi#9068]
### Please describe your feature request
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary
```
const ENUM_REGEX = new RegExp('^[_A-Za-z][_0-9A-Za-z]*$');
```

### Why is it needed?
As example i need a field for save a day of week, so its can be only from 0 to 6, the `number` format not okay for me
Current solution what works it only to use `string` with regex `^[0-6]{1}$`
Currently that validation works only in admin panel when we have to edit content type
but,
if we have to go model.json file directly and do something like code bellow, all works fine
```json
{
  "collectionName": "test_collection",
  "info": {
    "name": "test",
    "description": ""
  },
  "options": {},
  "attributes": {
    "day": {
      "type": "enumeration",
      "enum": [
        "0",
        "6"
      ]
    },
  }
}

```
### Suggested solution(s)
```
const ENUM_REGEX = new RegExp('^[_0-9A-Za-z]*$');
```

**Comment by derrickmehaffy** [comment]
Closing in favor of: https://github.com/strapi/strapi/issues/7904
