### ISSUE TITLE
How to use NextAuth.js with Strapi?

### ISSUE THREAD

**Issue by RiczCalixto** [strapi/strapi#9071]
### Why is it needed?

How to use NextAuth.js with Strapi? If can, is there any example ?

### Related issue(s)/PR(s)

https://github.com/nextauthjs/next-auth/discussions/574

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
