### ISSUE TITLE
Allow custom fields in GraphQL register mutation

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#9073]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

REST register route allows for custom field assignment, GraphQL does not include alternative fields into the schema

### Why is it needed?

Consistency between REST and GraphQL

### Suggested solution(s)

N/A

### Related issue(s)/PR(s)

N/A

**Comment by shestakov-vladyslav** [comment]
I need this
