### ISSUE TITLE
Email address has been taken error message, Oauth2 login flow

### ISSUE THREAD

**Issue by HorvathDavid** [strapi/strapi#908]
I may or may not wrong but I found that this part blocks me to create Oauth2 login and registration flow.

This valued always true: `advanced.unique_email` is it neccessary? Is there case when there are users with same email address but with different provider?

Please check the link below. Means, if there are any users with different provider than the actual, then evaluate it true.

I only tested with the Google provider. Thanks!

https://github.com/strapi/strapi/blob/479ab61b6b9e9aabd7a3a83c38e2f47e2bba5539/packages/strapi-plugin-users-permissions/services/Providers.js#L69

**Comment by changalberto** [comment]
I'm having similar issue with Facebook Auth

**Comment by lauriejim** [comment]
Hi @HorvathDavid 
You can easily change the `advanced.unique_email` value going in admin panel > groups & permission > advanced and switch off `One account per email address`. It's will allow you to have one email for your Google provider and same email for local email provider.

@changalberto maybe, be sure the email you use is not already used by a user. Same as @HorvathDavid , switch off the option to allow multiple emails

**Comment by HorvathDavid** [comment]
Thank for the answer! @lauriejim 
In my case, - I believe the Facebook provider struggling with similar issue, there is no registered user on the mail address. Fresh registration. The problem with the line which I marked in my  previous comment:
https://github.com/strapi/strapi/blob/479ab61b6b9e9aabd7a3a83c38e2f47e2bba5539/packages/strapi-plugin-users-permissions/services/Providers.js#L69
Now I know the second part of the condition is a configuration thing.
**The first part should be this:**
`!_.isEmpty(_.find(users, user => user.provider === provider)`
**Instead of this:**
`!_.isEmpty(_.find(users, user => user.provider !== provider)`

**Comment by changalberto** [comment]
@lauriejim yes, I made certain that the emails that I'm using are not already registered. The issue might be what @HorvathDavid described above.

**Comment by lauriejim** [comment]
@HorvathDavid Can you submit a PR to fix it please.

**Comment by HorvathDavid** [comment]
Hi @lauriejim ,
I have made a PR, but disabled it due to I found another related bug.

The bug is when we query the user. I marked the line below:
https://github.com/strapi/strapi/blob/479ab61b6b9e9aabd7a3a83c38e2f47e2bba5539/packages/strapi-plugin-users-permissions/services/Providers.js#L49
The query should look like this:
`{
         where: {email: profile.email
}
        }`

I have a question regarding roles. What should be the role when the user login with Provider? In the current state the user os registered as public, should we change this to authenticated?

Thanks,
David

**Comment by lauriejim** [comment]
@HorvathDavid When you register a new user there is an advanced settings for the role to link.
It' here for local register https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L246

You have to set the same thing for providers register (use `default_role`)

**Comment by zhuang17** [comment]
Hi @lauriejim , @HorvathDavid 
is there any document on how to use global.strapi or global.strapi.query ?

I've met the same issue as @HorvathDavid mentioned here.  
[strapi/packages/strapi-plugin-users-permissions/services/Providers.js Line 49](https://github.com/strapi/strapi/blob/479ab61b6b9e9aabd7a3a83c38e2f47e2bba5539/packages/strapi-plugin-users-permissions/services/Providers.js#L49)

The email filter don't work and will always return all users, 
this will cause the `Auth.form.error.email.taken` error even for new email registration.

```js
await strapi.query('user', 'users-permissions').find({ email: profile.email });

// only change to `{ where: {email: profile.email } }` will work
// or findOne without where, but i guess we actually need to find All here, so we need to use find()
```

**Comment by changalberto** [comment]
@HorvathDavid what is the state of this issue? Did you submit a PR for your [fix](https://github.com/HorvathDavid/strapi/commit/00eba760dcbd706e5b7f686462e600c7f5f6a5c4) yet =)?

**Comment by lauriejim** [comment]
@zhuang17 Query or in `/config/queries/` folder of the plugin. After it will use bookshelf or mongoose file depending of the database you use. We haven't doc about that.

Some one can try with latest version of Strapi (`alpha.12.0.1`) and clean database and tell me if it's still happened. (mongodb and mysql)

**Comment by lauriejim** [comment]
@HorvathDavid and @changalberto any update about this issue please.

**Comment by lauriejim** [comment]
Will reopen this issue if it persist on last version of Strapi.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by chan-fullstack** [comment]
@gvr37leo Did you find a solution for this?

> i think i just ran into this bug using discord oath {"data":null,"error":{"status":400,"name":"ApplicationError","message":"Email was not available.","details":{}}}
> 
> i'm on strapi 4.0.7 seems kind of random because a lot of users signed up on my website already, but one person ran into this issue. for him changing his discord email address and trying again solved the issue. after that he changed it back and now that email address works fine. weird

**Comment by gvr37leo** [comment]
unfortunately not


Op di 6 sep. 2022 om 20:28 schreef Chan Fullstack ***@***.***
