### ISSUE TITLE
Strapi --quickstart not working, sqlite3 error

### ISSUE THREAD

**Issue by MotaZor94** [strapi/strapi#9080]
Hello everyone,

I am trying to install Strapi for a new project locally, but it stops on sqlite3 installation.

I've tried reinstalling sqlite3 with npm uninstall and tried to do a fresh installation but it fails every time.

This is also 4th time that I'm doing a fresh installation of Strapi but it's not working.

Could anyone see anything interesting in this error log that might help?

Herre is the error log:

`
> sqlite3@5.0.1 install /Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/markocolic/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/markocolic/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/markocolic/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Users/markocolic/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/markocolic/Desktop/Projects/AENONA-CMS/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm WARN @buffetjs/utils@3.3.3 requires a peer of yup@^0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN strapi-connector-bookshelf@3.4.1 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
`

I'm running  node v14.15.0 and my npm is 6.14.9

**Comment by Caligulaa** [comment]
+1

**Comment by Caligulaa** [comment]
changing my sqllite version in the package jsonf rom latest to a specific issues fixed my issue!

**Comment by MotaZor94** [comment]
Which version did you use?

**Comment by ergo123** [comment]
Latest sqlite version (5.0.1) was released a few days ago and it causes the described error. It looks like unavailability of this file is the issue: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz

5.0.0 worked for me.

**Comment by MotaZor94** [comment]
Thanks everyone

**Comment by avalgott** [comment]
I was experimenting the same issue and downgrading node to v10.19.0 fixed it.

**Comment by derrickmehaffy** [comment]
> Latest sqlite version (5.0.1) was released a few days ago and it causes the described error. It looks like unavailability of this file is the issue: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
> 
> 5.0.0 worked for me.

Thank you

Related issue: https://github.com/strapi/strapi/issues/9120

**Comment by langarus** [comment]
> Latest sqlite version (5.0.1) was released a few days ago and it causes the described error. It looks like unavailability of this file is the issue: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
> 
> 5.0.0 worked for me.

Thank you, saved my life

**Comment by endashawdemsis** [comment]
> Latest sqlite version (5.0.1) was released a few days ago and it causes the described error. It looks like unavailability of this file is the issue: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
> 
> 5.0.0 worked for me.

Thank you, changing "sqlite3": "latest" => "5.0.0" worked for me

**Comment by dominicdaviescodes** [comment]
in package.json changed "sqlite3": "latest"  to "sqlite3": "5.0.0" 

Thanks everyone in this thread.

**Comment by EugeneLevchenya** [comment]
You can install nvm, then install Node 12.13.0 or run 'yarn add sqlite3@5.0.0'. Both work well, but the first one is better when the sqlite3 is a part of the npm package you want to install

**Comment by trangchongcheng** [comment]
> Latest sqlite version (5.0.1) was released a few days ago and it causes the described error. It looks like unavailability of this file is the issue: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
> 
> 5.0.0 worked for me.

perfect, i currently it working...thank so much.

**Comment by alpakaxaxa** [comment]
I am trying to run strapi on a Raspberry Pi 4 development server running ubuntu arm64.

Unfortunately, the sqlite3@5.0.0 workaround does not fix my issue. I have the following error message after trying to create a quickstart project with npx:

732 silly saveTree   ├── strapi-generate-plugin@3.6.8
732 silly saveTree   ├── strapi-generate-policy@3.6.8
732 silly saveTree   └── strapi-generate-service@3.6.8
733 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
734 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
735 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
735 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
735 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
735 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64
736 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
737 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64
739 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
740 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
741 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
741 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
741 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
741 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64
742 warn bootstrap@4.6.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
743 verbose stack Error: sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
743 verbose stack Exit status 1
743 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
743 verbose stack     at EventEmitter.emit (events.js:400:28)
743 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
743 verbose stack     at ChildProcess.emit (events.js:400:28)
743 verbose stack     at maybeClose (internal/child_process.js:1055:16)
743 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
744 verbose pkgid sqlite3@5.0.0
745 verbose cwd /home/ubuntu/insight-project/test/insight-project-backend
746 verbose Linux 5.4.0-1042-raspi
747 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm" "--allow-root"
748 verbose node v14.17.6
749 verbose npm  v6.14.15
750 error code ELIFECYCLE
751 error errno 1
752 error sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
752 error Exit status 1
753 error Failed at the sqlite3@5.0.0 install script.
753 error This is probably not a problem with npm. There is likely additional logging output above.
754 verbose exit [ 1, true ]

package.json
{
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.6.8",
    "strapi-admin": "3.6.8",
    "strapi-utils": "3.6.8",
    "strapi-plugin-content-type-builder": "3.6.8",
    "strapi-plugin-content-manager": "3.6.8",
    "strapi-plugin-users-permissions": "3.6.8",
    "strapi-plugin-email": "3.6.8",
    "strapi-plugin-upload": "3.6.8",
    "strapi-plugin-i18n": "3.6.8",
    "strapi-connector-bookshelf": "3.6.8",
    "knex": "0.21.18",
    "sqlite3": "5.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "770dc1dc-e333-440f-83f2-09393cf8fe5b"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}

I am sad that I am having such a hard time getting Strapi to work on the Raspberry Pi.

Any advice would be much appreciated.

**Comment by atakanzen** [comment]
If anyone else is still getting this error (Specially if you are a M1 Mac user) please check whether your machine has python2 or not. In my case, this was the main problem. `sqlite3` is using python2 for installation process and if you have python3 it won't work.
