### ISSUE TITLE
Strapi different models of the object with relationships

### ISSUE THREAD

**Issue by CtFelix** [strapi/strapi#9081]
I have a problem with model in relationship

I have Cities and Buildings in Cities

Relationship settings: 
City belongs to many Buildings 
City has many Buildings

In cities API i see

```
{
    id: 1,
    city_name: "Chicago",       

    building: {
        id: 3,
        building_name: "SomeBuilding in City",          
        city: 1
        }
}
```
In Building API i see

```
{
    id: 3,
    building_name: "SomeBuilding in City",      

    citys: [
        {
            id: 1,
            name: "Chicago",                
            building: 3
        }
        ]
}
```
Why in cities api in the building model city is only ID of city But in Buildings api city is model of city?

And how to make api of cities looks like example, witch full information about city in building model

example cities API
```

{
    id: 1,
    city_name: "Chicago",       

    building: {
        id: 3,
        building_name: "SomeBuilding in City",          
        
        citys: [
            {
                id: 1,
                name: "Chicago",                    
                building: 3
            ]
            }
    }
}
```

### System
- Strapi version:  v3.4.1 
- Database: MySQL
- Operating system: Usuntu

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by CtFelix** [comment]
I was create topic on the forum, but there is no one answered to me :(

**Comment by derrickmehaffy** [comment]
@CtFelix can you link the forum thread? (If you auto-link issues in a forum thread our bot will auto link it here)

**Comment by CtFelix** [comment]
https://forum.strapi.io/t/different-models-of-the-object-with-relationships/2074

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/different-models-of-the-object-with-relationships/2074/3

**Comment by Hellomik2002** [comment]
is there any info in the strapi docs?
