### ISSUE TITLE
Create a webhook for a specific collection...

### ISSUE THREAD

**Issue by philnind** [strapi/strapi#9083]
Is there a way to create a webhook for each collection?

I am running a Strapi instance to run the backend of 2 sites. One main site which uses the collections posts for the blog. And a further collection of buttons to manage a separate links page (like link Tree)

Deployed with netlify using a webhook.

I don’t want to rebuild the entire website if I update the buttons and visa versa for the blog posts.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
