### ISSUE TITLE
Can't migrate from sqlite3 to mongodb

### ISSUE THREAD

**Issue by dertrockx** [strapi/strapi#9084]
So far the only resources I found talked about setting up mongodb with strapi upon creating a project, but I haven't seen anything on how to migrate from sqlite3 to mongodb ( local and/or atlas connection )

My question is, how do you do so? Thanks

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
