### ISSUE TITLE
package-lock.json should not be ignored in plugin template

### ISSUE THREAD

**Issue by viters** [strapi/strapi#9090]
### Describe the bug

`package-lock.json` is included in gitignore template in `strapi-generate-plugin` package.
https://github.com/strapi/strapi/blob/master/packages/strapi-generate-plugin/templates/gitignore

### Expected behavior

`package-lock.json` is intended to be committed therefore it should not appear in gitignore by default.

**Comment by derrickmehaffy** [comment]
We will leave this to the users, generally speaking I do not agree it should be committed, and for the most part we recommend using yarn over npm.

Marking as closed, as this isn't breaking and the user can easily modify should they wish to commit it.
