### ISSUE TITLE
 npx create-strapi-app quickstart/Mac install errors

### ISSUE THREAD

**Issue by electroheadfx** [strapi/strapi#9091]
hey, 

I started to create the strapi, but I have error with dependencies and sqlite,

any idea ? : https://gist.github.com/electroheadfx/0c4cdaed7d04ea01e98b47c12ca47b6f

thanks

## Bug report

Error during npx install

### Steps to reproduce the behavior

npx create-strapi-app first-strapi-app2 --quickstart

### Code snippets

https://gist.github.com/electroheadfx/0c4cdaed7d04ea01e98b47c12ca47b6f

### System

- Node.js version: v14.15.1
- NPM version: 6.14.9
- Strapi version: create-strapi-app
- Database: -
- Operating system: macOS High Sierra 10.13.6

**Comment by alexandrebodin** [comment]
Hi, it seems you don't have build tools like make to build one of the dependencies for image processing :) On mac they can be installed with an xcode util easily. https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/
Once done retry & let me know if this fixed it for you :)

**Comment by electroheadfx** [comment]
yes you are right, and most I have not recent system to install last build tool. Thanks for now you can close ticket. Thanks

make: error: unable to find utility "make", not a developer tool or in PATH
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk" cannot be located.
clang: error: unable to find utility "clang", not a developer tool or in PATH

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

**Comment by electroheadfx** [comment]
Hey, I updated OS newer, and software, no way, I got this error with sqlite :

**Comment by electroheadfx** [comment]
Hey, I updated OS newer, and software, no way, I got this error with sqlite :
https://gist.github.com/electroheadfx/74be96916ee4ff2a4c7a2b15b8f553e1

**Comment by derrickmehaffy** [comment]
> Hey, I updated OS newer, and software, no way, I got this error with sqlite :
> https://gist.github.com/electroheadfx/74be96916ee4ff2a4c7a2b15b8f553e1

Just to confirm, you aren't on the new M1 Mac are you?

**Comment by electroheadfx** [comment]
Hey Derrick, no, Iam on i7 intel mac (macbook pro early 2013), I dont know what happen but something is broken, I tried to compile with node v14.15 node v12.2, no way :(

**Comment by derrickmehaffy** [comment]
Based on your error, you have some outdated build-tools such as libtool: https://github.com/nodejs/node/issues/2341#issuecomment-129387803

**Comment by electroheadfx** [comment]
Hey Derrick, great from you, it worked now, MAMP was using his libtool version (older) instead newer from system (/usr/bin/libtool), I removed MAMP link from .bash_profile and done !

**Comment by ZabdielSeg** [comment]
> > Hey, I updated OS newer, and software, no way, I got this error with sqlite :
> > https://gist.github.com/electroheadfx/74be96916ee4ff2a4c7a2b15b8f553e1
> 
> Just to confirm, you aren't on the new M1 Mac are you?

Hey! What if I have an M1 pro apple chip? I follwed the instructions and does not work on my mac :(
