### ISSUE TITLE
Unable to run on Termux

### ISSUE THREAD

**Issue by mrfoxie** [strapi/strapi#9096]
I'm trying to run `npx create-strapi-app siddh --quickstart` on my termux I install latest version of npm and npx `6.14.10` on my termux but when I run `npx create-strapi-app siddh --quickstart` I get this error 
```
$ npx create-strapi-app siddh --quickstart
npx: installed 92 in 46.808s
The "file" argument must be of type string. Received undefined
```
![Screenshot_20210111_230210.jpg](https://user-images.githubusercontent.com/25217451/104217179-13761a00-5461-11eb-9d93-92067559d360.jpg)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
