### ISSUE TITLE
"Enable sort on this field" is getting reset after restart

### ISSUE THREAD

**Issue by Naxos84** [strapi/strapi#9099]
### Describe the bug

Version 3.4.0 introduced the feature to have relational fields in the list view. Additionally these fields can be configured to be sortable. (This can be done either manually from strapi UI or with the provided migration script (that enables sorting for possible relational fields) ).
After enabling the sort option for a field (in development mode) it works.
But then after shutting strapi down and starting it again the option is disabled again.
This is also the case if the migration script for v3.4.0 is used since the script is run when strapi is not running (and has to be started to check the feature)

To be clear about the migration script: I ran the script after upgrading my strapi and then checked the DB manually. All possible fields were updated (in core table).

### Steps to reproduce the behavior

1. Create a new strapi project with 2 Contenttypes (Author and Book for example)
    Add relation between them (Author has many Books for example).
    Enable sorting for the author field in contenttype Book.
OR
1. Have an existing project that has relational fields between Contenttypes.
    Run the migration script for v3.4.0.
2. Shut down strapi
3. Start strapi again
4. check the sorting feature for the author field.

### Expected behavior

A shutdown/restart shouldn't overwrite any configuration made in the database.

### System

- Node.js version: v12.16.0
- NPM version: 6.13.4
- Strapi version: 3.4.1 
- Database: sqlite
- Operating system: Windows 10

### Additional context
I added some logs to the migration script to see wether I've done something wrong about my strapi setup.
The log cleary showed me that some fields were updated. `conf.metadatas[assoc.alias].list.sortable = true;`
No errors were logged during script execution.

If anything is unclear or additional information is needed please let me know.

**Comment by derrickmehaffy** [comment]
@Naxos84 can you try updating to v3.4.1, I don't believe any of the fixes directly targeted this, but wondering if indirectly.

**Comment by Naxos84** [comment]
As you can see in my versions I'm already using 3.4.1.

I just mentioned 3.4.0 since this feature was introduced with that version.

**Comment by derrickmehaffy** [comment]
> As you can see in my versions I'm already using 3.4.1.
> 
> I just mentioned 3.4.0 since this feature was introduced with that version.

Ah your right, sorry brain not firing on all pistons today :sweat_smile: I'll try and reproduce

**Comment by derrickmehaffy** [comment]
Confirmed on v3.4.2, even using the migration script did not enable sorting on the field. 

Note that sorting only is only able to be enabled on the "one" sides of a relation in my example I have "An author has many books" or a oneToMany:

![image](https://user-images.githubusercontent.com/8593673/104455895-296d0300-5565-11eb-95dd-c7d7568d25be.png)

**Comment by derrickmehaffy** [comment]
https://www.loom.com/share/002a6351d53d4abfa7a6373b89c4dd58

**Comment by Naxos84** [comment]
Do you already have a version where this fix will be present?

**Comment by derrickmehaffy** [comment]
@Naxos84 v3.4.5 has this fix: https://github.com/strapi/strapi/pull/9115

**Comment by Naxos84** [comment]
Thank you. I just asked because I couldn't find it on https://github.com/strapi/strapi/releases/tag/v3.4.5

I'll update and check it again as soon as possible.
