### ISSUE TITLE
INT based users ID conflicts with users-permissions users

### ISSUE THREAD

**Issue by sundowndev** [strapi/strapi#9100]
### Describe the bug

When creating a policy to verify if the creator of an entry was the actual user, I noticed the policy wrongly allowed access because the ID of the current user was the same as the admin user (who created the entry).

### Steps to reproduce the behavior

1. Create an entry from the admin panel
2. Create a non-admin user with role authenticated and permission to access model A with policy (code snippet below)
2. Login as a non-admin user
3. Make a request to the newly created resource

### Expected behavior

Policy to disallow user to access resource since it's not the creator/owner of the resource.

### Screenshots

![image](https://user-images.githubusercontent.com/16480203/104286911-245d7480-54cf-11eb-9cd6-95e7eed6a002.png)

![image](https://user-images.githubusercontent.com/16480203/104286946-2e7f7300-54cf-11eb-87a3-9f944dd369c0.png)

### Code snippets

policy: 

```js
module.exports = async (ctx, next) => {
  if (ctx.params.id) {
    const e = await strapi.query('model').findOne({id: ctx.params.id, created_by: ctx.state.user.id})

    if (!e) {
      return ctx.unauthorized(`error`);
    }
  }

  return await next();
};

```

### System

- Node.js version: v12.19.0
- NPM version: 6.14.8
- Strapi version: 3.4.1
- Database: postgres 13
- Operating system: Ubuntu 20 LTS

Proper solution would be to support UUID as primary key, this is a must have IMO.

**Comment by alexandrebodin** [comment]
Hello @sundowndev, you can detect if a user is an admin by checking this `ctx.state.isAuthenticatedAdmin` boolean.

**Comment by sundowndev** [comment]
@alexandrebodin thanks for that, but how would I know that ID 2 points to an admin user ?

**Comment by alexandrebodin** [comment]
Just checking at an ID you can't decide the type of an object whatever the ID type (uuid or not) you would still need to check the type in your policy via another property :). 
In strapi the authentication middlewares use different keys to create the auth tokens so we know the token was generated for an admin or a users-permissions user in our policies & we can fetch the right model in db.

**Comment by sundowndev** [comment]
> Unique Ids would help but would require making db queries for each user model randomly until we match the one corresponding so we would certainly keep the above method to decide earlier in the request stack

You could simply use different routes for admin and users-permissions users, couldn't you ?

**Comment by alexandrebodin** [comment]
The login routes are already different :) I'm talking about stateless authentication with jwt tokens :) Why not use the `ctx.state.isAuthenticatedAdmin` to check if the user is an admin ?

**Comment by sundowndev** [comment]
> The login routes are already different :) I'm talking about stateless authentication with jwt tokens :) Why not use the `ctx.state.isAuthenticatedAdmin` to check if the user is an admin ?

Because I want to allow non-admin users to access resources they own, not just admins. Also I don't find any docs about that `isAuthenticatedAdmin` property and my tests shows it's undefined. Is that a beta feature ?

**Comment by aksdevac** [comment]
How can you call it conflict if admin users are stored in different table, you can't expect id to be unique between different table/collections.

**Comment by derrickmehaffy** [comment]
@sundowndev What I suggest is we move this convo over to our [forum](https://forum.strapi.io) to discuss work arounds that would fit your use-case. There are other ways to validate users than their ID.

As @aksdevac mentioned, the `users-permissions` => users and `strapi-admin` => users are not the same and come from different packages for different purposes. The auto incremental id is based on the table (and isn't even controlled by Strapi, we just build the DB schema and the database itself assigns the ID, it's not a good practice to do ID generation in the application, especially at scale)

I'm going to mark as closed, but please do open a forum thread and link this issue on it and I'd be happy to continue the discussion there.

**Comment by sundowndev** [comment]
> How can you call it conflict if admin users are stored in different table, you can't expect id to be unique between different table/collections.

That's the purpose of UUID.

> What I suggest is we move this convo over to our [forum](https://forum.strapi.io) to discuss work arounds that would fit your use-case. There are other ways to validate users than their ID.
> 
> As @aksdevac mentioned, the `users-permissions` => users and `strapi-admin` => users are not the same and come from different packages for different purposes. The auto incremental id is based on the table (and isn't even controlled by Strapi, we just build the DB schema and the database itself assigns the ID, it's not a good practice to do ID generation in the application, especially at scale)
> 
> I'm going to mark as closed, but please do open a forum thread and link this issue on it and I'd be happy to continue the discussion there.

I know users-permissions users and admin users are not from the same plugin so it makes sense to put them in different tables. But the default "created_by" and "updated_by" fields in every collection make everything confusing, as it is set automatically when using the Strapi admin panel, but not when using the API. Documentation suggests we should use a custom field (e.g: author) to check who created the entry. But may be I'm missing something in the design. I'll open a thread on the forum later.
