### ISSUE TITLE
You first need to select actions (create, read, update, ...) before defining conditions on them.

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#9102]
Editing a Role (Define the rights given to the role), I'm facing the above message when clicking "Settings" under both Plugins and Settings. What am I supposed to do with this information? Where do I "select actions ..." before "defining conditions" on them?

This is NOT very informative, as I have absolutely no clue what you're talking about. I've been all over the application trying to figure out what I have to do PRIOR to enabling features for a role ...

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by blaasvaer** [comment]
Why don’t you prepopulate an issue with a template then?

**Comment by derrickmehaffy** [comment]
> Why don’t you prepopulate an issue with a template then?

We do, and in fact we strictly set "no empty issues":

https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

https://github.com/strapi/strapi/blob/368a789e06ae515b5caedb65d51224fc488db81d/.github/ISSUE_TEMPLATE/config.yml#L1

![image](https://user-images.githubusercontent.com/8593673/104429252-a5a21f00-5542-11eb-9f06-585d1a9f312c.png)

https://github.com/strapi/strapi/issues/new?assignees=&labels=&template=BUG_REPORT.md

**Comment by blaasvaer** [comment]
Well, the issue was empty when I created it. So, something was not working properly, I guess.

**Comment by derrickmehaffy** [comment]
:shrug: Up to you, if you want to edit your original post I can mark the other replies as outdated or if you want to try opening a new issue instead. We do need to have the template though please, even for the small stuff.

Thank you :heart:
