### ISSUE TITLE
Can't use GraphQL in a Heroku

### ISSUE THREAD

**Issue by BaptisteMonet** [strapi/strapi#9105]
### Trying to access /graphql via heroku instance

My goal was simply to access to http://www.host.com/graphql after deploy my strapi application via heroku

### Expected behavior
Try to access /graphql endpoint after setup graphql on heroku even if graphql server parameters was affected

### Code snippets

here you can find the parameters from config/plugin.js
```
module.exports = ({ env }) => ({
  
  graphql: {
    endpoint: '/graphql',
    shadowCRUD: true,
    playgroundAlways: true,
    depthLimit: 7,
    amountLimit: 100,
    introspection: true,
    apolloServer: {
      tracing: false,
    },
  },
});
```

### System

```
 "dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.5.1",
    "sqlite3": "latest",
    "strapi": "3.4.1",
    "strapi-admin": "3.4.1",
    "strapi-connector-bookshelf": "3.4.1",
    "strapi-plugin-content-manager": "3.4.1",
    "strapi-plugin-content-type-builder": "3.4.1",
    "strapi-plugin-email": "3.4.1",
    "strapi-plugin-graphql": "3.4.1",
    "strapi-plugin-upload": "3.4.1",
    "strapi-plugin-users-permissions": "3.4.1",
    "strapi-utils": "3.4.1"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
```
- Database: postgresql

**Comment by derrickmehaffy** [comment]
Tested on a fresh v3.4.1 project and am unable to reproduce the issue: 
![image](https://user-images.githubusercontent.com/8593673/104439879-e011b900-554e-11eb-9ecf-ac057de167fd.png)

@BaptisteMonet can you please provide reproduction steps?

**Comment by BaptisteMonet** [comment]
@derrickmehaffy  ok if it works for you I got a problem on my side
![omy](https://user-images.githubusercontent.com/53108208/104451105-622acd80-55a1-11eb-9e68-650cc24fe294.PNG)


some log from heroku:
`2021-01-13T12:16:21.327713+00:00 heroku[router]: at=info method=GET path="/graphql" host=stj-api.herokuapp.com request_id=150d799c-3f06-4fac-86a3-e2a8881331ca fwd="91.168.104.73" dyno=web.1 connect=2ms service=54ms status=400 bytes=327 protocol=https

2021-01-13T12:16:21.317151+00:00 app[web.1]: [2021-01-13T12:16:21.317Z] debug GET /graphql (34 ms) 400`

**Comment by derrickmehaffy** [comment]
It seems your setting in the plugins.js file isn't taking effect as thats the default for GraphQL playground in production (doesn't exist)

Ahhh here is the problem
> here you can find the parameters from config/plugin.js

It needs to be `./config/plugins.js` not `./config/plugin.js`

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/developer-docs/latest/plugins/graphql.html#configurations

> Path — ./config/plugins.js

**Comment by BaptisteMonet** [comment]
can you show me a picture of your folder ?
not sure to understand where the config folder start.
here is mine
![folder](https://user-images.githubusercontent.com/53108208/104455871-319a6200-55a8-11eb-8842-eafe6a1be422.PNG)

**Comment by derrickmehaffy** [comment]
I'm using the `./config/env/production/plugins.js` but `./config/plugins.js` also works (the env folder is optional but you should be using it with Heroku per our docs)

![image](https://user-images.githubusercontent.com/8593673/104457155-e4e26700-5566-11eb-99e1-9d9ded03d076.png)

**Comment by derrickmehaffy** [comment]
Also sorry, I'm a linux user so the `./` is a common path expression meaning "current folder"

**Comment by MSid01** [comment]
**Note**: It is changed from graphql to graphql.config
``` javascript
module.exports = {
    graphql: {
      config: {
        endpoint: '/graphql',
        shadowCRUD: true,
        playgroundAlways: true,
        depthLimit: 7,
        amountLimit: 100,
        apolloServer: {
          tracing: false,
        },
      },
    },
  };
```

**Comment by TOPAiiN** [comment]
> **Note**: It is changed from graphql to graphql.config
> 
> ```js
> module.exports = {
>     graphql: {
>       config: {
>         endpoint: '/graphql',
>         shadowCRUD: true,
>         playgroundAlways: true,
>         depthLimit: 7,
>         amountLimit: 100,
>         apolloServer: {
>           tracing: false,
>         },
>       },
>     },
>   };
> ```

Thanks! this is allowing me to see the GraphQL playground but I am getting a 400 once opened. 
![Screen Shot 2022-03-16 at 13 59 53](https://user-images.githubusercontent.com/69760923/158646024-d8d886ec-99ce-4885-b19c-4dfcc0423f0b.png)

Will keep trying and post any solution here.

**Comment by mmgolden** [comment]
I was able to fix this by changing the apollo server options to `inspection: true`. It gets turned off for production.

```
// ./config/env/production/plugins.js
module.exports = {
  graphql: {
    config: {
      endpoint: '/graphql',
      shadowCRUD: true,
      playgroundAlways: true,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
        introspection: true,
      },
    },
  },
};
```
