### ISSUE TITLE
Strapi Admin Panel loads very slow and causing r13 error on heroku

### ISSUE THREAD

**Issue by kevinvugts** [strapi/strapi#9108]
## Bug report

The strapi admin load takes more than 30 seconds. This is causing an [R13](https://devcenter.heroku.com/articles/request-timeout) error when deploying the admin panel to Heroku.

### Steps to reproduce the behavior

1. Install latest version of strapi
2. Push it to heroku
3. Wait some seconds
4. See error r13 (cause admin panel is loading very slow)

### Expected behavior

I would expect that the Strapi panel would load fast as it did in previous versions. The problem started to occur in new versions of Strapi. 

### Screenshots

`heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/admin/main.58220886.chunk.js" host=trekhaak-labels-api-staging.herokuapp.com request_id=9980e0b2-d207-4736-93eb-a8d3cd193cb0 fwd="91.198.27.90" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https`

### Code snippets

See error message above.

### System

- Node.js version: v12.18.3
- NPM version: v6.14.7
- Strapi version: 3.4.1
- Database: Mongo Db hosted on atlas
- Operating system: macos

### Additional context

Setup of my config: (these shared for all environments)

**Database**

```module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: env('DATABASE_CONNECTOR', 'mongoose'),
      settings: {
        client: env('DATABASE_CLIENT', 'mongo'),
        uri: env('DATABASE_URI'),
      },
      options: {
        useNullAsDefault: true,
        authenticationDatabase: env('AUTHENTICATION_DATABASE', ''),
        ssl: env.bool('DATABASE_SSL', true),
      }
    }
  }
});
```

**Server**
```module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: process.env.PORT || 1337,
  url: env('SERVER_URL', 'http://localhost:1337'),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'blablabla'),
    },
  },
});```

**Comment by derrickmehaffy** [comment]
@kevinvugts can you share your `./config/*/middleware.js` file if you have one? If you don't you might need to disable compression:

https://strapi.io/documentation/developer-docs/latest/concepts/middlewares.html#response-middlewares

Specifically see the note below about Brotli

**Comment by mikadze** [comment]
@derrickmehaffy I have the same issue. https://sovsekretno.tv/apis/admin it takes 1.5min + to load the login page.

current middleware config: 
`module.exports = {
  settings: {
    gzip: {
      enabled: true,
      options: {
        br: {
          params: {
            [zlib.constants.BROTLI_PARAM_MODE]: zlib.constants.BROTLI_MODE_TEXT,
            [zlib.constants.BROTLI_PARAM_QUALITY]: 4,
          },
        },
      },
    },
  },
};`

Also have tried disabling Brotli with br: false, but no help :(

**Comment by derrickmehaffy** [comment]
Can you try disabling gzip entirely?

**Comment by mikadze** [comment]
> Can you try disabling gzip entirely?

Yes I did try `gzip: { enabled: false }` no effect.

I had it hosted few weeks ago on  digitalocean and it worked fine, but today I hosted it on a dedicated machine with more resources and now it is slow. All configs are the same.

**Comment by sagenate24** [comment]
@mikadze I had the same issue today and the following fixed it for me:

`gzip: {
      enabled: true,
      options: {
        br: false
      }
    },`

**Comment by kevinvugts** [comment]
Thank you @sagenate24 and @derrickmehaffy, I disabled brotli in the gzip configuation and it worked instantaniously. Closisng this of now.
