### ISSUE TITLE
strapi is not installing with yarn and npx

### ISSUE THREAD

**Issue by hamzaamughal** [strapi/strapi#9111]
![srapi](https://user-images.githubusercontent.com/66194492/104416821-41a94600-5596-11eb-9b14-02c3e539259a.PNG)
with npx it says sqlite is not installed. try again

**Comment by gondar00** [comment]
It feels like it is due to the space between `Hamza Mughal`, try installing it at a different path by creating a new folder like `C:\Users\strapi`

**Comment by alexandrebodin** [comment]
Hi, from what I can see yarn is not happy with your \Users folder containing a space and ignors the name. You can try to create a folder without spaces first in which you will run the same command.

**Comment by hamzaamughal** [comment]
> It feels like it is due to the space between `Hamza Mughal`, try installing it at a different path by creating a new folder like `C:\Users\strapi`

**Comment by hamzaamughal** [comment]
not solved

**Comment by hamzaamughal** [comment]
not solved

**Comment by Sambhrama754** [comment]
Just don't start project name with capital letters

**Comment by Sambhrama754** [comment]
Pls try

**Comment by derrickmehaffy** [comment]
We need more information, please provide more steps to reproduce then we can reopen the issue.
