### ISSUE TITLE
TypeError: d.toISOString is not a function

### ISSUE THREAD

**Issue by avanwieringen-sensus** [strapi/strapi#9116]
### Describe the bug

I've created a Single Type with a `datetime` field. When trying to fill the it with data and save I get an error in the JS console saying `TypeError: d.toISOString` is not a function.

This is from a fresh install.

### Steps to reproduce the behavior

1. Create a new Content-Type
2. Add a field with type `datetime`
3. Finalize the Content-Type
4. Add new content and fill the date and time via the popup pickers
5. Press save
6. Error

### Expected behavior

I can save my content type

### Screenshots

See attached screenshots.
![Screenshot 2021-01-13 at 16 49 01](https://user-images.githubusercontent.com/75974534/104475431-64038980-55bf-11eb-961a-bc546ea11e9c.png)
![Screenshot 2021-01-13 at 16 49 12](https://user-images.githubusercontent.com/75974534/104475434-6534b680-55bf-11eb-87eb-e02fb46862d1.png)
![Screenshot 2021-01-13 at 16 49 18](https://user-images.githubusercontent.com/75974534/104475438-6534b680-55bf-11eb-9a0c-a27e1caea34c.png)
![Screenshot 2021-01-13 at 16 49 21](https://user-images.githubusercontent.com/75974534/104475442-65cd4d00-55bf-11eb-93d0-469d11e99a8a.png)
![Screenshot 2021-01-13 at 16 49 26](https://user-images.githubusercontent.com/75974534/104475444-6665e380-55bf-11eb-9ef8-8f4e542e034d.png)
![Screenshot 2021-01-13 at 16 49 39](https://user-images.githubusercontent.com/75974534/104475446-6665e380-55bf-11eb-9051-1aeabbc797ec.png)
![Screenshot 2021-01-13 at 16 49 50](https://user-images.githubusercontent.com/75974534/104475450-66fe7a00-55bf-11eb-8475-c9ab91e91585.png)

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: 3.4.2
- Database: MySQL
- Operating system: MacOS Big Sur 11.1

**Comment by emmanuelkant** [comment]
Exactly the same problem here.

**Comment by aldidas** [comment]
I got this too. Downgrading to 3.4.1 fixes the bug for now.

**Comment by Zielgestalt** [comment]
Same here.

**Comment by eugeneingram** [comment]
@soupette  Any idea when this fix will find its way into the strapi/strapi Docker image?  I'm just starting out with Strapi and was dismayed when my first attempt at creating a content type resulted in something that wouldn't allow saving of content because I'd used a date field.

**Comment by avanwieringen-sensus** [comment]
I see that 3.4.3 fixes this.

**Comment by avanwieringen-sensus** [comment]
I can confirm that it works again

**Comment by emmanuelkant** [comment]
I got the [3.4.3](https://github.com/strapi/strapi/releases/tag/v3.4.3) and the problem was solved!

**Comment by soupette** [comment]
I am closing this issue then.
