### ISSUE TITLE
Migrating 3.4.2 Limit at 100 entries plugin-content-manager 

### ISSUE THREAD

**Issue by JulienVerkest** [strapi/strapi#9117]
## Bug report
Bonjour, 

Je viens de procéder à une mise à jour de la v3.4.1 à la v3.4.2 et je ne retrouve plus mes petits. Je m'explique : j'avais auparavant 600 entrées pour mon model `page` et je me retrouve avec 100 entrées trouvées  sur la page `plugins/content-manager/collectionType/application::page.page`.  
En consultant ma base de données (mongodb) je constate que j'ai toujours mes 600 documents. 

En effectuant un rollback vers la v3.4.1 j'ai de nouveau mes 600 entrées affichées sur la page de listing pour mon model `page`

P.S. je pense avoir suivi correctement le guide de migration (et j'ai même désactivé mon layout custom) mais rien n'y fait. 

Merci d'avance à vous. 

### System

- Strapi version: 3.4.2
- Database: Mongoose

**Comment by petersg83** [comment]
Hi, I was able to reproduce it yes. Thank you! Working on it
