### ISSUE TITLE
cors enabled does not seem to disable cors

### ISSUE THREAD

**Issue by ddennis** [strapi/strapi#9127]
### Describe the bug
I am using version 3.1.4 (node v12.16.1) 
I would like to disable cors for development, but enable it for production.
I assume this can be done by switching the enabled flag.

in middleware.js
```
settings: {
    cors: {
      enabled: false,
      origin: [
        "https://staging.mydomain.com",
        "https://mydomain.com",
      ],
    },
  },
```

### Steps to reproduce the behavior

1. add a middelware.js inside config
2. npm run develop
3. Do a post request to the strapi server
4. 
```
Access to fetch at 'http://localhost:1337/contactforms' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Expected behavior

Setting enabled to false should disable cors and strapi should behave like there was no middelware.js file

### System

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Thu Jan 14 2021 14:19:42 GMT+0100 (Central Euro… │
│ Launched in        │ 4977 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 6132                                             │
│ Version            │ 3.1.4 (node v12.16.1)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

**Comment by ddennis** [comment]
@derrickmehaffy any wish for how to setup a reproduction. I tried setting up codesandbox but could not create a user.
project view: [codesandbox](https://bicx8.sse.codesandbox.io/admin/auth/register-admin)
project : https://codesandbox.io/s/strapi-cors-bicx8

**Comment by derrickmehaffy** [comment]
>  3.1.4 (node v12.16.1)

Can you please test with a fresh/new project using the latest version (v3.4.4) with an example repo?

**Comment by oneassasin** [comment]
I wrote project and disabling cors doesn't working. how it's can be possible to fix?

**Comment by oneassasin** [comment]
If i send Origin header
http://joxi.ru/brRpzRGTLQxYq2

If i don't send Origin header
http://joxi.ru/a2XGzkEIlyPDBm

Code of configs/middleware.js
http://joxi.ru/Dr8ORkjcJkRzXA

**Comment by derrickmehaffy** [comment]
should work fine in v4
