### ISSUE TITLE
Unable to get user via oAuth vk

### ISSUE THREAD

**Issue by vinkovsky** [strapi/strapi#9136]
Hello!  I am trying to register a user through a VK provider and ran into some problems

  1. If the user does not have an e-mail in the settings of his VKontakte account, the request cannot receive it either.

![image-2.png](https://user-images.githubusercontent.com/66293881/104693267-f3ce4280-573b-11eb-875b-1540c39e988b.png)

  2. If the user first deletes the account and then tries to log in through vk, the strapi server crashes with the following errors.

![image.png](https://user-images.githubusercontent.com/66293881/104693289-f9c42380-573b-11eb-8c71-5a1a06cec0f8.png)

![image-1.png](https://user-images.githubusercontent.com/66293881/104693297-fe88d780-573b-11eb-9f7d-f29fa9595335.png)

Version 3.3.4

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
