### ISSUE TITLE
Request limit of a relation is fixed to 20 in Strapi Admin

### ISSUE THREAD

**Issue by RaphaelWski** [strapi/strapi#9137]
### Describe the bug

I can't display more than 20 items of a relation in Strapi Admin.
The request contains  __limit=20_ and I want to know how to remove it.

### Steps to reproduce the behavior

1. Create a Collection Type Agences
2. Add more than 20 agences
2. Create a component with that collection inside
3. Create another Collection Type with a Dynamic Zone containing that component
4. Create an entry and try to add all available agences
5. See the dropdown is limited to 20

### Expected behavior

Display all the data in the relation's dropdown (more than 20).

### System

- Strapi Version: 3.4.2
- Operating System: Debian
- Database: MySQL
- Node Version: 12.18.2
- NPM Version: 6.14.6

### Additional context
Hi,

I have trouble to display more than 20 items of a relation in Strapi Admin.
We were on version 3.2.5 while we discovered what I will explain, and we’ve migrate to the latest version but it doesn’t change.
I guess there is something I missed so i need help to fix it.

So when I move to the content manager and add some Agences, I’m limited to 20 while I have more agences stored in database
This is because the request limit is fixed to 20

`http://localhost:1337/content-manager/relations/application::page.page/agences?_limit=20&_start=0&_component=pages.carte-interactive`

![link](https://strapi-discourse-prod.s3.dualstack.us-west-2.amazonaws.com/uploads/original/2X/5/595850788cdc69a8050ef8f130740711228a9a34.png)

**I want to know how to change the limit value or remove it from the request.**

Thanks for your help 

[Link to my Strapi Forum post](https://forum.strapi.io/t/request-limit-is-fixed-to-20-in-strapi-admin/2169)

**Comment by petersg83** [comment]
Hi, can you update to 3.4.3 please? A bug related to the count function has been fix in this version. It mays fix the problem you see too.

**Comment by RaphaelWski** [comment]
@petersg83 thanks for your quick response.

It's done but it seems like that doesn't solve my issue.

The request URL is still
`http://localhost:1337/content-manager/relations/application::page.page/agences?_limit=20&_start=0&_component=pages.carte-interactive`

I don't think it's related but for your information, I have a custom _Inputs_ components where I juste add this: 
`import 'moment/locale/fr'`

<img width="143" alt="2021-01-15_11h13_38" src="https://user-images.githubusercontent.com/12536139/104712558-fa03f500-5722-11eb-9d19-bff0a02c61c4.png">

**Comment by RaphaelWski** [comment]
Looks weird but i found a similar issue of 2 years here :

https://github.com/strapi/strapi/issues/766

**Comment by petersg83** [comment]
Thank you ! I could reproduce with a one-to-many relation (I didn't need components and dynamic-zones)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/request-limit-is-fixed-to-20-in-strapi-admin/2169/3

**Comment by RaphaelWski** [comment]
@derrickmehaffy I am the one who knocks

**Comment by derrickmehaffy** [comment]
That response was a bot :p whom shares my name

**Comment by LouisLec** [comment]
Hi ! Same issue in v4. Is there an easy way to override the default behavior ? thx !

**Comment by ziayamin** [comment]
Hi! Same issue in v4. Is there any way to solve this? thx!

**Comment by IlyasDiker** [comment]
2022 still the same issue ??

**Comment by petersg83** [comment]
Hello :) We are currently working on relations in the Content-Manager. So it will be fixed at the latest around september.
In the meantime, if you save the entry and edit it again does it work?
It looks like the frontend doesn't send the ids to omit along with the request

**Comment by hgulersen** [comment]
If someone ends up here and needs a quick fix using `patch-package`, the file to edit under node_modules is `node_modules/@strapi/admin/admin/src/content-manager/components/SelectMany/index.js`

Change the `limit` under `initialPaginationState` to the value you like
