### ISSUE TITLE
Cannot convert undefined or null to object.

### ISSUE THREAD

**Issue by azizcoban** [strapi/strapi#9145]
Hello, I was running strapi properly yesterday without any issue. But this morning when I tried to start strapi, with the commands "yarn develop" I got this error and it is not explicit for a better understanding. Can you help me about this ?

> yarn run v1.22.10
$ strapi develop
[2021-01-16T11:39:59.662Z] debug ⛔️ Server wasn't able to start properly.
[2021-01-16T11:39:59.662Z] error TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at checkReservedAttributeNames (/Users/azizcoban/Desktop/persquad-cms/node_modules/strapi-database/lib/validation/check-reserved-names.js:33:60)
    at /Users/azizcoban/Desktop/persquad-cms/node_modules/strapi-database/lib/validation/check-reserved-names.js:62:5
    at Array.forEach (<anonymous>)
    at module.exports (/Users/azizcoban/Desktop/persquad-cms/node_modules/strapi-database/lib/validation/check-reserved-names.js:60:68)
    at validateModelSchemas (/Users/azizcoban/Desktop/persquad-cms/node_modules/strapi-database/lib/validation/index.js:8:3)
    at DatabaseManager.initialize (/Users/azizcoban/Desktop/persquad-cms/node_modules/strapi-database/lib/database-manager.js:34:5)
    at Strapi.load (/Users/azizcoban/Desktop/persquad-cms/node_modules/strapi/lib/Strapi.js:312:19)
    at async Strapi.start (/Users/azizcoban/Desktop/persquad-cms/node_modules/strapi/lib/Strapi.js:191:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by bisubus** [comment]
FWIW, just ran into this error on initialization when accidentally deleting some files from existing API.

**Comment by alex-lushiku** [comment]
If you updated Strapi, go through their migration guides. For me following the guides from beta to the first stable release (3.0.0) solved my problem:
https://strapi.io/documentation/developer-docs/latest/migration-guide/

**Comment by gondar00** [comment]
If anyone stumbles upon this, 

This error comes when you add a file inside config folder, besides the ones mentioned in https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html 

Although adding a folder works fine, but this weird error is given and it makes no sense at all 🗡️

**Comment by pmNiko** [comment]
Me encontre con este error. El problema fue un error que tubo strapi al crear una nueva colección "address" la solución fue borrar la carpeta address/ que se habia creado dentro de la carpeta api de strapi. 
Saludos!

**Comment by derrickmehaffy** [comment]
> Me encontre con este error. El problema fue un error que tubo strapi al crear una nueva colección "address" la solución fue borrar la carpeta address/ que se habia creado dentro de la carpeta api de strapi.
> Saludos!

Hello!

To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms. 

Thank you and have a wonderful day!

**Comment by afpmodelogithub** [comment]
> Me encontre con este error. El problema fue un error que tubo strapi al crear una nueva colección "address" la solución fue borrar la carpeta address/ que se habia creado dentro de la carpeta api de strapi. Saludos!

Gracias.... (thanks)

**Comment by afpmodelogithub** [comment]
> > Me encontre con este error. El problema fue un error que tubo strapi al crear una nueva colección "address" la solución fue borrar la carpeta address/ que se habia creado dentro de la carpeta api de strapi.
> > Saludos!
> 
> Hello!
> 
> To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms.
> 
> Thank you and have a wonderful day!

**Comment by afpmodelogithub** [comment]
PTI [FYI]
Para ser inclusivo para todos en la comunidad:
Porcentaje de la poblacion mundial (2018) [Percentage of world population (2018)]
1	Mandarin Chinese	12.3%
2	Spanish	6.0%
3	English	5.1%

P.D.: No demuestres ignorancia
P.S.: Do not show ignorance

**Comment by afpmodelogithub** [comment]
> > Me encontre con este error. El problema fue un error que tubo strapi al crear una nueva colección "address" la solución fue borrar la carpeta address/ que se habia creado dentro de la carpeta api de strapi.
> > Saludos!
> 
> Hello!
> 
> To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms.
> 
> Thank you and have a wonderful day!

PTI [FYI]
Para ser inclusivo para todos en la comunidad:
Porcentaje de la poblacion mundial (2018) [Percentage of world population (2018)]
1	Mandarin Chinese	12.3%
2	Spanish	6.0%
3	English	5.1%

P.D.: No demuestres ignorancia
P.S.: Do not show ignorance
