### ISSUE TITLE
graphql connection not returning correct results anymore

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#9146]
### Describe the bug

So a bunch of changes to the graphql queries in 3.4.2 and 3.4.3 gave me the following: I have about 700 vehicles in my Strapi. When running this query:
```
query  {
  vehiclesConnection {
    groupBy {
      make {
        key
      }
    }
  }
}
```

I used to get all the makes, but with the latest release, the list is shorter. Playing with the `limit` gave me a hint. I think the `limit` actually limits the amount of `vehicles` that are taking into account. Since I can never seem to limit about `100` in graphql, only the first `100` vehicles are taking into account for finding the `make`. So I get only a subset of all actual available makes in the db.

### Steps to reproduce the behavior

1. Add hundreds of items to a model (vehicles)
2. request the connection in graphql (vehicleConnection)
3. Use the sort to play around with the result set and see that you can actually get a different result, still not being all makes

### Expected behavior

I'd expect to get every single make present in the db with this query

### System

- Node.js version :v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.3
- Database: mongo atlas
- Operating system: macos

### Additional context

Had no problems in 3.4.1

**Comment by derrickmehaffy** [comment]
Related to: https://github.com/strapi/strapi/pull/9020 ?

**Comment by alexandrebodin** [comment]
Hi @laurenskling I am actually having the same behavior in v3.4.1? Can you sahre the graphql config you have for the amountLimit ?

**Comment by laurenskling** [comment]
I don't know what `amountLimit` you are referring to?

So I've created 2 deployments with the same database.
https://exclusieveauto.herokuapp.com/graphql is (currently) running `3.4.1`
https://ea-strapi-3-4-3.herokuapp.com/graphql is running `3.4.3`

Running this query:
```
query  {
  vehiclesConnection(limit: 1) {
    groupBy {
      make {
        key
      }
    }
  }
}
```

will give 16 makes on `3.4.1` and 1 make on `3.4.3`

Which would probably be caused by the limit actually limiting the amount of vehicles to be considered. So 1 vehicle will give you 1 make. 

I can never request over limit 100 in graphql, which is the default when nothing is set. So there is no way for me to request all makes for all 700 vehicles. Because I will get the makes for only the first 100 hits.

**Comment by alexandrebodin** [comment]
The amountLimit is a config of the graphql plugin. that limits byt thefault the entries to 100. https://strapi.io/documentation/developer-docs/latest/plugins/graphql.html#configurations

You can increase it if necessary as a workarround for now

**Comment by laurenskling** [comment]
The workaround works for me, thanks :)

Don't know what to think about the default behaviour yet. Getting a connection limited by its source/relation feels quite weird. You'd expect the results to be limited.

**Comment by alexandrebodin** [comment]
Yeah only filtering would make sense here I think

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/api-efficiency-and-custom-conditions/2426/2

**Comment by michael-proulx** [comment]
I have something similar about that issue, but can't resolve by doing the workaround the Query take too long (~25s) using Gatsby, I have 1.5k Articles and only need 20 by language for exemple.

```
query {
  cms {
    blogArticlesConnection(sort: "publishedDate:desc", limit: 20) {
      groupBy {
        language {
          key
          connection {
            values {
              publishedDate
              slug
            }
          }
        }
      }
    }
  }
}
```

The argument limit, will limit the number of groups returned.
So here is an exemple, if I have "en" and "fr" and a limit of 1, I'll get "fr" or "en" etc...
There is no option to limit the one in the group like this.

```
query {
  cms {
    blogArticlesConnection {
      groupBy {
        language {
          key
          connection(sort: "publishedDate:desc", limit: 20) {
            values {
              publishedDate
              slug
            }
          }
        }
      }
    }
  }
}
```

I have tried to overwrite the type in graphql, but it didn't work.

**Comment by sachirjn** [comment]
I am having the same problem. Issue occurs after switching from `mongo 4.2.11` to `4.4.3`. Might have compatibility problems  with sort and limit update on mongo 4.4

**Comment by alexandrebodin** [comment]
right now you can only increase the amountLimit option to work around this. We need to refactor the way connections work to support this correctly

**Comment by derrickmehaffy** [comment]
should be fixed in v4
