### ISSUE TITLE
Request npm package is deprecated

### ISSUE THREAD

**Issue by PritamSangani** [strapi/strapi#9147]
### Describe the issue

This isn't a bug but this issue template is most aligned to the issue. I noticed that a couple of the packages including the main strapi package are still using `request` which has been deprecated since last year. Are there any plans to migrate to an alternative such as `axios` or the native `fetch` API?

**Comment by derrickmehaffy** [comment]
While it doesn't follow a template, you make a good point. 

Thank you, will alert the team and get their thoughts

**Comment by alexandrebodin** [comment]
Hi @PritamSangani  we are only use strapi in one of the plugins because one of our dependencies requires it :) we are hoping it will be removed soon :)

**Comment by kibblerz** [comment]
https://github.com/strapi/strapi/pull/13513

I created this PR, which fixes the issue for me. (While also adding Yarn PnP support without loose mode).

**Comment by derrickmehaffy** [comment]
Still exists in v4

**Comment by derrickmehaffy** [comment]
removed at least as of 4.6.1
