### ISSUE TITLE
GraphQL related queries broken with related objects as draft

### ISSUE THREAD

**Issue by vjagaro** [strapi/strapi#9149]
### Describe the bug

GraphQL queries with draft nested object result in an error when using the MySQL or PostgreSQL client.

```
select distinct `houses`.* from `houses` where `houses`.`id` = {} and (`houses`.`published_at` is not null) limit 1

...ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB...
```

### Steps to reproduce the behavior

1.  Create two collections, e.g., `channel`, `house`.
2.  Add a relation field between the two, e.g., `house` belongs to `channel`.
3.  Create an item in each collection.
4.  Set the publication state on the nested item to draft.
5.  Perform a GraphQL query with the nested object.

    ```graphql
    {
      channels {
        id
        title
        house {
          id
          title
        }
      }
    }
    ```

### Expected behavior

The GraphQL queries work as expected, e.g., would not result in an error. This was working in Strapi version 3.4.1.

### Code snippets

See the example code at https://github.com/vjagaro/strapi-graphql-draft-subobjects-example.

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.4.3 (also an issue in 3.4.2)
- Database: MySQL & PostgreSQL
- Operating system: Linux

### Additional context

SQLite seems to work as expected. In addition, REST queries work as expected for SQLite, MySQL and PostgreSQL.

This may be related to issue #8880.

**Comment by vjagaro** [comment]
This issue is still present in 3.4.4.

**Comment by vjagaro** [comment]
Pinning `strapi-plugin-graphql` to 3.4.1 fixes this issue.

Related #9167.

**Comment by vjagaro** [comment]
This issue is still present in 3.4.5.

**Comment by vjagaro** [comment]
Related #9239.

**Comment by vjagaro** [comment]
This is still an issue with Strapi 3.5.2. Similarly to before, pinning `strapi-plugin-graphql` to 3.4.1 fixes this, but this may cause other problems.

**Comment by finfa** [comment]
Cannot upgrade because of this

**Comment by SalahAdDin** [comment]
Up!

**Comment by monkeymosher** [comment]
Related to [9454](https://github.com/strapi/strapi/issues/9454), still cannot update because if this too.

**Comment by vjagaro** [comment]
This is still a problem with Strapi 3.6.2.

**Comment by Mortalife** [comment]
After some investigation, I managed to get the query to progress as expected with the following change:
`strapi-plugin-graphql/services/shadow-crud.js:243`
```
            if (model.modelType === 'component') {
              obj[alias] = _.get(obj[alias], targetModel.primaryKey, null);
              
              if(_.isNil(obj[alias])) {
                return null;
              }
            }
```
If somebody more familiar with the codebase could confirm that this doesn't impact anything else that would be great.

**Comment by Mortalife** [comment]
Okay, so I went back and actually tested the actual issue reported ahead and came across the same error as reported.

Checking for the empty object in the relationship processing seems to resolve the issue.
`strapi-plugin-graphql/services/shadow-crud.js:270`
```
if (!_.has(obj, alias) || _.isNil(foreignId) || (_.isObject(obj[alias]) && !_.has(obj[alias], targetPK))) {
  return null;
}
```

The code seems to be written with the assumption that the relationship field is either the populated object, an id, or null. When in fact, if the relationship is from a draft, it's an empty object.

**Comment by vjagaro** [comment]
#10320 appears to work for this particular issue but I don't know if the patch would cause other problems.

**Comment by Mortalife** [comment]
As it seems that time to merge is relatively low, and I realise the merge will be into the most recent version which might not be desirable, you can copy the graphql sub-project into your extensions folder with the modified `shadow-crud.js` file and it takes preference over the installed plugin.

![image](https://user-images.githubusercontent.com/14141518/118675474-89650600-b7f2-11eb-9618-1b711c29fdfa.png)

You'll just have to update any CI build steps to also build the plugin.

**Comment by Mortalife** [comment]
The issue appears to originate within the `strapi-bookshelf-connector` as the REST API also returns an empty object for drafts. I'm now running my modifications within a "custom" plugin as such I'm not going to look into this any further and handing it off to anybody else that's interested in resolving the root issue.

**Comment by derrickmehaffy** [comment]
setting as duplicate to https://github.com/strapi/strapi/issues/10574 (since that one had a bit more information)

**Comment by shivprasadsambhare** [comment]
I have found the solution. If any relational field is in draft mode or not available then simply add check for "not null".

Example : 
```
{
  channels(where:{house:{id_null: false}) {
    id
    title
    house {
      id
      title
    }
  }
}
```
