### ISSUE TITLE
Dynamic zones with components that have fields with the same name cause problems

### ISSUE THREAD

**Issue by dalbitresb12** [strapi/strapi#9150]
### Describe the bug

This bug happens whenever a model has a dynamic zone with at least two components. These two components need to have a field named the same, but of a different type (I haven't tried with the same type yet). One of those fields needs to be marked as `required`. What will happen is that Strapi won't accept the data, with the error `Invalid input data. Please verify unique constraints`.

For example, I created a model called `Posts`, with two fields: `title` of type `string` and `sections` of type `dynamiczone`. Then, I created two components and added them to the dynamic zone: `Images` and `Related Posts`. These two have only one field, called `items` **in both**. In `Images`, it is a file upload marked as `required` and in `Related Posts` it is a relation with the model `Posts`. When I tried to create an entry of the `Posts` model with **only** a component of `Related Posts`, I got the error I mentioned earlier on the admin panel, but this is what I got on the console:

```
[redacted] error Error: upload_file is not defined on the model.
    at EagerRelation.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/base/eager.js:50:15)
From previous event:
    at [redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:31:31)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at EagerRelation.eagerFetch ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at [redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:71:25)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at [redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:65:12
    at [redacted]/strapi-test-app/node_modules/lodash/lodash.js:3543:27
    at [redacted]/strapi-test-app/node_modules/lodash/lodash.js:4925:15
    at baseForOwn ([redacted]/strapi-test-app/node_modules/lodash/lodash.js:2990:24)
    at [redacted]/strapi-test-app/node_modules/lodash/lodash.js:4894:18
    at baseMap ([redacted]/strapi-test-app/node_modules/lodash/lodash.js:3542:7)
    at Function.map ([redacted]/strapi-test-app/node_modules/lodash/lodash.js:9580:14)
    at EagerRelation.morphToFetch ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:56:9)
    at EagerRelation.eagerFetch ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at [redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch ([redacted]/strapi-test-app/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager ([redacted]/strapi-test-app/node_modules/bookshelf/lib/model.js:1526:56)
    at Child.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/model.js:732:27)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Child.<anonymous> ([redacted]/strapi-test-app/node_modules/bookshelf/lib/model.js:730:12)
From previous event:
    at Child.fetch ([redacted]/strapi-test-app/node_modules/bookshelf/lib/model.js:702:19)
    at Function.findOne ([redacted]/strapi-test-app/node_modules/strapi-connector-bookshelf/lib/relations.js:65:8)
    at Function.update [as updateRelations] ([redacted]/strapi-test-app/node_modules/strapi-connector-bookshelf/lib/relations.js:100:51)
    at runUpdate ([redacted]/strapi-test-app/node_modules/strapi-connector-bookshelf/lib/queries.js:138:22)
```

This led me to believe initially that it was a problem with the database, which I completely erased multiple times without success. That's when I noticed that some of my components shared names and when I tried in an isolated instance of Strapi, [I managed to create a successful reproduction of the bug](https://github.com/dalbitresb12/dynamic-zones-bug-strapi).

### Steps to reproduce the behavior

1. Clone the [repository](https://github.com/dalbitresb12/dynamic-zones-bug-strapi) with the models pre-created.
2. Set the [environment variables needed](https://github.com/dalbitresb12/dynamic-zones-bug-strapi/blob/main/.env.example).
3. Start the instance with `yarn develop` and then create an entry in `Posts` **without any sections**.
4. Create another entry in `Posts` and add **only one instance** of `Related Posts` and select the previously created entry. **Don't create an instance of the `Images` component.**
5. You should get the errors described before.

### Expected behavior

Even though they are part of the same dynamic zone in `Posts`, I should be able to have fields with the same name without conflicting each other.

### Screenshots

This is how I entered the data in the admin panel and got the error. I had another entry of `Posts` created previously, called `Post 2`, which I used for the relation. You can see the error I mentioned earlier at the top.

![image](https://user-images.githubusercontent.com/7624090/104834606-91c22a00-586e-11eb-9397-1514c71f1021.png)

And this is how the `Posts` model looks in the Content-Type Builder. Remember that the field `items` in `Images` is marked as required (not shown in the screenshots):

![image](https://user-images.githubusercontent.com/7624090/104834838-1bbec280-5870-11eb-8bd1-1e4198528356.png)

![image](https://user-images.githubusercontent.com/7624090/104834841-22e5d080-5870-11eb-975a-32c41cf10daa.png)

### Code snippets

I believe this error should also be replicable using the quick start project, although I haven't tested it since [the quick start project is failing to create right now](https://github.com/strapi/strapi/issues/9120). But the reproduction repository was created using a manual configuration with the `create-strapi-app` package and a MySQL database. You can see the model definitions on the repository and create them manually on any project.

1. [This is the `Posts` model](https://github.com/dalbitresb12/dynamic-zones-bug-strapi/blob/main/api/posts/models/posts.settings.json).
2. [This is the `Related Posts` component](https://github.com/dalbitresb12/dynamic-zones-bug-strapi/blob/main/components/sections/related-posts.json).
3. [This is the `Images` component](https://github.com/dalbitresb12/dynamic-zones-bug-strapi/blob/main/components/sections/images.json).

### System

- Node.js version: v14.15.4
- NPM version: v6.14.10
- Strapi version: v3.4.3
- Database: MySQL Ver 8.0.22-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))
- Operating system: Ubuntu 20.04 running on WSL2 on Windows 10 2004

### Additional context

I'm not sure how this issue should be named, I hope it's okay.

Also, I haven't tested this using other databases, but at least using MySQL I've encountered this bug.

Finally, I haven't tested this yet, but I believe this error should also be present when having fields of different types than the ones I used (that's the use case I have and that's what led me to this error).

**Comment by fruluu** [comment]
same problem

**Comment by JeanLEUNG** [comment]
I have a similar issue in a slightly different case : error occurs when you attach a one-to-many reference to a collection defined with a component : 
![image](https://user-images.githubusercontent.com/26717079/105156615-5e9cc680-5b0c-11eb-8c58-6a4a358b6e32.png)

one-to-many (validation_activities in my case) field cannot be updated.

**Comment by JeanLEUNG** [comment]
Sorry guys, I have spent the whole day trying to spot the guilty, but without luck. All I can say is that in my case, the problem regularly occurs on some bidirectional links (no matter if this is one to many, one to one or many to one), does not seem to be directly due to one collection in particular, and occurs no matter the content of the object. My model is quite messy (sort of "spaghetti model"), and the problem seems to be linked to the global structure of the links between objects.

There can be 2 behaviours : 
- the edited object refuses the update (popup with "invalid input data") and the save is cancelled
- the edited object accepts the update, but it corrupts the linked object : the linked object cannot be accessed anymore, and some error show up in the console (error TypeError: m.pivot.get is not a function).

The model came from a 3.0.0 version where it worked well, I did not update it with the new optional fields.

**Comment by lamualfa** [comment]
Same issue with SQLite

**Comment by derrickmehaffy** [comment]
This issue is a bit more complex to debug due to that error returned to the admin panel "violates unique constraints"

There is a few try/catch blocks and the final one provides that error message. Can you please check the error stack provided on the server side to verify your issue is the same.

**Comment by dalbitresb12** [comment]
@derrickmehaffy Did you manage to reproduce the error with the repository provided?

**Comment by derrickmehaffy** [comment]
I'm sorry @dalbitresb12 I've been quite busy right now, it's on my list to test soon.

**Comment by LilyLauben** [comment]
I just got this error when I tried to rename a component within a dynamic zone. Presumably this is linked to #1114 since the old component still exists in the database, although I'm a little confused about why I'm getting this particular issue because the two different components and fields should also be of identical types since it's just a duplicate?

**Comment by moonvader** [comment]
I had the same problem - message `Invalid input data. Please verify unique constraints` when i tried to create record from Strapi admin panel. In my case it happened after I renamed filed which was required. 
In order to solve it - I had to delete column with old name from Postgres table.

**Comment by derrickmehaffy** [comment]
Confirmed on v4 by dogUnbound on Discord

**Comment by dogunbound** [comment]
@derrickmehaffy this issue is legit related to this https://github.com/strapi/strapi/issues/11955 

No joke!!! When I named the components different names in the field name, the images would stay!!! They disappear if your component names in the dynamic zones are similar.

You don't get the Invalid input data. Please verify unique constraints. You just get a missing media component when you go to save.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198
