### ISSUE TITLE
The port -1 is already used by another application after migration.

### ISSUE THREAD

**Issue by steveDL** [strapi/strapi#9151]
### Describe the bug

Having used the cli to install strapi I discovered that it installs unsupported beta version (why?)

I decided to follow the migration guide and I now have this error. 

<img width="715" alt="Screenshot 2021-01-17 at 08 33 32" src="https://user-images.githubusercontent.com/8135124/104835597-9d7a1480-589f-11eb-8738-f03148f076a4.png">

### System

- Node.js version: v14.6.0
- NPM version: 6.14.9
- Strapi version: 3.0.0
- Database: mysql
- Operating system: OSX

**Comment by derrickmehaffy** [comment]
Can you provide your `./config/server.js` and clarify if you are setting a port in your .env file?

Also

> Strapi version: 3.0.0

Is this your actual Strapi version and did you follow the migration guides? 
https://strapi.io/documentation/developer-docs/latest/migration-guide/#instructions

**Comment by derrickmehaffy** [comment]
closing as user provided no new information
