### ISSUE TITLE
Model attribute "autoPopulate" ignored when set to false in create/update action responses with MongoDB

### ISSUE THREAD

**Issue by uteegozi** [strapi/strapi#9152]
### Describe the bug

When defining the "autoPopulate" model attribute as false on a relation field (one-way in this case), responses for create and update requests do return the complete relation object.
Get and delete responses do return only the "id" of the relation field as expected.

### Steps to reproduce the behavior

1. Install Strapi with MongoDB - the bug does not happen with MySql as DB
2. Define a collection content type - "skill" in below example
3. Add a relation field to it - "user" in below example
4. Define the attribute "autoPopulate": false on the relation field
5. Create a user
6. Create a skill with the above user
7. See that response contains the whole user object

### Expected behavior

For "autoPopulate" set to false the response should only contain the "id" of the relation field.

### Code snippets

skill model:
{
  "kind": "collectionType",
  "collectionName": "skills",
  "info": {
    "name": "skill"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "user": {
      "plugin": "users-permissions",
      "model": "user",
      "autoPopulate": false
    }
  }
}

### Problematic code 

An attempt to debug the problem lead to the following finding:

**strapi-connector-mongoose -> lib -> relations.js,  line 84, excerpt:**

```
module.exports = {
  async update(params, { session = null } = {}) {
    const relationUpdates = [];
    const populate = this.associations.map(x => x.alias);
```

When initializing the "populate" variable should take "autoPopulate" of the relations (associations) into account:

 ```
const populate = this.associations
                          .filter(x => x.autoPopulate)
                          .map(x => x.alias);
```

### System

- Node.js version: v12.18.3
- NPM version: 6.14.11
- Strapi version: 3.4.3
- Database: MongoDB 4.4
- Operating system: Windows 10

**Comment by tobefuture827** [comment]
+ 1 
same problem. 
Webhook event send complete relation object when defining the "autoPopulate" model attribute as false on relation field.
As a result of the issue,  other applications return a "request entity too large" error .

**Comment by aksdevac** [comment]
Yes & we can't even pass custom populate in update/create query, see related issue issue https://github.com/strapi/strapi/issues/7731

**Comment by derrickmehaffy** [comment]
monogo is no longer supported in v4, closing
