### ISSUE TITLE
Uploading media to aws s3

### ISSUE THREAD

**Issue by anthonyatp** [strapi/strapi#9158]
### Describe the bug

I recently upgraded to 3.0.0 stable and now having issues uploading media to s3 via the media library. 

It seems media is being uploaded to `/uploads/<file_name>`, previously it was uploaded to 
```<bucket_name>.s3.<region>.amazonaws.com/<file_name>```

Thus, I'm unable to actually use these images as they are not in my s3 bucket.

My config file (`./config/plugin.js`) looks like this:
```
module.exports = ({ env }) => ({
    upload: {
        provider: 'aws-s3',
        providerOptions: {
            accessKeyId: env('BUCKETEER_AWS_ACCESS_KEY_ID'),
            secretAccessKey: env('BUCKETEER_AWS_SECRET_ACCESS_KEY'),
            region: env('BUCKETEER_AWS_REGION'),
            params: {
                Bucket: env('BUCKETEER_BUCKET_NAME'),
            },
        },
    },
});
```
### System

- Node.js version: 12.10.1
- Strapi version: 3.0.0

**Comment by alexandrebodin** [comment]
your config file is missing an `s` ;) it is config/plugins :)

**Comment by anthonyatp** [comment]
Wow - can't believe I wasted my afternoon trying to figure this out! haha

Thanks for spotting the error so quickly!
