### ISSUE TITLE
Context.state.user missing in GraphQL field resolvers

### ISSUE THREAD

**Issue by fregu** [strapi/strapi#9159]
## Bug report
Context in field resolvers does not contain user state.

### Describe the bug

When declaring a resolver for a field for instance

```gql
module.exports = {
  Restaurant: {
    owner: async (owner, opts, { context }) => {
      return owner.id === context.state.user.id ? owner : null; // cannot call id of undefined
    },
  },
};
```
user is missing from the context object, but is available for root queries like
```gql
module.exports = {
  Query: {
    restaurants: {
      resolverOf: 'application::restaurants.restaurants.find',
      resolver: async (obj, options, { context }) => {
        console.log(context.state.user) // works like a charm
      }
    }
  }
}
```

### Steps to reproduce the behavior
(I assume the GraphQL plugin is already installed)

1. Create a file `api/restaurant/config/schema.graphql.js` (or other available collection type)
2. Paste example from above, or just test the context state object with console.log(context.state)
3. Open GraphQL playground  eg.`http://localhost:1337/graphql`
4. Paste login mutation to get valid JWT
```
mutation login {
  login(input:{identifier:"myusername", password:"mypassword"}) {
    jwt
  }
}
```
5. Write query which will trigger your resolver e.g.
```
query restaurants {
  restaurants {
    id
    owner {
      id
      name
    }
  }
}
```
6. See logs to identify problem
7. Help me solve this, so I can customize the result of fields depending on who is making the request.

### Expected behavior

I expect `context.state.user` to contain the user information of the user making the request.

### System

- Node.js version: LTS
- NPM version: 6.14
- Strapi version: 3.4.2
- Database: sqlite
- Operating system: MacOS

### Additional context

For fields we cannot use the syntax of resolverOf, since they do not represent any controller action.

**Comment by darron1217** [comment]
I'm experiencing same issue here.
The weird thing is, accessing `context.state.user` is possible when using `AdminUser` token. It only happens when using `User` token from `users-permissions` plugin.

**Comment by darron1217** [comment]
I found that adding code below can solve this issue.

strapi-plugin-users-permissions/middlewares/users-permissions/index.js
```
module.exports = strapi => {
  return {
    initialize() {
      // ... some codes
      strapi.app.use(async (ctx, next) => {
        if (ctx.request && ctx.request.header && ctx.request.header.authorization) {
          try {
            const {id} = await strapi.plugins['users-permissions'].services.jwt.getToken(ctx);

            if (id === undefined) {
              throw new Error('Invalid token: Token did not contain required fields');
            }

            // fetch authenticated user
            ctx.state.user = await strapi.plugins[
              'users-permissions'
              ].services.user.fetchAuthenticatedUser(id);
            return next();
          } catch (err) {
            return handleErrors(ctx, err, 'unauthorized');
          }
        }
      });

    },
  };
};
```

I found that `AdminUser` uses middleware to get authentication.
But `User` uses policy to get authentication.

I think `policy` is not being applied to graphql custom resolver.
How about changing the way to get auth of `User` in users-permissions plugin?

**Comment by yeongjet** [comment]
you have to set `[]` to policy in the api's config:
```js
{
  "routes": [
    {
      "method": "GET",
      "path": "/user",
      "handler": "user.find",
      "config": {
        "policies": [] // must set to `[]` if no other policy
      }
    }
}
```

**Comment by derrickmehaffy** [comment]
should be fixed in v4
