### ISSUE TITLE
[Strapi 3.4.3] Cors configuration not working properly

### ISSUE THREAD

**Issue by TracyNgot** [strapi/strapi#9160]
### Describe the bug

While bumping Strapi to the latest version, it rejects calls from the endpoints. I had to revert to version `3.4.1`.

### Steps to reproduce the behavior

1. Bump Strapi to latest
2. Change cors's settings

### Screenshots

![image](https://user-images.githubusercontent.com/3769716/104958666-59cefa00-59c8-11eb-85eb-c43d06b67530.png)

### Code snippets

```
// Middleware's configuration
    cors: {
      enabled: true,
      headers: [
        'Content-Type',
        'Authorization',
        'X-Frame-Options',
      ],
      origin: [
                'http://localhost:5000',
                'http://localhost:3000',
                'http://localhost:1337',
              ]
    }
```

### System

- Node.js version: `14.15.3`
- NPM version: `6.14.9`
- Strapi version: `3.4.3`
- Database: `Postgresql`
- Operating system: `Mac/Linux`

**Comment by sercanov** [comment]
![image](https://user-images.githubusercontent.com/10291644/105487522-4c17be00-5cc1-11eb-961a-326ba7fb45bc.png)

I'm also having CORS issue only when uploading file to decoupled Strapi backend with following config 

package.json
```javascript
    "strapi": "3.4.3",
    "strapi-admin": "3.4.3",
    "strapi-connector-bookshelf": "3.4.3",
    "strapi-connector-mongoose": "^3.4.3",
    "strapi-plugin-content-manager": "3.4.3",
    "strapi-plugin-content-type-builder": "3.4.3",
    "strapi-plugin-email": "3.4.3",
    "strapi-plugin-upload": "3.4.3",
    "strapi-plugin-users-permissions": "3.4.3",
    "strapi-provider-upload-aws-s3": "^3.4.3",
    "strapi-utils": "3.4.3"
```

config/server.js
```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('STRAPI_URL'),
  admin: {
    serveAdminPanel: false,
    url: '/',
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'XXX'),
    },
  },
});
```

config/middleware.js
```javascript
module.exports = {
  settings: {
    cors: {
      enabled: true,
      headers: '*',
      origin: [
        'http://localhost',
        'https://dashboard.artlabs.ai',
      ],
    },
  },
};
```

**Comment by derrickmehaffy** [comment]
Can you please tell me the file path you used to configure cors?

**Comment by TracyNgot** [comment]
@derrickmehaffy `config/middleware.js`

**Comment by dalbitresb12** [comment]
I've experienced the same error as @sercanov and was about to post more details about it, but I found this on my `error.log` in Nginx: 

```
2021/01/27 04:17:11 [error] 19338#19338: *138 client intended to send too large body: 3674186 bytes, client: 172.19.144.1, server: api.strapi.test, request: "POST /upload HTTP/2.0", host: "api.strapi.test", referrer: "https://dash.strapi.test/"
```

I modified my Nginx configuration to allow bigger body sizes and now it works perfectly. I don't know if @sercanov is also using Nginx, but in case he's not, it might be worth checking if it is related to this.

**Comment by sercanov** [comment]
@dalbitresb12 My case was about Dokku's upload limit. Dokku is also managing nginx so it's probably about this. I solved it with https://github.com/Zeilenwerk/dokku-nginx-max-upload-size

**Comment by TracyNgot** [comment]
It's solved! It was due to the fact there was a conflict between *Bluebird.Promise* and the native one. I have removed `bluebird` in my dependencies
