### ISSUE TITLE
Data not visible for a Relation column in strapi cms

### ISSUE THREAD

**Issue by shoryavj** [strapi/strapi#9161]
Data for a Date column is not visible when it is used as a Relation for another table in strapi cms
![Screenshot 2021-01-19 at 3 05 13 AM](https://user-images.githubusercontent.com/22168535/104964789-2a89ae80-5a03-11eb-9582-2989fc324010.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
