### ISSUE TITLE
Can't pass parameters in link to custom controller

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#9164]
### Describe the bug

I can't pass parameters according to 
https://strapi.io/documentation/developer-docs/latest/plugins/graphql.html#link-a-query-or-mutation-to-a-controller-action
in a gql request with a link to a custom controller.

The controller itself runs fine and returns the string given as `ctx.body = JSON.stringify(ctx);` in gql response.
However, I can't receive the parameter name from the ctx object in the controller.

### Steps to reproduce the behavior

1. create schema
2. create controller using the cli
3. inspect the ctx object

### Expected behavior

`The where parameter is available via ctx.params and the data are available via ctx.request.body in the controller's action.` - docs

### Code snippets

schema:
```gql
module.exports = {
  mutation: `
    createDeal(name: String): String
  `,
  resolver: {
    Query: {},
    Mutation: {
      createDeal: {
        description: "Create a deal in pipedrive.",
        resolver: "application::configurator.configurator.createDeal",
      },
    },
  },
};
```

mutation:
```gql
mutation {createDeal(name: "Test")}
```

controller:
```js
"use strict";

module.exports = {
  createDeal: async (ctx) => {
    try {
      ctx.body = JSON.stringify(ctx);
    } catch (err) {
      ctx.body = err;
    }
  },
};

```

### System

- Node.js version: 12
- NPM version: 6.14.9
- Strapi version: 3.4.3
- Database: mongo
- Operating system: fedora

**Comment by tw1t611** [comment]
@derrickmehaffy I did update the issue.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I did update the issue.

Thank you!

**Comment by tw1t611** [comment]
@derrickmehaffy This still has the label `pending reproduction`. Just to clearify, you do build it yourself, or want me to do it?
Furthermore, please tell me the actual status. I need to decide, if I should fetch these endpoints on the rest api soon.

**Comment by derrickmehaffy** [comment]
Just a lack of time on our side to reproduce the issue

**Comment by tw1t611** [comment]
I figured out, that `ctx.params` is no included in `ctx`.
So I returned `ctx.body = JSON.stringify(ctx.params);`, which gave me `{}`

The expected result would be: `{"0":"pdf/offer/create/name","name":"name"}`

I even tried the REST route, which seems to work.

routes.json
```js
{
  "routes": [
    {
      "method": "GET",
      "path": "/pdf/offer/create/:name",
      "handler": "offer.create",
      "config": {
        "policies": []
      }
    }
  ]
}
```

Could you privide any updated on this please?

**Comment by derrickmehaffy** [comment]
should work in v4
