### ISSUE TITLE
how to backup data on strapi using SQLite database

### ISSUE THREAD

**Issue by Gabriel-Andy** [strapi/strapi#9166]
---hi 
I have been working with strapi for almost 6 months now but I had an issue this morning and 
I really need help.
by mistake, I open my strapi project on visual studio code and I wanted to change something on my database and It turned out that I went to my api folder and access a specific endpoint, which was project and then access his model and then his project.settings.json and by mistake I deleted the data inside the object and now I am getting error when I open my strapi project.
I am wondering if there is a backup to get all my data back as it was in the beginning.
this the path api/project/models/project.settings.json
 This is the link of my project https://www.screencast.com/t/8QUELwqhyn1

please I would really appreciate help from someone.
I look forward to hearing from you back.

[details="System Information"]
- **Strapi Version*3.3.3*: 
- **Operating System*window*: 
- **Database*SQLite *: 
- **Node Version*13,13.0*: 
- **NPM Version*6.14.9*: 
- **Yarn Version*1.22.5*: 
[/details]

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

---

I see you created a forum thread already and currently we are backlogged at reviewing forum threads.

**Comment by Gabriel-Andy** [comment]
thanks for replying
to be honest, it is not a big but I feel like this feature hasn't been
implemented yet on strapi.
