### ISSUE TITLE
Drastic performance drop in graphql queries on mongodb with multiple relations on collections after updating from strapi-plugin-graphql 3.4.1 to 3.4.3

### ISSUE THREAD

**Issue by vasilGerginski** [strapi/strapi#9167]
## Bug report
A query that used to take 2 s seconds now takes 71 s

### Steps to reproduce the behavior

Changing the version only of the graphql plugin fixes the issue
```
    ...
    "strapi-plugin-email": "^3.4.3",
    "strapi-plugin-graphql": "^3.4.1",
    "strapi-plugin-upload": "^3.4.3",

```
### Expected behavior

The query performance is unaffected 

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.3
- Database: MongoDb
- Operating system: Ubuntu 20

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8552

**Comment by abdonrd** [comment]
I also notice this performance drop!
