### ISSUE TITLE
Data protection: ask for sending data to analytics.strapi.io

### ISSUE THREAD

**Issue by lucaperret** [strapi/strapi#917]
**What is the expected behavior?**

Because of the new [GDPR European law](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation), Strapi's CLI should prompt the user to accept sending analytics data to Strapi. The user can also change this configuration.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by Aurelsicoko** [comment]
@lucaperret We're currently working on this topic with our lawyers. We're not collecting any personal data so we aren't directly concerned about the GDPR on this specific part. However, it doesn't mean we've nothing to do on our side to respect the European regulation. You should see some changes in the next weeks!
