### ISSUE TITLE
No add button on Heroku deployment.

### ISSUE THREAD

**Issue by abserari** [strapi/strapi#9173]
Click the deploy on Heroku.

Success! but no add button.
![image](https://user-images.githubusercontent.com/32089134/105347246-9ba6ad00-5c21-11eb-9024-e036454a2284.png)

**Comment by derrickmehaffy** [comment]
This is normal, please see our FAQ on our documentation. 

Marking as closed.

**Comment by abserari** [comment]
WARNING

For security reasons, the Content Type Builder plugin is disabled in production. To update content structure, please make your changes locally and deploy again.

**Comment by derrickmehaffy** [comment]
Also:
https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-paas
