### ISSUE TITLE
Collection Field not showing up in api response for users/me

### ISSUE THREAD

**Issue by aditya-mitra** [strapi/strapi#9175]
## Bug report

An attribute on the `user` model as **collection** is visible in `/users/1` but not in `/users/me`.

### Describe the bug

I have an attribute `badges` in my **users** models which is collection going to the badges model.

I get the `badges` field in the api response when I go to `/users/1` but not in `/users/me`.

For security reason, we should not disclose the `/users/:id` in the api response.

### Steps to reproduce the behavior

1. Create a collection called *boxes* in the `Content-Type Builder`
2. Go to Users (from users-permissions)
3. Click add another field
4. Select relation
5. Select *one to many* where it says *users has many boxes*
6. Save the model
7. Insert data (say `box 1`)into the boxes model
8. Go to `Users` in collection types and select *box 1* in the boxes dropdown
9. Access `/users/me` with proper auth header
10. The *boxes* field will be absent in the api response

### Expected behavior

The field to appear in the api response.

### Code snippets

This is my `users.setttings.json` file
```json
{
	"kind": "collectionType",
	"collectionName": "users-permissions_user",
	"info": {
		"name": "user",
		"description": ""
	},
	"options": {
		"draftAndPublish": false,
		"timestamps": true
	},
	"attributes": {
		"username": {
			"type": "string",
			"minLength": 3,
			"unique": true,
			"configurable": false,
			"required": true
		},
		"email": {
			"type": "email",
			"minLength": 6,
			"configurable": false,
			"required": true
		},
		"provider": {
			"type": "string",
			"configurable": false
		},
		"password": {
			"type": "password",
			"minLength": 6,
			"configurable": false,
			"private": true
		},
		"resetPasswordToken": {
			"type": "string",
			"configurable": false,
			"private": true
		},
		"confirmationToken": {
			"type": "string",
			"configurable": false,
			"private": true
		},
		"confirmed": {
			"type": "boolean",
			"default": false,
			"configurable": false
		},
		"blocked": {
			"type": "boolean",
			"default": false,
			"configurable": false
		},
		"role": {
			"model": "role",
			"via": "users",
			"plugin": "users-permissions",
			"configurable": false
		},
		"score": {
			"model": "score",
			"via": "users_permissions_user"
		},
		"badges": {
			"collection": "badges"
		}
	}
}

```

### System

- Node.js version:  12
- NPM version: 6
- Strapi version:  latest
- Database: sqlite3
- Operating system: ubuntu

**Comment by derrickmehaffy** [comment]
The specific service you need to modify via our [extensions system](https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#how-do-i-customize-a-plugin) is here: 

https://github.com/strapi/strapi/blob/2900584be57fc2e20c775ac111b37d817109bcd1/packages/strapi-plugin-users-permissions/services/User.js#L71-L77

Simply modifying the `['role']` to include the relation fields you wish to populate.

Marking as closed as mentioned by @Convly it's intended.
