### ISSUE TITLE
Media upload response url value ignores custom url in server config

### ISSUE THREAD

**Issue by zoltantothseon** [strapi/strapi#9176]
### Describe the bug

If in server.js configuration we set a custom url like 'http://localhost/api' as suggested in the nginx configuration documentation then the Media Library plugin's response on upload doesn't reflect it. When the `${strapi.backendURL}/upload` endpoint is used for uploading the response contains an url property which sends back a relative path e.g.: "/uploads/image.png" instead of "/api/uploads/image.png" or the full absolut path. However on the plugin's page it correctly shows the paths and the copy link button correctly copies the full path also: http://localhost/api/uploads/image.png

It's problematic e.g. when you use the image upload functionality of a wysiwyg editor like ckeditor. 

### Steps to reproduce the behavior

1. Go to Media Library plugin page in admin.
2. Open network in your browser and upload an asset.
3. Check the response of the upload request.

### Expected behavior

It should return in the url property the correct path if it's altered in server.js config file.

### Screenshots

![image](https://user-images.githubusercontent.com/64959066/105378781-73608380-5c0c-11eb-971c-40118a9f1504.png)

### System

- Node.js version: LTS
- NPM version: 6.14.6
- Strapi version: LTS
- Database: Mysql
- Operating system: MacOS

### Additional context

I replaced the wysiwyg editor with ckeditor5 and enabled image upload functionality with SimpleUpload plugin. The uploading is working well however then the image insertion is wrong as the returned url value is relative.

**Comment by derrickmehaffy** [comment]
This is intended, you will need to inject the url into the relative link to the file. Others have suggested giving the user the option but for the moment we are undecided (we are aware of the feature request though).

Marking as closed.

**Comment by harish2704** [comment]
For those who got stuck at this issue, please take a look at this comment 
https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/issues/12#issuecomment-915618516

**Comment by kirwako** [comment]
you can use this strapi plugin it fix the problem and work well
https://www.npmjs.com/package/strapi-plugin-media-prefix
