### ISSUE TITLE
Dependent Relations

### ISSUE THREAD

**Issue by Prashant4900** [strapi/strapi#9177]
## Feature request

i want to create dependent drop down in my admin panel i tried every possible rational combination but i still doesn't get result

![image](https://user-images.githubusercontent.com/62440911/105389342-bd159200-5c3d-11eb-923b-edfb17058c08.png)
![image](https://user-images.githubusercontent.com/62440911/105389407-d0c0f880-5c3d-11eb-8f75-2fee1c8056c3.png)
![image](https://user-images.githubusercontent.com/62440911/105389472-e59d8c00-5c3d-11eb-8903-71b44cf89fc9.png)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8708
