### ISSUE TITLE
[3.4.4] JSON field not reflecting data when moving inside a dynamic zone

### ISSUE THREAD

**Issue by wedneyyuri** [strapi/strapi#9180]
### Describe the bug

When the component is moved within a dynamic zone, the visual does not reflect the data that the data layer represents.

### Steps to reproduce the behavior

1. Create a custom component with a field of type JSON.
2. Create a collection with a repeatable dynamic zone. Include the previously created component inside this dynamic zone.
3. Create a new entry of the collection
4. Save the collection
5. Move components inside the dynamic zone, the visual will not reflet any change **(here is the bug)**.
6. When you save the collection everything will be working as expected

### Expected behavior

The data inside the JSON component should be updated as well.

### Screenshots

![Peek 2021-01-21 20-18](https://user-images.githubusercontent.com/7511692/105424665-82542f80-5c26-11eb-81d2-b07539c3fe60.gif)

### Code snippets

Not applicable.

### System

- Node.js version: v12.1.0
- NPM version: 6.9.0
- Strapi version: 3.4.4
- Database: default
- Operating system: Linux

### Additional context

Seems related to https://github.com/strapi/strapi/issues/9016. When React reaches this point it is ignoring the update:https://github.com/strapi/strapi/blob/ed6b206c19ff3c017255a765fdeede2d2ea5ae7e/packages/strapi-plugin-content-manager/admin/src/components/InputJSON/index.js#L57

![Peek 2021-01-21 20-33](https://user-images.githubusercontent.com/7511692/105425722-aadd2900-5c28-11eb-93d5-0a2eb603e251.gif)

**Comment by derrickmehaffy** [comment]
Confirmed on v3.4.4
