### ISSUE TITLE
Strapi failed to update content-type, error returned.

### ISSUE THREAD

**Issue by LQF2020** [strapi/strapi#9185]
# When created a new collection type or updated a existing content-type, strapi always return an error.

## The following is my console output:
![strapi_issue](https://user-images.githubusercontent.com/69631301/105485977-d4b64e80-5d01-11eb-9a98-597be2ef1795.jpg)

## When i open the admin/users/me/permission url in the browser, i got the following response:
![strapi_issue2](https://user-images.githubusercontent.com/69631301/105486083-07604700-5d02-11eb-856a-00ce4bee8938.jpg)

The strapi project worked perfectly before, but this issue happened 2 days ago. 

I am logged in as a super admin, which believed that has the highest level of permission.

Is there any one can help with this ?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
