### ISSUE TITLE
Strapi Admin - help button overlaps pagination

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#9186]
### Describe the bug

The help button at the right bottom of the admin panel overlaps the pagination foreward arrow, so that it can't be clicked.

### Steps to reproduce the behavior

1. Go to strapi admin
2. Open collection listview with pagination
3. See blue help (?) button over pagination

### Screenshots

![strapi-admin-helpbutton](https://user-images.githubusercontent.com/8960545/105491325-69935a80-5cb6-11eb-9be8-ce2a38bc2dcd.png)

### System

- Strapi version: 3.4.4

**Comment by derrickmehaffy** [comment]
Workaround, disable the tutorial videos (which removes that icon): https://strapi.io/documentation/developer-docs/latest/admin-panel/customization.html#tutorial-videos

**Comment by mfrachet** [comment]
Hello 👋🏻 

Thank you for submitting this issue 🙏🏻 . A fix has been merged and will be released in the next version. In the meantime, I'm closing this issue.

Feel free to reopen if you think the fix is not a valid one 😊 

Thanks for your help on the project 🙏🏻
