### ISSUE TITLE
the parameter "define condition" "Is creator" doesn't work properly anymore since 3.4.0

### ISSUE THREAD

**Issue by MickaelFondation** [strapi/strapi#9187]
Hi, I have some role custom (I have bronze plan). One of my collections have specific rights like they only have to be seen when you are author. It worked until i upgraded to 3.4.0 (3.4.4 is no better), now everyone can see each other entries in the list (but cannot modify them which is good)

**Describe the bug**
It look likes the parameter "define condition" "Is creator" doesn't work properly anymore since 3.4.0. When it's set to a specific Collection Types (on read condition for example). Every element are displayed in the list and there is "-" character at the place of datas when the user does not normaly have the right and when I click to modify I have this message "You are not allowed to see this document" (which is normal). In this case I should only see the entries I created.

**Steps to reproduce the behavior**

1. Having two user with two different roles
2. Create a few entries in a collection type  with those users (for exemple 5 for each)
3. As an administrator go to Permission then Roles
4. Edit the role of the two previous user 
5. Click on parameters who is display on mouseover on the collection types who correspond of the one you created before
6. Select "is creator" next to CAN READ WHEN
7. Apply
8. Go to the right collection type on the main menu
9. Every entries appear on the list but with no data displayed (only '-' characters on the list)

**Expected behavior**
The right behavior is to only datas on the list from the author or same role as creator if set like that. (By the way same role as creator didn't work well either before 3.4.0 because the field on the list was empty)

**Screenshots**
<img width="1399" alt="bugstrapi" src="https://user-images.githubusercontent.com/68648961/105494866-b62d6480-5cbb-11eb-9f69-2a0d1371cd99.png">

**System**

Strapi self hosted 3.4.0

**Comment by derrickmehaffy** [comment]
@MickaelFondation since you have a bronze license, can you please email us at support@strapi.io so we can do some one on one debugging. we will keep the bug report here and updated it after we have done some testing together.

**Comment by derrickmehaffy** [comment]
Hi @MickaelFondation 

Per our call I was able to confirm this issue only happens within the v3.4.x release and reverting back to the v3.3.x does not.

Attached screenshots from both versions (as Author):

## v3.3.x

![image](https://user-images.githubusercontent.com/8593673/105721461-d474a980-5ee1-11eb-861d-88ac5c3ff935.png)
![image](https://user-images.githubusercontent.com/8593673/105721659-0ede4680-5ee2-11eb-9ad9-baab9826ee86.png)


## v3.4.x

![image](https://user-images.githubusercontent.com/8593673/105721941-5c5ab380-5ee2-11eb-9507-c9f063f9e516.png)
![image](https://user-images.githubusercontent.com/8593673/105721659-0ede4680-5ee2-11eb-9ad9-baab9826ee86.png)
