### ISSUE TITLE
Allow for optional CDN on specific providers

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#9188]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Mirrored feature request from:
- https://github.com/strapi/strapi/issues/3218
- https://github.com/strapi/strapi/pull/5232

Allow optional CDN toggle + CDN URL as an example with AWS S3 + Cloudfront

### Why is it needed?

Suggested by an enterprise customer as well as many members of the community, previous response was to build a custom provider however the extra code is not complex and could be useful to build in natively.

### Suggested solution(s)

See related issue and PR links

### Related issue(s)/PR(s)

- https://github.com/strapi/strapi/issues/3218
- https://github.com/strapi/strapi/pull/5232

**Comment by kasonde** [comment]
Valid in v4 as well.

**Comment by sjoukedv** [comment]
As a workaround, using the core upload plugin, we can change the URLs directly in the (Postgres) database:

`update files set url = concat('https://cdn.example.com/', hash, ext);`

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/allow-for-optional-cdn-on-specific-providers
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
