### ISSUE TITLE
Relations not being saved with POST API request, only with PUT

### ISSUE THREAD

**Issue by pedrosimao** [strapi/strapi#919]
**Informations**
- **Node.js version**: 9.7.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.11.2
- **Database**: MongoDB
- **Operating system**: Ubuntu

**What is the current behavior?**
When doing a POST API request, fields with relations to other collections are ignored. 
I have later tried doing a PUT request with the exact same JSON in the body and it works just fine. So, I guess the problem only occurs when we do a POST, not with PUT.
Also, I was intrigued why it worked fine using the CMS Backoffice and I decided to try doing a POST request (via Postman) to `localhost/content-manager/explorer/pageshistory/?source=content-manager` instead of `localhost/pageshistory` and it worked perfectly. Relations were saved with no problem.

**Steps to reproduce the problem**
1 - Create two Content Types. One of the content types should be manually edited to have a "has one" relation to the other.  As we only edit one Collection I consider it a one-way relation. I chose to do so, because there would be too many relations associated with one document. Therefore it would look very ugly on the Backoffice/UI. Also on the API responses the information is not needed.
2 - Create one content on the Collection with no relation declared.
3 - Do a POST request (via Postman, for example) request to create a new content in the Collection where we should save de "one-way" relation. The relation should be saved by putting the ID of the content previously created in the field that defines the relation. Like this:
```
{
	"name": "Could be anything",
	"parentPage" : "5ab3872b5260f41ba7c480a4"
}
```
In parentPage value we should use the ID of the content previously created in the first collection.

4 - Relation won't be saved. ID will be ignored.

**What is the expected behavior?**
POST request should be able to save relation to other collections with no problem. Just like doing a PUT request or a POST via UI/Backoffice/Content-Manager.

- [X] I'm sure that this issue hasn't already been referenced

**Comment by pedrosimao** [comment]
Just making a small update.
I have managed to fix the API by editing the API services on the "add" function.
Basically, I had to delete the loadash function that omits the associations from the "values".
By default Strapi makes the API request like this:
```const data = await Pageshistory.create(_.omit(values, _.keys(_.groupBy(strapi.models.pageshistory.associations, 'alias')))); ```

So, I simply changed to this:
```const data = await Pageshistory.create(values);```

I just wonder if there is a serious reason why you omit the associations?

**Comment by pedrosimao** [comment]
New update:
I have just done a test using two collections that have a different relation. 
This time I had a "many-to-one" relation, instead of a "one-way" relation.
And again I had the exact same problem.
So I suggest to delete the loadash omit function from the POST APIs services.

**Comment by lauriejim** [comment]
Hi @pedrosimao can you submit a PR to fix it please. Will appreciate your help.

**Comment by pedrosimao** [comment]
Sure, I was just a bit afraid of doing changes that mess up something else.
For example, it would be usefull to know if there is any reason for you to use the `lodash` omit function on `values`object? Or if you just forgot this piece of code from a much earlier version?
```_.omit(values, _.keys(_.groupBy(strapi.models.pageshistory.associations, 'alias'))) ````

**Comment by lauriejim** [comment]
Hey @pedrosimao I test it with master branch and I have no problem with relations...

So I can't actually accept your PR. And as you can see, if your issue come from relations, you probably have to investigate on `await strapi.hook.mongoose.manageRelations('article', _.merge(_.clone(data), { values }));` function. It's this part of code that handle relations. You don't have to update `.create()` params.

Can you send me your models files and the request you send to create and update data (via postman)

**Comment by pedrosimao** [comment]
@lauriejim have you tested with One-Way relationship? I am pretty sure you will have a problem.
Also, it would be nice if you clarify the reason you have used lodash in that particular situation. It doesn't seem needed to me, and suppressing it fixed the issue to me.
Anyway, I will look into the part of the code you pointed out.

**Comment by pedrosimao** [comment]
@lauriejim I just checked again, and I think you are not correct about the issue.
I did a `console.log(data); ` and the data object simply does not contain the relation. Which clearly indicates that the problem comes from before `await strapi.hook.mongoose.manageRelations(...)` is executed. If we are sending the incorrect `data` to `manageRelations()` method, the relation will never be stablished.

**Comment by pedrosimao** [comment]
This is my `data` when `lodash omit` is used:
```
{ _id: 5ad4acdf4f8ea30622280dc9,
  name: 'This is the related to two',
  createdAt: 2018-04-16T14:02:07.783Z,
  updatedAt: 2018-04-16T14:02:07.783Z,
  __v: 0,
  id: '5ad4acdf4f8ea30622280dc9' }
```

And this is without `lodash omit`:
```
{ _id: 5ad4ade72537730646c9c34d,
  related: 5acfa7d43636e90f889b4aad,
  name: 'This is the related to two',
  createdAt: 2018-04-16T14:06:31.838Z,
  updatedAt: 2018-04-16T14:06:31.838Z,
  __v: 0,
  id: '5ad4ade72537730646c9c34d' }
```

**Comment by pedrosimao** [comment]
@lauriejim ?

**Comment by Aurelsicoko** [comment]
@pedrosimao You were right the one-way relationship wasn't supported in the generated API and the data wasn't sent correctly to the `manageRelations` method. I opened a PR https://github.com/strapi/strapi/pull/1004
