### ISSUE TITLE
[3.4.4] The admin panel is unavailable

### ISSUE THREAD

**Issue by sregdorr** [strapi/strapi#9195]
### Describe the bug

Following the installation instructions in the tutorial here https://strapi.io/documentation/developer-docs/latest/installation/cli.html with the --quickstart flag, the server is always started with the warning:

```The admin panel is unavailable... Impossible to open it in the browser.```

![image](https://user-images.githubusercontent.com/32646119/105538045-79ac3980-5cb8-11eb-8ca3-f2ca077bfd78.png)

### Steps to reproduce the behavior

Follow installation steps here: https://strapi.io/documentation/developer-docs/latest/installation/cli.html
- I tried with npx, pnpx, and yarn all receiving the same results.

### Expected behavior

Ability to open the admin panel

### Code snippets

> C:\Development\sandbox> npx create-strapi-app my-project --quickstart
> Creating a new Strapi application at C:\Development\sandbox\my-project.
> 
> Creating a quickstart project.
> Creating files.
> Dependencies installed successfully.
> 
> Your application was created at C:\Development\sandbox\my-project.
> 
> Available commands in your project:
> 
>   yarn develop
>   Start Strapi in watch mode.
> 
>   yarn start
>   Start Strapi without watch mode.
> 
>   yarn build
>   Build Strapi admin panel.
> 
>   yarn strapi
>   Display all available commands.
> 
> You can start by doing:
> 
>   cd C:\Development\sandbox\my-project
>   yarn develop
> 
> 
> > my-project@0.1.0 build C:\Development\sandbox\my-project
> > strapi build "--no-optimization"
> 
> Building your admin UI with development configuration ...
> 
> √ Webpack
>   Compiled successfully in 21.70s
> 
> Running your Strapi application.
> 
> > my-project@0.1.0 develop C:\Development\sandbox\my-project
> > strapi develop
> 
> [2021-01-22T19:52:29.455Z] info File created: C:\Development\sandbox\my-project\extensions\users-permissions\config\jwt.js
> 
>  Project information
> 
> ┌────────────────────┬──────────────────────────────────────────────────┐
> │ Time               │ Fri Jan 22 2021 13:52:30 GMT-0600 (Central Stan… │
> │ Launched in        │ 6417 ms                                          │
> │ Environment        │ development                                      │
> │ Process PID        │ 17332                                            │
> │ Version            │ 3.4.4 (node v14.15.1)                            │
> │ Edition            │ Community                                        │
> └────────────────────┴──────────────────────────────────────────────────┘
> 
>  Actions available
> 
> One more thing...
> Create your first administrator 💻 by going to the administration panel at:
> 
> ┌─────────────────────────────┐
> │ http://localhost:1337/admin │
> └─────────────────────────────┘
> 
> [2021-01-22T19:52:31.050Z] warn ⚠️  The admin panel is unavailable... Impossible to open it in the browser.

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.4
- Database: SQLite (quickstart)
- Operating system: Windows 10 Version 20H2 (OS Build 19042.746)

**Comment by derrickmehaffy** [comment]
Can you please check your project folder and see if there is an existing `build` folder?

**Comment by sregdorr** [comment]
Thanks for the quick response!

Yes there is

![image](https://user-images.githubusercontent.com/32646119/105539429-597d7a00-5cba-11eb-8c04-4fefd67b2744.png)

**Comment by derrickmehaffy** [comment]
Tested on:
- OS Name	Microsoft Windows 10 Pro
- Version	10.0.19042 Build 19042

Can't reproduce:

![image](https://user-images.githubusercontent.com/8593673/105539492-0dc6d280-5cb2-11eb-8ac0-8bc9eeddd97d.png)

**Comment by derrickmehaffy** [comment]
Can you try rebuilding the admin and starting the application manually:
- either `npm run build -- --clean` or `yarn build --clean`
- then `npm run develop` or `yarn develop`

**Comment by sregdorr** [comment]
Unfortunately, that didn't seem to work...

![image](https://user-images.githubusercontent.com/32646119/105539949-1243b900-5cbb-11eb-8aa4-304b54e92bb8.png)

**Comment by derrickmehaffy** [comment]
That is really odd :thinking: I've tested 3 different windows machines and can't reproduce that.

**Comment by derrickmehaffy** [comment]
This might sound really dumb, but can you test in powershell instead of cmd?

**Comment by sregdorr** [comment]
I deleted the old stuff and started over.
Still no go...

![image](https://user-images.githubusercontent.com/32646119/105541285-25f01f00-5cbd-11eb-94ab-b297860aab8b.png)

**Comment by sregdorr** [comment]
FYI, you're right I was using cmd before. Both are black on my machine.

**Comment by sregdorr** [comment]
Interesting... I disconnected from my company's VPN and everything worked! Not much of a networking guy, so I'm not sure why that was causing issues, but it's working now. Thanks for your time.

**Comment by derrickmehaffy** [comment]
That's really odd, could be because it was trying to bind to `0.0.0.0` instead of `127.0.0.1` and your company's VPN blocks local resources?
