### ISSUE TITLE
Migrate project to ESM

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#9197]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

ECMAScript modules are the official standard format to package JavaScript code.

And now that [Node.js supports it](https://nodejs.org/api/esm.html), it would be great to leave CJS behind.

---

One interesting reading: [Get Ready For ESM by Sindre Sorhus
](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77)

>At the end of April 2021, Node.js 10 will be end-of-life, which means that package maintainers can target Node.js 12. This Node.js version has full support for JavaScript Modules, also known as ESM.

**Comment by derrickmehaffy** [comment]
> And now that Node.js supports it, it would be great to leave CJS behind.

This is only in node v15+ and we don't support odd versions of node, the next supported version will be v16. I'll leave the feature request here, however it's highly unlikely we will adopt a new coding standard right as support is released. That would not be keeping stability and security in mind to migrate over to a newly supported system right as it's released.

**Comment by abdonrd** [comment]
No, it's from Node v12.

And it has been a long time before it is released as stable.

**Comment by abdonrd** [comment]
One interesting reading: [Get Ready For ESM by Sindre Sorhus
](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77)

>At the end of April 2021, Node.js 10 will be end-of-life, which means that package maintainers can target Node.js 12. This Node.js version has full support for JavaScript Modules, also known as ESM.

**Comment by derrickmehaffy** [comment]
Many of the features listed in the Node documentation list these as:

> Stability: 1 - Experimental. The feature is not subject to Semantic Versioning rules. Non-backward compatible changes or removal may occur in any future release. Use of the feature is not recommended in production environments.

**Comment by abdonrd** [comment]
Well, the experimental are:

- **`import.meta.resolve(specifier[, parent])`** - If Strapi needed it, there are a ponyfill
- **JSON modules** - Finally at Stage 3! https://twitter.com/MylesBorins/status/1354085367377522695
- **Wasm modules** - Strapi is not using it
- **Top-level await** - Strapi is not using it

**Comment by abdonrd** [comment]
Maybe it could be interesting for v4?

**Comment by abdonrd** [comment]
Once Node.js 16 becomes LTS, it will become **a third LTS version with native ES modules support**.

I want to share an interesting gist from Sindre Sorhus about: [Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Comment by derrickmehaffy** [comment]
We will be adding support for Node v16 with the release of Strapi v4 @abdonrd 

It's unlikely we will move over to ESM as it require far more rewrites than we have already done in the v4. Maybe in the future (like v5 or v6) but for now it doesn't provide enough benefit to justify the monumental amount of work it would require.

**Comment by derrickmehaffy** [comment]
After reviewing this with the product managers, it was decided that we don't intend to work on this in the future. At least not at this time.

So, I wanted to say thank you for the feature request but for this one I'll mark it as closed.

**Comment by dzcpy** [comment]
Node.js has envoluted to v18 now. Shall we always stay at Node 10?
Strapi is a great CMS, but it lacks a lot of advantages of features that every modern projects is equipted now. For example, ESM, TypeScript, proper eslint / prettier setup. I hope this situation can be improved in the future.

**Comment by derrickmehaffy** [comment]
> Node.js has envoluted to v18 now. Shall we always stay at Node 10? Strapi is a great CMS, but it lacks a lot of advantages of features that every modern projects is now equipted. For example, ESM, TypeScript, proper eslint / prettier setup. I hope this situation can be improved in the future.

Typescript is already in progress and we have default eslint and prettier setup already for all new projects. We opted not to rewrite the core in ESM is all. If you want to test out Typescript feel free to play with the v4.2.x beta releases
