### ISSUE TITLE
MongoClient deprecation warning

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#9198]
### Describe the bug

I get this error in the terminal:

>(node:44216) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Steps to reproduce the behavior

1. Run: `npx create-strapi-app freestylestats-api --use-npm`
2. Fill the fields
3. See the error

### Expected behavior

Not warning

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: v3.4.4
- Database: MongoDB
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
I could of swore we already included this a while back now as the default for the mongoose database.js template....

**Comment by Tronathon** [comment]
Also encountering the same issue

Node version - v10.16.3
NPM version - 6.9
Database - MongoDB
OS - Mac Mojave

**Comment by Tronathon** [comment]
It was actually an authentication error for me. All installed and working for me now.

**Comment by derrickmehaffy** [comment]
Confirmed on v3.5.1, issue only happens during connection test and not during application runtime.
