### ISSUE TITLE
postgres issue with has_and_belongs_to_many relationship

### ISSUE THREAD

**Issue by thg303** [strapi/strapi#9199]
### Describe the bug

Creating a has-and-belongs-to-many relationship between two entities with long-enough names breaks Strapi and prevents it from starting up.

### Steps to reproduce the behavior

1. Please clone [this repository](https://github.com/thg303/strapi_bug), read the README.md file and see it for yourself 
2. After the last commit Strapi does not start anymore.

### Expected behavior

it should run without any issue or the documentation should specify the limitation of maximum characters a user can have with PostgreSQL (the joint table name should not exceed 64 characters)

### System

- Node.js version: v10.17.0
- NPM version: 6.11.3
- Strapi version: 3.4.4
- Database: postgres
- Operating system: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

### Additional context
Maybe the bugfix applied at #3409 leads to a trimmed joint table name (64 characters)

**Comment by derrickmehaffy** [comment]
should be fixed in v4 minus components which is known here with a workaround: https://github.com/strapi/strapi/issues/12101
