### ISSUE TITLE
google provider return 302 error (error=request-compose%3A%20timeout)

### ISSUE THREAD

**Issue by naturalvoicer** [strapi/strapi#9201]
### Steps to reproduce the behavior

1. Go to 'http://localhost:1337/connect/google'
2. Click on 'Google Auth Button'
3. The link jump to 'http://localhost:3000/login?error=request-compose%3A%20timeout'

### Expected behavior

This link should jump to http://localhost:3000/login?access_token=xxxxxxxxxx
But return 302 error

### Screenshots
This is the section diagram of the request error：
![image](https://user-images.githubusercontent.com/70963486/105633903-44f5d900-5e96-11eb-91f0-1f8bd43ab76c.png)

This is my configuration：
![image](https://user-images.githubusercontent.com/70963486/105633711-2e9b4d80-5e95-11eb-9563-25c8bc28026d.png)
![image](https://user-images.githubusercontent.com/70963486/105633808-c6993700-5e95-11eb-82df-fcc89431d3b4.png)

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version:  3.4.3
- Database: mysql
- Operating system: windows10

**Comment by fjunqueira** [comment]
Also happens when using Cognito, and Discord, as seen [here](https://github.com/strapi/strapi/issues/8267).

Seems to be an issue related to running strapi locally, as the Cognito integration works in my production environment.

**Comment by derrickmehaffy** [comment]
Some providers state you can't use localhost so in some cases you have to use something like ngrok.

I'm unable to reproduce this but based on the information @fjunqueira mentioned it's most likely an environment issue I recommend we move this convo to the forum: https://forum.strapi.io
