### ISSUE TITLE
Cannot save 'unique relation' using a component

### ISSUE THREAD

**Issue by drullandev** [strapi/strapi#9220]
For a multilingual contents purpose, I'm work-arounding creating a component only including a 'title', a unique 'language' selector and a rich textarea 'content'. This is used attached to an 'Articles' collection.

I try to save these content rows, BUT the 'language' relation doesn't persist on DB or seems unsaved, and I cannot find the relations browsers ('Details' link) between both collections ('languages' and 'sub-articles').

Is a nice approach to set the multilingual risk, so nice idea to forget or avoid. And would be really nice to get this ability from Strapi to my project.

I hope this is possible with your help!!

### Steps to reproduce the behavior
- Create a 'languages' collection with 2 text columns 'tag' and 'label', enough with es_es:Spanish and en_uk:English.
- Create a component named 'Multicontent' with a text 'title' (multilingual) input, a relational link with 'language' viewing language label and a rich text textarea for extra writing content to locate.
- Create 'Articles' collection with a simple text as the title and the Multicontent component.
- Create new 'Article' and try to put there some content AND SELECT A LANGUAGE.
- When you push 'save' and in a totally replied context, this type of selectors BECOME DEFAULT again and again.
- The behavior becomes inconsistent and silly.

### Expected behavior
- Of course, I pretend a healthy interconexion between this kind of 'sucontents' under this component mask and the selected 'languages' as usuall 1-to-N (where n=2 and rows=2 inside 1 article)

### Screenshots
- 'The image' is: you try to select one lang to each row, you push 'save' and this language selectors turn back default again. Sorry

### Code snippets
- No code changes anywhere, only requires this collections to try.

### System
- common updated to last environment with all the requirements running (there are no errors coming on command line tail)

If someone can help I will be really appreciated! Looks like a nice way to make easy multilingual structure not that deep to be impossible to accomplish with this logic distribution.

**Comment by derrickmehaffy** [comment]
Hi @drullandev I think this is more about model design and structure than an actual bug (please do correct me if I'm wrong) and in that case I think this would be a better topic for our forum: https://forum.strapi.io

Going to mark this one as closed for now, but please do open a thread and we can discuss a bit more there.
