### ISSUE TITLE
Enum value limit (or lack of a proper message)

### ISSUE THREAD

**Issue by AdrianoCahete** [strapi/strapi#9221]
### Describe the bug
When you have a long list of enums, the message is vague `The value does not match the regex.`

### Steps to reproduce the behavior
1. Go to Collection
2. Create a new Enum
3. Add the following list as a value:
```
200
300
400
500
600
700
800
900
1000
```
4. The UI shows a `The value does not match the regex.` error.

### Expected behavior
Either show a clear message or display the limitation (refers to #7904 ?) before.

### Screenshots
![image](https://user-images.githubusercontent.com/37474/105799869-48f82880-5f74-11eb-86d5-ecf1beb3cea5.png)

### System
- Strapi version: v3.4.4
- Database: (there's a way to find this on UI? I'm running from the default CLI starter, locally)
- Operating system: Windows 10 x64

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7904
