### ISSUE TITLE
Relationship to self into a component leads to strapi crash, and corrupted database.

### ISSUE THREAD

**Issue by Norbz** [strapi/strapi#9224]
## Bug report

Hello,

I've found a case where adding a relationship to self leads to an infinite loop, which makes strapi unable to responds until manually restarted.
The worst thing is that afterwards, the database is "corrupted" in the sense that the relationship his written in base an any attempt to view and edit the faulty content-type instance leads to strapi crashing again.

### Describe the bug

This happens when the relationship is set in a component.

Let say I have a `Project` content-type with a `FeaturedProject` component.
In order to be able to restrict the number of featured project, I can't rely on relationship, so I rely on a repeatable component instead, `FeaturedProjectItem`.

to sum up : 
`Project` can contain a `FeaturedProject` component
`FeaturedProject` contains repeatable `FeaturedProjectItems`
`FeaturedProjectItems` contains a single  relationship to `Project`

### Steps to reproduce the behavior
With the previous Content-Types set up :
1. Create a project, "Project 1". At this point, you can't add a relationship to self as you didn't saved it already
2. Save "Project 1"
3. Edit "Project 1", add a `FeaturedProject` component
4. Inside the `FeaturedProject` component, add a `FeaturedProjectItem`
5. Add a relationship to self
6. Save
7. ----> Strapi will stop responding from here
8. Kill and restart strapi
9. Try to edit "Project 1"
10. ----> Strapi will stop responding again

### Expected behavior
Content-type should be saved without crashing the strapi process.

### Screenshots
<img width="1020" alt="insideProject" src="https://user-images.githubusercontent.com/6388929/105830012-48d44900-5fc5-11eb-8648-e6528bf8eb6d.png">
<img width="914" alt="ProjectRelationship" src="https://user-images.githubusercontent.com/6388929/105830004-470a8580-5fc5-11eb-8f0d-9aef6b793cfa.png">

### Code snippets
`Project` model
```
{
  "kind": "collectionType",
  "collectionName": "projects",
  "info": {
    "name": "Project",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "featured": {
      "type": "component",
      "repeatable": false,
      "component": "block.featured-project"
    }
  }
}

```

`FeaturedProject` component
```
{
  "collectionName": "components_block_featured_project",
  "info": {
    "name": "FeaturedProject",
    "icon": "copy",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "projects": {
      "type": "component",
      "repeatable": true,
      "component": "struct.project-item",
      "max": 2
    }
  }
}

```

`FeaturedProjectItem` component
```
{
  "collectionName": "components_struct_project_items",
  "info": {
    "name": "projectItem",
    "icon": "file",
    "description": ""
  },
  "options": {},
  "attributes": {
    "project": {
      "model": "project"
    }
  }
}

```

### System
- Node.js version: `12.x` 
- NPM version: `6.14.x`
- Strapi version: `3.4.4`
- Database: `MongoDB, 4.2.3`
- Operating system: `MacOS Catalina`, `Ubuntu 20.04`

### Additional context
1. The need to work with components and repeatable components initially comes from the fact that you can restrict the number of repeatable component instance, but not the number of relationships.
2. Only tried with MongoDB, no SQL database
3. Initially had the bug in Strapi `3.3.4` but the latest version also have this issue.
4. Feel free to ping me on Slack if needed (@Nicolas (Nicolas Ch))

**Comment by derrickmehaffy** [comment]
Confirmed that this happens on all versions with components and only happens with a relationship in a component in a self-referencing relationship. There is no intended use-case to self-reference itself but it can happen on accident causing the "corruption" of the database leading to a hard failure and requires manual cleanup.
