### ISSUE TITLE
Setup strapi in a sub-directory: admin assets fail to load

### ISSUE THREAD

**Issue by gustavpursche** [strapi/strapi#9225]
## Bug report

I'm currently trying to setup strapi in a sub-directory, which seems to fail because the assets aren't loading.

### Describe the bug

The setup look like this:

```
// config/server.js
module.exports = ({ env }) => ({
  host: '0.0.0.0',
  port: 1338,
  url: "[URL]/mc",
  admin: {
    url: '/admin'
  }
});
```

All requests to `/mc` are routed to `0.0.0.0:1338`. If I now visit `[URL]/mc/admin` I see the debug message:

```
[2021-01-26T11:54:52.212Z] debug GET /admin (3 ms) 200
```

but the assets are still loaded from:

`[URL]/admin/runtime~main.1aecfe8e.js` (instead of `/mc/admin/runtime~main.1aecfe8e.js`)

### Expected behavior

The assets should be loaded from the sub-directory, in my case:

`[URL]/mc/admin`

### System

- Node.js version: 12
- NPM version:
- Strapi version: 3.4.4
- Database: mysql
- Operating system: centos

### Additional context

I have tried to use an absolute URL in

```
// config/server.js
module.exports = ({ env }) => ({
  host: '0.0.0.0',
  port: 1338,
  url: "[URL]/mc",
  admin: {
    url: '[URL]/mc/admin'
  }
});
```

but the assets are still loaded from the same path.

**Comment by derrickmehaffy** [comment]
> url: '/admin'

Remove the admin URL as this isn't needed. Keep in mind you will need to use a proxy like Nginx, HAProxy, Traefik, ect to do sub-folder based proxying as you need to trip the route prefix before it reaches the Strapi Backend.

You can find some of the guides for this on our documentation.
https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#optional-software-guides

---

Also there is a known bug with modifying the "name" of the admin panel route, see: https://github.com/strapi/strapi/issues/8616

Marking as closed, please let me know if you think this was done in error.
