### ISSUE TITLE
Admin Panel Customization causing crash

### ISSUE THREAD

**Issue by acalvino4** [strapi/strapi#9228]
## Bug report

Strapi has a [documentation](https://strapi.io/documentation/developer-docs/latest/admin-panel/customization.html#development-mode) page outlining steps for customizing the admin panel. I followed these steps to override the file at `admin/src/containers/Users/ListPage/index.js`, copying the file to the same directory in my project. Without changing anything within the folder, when I load the route that uses this file. - `/admin/settings/users`, the page fails to load and I get a bunch of (very unhelpful) errors in the console.

### Steps to reproduce the behavior

1. Create `admin` folder in project directory
2. Copy `node_modules/strapi-admin/admin/src/containers/Users/ListPage/index.js` directly to `/admin/src/containers/Users/ListPage/index.js` in your project directory.
3. `npm run build && npm run develop --watch-admin`
4. navigate to `http://localhost:1337/admin/settings/users` (change port as appropriate)
5. observe a blank page, and errors in the console

### Expected behavior

The page should load as it did before the file addition.

### Screenshots

![image](https://user-images.githubusercontent.com/43254861/105890247-5a6d1f00-5fcc-11eb-9506-18be1b382aa4.png)

### Seemingly Useless Console Errors:

I am running a dev environment, btw, so that's not the reason I'm not seeing the 'full errors and additional helpful warnings'.

```
react_devtools_backend.js:2430 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Cl (main.6084e9ee.chunk.js:1)
    at f (main.6084e9ee.chunk.js:1)
    at h (main.6084e9ee.chunk.js:1)
    at main.6084e9ee.chunk.js:1
    at Oi (main.6084e9ee.chunk.js:1)
    at vc (main.6084e9ee.chunk.js:1)
    at sl (main.6084e9ee.chunk.js:1)
    at cl (main.6084e9ee.chunk.js:1)
    at Xc (main.6084e9ee.chunk.js:1)
    at main.6084e9ee.chunk.js:1
overrideMethod @ react_devtools_backend.js:2430
ec @ main.6084e9ee.chunk.js:1
a.componentDidCatch.n.callback @ main.6084e9ee.chunk.js:1
fa @ main.6084e9ee.chunk.js:1
ac @ main.6084e9ee.chunk.js:1
pl @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
fl @ main.6084e9ee.chunk.js:1
Xc @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
Yo @ main.6084e9ee.chunk.js:1
Go @ main.6084e9ee.chunk.js:1
Zc @ main.6084e9ee.chunk.js:1
hi @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
s @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
re @ main.6084e9ee.chunk.js:1
i @ main.6084e9ee.chunk.js:1
Promise.then (async)
re @ main.6084e9ee.chunk.js:1
i @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
oc @ main.6084e9ee.chunk.js:1
vl @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
hl @ main.6084e9ee.chunk.js:1
Xc @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
Yo @ main.6084e9ee.chunk.js:1
Go @ main.6084e9ee.chunk.js:1
Zc @ main.6084e9ee.chunk.js:1
hi @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
s @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
n @ main.6084e9ee.chunk.js:1
c @ main.6084e9ee.chunk.js:1
Promise.then (async)
n @ main.6084e9ee.chunk.js:1
c @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
oc @ main.6084e9ee.chunk.js:1
vl @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
hl @ main.6084e9ee.chunk.js:1
Xc @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
Yo @ main.6084e9ee.chunk.js:1
Go @ main.6084e9ee.chunk.js:1
Zc @ main.6084e9ee.chunk.js:1
hi @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
s @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
re @ main.6084e9ee.chunk.js:1
i @ main.6084e9ee.chunk.js:1
Promise.then (async)
re @ main.6084e9ee.chunk.js:1
i @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
oc @ main.6084e9ee.chunk.js:1
vl @ main.6084e9ee.chunk.js:1
t.unstable_runWithPriority @ main.6084e9ee.chunk.js:1
Uo @ main.6084e9ee.chunk.js:1
hl @ main.6084e9ee.chunk.js:1
(anonymous) @ main.6084e9ee.chunk.js:1
R @ main.6084e9ee.chunk.js:1
A.port1.onmessage @ main.6084e9ee.chunk.js:1
main.6084e9ee.chunk.js:1 An error has occured
main.6084e9ee.chunk.js:1 --------------------
main.6084e9ee.chunk.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Cl (main.6084e9ee.chunk.js:1)
    at f (main.6084e9ee.chunk.js:1)
    at h (main.6084e9ee.chunk.js:1)
    at main.6084e9ee.chunk.js:1
    at Oi (main.6084e9ee.chunk.js:1)
    at vc (main.6084e9ee.chunk.js:1)
    at sl (main.6084e9ee.chunk.js:1)
    at cl (main.6084e9ee.chunk.js:1)
    at Xc (main.6084e9ee.chunk.js:1)
    at main.6084e9ee.chunk.js:1
main.6084e9ee.chunk.js:1 Here is some infos
main.6084e9ee.chunk.js:1 {componentStack: "↵    in div↵    in A↵    in fc↵    in l↵    in t↵ …IntlProvider↵    in n↵    in A↵    in _l↵    in l"}
```

### System

- Node.js version: 14.8.0
- NPM version: 6.14.9
- Strapi version: 3.3.4
- Database: Postgres
- Operating system: MacOS 11.1

**Comment by derrickmehaffy** [comment]
This is most likely related to the relative paths used during an import, see the following example: https://github.com/strapi/strapi/blob/3f63902d4b471c4bafc571789970793783352bd8/packages/strapi-admin/admin/src/containers/Users/ListPage/index.js#L13-L16

Please note you do not need to copy the entire folder structure, only the fields you wish to modify. The build process will automatically pull in the rest, however it will not resolve the relative paths for you; those will need to be modified.

I'm marking this as closed as it's not directly an issue with the project code but the result of user modification, in cases like this please use our forum: https://forum.strapi.io

**Comment by acalvino4** [comment]
Thanks for the response @derrickmehaffy. I have to say it still seems like a bug to me insofar as it doesn't seem to match up with the documentation, which implies that files in my project's `admin` folder are basically drop-in replacements for files at the same path in `node_modules/strapi-admin/admin`

> For example, to change the top-left displayed admin panel's color, copy the ./node_modules/strapi-admin/admin/src/components/LeftMenu/LeftMenuHeader folder to ./admin/src/components/LeftMenu/LeftMenuHeader and change the styles inside ./admin/src/components/LeftMenu/LeftMenuHeader/Wrapper.js.

> Thus, you are replacing the files that would normally be in node_modules/strapi-admin/admin/src and directing them to admin/src/some/file/path.

This basically says "copy the [file]....[then] change the styles....[whereby which] you are replacing the files...."
This to me pretty much says that we should be able to do what I was doing without issue. If that is not the intended behavior, I think the documentation needs an update.

Can you explain further what you mean by "Please note you do not need to copy the entire folder structure, only the fields you wish to modify." I don't think I understand, since, as I pointed out above, I perceive myself to be following the documentation to a T.

To be clear, I did not modify any code in the copied file, so the only sense in which this is 'user modification' is in the copying of the file (which is perhaps what you meant, but I'm not sure).

**Comment by acalvino4** [comment]
Also, simply updating the paths from relative to absolute, such at replacing
```js
import PageTitle from '../../../components/SettingsPageTitle';
import { useSettingsHeaderSearchContext } from '../../../hooks';
```
with
```js
import PageTitle from 'strapi-admin/admin/src/components/SettingsPageTitle';
import { useSettingsHeaderSearchContext } from 'strapi-admin/admin/src/hooks';
```
does not work (without potentially more configuration) as the main project does not have a class loader configured to parse jsx in js files. I can of course rename it as a .jsx file, but then it doesn't match the file name in the strapi-admin package and therefore won't replace it.

In short, it seems to me that either a) this is a bug, as it requires undocumented hacking around to make it work, and/or b) the customization documentation is incomplete because it requires undocumented hacking around to make the concept work or c) I am missing something obvious, in which case I am happy to be informed.

**Comment by derrickmehaffy** [comment]
You make a good point, as I'm not sure yet, let me ping @soupette and @HichamELBSI to see if they can clarify. 

Based their response, we can determine if it's a bug.

(Also I meant files not fields, its been one of those days, fingers moving slower than brain)

**Comment by soupette** [comment]
Hello @acalvino4, I have just try to reproduce your issue and everything seems to work fine on my side. 
What modifications did you make to the copied file?

**Comment by acalvino4** [comment]
I didn't think I made any modifications.....but upon re-copying the file it all seems to be working. I am not sure what happened before. Thank you for looking into it and taking the request seriously - it seems I accidentally modified something. This can definitely stay closed or even get deleted since I don't think there is any helpful information giving our findings.
