### ISSUE TITLE
Enum field refusing numbers

### ISSUE THREAD

**Issue by dr-zappik** [strapi/strapi#9229]
### Describe the bug

In Content-type-builder the enum type field doesn't accept numeric entry.

### Steps to reproduce the behavior

1. Go to 'Content-type-builder'
2. Click on 'ADD ANOTHER FIELD'
3. Try to enter a [1-9] input anywhere in the field (inside a string, alone, in a new line, etc)
4. Click "finish" green button

### Expected behavior

having the possibility to enter numeric values in the enumeration

### Screenshots

https://nimb.ws/MvWRbg

### System

- Node.js version: 14-15-1
- NPM version:
- Strapi version: Strapi v3.4.5 — Community Edition
- Database: SQLite
- Operating system: Windows

### Additional context

Chrome browser

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7904
