### ISSUE TITLE
MySQL UTF8 problem - remove 🔑

### ISSUE THREAD

**Issue by whodevrim** [strapi/strapi#923]
https://github.com/strapi/strapi/blob/6934661845b375a6f4dd7b9f1e6f43ea32ee438a/packages/strapi-plugin-users-permissions/config/functions/bootstrap.js#L93

we get a UTF 8 error when lifting the project to the foot because of the key mark on the line. the problem will be solved if you remove the key mark.

**Comment by lauriejim** [comment]
Hey @whodevrim can you remove  🔑 from the template and submit a PR please.

Will appreciate to see you as Strapi contributor.
