### ISSUE TITLE
Unable to view complete name of uploaded assets 

### ISSUE THREAD

**Issue by msaeed99** [strapi/strapi#9231]
Full asset name is not displayable, please check below sample
![image](https://user-images.githubusercontent.com/71661406/105918765-9796e700-6088-11eb-9cee-cd2e53f72ccf.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
