### ISSUE TITLE
Route prefix:  Route prefix false does not remove the plugin name but prepend 'false' at the route.

### ISSUE THREAD

**Issue by iAmPriyam** [strapi/strapi#9232]
### Bug description
According to the Strapi documentation given at:
https://strapi.io/documentation/developer-docs/latest/plugin-development/backend-development.html#routes

As stated under the **Route prefix** section, when the prefix value is set to false the default path prefix is disabled. It did not happen when I tried overriding the path for the POST method of the upload plugin, rather it changed the path to **'false/api/v1/upoad'**.

### Steps to reproduce the behavior
Renaming the route of the upload plugin. In the file **/node_modules/strapi-plugin-upload/config/routes.json**, set the **prefix** under the **config** object as **false** and set the **path** to be your desired value. 

![Code change](https://user-images.githubusercontent.com/30063255/105964180-d8eabf00-60a7-11eb-96c8-8cbda2a4bcfb.png)

The result of the following changes was that the path was prepended by the string 'false'
![Bug](https://user-images.githubusercontent.com/30063255/105964765-a9888200-60a8-11eb-8f4f-61c060c7cea5.png)

### Expected behavior

The expected behavior was that the name of the plugin, which is the default prefix should be removed and the provided path is set.

![Expected change](https://user-images.githubusercontent.com/30063255/105965339-477c4c80-60a9-11eb-985c-530880966836.png)

### System

- Node.js version: v12.13.0
- NPM version: 6.14.5
- Strapi version: 3.4.3
- Database: MongoDB
- Operating system: Ubuntu 18.04

**Comment by alexandrebodin** [comment]
Hi, You must set it to an empty string :) @derrickmehaffy ping for the docs issue ;)

**Comment by iAmPriyam** [comment]
Hi, @alexandrebodin! Thanks for the quick solution. Any update on API versioning?

@derrickmehaffy Please update the docs! :smiley:

**Comment by derrickmehaffy** [comment]
@alexandrebodin do we just need to remove this from the docs or how is it implemented? (Looking at the gitblame these docs have existed since the beta version)

**Comment by alexandrebodin** [comment]
We can remove the false from the docs for now until we handle it in the code
