### ISSUE TITLE
useQueryParams ignores given initialParams when search query is set

### ISSUE THREAD

**Issue by ddhp** [strapi/strapi#9234]
### Describe the bug
Hi Strapi Team,
`useQueryParams` hook might ignore initialParams when location.search is not empty.
Is this expected?

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/admin/plugins/content-manager/collectionType/application::{model}.{modelname}?customquery=custom`

### Expected behavior

I am not sure what's the expected behavior, but if we pass custom search queries, the app would throw an exception

### Screenshots
<img width="1278" alt="スクリーンショット 2021-01-27 午後5 17 01" src="https://user-images.githubusercontent.com/1715380/105969810-9fc04800-60c3-11eb-9bd2-74b13f238e35.png">

### Code snippets
the exception is from [CustomTable/Header](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Headers/Header.js#L9), `_sort` is undefined, and it became undefined when [useQueryParams](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/hooks/useQueryParams/index.js#L16) find `location.search` is set without pagination related informations

Potential solution can be merging params
```js
    return {
      ...initialParams,
      ...parse(searchQuery),
    };
```

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.4.4
- Database: sqlite
- Operating system: OSX

### Additional context

We are trying to do naughty things by passing customized search query so this issue is raised. Thanks for your time looking this up!

**Comment by soupette** [comment]
I am closing this issue as it has already been fixed.
