### ISSUE TITLE
Uncaught TypeError: Cannot delete property 'regex' of #<Object>

### ISSUE THREAD

**Issue by shtelzerartem** [strapi/strapi#9236]
### Describe the bug

Getting error ```Uncaught TypeError: Cannot delete property 'regex' of #<Object>```, when trying to create or to save collection type item containing text field with regex validation.

### Steps to reproduce the behavior

1. Create collection type ```test```
2. Create field rgba_regex, set regex validation rule to ```rgba\(\d{1,3},\s?\d{1,3},\s?\d{1,3},\s?[0-1]\.\d+\)```, save it.
3. Open Test collection and try to create an item.

### Screenshots

![image](https://user-images.githubusercontent.com/20266461/106003200-a4343300-60ba-11eb-8783-e51bf04912b4.png)
![image](https://user-images.githubusercontent.com/20266461/106003443-e198c080-60ba-11eb-914a-5734f0105eaf.png)

### System

- Strapi version: v3.4.5
- Database: Mongo
- Operating system: Windows

### Additional context

Issue is happening in ```strapi-plugin-content-manager\admin\src\containers\EditViewDataManagerProvider\utils\schema.js``` in function ```createYupSchemaAttribute```. Because ```validations``` argument that is an object is read-only. We can do clone of it and then freely manipulate with it.

**Comment by jbgraug** [comment]
Temporary fix: Remove regex attributes from your models @

**Comment by CrushyChilli** [comment]
I have encountered it too, all I can do is just remove the regex attribute like jbgraug said

**Comment by CrushyChilli** [comment]
Is there any to solve the problem instead of avoiding any usage of regex?

**Comment by umbopepato** [comment]
> Is there any way to solve the problem instead of avoiding the usage of regex?
> I downgraded strapi, but the error still occurs.

@CrushyChilli `strapi build --clean` should help
