### ISSUE TITLE
Loose file relation on update content manager

### ISSUE THREAD

**Issue by NoahHahm** [strapi/strapi#924]
After uploading and saving the image with the latest strapi CONTENT MANAGER,
go to this post.
When you resave (modify) the post, the image is no longer linked.
If you change other fields without changing the image, the image is unlinked,
That's the problem.
Can not you keep existing image links even if fixes happen?

**Comment by lauriejim** [comment]
@NoahHahm Can you please follow the issue template with all needed informations.

We will take a look.

**Comment by lauriejim** [comment]
And I think it's the same issue as https://github.com/strapi/strapi/issues/825

**Comment by NoahHahm** [comment]
@lauriejim Register the one of the image, enter the post again and press the correction button, the image has been disconnected. Verification please.

**Comment by Aurelsicoko** [comment]
@NoahHahm I can reproduce it when the image field allows multiples files. I'm going to fix it today.

**Comment by NoahHahm** [comment]
@Aurelsicoko thank you.

**Comment by zhuang17** [comment]
@Aurelsicoko  @soupette  the issue is a little different on my side, can you help confirm this ?

file relations save successfully on update content manager which allow multiple files.

but single file relation save failed (`in UI show save succesfully, but don't actually store into db.`) when updating content manager which don't allows multiples files.
https://github.com/strapi/strapi/issues/1015

**Comment by lauriejim** [comment]
Yap it's fixed. did you migrate an application or it's a fresh new one ?

**Comment by BroTrue** [comment]
Got same problem. Create OneToOne relation between `users`(default) and `myContentType`. After updating any information at `myContentType`, relation gone... any ideas? its looks like bug.

**Comment by BroTrue** [comment]
Should I create new issue ?

**Comment by BroTrue** [comment]
But when I create relation 1to1 between `myContentType` and `myContentType2`, all is fine!

**Comment by lauriejim** [comment]
Yap, can you please create an issue.
