### ISSUE TITLE
STRAPI_TELEMETRY_DISABLED does not prevent telemetry from browser on admin pages

### ISSUE THREAD

**Issue by quentinhayot** [strapi/strapi#9240]
### Describe the bug

Running strapi with the environment variable `STRAPI_TELEMETRY_DISABLED` set to true should prevent any telemetry to be sent to strapi.io. 
In reality the browser is sending tracking data to https://analytics.strapi.io/track when visiting admin pages.

### Steps to reproduce the behavior

1. Add `STRAPI_TELEMETRY_DISABLED=true` in your env
2. Run strapi
3. Access http://localhost:1337/admin and check network activity

### Expected behavior

No telemetry should appear in the network activity.

### System

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.4.1
- Database: MySQL || SQlite
- Operating system: AWS Fargate || MacOS 10.15.7

**Comment by derrickmehaffy** [comment]
Hello,

Please see: https://strapi.io/documentation/developer-docs/latest/getting-started/usage-information.html

**Comment by quentinhayot** [comment]
Hmm, I guess that the env variable only affects the telemetry directly sent by the server then ?

https://github.com/strapi/strapi/blob/aad1c2fa032a76932a27729345501827bd05a41b/packages/strapi/lib/services/metrics/index.js#L27

**Comment by derrickmehaffy** [comment]
Variable is set in the same location as the UUID, you will most like likely need to set this variable during build time as well:

https://github.com/strapi/strapi/blob/3f63902d4b471c4bafc571789970793783352bd8/packages/strapi/lib/services/metrics/index.js#L27

**Comment by quentinhayot** [comment]
Removing the uuid from the package.json does prevent telemetry.
The env variable doesn't (at least when sent from the browser). I tried this:

```
$ STRAPI_TELEMETRY_DISABLED=true
$ npm run build
```

**Comment by derrickmehaffy** [comment]
I was able to confirm this on v3.4.5. Thank you @quentinhayot

**Comment by derrickmehaffy** [comment]
Confirmed this on v4.0.6

**Comment by ronronscelestes** [comment]
Hi @quentinhayot! Thank you for taking the time to share this issue, we will look into it! 😊

**Comment by derrickmehaffy** [comment]
Confirmed v4.2.3
