### ISSUE TITLE
Published Strapi page works, but fails to show Admin page after login

### ISSUE THREAD

**Issue by Seanmclem** [strapi/strapi#9241]
Node: v12.20.0
Npm: 6.14.8
Strapi: 3.4.1
Ubuntu 20.04.1 LTS via Amazon EC2 instance
nginx

## Description
I am experiencing a very similar issue to [this one](https://github.com/strapi/strapi/issues/4834). However, I am very sure I have run `npm run build` or `strapi build`

I am able to use strapi locally, including on the admin page.

I have it also published to an Amazon EC2 instance. I followed the documentation on this pretty closely, although it kind of falls apart near the end there and mostly just links off to external docs, but I was able to get nginx setup, custom domain, SSL, etc.

## Reproduce:
When I go to my instance, which is at api.my website.com , I am able to see it's running, I am able to go to `/admin` and use my credentials to log-in. I can hit all the api endpoints.

## Bug:
When it logs in and redirects, I am able to see a loading spinner, and sometimes I can see the admin page _flash_ on screen. But then it just goes to a white screen. Sometimes still with the `A new version of Strapi is available` message floating there.

In the sources tab I can see the files for the admin page have all loaded. 

<img width="332" alt="Screen Shot 2021-01-27 at 4 08 11 PM" src="https://user-images.githubusercontent.com/6831540/106054490-1b1cfc00-60ba-11eb-9072-5ba84aba6162.png">

When I go to the console screen, I do see some strange errors. 

<img width="861" alt="Screen Shot 2021-01-27 at 4 09 04 PM" src="https://user-images.githubusercontent.com/6831540/106054532-2bcd7200-60ba-11eb-89a2-951d5af34f20.png">

Consisting mostly of, `EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed`
This also shows on the dev-tools Issues page.  But as a CSP error under Security.

<img width="861" alt="Screen Shot 2021-01-27 at 4 11 45 PM" src="https://user-images.githubusercontent.com/6831540/106054696-66cfa580-60ba-11eb-80ea-41a4e73a8c08.png">

Any ideas on how I can get this to work? It's nice that I can run it locally, but being able to access it remotely would really help.
Thanks!

**Comment by derrickmehaffy** [comment]
@Seanmclem have you set the `./config/server.js` url key? (or any of the `./config/env/*/server.js` depending on if you are using our environment system)

See: https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#server

Are you using any proxy such as Nginx? Also have you made any custom modifications to the admin panel?

**Comment by Seanmclem** [comment]
Yes. I set up `./config/server.js` I gave `ADMIN_JWT_SECRET` a random uninqe key, and haven't really changed it since my initial commit. It uses port 1337 still. [This guide](https://strapi.io/documentation/developer-docs/latest/deployment/amazon-aws.html) mentions changing it, but not where or how.   It looks like this
```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337), 
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'myRandomKey'),
    },
  },
});

```

I am using Nginx. [This guide](https://strapi.io/documentation/developer-docs/latest/deployment/amazon-aws.html), is pretty sparse on details about setting up nginx, and links to external guides. So I'm not sure I did it right. I can put my nginx config files if that helps?

Heres my /sites-available config for nginx
```javascript
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             api.seanmclements.com;

    # SSL
    ssl_certificate         /etc/letsencrypt/live/api.seanmclements.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/api.seanmclements.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.seanmclements.com/chain.pem;

    # security
    include                 nginxconfig.io/security.conf;

    # reverse proxy
    location / {
        proxy_pass http://127.0.0.1:1337;
        include    nginxconfig.io/proxy.conf;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }

    location /hooks/ {
        proxy_pass http://127.0.0.1:8080/hooks;
    }

    # additional config
    include nginxconfig.io/general.conf;
}

# subdomains redirect
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             *.api.seanmclements.com;

    # SSL
    ssl_certificate         /etc/letsencrypt/live/api.seanmclements.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/api.seanmclements.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.seanmclements.com/chain.pem;
    return                  301 https://api.seanmclements.com$request_uri;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name .api.seanmclements.com;
    include     nginxconfig.io/letsencrypt.conf;

    location / {
        return 301 https://api.seanmclements.com$request_uri;
    }
}

```

**Comment by derrickmehaffy** [comment]
How about giving this one a shot:

https://strapi.io/documentation/developer-docs/latest/deployment/nginx-proxy.html

**Comment by Seanmclem** [comment]
@derrickmehaffy Reading it now, but does this error not seem like the cause `EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed`

I get a similar error is Safari. Threads like this one, [https://github.com/microsoft/Mezzurite-DevTools/issues/27](https://github.com/microsoft/Mezzurite-DevTools/issues/27) , make it seem like 1 `eval()` is enough to cause an issue, and I do see 1 in my `build/main.8f598d59.chunk.js` file.

**Comment by derrickmehaffy** [comment]
In your server.js, you need the change the url key to your public domain address and rebuild the admin panel (see the bottom most section of the most recent doc link I gave you.)

**Comment by Seanmclem** [comment]
> In your server.js, you need the change the url key to your public domain address and rebuild the admin panel (see the bottom most section of the most recent doc link I gave you.)

Thanks, I do see that part. I noticed it's also missing the `admin > auth > secret​: ​env​(​'ADMIN_JWT_SECRET'​, key) ` part. Do I take that out? Or maybe make it conditional by environment?

**Comment by Seanmclem** [comment]
@derrickmehaffy  Thanks, but I still get the same issue with no changes after deploying my changes

```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337), // maybe 80 / 8080 ?
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'my-unique-key'),
    },
  },
  url: 'https://api.mywebsite.com'
});
```

**Comment by derrickmehaffy** [comment]
Can you please give me a breakdown of your environment. I know you are on an EC2 instance but I need to have a few things clarified:

- Can you please provide your full Strapi Nginx virtual host config (the one you put in `/etc/nginx/sites-a*/`) omit any private information
- How are you running Strapi? (pm2?)
- Have you run a `sudo service nginx configtest` and did it return an `OK` status?
- If the above did not return an `OK` have you checked the Nginx error log at `/var/log/nginx/error.log`
- Is your project code somewhere public that I can look at?

I have done many many test deployments into AWS EC2 with proxying and even wrote the official Strapi AWS "one-click" (which we have yet to publish yet) code: https://github.com/strapi/one-click-deploy/tree/master/aws-ami

**Comment by derrickmehaffy** [comment]
If you want to see the exact steps it takes to create a new project (I understand you are deploying a project, so not all of these apply to you)

https://github.com/strapi/one-click-deploy/blob/master/aws-ami/configs/strapi/setup_strapi.sh
Here is the same Nginx Configs: https://github.com/strapi/one-click-deploy/tree/master/aws-ami/configs/nginx

**Comment by Seanmclem** [comment]
@derrickmehaffy Everything was fine. I was able to determine the issue is the `eval()` function-call in the build output. The one I'd mentioned was in my `main.chunk.js` file. The one cluttering the console with errors. 

I went into the main chunk file(s) in my build folder on my server, and replaced a `eval(duration+sign+60)` with just the number `100`. Since I don't know what else to replace it with, and the code block looked irrelevant to me. Something about a video duration.

I was able to successfully login and access my admin page on my server - only after replacing the `eval(duration+sign+60)` in these 2 main chunk files. The errors disappeared from the console.

So that seems to be the cause. This fix is obviously a short term solution. We'll need to find a way to keep the `eval()` out of the build output. I would consider this the actual bug for this issue.

**Comment by Seanmclem** [comment]
ok I found in `/etc/nginx/nginxconfig.io/security.conf` thst my `add_header Content-Security-Policy` does not include `unsafe-eval`... According to [this doc from Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src), including it there would "_Allows the use of eval() and similar methods for creating code from strings_"
So that might be my longer-term fix I suppose. I'll try it later today and report back

**Comment by Seanmclem** [comment]
ok, I updated `/etc/nginx/nginxconfig.io/security.conf` to include `unsafe-eval` in the `Content-Security-Policy` line after `https:`.
```
# security headers
add_header X-Frame-Options           "SAMEORIGIN" always;
add_header X-XSS-Protection          "1; mode=block" always;
add_header X-Content-Type-Options    "nosniff" always;
add_header Referrer-Policy           "no-referrer-when-downgrade" always;
add_header Content-Security-Policy   "default-src 'self' http: https: 'unsafe-eval' data: blob: 'unsafe-inline'" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# . files
location ~ /\.(?!well-known) {
    deny all;
}
```

This resolved my issue, without any of the other changes that were discussed. Although my issue is resolved -I think the real fix for this bug/issue would be to get the `eval()` out of the production build output. So I think this issue should stay open

**Comment by kearafallon** [comment]
Are there any new fixes to the Admin panel not working due to the runtime regenerator error?! I've been trying to solve this for weeks!

**Comment by drilon305** [comment]
Hello @[derrickmehaffy](https://github.com/derrickmehaffy) can you help me also have the same problem. I followed Zachary Reece course finished the project uploaded in aws says 'Server is running succesully' in production, but in admin panel just spinning ? my code are in my github profile: backend-mjellma. Thank you

**Comment by derrickmehaffy** [comment]
The recent comments are unrelated to this issue, please create new issues. The core issue mentioned in this issue should already be fixed in v4.
