### ISSUE TITLE
Media Content Type can be passed null in api though isRequired to true

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#9248]
### Steps to reproduce the behavior

1. Create a content type with Media as one of the field and turn isRequired to true.
2. Call the content type api without passing the media field
3. Even though the field is not passed, an entry will be created in database without any validation error

### Expected behavior

It should give validation error

### System

- Node.js version: 14.15.0
- NPM version: 6.14.5
- Strapi version:  3.4.5
- Database: sqlite
- Operating system: Linux and Windows , both

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/557
