### ISSUE TITLE
Heroku shows that an error occurd when you try to create fields in the Content Type

### ISSUE THREAD

**Issue by JonasJustus** [strapi/strapi#925]
Heroku shows that an error occurd when you try to create fields in the Content Type
Log doesnt show anything
same happens when you deploy it with the deploybutton from the website

Heroku should have the latest version of Node and npm

**Informations**
- **Node.js version**:
- **npm version**:
- **Strapi version**:
- **Database**:
- **Operating system**:

**What is the current behavior?**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**What is the expected behavior?**

---

- [ ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Please can you check heroku related issues and follow issue template before posting issue.

See here: https://github.com/strapi/strapi/issues/770
