### ISSUE TITLE
Insert values enumeration field

### ISSUE THREAD

**Issue by rfos** [strapi/strapi#9250]
When I'm inserting values for an enumeration field it doesn't accept values like 
Desktop
Laptop
Monitor
Switch
**Access Point**

Two words for the line cause and error and strapi don't allow me to save the field.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by derrickmehaffy** [comment]
Also duplicate: https://github.com/strapi/strapi/issues/7904
