### ISSUE TITLE
EACCES: permission denied, rmdir '/srv/strapi/strapi-development/.cache/plugins'

### ISSUE THREAD

**Issue by dailytravel** [strapi/strapi#9251]
Hi every body!

My strapi can not add more filed in Content-Type, also can not delete or install plugin. It's show error below when run with `pm2 logs strapi-development`.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-development@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-development@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/strapi/.npm/_logs/2021-01-28T06_56_50_876Z-debug.log
[Error: EACCES: permission denied, rmdir '/srv/strapi/strapi-development/.cache/plugins'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'rmdir',
  path: '/srv/strapi/strapi-development/.cache/plugins'
}

**Comment by derrickmehaffy** [comment]
EACCES Errors are a linux permissions issue, not a Strapi one. Please post for community support on our forum: https://forum.strapi.io

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
