### ISSUE TITLE
error MongoError: Aggregation stage not supported: '$lookup on multiple join conditions and uncorrelated subquery'

### ISSUE THREAD

**Issue by ddombrowsky** [strapi/strapi#9252]
### Describe the bug

The system throws an exception when trying to view any record.  For example, click on a collection type, then click on a record.  Devtools shows a 500 returned.  View the console messages on the server side.  The exception is there.

### Steps to reproduce the behavior

1. Log in to admin console (started with `strapi develop`)
2. Click on a content type
3. Click on a record
4. Server returns a 500 error. 
Server side error message:

```

2021-01-28T22:06:52.570-05:00 | [2021-01-29T03:06:52.570Z] error MongoError: Aggregation stage not supported: '$lookup on multiple join conditions and uncorrelated subquery'
-- | --
  | 2021-01-28T22:06:52.570-05:00 | at MessageStream.messageHandler (/srv/node_modules/strapi-connector-mongoose/node_modules/mongodb/lib/cmap/connection.js:268:20)
  | 2021-01-28T22:06:52.570-05:00 | at MessageStream.emit (events.js:314:20)
  | 2021-01-28T22:06:52.570-05:00 | at processIncomingData (/srv/node_modules/strapi-connector-mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
  | 2021-01-28T22:06:52.570-05:00 | at MessageStream._write (/srv/node_modules/strapi-connector-mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
  | 2021-01-28T22:06:52.570-05:00 | at doWrite (_stream_writable.js:403:12)
  | 2021-01-28T22:06:52.570-05:00 | at writeOrBuffer (_stream_writable.js:387:5)
  | 2021-01-28T22:06:52.570-05:00 | at MessageStream.Writable.write (_stream_writable.js:318:11)
  | 2021-01-28T22:06:52.570-05:00 | at TLSSocket.ondata (_stream_readable.js:718:22)
  | 2021-01-28T22:06:52.570-05:00 | at TLSSocket.emit (events.js:314:20)
  | 2021-01-28T22:06:52.570-05:00 | at addChunk (_stream_readable.js:297:12)
  | 2021-01-28T22:06:52.570-05:00 | at readableAddChunk (_stream_readable.js:272:9)
  | 2021-01-28T22:06:52.570-05:00 | at TLSSocket.Readable.push (_stream_readable.js:213:10)
  | 2021-01-28T22:06:52.570-05:00 | at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

### System

This is running in a docker container built from `strapi/strapi` on dockerhub.  Deployed to amazon ECS.

- Node.js version: 12.20
- NPM version:

```
{
  api: '0.1.0',
  npm: '6.14.10',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  http_parser: '2.9.4',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '72',
  napi: '7',
  nghttp2: '1.41.0',
  node: '12.20.1',
  openssl: '1.1.1i',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '7.8.279.23-node.45',
  zlib: '1.2.11'
}
```

- Strapi version: 3.4.5
- Database: Amazon Document DB
- Operating system: docker/linux

**Comment by derrickmehaffy** [comment]
> Database: Amazon Document DB

This is not a supported database, Amazon Document DB, while it says it's MongoDB compatible it's not actually MongoDB. We only test and support official versions of the various database platforms.

Please test your project on an official MongoDB server (Such as Atlas or a locally installed version)

**Comment by ddombrowsky** [comment]
bummer

**Comment by derrickmehaffy** [comment]
Going to mark as closed for now, if you hit the same issue on a MongoDB database please let me know and we can reopen this.

**Comment by ddombrowsky** [comment]
> Going to mark as closed for now, if you hit the same issue on a MongoDB database please let me know and we can reopen this.

Nah, it works fine with stock MongoDB.  I wish I had known this before I spent a day setting up Document DB in AWS.  Maybe a note in the documentation that `strapi-connector-mongoose` isn't compatible with Amazon's "MongoDB Compatible" database might be in order.  I'll just let the client know we have to switch databases.  No problem-o.

**Comment by derrickmehaffy** [comment]
Documentation: https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements

README: https://github.com/strapi/strapi#-requirements

While I do understand where you are coming from, I would rather avoid calling out specific of what we don't support (or that list could get quite long). Generally speaking we prefer to handle specifics of what we do support instead of the inverse. Glad to hear it works though ;)
