### ISSUE TITLE
Database cleanup after deleting fields.

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#9265]
### Describe the bug

After deleting a field from a Collection Type (`CT`), the field(s) are not removed from my Postgres database.

This leads to a number of issues.

For example, if the field that was deleted was a `non-null` field trying to create a new entry of the given `CT`, it will lead to an error preventing from creating due to the fact that there's a required field in the database.

### Reproduce

1. Create `CT`
2. Add a field that is Required
3. Delete the required field
4. Try programmatically create a new `CT` of the same kind.

### Expected

The field to be entirely removed from `CT`.

### Additional context

Similarly when renaming a field without deleting it, leads to unexpected behaviour as well.

Perhaps I'm missing something?

**Comment by derrickmehaffy** [comment]
Duplicate: #1114 

We plan to tackle this topic in Q3
