### ISSUE TITLE
Mongodb atlas connection problem

### ISSUE THREAD

**Issue by vipuluthaiah** [strapi/strapi#9267]
error Error Connecting to the mongo database .connection to 52.21.222.24:27017 closed We are working on a app .A local news app stack used Flutter and dart For c m s STRAPI.IO For editors to delete ,update news For deploying we were using HEROKU but same issue we faced .So now we are using AWS AND FOR DATABASE MONGOGODB ATLAS
![image](https://user-images.githubusercontent.com/45168922/106348874-a7643480-62ef-11eb-9ff2-5c84fab0ce1f.png)
![image](https://user-images.githubusercontent.com/45168922/106348880-ab905200-62ef-11eb-8e48-23bf62a3b339.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
