### ISSUE TITLE
Severe Bug in User Permissions Route Selection in Admin Panel

### ISSUE THREAD

**Issue by MaheshCasiraghi** [strapi/strapi#9269]
## Bug report

When using Postgres, every time the "Save" green button is pressed in order to change access to routes (endpoints) within the User Permission Interface in the Admin Panel (not the Administrator Panel, but in the User Permissions Plugin), entries are duplicated in the users-permissions_permission table, making in fact the functionality impossible, and randomly changing endpoints access (security issue).

### Steps to reproduce the behavior

Use Strapi Release 3.4.5, with Postgres (Bookshelf). Use the Strapi Admin Panel to change endpoints permissions within the User Permission Plugin (Settings). Change access (ticking and unticking checkboxes), and verify that multiple entries are created within the users-permissions_permission table, breaking the whole interface functionality.

### System

- Node.js version: v14
- NPM version: 6.4.10
- Strapi version: 3.4.5
- Database: Postgres 12
- Operating system: Ubuntu Server 20.04

**Comment by derrickmehaffy** [comment]
should be fixed in the v4
