### ISSUE TITLE
Amazon(AWS) SES  Email plugin not sending attachment.

### ISSUE THREAD

**Issue by AkshayMAnvekar** [strapi/strapi#9270]
### Describe the bug

 Strapi is not being able to send a text file attachment thru email using strapi-provider-email-amazon-ses. The email always arrives but without the file. The same code works in SendGrid. The emails are missing the attachments after switching to AWS SES.

### Steps to reproduce the behaviour

1. Install the plugin strapi-provider-email-amazon-ses
2. Configure the email plugin
3. Create an API and update the controller (see code snippets section)
4. Request the API by setting a valid email for receiving the message

### Expected behaviour

The Email should be sent with the attachment. Like it did in Sendgrid.

### Code snippets

```javascript
    //This is the controller
    const { body } = ctx.request;
    let bufferObj = Buffer.from(txtData, "utf8");
    let data = {
      to: body.email || body.to,
      from: process.env.AWS_SES_EMAIL,
      replyTo: process.env.AWS_SES_EMAIL,
      subject: body.subject,
      text: body.text,
      attachments: [
        {
          filename: "license.txt",
          content: bufferObj.toString("base64"),
          contentType: "text/plain"
        },
      ],
    };

    if(body.cc) {
      data.cc = body.cc
    }

    let result = await strapi.plugins["email"].services.email
      .send(data)
      .then((r) => {
        return r;
      })
      .catch((e) => {
        return e;
      });
```

### System

- Node.js version: v14.15.4 Dockerised setup using Official Strapi Docker image which happens to run on v12.20.1 during runtime.
- NPM version: v6.14.11 Dockerised setup using Official Strapi Docker image
- Strapi version: 3.4.5
- Database: Postgres
- Operating system: EC2 Running Ubuntu 18. But the Strapi is running in the Docker container.

### Additional context

The same setup used to work perfectly while using SendGrid.

**Comment by AkshayMAnvekar** [comment]
Found the issue.
The plugin uses sendEmail() method in the node-ses package. AWS supports attachments only in the sendRawEmail() method. 

Implemented a function in functions to send email using sendRawEmail() as a work around. 

The plugin will be able to support email attachments if it uses the raw email method over current method.

**Comment by derrickmehaffy** [comment]
Thank you @AkshayMAnvekar going to mark this one as closed unless you would like to submit a PR to the documentation repo: https://github.com/strapi/documentation or suggest a change to the codebase.

**Comment by AkshayMAnvekar** [comment]
> 
> 
> Thank you @AkshayMAnvekar going to mark this one as closed unless you would like to submit a PR to the documentation repo: https://github.com/strapi/documentation or suggest a change to the codebase.

@derrickmehaffy I can share the code or help in updating the code for AWS SES Plugin to support Attachments.

**Comment by derrickmehaffy** [comment]
Please do :) might be good to make a post on the forum: https://forum.strapi.io

**Comment by devpascoe** [comment]
@AkshayMAnvekar i'm facing the same issue. Would love for you share your workaround?

**Comment by AkshayMAnvekar** [comment]
> 
> 
> @AkshayMAnvekar i'm facing the same issue. Would love for you share your workaround?

Hi, @devpascoe ,

This is the function I created for email with attachments. This was for a csv file. 

```js
sendEmail: async (ctx) => {
    const { body } = ctx.request;

    var ses = require("node-ses");
    var mimemessage = require("mimemessage");

    let client = ses.createClient({
      key: process.env.AWS_ACCESS_KEY_ID,
      secret: process.env.AWS_SES_SECRET,
      amazon: process.env.AWS_SES_URL,
    });

    strapi.log.info("sending email");
    
    if (!body.email) {
      throwError(ctx, 400, "Email missing");
    }
    if (!body.text) {
      throwError(ctx, 400, "Text missing");
    }
    if (!body.subject) {
      throwError(ctx, 400, "Subject missing");
    }
    if (!body.attachment) {
      throwError(ctx, 400, "Attachment data missing");
    }

    let txtData = body.attachment;

    let bufferObj = Buffer.from(txtData, "utf8");
   
    let mailContent = mimemessage.factory({
      contentType: "multipart/mixed",
      body: [],
    });

    mailContent.header("From", `Team <${process.env.AWS_SES_EMAIL}>`);
    mailContent.header("To", body.email || body.to);

    if ("cc" in body) {
      mailContent.header("CC", body.cc);
    }

    mailContent.header("Subject", body.subject);

    var alternateEntity = mimemessage.factory({
      contentType: "multipart/alternate",
      body: [],
    });

    var plainEntity = mimemessage.factory({
      body: body.text,
    });

    alternateEntity.body.push(plainEntity);
    mailContent.body.push(alternateEntity);

    var attachmentEntity = mimemessage.factory({
      contentType: "text/csv",
      contentTransferEncoding: "base64",
      body: bufferObj.toString("base64"), //.replace(/([^\0]{76})/g, "$1\n"),
    });

    attachmentEntity.header(
      "Content-Disposition",
      'attachment ;filename="file.csv"'
    );

    mailContent.body.push(attachmentEntity);

    let result = await client.sendRawEmail(
      {
        from: process.env.AWS_SES_EMAIL,
        rawMessage: mailContent.toString(),
      },
      (err, sesdata, res) => {
        if (err) {
          result = err;
          strapi.log.info(err);
        }
        // an error occurred
        else {
          result = sesdata;
        }
      }
    );

    return result;
  }
```

Hope this helps.

**Comment by devpascoe** [comment]
Kind of you to share @AkshayMAnvekar
I think for my project i'll be able to get away with hyperlinks to the attachments in the body of the email. But the code sample is appreciated.

**Comment by akramaskar** [comment]
I found an implementation with nodemailer easier. Here is the code if anybody wants to use it:
For the attachments: Just use the path instead of the buffer as string. The array looks like this:

`attachments = [
        {
          path: pdfUrl,
          filename: `${documentTitle}.pdf`,
          contentType: 'application/pdf',
          content_id: 'invoice-attachment',
        },
      ];`

`sendEmailViaSES: async (emailRequest) => {

    const {from, bcc, replyTo, subject, text, to} = emailRequest;

    const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
    const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
    const AWS_REGION = process.env.AWS_REGION;

    const ses = new aws.SES({
      region: AWS_REGION,
      credentials: {
        secretAccessKey: AWS_SECRET_ACCESS_KEY,
        accessKeyId: AWS_ACCESS_KEY_ID,
      },
    });

    // create Nodemailer SES transporter
    const transporter = nodemailer.createTransport({
      SES: {ses, aws},
    });

    const message = {
      from,
      to,
      bcc,
      replyTo,
      subject,
      text,
      ses: {
        // optional extra arguments for SendRawEmail
        Tags: [
          {
            Name: 'tag_name',
            Value: 'tag_value',
          },
        ],
      },
    };

    if ('html' in emailRequest) {
      message['html'] = emailRequest.html;
    }

    if ('attachments' in emailRequest) {
      message['attachments'] = emailRequest.attachments;
    }

    await transporter.sendMail(message, (err, info) => {
      console.error(err || info);
    });
  },`
