### ISSUE TITLE
Many-to-many relations returning wrong data

### ISSUE THREAD

**Issue by alaminut** [strapi/strapi#9271]
### Describe the bug

Creating two models related to each other with "has many, belongs to many" relation and then querying that relation field in graphql returns all the data in the opposite end even though they are not related.

### Steps to reproduce the behavior

1. Create two models with "has many, belongs to many" relation.
2. Query the relation field with graphql
3. Observe the result set contains data that does not belong to the queried model's relation.

### Expected behavior

Relations should be correct?

### Code snippets

**Model: Tag**
```
{
  "kind": "collectionType",
  "collectionName": "tags",
  "info": {
    "name": "Tag",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "SystemName": {
      "type": "string",
      "required": true,
      "unique": true,
      "maxLength": 100,
      "private": true
    },
    "Searchable": {
      "type": "boolean",
      "default": true
    },
    "Hidden": {
      "type": "boolean",
      "default": false
    },
    "Listable": {
      "type": "boolean",
      "default": true
    },
    "testList": {
      "via": "tagList",
      "collection": "test"
    }
  }
}
```

**Model: test**
```
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "name": "Test",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "tagList": {
      "collection": "tag",
      "via": "testList",
      "dominant": true
    }
  }
}
```

Create objects for both models, leave relations empty (so test has no tags) run the following queries:

```
query Test {
  tests {
    tagList {
      id
    }
  }
}

query Tags {
  tags {
    testList {
      id
    }
  }
}
```

I get the following response from graphql when I run those queries with no related models in any collection.

```
{
  "data": {
    "tags": [
      {
        "testList": [
          {
            "id": "60157cf156ac8d24586cce1b"
          }
        ]
      },
      {
        "testList": [
          {
            "id": "60157cf156ac8d24586cce1b"
          }
        ]
      },
      {
        "testList": [
          {
            "id": "60157cf156ac8d24586cce1b"
          }
        ]
      },
      {
        "testList": [
          {
            "id": "60157cf156ac8d24586cce1b"
          }
        ]
      }
    ]
  }
}
```

### System

- Node.js version: 14.15.4
- NPM version: 6.14.11
- Strapi version: 3.4.4
- Graphql plugin version: 3.4.4
- Database: mongodb (mongoose)
- Operating system: Win / OS X

### Additional context

REST api works fine if a relation is empty it returns empty array as it should be. Problem only exists with the graphql.

**Comment by alaminut** [comment]
Hello, any development with this issue? Has anyone be able to reproduce the problem?

**Comment by ifeanyiisitor** [comment]
Having this problem as well

**Comment by alaminut** [comment]
Hello, any update on this?

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.4.4

@alaminut we have made some changes to population recently. Can you check with v3.5.0 and confirm the issue still exists. 
We have a bit of a backlog on reproducing issues. If you could provide a sample project for us to test with that would be great.

**Comment by alaminut** [comment]
@derrickmehaffy I haven't updated to 3.5.0 yet - I'm a bit of overwhelmed this week but I'll for sure create a sample repo with 3.5 - if the issue exists on that version, or the version that I'm using next week.

**Comment by alaminut** [comment]
@derrickmehaffy Updating v3.5 solved this issue.
