### ISSUE TITLE
Strapi-documentation-plugin: one to many relation without back reference wrong type.

### ISSUE THREAD

**Issue by MrAlevy** [strapi/strapi#9280]
The plugin generates a single instance ref instead of an array for one-to-many relations. 
` 
"employees": {
            "required": [
              "id",
              "email",
...
`

Property "type": "array" is missed. 

![image](https://user-images.githubusercontent.com/47833621/106469442-59e2f580-64b0-11eb-8c12-6a1001a0a8b9.png)

**Comment by avdeyev** [comment]
Possible fix: 

module: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/services/Documentation.js#L360

Add  `case 'manyWay':` to the switch

@soupette, @alexandrebodin, looks like you've been working on this plugin about 2 years ago. If you think that the solution doesn't break any logic around we can prepare pull request.

**Comment by alexandrebodin** [comment]
@avdeyev sure go ahead & make a PR :)

**Comment by derrickmehaffy** [comment]
closing as addressed in: https://github.com/strapi/strapi/pull/9379
