### ISSUE TITLE
lowercase only emails for account, but not clear error messages

### ISSUE THREAD

**Issue by tttp** [strapi/strapi#9284]
## Bug report

creating an account with a mixed case email generates a cryptic ValidationError error message

### Describe the bug
Accounts are expected to have lowercase emails only.
I'm pretty sure that there is a RFC somewhere that allows mixed cases, but it's a fair requirement... that isn't explicit enough and could be handled better.

### Steps to reproduce the behavior

1. Go to /admin/settings/users
2. Click on "Create new users"
3. fill Bob Doe Bob@example.org
4. you get a "ValidationError" alert

### Expected behavior
Either
1) accept mixed case emails (I'm not aware of the potential problems, it might not be an option)
2) re-format the email to lowercase it without displaying an error message
3) Display the full error message instead of "ValidationError"
the server response already contains:
email | [ "email must be a lowercase string" ]

but it isn't properly displayed

As I user with Bob@example.org email, I'd prefer to be able to register with this email, that it's silently converted to lowercase isn't a big issue so 2) has my preference.

### System

STRAPI VERSION v3.3.4

NODE VERSION v12.16.1

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/8235

**Comment by tttp** [comment]
@derrickmehaffy I'm not sure it's a duplicate of #8235 is about an account created with an external provider, here it's about not being able to create the account directly in strapi

**Comment by derrickmehaffy** [comment]
It's a general fix that needs to be done, there is a pending breaking change PR but all emails need to be converted to lowercase before they are saved. We are aware of the issue though, it's just of matter of a major release to fix it.
