### ISSUE TITLE
Triggering a validation error on a non-visible tab makes the UI seem broken

### ISSUE THREAD

**Issue by tomsaleeba** [strapi/strapi#9292]
### Describe the bug

This is in the `content-type-builder` plugin UI. When triggering a validation error on a non-visible tab, the UI appears broken.

### Steps to reproduce the behavior

1. start a strapi server
2. go to the admin web UI
3. go to the Content Types Builder plugin
4. create a new collection type (probably doesn't matter if it's not a collection but it's what I did)
5. give the model any name
6. select "text" to add a new field
7. enter `id` for the name
8. change to the *Advanced Settings* tab
9. click *Finish* or *Add another field*

### Expected behavior

There is some indication in the UI that a validation error has occurred. The error is there but on a different tab so some options:
 - a toast/popup is shown to indicate an error
 - the user is navigated to the tab with the error on it
 - the tab has some sort of error indicator on it so the user knows to navigate to it to check

### Actual behaviour

You are not allowed to create a field with the name `id` (as per https://github.com/strapi/strapi/issues/6279). The validation error happens correctly and it's shown on the *Base Settings* tab but the user cannot see that as they're still on the *Advanced Settings* tab. So clicking the buttons seems broken as nothing happens in the UI.

The error that is shown is `error.attributeName.reserved-name`: "This name cannot be used in your content type as it might break other functionalities"

### Screenshots

On the *Advanced Settings* tab with no indication of error:
![image](https://user-images.githubusercontent.com/1773838/106577309-24143e80-658e-11eb-9d3d-5c8baa34d68d.png)

Meanwhile on the *Base Settings* tab there is an error:
![image](https://user-images.githubusercontent.com/1773838/106577340-2f676a00-658e-11eb-919f-ac0d9b3ba770.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.4.4
- Database: Postgres 12
- Operating system: Manjaro Linux with 5.10.7-3-MANJARO kernel

### Additional context

Thanks for an awesome tool :heart_eyes:

**Comment by soupette** [comment]
@derrickmehaffy I think that this issue is more a feature request or an enhancement than a bug. Do you mind if I changes the label accordingly?

**Comment by derrickmehaffy** [comment]
@soupette yup makes sense

**Comment by marcoautiero** [comment]
This issue has been fixed in v4
