### ISSUE TITLE
Impossible to create a content type

### ISSUE THREAD

**Issue by managuilar** [strapi/strapi#9299]
### Describe the bug

I cannot create a content type.

### Steps to reproduce the behavior

1. I follow all the steps from google cloud installation https://strapi.io/documentation/developer-docs/latest/deployment/google-app-engine.html

### Screenshots

Here is the problem: I cannot see the add field button.

<img width="1724" alt="Captura de pantalla 2021-02-02 a las 16 53 12" src="https://user-images.githubusercontent.com/6086440/106628125-c544ca00-6579-11eb-9c6e-a393b103a6bb.png">

### System

- Node.js version: v10.23.1
- Strapi version: v3.4.5
- Database: postgresql Google cloud

**Comment by centogram** [comment]
Strapi must be running in development mode in order to alter Collection Types.

**Comment by managuilar** [comment]
Ok great thank you for the quick respond! 

Does it work with the same email and password, doesnt it? I tried in development mode and I cannot access with the same email. (invalidation credentials) I try to changed the password and there is no way.  Any tip? Thanks

**Comment by centogram** [comment]
If you are using the same database then the credentials would be the same in both environments.  You should be able to change your password in either environment.

**Comment by managuilar** [comment]
Ok that is because I am using another DB in development mode. Thank you again I close the issue!
