### ISSUE TITLE
"The file is too big" when uploading assets

### ISSUE THREAD

**Issue by ranimufid** [strapi/strapi#9301]
Currently using strapi with an S3 backend and receiving the following error when uploading a 5mb file

```
The file is too big
```

`config/plugins.js`

```
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      region: env('APP_REGION'),
      params: {
        Bucket: env('BUCKET_NAME'),
      },
    },
  },
})
```

`config/middleware.js`

```
module.exports = {
  settings: {
      parser: {
        enabled: true,
        multipart: true,
        formidable: {
          maxFileSize: 5 * 1024 * 1024 * 1024,
        },
      },
    },
  };
```

### Steps to reproduce the behavior

1. Go to 'Media Library'
2. Click on 'Upload assets'
3. Select a 5mb file
4. `The file is too big`

### System

- Node.js version: `node:14-alpine3.12`
- Strapi version: `3.4.4`
- Database: `postgres`
- Operating system: `alpine`

**Comment by ranimufid** [comment]
Apologies, the issue turned out to be that I had nginx behind strapi and nginx has a defualt `client_max_body_size` of 1 MiB. Increasing this accordingly helped fix the upload issue!

**Comment by 10054bondoc** [comment]
Hello, i'd like to know how you configured nginx file in strapi? I can't seem to find any docs on this. Thank you.

**Comment by RilDev** [comment]
@10054bondoc Just add the line `client_max_body_size 200M;` in the file `/etc/nginx/nginx.cong` as shown in this tutorial: https://linuxhint.com/what-is-client-max-body-size-nginx/
