### ISSUE TITLE
mysql request generation is wrong when opening a relationship select in ContentManager in Strapi 3.4.5

### ISSUE THREAD

**Issue by ermat77** [strapi/strapi#9305]
### Bug report

After upgrade from 3.4.0 to 3.4.5 (I haven't tried on versions 3.4.[1,2,3,4]), everywhere I have a Content-type that has some relationship AND that has an image attribute OR an Dynamic Zone attribute (I tried when those attributes were deleted and it worked) when I pull down the select to change the value, I see that the three dots loading indicator is always there and the list of selectable values never loads. Looking at the Strapi output I see that the POST that is made to get the list of values returned a 500 error that says:

Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near //this depends on the Content-type

And indeed when I inspect my MYSQL Server logs I see that the SQL request is cut, example :

> 
select distinct `type_de_materiels`.* from `type_de_materiels` where `type_de_materiels`.`id` not in (`gere_en_sav` = NULL, `published_at` = '2021-02-03T10:18:22.000Z', `Qui` = NULL, `created` = NULL, `created_at` = '2021-02-03T10:18:20.000Z', `nom` = 'ordi bureau', `created_by` = 1, `updated_at` = '2021-02-03T10:18:22.000Z', `updated` = NULL, `id` = 1, `updated_by` = 1, `Composants` = ) limit 20 

You can see just before the "limit 20" at the end of the request that the request has been cut

This doesn't happen when I delete the Dynamic Zone for the example above, and didn't happen on another content-type when i deleted the Image attribute...
This happens on develop build, haven't tried on production.

I think this is related to #9294

### Steps to reproduce the behavior

Create a content type, add a Relationship field selecting the first kind of relationship (x has y).
Now insert a record for this content type and select a linked object in the relationship. The first time you should succeed.
Save, publish, then come back editing the object. Try to change the linked object by opening the relationship select. You should see the error on Strapi console, and other values are not shown.

### System

  Node.js version: 12.18.2
  NPM version: 6.14.5
  Strapi version: 3.4.5
  Database: MySQL
  Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi I will close this as a duplciate of https://github.com/strapi/strapi/issues/9294 we are investigating it :)
