### ISSUE TITLE
Customise hide areas of the Admin interface per roles

### ISSUE THREAD

**Issue by sejersbol** [strapi/strapi#931]
Hi,

I'm new to Strapi and are wondering if I would be able to use it for a current project. The Strapi Admin interface gives me, the developer, everything I need. However I would like to have "superusers" that also have access to the Admin interface, but only be able to work with certain content types, e.g. add/remove/update Products. These "superusers" should not be able to access the Content Type Builder, Roles & Permissions, Settings Manager and so on. Is there a way to hide/remove the PLUGINS (and probably GENERAL) areas in the Amin menu? Can this be done on an access-role-base or is there another way?

Thanks and kind regards,

Anders Sejersbøl

**Comment by soupette** [comment]
@sejersbol, currently your can
- uninstall de content type builder when you're done using it (plugins link on the admin)
- create role for your users with specific permissions for each content type
- the admin is currently available to admin users only
- you can display specific content types in the [admin](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/doc/customize-menu.md)

**Comment by sejersbol** [comment]
Thanks for your reply. I tried to remove some plugins and it worked, no problems. However if I want to remove the "Roles & Permissions" plugin, so that the "superusers" can't change roles and permissions they can't login. Hmmm...

Another thing, would it be possible to have two different admin panels running? One that is minimal and one that gives more options/access?

**Comment by soupette** [comment]
Yes if you 'hack' the admin and you set the menu depending on the user...

**Comment by soupette** [comment]
Let me know if you need any help on implementing a temporary solution. Join us on [Slack](https://slack.strapi.io/)

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues.
Please check https://github.com/strapi/strapi/issues/1152
