### ISSUE TITLE
Error when deactivating all Mutations in GraphQL API

### ISSUE THREAD

**Issue by abett** [strapi/strapi#9313]
### Describe the bug

When setting all autogenerated GraphQL Mutation endpoints to `false` (including the ones that are created for strapi plugins), my server crashes on refresh with the following error: `Type Mutation must define one or more fields`.  
When I leave any 1+ Mutation in the API, this error does not appear.

(This is in a way a follow-up issue to https://github.com/strapi/strapi/issues/8754)

### Steps to reproduce the behavior

1. Deactivate all GraphQL Mutations for content types and plugins by overwriting them with `false`.

### Expected behavior

The server should start and expose only GraphQL query endpoints.

### Log

```
cms_1     | [2021-02-04T14:57:10.181Z] debug ⛔️ Server wasn't able to start properly.
cms_1     | [2021-02-04T14:57:10.181Z] error Error: Type Mutation must define one or more fields.
cms_1     |     at assertValidSchema (/srv/app/node_modules/graphql/type/validate.js:69:11)
cms_1     |     at assertValidExecutionArguments (/srv/app/node_modules/graphql/execution/execute.js:150:35)
cms_1     |     at executeImpl (/srv/app/node_modules/graphql/execution/execute.js:98:3)
cms_1     |     at Object.execute (/srv/app/node_modules/graphql/execution/execute.js:60:63)
cms_1     |     at Object.generateSchemaHash (/srv/app/node_modules/apollo-server-core/dist/utils/schemaHash.js:15:32)
cms_1     |     at ApolloServer.generateSchemaDerivedData (/srv/app/node_modules/apollo-server-core/dist/ApolloServer.js:269:41)
cms_1     |     at new ApolloServerBase (/srv/app/node_modules/apollo-server-core/dist/ApolloServer.js:161:38)
cms_1     |     at new ApolloServer (/srv/app/node_modules/apollo-server-koa/dist/ApolloServer.js:64:1)
cms_1     |     at Object.initialize (/srv/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:138:22)
cms_1     |     at /srv/app/node_modules/strapi/lib/hooks/index.js:37:28
cms_1     | error Command failed with exit code 1.
cms_1     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System

- Node.js version: v14.15.1
- NPM version: 7.5.2
- Strapi version: 3.4.6
- Database: postgres
- Operating system: Docker on WSL2

**Comment by brendankerrison** [comment]
We have exactly the same issue (v3.6.8). We are disabled mutations for security reasons but if we remove all of them the error reported above occurs. Any way to workaround this?

**Comment by abett** [comment]
I think the problem is that Strapi generates a GraphQL schema that ends up having a declaration for mutations, but no content in it, which then crashes Apollo on start.

If you can manage to grepl this block out of the schema after it's compiled by strapi but before Apollo tries to read it, you might have success.

I couldn't get that to work and instead added a dummy mutation which does nothing of harm.
You might be able to improve this solution by looking into the permission bit.

My addition, to one of the schema.graphql.js files I edited:
```
module.exports = {
  mutation: `
    yo: String!
  `,
  resolver: {
    // [...],
    Mutation: {
      // [... setting stuff to false here ...],
      yo: {
        resolver: async () => 'yo',
        // I didn't care who would see this mutation, so I just used a random component's find-permission
        resolverOf: 'application::xxx.xxx.find', 
      },
    }.
  },
};
```

**Comment by derrickmehaffy** [comment]
Code of the graphql plugin has fundamentally changed in the v4, marking as closed

**Comment by supercede** [comment]
So how does it work on v4?
