### ISSUE TITLE
backendURL is empty in production mode

### ISSUE THREAD

**Issue by andriichern** [strapi/strapi#9314]
Hello.

I found that on the frontend side `strapi.backendURL` contains actual strapi url when it runs in development mode, but in the production mode `strapi.backendURL` is an empty string.

In my case this causes bugs for resolving images path from MediaLibrary as we prefixing it with `prefixFileUrlWithBackendUrl` function. As `strapi.backendURL` empty it stores images with wrong relative path (containing some `../../`) and we can not load image from strapi by that path from our site where we use strapi API.

Is this an expected behaviour?

Thanks in advance

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
