### ISSUE TITLE
Getting error when setting filter variable to `null` in GraphQL query

### ISSUE THREAD

**Issue by boristian** [strapi/strapi#9318]
I have 2 GraphQL queries with the same variables:

```gql
query NotificationsCount ($search: String) {
  notificationsConnection (
    where: { text_contains: $search }
  ) {
    aggregate {
      count
    }
  }
}
```

```gql
query Notifications (
  $limit: Int=100
  $search: String
  $start: Int=0
  $sort: String="updatedAt"
) {
  notifications (
    limit: $limit
    sort: $sort
    start: $start
    where: { text_contains: $search }
  ) {
    autoClose
    deactivated
    delay
    id
    text
    variant
  }
}
```

For the first query if i do not to set `search` explicitly to `null` and just leave it `undefined` i get an error, which is fine because of #8490.
If in the second query `search` is set to `null` i get an error. If i leave it `undefined` it works.

Am I doing something wrong or is this unintended behavior?

### System

- Node.js version: 14
- Strapi version: 3.4.6
- Database: mongodb
- Operating system: docker desktop on macOS

**Comment by derrickmehaffy** [comment]
Can you please test with the dedicated `null` filter defined here: https://strapi.io/documentation/developer-docs/latest/content-api/parameters.html#filters

it it would be something like `fieldName_null: true/false`

**Comment by boristian** [comment]
Thanks for your super fast response!

I just did quick test with insomnia and it seems like only filter variables in connection request are throwing errors when omitted.

```gql
query RoomsCount(
  $search: String
  $hasNoProfile: Boolean
) {
  roomsCount(where: {
    label_contains: $search
    profile_null: $hasNoProfile
  }) 
}
```

For this query i wrote a resolver myself. When i pass `{}` as variables i am not getting an error.

**Comment by derrickmehaffy** [comment]
Can you pass along the errors you are seeing?

**Comment by boristian** [comment]
Query:

```graphql
query RoomsCount($search: String) {
  roomsConnection(where: {label_contains: $search}) {
    aggregate {
      count
    }
  }
}
```

Variables:

```json
{}
```

Response:

```json
{
  "errors": [
    {
      "message": "The value of field: 'label', in your where filter, is undefined.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "roomsConnection",
        "aggregate",
        "count"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "status": 400,
          "stacktrace": [
            "Error: The value of field: 'label', in your where filter, is undefined.",
            "    at /srv/app/node_modules/strapi-utils/lib/build-query.js:117:21",
            "    at Array.map (<anonymous>)",
            "    at normalizeWhereClauses (/srv/app/node_modules/strapi-utils/lib/build-query.js:115:6)",
            "    at buildQuery (/srv/app/node_modules/strapi-utils/lib/build-query.js:198:23)",
            "    at Object.count (/srv/app/node_modules/strapi-connector-mongoose/lib/queries.js:445:12)",
            "    at fn (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:31:54)",
            "    at Object.count (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:15:24)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "roomsConnection": {
      "aggregate": {
        "count": null
      }
    }
  }
}
```

For my projects i decided to refactor my queries to just use a JSON object as `$where` with an empty object as default.

```graphql
query RoomsCount ($where: JSON={}) {
  roomsCount(where: $where)
}
```

**Comment by violabg** [comment]
I’m getting the same error starting from version 3.4.6 same query on strapi 3.4.5 works fine.
It only appends on Connections, I have a request with multiple queries using the same filters parameters, anche only the Connection query complains about null values the other queries work fine.

**Comment by violabg** [comment]
Unfortunately I can't update past to 3.4.5 because it breaks my queries

```graphql
query GetTpEventsWithFilters(
  $startDate: Date
  $endDate: Date
  $cluster: [ID]
  $user: [ID]
  $eventTypes: [ID]
  $eventCategory: [ID]
  $sort: String
  $start: Int
  $limit: Int
) {
  tpEvents(
    sort: $sort
    start: $start
    limit: $limit
    where: {
      _where: [
        { eventDateFrom_gte: $startDate, eventDateFrom_lte: $endDate }
        { cluster_in: $cluster }
        { eventCategory_in: $eventCategory }
        { user_in: $user }
        { eventTypes_in: $eventTypes }
      ]
    }
  ) {
    id
    eventCategory {
      id
      label
    }
    businessAreas {
      id
      label
    }
    cluster {
      id
      label
      color
    }
    market
    eventLead
    eventName
    thematicFocusOfEvents {
      id
      label
    }
    leadFunction {
      id
      label
    }
    eventDateFrom
    eventDateTo
    location
    eventTypes {
      id
      label
    }
    themeOfEvent
    boothSize {
      id
      label
    }
    website
    organisersPublication
    speakerSecured
    dateAndTimeOfSpeakingSlot
    tetraPakSpeakerName
    titleAndTopic
    eventPageOnDotCom
    doYouHaveAnotherSpeakingOppty
    titleAndSpeaker
    user {
      id
      username
      firstName
      lastName
      color
    }
  }
  tpEventsConnection(
    where: {
      _where: [
        { eventDateFrom_gte: $startDate, eventDateFrom_lte: $endDate }
        { cluster_in: $cluster }
        { eventCategory_in: $eventCategory }
        { user_in: $user }
        { eventTypes_in: $eventTypes }
      ]
    }
  ) {
    aggregate {
      count
    }
  }
}
```
passing this variables
`
{
  "limit": 10,
  "start": 0
}
`
works in 3.4.5, but in 3.4.6
it only works for tpEvents query the tpEventsConnection complains about null parameters

**Comment by derrickmehaffy** [comment]
@violabg v3.4.6 included a patch that doesn't allow for undefined filters: https://github.com/strapi/strapi/pull/8490

This change was absolutely intended as you should never be passing over undefined filters. To prevent this, I would suggest setting your entire `where` statement to a variable and dynamically passing in the filters construction.

**Comment by violabg** [comment]
thanks for the reply, but I don't understand, is the applicable only to Connections? because it works in regular queries, like tpEvents in my previous example.

> To prevent this, I would suggest setting your entire `where` statement to a variable and dynamically passing in the filters construction.

This is something easy to do in rest/api, but not possible (to my knowledge) in GraphQL where your possible query variables need to be defined at built time.

By the way, the only reason that I call tpEventsConnection whit tpEvents query in my example is to get the count of my search query, so that I can show the total items founded in a paginated search. That is way the use the same parameters, but like I said the tpEvents works while tpEventsConnection fails.
this could be avoided if a content-type query would return the count by default, which is something I have seen in other graphql apis.

**Comment by derrickmehaffy** [comment]
There is more information in that PR @violabg

**Comment by violabg** [comment]
I tried to implement a count resolver as per 

https://strapi.io/documentation/developer-docs/latest/guides/count-graphql.html#setup-the-application

but I'm getting the same error I get with Connections, that complains about undefined filters.

So I went to my services to implement the filter as you suggested:

```js
module.exports = {
  count(params) {
    console.log("params", params);
    //     params I'm getting {
    //   eventDateFrom_gte: undefined,
    //   eventDateFrom_lte: undefined,
    //   cluster_in: undefined,
    //   eventCategory_in: [ '5' ],
    //   user_in: undefined,
    //   eventTypes_in: undefined
    // }

    const _where = [];

    const {
      eventDateFrom_gte,
      eventDateFrom_lte,
      cluster_in,
      eventCategory_in,
      user_in,
      eventTypes_in,
    } = params;

    const dates = {};

    if (cluster_in) {
      _where.push({ cluster_in });
    }
    if (eventCategory_in) {
      _where.push({ eventCategory_in });
    }
    if (cluster_in) {
      _where.push({ cluster_in });
    }
    if (user_in) {
      _where.push({ user_in });
    }
    if (eventTypes_in) {
      _where.push({ eventTypes_in });
    }
    if (eventDateFrom_gte) {
      dates.eventDateFrom_gte = eventDateFrom_gte;
    }
    if (eventDateFrom_lte) {
      dates.eventDateFrom_lte = eventDateFrom_lte;
    }

    const _dates = Object.keys(dates);

    if (_dates.length > 0) {
      _where.push(dates);
    }

    console.log("_where", _where);

    //     structure I need {
    //   _where: [
    //     { eventDateFrom_gte: undefined, eventDateFrom_lte: undefined },
    //     { cluster_in: undefined },
    //     { eventCategory_in: [Array] },
    //     { user_in: undefined },
    //     { eventTypes_in: undefined }
    //   ]
    // }

    return strapi.query("tp-event").count({ _where });
  },
};
```

It doesn't give me any error now and is working except for the date filter, which when is set it always return a count of 0.
Apart from the fact that is still not working as aspected, it feels like a breaking change from strapi 3.4.5 with no real solutions.

**Comment by derrickmehaffy** [comment]
We plan to do a massive refactoring of the GraphQL later this year as we have a number of issues with GraphQL ATM: 

https://github.com/strapi/strapi/issues?q=is%3Aopen+is%3Aissue+label%3A%22source%3A+plugin%3Agraphql%22
