### ISSUE TITLE
Media Library setting "Enable size optimization (without quality loss)" produces images of reduced quality

### ISSUE THREAD

**Issue by phripley** [strapi/strapi#9319]
### Describe the bug

My first issue in GitHub ever.  Hope I did this right!

Media Library setting "Enable size optimization (without quality loss)" produces images of reduced quality.

I have been looking forward to being able to use this feature that have had disabled for a while because it was creating images that were _larger_ than those uploaded.

I was pleased to see that Strapi [release 3.4.5](https://github.com/strapi/strapi/releases/tag/v3.4.5) included this Enhancement:

"[Prevent returning optimized image if it's larger than original](https://github.com/strapi/strapi/pull/9214)"

I have tested the behavior and am no longer seeing images saved at a larger size but I am seeing them being losslessly compressed which is not expected by me based on the name of the preference.

### Steps to reproduce the behavior

1. In Strapi settings for the Media Library turn on "Enable size optimization (without quality loss)"
2. Upload a JPEG to the Strapi Media Library.
3. Download the image you have just saved in strapi.
4. Compare the image size and image quality.
5. In my testing the image is smaller (good!) and of lower quality (not expected).
6. One easy way to compare the two images is to use the webservice "diffchecker": Upload your original and and the one that you downloaded from strapi here: https://www.diffchecker.com/image-diff/ you can use the "split" tab to compare or see the difference on the "Downloadable" tab, also see metadata differences in "File Details" tab.

### Expected behavior

With preference turned on with the label "Enable size optimization (without quality loss)" files should not lose quality.

### Screenshots

Specimen files:

Original file (320K):
![original](https://user-images.githubusercontent.com/1319850/106945822-49bc5780-66f6-11eb-808b-2f2853aa62c9.jpg)

File as saved in Media Library with "Lossless Compression" enabled (102K):
![original_through_strapi_lossless_on](https://user-images.githubusercontent.com/1319850/106945847-5345bf80-66f6-11eb-85ba-2f0eb99cb13a.jpg)

Difference between the two files as reported by diffchecker.com:

![difference](https://user-images.githubusercontent.com/1319850/106945639-0c57ca00-66f6-11eb-9513-4ea2f50833bd.png)

Details as reported by diffchecker.com:

<img width="1198" alt="details" src="https://user-images.githubusercontent.com/1319850/106945743-2f827980-66f6-11eb-9a11-4896e57e0d42.png">

Notice the different subsampling values.  (I don't know enough about image compression to know what this means tho.)

### Code snippets

I am probably not qualified to figure this out.  But at a quick review it looks to me like the file: /node_modules/strapi-plugin-upload/services/image-manipulation.js make no reference to "quality" or "chromaSubsampling".

A quick look at [the sharp docs](https://sharp.pixelplumbing.com/api-output#jpeg) seems to indicate that when no "options.quality" value is passed a quality of 80 is used and chromaSubsampling is set to 4:2:0.

It is OK for Strapi Media Library to apply compression when creating new images (thumbnails etc), but when a _original_ file is uploaded is should never lose quality, especially when the label on the preference says "lossless"!

It may be that this bug only applies to JPEGs.  I did a quick test with a PNG and it seemed unchanged. I have not tested other image formats.

### System

On my development machine where I am testing this feature:

- Node.js version:  v14.15.3
- NPM version: 6.14.9
- Strapi version:  3.4.5
- Database: MySQL
- Operating system: Mac Catalina 10.15.7

**Comment by krestaino** [comment]
If we could configure the sharp options [like we can with formidable](https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#configuration), I think that would be a nice addition.

**Comment by jcache** [comment]
Does anyone know if this bug still an issue with Strapi v4?

**Comment by derrickmehaffy** [comment]
> Does anyone know if this bug still an issue with Strapi v4? We have a Gatsby project that is also effected by this bug. We were using Gatsby's sharp compression, saving them in Strapi, and unexpectedly getting images that were doubly compressed.

As we didn't fundamentally change much with the upload plugin (other than convert it's UI designs to the new design system) most likely

**Comment by petersg83** [comment]
Hi everyone :)
I believe this issue is fixed :
- wording : it was changed to "Enabling this option will reduce the image size and slightly reduce its quality."
- image is larger : now it tries to optimize it and if the size is larger than original, then it doesn't optimize it.

If i'm wrong don't hesitate to reopen the issue !
