### ISSUE TITLE
Setting user with numeric password fails

### ISSUE THREAD

**Issue by exera** [strapi/strapi#932]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: mongo
- **Operating system**: macOS Sierra

**What is the current behavior?**
Updating user password if password contains only numeric characters, hashing password fails.

**Steps to reproduce the problem**
Set user password something like 123456, password is empty or not changed.

**What is the expected behavior?**
Entered password is hashed and password field updates correctly.

**Suggested solutions**
user-permissions/services/User.js ln85
user.password converted to string before calling bcrypt.hash function 

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @exera ! Thank you for this issue.

Did you test your suggested solution ? And if you did it can you submit a PR to fix it.

**Comment by lauriejim** [comment]
Maybe can be related to this issue https://github.com/strapi/strapi/issues/995

**Comment by lauriejim** [comment]
It works on `register` function but not on user entry creation from `content manager`.

**Comment by derrickmehaffy** [comment]
@exera Any update on this issue? Checking to see if we can close out old issues.
