### ISSUE TITLE
There should be a way to see the name of files in the media type widget

### ISSUE THREAD

**Issue by la55u** [strapi/strapi#9322]
## Feature request
A way to see the name of files in the media type field.

### Please describe your feature request

- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Currently (unless I'm missing something) there is no way to tell which file is which when uploading multiple *files* in the media type field. It is not a problem with images since they have a preview but files don't which makes it impossible to manage multiple files for the end user. 
![image](https://user-images.githubusercontent.com/30611343/107026064-834e9a80-67aa-11eb-921a-1c3153009079.png)

### Why is it needed?

To be able to edit/delete one specific file the user wants instead of uploading them all again.

### Suggested solution(s)

Show the filename below/in the widget.

**Comment by derrickmehaffy** [comment]
Currently implemented but could be improved (it's a bit ugly right now per @Aurelsicoko )

**Comment by gu-stav** [comment]
We discussed the issue today and will discuss it internally. Thank you for opening the report.

**Comment by gu-stav** [comment]
We discussed the issue today and believe this is fixed in v4 already. In case anyone experiences any other there, please let @yanniskadiri now and we are going to re-open the issue.
