### ISSUE TITLE
"Cannot read property 'pool' of undefined", strapi-connector-bookshelf

### ISSUE THREAD

**Issue by TheMangoTrain** [strapi/strapi#9325]
## Bug report

I'm unable to run Strapi due to a problem with the plugin `strapi-connector-bookshelf`.

### Describe the bug

Upon running `npm run dev`, I get the following error in console:

```
[2021-02-05T13:58:41.088Z] debug ⛔️ Server wasn't able to start properly.
[2021-02-05T13:58:41.090Z] error TypeError: Cannot read property 'pool' of undefined
    at /Users/xxx/projects/my-project/node_modules/strapi-connector-bookshelf/lib/knex.js:105:43
```

### Steps to reproduce the behavior

1. Open your Strapi project
2. Run `npm run dev`

### Expected behavior

Strapi should run without errors.

## Bug details

This occurs due to the `strapi-connector-bookshelf` plugin, specifically version 3.4.4 - 3.4.6 (current).
Version 3.4.3 doesn't have this problem.

As a quick test, deleting the following lines inside the plugin, clears the error for me when using current ver (3.4.6) and I seem to have regular Strapi functionality. I'm using use a regular mysql database.

/node_modules/strapi-connector-bookshelf/lib/knex.js
```
          pool: {
            min: _.get(connection.options.pool, 'min', 0),
          },
```

Ultimately the below issue+fix seems to have introduced these lines; maybe extra testing is needed?
https://github.com/strapi/strapi/issues/8436

**Comment by NgyAnthony** [comment]
Can you try `min: _.get(connection.options, 'pool.min', 0)` ?

**Comment by NgyAnthony** [comment]
```

[...]
            debug: _.get(connection.options, 'debug', false),
        },
        strapi.config.hook.settings.knex,
        defaultConfig
      );

      options.pool = {
        min: _.get(connection.options, 'pool.min', 0),
      }
```
This should work
