### ISSUE TITLE
Wrong input overlaying a dropdown

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#9333]
### Describe the bug

Wrong input overlaying a dropdown

### Screenshots

![error-1](https://user-images.githubusercontent.com/1007051/107115189-25ce5280-686b-11eb-9541-96f41a4bcf23.png)
![error-2](https://user-images.githubusercontent.com/1007051/107115192-26ff7f80-686b-11eb-8a94-8854b7cbacd1.png)

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: v3.4.6
- Database: MongoDB
- Operating system: macOS

**Comment by abdonrd** [comment]
@soupette fixed in v4?

**Comment by soupette** [comment]
> @soupette fixed in v4?

Yes it should be!
