### ISSUE TITLE
Send just the changed data from content manager

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#9334]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Right now, when you edit a document from the content manager, it sends all the data, even information that hasn't changed on the form. It would be great if only the information that has changed is sent.

### Suggested solution(s)

Send just the changed data from content manager

**Comment by derrickmehaffy** [comment]
Can you clarify as sent to where? The lifecyles or the database?

**Comment by abdonrd** [comment]
I mean when you edit a document from the Content Manager at the Strapi admin dashboard.

The request is: `PUT content-manager/collection-types/application::MODEL_NAME.MODEL_NAME/MODEL_ID`

Example when I just update the `replicas` field from `1` to `2`.

<img width="514" alt="Screenshot 2021-02-07 at 10 08 10" src="https://user-images.githubusercontent.com/1007051/107141992-693cc580-692c-11eb-9093-5e6a06c6a3ba.png">

The Content Manager send all the fields, with all the relations, etc.

**Comment by derrickmehaffy** [comment]
Yes but where are you logging that information?

**Comment by abdonrd** [comment]
> Yes but where are you logging that information?

From the Chrome Dev Tools, Network tab.

**Comment by soupette** [comment]
Hello @abdonrd I agree the CM should only send the modified field, however when using dynamic zones or repeatable components we need to send back the entire data, even the unmodified one. But we could definitely only send the modified fields for the common ones. 
Is there a particular reason you need only the modified fields to be sent?

**Comment by abdonrd** [comment]
Hi @soupette!

>But we could definitely only send the modified fields for the common ones.

Yes, please! 🙏🏻 

>Is there a particular reason you need only the modified fields to be sent?

We need to create a few lifecycles (`beforeCreate` & `beforeUpdate`) to perform certain tasks. Tasks that only need to be done if certain fields have changed. And since now all the repeated data is being sent... In those lifecycles, I need to request the previous data and compare with the new data to know if the data has changed:

```javascript
const previousData = await strapi.query('MODEL').findOne({ id: params._id }, [])
```

If we only send the data that has changed, besides that it is more correct and efficient, it would avoid that extra call.

**Comment by soupette** [comment]
I understand, until we add such behaviour you can make a small update to the CM on your side, there's a utility in the `strapi-helper-plugin` that might help you with this:

```
import { difference } from 'strapi-helper-plugin'

const dataToSend = difference(initialData, modifiedData);
```

**Comment by abdonrd** [comment]
Thanks @soupette!

Could you tell me where in CM should I apply that logic?

**Comment by soupette** [comment]
You can apply the logic [here](https://github.com/strapi/strapi/blob/1e9e02b4de065e48e8e43d7f78aa91446eaf0494/packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js#L287)

It should be something like the following:


```
const initFormData = createFormData(initialData);
const toSend = difference(initFormData, formData);
```

However, you will need to add the logic regarding the dynamic zones and the components.

**Comment by abdonrd** [comment]
@soupette @derrickmehaffy the v4 fix this? Thanks!

**Comment by soupette** [comment]
> @soupette @derrickmehaffy the v4 fix this? Thanks!

No it does not yet...

**Comment by WardenCommander** [comment]
I think this is double edge sword, for someone who is looking only for changes it will be great as it will not require extra steps, but for someone who needs all data not as he will have to find way to get all data in lifecycle hook.
example:
if you are running calculation between in data.

**Comment by abdonrd** [comment]
> I think this is double edge sword, for someone who is looking only for changes it will be great as it will not require extra steps, but for someone who needs all data not as he will have to find way to get all data in lifecycle hook. example: if you are running calculation between in data.

You could send only the new information and receive all the information, that's no problem.

**Comment by derrickmehaffy** [comment]
Fairly certain this is what we already do in Strapi v4
