### ISSUE TITLE
the entry title of a collectionType(contentType) is not updated and show on  the relational collectionType (v3.4.4)

### ISSUE THREAD

**Issue by searich** [strapi/strapi#9335]
## Bug report
I am not sure it has been fixed or not because I am staying at version 3.4.4. 

### Describe the bug
The issue is that the entry title can not properly show on the related collectionType when it has been updated in the configuration of the original collectionType.

### Steps to reproduce the behavior

1. Go into one collection type, then click the "configruation view" at the right of the bottom, open the "configure the view". 
2. Click on the selector of "entry title" at the top, select and change it to any other content,  save it.
3. Find and go into any other collection type which already has a relational field with the above collection type. 
4. Add new or update the existing record, and then at the right-side panel, find the relational field box with the above collection type,  click the selector box, there is still the previous content list for the selection.
5.  The entry title is expected to be updated and show on the related the collectionType.

<img width="984" alt="Screen Shot 2021-02-07 at 10 08 46" src="https://user-images.githubusercontent.com/2938921/107134837-a1460780-6930-11eb-816c-af75c550836b.png">

<img width="991" alt="Screen Shot 2021-02-07 at 10 12 14" src="https://user-images.githubusercontent.com/2938921/107134844-aacf6f80-6930-11eb-9256-2b2782fd5422.png">

### System

- Node.js version: 
- v14.5.0
- NPM version: 
- v6.14.9
- Strapi version: 
- strapi v3.4.4.
- Database:
- mongoDB
- Operating system:
- Centos 7.0

**Comment by derrickmehaffy** [comment]
Please see: https://strapi.io/documentation/user-docs/latest/content-manager/configuring-view-of-content-type.html#configuring-the-edit-view

On your quotation type, edit the view and click on the relational field to pick the field shown.

Marking as closed
