### ISSUE TITLE
Populate with new values?

### ISSUE THREAD

**Issue by t0mclaudio** [strapi/strapi#9344]
Just want to ask if we are going to populate `margins` with new values?

https://github.com/strapi/strapi/blob/781cf2b9c99318d614010f2c33647b6393c6041e/packages/strapi-admin/admin/src/themes/sizes.js#L10-L13

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
