### ISSUE TITLE
Enterprise license not fully in effect

### ISSUE THREAD

**Issue by Timester** [strapi/strapi#9347]
### Describe the bug

I wanted to test the Enterprise RBAC functionalities of Strapi since it would be very useful for my use case. I got a 14-day trial enterprise license and started my Strapi project with ```STRAPI_LICENSE=xyz npm run develop```. The license got recognized, because the CLI showed this:

```
┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Mon Feb 08 2021 16:54:14 GMT+0100 (Central Euro… │
│ Launched in        │ 4242 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 50518                                            │
│ Version            │ 3.4.3 (node v12.13.0)                            │
│ Edition            │ Enterprise                                       │
└────────────────────┴──────────────────────────────────────────────────┘
```
Also on the Strapi admin, it said it is an enterprise version, not the community. However, when I tried to add a new role under Settings > Administration panel > Roles to try out the custom rules, I got the small picture with the balloons saying it is a community edition and to buy the enterprise license for creating a new role.

### Steps to reproduce the behavior

1. Create a Strapi project
2. Get a temporary enterprise license key from the Strapi website https://strapi.io/pricing
3. Build your project
4. Start the project with ```STRAPI_LICENSE=license-key npm run develop```
5. Try to add a new role in the settings

### Expected behavior

To be able to create new roles and edit them freely until the temporary enterprise license expires.

### Screenshots

<img width="1162" alt="Screen Shot 2021-02-08 at 17 14 40" src="https://user-images.githubusercontent.com/6758515/107247083-329ca300-6a31-11eb-9f9e-f4f06c474835.png">
<img width="536" alt="Screen Shot 2021-02-08 at 17 14 21" src="https://user-images.githubusercontent.com/6758515/107247102-37615700-6a31-11eb-8951-6c857b348cc8.png">
<img width="581" alt="Screen Shot 2021-02-08 at 17 13 52" src="https://user-images.githubusercontent.com/6758515/107247104-37f9ed80-6a31-11eb-97bf-cad891b59a0c.png">

### System

- Node.js version: v12.13
- NPM version: 7.5.2
- Strapi version: 3.4.3
- Database: MySQL
- Operating system: MacOS

**Comment by alexandrebodin** [comment]
Hi. You need to rebuild your admin with the env var set too :) Closing as it should work just fine once done ;)

**Comment by Timester** [comment]
> Hi. You need to rebuild your admin with the env var set too :) Closing as it should work just fine once done ;)

Hi, thanks it worked perfectly! It is a bit strange though that the UI must be rebuilt to make it work. Seems redundant to me, also makes upgrading difficult in production (I don't know how common that case is but I can imagine it happen).

Anyhow, thank you a lot for your quick help! Much appreciated!

**Comment by alexandrebodin** [comment]
> > Hi. You need to rebuild your admin with the env var set too :) Closing as it should work just fine once done ;)
> 
> Hi, thanks it worked perfectly! It is a bit strange though that the UI must be rebuilt to make it work. Seems redundant to me, also makes upgrading difficult in production (I don't know how common that case is but I can imagine it happen).
> 
> Anyhow, thank you a lot for your quick help! Much appreciated!

We want to make it a runtime think eventually so the switch is simpler :D thanks for the support !
