### ISSUE TITLE
Error - "upload" failed Bootstrap

### ISSUE THREAD

**Issue by galvaodev** [strapi/strapi#9349]
### Describe the bug

When I try to run my project it returns this error, I've tried everything but I believe it is in the database, someone with a similar error?

### Steps to reproduce the behavior

1. Imagem Error

### Screenshots

![Captura de Tela 2021-02-08 às 18 33 45](https://user-images.githubusercontent.com/10669905/107285108-74cbe180-6a3d-11eb-83a5-a538dd1cfa5e.png)

### System

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.0.6
- Database: Postgres 
- Operating system: macOS Big Sur Version 11.0.1

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.0.6

Can you please test on the latest release, as of writing this is v3.5.0.

Going to mark this as closed until it can be confirmed to happen on the latest release.
