### ISSUE TITLE
How to run yarn develop without generating .cache folder?

### ISSUE THREAD

**Issue by jeffycai** [strapi/strapi#9350]
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
.cache is generated when you build the admin, the `build` folder doesn't exist when you run the develop command, Strapi will automatically build it.

Closing as you didn't follow the issue template, questions should be asked on our forum: https://forum.strapi.io
