### ISSUE TITLE
Strapi-provider-upload-cloudinary does not get customConfig options passed

### ISSUE THREAD

**Issue by supermooshman** [strapi/strapi#9352]
### Describe the bug

`strapi-provider-upload-cloudinary` does not get customConfig object passed. For example setting a custom folder destination does not work and all uploads end up in the Cloudinary root.

### Steps to reproduce the behavior

1. `yarn add strapi-provider-upload-cloudinary`
2. create `config/plugins.js` and add code snipped listed below
3. add variables to `.env`
4. `yarn dev`
5. upload image through the media library

### Expected behavior

The uploaded files are expected to be in a folder, set in the .env file

### Screenshots

n/a

### Code snippets

``` javascript
// config/plugins.js
module.exports = ({ env }) => ({
  upload: {
    provider: "cloudinary",
    providerOptions: {
      cloud_name: env("CLOUDINARY_NAME"),
      api_key: env("CLOUDINARY_KEY"),
      api_secret: env("CLOUDINARY_SECRET"),
      actionOptions: {
        upload: {
          folder: env("CLOUDINARY_FOLDER"),
        },
        delete: {},
      },
    },
  },
});
```

```
# .env
CLOUDINARY_NAME = cloudinary-name
CLOUDINARY_KEY = cloudinary-key
CLOUDINARY_SECRET = cloudinary-secret
CLOUDINARY_FOLDER = cloudinary-destination-folder
```

### System

- Node.js version: 14.3.0
- NPM version: 6.14.4
- Strapi version: 3.4.6
- Database: sqlite
- Operating system: macos 11.1

### Additional context

When logging the customConfig object that is passed to upload() in `strapi-provider-upload-cloudinary`, it shows that it is an empty object (ie the default value).

**Comment by alexandrebodin** [comment]
hi @supermooshman  the actionOptions should be set at the upload key level not inside providerOptions :) 

Closing as there are no bugs

**Comment by furkan-guvenc** [comment]
The **customConfig** parameter is not passed at [upload function](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js). Isn't it a bug?

**Comment by iclickuae** [comment]
i am facing the same issue it is a bug
