### ISSUE TITLE
How to provide different custom roles to different users authenticating through a grant oauth provider

### ISSUE THREAD

**Issue by exilien-supreme** [strapi/strapi#9353]
Right now, when a user authenticates himself/herself with an external grant oauth provider, the default "Authenticated" role is assigned to him/her. 

But how can we provide the users different custom roles when they are using auth provider.
For example:
John gets a custom role "SALES_EMPLOYEE"
Jane gets a custom role "CUSTOMER_SERVICE_EMPLOYEE"

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
