### ISSUE TITLE
Broken logging in strapi library

### ISSUE THREAD

**Issue by weidox** [strapi/strapi#9356]
### Describe the bug

Fails to log original exception. This thing is being logged:
```
TypeError: Cannot read property 'includes' of undefined
    at ..........\node_modules\strapi\lib\middlewares\parser\index.js:54:25
```
### Steps to reproduce the behavior

Happens when error is thrown in controller code, not using ctx.throw() method.

### Expected behavior

Original exception to be seen, to know what happened.

### Code snippets
\node_modules\strapi\lib\middlewares\parser\index.js:54:25
```
        } catch (e) {
          if (e.message.includes('maxFileSize exceeded')) {
```
Problem is that it calls `e.message` method, not checking first if `e.message` is defined. In my case error thrown did not contain "message" property.

### System

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.3.2
- Database: MongoDB
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
Can you provide more context on how to reproduce this?

**Comment by weidox** [comment]
Just in custom controller code, instead of usual `ctx.throw(400, "something")` write `throw "something"`.

**Comment by derrickmehaffy** [comment]
Is there a reason you aren't using ctx.throw (or even better would be our boom methods): https://github.com/strapi/strapi/blob/d5049777ead948e1041690f8c88772423603959a/packages/strapi/lib/middlewares/boom/index.js#L12-L43

Such as doing a `return ctx.badRequest('some message')

**Comment by weidox** [comment]
Yes, but that is the whole point why there is problem with broken logging. I had a wrong throws statement in an imported library and I spent long time trying to find out what is failing because logs were not printing the cause of issue.

**Comment by derrickmehaffy** [comment]
@weidox do you have a suggestion on how we can improve this? If so can you submit a PR?

**Comment by weidox** [comment]
I thought it would be easier if someone from actual support does make the change, as for the few letters I wasn't much inclined to go through whole process. I wrote the place of issue in ticket 
`\node_modules\strapi\lib\middlewares\parser\index.js:54:25`
```
        } catch (e) {
          if (e.message.includes('maxFileSize exceeded')) {
```
change to (or probably some check if e.message is instance of string or explicit not undefined, don't know your exact coding style):
```
        } catch (e) {
          if (e.message && e.message.includes('maxFileSize exceeded')) {
```

**Comment by ognjenjevremovic** [comment]
This seems trivial to fix.
@derrickmehaffy may I provide a proposed solution to this (as a first time `Stripe` contributor)?

Also, can you point me to the right place on where the tests regarding this issue should be added (if one was to add tests for this change)?

Thanks! 🙂

**Comment by derrickmehaffy** [comment]
@ognjenjevremovic absolutely we would love to have a PR :+1: 

 For tests I would suggest poking @alexandrebodin or @Convly
