### ISSUE TITLE
Webhook no longer allows to be saved without events

### ISSUE THREAD

**Issue by marko-s17** [strapi/strapi#9357]
## Bug report

Strapi won't allow the webhook to be saved if no events are selected. Previous versions allowed you to have _eventless_ webhook that can only be triggered manually, which was awesome for CI workflows. Now you **have** to have at least one event selected in order to save, therefore use the webhook. It could be that the Yup validation is a bit too strict with the webhook form.

### Steps to reproduce the behavior

1. Go to Webhook
2. Remove all events
3. Try to save the webhook

### Expected behavior

Strapi should allow users to have webhooks that are not triggered by any event aside from the manual trigger button.

### Screenshot

![screenshot](https://i.imgur.com/FPoDAIY.png)

### System

- Node.js version: v12.18.2
- Strapi version: 3.4.6
- Database: postgres
- Operating system: Linux/Debian

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-eventless-webhook-trigger/2734/5

**Comment by derrickmehaffy** [comment]
Confirmed on latest v3.4.6

**Comment by marko-s17** [comment]
Hey guys, any movement on this? We are thinking of rolling back to old version.

**Comment by KoTTi97** [comment]
Any updates on this?

**Comment by Convly** [comment]
Hey, sorry for the wait on this, it has been implemented in #12174 and will be available in the next release :magic_wand: 

_Closing this as it has been resolved, don't hesitate to reopen if you need._

**Comment by Convly** [comment]
Also, fixed it for the next V3 release too #12192
