### ISSUE TITLE
Logic of Password cannot contain more than three times the symbol `$` is not working as expected

### ISSUE THREAD

**Issue by neekneeraj** [strapi/strapi#9358]
### Describe the bug

Git Tag 3.4.6

Got the following code  while looking in the controller code for the route:/auth/local/register which calls the controller(register) present in the file: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js

```
 // Throw an error if the password selected by the user
  // contains more than three times the symbol '$'.
    if (strapi.plugins['users-permissions'].services.user.isHashed(params.password)) {
      return ctx.badRequest(
        null,
        formatError({
          id: 'Auth.form.error.password.format',
          message: 'Your password cannot contain more than three times the symbol `$`.',
        })
      );
    }
```

As per the comment, this code basically checks that received password string should not contain more than three times the character $.

When looking in the code of service isHashed present in the file: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/User.js
```
isHashed(password) {
    if (typeof password !== 'string' || !password) {
      return false;
    }
    return password.split('$').length === 4;
  },  
```

isHashed code is splitting password string on character $ & checking if the length of the array is 4. 

As per the comment present in the controller code, password string should not contain more than three time the symbol $.

But based on the isHashed logic, if password string has more than three times the character $, still the password will be valid & the user will be registered. 

So comment logic in controller code is not matching with the isHashed logic.
### Steps to reproduce the behavior

1. Send a post request to route /auth/local/register having three times the character $ in the password string.
2. Will get a error message:  "Your password cannot contain more than three times the symbol `$`."
3. Send a post request to route /auth/local/register having more than three times the character $ in the password string.
4. User will get registered without error.

### Expected behavior

Ideally when the password string has more than three times the symbol $ in the password string, then also the user should not get registered.

### Screenshots

POST request sent using postman & having three times the symbol $ in the password string. Got the expected error
![image](https://user-images.githubusercontent.com/12640133/107426293-0888d500-6b46-11eb-9a2a-b32516a9e6c6.png)

POST request sent using postman & having five times the symbol $ in the password string. User got registered, but ideally it should throw the error & user should not get registered.
![image](https://user-images.githubusercontent.com/12640133/107426610-7503d400-6b46-11eb-8bd0-ad05dd6fe22e.png)

### System

- Node.js version: v12.18.3
- NPM version:  6.14.6
- Strapi version: 3.4.6 Community edition
- Database: MySQL Ver 14.14
- Operating system: Ubuntu 16.04.7 LTS

**Comment by alexandrebodin** [comment]
Hi I'm going to go ahead and close this issue as we rebuilt the logic in v4 :)
