### ISSUE TITLE
Make page <title>s consistent in the Settings section of the Admin Panel

### ISSUE THREAD

**Issue by phripley** [strapi/strapi#9359]
### Describe the bug

The HTML `title`s in "Settings" are inconsistent and some are unclear.

With the plugins I have installed the titles read as follows:

| Label | Current Title | Suggested Title |
| ----------- | ----------- | ----------- |
| Application | "Settings - Infos" | Settings - Application |
| Media Library | "Settings" | Settings - Media Library |
| Webhooks | "Settings - Webhooks" | -  |
| Roles | "Settings - Roles"  | - |
| Users | "Settings - Users" | - |
| Roles | "Settings" | Settings - Roles |
| Providers | "Settings - Providers" | - |
| Email templates | "Settings - Email templates" | Settings - Email Templates |
| Advanced settings | "Settings - Advanced Settings" | - |

A weakness of my suggested titles is that they are not unique (there are two "Roles").

### Steps to reproduce the behavior

1. Load the pages in the control panel.  
2. Inspect in browser to see the <title>.

### Expected behavior

Clear and meaningful titles are useful for bookmarks, discerning among browser tabs and browser history.  These titles don't meet that standard.

### Screenshots

None.

### Code snippets

None.

### System

- Node.js version: v14.15.3 
- NPM version: 6.14.9
- Strapi version: 3.4.6: 
- Database: MySQL
- Operating system: Mac Catalina

**Comment by mfrachet** [comment]
Thank you for reporting this issue 🙏🏻 . This should have been fixed in the merged PR. I'm going to close this issue but feel free to reopen or ask for more details if you think it is not 😊 .

Have a great one and thank you again 👍🏻
