### ISSUE TITLE
Unhelpful error message when trying to create field with Chinese characters

### ISSUE THREAD

**Issue by ortonomy** [strapi/strapi#9365]
### Describe the bug

A deeply unhelpful error message when trying to create a field with Chinese characters

`The value does not match the regex.`

### Steps to reproduce the behavior

Try to create a field with chinese characters

### Expected behavior

I can create a field with chinese characters. Get a better error message if it doesn't exist. 

### Screenshots

![image](https://user-images.githubusercontent.com/6688676/107492530-88a34f00-6bc7-11eb-9c15-4fb7eeba5ecc.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.14.1
- NPM version: yarn, not npm: 1.22.10
- Strapi version: 3.4.6
- Database: mysql 8
- Operating system: macos big sur

### Additional context

-

**Comment by ortonomy** [comment]
Seems like it's not just chinese chracters. The form just flat out doesn't like spaces in field names:

![image](https://user-images.githubusercontent.com/6688676/107494143-68748f80-6bc9-11eb-9f16-48a6b02ae8c2.png)

Not very robust it seems.

**Comment by derrickmehaffy** [comment]
Currently in the CTB you need to create programmatic names that you can adjust later in the content-manager view settings.

https://strapi.io/documentation/user-docs/latest/content-manager/configuring-view-of-content-type.html

I've set this as a feature request to set the names and allow defining the "visual" names at the same time.

**Comment by derrickmehaffy** [comment]
I believe this already be handled properly in Strapi v4

**Comment by grimdeathr** [comment]
So what is the key that can update the message from "this does not match the regex" to something custom?
