### ISSUE TITLE
Custom Status Code During Registration

### ISSUE THREAD

**Issue by Prashant4900** [strapi/strapi#9366]
## Feature request
Is it's possible to return the custom Status Code during user registration

### Please describe your feature request
Sir is it's possible to return custom Status Code according to our preparance means if the username is already exists in database to it's return custom Status Code like 409 or if email is already exists so it's will return 407 or something like that 

Currently it's will return only 400 status code in any type of error or if I pass unique email but user name is Same in both condition the errors message is _email is already exists_

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Comment by derrickmehaffy** [comment]
We currently do not plan to add native support for this at this time.

Marking as closed as discussed with @Aurelsicoko
