### ISSUE TITLE
Useless password comparison in users-permissions/controllers/user/* update

### ISSUE THREAD

**Issue by boristian** [strapi/strapi#9374]
Hi,

this is not a real bug, it's more a code improvement.

In both controllers, admin and api, the comparison to decide wether to delete `password` from `updateData`.

The cleartext password from the request body is compared with the hashed password from the database. So, this comparison will never be true:
  * [admin](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/user/admin.js#L216-L218)
  * [api](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/user/admin.js#L216-L218)

**Comment by derrickmehaffy** [comment]
@boristian can you please update this with our issue template: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

This template is required for all issue, and in your case regardless of a true "bug" it's still a bug report.

**Comment by derrickmehaffy** [comment]
closing as the user isn't following our template
