### ISSUE TITLE
Impossible to have test working

### ISSUE THREAD

**Issue by Barbapapazes** [strapi/strapi#9376]
### Describe the bug

I'm not able to run any test. Can you provide a real world exemple test cases which work? I want to play with strapi but without test, it's just impossible.

### Steps to reproduce the behavior

1. Create app using quickstart
2. Follow the test guide on strapi docs
3. Test

### Expected behavior

I think this must work.

### Screenshots

![image](https://user-images.githubusercontent.com/45267552/107627475-a15f4380-6c5f-11eb-8f51-f9eb3c8f9ee7.png)

### System

- Node.js version: 14.15.5
- NPM version: 6.14.10
- Strapi version: 3.4.6
- Database: sqlite
- Operating system: windows 10 / ubuntu 20

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/7811
