### ISSUE TITLE
configuration restore does not respect environment

### ISSUE THREAD

**Issue by jorrit** [strapi/strapi#9378]
### Describe the bug

The `core_store` table contains an environment column. In my installation, only the key `plugin_upload_settings` uses the environment column to store different settings for production and development.

When dumping the configuration using `strapi config:dump` the dumped config file contains both entries for `plugin_upload_settings`, if they are present. But when importing using `strapi config:restore` only the `key` is used to check if a configuration section exists, so on production the production row is overwritten with the development row.

### Steps to reproduce the behavior

1. On an environment with both a development and production value for `plugin_upload_settings`, run `strapi config:dump`
2. On an environment with only `production`, run `strapi config:restore` with this file.
3. Observe that the row that used to contain `environment = production` now contains `environment = development`. This happens only when the development row appears after the production row in the dump file.
4. /admin/settings/media-library now fails to load because no production values can be found.

### Expected behavior

The environment value should be used as a key and both rows should be in the target database -or- only the production row should be present.

### System

- Node.js version: v14
- NPM version: v7
- Strapi version: 3.4.6
- Database: PostgreSQL
- Operating system: alpine docker on Ubuntu Linux

### Additional context

I noticed that all configuration values except `plugin_upload_settings` opt out of having environment specific settings. I think it would be wise to consider to drop the `environment` column, thereby circumventing this entire situation.

**Comment by derrickmehaffy** [comment]
@jorrit I've notified our dev team, as this is very legacy code (we don't actually use the environment option anywhere in the base code) we will review this and see if it's something we need to keep or if we can fix it.

If you have some thoughts on it and why you think it's important please do let us know.

**Comment by NamedPython** [comment]
Same here when I use plugins that could sync configuration between environment(e.g. strapi-plugin-migrate, strapi-plugin-config-sync)
Any updates?

Thanks.

**Comment by derrickmehaffy** [comment]
should be fixed as we don't use the env key anymore
