### ISSUE TITLE
Error installing or upgrading Strapi

### ISSUE THREAD

**Issue by ruijt** [strapi/strapi#9383]
## Bug report

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: backend@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.4.4
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.4.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sebastiaan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastiaan/.npm/_logs/2021-02-11T14_40_17_493Z-debug.log

### Describe the bug

When installing strapi with the command: npx create-strapi-app my-project --quickstart  OR running npm update on an existing strapi project, I get these errors.

### Steps to reproduce the behavior

run npx create-strapi-app my-project --quickstart  
OR running npm update on an existing strapi project

### System

- Node.js version: v12.13.1
- NPM version: 7.5.2
- Strapi version: v3.4.4
- Database: sql light
- Operating system: OSX

**Comment by perkinsjr** [comment]
I am also facing the same issue, running on Heroku after upgrade.

**Comment by cullylarson** [comment]
FYI, you can pass the `--force` flag to `npm install`. It will make npm ignore the peer dependency constraint. I just did it and haven't had any problems.

**Comment by MuradBuyukasik** [comment]
Same issue

**Comment by mirkonasato** [comment]
Same here. Probably related to npm 7 being stricter about [peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies).

Setting `"knex": "^0.20.0"` in `package.json` seems to work fine. After all, if that's the version expected by `strapi-connector-bookshelf` I don't see why the project should use an older version?

**Comment by derrickmehaffy** [comment]
Closing this in favor of: https://github.com/strapi/strapi/issues/9450

**Comment by loghomefinishing** [comment]
Strapi likes Node version 16.x.x and NPM 8.0.0
