### ISSUE TITLE
Access useDataManager in custom plugin

### ISSUE THREAD

**Issue by svrin** [strapi/strapi#9384]
Hi,

we extend the EditView of the content-plugin and want to listen for changes on the model or when the model is saved or published. 

When trying to import the useDataManager hook it gives us undefined:
`import useDataManager from "strapi-plugin-content-type-builder/admin/src/hooks/useDataManager";`

When we import it via .cache it works:
`import {useDataManager} from "../../../../../../.cache/plugins/strapi-plugin-content-manager/admin/src/hooks";`

We render our component via InjectedComponent:

```export default strapi => {
  // ...
    injectedComponents: [
      {
        plugin: 'content-manager.editView',
        area: 'right.links',
        component: OurComponent,
        key: 'ourplugin.OurComponent',
        props: {},
      }
    ],
  // ....
```

Is there are way to access DataManager in an injected component?

**Comment by soupette** [comment]
Hello!

Currently, there's no way to access the DataManager from a plugin, for the moment you'll need to override the core files in order to access it.

**Comment by derrickmehaffy** [comment]
Marking as closed as this was a question and was answered. Further questions should be directed to our forum: https://forum.strapi.io

**Comment by ashbuilds** [comment]
Hi @soupette @derrickmehaffy, I'm also looking for something similar. Where I want my plugin to reflect changes according to data changes on `collectionType` page, similar to what we have for `slug / UID` types. We should be able to get those UI updates in order to update our plugin accordingly. Is there anything else I can use for this purpose?
I tried using `useDataManager` but it's only available in `.cache`

**Comment by 29hsaeed** [comment]
Hii!

I'm getting this error: 

Error: Module not found: Error: Can't resolve '../../hooks/useDataManager' in '../.cache/plugins/strapi-plugin-content-manager/admin/src/InjectedComponents/PreviewURL'.

I shall be thankful if anyone could point me in the right direction.

**Comment by soupette** [comment]
You need to import it from the `strapi-helper-plugin` 

```
import { useContentManagerEditViewDataManager } from 'strapi-helper-plugin'
```
