### ISSUE TITLE
Question: permission on row level?

### ISSUE THREAD

**Issue by oeddyo** [strapi/strapi#939]
Hi,

I'm trying to allow multiple users to publish articles, and they can only operate on their articles (i.e. update, delete etc). But seems strapi currently only support role level, i.e. either an user can edit all articles or not. 

Is there anyway I can achieve this?

**Comment by lauriejim** [comment]
Can you please check existing issues if one already exist : https://github.com/strapi/strapi/issues/624

**Comment by lauriejim** [comment]
I write this search to find this issue https://github.com/strapi/strapi/issues?utf8=✓&q=is%3Aissue+is%3Aopen+data+owner
