### ISSUE TITLE
Bad error message in registration

### ISSUE THREAD

**Issue by arnaud512** [strapi/strapi#9398]
### Describe the bug

When user register with same username, the error message say: "Email already taken".

### Steps to reproduce the behavior

1. Register a user with username aa and email a@a.fr
2. Try register a user with username aa and email aa@aa.fr

the error message say:
` "id": "Auth.form.error.email.taken",
   "message": "Email already taken"`

### Expected behavior

The message should be something like username already taken

### Screenshots

![image](https://user-images.githubusercontent.com/3939593/107894915-49466c80-6eff-11eb-91bb-f019e858cb39.png)
![image](https://user-images.githubusercontent.com/3939593/107894920-4c415d00-6eff-11eb-9e75-ab69d80c7edf.png)

### System

- Node.js version: v14.15.1
- Strapi version: 3.4.6
- Database: postgres
- Operating system: mac

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/5479

The issue is because this is the last "check" when something fails. It's a part of a much larger refactoring to the users-permissions plugin that is needed.
