### ISSUE TITLE
Strapi Admin Frontend returns 404 not found on page refresh

### ISSUE THREAD

**Issue by ravgeetdhillon** [strapi/strapi#9399]
### Describe the bug

Strapi Admin Frontend returns 404 not found on page refresh

### Steps to reproduce the behavior

1. Deploy Strapi backend on Heroku
2. Deploy Strapi Admin frontend on Netlify
3. Login to Strapi Admin
4. Go into any page, for example,  **Users** content type
5. Refresh the page
6. It will show **404 not found**

### Expected behaviour

The page should reload normally as happens with every web application.

### System

- Node.js version: 14.15.1
- NPM version: 6.14.11
- Strapi version: 3.4.6
- Database: MySql
- Operating system: Linux Ubuntu 20.04

**Comment by ravgeetdhillon** [comment]
Since I am using Netlify, I added a redirect in my **netlify.toml**

```toml
[[redirects]]
from = "/*"
status = 200
to = "/index.html"
```

But in my opinion, this could be handled within Strapi using HashRouter instead of BrowserRouter to solve this problem.

**Comment by ath88** [comment]
This is not something Strapi can do - Netlify handles the way the client receives your bundle. I Netlify doesn't serve the index.html on a specific path, theres nothing Strapi can do. The 404 you got was from Netlify itself.
