### ISSUE TITLE
Can't also fix CORS blocking

### ISSUE THREAD

**Issue by kgnfth** [strapi/strapi#9406]
Hello i keep getting this error

`Access to XMLHttpRequest at 'https://strapi.domain.fun/links' from origin 'https://laravel.domain.fun' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.`

i have addid this to my `./config/middleware.js`

```
module.exports = {
  settings: {
    cors: {
      enabled: true,
      origin: ['*']
    },
  },
};
```

i run strapi using docker with nginx reverse proxy

this is my dockerfile 

```
FROM strapi/base

WORKDIR /backend

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
```

can anyone help me pls

**Comment by alexandrebodin** [comment]
Form you error message the cors issue is on the "laravel.domain.fun" domain not the strapi domain. 

It looks like you have a client side app making api queries to a laravel app. Can you give more details about your setup ?

**Comment by kgnfth** [comment]
> Form you error message the cors issue is on the "laravel.domain.fun" domain not the strapi domain.
> 
> It looks like you have a client side app making api queries to a laravel app. Can you give more details about your setup ?

yes i am trying to access the api using axios like this

```
axios.get('https://strapi.domain.fun/links')
.then((response)=>{
  this.links = response.data
  })
```

**Comment by alexandrebodin** [comment]
You need to add the header "x-requested-with" into the cors allowed headers

**Comment by kgnfth** [comment]
Thank you it working now
