### ISSUE TITLE
Strapi `docker-compose up` gets stuck on Error: Cannot find module './moment-timezone'

### ISSUE THREAD

**Issue by gilzon** [strapi/strapi#9408]
![image](https://user-images.githubusercontent.com/24877990/107967209-d6a6c100-6fd2-11eb-8d17-a306f4831d58.png)

Tried installing `moment-timezone` from npm! Didn't solve the error!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
