### ISSUE TITLE
Empty dynamic zones can break graphql scheam generation

### ISSUE THREAD

**Issue by alexandrebodin** [strapi/strapi#9409]
### Describe the bug

When you create multiple Dynamic zones without components in them graphql will break on restart because of the EmptyQuery type generated too many times :)

### Steps to reproduce the behavior

1. go into the content type builder
2. create multiple dynamic zones without components
3. click save 

### Expected behavior

Nothing should happen :D

### Code snippets

```
There can be only one type named "EmptyQuery".
```

### System

- Node.js version: v12
- NPM version: v6
- Strapi version: 3.4.6
- Database: sqlite
- Operating system: linux

**Comment by noxsiio** [comment]
have the same problem. someone has a solution for that? :(

**Comment by alexandrebodin** [comment]
Hi @noxsiio make sure you don't leave the dynamic zones empty :) e.g

```json
{
  "attributes": {
    "my-dz": {
       "components": [] //make sure there is at least one compo
     }
  }
}
```

**Comment by marcoautiero** [comment]
In v4 it's not possible to save a DZ without any component inside.
