### ISSUE TITLE
Custom route on models with hyphens cannot be accessed with GraphQL - 403 forbidden

### ISSUE THREAD

**Issue by sanjuant** [strapi/strapi#9410]
### Describe the bug

Hello, while trying to create a custom route for my slugs on an entity with a hyphen, I noticed that the resource was becoming inaccessible with Graphql.

### Steps to reproduce the behavior

1. Install GraphQL and slugify
```
yarn strapi install graphql
yarn add slugify
```
2. Create model with hyphen and add title and slug
![image](https://user-images.githubusercontent.com/27998877/107987256-f687b600-6fcd-11eb-8b78-f562d3d3e49f.png)
3. In model config add schema.graphql.js
```js
// api/model/schema.graphql.js

const {sanitizeEntity} = require('strapi-utils');

module.exports = {
  query: `faqInformationBySlug(id: ID slug: String): FaqInformation`,
  resolver: {
    Query: {
      faqInformationBySlug: {
        resolverOf: 'FaqInformation.findOne', async resolver(_, {slug}) {
          const entity = await strapi.services.faqInformation.findOne({slug});
          return sanitizeEntity(entity, {model: strapi.models.faqInformation});
        },
      },
    },
  },
};
```
4. In model definition add lifecycles for slug
```js
// api/models-faq-informations.js
'use strict';
const slugify = require('slugify');

module.exports = {
  lifecycles: {
    beforeCreate: async (data) => {
      if (data.title) {
        data.slug = slugify(data.title,{ lower: true});
      }
    },
    beforeUpdate: async (params, data) => {
      data.slug = slugify(data.title,{ lower: true});
    },
  },
};
```
5. Allow permissions to findOne and find
![image](https://user-images.githubusercontent.com/27998877/107986169-cc34f900-6fcb-11eb-9478-bda008923d3f.png)
6. Add an item
![image](https://user-images.githubusercontent.com/27998877/107986243-f25a9900-6fcb-11eb-804f-81ac292049ac.png)
7. Go on graphql endpoint and make request
![image](https://user-images.githubusercontent.com/27998877/107986305-17e7a280-6fcc-11eb-9ece-7b357ddf3cbe.png)
![image](https://user-images.githubusercontent.com/27998877/107986865-3a2df000-6fcd-11eb-8273-ed1041dd8563.png)
8. You can see your access is forbidden

### Expected behavior

With model without hyphen is work perfectly.

![image](https://user-images.githubusercontent.com/27998877/107986520-89bfec00-6fcc-11eb-9f2e-58e911a051fb.png)
![image](https://user-images.githubusercontent.com/27998877/107986830-284c4d00-6fcd-11eb-8f9a-59388ce2290b.png)

### Code snippets

I tried several ways to write the name of the model, but it didn't work.
```js
resolverOf: 'FaqInformation.findOne', async resolver(_, {slug}) {
  const entity = await strapi.services.faqInformation.findOne({slug});
  return sanitizeEntity(entity, {model: strapi.models.faqInformation});
},

resolverOf: 'FaqInformation.findOne', async resolver(_, {slug}) {
  const entity = await strapi.services.faqinformation.findOne({slug});
  return sanitizeEntity(entity, {model: strapi.models.faqinformation});
},

resolverOf: 'FaqInformation.findOne', async resolver(_, {slug}) {
  const entity = await strapi.services.faq_information.findOne({slug});
  return sanitizeEntity(entity, {model: strapi.models.faq_information});
},

resolverOf: 'FaqInformation.findOne', async resolver(_, {slug}) {
  const entity = await strapi.services['faq-information'].findOne({slug});
  return sanitizeEntity(entity, {model: strapi.models['faq-information']});
},
```

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.6
- Database: postgres
- Operating system: windows 10 x64

**Comment by derrickmehaffy** [comment]
Generally speaking since this is a question about customization we don't allow these issues on github and should be posted on our forum: https://forum.strapi.io

However I will make an exception here as this is a fairly complex issue. Let me tag @strapi/maintainers to see if anyone on the team has an idea.

**Comment by derrickmehaffy** [comment]
@pwizla we will probably need to document this if a workaround is found as it would be good for the schema customization part.

**Comment by sanjuant** [comment]
For my part, the only workaround I found was to name my entity without hyphens or underscore.

![image](https://user-images.githubusercontent.com/27998877/109177642-4f9ed900-7788-11eb-8815-0b9c99d73b92.png)

Then I changed the name of my collection but it wouldn't have mattered. And most importantly I changed the name of my roads to make them more readable.

_api/faqinformation/models/faqinformation.settings.json_
```json
{
  "kind": "collectionType",
  "collectionName": "faq_informations",
  "info": {
    "name": "FAQ et Informations",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "slug": {
      "type": "string",
      "unique": true
    },
    "content": {
      "type": "richtext"
    },
    "footer_link_category": {
      "model": "footer-link-category",
      "via": "faq_informations"
    }
  }
}
```

_api/faqinformation/config/routes.json_
```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/faqinformations",
      "handler": "faqinformation.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/faq-informations/count",
      "handler": "faqinformation.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/faq-informations/:id",
      "handler": "faqinformation.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/faq-informations/:slug",
      "handler": "faqinformation.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/faqinformations",
      "handler": "faqinformation.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/faq-informations/:id",
      "handler": "faqinformation.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/faq-informations/:id",
      "handler": "faqinformation.delete",
      "config": {
        "policies": []
      }
    }
  ]
}

```

_api/faqinformation/config/schema.graphql.js_
```js
const {sanitizeEntity} = require('strapi-utils');

module.exports = {
  query: `faqinformationBySlug(id: ID slug: String): Faqinformation`,
  resolver: {
    Query: {
      faqinformationBySlug: {
        resolverOf: 'Faqinformation.findOne', async resolver(_, {slug}) {
          const entity = await strapi.services.faqinformation.findOne({slug});
          return sanitizeEntity(entity, {model: strapi.models.faqinformation});
        },
      },
    },
  },
};
```

**Comment by MikeMajara** [comment]
@sanjuant Did you try using key access like so: `strapi.services['faq-informations'].create({...` I had a similar problem with a space separated entity name with hyphen separated words.

**Comment by sanjuant** [comment]
@MikeMajara  Yes i try this. You can see on Code Snippet in my first post. In debug, inside Strapi.service i see 'faq-informations' but dont work. My workaround is on top of your message.

**Comment by MikeMajara** [comment]
Oh sorry I missed that bit.

Can you console.log(strapi.services) and see what that contains? Can you see your service there?

**Comment by derrickmehaffy** [comment]
fixed on v4 since graphql doesn't rely on REST except for users-permissions
