### ISSUE TITLE
Graphql: Result array items of query for collection items should be required.

### ISSUE THREAD

**Issue by tvojtech** [strapi/strapi#9411]
### Describe the bug

Having a simple Collection type `Test {a: string}` graphql plugin generates query `tests(): [Test]`. This means items in the result array are optional. I think it should be `[Test!]`. I can't see any situation the API should return null array items.

It leads in unnecessary nullability checks and TS errors.

### Steps to reproduce the behavior

- Create a simple collection type.
- Install graphql plugin.
- Check in graphql playground.

### Expected behavior

Array items should be required in query result. `tests(): [Test!]`

### Screenshots

![tests gql](https://user-images.githubusercontent.com/1427446/107996045-baf5e780-6fdf-11eb-8d0e-b5accd3e1549.png)

### Code snippets

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/type-definitions.js#L470

**Comment by matheusmb** [comment]
Any updates on this? I'm having issues with graphql-code-generator due this bug. It's marking array items as optional when it shouldn't.

**Comment by stutrek** [comment]
Note that the solution above only works for the shadow CRUD queries that are automatically generated. It does not work for custom queries, nor does it work for relations.

**Comment by christiaan-lombard** [comment]
Related issue: https://github.com/strapi/strapi/issues/11815

**Comment by derrickmehaffy** [comment]
> Related issue: #11815

Gut is telling me these are duplicates :thinking:

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/11815

**Comment by ericbf** [comment]
This seems unrelated to #11815, which is about GraphQL-Entity props, whereas this one is about the element type of an array. Generally speaking, there shouldn't really ever be an array type where the element itself is nullable, as in `foo: [Bar]`. It should always be `foo: [Bar!]`.
