### ISSUE TITLE
Enable RTL support in rich-text formats already solved. 

### ISSUE THREAD

**Issue by maggie0002** [strapi/strapi#9412]
This request is somewhere between a query and a feature request, hence posting here.

There is a great solution posted here for allowing right-to-left languages in the rich-text boxes (such as writing in Arabic):

https://github.com/strapi/strapi/issues/3114#issuecomment-629813215

Is there a reason not to include that CSS by default? Querying before submitting a pull request.

**Comment by derrickmehaffy** [comment]
No particular reason @maggie0002 but we would be happy to see a PR!
