### ISSUE TITLE
GraphQL Forgot Password mutation is not working

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#9415]
### Describe the bug

GraphQL `forgotPassword` mutation does not work as it always responses `Bad Request` even though I already set allow to `forgotpassword` in Users-Permissions and followed `forgotPassword` mutation documentation provided by Strapi in GraphQL Playground.

### Steps to reproduce the behavior

1. Go to 'Settings' on the left menu
2. Click on 'Users & Permissions plugin' then select 'Roles'
3. Edit 'Authenticated' role
4. Scroll down to 'USERS-PERMISSIONS' then give a mark to 'forgotpassword' to allow it. Click Save.
5. Go to GraphQL Playground (http://localhost:1337/graphql) to test forgotPassword mutation and set email as a variable.
6. Insert email address in variable.
7. Run forgotPassword mutation.
8. See error response `Bad Request` but Strapi log showing  /POST graphql 200.

### Expected behavior

Response : `{ ok : true }`

### Screenshots
I allowed Forgot Password for authenticated users in Roles and Permissions : 

![allowed forgot password](https://user-images.githubusercontent.com/43397636/108033051-fb984400-7065-11eb-8c45-ab525939b6f5.png)

Then I tested Forgot Password mutation in GraphQL Playground. I already followed GraphQL docs for `forgotPassword` mutation but it always responded `Bad Request` :

![forgot password - bad request](https://user-images.githubusercontent.com/43397636/108032558-42396e80-7065-11eb-9673-fe61b70113c1.png)

However, Strapi log shows HTTP response status 200 OK : 

![strapi log](https://user-images.githubusercontent.com/43397636/108032662-672de180-7065-11eb-9caa-222cce4076df.png)

### System

- Node.js version: v14.15.5
- Yarn version: v1.22.5
- Strapi version: v3.4.6
- Database: MongoDB
- Operating system: Ubuntu Focal 20.04 LTS

**Comment by dani832m** [comment]
I am experiencing exactly the same problem. Have you found a solution, or is the mutation simply not working right now?

**Comment by kevinadhiguna** [comment]
@dani832m Yes, I can confirm that this still happens in latest Strapi stable and NodeJS LTS version.

![forgot password](https://user-images.githubusercontent.com/43397636/110925844-3f752500-8356-11eb-9141-fe18f18d8684.png)

Application Info : 
![System](https://user-images.githubusercontent.com/43397636/110925854-43a14280-8356-11eb-8405-0ac304989c36.png)

**System** : 
- Node.js version: v14.16.0
- Yarn version: v1.22.5
- Strapi version: v3.5.3
- Database: MongoDB
- Operating system: Ubuntu Focal 20.04 LTS

Any help will be appreciated.

**Comment by dani832m** [comment]
By default Strapi provides a local email system called Sendmail, but I can see that many experience they get "Bad Request" using this provider. I switched to a third party ([SendGrid](https://www.npmjs.com/package/strapi-provider-email-sendgrid)), and now everything is working!

Just install a new provider, get your API key and make a few configurations in `./config/plugins.js`

Doc: https://strapi.io/documentation/developer-docs/latest/development/plugins/email.html

**Comment by derrickmehaffy** [comment]
@dani832m is correct, you need to have sendmail package installed and configured.

Marking as closed:

![image](https://user-images.githubusercontent.com/8593673/112908686-cb03eb00-90a4-11eb-88a0-5e6043d3e56a.png)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/email-setup-on-ubuntu-auth-form-error-email-invalid/4130/4

**Comment by kevinadhiguna** [comment]
I was just reading that at the moment. What a coincidence haha. Although, I heard that `sendmail` needs to be configured before we are able to use it, is that true ?
Furthermore, I heard a third-party service such as `sendmail` or `mailgun` are easier to setup. What's your thought ?

**Comment by kevinadhiguna** [comment]
> By default Strapi provides a local email system called Sendmail, but I can see that many experience they get "Bad Request" using this provider. I switched to a third party ([SendGrid](https://www.npmjs.com/package/strapi-provider-email-sendgrid)), and now everything is working!
> 
> Just install a new provider, get your API key and make a few configurations in `./config/plugins.js`
> 
> Doc: https://strapi.io/documentation/developer-docs/latest/development/plugins/email.html#configure-the-plugin

Thanks for your response @dani832m . It was helpful although Sendmail asks details how we use the service and sometimes one can be suspended/banned if required information is not provided enough (even though we say it is for testing only).

**Comment by derrickmehaffy** [comment]
Largely depends @kevinadhiguna as many hosts block sending emails from servers to prevent spam. I would say that most of the providers are generally safer and easier to setup but there is obviously a cost involved.

The other option (the one I use on my own projects) is to create an actual email server using something like mailcow: https://mailcow.email/ and use the nodemailer provider. Similiar restrictions as sendmail but it has some baked in middleware to handle a lot of the required headers and such, plus it has a built in SoGo interface if you really want to go the "self-hosted" email service.

**Comment by dlujan** [comment]
I'm still facing a similar issue. Instead I get an "unauthorized" error when I try to fire the forgotPassword mutation. I have the permission checked in the strapi admin too. I'm using strapi v4.
`"errors": [
    {
      "message": "Unauthorized",
      "extensions": {
        "error": {
          "name": "ApplicationError",
          "message": "Unauthorized",
          "details": {}
        },
        "code": "STRAPI_APPLICATION_ERROR"
      }
    }
  ],
  "data": {
    "forgotPassword": null
  }`

**Comment by james-theretreater** [comment]
I am having this same problem, `forgotPassword` is checked in Users and Permissions for Public user. My mutations...

```
mutation forgotPassword {
  forgotPassword(email: "james+test1@theretreater.com") {
    ok
  }
}
```

Response
```
{
  "errors": [
    {
      "message": "Internal Server Error",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": {
    "forgotPassword": null
  }
}
```

Strapi Log
```
[2022-04-20 09:26:52.312] error: Forbidden
ApplicationError: Forbidden
    at Object.forgotPassword (/app/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:271:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-04-20 09:26:52.313] http: POST /graphql (313 ms) 200
```
