### ISSUE TITLE
POST Request using Postman? 

### ISSUE THREAD

**Issue by lddd** [strapi/strapi#942]
Hey there,

i am new to Strapi and API development at all and would like to know how a Post Request using Postman will have to look like to create a new api object with its attributes.

When i send a raw JSON post request like:

http://localhost:1337/car/

```
{
   "name": "Test",
   "year": "1955",
   "license": "A"
}
```

It creates a new car object with an id but all the attributes are not stored like name, year, license...

**Comment by lauriejim** [comment]
Please can you use the issue template, we need to know you node, npm, strapi version and if you are using mongo or sql database.

**Comment by lauriejim** [comment]
Your Car.settings.json has `name`, `year` and `licence` attributes with text type ?

**Comment by lddd** [comment]
Yes

**Comment by lddd** [comment]
> Please can you use the issue template, we need to know you node, npm, strapi version and if you are using mongo or sql database.

All just latest technologies following the starter docs at Strapi.io

**Comment by bugvish** [comment]
@lddd are any of 'name' 'year' or 'license' their own tables (e.g are they 'relational')?  For what it's worth - I had a similar issue with my collections containing relational components.  I needed to modify my generated APIs' service to NOT reject relational values in order make a POST, like the following:
https://github.com/strapi/strapi-examples/blob/master/cheesecakes/api/cake/services/Cake.js#L68

Change:
const data = await Cake.create(_.omit(values, _.keys(_.groupBy(strapi.models.cake.associations, 'alias'))));

To:
const data = await Cake.create(values);

Might not apply to your particular issue @lddd , but hopefully others might see this and benefit.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
