### ISSUE TITLE
Error while running create-strapi-app (`error: unknown option `--no-optional'`)

### ISSUE THREAD

**Issue by cullylarson** [strapi/strapi#9425]
### Describe the bug

I'm running create-strapi-app according to the Quickstart guide (`npx create-strapi-app my-project --quickstart`) and getting this error:

```
Creating a new Strapi application at /path/to/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:

  error: unknown option `--no-optional'

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
...
```

### Steps to reproduce the behavior

1. Run `npx create-strapi-app my-project --quickstart`
1. See error

### System

- Node.js version: 14.15.4
- NPM version: 7.5.2
- Strapi version: 3.4.6
- Database: NA
- Operating system: macos

**Comment by derrickmehaffy** [comment]
> NPM version: 7.5.2
We don't support npm v7: https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements
