### ISSUE TITLE
Setting id to a private variable in /config/api.js breaks the media picker in content type.

### ISSUE THREAD

**Issue by iamscottcab** [strapi/strapi#9426]
### Describe the bug

When configuring the API to set global private attributes via `/config/api.js` the Media Picker when selecting media in a content type returns the error:

```
Something went wrong.
Details
TypeError: Cannot read property 'toString' of undefined
```

### Steps to reproduce the behavior

1. Create a Content Type with a Media field (mine is set to multiple and image only)
2. Create a config file `/config/api.js` and set to the following:

```
module.exports = ({ env }) => ({
    responses: {
      privateAttributes: ['id', 'created_at', 'updated_at'],
    }
  });
```

3. Try to create a new entry for the content type created.
4. Click on the image picker.
5. Select and image.

### Expected behavior

Image is inserted into the content.

### Current behavior

Error is thrown and not cleared until a hard refresh.

### System

- Node.js version: 14.15.3
- NPM version: 6.14.9
- Strapi version: 3.4.6 Community Edition
- Database: Postgres
- Operating system: Ubuntu WSL2

### Additional context

The media library itself seems to be working as expected here, it's just the media picker object within the content type itself.

**Comment by soupette** [comment]
Well, in order to associated a file to entry we need the file's `id` so even though if we provide a fix so the input does not break when you remove the id from the response you won't able to associate any file to your entry. I suggest to not remove the id from the responses.

cc/ @alexandrebodin

**Comment by iamscottcab** [comment]
Thanks, I have removed the id from the `privateAttributes` for now and am just stripping the value from the response body which is fine.

My understanding was a private attribute was available in the admin portal (and I guess by extension any of those plugins) but not the API endpoints. Is this not how it works or should the id just never be set as a `privateAttribute`? If it's the latter maybe a change to the docs would be a useful short term fix.

**Comment by derrickmehaffy** [comment]
I believe this should be fixed in v4
