### ISSUE TITLE
Store view configuration of a component

### ISSUE THREAD

**Issue by felixhagspiel** [strapi/strapi#9432]
## Feature request
(Nice to have)

### Please describe your feature request

- [ x] **I have created my request on the Product Board before I submitted this issue**
- [ x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I would like to store a components view configuration in a JSON file (or inside the components config JSON file) to be able to keep the view when I deploy to staging or development. 

### Why is it needed?

When I add new fields to a component on my local machine, I configure the view of the component. When I deploy the changes to staging or production, I have to re-arrange the fields for each component.

### Suggested solution(s)

Use the field order according to the components `attributes` order in the settings JSON file or create a separate JSON file for configuring the component view.

Example: 
```

{
  "collectionName": "components_page_body_components_formatted_texts",
  "info": {
    "name": "FormattedText",
    "icon": "align-justify",
    "description": ""
  },
  "options": {},
  "attributes": {
    "MarginBottom": {
      "type": "enumeration",
      "enum": [
        "default",
        "x1",
        "x2",
        "x3",
        "x4",
        "x5",
        "x6"
      ],
      "default": "default"
    },
    "text_de": {
      "type": "richtext"
    },
    "text_en": {
      "type": "richtext"
    }
  }
}

```
If the file looks like this, it should display `MarginBottom` first, then `text_de` and then `text_en`. Currently, if the component already exists and I add `MarginBottom` at a later point to that component, it is displayed last. When I change the view to show `MarginBottom` as first field it works, but after a deployment I have to re-arrange the view again.

### Related issue(s)/PR(s)

-

**Comment by derrickmehaffy** [comment]
At the moment we are not entertaining content-manager views in a file, see: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#can-i-store-my-content-manager-layout-configurations-in-the-model-settings

I would recommend using the CLI dump/restore commands:

https://strapi.io/documentation/developer-docs/latest/cli/CLI.html#strapi-configuration-dump
https://strapi.io/documentation/developer-docs/latest/cli/CLI.html#strapi-configuration-restore
