### ISSUE TITLE
Strapi server in development mode is not starting

### ISSUE THREAD

**Issue by carlopfd** [strapi/strapi#9435]
### Describe the bug

The Strapi server when started in development mode by `npm run develop` or `strapi develop` would not start. The process stops without an error or any other message. `npm run start`, `strapi start` or `strapi build` works without a problem. 

### Steps to reproduce the behavior

1. Setup new project via `npx create-strapi-app test_bug --quickstart`
2. Wait until installation is completed
3. The included `strapi start` in the installation process is not working
4. Try to start the server manually by changing to the project directory and executing `npm run develop`

### Expected behavior

Strapi server starts fine in development mode and browser opens up.

### System

- Node.js version: v14.15.5
- NPM version: 6.14.11
- Strapi version: 3.4.6
- Database: SQLite
- Operating system: macOS 11.2.1 (Apple Silicon)

### Additional context

Thank you very much for your support!!

**Comment by carlopfd** [comment]
Just to show what I mean with not showing any error log. Thank you!
<img width="569" alt="Bildschirmfoto 2021-02-17 um 22 07 27" src="https://user-images.githubusercontent.com/41333018/108268262-8e230b00-716c-11eb-8408-b3a57fef2bd2.png">

**Comment by LucaNerlich** [comment]
This is not an issue with strapi, it is most likely due to your machines setup. Have you retried with the same versions on a different machine / vm?

Also please check this information regarding Apple M1 https://github.com/strapi/strapi/pull/9106

**Comment by derrickmehaffy** [comment]
As @LucaNerlich this is almost certainly an issue with your environment. Without more information we can't reproduce, and thus can't fix the issue.

Strapi usage on M1 ARM based Macs is not technically supported (we even have a few internally within Strapi) and are currently using the sharp workaround until better support in the node ecosystem.

**Comment by awwabtahir** [comment]
I am facing the same issue, I am running in Linux Mint.

**Comment by derrickmehaffy** [comment]
> I am facing the same issue, I am running in Linux Mint.

Can you provide more information as I am also a Linux Mint user and cannot reproduce:

![image](https://user-images.githubusercontent.com/8593673/126706620-add14305-569c-4cc7-a785-26b6a7bf1331.png)

![image](https://user-images.githubusercontent.com/8593673/126706687-d15898a7-2d88-48b3-a796-c321838a102d.png)

**Comment by awwabtahir** [comment]
@derrickmehaffy I restarted the machine, tried to develop again and it works. So most probably there was some problem in the environment.

**Comment by derrickmehaffy** [comment]
One of those odd moments when turning it off and on again fixes the issue :rofl: 

Glad you got it working again though!
