### ISSUE TITLE
Allow to specify core-store db connection

### ISSUE THREAD

**Issue by brooth** [strapi/strapi#9452]
### Please describe your feature request

- [ ] **I have created a pull request that fixes this issue**

### Summary

We need a way to store admin layout settings to a file and push it to the git repository. Otherwise, we have to modify settings manually in the staging/production environment (which is always forgotten)

### Why is it needed?

I respect your need to store the configs to a database but in my cases (I work as a freelancer and use Strap Admini to provide UI/CMS/PIM/Admin panel to my customers) it's just a nightmare 

### Suggested solution(s)

Allow to modify core-store database connection and thus to store the settings to a project file

**Comment by derrickmehaffy** [comment]
We have two commands for this (dump to file and restore from file):

https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html#strapi-configuration-dump
https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html#strapi-configuration-restore

We won't change the logic of the core-store to pull only from a file based on this FAQ: https://docs.strapi.io/developer-docs/latest/getting-started/troubleshooting.html#can-i-store-my-content-manager-layout-configurations-in-the-model-settings
