### ISSUE TITLE
Login with twitter seems broken

### ISSUE THREAD

**Issue by erhankaradeniz** [strapi/strapi#9458]
When loggin in with twitter it seems something is going wrong.
I've followed this guide: `https://strapi.io/blog/user-authentication-in-next-js-with-strapi` and replaced google with Twitter. backend I make a request to `auth/twitter/callback?access_token?{token-her}` it return a bad request.

Saying this:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": {
    "errors": [
      {
        "code": 32,
        "message": "Could not authenticate you."
      }
    ]
  },
  "data": {
    "errors": [
      {
        "code": 32,
        "message": "Could not authenticate you."
      }
    ]
  }
}
```

It seems to work when I disabled jwt, however when that is disabled it doesnt link anything to a strapi account. so the jwt option needs to be turned on I guess.

**Comment by erhankaradeniz** [comment]
I've tested the same functionality with Google auth and that seems to work, after a successful login a user is also created within the strapi admin. So I'm sure that the Twitter part is broken. Just not sure why it's broken. The only thing I noticed is that the access_token given by google is alot longer than the access_token given by Twitter.

**Comment by alaminut** [comment]
Had the exact same issue with Twitter. When you call your backend api from frontend with the access_token query parameter. You must include all query parameters coming down to your frontend for Twitter not just the access_token.

This is the code that is working for me to login with Twitter, Facebook, Instagram and Discord:


```
const url = `${process.env.NEXT_PUBLIC_API_URL}/auth/${provider}/callback`;
    try {
      const loginResponse = await axios.get<LoginResult>(url, {
        params: { ...ctx.query }, // notice I'm passing all query string params not just access_token
      });
      user = loginResponse.data;
    } catch (e) {
      statusCode = e.response?.status || 500;
      ctx.res.statusCode = statusCode;
      console.log(e.response);
    }
```

**Comment by erhankaradeniz** [comment]
He Thanks for the response, are you also using next-auth on the frontend? What else do you have in your query parameters, since I only have an access_token and a refreshtoken, I tried adding both but without success..

**Comment by derrickmehaffy** [comment]
@erhankaradeniz can you please update your issue with the proper template or at least the SYSTEM block of information so I can try to reproduce. Issue templates are required here as dictated by our github config: 

https://github.com/strapi/strapi/blob/d5049777ead948e1041690f8c88772423603959a/.github/ISSUE_TEMPLATE/config.yml#L1

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
