### ISSUE TITLE
net::ERR_CONNECTION_REFUSED with bash scritpt on ubuntu 16.4

### ISSUE THREAD

**Issue by JonasJustus** [strapi/strapi#946]
Node

**Informations**
- **Node.js version**: node 9.11.1
- **npm version**: npm 5.6.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: mongo v3.4.14
- **Operating system**: Ubuntu 16.04.4 LTS 

**What is the current behavior?**
I installed it with the bash script from your Blog
I can access Admin console and create stuff 
If I want to make a get with my website in the public folder I get net::ERR_CONNECTION_REFUSED 
(Roles &Permission are set on Find for public users)
Any Idea?

**Comment by thebetterjort** [comment]
I have the same issue. I'm currently debugging this.

**Comment by lauriejim** [comment]
Hello, can you give me more informations please. Can you link the script you use.
What is the file path you try to get in your public folder ?

**Comment by JonasJustus** [comment]
script: wget -qO - https://strapi.io/install.sh | sudo -E bash && source ~/.bashrc 
from here: [https://blog.strapi.io/how-to-deploy-a-strapi-application/](https://blog.strapi.io/how-to-deploy-a-strapi-application/)

File path: /home/user/Project(Strapi Project)/public/

**Comment by pierreburgy** [comment]
It's because the script setup the server but does not generate and start the Strapi project. After running the script please run the following command:
```
strapi new app
cd app
NODE_ENV=production pm2 start server.js
```

Maybe we should add these commands in the scripts?

**Comment by JonasJustus** [comment]
It was my fault. The error was in my code, had still a localhost in it :(
Thanks for your help guys
Solved
