### ISSUE TITLE
Nested Image component relation broken and does not save 

### ISSUE THREAD

**Issue by kevinvugts** [strapi/strapi#9462]
## Bug report
I have a Card List component which contains a repeatable list of Card components. Each card component has the ability to add an Image component. This functionality cannot be saved form the UI which is as expected. But can be achieved via the code. 

**This is how I did this in earlier versions:**

**Card List**
```
{
  "collectionName": "components_blocks_card_lists",
  "info": {
    "name": "Card List",
    "icon": "grip-horizontal"
  },
  "options": {},
  "attributes": {
    "cards": {
      "type": "component",
      "repeatable": true,
      "component": "common.card"
    },
  }
}
```

**Card component**
```
{
  "collectionName": "components_common_cards",
  "info": {
    "name": "card",
    "icon": "box",
    "description": ""
  },
  "options": {},
  "attributes": {
    "thumbnail": {
      "type": "component", <--- this does not work anymore (since new versions) 
      "repeatable": false,
      "component": "common.image"
    },
    "title": {
      "type": "string"
    },
    "image": { <--- this works
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false
    }
  }
}
```

**Image component**
```
{
  "collectionName": "components_common_images",
  "info": {
    "name": "image",
    "icon": "address-book",
    "description": ""
  },
  "options": {},
  "attributes": {
    "image": {
      "model": "file",
      "via": "related",
      "allowedTypes": ["images", "files", "videos"],
      "plugin": "upload",
      "required": false
    },
  }
}
```

### Describe the bug

After I upgraded to the newest version I detected the bug that when an image was uploaded inside a card component the image relation became lost on save. 

[Screenshot can be found here](https://ibb.co/vJBxm5b)

When I tried to downgrade Strapi again the bug remained. So I am assuming the newest version 3.4.6 / 3.5.0 introduced some database changes.

### Steps to reproduce the behavior

1. Install the latest version
2. Added the three components above.
3. Append an image to a card component inside the card list
4. Press green save button on a page collection type which has a dynamic zone with the card list component 
5. Tadaa! The image does not save properly.

### Expected behavior

I am expecting the image to be saved inside the nested component card as it did in earlier versions.

### Screenshots

s### System

- Node.js version: 12.20.1
- NPM version: 6.14.1
- Strapi version: 3.4.6 / 3.5.0 (previous 3.4.2 where it worked) 
- Database: mongo db hosted on atlas
- Operating system: MacOS Big Sur

### Additional context

The error remained after downgrading again to the version where it worked for. (3.4.2)

**Comment by alexandrebodin** [comment]
Hi @kevinvugts the relation is created correctly but you are using a depth level greater than 2 which isn't something you should do (that's why it is not allowed in the content type builder for example) to avoid performance issues. We recently enforced this to avoid overloading data that's why you are seeing this. I'm going to see if we can fix it while avoid perf issues :)

**Comment by alexandrebodin** [comment]
FYI @cgonzalezsan this might be realted to your issue. Are you using a nesting level greater than 2 for your components ?

**Comment by kevinvugts** [comment]
> Hi @kevinvugts the relation is created correctly but you are using a depth level greater than 2 which isn't something you should do (that's why it is not allowed in the content type builder for example) to avoid performance issues.
> 
> We recently enforced this depth on data loading to avoid over fetching data et avoid infinite loops. That's why you are seeing this issue.
> 
> I'm going to see if we can fix it while avoid perf issues :)

Hi Alexandre,

thank you for your quick reply.

I haven’t experience any performance issues on 3.4.2. It worked perfectly and this is quite an important feature since there are a lot of cases where this has a place.

For example in my Card list which is responsible for showing a list of Card Components. Each Card compent needs a thumbnail which contains properties like an image, a absolute positioned image label, image distrubution settings, alignments etc.

Could you tell me in the mean time how I can go back to the old situation which worked. Downgrading didn’t do the job. Cause right now it’s stopping us from further development. 

Looking forward for your answer.

**Comment by alexandrebodin** [comment]
Hi @kevinvugts I justed push a fix PR. If you can point your npm config to the branch you will have the fix available. 

When reverting to a version prior to 3.5.0 you should be able to fix it. How did you revert when you tested ?

**Comment by kevinvugts** [comment]
> Hi @kevinvugts I justed push a fix PR. If you can point your npm config to the branch you will have the fix available.
> 
> When reverting to a version prior to 3.5.0 you should be able to fix it. How did you revert when you tested ?

I reverted by changing all strapi packages to 3.4.2, removing node modules, removing yarn.lock file, yarn cache clean, and also clean build for Strapi. This didn’t had any effect.

**Comment by gustavpursche** [comment]
Actually, I faced the same issue today. Here a commit, which replaces the component with an actual `UploadFile` to fix the issue for now: https://github.com/seebruecke-org/cms/commit/736c40d9a3df217cd50c50db96d37693d6796d69

Weirdly it still works in this case: https://github.com/seebruecke-org/cms/blob/main/components/shared-blocks/stage-large.json

**Comment by cgonzalezsan** [comment]
> FYI @cgonzalezsan this might be related to your issue. Are you using a nesting level greater than 2 for your components ?

I have the following:
Dynamic zone -> Gallery component -> Image component with 2 properties: image (strapi media) and caption (rich text)

**Comment by Ic3m4n34** [comment]
I'm having the same issue as @kevinvugts

**Comment by kevinvugts** [comment]
@alexandrebodin I was able to revert back to prior version. So for now this is okey, but can you guys include the fix in the next release cycle?

**Comment by alexandrebodin** [comment]
Can some of you test this PR in your projects ? https://github.com/strapi/strapi/pull/9464

**Comment by kevinvugts** [comment]
> Can some of you test this PR in your projects ? #9464

HI Alexandre,

I am so sorry that I didn't get back to this any sooner.
However, is this still something which is not in the newer versions of Strapi?

Or is this issue resolved in the newest version of Strapi?

Best,
Kevin

**Comment by kevinvugts** [comment]
bump @alexandrebodin

**Comment by kevinvugts** [comment]
@soupette 

Can you please ask @alexandrebodin to get back to me about this issue?
Is this something which is solved in the new versions of Strapi?

**Comment by Haukez** [comment]
bump @alexandrebodin would love to hear from that issue too

**Comment by rcabret** [comment]
Any updates on this? This is still very present in 4.0.0 and possibly worse as it doesn't let you save any nested components even 1 level down.

**Comment by aukgit** [comment]
> Actually, I faced the same issue today. Here a commit, which replaces the component with an actual `UploadFile` to fix the issue for now: [seebruecke-org/cms@736c40d](https://github.com/seebruecke-org/cms/commit/736c40d9a3df217cd50c50db96d37693d6796d69)
> 
> Weirdly it still works in this case: https://github.com/seebruecke-org/cms/blob/main/components/shared-blocks/stage-large.json

@alexandrebodin facing the same issue.

How handle strapi in production with modification:

1. Can we modify fields or add fields in production?
2. Will it break other relational data in production?
3. How to handle future modification in production?


Is there any solution or alternatives that we are missing?

CC:
@siamekanto19

Thanks

**Comment by derrickmehaffy** [comment]
> > Actually, I faced the same issue today. Here a commit, which replaces the component with an actual `UploadFile` to fix the issue for now: [seebruecke-org/cms@736c40d](https://github.com/seebruecke-org/cms/commit/736c40d9a3df217cd50c50db96d37693d6796d69)
> > Weirdly it still works in this case: https://github.com/seebruecke-org/cms/blob/main/components/shared-blocks/stage-large.json
> 
> @alexandrebodin facing the same issue.
> 
> How handle strapi in production with modification:
> 
> 1. Can we modify fields or add fields in production?
> 2. Will it break other relational data in production?
> 3. How to handle future modification in production?
> 
> Is there any solution or alternatives that we are missing?
> 
> CC: @siamekanto19
> 
> Thanks

1. No you can't, see this [FAQ](https://docs.strapi.io/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging) And here is a small quote from that:

> At this time and in the future there is no plan to allow model creating or updating while in a production environment, and there is currently no plans to move model settings into the database. There are no known nor recommended workarounds for this.

2. It will break a lot of stuff, which is why we don't recommend it or support it
3. You should be doing everything via source control and deploying changes, not doing it in production.

The only alternate is to follow what we recommend, anything outside of that is not something we can/will help with. We never intended or built Strapi to allow content-type modifications in production, and in most cases we **specifically** design it not to and to lock that ability.

**Comment by msadcenko** [comment]
Any updated on this? We face the same issue in Strap version >= 4

**Comment by derrickmehaffy** [comment]
> Any updated on this? We face the same issue in Strap version >= 4

Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
