### ISSUE TITLE
GraphQL publicationState doesn’t appear to pass down to components?

### ISSUE THREAD

**Issue by gaz-99** [strapi/strapi#9463]
I posted this on the strapi forum and was asked to create a bug report:

I’m not sure if this is expected behaviour or i’m setting up my queries wrong but I have the following collections:

    Static Pages (has a dynamic zone called PageContent)

    Sites (a site has a relation to many offers)

    Offers (an offer belongs to only one site)

I then have a custom component which has two string properties and then a repeatable component of site relations.

all data for all collections is in DRAFT state.

when i use the following query in the graphql playground:
```graphql
query($pageID: String!, $publicationState: PublicationState!) {
  staticPages(publicationState:$publicationState, where: { PageID: $pageID }) {
    Title,
    Heading,
    HeadingImage{
      url,
      alternativeText
    },
    PageContent {
      ... on ComponentStaticComponentsSitesList {
        __typename,
        Heading,
        Description,
        Sites {
          site {
            Name,
            Slug,
            Logo {
              url,
              alternativeText
            },
            Rating,
            offers{
              Title,
              OfferLink
            }
          }
        }
      }
    }
  }
}
```

with these query parameters

```
{
  "publicationState": "PREVIEW",
  "pageID": "Home"
}
```

everything populates except the offers array, it just returns empty, however if i PUBLISH the items in Offers and Sites (Static Pages can be left in DRAFT), everything populates as i would expect.

Is this the normal behaviour? Is there a way to get the offers relation to populate when in DRAFT state?

I feel like the publicationState must not be passing into the sub selections hence why it returns empty.

### System

- Node.js version: 14.15.1
- NPM version:
- Strapi version:  v3.4.4
- Database: MongoDB
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/graphql-publicationstate-doesnt-appear-to-pass-down-to-components/2956/5

**Comment by derrickmehaffy** [comment]
Confirmed on v3.5.0 as well.

**Comment by Irian** [comment]
Any news on this? I noticed this as well, also on v3.6.7.

**Comment by maxime50** [comment]
This issue is still present in v4.

I my case, I wanted to fetch a current logged user and it’s informations, but the Contact field (which i saved as component type) always return null in the response.

**Comment by shetshrikant** [comment]
I've noticed this issue in V4.1.2 as well.

**Comment by kasonde** [comment]
Bumping this up to high as there is currently no work-around for this (for relations to single content-types). Applyting the publication state to relations to many content-types applies the publication state filter to the result set

**Comment by Convly** [comment]
> I feel like the `publicationState` must not be passing into the sub selections hence why it returns empty.

This is indeed what's happening. Every resolver's params are independent. If you want drafts and published offers, add this to the `offers` child resolver.

```graphql
offers(publicationState: $publicationState) {
  Title,
  OfferLink
}
```

As far as I know, this is the intended behavior. One idea that has been proposed by the team was to add some kind of customization to allow the propagation of such filters, but it's still something that would need to be discussed more before implementation.

> Applyting the publication state to relations to many content-types applies the publication state filter to the result set

@kasonde I'm sorry, but I'm not sure I understood this one, would you mind rephrasing/adding an example for this?

**Comment by kasonde** [comment]
Hi @Convly sure. let me reproduce this behavior and share it with you.
