### ISSUE TITLE
Prevent login overrides with SSO feature

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#9466]
### Describe the bug

The new SSO feature of Strapi is great and it has it's pros - however, also cons. And the biggest con is that it's possible for intruder to access another user's account by creating an account on some provider with an e-mail of such admin user. For example, let's say you have two provider: Google and Sign in with Apple. An admin panel user has an Apple ID, but doesn't have a Google account. An intruder wants to access the system and knows an email of the user. He creates a Google account with an e-mail address of a user. Then he logs in to the admin panel without any problems under that user's account and gains access to the data in Strapi.

### Steps to reproduce the behavior

For example, 
1. Add an admin panel user with an email and password.
2. Add two SSO providers, say, Google and Apple. There should be an Apple ID for our user's email and no Google account.
3. Try to log in with Google account. You should be able to log in - that's the expected behaviour.
4. Create a Google account and try to log in with it. Strapi will check for Google account's email address and issue JWT token. That's not expected at all. Now an intruder has an access to the account and this might be even Super Admin.

### Expected behavior

It should be possible to
a) Register with an SSO-access-based account and authenticate that account only with this respective SSO provider
b) Link SSO providers to admin panel account through the Profile tab

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.18.3
- NPM version:
- Strapi version: 3.5.0
- Database: PostgreSQL
- Operating system: Ubuntu

**Comment by LucaNerlich** [comment]
Could you possible provide steps written a bit clearer? Ive got trouble following your steps to reproduce, since I cant quite understand what you mean.

If this can be reproduced, this is a major issue and huge oversight and should be looked into immediately.

**Comment by Convly** [comment]
Hello,

Thanks for your feedback.

Indeed, it is not possible for the moment to associate a specific provider to an account and restrict the use of that provider only with that account. It can lead to the situation you describe.

This is the first iteration of the SSO feature and we plan on adding this feature on the next one. We decided to not include it in the scope for the moment to keep SSO simple with few configurations.

While the case you describe can happen, there are several ways to avoid it.
- By disabling the auto-register feature, which will require a SuperAdmin to create an account first before being able to login with SSO
- By using only one provider, it is thus impossible to use other app credentials to log in
- Finally, if neither of the solutions above is an option, you can create custom conditions and flows programmatically.
  
Concerning the third option, here are some examples:

1. Using a simple Regex check

    The first (and easiest) way to counter this would be to declare a regex matching appleID emails and prevent those to connect using the Google provider. To implement this, you can hook yourself directly in the verify function of your provider (here: Google) and replace it with something like the following:

   ```javascript
    const verify = (request, accessToken, refreshToken, profile, done) => {
      const appleIDMatcher = new RegExp(/* Some regex that will match any appleID */);
    
      if (appleIDMatcher.test(profile.email)) {
        done(new Error('Forbidden'));
      }
    
      done(null, {
        email: profile.email,
        firstname: profile.given_name,
        lastname: profile.family_name,
      });
    };
    ```

2. Using a local record

    The second option is a bit trickier but will probably fit better in your situation. It consists of adding a new collection type that will record with which provider admins registered themselves.
  
      You can then prevent a connection if the email/provider association doesn't match the one recorded in your DB. Here's an example of a simple implementation:
     
      First, we define the admin-providers model that will keep track of the email/provider couples.

      _Note: Here I've used an enum to store the available providers, but you can use any string-related type you want._
      
      `admin-providers.settings.json`
      ```json
      {
        "kind": "collectionType",
        "collectionName": "admin_providers",
        "info": {
          "name": "admin-providers",
          "description": ""
        },
        "options": {
          "increments": true,
          "timestamps": false,
          "draftAndPublish": false
        },
        "attributes": {
          "provider": {
            "type": "enumeration",
            "enum": [
              "google",
              "github",
              "apple",
              "local"
            ],
            "default": "local",
            "required": true
          },
          "email": {
            "type": "email",
            "unique": true,
            "required": true
          }
        }
      }
      ```
     
      Then we add a new record whenever a new user creates an account using SSO:
     
      `/config/server.js`
      ```javascript
      module.exports = () => ({
        // ...
        admin: {
          // ...
          auth: {
            // ...
            events: {
              // ...
              async onSSOAutoRegistration(e) {
                const { user, provider } = e;
      
                await strapi.query('application::admin-providers.admin-providers').create({
                  provider,
                  email: user.email,
                });
              },
            },
          },
        },
      });
      ```
     
      Finally, we add a guard to the verify function of the Google provider to prevent connections with a Google account when the Strapi admin has been registered using another provider:

      `/config/server.js`
      ```javascript
      module.exports = () => ({
        // ...
        admin: {
          // ...
          auth: {
            // ...
            events: {
              // ...
              onSSOAutoRegistration(e) {/*...*/}, // Same as step above
            },
      
            providers: [
              // other providers...
              {
                uid: 'google',
                displayName: 'Google',
                icon: 'https://cdn2.iconfinder.com/data/icons/social-icons-33/128/Google-512.png',
                createStrategy: strapi =>
                  new GoogleStrategy(
                    {/*...*/},
                    (_, __, ___, profile, done) => {
                      strapi
                        .query('application::admin-providers.admin-providers')
                        .findOne({ email: profile.email })
                        .then(res => {
                          if (res && res.provider !== 'google') {
                            done(new Error('Forbidden'));
                            return;
                          }
      
                          done(null, {
                            email: profile.email,
                            firstname: profile.given_name,
                            lastname: profile.family_name,
                          });
                        })
                        .catch(done);
                    }
                  ),
              },
            ],
          },
        },
      });
      ```
     
      _Note: The only limitation with this method would be that admins who registered without the SSO auto-registration would not be listed in the CT's records._
  
(pinging  @sam-pires)

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/security/p/prevent-login-overrides-with-sso-feature

Thanks!
