### ISSUE TITLE
Strapi quickstart not starting up

### ISSUE THREAD

**Issue by jr00n** [strapi/strapi#9469]
## Bug report

Just followed the tutorial on https://strapi.io/documentation/developer-docs/latest/getting-started/quick-start.html

### Describe the bug

The Strapi server when started in development mode by npm run develop or strapi develop would not start. The process stops without an error or any other message. npm run start, strapi start or strapi build works without a problem.

`> my-project@0.1.0 build /Users/jr00n/src/strapi/my-project
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (68%) 2414/2472 modules 58 active
 ...34m› .cache/plugins/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/DraggedItem/utils/select.js

Error: Module not found: Error: Can't resolve '/Users/jr00n/src/containers/App/utils/customRoutes' in '/Users/jr00n/src/strapi/my-project/.cache/admin/src/containers/App/utils'
    at /Users/jr00n/src/strapi/my-project/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compiler.js:265:20)
    at /Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/jr00n/src/strapi/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2830:7
    at /Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2830:7
    at done (/Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2863:11)
    at /Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2818:7
    at /Users/jr00n/src/strapi/my-project/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2830:7
    at /Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2830:7
    at done (/Users/jr00n/src/strapi/my-project/node_modules/neo-async/async.js:2863:11)`

### Steps to reproduce the behavior

Setup new project via npx create-strapi-app my-project --quickstart
Wait until installation is completed
The included strapi start in the installation process is not working
Try to start the server manually by changing to the project directory and executing npm run develop

### Expected behavior

Strapi server starts fine in development mode and browser opens up.

### System

- Node.js version: v14.15.5 (with v12.20.2 same results)
- NPM version: 6.14.11
- Strapi version: 3.5.0
- Database: sqlite3 5.0.0
- Operating system: OSX 11.2.1

### Additional context

Thank you very much for your support!! I really would like to test Strapi

**Comment by nao360** [comment]
@jr00n I experienced the very same, however with a custom (non-quickstart) project creation profile. I followed this work-around posted [here](https://github.com/strapi/strapi/issues/9442#issuecomment-782657871), and got the admin UI to build successfully. Turns out v3.5.0 has a problem with directory paths that contain `src`.

**Comment by jr00n** [comment]
thanks @nao360 ... how bizar...that is the problem..al my code is running in ~/src/.... and that is not working with 3.5.0 webpack's config. I tested it to run in another directory ~/develop/... and now it works fine. Thanks a lot!! A bizar bug

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/9442
