### ISSUE TITLE
Is there a way to set up one-to-one-morph and one-to-many-morph relations?

### ISSUE THREAD

**Issue by shtelzerartem** [strapi/strapi#9478]
I'm developing plugin for strapi and I need to use one-to-many-morph relation. 
I wanted to ask, maybe there is a way to specify not only many-to-many polymorphic relation, but also one-to-one and one-to-many in model settings? Haven't found anything in docs, that's why creating this issue.

**Comment by shtelzerartem** [comment]
I have found this issue #5348 and this PR request #9396
And it seems it would fix it, right?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

---

Polymorphic relations are a bit of a no-go right now but for other relations: https://strapi.io/documentation/developer-docs/latest/concepts/models.html#relations
