### ISSUE TITLE
Strapi - Build error in browser console after installing

### ISSUE THREAD

**Issue by ajohnson10209** [strapi/strapi#9484]
### Describe the bug

After strapi is installed and I run npm run develop, I see an error in the browser console and the /admin page doesn't load. My node verison is 14.15.4 and my npm version is 6.14.10

### Steps to reproduce the behavior

1. Run yarn create strapi-app my-project --quickstart
2. Run npm run develop
3. Go to the browser console to see error

### Expected behavior

The login screen is supposed to appear

### Screenshots

(1) Blank screen + my command prompt
![image](https://user-images.githubusercontent.com/41972632/108791208-88526e80-754c-11eb-9fc1-04b245a2e14f.png)

(2) Web console displaying the error
![image](https://user-images.githubusercontent.com/41972632/108791285-ad46e180-754c-11eb-8023-691c7b7ba81b.png)

### System

- Node.js version: 14.15.4
- NPM version:  6.14.10
- Strapi version: 3.5.0
- Database: sqllite
- Operating system: Windows

### Additional context

Thanks for your help!

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9482
