### ISSUE TITLE
Twitter login problem

### ISSUE THREAD

**Issue by erhankaradeniz** [strapi/strapi#9492]
### Describe the bug

When you login with twitter it does not seem to work.
I've followed this guide: [https://strapi.io/blog/user-authentication-in-next-js-with-strapi](https://strapi.io/blog/user-authentication-in-next-js-with-strapi)

This guide works for Google, I've tested it and it's working fine. However when using Twitter auth, it does not seem to work. 
The guide states that the jwt option has to be set to true, when I remove the jwt option the login seems to work, but no user is created on the strapi end.

### Steps to reproduce the behavior

1. Go to login with twitter (enabled in next-auth)
2. Click on Login with twitter
4. See error that I have pasted below in the code snippets part.

### Expected behavior

I would expect to be logged in an a user is created in the strapi admin.

### Code snippets

Error from the strapi console
```
[2021-02-23T08:05:04.662Z] debug GET /auth/twitter/callback?access_token={TOKEN IS DISPLAYED HERE} (271 ms) 400
```
Where next-auth gives me this error in console:
```
https://next-auth.js.org/errors#oauth_callback_handler_error TypeError: Cannot read property 'id' of undefined
```

this is the login with next-auth:

```
import NextAuth from "next-auth"
import Providers from "next-auth/providers"

const options = {
  providers: [
    Providers.Twitter({
      clientId: process.env.TWITTER_CLIENT_ID,
      clientSecret: process.env.TWITTER_CLIENT_SECRET,
    }),
  ],
  database: process.env.NEXT_PUBLIC_DATABASE_URL,
  session: {
    jwt: true,
  },
  debug: true,
  callbacks: {
    async session(session, user) {
      session.jwt = user.jwt
      session.id = user.id
      return session
    },
    async jwt(token, _, account) {
      if (account) {
        const url = new URL(
          `${process.env.NEXT_PUBLIC_API_URL}/auth/${account.provider}/callback`
        )
        url.searchParams.set("access_token", account.accessToken)
        const response = await fetch(url.toString())
        const data = await response.json()
        token.jwt = data.jwt
        token.id = data.user.id
      }
      return token
    },
  },
}

const Auth = (req, res) => NextAuth(req, res, options)

export default Auth
```

The value of `NEXT_PUBLIC_API_URL` is to my strapi backend with an ngrok url. since twitter does not allow localhost.
The `response` part seems to be broken because of the data which is returned is not actual data but an error.

### System

- Node.js version: 12
- Strapi version: 3.5.0
- Database: postgres
- Operating system: OSx

**Comment by erhankaradeniz** [comment]
Okay I fixed the issue, I had a look in `Providers.js` in the `strapi-plugin-users-permissions`
Here is the fix for others searching for a solution to get this working with next-auth.

Strapi expects for the Twitter provider also an `access_secret` query parameter. use the `refreshToken` you receive from next-auth as the `access_secret`.

Below is the part which does the callback to strapi:

```
callbacks: {
    async session(session, user) {
      session.jwt = user.jwt
      session.id = user.id
      return session
    },
    async jwt(token, _, account) {
      if (account) {
        const url = new URL(
          `${process.env.NEXT_PUBLIC_API_URL}/auth/${account.provider}/callback`
        )
        url.searchParams.set("access_token", account.accessToken)
        url.searchParams.set("access_secret", account.refreshToken) // Notice I'm sending the refreshToken as access_token
        const response = await fetch(url.toString())
        const data = await response.json()
        token.jwt = data.jwt
        token.id = data.user.id
      }
      return token
    },
  },
```

**Comment by derrickmehaffy** [comment]
Going to close this one out since you found a fix :)

**Comment by eikaramba** [comment]
for anyone else coming across this:

according to https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens you get the oauth_token_secret parameter in the return url

so when you try to authenticate the user via the access_token, in the case of twitter you also need to take this query parameter and pass it along as well.

e.g. (using svelte)
```js
let url = `${VITE_APIURL}/auth/${$page.params.provider}/callback?access_token=${$page.query.get('access_token')}`;
if($page.params.provider=="twitter"){
	url = `${VITE_APIURL}/auth/twitter/callback?access_token=${$page.query.get('access_token')}&access_secret=${$page.query.get('raw[oauth_token_secret]')}`;
}
```


the docs really need to also mention this
