### ISSUE TITLE
Plugin registry issue `strapi-plugins-'. Custom plugins requests 404 Not Found

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#9499]
## Problem

When developing a plugin locally (overriding `/plugins`) the name of the folder is used as the `pluginId` that's stored in `strapi.services`.

This causes a potentially very confusing issue where if the plugin is cloned into the `/plugins` folder with the name of the package (for example `strapi-plugin-migrate`) and is not stripped off the part `strapi-plugin-` the requests to plugin routes will fail as `404 Not Found`.

## Feature request

To add regex or some helper that checks the name of the `/plugins` folders before registering them AND IF the name contains `strapi-plugin-` - strip it, if not register the plugin.

**Comment by derrickmehaffy** [comment]
Fixed in v4 as we have the resolver config option now
