### ISSUE TITLE
How can I pass custom params to the upload-s3 plugin

### ISSUE THREAD

**Issue by mahcr** [strapi/strapi#9503]
## Bug report
There is no documentation of how to pass custom params to the config of the s3, I've tried passing the `customParam` property in different places in the plugins.js config but doesn't seem to work

```
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('AWS_ACCESS_KEY_ID', 'xxx'),
      secretAccessKey: env('AWS_ACCESS_SECRET', 'xxx'),
      region: env('AWS_REGION', 'xx'),
      params: {
        Bucket: env('AWS_BUCKET', 'xxx'),
      }
    },
    customParams: {
      ACL: 'private'
    }
  },
});

```

### Steps to reproduce the behavior

1.  Install the plugin `yarn install strapi-provider-upload-aws-s3`
2. Create the plugin.js file with the required config

### Expected behavior

Passing the `customParam` property through the config should  be injected in the S3 config

### Code snippets

Source code of the plugin
```
S3.upload(
            {
              Key: `${path}${file.hash}${file.ext}`,
              Body: Buffer.from(file.buffer, 'binary'),
              ContentType: file.mime,
              ...customParams,
            },
......
```

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
