### ISSUE TITLE
Wrong strapi.env value in development

### ISSUE THREAD

**Issue by zoltantothseon** [strapi/strapi#9510]
### Describe the bug

The value of strapi.env is 'production' when running in development mode. I wan't to differentiate some behaviour between development mode and production which would be straightforward using the env.

### Steps to reproduce the behavior

1. start strapi in dev mode: npm run develop
2. log strapi global value: console.log(strapi).

### Expected behavior

The value of strapi.env should be development or such when running in development mode.

### System

- Node.js version: 14.15.4
- NPM version: 6.14.6
- Strapi version: 3.5.1

**Comment by soupette** [comment]
Hello, are you referring to the environment in the admin panel or in the back-end?

**Comment by zoltantothseon** [comment]
Yeah sorry, it's the admin panel.

**Comment by soupette** [comment]
I understand then.

So when you start you application and there's no generated build, the built environnement is the same one as the back-end one, meaning development. If you are in production you need to generate a production build in this case the `env` of the admin panel will be `production`.

If you need the backend environment you can use the `useGlobalContext` hook:


```
import { useGlobalContext } from 'strapi-helper-plugin';

const MyCompo = () => {
  const { currentEnvironment } = useGlobalContext();

  console.log({ currentEnvironment });
}
```

**Comment by zoltantothseon** [comment]
The value of strapi.env is 'production' for me bot if i start it via `npm run build && npm run develop` and if just run `npm run develop` without build (rm -rf build too). I will try your suggestion however it's weird for me that the value is production... i don't know if it's intended.

**Comment by soupette** [comment]
In the admin panel we have only 2 modes `production` or `development`. If you need the back-end environment you need to use the provide `useGlobalContext` hook.

I am closing this issue, feel free to reopen it.
