### ISSUE TITLE
Time field doesn't save the timezone information

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#9513]
### Describe the bug

Right now, if you have a `Time` field, in the database it saves a string like this: `18:00:00.000`.
But with just this, we don't have information about the timezone.

It will be the same time if I save it at 6pm in Spain as if someone saves it at 6pm in Argentina. 😕 

Which can make the component a bit useless, due to daylight savings time, etc.

### Expected behavior

Shouldn't we keep the time in UTC? Like `18:00:00.000Z` (note the `Z` at the end)

Like when use the `Datetime` field.

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: v3.5.0
- Database: MongoDB
- Operating system: macOS

**Comment by abdonrd** [comment]
If you want a real use case, we want to migrate from a `Datetime` field to a `Date` & `Time` fields, because the time is optional.

**Comment by abdonrd** [comment]
I think the related logic is this:

https://github.com/strapi/strapi/blob/1e9e02b4de065e48e8e43d7f78aa91446eaf0494/packages/strapi-utils/lib/parse-type.js#L6-L26

**Comment by abdonrd** [comment]
Thinking about it, I think the best scenario would be to treat it in the same way as the dates. That is:

The API should always receive the time in UTC. And save it that way in the database.
The admin panel must convert the local time that the user introduces to UTC to send to the API.

**Comment by alexandrebodin** [comment]
Hi, using UTC for a time will be a breaking change. right now those are simple string values et would need to be parse again by the user. 

We could had this as an option or different time & time with timezone fields. this needs a bit more thinking. i'll poing @sam-pires  to put this topics in the user research backlog

**Comment by abdonrd** [comment]
Got it! Should be nice, to allow the API consumers makes something like to get a full datetime:

```javascript
// If just date
const date = new Date(date);

// If date & time
const datetime = new Date(`${date}T${time}`);
```

Since they don't have any information about the timezone it was saved on...
Then the date could show wrong depending on location.

**Comment by abdonrd** [comment]
Thinking more about it...
Makes sense to have a new date type field to be "date with optional time"?

In the admin:
- If the user just set the date, we can save as the current date type (`2021-02-25`).
- If the user set date & time, we can save as the current datetime type (`2021-02-25T10:38:17.746Z`);

**Comment by abdonrd** [comment]
For now I think we are going to use this to allow optional time with timezone support:

<img width="761" alt="Screenshot 2021-02-25 at 13 10 17" src="https://user-images.githubusercontent.com/1007051/109151830-f7a5a980-776a-11eb-9205-40e0d30c9cdf.png">

**Comment by jseashell** [comment]
@abdonrd you could create a custom Component with an Enumeration field for timezone, like this
![image](https://user-images.githubusercontent.com/35895180/168098262-a2241c8a-b0f4-4985-af38-e356229da3e5.png)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/add-time-andor-timedate-field-that-saves-timezone-data
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
