### ISSUE TITLE
Build process on server failed: internal/process/per_thread.js

### ISSUE THREAD

**Issue by milanffm** [strapi/strapi#9519]
## Bug report

when I build strapi on uberspace.de I get following error:

### Code snippets

```
internal/process/per_thread.js:151
       _memoryUsage(memValues);^

      `Error: EFAULT: bad address in system call argument, uv_resident_set_memory
          at process.memoryUsage (internal/process/per_thread.js:151:5)
          at ConsoleReporter.checkPeakMemory (/usr/share/yarn/lib/cli.js:33565:40)
          at Timeout._onTimeout (/usr/share/yarn/lib/cli.js:33558:13)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7) {
        errno: -14,
        code: 'EFAULT',
        syscall: 'uv_resident_set_memory'
}
```
### Description

I have similar problem with nuxt on uberspace.de I fixed it with this:

https://webpack.js.org/configuration/optimization/#optimizationminimizer

I have to change the settings from the terser plugin, that it doesn't use many CPUs.

```
optimization: {
	minimizer: [
		new TerserPlugin({
			parallel: false,
		}),
	],
}
```

**It is possible the change the CPUs from NODE for strapi using in the build process?**

### System

- Node.js version: v12.19.0.
- NPM version: 6.14.8
- Strapi version: 3.4.3
- Database: mongodB
- Operating system: Linux (hosted on https://uberspace.de)

**Comment by soupette** [comment]
Hello, you can try to change the webpack config of your application you can check out our [documentation](https://strapi.io/documentation/developer-docs/latest/admin-panel/custom-webpack-config.html)

**Comment by milanffm** [comment]
Hi, I found the Problem. I think it has something todo with RAM on ubersace:
https://manual.uberspace.de/basics-resources/
they have only 1.5 GB Ram
