### ISSUE TITLE
Can't download/install plugin

### ISSUE THREAD

**Issue by breinkober** [strapi/strapi#952]
**Can't install "Roles and Permissions" Plugin**
- **9.10.0**:
- **5.8.0**:
- **Strapi version: 3.0.0-alpha.11.3**
- **MongoDB**
- **Linux Mint Latest**

**What is the current behavior?**
I want to install the Roles and Permissions Plugin. When I click on "Download" nothing happens. Just a green ✔ pops up for a 1/10 second.

**Steps to reproduce the problem**
Go to Plugins and click download.

[X] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @breinkober, this plugin is installed by default. You delete it and try to install it again ?

**Comment by breinkober** [comment]
I was wondering because it is not installed by default (for me atleast). The other plugins have the label "already installed" but the permissions plugin is not.


Oh wait. I remember an error while the installation...
[2018-04-17T08:16:24.782Z] error An error occurred during users-permissions plugin installation.
[2018-04-17T08:16:24.783Z] error Command failed: node /usr/local/lib/node_modules/strapi/bin/strapi.js install users-permissions

**Comment by lauriejim** [comment]
Ho it's strange. Can you just test to create new project and tell me if the plugin installation fail again.

**Comment by breinkober** [comment]
I just made a new test project and everything worked fine.

How can i delete a stripe project?

**Comment by lauriejim** [comment]
Don't know where this issue come from. And we haven't steps to reproduce it..
Maybe we can close this issue now.

**Comment by hbakhtiyor** [comment]
@lauriejim 
i've the same issue while creating new project with fresh strapi installed,

```
[2018-05-14T13:11:45.008Z] error An error occurred during users-permissions plugin installation.
[2018-05-14T13:11:45.038Z] error Command failed: node /usr/lib/node_modules/strapi/bin/strapi.js install users-permissions
```

**Comment by Defozo** [comment]
Can we reopen the issue? I'm experiencing the same problem.

**Comment by lauriejim** [comment]
@Defozo Can you give us more details please.

**Comment by maciekkus** [comment]
@lauriejim 
Hi, recently I got that error also
[2018-11-14T15:34:41.550Z] debug Moving the `node_modules/strapi-plugin-user-permissions` folder to the `./plugins` folder.
[2018-11-14T15:34:41.626Z] error An error occurred during plugin installation.

I've checked the content of plugins dir, and this plugin exists, but not all files were copied.
there is no "services" directory.
the same issue is with upload plugin

**Comment by lauriejim** [comment]
Hello @maciekkus can you open a new issue please.

Title: "Catch plugin install error"

We have to catch installation error and delete the generated plugin folder if an error happen.

**Comment by maciekkus** [comment]
@lauriejim 
Hi, created an issue, but then found out this one: https://github.com/strapi/strapi/issues/1866
which is about the same thing.

**Comment by franquil** [comment]
I encountered similar issues. I can not install plugins used by strapi when using strapi with docker.

> An error occurred during plugin installation.
> backend_1     | Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-settings-manager

<img width="491" alt="2019-05-17 17_49_0" src="https://user-images.githubusercontent.com/3143067/57919800-29b68600-78cc-11e9-9f52-09796acd47e3.png">

**Comment by seba-t** [comment]
> I encountered similar issues. I can not install plugins used by strapi when using strapi with docker.
> 
> > An error occurred during plugin installation.
> > backend_1     | Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-settings-manager
> 
> <img alt="2019-05-17 17_49_0" width="491" src="https://user-images.githubusercontent.com/3143067/57919800-29b68600-78cc-11e9-9f52-09796acd47e3.png">

This same with NPM!

**Comment by Preyash** [comment]
![strapi](https://user-images.githubusercontent.com/26684774/65132947-713a5380-da1f-11e9-91bc-7924297ef2c1.png)
Can you solve my issue?

**Comment by lauriejim** [comment]
I suggest you to move on the `beta.16.x` version of Strapi.
Follow [these commands 📚](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project)

**Comment by Nauman440** [comment]
I faced the same issue in start then I switched to strapi beta version and everything works fine for me.
You can check this article for further reference 
https://www.mstweaks.com/how-to-install-and-create-a-project-in-strapi/
Thanks
