### ISSUE TITLE
Author One can link the relation with another Author item. In fact Author One is only supposed to link with its own created item.

### ISSUE THREAD

**Issue by Ben888GitHub** [strapi/strapi#9520]
## Bug report
Hello everyone 🙂, hope you guys are well. I’m looking forward to hiding the Second Exhibitors on the list because it does not belong to Author One. 

### Describe the bug
Since I only have 1 item in my Exhibitors Collection Type in this Author One. The Second Exhibitors on the list there is belonged to Author Two, and it can of course be viewed by the Admin. And I don’t give any permission to Author One.
Is there any possible solution for me to do it? Thank you very much in advance… 

### Screenshots
<img width="1548" alt="Screen Shot 2021-02-25 at 12 38 13 AM" src="https://user-images.githubusercontent.com/50259107/109140173-ea9ab180-778e-11eb-8b40-b51cbb916c81.png">
<img width="1548" alt="Screen Shot 2021-02-25 at 12 42 34 AM" src="https://user-images.githubusercontent.com/50259107/109140231-f5eddd00-778e-11eb-99c8-25d0ce489f9c.png">

### System

- Node.js version: v12.20.0
- NPM version: 6.14.5
- Strapi version: 3.5.1
- Database: MySQL
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7696
