### ISSUE TITLE
Can't build content types when custom node env has been set

### ISSUE THREAD

**Issue by zoltantothseon** [strapi/strapi#9524]
### Describe the bug

When a custom node env is provided then content types can't be modified or new ones can't be built in development mode. It behaves like we run strapi in production mode.

### Steps to reproduce the behavior

1. Run strapi with custom node env e.g.: NODE_ENV=local npm run develop
2. Go to content type builder
3. Check that no create new or add new field buttons are present.

### Expected behavior

The content type building should be available in case we run strapi in development mode even if we set custom node envs.
I use custom env to use different configurations. Configs can be different on production, staging or on local and such so this should not affect content type building.

### System

- Node.js version: 14.15.4
- NPM version: 6.14.6
- Strapi version: 3.5.1

### Additional context

We run strapi in docker behind nginx proxy. Added s3 provider to upload and only want to use local provider in local environment thus i set custom node env in local.

**Comment by soupette** [comment]
I guess we could change the [following statement](https://github.com/strapi/strapi/blob/ebcfa07c338f3d1ac7fe29162fd9ab8edb4fba39/packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js#L62) to only check if the autoreload feature is enabled. This way we could use the content type builder in different environments.

cc/ @alexandrebodin

**Comment by alexandrebodin** [comment]
Sounds like we can do that yes @soupette
