### ISSUE TITLE
Inefficent SQL

### ISSUE THREAD

**Issue by jonmol** [strapi/strapi#9531]
### Describe the bug

In `packages/strapi-connector-bookshelf/lib/buildQuery.js` buildQuery have the two following if statements I can't wrap my head around:
```
  if (_.has(filters, 'sort')) {
    const clauses = filters.sort.map(buildSortClauseFromTree(joinsTree)).filter(c => !isEmpty(c));
    const orderBy = clauses.map(({ order, alias }) => ({ order, column: alias }));
    const orderColumns = clauses.map(({ alias, column }) => ({ [alias]: column }));
    const columns = [`${joinsTree.alias}.*`, ...orderColumns];

    qb.distinct()
      .column(columns)
      .orderBy(orderBy);
  }
```

```
  if (_.has(filters, 'where') && Array.isArray(filters.where) && filters.where.length > 0) {
    qb.distinct();
  }

```
That results in every query adding a WHERE or SORT BY via buildQuery a `distinct table_name.*` is being added. I fail to understand why you'd want a distinct * in the first place, but it especially gets silly when there's a limit 1 in the query or the primary key is being used as a filter.

### Steps to reproduce the behavior

Search for anything from the admin GUI.

### Expected behavior
I would expect it to not add distinct unless being asked for. It's very expensive and it's impossible to make it more effective with an index since it would have to be an index covering the whole table.

I noticed that the distinct for when sorting was added pretty recently by @petersg83 while the second was added by @alexandrebodin in 2019 so I'm reluctant to make a PR where I just remove them.

It's also worth noting that every table have a primary key, so distinct * will return all rows anyway?

- Strapi version: 3.5.1

**Comment by alexandrebodin** [comment]
Hi, distinct are used to allow for deep filtering & deep sorting. 

As they require joins we need to add the distinct (limit or not) We could optimize this when the queries don't contain deep filters

**Comment by jonmol** [comment]
Hi,

Ah ok, then I get it. 

Regarding those queries deep filtering/sorting, what's triggering them? I think the deep filtering you're talking about is in the admin GUI and you select a related type to filter on? That is type a "has many" type b, and you filter on type b contains?

That generates this query (bonus question: How do I control which field in the relation it's filtering on, ie say I'd want tableB.name to be the filter?):
```
select distinct "tableA".*, "tableA"."internalName" as "_strapi_tmp_tableA_internalName" 
from "tableA" left join "strapi"."public"."tableB" as "tableB_1" on "tableB_1"."tableA_id" = "tableA"."id" 
where "tableB_1"."uploadedByText" > '1' order by "_strapi_tmp_tableA_internalName" asc limit 10
```

If it instead went for a subquery the distinct wouldn't be needed:
```
explain select a.*, a."internalName" as "_strapi_tmp_tableA_internalName"
from tableA a
where exists (select 1 from "tableB" b where b.exam = a.id and b."uploadedByText" > '1')  order by "_strapi_tmp_tableA_internalName" asc limit 10;
```

The first query will pretty quickly need to use disk to sort the result (of course depending on the amount of RAM you have available and the amount of data in the tables), and it can't be much quicker by adding an index due to the distinct *. The second query doesn't even need to go through all tableB rows, it can stop as soon as there's one match which is all that is needed.

I think that's where the optimisation would make most sense, because then distinct wouldn't really be needed at all. I'm mainly using the admin GUI so I realise I may very well be missing other parts where it's being used.

**Comment by derrickmehaffy** [comment]
Deep filtering is doing something like:

> localhost:1337/articles?category.name=someName

This would be a relation between articles and categories and you are filtering articles based on a name field on the category model.

**Comment by jonmol** [comment]
@derrickmehaffy ok, so the same as when searching via the admin gui. IE this query is generated:
```
select distinct "articles".* from "articles" left join
    "strapi"."public"."categories" as "categories_1" on "categories_1"."id" = "articles"."category" where
    "categories_1"."name" = ? and ("articles"."published_at" is not null) limit 100
```
That could be changed to use exists:
```
select articles.* from articles where articles.published_at is not null and exists
  (select 1 from "strapi"."public"."categories" as "categories_1" where
     "categories_1"."id" = "articles"."category" and "categories_1"."name" = ?) limit 100
```
That would improve the speed of those queries a lot, and it'd also be possible to use indices when there's a need

**Comment by derrickmehaffy** [comment]
Closing as this was fixed in: https://github.com/strapi/strapi/pull/9538
