### ISSUE TITLE
 Error: write ECONNRESET       at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)

### ISSUE THREAD

**Issue by angeltonio** [strapi/strapi#9534]
I make a app to connect strapi backend to reproduce videos on flutter by url, for that i using chewie pub, the video execute well, but when I'ts have momento playing strapi logs see that error, and the video stop...

### System

- Node.js version: v14.15.4
- NPM version :6.14.10
- Strapi version:  v3.5.1
- Database: MySQL
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

Please completely fill out the required template providing reproduction steps. Note that Github issues are only related to bugs within the Strapi code-base, if you are having issues with an external library or project connecting to your Strapi project then please use our community forums: https://forum.strapi.io

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
