### ISSUE TITLE
_or clause in GraphQL getting treated as and

### ISSUE THREAD

**Issue by ssmith-14Four** [strapi/strapi#9536]
### Describe the bug

When I try to query a collection using a where with an _or on two relationships it is treating it as an and query. This is true of both graphql and the rest endpoints.

When I run the example queries with only one of the filters I will get back entries with one or the other entries that have that relationship. But when I do both no entries are returned.

### Steps to reproduce the behavior

1. Create a collection with 2 relationships.
2. Create an 2 entries with each having 1 of the relationships filled out for each.
3. Run an or query on it.

### Expected behavior

It should return all entries that have the content_category slug of "industry-insider" and gme_resources slug of "personal-support".

#### GraphQL

```graphql
query {
  journals(
    where: {
      _or: [
        { content_category: { slug: "industry-insider" } }
        { gme_resource:{ slug:"personal-support"}}
      ]
    }
  ) {
    id
  }
}
```

#### REST
http://cms-psdrecruit.local.14four.com/journals?_where[_or][0][content_category.slug]=industry-insider&_where[_or][0][gme_resource.slug]=personal-support

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.5.1
- Database: MariaDB 10.5.9
- Operating system: Docker

**Comment by lautr** [comment]
having the same issue :/

**Comment by derrickmehaffy** [comment]
fixed in v4, marking as closed
