### ISSUE TITLE
strapi.router.stack generate bad regex for GET method

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#9537]
### Describe the bug

in `strapi.router.stack` generate bad regexp that not match url with query

example:

for `/articles` and GET method generate `/^\/articles(?:\/(?=$))?$/i` regexp that dosn't match `/articles?speciality=80&meta=80` url (ctx.request.url)

### System

- Node.js version:v14
- NPM version:6
- Strapi version: 3.5.1
- Database:mysql
- Operating system:ubuntu

**Comment by marefati110** [comment]
regex can be `/^\/articles\/?(\/?\?.*?)?$/i`

**Comment by derrickmehaffy** [comment]
@marefati110 can you dive a bit deeper? the `strapi.router` comes directly from `koa-router` we don't modify this logic:

https://github.com/strapi/strapi/blob/8661d31ba073c77c51d21aa799036ebab08cd006/packages/strapi/lib/Strapi.js#L7
https://github.com/strapi/strapi/blob/8661d31ba073c77c51d21aa799036ebab08cd006/packages/strapi/lib/Strapi.js#L42

**Comment by derrickmehaffy** [comment]
As no additional information has been provided and we do not modify the logic of the koa-router package. I'm going to mark this one as closed.

If you can provide additional information to help narrow down the issue we can reopen this at a later date.
