### ISSUE TITLE
Guest Permission

### ISSUE THREAD

**Issue by ShankyRana** [strapi/strapi#954]
**Informations**
- **Node.js version**: 9.11.1 
- **npm version**: 5.6.0
- **Strapi version**: strapi@3.0.0-alpha.11.3
- **Database**: MongoDB
- **Operating system**:  MacOS High Sierra v10.13.4

How can we provide guest permission to a route manually? 
Not from the Strapi dashboard.
As API is not visible on Production environment but on Local environment in Roles and Permissions.
Simliar to the issue: https://github.com/strapi/strapi/issues/779
Need a way around.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
You will have to create custom routes on your project.
And check how works loops to manage roles (https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L269) that will help you to create our own role management routes.

**Comment by ShankyRana** [comment]
Thanks.
