### ISSUE TITLE
an error occured when create collection type named manga

### ISSUE THREAD

**Issue by szerntt** [strapi/strapi#9540]
### Describe the bug

When tried create new collection type named manga i get an error 'an error occured'...
### Steps to reproduce the behavior

1. I tried add collection named manga
2. when try saved get this error
3. Then i tried create a new collection in different name i don't get an error

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.5
- NPM version: 6.14.11
- Strapi version: v3.5.1
- Database: mongodb atlas
- Operating system: windows 10

### Additional context

I get error only when i make name 'manga'

**Comment by soupette** [comment]
Hello, thank you for opening this issue.

Manga, is a reserved name as it cannot be pluralised, until we find a proper solution for enabling model names such as `manga` I suggest you to rename your model to something like `manga book` or `manga comic`

**Comment by soupette** [comment]
@derrickmehaffy I let you decide if whether or not we should close this issue and add `manga` to the list of reserved names.

**Comment by felixhagspiel** [comment]
please add "references" as well to the list of reserved names for collections (gives issues on postgres databases)

**Comment by szerntt** [comment]
Thanks for answer. Well then i will make different name

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/1198

@soupette I'll probably create a tracking issue at some point.
