### ISSUE TITLE
Custom field shows NULL when object

### ISSUE THREAD

**Issue by MotaZor94** [strapi/strapi#9547]
Hi everyone,

I have created a custom field plugin which is connectect to mapbox search API to get locations when the user types.
I have created the component and everything seems to be working fine until the part where I need to send the object to API.

When I want to store the location title in the API it works just fine 

```
{
"id": 1,
"companyName": "Stina",
"location": "South Africa",
"published_at": "2021-02-25T22:31:14.550Z",
"created_at": "2021-02-25T22:29:18.335Z",
"updated_at": "2021-02-28T21:55:15.064Z",
}
```

So this is the code used to get that: 

```
 const updateLocationValue = (locationValue) => {
    props.onChange({
      target: { name: "location", value: locationValue.title },
    });
  };
```

But when I want to send the whole object so I can get the coordinates as well I get null 

```
{
"id": 1,
"companyName": "Stina",
"location": null,
"published_at": "2021-02-25T22:31:14.550Z",
"created_at": "2021-02-25T22:29:18.335Z",
"updated_at": "2021-02-28T21:55:15.064Z",
}
```

This is the code that I use to send the whole object, and this works just fine in the console log and I am getting the coordinates as well but I can't pass it to Strapi: 

```
 const updateLocationValue = (locationValue) => {
    props.onChange({
      target: { name: "location", value: locationValue },
    });
  };
```

I am expecting to see an object just as below so I can get the title and coordinates:

```
{
"id": 1,
"companyName": "Stina",
"location": {object},
"published_at": "2021-02-25T22:31:14.550Z",
"created_at": "2021-02-25T22:29:18.335Z",
"updated_at": "2021-02-28T21:55:15.064Z",
}
```

I have registered the field in company.settings.json just as you can see below:

```
{
  "kind": "collectionType",
  "collectionName": "companies",
  "info": {
    "name": "Company",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "companyName": {
      "type": "string"
    },
    "location": {
      "type": "locationsearch",
      "columnType": "longtext"
    },
    "products": {
      "collection": "product",
      "via": "company"
    }
  }
}
```

So the columnType is longtext, I have tried to change it to "object" or "JSON" but it still shows me null

Here is the full code of the component which is working just fine

### Code snippets

```import React, { useState, useEffect, useRef } from "react";
import { Label, InputText } from "@buffetjs/core";

const apiToken =
  "****************************************";

export default function Location(props) {
  const [locationTitle, setLocationTitle] = useState("");
  const [suggestions, setSuggestions] = useState([]);
  const [suggestionsOpen, setSuggestionsOpen] = useState(false);
  const wrapperRef = useRef(null);
  const popperEl = useRef(null);
  const [cursor, setCursor] = useState(null);

  const fetchLocation = (searchText) => {
    searchText &&
      fetch(
        `https://api.mapbox.com/geocoding/v5/mapbox.places/${searchText}.json?access_token=${apiToken}`
      )
        .then((response) => response.json())
        .then((data) => {
          const newSuggestions = data
            ? data.features.map((feature) => ({
                title: feature.place_name,
                centerCoordinates: feature.center,
              }))
            : [];
          setSuggestions(newSuggestions);
        });
  };

  useEffect(() => {
    locationTitle && fetchLocation(locationTitle);
  }, [locationTitle]);

  useEffect(() => {
    document.addEventListener("mousedown", handleClickOutside);

    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  });

  const updateLocationValue = (locationValue) => {
    props.onChange({
      target: { name: "location", value: locationValue.title },
    });
  };

  const handleClickOutside = (e) => {
    const { current: wrap } = wrapperRef;
    if (wrap && !wrap.contains(e.target)) {
      setSuggestionsOpen(false);
    }
  };

  const setLocationValue = (location) => {
    setLocationTitle(location.title);
    updateLocationValue(location);
    setSuggestionsOpen(false);
  };

  return (
    <div ref={wrapperRef}>
      <Label htmlFor="input">Location</Label>
      <InputText
        name="input"
        onChange={(e) => setLocationTitle(e.target.value)}
        placeholder="Riva 16, 21420, Bol, Croatia"
        type="search"
        value={locationTitle}
        onClick={() => setSuggestionsOpen(true)}
      />
      <div ref={popperEl} className="options-wrapper">
        {suggestionsOpen && (
          <div>
            {suggestions.map((suggestion) => {
              return (
                <div
                  onClick={() => setLocationValue(suggestion)}
                  key={suggestion.id}
                >
                  {suggestion.title}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
```

Could anyone recommend any steps to finalize this?

Thanks a lot!

**Comment by soupette** [comment]
Can you try with the following:


`onClick = {() => setLocationValue(suggestion.id) }`

**Comment by MotaZor94** [comment]
Hi, this will still show null in DB,

I have tried now again to send the 

> Can you try with the following:
> 
> `onClick = {() => setLocationValue(suggestion.id) }`

Hi @soupette,

Thank you for the reply.

This will show null as well in the database.

I have tried to send the full object now again.



So now I'm trying to do this:
```
onClick={() => setLocationValue(suggestion)}
```

Then the locationValue get's updated

```
 const setLocationValue = (location) => {
    setLocationTitle(location.title);
    updateLocationValue(location);
    setSuggestionsOpen(false);
  };
```

Goes over here:

```
 const updateLocationValue = (locationValue) => {
    console.log(locationValue);
    props.onChange({
      target: { name: "location", value: locationValue },
    });
  };
```

When I console log the locationValue that is being sent to strapi I get this:

<img width="1170" alt="Screen Shot 2021-03-01 at 10 26 36" src="https://user-images.githubusercontent.com/45624002/109479165-67bd7380-7a7a-11eb-9139-b0f98c8ed80d.png">

But location in API shows NULL, which I belive is due to the fact that the columnType is longtext in company.setings.json:

```
 "location": {
      "type": "locationsearch",
      "columnType": "longtext"
    },
```

Is there something else that maybe is done wrong?

**Comment by MotaZor94** [comment]
Just an update

I've wrapped locationValue in JSON.stringify and it works now but it seems to me that this is a hacky way of doing it.
"location": "{\"title\":\"Praha, Prague, Czech Republic\",\"centerCoordinates\":[14.42139,50.08861]}",

**Comment by MotaZor94** [comment]
I get this error when pushed to Heroku which is using postgres 

<img width="1437" alt="Screen Shot 2021-03-01 at 11 46 53" src="https://user-images.githubusercontent.com/45624002/109487017-f256a080-7a83-11eb-9e8c-bfedf3559f57.png">

**Comment by derrickmehaffy** [comment]
> I get this error when pushed to Heroku with columnType: longtext. I am using postgreSQL

longtext isn't a valid type in PostgreSQL: https://www.postgresql.org/docs/12/datatype-character.html

You either need varchar(n) or text, longtext is a MySQL/MariaDB data type. Marking as closed as this is not an issue with Strapi.
