### ISSUE TITLE
Cannot create table when create a Content Types

### ISSUE THREAD

**Issue by samawong** [strapi/strapi#955]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**:v9.3.0
- **npm version**:v5.8.0
- **Strapi version**:3.0.0-alpha.11.3
- **Database**:PostgreSQL 10.3 (Ubuntu 10.3-1.pgdg16.04+1) 
- **Operating system**:Ubuntu 17.10

**What is the current behavior?**
When I create a content types, and i  fields in this content type,the system notice an error,i find some information about this error,like:
 UnhandledPromiseRejectionWarning: Error: A model cannot be destroyed without a "where" clause or an idAttribute. and
[2018-04-17T15:06:10.597Z] error select count(*) as "count" from "products" - 关系 "products" 不存在
[2018-04-17T15:06:10.598Z] debug GET /content-manager/explorer/product/count?source=content-manager (37 ms)
[2018-04-17T15:06:10.606Z] error select "products".* from "products" order by "id" asc limit $1 - 关系 "products" 不存在
,so what  I need to fixed this problem?

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

---

*FEATURE REQUEST TEMPLATE*  

**What is the expected behavior?**

---

- [ ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hi @samawong have you manually create your table and column ?

**Comment by samawong** [comment]
Do I have to manually create the table myself? If it is necessary, then there is no problem

**Comment by lauriejim** [comment]
Actually yes, we will work on SQL experience during next months.

**Comment by samawong** [comment]
Thanks!
