### ISSUE TITLE
Update user email validation

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#9554]
### Describe the bug

The email validation fails, when updating a user. Validation on registration works. The bug occured on production.

### Steps to reproduce the behavior

1. Go to  Settings > Users > Edit
2. Change data
2. Click on savve

### Expected behavior

User data can be saved.

### Screenshots

![image](https://user-images.githubusercontent.com/13353525/109494712-888fc400-7a8e-11eb-9582-4a916308246f.png)

### System

- Node.js v14.15.3
- NPM version: 6.14.11
- Strapi version: 3.5.2
- Database: mongo
- Operating system: gcloud run (managed), don't know further

**Comment by LevanMamontTsiklauri** [comment]
We observe the same behavior with v3.5.2

**Comment by frouo** [comment]
I was able to reproduce using `strapi/examples/getstarted` (cf. [CONTRIBUTING.md](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md)). 

The email regex in `inputsValidations.js` looks ok.

I am trying to find the issue but I must confess that I am new to JS / web development / nodejs, so I hope someone more experimented could help us 🙏🏻

![Capture d’écran 2021-03-02 à 23 36 56](https://user-images.githubusercontent.com/2499356/109725264-2976a000-7bb1-11eb-8303-a3679b8fc8cc.jpg)

**Comment by derrickmehaffy** [comment]
Most likely culprit

https://github.com/strapi/strapi/blob/048e6fd3afe7e96bcf4e75ccff7ce78cd1bc89e9/packages/strapi-helper-plugin/lib/src/utils/inputsValidations.js#L14-L15

**Comment by frouo** [comment]
> Most likely culprit
> 
> https://github.com/strapi/strapi/blob/048e6fd3afe7e96bcf4e75ccff7ce78cd1bc89e9/packages/strapi-helper-plugin/lib/src/utils/inputsValidations.js#L14-L15

I don't think so, the regex seems to be ok, see:

<img width="1392" alt="Capture d’écran 2021-03-03 à 09 54 03" src="https://user-images.githubusercontent.com/2499356/109780305-2e663e80-7c07-11eb-9f3d-a7e60a24a24a.png">

**Comment by frouo** [comment]
@derrickmehaffy I found out that this line throw an error of type `topLevelDomainValidation`.

https://github.com/strapi/strapi/blob/ebcfa07c338f3d1ac7fe29162fd9ab8edb4fba39/packages/strapi-admin/admin/src/utils/checkFormValidity.js#L7

I have to stop here, I hope this could help. Thank you for all your work!

<img width="2560" alt="Capture d’écran 2021-03-03 à 11 09 58" src="https://user-images.githubusercontent.com/2499356/109789943-24493d80-7c11-11eb-8e7f-eaa6c7da291f.png">
