### ISSUE TITLE
Grapql error "Cannot return null for non-nullable field UsersPermissionsMeRole.name."

### ISSUE THREAD

**Issue by DennieMello** [strapi/strapi#9557]
### Describe the bug

If you enable email confirmation for users when using graphql and the emailConfirmation mutation, you cannot get the user's role. The error "Cannot return null for non-nullable field UsersPermissionsMeRole.name." At the same time jwt and other user data returns. The role is also returned when this user is registered.

### Expected behavior

User role should return.

### Screenshots

![Снимок экрана 2021-03-01 в 19 47 39](https://user-images.githubusercontent.com/39631512/109529677-040d6780-7ac7-11eb-8e31-32c56601191f.jpg)

### Code snippets

`{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field UsersPermissionsMeRole.name.",
      "locations": [
        {
          "line": 8,
          "column": 9
        }
      ],
      "path": [
        "emailConfirmation",
        "user",
        "role",
        "name"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field UsersPermissionsMeRole.name.",
            "    at completeValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:595:13)",
            "    at completeValueCatchingError (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:530:19)",
            "    at resolveField (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:461:10)",
            "    at executeFields (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:297:18)",
            "    at collectAndExecuteSubfields (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:626:12)",
            "    at completeValueCatchingError (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:530:19)",
            "    at resolveField (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:461:10)",
            "    at executeFields (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:297:18)",
            "    at collectAndExecuteSubfields (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:626:12)",
            "    at completeValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:592:21)",
            "    at completeValueCatchingError (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:530:19)",
            "    at resolveField (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:461:10)",
            "    at executeFields (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:297:18)",
            "    at collectAndExecuteSubfields (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:626:12)",
            "    at /Users/Rikka/iMac/Projects/apps/speak/backend/speak_backend/node_modules/graphql/execution/execute.js:527:16"
          ]
        }
      }
    }
  ],
  "data": {
    "emailConfirmation": {
      "jwt": "{I hid it}",
      "user": {
        "id": "24",
        "username": "monolog",
        "role": null
      }
    }
  }
}`

### System

- Node.js version: Node.js version: 14.15.4
- NPM version: 7.5.4
- Strapi version:  3.5.1
- Database: 12.2
- Operating system: Mac OS 10.15.7

**Comment by derrickmehaffy** [comment]
should be fixed in v4
