### ISSUE TITLE
Auto sort results fetched from content API in DESC order with respect to entry id.

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#9567]
### Summary

Its very panic to pass _sort=id:DESC after every api endpoint to fetch result with the latest data on top, or to modify each controller and hardcore the query, I mean its obvious the api should return the data with latest rows on top and oldest in bottom , or if you can't make it default then atleast give some option in admin panel to set default sort for all Content Rest Api's

### Why is it needed?

Its frustrating to add filter in every api endpoint and when integrating it with android app, we have to pass sort param in every api call. 

### Suggested solution(s)

Make sort DESC by Id or created date as default.

**Comment by derrickmehaffy** [comment]
>  I mean its obvious the api should return the data with latest rows on top and oldest in bottom

This is not always the case, and in most examples I've seen there is no need. It's quite common to fetch things in alphabetical order, ect. We make no assumptions about the use-case and simply provide it in the most common standard which is the default method of how the database responds (no sort applied).

---

The easiest means to modify this logic is to create a policy (see our docs: https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#policies )

And in this I've created a very basic example for you, create a global policy: https://github.com/derrickmehaffy/strapi-sort-policy/blob/main/config/policies/sortDesc.js that checks if there is a _sort key, and if there isn't then set one.

You then apply this policy to the routes that need it: https://github.com/derrickmehaffy/strapi-sort-policy/blob/723edd9cc95f5ace1644d33be7fbce26b316e942/api/article/config/routes.json#L8

![image](https://user-images.githubusercontent.com/8593673/110367082-7371e280-8004-11eb-84c1-244ffbccf6c9.png)

Marking as closed as this is quite easy to handle at a per-project level.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/custom-sort-order-to-ignore-the-prefix/5005/1
