### ISSUE TITLE
How to install graphql plugin to strapi V3.x.x

### ISSUE THREAD

**Issue by Lengatox** [strapi/strapi#957]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: MongoDB
- **Operating system**: Ubuntu 16.0.4

Maybe someone could give me information, about how to install strapi-plugin-graphql on strapi 3.0.0-alpha.11.3 ?

**Comment by lauriejim** [comment]
This feature is not available on npm. So you can't, we will try to release it tomorrow.

If you have a local setup of Strapi (see contributing guide) run `strapi install graphql --dev`

**Comment by Lengatox** [comment]
ok, i will wait for the release.

thanks for your answer.

**Comment by Lengatox** [comment]
ok, i will wait for the release.

Maybe you could help me, to find an alternative way to execute complex nested requests? :) :+1:
