### ISSUE TITLE
No preview available for video or audio

### ISSUE THREAD

**Issue by fandy** [strapi/strapi#9570]
.wav and .mp4 files don't seem to show previews after uploading. Is this intended?

![image](https://user-images.githubusercontent.com/19108762/109646404-25517080-7b26-11eb-9a73-0f62d07a3ab8.png)

**Comment by Leotrimlota** [comment]
One up here 👍

**Comment by flipswitchingmonkey** [comment]
The issue appears to be that for video files, the `previewUrl` in `node_modules/strapi-plugin-upload/admin/src/components/CardPreview/index.js:36` is `null`. For some reason the preview is not passed through, but instead the preview is in `url`. So, as a quick fix, copy this file to`extensions/upload/admin/src/components/CardPreview/index.js` and replace the line with:
```
...
 <VideoPreview src={url} previewUrl={url} hasIcon={hasIcon} />
...
```
This will show the preview (at least until I've worked out at what point the previewUrl is _not_ set....)

**Comment by soupette** [comment]
This has been fixed in the v4.

**Comment by derrickmehaffy** [comment]
^^^ Closing
