### ISSUE TITLE
Files linking to collections have no relations (after restart)

### ISSUE THREAD

**Issue by ms-eztut** [strapi/strapi#9573]
### Describe the bug

Files (model from plugin upload) have no relation to linked collections.

### Steps to reproduce the behavior

1. Create a collection test
2. Create a component testcomponent with a media field
3. Create a relation from test to testcomponent
4. Create a new test entity, add a testcomponent and upload a file to the media field
5. Use the strapi api to view the files attributes (it is related to the collation)
6. Restart the server
7. Look at the file again. The relation is gone

### Expected behavior

Files should have relations to collections. Even after a restart.

### Screenshots

The related array has one relation after creating the file as expected
![image](https://user-images.githubusercontent.com/67739902/109670105-147b1c00-7b73-11eb-999e-78953a96c44b.png)

The related array is now empty (after restart)
![image](https://user-images.githubusercontent.com/67739902/109670588-8d7a7380-7b73-11eb-9ac0-d8323a6e2424.png)

### System

- Node.js version: 14
- Strapi version: 3.5.1
- Database: mongo
- Operating system: Windows/Linux

**Comment by MattieBelt** [comment]
> Operating system: Windows/Linux

@ms-eztut, I assume you are using docker here? 
This FAQ also applies for when you have a new docker container: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-paas

Does this help?

**Comment by ms-eztut** [comment]
@MattieBelt thank you for your answer.
But this case does not match at all.

I believe some start up scripts from strapi are removing the relations.
All other data is still stored

**Comment by derrickmehaffy** [comment]
We need more information to reproduce this as I tested and could not.

**Comment by ms-eztut** [comment]
Hi @derrickmehaffy, thank you for your answer.
Tested it again right now with 3.5.3. Same problem.

I made a video for better understanding:
https://easytutoronline-my.sharepoint.com/:v:/g/personal/max_spies_easy-tutor_eu/EemJ0-EmN7xApY1EhL7STL0BHEcJvePnXh5Xa5VVmBXNdw?e=4lylIY

Repo for this issue on https://github.com/ms-eztut/strapi-component-relation-issuse.

It's an almost empty strapi project with one collection 'test' relating on a component 'testcomponent' and a media field in it.

1. create a new collection entry of type 'test'
2. insert inside this entry a new component of type 'testcomponent' with a media field
3. upload a file to the media field
4. the relation of the uploaded file at the field 'related' exists in the mongo collection upload_file.
5.restart the server
6. the 'related' field of the new file in the mongo collectio upload_file is gone.

**Comment by derrickmehaffy** [comment]
Can you test on v3.5.3 please.

**Comment by ms-eztut** [comment]
@derrickmehaffy i did.
Please take a look at the video i've made (about 1min). This may describes the bug better

**Comment by ms-eztut** [comment]
@derrickmehaffy you saw that issue on the video: https://easytutoronline-my.sharepoint.com/:v:/g/personal/max_spies_easy-tutor_eu/EemJ0-EmN7xApY1EhL7STL0BHEcJvePnXh5Xa5VVmBXNdw?e=4lylIY ?

**Comment by derrickmehaffy** [comment]
Ah alright it's in components thats why, I believe this is related to https://github.com/strapi/strapi/issues/9308 can you confirm?

**Comment by ms-eztut** [comment]
yes, this is a simular behaviour

**Comment by derrickmehaffy** [comment]
Closing this in favor of https://github.com/strapi/strapi/issues/9308 then as it's a duplicate but thank you for the additional information.
