### ISSUE TITLE
GraphQL groupBy not available in many to many relationships

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#9574]
### Describe the bug

If a `many to many` relationship is made, the `schema.graphql` file doesn't add a `groupBy` connection, so it is not possible to make `groupBy` queries about that relationship.

### Steps to reproduce the behavior

Create a many to many relationship. For example: `Book` can have multiple `Authors`, each `Author` can have multiple `Books`.
Create a query in order to get how many authors have a book that is available for sale. This will output graphQL validation error `"Cannot query field \"authors\" on type \"BookGroupBy\"`

```
  getAuthorsCount: {
      query: gql`query {
        getAuthorsCount: booksConnection(where: {available_for_sale: true}) {
          groupBy {
            authors {
              name {
                key
                connection {
                  aggregate {
                    count
                  }
                }
              }
            }
          }
        }
      }`,
```

I also tried this approach, but it outputs the total number of books available for sale, not the number of authors with books available for sale (that is what I intended).

  ```
getAuthorsCount: {
      query: gql`query {
        getAuthorsCount: authorsConnection(where: { books: {available_for_sale: true}}) {
          aggregate {
            count
          }
        }
      }`,
    },
```

### Expected behavior
Right now this is what is created in `/exports/graphql/schema.graphql`
```
type BookGroupBy {
  id: [BookConnectionId]
  title: [BookConnectionTitle]
}
```
This should be created instead
```
type BookGroupBy {
  id: [BookConnectionId]
  title: [BookConnectionTitle]
  authors: [BookConnectionAuthors]
}
```

### System

- Node.js version: v12.16.3
- NPM version: 6.14.10
- Strapi version: 3.5.2
- Database: PostgreSQL
- Operating system: Ubuntu 20.10

**Comment by ssmith-14Four** [comment]
The same issue exists on a "has many" relationship.

**Comment by Jesus82** [comment]
Are you having any issues reproducing this?

**Comment by derrickmehaffy** [comment]
> Are you having any issues reproducing this?

Time lol, just time for now.

**Comment by derrickmehaffy** [comment]
aggregations don't exist in v4 for now, marking as closed

**Comment by Jesus82** [comment]
That's bad news as my project (and I guess many others) relies on aggregations. Without them I may have to download a set of data just for counting it and giving a total.

Are they totally discarded for v4 or are they planned to be implemented later? Thanks!

**Comment by derrickmehaffy** [comment]
> That's bad news as my project (and I guess many others) relies on aggregations. Without them I may have to download a set of data just for counting it and giving a total.
> 
> Are they totally discarded for v4 or are they planned to be implemented later? Thanks!

possibly later, hasn't been scoped out
