### ISSUE TITLE
Plugin development setup failed

### ISSUE THREAD

**Issue by crackhopper** [strapi/strapi#958]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.11.3 (clone from github today)
- **Database**: mongodb (runing in docker, latest version)
- **Operating system**: ubuntu 16.04

**What is the current behavior?**

when I follow the online document https://strapi.io/documentation/plugin-development/quick-start.html , I got following error when I tried to lauch the plugin's frontend.
 
```
~/proj/work/myDevelopmentProject/plugins/my-plugin/admin$ sudo npm start

> strapi-plugin-my-plugin@0.0.0 start /home/crackhopper/proj/work/myDevelopmentProject/plugins/my-plugin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development node ./node_modules/strapi-helper-plugin/lib/server


Strapi plugin succesfully started in development mode. ✓

-----------------------------------
Access URL: http://localhost:3000
-----------------------------------
Press CTRL-C to stop
    
webpack built 6f8180f0c746b4c6b784 in 854ms

ERROR in /home/crackhopper/proj/work/myDevelopmentProject/admin/admin/src/app.js
Module parse failed: Unexpected token (57:4)
You may need an appropriate loader to handle this file type.
| const render = (translatedMessages) => {
|   ReactDOM.render(
|     <Provider store={store}>
|       <LanguageProvider messages={translatedMessages}>
|         <ConnectedRouter history={history}>
 @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr /home/crackhopper/proj/work/myDevelopmentProject/admin/admin/src/app.js
```

**Steps to reproduce the problem**

Just following the documentation.

**What is the expected behavior?**

The server could start normally.

**Suggested solutions**

I have no idea.  I guess it is because webpack configuration (something about react loader?).  I am not an expert about webpack, so I need your help or any suggestions.  I want to keep following the plugin development tutorial.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by soupette** [comment]
Hi @crackhopper just to make you did `npm run setup` after cloning the repository?

Also, why are you using the `3000` port?

**Comment by crackhopper** [comment]
I have also tried to log out the webpack configuration, it is listed partly as below:

```
....

  "module": {
    "loaders": [
      {
        "test": {},
        "use": {
          "loader": "babel-loader",
          "options": {
            "presets": [
              [
                "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-preset-env/lib/index.js",
                {
                  "es2015": {
                    "modules": false
                  }
                }
              ],
              "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-preset-react/lib/index.js",
              "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-preset-stage-0/lib/index.js",
              "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-preset-react-hmre/index.js"
            ],
            "env": {
              "production": {
                "only": [
                  "src"
                ],
                "plugins": [
                  "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js",
                  "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js",
                  "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-plugin-transform-react-inline-elements/lib/index.js",
                  "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js",
                  "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-plugin-transform-es2015-parameters/lib/index.js",
                  "/home/crackhopper/proj/work/strapi/packages/strapi-helper-plugin/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js"
                ]
              },
              "test": {
                "plugins": [
                  "istanbul"
                ]
              }
            }
          }
        },
        "include": [
          "/home/crackhopper/proj/work/myDevelopmentProject/plugins/my-plugin/admin/src",
          "/home/crackhopper/proj/work/myDevelopmentProject/plugins/my-plugin/node_modules/strapi-helper-plugin/lib/src"
        ]
      },
....

```
I will track it down to figure out why it doesn't work.  and post it here.

**Comment by soupette** [comment]
You're right it's completely due to webpack. What's weird is that I've never faced this issue before...

Can you try to install Strapi from the `reduce-setup-monorepo` and create a new app?

**Comment by crackhopper** [comment]
I guess I figure out where is the problem.  The webpack configuration is load from `strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js`,  and it defines the babel-loader's include directory as 
```
include: [path.join(adminPath, 'admin', 'src')]
        .concat(plugins.src.reduce((acc, current) => {
          acc.push(path.resolve(appPath, 'plugins', current, 'admin', 'src'), plugins.folders[current]);

          return acc;
        }, []))
            .concat([path.join(adminPath, 'node_modules', 'strapi-helper-plugin', 'lib', 'src')])
```

if I `npm start` from plugin's `admin` folder, then it would not include the `myDevelopmentProject/admin` folder which is a soft link to `strapi/packages/strapi-admin/`.

When I tried to lauch `npm start` from `myDevelopmentProject/admin`, it tried to use port 4000 but blamed `Cannot find module '/home/crackhopper/proj/work/strapi/packages/node_modules/strapi'`. 

I think I could fix it temporarily by some hacks.

By the way, what is `reduce-setup-monorepo`, could you please give me some references, I would try.

**Comment by crackhopper** [comment]
by adding `.concat([path.join(appPath, 'admin','admin','src'),path.join(appPath,'admin', 'node_modules', 'strapi-helper-plugin', 'lib', 'src')])` to the `include` entry, I can start up the frontend now.

But, another issue, the frontend page cannot retrieve the layout.  Don't know why.

**Comment by soupette** [comment]
Hi @crackhopper did you find a solution to your issue?

**Comment by soupette** [comment]
@crackhopper I found the bug!

You have to start your dev server from the admin folder:

`cd my-app/admin && npm start`

You were starting your server from the a plugin folder therefore the path for webpack weren't good
