### ISSUE TITLE
After Restart Server Create Collection type is Invisible

### ISSUE THREAD

**Issue by designer-eleven11** [strapi/strapi#9583]
When I start strapi server for 1st Time it shows all options without any problem
but when I restart the Server 2nd Time it hides the  options of **creating new collection types**
in **Content-Type Builder**

## When 1st Load Up 
![issue-img-1](https://user-images.githubusercontent.com/78849432/109788399-17d4dd00-7c31-11eb-9bff-e33fc95c58cb.PNG)
Work Proper As it Should
I have create 2 collection type Blogs & Categories
## After Restart
![issue-img-2](https://user-images.githubusercontent.com/78849432/109788833-887bf980-7c31-11eb-8b95-f5afe91227fd.PNG)
it Remove OR Hide The **creating new collection types**

**Comment by designer-eleven11** [comment]
_**### Please How can I fix it**_

**Comment by aksdevac** [comment]
you will need to start server using 'develop' command, `yarn develop` to enable that.

**Comment by MattieBelt** [comment]
This FAQ might give you an answer: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
But indeed, as @aksdevac said, you need to start your strapi app in development mode.

**Comment by derrickmehaffy** [comment]
Closing as it's either related to the `NODE_ENV` being used or the user is not using the `develop` command and is instead using start. See the link provided to our FAQ: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

Closing
