### ISSUE TITLE
Cannot upload file using user API

### ISSUE THREAD

**Issue by miladreisi** [strapi/strapi#9585]
Hello
I want to upload user profile image using standard API but it seems that strapi don't care about multipart in user api.

my request

url: http://localhost:1337/users/:id

JS code

var myHeaders = new Headers();
myHeaders.append("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMzgzNjE4Yzg1MzNjMTg5Njk3YTE0MiIsImlhdCI6MTYxNDI5NjYwMCwiZXhwIjoxNjE2ODg4NjAwfQ._CfQLo_dNi4u0IYVAPaOCUQbjaZcrivy_vxWYGl5S6g");

var formdata = new FormData();
formdata.append("files.image", fileInput.files[0], "Screenshot from 2020-12-17 20-54-22.png");
formdata.append("data", "{\"basicProfile\":{\"name2\":\"m\"}}");

var requestOptions = {
  method: 'PUT',
  headers: myHeaders,
  body: formdata,
  redirect: 'follow'
};

fetch("http://localhost:1337/users/60383618c8533c189697a142", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));

![Screenshot from 2021-03-03 15-42-37](https://user-images.githubusercontent.com/16034365/109804103-20c8ad00-7c37-11eb-8fac-11fb4db62d99.png)

**Comment by abhiditi** [comment]
facing similar issue while uploading images using multipart

**Comment by abhiditi** [comment]
facing a similar issue while uploading a file using multipart to a collection with Cloudinary plugin.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
