### ISSUE TITLE
Collections rows not accessible via strapi global when in draft mode

### ISSUE THREAD

**Issue by bidoubiwa** [strapi/strapi#9586]
### Describe the bug

I tried retrieving a restaurant using the global `strapi` object the following way: 
```js
const test = await strapi.services.restaurant.findOne({ id: 1 })
// { test: null }
```
I expected retrieving my restaurant with id 1

### Steps to reproduce the behavior

1. Create content type and add draft mode
2. Add rows
3. In a backend controller try to retrieve a row
4. There is none

### Expected behavior

I would have liked to be able to retrieve my rows

### Code snippets

```js
const test = await strapi.services.restaurant.findOne({ id: 1 })
// { test: null }
```

### System

- Node.js version: Node v14
- NPM version: 6.14.6
- Strapi version: 3.5.1
- Database: sqlite
- Operating system: IOS

**Comment by MattieBelt** [comment]
I guess this is not an bug, as this is intended.
`GET /restaurants/1` also gives back `404` when _Restaurant_ 1 is in draft state.

However `GET /restaurants/1?_publicationState=preview` will give back _Restaurant_ 1.
So does 
```js
const entity = await strapi.services.restaurant.findOne({ id, _publicationState: 'preview' });
```

Docs: https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#publication-state

So the example custom `findOne` will only work for non-draft-and-publish content-types 😕 
![image](https://user-images.githubusercontent.com/31662805/110109869-504df580-7dae-11eb-9299-d26d7c7962bf.png)

**Comment by derrickmehaffy** [comment]
@MattieBelt I think we are planning to change that logic for I18N but it would be good to confirm that with @Convly or @petersg83

**Comment by bidoubiwa** [comment]
Hey! Thanks for the answer :) I did not know those parameters worked in this context as well. It works for me when using `_publicationState`

**Comment by JabStrapi** [comment]
Hi @bidoubiwa, 
I am closing this issue since Mattie & Derrick answered it. Don't hesitate to reopen it if you need more details.
