### ISSUE TITLE
Search doesn't work in relation data

### ISSUE THREAD

**Issue by oeddyo** [strapi/strapi#959]
**Informations**
- **Node.js version**: 9.0
- **npm version**: 3.10.8
- **Strapi version**:  3.0.0-alpha.11.2
- **Database**: Mongo
- **Operating system**: OSX

**What is the current behavior?**
Type in relation and it doesn't do filtering
**Steps to reproduce the problem**
create a model Bag
create a model Brand
associate bag with brand. Then create two brands like LV, Chanel
Then create a bag and try to search for Chanel
it doesnt work
**What is the expected behavior?**
when you type C, the list shall be filtered to all the C started (or contains character C brands) brands
![image](https://user-images.githubusercontent.com/1943146/38924001-6776d9c4-432e-11e8-9ef6-609693ecab94.png)

**Suggested solutions**

**Comment by oeddyo** [comment]
see screenshot above

the right side, when I tried to associate Chanel with this bag. It's only two thus quite trivial, but image there are 100 brands :D

**Comment by oeddyo** [comment]
oh my god that's fast

**Comment by lauriejim** [comment]
I think this issue can be linked to this one https://github.com/strapi/strapi/issues/766

**Comment by soupette** [comment]
@lauriejim I need to fix both issue in the same time. 
I need to investigate but IMO the React Select query options is not implemented...
