### ISSUE TITLE
Unable to modify profile in Admin Panel

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#9595]
### Describe the bug

I tried to change `First Name` and `Last Name` in Strapi admin panel without changing the rest of columns. Then it gave an error message saying `This is not an email` under the `Email` column after I clicked save button although the email address is valid.

### Steps to reproduce the behavior

1. Go to Strapi admin panel then hover your name in the right top corner in the page.
2. Click on 'Profile'
3. Change 'First name' and 'Last name'
4. Click save button
4. See an error message saying `This is not an email` under the `Email` column

### Expected behavior

`First name` and `Last name` can be modified successfully and Strapi will not complain to the email address column unless the email is invalid (RegEx).

### Screenshots

Initial Profile :

![initial](https://user-images.githubusercontent.com/43397636/109921166-01d92200-7cee-11eb-9c1f-94a0b51e72bd.png)

After changing `First name` and `Last name` columns : 

![After](https://user-images.githubusercontent.com/43397636/109921218-15848880-7cee-11eb-8d03-c67031036eea.png)

Even though I fill in all columns, it still complains : 

![Complain](https://user-images.githubusercontent.com/43397636/109922034-58932b80-7cef-11eb-8d7e-039f14574dea.png)

This is the Strapi log :

![Strapi-Log](https://user-images.githubusercontent.com/43397636/109922083-6d6fbf00-7cef-11eb-9e74-97766d2441cc.png)

Network Tab (Headers) : 

![network-headers](https://user-images.githubusercontent.com/43397636/109922153-87a99d00-7cef-11eb-86bf-38e46f1cea1d.png)

Network Tab (Request) : 

![Request](https://user-images.githubusercontent.com/43397636/109922219-985a1300-7cef-11eb-913a-dee1b511add4.png)

### System

- Node.js version: v14.16.0
- NPM version: v6.4.11
- Yarn version: v1.22.5
- Strapi version: v3.5.2
- Database: MongoDB
- Operating system: Ubuntu 20.04 LTS

**Comment by soupette** [comment]
I am closing this issue as a fix has already been provided

#9588
