### ISSUE TITLE
Ratelimit has NO effect on graphql

### ISSUE THREAD

**Issue by zorox-1** [strapi/strapi#9598]
Im trying to apply rate limit on user registration graphql mutation. However. setting the register route in the admin and adding ratelimit to 'register',  has NO effect on the graphql requests. any idea on how to applt ratelimits on graphql requests // ??

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by zorox-1** [comment]
i think its a bug , the expected behaviour is to have graphql to behave normally and respect policies on routes, however, grpahql compleltety ignores policies

**Comment by derrickmehaffy** [comment]
@zorox-1 if you believe it's a bug can you please open a bug report and follow the template and include steps to reproduce.
