### ISSUE TITLE
Impossible to create a custom id primary key

### ISSUE THREAD

**Issue by ElGecko76** [strapi/strapi#9602]
### Describe the bug

I created a new collection named "Members", I did not create a service or a controller, I only used the administration. After creating a Member via a POST request, when I go to :

https://myapi.fr/members/UonjSQZVDDagt0K9yz7iAYPoj4r1

I get a 500 error and this log:

> [2021-03-04T19:33:11.359Z] error CastError: Cast to ObjectId failed for value "UonjSQZVDDagt0K9yz7iAYPoj4r1" at path "_id" for model "member"
>     at model.Query.exec (/srv/app/node_modules/mongoose/lib/query.js:4371:21)
>     at model.Query.Query.then (/srv/app/node_modules/mongoose/lib/query.js:4463:15)
>     at find (/srv/app/node_modules/strapi-connector-mongoose/lib/queries.js:434:8)
>     at Object.findOne (/srv/app/node_modules/strapi-connector-mongoose/lib/queries.js:438:27)
>     at fn (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:31:54)
>     at Object.findOne (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:15:24)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Object.findOne (/srv/app/node_modules/strapi/lib/core-api/controller.js:95:22)
>     at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
>     at async module.exports (/srv/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:88:3)
>     at async /srv/app/node_modules/strapi-utils/lib/policy.js:68:5
>     at async serve (/srv/app/node_modules/koa-static/index.js:59:5)
>     at async /srv/app/node_modules/strapi/lib/middlewares/parser/index.js:48:23
>     at async /srv/app/node_modules/strapi/lib/middlewares/xss/index.js:26:9
> [2021-03-04T19:33:11.360Z] debug GET /members/UonjSQZVDDagt0K9yz7iAYPoj4r1 (18 ms) 500

It's not possible to create a custom id?

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 5.3.2
- Database: MongoDB
- Operating system: Debian

**Comment by derrickmehaffy** [comment]
Hi @ElGecko76 currently no you cannot assign custom IDs, change the ID name or it's type on any database. We have an FAQ entry for that here: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#does-strapi-allow-me-to-change-the-default-id-type-or-name

We are planning to add this option back but currently there is no ETA. I'm going to mark this as closed but if you have questions please do let me know.

**Comment by ElGecko76** [comment]
@derrickmehaffy Thank you for the answer. So when we use a login provider like Facebook on Strapi, the uid returned by Facebook does not become the user id?

**Comment by derrickmehaffy** [comment]
No, we create an internal user, Facebook gives a token the backend application uses to fetch user information.

AFAIK it don't store that, only username and email.

**Comment by derrickmehaffy** [comment]
You could add another field and modify the provider to store it though.

**Comment by ElGecko76** [comment]
Ok thank you for the explanations. I use Firebase Authentication mainly for phone number authentication because Strapi doesn't offer it. When I log in, Firebase return a uid, I thought I'd use this uid as an identifier for each document in my Member collection. If I understand correctly, you'll instead use the id generated by Strapi as the identifier for each document and you'll use the email or phone number to find a Member and suddenly forget the uid generated by Firebase?

**Comment by derrickmehaffy** [comment]
Basically yes.
