### ISSUE TITLE
WYSIWYG editor media attachment problem

### ISSUE THREAD

**Issue by Zend87** [strapi/strapi#9606]
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:  LTS v14 
- NPM version: 6.14.11
- Strapi version: 3.5.2
- Database: sqlite
- Operating system: Debian

### Additional context

Hi, I have problem with default wyiwyg editor, when inserting media like image, it doesn't show absolute path. 
It should be like this 
![2.png] (http://localhost:1337/uploads/image.png)  

but it only appear 

![2.png] (/uploads/image.png)

It caused my angular frontend doesn't show the image from content. 

How to fix it ??

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
