### ISSUE TITLE
Google Cloud Storage is not working

### ISSUE THREAD

**Issue by Prashant4900** [strapi/strapi#9624]
I will try to upload my asset fine in google cloud storage but whenever I upload any file its give error like error Error: Internal Server Error

![image](https://user-images.githubusercontent.com/62440911/110207286-896a9080-7ea8-11eb-8656-801dec1e622b.png)

![image](https://user-images.githubusercontent.com/62440911/110207314-a737f580-7ea8-11eb-9843-cb7b820351c9.png)

**Comment by derrickmehaffy** [comment]
We did not create nor maintain this provider. Please speak to the author of the provider for issues.
