### ISSUE TITLE
Getting error when trying to download pdf in strapi gui using cloudinary file upload

### ISSUE THREAD

**Issue by ajohnson10209** [strapi/strapi#9627]
### Describe the bug

I'm using strapi-provider-upload-cloudinary (^3.1.4) and I uploaded a pdf file via the media library in the strapi gui. When I try and download the file, I see a 404 error in the web console. The page seems to be requesting a file that doesn't exist in cloudinary. 
 
### Steps to reproduce the behavior

1. Spin up a strapi project using the strapi-provider-upload-cloudinary upload provider
2. Go to media library and upload a pdf file
3. Click edit on the pdf file and click download
4. Inspect the page and go to the console. You will see a 404 error coming from cloudinary
5. You can click on this link here (same link that you will see in the screenshot below) and you will get an error: [](https://res.cloudinary.com/ajohnson10209/image/upload/v1615088515/Request_Path_cfa7610197.pdf?7583296.800000004)

### Expected behavior

The file should download onto your file system

### Screenshots

![image](https://user-images.githubusercontent.com/41972632/110228304-1116c600-7ece-11eb-9161-f1291821fdda.png)

![image](https://user-images.githubusercontent.com/41972632/110228321-31468500-7ece-11eb-8099-4286f0396f7f.png)

### System

- Node.js version: v12.20.2
- NPM version: 6.14.11
- Strapi version: 3.1.4
- Database: sqllite
- Operating system: windows

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.1.4

Please test in the latest version v3.5.2, going to mark as closed for now unless this can be reproduced in the latest version.
