### ISSUE TITLE
Strapi Auth Provider is not working

### ISSUE THREAD

**Issue by Prashant4900** [strapi/strapi#9629]
### Describe the bug

I will try to implement google and Facebook login in my Strapi project but when I tried to log in after complete every setup process it will show the 400 error

### Screenshots

![image](https://user-images.githubusercontent.com/62440911/110249744-9c12c180-7f9d-11eb-8ed5-1e94847f4ce7.png)

![image](https://user-images.githubusercontent.com/62440911/110249755-adf46480-7f9d-11eb-8abc-03726b967b68.png)

### System

- Node.js version:  v14.15.5
- NPM version: v6.14.11
- Strapi version:  v3.5.2
- Database: MongoDB Atlas
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by Prashant4900** [comment]
> > This is a templated message
> 
> Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> A proper issue submission lets us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue with the template and we can reopen this report.
> 
> Thank you.

sir pls reopen the issue this time I modify its

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/11337
