### ISSUE TITLE
Who created the collection? Who added data? Someone from my team messed up data on Strapi and I even don't know who is that?

### ISSUE THREAD

**Issue by shyam-bihari** [strapi/strapi#9636]
Please give information about who is the editor of things? I am working with the team of 20 people and one of them added wrong data? created lots of non-sense collections and When I did asked they all said No. How to figure out Who did this?

If no option to find out. Why we have to create different users when we even can't find out who the hell is evil here

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
