### ISSUE TITLE
Local plugin API routes not working unless providing a "prefix" key (of any value!)

### ISSUE THREAD

**Issue by orro3790** [strapi/strapi#9639]
### System

- Node.js version:  v14.15.1
- NPM version: 6.14.11
- Strapi version: 3.5.2
- Database: MongoDB Atlas
- Operating system: Win 10

### Problem:

I have a local plugin called "vehicle-router" and I'm trying to set up an api endpoint for it at /vehicle-router/calculate

in my \plugins\vehicle-router\config\routes.json file:

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/vehicle-router",
      "handler": "vehicle-router.calculate",
      "config": {
        "policies": [],
        "prefix": ""
      }
    }
  ]
}
```

and in my \plugins\vehicle-router\controllers\vehicle-router.js file:

```
"use strict";

module.exports = {
  async calculate(ctx) {
    ctx.send("triggered the calculate endpoint!");
  },
};
```

Now, when I go to http://localhost:1337/vehicle-router/calculate I get a 404. If I add ANYTHING to the prefix key, it suddenly works:

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/vehicle-router",
      "handler": "vehicle-router.calculate",
      "config": {
        "policies": [],
        "prefix": "dfsdfdsfdsfsdfds"
      }
    }
  ]
}
```

I can't seem to understand what is happening here. Any help? :( Thanks!

**Comment by derrickmehaffy** [comment]
@orro3790 remove the prefix key from your routes and it will default to your plugin's name. Generally speaking we don't usually allow for questions about custom development or plugins on the main repo but I want to ensure there isn't a bug we aren't aware of so I'll leave this open.

However, can you please include at least the `system` information from our bug report template, usually any issue opened that doesn't follow one of our templates will be closed.

see: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

**Comment by orro3790** [comment]
You are correct, I removed the prefix key and it works. No bug!

**Comment by artuska** [comment]
I have absolutely the same problem, but my `routes` route was without the `prefx: ""` and nothing worked for me... until i found this issue and put `prefix` in my route config and now everythin magically works.
