### ISSUE TITLE
"Description" field is always empty in Strapi's editor

### ISSUE THREAD

**Issue by cgonzalezsan** [strapi/strapi#9645]
## Bug report

`description_en` and `description_de` fields are always empty in Strapi editor

My product collection type settings.json

```
{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "name": "Product",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "import_complete": {
      "default": false,
      "type": "boolean",
      "private": true
    },
    "slug": {
      "type": "uid",
      "targetField": "term_en"
    },
    "designer": {
      "model": "designer",
      "via": "products"
    },
    "pim_id": {
      "type": "string",
      "private": false
    },
    "product_categories": {
      "collection": "product-category",
      "via": "products",
      "dominant": true
    },
    "product_subcategories": {
      "via": "products",
      "collection": "product-subcategory",
      "dominant": true
    },
    "product_series": {
      "model": "product-series",
      "via": "products"
    },
    "product_variants": {
      "via": "product",
      "collection": "product-variant"
    },
    "name_en": {
      "type": "string"
    },
    "name_de": {
      "type": "string"
    },
    "description_en": {
      "type": "richtext"
    },
    "description_de": {
      "type": "richtext"
    },
    "assets": {
      "collection": "asset",
      "via": "products"
    },
    "articles": {
      "collection": "article",
      "via": "products"
    },
    "references": {
      "collection": "reference",
      "via": "products"
    },
    "location_types": {
      "collection": "location-type",
      "via": "products",
      "dominant": true
    },
    "channels": {
      "type": "json"
    },
    "term_en": {
      "type": "string"
    },
    "term_de": {
      "type": "string"
    },
    "ranking": {
      "type": "integer"
    },
    "dynamic_content": {
      "type": "dynamiczone",
      "components": [
        "template.s",
        "template.m",
        "template.l",
        "text-image.multi-image-layout",
        "text-image.card",
        "text-image.hero",
        "text-image.text-and-image",
        "media.side-by-side-images",
        "media.gallery",
        "media.video",
        "media.image",
        "text.text-block",
        "text.quote",
        "media.product-in-context"
      ]
    },
    "master_product": {
      "model": "product"
    },
    "meta_title_en": {
      "type": "string"
    },
    "meta_title_de": {
      "type": "string"
    },
    "meta_description_en": {
      "type": "string"
    },
    "meta_description_de": {
      "type": "string"
    }
  }
}

```
### Describe the bug

I have 2 rich text fields in my product collection type. I can save them, but when going back to the editor page, they will always be empty.

For any other rich text fields, it works fine.

### Steps to reproduce the behavior

1. Go to any product in the products collection type
2. Add some content to `description_en` and `description_de` and save
3. Reload the page
4. `description_en` and `description_de` are empty but the right values are coming through in the API request as per attached screenshot.

### Expected behavior

The content of`description_en` and `description_de` should be displayed in the rich text editor.

### Screenshots

<img width="723" alt="Screenshot 2021-03-08 at 20 28 20" src="https://user-images.githubusercontent.com/6850051/110365230-734a0500-804d-11eb-98de-15d2bfb7dd51.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.16.0
- NPM version: 6.14.11
- Strapi version: 3.5.1
- Database: MongoDB
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment]
It appears you are using a WYSWYG editor that we did not build, please contact the author of that editor or you can try using one of the ones submitted to our awesome-strapi repo: https://github.com/strapi/awesome-strapi#community-wysiwyg-replacements

In either case this is a custom modification that is not directly supported.
