### ISSUE TITLE
Getting error when trying to download pdf in strapi gui using cloudinary file upload: v3.5.2

### ISSUE THREAD

**Issue by ajohnson10209** [strapi/strapi#9646]
**Describe the bug**
I'm using strapi-provider-upload-cloudinary (3.5.2) and I uploaded a pdf file via the media library in the strapi gui. When I try and download the file, I see a 404 error in the web console. The page seems to be requesting a file that doesn't exist in cloudinary.

**Steps to reproduce the behavior**
Spin up a strapi project using the strapi-provider-upload-cloudinary upload provider
Go to media library and upload a pdf file
Click edit on the pdf file and click download
Inspect the page and go to the console. You will see a 404 error coming from cloudinary
You can click on this link here (same link that you will see in the screenshot below) and you will get an error:

**Expected behavior**
The file should download onto your file system

**Screenshots**
![image](https://user-images.githubusercontent.com/41972632/110393786-265c3380-8039-11eb-84c2-42127cbaa62b.png)
![image](https://user-images.githubusercontent.com/41972632/110393823-3bd15d80-8039-11eb-92ae-048cca62cc29.png)

**System**

- Node.js version: v12.20.2
- NPM version: 6.14.11
- Strapi version: 3.5.2
- Database: sqllite
- Operating system: windows

**Additional context**
I updated my version and still got the same error, so I created a follow up ticket to the one below.
#9627 
@derrickmehaffy

**Comment by derrickmehaffy** [comment]
@ajohnson10209 is this on a fresh project or do you have custom modifications?

Also is your project code somewhere I can look at? (I can't reproduce this on a fresh project)

**Comment by ajohnson10209** [comment]
Here is the link to the repo: https://github.com/ajohnson10209/business-bar-strapi/tree/update/verison. The only modifications I made was adding the strapi-provider-upload-cloudinary plugin.  @derrickmehaffy

**Comment by DropTheBase** [comment]
@ajohnson10209 Hi, sorry for pinging you but im having exactly the same problem as you had, did you find any solution? Can you help a brother out please?

Thanks

**Comment by ajohnson10209** [comment]
@DropTheBase No one got back to me on this issue so since I'm familiar with aws and their sdk, I used s3 for uploading my pdfs. I can share my repo if you are interested.

**Comment by derrickmehaffy** [comment]
This issue comes from Cloudinary itself and the security settings in Cloudinary. I'm marking as confirmed but it's an upstream issue.

**Comment by LouisMarzorati** [comment]
[Do you have PDFs enabled on your Cloudinary account](https://support.cloudinary.com/hc/en-us/articles/360016480179-PDF-or-ZIP-files-appearing-in-Media-Library-but-download-URLs-return-an-error-)? Free Cloudinary accounts block PDF uploads unless you manually request access to them from their support.

**Comment by ajohnson10209** [comment]
@LouisMarzorati  I didn't request pdf access on Cloudinary. Thank you.

**Comment by abhijithkmpixel** [comment]
But still in strapi the thumbnail for pdf is not getting generated also the url i get in strapi after the pdf is uploaded is
https://res.cloudinary.com/demnmts6e/image/upload/v1723547442/sohardevelopment/english_tarrifs_apr_2024_1_eb109c050a.pdf

im using the latest version of strapi v4.25.4
