### ISSUE TITLE
Social login is not secure

### ISSUE THREAD

**Issue by DennieMello** [strapi/strapi#9654]
### Describe the bug

Now, when a user registers or logs into the site via social media, the access_token is sent to the user's browser and stored in history and logs. By using this link in your browser, you can log in again, even if you have already logged out of the social network.

### Expected behavior

It would be safer to receive access_token to servers using the "Authorization code flow" approach. Then, in the user's browser, only the code with a duration of up to 1 hour will be saved and using this code, the server will receive an access_token and issue a jwt.

It seems to me worth considering this approach in the new version of authorization based on passport js.

### System

- Node.js version: Node.js version: 14.15.4
- NPM version: 7.5.4
- Strapi version:  3.5.1
- Database: 12.2
- Operating system: Mac OS 10.15.7

**Comment by derrickmehaffy** [comment]
Rough TLDR: Example of a replay attack.

@DennieMello can you dive into this a bit more on where you noticed this? Is it just the normal end-user authentication with social providers or is this in the Gold EE plan SSO?

**Comment by DennieMello** [comment]
This is a normal user authentication with social provider. According to the current documentation, it is required to send the received access_token from the frontend in order to receive jwt in exchange.

**Comment by DennieMello** [comment]
> Rough TLDR: Example of a replay attack.
> 
> @DennieMello can you dive into this a bit more on where you noticed this? Is it just the normal end-user authentication with social providers or is this in the Gold EE plan SSO?

This is a normal user authentication with social provider. According to the current documentation, it is required to send the received access_token from the frontend in order to receive jwt in exchange.

**Comment by derrickmehaffy** [comment]
Thank you for the info, I've notified our dev team to let them do some more debugging

**Comment by derrickmehaffy** [comment]
We are considering moving to Passport.js in a new users-permissions plugin we want to develop, moving this to feature request: https://feedback.strapi.io/developer-experience/p/switch-users-permissions-to-passportjs
