### ISSUE TITLE
Unable to get data from API

### ISSUE THREAD

**Issue by anshawasthi24** [strapi/strapi#9655]
I created data in admin portal, when i want to view that JSON data, i am getting empty array.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by derrickmehaffy** [comment]
@anshawasthi24 please check if that model has draft & publish enabled (it is by default): https://strapi.io/documentation/developer-docs/latest/concepts/draft-and-publish.html#draft-and-publish
