### ISSUE TITLE
Save button is disabled for wyswig edits with buttons only

### ISSUE THREAD

**Issue by yakou32** [strapi/strapi#9667]
### Describe the bug

Using the wyswyg buttons to edit an entry, the save buttons stays disabled.

### Steps to reproduce the behavior

1. Go to 'http://localhost:1337/admin/plugins/content-manager/collectionType/application:restaurants.restaurants/4' Without any edition, the save button is disabled.
2. Select some text in a wyswyg field
3. Apply bold by clicking on the bold button -> markdown code is changed with \*\*
4. See error: the save button is still disabled. Also, the user is not prompted when leaving the page without saving.
5. Edit some changes with keyboard
6. Save button becomes available

### Expected behavior

The save button should be enabled, whenever a change occurs (by keyboard or button clicks)

### System

- Node.js version: v14.16.0
- NPM version: v6.14.11
- Strapi version: v3.5.2
- Operating system: Windows 10

### Additional information
May be related to #9668

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/9589
