### ISSUE TITLE
Wyswig style is not saved for new entries under certain conditions

### ISSUE THREAD

**Issue by yakou32** [strapi/strapi#9668]
### Describe the bug

When using wyswyg buttons to edit style on a new entry, changes are not saved.

### Steps to reproduce the behavior

1. Go to a collection type
2. Create a new entry
3. Type some text and apply bold by clicking on the bold button -> markdown code is changed with \*\*
4. Save the post
5. See error: the \*\* have disappeared.

### Expected behavior

The save button should save the content, with style editions performed with buttons.

### System

- Node.js version: v14.16.0
- NPM version: v6.14.11
- Strapi version: v3.5.2
- Operating system: Windows 10

### Additional information
May be related to #9667

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/9589
