### ISSUE TITLE
Components are showing IDs instead of names when using relations

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#9672]
### Describe the bug
As seen in the screen shot components are showing IDs instead of names when using relations. And it is also not possible to set another field to display.
![Screenshot from 2021-03-10 11-28-30](https://user-images.githubusercontent.com/45003352/110616073-6a178000-8194-11eb-8c80-32fbe06da1b7.png)

### Steps to reproduce the behavior

1. Create a component with one relational field and one big text field, like this one:
![Screenshot from 2021-03-10 11-20-03](https://user-images.githubusercontent.com/45003352/110614799-fe80e300-8192-11eb-8024-f99872a0a1b9.png)
2. Use this component in a collection type

### Expected behavior

I expected to be able to set the displayed field of my entry (in my case email) like I do with relational field inside of a collection type.

### Screenshots

See above

### System

- Node.js version: v14.15.4
- Strapi version: 3.2.5
- Database: Sqlite
- Operating system: Ubuntu 20.04

**Comment by soupette** [comment]
I think it's more a feature request as we did not add the ability to set a relation as a displayable field.

**Comment by derrickmehaffy** [comment]
> I think it's more a feature request as we did not add the ability to set a relation as a displayable field.

Ah thank you @soupette, good catch

**Comment by derrickmehaffy** [comment]
Should already be possible in v4
