### ISSUE TITLE
Components: deleted field remain in API response

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#9673]
### Describe the bug

Currently I have only two fields in my component, but I had two **additional** fields `title` and `test_field`. After I deleted them, they still remain inside the API response. 
![Screenshot from 2021-03-10 11-52-39](https://user-images.githubusercontent.com/45003352/110619324-f7100880-8197-11eb-9afe-612c4abc9085.png)

### Steps to reproduce the behavior
1. Create a component and add it to a collection type
2. create content and then add and delete fields of the component

### Expected behavior
Don't show deleted fields

### System

-Node.js version: v14.15.4
-Strapi version: 3.2.5
-Database: Sqlite
-Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
Confirmed on v3.5.2 
- add a new field to the component
- add data to the articles content-type with data in the component
- check api response to ensure new field data is there
- delete the field
- check api response to see data still exists

Code example: 
[test9673.zip](https://github.com/strapi/strapi/files/6119307/test9673.zip)

---

Workaround: Manually delete the column from the database table.

**Comment by Hamza-Liaqat1** [comment]
Getting same issue on ubuntu 18.04, even after delete table data manually, still getting values

**Comment by derrickmehaffy** [comment]
Will be handled in the v4 by the new schema migration system.

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
