### ISSUE TITLE
autoPopulate does not work for polymorphic relations

### ISSUE THREAD

**Issue by kpirumyan** [strapi/strapi#9676]
name | about
-- | --
🐛 Bug Report | autoPopulate does not work for polymorphic relations.

**Bug report**
Can't disable auto-population for polymorphic fields like 'Media' from Upload plugin.

**Steps to reproduce the behavior**
Create a content type
Add a polymorphic media field
Go to <content_type>.settings.json
Add "autoPopulate": false to the field in attributes

**Expected behavior**
The response should contain only id for this field, but it actually contains whole document 

**Screenshots**
![image](https://user-images.githubusercontent.com/38978169/110662696-2e55d800-81df-11eb-832d-6449610d68d2.png)

**System**
Node.js version: v12.20.0
NPM version: 6.14.8
Strapi version: v3.5.2
Database: Mongo 4.4.2
Operating system: Win 10 x64

**Comment by derrickmehaffy** [comment]
auto-pop no longer exists in v4

**Comment by dzcpy** [comment]
@derrickmehaffy So is there any way to do the same thing in v4?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy So is there any way to do the same thing in v4?

no as automatically populating something via a toggle doesn't exist you could use a route middleware to specify a default population but we no longer populate anything by default and there is no setting to automatically do it.
