### ISSUE TITLE
strapi new my-project fails when strapi is installed globally with yarn

### ISSUE THREAD

**Issue by nklayman** [strapi/strapi#968]
**Informations**
- **Node.js version**: 9.11.1 (installed with scoop)
- **npm version**: 5.8.0
- **Yarn version**: 1.6.0 (installed with scoop)
- **Strapi version**: 3.0.0-alpha.12 (installed with yarn)
- **Database**: MongoDB community 3.6.4
- **Operating system**: Windows 10 64bit professional

**What is the current behavior?**
When installing Strapi globally with yarn, creating a new project fails with error:
`"Failed to load 'admin'... (Error: Cannot find module 'C:\Users\Noah\AppData\Local\Yarn\Data\global\node_modules\strapi\node_modules\strapi-generate-admin')`
In strapi's node_modules folder, there is only boom and koa-compose, however, strapi-generate-admin (and strapi-generate-\*) are located in C:\Users\Noah\AppData\Local\Yarn\Data\global\node_modules\
**Steps to reproduce the problem**
install strapi with yarn `yarn global add strapi@alpha`
run `strapi new my-project`
**What is the expected behavior?**
searches proper directory for strapi-generate-*, and creates the project successfully
(it works just fine with npm)
**Suggested solutions**
detect if strapi was installed with yarn and search global node_modules dir, or first check normal dir and then, if it fails, check global node_modules dir

**Comment by lauriejim** [comment]
Hi @nklayman ! We actually developed Strapi to work with npm. Yarn is not supported so you can have bugs.

We will not work on it, it's not an high priority for us.

Hope the community will be able to help you.

**Comment by abdonrd** [comment]
I have used yarn since the first day and I have not had any problems.

Operating system: macOS

**Comment by mekeor** [comment]
I'm experiencing the same error when I try to create a new project with strapi after installing it with NPM locally. See https://github.com/strapi/strapi/issues/315#issuecomment-383743350

**Comment by msgeissler** [comment]
Maybe this is a bug in yarn? There are a few old issues with similar errors:
https://github.com/yarnpkg/yarn/issues/2206

Maybe the update posted by peteroid can help you: https://github.com/yarnpkg/yarn/issues/2206#issuecomment-266351947

As it works for abdonrd, it does not seem to be a global problem.

**Comment by juicycleff** [comment]
Experiencing the same issue with the alpha cli

**Comment by intensr** [comment]
also experiencing permission problems and so on with yarn

**Comment by sajjad-shirazy** [comment]
the issue is because the package doesn't install dependencies right. so we have to do it manually :| :
```
cd C:\Users\Noah\AppData\Local\Yarn\Data\global\node_modules\strapi
yarn install
```

**Comment by derrickmehaffy** [comment]
Windows isn't supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows
Yarn isn't supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#yarn

**Comment by mynameisone** [comment]
https://github.com/strapi/strapi/issues/968#issuecomment-452201986
this worked for me
Thank you so much!

**Comment by frozmanX** [comment]
> the issue is because the package doesn't install dependencies right. so we have to do it manually :| :
> 
> ```
> cd C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\strapi
> yarn install
> ```

it works 4 me
