### ISSUE TITLE
Strapi count not working with postgresql

### ISSUE THREAD

**Issue by usermine12** [strapi/strapi#9686]
### Describe the bug

I multiple entries of my data type, and when I query the count with filter "field_contains" I get ```Error: select distinct count(*) as "count" from "companies" where LOWER(CAST("companies"."name" AS VARCHAR)) LIKE LOWER($1) - could not find pathkey item to sort```

I have 250 000+ entries of the type and when I had 100 000 entries I could query the count with filter "field_contains"

I have even tried to use [this](https://strapi.io/documentation/developer-docs/latest/guides/count-graphql.html#count-with-graphql) method from the docs instead of the normal aggregation.

### Steps to reproduce the behavior

1. Have 250 000 entries of one data type
2. query the count of datatype with filter "field_contains"

### Expected behavior

That I could query the count with filter "field_contains"

### Screenshots

When making the query
![image](https://user-images.githubusercontent.com/61495436/110794952-f3a37c80-827e-11eb-9eb9-7134c5567123.png)
error:
![image](https://user-images.githubusercontent.com/61495436/110794999-00c06b80-827f-11eb-870d-e1837bc21762.png)

this does instead work:
![image](https://user-images.githubusercontent.com/61495436/110795060-159cff00-827f-11eb-8afc-86327470c9ab.png)
results:
![image](https://user-images.githubusercontent.com/61495436/110795081-1d5ca380-827f-11eb-8059-345681e336fa.png)

### Code snippets

I have tried making a custom query to get the count as shown [here](https://strapi.io/documentation/developer-docs/latest/guides/count-graphql.html#count-with-graphql) in the docs
```
module.exports = {
    query: `
        companiesCount(where: JSON): Int!
    `,
    resolver: {
        Query: {
            companiesCount: {
                description: 'Return the count of companies',
                resolverOf: 'application::companies.companies.count',
                resolver: async (obj, options, ctx) => {
                    return await strapi.api.companies.services.companies.count(options.where || {});
                }
            }
        }
    }
}
}
```

### System

All run on digitalocean basic droplet with 1gb of ram and 1 cpu

- Node.js version: Docker image node:14-slim
- NPM version: Docker image node:14-slim
- Strapi version: 3.5.2
- Database: Postgresql 13.2, docker image postgres:latest
- Operating system: Ubuntu

### Additional context

I have tried dropping the database and adding all the entries back through strapi, but nothing changed

**Comment by derrickmehaffy** [comment]
Not an exact duplicate but merging into https://github.com/strapi/strapi/issues/7631
