### ISSUE TITLE
JSON type gives `"[object Object]"`

### ISSUE THREAD

**Issue by Joshfindit** [strapi/strapi#970]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**: `v9.9.0`
- **npm version**: `5.6.0`
- **Strapi version**: `image: strapi/strapi`
- **Database**: mongodb
- **Operating system**: docker

**What is the current behavior?**
Saving the following:
```
    [
      {
        "2018-04-12" : "Row-Data"
      }
    ]
```
Works most of the time, but once in a while the admin interface saves the field and it returns  `[object Object]`

**Steps to reproduce the problem**
Save a JSON array via the admin interface

**What is the expected behavior?**
It stores and retrieves successfully

**Suggested solutions**
Store and retrieve as a JSON string without eval

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello, can you check this issue.

**Comment by Joshfindit** [comment]
@lauriejim I checked again, and cannot find a duplicate of this issue. Can someone please connect the two?

**Comment by Joshfindit** [comment]
@lauriejim excellent, thank you.
