### ISSUE TITLE
Unable to upload file to media assets from UI

### ISSUE THREAD

**Issue by simwai** [strapi/strapi#9701]
### Describe the bug

No media upload possible from the admin UI interface

### Steps to reproduce the behavior

1. Go to http://localhost:1001/admin
2. Click on "media library"
3. Click on "upload files"
4. Click on "search for files"
5. Double click on file
6. Click on "upload to library"
7. See error "An internal server error occured" below the file size

### Expected behavior

Should be possible to upload files without an error.

### Screenshots

![image](https://user-images.githubusercontent.com/16225108/110953557-cb338500-8347-11eb-95c3-99a76ba56cf7.png)

### System

- Node.js version:   12.18.3
- NPM version: 6.14.6
- Strapi version:  3.5.3
- Database: sqlite
- Operating system: Windows 10

### Additional context

Console error mesage (when i run develop):
`[2021-03-12T14:29:42.929Z] error Error: ENOENT: no such file or directory, open 'D:\Documents\Programming\Web\Projects\wobby\public\uploads\boruto_min_e743b535ae.gif'
[2021-03-12T14:29:42.929Z] error Error: Internal Server Error
    at convertToStrapiError (D:\Documents\Programming\Web\Projects\wobby\node_modules\strapi-plugin-upload\errors.js:38:26)
    at Object.upload (D:\Documents\Programming\Web\Projects\wobby\node_modules\strapi-plugin-upload\config\functions\bootstrap.js:35:11)
[2021-03-12T14:29:42.930Z] debug POST /upload (48 ms) 500`

---------------------------------------------------------------------------------------------------------------------------------
Would be cool if you could fix that.

Thanks for your time.

Best regards,
Simon Waiblinger aka simwai

**Comment by derrickmehaffy** [comment]
> strapi v3.2.4

Please also test on the latest version, which at the time of writing is v3.5.3

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by simwai** [comment]
Ok, sry for that...

**Comment by simwai** [comment]
@derrickmehaffy updated it

**Comment by elJeffco** [comment]
Had the same issue today. Issue is caused because the folder `public/uploads` does not exists when creating a new project. Just adding this folder resolves it 😄

**Comment by simwai** [comment]
@elJeffco worked ty 💜

**Comment by simwai** [comment]
I reopend the issue, because it would be cool if that error could be prevented for other users.

**Comment by SonnyCastro** [comment]
This didn't work for me I added the new folder public/uploads and still got the error I also tried public/upload but that didn't work either. Please share how you were able to fix this issue

**Comment by SonnyCastro** [comment]
> Had the same issue today. Issue is caused because the folder `public/uploads` does not exists when creating a new project. Just adding this folder resolves it 😄 @derrickmehaffy

This didn't work for me I added the new folder public/uploads and still got the error I also tried public/upload but that didn't work either. Please share how you were able to fix this issue

**Comment by SonnyCastro** [comment]
> > Had the same issue today. Issue is caused because the folder `public/uploads` does not exists when creating a new project. Just adding this folder resolves it 😄 @derrickmehaffy
> 
> This didn't work for me I added the new folder public/uploads and still got the error I also tried public/upload but that didn't work either. Please share how you were able to fix this issue

I fixed my issue 🕺  I had to update my environment variables on heroku

**Comment by callum-gander** [comment]
I had a similar issue with strapi-provider-upload-google-cloud-storage. I added the following to the config/env/production/plugin.js, as instructed but it still didn't work

`module.exports = {
    upload: {
        provider: 'google-cloud-storage',
        providerOptions: {
            bucketName: 'bucketname',
            publicFiles: true,
            uniform: false,
            serviceAccount: JSON.stringify(service account JSON goes here},
    },
}
`

After a long period of trial and error, and a failure on the part of the documentation from both strapi and strapi-provider-upload-google-cloud-storage, I figured out from looking at old documentation that you need to put the following into extensions/upload/config/settings.json or create it. 

`{
  "provider": "google-cloud-storage",
  "providerOptions": {
    "bucketName": "bucketname",
    "publicFiles": true,
    "uniform": false,
    "serviceAccount": {service account json, no need to stringify}
}`

Once you've done this, it should connect properly. I think this issue will occur with others providers like the aws-s3 one. I think without putting a settings.json, the upload plugin just keeps trying to write the uploaded files from the admin dashboard to the local drive, even when, as on Google App Engine standard environment, you don't have write permissions to them, causing a 500 internal server error, like the following.

`error Error: ENOENT: no such file or directory, open '/workspace/public/uploads/236355598_4331515110220639_8777552771168383494_n_dc54405c7e.jpg'
2021-08-20 16:47:21 default[17]  [2021-08-20T16:47:21.452Z] error Error: Internal Server Error
2021-08-20 16:47:21 default[17]      at convertToStrapiError (/workspace/node_modules/strapi-plugin-upload/errors.js:38:26)
2021-08-20 16:47:21 default[17]      at Object.upload (/workspace/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
2021-08-20 16:47:21 default[17]      at async Object.uploadFileAndPersist (/workspace/node_modules/strapi-plugin-upload/services/Upload.js:154:5)
2021-08-20 16:47:21 default[17]      at async Promise.all (index 0)
2021-08-20 16:47:21 default[17]      at async Object.upload (/workspace/node_modules/strapi-plugin-upload/services/Upload.js:140:12)
2021-08-20 16:47:21 default[17]      at async uploadFiles (/workspace/node_modules/strapi-plugin-upload/controllers/upload/admin.js:187:27)
2021-08-20 16:47:21 default[17]      at async Object.upload (/workspace/node_modules/strapi-plugin-upload/controllers/Upload.js:65:5)
2021-08-20 16:47:21 default[17]      at async /workspace/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
2021-08-20 16:47:21 default[17]      at async /workspace/node_modules/strapi-utils/lib/policy.js:68:5
2021-08-20 16:47:21 default[17]      at async /workspace/node_modules/strapi/lib/middlewares/parser/index.js:48:23
2021-08-20 16:47:21 default[17]      at async /workspace/node_modules/strapi/lib/middlewares/xss/index.js:26:9`

 Hope this helps some people out, drove me mad!

**Comment by derrickmehaffy** [comment]
> I added the following to the config/env/production/plugin.js

It should be `config/env/production/plugins.js` key difference is **plugins.js** not plugin.js

**Comment by derrickmehaffy** [comment]
can't reproduce in v4, closing based on age of issue
