### ISSUE TITLE
Notification blocks UI

### ISSUE THREAD

**Issue by danielehrhardt** [strapi/strapi#9703]
### Describe the bug

![image](https://user-images.githubusercontent.com/19570043/110965164-397e4480-8354-11eb-911e-6e63f38204c7.png)
When a Notification Pops Up the UI is then blocked in that Area (Left Menu Area).

**Comment by derrickmehaffy** [comment]
Please check on v3.5.3 as we just had the following PR to fix it: https://github.com/strapi/strapi/pull/9562

See the v3.5.3 changelog: https://github.com/strapi/strapi/releases/tag/v3.5.3

Closing until this can be confirmed on the current version.
