### ISSUE TITLE
Strapi Unique field is not working with MongoDB

### ISSUE THREAD

**Issue by Prashant4900** [strapi/strapi#9704]
### Describe the bug

I build a Strapi project with some unique fields in SQLite at that time everything works fine it gives an error message if the field already exists but when I migrate on mongo atlas or change the database from SQLite to MongoDB the unique field now stops working I didn't change anything un projects

### Steps to reproduce the behavior

4. See an error

### Screenshots

with sqlite
![image](https://user-images.githubusercontent.com/62440911/110968010-04d2b300-837d-11eb-94b5-5946c51f451e.png)

with mongo
![image](https://user-images.githubusercontent.com/62440911/110968264-51b68980-837d-11eb-971a-eaf6be7ba9d8.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.5
- NPM version: 6.14.11
- Strapi version: 3.5.3
- Database: sql or mongo
- Operating system: any

### Additional context

I think this problem occurs due to a unique id which is created by default in the SQLite or SQL database the id field is int type or in mongo database id field is string datatype 

is there any temp solution so I complete my projects?

**Comment by abdonrd** [comment]
Related: https://github.com/strapi/strapi/issues/5863

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/5863
