### ISSUE TITLE
Migration v3.4.X to v3.5.X

### ISSUE THREAD

**Issue by xAgustin93** [strapi/strapi#9706]
Strapi already detects a new version that is 3.5.3, but the link where it says that the documentation is to go from 3.4.x to 3.5.x there is none, a guide on how to do it.

https://strapi.io/documentation/developer-docs/latest/update-migration-guides/migration-guides.html#instructions

**Comment by derrickmehaffy** [comment]
If no guide exists, there is no migration actions to perform and you can just follow the standard update guide: https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html
