### ISSUE TITLE
Feature request to add is / is not null filter

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#9709]
### Describe the bug

Filter doesn't work the way you would it expect to work for empty values. Here are some exemplary entries with and without values inside the field "description":
![Screenshot from 2021-03-13 12-47-25](https://user-images.githubusercontent.com/45003352/111029636-07292180-83fe-11eb-8f93-6672ff62bf73.png)

If you set it to: `field_name` `is not` `empty` Strapi will show the entries, which are not empty:
![Screenshot from 2021-03-13 12-47-54](https://user-images.githubusercontent.com/45003352/111029667-2d4ec180-83fe-11eb-9343-297e52fc7998.png)

But when you set it to: `field_name` `is` `empty` Strapi will **NOT** show the entries, which don't contain a value inside the mentioned field:
![Screenshot from 2021-03-13 12-48-41](https://user-images.githubusercontent.com/45003352/111029684-46577280-83fe-11eb-88f6-1f6f35b6a1c7.png)

### Steps to reproduce the behavior
Set the above mentioned filters.

### Expected behavior
Show entries, which are empty

### Screenshots
See above

### System
- Node.js version: 14.15.4
- Strapi version: 3.5.3
- Database: Sqlite
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
Updated title to a feature request for _null filter to the admin.

**Comment by derrickmehaffy** [comment]
Already added in v4, marking as closed
