### ISSUE TITLE
The argument to $size must be an array, but was of type: objectId

### ISSUE THREAD

**Issue by BeyondSpace609520** [strapi/strapi#9715]
Hello, I created table which has two relation ship fields, didn't put anything in the table, but the Strapi admin gives strange error.

![image](https://user-images.githubusercontent.com/56730274/111072430-e1be1580-84da-11eb-956a-58b069fa8b31.png)

I still able to add column in the table so I added some, but still gives error, however, I can get table data from API or Graphql.

I know actually, it is aggregate issue from MongoDB, I searched "aggregate" in project but it appears only in chunk.js which produced from Strapi.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
