### ISSUE TITLE
Use yarn workspaces

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#972]
> Workspaces are a new way to setup your package architecture that’s available by default starting from Yarn 1.0. It allows you to setup multiple packages in such a way that you only need to run `yarn install` once to install all of them in a single pass.

Reference: https://yarnpkg.com/lang/en/docs/workspaces/

Reference at `Yarn Workspaces` of [One vs. many — Why we moved from multiple git repos to a monorepo and how we set it up](https://hackernoon.com/one-vs-many-why-we-moved-from-multiple-git-repos-to-a-monorepo-and-how-we-set-it-up-f4abb0cfe469).

**Comment by lauriejim** [comment]
Hello @abdonrd can you check this issue please https://github.com/strapi/strapi/issues/885

**Comment by lauriejim** [comment]
We have to regroup all informations in one issue.

**Comment by abdonrd** [comment]
Ouch! Thanks @lauriejim!
