### ISSUE TITLE
Strapi query function does not use default limit config

### ISSUE THREAD

**Issue by ppa993** [strapi/strapi#9736]
### Describe the bug

I have the `defaultLimit ` config set to `-1` but `strapi.query` function does not seem to use it, only `strapi.service `does

### Expected behavior

strapi.query('restaurants').find() to load the default limit config

### Code snippets

`const restaurants = await strapi.query('restaurants').find()`

### System

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.5.3
- Database: MongoDB
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
We won't allow setting -1 for the query layer in v4, if you want this you need to specify it.
