### ISSUE TITLE
bug: Updating User Information with uncommon email address domain

### ISSUE THREAD

**Issue by sshanzel** [strapi/strapi#9738]
### Updating User Information with uncommon email address domain

When I try to update user information it stops me from doing so. When I register for the first time it works, this only happens on updating in the admin panel

### Steps to reproduce the behavior

1. Go to users
2. Register a user - use an email address domain from the likes of the screenshot below.
3. Complete registration by following the link
4. Go back to users page
5. Update users information 
6. See error like below

### Expected behavior

Should be able to update user information and allow email addresses from uncommon domains

### Screenshots

![image](https://user-images.githubusercontent.com/13744167/111318992-fe934e00-867e-11eb-8e14-e3a49ca51939.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.3
- NPM version: v6.14.9
- Strapi version: v3.5.2
- Database: default built-in (SQLite?)
- Operating system: Windows 10

### Additional context

I can help to work on this very simple issue, just kindly point me in the direction where I could start.

**Comment by aksdevac** [comment]
this is already fixed in `3.5.3`. please update.

**Comment by JWambaugh** [comment]
I am also having this issue in 3.5.3. In my specific case, it's email addresses that have a '.' in the name:
![image](https://user-images.githubusercontent.com/23184/111835026-a6905d80-88b1-11eb-96b7-962c1236bca3.png)

**Comment by soupette** [comment]
@JWambaugh can you upgrade all your packages to the latest version and rebuilt your admin panel using the following command : `yarn run build --clean`?

This bug as already been fixed so I am closing this issue, feel free to reopen it if the problem persists.
