### ISSUE TITLE
Qovery Deploy is only opening index page

### ISSUE THREAD

**Issue by rashidpathiyil** [strapi/strapi#9764]
### Describe the bug

Only index page is working and /admin page is showing not found when deploy to Qovery as per your documentation.

### Steps to reproduce the behavior

1. Go to 'Qovery Deployment Doc'
2. Follow the steps to deploy to Qovery
3. If your deploy is successful, try to navigate to /admin
4. See error 'not found'

### Expected behavior

When navigate to /admin, the first administrator creation form should display on the page.

**Comment by derrickmehaffy** [comment]
Please speak to the author of the documentation (PR: https://github.com/strapi/documentation/pull/96)

The author is the CEO of Qovery who wrote and contributed that documentation: https://github.com/evoxmusic
