### ISSUE TITLE
Results duplicate query 

### ISSUE THREAD

**Issue by rserafim** [strapi/strapi#9769]
### 
I am getting duplicate results when using sort, limit and start.

### Steps to reproduce the behavior

1 - starting with 0
2 - incrementing the start

### Expected behavior

Do not bring the same record sought previously.

### Screenshots

https://streamable.com/qkw7qm

### Code snippets

`query QueryListings(
    $limit: Int!, 
    $start: Int
) {
  listings(
      limit: $limit, 
      start: $start, 
      sort: "likes:desc"
  ) {
    id
    title
    street
    neighborhood
    zipcode
    city
    phones
    likes
    logo {
      url
    }
    slug
  }
}
`

### System

- Node.js version: v12.18.3
- Strapi version: v3.4.3
- Database: MongoAtlas
- Operating system:

### Additional context

If you remove the sort. He apparently doesn't have a duplicate.

**Comment by derrickmehaffy** [comment]
I've marked this as a bug, but unfortunately I'm not sure there is much we can do here. This is a nature problem of MongoDB as it will return random results. My suggestion to you here would be to switch over to a SQL database as it's default action would be to short by that key, and if there are values that are duplicate it will add in a sort by ID however MongoDB uses UUIDs that have no "order".

**Comment by rserafim** [comment]
Thanks for the feedback. But unfortunately I have no option to switch to SQL for this project. I really can't understand why he brought the same item in the other calls from the start. Sad!


> I've marked this as a bug, but unfortunately I'm not sure there is much we can do here. This is a nature problem of MongoDB as it will return random results. My suggestion to you here would be to switch over to a SQL database as it's default action would be to short by that key, and if there are values that are duplicate it will add in a sort by ID however MongoDB uses UUIDs that have no "order".

**Comment by AlexeyVlasenko** [comment]
Facing the same issue using PostgreSQL

```
/route?_limit=2&_start=0&_sort=priority:DESC
```
and
```
/route?_limit=2&_start=123&_sort=priority:DESC
```

returns the same SECOND item

(priority off all items in DB === 0)

**Comment by rserafim** [comment]
> Facing the same issue using PostgreSQL
> 
> ```
> /route?_limit=2&_start=0&_sort=priority:DESC
> ```
> 
> and
> 
> ```
> /route?_limit=2&_start=123&_sort=priority:DESC
> ```
> 
> returns the same SECOND item
> 
> (priority off all items in DB === 0)


in this case it is with Mongo. So it doesn't work for me.

**Comment by rserafim** [comment]
It is now working properly. Apparently they did.
