### ISSUE TITLE
Permission ticks disappear from UI

### ISSUE THREAD

**Issue by XcrossD** [strapi/strapi#977]
**Informations**
- **Node.js version**:
9.8.0
- **npm version**:
5.6.0
- **Strapi version**:
alpha.12
- **Database**:
mongodb
- **Operating system**:
windows 10

**What is the current behavior?**
Permissions in public role can be saved, but does not reflect on UI.

**Steps to reproduce the problem**
Tick desired route, save, ticks disappeared.
![recording1](https://user-images.githubusercontent.com/6669029/39030659-e9c0929a-4495-11e8-8a3a-7974f1811d70.gif)

**What is the expected behavior?**
Permissions should persist after save.

**Suggested solutions**

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Thank for issue reporting. Will take a look.

**Comment by Aurelsicoko** [comment]
@XcrossD Can you give us the MongoDB version? Are you using a hosted database? The requests seem pretty slow... I can't reproduce this on my machine, I need more information.

**Comment by XcrossD** [comment]
@Aurelsicoko Hosted with mLab. From the dashboard - mongod version: 3.4.14. Happy to provide more information.

Actually the route permissions have been saved, it's just after 1 second the saved route permissions disappeared.

**Comment by XcrossD** [comment]
[api.zip](https://github.com/strapi/strapi/files/1942131/api.zip)
I will test a fresh app later and let you know.

**Comment by XcrossD** [comment]
Fresh install shows the same. I could DM you my server details on slack for further testing.

**Comment by Aurelsicoko** [comment]
Thank, I just tried and it works fine on my machine again... Are you still running the app on Windows?

**Comment by XcrossD** [comment]
Yes running on windows

**Comment by soorur** [comment]
Same bug, running also on Windows :D

**Comment by Aurelsicoko** [comment]
@XcrossD @soorur Which browser are you using?

**Comment by XcrossD** [comment]
Tested both on Chrome and Firefox.

On 2018 M05 1, Tue 5:36 PM Aurélien GEORGET <notifications@github.com<mailto:notifications@github.com>> wrote:

@XcrossD<https://github.com/XcrossD> @soorur<https://github.com/soorur> Which browser are you using?

**Comment by soorur** [comment]
Latest Chrome as well - funny thing is it only reproduces for the first entity in the permission list

**Comment by XcrossD** [comment]
@Aurelsicoko I didn't do anything extra in mLab after following [this tutorial](https://blog.strapi.io/using-mlab-with-strapi/). I think by default on mLab I have write permission? I don't see where I can set write permissions for individual collections either. As I mentioned before, the route permissions are saved. If I don't have write permission, how can the route permissions be saved? Maybe this is an issue on mLab only? But then again @soorur  might be using a local database.

**Comment by XcrossD** [comment]
@Aurelsicoko Also before you said it was running fine after I gave you the mLab. What is causing the difference now?

**Comment by Aurelsicoko** [comment]
The issue was due to permissions duplication, I made a PR to fix it (https://github.com/strapi/strapi/pull/1103)

**Comment by XcrossD** [comment]
@Aurelsicoko  Weird, I just updated to 12.2 and this issue still persists. I see some permissions are ticked, some are not, so I tick those that are unticked and save, but only those that were originally ticked are visible.

**Comment by XcrossD** [comment]
Nevermind, I saw it's going to roll out in the next update. Although I'd like to come out sooner though.

**Comment by ashbrener** [comment]
I am experiencing this issue as well on our production MongoDB (compose.io).

**Comment by virtualkitchenco** [comment]
We also lost the permission on some of the public apis. We are using dockerized version of  Strapi v3.0.0-beta.14.

**Comment by ashbrener** [comment]
@virtualkitchenco this resolved the issue for us:

1. Upgraded to Strapi 3.0.1
2. Deleted the users-permissions-permissions collection in MongoDB
3. Restarted Strapi 
4. Reassigned all permissions

**Comment by virtualkitchenco** [comment]
Is there a way to fix this without upgrading to 3.0.1? Currently using Strapi v3.0.0-beta.20 @ashbrener

**Comment by ashbrener** [comment]
Have you tried simply deleting the users-permissions-permissions collection and restarting ?

**Comment by lvargas0584** [comment]
hi guys, i having the same problem.
Any one fixed that?
I'm using Strapi v 3.2.1

**Comment by derrickmehaffy** [comment]
> hi guys, i having the same problem.
> Any one fixed that?
> I'm using Strapi v 3.2.1
> 
> 

Please test on the latest release, we do not debug issues on older versions

**Comment by lvargas0584** [comment]
> > hi guys, i having the same problem.
> > Any one fixed that?
> > I'm using Strapi v 3.2.1
> 
> Please test on the latest release, we do not debug issues on older versions

Thanks, I will do it.

**Comment by Maqro-Capital** [comment]
Hi guys, 
Im still facing this problem. 
I have strapi 3.6.8 and mongo DB

I already tried:
1. Deleted the users-permissions-permissions collection in MongoDB
2. Restarted Strapi
3. Reassigned all permissions

Still, every 24 hours, the permissions are deleted. 
Is there a proper solution for this ?

**Comment by RohanJ14** [comment]
Hi guys, 
Im still facing this problem. 
I have strapi 3.6.8 and mongo DB

I already tried:
1. Deleted the users-permissions-permissions collection in MongoDB
2. Restarted Strapi
3. Reassigned all permissions

Still, every 24 hours, the permissions are deleted. 
Is there a proper solution for this ?
