### ISSUE TITLE
WYSIWYG - Text Alignement

### ISSUE THREAD

**Issue by michael-proulx** [strapi/strapi#9770]
## Feature request
Shortcode for text alignement

### Please describe your feature request
Adding 3 buttons for Text Alignement in WYSIWYG

### Why is it needed?
We are migrating from wordpress to strapi, the features is not for me but for my marketing team.
Instead of asking me every single day how to align the text in Markdown/Html, by adding a button that will do for them.

I did it in our own strapi, but if you think more people would like to have it, I could do a PR for that feature.
I could look into that issue (#8489) at the same time.

### Suggested solution(s)
- Align Left: `<p style="text-align: left;">Lorem Ipsum</p>`
- Align Center: `<p style="text-align: center;">Lorem Ipsum</p>`
- Align Right: `<p style="text-align: right;">Lorem Ipsum</p>`

![strapi-rich-text](https://user-images.githubusercontent.com/23478544/111680697-dc254000-87f8-11eb-8e71-525dbdc8e759.jpg)

**Comment by Misiu** [comment]
Please consider Justify, as many still use this in WordPress (https://wpintensity.com/justify-text-wordpress/), so this will help while migrating.

**Comment by derrickmehaffy** [comment]
I would suggest you swap out the editor for one that better suits your needs: https://github.com/strapi/awesome-strapi#community-wysiwyg-replacements

I have also seen someone in the community working on one that uses the editor from wordpress but last I saw it was still quite buggy.

**Comment by derrickmehaffy** [comment]
Closing this in favor of #12440
