### ISSUE TITLE
graphql amount limit causes limit to not work .

### ISSUE THREAD

**Issue by seloner** [strapi/strapi#9780]
## Bug report  

graphql amount limit causes limit to not work 

### Describe the bug

When you change the amountLimit to -1 then the limit option in the graphql queries does not work and returns all records

### Expected behavior

I would expect that you can use the limit option when the amount limit it set to -1 

### Screenshots

- Node.js version: 

- Strapi version: 
- Database: postgre
- Operating system: macos

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
