### ISSUE TITLE
Renaming a field with SQLite deletes the column and creates a new one

### ISSUE THREAD

**Issue by DirkHeinke** [strapi/strapi#9785]
### Describe the bug

When using Strapi with the SQLite database and renaming a field in the content types builder, a new column is added to the database but the old column is removed. When using MariaDB as database, the old column is still in the database.

This bug is not about that the column is not renamed, as I understand that schema migrations are not yet handled, it's about the deletion of data by renaming a field.

### Steps to reproduce the behavior

1. Create a *Restaurant*-Type as in the [quickstart guide](https://strapi.io/documentation/developer-docs/latest/getting-started/quick-start.html#_3-create-a-restaurant-content-type).
2. Add one restaurant
3. Change the `description` to `description2`.
4. Inspecting the database will show, that the column `description` is missing an `description2` is empty.

### Expected behavior

I would expect the SQLite database to have the same behaviour than the other databases and to follow the principle to not delete data by editing content types.

### System

- Node.js version: v15.11
- NPM version: 7.6.3
- Strapi version: 3.5.3
- Database: SQLite
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
Duplicate: #1114

**Comment by DirkHeinke** [comment]
Thanks @derrickmehaffy for the reference, but isn't in that topic said, that the old column should still be there?

With MariaDB I end up with two columns `description` and `description2` with SQLite the `description`column is gone. Is that correct?

**Comment by derrickmehaffy** [comment]
I would have to confirm but all migration issues are linked to that one. We don't plan on addressing them til Q3 unless it's a critical issue.

**Comment by DirkHeinke** [comment]
Alright thanks :)
