### ISSUE TITLE
Error shows "Email is already taken." while it username duplicates when using register API

### ISSUE THREAD

**Issue by velopert** [strapi/strapi#9787]
## Bug report

When using register API (/auth/local/register), username duplicate error results in "Email is already taken" error message.

### Describe the bug

This is caused because error message of username duplication does not contain the string "username".

https://github.com/strapi/strapi/blob/ba0637e26bed08b06e4c0e3654965370e71d3b21/packages/strapi-plugin-users-permissions/controllers/Auth.js#L514-L521

When I printed the error message of the error, it only shows: "Duplicate entry"

### Steps to reproduce the behavior

Register account using Auth API

1st request
```
POST http://localhost:1337/auth/local/register
{
    "username": "johndoe",
    "email": "johndoe@email.com",
    "password": "abcd1234"
}
```

2nd request
```
POST http://localhost:1337/auth/local/register
{
    "username": "johndoe",
    "email": "johndoe2@email.com",
    "password": "abcd1234"
}
```

Wrong error message:
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                }
            ]
        }
    ],
    "data": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                }
            ]
        }
    ]
}
```

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.15.0
- NPM version:6.13.4
- Strapi version: v3.5.3
- Database: SQLite
- Operating system: macOS

**Comment by ahmadkhudeish** [comment]
Error handling is really missed up on this endpoint

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/5479

@velopert can you change your PR issue target to #5479

**Comment by ChristherLenander** [comment]
This issue is still not fixed. Strapi version 3.6.8 community edition.

**Comment by ifkas** [comment]
> This issue is still not fixed. Strapi version 3.6.8 community edition.

I can confirm this too on the same version.

**Comment by derrickmehaffy** [comment]
see the duplicate issue, locking.
