### ISSUE TITLE
Service unavailble when trying to build static files

### ISSUE THREAD

**Issue by Zahroon** [strapi/strapi#9802]
## Bug report

Service unavailble when trying to build static files.

### Describe the bug

I have some problem with static build in Nuxt. When I push it on the server, some routes from Strapi give me a "Service unavailable" error. Is it possible to catch which routes gives an error and generate them until it makes static file? I would like to add that the site is huge and strapi has to build over 1000 pages.

### Expected behavior

Generate all static files.

### Screenshots

<img width="736" alt="Zrzut ekranu 2021-03-22 o 15 42 26" src="https://user-images.githubusercontent.com/19294314/112011524-a352d700-8b28-11eb-8bad-5465bc4d8aee.png">

### System

- Node.js version: 12
- NPM version: 6
- Strapi version: 3.3.4
- Database: Atlas MongoDB
- Operating system: MacOs Catalina 10.15.7

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
