### ISSUE TITLE
Content type's attributes marked as private are being exposed

### ISSUE THREAD

**Issue by ralphsomeday** [strapi/strapi#9804]
### Describe the bug

Content type's attributes marked as private are available in the Strapi exported GraphQL schema.

### Steps to reproduce the behavior

1. Go to Content type builder
2. Create a new content type with one attribute marked as private
3. Go to the graphql playground (http://localhost:1337/graphql) and click on the schema on the right hand side
4. See the private attribute in the graphql schema

### Expected behavior

The content type's attribute marked as private should not be available in the graphql schema in the graphql playground

### System

- Node.js version: v14
- Strapi version: 3.5.3

---

**Edited by** @derrickmehaffy

This is not just limited to GraphQL, per https://github.com/strapi/strapi/issues/10236

**Comment by ralphsomeday** [comment]
Found the bug in the GraphQL plugin, will submit a PR.

**Comment by ralphsomeday** [comment]
@derrickmehaffy let me know if you can reproduce. Thanks

**Comment by JuanGrauGGG** [comment]
**This is not a graphql only issue**, the same happens with dynamic zone's component attributes with "private" set to true.
When you retrieve the entity containing the dynamic zone though the REST API all the component's private attributes are leaked.

**Comment by ralphsomeday** [comment]
Apparently the private attribute works as designed which i would say if you mark things private they should not at all be exposed but how it is designed is that you remove the read function but create and update keeps the private fields so you can update them via the API and not only via the admin panel. This PR solves it for graphql you may need to check with @alexandrebodin for the REST API.
