### ISSUE TITLE
An error occurred during models config fetch

### ISSUE THREAD

**Issue by bigpreshy** [strapi/strapi#9811]
### Describe the bug

This happens when one adds a new API with just `strapi generate:api <name>` without attaching at least one attribute

### Steps to reproduce the behavior

1. Generate a new API with `strapi generate:api <name>` where <name> is the name of the api
2. Start your server go to your application in web
3. Try to add new new field to the collection <name>
4. See error _**An error occurred during models config fetch**_

### Expected behavior

It allow me to add attribute from the application

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by bigpreshy** [comment]
I have fixed this such that it makes you add at least one attribute when using strapi generate:api <name>.
This is my first time I want to contribute to this main strapi repo. That is why I am making this Issue. I will soon send a PR.

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
