### ISSUE TITLE
ParameterOptions.json to have equal parameter text rather than "="

### ISSUE THREAD

**Issue by simranjeet30691** [strapi/strapi#9814]
The parameteroptions.json file has the "name": "=", which should have certain text like  "name": "eq",
![image](https://user-images.githubusercontent.com/20557409/112125348-5551d800-8be9-11eb-8afc-def1f6b39e52.png)

This is creating syntax error when json gets converted into CSharp client via Nswag.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7219
