### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by Xanacas** [strapi/strapi#9815]
Hi There,
I'm very confused about the naming conventions and conversations.
Why does a content type named abcde_efgh_ijklm result in files called 'abcde-efgh-ijklm' ???
Which means - correct me if I'm wrong - I need to write the following: 
await strapi.services['abcde-efgh-ijklm'].find(ctx.query);
instead of 
await strapi.services.abcde_efgh_ijklm .find(ctx.query);
this not only looks very ugly, but also makes code completion much harder.

What did I miss? the only nice way I can see is using CamelCase rather than _?

Many thanks for explanations and recommendations

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
