### ISSUE TITLE
Delete with non-repeatable component 

### ISSUE THREAD

**Issue by ronny35** [strapi/strapi#9817]
### Describe the bug

I follow this [link](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#models) in order to delete a component.
Using curl, this example seems to work but, in MongoDB, the relation persists :
```
openinghours: [
        {
            _id: ObjectId('6053cfcc36a4a1002349e21f'),
            kind: 'ComponentRestaurant0peninghours',
            ref: ObjectId('5ff2428a8194c9c8708876d4')
        }
    ],
```

### Steps to reproduce the behavior

Following this [link](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#models)

### Expected behavior

The relation must be deleted from database.

### System

Docker :
- Strapi version: strapi/strapi:3.3.3-alpine
- Database: mongo:4.4.1-bionic

**Comment by derrickmehaffy** [comment]
shouldn't be an issue in v4
