### ISSUE TITLE
(bug): Deleting a field, doesn't drop the column in PostgreSQL

### ISSUE THREAD

**Issue by juanzgc** [strapi/strapi#9826]
## Bug report
Deleting fields from `User` deletes the field from Strapi `Content-Types Builder` but **does not** delete from the PG database. In the case that your field is a `required` field, this will cause errors at `Auth.connect`.

Only way to fix these errors is by ssh into PG database and dropping the columns that you _already_ had deleted within Strapi.

### Describe the bug

Strapi:`v3.5.3`
Database: PostgreSQL
Collection Type: `User (from: users-permissions)`

A `User` custom field (which was originally set as `required` is deleted (does not appear) in `Content-Types Builder` however, this field appears as a column when you ssh into `PostgreSQL`.

This causes an issue when you attempt to perform an `Auth.connect` when signing up a new user via a provider.

It will expect that user to have a custom field as it was set to be required, and therefore will  **not** authenticate that user.

### Steps to reproduce the behavior

1. Add a new **required** field, lets call it `stripe_id`
2. Save the field
3. Delete the field
4. Authenticate a new user via `Auth.connect` (to authenticate with a provider). In my case I am using auth0. At this point, you will notice a `400` status error in your client application. The detail will include: `Failing row contains (.....)` which is not descriptive. 

If you access `Content-Types Builder` -> `User` you will notice that `stripe_id` (the field we created and deleted earlier does not exist, which is expected). However, if you ssh into PostgreSQL, `stripe_id` will still be an existing column that is still required (NOT NULL). Which explains the errors we were receiving at authentication.

### Expected behavior

Expected behavior is if you delete a field in `Content-Types Builder` you expect it to delete the column in `PostgreSQL`.

### Screenshots

![image](https://user-images.githubusercontent.com/24414523/112313403-2e91b100-8c7e-11eb-8b32-e952a88edfb6.png)

### Code snippets

```
                                                                Table "public.users-permissions_user"
       Column       |           Type           | Collation | Nullable |                       Default                        | Storage  | Stats target | Description 
--------------------+--------------------------+-----------+----------+------------------------------------------------------+----------+--------------+-------------
 id                 | integer                  |           | not null | nextval('"users-permissions_user_id_seq"'::regclass) | plain    |              | 
 username           | character varying(255)   |           | not null |                                                      | extended |              | 
 email              | character varying(255)   |           | not null |                                                      | extended |              | 
 provider           | character varying(255)   |           |          |                                                      | extended |              | 
 password           | character varying(255)   |           |          |                                                      | extended |              | 
 resetPasswordToken | character varying(255)   |           |          |                                                      | extended |              | 
 confirmationToken  | character varying(255)   |           |          |                                                      | extended |              | 
 confirmed          | boolean                  |           |          |                                                      | plain    |              | 
 blocked            | boolean                  |           |          |                                                      | plain    |              | 
 role               | integer                  |           |          |                                                      | plain    |              | 
 created_by         | integer                  |           |          |                                                      | plain    |              | 
 updated_by         | integer                  |           |          |                                                      | plain    |              | 
 created_at         | timestamp with time zone |           |          | CURRENT_TIMESTAMP                                    | plain    |              | 
 updated_at         | timestamp with time zone |           |          | CURRENT_TIMESTAMP                                    | plain    |              | 
 stripe_id          | character varying(255)   |           | not null |                                                      | extended |              | 
Indexes:
    "users-permissions_user_pkey" PRIMARY KEY, btree (id)
    "users-permissions_user_username_unique" UNIQUE CONSTRAINT, btree (username)
    "users_permissions_user_stripe_id_unique" UNIQUE CONSTRAINT, btree (stripe_id)
```

### System

- Node.js version: `v14.16.0`
- NPM version: `v6.14.11`
- Strapi version: `v3.5.3`
- Database: `PostgreSQL`

**Comment by derrickmehaffy** [comment]
Duplicate: #1114
