### ISSUE TITLE
invalid input data, please verify unique constraints

### ISSUE THREAD

**Issue by josualoh** [strapi/strapi#9827]
### Describe the bug
When I throw an Error in a lifecycle method of an model, like `beforeUpdate`, the UI does not recognize the error message, it shows *invalid input data, please verify unique constraints* ...

### Steps to reproduce the behavior
1. Throw an Error inside a model lifecycle method, like `beforeUpdate` - `throw new Error('This message should show up in the toggled notification')`.

### Expected behavior
see above

### Additional info
"strapi": "3.5.3"

I used it in a previous project and it worked as expected ("strapi": "3.1.2"). The error message of the thrown error shows up in the notification.

**Comment by eriskhan** [comment]
You should use: 
`throw strapi.errors.badRequest('This message should show up in the toggled notification')`

**Comment by josualoh** [comment]
nice, thanks a lot! :)
