### ISSUE TITLE
Restart server after install plugin (GraphQL) from the admin panel

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#983]
**Informations**
- **Node.js version**: v9.10.0
- **npm version**: v5.8.0
- **Strapi version**: 3.0.0-alpha.12
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

From: https://github.com/strapi/strapi/issues/962:

After install a plugin from the admin panel (GraphQL for example), we have needed to restart the server to see the plugin installed in the Plugins section.

Also, in the Marketplace I still see the option to download:

<img width="345" alt="screen shot 2018-04-18 at 14 23 35" src="https://user-images.githubusercontent.com/1007051/38931626-18e84b86-4314-11e8-9858-257138a9125b.png">

**Steps to reproduce the problem**

Install a plugin from the admin panel.

**What is the expected behavior?**

Restart the server and show the installed plugin.

- ✅ I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
In fact it's all plugins that haven't front end code.

**Comment by soupette** [comment]
It's been fixed in #1732
