### ISSUE TITLE
Typescript compile error TS1046 raised while using module strapi-dabase

### ISSUE THREAD

**Issue by river0825** [strapi/strapi#9837]
## Bug report

Typescript compile error while using module strapi-dabase

### Describe the bug

An error is raised while I using module strapi-database with typescript compiler (tsc)

### Steps to reproduce the behavior

1. make a clean project using strapi
2. run script below
```shell
npm i strapi typescript

echo " 
import {DatabaseManager} from 'strapi-database';

interface Strapi {
    db: DatabaseManager;
}" > db.ts

./node_modules/.bin/tsc ./db.ts

```

### Expected behavior

No error should raised.

### Screenshots

<img width="549" alt="Screen Shot 2021-03-26 at 9 15 45 AM" src="https://user-images.githubusercontent.com/1509781/112563200-da203a00-8e13-11eb-9d96-a5c32db4d9ca.png">

### Code snippets

```typescript
import {DatabaseManager} from 'strapi-database';

interface Strapi {
    db: DatabaseManager;
}
```

### System

- Node.js version: v12.21.0
- NPM version: 6.14.11
- Strapi version: 3.5.4
- Database:
- Operating system: macOS 11.2.3
- Typescript: 4.2.3

**Comment by derrickmehaffy** [comment]
We don't currently support Typescript. Marking as closed.

**Comment by river0825** [comment]
If Typescript is not supported, why do you provide a definition file for Typescript which is a buggy one??
Although I've found a way to walk around the buggy definition file.
But still please fix or removing the definition file

**Comment by derrickmehaffy** [comment]
It was a "work in progress" example, our official stance at the moment is we don't support TS for now. We are looking at possibly adding it in the future.

**Comment by river0825** [comment]
Maybe we can move the "WIP" example to the example folder instead of the project root next time.
Although there is a walk around to the problem. 
But it still causes much time to investigate and resolve.
Thanks for your time.

**Comment by bradharms** [comment]
If I want to use TypeScript for my own project code, will the broken definitions in the strapi packages prevent me from doing that? Is there an easy way to tell typescript to ignore strapi typescript definitions?
