### ISSUE TITLE
[CLI] strapi generate:policy command leads to not find policy

### ISSUE THREAD

**Issue by nclsndr** [strapi/strapi#9844]
### Describe the bug

Command `strapi generate:policy myCustomPolicy` generates a file named `my-custom-policy.js`.
Following the [Policies docs](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#usage), we declare `"global::myCustomPolicy"` in routes config.
Starting the dev server:

```
debug ⛔️  Server wasn't able to start properly.
error Error creating endpoint get /website-pages: Could not find policy "myCustomPolicy"
```

**Note 1:** The content of the generated function is ok displaying 
```javascript
/**
 * `myCustomPolicy` policy.
 */

module.exports = async (ctx, next) => {
```

**Note 2:** Just renaming the file to correct custom policy name solves the issue.

### Steps to reproduce the behavior

1. `$ strapi generate:policy myCustomPolicy`
3. Declare policy in some routes
4. Start dev server

### Expected behavior

The filename is matching the chosen policy name.

### System

- Node.js version: 14.16
- NPM version: 6.14
- Strapi version: 3.3.2
- Database: PG
- Operating system: MacOS

### Additional context

My Strapi version is pretty old, maybe this is solved in next releases, but still wasn't able to find an issue about it.

**Comment by petersg83** [comment]
Hi ! Thanks for sharing this issue. If i'm not mistaken the doc will be updated soon by @pwizla so it uses kebab-case instead of camelCase

**Comment by pwizla** [comment]
Indeed! This [pull request for our documentation repo](https://github.com/strapi/documentation/pull/203) addresses it. I'm sorry you are having this issue. The documentation will be fixed next week.

**Comment by nclsndr** [comment]
Great! Thanks for the reference 👌

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
