### ISSUE TITLE
The link to the (latest) migration guide is broken

### ISSUE THREAD

**Issue by uchilaka** [strapi/strapi#9847]
### Describe the bug

A link to the migration guide from the release notes is broken. If this is a dynamically generated URL, then there's possibly something wrong with the logic that handles that for the latest release. 

### Steps to reproduce the behavior

1. Go to <https://github.com/strapi/strapi/releases/tag/v3.5.4> (currently tagged as the `latest` release)
2. Click on <https://strapi.io/documentation/v3.x/migration-guide>

![image](https://user-images.githubusercontent.com/2763396/112709038-57879100-8e8c-11eb-979e-477865f3af71.png)

### Expected behavior

Expected... a migration guide doc.

### Screenshots

> If applicable, add screenshots to help explain your problem.

Done

### Code snippets

> If applicable, add code samples to help explain your problem.
NA

### System

- Node.js version:  NA
- NPM version: NA
- Strapi version:  `3.5.4`
- Database: NA
- Operating system: macOS Big Sur `11.2.3`

### Additional context

> Add any other context about the problem here.
NA

**Comment by derrickmehaffy** [comment]
Fixed, however there is no migration guide for this release. You can find them here: https://strapi.io/documentation/developer-docs/latest/update-migration-guides/migration-guides.html
