### ISSUE TITLE
Controller couldn't access custom functions for GraphQL based requests 

### ISSUE THREAD

**Issue by shivagouraram** [strapi/strapi#9850]
### Describe the bug

I am trying to develop a custom controller, in which I would like to call a user defined function to perform some task and return the result so that I can use it within the action, however, when the action is being called with GraphQL mutation, it fails to access the custom function defined and throes exception

### Steps to reproduce the behavior

1) Create a new Collection
2) Modify the controller and add a custom create action
3) Define a function within the controller that performs some operation and returns data
4) Call the function created at step 3 from the create action
5) Develop a **GraphQL client** and call the create function with required parameters

### Expected behavior

Custom controller action should execute normally and create an entry to the collection.

### Screenshots

Strapi fails to identify the custom method that was defined within the same controller and fails to create an entry.

TypeError: Cannot read property '**updateMotherToungeSeq**' of undefined
    at create (W:\Projects\myjodi-strapi\api\user-profile\controllers\user-profile.js:28:47)
    at W:\Projects\myjodi-strapi\node_modules\strapi-plugin-graphql\services\resolvers-builder.js:50:26
### Code snippets

```
async updateMotherToungeSeq(motherTounge) {
    try {
      if (motherTounge) {
        const result = await strapi
          .query("mother-tounge")
          .model.findOneAndUpdate(
            { id: motherTounge },
            {
              $inc: {
                ProfileCounter: 1,
              },
            },
            { new: true }
          );

        return result.ShortCode + result.ProfileCounter;
      }

      /*return (
        updatedCounter.ShortCode.toUpperCase() + updatedCounter.ProfileCounter
      );*/
    } catch (err) {
      // Silent
      console.log(err);
      return 0;
    }
  },
  /**
   * Create a record.
   *
   * @return {Object}
   */

  async create(ctx) {
    let entity;
    try {
      console.log(ctx.request.body);
      //adding profile ID to the user profile
      ctx.request.body.ProfileID = await this.updateMotherToungeSeq(
        ctx.request.body.mother_tounge
      );
      entity = await strapi.services["user-profile"].create(ctx.request.body);

      return sanitizeEntity(entity, { model: strapi.models["user-profile"] });
    } catch (err) {
      // Silent
      console.log(err);
      return null;
    }
  }
```
### System

- Node.js version: v14.15.0
- NPM version: 6.15.8
- Strapi version: 3.5.4
- Database: Mongo
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
Can you please use markdown to clean up the code snippets? they are quite hard to read.

**Comment by kasonde** [comment]
@shivagouraram this is a confirmed issue with the graphql plugin. Right now, it seems when you perform a request, the plugin will call the controller function directly without preserving the context in which the function exists i.e the object exported by the controller file. 

A work-around I can recommend for this though is to take your custom function, `updateMotherTongueSeq`, and make it a service, i.e
```
"use strict";

/**
 * Read the documentation (https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#core-services)
 * to customize this service
 */

module.exports = {
  updateMotherTongueSeq: async (your_params) => {
    // do something with your params ideally
    return 1; // completely arbitrary return value. Adapt it to your usecase.
  },
};
```
You should then be able to access the service in your `create` function like `let returnValue = await strapi.services.<api_name>.updateMotherTongueSeq(your_params)`

More info on services can be found [here](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#services) 😃

**Comment by shivagouraram** [comment]
Thanks @kasonde - I have currently included the function code within the create function but your approach looks more cleaner. Thanks for the workaround.

**Comment by derrickmehaffy** [comment]
Alternatively also you can use the global functions: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#functions

**Comment by derrickmehaffy** [comment]
should be fixed in v4
