### ISSUE TITLE
Editor uses * for italic which breaks inside ** block

### ISSUE THREAD

**Issue by flipswitchingmonkey** [strapi/strapi#9851]
### Describe the bug

Markdown Editor marks a bold block with ** and an italic block with * instead of _. An italic bold text thus does not work, as you can't use asterisks for marking italic inside a bold block. It does however work with underscores. So I think the editor's default behaviour for italic should be _

### Steps to reproduce the behavior

Edit a text field, mark some text, click on bold. Mark some text inside the bold text and click on Italic. Note it not working but rather display the single asterisks

### Expected behavior

Shold show bold italic text

### System

- Node.js version: 14
- NPM version:
- Strapi version: 3.5.4
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
Tested on v3.5.4 using manual formatting and the WYSIWYG buttons:

![image](https://user-images.githubusercontent.com/8593673/112900750-b9b4e180-9098-11eb-9817-aa4f4043b926.png)

![image](https://user-images.githubusercontent.com/8593673/112900777-c33e4980-9098-11eb-8817-9790186e8e6b.png)

Marking as closed unless additional debug and reproduction steps can be provided.
