### ISSUE TITLE
Management Commands / Tasks

### ISSUE THREAD

**Issue by budlight** [strapi/strapi#9860]
It seems like at least one goal for this project is to provide a Node / javascript alternative to projects that use Rails or Django as backend + api only correct?

Why is how to make a management command / task so sparsely documented?  

The best I can find is right here 
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#functions

The cron work is excellent and imo solves a lot of the use case for commands like these, but there will still be a need for one off commands to generate dumps/exports/experimentation/stats/.  Kind of shocking this isn't already here to me because for django and rails unit testing builds up from commands such as these.  

examples for rails and django:
https://guides.rubyonrails.org/v4.2/command_line.html#custom-rake-tasks
https://docs.djangoproject.com/en/3.1/howto/custom-management-commands/

Maybe there is already something here, and just not documented well?

**Comment by alexandrebodin** [comment]
Hi it is not yet available but we want to make this available for sure :) I'll mark this as a feature request for our Product managers ;)

**Comment by derrickmehaffy** [comment]
Would largely be better implemented in a community plugin so unlikely we would bake that into the core. Going to set as closed for now.
