### ISSUE TITLE
Admin initial setup error

### ISSUE THREAD

**Issue by noid2** [strapi/strapi#987]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**:9.11.1
- **npm version**:5.6
- **Strapi version**:3 a12
- **Database**: mongoDB
- **Operating system**: Linux

**What is the current behavior?**

**Steps to reproduce the problem**
after install I changed the port (/config/environments/development/server.json) to 8080 (I can only use this port).  The main page is displayed but  the /Admin show the error 
![strapi issue](https://user-images.githubusercontent.com/33399557/39055457-9428e8e0-44b4-11e8-98c0-e93ccc9312fc.png)

**What is the expected behavior?**

**Suggested solutions**

---

*FEATURE REQUEST TEMPLATE*  

**What is the expected behavior?**

---

- [ ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @noid2 did you follow https://strapi.io/documentation/guides/deployment.html ?
