### ISSUE TITLE
At new role creation linked role user can't access to data

### ISSUE THREAD

**Issue by pierredarrieutort** [strapi/strapi#9876]
### Describe the bug

At new role creation linked role user can't access to data created before role creation

### Steps to reproduce the behavior

**Example :**
I'm connected as "Super Admin" role and have a collection "Language" with data :
![image](https://user-images.githubusercontent.com/25182438/112959818-1ae5bf00-9144-11eb-91a7-e35a521ffaad.png)

I create a new role with only right to see "Language" collection  :
![image](https://user-images.githubusercontent.com/25182438/112960250-83cd3700-9144-11eb-8da9-d3f814c23510.png)

A user with this role can't see the existing data :
![image](https://user-images.githubusercontent.com/25182438/112960398-a95a4080-9144-11eb-9b19-3095cc20e6d2.png)

Btw, when I refresh the page after create a new role, parameters are auto-set, and I' think the problem could be here but I'm unable to edit these properties :
![image](https://user-images.githubusercontent.com/25182438/112961103-58971780-9145-11eb-9e34-4f895482fdbd.png)

### Expected behavior

A user linked to a new role can access to data created before his account / role creation

OR

Enhance documentation / UI to make understable the encounted issue

### System

![image](https://user-images.githubusercontent.com/25182438/112961796-fdb1f000-9145-11eb-911c-34eddd05f151.png)

**Comment by derrickmehaffy** [comment]
This feature (Specifically [RBAC Conditionals](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#role-based-access-control) ) is limited for the community edition, to have control over the conditions you will need to purchase an EE license or if your project is open-source / non-profit / you are a student you can apply for a free enterprise edition here: 

EE License: https://strapi.io/pricing-self-hosted
Free EE: https://strapi.io/free-enterprise-edition
