### ISSUE TITLE
Relationships not returning file upload data

### ISSUE THREAD

**Issue by ChristopherJohnson25** [strapi/strapi#988]
**Informations**
- **Node.js version**: v9.9.0
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.11.3
- **Database**: Mongo
- **Operating system**: Docker

**What is the current behavior?**
Currently when adding a relation to a model, the relationship's s3 image is responding as null. 

See image of JSON response ('logo' should have all the typical file fields, instead comes back as 'null')...

<img width="446" alt="screen shot 2018-04-20 at 10 07 47 am" src="https://user-images.githubusercontent.com/15021119/39055628-bedc6940-4482-11e8-8530-d4d68848cc38.png">

**Steps to reproduce the problem**
Use s3 plugin. Create content model, add relationship to another content model with file upload on it. Check JSON.

**What is the expected behavior?**
Relations should return all data as normal. 

**Suggested solutions**
Unsure.

- [ x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @ChristopherJohnson25, It's because by default we are not deep populate data.

Please check this issue : https://github.com/strapi/strapi/issues/877

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
