### ISSUE TITLE
Policies are ignored, controller function called regardless graphql

### ISSUE THREAD

**Issue by viocost** [strapi/strapi#9882]
### Describe the bug

Policies are ignored and controller function called regardless of policy calling next() or not.

I observe this behavior using custom policies, custom controller and graphql playground

### Steps to reproduce the behavior

1. Create any entity
2. Create custom graphql schema, 
3. Create custom controller function for the entity
4. Create one or more policies according to the main documentation.
5. Trigger mutation using graphql playground.
6. Observe that regardless of policies calling next() or not, controller function is still is called

### Expected behavior
I expect controller function to not be called if at least one of defined policies fails to call next()

#### Schema
app/api/workout/config/schema.graphql.js
```
module.exports = {

    mutation: `
    cancelWorkout(id: ID): Workout!
    joinWorkout(id: ID): Workout!

`,
    resolver: {
        Mutation: {
            createWorkout: {
                resolver: 'application::workout.workout.createWorkout',
                policies: [
                      'application::workout.isCategoryValid'
                ]
            },

        }
    }

}
```

#### Custom controller
app/api/workout/controllers/workout.js
```
module.exports = {
    async createWorkout(ctx) {
          console.log("Just hit custom create workout controller");
    },
};
```

#### Policy
app/api/workout/config/policies/isCategoryValid.js

```
module.exports = async (ctx, next) => {
    console.log("Is category valid called");

    let { category } = (ctx.request.body)
    let found = await strapi.query('category').find({ id: 555 }) // category with id 555 does not exist, so next() never called

    if (found.length > 0) {
        // Go to next policy or will reach the controller's action.
        console.log("Category is valid. Continuing");
        return await next();
    }

    console.log("Category not found!");
    ctx.badRequest("Invalid category")

};
```

### System

- Node.js version: 12.20.01
- NPM version: 6.14.10
- Strapi version: 3.5.3
- Database: postgres
- Operating system: linux

### Additional context
Using official strapi docker image

### Edit 1:
I thought the issue was that I haven't added resolverOf property in schema.graphql.js, but I observe the same behavior after adding it. So the policy is executed and fails, but controller function is still called

### Edit 2:
The only way to stop policies from propagating is to throw an error, or use ctx.throw function, but the return status then becomes 
INTERNAL_SERVER_ERROR regardless of status code set before.

**Comment by viocost** [comment]
My bad. I've just realized I haven't added resolverOf property for the Mutation in shcema.graphql.js.

**Comment by derrickmehaffy** [comment]
> `ctx.badRequest("Invalid category")`

Please try changing this to `return ctx.badRequest("Invalid category")`

**Comment by viocost** [comment]
I looked at the source code, in file packages/strapi-plugin-graphql/services/resolvers-builder.js there is a buildMutation function,
in particular this snippet:
```

  // custom resolvers
  if (_.isFunction(resolver)) {
    return async (root, options = {}, graphqlContext, info) => {
      const ctx = buildMutationContext({ options, graphqlContext });

      await policiesMiddleware(ctx);
      graphqlContext.context = ctx;

      return resolver(root, options, graphqlContext, info);
    };
  }

```

It seems to me that await policiesMiddleware always resolves unless something thrown and resolver is always called

**Comment by pedrosimao** [comment]
@viocost did you find an alternative solution for yourself?

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
