### ISSUE TITLE
Collection Types created with numbers in the display name break the collection api calls

### ISSUE THREAD

**Issue by jgambarios** [strapi/strapi#9896]
## Bug report

Creating a new Collection Type with a number on the Display Name, like **"Test1"** breaks the endpoints where the collection names are required, like `http://localhost:1337/test1s/1` or `http://localhost:1337/test1s` returning 404s.

### Steps to reproduce the behavior

1. Go to Content-Types Builder
2. Create a new Collection Type using Display Name **"Test1"** and click continue.
3. Add any field to the Collection type, a Text field is enough for the test.
4. Save the new Collection type.
5. Go to Collection Types and add a content of type **Test1**.
6. Use for example `http://localhost:1337/content-type-builder/content-types/application::test1.test1` to get the `collectionName` of the Collection Type (from the UI is it also possible to get the Collection name).
6. Try to use the collections API to return information for that Content or Collection type.
```
GET http://localhost:1337/test1s/1

HTTP/1.1 404 Not Found
Vary: Origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Powered-By: Strapi <strapi.io>
X-Response-Time: 28ms
Content-Type: text/plain; charset=utf-8
Content-Length: 9
Date: Tue, 30 Mar 2021 16:26:55 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Not Found

Response code: 404 (Not Found); Time: 80ms; Content length: 9 bytes
```

```
GET http://localhost:1337/test1s

HTTP/1.1 404 Not Found
Vary: Origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Powered-By: Strapi <strapi.io>
X-Response-Time: 25ms
Content-Type: text/plain; charset=utf-8
Content-Length: 9
Date: Tue, 30 Mar 2021 16:28:55 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Not Found

Response code: 404 (Not Found); Time: 76ms; Content length: 9 bytes
```

### Expected behavior

I should be able to use the Collections API (sorry if it is not the proper name for those set of calls) as I'm able to use other endpoints like `http://localhost:1337/content-type-builder/content-types/application::test1.test1`, `http://localhost:1337/content-manager/collection-types/application::test1.test1`, `http://localhost:1337/content-manager/collection-types/application::test1.test1?id=1`, etc, all those queries work as expected except for the queries where I need to use the collection name.

### System

- Node.js version: v14.15.2
- Strapi version: v3.4.0

### Additional context

When creating a Collection type without a number, like **"Test"** everything works as expected. 
It is also worth mentioning that if I change the Collection name of an existing Collection type let's say from **"demo"** to **"demo1s"** I will be able to reproduce the issue where the Collections API returns 404s and if I change back the Collection name from **"demo1s"** to **"demo"** looks like it fixes the problem for this case **BUT** if from the beginning I created the Collection type with a number even if I change the Collection name I won't be able to recover from this behavior and use the Collections API.

**Comment by akhilmhdh** [comment]
@derrickmehaffy  @soupette 

I have gone through this. And here is more detailed one.

Two Scenerios:

1. Create a collection type with name **test1** ( or whatever a mix of numerical and alphabet)

In these situations the path is actually **/test-1-s** and not **/test1s**. I think this got be something wrong with pluralise case.

2. Create a collection type with name **test** and then rename to **test1**

It doesn't rename the path. We have to delete the collection to change the path. Also its application for above case.

I would love to work on this. If its ok please assign it to me.

**Comment by derrickmehaffy** [comment]
> I would love to work on this. If its ok please assign it to me.

Please do feel free to try, but I would suggest submitting an [RFC](https://github.com/strapi/rfcs) first on how you plan to fix these as we are basically waiting for the v4 to see if we will have time to remove pluralize which would solve issue one.

Issue 2 isn't really an issue per-say it's a structural choice so I'm not sure if there is anything to "fix" here.

**Comment by akhilmhdh** [comment]
@derrickmehaffy  Yah ok. 

But on second one. Don't you think it should change the url on rename, instead of deleting the whole collection builder for a route change.

**Comment by akhilmhdh** [comment]
@derrickmehaffy @soupette 

Sorry to bother u guys.
But here is the issue

Filename: `packages/strapi-generate-api/lib/before.js`

Code:
```
  _.defaults(scope, {
    name,
    route:
      scope.contentTypeKind === 'singleType'
        ? _.kebabCase(scope.id)
        : _.kebabCase(pluralize(scope.id)),
  });
```

The kebab case converter with pluralise convert lines like book1 -> book1s (pluralise) -> book-1-s (kebabCase)

Is this behavoir expected. So the routes will be book-1-s and  not book1s. I am assuming a kebaCase converter was applied to make spaces and also to make it one work.

Another option is to just apply a lodash.replace the spaces with - to avoid this. Any suggestions?

**Comment by derrickmehaffy** [comment]
@akhilmhdh sorry for the late reply. I would suggest holding off on attempting to fix this right now as we plan to massively change the model structure in our v4 development that we are starting on this week and will last until likely the end of the summer.

**Comment by akhilmhdh** [comment]
@derrickmehaffy Yah i thought so. After the teaser,I knew that you guys will be concentrating on making v4 awesome. 
Its completely understandable. 😃

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Yah i thought so. After the teaser,I knew that you guys will be concentrating on making v4 awesome. 
> Its completely understandable. 😃 

Thank you though for offering your help, and by all means if you wish to help out on other topics please do speak up on those issues.

**Comment by akhilmhdh** [comment]
I was actually kinda pulling myself, because felt may be these issues were actually planned to solve in coming updates.
But definitely now I'll work on putting like these issue details, if in future u want a good reference or may be put a PR by myself. 😆

**Comment by derrickmehaffy** [comment]
shouldn't be a problem in v4, marking as closed
