### ISSUE TITLE
Redirect to Login after successful login for admin page

### ISSUE THREAD

**Issue by manishsg** [strapi/strapi#990]
*BUG TEMPLATE* 

Node - v9.11.1
npm 5.6.0
strapi 3.0.0
Database - MySQL - mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) 
OS - Ubuntu - 4.13.0-1012

**What is the current behavior?**
After successful login it redirect back to login page for admin user.

**Steps to reproduce the problem**

**What is the expected behavior?**
It should go to the admin panel.
It used to work fine. created a api also.
**Suggested solutions**

---

**Comment by lauriejim** [comment]
Hello @manishsg can you specify the alpha version of Strapi you use.

Can you try to login with postman (https://strapi.io/documentation/guides/authentication.html#login) and tell me if it works.

**Comment by manishsg** [comment]
3.0.0-alpha.11.3

I had to re-create the api (deleted the old one) and its working fine.

Regards

**Comment by manishsg** [comment]
It happens after creating the first api - content. 

I am able to reproduce the issue.

Still haven't created the back end table for the api

**Comment by manishsg** [comment]
It pop's up an error message - error occurred while gaconfig.js and redirects back

**Comment by manishsg** [comment]
MongoDB back end works fine. Seems to be issue with MYSQL DB back end.

**Comment by lauriejim** [comment]
You create content type with the dashboard ? after restart you get an error ?
Did you manually create your table ?

I think you are with the same interrogation as https://github.com/strapi/strapi/issues/994

**Comment by manishsg** [comment]
What's the script to create the table in MySQL

**Comment by manishsg** [comment]
In case of relationship how do we specify that in the table creation.

**Comment by lauriejim** [comment]
You have to run SQL query as logged when you start your server for the first time to create plugins tables.
And you need relation table only for manyToMany relation.

But I recommend you to use MongoDB if you can, SQL experience will be release increase when this PR will merged and publish on npm https://github.com/strapi/strapi/pull/1025
