### ISSUE TITLE
Implement Strapi side Database index creation

### ISSUE THREAD

**Issue by creazy231** [strapi/strapi#9913]
### Describe the bug
I have a MySQL Database with a results table to store requests data. When I want to query for results where `success = false` it takes ~15 seconds to load 2 results for example.

### Steps to reproduce the behavior

1. Create a Table with ~5 million rows
2. `SELECT * FROM <table> WHERE success = false LIMIT 100;`

### Expected behavior
Faster response.

### Screenshots
![image](https://user-images.githubusercontent.com/13473174/113131864-0675f500-921e-11eb-8c60-60dc698c38a5.png)

### System

- Node.js version: v14.16.0
- NPM version: 6.14.11
- Strapi version: v3.5.3
- Database: MySQL
- Operating system: Debian with 3x vCPU, 4GB RAM

**Comment by alexandrebodin** [comment]
Hi @creazy231 We can't do anything about any database performances per say :) here you need to create indexes in your DB to  improve the performances. This is something we will want to support in strapi mid term but in the meantime it is fairly easy to add on your own :)

**Comment by creazy231** [comment]
> Hi @creazy231 We can't do anything about any database performances per say :) here you need to create indexes in your DB to improve the performances. This is something we will want to support in strapi mid term but in the meantime it is fairly easy to add on your own :)

Thanks for the fast reply. Could you give me an example on how to do so? I'm not an expert on mysql and has been some time I actively worked with it without using strapi or laravel etc. 
Would be awesome 🤩

**Comment by creazy231** [comment]
Current structure is:

![image](https://user-images.githubusercontent.com/13473174/113139939-0a0e7980-9228-11eb-8f1b-871cc2184b3f.png)

**Comment by alexandrebodin** [comment]
here is an example of what you can do 

```js
// in ./config/functions/bootstrap.js

module.exports = () => {
  const knex = strapi.connections.default;
  knex.schema.alterTable('tableName', async t => {

    // you might need to check the index existence first
    
   // single column indexes
    t.index('columnName', 'index_name');
    // for multi column indexes
     t.index(['colA', 'colB'], 'index_name')
  })
}
```

**Comment by creazy231** [comment]
Wow. Didn't expect such a huge change. From ~15.000ms to ~35ms
Thanks a lot @alexandrebodin <3

**Comment by andreich-tut** [comment]
> here is an example of what you can do in strapi directly. Else you can do it outside of strapi completly
> 
> ```js
> // in ./config/functions/bootstrap.js
> 
> module.exports = () => {
>   const knex = strapi.connections.default;
>   await knex.schema.alterTable('tableName', async t => {
> 
>     // you might need to check the index existence first
>     
>    // single column indexes
>     t.index('columnName', 'index_name');
>     // for multi column indexes
>      t.index(['colA', 'colB'], 'index_name')
>   })
> }
> ```

Looks like this solution works. Thank you! Do you know why this might not work in a migration?

**Comment by derrickmehaffy** [comment]
> > here is an example of what you can do in strapi directly. Else you can do it outside of strapi completly
> > ```js
> > // in ./config/functions/bootstrap.js
> > 
> > module.exports = () => {
> >   const knex = strapi.connections.default;
> >   await knex.schema.alterTable('tableName', async t => {
> > 
> >     // you might need to check the index existence first
> >     
> >    // single column indexes
> >     t.index('columnName', 'index_name');
> >     // for multi column indexes
> >      t.index(['colA', 'colB'], 'index_name')
> >   })
> > }
> > ```
> 
> Looks like this solution works. Thank you! Do you know why this might not work in a migration?

Likely because our DB sanitization is removing the index which the bootstrap fires after and basically recreates the index on every reboot of the app. Certainly not ideal and something we want to solve.

**Comment by derrickmehaffy** [comment]
https://feedback.strapi.io/developer-experience/p/ability-to-define-custom-indexes-in-the-schema
