### ISSUE TITLE
Cannot login with mongo dump data

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#9917]
### Describe the bug

I cannot log into the dev environment, after dumping data from live mongo db.
It was working fine before the last update.
Deleting the db data lets me register a new admin user and login works.

### Steps to reproduce the behavior

1. Set up live mongodb
2. mongo mongodump --uri ...
3. mongo mongorestore  ...
4. Try to login locally

### Expected behavior

Login works.

### System

- Node.js version: v14.15.3 (v12 seems not to be standard as of my build)
- NPM version: 6.14.11
- Strapi version: 3.5.4
- Database: mongo
- Operating system: fedora 33

### Additional context

I upgraded live to have the same package versions as local
Could be somehow related to this: https://github.com/strapi/strapi/issues/3523 (last comment)

package.json
```json
{
  "name": "app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@google-cloud/storage": "^5.8.3",
    "axios": "^0.21.1",
    "pdf-lib": "^1.16.0",
    "pdfmake": "^0.1.69",
    "pipedrive": "^10.4.3",
    "strapi": "^3.5.3",
    "strapi-admin": "^3.5.3",
    "strapi-connector-mongoose": "^3.5.3",
    "strapi-plugin-content-manager": "^3.5.3",
    "strapi-plugin-content-type-builder": "^3.5.3",
    "strapi-plugin-email": "^3.5.3",
    "strapi-plugin-graphql": "^3.5.3",
    "strapi-plugin-upload": "^3.5.3",
    "strapi-plugin-users-permissions": "^3.5.3",
    "strapi-provider-upload-google-cloud-storage": "^3.4.6",
    "strapi-utils": "^3.5.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "42b22690-b5f0-40fb-be60-455509623cf1"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by derrickmehaffy** [comment]
Mongo imports are outside the scope of Strapi itself, please open a thread on our forum: https://forum.strapi.io and try to provide some additional information. 


I would suggest comparing your data dump to that of fresh project.

**Comment by tw1t611** [comment]
@derrickmehaffy Please open the issue again. The dump is identical. I really think, there is a problem with strapi login.
Furthermore I can query data and execute custom resolvers fine.

**Comment by derrickmehaffy** [comment]
> As I said, it was working before the last update. So could you at least ask around, if anything changed to the login process, or the admin plugin lately?

What was your previous version?

To reopen I need more complete steps to reproduce, I created 8 different Strapi applications running back 8 Strapi versions and attempted the update with an export/import and could not reproduce the issue.

**Comment by tw1t611** [comment]
I am so sorry. It was my fault. You can leave the ticket closed.
If someone else comes across a similar problem, there is a workaround.
Add this to the mongorestore command: `--excludeCollection strapi_administrator` (or any other collection name)

**Comment by krisstern** [comment]
Hi, I tried the fix with `--excludeCollection strapi_administrator` for the `mongorestore` command but to no avail. We have just migrated all data from an old MongoDB database to a new one. Is there any other way to attempt a patch?

**Comment by krisstern** [comment]
Turns out I was able to fix the problem by having an empty `strapi_administrator` collection in our `mongodb` database. So it is a non-issue after all.
