### ISSUE TITLE
SSO - /admin/auth/login/success spins forever after OAuth callback

### ISSUE THREAD

**Issue by tyler8691** [strapi/strapi#9919]
## Description

We're using the [passport-oauth2](https://github.com/jaredhanson/passport-oauth2) provider with our enterprise Strapi installation. As part of this, our IdP has a portal that allows users to link directly into Strapi, triggering the OAuth flow via the `/admin/connect/oauth2` path.

We're seeing that the OAuth flow succeeds, but when returning to Admin tool the page spins and does not load the Admin home page.

- Triggering the flow directly from the Strapi login page works fine. It only happens when triggering the flow by going directly to the `/admin/connect/oauth2` URL from our SSO portal.
- Reloading the page (`/admin/auth/login/success`) does not solve the issue.
- Visiting the `/admin` page after this happens allows users to proceed into the CMS and use it without any issues. So the users are authenticated, it's just the Admin page is not "finishing" the authentication process and resolving to the home page.

## Steps to Reproduce

1. Connect Strapi to an OAuth provider via Enterprise SSO: https://strapi.io/documentation/user-docs/latest/settings/managing-global-settings.html#configuring-single-sign-on
   - Specify the custom provider in the `server.js` via `admin.auth.providers`
1. Launch the OAuth flow directly by loading the URL: https://mystrapidomain.com/admin/connect/oauth2

**Expected:** After the OAuth flow succeeds, the Admin home page loads.
**Actual:** The Admin page loads but gets stuck on the full-page spinner.

## Context

Here's what our provider configuration looks like:

```
const OAuth2Strategy = require('passport-oauth2').Strategy;
const provider = {
  uid: 'oauth2',
  displayName: 'SSO Credentials',
  createStrategy: strapi => new OAuth2Strategy({
    authorizationURL: `https://${process.env.PING_HOST}/as/authorization.oauth2`,
    tokenURL: `https://${process.env.PING_HOST}/as/token.oauth2`,
    clientID: process.env.PING_CLIENT_ID,
    callbackURL: strapi.admin.services.passport.getStrategyCallbackURL('oauth2'),
    clientSecret: process.env.PING_CLIENT_SECRET
  }, processToken)
};
```

Here's a screenshot of the issue including the network calls that are made:

![Screen Shot 2021-03-31 at 10 39 44 AM](https://user-images.githubusercontent.com/3145469/113162562-6912c500-920d-11eb-8beb-fc72c2ff987d.png)

1. Our SSO tool redirects to the application.
   - Example: `https://dsw-cms.dswincq.corp/admin/connect/oauth2?code=TgjAIAfBTwX0WaNkuViU527C0w5PbzlQuVUAAAEu`
1. Strapi redirects to the admin success page.
   - Example: `https://dsw-cms.dswincq.corp/admin/auth/login/success`
1. The Admin success page loads with HTTP 200, and loads in some Javascript, but the spinner stays forever.

There are no messages in the Console logs when this happens. I have tried removing the spinner element and there is nothing beneath it.

Let me know if I can provide any more context on this issue!

**Comment by derrickmehaffy** [comment]
Hi @tyler8691 can you expand on a few points:

- What is the software or service your OAuth2 passport provider is connecting to (if this not restricted information)
- Are the users created within the Admin panel if you login from an account that isn't managed via SSO (Initial super admin user)

**Comment by derrickmehaffy** [comment]
Also if possible can you please confirm the following information:

```
### System

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

**Comment by Convly** [comment]
@derrickmehaffy @tyler8691 
Hello :wave:
A fix has been developed, the related PR has been linked right above.
