### ISSUE TITLE
Language selector not visible

### ISSUE THREAD

**Issue by intoku** [strapi/strapi#992]
latest strapi

**Informations**

**What is the current behavior?**
When browser is german, the admin of strapi is automatically german (Even if specifically defined in the config to be english). The usual dropdown language selector is not visible in this case. There is no way to switch the language

**Steps to reproduce the problem**

**What is the expected behavior?**
The language dropdown should be visible.

**Suggested solutions**
I changed the chrome language settings to english, than the select field for languages appeared. Possibly something with the autodetect

----

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @intoku thank you for this issue.
Actually it's some `css` update to fix the position on the language selector when `Powered by` translation is to long.

Will appreciate your contribution on this issue !
