### ISSUE TITLE
Created automatically MySQL tables and columns

### ISSUE THREAD

**Issue by alexandrecanuto** [strapi/strapi#994]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**: v9.11.1
- **npm version**: v5.6.0
- **Strapi version**: v3.0.0-alpha.12.0.1
- **Database**: MySQL
- **Operating system**: macOS Sierra

**What is the current behavior?**
Content Type tables and fields are not created. Message *Make sure to create table `project` in your database* is shown.

**Steps to reproduce the problem**
Follow quick start guide available at http://strapi.io.
Don't know if it helps but during installation all tables had to be created manually as well, per instructions provided via Terminal each time I ran `strapi start`.

**What is the expected behavior?**
I was under the impression that tables and fields would be created using the admin.

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by dzuncoi** [comment]
I had the same problem with Mongodb database, v3.0.0-alpha.12.0.1

**What is the current behavior?**
I created a Article type in Content-type Builder and added some fields, but when I click on Article on left menu, it shows "There are no fields yet Add your first field to your Content Type".
This bug doesn't happen in the previous version.

**Comment by manishsg** [comment]
I had to manually run the scripts on MYSQL

**Comment by alexandrecanuto** [comment]
@dzuncoi Previous as in v12.0.0 or v11.x? Might test it here.

**Comment by kamalbennani** [comment]
I have the exact same problem as @dzuncoi

**Comment by alexandrecanuto** [comment]
Thanks for the info, @dzuncoi !

In my case, with MySQL, it happens when running both `strapi start` and `npm start`.

I might downgrade strapi to `v11.x` for the time being while this issue is investigated.

**Comment by alexandrecanuto** [comment]
@lauriejim Thanks for the info and thanks for adding it as a new feature! Based on the Quick Start tutorial video, I was under the impression that tables and fields were created automatically. Probably because it's based on a MongoDB installation and there's no need to create tables.

**Comment by lauriejim** [comment]
It's actually doesn't exist. Working on it https://github.com/strapi/strapi/tree/sql-xp

**Comment by lauriejim** [comment]
It's have been release in alpha.12.1.2
