### ISSUE TITLE
If I create a user with the same Username I have the bad error

### ISSUE THREAD

**Issue by Giildo** [strapi/strapi#9948]
### Describe the bug

If I create two users with the same Username, I have the error `Auth.form.error.email.taken` but not the error `Auth.form.error.username.taken`.

### Steps to reproduce the behavior

I would like to create a new user with the URL : `https://www.domaine.fr/auth/local/register`.
If I create a new user with the values : 
```json
{
    "email": "jmarco@jojotique.fr",
    "username": "JaneDoe",
    "password": "password"
}
```
...it's OK.
After, I tried with the same values and the API returns the error `Auth.form.error.email.taken`, it's OK, but if I tried with these values : 
```json
{
    "email": "giildo@jojotique.fr",
    "username": "JaneDoe",
    "password": "password"
}
```
... I have not the error `Auth.form.error.username.taken` I have again the error `Auth.form.error.email.taken`, but it's not the same email and I only have the user created before.

### Screenshots

![Capture d’écran de 2021-04-03 18-13-11](https://user-images.githubusercontent.com/34237011/113484396-62ec4500-94a8-11eb-9165-b845551bcf0f.png)
![Capture d’écran de 2021-04-03 18-13-36](https://user-images.githubusercontent.com/34237011/113484398-641d7200-94a8-11eb-89cd-56625741212e.png)

### System

- Node.js version: 14.15.5
- NPM version: 7.6.3
- Yarn version: 1.22.5
- Strapi version: 3.5.4
- Database: PostgreSQL
- Operating system: Linux / Debian 10

**Comment by Giildo** [comment]
The error is in the file `node_modules/strapi-plugin-users-permissions/controllers/Auth.js` : 
![Capture d’écran de 2021-04-04 09-34-55](https://user-images.githubusercontent.com/34237011/113501906-13019280-9529-11eb-8e91-329740bb66e8.png)

In the line : 
```javascript
const adminError = _.includes(err.message, 'username')
```
The error returned by `err.message` is `Duplicate entry` : 
![Capture d’écran de 2021-04-04 09-37-15](https://user-images.githubusercontent.com/34237011/113501962-6378f000-9529-11eb-893d-e361c9ad08d0.png)
(It's the result for: `console.log('error : ', err.message)`)

**Comment by derrickmehaffy** [comment]
> I would like to create a new user with the URL : https://www.domaine.fr/auth/local/register.

If you already have an Admin user, new admins cannot register, the only exception to this is the SSO in our Gold EE plan.

New admins have to be created through the Admin Panel or the Internal API. (Though the error message is wrong)

**Comment by Giildo** [comment]
Is not for create a admin user, it's for create a new user in the `users-permissions_user` table to use the JWT system to protect some APIs. The URL: https://www.domaine.fr/auth/local/register, is not the good URL to create this type of user ?

**Comment by derrickmehaffy** [comment]
Sorry I missread the issue based on that line `adminError`.

You are correct on that route for registering new end users.

**Comment by akhilmhdh** [comment]
Issue in detail:

Filename : `node_modules/strapi-plugin-users-permissions/controllers/Auth.js`

![image](https://user-images.githubusercontent.com/31166322/114382279-d3cae580-9ba9-11eb-88e3-aad1f6c7415f.png)


Line 491: which is inside a try statement throws an error Duplicate Entry from

```
When in sql: packages/strapi-connector-bookshelf/lib/utils/errors.js

When in nosql/mongodb : packages/strapi-connector-mongoose/lib/utils/errors.js
```
This will go to catch statement and as catch is just an if else check it always fires second one that is email already taken. 
Any suggestion from core team to fix this. I would love to attach a PR. 

One way to solve is modify the duplicate error by throwing a particular string denoting duplicate field. Then check if that key exist as in string.

**Comment by wfpaisa** [comment]
yes, i spent a long time figuring out the problem :cry: if a user selects the first day to log in via google and the second day via facebook the auth will not allow

**Comment by alexandrebodin** [comment]
We completely refactored that part of the code and now the error is managed correctly :)
