### ISSUE TITLE
i18n plugin

### ISSUE THREAD

**Issue by cipriancaba** [strapi/strapi#9950]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Creating this issue to track the upcoming i18n plugin beta release. Been seeing on multiple channels the upcoming release and want to give people a way to be notified by this release. 

Initial ETA was end of this week, was wondering if you could share any updates over that.

Much appreciated

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
https://forum.strapi.io/t/content-internationalization-i18n-beta-is-live/3892/5
