### ISSUE TITLE
GCP postgres deploy timeouted (DEADLINE_EXCEEDED)

### ISSUE THREAD

**Issue by Carduelis** [strapi/strapi#9957]
### Describe the bug

Unable to deploy strapi using [this official](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html) guide.

Reason: deploy process takes too long (more than 10 minutes). 

### Steps to reproduce the behavior

Follow the official guide with default settings
Pick **Flexible environment**

### Screenshots

I also followed the [video guide](https://www.youtube.com/watch?v=4Z79lmOpHGo) . 

On [11:59](https://youtu.be/4Z79lmOpHGo?t=719) is visible that the configuration of the GCP server is:
```
1 vCPUs       3.75 GB of memory      10 Gb of SSD
```
![image](https://user-images.githubusercontent.com/3492820/113573305-2c363c00-961a-11eb-9257-384752dced02.png)

My the configuration is:
```
8 vCPUs       16 GB of memory      20 Gb of SSD
```
![image](https://user-images.githubusercontent.com/3492820/113573339-3c4e1b80-961a-11eb-864e-24adcdb30ad7.png)

And Strapi can't be deployed within 10 minutes. 

As a workaround I can increase amount of vCPUs (by upgrading from 4 to 8 it 15% faster).
Or set a bigger timeout: 
```
gcloud config set app/cloud_build_timeout 1500  
```
But nothing is stated about the timeout in both guides. 

### Some timings that console output provides when 4 vCPUs and 26 GB of Memory:
```
<...>
Step #1: [5/5] Building fresh packages...
Step #1: Done in 76.11s.
<...>
Step #1: ? Webpack: Compiled successfully in 2.63m
```

### Some timings that console output provides when 8 vCPUs and 16 GB of Memory:
```
<...>
Step #1: [5/5] Building fresh packages...
Step #1: Done in 63.34s.
<...>
Step #1: ? Webpack: Compiled successfully in 2.17m
```

**Comment by derrickmehaffy** [comment]
Confirmed: 
![image](https://user-images.githubusercontent.com/8593673/113595468-e8c5d880-95ed-11eb-9985-e9b419707495.png)

@Lith since you wrote that guide, do you have any suggestions? We don't regularly test GAE for deployment

**Comment by Carduelis** [comment]
@derrickmehaffy @Lith 
Also, by this guide I accidentally spent 70 euro by keeping flex and standard environments. Which... is my fault of course. But it's good to have a highlighted sentence about it.

Also, mysql is much cheaper than postressql in Google Cloud. 

And don't pick for testing purposes more than one virtual CPU, unless you will pay a lot. 
Yeah, Google adds you $300 for first 90 days, but it can be expired. Or you create a flex environment and forget to shut it down.

**Comment by derrickmehaffy** [comment]
I am not largely familiar with GCP/GAE myself so it would be good to get @Lith 's feedback.

**Comment by derrickmehaffy** [comment]
I believe this is fixed in v4 but if someone else hits the issue feel free to open a new issue as this one is quite stale
