### ISSUE TITLE
Register user | Error "Please provide your password." even if password is provided.

### ISSUE THREAD

**Issue by kasperbb** [strapi/strapi#9958]
### Describe the bug

When trying to create a user by sending a POST request to the `/auth/local/register` endpoint I get an error that tells me to provide a password, even if the password is provided in the request. I've tried sending the information via the URL and in raw JSON format via Postman.

I have `One account per email` address and `Enable sign-ups` enabled in the settings. Email provider is also enabled in the Providers settings. `Enable email confirmation` is disabled.

This is the response I get back:
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.password.provide",
                    "message": "Please provide your password."
                }
            ]
        }
    ],
    "data": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.password.provide",
                    "message": "Please provide your password."
                }
            ]
        }
    ]
}
```

### Steps to reproduce the behavior

1. Make sure the `One account per email address` and `Enable sign-ups` settings are enabled. Make sure `Enable email confirmation` is disabled.
2. Send a POST request to the `/auth/local/register` endpoint with this payload:
```
{
    "username": "user",
    "email": "user@exmaple.com",
    "password": "user12345678",
}
```
3. See the error.

### Expected behavior

The expected behavior is a user will be created with the role `Authenticated`.

### System

- Node.js version: 14.4.0
- NPM version: 6.14.5
- Strapi version: 3.5.4
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Test on v3.5.4 with the same settings:

![image](https://user-images.githubusercontent.com/8593673/113590907-1c056900-95e8-11eb-9052-d67f1b6c3346.png)

Trying to create the same user again results in a normal "email is taken error"

![image](https://user-images.githubusercontent.com/8593673/113590951-2889c180-95e8-11eb-8cee-fb2fc0369323.png)

Can you please provide additional steps to reproduce or more information about your project (modifications, extensions, ect)

**Comment by kasperbb** [comment]
Not quite sure what more I can add. This is my first time using Strapi, so I haven't made any modifications other than adding the GraphQL plugin and Documentation plugin.

I haven't touched authentication until now and the settings should all be the default. I have one user, the one I created when setting up Strapi for the first time.

I have created two collection types that I will be using for my project. No single types or components.

I did try to force the `Email is already taken` error. Although even when trying to create a user with the same email, I only get the password error.

**Comment by kasperbb** [comment]
Weird, I slept on it. I haven't changed a single thing other than restarting the server (something I've done a dozen times without it fixing the problem), but it works now.  Not quite sure what the problem was, as I did everything the same.

**Comment by derrickmehaffy** [comment]
It's the typical "I take my car to the mechanic and the issue stops", if it comes back and you find a way to reproduce it do let us know.

**Comment by ssoftwares** [comment]
@kasperbb Make sure you are passing username, Strapi registration API does not handle error well and show wrong error message often.

**Comment by derrickmehaffy** [comment]
> @kasperbb Make sure you are passing username, Strapi registration API does not handle error well and show wrong error message often.

Indeed, the legacy error messages in that plugin will be refactored in our v4

**Comment by kwiat1990** [comment]
Hi, i have encountered the same problem with Strapi `4.1.7`. I have registered yesterday a new user and today I can't register another one. After I deleted the first one, I get an error response, which states that I should pass email and password as they both are required fields. Oddly enough, I set both fields.

```js
fetch("http://localhost:1337/api/auth/local/register", { 
    method:"post",
    body: JSON.stringify({
        username: "Lorem",
        email: "lore@ipsum.com",
        password: "LoremIpsum"
    })
})
```

And the response from server looks like this:
```js
{ 
  data: null
  error: {status: 400, name: "ValidationError", message: "2 errors occurred",…}
  details: {errors: [{path: ["email"], message: "email is a required field", name: "ValidationError"},…]}
  message: "2 errors occurred"
  name: "ValidationError"
  status: 400
)
```
