### ISSUE TITLE
Respect limit value greater that 100 for GraphQL query

### ISSUE THREAD

**Issue by kliakos** [strapi/strapi#9960]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

When querying a collection with GraphqQL, specifying a limit greater than 100 does not return more that 100 records. The same works fine on the REST API, either by specifying _limit=-1 or a number greater than 100. The same should work for GQL too.

### Why is it needed?

You should be able to retrieve all records or the exact amount of items you want, per query, just like with the REST API.

### Suggested solution(s)

Mimic the behavior of the `_limit` param of the REST API.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/9959

**Comment by derrickmehaffy** [comment]
Adding a bit more information here:

There are currently two API "methods":

- REST
- GraphQL

The maximum limits are set in two different locations:

- REST => https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#api
- GraphQL => https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#configurations

REST has the option to set the default limit, GraphQL does not. However you can specify a custom returned limit using the `_limit` / `limit` filters (REST/GraphQL respectively). See: https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#limit

This feature request is more about **syncing** the REST and GraphQL default limits and maybe adding a default to GraphQL, either way you will still need to use the `_limit` / `limit` filters if you want custom limits.

---

As a side note, **it is absolutely not recommended** that you use a `limit: -1` to fetch everything as that is an extremely large query, you should be using a combination of `limit` and `start` to **page** through the records. Combining that with a count query will allow you to loop and fetch all records without overloading the Strapi backend.
