### ISSUE TITLE
sslCA in strapi-connector-mongoose

### ISSUE THREAD

**Issue by jean27garbi** [strapi/strapi#9962]
### Describe the bug

The sslCA is not being taken into account in the mongodb connection options

### Steps to reproduce the behavior

1. Set env vars filepath in sslCA: "DB_SSL_CA=../../foo.pem"
2. Go to and config env vars options.sslCA = [fs.readFileSync(DB_SSL_CA, "utf8")] in 'config/database.js'
3. npm start
4. See error: "Error connecting to the Mongo database. unable to verify the first certificate"

### Expected behavior

This must connect to the databases in replicaset mode taking into account the ssl and sslCA options.

### Screenshots

Error:
![image](https://user-images.githubusercontent.com/40599962/113617613-27728780-961c-11eb-8dca-63794ac38706.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12
- NPM version: 6.14.11
- Strapi version: 3.5.4
- Database: Mongodb - IBM Hyper protect
- Operating system: Ubuntu 20.04

### Additional context

Solution:

The sslCA property needs to be added in the strapi-connector-mongoose options as follows:
![image](https://user-images.githubusercontent.com/40599962/113617964-a4056600-961c-11eb-8854-524477bb25a2.png)

And with that the fault is corrected:
![image](https://user-images.githubusercontent.com/40599962/113618133-db741280-961c-11eb-99a3-27c7974e2afe.png)

**Comment by chris-makaio** [comment]
sorry, my mistake - I'm on it!

**Comment by chris-makaio** [comment]
Okay, created a PR but I think it's still confusing... it works now, though

**Comment by EnkeyCaps** [comment]
Any solution for this?

**Comment by SpaceMalamute** [comment]
> Any solution for this?

I had to use "URI" property directly. 
Working on my side. 

`
const path = require("path");

const cert_path = path.resolve(
  __dirname,
  "/usr/local/share/ca-certificates/my-cert/my-cert.crt"
);

module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "mongoose",
      settings: {       
        srv: env.bool("DATABASE_SRV", false),
        port: env.int("DATABASE_PORT", 27017),
        database: env("DATABASE_NAME", "exsmap-blog"),
        uri: env(
          "DATABASE_URI",
          `mongodb+srv://[USER]:[PASSWORD]@[HOST]&replicaSet=[REPLICASET]&tls=true&tlsCAFile=${cert_path}`
        ),
      },
      options: {
        authenticationDatabase: env("AUTHENTICATION_DATABASE", "admin"),
        ssl: env.bool("DATABASE_SSL", true),
      },
    },
  },
});
`

**Comment by SpaceMalamute** [comment]
> Any solution for this?

I had to use "URI" property directly. 
Working on my side. 


```javascript
const path = require('path');

const cert_path = path.resolve(
    __dirname,
    '/usr/local/share/ca-certificates/my-cert/my-cert.crt'
);

module.exports = ({ env }) => ({
    defaultConnection: 'default',
    connections: {
        default: {
            connector: 'mongoose',
            settings: {
                srv: env.bool('DATABASE_SRV', false),
                port: env.int('DATABASE_PORT', 27017),
                database: env('DATABASE_NAME', '[DB_NAME]'),
                uri: env(
                    'DATABASE_URI',
                    `mongodb+srv://[USER]:[PASSWORD]@[HOST]&replicaSet=[REPLICASET]&tls=true&tlsCAFile=${cert_path}`
                ),
            },
            options: {
                authenticationDatabase: env('AUTHENTICATION_DATABASE', 'admin'),
                ssl: env.bool('DATABASE_SSL', true),
            },
        },
    },
});
```

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
