### ISSUE TITLE
Facebook auth provider problem

### ISSUE THREAD

**Issue by stolicamedia** [strapi/strapi#9963]
Hi!
I am using Facebook auth provider. Everything works fine, except that provider sets username field value in strapi users model like user's first name and surname on facebook, that's incorrect. Is it possible to configure this provider, to set user's facebook first name and surname to specific fields in model?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
