### ISSUE TITLE
SuperAdmin cannot access relation fields when creating entries

### ISSUE THREAD

**Issue by haiderali136a** [strapi/strapi#9973]
Hello!
        
The issue I'm facing in getting 405 error code for all APIs of pattern while logged in as SuperAdmin 

**POST /content-manager/relations/application::[collection-type].[collection-type]/[relation_field]?_limit=20**

where collection-type is any collection-type that I created and relation fields could be any relations associated to the collection type.

So when I try to create an entry of any collection-type, while selecting the relation field value from drop down, I get 405 error (Method not allowed).

**What I changed in the code most recently**

I was working on an Ecommerce application with some additional features. I had to use twilio for OTP authentication. In order to do that, I extended the User (from users-permissions), added custom controllers as well as routes for verification. The routes are working fine. But this issues was raised.
bug

**Screenshots**

![Screenshot from 2021-04-06 16-29-33](https://user-images.githubusercontent.com/71278425/113704631-d3d46c80-96f5-11eb-8e5c-a5fdf07b6bca.png)

It can be seen in the screenshot that store_id relation field stuck on loading at the bottom right

**Comment by derrickmehaffy** [comment]
> I was working on an Ecommerce application with some additional features. I had to use twilio for OTP authentication. In order to do that, I extended the User (from users-permissions), added custom controllers as well as routes for verification. The routes are working fine. But this issues was raised.
bug

We don't support bugs with extended code, only Strapi built and maintained code. For issues when modifying core files please post on our forums: https://forum.strapi.io

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
