### ISSUE TITLE
How can I connect Strapi to Github??

### ISSUE THREAD

**Issue by D-Rosa99** [strapi/strapi#9976]
Hello folks !👋
 
does anyone know how to connect strapi to github, like passing document and images to github?????

I have some images and documents in the media library section of Strapi and I want to send it to Github so I can
versioning.

Or just send it to storage them back them.

**Comment by millord** [comment]
I would like to know too  since I will implement something similar in a project.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
