### ISSUE TITLE
Cannot login as admin after upgrade to Strapi 3.2.5 : React error

### ISSUE THREAD

**Issue by daxyonis** [strapi/strapi#9977]
### Describe the bug

I have updated Strapi from 3.1.4 to version 3.2.5. I launch in dev mode, go to the admin console but the login page is blank and there is an error in javascript console (see screenshot).

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Steps to reproduce the behavior

1. Update versions to 3.2.5 in package.json
2. Erase yarn.lock and node_modules folder
3. npm install
4. I had deprecated warnings so I did npm audit fix
5. Everything ok : then I did npm run dev
6. Go to localhost:1337, page shows server is running, click on Open the administration
7. Page http://localhost:1337/admin/auth/login is blank and error in js console

### Expected behavior

Be able to login

### Screenshots

![image](https://user-images.githubusercontent.com/16484367/113764613-34a97800-96e9-11eb-9f7f-54032a3028c9.png)

### System

- Node.js version: 14.15.1
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: sqlite3
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Did you follow the migration guides, including rebuilding the admin panel?

**Comment by daxyonis** [comment]
Yes I followed this guide : https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html#rebuild-your-administration-panel including rebuild.
When I saw the deprecated warnings, there were some that were about unmaintained packages. Is there no risk of malfunction ? Should I ignore those warnings then ?

**Comment by soupette** [comment]
Hello @daxyonis what kind of customisations did you make to your app?

**Comment by derrickmehaffy** [comment]
> When I saw the deprecated warnings, there were some that were about unmaintained packages. Is there no risk of malfunction ? > Should I ignore those warnings then ?

Yes they are fine, some of them are just because a package changed ownership without any code changes such as boom vs @hapi/boom

https://www.npmjs.com/package/boom
https://www.npmjs.com/package/@hapi/boom

Or upstream packages widely changed their APIs with breaking changes that provide no benefit for us to change (more work for little benefit)

**Comment by derrickmehaffy** [comment]
Should no longer be an issue in v4
